### ISSUE TITLE
Type.IsSubclassOf Performance Regression

### ISSUE THREAD

**Issue by joncham** [mono/mono#10000]
## Steps to Reproduce

1. Run test case below

```
using System;
  
class Program
{
    static void Main(string[] args)
    {
        var stopwatch = new System.Diagnostics.Stopwatch();
        stopwatch.Start();
        var type = typeof(Program);
        for (var i = 0; i < 1000000; ++i)
            type.IsSubclassOf(typeof(System.ICloneable));

        stopwatch.Stop();
        Console.WriteLine(stopwatch.ElapsedMilliseconds);
    }
}
```

### Current Behavior

```
/Library/Frameworks/Mono.framework/Versions/2.10.2/bin/mono Program.exe 
50

/Library/Frameworks/Mono.framework/Versions/4.8.1/bin/mono Program.exe 
114

/Library/Frameworks/Mono.framework/Versions/5.14.0/bin/mono Program.exe 
558

```

## On which platforms did you notice this

[ x] macOS
[ ] Linux
[x ] Windows

**Version Used**:

See version comparison above

**Comment by lambdageek** [comment]
So this is just hammering this function:
https://github.com/mono/mono/blob/36956720f7a3e854b467bf6dbd7aedd8d142e1ae/mcs/class/referencesource/mscorlib/system/rttype.cs#L3708-L3733

which is... several icalls and a while loop with an icall in it.   We should probably dive down to native sooner.

**Comment by vargaz** [comment]
We used to:
https://github.com/mono/mono/blob/mono-3.4.0-branch/mono/metadata/icall.c#L1496

**Comment by lambdageek** [comment]
Commits on `master`, `2018-08` and `2018-06` branches improve performance of this microbenchmark roughly 4x - near Mono 4.8.1 numbers.
