### ISSUE TITLE
Is it possible to have Mono compiler to wasm as wasm?

### ISSUE THREAD

**Issue by Thaina** [mono/mono#10018]
What is the roadblock that stop us from having mono compiler as wasm that could be loaded into browser and compile C# to wasm directly in browser?

**Comment by lewurm** [comment]
Already done: https://github.com/Suchiman/Runny

**Comment by Thaina** [comment]
@lewing Is there a way we could export what compiled as another wasm file?

**Comment by lewurm** [comment]
What actually happens there is:
* `roslyn` compiles C# to CIL code.
* then, the mono runtime (running on WebAssembly) executes that CIL code with an interpreter.

There is no WebAssembly file generated anywhere.

**Comment by Thaina** [comment]
@lewurm Then would you please reopen this issue. Because that was the main feature I wish to have it exist. So we could have webassembly IDE in C#

**Comment by lewurm** [comment]
I'm afraid I don't understand what you are asking for. Every building block is available to build an IDE in WebAssembly with C# right now. `Runny` is a minimal example showcasing that.

If you build WebAssembly applications with C#, you don't distribute wasm files, but DLLs and the Mono Runtime (as a wasm file). In the future there will be an AOT compiler, so additionally (or instead?) you will distribute wasm files along the DLLs. For the AOT compiler see this issue: https://github.com/mono/mono/issues/9825

**Comment by lewurm** [comment]
@Thaina I think it's best you ask our friends from the Blazor team in their gitter chat channel: https://gitter.im/aspnet/Blazor
