### ISSUE TITLE
Bug: AutoWebProxyScriptEngine.InitializeRegistryGlobalProxy

### ISSUE THREAD

**Issue by KevinKeyser** [mono/mono#10030]
InitializeRegistryGlobalProxy should not error out if ProxyEnable is true and ProxyServer is null. All other applications and services work when my registry has proxyenabled with no proxyserver key. The only test I tried is when using System.Net.WebRequest.Create() and InitializeRegistryGlobalProxy throws a null object exception which I believe is on this line of code:
https://github.com/mono/mono/blob/22c9616fe2d23d11d12b883cb39020a5495c0e16/mcs/class/System/ReferenceSources/AutoWebProxyScriptEngine.cs#L127.

This should get a null check or default value of an empty string e.g. :
1.) set strProxyServer default value to String.Empty or equivalent. 
string strProxyServer = (string)Microsoft.Win32.Registry.GetValue ("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings", "ProxyServer", String.Empty);
2.) null check for strProxyServer could be on the line 127 before checking strProxyServer.Contains("=").

**Comment by witcher112** [comment]
Pull request has been sent - I've chosen to go with second option:

> 2.) null check for strProxyServer could be on the line 127 before checking strProxyServer.Contains("=").
