### ISSUE TITLE
Expose SourceLink values in sdb

### ISSUE THREAD

**Issue by leonidumanskiy** [mono/mono#10038]
Since Mono supports Portable PDBs now, are there any plans to support SourceLink?
SourceLinks section of portable PDB are supported by Mono.Cecil. However, I could not make it work with Mono soft debugger.

The only way I could find to debug external assemblies without rebuilding them from scratch using mono was to use mdbs and mdbrebase tool to patch MDB file to update source code paths. Source link solves this problem in .NET / .NET Core and it would be amazing to have mono support it.

**Comment by vargaz** [comment]
So the ModuleMirror class now has a SourceLink property which returns the the sourcelink data.
