### ISSUE TITLE
unhandled-exception-2.exe crashes crash reporting

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#10031]
There is a unhandled-exception-2.exe crash on CI that seems to hit the assertion at `mini-exceptions.c:1196`. 

I need to investigate this for bugs week. If the domain isn't set, stack walking shouldn't die spectacularly. It should indicate failure to the caller.

**Comment by alexanderkyte** [comment]
@akoeplinger @lambdageek please include any information you know about this that I haven't mentioned.

**Comment by akoeplinger** [comment]
It seems to occur on unhandled-exception-4.exe too ([see Jenkins PR](https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx/13540/testReport/junit/MonoTests/test-unhandled-exception-2-255-without-managed-handler/unhandled_exception_4_exe/)), albeit way more infrequently than with -2.exe. Disabled it as well.

**Comment by alexanderkyte** [comment]
It sounds like @lambdageek is debugging this one as well. We agreed that it seemed to be a race between `mono_thread_interruption_checkpoint_void` and getting the info block to pass to `mono_thread_suspend_all_other_threads`

**Comment by lambdageek** [comment]
@alexanderkyte Thanks for helping to track this down! Take a look at #10161 for an attempted fix.
