### ISSUE TITLE
DeflateStream behaviour is different on Mono

### ISSUE THREAD

**Issue by JimBobSquarePants** [mono/mono#10054]
This issue has been compiled from information gathered by @Splamy in an issue raised on the ImageSharp issue tracker affecting our ability to decode png files.

https://github.com/SixLabors/ImageSharp/issues/598

`DeflateStream` exhibits slightly different behavior in net/dotnet and Mono. The following code will execute differently:
 
## Steps to Reproduce

```csharp
using System;
using System.IO;
using System.IO.Compression;
using System.Text;

namespace Bug1
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            // "HelloWorld" as UTF8/DeflateStream(...,CompressionMode.Compress)
            var buffer = new byte[] { 243, 72, 205, 201, 201, 15, 207, 47, 202, 73, 1, 0 };
            var mem = new MemoryStream(buffer);
            var chu = new ChunkedReader(mem);
            var def = new DeflateStream(chu, CompressionMode.Decompress);
            
            var buffer2 = new byte[4096];
            int read2 = 0;

            chu.limit = 3;
            read2 += def.Read(buffer2, read2, buffer2.Length - read2);
            chu.limit = 100;
            read2 += def.Read(buffer2, read2, buffer2.Length - read2);

            var res = Encoding.UTF8.GetString(buffer2, 0, read2);
            Console.WriteLine(res);
        }
    }   
    
    public class ChunkedReader : Stream
    {
        private int sum = 0;
        public int limit = 0;
        private string name;
        private Stream baseStream;
        
        public ChunkedReader(Stream baseStream, string name = null)
        {
            this.baseStream = baseStream;
            this.name = name;
        }

        public override void Flush()
        {
            this.baseStream.Flush();
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            int read;
            read = this.baseStream.Read(buffer, offset, Math.Min(count, this.limit));
            sum += read;
            this.limit -= read;
            Console.WriteLine("{3}> Sum: {0}, Read {1}, Req: {2}", this.sum, read, count, name ?? "XXX");
            return read;
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            return this.baseStream.Seek(offset, origin);
        }

        public override void SetLength(long value)
        {
            this.baseStream.SetLength(value);
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            this.baseStream.Write(buffer, offset, count);
        }

        public override bool CanRead => this.baseStream.CanRead;

        public override bool CanSeek => this.baseStream.CanSeek;

        public override bool CanWrite => this.baseStream.CanWrite;

        public override long Length => this.baseStream.Length;

        public override long Position
        {
            get => this.baseStream.Position;
            set => this.baseStream.Position = value;
        }
    }
}
```

### Current Behavior

Under Mono it will refuse to continue reading after it once got `0` and only prints

```
XXX> Sum: 3, Read 3, Req: 4096
XXX> Sum: 3, Read 0, Req: 4096
He
```

### Expected Behavior
While under net/dotnet it will print
```
XXX> Sum: 3, Read 3, Req: 8192
XXX> Sum: 3, Read 0, Req: 8192
XXX> Sum: 12, Read 9, Req: 8192
HelloWorld
```

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
Tested it locally on Arch Linux with:
```
Mono JIT compiler version 5.12.0 (makepkg/58637d0ee7c Wed Jun  6 22:41:15 CEST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

The server is running Ubuntu 16.04 with `Mono JIT compiler version 5.12.0.301 (tarball Wed Jul 25 15:47:18 UTC 2018)` (rest same) Where the problem is the same.

It has also been tested on Ubuntu 18.04 with `Mono JIT compiler version 5.17.0.535 (tarball Mon Aug  6 10:00:43 UTC 2018)` (latest ubuntu nightly version) and the problem persists.

Additionally this is present in Android 8.0.0.

**Comment by JimBobSquarePants** [comment]
Is there any further information required to make progress on this issue?

**Comment by baulig** [comment]
I would argue the `DeflateStream` behaves absolutely correctly - getting a 0 return from the underlying `Read()` means end-of-stream.  However, I fail to understand why `MemoryStream` would return 0 here.

**Comment by baulig** [comment]
Well, I added some debugging to your test case and it turns out that on the second invocation of `this.baseStream.Read(buffer, offset, Math.Min(count, this.limit))` your `this.limit` is 0.

**Comment by filipnavara** [comment]
@baulig I think that's intentional that the second read calls it with zero. Imagine the scenario when DeflateStream wraps a NetworkStream and the underlying socket is non-blocking. I would expect the DeflateStream.Read to return zero when there are no data in the socket, but work on a subsequent call when some data arrives.

**Comment by filipnavara** [comment]
Well, it's "end of stream" at that particular moment, so it's not a violation of that rule. There's no guarantee that it won't change.

**Comment by baulig** [comment]
The problem is that we have a lot of other code with the assumption that "end of stream" is permanent - some of which may be very hard to change.
