### ISSUE TITLE
[ios] Mono SDK doesn't work with Xcode 10 (32 bits executable)

### ISSUE THREAD

**Issue by VincentDondain** [mono/mono#10100]
## Steps to Reproduce

1. `xcode-select -s /Applications/Xcode10.app/Contents/Developer`
2. make in `mono/sdks/builds`

### Current Behavior

Fails. Here's a simplified build command that shows the issue: https://gist.github.com/VincentDondain/fab2bb948ad53c411073414a15f674df

### Expected Behavior

- Instead of using `clang++` which picks up the one from the default installed Xcode (xcode-select). We should be using the `clang++` from `XCODE_DIR`.
- building 32 bit executables needs to be done with Xcode 9.4.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Installed `Mono JIT compiler version 5.12.0.226 (2018-02/9824e260f56 Mon Apr 30 18:45:52 EDT 2018)` and locally I was building mono d15-8 (4fe3280bba1)

**Comment by luhenry** [comment]
@vargaz please take a look at that.

**Comment by spouliot** [comment]
All 64bits executables should be built with Xcode 10 (or newer)
while all 32bits executables must be built with Xcode 9.4 (as long as we support them)
c.c. @rolfbjarne

**Comment by VincentDondain** [comment]
That's what I started doing with Ludo locally but I believe this won't work because you're calling `clang++` without using the `XCODE_DEVELOPER_ROOT`. So it picks up the current (`xcode-select`) version, in this case Xcode 10.

See https://gist.github.com/VincentDondain/fab2bb948ad53c411073414a15f674df#file-gistfile1-txt-L50.

Also we could customize the mono sdk make target that are on our side but you will still have the problem on your side no? So isn't it better just to fix it once on you side?

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/10139

**Comment by luhenry** [comment]
@vargaz https://github.com/mono/mono/pull/10139 is not the right fix. We need to explicitly define the c++/c/ld/etc. command and pass that to `configure`, otherwise it will still pick up the Xcode version from `xcode-select`.

**Comment by marek-safar** [comment]
@vargaz @luhenry could you guys wrap this up? The original PR has now conflicts due to SDK work and perhaps it's no longer needed?

**Comment by luhenry** [comment]
It's been already fixed in XI: https://github.com/xamarin/xamarin-macios/blob/master/builds/Makefile#L1568
