### ISSUE TITLE
Discord API with Macs

### ISSUE THREAD

**Issue by xPenguinx** [mono/mono#10114]
I worked on a project in C# with Visual Studio creating and exe file using a discord API to run a discord bot. I ran the file and the discord bot will load up but after it loads up I am only able to do one thing with the bot something like !help and then it will send a message back and when I do it again it won't work. Then I tried to run this on a VPS (Windows) it would perfectly work. I would do !help 10 times and every time I would get a message back but not on a mac. On the mac once i do something it won't do anything else its like it turns the bot off.

**Comment by lewurm** [comment]
Hello @xPenguinx! Please provide a minimal example program where you observe the issue, so we can look into it

**Comment by xPenguinx** [comment]
Wym like you want me to make a program?

**Comment by luhenry** [comment]
@xPenguinx we have no idea what are the steps you are doing, so we have no way to reproduce, let alone understand what problem you are running into.

If you want us to be able to help you, re-fill your issue following the provided template.
