### ISSUE TITLE
wasm  build warnings: unresolved symbols: fputs, fputs, putchar

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#10116]
Someone (not me) random PR:

https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/3714/consoleFull

<span class="timestamp"><b>13:12:12</b> </span>warning: unresolved symbol: fputc
<span class="timestamp"><b>13:12:12</b> </span>warning: unresolved symbol: fputs
<span class="timestamp"><b>13:12:12</b> </span>warning: unresolved symbol: putchar

If my own work, I caused a few extra of these warnings and they turned out to be significant.
It didn't take me long to notice and fix.
But therefore, it might be nice to 1) make it an error 2) fix the existing ones.

**Comment by kjpou1** [comment]
fixed: https://github.com/mono/mono/pull/11291
