### ISSUE TITLE
String.TrimEnd backwards compatibility issue on Mac

### ISSUE THREAD

**Issue by leezer3** [mono/mono#10179]
## Steps to Reproduce
Take the following code:
```
using System;

namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			string testString = "test string   ";
			Console.WriteLine(testString);
			testString.TrimEnd();
			Console.WriteLine(testString);
		}
	}
}
```
Compile using Mcs on the Mac using the current stable channel (5.14.0)
Attempt to run using the following Mono version `mono --version
Mono JIT compiler version 5.12.0.226` (This is what was on the box previously. I believe it was the previous stable, but not 100% on that)

Only just noticed this, as the CI which I use to produce my Mac builds appears to have updated to 5.14.0 over the last couple of days.

### Current Behavior
```Unhandled Exception:
System.MissingMethodException: string string.TrimEnd()
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: string string.TrimEnd()
```

### Expected Behavior

No exception.
This is basic enough that I would have expected the IL generated to remain backwards compatible.

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Runtime:
`5.12.0.226`
Compiler:
`5.14.0.177`

**Comment by leezer3** [comment]
Have just upgraded the Ubuntu VM to 5.14.0.177 (from the Ubuntu repos version), and am seeing the same issue with the code above once the compiled exe is copied to the Mac.

Not sure if I can pin the version to the previous stable to test?

**Comment by migueldeicaza** [comment]
Likely the version of Mono on the Ubuntu machine is newer than the version on the Mac.  Make sure they are the same version.

**Comment by leezer3** [comment]
Sure, I get that much.

My issue is that this is dead basic code, and it really shouldn't be breaking backwards compatibility in a release within the 5.* series.

My expectation, and the impression I get from reading the Mono versioning page ( https://www.mono-project.com/docs/about-mono/versioning ) is that the generated IL should remain compatible (At least between major version numbers) unless a new feature is introduced that specifically changes the code in question.

**Comment by marek-safar** [comment]
This is the expected behaviour. You need to build against API to get the stable behaviour you can do that using msbuild or by using e.g. .NET API references manually with for example `mcs -sdk:4.7 foo.cs`
