### ISSUE TITLE
LLDB EXC_BAD_ACCESS during a native exception

### ISSUE THREAD

**Issue by steveisok** [mono/mono#10180]
## Steps to Reproduce

1. Build mono w/ native debug symbols 

2. Compile the code below:

```
using System;
using System.Reflection;

namespace LLDBTest
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hit Enter to start");
            Console.Read();

            var mc = new MainClass();
            mc.TestMeReflection();

            Console.WriteLine("Hit Enter to Finish");
            Console.Read();
        }

        public void TestMeReflection()
        {
            try
            {
                var testString = typeof(MainClass)
                    .GetProperty("TestProp")
                    .GetValue(null, null);

                if (testString == null) {
                    Console.WriteLine("String is null");
                }
                else {
                    var invalidVal = testString.GetType()
                               .GetField("_DOESNOTEXIST", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.IgnoreCase)
                                               .GetValue(testString);

                    Console.WriteLine("Should Not Print: " + invalidVal.ToString());
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("Caught! " + e.ToString());
            }
        }

        internal static string TestProp { get { return "Test"; } }
    }
}
```
 
3. Open two terminals and in the first execute <mono-root>/mono/mini/mono --debug LLDBTest.exe

4. In the second terminal get the process ID of the executing LLDBTest process

5. Type lldb and attach to the process (process attach --pid <pid>)

6. Type process continue into lldb and press enter in the LLDB console to start the routine.  

### Current Behavior

The debugger breaks w/ an EXC_BAD_ACCESS stop reason and I cannot continue to debug

<img width="932" alt="screen shot 2018-08-19 at 10 16 46 pm" src="https://user-images.githubusercontent.com/471438/44317143-a3811800-a3fd-11e8-996e-e77bdc6d230e.png">

### Expected Behavior

In most scenarios this is a completely valid fault, but there are some cases where I want execution to continue.  I would like to know the best way to ignore EXC_BAD_ACCESS.

## On which platforms did you notice this

[X ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.12.0.298 (2018-02/f795aa5d2db Thu Jul 19 10:21:35 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by lewurm** [comment]
Mono uses implicit null checks to implement null checks efficiently. You are running into [this issue of LLDB](http://lists.llvm.org/pipermail/lldb-dev/2013-July/002004.html). Unfortunately it hasn't been fixed for _years_.

There are two workarounds:
1. Run mono with `MONO_DEBUG=explicit-null-checks`, so the runtime won't use mentioned technique. Performance-wise this is a bit slower, but for debugging purposes that's fine.

2. Use `gdb`. Unfortunately this requires some work on macOS these days.

FWIW, I'm gonna update https://www.mono-project.com/docs/debug+profile/debug/#debugging-with-lldb

**Comment by steveisok** [comment]
Thanks!  I knew there was something other than use gdb :-).

**Comment by jaykrell** [comment]
You shouldn't really write code that expects to often catch null dereference exceptions.
Check for the nulls yourself in the few cases you expect them.

**Comment by lewurm** [comment]
I ran into a similar issue with Java, but for some reason I only got an `EXC_BAD_INSTRUCTION`, but never an`EXC_BAD_ACCESS`. Instead lldb will receive `SIGSEGV`/`SIGBUS` and it can continue from that (as it should be).

Turns out there is a little code snippet that seems to cause that behaviour in HotSpot:
https://github.com/openjdk/jdk/blob/50cc54c730bb0f130991648d1547d42483edddc1/src/hotspot/os/bsd/os_bsd.cpp#L2810-L2817
IMHO worth a try, as this is quite annoying when debugging Mono on macOS/iOS. FWIW add `EXC_MASK_BAD_INSTRUCTION` if you want to have the same behaviour for SIGILL.

**Comment by lewurm** [comment]
Fixed by https://github.com/mono/mono/issues/10180 I assume 🙂

**Comment by imhameed** [comment]
Should be; with that change applied, I'm able to step through Mono's SEGV signal handler in the copy of LLDB that ships with XCode and I no longer need to use a [hand-patched version of LLDB](https://stackoverflow.com/a/32724035) to make this work. (I'll close this issue.)
