### ISSUE TITLE
Encoding 1252 does not supported.

### ISSUE THREAD

**Issue by kant2002** [mono/mono#10217]
## Steps to Reproduce

1. Start simple Blazor application
2. Add following line as handler for the button. or inside OnInit()
```
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var encoding = Encoding.GetEncoding(1252);
```

### Current Behavior

Exception thrown
```
System.NotSupportedException: Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
 at System.Text.Encoding.GetEncoding (System.Int32 codepage)
```

### Expected Behavior
No exception happens. Or some workaround how this could be avoided..

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] Wasm

**Version Used**:

## Stacktrace

```
 at System.Text.Encoding.GetEncoding (System.Int32 codepage)
```

Initially reported here: https://github.com/aspnet/Blazor/issues/1338

**Comment by kumpera** [comment]
This is a build issue on Blazor's side.
It needs to include I18N.West.dll
