### ISSUE TITLE
Mono Framework MDK version 5.10.1.57 for macOS not yet in the download archive

### ISSUE THREAD

**Issue by brendanzagaeski** [mono/mono#10242]
## Steps to Reproduce

Navigate to <https://download.mono-project.com/archive/5.10.1/macos-10-universal/> to check the list of available archived versions for Mono Framework MDK version 5.10.1.

### Current Behavior

Mono Framework MDK version 5.10.1.57 is not yet included in the list.

### Expected Behavior

The previous published build (Mono Framework MDK version 5.10.1.47) is there, so it looks like the archive just needs a little update to include this newer build.

Thanks much!

**Comment by directhex** [comment]
Might have just been a CDN caching issue? I see the file listed fine.

**Comment by brendanzagaeski** [comment]
@directhex, interesting. I still don't see the file in that list at the moment. For example, if I do an in-page search for the number 57, there aren't any matches. Just to double-check, are you seeing the file listed on the rendered HTML page (<https://download.mono-project.com/archive/5.10.1/macos-10-universal/>) or on a list of the files in storage that should be picked up by that page?

Thanks!

**Comment by brendanzagaeski** [comment]
In case it's helpful for additional reference, I don't think Mono Framework MDK version 5.10.1.57 was published to <https://www.mono-project.com/download/stable/> either, so I was guessing that the usual upload step for that exact version hadn't happened yet.

**Comment by directhex** [comment]
Would you believe I was looking for 47, not 57?

**Comment by directhex** [comment]
Yeah, OK, so the mono-project.com release pipeline is based on either publishing to a branch, or promotion to a branch. 5.10.1.47 is the last  5.10 version that was promoted from preview to stable: https://jenkins.mono-project.com/view/Releases/job/ng-release-promote/156/

The next promotion to stable was 5.12.0.226: https://jenkins.mono-project.com/view/Releases/job/ng-release-promote/182/

Why exactly are you expecting to find 5.10.1.57 in stable?

**Comment by brendanzagaeski** [comment]
No worries, and sounds good thanks. I was checking for 5.10.1.57 because that version was published to the Visual Studio for Mac updater channels as part of the Visual Studio 2017 for Mac version 7.5.2 release (from May 30). That said, no worries if there won't necessarily always be an update to the mono-project.com download list for every version published through Visual Studio for Mac. In that case, feel free to go ahead and close this issue 😄

**Comment by directhex** [comment]
Mono versions corresponding to stable releases of VS _ought_ to end up published to the `vs` branch on mono-project.com, so the bug is real. I don't slavishly follow those release threads, as they rarely include Mono updates, and go on forever.

**Comment by brendanzagaeski** [comment]
Sounds perfect. Thanks again!
