### ISSUE TITLE
`opt` and `llc` missing from mono 2018-08 pkg

### ISSUE THREAD

**Issue by kdubau** [mono/mono#10243]
## Steps to Reproduce

1. Install Mono 5.18 / 2018-08
2. `mono --aot --llvm someexecutable.exe`
3. fails with `sh: opt: command not found`

### Current Behavior

Cannot find the `opt` binary in Mono.framework.

```kylewhite@kyles-mbp ~ $ mono --version
Mono JIT compiler version 5.18.0.36 (2018-08/faac90015cd Wed Aug 22 07:22:48 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
kylewhite@kyles-mbp ~ $ find /Library/Frameworks/Mono.framework -name "opt"
kylewhite@kyles-mbp ~ $ find /Library/Frameworks/Mono.framework -name "llc"
```

### Expected Behavior

The `opt` binary should be found and should be able to AOT an executable with `mono --aot --llvm`.

On Mono 5.16 the binaries can be found:

```Mono JIT compiler version 5.16.0.119 (2018-06/0955dd23071 Wed Aug 22 07:57:34 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/0b3cb8ac12c)
	GC:            sgen (concurrent by default)
kylewhite@kyles-mbp ~ $ find /Library/Frameworks/Mono.framework -name "opt"
/Library/Frameworks/Mono.framework/Versions/5.16.0/bin/opt.dSYM/Contents/Resources/DWARF/opt
/Library/Frameworks/Mono.framework/Versions/5.16.0/bin/opt
kylewhite@kyles-mbp ~ $ find /Library/Frameworks/Mono.framework -name "llc"
/Library/Frameworks/Mono.framework/Versions/5.16.0/bin/llc.dSYM/Contents/Resources/DWARF/llc
/Library/Frameworks/Mono.framework/Versions/5.16.0/bin/llc
```

## On which platforms did you notice this

- [x] macOS
- [ ] Linux
- [ ] Windows

**Version Used**:

See above.

**Comment by EgorBo** [comment]
https://github.com/mono/mono/issues/9415

**Comment by kdubau** [comment]
I think #9415 explains why `mono --aot --llvm` doesn't work, but with 2018-08 even specifying the llvm path with `mono --aot=llvm,llvm-path=/Library/Frameworks/Mono.framework/Versions/Current/bin/ someexecutable.exe` still fails (as expected since `opt` is missing).

**Comment by EgorBo** [comment]
ah, sorry I didn't notice `find /Library/Frameworks/Mono.framework -name "opt"` results

**Comment by alexischr** [comment]
The files end up at `$(mono source root)/llvm/usr/bin` and not on the mono install prefix. For now, the solution is to copy them to the mono install prefix at bockbuild time so that they are picked up
