### ISSUE TITLE
[prototype] Create sentry telemetry prototype

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#10262]
- Get MVP up and running that uploads our blobs as messages
- Improve mono support by fixing https://github.com/getsentry/raven-csharp/issues/268 so we're treated as Exceptions

**Comment by bruno-garcia** [comment]
@alexanderkyte any updates on this one?
I'd be glad to get involved on this from Sentry side.

**Comment by alexanderkyte** [comment]
We are currently using sentry through our CI infrastructure. 
The entry point is here: https://github.com/mono/mono/blob/master/scripts/ci/run-upload-sentry.sh
