### ISSUE TITLE
Interpreter support for hybrid/coop suspend

### ISSUE THREAD

**Issue by lewurm** [mono/mono#10260]
We've recently switched over to hybrid suspend for the runtime as default. This doesn't work in the interpreter yet, so we fall back to preemptive suspend.

Quoting @lambdageek on the difference between hybrid and coop, regarding the interpreter:
> hybrid means that while running runtime or managed code we should be using cooperative suspend.  So it would probably amount to the same thing as coop.   I guess (but correct me if I'm wrong) is that the interpreter calls the rest of the runtime more often than JITed code, so there's more of a chance we'll get to a safepoint somewhere in the callgraph.  But things like tight loops would still need actual safepoints.
> (to be clear: we wouldn't need to add coop handles in the interpreter to get this working)

Most of the tests are actually passing in hybrid suspend (https://github.com/mono/mono/pull/7046#issuecomment-365764273), but someone needs to look into the failing tests and fix them. Most likely we have to introduce safepoints in the interpreter.

Once done we should (partially) revert a7c699ab008e3ea262d661226ee45c92de288899

**Comment by lambdageek** [comment]
@lewurm Do we have a list of the failing tests anywhere?  If not, I can work on generating one. After that, I can start to look at them.

For introducing safepoints, do you think we should take an approach similar to the JIT: insert safepoint opcodes in interp/transform.c, or something more ad-hoc - safepoint when the interpreter enters a new function and when it interprets a backward jump?

**Comment by lewurm** [comment]
I don't have a list handy, I just remember it not being that many tests failing.

I don't think dedicated opcodes are necessary. Maybe a new opcode for specifically backward jumps, so we only do the safepoint check there. Also safepointing on function entry sounds good to me.

**Comment by jaykrell** [comment]
I believe function entry and "loop back edges" are the standard places. Maybe also icalls are different, i.e. before or after the function, not the function itself? (not  clear if "function entry"  is the start of a function, vs. the call or the return).
