### ISSUE TITLE
Mkbundle windows problem

### ISSUE THREAD

**Issue by T0bi-Ethirbirge** [mono/mono#10290]
### Current Behavior
Error mapping file: mono_file_map_error failed file:NewConsoleApp.exe length:0x46D000 offset:0x27000 function:MapViewOfFile error:The base address or the file offset specified does not have the proper alignment.(0x46C).

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[-] Windows

**Version Used**:
Mono 5.12.0.

**Comment by jaykrell** [comment]
Please try https://github.com/mono/mono/pull/8884.

**Comment by jaykrell** [comment]
Or as an easier/smaller fix, just change `4096` to  `1 << 16`.

**Comment by T0bi-Ethirbirge** [comment]
You are a lifesaver.
Thanks man

**Comment by T0bi-Ethirbirge** [comment]
Well another problem 
function:MapViewOfFile error:Access is denied.(0x5)

**Comment by T0bi-Ethirbirge** [comment]
Well it worked on my main PC.
But the server it gives me this error function:MapViewOfFile error:Access is denied.(0x5)

**Comment by jaykrell** [comment]
What  happened with "Well it worked on my main PC.
But the server it gives me this error function:MapViewOfFile error:Access is denied.(0x5)"?

**Comment by T0bi-Ethirbirge** [comment]
Because i was the using [this](https://download.mono-project.com/archive/nightly/windows-installer/) version of mono [The nightly build]

**Comment by T0bi-Ethirbirge** [comment]
Thank you it works with the normal build.
You saved my life.

**Comment by T0bi-Ethirbirge** [comment]
Hey i still get this error when i build mono from scratch [Here](https://www.mono-project.com/docs/compiling-mono/windows/)
Do you know what is the cause of it.
`Error mapping file: mono_file_map_error failed file:ConsoleApp.exe length:0x3F4000 offset:0x4C0000 function:MapViewOfFile error:Access is denied.(0x5)`

**Comment by lukespragg** [comment]
Also noticing this when compiling Mono from scratch on Windows using MSBuild. Tried both boehm and sgen targets.
