### ISSUE TITLE
WCF - FaultExceptions are ignored when using a binding with Streamed transferMode

### ISSUE THREAD

**Issue by Yves-Be** [mono/mono#10304]
## Steps to Reproduce

1. Host any WCF service with an endpoint with transferMode="Streamed"
2. Call an operation of the service from a client on Android
3. In the service, throw an Exception with a custom message
4. Catch the exception on the Android client

### Current Behavior

On Android, a WebException is caught with the following message :
> Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null.
> Parameter name: src

### Expected Behavior

A FaultException is caught with the original message, as thrown from the service. (As on UWP)

## On which platforms did you notice this

[ ] Windows
[x] Android

**Version Used**:

5.10 (Xamarin Android 8.3)

## Sample & Screenshots

![streamed faultexception](https://user-images.githubusercontent.com/1593717/44657621-beefb280-a9fd-11e8-9146-48d99b03f9a8.png)

[WcfFaultExceptions.zip](https://github.com/mono/mono/files/2323657/WcfFaultExceptions.zip)

To run the sample on Android, you will need to set the url in MainPage.xaml.cs to wherever you run the service. The service is selfhosted wcf service in a console app (and must be run as admin).

**Comment by sgilabert** [comment]
Is there a workaround to this problem? Thanks

**Comment by JonathonMinard** [comment]
We have a WCF service that relies on passing exceptions to Xamarin.Android and Xamarin.iOS clients, and this bug breaks that error messaging.  This did work with older versions of Xamarin.Android and Xamarin.iOS which used Mono version 5.8.1, so it's a regression.

We could change the service's transfer mode to Buffered or StreamedRequest, but that would break backwards compatibility with older versions of the service and would not handle larger data transfers as well.  So it's a workaround that we'd like to avoid if at all possible. 

Are there any plans to fix this regression?

**Comment by JonathonMinard** [comment]
Any updates on this?  The workaround for this would cause a lot of grief for us and our customers.

**Comment by Yorgl** [comment]
Hello, any news about this issue ? In .Net Standard 2, the WCF service methods are automatically async generated. It's does not work with buffered streams. I had to rewrite all async methods as sync methods (and then encapsulate them in Tasks to behave like async methods...). I can understand this issue is low priority, but it should be resolved, well... one day ? :)
Many thanks.

**Comment by JonathonMinard** [comment]
May we please get an update on this issue?

**Comment by JonathonMinard** [comment]
We're using older versions of Xamarin.iOS and Xamarin.Android currently to avoid this issue, but we're starting to get this warning from Apple:

"We identified one or more issues with a recent delivery for your app [...]. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

SDK Version Issue - This app was built with the iOS 11.4 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later."

**Comment by marek-safar** [comment]
@JonathonMinard I have no update on the issue but we'll try to investigate it this week

**Comment by EgorBo** [comment]
Investigating... Reproduces on XA 9.1
but doesn't reproduce on a console client on macOS and Windows (tried mono-master, mono-5.10, 5.16, 5,18).

**Comment by marek-safar** [comment]
The issue no longer reproduces with dev16.0 version (in preview), closing it.
