### ISSUE TITLE
Security: Android: Mono is vulnerable to Man In The Disk CWE-921

### ISSUE THREAD

**Issue by globeone** [mono/mono#10353]
## Steps to Reproduce

1.  Create an application using Mono Android
2.  Have it use external Storage
3. External storage is not validated or encrypted leading to access outside the sandbox.

### Current Behavior

The Android version of Mono is vulnerable to Man-In-The-Disk CWE-191
https://research.checkpoint.com/androids-man-in-the-disk/

Details:
There is **'getExternalStorageDirectory()'** found in file 'mono/MonoPackageManager.java':
line 63:                 ClassLoader classLoader = object.getClassLoader();
line 64:                 Object object5 = Environment.**getExternalStorageDirectory();**
line 65:                 Object object6 = new Object();

### Expected Behavior

Example of secure code:
// If you use external storage you should perform input validation.
// In the case that you use external storage for executables files,
// these files should be signed and cryptographically verified.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] Android

**Version Used**:
Current version

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
This issue was moved to xamarin/xamarin-android#2113
