### ISSUE TITLE
What is packager.exe?

### ISSUE THREAD

**Issue by ArionTT** [mono/mono#10411]
### Current Behavior

I am trying to run the wasm sample. But when I see the line [ mono $WASM_SDK/packager.exe sample.dll ], what is packager.exe?

### Expected Behavior

I want to compile C# code to webassembly file that will be called by html and js.

## On which platforms did you notice this

[*] Linux

**Version Used**:

master github version

**Comment by kumpera** [comment]
Hi, packager.exe is a binary you'll find in the wasm binaries we distribute.
You can download the latest version from our jenkins job: https://jenkins.mono-project.com/job/test-mono-mainline-wasm

**Comment by DutchmanDavid** [comment]
For those who can't find anything executable: https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/

Search for "Latest Azure Artifacts"

This is the first result when I Google "Mono packager.exe" :P
