### ISSUE TITLE
[ WASM ]Build fail  host error

### ISSUE THREAD

**Issue by ArionTT** [mono/mono#10446]
I have make and make install mono on linux. And now I am trying to build sdks/wasm.

I type the command :
`make -C builds {toolchain,configure,build,package}-wasm-interp`

And it return me a error:
```
configure: loading cache /home/Arion/WebAssembly/mono/sdks/builds/wasm-interp.config.cache
checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `wasm32': machine `wasm32' not recognized
configure: error: /bin/sh /home/Arion/WebAssembly/mono/config.sub wasm32 failed
ERROR:root:**Configure step failed with non-zero return code: 1.  Command line: /home/Arion/WebAssembly/mono/configure --cache-file=/home/Arion/WebAssembly/mono/sdks/builds/wasm-interp.config.cache --prefix=/home/Arion/WebAssembly/mono/sdks/out/wasm-interp --enable-interpreter --disable-mcs-build --disable-nls --disable-boehm --disable-btls --with-lazy-gc-thread-creation=yes --with-libgc=none --disable-executables --disable-support-build --disable-visibility-hidden --enable-maintainer-mode --enable-minimal=ssa,com,jit,reflection_emit_save,reflection_emit,portability,assembly_remapping,attach,verifier,full_messages,appdomains,security,sgen_marksweep_conc,sgen_split_nursery,sgen_gc_bridge,logging,remoting,shared_perfcounters,sgen_debug_helpers,soft_debug --host=wasm32 at /home/Arion/WebAssembly/mono/sdks/builds/wasm-interp**
make: *** [.stamp-wasm-interp-configure] Error 1
```

**Comment by ArionTT** [comment]
@lewurm Thanks for reply. My automake version is 1.13.5 and now I have updated it to 1.16.1.(The blow last command is show automake version)

But it still return me a same error that the host is wrong.
Is any other soft should update to the certain version?

My system is CentOS 7.4

configure: loading cache /home/Arion/WebAssembly/mono/sdks/builds/wasm-interp.config.cache
checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `wasm32': machine `wasm32' not recognized
configure: error: /bin/sh /home/Arion/WebAssembly/mono/config.sub wasm32 failed
ERROR:**root:Configure step failed with non-zero return code: 1.  Command line: /home/Arion/WebAssembly/mono/configure --cache-file=/home/Arion/WebAssembly/mono/sdks/builds/wasm-interp.config.cache --prefix=/home/Arion/WebAssembly/mono/sdks/out/wasm-interp --enable-interpreter --disable-mcs-build --disable-nls --disable-boehm --disable-btls --with-lazy-gc-thread-creation=yes --with-libgc=none --disable-executables --disable-support-build --disable-visibility-hidden --enable-maintainer-mode --enable-minimal=ssa,com,jit,reflection_emit_save,reflection_emit,portability,assembly_remapping,attach,verifier,full_messages,appdomains,security,sgen_marksweep_conc,sgen_split_nursery,sgen_gc_bridge,logging,remoting,shared_perfcounters,sgen_debug_helpers,soft_debug --host=wasm32 at /home/Arion/WebAssembly/mono/sdks/builds/wasm-interp**
make: *** [.stamp-wasm-interp-configure] Error 1


[Arion@vultr builds]$ automake --version
**automake (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.**

**Comment by lewurm** [comment]
@kumpera any idea?

**Comment by kumpera** [comment]
Yes, you have an old automake (prior to 1.16.1) and/or you have a configure cache that you must remove. `git clean -xfd` your checkout.

**Comment by zwcloud** [comment]
Still got the same error:

> root@localhost:/home/cloud/mono/sdks# make -C builds {toolchain,configure,build,package,clean}-wasm-runtime
> make: Entering directory '/home/cloud/mono/sdks/builds'
> make: Nothing to be done for 'toolchain-wasm-runtime'.
> mkdir -p /home/cloud/mono/sdks/builds/wasm-runtime-release
> cd /home/cloud/mono/sdks/builds/wasm-runtime-release && source /home/cloud/mono/sdks/builds/toolchains/emsdk/emsdk_env.sh && CFLAGS="-Os -g" emconfigure /home/cloud/mono/configure ac_cv_func_shm_open_working_with_mmap=no --cache-file=/home/cloud/mono/sdks/builds/wasm-runtime-release.config.cache --prefix=/home/cloud/mono/sdks/out/wasm-runtime-release --disable-mcs-build --disable-nls --disable-boehm --disable-btls --with-lazy-gc-thread-creation=yes --with-libgc=none --disable-executables --disable-support-build --disable-visibility-hidden --enable-maintainer-mode --enable-minimal=ssa,com,jit,reflection_emit_save,portability,assembly_remapping,attach,verifier,full_messages,appdomains,security,sgen_marksweep_conc,sgen_split_nursery,sgen_gc_bridge,logging,remoting,shared_perfcounters,sgen_debug_helpers,soft_debug,interpreter --host=wasm32 --enable-llvm-runtime --enable-icall-export --disable-icall-tables --disable-crash-reporting --with-bitcode=yes  CFLAGS="-fexceptions"
> Adding directories to PATH:
> PATH += /home/cloud/mono/sdks/builds/toolchains/emsdk
> PATH += /home/cloud/mono/sdks/builds/toolchains/emsdk/clang/e1.38.11_64bit
> PATH += /home/cloud/mono/sdks/builds/toolchains/emsdk/node/8.9.1_64bit/bin
> PATH += /home/cloud/mono/sdks/builds/toolchains/emsdk/emscripten/1.38.11
> 
> Setting environment variables:
> EMSDK = /home/cloud/mono/sdks/builds/toolchains/emsdk
> EM_CONFIG = /home/cloud/mono/sdks/builds/toolchains/emsdk/.emscripten
> EM_CACHE = /home/cloud/mono/sdks/builds/toolchains/emsdk/.emscripten_cache
> LLVM_ROOT = /home/cloud/mono/sdks/builds/toolchains/emsdk/clang/e1.38.11_64bit
> EMSCRIPTEN_NATIVE_OPTIMIZER = /home/cloud/mono/sdks/builds/toolchains/emsdk/clang/e1.38.11_64bit/optimizer
> BINARYEN_ROOT = /home/cloud/mono/sdks/builds/toolchains/emsdk/clang/e1.38.11_64bit/binaryen
> EMSDK_NODE = /home/cloud/mono/sdks/builds/toolchains/emsdk/node/8.9.1_64bit/bin/node
> EMSCRIPTEN = /home/cloud/mono/sdks/builds/toolchains/emsdk/emscripten/1.38.11
> 
> configure: loading cache /home/cloud/mono/sdks/builds/wasm-runtime-release.config.cache
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... Invalid configuration `wasm32': machine `wasm32' not recognized
> configure: error: /bin/bash /home/cloud/mono/config.sub wasm32 failed
> ERROR:root:Configure step failed with non-zero return code: 1.  Command line: /home/cloud/mono/configure ac_cv_func_shm_open_working_with_mmap=no --cache-file=/home/cloud/mono/sdks/builds/wasm-runtime-release.config.cache --prefix=/home/cloud/mono/sdks/out/wasm-runtime-release --disable-mcs-build --disable-nls --disable-boehm --disable-btls --with-lazy-gc-thread-creation=yes --with-libgc=none --disable-executables --disable-support-build --disable-visibility-hidden --enable-maintainer-mode --enable-minimal=ssa,com,jit,reflection_emit_save,portability,assembly_remapping,attach,verifier,full_messages,appdomains,security,sgen_marksweep_conc,sgen_split_nursery,sgen_gc_bridge,logging,remoting,shared_perfcounters,sgen_debug_helpers,soft_debug,interpreter --host=wasm32 --enable-llvm-runtime --enable-icall-export --disable-icall-tables --disable-crash-reporting --with-bitcode=yes CFLAGS=-fexceptions at /home/cloud/mono/sdks/builds/wasm-runtime-release
> wasm.mk:46: recipe for target '.stamp-wasm-runtime-release-configure' failed
> make: *** [.stamp-wasm-runtime-release-configure] Error 1
> make: Leaving directory '/home/cloud/mono/sdks/builds'

![20181016203906](https://user-images.githubusercontent.com/6965758/47016931-8eb5cc00-d183-11e8-8fc6-b2eda1acbd99.png)
