### ISSUE TITLE
[iOS] FileTest.LastWriteTimeSubMsCopy fails

### ISSUE THREAD

**Issue by lewurm** [mono/mono#10447]
see https://github.com/xamarin/xamarin-macios/pull/4277#issuecomment-417665313

## Steps to Reproduce

1. build mono-2018-06 branch from xamarin/xamarin-macios
2. run `FileTest.LastWriteTimeSubMsCopy` 32-bit or 64-bit mode on an iOS 10.3.3 device

since it worked on 2018-04 (?) the possible candidates for this regression are:
* https://github.com/mono/mono/pull/9696
* https://github.com/mono/mono/pull/10010 which only exists on 2018-06 if I see it correctly

potential missing piece:
* https://github.com/mono/mono/pull/10020 merged on master and 2018-08. It might should replace https://github.com/mono/mono/pull/10010

**Comment by lewurm** [comment]
as pointed out by @rolfbjarne on Slack:
> it started failing after this bump: https://github.com/xamarin/xamarin-macios/pull/4277/commits/b3245a6930b7a6f4eaccdee01f9dbba520a0d205
> which is https://github.com/mono/mono/compare/a8b65e127b5e4ce072bef31359dfa18073996159...f9c42ea71673aabe0010be96274038cb7561dce2
> which has this copyfile commit: https://github.com/mono/mono/commit/341142d7656f43239a041b2c44f00acfb8fa7c59 (= https://github.com/mono/mono/pull/10010)

**Comment by lewurm** [comment]
FWIW, I can't reproduce it on a 32-bit device (iPhone 5c) with iOS 10.3.3 and neither with a 64-bit device (iPhone 7) with iOS 11.4.1.

I was able to reproduce it on the 32-bit simulator with iOS 10.3.1 though.

**Comment by lewurm** [comment]
fixed by https://github.com/mono/mono/pull/10455

**Comment by filipnavara** [comment]
JFYI the test case is not very well written. It would be nice to ensure that the original file before the copy has time with nano-seconds by explicitly setting it and then compare the exact time stamp after the copy.
