### ISSUE TITLE
Suggestion about icon load in win32-executable and mac-application and linux-desktop file

### ISSUE THREAD

**Issue by sourceskyboxer** [mono/mono#10465]
Hello everyone, I would like to give suggestion 

### For Windows:

if `mkbundle --icon C:\Path-to-Icon\your-icon.ico` and it will embed in native executable
If you don't use `--icon` than executable looks like default application

### For Mac OS X Applications 

If you generate to native simple executable for macOS than it will generate as like myapp = ./myapp
Or `mkbundle` should generate with --icon [PATH TO ICON] to simple mac application
like this:
myapp.app
/contents
   /MacOS
     /myapp
    /Resources
      /icon.icon or I don't know what is format of apple's icon file
   /info.plist

### For Linux

If you use `sudo mkbundle -o /usr/bin/myapp` and `--icon myicon.xpm` than it will generate as simple linux application with generate desktop file into `/usr/share/applications/myapp.desktop`

Output should like this:
executable /usr/bin/myapp
icon /usr/share/icons/myapp.xpm
desktop file /usr/share/applications/myapp.desktop

### For Android / Monodroid:
If you generate `mkbundle ... --icon myapp.png -o myapp.apk -v`

PS: I have to prepare my learning with C++/header But I am starting to learn with youtube C++ programming tutorial - Don't worry! I will try...

If you have experience of sometimes converter of icon file into Android, Linux, macOS and Windows which format of icon file and should show in executable.

If you use simple png or tiff than mkbundle will convert to bmp, ico or rgb format of default icon format.
Is it possible? I can draw concept - if you understand better? I will snap and send here.

Thanks for understanding - I hope - Sorry my bad English......

**Comment by migueldeicaza** [comment]
I think the suggestion makes sense for Windows, where the OS can extract the icon from the executable, but I am not sure if this is something that can be done today in the "simple" mode, it could perhaps only be supported in the scenario where we create a new binary, or if we figure out a way of adding the icon to an existing executable after the fact.

For MacOS, I do not think that this is the right approach, for one, there are too many other pieces of metadata that need to be included, and I do not think that `mkbundle` should be the tool that is in charge of orchestrating that, nor that it should grow to do that.   This is something that belongs elsewhere, for instance, there are already target to create native Mac apps with all the proper metadata in place when you create a Xamarin.Mac project.    

The same comments apply to Linux and Android - mkbundle is only resposible for producing the standalone executable - the generation of auxiliary files for the sake of those platforms belongs elsewhere.

Will close this issue, but I am open to reviewing the patch that implements the Windows functionality.

**Comment by sourceskyboxer** [comment]
okay thanks....
