### ISSUE TITLE
mono_thread_info_exit ignores exit_code and just passes 0 on.

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#10467]
mono-threads.c:

```
void
mono_thread_info_exit (gsize exit_code)
{
	mono_thread_info_detach ();

	mono_threads_platform_exit (0);
}
```

Why does it pass 0 and not `exit_code`? This  seems very counter intuitive, and there is no comment.

**Comment by luhenry** [comment]
Follow the template if you want anyone to take a look at it. How do we reproduce? How does it impact anything?
