### ISSUE TITLE
Why does it happen like old time since 4.8 or 4.9???

### ISSUE THREAD

**Issue by sourceskyboxer** [mono/mono#10482]
Hello everyone, 

I am using Ubuntu 16.04 - x64

Mono from Github 5.19.0

mkbundle generates successful great.

Now "Segmentation fault (core dumped)" Grrr I am now explosive because Mono Development always failed like old version on Windows now for Ubuntu happens. I am arguing again. Please check and fix.. I feel explosively.

Thanks!

// EDIT:

If I use -z than it works fine like normal.

If you don't use "-z" than it happens native executable throws "Segmentation fault (core dumped)"

if you use mkbundle --deps --static -L /usr/lib/mono/4.5 myapp.exe -o myapp -v until generates successfully Great well..
And ./myapp 
Segmentation fault (core dumped)

What is shit...... ?

I try that
mkbundle --deps --static -z -L /usr/lib/mono/4.5 myapp.exe -o myapp -v
And generates successfully fine fine

./myapp 
Shows up gui or console.Writeline(9 wow it works fine.

**Comment by luhenry** [comment]
Please follow the Issue template if you want us to be able to provide you help. Also, refer to the [Code of Conduct](https://github.com/mono/mono/blob/master/code_of_conduct.md) and be respectful of the project and its maintainers. Thank you.
