### ISSUE TITLE
Update CI build scripts to not hardcode -j4

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#10506]
We have been updating our infrastructure but most of our CI script still have hardcoded make -j4 even if we nowadays build on machines like Intel Xeon E5-2667 which can handle more.

We should look into the more future proof handling of this which would scale automatically

**Comment by lewurm** [comment]
how about `make -j`?

**Comment by marek-safar** [comment]
I would be worried that it'd make the system unresponsive to the point that to get any crash reports might be too hard
