### ISSUE TITLE
Mono not return environment variable.

### ISSUE THREAD

**Issue by KubekSzklany** [mono/mono#10518]
## Steps to Reproduce

Create windows form application and print this string:
string AppData = Environment.GetEnvironmentVariable("APPDATA");

### Current Behavior

string AppData is just empty string (AppData = "")

### Expected Behavior

I remember that on ubuntu 16.04 it returns:
/home/myusername/.wine/drive_c/users/myusername/applicationdata
or something like that.

## On which platforms did you notice this

[ x] Linux 18.04
[ ] Windows

**Version Used**: Mono 5.14

I am not sure, but i think on ubuntu 16.04 it works.

***I dont know it is problem with latest linux and mono, or just my computer, so i asking for help.***

**Comment by EgorBo** [comment]
Is not it a windows specific variable?
on my ubuntu 18 both mono and .NET Core have:
```
TERM
LESSCLOSE
HOSTTYPE
NAME
_
LOGNAME
LS_COLORS
LANG
SHLVL
HOME
LESSOPEN
SHELL
OLDPWD
PWD
USER
```

**Comment by marek-safar** [comment]
`APPDATA` is Windows specific env variable. I don't think you should expect it to be available on non-Windows unless it's set manually.

**Comment by KubekSzklany** [comment]
Ok, i probably see this variable in wine. Thanks for answer.
