### ISSUE TITLE
[REGRESSION][master] Getting custom attributes+AttributeType for a `DllImport` method throws NRE

### ISSUE THREAD

**Issue by radical** [mono/mono#10544]
Failed output:
```
attr.Type: System.Runtime.InteropServices.PreserveSigAttribute

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Reflection.CustomAttributeData.get_AttributeType () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/master/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/CustomAttributeData.cs:147
  at MainClass.Main (System.String[] args) [0x00052] in <a90fc1674b9b42588ce3846543c65a1e>:0
```

Expected output:
```
attr.Type: System.Runtime.InteropServices.PreserveSigAttribute
attr.Type: System.Runtime.InteropServices.FieldOffsetAttribute
```

test case:
```
using System;
using System.Reflection;
using System.Runtime.InteropServices;

public class MainClass
{
	public static void Main(string[] args)
	{
		var mi = typeof(MainClass).FindMembers(MemberTypes.Method, BindingFlags.Static | BindingFlags.Public, (m, criteria) => m.Name == "pinvoke", null);

		foreach (CustomAttributeData data in ((MethodInfo)(mi[0])).CustomAttributes)
		{
			Console.WriteLine($"attr.Type: {data.AttributeType}");
		}
	}

	[DllImport("libc")]
	public static extern void pinvoke();
}
```

This is because of the `CustomAttributeData` being passed a null `ctorInfo` in the .ctor . And that seems to stem from [this](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Reflection/MonoMethod.cs#L462) where it is trying to find a constructor for `FieldOffsetAttribute` that takes a `string`, but there seems to be only a .ctor taking an `int`. This came from https://github.com/mono/mono/commit/7454c2de2b1e6e4b7da937e91f39d32867801d48 .

This works fine with 2018-06.

**Comment by marek-safar** [comment]
@MaximLipnin it looks like predefined ctor handling broke

**Comment by MaximLipnin** [comment]
It looks like that some changes related to pseudo custom attribute data were not so correct initially.
Mentioned test case for CoreFX and NetFX returns
```
attr.Type: System.Runtime.InteropServices.DllImportAttribute
attr.Type: System.Runtime.InteropServices.PreserveSigAttribute
```
So Mono should also return `DllImportAttribute` not `FieldOffsetAttribute`

BTW `GetCustomAttributes` method on Mono 5.14 for mentioned test case returns only `System.Runtime.InteropServices.PreserveSigAttribute` attribute.
