### ISSUE TITLE
csc.exe: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0

### ISSUE THREAD

**Issue by stil** [mono/mono#10550]
## Steps to Reproduce

1. Install latest Mono for Windows 5.14.0 Stable (5.14.0.177)
2. In Powershell, execute following command:
```ps
& "C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe"
```

### Current Behavior
Following problem occurs

```
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

### Expected Behavior
csc.exe is called from MSBuild, effectively breaking compilation.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:
5.14.0 Stable (5.14.0.177)

## Stacktrace

```
n/a
```

![obraz](https://user-images.githubusercontent.com/714004/45373249-36713480-b5ef-11e8-88b4-1e1d43b45923.png)

**Comment by marek-safar** [comment]
You are trying to run Mono customized csc compiler on your version of .NET (whatever that's it). This is not going to work as need to run int with Mono runtime

**Comment by stil** [comment]
@marek-safar I see, you're right.

However I get the same problem (`Could not load... System.Text.Encoding.CodePages`) when I try to compile my solution with `C:\Program Files\Mono\bin\msbuild.bat`.

I'm pretty sure that msbuild.bat is ran in Mono runtime, so why my compilation fails?
