### ISSUE TITLE
[roslyn] CustomModifiersTests.ConcatModifiers_03 does not work on Mono

### ISSUE THREAD

**Issue by kg** [mono/mono#10564]
```
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.CustomModifiersTests.ConcatModifiers_03 [FAIL]
      System.Runtime.Serialization.SerializationException : Type 'CL3' in Assembly '8c5f7036-342e-4da0-80d2-af0f521d8894, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
      Stack Trace:
          at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <af30111a119b4c33adf68bea3aff0284>:0  
```

**Comment by lambdageek** [comment]
Standalone repro gist https://gist.github.com/lambdageek/982e57262a8dffe3e19fda6141a67e11

This appears to be passing with `master` ac5ab1a7efe

Output is:
```
Set Overridden
Get Overridden
```

(and monodis of the repro .exe shows the expected modopts on the property - but that part isn't really mono-related - just means Roslyn is working correctly)

**Comment by lambdageek** [comment]
Hmm.  Actually now I'm not so sure.

1. The expected failure is a serialization exception of some sort - nothing to do with what my repro is doing.
2. The repro could be passing for the wrong reasons - namely - there is nothing ambiguous in the way the vtable is set up here - there's only one method of each name and if you drop the modifiers completely everything will still line up nicely.

I think we need to actually understand what the roslyn test is doing - I'm not sure where serialization comes into it at all.

**Comment by lambdageek** [comment]
This is passing with #13320.
