### ISSUE TITLE
[System.Windows.Forms]PropertyGrid Scrollbar on wrong side

### ISSUE THREAD

**Issue by sancheolz** [mono/mono#10594]
[propertigridTest.zip](https://github.com/mono/mono/files/2379571/propertigridTest.zip)

## Steps to Reproduce

1.  Launch attached test
Scrollbar of PropertyGrid must appear on right side.
ubuntu 18.04 mono 5.17 Screenshot
![virtualbox_ubuntuwithmultymono_13_09_2018_15_41_08](https://user-images.githubusercontent.com/2684465/45490927-0d78ad00-b771-11e8-9df2-2ec10f0f3322.png)
windows .net 4.0 screenshot
![windowsnet4 0_13_09_2018_15_41_08](https://user-images.githubusercontent.com/2684465/45490936-14072480-b771-11e8-8c7a-12b318cfedcb.png)

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
mono 5.17

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by abrevet-dev** [comment]
Not reproducible with mono version 6.9.0 on Ubuntu 19.04.

**Comment by sancheolz** [comment]
It looks like a flaky issue. Not reproducible with Mono JIT compiler version 6.11.0 (master/a2f9fb77a37 Вт дек  3 10:31:13 MSK 2019) on Ubuntu 19.04.3 and with Mono JIT compiler version 6.0.0.327 (tarball Thu Aug 29 21:15:03 UTC 2019), but sometimes in our project it occurs on latest mono.

**Comment by sancheolz** [comment]
Not reproducible now with master mono.
