### ISSUE TITLE
[mono-2018-06] [XA] Failing System.Buffers.Text.Tests.FormatterTests.System.Buffers.Text.Tests.FormatterTests

### ISSUE THREAD

**Issue by luhenry** [mono/mono#10607]
## Steps to Reproduce

1. Run `System-xunit` tests on Android

### Current Behavior

Following tests are failing:
 - System.Buffers.Text.Tests.FormatterTests.System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal
   - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3989/testReport/junit/Test%20collection%20for%20System.Buffers.Text.Tests/FormatterTests/System_Buffers_Text_Tests_FormatterTests_TestFormatterDecimal___Debug/

### Expected Behavior

Tests succeed

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] Android

## Stacktrace

 -  System.Buffers.Text.Tests.FormatterTests.System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal

```
## Error Message

System.InvalidOperationException : No data found for System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal
```

**Comment by marek-safar** [comment]
@EgorBo could you please look into it

**Comment by EgorBo** [comment]
Seems like an issue in xunit. `TestFormatterDecimal` has empty [MemberData] and the desktop xunit just ignores it, xunit in XA fails with `No data found`

**Comment by luhenry** [comment]
Still failing at:
 - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4061/testReport/Test%20collection%20for%20System.Buffers.Text.Tests/FormatterTests/System_Buffers_Text_Tests_FormatterTests_TestFormatterDecimal___Debug/

@EgorBo if the test should be disabled, please submit a PR against `mono:2018-06` that does so, even if only for XA.

**Comment by luhenry** [comment]
Didn't reproduce in https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/
