### ISSUE TITLE
[mono-2018-06] [XA] Failing System.Collections.Generic.Tests.StringComparersTests.System.Collections.Generic.Tests.StringComparersTests

### ISSUE THREAD

**Issue by luhenry** [mono/mono#10608]
## Steps to Reproduce

1. Run `System-xunit` tests on Android

### Current Behavior

Following tests are failing:
 - System.Collections.Generic.Tests.StringComparersTests.System.Collections.Generic.Tests.StringComparersTests.EqualityComparer_GetHashCodeShouldBeOverriddenAndBeTheSameAsLongAsTheTypeIsTheSame_cloned
   - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3989/testReport/junit/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_GetHashCodeShouldBeOverriddenAndBeTheSameAsLongAsTheTypeIsTheSame_cloned___Debug/
 - System.Collections.Generic.Tests.StringComparersTests.System.Collections.Generic.Tests.StringComparersTests
   - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3989/testReport/junit/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_EqualsShouldBeOverriddenAndWorkForDifferentInstances_cloned___Debug/

### Expected Behavior

Tests succeed

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] Android

## Stacktrace

 -  System.Collections.Generic.Tests.StringComparersTests.System.Collections.Generic.Tests.StringComparersTests.EqualityComparer_GetHashCodeShouldBeOverriddenAndBeTheSameAsLongAsTheTypeIsTheSame_cloned

```
## Error Message

Assert.Equal() Failure\nExpected: 234485397\nActual:   297194330

## Stacktrace

  at System.Collections.Generic.Tests.ComparersGenericTests`1[T].EqualityComparer_GetHashCodeShouldBeOverriddenAndBeTheSameAsLongAsTheTypeIsTheSame_cloned () [0x00028] in <09be0bd04c2642ae99615c36d4d3ab91>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
```

 -  System.Collections.Generic.Tests.StringComparersTests.System.Collections.Generic.Tests.StringComparersTests.EqualityComparer_EqualsShouldBeOverriddenAndWorkForDifferentInstances_cloned

```
## Error Message

Assert.True() Failure\nExpected: True\nActual:   False

## Stacktrace

  at System.Collections.Generic.Tests.ComparersGenericTests`1[T].EqualityComparer_EqualsShouldBeOverriddenAndWorkForDifferentInstances_cloned () [0x00014] in <09be0bd04c2642ae99615c36d4d3ab91>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
```

**Comment by luhenry** [comment]
Still failing at : 
 - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4061/testReport/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_GetHashCodeShouldBeOverriddenAndBeTheSameAsLongAsTheTypeIsTheSame_cloned___Debug/
 - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4061/testReport/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_EqualsShouldBeOverriddenAndWorkForDifferentInstances_cloned___Debug/

**Comment by EgorBo** [comment]
I'll cherry-pick https://github.com/mono/mono/pull/9707 to 2018-06

**Comment by luhenry** [comment]
Still failing at :
 - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/testReport/junit/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_GetHashCodeShouldBeOverriddenAndBeTheSameAsLongAsTheTypeIsTheSame_cloned___Debug/
 - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/testReport/junit/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_GetHashCodeShouldBeOverriddenAndBeTheSameAsLongAsTheTypeIsTheSame_cloned___Release/
 - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/testReport/junit/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_EqualsShouldBeOverriddenAndWorkForDifferentInstances_cloned___Debug/
 - https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/testReport/junit/Test%20collection%20for%20System.Collections.Generic.Tests/StringComparersTests/System_Collections_Generic_Tests_StringComparersTests_EqualityComparer_EqualsShouldBeOverriddenAndWorkForDifferentInstances_cloned___Release/

**Comment by EgorBo** [comment]
I suspect this one was introduced here https://github.com/mono/mono/pull/8874/files#diff-e7526071878d708680e4a8c5fa5a46edR5986

**Comment by marek-safar** [comment]
Fixed
