### ISSUE TITLE
[wasm] Stop using mmap for loading assemblies

### ISSUE THREAD

**Issue by kumpera** [mono/mono#10603]
loading assemblies can hit this issue: https://github.com/kripken/emscripten/issues/7118

Additionally, the way this is done will cause assemblies to be held in memory twice, in the wasm heap and as a TypedArray.

Move away from using the emcc file system and use the mkbundle setup of providing a list of assemblies.

**Comment by alexanderkyte** [comment]
This will make us much less dependent on the correctness and layout of the filesystem as a whole. I think this is an important, beneficial change if we want to avoid bitrot.
