### ISSUE TITLE
bcl.sln doesn't seem to work

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#10635]
Obvious uses of bcl.sln don't work. Perhaps this is known.

## Steps to Reproduce

1. msbuild bcl.sln

### Current Behavior

msbuild bcl.sln

with no parameters:

C:\s2\mono>msbuild bcl.sln
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 9/16/2018 12:40:27 AM.
Project "C:\s2\mono\bcl.sln" on node 1 (default targets).
C:\s2\mono\bcl.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x64" is invalid. Please specify a valid solution c
onfiguration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") o
r leave those properties blank to use the default solution configuration. [C:\s2\mono\bcl.sln]
Done Building Project "C:\s2\mono\bcl.sln" (default targets) -- FAILED.

Build FAILED.

"C:\s2\mono\bcl.sln" (default target) (1) ->
(ValidateSolutionConfiguration target) ->
  C:\s2\mono\bcl.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x64" is invalid. Please specify a valid solution
 configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU")
 or leave those properties blank to use the default solution configuration. [C:\s2\mono\bcl.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.38

So then try the non-defaults the error says to use, they don't work either:

C:\s2\mono>msbuild bcl.sln /p:Configuration=Debug /p:Platform="Any CPU"
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 9/16/2018 12:40:35 AM.
Project "C:\s2\mono\bcl.sln" on node 1 (default targets).
C:\s2\mono\bcl.sln.metaproj : error MSB4126: The specified solution configuration "Debug|Any CPU" is invalid. Please specify a valid soluti
on configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU
") or leave those properties blank to use the default solution configuration. [C:\s2\mono\bcl.sln]
Done Building Project "C:\s2\mono\bcl.sln" (default targets) -- FAILED.

Build FAILED.

"C:\s2\mono\bcl.sln" (default target) (1) ->
(ValidateSolutionConfiguration target) ->
  C:\s2\mono\bcl.sln.metaproj : error MSB4126: The specified solution configuration "Debug|Any CPU" is invalid. Please specify a valid solu
tion configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any C
PU") or leave those properties blank to use the default solution configuration. [C:\s2\mono\bcl.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.38

### Expected Behavior

Successful build.

## On which platforms did you notice this

Windows

**Comment by marek-safar** [comment]
@kg could you look into this one

**Comment by kg** [comment]
You have to specify the platform manually as described in the build instructions. ```net_4_x``` is probably what you want. ```/p:Platform="net_4_x"```

**Comment by luhenry** [comment]
@kg we should probably default to `net_4_x` since that's what we already do by default.

**Comment by kg** [comment]
I'm not aware of any way to set a default. The default platform for each csproj is already net_4_x. Visual studio seems to pick solution platforms completely at random.

**Comment by knocte** [comment]
How about using a `Directory.Build.rsp` file? See https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files?view=vs-2017#directorybuildrsp

**Comment by kg** [comment]
@knocte I added one but it broke everything else in the tree, because apparently ones in parent directories apply to child directories.
