### ISSUE TITLE
[System.Windows.Forms] Combobox SelectedIndexChanged when mouse move

### ISSUE THREAD

**Issue by sancheolz** [mono/mono#10643]
## Steps to Reproduce

1. Add to Form ComboBox whith 3 items
2. Subscribe to event SelectedIndexChanged
3. Select by mouse any item of combobox

### Current Behavior
When mouse cursor appears under item occurs SelectedIndexChanged event

### Expected Behavior
When mouse moved under item shoudn`t occurs SelectedIndexChanged event. It must occur when mouse clicked. On .net works like this. Insted of this event you can use SelectionChangeCommitted

## On which platforms did you notice this

[ ] macOS
[x] Linux ubuntu 18.05
[ ] Windows

**Version Used**:
5.14

**Comment by abrevet-dev** [comment]
Not reproducible with mono version 6.9.0 on Ubuntu 18.04 and Win10.

**Comment by sancheolz** [comment]
@abrevet-dev sorry, the was reproduce incorrect.
Here the correct one
```cs
public partial class Form1 : Form
    {
        private ComboBox comboBox1;
        public Form1()
        {
            comboBox1 = new ComboBox();
            comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            comboBox1.Items.AddRange(new object[] {
            "1",
            "2",
            "3"});
            comboBox1.DropDown += comboBox1_DropDown;
            comboBox1.SelectedIndexChanged += comboBox1_SelectedIndexChanged;
            Controls.Add(comboBox1);
            comboBox1.Items.Add("");
            comboBox1.SelectedIndex = 0;
        }

        private void comboBox1_DropDown(object sender, EventArgs e)
        {
            comboBox1.Items.RemoveAt(0);
            comboBox1.DropDown -= comboBox1_DropDown;
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            MessageBox.Show("SelectedIndesChanged Occured");
        }
    }
```
Perhaps this is not quite the right use of DropDown event, but on .NET works fine.
