### ISSUE TITLE
Missing memory barrier with some atomic operations

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#10651]
It appears that we are using __sync_val_compare_and_swap for i64 with the atomic helpers for CAS, which doesn't give us the needed memory barriers. @luhenry has confirmed that the API design expects the memory barriers to be implemented on the callee side everywhere here. 

https://github.com/mono/mono/blob/master/mono/utils/atomic.c#L505

**Comment by alexanderkyte** [comment]
Some clarification:
It seems that the docs for ` __sync_val_compare_and_swap` say that it creates an implicit memory barrier, but 
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mono/utils/atomic.h#L223
seems to suggest that we need to wrap it on ARM64 / can't rely on that.

**Comment by alexanderkyte** [comment]
This bug would then impact `#if defined (HOST_ARM64) && (defined (__clang__) || MONO_GNUC_VERSION < 50300)
`

**Comment by alexrp** [comment]
Indeed, any use of `__sync` or `__atomic` intrinsics must be wrapped in `WRAP_ATOMIC_INTRINSIC` unless it's in a code path that's known not to run on ARM64.

**Comment by kumpera** [comment]
Can you state which targets have which ordering requirements missing?

**Comment by luhenry** [comment]
`mono_atomic_cas_i64` is AFAIK the only one that doesn't use `gcc_sync_*` wrappers that ensure we have the proper memory barriers around their equivalent `__sync_*`.
