### ISSUE TITLE
[sdks] Change MXE default deploy location to be sdks/builds/toolchains

### ISSUE THREAD

**Issue by kumpera** [mono/mono#10671]
The current default location of MXE is $HOME/android-toolchain.
This should be changed to be self contained into `sdks/builds`.

It was done this way to remain compatible with where XA expects to find mxe so in order for us to change it we'd need to coordinate this change with XA and I assume it means letting them set the prefix they desire.

One interesting issue this raises is the prospect of having the toolchains stored outside of the `sdks` tree, which would allow for faster `git clean -xfd` and sharing it among multiple trees. Food for thought. 🤔

**Comment by luhenry** [comment]
Compiling MXE takes around 1h on a powerful machine, so putting it in `sdks/builds/toolchains/mxe` for example expose us to easily wipe it out by accident. You could argue that we should be able to just download it, but the problem is the MXE generated binaries are not relocatable. The other solution is for us to come up with a package you install in a common location; it could for example be a `brew` package.

**Comment by vargaz** [comment]
I agree that it should be outside the tree since it takes very long to build.
Note that we already have a jenkins lane to build it (osx only):
https://jenkins.mono-project.com/job/build-package-osx-mxe/
The build packages are built in /tmp/mxe-<HASH>, so they need to be installed there to work.

**Comment by kumpera** [comment]
That's a very good point. I do `git clean -xfd` builds a lot when crossing releases but I'm lucky that emcc does binaries and takes about 5m.

The issue of installing them globally is versioning.

How about we install all toolchains[1] under the same prefix and symlink the desired version under `sdks/build/toolchains` - assuming mxe can handle that. Strawman proposal:
```
/opt/mono-toolchains/mxe-3dea81/
/opt/mono-toolchains/mxe-823828/
/opt/mono-toolchains/emscripten-1.2.2/
```

Then on the mono tree:
```
sdks/builds/toolchains/mxe -> /opt/mono-toolchains/mxe-823828/
sdks/builds/toolchains/emcc -> /opt/mono-toolchains/emscripten-1.2.2/
```

Why symlink? Well, I do experiment a lot with the active emcc sdk and the symlink is a small, nice QOL improvement.

[1] We'd do that with emscripten as well.

**Comment by luhenry** [comment]
We already do versioning for `mxe`, right now it's `mxe-b9cbb53` (same form as what XA requires). I like your idea of putting it in `/opt/mono-toolchains/...`.

**Comment by marek-safar** [comment]
How is LLVM different to MXE? Should we use the same approach for both?

**Comment by vargaz** [comment]
LLVM is not really a toolchain for us, its something we build and ship.

**Comment by kumpera** [comment]
I think we agreed this ticket was a bad idea. Let me close it before it drives more distraction. :)
