### ISSUE TITLE
Mono and macOS 10.14 Mojave problems

### ISSUE THREAD

**Issue by lemonmojo** [mono/mono#10689]
Hi mono team,

I posted basically the same already here: https://github.com/xamarin/xamarin-macios/issues/4509#issuecomment-422784459

Since macOS 10.14 Mojave DP1 I'm suffering from problems with mono.

Basically creating NSWindow instances with mono results in visual artefacts when resizing them. There's also other visual problems like NSScrollView's getting stuck (refuse to scroll) after some time and NSOutlineView's suddenly refusing to draw some cells. These problems occur at random times but I found a nice reproduction case in the Xamarin Mac samples repo: https://github.com/xamarin/mac-samples.

Here's what I did to reproduce the problem:
- Download https://github.com/xamarin/mac-samples
- Open VisualEffectPlayground in VS 7.7 build 1282 with Mono 5.14.0.177
- Run project
- Click Vibrant Colors button
- Start resizing the window

Here's how this looks:
![mono mojave bug](https://user-images.githubusercontent.com/186198/45752865-253fad80-bc17-11e8-915e-8758f626f835.gif)

Note that the window is not resized correctly, there are visual artifacts (kind of a shadow) around the areas where it's resized and various error log messages by WindowServer (`CoreAnimation: Context ID mismatch`).

Now the really interesting part: I'm 100% certain that this is not an issue in Xamarin.Mac but probably in the mono runtime. The reason I'm so sure about that is that my app, [Royal TSX](https://www.royalapplications.com/ts/mac) suffers from the very same problems. Royal TSX is based on mono and a custom fork of Monobjc. It doesn't use Xamarin.Mac at all. Unfortunately, the issues appear randomly there and are not as easily reproducible as with the VisualEffectPlayground. I also struggled to provide a reduced test case until I found this thread. With the sample project the problem is reproducible 100% of the time which is at least something. It appears though that the problems are timing sensitive.

I previously filed a radar with Apple about this because I suspected some defect in the OS. Instead, they pointed to mono's use of `thread_suspend`. I'm not sure what's wrong with it but they seem to believe it's somehow related. Unfortunately the radar was closed as it appeared that upgrading to a newer mono release fixed the issue. This doesn't seem to be the case though. I also hoped that the problem would be fixed by one of the DPs but alas, it's still there with the GM candidate.

As I see it, this affects every single Mac application built using mono so this is a huge issue that needs to be solved quickly as Mojave's release date is next Monday.

cheers,
felix

**Comment by lemonmojo** [comment]
Here's the info from Visual Studio's about dialog:
```
=== Visual Studio Professional 2017 for Mac (Preview) ===

Version 7.7 Preview (7.7 build 1282)
Installation UUID: 7c1f22f0-9e53-4c07-9bd3-4086f6c262d4
Runtime:
	Mono 5.14.0.177 (2018-04/f3a2216b65a) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 514000177

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Android Device Manager ===

Version: 7.7.1.0
Hash: f11c178f

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 4.8.0.22 (Visual Studio Professional)
Hash: bd81f1c3
Branch: 
Build date: 2018-08-24 17:10:45-0400

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707001282
Git revision: cfff48c7cf9ee2db7ccad51846abf697c0bc2b91
Build date: 2018-09-07 18:06:37+00
Build branch: release-7.7
Xamarin extensions: ce83fabc2c8823a41b3981363c8ee39bdde61612

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.4.3
Monobjc Visual Studio 1.0
Internet of Things (IoT) development (Preview) 7.5.3
```

**Comment by marek-safar** [comment]
Closing this to keep the discussion at one place

**Comment by lemonmojo** [comment]
@marek-safar I intentionally posted this in the mono repo because I strongly believe that it's not Xamarin.Mac related as explained in my post.

**Comment by Rogister** [comment]
I test my application on MacOS Mojave for 3 weeks and there are problems.

My application works perfectly on MacOS High Sierra but Mojave, there are problems refresh. Boxes of messages that appears but completely empty (we see nothing). With datagrids, I also see problems.

I click on a line of the datagrid, it works normally a few times then I do not know why, the clique does not answer anymore, the datagrid refreshes itself.

I tried to debug and see what happens but it's impossible, there is no logic to the problem. For me, there is a problem Mono or MacOS because it is incomprehensible.

it joins the problem that I read above.

Alain
