### ISSUE TITLE
beforefieldinit is not correctly recognized for static ctors

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#10710]
## Steps to Reproduce

1. Compile following
```c#
using System;

	public class SideEffectCctorWithInitializer
	{
		private static int counter;
		
		public static void Main()
		{
			counter = 0;
			Foo.Method();
			Console.WriteLine(counter);
		}

		public static class Foo
		{
			public static Bar o = new Bar();
			
			public static void Method()
			{
			}
		}

		public class Bar
		{
			public Bar()
			{
				counter++;
			}
		}
	}
```
2. mono output.exe

### Current Behavior

1

### Expected Behavior

0

All versions .NET print 0. The static ctor is not run unless a static field is touched.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

master/d7337904202

**Comment by lewurm** [comment]
this is going to be ugly, as this is deeply wired into class loading (therefore, interp behaves the same).

is this behaviour blocking something?

**Comment by vargaz** [comment]
According to the spec, beforefieldinit cctors can be ran at  any time.

**Comment by marek-safar** [comment]
The spec says

>3. If marked BeforeFieldInit then the type’s initializer method is executed at, or
sometime before, first access to any static field defined for that type. 

In the sample above the static field is not accessed at all, therefore, the static ctor should not run at all, the working is not perfect but that's how I would read it for the case where there is no access.

@lewurm I don't think this block anything we just execute .NET code differently which can cause programs to misbehave

**Comment by vargaz** [comment]
What the spec means is that the only constraint is that the static cctor needs to be executed before the first field access. It could be executed anytime before.

**Comment by vargaz** [comment]
The reason beforefieldinit was added to spec was so that the runtime can optimize it any way it likes, if somebody wants consistency, they can define an explicit cctor.

**Comment by EgorBo** [comment]
.NET 4.7.1 prints 1 on my machine (.NET Core prints 0).
