### ISSUE TITLE
 UI Thread Freeze on WebClient DownloadDataAsync

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#10719]
_From @manuelpa-ms on September 20, 2018 15:2_

### Steps to Reproduce

1. Environment: iOS device is connected to an Access Point with limited connectivity (no internet access, no DNS resolution).
2. In a Xamarin.iOS application, run the following code (first button on shared sample):
private void RunTest()
{
var wc1 = new WebClient();
wc1.DownloadDataAsync(new Uri("http://www.test.aero"));
var wc2 = new WebClient();
wc2.DownloadDataAsync(new Uri("http://www.test.aero"));
// Execution will never reach here. The above call will simply lock up.
}

Possible changes listed here: https://developer.xamarin.com/releases/ios/api_changes/ios-11-12-0-11-14-0/#Namespace_System.Net

### Expected Behavior
The UI thread should not freeze; the DownloadDataAsync functions should return. This is the behavior on Xamarin.iOS 11.12

### Actual Behavior
UI thread freezes even if running this code from a background thread. The stacktrace while frozen is as follows:

System.Net.ServicePoint.SendRequest(System.Net.WebOperation operation, string groupName) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/ServicePoint.cs:267
System.Net.HttpWebRequest.SendRequest(bool redirecting, System.Net.BufferOffsetSize writeBuffer, System.Threading.CancellationToken cancellationToken) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:851
System.Net.HttpWebRequest.MyGetResponseAsync() in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:995
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.HttpWebResponse>.Start<System.Net.HttpWebRequest.<MyGetResponseAsync>d__243>(System.Net.HttpWebRequest stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
System.Net.HttpWebRequest.MyGetResponseAsync(System.Threading.CancellationToken cancellationToken) in 
System.Net.HttpWebRequest.RunWithTimeout<System.Net.HttpWebResponse>(System.Func<System.Threading.CancellationToken,System.Threading.Tasks.Task<System.Net.HttpWebResponse>> func, int timeout, System.Action abort) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs
System.Net.HttpWebRequest.RunWithTimeout<System.Net.HttpWebResponse>(System.Func<System.Threading.CancellationToken,System.Threading.Tasks.Task<System.Net.HttpWebResponse>> func) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs
System.Net.HttpWebRequest.BeginGetResponse(System.AsyncCallback callback, object state) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:1169
System.Net.WebClient.GetWebResponseTaskAsync() in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:268
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.WebResponse>.Start<System.Net.WebClient.<GetWebResponseTaskAsync>d__112>(System.Net.WebClient stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
System.Net.WebClient.GetWebResponseTaskAsync(System.Net.WebRequest request) in 
System.Net.WebClient.DownloadBitsAsync() in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:865

### Environment

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.14
Working correctly on Xamarin.iOS 11.12.x

```
```

### Example Project (If Possible)

[WebClientFreezesUIFromBackgroundThread_ext.zip](https://github.com/xamarin/xamarin-macios/files/2401841/WebClientFreezesUIFromBackgroundThread_ext.zip)

_Copied from original issue: xamarin/xamarin-macios#4858_

**Comment by rolfbjarne** [comment]
I can reproduce this in the simulator if I set Apple's Network Link Conditioner to "100% Loss".

Full stack traces, both kill -QUIT and lldb: https://gist.github.com/rolfbjarne/4698d9d6e8697d8f963ea7c66c300555

**Comment by marek-safar** [comment]
@baulig it looks like we are not fully async for this code path. Any idea why is SendRequest blocking here?

**Comment by baulig** [comment]
From that stack trace, `HttpWebRequest.SendRequest` is supposed to be synchronous by design - which is perfectly fine even for the async code path as long as nothing _blocks_ on an expensive operation.

So let's have a look at what that method does.  This is `ServicePoint.SendRequest`:

```
		internal void SendRequest (WebOperation operation, string groupName)
		{
			lock (this) {
				if (disposed)
					throw new ObjectDisposedException (typeof (ServicePoint).FullName);
				Scheduler.SendRequest (operation, groupName);
			}
		}
```

This is `ServicePointScheduler.SendRequest`:

```
		public void SendRequest (WebOperation operation, string groupName)
		{
			lock (ServicePoint) {
				var group = GetConnectionGroup (groupName);
				Debug ($"SEND REQUEST: Op={operation.ID} group={group.ID}");
				group.EnqueueOperation (operation);
				Run ();
				Debug ($"SEND REQUEST DONE: Op={operation.ID} group={group.ID}");
			}
		}
```

Neither `GetConnectionGroup()` nor `EnqueueOperation()` can block on anything, they're just modifying lists and hash tables.  Here is `ServicePointScheduler.Run()`:

```
		public void Run ()
		{
			Debug ($"RUN");
			if (Interlocked.CompareExchange (ref running, 1, 0) == 0)
				Task.Run (() => RunScheduler ());

			schedulerEvent.Set ();
		}
```

So I have two possible explanations at the moment: either we somehow deadlock or there's something wrong with that `Task.Run()` above.

Could this possibly block?

**Comment by baulig** [comment]
However, there is also the possibility that your stack trace is not showing the real issue, because something from your description looks very suspicious:

> Environment: iOS device is connected to an Access Point with limited connectivity (no internet access, _no DNS resolution_).

There is a possibility that a hanging DNS lookup could cause problems.

**Comment by jonathanantoine** [comment]
Hello @baulig , I have an issue which looks a lot like this one, maybe it can help ? https://github.com/xamarin/xamarin-macios/issues/5333 

Thanks for your help !

**Comment by marek-safar** [comment]
@rolfbjarne we have difficulties to reproduce it, could you double check it's still happening with 2018-10.

@akoeplinger could you please try as well

**Comment by akoeplinger** [comment]
I can't reproduce with the following XI version and instructions from https://github.com/mono/mono/issues/10719#issuecomment-423221279, it takes about 60-90 seconds to return from the method (presumably some timeout):

```
Xamarin.iOS
Version: 12.2.1.15 (Visual Studio Enterprise)
Hash: d60abd198
Branch: d15-9
Build date: 2019-02-01 12:23:29-0500
```

Same result with the 2018-10 version, though I've seen it take up to 160 seconds here:

```
Xamarin.iOS
Version: 12.7.0.268 (Visual Studio Enterprise)
Hash: 75ea3ca9b
Branch: mono-2018-10
Build date: 2019-02-18 18:05:55+0100
```

Note: make sure to change the URL/domain if you ran with working internet otherwise the DNS lookup will be cached.

WebClient is known for performing synchronous DNS requests even on the Download*Async methods, one more reason why HttpClient should be preferred. It seems to be working as expected to me.

**Comment by marek-safar** [comment]
Thank you @akoeplinger!
