### ISSUE TITLE
Changes in corlib_xtest.dll.sources don't get applied on Windows

### ISSUE THREAD

**Issue by MaximLipnin** [mono/mono#10717]
## Steps to Reproduce

1. build the latest master on Windows
2. `cd mcs/class/corlib` and `make run-xunit-test`; note the number passed tests
3. make change in corlib_xtest.dll.sources (e.g. comment out some tests)
4. run `make run-xunit-test`; compare the number passed tests got on step 2

### Current Behavior

The change in corlib_xtest.dll.sources don't get applied.

### Expected Behavior

The change in corlib_xtest.dll.sources should get applied.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:

master/0cf1a2b4a8d

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by EgorBo** [comment]
looks similar to the problem we had a while ago with regular sources https://github.com/mono/mono/pull/9061
so I guess we should apply the same fix for xunit tests (corlib has a windows-only `win32_corlib_xtest.dll.sources`)
