### ISSUE TITLE
How to dump all threads with Stack traces? ( mono_threads_request_thread_dump() )

### ISSUE THREAD

**Issue by michaldobrodenka** [mono/mono#10720]
How to call `mono_threads_request_thread_dump()` from C#?

Can I execute this method from C#?

I can execute this from gdb, but I have to flush stdout many times manually from gdb to get real output (bug?). mono_stack macro works normally.

**Comment by Therzok** [comment]
You could send a SIGQUIT signal to the process, it'll do that automatically.

**Comment by michaldobrodenka** [comment]
Ok, I got it.

```
[DllImport("__Internal")]
public static extern void mono_threads_request_thread_dump();
```

But it doesn't write everything, I have to trigger flushing stdout manually.

Sending SIGQUIT is better way. Thank you very much!
