### ISSUE TITLE
xbuild and msbuild preserves readonly file permission when copying referenced assembly.

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#10743]
Found this while debugging a xamarin-macios failure using the mono-2018-08 branch.

## Steps to Reproduce

1. Download and extract attached
[Xamarin.MMP.Tests.MMPTests.RunMMPTest68.zip](https://github.com/mono/mono/files/2406573/Xamarin.MMP.Tests.MMPTests.RunMMPTest68.zip)
2. edit UnifiedExample.csproj to adjust the HintPath for `b.dll`
3. Note that `b.dll` in the project is readonly.
4. Run `xbuild` or `msbuild`  (Both behave the same way)
5. `ls -l bin/Debug/UnifiedExample.app/Contents/MonoBundle/b.dll`

### Current Behavior

Output of `ls` is

```
-r-xr-xr-x  1 alklig  staff  3072 Sep 21 11:24 bin/Debug/UnifiedExample.app/Contents/MonoBundle/b.dll
```

Note that the result file is readonly.

### Expected Behavior

```
-rwxr-xr-x  1 alklig  staff  3072 Sep 21 11:24 bin/Debug/UnifiedExample.app/Contents/MonoBundle/b.dll
```

Note that the result file is readwrite.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Bad result: mono 5.16 and 5.18.

Expected result: mono 5.14

Please see https://github.com/xamarin/xamarin-macios/pull/4596#issuecomment-423444555 for the failure in-situ.  The test is called `Xamarin.MMP.Tests.MMPTests.Dontlink_Allow_ReadonlyAssembly`

**Comment by marek-safar** [comment]
There is nothing special in msbuild about it.

@lambdageek could you try to reproduce it with simple File.Copy BCL call?

**Comment by lambdageek** [comment]
`File.Copy ("x.from", "x.to", True);` when `x.from` is readonly and `x.to` doesn't exist creates a readonly `x.to`.  So just using File.Copy and not fixing up the permissions doesn't give the result that XM expects.

**Comment by radical** [comment]
I'm not able to reproduce this with 5.16.05, 5.16.0.152 or 5.18.0.106 . One thing to note is that msbuild (via the `Copy` task) is copying `b.dll` *only* to `bin/Debug/b.dll`, which has the expected permissions. But the file that mentioned above, `bin/Debug/UnifiedExample.app/Contents/MonoBundle/b.dll`, is copied by the `mmp` task from XI and not msbuild itself. But I'm not being able to reproduce that either.

@lambdageek should I be using a jenkins build of XI for this?

**Comment by lambdageek** [comment]
@radical I'm using the versions below.   As far as I know, this is all released Alpha channel stuff, except for mono 5.18.0.115 which is from Jenkins.

```
Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.8 Preview (7.8 build 408)
Installation UUID: c1b3b394-68d8-4231-92e8-47d068034506
Runtime:
	Mono 5.18.0.115 (2018-08/005c804cb2c) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 518000115

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.1.0
	2.0.7
	2.0.6
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.300
	2.1.200
	2.1.103
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Apple Developer Tools
Xcode 10.0 (14320.25)
Build 10A255

Xamarin.Mac
Version: 4.8.0.22 (Visual Studio Enterprise)
Hash: bd81f1c3
Branch: 
Build date: 2018-08-24 17:10:45-0400

Xamarin.iOS
Version: 11.16.0.22 (Visual Studio Enterprise)
Hash: bd81f1c3
Branch: HEAD
Build date: 2018-08-24 17:10:45-0400

Xamarin.Android
Version: 9.1.0.17 (Visual Studio Enterprise)
Android SDK: /Users/alekseyk/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.0.2
SDK Platform Tools Version: 26.0.0
SDK Build Tools Version: 23.0.3

Java SDK: /usr
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.1.652.0
Hash: d9c8ea86

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 708000408
Git revision: 71e204ffc2fbfac5fd56710ad49746b77ce1361d
Build date: 2018-09-07 16:55:06+00
Build branch: master
Xamarin extensions: b2631e0f54e48c46f45e661017f59180fd419d73

Operating System
Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
AddinMaker 1.4.3
```

**Comment by radical** [comment]
After installing everything from the alpha channel, I am able to reproduce this. But IIUC, this is a XM/mmp issue, as I can reproduce it with just mmp (which doesn't depend on msbuild) by running it with the arguments obtained from a build:

```
          /verbose 
          /debug 
          /output:/private/tmp/Xamarin.MMP.Tests.MMPTests.RunMMPTest68/bin/Debug/ 
          /name:UnifiedExample 
          '/profile:Xamarin.Mac,Version=v2.0,Profile=Mobile' 
          /arch:x86_64 
          --http-message-handler=HttpClientHandler 
          /minos=10.7 
          /nolink 
          /assembly:/tmp/Xamarin.MMP.Tests.MMPTests.RunMMPTest68/b.dll 
          /assembly:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/mscorlib.dll 
          /assembly:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.Core.dll 
          /assembly:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.dll 
          /assembly:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Xamarin.Mac.dll 
          /assembly:/tmp/Xamarin.MMP.Tests.MMPTests.RunMMPTest68/b.dll 
          /root-assembly:/private/tmp/Xamarin.MMP.Tests.MMPTests.RunMMPTest68/bin/Debug/UnifiedExample.exe 
          /sdkroot:/Applications/Xcode.app/Contents/Developer 
          --cache:/private/tmp/Xamarin.MMP.Tests.MMPTests.RunMMPTest68/obj/Debug/mmp-cache 
```

Steps:
1. Write the above set of args to a temp file, like `/tmp/mmp-args.rsp`
2. Build with msbuild
3. `rm bin/Debug/UnifiedExample.app/Contents/MonoBundle/b.dll*` # this is the file in question
4. run `/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/tmp/mmp-args.rsp`
5. `ls -l bin/Debug/UnifiedExample.app/Contents/MonoBundle/b.dll`

Step 5 shows the file with readonly permissions.
Maybe @jstedfast or @chamons can correct me if I'm wrong about `mmp`.

**Comment by radical** [comment]
Oh, also since the arguments have the full path to the project, unzip the project in `/tmp` or adjust the paths.

**Comment by lambdageek** [comment]
Okay, I @marek-safar I think this bug is due to https://github.com/mono/linker/commit/0f781501fa17c8018fdbd7001e912c5073ee21e1
That change changed the linker OutputStep `CopyAssembly` function to use as the source the original (read-only) assembly file, not the copied over (read-write) assembly. 

The following patch (for https://github.com/mono/linker) makes the test pass:

```patch

---
 linker/Linker.Steps/OutputStep.cs | 15 ++++++++++++---
 1 file changed, 12 insertions(+), 3 deletions(-)

diff --git a/linker/Linker.Steps/OutputStep.cs b/linker/Linker.Steps/OutputStep.cs
index 61852b7..4969ef8 100644
--- a/linker/Linker.Steps/OutputStep.cs
+++ b/linker/Linker.Steps/OutputStep.cs
@@ -213,18 +213,27 @@ namespace Mono.Linker.Steps {
 			if (source == target)
 				return;
 
-			File.Copy (source, target, true);
+			CopyFileAndRemoveReadOnly (source, target);
 
 			if (!Context.LinkSymbols)
 				return;
 
 			var mdb = source + ".mdb";
 			if (File.Exists (mdb))
-				File.Copy (mdb, target + ".mdb", true);
+				CopyFileAndRemoveReadOnly (mdb, target + ".mdb");
 
 			var pdb = Path.ChangeExtension (source, "pdb");
 			if (File.Exists (pdb))
-				File.Copy (pdb, Path.ChangeExtension (target, "pdb"), true);
+				CopyFileAndRemoveReadOnly (pdb, Path.ChangeExtension (target, "pdb"));
+		}
+
+		static void CopyFileAndRemoveReadOnly (string src, string dest) {
+			File.Copy (src, dest, true);
+
+			FileAttributes attrs = File.GetAttributes (dest);
+
+			if ((attrs & FileAttributes.ReadOnly) == FileAttributes.ReadOnly)
+				File.SetAttributes (dest, attrs & ~FileAttributes.ReadOnly);
 		}
 
 		protected virtual string GetAssemblyFileName (AssemblyDefinition assembly, string directory)
-- 
2.19.0
```

But I think the original commit was wrong to use the original assembly info.  MMP ends up copy every assembly twice.  Once during its `CopyAssemblies`  run and once during the linker's `OutputStep`.
