### ISSUE TITLE
WebRequest timeout

### ISSUE THREAD

**Issue by grendello** [mono/mono#10774]
_From @rgroenewoudt on September 21, 2018 13:15_

Timeout while using WebResponse many times.

System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000ba] in <b78695579ed9422b8bc80218eeda782c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.GetResponse () [0x00013] in <b78695579ed9422b8bc80218eeda782c>:0 

### Steps to Reproduce
```
while (true)
                    {
                        System.Diagnostics.Debug.WriteLine("google.nl start");
                        var client = (HttpWebRequest) WebRequest.Create("http://google.nl");
                        client.Timeout = (int) TimeSpan.FromSeconds(10).TotalMilliseconds;
                        client.GetResponse();
                        System.Diagnostics.Debug.WriteLine("google.nl end");
                    }
```
No issues when response is disposed or WebRequest is aborted.

### Version Information
Visual Studio 15.8.5. Same issue with 15.7.6.

_Copied from original issue: xamarin/xamarin-android#2209_

**Comment by grendello** [comment]
_From @rgroenewoudt on September 21, 2018 13:18_

When calling asmx webservice, the implementation of SoapClientProtocol does not dispose of the response (only the stream) resulting in the same timeout.

**Comment by grendello** [comment]
[test.zip](https://github.com/xamarin/xamarin-android/files/2411660/test.zip)

This issue is not specific to Xamarin.Android, I was able to reproduce it on desktop and therefore the issue will be moved to the Mono repository.

**Comment by rgroenewoudt** [comment]
Probably related to #8775

**Comment by rgroenewoudt** [comment]
Update: I've tried this with the latest Xamarin Android master, which is on mono commit 709b46e3 on 2018-06 branch.

It doesn't hang anymore but any WebRequests after 10 give a timeout.
~~~
Exception for request 11: System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <3ce14cdcdd91498783a49521fbaf80e9>:0 
  at System.Net.HttpWebRequest.GetResponse ()
~~~

Not hanging anymore is better but failing all webrequests afterwards is still not good.

**Comment by DragonTM** [comment]
@rgroenewoudt Do you know if these changes are released?

**Comment by rgroenewoudt** [comment]
In any case not in mono 5.12/5.14 or in Visual Studio 15.9.

**Comment by DragonTM** [comment]
@marek-safar Could you clarify when changes @rgroenewoudt mentioned will be released?

> mono commit 709b46e

**Comment by marek-safar** [comment]
@DragonTM the changes will be included in dev16 preview 2
