### ISSUE TITLE
[xammac] 2018-08 CertificateTest.MailX1 test failure

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#10805]
We see this failure in the 2018-08 Xamarin.Mac integration: https://github.com/xamarin/xamarin-macios/pull/4596#issuecomment-417625169

## Steps to Reproduce

1. clone and build `mono-2018-08` branch of xamarin-macios
2. `cd tests && make run-mac-unified-xammac_tests`

### Current Behavior

```
MonoTouchFixtures.Security.CertificateTest.MailX1: Handle
Expected: not 0
But was: 0
```

### Expected Behavior

`MonoTouchFixtures.Security.CertificateTest.MailX1` test passes.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

xamrin-macios mono-2018-08 branch.  mono is at 65c1b9

---

More details from Rolf's comment:

>         [FAIL] CertificateTest.MailX1 : Handle 
>        [FAIL] RecordTest.SecRecordRecordTest : Same Handle 
>
>    They both represent failures to create a `X509Certificate`.
>
>    The first is here:

https://github.com/xamarin/xamarin-macios/blob/6cfc8b5a60516d25bd032361224a09e1f8ba0f12/tests/monotouch-test/Security/CertificateTest.cs#L574-L579
>
>    The second is here (`cert.Handle` is IntPtr.Zero):

https://github.com/xamarin/xamarin-macios/blob/6cfc8b5a60516d25bd032361224a09e1f8ba0f12/tests/monotouch-test/Security/RecordTest.cs#L317

> and which was created a few lines above using the same `X509Certificate` code:
 
https://github.com/xamarin/xamarin-macios/blob/6cfc8b5a60516d25bd032361224a09e1f8ba0f12/tests/monotouch-test/Security/RecordTest.cs#L310

**Comment by marek-safar** [comment]
@baulig please help with the fix

**Comment by baulig** [comment]
PR is up: https://github.com/mono/mono/pull/10865.
We also need to land https://github.com/xamarin/xamarin-macios/pull/4888.
