### ISSUE TITLE
Delegate members

### ISSUE THREAD

**Issue by jaredpar** [mono/mono#10838]
## Steps to Reproduce

Consider the following code in Program.cs:

``` csharp
using System.Linq;

class Program
{
    delegate int D1();

    static void Main()
    {
        foreach (var member in typeof(D1).GetMembers(
            System.Reflection.BindingFlags.DeclaredOnly |
            System.Reflection.BindingFlags.Public |
            System.Reflection.BindingFlags.Instance).OrderBy(m=>m.MetadataToken))
        {
            System.Console.WriteLine(member.ToString());
        }
    }
}
```

Then do the following:

1. `mcs Program.cs`
1. `mono Program.exe`

The output for the delegate constructor will be:

> Void .ctor(Object, IntPtr)

The expected output is:

> Void .ctor(System.Object, IntPtr)

Note: this is breaking the C# emit test [Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenClosureLambdaTests.OrderOfDelegateMembers](https://github.com/dotnet/roslyn/blob/5bedd8b880ae7123791fd1b77a319c42f3100aac/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs#L4248)

## On which platforms did you notice this

Ubuntu 18.04 using Mono 5.19.0.209

**Comment by jaredpar** [comment]
Further testing shows this is not just delegate signatures, appears to happen on all signatures.

**Comment by marek-safar** [comment]
@MaximLipnin could you look into this one about ToString implementation
