### ISSUE TITLE
VSMac F# test fail after upgrading to 2018-08

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#10851]
## Steps to Reproduce

1. Run MonoDevelop.FSharp.Tests
2. There are test failures

### Current Behavior

Test failures, see https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=164928&environmentId=598459&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension:

```
MonoDevelopTests.Template tests.Xamarin Android FSharp AndroidApp

[("Build error",
"/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets",
"The reference assemblies for framework "MonoAndroid,Version=v1.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.")]
```

It only seems to affect MonoDroid apps.

### Expected Behavior

No failures.

## On which platforms did you notice this

[ x ] macOS
[ ] Linux
[ ] Windows

**Version Used**: 5.18.0.115

**Comment by marek-safar** [comment]
@radical please investigate

**Comment by radical** [comment]
This will be fixed once the msbuild update PR: https://github.com/mono/mono/pull/10668 is merged. [This commit](https://github.com/mono/msbuild/commit/300887e680a0cc790476efad9613507ead5957d3) specifically fixes the issue.

**Comment by radical** [comment]
The XF test failures look to be the same issue, based on the logs.

**Comment by marek-safar** [comment]
@akoeplinger could you bump the VS integration to see if it works now?

**Comment by akoeplinger** [comment]
Yup it works now (still other tests failing): https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=166645&environmentId=606815&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension
