### ISSUE TITLE
64-bit integers not aligned correctly for calli on 32-bit Android

### ISSUE THREAD

**Issue by mhutch** [mono/mono#10858]
Per https://github.com/mellinoe/veldrid/issues/83#issuecomment-425204801 it appears that 64-bit integers are not aligned to 8-byte boundaries on the stack when using `calli` on 32-bit Android, unlike clang. The ARM calling convention spec appears to support clang's behavior in this case.

**Comment by marek-safar** [comment]
@vargaz could you please confirm?

**Comment by lewurm** [comment]
I came up with a testcase that works on amd64, but fails on armv7: https://github.com/lewurm/mono/commit/7e2782c1044198bceaf590e4da177d65aad2ed0b

**Comment by SamMonoRT** [comment]
Closing this old mono\mono issue we haven't had a need to fix(or was already fixed and not marked correctly) that for 2+ years now. Please re-open if we need to revisit this again.
