### ISSUE TITLE
System.TypeLoadException in mono when running fsharp code linked to a library with same name

### ISSUE THREAD

**Issue by sporring** [mono/mono#10872]
## Steps to Reproduce

1. Make a library and an application with filenames app.fs and app.fsx, e.g.,

E.g., app.fs:
```
module test
let trunc v =
  if v < 0 then 0
  elif v > 255 then 255
  else v
```
app.fsx:
`printfn "%d" (test.trunc 260)`

2. Compile the library and link with the application:

`fsharpc --nologo -a app.fs && fsharpc --nologo -r app.dll app.fsx && mono app.exe`

### Current Behavior

The above procedure causes mono to halt with an 

```
$  fsharpc --nologo -a app.fs && fsharpc --nologo -r app.dll app.fsx && mono app.exe

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000010 from typeref (expected class 'test' in assembly 'app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000010 from typeref (expected class 'test' in assembly 'app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
```

Note, that this neither the case, if the two files are compiled simultaneously

```
$ fsharpc --nologo app.fs app.fsx && mono app.exe
255
```

nor if run through fsharpi

```
$ fsharpi app.fs app.fsx
255
```

There seems to be a name clash in the exe-file, since if app.fs is changed to a name, whose prefix does not coincide with app.fsx, then everything works fine:

```
$ mv app.fs lib.fs
$ fsharpc --nologo -a lib.fs && fsharpc --nologo -r lib.dll app.fsx && mono app.exe
255
```

### Expected Behavior

It is expected not to cast an exception at runtime or to give a compile error.

## On which platforms did you notice this

[X] macOS
[X] Linux
[X] Windows

**Version Used**:

I have tried on various versions of operating systems and Mono versions 5.10.1 and 5.14.0. Presently, I'm using macOS and:

mono --version
Mono JIT compiler version 5.14.0.177 (2018-04/f3a2216b65a Fri Aug  3 09:28:16 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

**Comment by lambdageek** [comment]
I don't think this is Mono-specific.
This also happens with .NET Framework on Windows:
```
Z:\>fsc -a app.fs
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

Z:\>fsc -r app.dll app.fsx
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

Z:\>app.exe

Unhandled Exception: System.TypeLoadException: Could not load type 'test' from a
ssembly 'app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at <StartupCode$app>.$App$fsx.main@()
```

In general .NET cannot distinguish two assemblies with the same name, version, public key token and culture.  The filename doesn't matter.  In this case both `app.dll` and `app.exe` are `'app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'` so loading both at the same time is not supported and will have unpredictable results.

**Comment by emiludenz** [comment]
If the app.fsx file includes the line #load "app.fs" it will compile and run as expected.

>#load "app.fs"
>printfn "%d" (test.trunc 260)


>$ fsharpc --nologo -a app.fs && fsharpc --nologo -r app.dll app.fsx && mono app.exe
>255

**Comment by lambdageek** [comment]
@emiludenz `#load` works by textual inclusion. it doesn't actually cause a reference to `app.dll` to be included in `app.exe` - it just loads the source code from `app.fs` when compiling `app.fsx`.

Try this:
```
  $ rm app.dll app.exe
  $ fsharpc app.fsx
  $ mono app.exe
  255
```

**Comment by sporring** [comment]
@marek-safar, why has this been closed? If this is a known issue, then I would say that the bug is the missing error message at the time of linking. A run-time error caused by filename issues during compilations is a bad mix of concepts.

**Comment by marek-safar** [comment]
You get TypeLoadException exception which if I understood the @lambdageek conclusion is what is expected. What else would you like to be improved?

**Comment by sporring** [comment]
I agree with the diagnosis. Since this is expected behavior and can be determined at compile-time, then a compile-time error would be the right thing to do, in my view.

**Comment by marek-safar** [comment]
Please F# compiler issue in that case at https://github.com/fsharp/fsharp

**Comment by sporring** [comment]
I have reposted it as https://github.com/fsharp/fsharp/issues/877.

Thanks.
