### ISSUE TITLE
System.Security.Cryptography.CryptographicException: Input data cannot be coded as a valid certificate.

### ISSUE THREAD

**Issue by shravan2x** [mono/mono#10949]
## Steps to Reproduce

1. Try to load the attached certificate as an `X509Certificate2`. This works correctly on NET46 and NETSTANDARD2.1. The certificate is a testing certificate and is not private. Feel free to redistribute it.
[test.zip](https://github.com/mono/mono/files/2440736/test.zip)

### Current Behavior

It throws an exception.

### Expected Behavior

The certificate loads correctly.

## On which platforms did you notice this

[ ] macOS
[ x ] Linux
[ ] Windows

**Version Used**: 4.6.2

As of the time of writing, this was the latest version available in the default sources on Raspbian Stretch (RasPi Zero W).

## Stacktrace

```
Unhandled Exception:
System.Security.Cryptography.CryptographicException: Input data cannot be coded as a valid certificate. ---> System.Security.Cryptography.CryptographicException: Input data cannot be coded as a valid certificate.
  at Mono.Security.X509.X509Certificate.Parse (System.Byte[] data) [0x00041] in <1d0bb82c94e7435eb09324cf5ef20e36>:0
   --- End of inner exception stack trace ---
```

**Comment by marek-safar** [comment]
Could you try with newer Mono version? Version 4.6.2 is quite old and we have made several fixes in this area.

**Comment by shravan2x** [comment]
Just tried with 5.14.0 and the issue isn't there. My bad, sorry.
