### ISSUE TITLE
BitConverter.GetBytes(float.NaN) returns unexpected result on ARM

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#10963]
```csharp
byte[] bytes = BitConverter.GetBytes(float.NaN);
``` 
on arm returns `[0, 0, 192, 127]` instead of `[0, 0, 192, 255]` like on x86/x86_64. 
Same for `BitConverter.GetBytes(double.NaN)`

I was trying to import a corefx test and it failed on all ARM CI agents (Linux ARMv5, Linux ARMv7, etc).
see https://github.com/mono/corefx/pull/145

**Comment by lewurm** [comment]
I can't reproduce it on armv7 with this:

```csharp
using System;
using System.Text;

public class FloatStuff {
    public static void Main (string []args) {
        byte[] r4_nan = BitConverter.GetBytes (float.NaN);
        Console.WriteLine ("r4_nan: " + DumpByteArr (r4_nan));
    }

    private static string DumpByteArr (byte[] arr)
    {
        StringBuilder sb = new StringBuilder ("[");
        for (int i = 0; i < arr.Length; i++)
            sb.Append ((byte)(sbyte) arr [i] + ", ");

        sb.Append ("]");
        return sb.ToString ();
    }
}
```
result:
```
r4_nan: [0, 0, 192, 255, ]
```
same as on amd64. @EgorBo am I missing something? tested with mono master from 21st September

**Comment by lewurm** [comment]
FWIW, `[0, 0, 192, 127]` is the bit pattern for a _Signaled NaN_:
> An SNaN is a NaN with the most significant fraction bit clear. It can be used to signal an exception when used in operations. SNaN's can be handy to assign to uninitialized variables to trap premature usage.

For example it's the result of `1337.0f / 0.0f`. However that's consistent with AMD64. Maybe there are differences between ARM and AMD64 on different operations. Do you have more context on the failing tests?

**Comment by lewurm** [comment]
It's a problem with the test imho, submitted a PR to corefx: https://github.com/dotnet/corefx/pull/32741

**Comment by lewurm** [comment]
We are going to have to wait until a proper fix landed in roslyn: https://github.com/dotnet/roslyn/issues/30439

**Comment by marek-safar** [comment]
@EgorBo let's disable the tests for now with tracking number referencing the roslyn issue

**Comment by lewurm** [comment]
roslyn fix is merged https://github.com/dotnet/roslyn/pull/30587
gonna need to wait until we have it in mono 🙂
