### ISSUE TITLE
WaitForFullGCComplete is not implemented

### ISSUE THREAD

**Issue by jaredpar** [mono/mono#10961]
## Steps to Reproduce

Call `GC.WaitForFullGCComplete()` 

### Current Behavior

Throws `NotImplementedException`

### Expected Behavior

Waits for a full GC routine to complete

Note: this is used as a part of the Roslyn unit test [Microsoft.CodeAnalysis.UnitTests.TextChangeTests.TestMergeChanges_NoMiddleMan](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/CodeAnalysisTest/Text/TextChangeTests.cs#L743)

## On which platforms did you notice this

Ubuntu 18.04 using Mono 5.19.0.209

**Comment by marek-safar** [comment]
That test is not great, it could still just hang on Mono because we don't have precise stack scanning. Please just disable the test.

**Comment by jaredpar** [comment]
Sounds good. Think this is the only test that uses this API so disabling it is not much of a coverage loss.
