### ISSUE TITLE
Error mapping file: mono_file_map_error failed, Access is denied

### ISSUE THREAD

**Issue by lukespragg** [mono/mono#10985]
## Steps to Reproduce

1. Create an mkbundle .exe on Windows, for Windows with bundled dependencies
2. Try to run that bundled .exe on Windows
3. Watch with sadness as it errors

### Current Behavior

A broken .exe that does not work nor run without errors.

### Expected Behavior

A working .exe produced by mkbundle on Windows, for Windows.

## On which platforms did you notice this

[x] Windows

**Version Used**:

```
Mono JIT compiler version 5.19.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

## Stacktrace

`Error mapping file: mono_file_map_error failed file:C:\test\mono\mcs\class\lib\net_4_x-win32\Compiler.exe length:0xF22000 offset:0x20000 function:MapViewOfFile error:Access is denied.(0x5)`

Previously posted at somewhat related issue: https://github.com/mono/mono/issues/10290

**Comment by jaykrell** [comment]
Maybe length needs to be 64k-aligned too.

**Comment by T0bi-Ethirbirge** [comment]
Sorry for my question but what length?

**Comment by elitest** [comment]
I'm also seeing this on 5.23.0.

**Comment by lateralusX** [comment]
Should be fixxed by https://github.com/mono/mono/pull/13061.
