### ISSUE TITLE
Mono fails to build on FreeBSD/PowerPC64

### ISSUE THREAD

**Issue by lenoil98** [mono/mono#11021]
I understand that PowerPC64 is not officially supported on FreeBSD. I can successfully build 32-bit Mono on FreeBSD/PowerPC.  The 64-bit build progresses fairly well.  However I get a SIGILL when building.  Below is an excerpt from the build log:

```
System.Net/HttpConnection.cs(57,19): warning CS0414: The private field `System.Net.HttpConnection.cert' is assigned but its value is never used
System.Net/HttpWebRequest.cs(86,10): warning CS0414: The private field `System.Net.HttpWebRequest.initialMethod' is assigned but its value is never used
System.Net/WebConnection.cs(196,25): warning CS0649: Field `System.Net.WebConnection.ID' is never assigned to, and will always have its default value `0'
System.Net/WebConnectionStream.cs(46,10): warning CS0414: The private field `System.Net.WebConnectionStream.locker' is assigned but its value is never used
System.Net/WebConnectionStream.cs(49,17): warning CS0649: Field `System.Net.WebConnectionStream.IgnoreIOErrors' is never assigned to, and will always have its default value `false'
System.Net/WebOperation.cs(65,25): warning CS0649: Field `System.Net.WebOperation.ID' is never assigned to, and will always have its default value `0'
System.Net/WebOperation.cs(66,10): warning CS0649: Field `System.Net.WebOperation.ME' is never assigned to, and will always have its default value `null'
System.Net/WebRequestStream.cs(49,28): warning CS0649: Field `System.Net.WebRequestStream.ME' is never assigned to, and will always have its default value `null'
System.Net/WebResponseStream.cs(78,28): warning CS0649: Field `System.Net.WebResponseStream.ME' is never assigned to, and will always have its default value `null'
Compilation succeeded - 45 warning(s)
MCS     [basic] System.Xml.dll
MCS     [basic] System.Security.dll
../../../external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/KeyInfoRetrievalMethod.cs(78,24): warning CS0219: The variable `retrievalMethodElement' is assigned but its value is never used
System.Security.Cryptography.Xml/SignedXml.cs(391,11): warning CS0219: The variable `hashvalue' is assigned but its value is never used
Compilation succeeded - 2 warning(s)
MCS     [basic] System.Core.dll
../../build/common/MonoTODOAttribute.cs(100,25): warning CS1635: Cannot restore warning `CS0436' because it was disabled globally
../../../external/corefx/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/IncrementalHash.net46.cs(23,26): warning CS0472: The result of comparing value type `System.Security.Cryptography.HashAlgorithmName' with null is always `true'
Compilation succeeded - 2 warning(s)
MCS     [basic] System.ComponentModel.Composition.dll
MCS     [basic] System.Numerics.dll
MCS     [basic] System.Xml.Linq.dll
MCS     [basic] Mono.Cecil.dll
MCS     [basic] Mono.Cecil.Mdb.dll
MCS     [basic] Mono.CompilerServices.SymbolWriter.dll
MCS     [basic] PEAPI.dll
mkdir -p -- ../../class/lib/basic/tmp/
MCS     [basic] cil-stringreplacer.exe
./../jay/jay: 7 rules never reduced
./../jay/jay: 14 shift/reduce conflicts.
MCS     [basic] ilasm.exe
ILParser.cs(165,37): warning CS0429: Unreachable expression code detected
ILParser.cs(165,68): warning CS0429: Unreachable expression code detected
ILParser.cs(166,7): warning CS0162: Unreachable code detected
codegen/CodeGen.cs(460,48): warning CS0219: The variable `asmb' is assigned but its value is never used
codegen/DebuggingInfo.cs(103,16): warning CS0219: The variable `entry' is assigned but its value is never used
codegen/PeapiTypeRef.cs(249,25): warning CS0162: Unreachable code detected
codegen/CodeGen.cs(60,30): warning CS0414: The private field `Mono.ILASM.CodeGen.image_base' is assigned but its value is never used
codegen/MethodDef.cs(54,33): warning CS0414: The private field `Mono.ILASM.MethodDef.codegen' is assigned but its value is never used
codegen/DataDef.cs(18,43): warning CS0414: The private field `Mono.ILASM.DataDef.segment' is assigned but its value is never used
Compilation succeeded - 9 warning(s)
Assembling '../../../class/corlib/System.Runtime.CompilerServices/Unsafe.il' , no listing file, to dll --> '../../../class/lib/basic/corlib.unsafe.dll.tmp'

../../../class/corlib/System.Runtime.CompilerServices/Unsafe.il : Warning -- Reference to undeclared extern assembly 'mscorlib', adding.
Operation completed successfully
mkdir -p -- ../../../class/lib/basic/Facades/
./../jay/jay: 7 shift/reduce conflicts.
MCS     [basic] System.Runtime.dll
MCS     [basic] System.Collections.dll
MCS     [basic] System.Reflection.dll
MCS     [basic] mcs.exe
MCS     [basic] System.Resources.ResourceManager.dll
MCS     [basic] System.Globalization.dll
MCS     [basic] System.Threading.Tasks.dll
MCS     [basic] System.Collections.Concurrent.dll
MCS     [basic] System.Text.Encoding.dll
MCS     [basic] System.IO.dll
MCS     [basic] System.Threading.dll
MCS     [basic] System.Diagnostics.Debug.dll
MCS     [basic] System.Linq.Expressions.dll
MCS     [basic] System.Dynamic.Runtime.dll
MCS     [basic] System.Linq.dll
MCS     [basic] System.Threading.Tasks.Parallel.dll
MCS     [basic] System.Xml.ReaderWriter.dll
MCS     [basic] System.Diagnostics.Tools.dll
MCS     [basic] System.Reflection.Primitives.dll
MCS     [basic] System.Runtime.Extensions.dll
MCS     [basic] System.Runtime.InteropServices.dll
MCS     [basic] System.Text.Encoding.Extensions.dll
MCS     [basic] System.Runtime.Numerics.dll
MCS     [basic] System.Xml.XDocument.dll
MCS     [basic] System.Reflection.Extensions.dll
MCS     [basic] System.IO.FileSystem.Primitives.dll
MCS     [basic] System.IO.FileSystem.dll
MCS     [basic] System.Diagnostics.FileVersionInfo.dll
MCS     [basic] System.Security.Cryptography.Primitives.dll
MCS     [basic] System.Security.Cryptography.Algorithms.dll
MCS     [basic] System.ValueTuple.dll
MCS     [basic] System.Text.Encoding.CodePages.dll
Creating .dep_dirs-build...
Creating .dep_dirs-build...
mkdir -p -- ../../class/lib/build-linux/
Stacktrace:

  at <unknown> <0xffffffff>
  at System.Globalization.CultureData.get_Invariant () [0x000b2] in <445343b3499f4493aad682c3d706c4c0>:0
  at <unknown> <0xffffffff>
  at Mono.ILASM.Driver.Main (string[]) [0x00005] in <cab757a6a332478ea5d0afa123379e6b>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) [0x00054] in <cab757a6a332478ea5d0afa123379e6b>:0

=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

gmake[10]: *** [il/il.make:4: ../../class/lib/build-linux/corlib.unsafe.dll.tmp] Abort trap (core dumped)
gmake[10]: *** Waiting for unfinished jobs....
gmake[9]: *** [../../build/rules.make:211: do-all] Error 2
gmake[8]: *** [../build/rules.make:232: all-recursive] Error 1
gmake[7]: *** [build/rules.make:232: all-recursive] Error 1
gmake[6]: *** [Makefile:54: profile-do--build--all] Error 2
gmake[5]: *** [Makefile:50: profiles-do--all] Error 2
gmake[4]: *** [Makefile:610: all-local] Error 2
gmake[4]: Leaving directory '/usr/ports/lang/mono/work/mono-5.14.0.177/runtime'
gmake[3]: *** [Makefile:552: all-recursive] Error 1
gmake[3]: Leaving directory '/usr/ports/lang/mono/work/mono-5.14.0.177'
gmake[2]: *** [Makefile:482: all] Error 2
gmake[2]: Leaving directory '/usr/ports/lang/mono/work/mono-5.14.0.177'
===> Compilation failed unexpectedly.
```

Anyone with suggestions will be greatly appreciated.

**Comment by lewurm** [comment]
@lenoil98 thanks for your report. could you specify which version/revision of mono you are trying to build? also, could you make sure `gdb` is installed? with that mono should provide a better native stack trace.

**Comment by NattyNarwhal** [comment]
I think I vaguely remember this happening under AIX - I can't remember if it was a case of bad hwcap (FreeBSD has no implementation at all for PowerPC) or when I was trying to get PPC32 to work (some kind of fucky calling convention issue) - if I recall, this icall is called early and has a strange calling convention layout that stresses marshalling (I think floats?)

**Comment by NattyNarwhal** [comment]
Oh, I was misremembering, I'm pretty sure it was the time [I tried to get Darwin/ppc working again](https://github.com/mistydemeo/tigerbrew/issues/605).

**Comment by lenoil98** [comment]
Build is against Mono-5.14.0.177.  gdb is installed but debugging not enabled,  will rerun build with debugging enabled.

**Comment by NattyNarwhal** [comment]
for ppc64 I'd recommend building against the latest git master; if I remember correctly, there's been some improvements there. (I also verified master DOES build with FreeBSD/amd64 OOTB.)

also, if FreeBSD for ppc64 works on IBM systems, let me know; I *might* be able to get an LPAR to try myself on with.

**Comment by NattyNarwhal** [comment]
Actually, my suspicion here is that the calling convention definitions for FreeBSD are wrong; either by differing from Linux, or by using the wrong definitions. I'm very sure this is the first icall called, so it makes sense that it has issues.

What calling conventions does FreeBSD on ppc64 use? Do they match up with the ifdefs in `mini-ppc.*`? Can we get a FreeBSD/powerpc developer here to clarify?

**Comment by lenoil98** [comment]
Could this be an ENDIAN issue.  I noticed there are a few tests for "_CALL_ELF == 2" in the ppc code.  This makes me believe the ppc 64bit code is written for the ppc64le.  Does anyone know if mono builds on BE ppc64 Linux OOTB?

**Comment by NattyNarwhal** [comment]
the `_CALL_ELF` stuff is indeed for Linux - the way its set up, is that ppc64 with ELFv1 calling convention (most ppc64be Linux and AIX/PASE via a historical quirk) will build with the ELFv1 ABIs when its not present or set to 1, and ppc64 with the ELFv2 calling convention (ppc64le Linux and some ppc64be Linux, particularly distros that use musl) will build with the ELFv2 ABIs with it set to 2.

I think FreeBSD actually uses the ELFv2 one on ppc64 too, so I wonder what defines it uses. Can you paste the output of `echo | cc -dM -E`? (replace cc with gcc if needed)

**Comment by awilfox** [comment]
FreeBSD uses "whatever ABI the compiler supports".  For gcc 4.2, that's ELFv1; for LLVM, it could be either one, and indeed, there have been "test" images using ELFv2 on FreeBSD BE.

GCC has always provided `_CALL_ELF` [since adding ELFv2 support](https://gcc.gnu.org/ml/gcc-patches/2013-11/msg01141.html), and that macro being defined is [required for any C compiler that implements ELFv2](http://openpowerfoundation.org/wp-content/uploads/resources/openpower-elfv2abi-thts/content/ch03s01s01.html).  Therefore, you are guaranteed to have either no `_CALL_ELF` if ELFv1 ABI is in use or` _CALL_ELF` defined to _something_ if the toolchain is new enough to support ELFv2.

**Comment by NattyNarwhal** [comment]
Yeah, I haven't tested Mono on a ppc64be system with ELFv2; just ELFv1 BE Linux and AIX/i. For all I know, there could be some incorrect ifdef; there has been before.

**Comment by lenoil98** [comment]
I checked with Justin Hibbits and here are his thoughts:

I get the sneaking suspicion with ABI issues.  A SIGILL likely means,
if you can track it down in a debugger, that it's calling a function
descriptor as a function.  Since I haven't even bothered to look at any
code yet, it's purely a guess, but I'm guessing they're targeting ELFv2
these days (particularly, ppc64le primarily), and ELFv1 has
languished.  ELFv1 requires function descriptors, whereas ELFv2 does
not.  If the compiler doesn't know that it has to call through the
function descriptor, which is an indirect call, then it could be
calling the function descriptor itself instead of the function it
describes.

**Comment by NattyNarwhal** [comment]
I was trying to get his attention on IRC, but he didn't respond back. Mono does support ELFv2 (the CI builder is ppc64le, so ELFv2) but it still does support the ELFv1 ABI with function descriptors; AIX is using (something to close to, at least) said ABI., and that's run over CI.

I did have similar issues with bringup on AIX, (trying to make it use function descriptors; see #6677 for what that entailed) but the fact you're hitting the issue on what I believe to be the first icall (meaning trampolines generated for the first managed function ran, the OutOfMemoryException ctor, worked out enough to get this far) means it might be a bit pickier.

**Comment by lewurm** [comment]
it also could be that mono is emitting an instruction that isn't understood by your hardware; what CPU are you running on?

**Comment by awilfox** [comment]
It has nothing to do with the processor.  ELFv2 works fine on the 970MP, in an environment that uses ELFv2.  There are no newer instructions needed for that calling convention.  The Linux musl libc, for example, uses ELFv2 all the way back to the POWER4.

That said, you should make sure that it is being compiled with -mcpu=970 or similar, so that GCC isn't emitting newer instructions.

**Comment by NattyNarwhal** [comment]
Well, the Mono JIT could be emitting the invalid opcodes in this case. There is no hwcap for FreeBSD/ppc64, so it'll use a very conservative set of instructions. (no POWER4 instructions, no PPC64 instructions, no POWER7 instructions, no load/store optimizations - maybe it needs one of them on ppc64?)

**Comment by lenoil98** [comment]
Let me clarify, I meant that FreeBSD only supports ELFv1 on PowerPC.  Being that this is a Tier 2 supported platform and does not always get some updated features.

BTW, I tried compiling with -mcpu970 and got the same results.

**Comment by NattyNarwhal** [comment]
Unfortunately, we're kinda flying blind here unless we have a disassembly - if you have `objdump` installed, run mono with `-v -v`.

One thing I realized just now is.... `basic` profile builds fine with what I assume is Monolite, but the build goes nuts once it changes over to the platform-specific `build` profile. I want to get my hands on a FreeBSD/powerpc64 system for myself and try to poke it; I'll see if I can't poke some people for an LPAR if it runs on pSeries...

**Comment by lenoil98** [comment]
Here the output for mono -v -V:

Mono JIT compiler version 5.14.0.177 (5.14.0.177 Thu Oct 11 22:10:44 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  ppc
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	GC:            sgen (concurrent by default)

**Comment by NattyNarwhal** [comment]
`-v -v` needs to be run with the program. You can monkey patch `runtime/mono-wrapper` to include it; alternatively, you can also edit said file to run Mono under gdb (like `gdb --args the mono executable...`)

**Comment by lenoil98** [comment]
Okay, the output the attached.

[mono.log](https://github.com/mono/mono/files/2471268/mono.log)

**Comment by awilfox** [comment]
```
  ec:   00 00 01 01     .long 0x101
  f0:   00 00 01 01     .long 0x101
```

That looks wrong.

**Comment by lewurm** [comment]
That's indeed wrong.
```
  ec:	00 00 01 01 	.long 0x101
  f0:	00 00 01 01 	.long 0x101
  f4:	78 00 07 c6 	rldicr  r0,r0,32,31
  f8:	50 92 01 01 	rlwimi. r18,r4,0,4,0
  fc:	59 dc 01 01 	rlmi.   r28,r14,r0,4,0
```
is generated by this:
https://github.com/mono/mono/blob/51ebea7a4891ef106028241ce7345478d6cf6727/mono/mini/mini-ppc.c#L5290-L5292
which expands to:
https://github.com/mono/mono/blob/51ebea7a4891ef106028241ce7345478d6cf6727/mono/arch/ppc/ppc-codegen.h#L776-L784

Later this code will be patched by 
https://github.com/mono/mono/blob/51ebea7a4891ef106028241ce7345478d6cf6727/mono/mini/mini-ppc.c#L4718-L4721
https://github.com/mono/mono/blob/51ebea7a4891ef106028241ce7345478d6cf6727/mono/mini/mini-ppc.c#L4691-L4699

so...
```
Method [...] emitted at 0x509258f0 to 0x50925b04 (code length 532) [ilasm.exe]
```
therefore the address that should be patched in is `0x509258f0` + `0xec` = `0x509259dc`. Have a look again at the disassembly, can you spot those values? 😉 Note it's really `0x0000_0000_5092_59dc` that we patch in.

Not sure what goes wrong here. Wrong macro maybe? `_LITTLE_ENDIAN`/`_BIG_ENDIAN` is used for defining `patch_load_sequence ()`, but usually we have `G_LITTLE_ENDIAN`/`G_BIG_ENDIAN` in mono. Could you give that a try @lenoil98 ?

**Comment by NattyNarwhal** [comment]
A lot of the PPC ABI sensitive things are (IMHO) guarded by the wrong the definitions - ones that might work on glibc Linux, but got sketchy anywhere else. (The obvious ones had to be fixed for AIX, for instance.) This one on mini-ppc.c+4691 looks sketchy even if you changed it to G_BYTE_ORDER; should be _CALL_ELF != 2 or at the least, or be G_BYTE_ORDER == G_BIG_ENDIAN. (The latter is what I had to do to fix the previous decimal impl....)

**Comment by lenoil98** [comment]
Changing line  4691 as suggested you suggested did the trick.  Changed line 4682, for consistency, to

#if G_BYTE_ORDER == G_LITTLE_ENDIAN

**Comment by NattyNarwhal** [comment]
Nice! Could you submit a PR/patch for it here? I'm curious what it does to Linux/ppc64le and aix/ppc64be in this case.

**Comment by NattyNarwhal** [comment]
I can file a properly branched PR for you over my lunch break after I test it on AIX, hold still...
