### ISSUE TITLE
Build of mono-core RPM fails due to problems with corefex native objects

### ISSUE THREAD

**Issue by nealef** [mono/mono#11067]
## Steps to Reproduce

1. Install 5.16.0-187 src RPM
2. run rpmbuild -bb

### Current Behavior
I took the mono-core src rpm for 5.16 and attempted a build with in on s390x (a few minor edits of the spec file were required). However, it appears the external/corefx directory is already populated with binaries:
```
 ../BUILD/mono-5.16.0.187/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_errno.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

Even after I get rid of those object files the build process doesn't remake them.

The few edits to spec file:
1. Make setting of %llvm conditional on architecture
2. s390x build doesn't produce csc - remove from manifests
3. s390x produces .mdb files not .pdb

### Expected Behavior

Clean build

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:
5.16.0-187

## Stacktrace

N/A

**Comment by nealef** [comment]
@directhex Any ideas?

**Comment by nealef** [comment]
make dist takes the objects built of external/corefx and includes it in the tarball. These don't get rebuilt. I created my own dist tarball from a local build.

**Comment by directhex** [comment]
This will be fixed by https://github.com/mono/mono/pull/11509
