### ISSUE TITLE
Type.IsByRefLike throws NotSupportedException

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#11086]
## Steps to Reproduce

```csharp
int test = 10;
Console.WriteLine (test.GetType ().IsByRefLike);
```

### Current Behavior

```
   System.NotSupportedException : Derived classes must provide an implementation.
  at System.Type.get_IsByRefLike () [0x00000] in /Users/alexander/dev/mono/mcs/class/corlib/ReferenceSources/Type.cs:42
```

### Expected Behavior

No exception and `false` for types like int.

## On which platforms did you notice this

[ X ] macOS
[ X ] Linux
[ X ] Windows

**Version Used**: master

**Comment by akoeplinger** [comment]
This is most likely because of https://github.com/mono/mono/pull/10982

@MaximLipnin @marek-safar 

It's breaking xunit 2.4.1 which started looking up this property and trying to get its value.

**Comment by MaximLipnin** [comment]
New version of `TypeDelegator` expects `Type` to have `IsByRefLike` property. So I've added it with throwing NSE by default. I'm not sure how it should be addressed for particular types.

**Comment by akoeplinger** [comment]
Looks like the implementation in coreclr (https://github.com/dotnet/coreclr/commit/c61525b5883e883621f98d44f479b15d790b0533) calls into the runtime.

**Comment by marek-safar** [comment]
@MaximLipnin you have to implement it in RuntimeType properly, why did their test not catch that?

**Comment by akoeplinger** [comment]
It would be in https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/Type/TypeTests.netcoreapp.cs#L208-L213 but we don't run those tests.

**Comment by MaximLipnin** [comment]
@vargaz @lambdageek Could you help please? Is it possible to add any stuff for `IsByRefLike`? If I'm correct it's something similar to what we have for `IsByRef` ...
 https://github.com/mono/mono/blob/2c3ad9d4580b2e967075a4468be865a015e6ffae/mono/metadata/icall.c#L2775-L2779

**Comment by lambdageek** [comment]
@MaximLipnin I sketched out an implementation #11111.  I don't know what "byref-like" means, however.  there's no documentation on docs.microsoft.com, the test from corefx is mysterious and I haven't looked through the coreclr implementation to find the actual definition yet.

**Comment by lambdageek** [comment]
> It would be in https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/Type/TypeTests.netcoreapp.cs#L208-L213 but we don't run those tests.

@akoeplinger Can I turn that test on for #11111 or would I need to port it over to our test suite?

**Comment by lambdageek** [comment]
Hm. there are compilation issues if I just add `TypeTests.cs` and `TypeTests.netcoreapp.cs`

I added a new issue to track: https://github.com/mono/mono/issues/11220
