### ISSUE TITLE
Seeking clarification on documentation around System.Xml.Serialization

### ISSUE THREAD

**Issue by majellin24** [mono/mono#11083]
This is not really an issue, I am posting here due to the line on the page https://www.mono-project.com/community/ which says 

> Feel free to file an issue on GitHub if you want to discuss something, even if it's not a bug.

### Current Behavior

Currently, I have a PCL with a System.Xml.Serialization XmlSerializer constructed with the XmlSerializer(Type, XmlAttributeOverrides) constructor so I can modify how a list of subclasses gets serialized/deserialized.  Essentially, each of my classes derives from the same abstract class, and each of them have a List property (called "children") of the abstract class type.   My XmlAttributeOverrides allows the XmlSerializer to deserialize XML in which any node can be within any other and the enclosing node will have its "children" property deserialized to contain any enclosed nodes. 

This works as I expect on my windows project which references the PCL but my android project which references the same PCL does not work.

I noticed the docs (https://www.mono-project.com/docs/tools+libraries/libraries/xml/) state that:

> Because of lack of ambiguity detection, there is no way to provide XmlMapping XmlTypeMapping/XmlMemberMapping). But If anyone is interested in such effort, integration with XmlSerializer would be interesting task.

Does that apply to my situation?

I basically asked the same thing here: https://stackoverflow.com/questions/52748779/mono-android-xmlserializer-does-not-use-xmlattributeoverrides

## On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**:

I am using Xamarin.Android 8.2.0.16

This may be another source of my confusion as I am uncertain about the difference between Mono and Xamarin and where each is used/for what each is responsible.

For instance, would the same src code in mcs/class/System.XML be referenced, for instance, in both a Xamarin.Android AND Xamarin.iOS project.

I'm sorry if this issue is inappropriate or if I am even more confused than I think I am :)

**Comment by knocte** [comment]
This bug needs to be reopened because its fix has been reverted, here: https://github.com/mono/mono/commit/9988ebc7f2cf61216d9f27a07074046357440079
