### ISSUE TITLE
CI accepts failure as success

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#11091]
1. Submit a PR
2. Expect success to mean things are working.

Counter example:

https://github.com/mono/mono/pull/11017

https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15230/

```
Checking unintended native code changes in iltests.exe with AOT
Unable to compile method 'int Tests:calli_sig_check_2 ()' due to: 'Invalid IL code in Tests:calli_sig_check_2 (): IL_000b: calli     0x11000044

 assembly:<unknown assembly> type:<unknown type> member:(null)'.
Memory around native instruction pointer (0xa17f0496):
0xa17f0486  8e 05 ff e2 c3 90 b8 48 01 08 00 e8 72 1f 00 00  .......H....r...
0xa17f0496  73 0e e8 00 00 00 00 5a 8b 92 87 1b 8e 05 ff e2  s......Z........
0xa17f04a6  c3 90 b8 4c 01 04 00 e8 56 1f 00 00 73 0e e8 00  ...L....V...s...
0xa17f04b6  00 00 00 5a 8b 92 6b 1b 8e 05 ff e2 c3 90 b8 49  ...Z..k........I

Native stacktrace:

	0   mono                                0x001fe0a9 mono_dump_native_crash_info + 809
	1   mono                                0x001aa4a3 mono_handle_native_crash + 179
	2   mono                                0x001fd389 sigabrt_signal_handler + 153
	3   libsystem_platform.dylib            0xa18cae5b _sigtramp + 43
	4   ???                                 0xffffffff 0x0 + 4294967295
```

I suspect I regressed this (the assertion failure, not CI missing it) back in May but I have to dig more.

**Comment by jaykrell** [comment]
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15206/parsed_console/log.html

search for "due to:"

**Comment by jaykrell** [comment]
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15066/parsed_console/log.html

search for "due to:"

**Comment by jaykrell** [comment]
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15055/parsed_console/log.html

search for "due to:"

**Comment by lewurm** [comment]
the problem is that https://github.com/mono/mono/blob/6b9b24c5832cf58f74fd9cf956d922edace2496d/mono/mini/test_op_il_seq_point.sh doesn't propagate exit codes when calling the runtime

**Comment by jaykrell** [comment]
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15065/parsed_console/log.html

search for "due to:"
