### ISSUE TITLE
Blazor + Neo4j database driver throws exception

### ISSUE THREAD

**Issue by danroth27** [mono/mono#11115]
_From @jsmars on October 11, 2018 8:7_

I'm trying to use Neo4j as my database for a blazor application, but when I this to create the driver:
`var driver = GraphDatabase.Driver(url, AuthTokens.Basic(user, pass));`
I get the following exception:

> Uncaught (in promise) Error: System.TypeInitializationException: The type initializer for 'Neo4j.Driver.Internal.RuntimeHelper' threw an exception. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
>   at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription () <0x1ecef00 + 0x00008> in <a000ed3d4b9e472a83ff413e4de5d0f5>:0 
>   at Neo4j.Driver.Internal.RuntimeHelper..cctor () <0x1eceda0 + 0x00000> in <c93a7057b815482a9e82ec8a533e517a>:0 
>    --- End of inner exception stack trace ---
>   at Neo4j.Driver.Internal.ConnectionSettings..ctor (Neo4j.Driver.V1.IAuthToken authToken, Neo4j.Driver.Internal.EncryptionManager encryptionManager, System.TimeSpan connectionTimeout, System.Boolean socketKeepAlive, System.Boolean ipv6Enabled, System.String userAgent) <0x1ece968 + 0x00074> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.Internal.ConnectionSettings..ctor (Neo4j.Driver.V1.IAuthToken auth, Neo4j.Driver.V1.Config config) <0x1ec9090 + 0x0006e> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.V1.GraphDatabase.Driver (System.Uri uri, Neo4j.Driver.V1.IAuthToken authToken, Neo4j.Driver.V1.Config config) <0x1ec5338 + 0x00044> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.V1.GraphDatabase.Driver (System.Uri uri, Neo4j.Driver.V1.IAuthToken authToken) <0x1ec4e10 + 0x00012> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.V1.GraphDatabase.Driver (System.String uri, Neo4j.Driver.V1.IAuthToken authToken) <0x1ec44d0 + 0x00018> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at BlazorTest.NeoDB..ctor () [0x00025] in D:\Cloud\Dev\Random\BlazorTest\BlazorTest\Components\NeoDB.cs:32 
>   at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) <0x1936d20 + 0x00030> in <ae27a67421134ebf9282a052b2cd8248>:0 
> --- End of stack trace from previous location where exception was thrown ---
> 
>   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously (System.String assemblyName, System.String methodIdentifier, System.Object targetInstance, System.String argsJson) <0x1e92728 + 0x001c8> in <7184a60a97e641c9941a7f131958b58c>:0 
>   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke (System.String callId, System.String assemblyName, System.String methodIdentifier, System.Int64 dotNetObjectId, System.String argsJson) <0x1e922d8 + 0x00088> in <7184a60a97e641c9941a7f131958b58c>:0 
>   at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription () <0x1ecef00 + 0x00008> in <a000ed3d4b9e472a83ff413e4de5d0f5>:0 
>   at Neo4j.Driver.Internal.RuntimeHelper..cctor () <0x1eceda0 + 0x00000> in <c93a7057b815482a9e82ec8a533e517a>:0 
>    --- End of inner exception stack trace ---
>   at Neo4j.Driver.Internal.ConnectionSettings..ctor (Neo4j.Driver.V1.IAuthToken authToken, Neo4j.Driver.Internal.EncryptionManager encryptionManager, System.TimeSpan connectionTimeout, System.Boolean socketKeepAlive, System.Boolean ipv6Enabled, System.String userAgent) <0x1ece968 + 0x00074> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.Internal.ConnectionSettings..ctor (Neo4j.Driver.V1.IAuthToken auth, Neo4j.Driver.V1.Config config) <0x1ec9090 + 0x0006e> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.V1.GraphDatabase.Driver (System.Uri uri, Neo4j.Driver.V1.IAuthToken authToken, Neo4j.Driver.V1.Config config) <0x1ec5338 + 0x00044> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.V1.GraphDatabase.Driver (System.Uri uri, Neo4j.Driver.V1.IAuthToken authToken) <0x1ec4e10 + 0x00012> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at Neo4j.Driver.V1.GraphDatabase.Driver (System.String uri, Neo4j.Driver.V1.IAuthToken authToken) <0x1ec44d0 + 0x00018> in <c93a7057b815482a9e82ec8a533e517a>:0 
>   at BlazorTest.NeoDB..ctor () [0x00025] in D:\Cloud\Dev\Random\BlazorTest\BlazorTest\Components\NeoDB.cs:32 
>   at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) <0x1936d20 + 0x00030> in <ae27a67421134ebf9282a052b2cd8248>:0 
> --- End of stack trace from previous location where exception was thrown ---
> 
>   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously (System.String assemblyName, System.String methodIdentifier, System.Object targetInstance, System.String argsJson) <0x1e92728 + 0x001c8> in <7184a60a97e641c9941a7f131958b58c>:0 
>   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke (System.String callId, System.String assemblyName, System.String methodIdentifier, System.Int64 dotNetObjectId, System.String argsJson) <0x1e922d8 + 0x00088> in <7184a60a97e641c9941a7f131958b58c>:0 
>     at endInvokeDotNetFromJS (http://localhost:10677/_framework/blazor.webassembly.js:1:26855)
>     at Object.invokeJSFromDotNet (http://localhost:10677/_framework/blazor.webassembly.js:1:26276)
>     at _mono_wasm_invoke_js_marshalled (http://localhost:10677/_framework/wasm/mono.js:1:153331)
>     at wasm-function[1530]:520
>     at wasm-function[754]:19425
>     at wasm-function[754]:18238
>     at wasm-function[754]:18238
>     at wasm-function[754]:18238
>     at wasm-function[754]:18853
>     at wasm-function[754]:18853

Is there any way to get this working, or isn't it possible to fun Neo4j with Blazor at this time? If so, is there any indication whether Neo4j will be or will not be supported by Blazor in the future?

_Copied from original issue: aspnet/Blazor#1549_

**Comment by danroth27** [comment]
This looks like a limitation with the  System.Runtime.InteropServices.RuntimeInformation implementation in mono.wasm. Moving this over to the Mono repo.

**Comment by jsmars** [comment]
Note for others trying to run Neo4j: Setting it up with a Server-hosted Blazor setup and having the driver running on the server works fine, just as it would on most other server setups. Hopefully in the future support will be added for running it directly on the client side too.

**Comment by kjpou1** [comment]
Running the following code:

```

            Console.WriteLine($"OSDescription: {System.Runtime.InteropServices.RuntimeInformation.OSDescription}");
            Console.WriteLine($"FrameworkDescription: {System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription}");
            Console.WriteLine($"IsOSPlatform WebAssembly: {System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))}");
            Console.WriteLine($"OSArchitecture: {System.Runtime.InteropServices.RuntimeInformation.OSArchitecture}");
            Console.WriteLine($"ProcessArchitecture: {System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture}");

```

The output is the following:

```

OSDescription: web
FrameworkDescription: Mono 5.21.0 (master/f973c6d90f1)
IsOSPlatform WebAssembly: True
OSArchitecture: X86
ProcessArchitecture: X86

```

When looking at the [RuntimeHelpers](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.7/Neo4j.Driver/Neo4j.Driver/Internal/Helpers/RuntimeHelper.csl) there is a method:

```

        public static bool IsMono()
        {
            return FrameworkDescription.StartsWith("mono", StringComparison.OrdinalIgnoreCase);
        }

```

With the following comment in the `IsDotnetCore()`:

```

        public static bool IsDotnetCore()
        {
            // there are entries that RuntimeInformation.FrameworkDescription returns null
            // so we will rely on not being IsMono and IsDotnetFramework
            return !IsMono() && !IsDotnetFramework();
        }

```

Not sure what all platforms are supported for *Neo4j database*.  It looks like they may not support `Mono` as a valid system?

**Comment by kjpou1** [comment]
Digging a little deeper it looks like it is throwing the `System.PlatformNotSupportedException` because it is using sockets which we do not support yet.

**Comment by kjpou1** [comment]
o	Through Blazor we can not seem to pinpoint the action error that is thrown.
o	Create a sample Neo4j test program to be run from the mono sdks webassembly package using debug mono wasm.
o	Install neo4j nuget package.
o	Run test program.
o	Different stack trace is produced and more detailed. 

```

Uncaught (in promise) Error: Neo4j.Driver.V1.ServiceUnavailableException: Connection with the server breaks due to IOException: Failed to connect to server 'bolt://localhost:7687/' via IP addresses'[127.0.0.1]' at port '7687'. ---> System.IO.IOException: Failed to connect to server 'bolt://localhost:7687/' via IP addresses'[127.0.0.1]' at port '7687'. ---> System.AggregateException: One or more errors occurred. (Failed to connect to server 'bolt://localhost:7687/' via IP address '127.0.0.1': Protocol option not supported) ---> System.IO.IOException: Failed to connect to server 'bolt://localhost:7687/' via IP address '127.0.0.1': Protocol option not supported ---> System.Net.Sockets.SocketException: Protocol option not supported
	  at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) <0x232fc10 + 0x000a6> in <5a14992f0925432b877fd3fce67045b9>:0

```

o	Signup and install the neo4j server.
o	Create a desktop program for testing and got a connection so it is working.
o	Still getting via webassembly the Protocol option not supported ---> System.Net.Sockets.SocketException: Protocol option not supported

**Comment by kjpou1** [comment]
Closing this for now.  Please re-open if needed.
