### ISSUE TITLE
sgen_new_threads_dont_join_stw_exe flaky

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#11131]
## Steps to Reproduce

1. Submit a PR.

### Current Behavior

Failures, for example:

https://jenkins.mono-project.com/job/test-mono-pull-request-armhf/17122/testReport/junit/MonoTests/test-sgen-regular-ms-conc-simple/sgen_new_threads_dont_join_stw_exe/

### Expected Behavior

Success.

## Stacktrace

None reported.

**Comment by BrzVlad** [comment]
https://github.com/mono/mono/pull/15283
