### ISSUE TITLE
[MacSDK] libtiff build sometimes fails

### ISSUE THREAD

**Issue by alexischr** [mono/mono#11200]
Example: https://jenkins.mono-project.com/job/build-package-osx-mono/job/2018-10/28/consoleText
```
libtool: install: /usr/bin/install -c .libs/libtiff.lai @/external/bockbuild/scratch/tiff-x64.install/Library/Frameworks/Mono.framework/Versions/5.20.0/lib/libtiff.la
install: .libs/libtiff.lai: No such file or directory
```

Either avoid the race with a single-threaded `make -j1` or switch to the project's CMake build process.

**Comment by akoeplinger** [comment]
@alexischr this is pretty painful as it causes frequent fails of the OSX packaging build. If switching to `-j1` really works around the issue then we should do this.

**Comment by lambdageek** [comment]
@akoeplinger is this still an issue?  Can we close it?

**Comment by akoeplinger** [comment]
Yes it is still happening from time to time.

**Comment by akoeplinger** [comment]
Recent example from 6 days ago: https://jenkins.mono-project.com/job/build-package-osx-mono/job/2019-06/110

**Comment by SamMonoRT** [comment]
Closing old issue, will triage if re-opened. @akoeplinger - please reopen if we are still seeing this.
