### ISSUE TITLE
LLVM caching is broken in xamarin-macios/master

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#11212]
From the [build log](https://jenkins.internalx.com/blue/organizations/jenkins/macios/detail/master/142/pipeline/35):

```
curl --location --silent --show-error "http://xamjenkinsartifact.blob.core.windows.net/mono-sdks/llvm-llvm64-fc854b8ec5873d294b80afa3e6cf6a88c5c48886-Darwin.tar.gz" | tar -xvzf - -C /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/sdks/out/llvm-llvm64/
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make[3]: *** [/Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/sdks/out/llvm-llvm64/.stamp-download] Error 1
```

which makes sense, given that:

```
$ curl -I "http://xamjenkinsartifact.blob.core.windows.net/mono-sdks/llvm-llvm64-fc854b8ec5873d294b80afa3e6cf6a88c5c48886-Darwin.tar.gz"
HTTP/1.1 404 The specified blob does not exist.
```

## Steps to Reproduce

1. Build xamarin-macios from master.
2. Review build log to see that llvm was built, not downloaded.

### Current Behavior

llvm is built

### Expected Behavior

llvm should be downloaded.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Comment by marek-safar** [comment]
@rolfbjarne is this happening with 2018-08 PR too?

**Comment by rolfbjarne** [comment]
This is working now in xamarin-macios/master.
