### ISSUE TITLE
Type.GetType doesn't return type for full type name in upper case

### ISSUE THREAD

**Issue by MaximLipnin** [mono/mono#11269]
## Steps to Reproduce

Type.GetType takes type full name in upper case and should ignore case.

```c#
using System;
using System.Reflection;

namespace test
{
    public class MainClass
    {
        public static void Main(string[] args)
        {
            string typeName = typeof(MyNamespace1.MynAmespace2.Foo<int>).FullName.ToUpper();
            Type type = Type.GetType(typeName, throwOnError: false, ignoreCase: true);
            Console.WriteLine(type);        
        }
    }

    namespace MyNamespace1
    {
        namespace MynAmespace2
        {
            public class Foo<T> { }
        }
    }
}
```

Seems that possible reason is that `PUBLICKEYTOKEN` substring in type full name ```"TEST.MYNAMESPACE1.MYNAMESPACE2.FOO`1[[SYSTEM.INT32, MSCORLIB, VERSION=4.0.0.0, CULTURE=NEUTRAL, PUBLICKEYTOKEN=B77A5C561934E089]]";``` starts from upper `P`.
At least for `pUBLICKEYTOKEN` it works.

### Current Behavior
Empty output
### Expected Behavior
```
test.MyNamespace1.MynAmespace2.Foo`1[System.Int32]
```
## On which platforms did you notice this

[ ] macOS
[X] Linux
[X] Windows

**Version Used**:

5.16.0 or the latest master

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by lambdageek** [comment]
N.B. we have at least 2 (maybe it's 3 or 4 - I can't remember now) assembly-qualified type name parsers: at least one in managed and at least one in native that are reached by various means.  So this will need to get fixed up at least twice.

**Comment by akoeplinger** [comment]
I wasn't able to repro this on OSX or in a Linux container with the repo mounted from the OSX host so I assume the file system case sensitivity plays a role? On CI it also didn't show up on Windows and OSX.

**Comment by MaximLipnin** [comment]
As for Windows I have a repro for Mono 5.16 and no repro for latest master.

**Comment by MaximLipnin** [comment]
Also there is a repro on Ubuntu 16.04 with the latest master d0069a948d89b5e3705a9d3d8a94a79be073c2cf
