### ISSUE TITLE
Reference equality problem with empty arrays

### ISSUE THREAD

**Issue by josesalvador** [mono/mono#11311]
## Steps to Reproduce

1.- Execute the TestCase
2.- Second assert should not fail

```
using NUnit.Framework;
using System;
using System.Collections.Generic;

namespace arrays_equality_tests
{
    public class Foo
    {
        private int[] anIntArray = new int[0];
        public int[] AnIntArray => anIntArray;

        public void AddIntArray(int[] value)
        {
            List<int> ints = new List<int>(this.anIntArray);
            ints.AddRange(value);
            this.anIntArray = ints.ToArray();
        }
    }

    [TestFixture()]
    public class Test
    {
        [Test()]
        public void TestCase()
        {
            var one = new Foo();
            var two = new Foo();
            Assert.That(one.AnIntArray != two.AnIntArray);

            one.AddIntArray(new int[0]);
            two.AddIntArray(new int[0]);
            Assert.That(one.AnIntArray != two.AnIntArray);
        }
    }
}
```

### Current Behavior

Test shows an array equality for distinct references

### Expected Behavior

Array's references should be distinct

## On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:    xenial

Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:29:10 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)

**Comment by EgorBo** [comment]
empty List<T>.ToArray() returns same Array.Empty object so the last assert fails. Nor sure if it's a bug or feature. Mono uses .NET Core sources for List<> and the test cases also fails there.

**Comment by josesalvador** [comment]
I don't pretend compare array with == else its instance references and I think they should be distinct.

I mean, in the test I put above the first assert is true. Why not is the second assert too?? The only difference was an adding operation on array...

**Comment by marek-safar** [comment]
This is by design. You get different behaviour because in the second case there is internal optimization which converts an empty array into single static value.

@EgorBo it would be useful submitting corefx PR which removed the empty array from list completely and just use Array.Empty
