### ISSUE TITLE
cert-sync behaviour depends on filename extension?

### ISSUE THREAD

**Issue by annekebr** [mono/mono#11316]
It seems to me that the cert-sync command changes its behaviour depending on the filename extension of the argument (certificate bundle). If I use .crt  the mono Trust store will contain only the input certificate files. In the case of using a  .pem filename (with the same content) the input certificate bundle will be added to the Trust store, while all other certificates will remain.

Am I mistaken in this case or did I observe this behaviour correctly?
In the case that I'm correct, I would be glad to hand in a pull request to clarify the docs.

**Comment by marek-safar** [comment]
@spouliot do you remember any details around this?

**Comment by spouliot** [comment]
@marek-safar no, `cert-sync` was written by @directhex (a few years back but well after the other tools I wrote)

**Comment by directhex** [comment]
There's no logic in cert-sync.cs which could result in this. The X509 handling methods only ever see a `Stream`, and file extension is entirely ignored (although the file needs to be PEM format, with `-----BEGIN CERTIFICATE-----` stanzas)

**Comment by akoeplinger** [comment]
Looks like the question was addressed, thank you.
