### ISSUE TITLE
mcs's behavior in tuple deconstruction differs from csc's

### ISSUE THREAD

**Issue by suzusime** [mono/mono#11334]
## Steps to Reproduce
```cs
using System;
 
public class Test
{
	public static void Main()
	{
		int a = 1;
		int b = 2;

		(a, b) = (b, a);
        
		Console.WriteLine($"a:{a} b:{b}");
	}
}
```

### Current Behavior
`a:2 b:2`

### Expected Behavior
`a:2 b:1`

- cf. https://github.com/dotnet/roslyn/blob/master/docs/features/deconstruction.md

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:
5.21.0 and 5.16.0

**Comment by EgorBo** [comment]
Seems like `mcs` issue, works fine with `csc`.
