### ISSUE TITLE
[wasm] Figure out linux build/packaging

### ISSUE THREAD

**Issue by kumpera** [mono/mono#11354]
We should figure out our linux build/packaging story.

An user reported that the AOT compiler from our zip file failed for them with: 
```
And if it can be useful, I'm getting this on Ubuntu 16.04: 
`2018-10-24T19:24:19.4274221Z   /tmp/mono-wasm-aa670c98cbe/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen: /lib32/libm.so.6: version 'GLIBC_2.27' not found (required by /tmp/mono-wasm-aa670c98cbe/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen)
```

We should figure out which flavor/versions to support (if at all) and what needs to be done for that.
Actually doing the work can be left for later.

**Comment by directhex** [comment]
OK.

Requirements definition:

* What does building "the thing we want to ship" require, above and beyond what a normal Linux build would require?
* How wide a support matrix would you like? e.g. should this be available only on a limited set of distributions or host CPU architectures? Would someone on a Raspberry Pi want to be able to use this?
* What would a user running `apt-get install mono-wasm` expect to be added to their system? I took a look at one of the .zip files CI is creating, and there were a LOT of different things in there - Windows cross-compiled executables, header files, etc. Presumably a lot of that is unwanted cruft.
* Do we want to ship this as part of our stable release cadence, or only from git master?

**Comment by jeromelaban** [comment]
I’ll add some context to why I’d need this. For now, Linux is the only target that is functional from the Wasm mono packager. 

Windows is produced, but it’s not in a useable state (missing dependencies) and macOS binaries do not seem to be generated.

At the moment, I’m trying to setup a CI that uses those Linux binaries on azure DevOps, for which the hosted agents only provide Ubuntu 16.04, but the glibc version is too low for the mono binaries to be used.

**Comment by directhex** [comment]
@jeromelaban just tell me how it should look, and I can bang rocks together until it happens. I don't really have any solid grounding in wasm, so I don't know what users would expect a package to contain.

**Comment by jeromelaban** [comment]
@directhex feature-wise, the current wasm `packager.exe` is providing what I need. Aside from the fact that the packager is using ninja, but @kumpera said that it would ultimately be changed to use msbuild.

That aside, the only problem for linux is this: 
```
2018-11-06T13:57:49.1267791Z   MONO_PATH=./linker-out /tmp/mono-wasm-a682a3b2b63/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen   --aot=llvmonly,asmonly,no-opt,static,direct-icalls,llvm-outfile=./mscorlib.dll.bc ./linker-out/mscorlib.dll
2018-11-06T13:57:49.1268739Z   /tmp/mono-wasm-a682a3b2b63/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen: /lib32/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/mono-wasm-a682a3b2b63/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen)
2018-11-06T13:57:49.1269260Z   /tmp/mono-wasm-a682a3b2b63/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen: /lib32/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/mono-wasm-a682a3b2b63/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen)
```

from this build: https://uno-platform.visualstudio.com/Uno%20Platform/_build/results?buildId=1254&view=logs

If there were the ability to lower the version of the glibc, or statically link it (if that's even possible), that'd ease up the whole process.

**Comment by directhex** [comment]
I mean, that's because that job runs on Ubuntu 18.04. I don't remember which package @kumpera wanted which wasn't in 16.04 (or was too old in 16.04)
