### ISSUE TITLE
Fully support custom modifiers

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11395]
We have very spotty support for this old CLR feature which used to be used by Managed C++ only. Only recently C# 7.3 took a dependency on it which uncovered several issues in our implementation.

## Runtime support
- [x] Pass all CoreCLR tests
	- [x] https://github.com/mono/mono/issues/11350
- [x] Pass all Roslyn tests
	- [x] https://github.com/mono/mono/issues/10782
	- [x] https://github.com/mono/mono/issues/10565
	- [x] https://github.com/mono/mono/issues/10564
	- [x] #12422
	- [x] https://github.com/mono/mono/issues/10945
	- [x] #6936
- [ ] Fix runtime limitations
   - [ ] arrays of types with custom modifiers #13203 

## BCL support
- [ ] System.Reflection
	- [ ] https://github.com/mono/mono/issues/11320

## Tooling support
- [x] ikdasm
   - [x] https://github.com/mono/mono/issues/12973
- [x] ilasm
- [x] monodis (optional)

**Comment by jaredpar** [comment]
Note: this was also taken advantage of in C# 7.2 for `ref readonly` returns and `in` parameters which appear in a virtual method or delegate. Example:

``` csharp
public virtual void M(in DateTime dt)
```

This will generate a `modreq[IsReadOnly]` on the parameter `dt`. If you remove `virtual` the `modreq` will not be generated.

**Comment by lambdageek** [comment]
There are, in general, a few classes of bugs represented here:

* Incorrect virtual calls even when the vtable is correct (#12422)
* Possibly incorrect vtable layout (#11350)
* A couple of Roslyn infrastructure bugs (#10564/#10565) - when I extract them into standalone tests, they appear to pass.
* SRE.Run doesn't seem to bake custom mods (#11320)
* Tooling (#12973)

I think these are roughly in the order of difficulty/importance.  The first two seem the most important.  

I'm going to work on #12422
