### ISSUE TITLE
.NET Standard 2.1 support

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11430]
Umbrella ticket tracking work on full .NET Standard 2.1 support. The changes and enhancements to the standard have started landing to dotnet/standard master but the .NET Standard 2.1 has not been finalized.

Most of the missing APIs will show up automatically as we progress on [importing CoreFX code](#6845).

The planning document is available at https://github.com/dotnet/standard/tree/master/docs/planning/netstandard-2.1 

## Namespaces with significant differences on desktop (net_4_x)
- [x] System.Reflection
- [x] System.Reflection.Emit
- [x] System.Drawing
- [x] System.IO
- [x] System.IO.Compression with Brotli #11431
- [x] System.Security.Cryptography
- [x] System.Net

## Mobile profiles changes
- [x] System.Xml.Serialization
- [x] System.Drawing convertors
- [x] DbProviderFactories
- [x] ECDiffieHellman

## Runtime required changes
- [ ] https://github.com/mono/mono/issues/8397

The announcement is available at https://blogs.msdn.microsoft.com/dotnet/2018/11/05/announcing-net-standard-2-1/

**Comment by marek-safar** [comment]
Status check https://gist.github.com/marek-safar/acc256181fa4ef5a74f3c36d4c2a783c

**Comment by marek-safar** [comment]
Status check https://gist.githubusercontent.com/marek-safar/b322a00f68f45e2d154a8d3cc9b32745/raw/e56378308a16665281b334a7bd7f377ae490832c/gistfile1.txt

**Comment by danielmeza** [comment]
Hi, I wish to know the state of this, where I can find info about the release or integration?

**Comment by marek-safar** [comment]
Unfortunately .NET 2.1 is still moving target but our goal is to have it available fully in Mono 6.4 which aligns with dev16.3.

**Comment by danielmeza** [comment]
Si we have this on the 16.3 preview right now?

**Comment by borgdylan** [comment]
What about IAsyncEnumerable that is also in NS 2.1?

**Comment by danielmeza** [comment]
Currently in android it work but the project still use by default the 7.3 version o c#, so do yo need to edit the .csproj file and put the version manually to 8.0 or to latest.

**Comment by aaronfranke** [comment]
What is the status of this? How do you use .NET Standard 2.1 with Mono? This comment on this issue indicates that you can't: https://github.com/dotnet/standard/issues/1689#issuecomment-579550027

**Comment by rvalitov** [comment]
I have the same issue that it seems 2.1 is still not supported. 
@aaronfranke did you got an answer to your question somehow after 2 years have passed? Were you able to use 2.1?
