### ISSUE TITLE
iconify

### ISSUE THREAD

**Issue by sjkrypa** [mono/mono#11457]
## Steps to Reproduce

1. Override some box (for example EventBox)
2. Set it to the TitleBar
3. Try to iconify via tray icon

### Current Behavior
Actually you cannot iconify via clicking by tray icon.

### Expected Behavior
Iconifying and deiconifying is ok

## On which platforms did you notice this

[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
Please include sample code with the repro
