### ISSUE TITLE
System.Drawing in Blazor/Wasm

### ISSUE THREAD

**Issue by JornPalsenbarg** [mono/mono#11461]
Is there going to be any support for System.Drawing in the future? It would seem that this would be possible since it is already supported by Mono.

<img width="636" alt="screenshot 2018-10-30 at 16 14 28" src="https://user-images.githubusercontent.com/13984474/47728667-13faaf80-dc5f-11e8-8b43-09182987feb6.png">

**Comment by kjpou1** [comment]
There are no plans for supporting `System.Drawing` but Blazor has Canvas support here: https://github.com/BlazorExtensions/Canvas.

WebAssembly really only has access to the javascript API and what is delivered in the browser.  Right now that would be via `Canvas` and/or `WebGL`.  I think I saw somewhere a mention about SDL as well.

**Comment by marek-safar** [comment]
We are going to support the only netstandard subset of System.Drawing which are just general purpose types
