### ISSUE TITLE
Threading: implement MONO_ENTER_NO_SAFEPOINTS/MONO_EXIT_NO_SAFEPOINTS

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#11465]
# Summary #

Let's add a scope that causes a runtime assertion if the thread attempt to cooperatively suspend while in that region, or if it attempts to switch to GC Safe mode.

# Motivation #

We often have places in the code where we need to do something to a managed object while in GC Unsafe where we "know" that a cooperative safepoint won't occur.  For example we may temporarily take a raw pointer to a MonoObject for a valuetype that has no reference types in it and memcpy it somewhere.  We could take a gchandle to pin the object, memcpy and then unpin.  Or we could wrap the entire block in a `MONO_ENTER_NO_SAFEPOINTS`/`MONO_EXIT_NO_SAFEPOINTS` pair which would assert at runtime if we later added a call to `mono_object_new` in that block (or anything similar).

# Implementation idea #

Take a bit in the thread state machine.  add transitions that set the bit only from `RUNNING` state.  Disallow transitions from `RUNNING`+`UNINTERRUPTIBLE` to `BLOCKING`.  Transition from `RUNNING`+`UNINTERRUPTIBLE` to `ASYNC_SUSPEND_REQUESTED`+`UNINTERRUPTIBLE` (ie - suspend initiator asks victim thread to suspsend - and the victim is expected to suspend next time it reaches a safepoint) is allowed.  but polling from `ASYNC_SUSPEND_REQUESTED`+`UNINTERRUPTIBLE` would assert.

**Tricky bit** don't let an `UNINTERRUPTIBLE` thread become the GC Initiator, either! so if the current thread is going to stop the world, it better not be uninterruptible.

(This only makes sense if we're not using preemptive suspend - so define the macros as a no-op if preemptive suspend is enabled.)

**Comment by jaykrell** [comment]
nits: NO_SUSPEND  is shorter. Not sure if banning a verb or describing a region is preferred.
END will be `}` if C++.

**Comment by lambdageek** [comment]
or maybe even `MONO_BEGIN_NO_SAFEPOINTS`/`MONO_END_NO_SAFEPOINTS` to be completely direct about it.

I think it's similar to `ENTER_CRITICAL_REGION`, but the mechanisms are different - critical regions are about async suspension - we're guaranteeing that the thread won't be interrupted by the suspend machinery.   `NO_SAFEPOINTS` is about cooperative suspension.

There are different reasons also, I think, to protect against one or the other.  (in particular, I think NO_SAFEPOINTS regions would be much more frequent).

**Comment by lambdageek** [comment]
Done. See #11476
