### ISSUE TITLE
[XA] [2018-10] Failure in ExtractBytesMembersTests.ToByteArray_FromStringTests

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#11477]
The test 

```System.Numerics.Tests.ExtractBytesMembersTests.System.Numerics.Tests.ExtractBytesMembersTests.ToByteArray_FromStringTests```

seems to be failing on the 2018-10 XA integration build.

The failure can be seen below:

https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4440/testReport/Test%20collection%20for%20System.Numerics.Tests/ExtractBytesMembersTests/System_Numerics_Tests_ExtractBytesMembersTests_ToByteArray_FromStringTests___Debug/

with the error:

```
System.InvalidOperationException : No data found for System.Numerics.Tests.ExtractBytesMembersTests.ToByteArray_FromStringTests
```

https://github.com/xamarin/xamarin-android/pull/2253

**Comment by marek-safar** [comment]
This is actually issue in CoreFX test suite

**Comment by marek-safar** [comment]
Should be fixed on Mono
