### ISSUE TITLE
IronPython 2.7.9 strange issue on mono 5.16

### ISSUE THREAD

**Issue by equiclouds** [mono/mono#11489]
I installed ironpython 2.7.9 on rasperberry pi, and code bellow:

```python
class test:
    def extend(self, a, *b):
        return a, b
def main():
    c1 = test().extend({},{})
    for i in range(0,100):
        c2 = test().extend({},{})
        if c1!=c2:
            print(i,c1,c2)
            return
main()
```

Randomly, after some times, the extend function b paramters will be valued with test() object...

```
root@raspberrypi:/tmp/tmp# ipy test.ipy 
(39, ({}, ({},)), ({}, <__main__.test instance at 0x000000000000006C>))
root@raspberrypi:/tmp/tmp# ipy test.ipy 
(82, ({}, ({},)), ({}, <__main__.test instance at 0x000000000000006C>))
```

The result above means after call test().extend fuctions 39 or 82 times, the test instance will pass to *b paremeter. While the code return None on X86 Devices.

Is mono compile differences for ARM and X86 caused the issue?

**Comment by marek-safar** [comment]
What ARM is this and could you reproduce the issue it with previous Mono versions?

**Comment by equiclouds** [comment]
@marek-safar My platform is RASPBERRY PI DESKTOP run on RASPBERRY PI 3B+:

```
Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
```

I haven't test the code on previous Mono versions yet.

**Comment by equiclouds** [comment]
@marek-safar My platform is RASPBERRY PI DESKTOP run on RASPBERRY PI 3B+, and I can't reproduce the issue it with mono 5.12.

**Comment by lewurm** [comment]
@equiclouds with what mono version do you see this problem? could you try `export MONO_ENV_OPTIONS='-O=-aot'` and run your example code again?

**Comment by lewurm** [comment]
I can reproduce with current master on armv7 (armhf). suggested workaround from my previous comment does _not_ work. will investigate

**Comment by lewurm** [comment]
As a workaround: `MONO_ENV_OPTIONS=--interp` works, but it's significant slower.

**Comment by lewurm** [comment]
```patch
diff --git a/mono/mini/mini-arm.c b/mono/mini/mini-arm.c
index b44ecd7..9f98aa7 100644
--- a/mono/mini/mini-arm.c
+++ b/mono/mini/mini-arm.c
@@ -1814,6 +1814,8 @@ mono_arch_tailcall_supported (MonoCompile *cfg, MonoMethodSignature *caller_sig,
        g_assert (caller_sig);
        g_assert (callee_sig);
 
+       return FALSE;
+
        CallInfo *caller_info = get_call_info (NULL, caller_sig);
        CallInfo *callee_info = get_call_info (NULL, callee_sig);
```
makes it work. @jaykrell this looks like a problem around tail calls.

**Comment by marek-safar** [comment]
@jaykrell are you aware of this regression?

/cc @luhenry

**Comment by jaykrell** [comment]
I  reproduced the problem, on armhf, on a builder.

**Comment by lewurm** [comment]
@jaykrell run with `-v`, you will see that right before the crash some method will be compiled. I assume IronPython rewrites the AST or something during execution.

**Comment by equiclouds** [comment]
The issue is still in mono 5.18
