### ISSUE TITLE
mono-5.16 release contains object files in release tar

### ISSUE THREAD

**Issue by RealDolos** [mono/mono#11501]
The official release tar for the stable channel at
https://download.mono-project.com/sources/mono/mono-5.16.0.179.tar.bz2
contains in `external/corefx/src/Native/Unix/System.Native/` various object and other build files that have no business being included.
The presence of the object files (along with the `.dirstamp`) makes the build system not actually rebuild the files, but instead it will try to use and link the object files from the tar.

```text
$ tar tjf mono-5.16.0.179.tar.bz2 | grep -e '.*\.o$'
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_random.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networking.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_memory.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_maphardwaretype.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_random.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networking.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_memory.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_maphardwaretype.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_io.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_errno.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networkstatistics.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_tcpstate.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_errno.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networkstatistics.o
mono-5.16.0.179/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_tcpstate.o
```

This is most probably a simple mistake by whoever packaged the release tar, but there is also an ever so slight possibility of something malicious going on.

Since I am building mono on a platform not compatible to the object files (the tarred object files are `ELF 64-bit LSB relocatable, x86-64`), `make` eventually rightfully failed with the linker complaining about incompatible object files.

**Comment by directhex** [comment]
Yeah, so here's the problem:
```
EXTRA_DIST= \
[...]
        external                \
```

`make dist` is including the world from external, but `make` in `mono.native` causes object files to be created in `../../external/corefx/src/Native/Unix/System.Native/`

We can add some housekeeping to `dist-hook` to purge all `.o` files and `.libs` directories from `external/` (we already do `.exe`/`.dll`) to try and guard against this.
