### ISSUE TITLE
[gensources]: Use platform-specific sources for tests

### ISSUE THREAD

**Issue by baulig** [mono/mono#11515]
When computing the source lists for BCL tests, we currently don't use the platform-specific `.sources` files.

For instance, if you have `win32_net_4_x_corlib_test.dll.sources` containing

```
#include corlib_test.dll.sources
```

and `win32_net_4_x_corlib_test.dll.exclude.sources` containing

```
#include testing_aot_full_corlib_test.dll.exclude.sources
Mono/NativePlatformTest.cs
```

as well as `testing_aot_full_corlib_test.dll.exclude.sources` containing (among others) `Mono/NativePlatformTest.cs`, that test is still compiled on Windows.

This is because in `tests.make` we are using [this](https://github.com/mono/mono/blob/master/mcs/build/tests.make#L272) code to generate the sources, which effectively comes down to this:

```
test_sourcefile = $(PROFILE)_$(ASSEMBLY:$(ASSEMBLY_EXT)=_test.dll.sources)

$(test_response_preprocessed): $(test_sourcefile) $(wildcard *_test.dll.sources) $(wildcard *_test.dll.exclude.sources)
	$(GENSOURCES) --basedir:./Test --strict --platformsdir:$(topdir)/build "$@" "$(test_sourcefile)" "$(test_sourcefile_excludes)"
```

Whereas `library.make` uses the following:

```
PROFILE_sources = $(filter-out %test.dll.exclude.sources %test.dll.sources, $(wildcard *.sources))

sourcefile = $(depsdir)/$(PROFILE_PLATFORM)_$(PROFILE)_$(LIBRARY_SUBDIR)_$(LIBRARY).sources
$(sourcefile): $(PROFILE_sources) $(PROFILE_excludes) $(depsdir)/.stamp
	$(GENSOURCES) --strict --platformsdir:$(topdir)/build "$@" "$(LIBRARY)" "$(PROFILE_PLATFORM)" "$(PROFILE)"
```

**Comment by EgorBo** [comment]
I'll try to fix it in https://github.com/mono/mono/pull/11508/files (it currently fixes only nunit)

**Comment by baulig** [comment]
Fixed with https://github.com/mono/mono/pull/11967
