### ISSUE TITLE
Interpreter performance optimizations

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11531]
The summary ticket with the interpreter optimizations we have done or planning to do. At this point, we are interesting low-hanging fruit like optimizations only. Anything more advanced will be moved to future milestones.

## Implemented

- ldtoken + GetTypeFromHandle pair #10660
- Method execution start optimization #11328
- Optimize cpobj, ldobj and box #11167
- Optimize static field access #11053
- More type resolution to happend during transform #11778
- Inlining of small methods #11735
- Virtual call optimization #12554
- stinarg opcode removal #13038 
- type check/cast optimization #13225
- intrinsics
- .ctor inlining #15665
- local and constant propagation
- constant propagation
- basic superinstructions, mainly for local operations

## Proposed

- [ ] call path optimizations

**Comment by SamMonoRT** [comment]
Seems like all optimizations identified above are done. Closing this issue.
