### ISSUE TITLE
Module's corefx CustomAttributes test fails 

### ISSUE THREAD

**Issue by MaximLipnin** [mono/mono#11569]
[CustomAttributes](https://github.com/mono/corefx/blob/master/src/System.Reflection/tests/ModuleTests.cs#L38) corefx test fails on the latest mono master.
It fails even method body is commented out.

The error is `System.BadImageFormatException : Cannot box IsByRefLike type 'System.ReadOnlySpan`1'`

**Comment by marek-safar** [comment]
@vargaz could you fix the JIT handling for this case

**Comment by vargaz** [comment]
What needs to be fixed here ? Span is a stack-only type so it cannot be boxed.

Which test fails exactly ?

**Comment by marek-safar** [comment]
This requires https://github.com/mono/mono/pull/11577 to land first and then uncommenting the test

**Comment by MaximLipnin** [comment]
Closing it because the test was re-enabled (https://github.com/mono/mono/pull/11665#issuecomment-439712207)
