### ISSUE TITLE
Trying to install mono with Apache on Windows

### ISSUE THREAD

**Issue by crpeters2000** [mono/mono#11578]
## Steps to Reproduce

1. I installed Apache and Mono
2. Guide says to include mod_mono in the Apache httpd.conf file
3. I am unable to locate mod_mono anywhere Any help would be greatly appreciated!

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ x] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
Please visit https://github.com/mono/mod_mono

**Comment by crpeters2000** [comment]
Those instructions would be helpful if I were trying to do it on Linux.  I
am trying to use it on Windows with Apache though and I don't see anything
there related to that.
