### ISSUE TITLE
Setup BenchmarkDotNet to run managed micro benchmarks

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11574]
We would like to setup BenchmarkDotNet in the way it's not affected by any code changes except Mono runtime.

**Comment by alexanderkyte** [comment]
Work done on this by https://github.com/mono/mono/pull/9833

**Comment by alexanderkyte** [comment]
Between https://github.com/mono/mono/pull/9833 and the microbenchmarks in https://github.com/mono/mono/issues/13104 , I am pretty sure that this has been completely implemented. May be worth automating.
