### ISSUE TITLE
No Facades on testing_aot_full 

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#11584]
The testing_aot_full profile cannot run code compiled for .netstandard 2.0 because it does not contain a Facades directory. 

```NO_FACADES_PROFILE := $(filter monodroid_tools wasm_tools testing_aot_full testing_aot_hybrid binary_reference_assemblies xbuild_12 xbuild_14, $(PROFILE))```

I need this to change so that I can run BenchmarkDotNet on testing_aot_full.

**Comment by marek-safar** [comment]
We could add it but I am not sure it's a good idea at all. You should run BenchmarkDotNet on standalone Mono not testing mobile profile

**Comment by alexanderkyte** [comment]
BenchmarkDotNet produces a .cs that is compiled and is run by the client mono being benchmarked.

This standalone mono would run: https://gist.github.com/alexanderkyte/83c3424d4d0be38f1da9125640faae16

Which includes

```
using BenchmarkDotNet;
using BenchmarkDotNet.Characteristics;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Extensions;
using BenchmarkDotNet.Helpers;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Engines;
using BenchmarkDotNet.Validators;
using BenchmarkDebianShootout;
```

So it's necessary that we be able to load BDN on the mono that's being benchmarked.

**Comment by luhenry** [comment]
@marek-safar could you please go through the reasoning why adding `netstandard.dll` to `testing_aot_full` is a bad idea?

**Comment by marek-safar** [comment]
We treat these profiles as internal testing profiles, they are not compatible with .NET Desktop or .NET Core. Running desktop applications on them is just asking for more troubles later.

**Comment by alexanderkyte** [comment]
I have created the addition of NS2.0. Debugging it's use now, but I think it should be good to go. I'll reference this from the PR.

**Comment by alexanderkyte** [comment]
@marek-safar we're using them as proxies of XM+AOT/XI. If they diverge from XI, they're not doing their purpose. They should be able to run NS2.0 apps on them, to test and debug that such apps can run on XI.

**Comment by marek-safar** [comment]
@alexanderkyte no, they are testing profiles and diverge from XI otherwise we'd not call them testing profiles. When we need to test XI we use the normal monotouch profile to run the test as part of SDKs.

**Comment by akoeplinger** [comment]
@marek-safar still, the reason why we added the `testing_*` profiles back then was to have a somewhat close approximation of the mobile profiles that we could run in CI, there should be very little difference between a monotouch and a testing_aot_full BCL.

Whether running benchmarks on those profiles provides a good approximation of how a real app might behave with all the other Xamarin pieces wired in is a different question :)

**Comment by alexanderkyte** [comment]
This motivation for this was fixed by the merging of https://github.com/mono/mono/pull/9833
