### ISSUE TITLE
Deleting "mono-master.zip" 

### ISSUE THREAD

**Issue by gvanem** [mono/mono#11598]
This is not a PR for Mono itself. But after downloading `mono-master.zip` from Github (and unpacking it) I have big troubles deleting it! 
Seems the Windows Defender has 2 threads working forever on the .zip-file for some strange reason:
```
C:\Program Files (x86)\Mono\bin>handle mono-master

Nthandle v4.1 - Handle viewer
Copyright (C) 1997-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

MsMpEng.exe        pid: 170880 type: File          5C08: F:\gv\tmp\mono-master.zip
MsMpEng.exe        pid: 170880 type: File          5ECC: F:\gv\tmp\mono-master.zip
4NT.EXE            pid: 201480 type: File           B74: F:\gv\tmp\mono-master.zip
```

Because of this, my `4NT.EXE` shell will hang waiting for `MsMpEng.exe` to finish. It's been handing for 1 hour now. Same issue with `cmd.exe`. When trying to delete it in `explorer.exe`, it seems to work. But it won't get deleted.  `MsMpEng.exe` keep it open.

What could I do?

**Comment by gvanem** [comment]
I fixed it by using [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer), looking at the handles in `MsMpEng.exe` (**Ctrl-L**) and closing the handles for `mono-master.zip`. That helped and `mono-master.zip` disappeared. Strange....

**Comment by akoeplinger** [comment]
For what it's worth the .zip file from GitHub is useless anyway since it doesn't contain the git submodules so you wouldn't be able to use it :)

**Comment by gvanem** [comment]
I wasn't able to build Mono either. So I deleted every trace of it.
