### ISSUE TITLE
Outdated package avaibility relying on Centos for Fedora repository 

### ISSUE THREAD

**Issue by Ricky-Tigg** [mono/mono#11614]
Enhancement request:

## Steps to Reproduce

$ LANG=C rpm -qfi `which  mono`
Name        : mono-core
Version     : 4.8.0
Release     : 12.fc28
Architecture: x86_64
(...)
Source RPM  : mono-4.8.0-12.fc28.src.rpm
Build Date  : Wed Sep 20 23:33:08 2017
(...)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.mono-project.com
(...)

### Current results
- _Version_ available to _Fedora_ repository is outdated – _4.8.0 (22 Feb 2017)_ –. Since then no less than **twelve** stable versions have been released –last: _5.16.0 (08 Oct 2018)_ –. At [Mono](https://www.mono-project.com/download/stable/#download-lin-fedora) website it is stated 
> Note: we're using the CentOS repositories on Fedora.

While CentOS does observe Red Hat's release protocol in that matter.
- _Source RPM_ is from _x.28.src.rpm_; then it does not match current repository:
```
$ LANG=C dnf -v repolist --enabled fedora
(...)
Repo-id      : fedora
Repo-name    : Fedora 29 - x86_64
(...)
Repo-pkgs    : 58215
Repo-size    : 69 G
```
- _URL_ mention is obsolete: it illustrates an insecure protocol – _HTTP_ – while page is served using a secure protocol – _TLS v1.2_ protocol for _HTTPS_ connections –, 

### Expected results
- _Version_ to be as close as possible to last release;
- _Source RPM_ to match current system repository;
- _URL_ mention to match current protocol in use.

## On which platforms did you notice this
[ Fedora 29] Linux

**Version Used**: _Mono JIT compiler version 4.8.0 (Stable 4.8.0.520/8f6d0f6_

**Comment by directhex** [comment]
RPM installation got a spring clean last week.
