### ISSUE TITLE
Memory leak in System.Diagnostics.Process

### ISSUE THREAD

**Issue by HeikoWeiss** [mono/mono#11615]
## Steps to Reproduce

1. Start a Process with redirecting it's output
2. Wait till process end
3. loop for many hours

### Current Behavior

Memory leak

### Expected Behavior

no memory leak
## On which platforms did you notice this

[ ] macOS
[ X] Linux
[ ] Windows

**Version Used**: mono-5.21.0.413.tar.bz2

**Comment by HeikoWeiss** [comment]
[Program.cs.txt](https://github.com/mono/mono/files/2561675/Program.cs.txt)

**Comment by HeikoWeiss** [comment]
After more test I have to reopen this issue.
There IS a memory leak, starting a process.

**Comment by HeikoWeiss** [comment]
[Program.cs.txt](https://github.com/mono/mono/files/2606843/Program.cs.txt)

Try this sample code.

The memory consumption increases. Slow but steady.

**Comment by HeikoWeiss** [comment]
Redirecting output is not necessary, just starting process causes memory leak.

**Comment by HeikoWeiss** [comment]
just tried this versions: 
5.11.0.345 --> "slow" memory leak
5.21.0.513 --> "fast" memory leak !!! 
the newer version is worse !!!

**Comment by marek-safar** [comment]
I can reproduce the issue

**Comment by EgorBo** [comment]
Memory usage even in a smaller code that tries to start some garbage-value process grows extremely fast (unlike .NET Core where memory usage is stable).
```csharp
      int iCount = 0;
      while(true) 
      {

        if( ++iCount % 100 == 0 ) {
          GC.Collect();
          GC.WaitForPendingFinalizers();
          GC.Collect();
          iCount = 0;
          Console.Write( "." );
        }

        try  {
                Process process = new Process();
                process.StartInfo.UseShellExecute = false;
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.RedirectStandardError = true;
                process.StartInfo.CreateNoWindow = true;
                process.StartInfo.FileName = "ffffoooo";
                process.StartInfo.WorkingDirectory = ".";
                process.Start();
                process.Close();
        }
        catch {}
      }
```
Managed profiler doesn't show anything suspicious (on the managed size) I tried to track the leak on the native side but with no luck 🙂  

<img width="1342" alt="screen shot 2019-01-09 at 1 51 06 am" src="https://user-images.githubusercontent.com/523221/50863868-3b819d00-13b1-11e9-8ceb-8014aaae90a8.png">
(snapshot, current state of an app that actually uses >100mb of memory)

**Comment by HeikoWeiss** [comment]
I can confirm the memory leak is fixed with the fix in g_find_program_in_path().
