### ISSUE TITLE
Compilation artifacts (accidentally?) packaged into official source tarball leads to failed builds on non x86_64 platforms

### ISSUE THREAD

**Issue by DarkCaster** [mono/mono#11619]
It seems there are some incorrect (?) build artifacts packaged into official mono-core source tarball at https://download.mono-project.com/sources/mono/mono-5.16.0.179.tar.bz2

Artifacts (object files, libtool files) located at "external/corefx/src/Native/Unix/System.Native" directory. 

### Current Behavior

Presence of these files causes build failure on non x86_64 platforms with the following error (arm64 build, for example):

[ 1066s] Making all in metadata
[ 1066s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/mono-5.16.0.179/mono/metadata'
[ 1066s]   CCLD     libmono-system-native.la
[ 1067s] collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
[ 1067s] compilation terminated.
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_errno.o' is incompatible with aarch64 output
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_io.o' is incompatible with aarch64 output
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_maphardwaretype.o' is incompatible with aarch64 output
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_memory.o' is incompatible with aarch64 output
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networking.o' is incompatible with aarch64 output
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networkstatistics.o' is incompatible with aarch64 output
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_tcpstate.o' is incompatible with aarch64 output
[ 1067s] /usr/lib64/gcc/aarch64-suse-linux/8/../../../../aarch64-suse-linux/bin/ld: i386:x86-64 architecture of input file '../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_random.o' is incompatible with aarch64 output
[ 1067s] make[3]: *** [Makefile:1596: libmono-system-native.la] Error 1
[ 1067s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/mono-5.16.0.179/mono/metadata'
[ 1067s] make[2]: *** [Makefile:474: all-recursive] Error 1
[ 1067s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/mono-5.16.0.179/mono'
[ 1067s] make[1]: *** [Makefile:595: all-recursive] Error 1
[ 1067s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/mono-5.16.0.179'
[ 1067s] make: *** [Makefile:504: all] Error 2
[ 1067s] error: Bad exit status from /var/tmp/rpm-tmp.GLecak (%build)

## On which platforms did you notice this

[ ] macOS
[X ] Linux, non x86_64
[ ] Windows

**Comment by marek-safar** [comment]
@directhex did we fix that already?

**Comment by directhex** [comment]
@marek-safar 7184737beed16f3091e8ee75cb0e11bd73d872fe and 791ec7faea86b4cfb53d22b92d3da431d931cdbc

**Comment by luhenry** [comment]
Duplicates of https://github.com/mono/mono/issues/11501
