### ISSUE TITLE
sentry uploading sometimes fails with "Crash reporting version mismatch"

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#11654]
### Current Behavior

E.g. https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/16368,
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/16366/,
https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/16358/

```
23:03:44 	-- Success Parsing /Users/builder/jenkins/workspace/test-mono-pull-request-i386-osx/mono/unit-tests/callspec.exe: 5557C3C2-AD4A-4DBD-AC26-0DEC55A30C5B
23:03:56 
23:03:56 Unhandled Exception:
23:03:56 System.Exception: Crash reporting version mismatch
23:03:56   at UploadToSentry.Uploader.Upload (System.String filePath, System.String os_tag, UploadToSentry.Dsn url) [0x00083] in <809c3ef58f654f3395b716a708d4f925>:0 
23:03:56   at UploadToSentry.Uploader.Main (System.String[] args) [0x00083] in <809c3ef58f654f3395b716a708d4f925>:0 
23:03:56 [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Crash reporting version mismatch
23:03:56   at UploadToSentry.Uploader.Upload (System.String filePath, System.String os_tag, UploadToSentry.Dsn url) [0x00083] in <809c3ef58f654f3395b716a708d4f925>:0 
23:03:56   at UploadToSentry.Uploader.Main (System.String[] args) [0x00083] in <809c3ef58f654f3395b716a708d4f925>:0 
23:03:56 
```

### Expected Behavior

No exception.

## On which platforms did you notice this

[ x ] macOS
[ ] Linux
[ ] Windows

**Version Used**: master

**Comment by alexanderkyte** [comment]
Wow. That's really surprising. That version string should always be in the file. I wonder if that's an empty file it's trying to upload. It says it parsed it alright too.

**Comment by alexanderkyte** [comment]
https://github.com/mono/mono/pull/11655/files

**Comment by alexanderkyte** [comment]
The mono_crash files in question are 0.0.1, which we confirmed means it's from the wrong/an old mono.

**Comment by akoeplinger** [comment]
Added a workaround with https://github.com/mono/mono/commit/49a5af74f70f8ae33b023434bab9962163602c83.
