### ISSUE TITLE
[ios] reintroduce DISABLE_POLICY_EVIDENCE properly

### ISSUE THREAD

**Issue by lewurm** [mono/mono#11651]
PR https://github.com/mono/mono/pull/11582 removed `DISABLE_POLICY_EVIDENCE`. While the original change dates a while back, I _think_ the intended idea was to also remove the relevant icalls in order to minimize footprint. This will require some BCL changes as well.

Any thoughts @marek-safar @spouliot @rolfbjarne ?

**Comment by marek-safar** [comment]
I think we always link out the icalls from managed side so the original code was not that incorrect

**Comment by lewurm** [comment]
@marek-safar let me make sure if I understand that correctly: If managed code doesn't call any of those icalls, the _native_ linker will remove that code, right? (There are some tests in `corlib` that are using it, but the regular user will not be penalized by that size-wise).

If so, we can leave it as is and close this issue.

**Comment by marek-safar** [comment]
I think that's correct
