### ISSUE TITLE
Replace MONOMAC/XAMCORE defines in the codebase

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#11679]
We have several #if conditions in the BCL that are using symbols which we don't define in Mono, for example `MONOMAC`, `XAMCORE_4_0`, `XAMCORE_2_0`. Those will need to be fixed as part of the SDKs effort to mantain the same behavior.

/cc @luhenry

**Comment by luhenry** [comment]
@akoeplinger is that the case that these are defined in the products but not in Mono, or that they are defined nowhere?

**Comment by akoeplinger** [comment]
@luhenry they should be defined in the products but I haven't checked which combinations are used for what.

**Comment by luhenry** [comment]
It doesn't seem to be passed to `external/mono` when building the BCL, so it sounds safe to assume we can remove it. @spouliot @rolfbjarne @chamons could you please confirm?

**Comment by marek-safar** [comment]
We will remove the defines from CFNetworkHandler.cs

**Comment by rolfbjarne** [comment]
* `MONOMAC`: might be removed, or replaced with `XAMMAC` and/or `XAMMAC_4_5`. Each case should be considered individually.
* `XAMCORE_2_0`: remove, it's always defined (which means you can remove the code where `XAMCORE_2_0` is not defined)
* `XAMCORE_4_0`: Do *not* remove: it marks code that we can/must change once we can do a breaking API change.

**Comment by chamons** [comment]
Feel free to CC on PRs that make MONOMAC changes and I'll happily review.

**Comment by akoeplinger** [comment]
All traces of these symbols were removed, closing.
