### ISSUE TITLE
Report session ID in crash reports

### ISSUE THREAD

**Issue by slluis** [mono/mono#11699]
It would be useful to include a session ID in crash reports. We need this in VSMac to correlate crash reports with other telemetry data.

A session ID is just a string that VSMac would somehow provide (up to you to decide how), and should be included somewhere in the crash report metadata.

**Comment by akoeplinger** [comment]
Is this a duplicate of https://github.com/mono/mono/issues/11579 ?

**Comment by slluis** [comment]
Yes it is a duplicate.
