### ISSUE TITLE
typeof(anything).MakeByRefType().IsByRefLike should return False

### ISSUE THREAD

**Issue by MaximLipnin** [mono/mono#11693]
## Steps to Reproduce

```
using System;
class Program
{
	static void Main()
	{
		Type t = typeof(Span<int>).MakeByRefType();
		Console.WriteLine(t.IsByRefLike);
	}
}
```

### Current Behavior

The output is 
`True`

### Expected Behavior

The output should be
`False`

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

The latest Mono master

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by lambdageek** [comment]
Any by ref type should be not `IsByRefLike`.  .NET Core prints `False`,`False` for the example below.

```csharp
using System;
class Program
{
	static void Main()
	{
		Type t = typeof(Span<int>).MakeByRefType();
		Console.WriteLine(t.IsByRefLike);
		Type t2 = typeof(int).MakeByRefType();
		Console.WriteLine(t2.IsByRefLike);
	}
}
```

**Comment by borgdylan** [comment]
Shouldn't by ref pointers by by ref like (as the name "by ref like" suggests)?

**Comment by lambdageek** [comment]
@borgdylan ¯\\\_(ツ)\_/¯

Mono doesn't have much flexbility here: got to match what .NET Core returns.

**Comment by borgdylan** [comment]
Thanks for the clarification. I have my own compiler which treets byrefs and spans and other byref likes as banned from being put anywhere off the stack. Is that ok?

**Comment by lambdageek** [comment]
@borgdylan Yea, the motivation for `IsByRefLike` is to make it possible to define `ref struct` types like `Span<T>` that - exactly as you say - can only be on the stack.

Although Mono has had `Span<T>` implemented for a while, we haven't enforced - in the runtime - the prohibition against boxing a `Span<T>` until fairly recently (see #11111 - in particular there's a list of uses of reflike types that are considered by the runtime to be erroneous).

As far as I know, we don't have any optimizations in Mono's JIT for `IsByRefLike` types yet.

**Comment by borgdylan** [comment]
Thanks for your comment. I need to error out when a user tries to do ```$object$span``` or similar as that syntax for my compiler triggers boxing.
