### ISSUE TITLE
Add what's needed in Mono Archive for XI/XM/XA

### ISSUE THREAD

**Issue by luhenry** [mono/mono#11719]
The progress is tracked at #11397

| Item | Profiles | Extra Requirements |
| ----- | -------- | --------------------- | 
| `Mono.Posix` | `monodroid` | | 
| `Mono.Data.Sqlite` | `monodroid` | | 
| `Mono.Cecil` `Mono.Cecil.Mdb` | `monotouch_tools` `monodroid_tools` | Rename to `Xamarin.Android.Cecil` and `Xamarin.Android.Cecil.Mdb` for `monodroid_tools` |
| `Mono.Linker` | `monodroid_tools` `monotouch_tools` | We only compile `monolinker.exe`, we need to compile a library as well |
| `Mono.Options` | `monodroid_tools` `monotouch_tools` | |
| `mono-api-info` `mono-api-html` `Microsoft.DotNet.GenAPI` | `monodroid_tools` `monotouch_tools` | | 
|~~`netstandard`~~ | ~~`monodroid` `monotouch` `monotouch_tv` `monotouch_watch`~~ | ~~Compile against `Mono.Android` and `Xamarin.{iOS,TVOS,WatchOS}` reference assemblies [1]~~ |
| ~~`System.Drawing.Primitives`~~ | ~~`monodroid` `monotouch` `monotouch_tv` `monotouch_watch`~~ | ~~Compile against `Mono.Android` and `Xamarin.{iOS,TVOS,WatchOS}` reference assemblies [1]~~ |
| `System.Net.Http` | `monotouch` `monotouch_tv` `monotouch_watch` | Compile against `Xamarin.{iOS,TVOS,WatchOS}` reference assemblies [1] |
| `pdb2mdb` | `monodroid_tools` | |
| `ikvm` | `monotouch_tools` | |
| ~~`KnownColor.cs` `KnownColors.cs` `KnownColorConverter.cs` `SystemColor.cs` `Point.cs` `Pointf.cs` `Rectangle.cs` `Rectanglef.cs` `Size.cs` `Sizef.cs`~~ | ~~`monotouch` `monotouch_tv` `monotouch_watch`~~ | ~~We only want to pack the sources, not the binaries~~ |
| `xunit.*.dll` | `monodroid` `monotouch` `monotouch_tv` `monotouch_watch` | |
 | `dSYM` bundles for mono libraries | `monotouch` +  `xammac` | |

[1] The `Mono.Android` and `Xamarin.{iOS,TVOS,WatchOS}` reference assemblies needs to be added to `mono/mono`

/cc @rolfbjarne @jonpryor

**Comment by akoeplinger** [comment]
Regarding KnownColor.cs etc, I assume this is needed in source code form because the types are compiled into OpenTK.dll/Xamarin.iOS.dll?

**Comment by rolfbjarne** [comment]
> Regarding KnownColor.cs etc, I assume this is needed in source code form because the types are compiled into OpenTK-1.0.dll/Xamarin.iOS.dll?

Correct.

**Comment by akoeplinger** [comment]
Maybe we should look at creating a new assembly where we put these types and type-forward them there?

**Comment by marek-safar** [comment]
Yes, that's the plan but that's not clear from this issue.

**Comment by akoeplinger** [comment]
Closing this since we've added everything necessary.
