### ISSUE TITLE
Cannot load .NET Standard 2.0 class library built by VS2017 with mono/wasm.

### ISSUE THREAD

**Issue by zwcloud** [mono/mono#11732]
## Steps to Reproduce

1. Create a .NET Standard 2.0 class library project in VS2017. (project is attached)
2. Download the latest mono/wasm sdk
3. Use the dll built by VS2017 in a static website with mono/wasm
4. See the error when the page loaded.

Note: the error will not occur if the class library is built with mcs. (See build.ps1)

### Current Behavior

Error occurred:  
> Uncaught (in promise) Error: Could not find class: MonoWasmDemo:Program

The .NET Standard class library project containing downloaded mono/wasm files: 
[MonoWasmDemo.zip](https://github.com/mono/mono/files/2592562/MonoWasmDemo.zip)

### Expected Behavior

No error occurs and the console prints "Hello from C#!".

## On which platforms did you notice this

Windows 10, Chrome Version 70.0.3538.102

**Version Used**:
mono-wasm:
https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/processDownloadRequest/1476/ubuntu-1804-amd64/sdks/wasm/mono-wasm-f30ce1cbcee.zip

## Stacktrace

```text
mono.js:7877 Loaded: MonoWasmDemo.dll
mono.js:7877 Loaded: System.Net.Http.dll
mono.js:7877 Loaded: Mono.Security.dll
mono.js:7877 Loaded: WebAssembly.Bindings.dll
mono.js:7877 Loaded: WebAssembly.Net.Http.dll
mono.js:7877 Loaded: System.Core.dll
mono.js:7877 Loaded: System.dll
mono.js:7877 Loaded: System.Xml.dll
mono.js:7877 Loaded: mscorlib.dll
mono.js:7883 initializing mono runtime
mono.js:7809 >>mono_wasm_runtime_ready
mono.js:8546 Uncaught (in promise) Error: Could not find class: MonoWasmDemo:Program
    at Object.resolve_method_fqn (mono.js:8546)
    at Object.call_static_method (mono.js:8555)
    at runtime.js:11
    at mono.js:7900
```

**Comment by kjpou1** [comment]
@zwcloud First thank you for the great example.

It looks like there are some libraries missing from the loaded assemblies list if you are publishing for .NET Standard 2.0.

Did you run the packager.exe on the `MonoWasmDemo.dll` that was output in the `.\bin\debug\netstandard2.0\`? 

I did the following as outline from [sample doc](https://github.com/mono/mono/blob/master/sdks/wasm/docs/getting-started/sample.md#create-sample).

In step  `4. Package and publish sample` there is a utility program delivered in the zip file that you can run to assemble all the assemblies needed. 

```

%WASM_SDK%packager.exe --copy=ifnewer --out=.\publish --asset=index.html .\bin\debug\netstandard2.0\MonoWasmDemo.dll

```

The `%WASM_SDK%` points to the .zip file download.  Instructions can be found [here](https://github.com/mono/mono/blob/master/sdks/wasm/docs/getting-started/obtain-wasm-sdk.md)

I just set:

```

set WASM_SDK=c:\projects\mono\sdks\

```

Once you have that you can serve it from the `publish` directory.

Try that and let us know how it goes.

**Comment by zwcloud** [comment]
@kjpou1 
> It looks like there are some libraries missing from the loaded assemblies list if you are publishing for .NET Standard 2.0.

But if I build the project as an .NET Framework 4.6.1 class library, the output MonoWasmDemo.dll is able to be loaded. So I thought it also works for a regular .NET Standard assembly.

> In step 4. Package and publish sample there is a utility program delivered in the zip file that you can run to assemble all the assemblies needed.

This is the step I neglected. The assembly processed by packager.exe can now be loaded by mono-wasm! Thank you very much!

------
But I want to make a point that mono-wasm should be able to load the .NET Standard assembly built by Visual Studio directly without any extra assembling procedure. I think this compatibility guarantee is essential for easier integration with current .NET environment.

**Comment by kjpou1** [comment]
We are working on tooling.

Thanks for letting us know that it worked and your feedback.
