### ISSUE TITLE
Latest Xamarin.iOS's System.Threading.Tasks.Extensions facade causes build to fail

### ISSUE THREAD

**Issue by dalexsoto** [mono/mono#11731]
_From @juepiezhongren on November 16, 2018 10:11_

no such problem for previous xamarin.ios sdk and vs4mac

MTOUCH : error MT2002: Failed to resolve "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder" reference from "System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"

VS mac : 
Xamarin.iOS
Version: 12.2.1.10 (Visual Studio Community)
Hash: f2a05edd
Branch: d15-9
Build date: 2018-10-31 18:55:57-0400

_Copied from original issue: xamarin/xamarin-macios#5135_

**Comment by dalexsoto** [comment]
Hello, thank you for your feedback!

 For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your **full** version information.

 To get full build logs just set the log verbosity to diagnostic at the following locations:

 - On Visual Studio for Mac: Preferences > Projects > Build
 - On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

 On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

 Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

 The easiest way to get exact version information:

 - On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
 - On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

 Then copy/paste the version information (you can use the "Copy Information" button).

 We look forward to hearing from you!

**Comment by dalexsoto** [comment]
_From @Wenfengcheng on November 17, 2018 2:13_

@juepiezhongren same error as you, this is most likely caused by the package [Microsoft.AspNetCore.SignalR.Client](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/1.1.0-preview3-35497) that relies on [System.Threading.Tasks.Extensions](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/), there are two workarounds that can temporarily solve the build problem:
1. Removing  _Microsoft.AspNetCore.SignalR.Client_ from your project if this package is not required
2. Rolling back to the previous mono version means you need to lower your Xamarin.iOS version. For example 12.1.0.5. You can download it from [here](https://download.visualstudio.microsoft.com/download/pr/87c37317-519f-41cc-851d-9690784bb375/2c67088e33a30432a729a6a512916c89/xamarin.ios-12.1.0.15.pkg)

**Comment by dalexsoto** [comment]
_From @juepiezhongren on November 17, 2018 2:35_

@Wenfengcheng yes, i guess u r write, we do use signalr core, thx!
大神，给个qq号吧，我的是261533144

**Comment by dalexsoto** [comment]
_From @brendanzagaeski on November 17, 2018 7:56_

While checking whether this error also affects Xamarin.Android, I noticed that it is possible to stop the build error by moving the facade assembly away from its install location:

*C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\ReferenceAssemblies\\Microsoft\\Framework\\Xamarin.iOS\\v1.0\\Facades\\System.Threading.Tasks.Extensions.dll*

That said, I suspect this might not be a complete workaround because apps might then hit a related error at run time: https://github.com/xamarin/xamarin-macios/issues/5133.

### Steps to Reproduce

Attempt to build the attached project in the "Debug|iPhoneSimulator" configuration in Visual Studio on Windows.

### Expected Behavior

The project builds without error.

### Actual Behavior

The build fails with an error and a warning:

`error MT2002: Failed to resolve "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder" reference from "System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"`

`warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.`

In contrast, building directly on macOS succeeds but produces two warnings:

<details>

`warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.`

`MTOUCH : warning MT0109: The assembly 'System.Threading.Tasks.Extensions.dll' was loaded from a different path than the provided path (provided path: /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Facades/System.Threading.Tasks.Extensions.dll, actual path: /Users/macuser/src/SignalRTaskExtensions/packages/System.Threading.Tasks.Extensions.4.5.0/lib/netstandard2.0/System.Threading.Tasks.Extensions.dll).`

</details>

### Environment

<details>

#### Windows 10

Visual Studio 2017 version 15.9

#### macOS 10.13

Mono Framework MDK version 5.12.0.309 (2018-02/39d89a335c8)
Microsoft (R) Build Engine version 15.7.224.30163 (xplat-master/d375bb6e Thu Sep 27 07:16:13 EDT 2018)

</details>

### Build Logs

[DiagnosticBuildOutput.zip](https://github.com/xamarin/xamarin-macios/files/2591522/DiagnosticBuildOutput.zip)

### Example Project (If Possible)

[TestCase5135.zip](https://github.com/xamarin/xamarin-macios/files/2591524/TestCase5135.zip)

**Comment by marek-safar** [comment]
This will require 2018-04 fix only and we will probably have to disable parts of the implementation to compile it

**Comment by BenBtg** [comment]
Are there any known workarounds for this issue? This is currently a blocking issue for me.

**Comment by dalexsoto** [comment]
> Is there an equivalent workaround for VS for Mac?

Yes, you can delete the following file `/Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.10/lib/mono/Xamarin.iOS/Facades/System.Threading.Tasks.Extensions.dll`

**Comment by Wenfengcheng** [comment]
@dalexsoto Does this work for windows?

**Comment by marek-safar** [comment]
Closing as the issue was fixed on Mono side

**Comment by sAntoni** [comment]
help for me [Xamarin.iOS project fails to build after update to System.Reactive 4.1.0.0](https://github.com/xamarin/xamarin-macios/issues/4629#issuecomment-414165149)
need to change only iOS csproj

**Comment by xperiandri** [comment]
@EgorBo this does not work in VS 2019 Preview 3.0 although works in 15.9.4
