### ISSUE TITLE
mono 5.16.0.179 with ca-certificates

### ISSUE THREAD

**Issue by Abinayasandhiya** [mono/mono#11759]
Hi,

We are using mono - 5.16.0.179 on our Linux RedHat 6 and 7 machine.

As our user request,  this mono installation should be complete with ca-certificate.
[To be honest we are new to this tool].

So we have downloaded the source of mono from : https://download.mono-project.com/sources/mono/ 
then we did normal installation.

But then I got to know that our user requirement is to install mono with ca-certificate.

So I did further search and i could see the help from : https://www.mono-project.com/download/stable/#download-lin [ On verify installation part ].

we have execute "mozroots --import –sync" and could get the certificates under $HOME/.config/.mono [ even i want to know that this is the correct certificate or not ].

Now my question is, how this certificate can be provide the host in centrally [ on specific folder / custom PATH ] to user and how can we enable mono to identify the certificate path correctly.

Is there any command/option can be use on mono build step.

Can anyone help me on this.

Regards,
Abinaya

**Comment by Abinayasandhiya** [comment]
This is very urgent case, can we get any idea here.

We could get certificate by execute "cert-sync /etc/pki/tls/certs/ca-bundle.crt" under /usr/share/.mono.

But we need to provide this some other PATH other than /usr/share or $HOME/.config/.mono.

**Comment by directhex** [comment]
The certificate paths are hardcoded here: https://github.com/mono/mono/blob/master/mcs/class/Mono.Security/Mono.Security.X509/X509StoreManager.cs#L59-L81

I filed an issue asking for this feature already, in https://github.com/mono/mono/issues/6388
