### ISSUE TITLE
[wasm] Memory leak caused by small byte[] array allocations

### ISSUE THREAD

**Issue by kjpou1** [mono/mono#11766]
Intermittent memory leak in the WASM runtime.

EMSCRIPTEN emulates `mmap` and `munmap` memory using a large contiguous byte array.  One of the problems is the `munmap` implementation does not support support `unmmapp’ing` parts of allocations.  https://github.com/kripken/emscripten/blob/incoming/src/library_syscall.js#L454

The memory allocation for smaller objects like byte[] arrays depends on the unmapping functionality which causes leaks by not de-allocating these objects correctly.

**Comment by vargaz** [comment]
Work in progress:
https://github.com/vargaz/mono/tree/fix-wasm-mmap
Crashes in some test suites for some reason.

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/11772

**Comment by kjpou1** [comment]
fixed via https://github.com/mono/mono/pull/11840
