### ISSUE TITLE
CI pipeline fails to run tests after build

### ISSUE THREAD

**Issue by NattyNarwhal** [mono/mono#11799]
First run that exhibits behaviour: https://jenkins.mono-project.com/job/test-mono-mainline-community/label=aix-ppc64/3908/

## Steps to Reproduce

1. Begin a build of Mono on Jenkins (auto/manual)

### Current Behavior

CI fails to run any tests.

### Expected Behavior

CI test suite should begin.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] AIX

**Version Used**: master

## Stacktrace

```
*** end(1069): make: Passed
MONO_LLVMONLY= ./scripts/ci/run-test-net_4_x.sh
/opt/freeware/bin/bash: ./scripts/ci/run-test-net_4_x.sh: A file or directory in the path name does not exist.
Makefile:1028: recipe for target 'check-ci' failed
make: *** [check-ci] Error 127
Build step 'Execute shell' marked build as failure
Set build name.
New build name is '94d4055'
```

**Comment by NattyNarwhal** [comment]
Actually looks like *all* tests are broken by this.

**Comment by akoeplinger** [comment]
This should be fixed.
