### ISSUE TITLE
Memory leads in python-language-server

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11805]
On my Mac, if I open a small Python file in VS Code, I find that the mono-sgen64 process takes increasing amounts of memory until my Mac grinds to an entire halt (even the spinner doesn’t spin at times). The process seems to be related to the Python language server, but when I searched for info on it it seems like it is a garbage collector process? Anyway, I am trying to understand why it grows like this and whether it is a bug in the language server or something else. Any tips or insights that might be useful?

## Steps to Reproduce

1. clone https://github.com/Microsoft/python-language-server 
2. open src/PLS.sln
3. Navigate the solution Visual Studio Code (with the C# extension installed) until mono-sgen64 consumes CPU

### Current Behavior

mono-sgen64 process takes increasing amounts of memory until my Mac grinds to an entire halt

### Expected Behavior

Restricted memory consumption

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.16.0.209 (2018-06/709b46e3338 Wed Oct 31 09:14:07 EDT 2018)

**Comment by BrzVlad** [comment]
This looks like omnisharp/msbuild issue. Let's close it for now
