### ISSUE TITLE
AM_EXTRA_RECURSIVE_TARGETS requires AM 1.13; breaks CentOS6

### ISSUE THREAD

**Issue by directhex** [mono/mono#11809]
```
05:27:41 DEBUG: configure.ac:23: error: possibly undefined macro: AM_EXTRA_RECURSIVE_TARGETS
05:27:41 DEBUG:       If this token and others are legitimate, please use m4_pattern_allow.
05:27:41 DEBUG:       See the Autoconf documentation.
05:27:41 DEBUG: **Error**: autoconf failed.
```

Introduced in 5d2525527ef8 and c4087410008d

There's already special-case handling for stuff like this in our AM_INIT_AUTOMAKE

**Comment by akoeplinger** [comment]
Do you think we need to find a workaround or is it fine to bump our requirements to AM1.13 ?

**Comment by directhex** [comment]
Automake 1.13 is problematic for RHEL/CentOS 6.

We should have discussions before dropping 6. 8 is in beta though.
