### ISSUE TITLE
Windows i386 CI very high failure rate lately.

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#11898]
Windows i386 CI is failing very frequently lately.
In  pinvoke2.exe.
Here is a reduced case that fails.
It is heap corruption -- well, mismatched allocate vs. free  -- different heap.
If you run under a debugger, it breaks in due to the heap corruption detected in free.

```
using System;
using System.Runtime.InteropServices;

public class Tests
{
	[DllImport ("libtest", EntryPoint="mono_test_asany")]
	public static extern int mono_test_asany ([MarshalAs (UnmanagedType.AsAny)] object o, int what);

	public static int Main (string[] args)
	{
		mono_test_asany ("ABC", 2);
		return 0;
	}
}
```

**Comment by jaykrell** [comment]
There is a second problem sometimes in this test:

cant resolve internal call to "Tests/T2::MyClone" (tested without signature also)

Your mono runtime and class libraries are out of sync.
The out of sync library is: C:\s2\mono\mono\tests\pinvoke2.exe

When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "Tests/T2::MyClone" (tested without signature also)

Your mono runtime and class libraries are out of sync.
The out of sync library is: C:\s2\mono\mono\tests\pinvoke2.exe

When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
test_0_x86_single_double_struct_ret failed: got 1, expected 0
Regression tests: 97 ran, 1 failed in Tests

that I haven't debugged yet, which really might be what is failing in CI.

The allocater/free problem shows as a break into the debugger with free.
Perhaps outside of a debugger it is tolerated and no failure.

**Comment by jaykrell** [comment]
Actually that is maybe just expected, not an error. I need to look more.

**Comment by jaykrell** [comment]
Yes, indeed.

**Comment by jaykrell** [comment]
So I think the problem is the allocate/free mismatch, fixed by https://github.com/mono/mono/pull/11899. Let's see how CI fairs with that.

**Comment by jaykrell** [comment]
I can get gcc to agree with msvc by unioning in a long long.
mono still  doesn't agree, because  !pinvoke.
The mono code looks correct, if the signature is pinvoke.

**Comment by jaykrell** [comment]
Workaround gcc  ABI by changing struct to union.

**Comment by lateralusX** [comment]
Any clue why this has started to happen, looks like the source hasn't changed for a while? On CI we run the msvc build mono runtime and should load the msvc build version of libtest.dll so maybe  CI has started to pick up gcc build of the test library instead or started to install new version of gcc introducing this change?

**Comment by lateralusX** [comment]
Looked at Windows master CI builds but didn't find failures related to pinvoke2.exe failures? PR says frequent failures on i386, only for PR builds?

**Comment by lateralusX** [comment]
@jaykrell guess this can be closed?

**Comment by jaykrell** [comment]
Yes.
