### ISSUE TITLE
Do not truncate 64bit MERP hashes to 32bits

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11924]
This is follow up issue on https://github.com/mono/mono/commit/4e34b6a8fd4304e5ab0042d5a275c85853c5fa1b which didn't fix all occurrences. We also need to address the same pattern in XML output at https://github.com/mono/mono/blob/master/mono/utils/mono-merp.c#L494

/cc @leculver

**Comment by jaykrell** [comment]
Good  catch.

**Comment by alexanderkyte** [comment]
This has been fixed on master with https://github.com/mono/mono/pull/11864 and in the backports of the https://github.com/mono/mono/pull/12037 class
