### ISSUE TITLE
Translation of signal names in MERP

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11920]
Why does Mono translate meaningful signal names here (SIGSEGV, SIGABRT, SIGILL, etc) into opaque string hex values at https://github.com/mono/mono/blob/cf7b6cfd5f3bc653a4a139c299fb2d6006d49fa9/mono/utils/mono-merp.c#L184 ?  Is there a particular reason we do that?  Wouldn’t it be better to just report the signal name?

/cc @leculver

**Comment by alexanderkyte** [comment]
If you'd like me to duplicate this information with the names of strings, or add symbolication logic in the sentry uploader, please reopen this issue.
