### ISSUE TITLE
Mono crash JSON files are not always well-formed

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11922]
Some of crash .JSON files are not well-formed JSON (missing “,” etc).  

Example:
```
    "SystemManufacturer:" : "apple",
    "SystemModel:" : "MacBookPro11,4"           <- missing , at end of line?
    "EventType:" : "AppleAppCrash"
```

Can we also add JSON reader test for the output we generate to ensure we don't regress?

**Comment by alexanderkyte** [comment]
This is now covered by https://github.com/mono/mono/blob/master/mono/tests/merp-json-valid.cs

**Comment by alexanderkyte** [comment]
Further, added tests will also validate these json files.
