### ISSUE TITLE
Can't get mono 5.16 installation working on Ubuntu 17.10

### ISSUE THREAD

**Issue by breezytm** [mono/mono#11953]
I have exhausted my research but I can not for the life of me understand why I can not install mono 5.16. It constantly return dependency errors. 

I have followed the guide 

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
sudo apt install mono-complete

`Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mono-complete : Depends: mono-runtime (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-runtime-sgen (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-llvm-support (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: libmono-2.0-1 (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-utils (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-devel (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-mcs (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-roslyn (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-csharp-shell (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-4.0-gac (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: mono-4.0-service (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: monodoc-base (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: monodoc-manual (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: libmono-cil-dev (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
                 Depends: referenceassemblies-pcl but it is not going to be installed
                 Depends: msbuild but it is not going to be installed
                 Depends: ca-certificates-mono (= 5.16.0.220-0xamarin4+ubuntu1804b1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

What am I doing wrong? I did this this as well just in case
sudo add-apt-repository "deb https://download.mono-project.com/repo/ubuntu $(lsb_release -sc) universe"

**Comment by marek-safar** [comment]
@directhex could you help here?

**Comment by mageshmagi00** [comment]
same issue, Any one can fix it?

**Comment by breezytm** [comment]
I was able to fix it. Not sure if the issue I was experiencing is the same as yours but below is the root cause and solution. 

Root cause: I received this error message because I had a previous version of mono installed. Even after uninstalling it, there were a few packages left behind. 

`sudo apt-get purge mono-complete`

Solution: I had to remove these leftover packages manually for the installation to work. Do keep in mind, I ended up uninstalling mono version 5.8.127 instead because of issues with some application that I use. Any version later than 5.8 breaks the application. I never attempted 5.16 after I fixed the issue with my system. 

```
dpkg -l | less (list all installed packages)
dpkg -r <package name>   Removes the package from the system.
``` 
Note: Mono packages tends to have mono in the name somewhere like libmono* for example. And it clearly states mono in the description most of the time. Or version section has the mono version number. 

Some application will fail to remove using _dpkg -r_ instead use  _sudo apt-get --purge remove <package_ name>_
Once all packages have been removed. 

I later found out the proper way to remove mono and not experience this issue is to use this command
sudo apt remove --purge --auto-remove mono-complete  I never got to try it. I had already removed everything manually before i found out.

**Comment by directhex** [comment]
Which other repositories do you have enabled? We need the Ubuntu `universe` repo turned on, and in some environments you might only have `main` and `restricted`

**Comment by breezytm** [comment]
`cat /etc/apt/sources.list
#

# deb cdrom:[Ubuntu-Server 17.10 _Artful Aardvark_ - Release amd64 (20171017.1)]/ artful main restricted

# deb cdrom:[Ubuntu-Server 17.10 _Artful Aardvark_ - Release amd64 (20171017.1)]/ artful main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://us.archive.ubuntu.com/ubuntu/ artful main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ artful main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://us.archive.ubuntu.com/ubuntu/ artful-updates main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ artful-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ artful universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ artful universe
deb http://us.archive.ubuntu.com/ubuntu/ artful-updates universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ artful-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://us.archive.ubuntu.com/ubuntu/ artful multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ artful multiverse
deb http://us.archive.ubuntu.com/ubuntu/ artful-updates multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ artful-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ artful-backports main restricted universe multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ artful-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu artful partner
# deb-src http://archive.canonical.com/ubuntu artful partner

deb http://security.ubuntu.com/ubuntu artful-security main restricted
# deb-src http://security.ubuntu.com/ubuntu artful-security main restricted
deb http://security.ubuntu.com/ubuntu artful-security universe
# deb-src http://security.ubuntu.com/ubuntu artful-security universe
deb http://security.ubuntu.com/ubuntu artful-security multiverse
# deb-src http://security.ubuntu.com/ubuntu artful-security multiverse
`

**Comment by directhex** [comment]
OK, that's as expected

It's a bit late to determine why the upgrade failed, now - I need to see how apt reacts to `apt-get install X` on some of the lower-level "will not be installed" packages

**Comment by breezytm** [comment]
Yeah. I know. I think the ideal thing should be an apt-get upgrade for those who already already have an older version. Perhaps if someone already have an older package and trying to installer a newer, it should be flagged and advised the user to do an upgrade or something. I was looking for that upgrade switch but I can not find anything about it. If there is, kindly point me to it.

**Comment by directhex** [comment]
`upgrade` will never work, because it will never alter the dependency chain (i.e. `dist-upgrade` will pull in new packages if needed, `upgrade` will skip any upgrades which add dependencies)

One thing I'm not clear on - you said you had random pieces of Mono 5.8 installed, which blocked the installation. But the first version of Mono we published for Ubuntu 18.04 was 5.10 - so I'm not sure how you had any 5.8 packages at all

**Comment by breezytm** [comment]
No that's my fault. I thought I had upgraded my Ubuntu to 18.04 but I never actually did. I was still on 17.10

**Comment by directhex** [comment]
I'd suggest dropping 17.10 ASAP. https://www.ubuntu.com/about/release-cycle
