### ISSUE TITLE
[XA] [2018-08] GetDrivesValidInfo test is now failing on Android

### ISSUE THREAD

**Issue by pjcollins** [mono/mono#11960]
This appears to be a byproduct of https://github.com/mono/mono/pull/9521. The [GetDrivesValidInfo](https://github.com/mono/mono/blob/master/mcs/class/corlib/Test/System.IO/DriveInfoTest.cs#L90) unit test now fails on Android as not all drives are "ready" on all Android devices.

## Steps to Reproduce

1. Create or load a Xamarin.Android project and drop in the following code:
```c#
var drives = DriveInfo.GetDrives();

foreach (var d in drives)
{
    if (d.DriveType == DriveType.Fixed)
        Console.WriteLine($"\nDrive Name: {d.Name}, IsReady: {d.IsReady}");
}
```

### Current Behavior
Not all fixed drives identified by `System.IO.DriveInfo.GetDrives()` are ready.
```
12-06 10:25:02.507 18065 18065 I mono-stdout: Drive Name: /, IsReady: True
12-06 10:25:02.508 18065 18065 I mono-stdout: Drive Name: /firmware, IsReady: True
12-06 10:25:02.509 18065 18065 I mono-stdout: Drive Name: /persist, IsReady: False
12-06 10:25:02.490 18065 18065 W o.TestDriveInfo: type=1400 audit(0.0:4377): avc: denied { getattr } for path="/persist" dev="mmcblk0p27" ino=2 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:persist_file:s0 tclass=dir permissive=0
12-06 10:25:02.509 18065 18065 I mono-stdout: Drive Name: /dsp, IsReady: True
12-06 10:25:02.509 18065 18065 I mono-stdout: Drive Name: /data, IsReady: True
```

### Expected Behavior
The unit test expects that all drives will be "ready" due to a previous implementation that always returned true.

**Comment by akoeplinger** [comment]
We should ifdef ignore the `IsReady` part of the test on mobile, having drives where not even `Directory.Exists()` is allowed shouldn't happen on desktop.
