### ISSUE TITLE
Race in BTLS/LLVM enablement in MSVC

### ISSUE THREAD

**Issue by directhex** [mono/mono#11961]
`build-init.vcxproj` enables BTLS in MSVC builds of the runtime (i.e. defining `HAVE_BTLS`), by checking whether `cygconfig.h` contains `MONO_ENABLE_BTLS`, and if so, adding an argument `HAVE_BTLS` to `winsetup.bat` which adds `#define HAVE_BTLS=1` to winconfig.h

`cygconfig.h` is created by `winsetup.bat`

Therefore `_CheckEnableBtls` in `msvc/mono.external.targets` will always return false until _after_ winsetup.bat has been called - meaning on a clean git checkout, it will never add `#define HAVE_BTLS=1` to winconfig.h until the _second time_ it is executed.

This causes our Mono builds not to enable BTLS, except in 32-bit SGen (because we build Boehm first, triggering the bad first call on `winsetup.bat`, allowing the SGen call of `winsetup.bat` to succeed).

**Comment by directhex** [comment]
This likely also means we never CI'd BTLS on Windows at any point - because the CI system only runs `winsetup.bat` once per lane, meaning that whilst libmono-btls-shared.dll might exist, the runtime isn't looking for it or using it

**Comment by lateralusX** [comment]
Added fix into PR already in the flight:
https://github.com/mono/mono/pull/11946/commits/bf1ed7a6c75f5910ce83e4b79757b1a3c9ca32cb

**Comment by lateralusX** [comment]
https://github.com/mono/mono/pull/1194 has been merged including fix for this issue.

**Comment by directhex** [comment]
Definitely enabled now, e.g. in https://jenkins.mono-project.com/view/Releases/job/build-package-win-mono/job/master/2301/Azure/

Need to test it
