### ISSUE TITLE
There is no ppa for Ubuntu 18.10

### ISSUE THREAD

**Issue by laichiaheng** [mono/mono#11988]
## Steps to Reproduce

1. Find the ppa on website

### Current Behavior

I can't find the ppa

### Expected Behavior

There is a ppa for Ubuntu 18.10

## On which platforms did you notice this

[ ] Linux

**Version Used**:

Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)

**Comment by directhex** [comment]
There's a huge amount of work involved in adding a repo, so I don't tend to create them for releases with 9-month lifespan - LTS releases only.

**Comment by akoeplinger** [comment]
Looks like the question was answered, please feel free to follow up if something is still unclear.
