### ISSUE TITLE
[bockbuild] bb MacSDK --shell doesn't work

### ISSUE THREAD

**Issue by bratsche** [mono/mono#12007]
## Steps to Reproduce

1. Clone mono
2. `./external/bockbuild/bb MacSDK --shell` as described in the README

### Current Behavior

`(bockbuild error) Bockbuild instance has no attribute 'shell' (AttributeError)`

### Expected Behavior

Expected it to build and give me a shell setup to use the build.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

master branch

**Comment by SamMonoRT** [comment]
Closing old issue, will triage if re-opened.
