### ISSUE TITLE
New F# project in VS for Mac shows intellisense errors

### ISSUE THREAD

**Issue by willsam100** [mono/mono#12006]
## Steps to Reproduce

1. create an F# solution eg Xamarin.Forms app in VS4Mac
2. add a new project eg .NETStandard2.0 project
3. see that the F# file in the new project shows red lines by the editor

### Current Behavior

See that the F# file in the new project shows red lines by the editor. Errors are shown parsing the F# syntax. 
Note the project does compile. 

<img width="476" alt="screen shot 2018-12-11 at 5 37 45 am" src="https://user-images.githubusercontent.com/732506/49752270-bc973700-fd14-11e8-8e10-d1fb32c36322.png">

From the screenshot attached, it would appear that when a new project is created, the syntax parser is using C# as it is expected a `{` after the namespace

### Expected Behavior

No syntax highlighting errors when adding a new project to a solution in VS4Mac

## On which platforms did you notice this

[x ] macOS
[ ] Linux
[ ] Windows

**Version Used**:
```
Visual Studio Community 2017 for Mac
Version 7.7.1 (build 15)
Installation UUID: 8d3712bd-ee56-4387-80b1-d5ddc495dce3
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221
```
## Known work-around

unload the entire solution, and reloading the solution fixes this issue.

**Comment by knocte** [comment]
I think this bug report should be moved to https://github.com/mono/monodevelop/issues

**Comment by willsam100** [comment]
Moved to mono-develop repo: https://github.com/mono/monodevelop/issues/6757
