### ISSUE TITLE
Upgrade runtime msvc projects to VS2017

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#12016]
We talked about getting rid of the VS2015 requirement for the MSVC runtime build. Unity has no objections.

- [ ] Upgrade the .vcxproj's
- [ ] Ship new UCRT runtime redist in the [msi](https://github.com/mono/mono/blob/d5b777ea13e218440dc58ee14ad33be10a86f20d/packaging/Windows/resources/Product.wxs#L56)

**Comment by jaykrell** [comment]
Might be nice to fix the "msvcrt.dll" references too.

```
jaymac1:mono4 jay$ git grep -i msvcrt.dll
data/config.in: <dllmap dll="i:msvcrt.dll" target="@LIBC@" os="!windows"/>
mcs/class/Mono.Posix/Documentation/en/Mono.Unix/UnixMarshal.xml:            runtime C library, <c>MSVCRT.DLL</c> on Win32 and <c>libc</c> on
mcs/class/Mono.Posix/Documentation/en/Mono.Unix/UnixMarshal.xml:            runtime C library, <c>MSVCRT.DLL</c> on Win32 and <c>libc</c> on
mcs/class/Mono.Posix/Documentation/en/Mono.Unix/UnixMarshal.xml:            runtime C library, <c>MSVCRT.DLL</c> on Win32 and <c>libc</c> on
mcs/class/Mono.Posix/Test/Mono.Unix.Native/StdlibTest.cs:               // MSVCRT.DLL doesn't export snprintf(3).
mcs/tests/test-473.cs:  internal const string LIBC = "msvcrt.dll";
mono/metadata/coree.c:/* Called by msvcrt.dll when shutting down. */
mono/tests/Makefile.am:# FIXME depends on msvcrt.dll, and calli
mono/tests/tailcall/coreclr/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:  .method public static pinvokeimpl("msvcrt.dll" cdecl) int32 puts(int8* A_0) il managed preservesig{ }
mono/tests/tailcall/coreclr/JIT/Directed/IL/PInvokeTail/PInvokeTail.il:.method public static pinvokeimpl("msvcrt.dll" cdecl) int32 puts(int8* A_0) il managed preservesig{ }
jaymac1:mono4 jay$ 
```

It isn't simple though.
On desktop and UWP, "apisets" are used, so the C runtime *appears* to be split into several .dlls, which, under the covers, implementation detail, are "hosted" in one dll, whose name can change, w/o breaking the interface.

On older Windows (pre-Windows 10), forwarders are redistributable.

It might be a good to lobby for a change here, and for "ucrtbase.dll" to be a public name.

**Comment by lateralusX** [comment]
https://github.com/mono/mono/pull/17269
