### ISSUE TITLE
Form closes although its DialogResult is manually set to None

### ISSUE THREAD

**Issue by daniel-lerch** [mono/mono#12022]
## Steps to Reproduce

1. Run a Form with `ShowDialog()`
1. Set the AcceptButton's `DialogResult` to any value except `DialogResult.None`
2. Define a click listener for this button to set the Form's `DialogResult` to `DialogResult.None`
3. Run your application and click the button

### Current Behavior

The Form closes.

### Expected Behavior

The Form should stay opened because it's `DialogResult` has been set to `DialogResult.None`.

For reference see [this thread](https://stackoverflow.com/questions/2499644/preventing-a-dialog-from-closing-in-the-buttons-click-event-handler). As far as I could find out, this functionality is implemented by [this method](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Form.cs,9e5ff82765459e00) in the .NET Framework.

## On which platforms did you notice this

Only tested on Linux

**Version Used**:

```
Mono JIT compiler version 5.16.0.220 (tarball Mon Nov 26 17:17:59 UTC 2018)
```

## Example code

```csharp
using System;
using System.Windows.Forms;

namespace WinFormsTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Application.Run(new MainForm());
        }
    }

    class MainForm : Form
    {
        public MainForm()
        {
            Button button1 = new Button() { Text = "Open dialog" };
            button1.Click += (s, e) => new DialogForm().ShowDialog();
            this.Controls.Add(button1);
        }
    }

    class DialogForm : Form
    {
        public DialogForm()
        {
            Button submit = new Button() { Text = "Submit" };
            submit.DialogResult = DialogResult.OK; // Unlike on .NET Framework this line closes the form.
            // It doesn't matter if this.DialogResult is overridden in the event listener.
            submit.Click += (s, e) => this.DialogResult = DialogResult.None;
            this.Controls.Add(submit);
            this.AcceptButton = submit;
        }
    }
}
```

**Comment by abrevet-dev** [comment]
Not reproducible with Mono 6.9.0 On Ubuntu 19.04 and Win10
