### ISSUE TITLE
AOT runtime tries to search disk when using static assemblies

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#12048]
In trying to fix XA startup time, they've found that we search the filesystem for native AOT libs when we're working with bundled assemblies. From their output, it appears that they are hitting this else branch https://github.com/mono/mono/blob/master/mono/mini/aot-runtime.c#L2084 while using bundled assemblies, which means that the earlier lookup

```
		info = (MonoAotFileInfo *)g_hash_table_lookup (static_aot_modules, assembly->aname.name);
```

is failing. This looks like a bug.

@jonpryor may have more info, he brought it to my attention.

**Comment by alexanderkyte** [comment]
https://github.com/mono/mono/blob/01f6a0203b0566dc845eefb453e345f7ede77803/mono/mini/aot-runtime.c#L2436 should be registering it

**Comment by alexanderkyte** [comment]
My wager would be that

```
	aname = (char *)info->assembly_name;
	g_hash_table_insert (static_aot_modules, aname, info);
```

and 

```
		info = (MonoAotFileInfo *)g_hash_table_lookup (static_aot_modules, assembly->aname.name);
```

aren't working because the anames somehow differ, *or*

https://github.com/xamarin/xamarin-android/blob/e6044b0c1f664243d496390b9f7c3263bd4176f8/src/monodroid/jni/dylib-mono.cc#L139

isn't using the prefix like it tries for all of the other mono functions, so XA doesn't find the right mono function

https://github.com/xamarin/xamarin-android/blob/e6044b0c1f664243d496390b9f7c3263bd4176f8/src/monodroid/jni/dylib-mono.cc#L841 here

so 

https://github.com/xamarin/xamarin-android/blob/e6044b0c1f664243d496390b9f7c3263bd4176f8/src/monodroid/jni/dylib-mono.cc#L840-L847 

will exit. 

@jonpryor could we merge some logging right there?

https://github.com/xamarin/xamarin-android/blob/e6044b0c1f664243d496390b9f7c3263bd4176f8/src/monodroid/jni/dylib-mono.cc#L844

**Comment by alexanderkyte** [comment]
After getting back some feedback from @grendello , I've come to understand that the issue is that we're never calling register_modules, but because we're working with bundled assemblies we know that we don't want to check those bundled assemblies. That `} else {` should be `} else if (!bundled) {`

**Comment by vargaz** [comment]
Bundled assemblies are not related to aot, a bundled assembly could still have an aot image on disk. We probably need some additional apis to let the app control the directories used to search for aot images.

**Comment by alexanderkyte** [comment]
After discussing the XA problem in channel, it seems more that they are watching us probe the filesystem by default. 

It was my understanding that MONO_AOT_MODE_NORMAL would probe, but MONO_AOT_MODE_NONE would not.

What actually happens is that we install the loading function as an assembly loading hook. 

Also it seems that we default to `MonoAotMode mono_aot_mode = MONO_AOT_MODE_NONE;` on the desktop, while wanting it to probe (MONO_AOT_MODE_NORMAL). 

I'll have a PR shortly.

**Comment by lambdageek** [comment]
Addressed in part by:
* #12058
* #12074

**Comment by alexanderkyte** [comment]
Confirmed by @grendello to be fixed
