### ISSUE TITLE
how to embed mono with interpreter

### ISSUE THREAD

**Issue by srxqds** [mono/mono#12068]
I want to load mono with interpreter mode , but i can't find mono_interp_init api 

is there other method embedd with interpreter mode?
I want to use it on ios so that it can hot fix (reload) code!

**Comment by lewurm** [comment]
If you are using Xamarin.iOS, you can pass `--interpreter` to mtouch. If you embed mono yourself, it's described here: https://github.com/mono/mono/blob/d8faa8e8819b9f7b5a060bb972609e792808293e/man/mono.1#L248-L257

feel free to reopen if you have further questions

**Comment by srxqds** [comment]
I should built mon runtime and mcs library with --enable-minial-jit ?

**Comment by lewurm** [comment]
@srxqds you should be able to build it with `--enable-minimal=jit` if you plan only to use the interpreter. you might need this patch though: https://github.com/mono/mono/pull/12080
