### ISSUE TITLE
Issue with Xamarin F# on iOS ARM64, related to struct types

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [mono/mono#12073]
I am experiencing a very strange bug, which I am almost certain is related to 

https://github.com/mono/mono/issues/11263

which in turn was reported due to 

https://github.com/Microsoft/visualfsharp/issues/5765

I had previously had the issue above on Android, and worked around it by disabling the 64 bit extensions. This is not an option with iOS as Apple require them.

My repro conditions this time around are almost exactly the same and as complex. The main difference is I am running on iOS, not Android.

If I run on a 32 bit device (I have an older iPad) I see no issues.

On 64 bit devices, I get a bug where an FSharp Result can be created correctly and can be inspected, but as soon as it is passed to another function, whatever is inside is lost. The next line of code that tries to access the content (or even inspecting after setting a breakpoint) causes the app to crash immediately. 

It is a nightmare to create an example project as it makes no sense and seems to be sensitive to context. I would guess that the repro from the above possibly-related F# issue may well show the same behaviour if ported to iOS. I will try that if necessary and update this thread with a sample. I am in a similar situation to that guy in that it is currently occurring for me in a large and commercially sensitive application so I can't share its source.

## On which platforms did you notice this

[ x] iOS

**Version Used**:

Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
Package version: 516000221

Xamarin.iOS
Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

**Comment by RyanBuzzInteractive** [comment]
@dsyme I hope you don't mind me tagging you here, I expect Github emailed you when I linked your issue anyways. I am guessing this is the correct place to report this seems like a good idea to have you and the FSharp guys aware of it too.

**Comment by dsyme** [comment]
@RyanBuzzInteractive Do the workarounds listed there work for you?

**Comment by RyanBuzzInteractive** [comment]
There was only one workaround as far as I know, which was to disable the 64 bit extensions, which you can't do on iOS.

**Comment by dsyme** [comment]
Oh i see. Ugh

**Comment by dsyme** [comment]
Can you eliminate your use of the `Result` struct?

**Comment by RyanBuzzInteractive** [comment]
Running on a 32bit iPad works fine though, I am sure it has to be the same issue somehow.

**Comment by dsyme** [comment]
See also this?
> It doesn't crash with a newer Xamarin.Android version anymore (Version: 9.1.199.8). In mono terms that is a jump from 2018-02 -> 2018-06, so I assume the issue you are seeing was fixed between those two releases.

**Comment by RyanBuzzInteractive** [comment]
Yeah, I see that, but I am on iOS, not Android, and I am up to date.

**Comment by RyanBuzzInteractive** [comment]
It would be nice to know what the mono team did to fix it for Xamarin.Android, and to know if the same fix might be applied to Xamarin.iOS or at least shed some light into the cause. Not that I would understand it I expect!

**Comment by RyanBuzzInteractive** [comment]
Also, removing the Result type isn't really an option, as the app is massive and uses it almost everywhere in the core. We would be talking probably 10s of thousands of changes. We have 2k unit tests alone.

**Comment by knocte** [comment]
> It would be nice to know what the mono team did to fix it for Xamarin.Android

@RyanBuzzInteractive hey, it seems you didn't understand https://github.com/mono/mono/issues/12073#issuecomment-447401025 . The "jump from 2018-02 -> 2018-06" means that Xamarin.Android from time to time updates the internal mono version used by it. You can map month-releases with number releases here: https://www.mono-project.com/docs/about-mono/versioning/#mono-source-versioning , then that above means "jump from Mono 5.12 to 5.16.

Then what you have to do is make sure you're using a version of xamarin-macios that includes mono version 5.16. (There are also mono bumps in xamarin-macios, for example: https://github.com/xamarin/xamarin-macios/commit/7c4aa8cbf860ac15e4b45b0d3961159ca2975faf )

**Comment by RyanBuzzInteractive** [comment]
Hi @knocte  I did understand that, sorry if I didn't explain myself clearly. I am using the most recent Xamarin iOS release, so I have no option to update. 

I just meant that obviously something changed in mono which fixed Xamarin Android. I thought that could perhaps provide a clue as to what is going on in Xamarin iOS and how it might be fixed.

**Comment by RyanBuzzInteractive** [comment]
I have just looked at the Xamarin iOS release notes here https://docs.microsoft.com/en-us/xamarin/ios/release-notes/12/12.3

I am currently using 12.2.1.12 which is the most recent stable.

Even 12.3, the upcoming release I linked to, says it is built against mono 5.14, which is too early for the fix which as you say will probably need mono 5.16.

**Comment by marek-safar** [comment]
We are previewing XI 12.6 version which the latest of it should be based on 2018-06 or newer. Could you check if this version does fix your issue?

**Comment by RyanBuzzInteractive** [comment]
I would be very happy to try it. Will it be in the alpha channel in the near future or will I need to build it from source? I won't lie, that is a bit intimidating for me! I can give it a go though if that is the only way.

**Comment by marek-safar** [comment]
It should show up in your preview channel

/cc @spouliot

**Comment by RyanBuzzInteractive** [comment]
Awesome, thanks for your help, I will post back once it shows up and I have tried it.

**Comment by spouliot** [comment]
16.0 preview 1 was still based on 2018-04 (same as stable).
16.0 preview 2 is based on 2018-06 but **unreleased** (and might be updated to 2018-08 before it's release).
Future previews (and final) will be based on 2018-08.

@RyanBuzzInteractive your best bet would be to use a build from master - minimally to confirm the fix.

**Comment by RyanBuzzInteractive** [comment]
Thanks, just downloading the build you posted on the linked issue.

**Comment by RyanBuzzInteractive** [comment]
I can happily confirm that the recent build from Xamarin.iOS master provided by @spouliot did indeed fix the issue. Thanks everyone for your support (and have a great xmas!)
