### ISSUE TITLE
how to build mono runtime with interpreter mode on windows?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#12085]
how to build mono runtime with interpreter mode ?
with "--enable-minial=jit" but the output also show:
"Engine: building and using JIT"

And it should rebuild bcl library (mscorlib.dll  or mcs.exe) when it is in interpreter mode or jit mode?
If it should rebuild and how to setting build with interpreter mode?

platform: windows
host target:x86-64

**Comment by srxqds** [comment]
I call mono_jit_set_aot_mode (MONO_AOT_MODE_INTERP);
It will crash...

**Comment by srxqds** [comment]
I have confused with blow three questions:

1.as the website: https://www.mono-project.com/docs/about-mono/supported-platforms/ show:
![image](https://user-images.githubusercontent.com/5187024/50120048-4c962d00-028f-11e9-805f-fa4bc772412d.png)
windows don't support interpreter mode?

2.if windows support interpreter mode how should i build mono runtime and bcl should rebuild ( it differ from jit ?)

**Comment by srxqds** [comment]
I use this command build mono with cywin64:
./autogen.sh --prefix=$PREFIX --host=x86_64-w64-mingw32 --enable-msvc --disable-boehm --disable-jit --enable-minimal=jit

I found in cygconfig.h has:

![image](https://user-images.githubusercontent.com/5187024/50143333-4cc21700-02e7-11e9-9c2d-3870cfb869d1.png)

![image](https://user-images.githubusercontent.com/5187024/50143341-5186cb00-02e7-11e9-833a-b00add850c81.png)

but when I call make command, config.h will replace by winconfig.h so that the "--disable-jit --enable-minimal=jit" args not work?

how can I do it?

I want implement that: use all platfom (windows, android, ios) runing with interpreter mode

I call mono_jit_set_aot_mode (MONO_AOT_MODE_INTERP); it will crash!

can someone help me?

**Comment by lateralusX** [comment]
No work has been done to port or test interpreter to Windows (at least not that I'm aware of). It's on the list of things to do.

The mingw gcc build still uses the flags used in configure step (replaced config.h includes cygconfig.h that is the original config file), so that build should at least build with expected flags, but since interpreter has not been validated or tested, there might be issues actually running it. For MSVC build, additional work needs to be done in order to preserve the flags. If you just want to test the MSVC build, you can manually add the needed flags directly into winconfig.h and make sure they end up in final config.h

**Comment by lateralusX** [comment]
Until we have properly ported the interpreter to Windows (including adding CI lanes running it) it's still experimental feature for that platform. You are of course free to experiment with it and see if you could get it up and running.

If you run configure without --enable-msvc you will just do mingw gcc build as part of make build (you can of course build MSVC mono runtime as stand alone build step). All detailed Windows build steps are described on the Mono page.

Having that said, the mingw gcc build is not what's being tested at all on CI for Windows (only MSVC build is tested), so using that build is even more of an experiment, not just the interpreter part.

If you just want to start running the interpreter, I believe you should start looking at mixed mode. That configuration should already build as part of regular build configuration. If you get mixed mode running then next step is to disable JIT. So you could try:

./autogen.sh --prefix=$PREFIX --host=x86_64-w64-mingw32 --enable-msvc --disable-boehm

and then make.

This will do full build, mingw gcc Mono runtime, MSVC build Mono runtime, BCL and tests. If you would like to experiment with the MSVC build runtime you find it under:

[mono-root]\msvc\build\sgen\x64\bin\Release

If you just run mono-sgen.exe --version from there you will see something like this:

Mono JIT compiler version 5.23.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          no
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

This indicates that you have a Mono runtime supporting interpreter. To try it out, setup MONO_PATH to point to your BCL and run, mono-sgen.exe --interpreter yourassembly.exe.

When I just quickly tested this on a Windows x64 build I had there was a crash as part of running finalizers, so as I initially said, no work has been done so far to do full port of interpreter to Windows.
