### ISSUE TITLE
make asserts optional or smaller

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#12084]
As a size optimization, some or all of the following would be nice.

1. Audit all g_asserts and make sure none have side affects.
Therefore make g_assert optional.
Perhaps this can be automated but I don't know how.

2. Reduce the size of the asserts such as by:
2a. Having them only contain leaf-filename and line number, no string.
2b. Moving file and/or string out of the code, into a separate file, that is released along with any release, probably with a git hash in its name/path.
The object code (not the maintained source) would probably remain with just a dense enum for the strings or a hash.

In any case, maintenance must remain no more difficult than it is today. The strings could be wrapped in a macro, though g_assert itself is probably it.
Any movement of data out of object code should be a build step.
Real systems do put the strings in separate files. That debuggers know how to find them.

Again the point is extreme size optimizing, if there are small enough systems to warrant.

And the size cost should be measured early. A first order not necessarily working approximation is just build with assert defined to be empty (ignoring the semantic loss if any contain side effects).

**Comment by lewurm** [comment]
there is `--enable-minimal=assert_messages` and it's used on WebAssembly
