### ISSUE TITLE
[WASM] System.IO is not functional

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#12122]
### Current Behavior
After the merging of https://github.com/mono/mono/pull/11342, the whole `System.IO` became unuseable, throwing `PlatformNotSupportedException`.

### Expected Behavior
System.IO operations, (File, Directory, etc...) work properly, backed by emscripten's emulated filesystem APIs.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] WebAssembly

**Comment by lewing** [comment]
The wasm corlib tests aren't currently part of the jenkins build (probably because they aborted on a single fixture) so we didn't see these before the merge.

**Comment by vargaz** [comment]
Fixed in master.
