### ISSUE TITLE
LLVM failed for 'UIEdgeInsets.Equals': opcode r4_cneq

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#12131]
## Steps to Reproduce

Use same steps as for #12130.

### Current Behavior

This shows up in the [build log](https://gist.github.com/rolfbjarne/645ac18d7148e4a699a100b4ae733dda):

> LLVM failed for 'UIEdgeInsets.Equals': opcode r4_cneq

### Expected Behavior

LLVM should not fail to compile anything when building for watchOS.

**Comment by vargaz** [comment]
This is already fixed in master, it can be backported if needed.

**Comment by rolfbjarne** [comment]
> This is already fixed in master, it can be backported if needed.

Yes, back until 2018-08 please :)

**Comment by lewurm** [comment]
@rolfbjarne please confirm that the issue is fixed for you

**Comment by rolfbjarne** [comment]
Yes, this is fixed now.
