### ISSUE TITLE
embeded mono runtime on ios crash, is there embeded mono on ios xcode project sample?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#12134]
when call mono_set_dirs it crash with "signal SIGABRT" 

this is my xcode project screenshot:

![1545293642 1](https://user-images.githubusercontent.com/5187024/50272345-73608900-0472-11e9-9ee3-78f2beae3304.jpg)

**Comment by srxqds** [comment]
How can I generate mono runtime xcode project, I can debug with source code?

**Comment by srxqds** [comment]
@lateralusX @lewurm @marek-safar may you help me?

**Comment by srxqds** [comment]
I use static lib or dynamic lib always crash

**Comment by srxqds** [comment]
I user sdk/ios/runtime source code run also has the same error:

![image](https://user-images.githubusercontent.com/5187024/50330935-fbf52d00-0537-11e9-80ed-deecdd6b22c7.png)

**Comment by lewurm** [comment]
It looks like to me you _are_ already debugging.  On the right bottom you have a `lldb` prompt. Type `bt all` there and it should give you more information about the nature of the `SIGABRT`. Guessing from your screenshot, it is probably related to `lib_path` and `config_path` being empty strings.

**Comment by srxqds** [comment]
hi, @lewurm , thank you for reply!

The error traceback show below:
![image](https://user-images.githubusercontent.com/5187024/50630001-efca9000-0f79-11e9-8d00-4d8ba1ba9928.png)

Can you provide some Xcode embedded mono runtime only sample or some detail steps or tips for it!

**Comment by lewurm** [comment]
Oh, that actually looks like the dynamic linker can't find the `libmonosgen.dylib`, so something is wrong with your linker settings.

As part of the Mono iOS SDK, there is a small project that shows how to embed the Mono Runtime in an iOS project: https://github.com/mono/mono/tree/master/sdks/ios/runtime It's `Makefile`-based though, but it should be straight forward to create a Xcode project out of it.

This shows how to initialize the runtime:
https://github.com/mono/mono/blob/40ec59d65b22590c6a5f4ed065d9f0a04de3db39/sdks/ios/runtime/runtime.m#L218-L335

**Comment by lewurm** [comment]
Depending on your goal, it might be easier to use Xamarin.iOS by the way.

**Comment by srxqds** [comment]
I did it.
