### ISSUE TITLE
Invoking TransparentProxy via embedded API.

### ISSUE THREAD

**Issue by mugginsoft** [mono/mono#12132]
Question.

Is it possible to invoke methods on a TransparentProxy using the embedded API?

Obviously invocation is transparent in the managed world.
How do I approach it natively?

**Comment by lambdageek** [comment]
@mugginsoft I think if you have a `MonoMethod* itf_method` for an interface method, and a `MonoObject* proxy_obj` that's a transparent proxy, you can call `mono_object_get_virtual_method` to get the remoting invoke method that will call `m` on the proxy target.  So something like this (with appropriate error checking, etc):

```c
   MonoMethod *m = mono_object_get_virtual_method (proxy_obj, itf_method);
   MonoObject *result =  mono_runtime_invoke (m, proxy_obj, args, &exc_out);
```

**Comment by lambdageek** [comment]
@mugginsoft - `itf_method` should be the method you already have - the call to `mono_object_get_virtual_method` is precisely the operation that will pull the correct method for the proxy target.

if you have something like this:

```csharp
  namespace Example {
       interface Itf {
          void MyMethod ();
       }
  }
```

Suppose you have `MonoObject *proxy_obj` which is a transparent proxy for an `Itf`.

Then you can do something like:
```c
   MonoClass *itf_class = mono_class_from_name (image, "Example", "Itf");
   MonoMethod *itf_method = mono_class_get_method_from_name (itf_class, "MyMethod", 0);
```
At this point `itf_method` is the `MonoMethod*` for `Itf.MyMethod`
```c
   MonoMethod *m = mono_object_get_virtual_method (proxy_obj, itf_method);
```
now `m` is the remoting-invoke method that will call `MyMethod` implemented by the proxy target.

**Comment by mugginsoft** [comment]
That works. Thanks a lot.
