### ISSUE TITLE
monodevelop install under Debian 9 gpg: Keyserver receive failed: No Name

### ISSUE THREAD

**Issue by TucsonYazdi** [mono/mono#12144]
I'm trying to install monodevelop on a BeagleBoard X15 running Debian 9. I get the following error when following the install instructions for Debian 9:

# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
Executing: /tmp/apt-key-gpghome.nPwBCYJOXu/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: keyserver receive failed: No name

Can someone help!

**Comment by directhex** [comment]
Are you in some weird proxy environment?

Try using `curl http://download.mono-project.com/repo/xamarin.gpg | apt-key add -` instead

**Comment by TucsonYazdi** [comment]
Yes, I have to go through a proxy server.  The above command worked! I followed that with an apt update, apt-get upgrade mono-complete, and apt-get install monodevelop.

Thank you!
