### ISSUE TITLE
mono-master.zip - 'external' and its sub-folders missing

### ISSUE THREAD

**Issue by LeeMSilver** [mono/mono#12166]
I downloaded mono-master.zip yesterday, unzipped it and loaded bcl.sln into Visual Studio. No files from 'external' or its sub-folders were present. I examined the zip-file and 'external' and its sub-folders are not present.

I then did a 'pull' with GitHub Desktop. 'external' and it sub-folders are present but unpopulated.

## Steps to Reproduce

1. Click 'Clone or download' and then 'Download zip'

### Current Behavior

Projects won't compile because required files are not present.

### Expected Behavior

That the files in 'external' and its sub-folders be present.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:

n/a - using it on Windows without Mono installed.

## Stacktrace

n/a`

**Comment by marek-safar** [comment]
Please follow instructions at https://www.mono-project.com/docs/compiling-mono/windows/no-cygwin/

**Comment by akoeplinger** [comment]
The issue is that the .zip provided by GitHub doesn't contain the required git submodules in external/.

Unfortunately GitHub doesn't allow us to disable the .zip download on the website...
