### ISSUE TITLE
Latest RPM packages are not signed

### ISSUE THREAD

**Issue by rohoog** [mono/mono#12199]
## Steps to Reproduce

1. dnf update
2. dnf complains that the mono-xxx-5.18.0.225-0-xamarin.1.epel7.x86_64.rpm packages are not signed
3. dnf refuses the update until you omit the mono packages or disable the mono repo

### Current Behavior

Mono packages are refused to update by dnf

### Expected Behavior

Mono packages should update normally

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**: Fedora 28

This is since 5.18.0.225

## Stacktrace

```
Not applicable
```

**Comment by directhex** [comment]
I fixed this at the time when someone brought it up on Gitter. The file ~/.rpmmacros was missed in the move from the old origin-download VM to the new one, and that is the file which specified which GPG key to use for `rpmsign`. I re-added the file, resigned all the RPMs in the stable branch, recreated the repo manifests, and expired the CDN, on Xmas Eve

**Comment by rohoog** [comment]
Thanks!
