### ISSUE TITLE
[bcl] DeflateNativeStream may leak SafeDeflateStreamHandle if an exception in the underlying stream occurs.

### ISSUE THREAD

**Issue by galli-leo** [mono/mono#12205]
## Steps to Reproduce

1. Create a DeflateStream (e.g. via GzipStream or using the normal HttpWebRequest classes).
2. Cause the underlying stream to throw an error on write / read (e.g. when the other end of the NetworkingStream closes the connection)

Reproduction case: https://gist.github.com/Taloth/5a9e0e2408717ab464810984b645e250

Discovered by: @Taloth

### Current Behavior

The native zlib code calls `UnmanagedRead` / `UnmanagedWrite` which in turn calls `base_stream.Read` / `base_stream.Write`. If `base_stream` throws an exception during those calls, the exception will be propagated to unmanaged code. Since the unmanaged code does not understand exceptions, this causes a few issues. The most noticeable being, that `SafeDeflateStreamHandle` will not be disposed properly. This is because, the call to native zlib increases the ref count by one. If there is an exception in the managed code called by the native code, the ref count will not be decreased again. This leads to a ref count of 2 or more for the `SafeDeflateStreamHandle`. When disposing a `SafeHandle` its ref count must be 1. Hence, the `ReleaseHandle` method of `SafeDeflateStreamHandle` will never be called and hence the native resources will not be correctly freed. There could also be other possible side effects.

### Expected Behavior

`UnmanagedRead` / `UnmanagedWrite` catch exceptions and do not let them propagate through to native code. However, maybe `WriteZStream` / `ReadZStream` also need to catch exceptions. In the rare case of an exception that cannot be caught by `UnmanagedRead` / `UnmanagedWrite` (e.g. a ThreadAbortException), the `SafeDeflateStreamHandle` should still be properly disposed.

**Edit:** One could also rewrite the whole DeflateStream to only use the native zlib calls and not use any native "glue" like .NET does it. However, that would require significantly more work.

## On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.23.0 (fix/inner-stream-leaking/d5988ae8874 Tue 25 Dec 2018 02:44:51 CET)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

I can make a PR if that's ok. Should be relatively easy to fix.

**Comment by baulig** [comment]
It looks like returning a negative value from `UnmanagedWrite` causes it to be called over and over again.

To illustrate that, with a 64 mb random file, and adding the following to `UnmanagedWrite`:

```
				try {
					base_stream.Write (io_buffer, 0, count);
				} catch (Exception ex) {
					Console.Error.WriteLine ($"DS UNMANAGED WRITE EX: {++martinTest} {ex.Message}");
					// last_error = ex;
					// return -1;
					throw;
				}
```

That line is executed 100 times per cycle.

Uncomment the `return -1` and it gets called ... I cancelled after about 300k calls.

**Comment by baulig** [comment]
I am still a bit confused about what calls `UnmanagedWrite` and why it would be called over and over again if it returns a negative number (I also tried different negative values than `-1`).

**Comment by Taloth** [comment]
UnmanagedWrite is exclusively called in zlib-helper.c (write_to_managed) as callback from the native layer.
If the return value is < 0 then it returns IO_ERROR in the native layer. That seems to be handled properly in WriteZStream, which also aborts if < 0.

One possible failure path is in CloseZStream with calls flush_internal without checking the flush_status value. But that's just from reading the code. I'm not entirely sure if deflate(..) will keep returning Z_OK there, which would be required to keep that loop alive.
