### ISSUE TITLE
CDN problems with mono-llvm

### ISSUE THREAD

**Issue by zvonimir** [mono/mono#12228]
This is a recent issue since this used to work just fine only several weeks ago. I am not sure what changed since then. Also, note that everything works fine on Ubuntu 16.04.

## Steps to Reproduce

1. Follow the official instructions for installing mono on Ubuntu 14.04
2. Run `sudo apt-get install mono-complete`

### Current Behavior

The installation fails right away with the following error:
```
E: Failed to fetch https://download.mono-project.com/repo/ubuntu/pool/main/m/mono-llvm/mono-llvm-tools_6.0+mono20180728010642-0xamarin12+ubuntu1404b1_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Expected Behavior

I am expecting for the installation to go through.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Comment by romanm-odysii** [comment]
@zvonimir , at first sight it doesn't looks as issue related to Mono but dpkg.
try to download file again in following way:
`curl https://download.mono-project.com/repo/ubuntu/pool/main/m/mono-llvm/mono-llvm-tools_6.0+mono20180728010642-0xamarin12+ubuntu1404b1_amd64.deb`
The total size should be 18,455,638 bytes exactly. If your downloaded file has different size or even much smaller, then you should check this issue with system administrator.

Here is my try:
`$ curl -I https://download.mono-project.com/repo/ubuntu/pool/main/m/mono-llvm/mono-llvm-tools_6.0+mono20180728010642-0xamarin12+ubuntu1404b1_amd64.deb`
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: application/x-debian-package
Date: Tue, 01 Jan 2019 16:08:23 GMT
Etag: "1199c56-57a37acb4d985"
Last-Modified: Fri, 09 Nov 2018 09:07:02 GMT
Server: ECAcc (dcb/7F46)
X-Cache: HIT
Content-Length: 18455638

Additional reference: https://askubuntu.com/a/165935

**Comment by marek-safar** [comment]
@directhex did anything changed recently?

**Comment by zvonimir** [comment]
Thanks for your help. Yes, it seems that this weird problem is happening only within our university network. I contacted our admins and we'll see what they say.

**Comment by directhex** [comment]
To help me work out which end is causing issues, can you please provide me with the contents of:

`grep -A15 "^Package: mono-llvm-tools" /var/lib/apt/lists/*_Packages`

"Good" values would be something like:

```
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages:Package: mono-llvm-tools
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Source: mono-llvm
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Version: 6.0+mono20180728010642-0xamarin12+ubuntu1404b1
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Architecture: amd64
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Maintainer: Jo Shields <joshield@microsoft.com>
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Installed-Size: 80450
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Depends: libc6 (>= 2.15), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.8.1)
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Homepage: http://www.mono-project.com/docs/advanced/mono-llvm/
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Priority: optional
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Section: devel
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Filename: pool/main/m/mono-llvm/mono-llvm-tools_6.0+mono20180728010642-0xamarin12+ubuntu1404b1_amd64.deb
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Size: 18455638
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-SHA256: 5882a828bea68eeca2a39c702d2abb6431d03e5e651fb2b3a71986dffcc61067
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-SHA1: 15df61e2e02b96f7b56b98968d6e1d6ec8e990a2
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-MD5sum: f20c5e77c1897fb0c838800be3806f86
/var/lib/apt/lists/download.mono-project.com_repo_ubuntu_dists_stable-trusty_main_binary-amd64_Packages-Description: opt and llc for Mono llvm mode
```

Note the size and hashes it expects.

Then if you download the package by hand with `wget https://download.mono-project.com/repo/ubuntu/pool/main/m/mono-llvm/mono-llvm-tools_6.0+mono20180728010642-0xamarin12+ubuntu1404b1_amd64.deb`, what size is it? What are the sums?

If I know which end shows up wrong for you, I can try flushing our CDN (in case there's a bad cache at our end)

**Comment by directhex** [comment]
Any change?
