### ISSUE TITLE
Update System.Data.Entity to handle new String overloads

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#12255]
After adding new string overloads we need to update System.Data.Entity mapping table otherwise the new overloads won't be recognized leading to unhandled exceptions for the new best overloads

The code to be updates can be fount at https://github.com/mono/mono/blob/40ec59d65b22590c6a5f4ed065d9f0a04de3db39/mcs/class/referencesource/System.Data.Entity/System/Data/Objects/ELinq/MethodCallTranslator.cs#L972

Trim/TrimStart/TrimEnd are already failing but we should check all

**Comment by EgorBo** [comment]
I wonder who uses this BCL assembly at all, when users run EF6 on top of mono  - they use EF's System.Data.Entity, don't they?
