### ISSUE TITLE
Why is jessie-stable updated daily?

### ISSUE THREAD

**Issue by jeroenmeulenaar** [mono/mono#12284]
I'm not sure if this is the right place to ask, but https://download.mono-project.com/repo/debian brought me here.

I'm maintaining a debian Jessie (old-stable) system. To be able to run Duplicati, I have a line in `apt.sources.d` which reads
`deb https://download.mono-project.com/repo/debian stable-jessie main`

However, this has an update each day! This is not what I'd like on my stable system (also reflected in https://github.com/mono/linux-packaging-mono/blob/master/debian/changelog) - I'd prefer to only have security fixes and as little downloads as possible.

Is there a different release channel that only has the important updates available?

(again, if there's a better place to ask, I'd be happy to ask there)

**Comment by directhex** [comment]
It's not actually updated daily - the last pushes to the Stable repo were 5.18.0.225-0xamarin13 on Jan 3 (which fixed install failures for people with CPUs without SSE4.1 support), 5.18.0.225-0xamarin1 on Dec 22 (the 5.18 stable upload), and 5.16.0.220-0xamarin4 (5.16 update to align with release of Visual Studio for Mac 7.7)

What does `apt-cache policy mono-runtime` say?

And are you seeing _package_ downloads (from `apt-get upgrade`), or _metadata_ downloads (from `apt-get update`)?
