### ISSUE TITLE
Incorrect abort rethrow check

### ISSUE THREAD

**Issue by BrzVlad** [mono/mono#12292]
## Steps to Reproduce

1.  Run the following test case.

```csharp
using System;
using System.Threading;

class Test
{
	public static void DoStuff ()
	{
	}

	public static int Main (string [] args) {
		try {
			try {
				Thread.CurrentThread.Abort ();
			} catch (ThreadAbortException e) {
				try
				{
					DoStuff ();
					/*
					 * We have a pending abort and a leave inside a catch clause,
					 * which is not exiting it though. It shouldn't rethrow here
					 * so we get to reset the abort later
					 */
				} catch (Exception) {
				}
				Thread.ResetAbort ();
			}
		} catch (Exception) {
			return 1;
		}

		Console.WriteLine ("OK");
		return 0;
	}
}
```

### Current Behavior

The thrown abort exception is not reset.

### Expected Behavior

The abort exception should be reset and the test should print ok

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

master

**Comment by SamMonoRT** [comment]
Closing this old mono\mono issue we haven't had a need to fix(or was already fixed and not marked correctly) that for 2+ years now. Please re-open if we need to revisit this again.
