### ISSUE TITLE
mkbundle -z not working with --cross/--runtime

### ISSUE THREAD

**Issue by wolfgangmauer** [mono/mono#12333]
## Steps to Reproduce

1. mkbundle -v **-z** --deps --static --runtime /usr/bin/mono -z ./input.exe -o ./output -L /usr/lib/mono/4.5 --library libWrapper.so

### Current Behavior

Assemblies will not be compressed

### Expected Behavior

Assembly will be compressed (-z)

## On which platforms did you notice this

[ ] macOS
[ X] Linux
[ ] Windows
Mono JIT compiler version 5.18.0.225 (tarball Wed Jan  2 21:20:16 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)

**Comment by migueldeicaza** [comment]
Correct, mkbundle in simple/cross mode does not support the -z flag.   There are no plans to change that, unless someone wants to contribute the work.
