### ISSUE TITLE
Debug Proxy cannot get assemblies because their names are lower-cased. toLower works culture spesific.

### ISSUE THREAD

**Issue by ud09** [mono/mono#12347]
I created an issue for blazor here [https://github.com/aspnet/AspNetCore/issues/6474](url)
But that's actually an issue for the mono debug proxy.
(Mono.WebAssembly.DebuggerProxy/DebugStore.cs ctor)  
In Turkish culture toLower does not work for Capital I's in the assembly names. Using toLowerInvariant may be the fix, but not sure  if there is a better solution for all cases.

**Comment by lewing** [comment]
So this is culture specific on the server side. https://github.com/mono/mono/pull/12540 may resolve this the problem but we'll need to verify.

**Comment by jeromelaban** [comment]
This change https://github.com/mono/mono/pull/12540/files#diff-dd2a845ca2ae32b7f4144f59ed43ec02R483 will most likely help for that specific use case.

**Comment by lewing** [comment]
I believe this is fixed now that #12540 is in. If it is isn't please reopen the issue and attach a test case.
