### ISSUE TITLE
System.Xml and other tests do have failures on iOS platforms

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12354]
On the iOS xamarin side we have started executing the test dlls that are provided in the SDK on devices. He have noticed that there are a number of tests that fail de to the fact that certain files needed by the tests are missing. If you take a look at the new file added in https://github.com/xamarin/xamarin-macios/pull/5370 you will see the list of all the failing tests + the reason for each of the tests.

**Comment by akoeplinger** [comment]
This should be obsolete once the 2018-10 integration lands since starting with that the tests embed all files inside of the test assembly itself.

**Comment by akoeplinger** [comment]
Doesn't repro anymore on mono-2018-10.
