### ISSUE TITLE
System.IO.Compression tests fail on iOS platforms

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12356]
We have started executing the tests from the test dlls that are present in the Mono SDK. In those dlls there are some tests that fail because the tests expect a file that is not present in the system. Please take a look at the new file https://github.com/xamarin/xamarin-macios/pull/5373 which states the ignored tests and the reason.

**Comment by akoeplinger** [comment]
Duplicate of https://github.com/mono/mono/issues/12354
