### ISSUE TITLE
[Wasm] Very limited call stack depth using the interpreter on Safari iOS

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#12357]
## Steps to Reproduce

Run the following sample: https://github.com/jeromelaban/Wasm.Samples/tree/master/RecursionTests

### Current Behavior

Depending on _when_ the code is executed, the call stack depth can vary between 57 and 390 (after waiting 5 to 10s) when recursing using delegates, and between 116 and 790 (after a while) using plain methods.

### Expected Behavior

Aside from the fact that the Safari iOS javascript call stack is around 7900 (given http://jsfiddle.net/josh3736/Z5pLM) the room for recursion is limited, but it could help to be more conservative under the interpreter, particularly for static delegates.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] WebAssembly

Version: Mono-master 01f6a0203b0.

**Comment by jeromelaban** [comment]
with #12367, the updated results are for the tests above :
``` 
// Using Safari for iOS 12.1.2, with the interpreter
// 
// SmallStackFailure(1000);             // 01f6a02: 116 levels deep -> 7952489bd2c: 129 levels deep
// SmallStackFailure(5000);             // 01f6a02: 790 levels deep ->  7952489bd2c: 918 levels deep
// SmallStackFailureDelegates(1000);    // 01f6a02: 57 levels deep -> 7952489bd2c: 64 levels deep
SmallStackFailureDelegates(2000);       // 01f6a02: 390 levels deep ->  7952489bd2c: 460 levels deep
```
as for the performance, using Firefox on desktop, using [this raytracer](https://github.com/nventive/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.AotTests/Program.cs):
```
mono-master 01f6a02: 30s
mono-master 7952489bd2c: 33s
```

**Comment by jeromelaban** [comment]
Note that this issue also happens on latest Safari for macOS

**Comment by jaykrell** [comment]
There has been much further removal of recursion in the Mono interpreter, leaving still some but a lot less, and fixes are in the pipeline (or released?) from Apple.

**Comment by jeromelaban** [comment]
This issue has been fixed in recent mono builds
