### ISSUE TITLE
NuGet: bump to latest NuGet to support GeneratePathProperty

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/mono#12393]
See https://github.com/NuGet/NuGet.Client/pull/2271. @radical asked me to open an issue here to bump NuGet in Mono to at least 4.9 to have this fix.

**Comment by marek-safar** [comment]
@KirillOsenkov what Mono version is this for?

**Comment by KirillOsenkov** [comment]
We're on 5.18.0.234. It's not strictly required (we worked around), but very nice to have.
