### ISSUE TITLE
tlstest.cs will not build.

### ISSUE THREAD

**Issue by Kr3m** [mono/mono#12400]
## Steps to Reproduce

1. csc tlstest.cs -r:System.dll

### Current Behavior

What is the current behavior?
![screenshot from 2019-01-13 03-20-03](https://user-images.githubusercontent.com/290740/51083101-2626ae80-16e2-11e9-9cfd-44dd6c4d6565.png)

### Expected Behavior

the code to build properly...

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

5.18.0.225

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by baulig** [comment]
We should really delete that old and obsolete tool.

**Comment by baulig** [comment]
PR to finally remove this old an obsolete tool is up: https://github.com/mono/mono/pull/12542.
