### ISSUE TITLE
Some tests from System.Core fail on iOS/WatchOS and TvOS

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12419]
In Xamarin.iOS we are executing the tests for System.Core provided by the Mono SDK. We have a failing test that had to be ignored in PR https://github.com/xamarin/xamarin-macios/pull/5397

Please look at the .ignore file added that contains the failing test and the error.

**Comment by akoeplinger** [comment]
Doesn't repro anymore on mono-2018-10.
