### ISSUE TITLE
System.ServiceModel tests fail on iOS/TvOS/WatchOS

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#12417]
We have started executing the ServiceModel tests that are provided from the test dlls in the Mono SDK. Some of the tests fail on ios/watchos and tvOS, we have added the required ignores in PR https://github.com/xamarin/xamarin-macios/pull/5384 

Please take a look at the new ignore files that contain the failing tests and the reasons to be ignored.

**Comment by akoeplinger** [comment]
Duplicate of https://github.com/mono/mono/issues/12354
