### ISSUE TITLE
Runtime incorrectly resolving overloads that differ by modopt 

### ISSUE THREAD

**Issue by jaredpar** [mono/mono#12422]
## Steps to Reproduce
This was found attempting to get the C# semantic tests running on Mono

1. Clone https://github.com/jaredpar/roslyn
1. Run `./build.sh --restore --build`
1. Run `cd src/Compilers/CSharp/Test/Emit`
1. Run `dotnet msbuild /t:Test /p:TestRuntime=Mono` 

### Actual Behavior
This will run the Emit unit tests and eventually Mono will fail executing the test ` TestCallMethodsWithLeastCustomModifiers`.  The output of the test will be 11 and the expectation is 51. 

Note: this behavior is flaky. It occurs roughly 5% of the time in our test runs. 

### Expected Behavior
The test passes

## On which platforms did you notice this

This was discovered on Ubuntu 18.04. I'm using the latest nightly mono as described by the Download page

https://www.mono-project.com/download/nightly/#download-lin

```
Mono JIT compiler version 5.19.0.290 (tarball Tue Sep  4 10:59:48 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(4)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Full Details

This is a test of the C# compilers behavior when invoking a method that has many overloads where the only difference is the number of `modopt` on each signature. The C# compiler will choose the one with the least number of `modopt` signatures (historical reasons). 

In this case the compiler is invoking the overload of `M` with the following signature:

``` il
  IL_0014:  callvirt   instance uint8 modopt([mscorlib]System.Runtime.CompilerServices.IsConst) [ModoptTests]Metadata.LeastModoptsWin::M(uint8,
                                                                                                                                         uint8)
```

The Mono runtime though is not resolving this correctly at runtime. Instead it's picking the overload with the following signature:

``` il
.method public hidebysig newslot virtual 
        instance uint8 modopt([mscorlib]System.Runtime.CompilerServices.IsConst) modopt([mscorlib]System.Runtime.CompilerServices.IsLong) 
        M(uint8 t,
          uint8 v) cil managed
```

Notice that the difference here is that this signature has a `modopt` for `IsConst` and `IsLong` where the one the C# compiler is targeting only has `IsConst`.

**Comment by marek-safar** [comment]
Part of #11395

**Comment by lambdageek** [comment]
Standalone repro gist https://gist.github.com/lambdageek/0271a0bb3a46b6f889cd478d2d5e3df2

Still fails on `master` ac5ab1a7efe

**Comment by lambdageek** [comment]
vtable looks ok.  (but everything in this example is `newslot`, so that's not surprising).  Need to see what happens in method-to-ir

```
Packed interface table for class Metadata.LeastModoptsWinAmbiguous has size 0
Interface flags: (0,F)
Dump interface flags: 00
[LEVEL 0] Implemented interfaces by class LeastModoptsWinAmbiguous:
[LEVEL 1] Implemented interfaces by class Object:
VTable Metadata.LeastModoptsWinAmbiguous (vtable entries = 7, interfaces = 0)
  slot assigned: 000, slot index: 000 string object:ToString ()
  slot assigned: 001, slot index: 001 int object:GetHashCode ()
  slot assigned: 002, slot index: 002 void object:Finalize ()
  slot assigned: 003, slot index: 003 bool object:Equals (object)
  slot assigned: 004, slot index: 004 byte modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWinAmbiguous:GetByte ()
  slot assigned: 005, slot index: 005 byte modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWinAmbiguous:M (byte modopt(System.Runtime.CompilerServices.IsConst),byte)
  slot assigned: 006, slot index: 006 byte Metadata.LeastModoptsWinAmbiguous:M (byte modopt(System.Runtime.CompilerServices.IsConst),byte modopt(System.Runtime.CompilerServices.IsConst))
Packed interface table for class Metadata.LeastModoptsWin has size 0
Interface flags: (0,F)
Dump interface flags: 00
[LEVEL 0] Implemented interfaces by class LeastModoptsWin:
[LEVEL 1] Implemented interfaces by class LeastModoptsWinAmbiguous:
[LEVEL 2] Implemented interfaces by class Object:
VTable Metadata.LeastModoptsWin (vtable entries = 10, interfaces = 0)
  slot assigned: 000, slot index: 000 string object:ToString ()
  slot assigned: 001, slot index: 001 int object:GetHashCode ()
  slot assigned: 002, slot index: 002 void object:Finalize ()
  slot assigned: 003, slot index: 003 bool object:Equals (object)
  slot assigned: 004, slot index: 004 byte modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWinAmbiguous:GetByte ()
  slot assigned: 005, slot index: 005 byte modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWinAmbiguous:M (byte modopt(System.Runtime.CompilerServices.IsConst),byte)
  slot assigned: 006, slot index: 006 byte Metadata.LeastModoptsWinAmbiguous:M (byte modopt(System.Runtime.CompilerServices.IsConst),byte modopt(System.Runtime.CompilerServices.IsConst))
  slot assigned: 007, slot index: 007 byte modreq(System.Runtime.CompilerServices.CallConvCdecl) Metadata.LeastModoptsWin:M (byte,byte)
  slot assigned: 008, slot index: 008 byte modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWin:M (byte,byte)
  slot assigned: 009, slot index: 009 byte modopt(System.Runtime.CompilerServices.IsLong) modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWin:M (byte,byte)
```

with `MONO_METHOD_VERBOSE=Main`, I see

```
AFTER METHOD-TO-IR 2: [IN:  BB3(0), OUT:  BB1(0) ]
 il_seq_point il: 0x0
 nop
 il_seq_point il: 0x1
 i8const R17 <- [4320347896]
 iconst R18 <- [16]
 move R20 <- R17
 move R21 <- R18
 call R19 <- [(wrapper alloc) object object:AllocSmall (intptr,intptr)] [%rdi <- R20] [%rsi <- R21] clobbers: c
 not_null R19
 nop
 move R22 <- R19
 move R23 <- R22
 nop
 move R24 <- R23
 move R25 <- R24
 nop
 nop
 nop
 il_seq_point il: 0x6, nonempty-stack
 move R16 <- R19
 il_seq_point il: 0x7
 move R26 <- R16
 move R27 <- R16
 move R29 <- R27
 not_null R27
 load_membase R30 <- [R27 + 0x0]
 call_membase R28 <- [R30 + 0x68] [byte modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWinAmbiguous:GetByte ()] [%rdi <- R29] clobbers: c
 il_seq_point il: 0xe, nonempty-stack
 move R31 <- R16
 move R33 <- R31
 not_null R31
 load_membase R34 <- [R31 + 0x0]
 call_membase R32 <- [R34 + 0x68] [byte modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWinAmbiguous:GetByte ()] [%rdi <- R33] clobbers: c
 il_seq_point il: 0x14, nonempty-stack
 move R36 <- R26
 move R37 <- R28
 move R38 <- R32
 not_null R26
 load_membase R39 <- [R26 + 0x0]
 call_membase R35 <- [R39 + 0x90] [byte modopt(System.Runtime.CompilerServices.IsLong) modopt(System.Runtime.CompilerServices.IsConst) Metadata.LeastModoptsWin:M (byte,byte)] [%rdi <- R36] [%rsi <- R37] [%rdx <- R38] clobbers: c
 il_seq_point il: 0x19, nonempty-stack
 move R40 <- R35
 voidcall [void System.Console:Write (int)] [%rdi <- R40] clobbers: c
 il_seq_point il: 0x1e, nonempty-stack
 il_seq_point il: 0x1e
 nop
 il_seq_point il: 0x1f
 br [B1]
```

So it looks like method-to-ir picked the wrong method for the call to `M` (has both `IsLong` and `IsConst`, should've been the one with just `IsConst`)

**Comment by lambdageek** [comment]
This boils down to a `mono_metadata_signature_equal` comparison (when searching for the appropriate `M` method in the metadata, given its token) where we're ignoring the custom modifiers and returning TRUE for `byte modopt(IsConst)` vs `byte modopt(IsLong)  modopt (IsConst)` due to the work in #11134.

So it's all related.

I wonder if we need a strict (custom modifier respecting) equality comparison for the runtime and something less precise for the binary formatter serialization.

**Comment by lambdageek** [comment]
Have to be careful about fixing this without breaking #10945 again - both issues depend right now on conflicting type equivalence checking - this issue wants cmods considered, but 10945 wants the cmods ignored.  So any fix here has to be vetted against 10945 (which unfortunately we don't have a concise standalone reproduction for yet)

**Comment by lambdageek** [comment]
At least one of the problems here is that `mono_metadata_type_dup_with_cmods` doesn't consider the case where both the type and the cmod source both have custom modifiers.  This is actually something that Roslyn tests do.  we have cases where a generic method signature `void Test (T modopt(IsConst) t)` is instantiated with `int32 modopt(IsLong)` for T, and the test expects to get `int32 modopt (IsLong) modopt (IsConst)` but `type_dup_with_cmods` just returns `int32 modopt (IsConst)`.

Its straightforward enough to add a concatenation case to `type_dup_with_cmods` _except_ if `mono_type_get_cmods (o)->image != mono_type_get_cmods (cmod_source)->image`.  our `MonoCustomModContainer` stores a single image and an array of tokens.  It simply cannot represent a type with custom modifiers from more than one  image.  But this actually happens in some Roslyn tests (and it could happen in real life, too).

So we need a fancier `MonoCustomModContainer`

**Comment by lambdageek** [comment]
New sub-problem:  Mono doesn't inflate custom modifiers.  .NET IL can have things like this:
```
    .method public hidebysig newslot virtual
            instance void  Test(!T1 modopt(valuetype [mscorlib]System.Nullable`1<!T1>) t1) cil managed 
```

Note that `T1` is both the the of an argument, and also part of the type of the modifier of the argument.   Once I make mono's signature comparison stricter about respecting modifiers, overriding this method in an instantiation doesn't work anymore because we don't inflate the modifier and things fail to match up.

Full notes at https://gist.github.com/lambdageek/cdb2b5ea69bcce3debce410b03a7e601
