### ISSUE TITLE
[cxx] Bypass automake linker detection for .cpp files

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#12435]
Once we begin writing Mono code in C++, we will be using a subset of C++ that does not require linking with the C++ runtime library  (libstdc++ or libc++).  As a result we will have to fight with the [automake automatic linker selection](https://www.gnu.org/software/automake/manual/html_node/How-the-Linker-is-Chosen.html)

This is different from the existing work we've done:
* The existing work was to compile `.c` files with a c++ compiler but link with a C linker, without the C++ library.

   This doesn't step on automake's toes too much.  We just pass some extra CFLAGS to gcc or clang to pick the correct language.

* The new work is to feed `.cpp` files to a c++ compiler, but link with a C linker, without the C++ library.

   This is more annoying - just adding `.cpp` files to `target_SOURCES` will make `target_LINK` be `$(CXXLINK) args...`.  So we have to do something.

We could just set `target_LINK=$(CXXLINK) args...` ourselves, *but* `args...` is actually pretty finnicky - we have to make sure to pick up all the relevant (general and target specific) `_LDADD` and `_LIBADD` and so forth, all in the correct order.

It would be better if we didn't have to maintain `target_LINK` ourselves.  But it's really not clear how.  

One option, perhaps, is to write our new C++ code in `.c` files and continue lying to automake.  But this is unfriendly to new contributors, to editors that do syntax-highlighting based on file extension, etc...

Another option might be to set `CXXLINK` to `LINK` somewhere (configure.ac? in the makefile?).  But then we'd have to make sure to add `-lc++` or `-lstdc++` when we really do need the C++ library (for example if LLVM is enabled).

We need some better options.

**Comment by jaykrell** [comment]
Why does FOO_LINK=$(LINK) lose flags? I'll try it.

**Comment by lambdageek** [comment]
I made a skeleton autotools project https://github.com/lambdageek/auto-blah-cpp

The problem is that 

```
foo_LINK=$(CXXLINK)
```
will not pick up `foo_LDFLAGS (although it does pick up `foo_LDADD`)

You need
```
foo_LINK=$(CXXLINK) $(foo_LDFLAGS)
```

For libtool convenience libraries like `libmeh.la`, setting the linker with
```
libmeh_la_LINK=$(CXXLINK)
```
won't pick up target specific `_LDFLAGS` (although it will get `_LIBADD`)
```
libmeh_la_LINK=$(CXXLINK) $(libmeh_la_LDFLAGS)
```

Also you probably need to pass target-specific `CFLAGS` and `CXXFLAGS`, because the automatic link line is like this:

```
foo_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(foo_LDFLAGS) $(LDFLAGS) -o $@
```

and it's then called with:

```
	$(AM_V_GEN)$(foo_LINK) $(foo_OBJECTS) $(foo_LDADD) $(LIBS)
```

**Comment by lambdageek** [comment]
```
CXXLD=$(CCLD)
```
will do the correct (evil) thing because all the CXXLINK commands ultimately boil down to a call to CXXLD.

Maybe this is okay, actually - it's global (I only tried setting it in Makefile.am, which is a tad inconvenient, but maybe setting it in configure.ac would work too), but we can leave it alone for --enable-llvm builds.
