### ISSUE TITLE
Add mono.wasm support for threads

### ISSUE THREAD

**Issue by danroth27** [mono/mono#12453]
The WebAssembly community group has been [working on a proposal for threads](https://github.com/WebAssembly/threads). Chrome 70 added support for threads: https://developers.google.com/web/updates/2018/10/wasm-threads presumably based on the community group's proposal. We should track the progress on threads in the community group and in the browsers and implement support for threads in mono.wasm when appropriate.

@marek-safar @lewing @stevesandersonms

**Comment by migueldeicaza** [comment]
I added this card to the Project/Wasm board.

**Comment by kjpou1** [comment]
PR: https://github.com/mono/mono/pull/15504
PR: https://github.com/mono/mono/pull/15389

**Comment by DierkDroth** [comment]
I'm trying to understand where we're at regarding WASM support for Blazor and would have thought that this very feature would be important for Blazor on WASM. Given that Blazor is supposed to have WASM support by May 2020 I find it concerning that there hasn't been much progress recently on this particular issue. 

Could anyone please shed some light? What am I missing?

**Comment by chucker** [comment]
There isn’t even widespread WASM threading support in browsers today, so Blazor WebAssembly 1.0 in May will almost certainly not ship with production support for threading.

**Comment by tomasfabian** [comment]
I tried to connect to my pub/sub notifications via .Net Standard package StackExchange.Redis in a Blazor WASM 3.2 app. I received the following error:
_System.NotSupportedException: Cannot start threads on this runtime_

Is it possible to use packages which a relying on thread pool in some way, or will it be integrated only later with webworkers? I enabled them as an Experimental feature in Chrome.
If it is possible, is there a [guidance how to call them](https://github.com/dotnet/aspnetcore/issues/14253)? 

It looks like that the TPL is somehow integrated with the JavaScript single threaded nature. This does not throw an exception:
```C#
var task = new System.Threading.Tasks.TaskFactory<int>().StartNew(() => 42);
```

but this throws the above mentioned exception:
```C#
new System.Threading.Thread(() => { }).Start();
```` 
Is this only an issue with Thread Pool scheduling? Thank you

**Comment by maxim-saplin** [comment]
@tomasfabian https://github.com/dotnet/aspnetcore/issues/17730

**Comment by tomasfabian** [comment]
@maxim-saplin thx. I'm sorry in case I'm in a correct forum. I feel like in a vicious circle :)
Quote from the forum you posted me:

> This is blocked on mono/mono#12453

**Comment by chucker** [comment]
@tomasfabian 

* regardless of you enabling WASM threading in Chrome, it simply isn't implemented in Mono WASM, much less is there any high-level support for it in Blazor. This issue exists to track that general topic in the long run. My guess is it won't happen until .NET 6 in November 2021, as the [Blazor Roadmap for .NET 5](https://github.com/dotnet/aspnetcore/issues/21514) _doesn't_ mention it.

* I'm not sure what you're trying to accomplish with Redis. If you're trying to store and retrieve data inside a user's browser, consider something like https://github.com/Blazored/LocalStorage. If you have a Redis instance running somewhere, you probably want to write an API to access it via HTTP.

**Comment by jeromelaban** [comment]
@chucker WebAssembly threading is implemented in mono wasm at this time, though it's still very much a work in progress. If you want to experiment with it [the Uno.Wasm.Bootstrap supports it](https://github.com/unoplatform/uno.wasm.bootstrap#threads-support).

Some cases are not yet supported properly, such as some threading APIs are still queued on the main thread.

**Comment by tomasfabian** [comment]
@chucker in short: I wanted to use Redis pub/sub ISubscriber 

@jeromelaban I already experimented with Uno.Wasm.Bootstrap. I was able to convert a Console app with threading to WASM. But in Blazor it didn't work, I got the same results as without it. 
That's why I ended here.

**Comment by przemo098** [comment]
It seems that this topic is dead from almost 2 years...
Are there any updates?

**Comment by ivan-prodanov** [comment]
@przemo098 yeah, threads are available in the master branch in dotnet/runtime.

**Comment by bruno-garcia** [comment]
I've tested the [Sentry SDK with Blazor Wasm](https://github.com/getsentry/sentry-dotnet/tree/42368a1a9e2f480b3cf022d103b9f678c86a0665/samples/Sentry.Samples.AspNetCore.Blazor.Wasm) and it successfully submits events on the background. The Sentry SDK uses `Task.Run` under the hood. I assume this was powered by wasm threads, isn't that the case?

I tried on .NET 5 Blazor Wasm, .NET SDK 5.0.100.

**Comment by lewing** [comment]
@bruno-garcia no threads involved. While is it possible to build the runtime with experimental thread support, 3.2-5.0 rely on async task scheduling to make things work.

**Comment by bruno-garcia** [comment]
I thought that might be the case, but since early attempts with Blazor didn't work, I thought it was the threads support landing.
Thanks for clarifying. Works like a charm for that use case anyway, I'm a happy camper.

**Comment by Xyncgas** [comment]
imagine if in the future we just have one platform for all the language to target, a browser that is your operating system but not chromeOS, people can still run their native code in their own bare metal I just really want to see wasm support threads and it's basically another 20~30% closer to this goal

**Comment by Xyncgas** [comment]
Just the performance gain being able to use multiple core makes it so much powerful.
I wonder if microsoft is intentionally stalling the blazor project because it might be too awesome idk

**Comment by Xyncgas** [comment]
Or if I can use blazor without javascript or the browser it would be awesome too

**Comment by kristof12345** [comment]
Any update on this? Is this planned for .NET 7?

**Comment by Xyncgas** [comment]
blazor should support workers out of the box, to run something in another worker, just make a generic glue code that let workers to call back functions in .net, wait but it still runs in a single thread, ok we need webassembly threads, other wise unless roslyn somehow decompiles dll into javascript and run inside javascriptVM, we can't use workers or threads

**Comment by Xyncgas** [comment]
I think if in general we can promise something being a pure function the browser should run it inside a thread pool if it's hot

**Comment by mattgenious** [comment]
Looking to see what progress is happening on this front.
I have joined the webassembly community group and am trying to figure out why it seems to have stalled.

In https://github.com/WebAssembly/threads/issues/163 @tlively and @conrad-watt explained to me that testing is the only thing missing on their part to move the spec to phase 3 (of 5 described here https://github.com/WebAssembly/meetings/blob/main/process/phases.md ) and as @Xyncgas correctly mentions most major browsers have already implemented versions of the spec.

So what is the next step in the development of thread support on mono.wasm?

**Comment by Xyncgas** [comment]
> Looking to see what progress is happening on this front. I have joined the webassembly community group and am trying to figure out why it seems to have stalled.
> 
> In [WebAssembly/threads#163](https://github.com/WebAssembly/threads/issues/163) @tlively and @conrad-watt explained to me that testing is the only thing missing on their part to move the spec to phase 3 (of 5 described here https://github.com/WebAssembly/meetings/blob/main/process/phases.md ) and as @Xyncgas correctly mentions most major browsers have already implemented versions of the spec.
> 
> So what is the next step in the development of thread support on mono.wasm?

I've never said that, I am fairly new on this topic

**Comment by mattgenious** [comment]
Any progress here?

Also any thoughts on how this might be coupled with the aspnetcore implementation of Blazor to improve startup time and UI locking when loading a Blazor webassembly application?

I am writing here because I have an business interest in Blazor Webassembly load times.
