### ISSUE TITLE
Why call c native function with string args from c# cost so many time?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#12463]
I make the test for c# side call c method:
case1:
c# side:
 test(1,2);

c side:
 test(int a, int b)

case 2:
c# side:
 test("abc", 1, 2);

c side:
 test(MonoString* a, int b, int c);

call 1000000 times each function and the result is:
case1 cost 1800ms
case2 cost 190ms

Why case1 take so many time?

test environment:
mono 5.18.0.225 aot_interp mode
ipad mini2 with ios 11

**Comment by migueldeicaza** [comment]
Please provide a complete test case, and configuration options.
