### ISSUE TITLE
Path.GetTemp* isn't affected by change in tmpdir at runtime, differs from what dotnet does

### ISSUE THREAD

**Issue by radical** [mono/mono#12481]
## Behavior with dotnet:

```
$ dotnet  run

new tmp file: /var/folders/7c/zpmy8k_d4d1grky_s154kk640000gp/T/tmp24c3Bg.tmp
After changing tmpdir.
new tmp file: /tmp/foo-test/tmpFUzBPb.tmp
```

## Behavior with mono:

```
$ csc Program.cs && mono Program.exe

new tmp file: /var/folders/7c/zpmy8k_d4d1grky_s154kk640000gp/T/tmp609b8ec9.tmp
After changing tmpdir.
new tmp file: /var/folders/7c/zpmy8k_d4d1grky_s154kk640000gp/T/tmpe88e182.tmp
```

Mono is caching the temp directory path and so `Path.GetTemp*` is not affected by change in the environment variables.

### Test code
```
using System;
using System.IO;

class Program
{
	static void Main(string[] args)
	{
		Console.WriteLine ($"new tmp file: {Path.GetTempFileName()}");

		Directory.CreateDirectory("/tmp/foo-test");
		foreach (var envvar in new string[] {"TMPDIR", "TMP", "TEMP"})
			Environment.SetEnvironmentVariable (envvar, "/tmp/foo-test");

		Console.WriteLine ($"After changing tmpdir.\nnew tmp file: {Path.GetTempFileName()}");
	}
}

```

/cc @marek-safar

**Comment by steveisok** [comment]
In mono/eglib/gmisc-unix.c (and win32 too):

```c
static const char *tmp_dir;

static pthread_mutex_t tmp_lock = PTHREAD_MUTEX_INITIALIZER;

const gchar *
g_get_tmp_dir (void)
{
	if (tmp_dir == NULL){
		pthread_mutex_lock (&tmp_lock);
		if (tmp_dir == NULL){
			tmp_dir = g_getenv ("TMPDIR");
			if (tmp_dir == NULL){
				tmp_dir = g_getenv ("TMP");
				if (tmp_dir == NULL){
					tmp_dir = g_getenv ("TEMP");
					if (tmp_dir == NULL)
						tmp_dir = "/tmp";
				}
			}
		}
		pthread_mutex_unlock (&tmp_lock);
	}
	return tmp_dir;
}
```

Is there a reason why tmp_dir is written to once?

**Comment by steveisok** [comment]
Not an everyday C guy.... So, if I'm looking at things correctly, the return value from g_getenv needs to be freed by the caller.  If that's correct, then it *seems* like the existing tmp_dir will never be freed.

If we make tmp_dir local, then is it correct that the callers of g_get_tmp_dir also must free the return value?  Is that right?

**Comment by lewurm** [comment]
Ugh... I think a general assumption in the unix world is that environment variables are _not_ changing during the lifetime of a process. The code in `gmisc-unix.c` takes advantage of that assumption and caches the retrieved value since `getenv ()` can be slow.

Unfortunately we have a _lot_ of places in the Mono runtime where we assume environment variables aren't changing during the process lifetime, so I'm not sure if we want to get into that rabbit hole and fix that.

Except for the repro you provided, does it actually break something?

**Comment by baulig** [comment]
I fully agree with what @lewurm wrote above.  In case it actually does break something, I would suggest to add some Mono-specific internal method to force-modify the temp path.

Or in other words, let's keep the current code that's caching the value - and if need be add some kind of a "force override" mechanism.

**Comment by radical** [comment]
[This](https://github.com/mono/msbuild/commit/d05c49c6c7852397dda56d42acc63b8454c58933) is how it breaks and is worked around. I wasn't sure whether this should be fixed in mono.

**Comment by lewurm** [comment]
since there is a workaround (easily) possible in msbuild I'll close this issue
