### ISSUE TITLE
[wasm] make aot-sample not working

### ISSUE THREAD

**Issue by jacano** [mono/mono#12491]
## Steps to Reproduce

1. Follow instructions from: https://github.com/mono/mono/blob/master/sdks/wasm/README.md
2. `make aot-sample`

### Current Behavior
`make: *** No rule to make target 'bug.exe', needed by 'aot-sample'.  Stop.`

### Expected Behavior
Get the aot-sample built in bin/aot-sample

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

Using latest version from master:
`9d697e9c5f0 (HEAD -> master, origin/master, origin/HEAD) Don't hardcode "mscorlib" use MONO_ASSEMLBY_CORLIB_NAME or mono_is_corlib_image`

Not sure, but this target is used but undefined here: https://github.com/mono/mono/commit/f24d652d567c4611f9b4e3095be4e2a1a2ab23a4#diff-2f161238e8367fb46cf04ce102f524beR153

**Comment by kjpou1** [comment]
@jacano 

That target is used only for development purposes for right now.

Try using the:
```
make -C sdks/wasm build-aot-all
make -C sdks/wasm run-aot-all
```

The should already work:

```
make -C sdks/wasm run-aot-mini
make -C sdks/wasm run-aot-System.Core
```

We will need to create a sample to go along with that option.

**Comment by vargaz** [comment]
Will be fixed by:
https://github.com/mono/mono/pull/12512

**Comment by kjpou1** [comment]
fixed by: https://github.com/mono/mono/pull/12512
