### ISSUE TITLE
[WASM] The linker is disabled for non-AOT packager

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#12500]
The packager does not provide a `--linker` option when AOT is not enabled.

Also, the monolinker.exe file is placed in the larger artifacts file (e.g. wasm-release-Linux-292c674043d9b319c92c2c2a82e245539eec7081.zip), which is not used for interpreter build. It would be easier if it were in the smaller artifact file (mono-wasm-292c674043d.zip)

**Version Used**: mono master 292c674043d9b319c92c2c2a82e245539eec7081

**Comment by vargaz** [comment]
This is already implemented by 4d57a5786ac06c8f1ea5ff0bcc2d47a0a3893b91, there is now a --linker option.

**Comment by vargaz** [comment]
Note that this will only link the class libs, it will not link out the runtime code, that will be implemented later.

**Comment by jeromelaban** [comment]
Agreed. There's only the fact that the linker is in the larger artifact then, thanks!

The reason I'm asking this is that the part of the packager that produces interpreter layouts does not use ninja, and adding the linker does. I'm trying to avoid the use of ninja on windows for now, until msbuild is used.

**Comment by vargaz** [comment]
ninja is used to handle the dependencies during the build, the non-ninja version can only do simple things like coping files around, so the more complicated options will require ninja.

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/12512

**Comment by kjpou1** [comment]
Fixed by: https://github.com/mono/mono/pull/12512
