### ISSUE TITLE
Microsoft.SqlServer.Management.Smo.Wmi not supported

### ISSUE THREAD

**Issue by Redirts** [mono/mono#12524]
## Steps to Reproduce

C# program:

using Microsoft.SqlServer.Management.Smo.Wmi;
...
ManagedComputer mc = new ManagedComputer(server, "username", "password", ProviderArchitecture.Use64bit);
...

The aim is to obtain an object with a list of server instances (SQL) on a windows server so that we can then run a query against each one.

The run directory has Microsoft.SqlServer.Smo.DLL and Microsoft.SqlServer.SqlWmiManagement.dll

### Current Behavior

At line ManagedComputer mc = new ManagedComputer(server, "username", "password", ProviderArchitecture.Use64bit) I get:

Error:
The method or operation is not implemented.  at Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer.Init (System.String machineName) [0x00059] in <2689ca8edc2c41258b00c6ab4e735e
fc>:0
  at Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer..ctor (System.String machineName, System.String userName, System.String password, Microsoft.SqlServer.Management.Smo.Wmi.ProviderArchitect
ure providerArchitecture) [0x0004f] in <2689ca8edc2c41258b00c6ab4e735efc>:0
  at ConsoleApp1.Kernel.doIt () [0x00045] in <9467f890caab47bc9e55d8d1abeb0988>:0

### Expected Behavior

Obtain back an object from the command:
ManagedComputer mc = new ManagedComputer(server, "username", "password", ProviderArchitecture.Use64bit);

## On which platforms did you notice this

[ ] macOS
[X] Linux (CentOS 7)
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.18.0.240 (tarball Thu Jan 17 08:37:29 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

## Stacktrace

The method or operation is not implemented.  at Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer.Init (System.String machineName) [0x00059] in <2689ca8edc2c41258b00c6ab4e735e
fc>:0
  at Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer..ctor (System.String machineName, System.String userName, System.String password, Microsoft.SqlServer.Management.Smo.Wmi.ProviderArchitect
ure providerArchitecture) [0x0004f] in <2689ca8edc2c41258b00c6ab4e735efc>:0
  at ConsoleApp1.Kernel.doIt () [0x00045] in <9467f890caab47bc9e55d8d1abeb0988>:0

Any help appreciated.

**Comment by marek-safar** [comment]
Microsoft.SqlServer.Smo.dll is Windows specific assembly which won't work cross-platform
