### ISSUE TITLE
StringComparers' GetHashCode yield unexpected results when comparing null characters string and empty string

### ISSUE THREAD

**Issue by Gnbrkm41** [mono/mono#12522]
Related: https://github.com/dotnet/corefx/issues/34662

[Docs on string class](https://docs.microsoft.com/en-us/dotnet/api/system.string?view=netframework-4.7.2#strings-and-embedded-null-characters) state that:
`Null characters are ignored when performing culture-sensitive comparisons between two strings, including comparisons using the invariant culture.`

Also, [docs on IEqualityComparer interface](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1.gethashcode?view=netframework-4.7.2#notes-to-implementers)  state that: `Implementations are required to ensure that if the Equals(T, T) method returns true for two objects x and y, then the value returned by the GetHashCode(T) method for x must equal the value returned for y.`

However, when comparing `string.Empty` and string made of null characters, GetHashCode methods of StringComparers (except StringComparer.Ordinal) seems to yield conflicting results when compared with Equals method.

Code used to test:
```cs
string empty = string.Empty;
string nullChars = new string('\0', 10);

StringComparer ordinal = StringComparer.Ordinal;
StringComparer ordinalIgnoreCase = StringComparer.OrdinalIgnoreCase;
StringComparer invariant = StringComparer.InvariantCulture;
StringComparer invariantIgnoreCase = StringComparer.InvariantCultureIgnoreCase;
StringComparer current = StringComparer.CurrentCulture;
StringComparer currentIgnoreCase = StringComparer.CurrentCultureIgnoreCase;

var separator = new string('-', 20);

Console.WriteLine($"Equality comparison using InvariantCulture.Equals: {invariant.Equals(empty, nullChars)}");
Console.WriteLine($"Is the hashcode generated using StringComparer the same?: {invariant.GetHashCode(empty) == invariant.GetHashCode(nullChars)}");
Console.WriteLine($"Hashcode of String.Empty and null characters: {invariant.GetHashCode(empty)}, {invariant.GetHashCode(nullChars)}");
Console.WriteLine(separator);
Console.WriteLine($"Equality comparison using InvariantCultureIgnoreCase.Equals: {invariantIgnoreCase.Equals(empty, nullChars)}");
Console.WriteLine($"Is the hashcode generated the same?: {invariantIgnoreCase.GetHashCode(empty) == invariantIgnoreCase.GetHashCode(nullChars)}");
Console.WriteLine($"Hashcode of String.Empty and null characters: {invariantIgnoreCase.GetHashCode(empty)}, {invariantIgnoreCase.GetHashCode(nullChars)}");
Console.WriteLine(separator);
Console.WriteLine($"Equality comparison using Ordinal.Equals: {ordinal.Equals(empty, nullChars)}");
Console.WriteLine($"Is the hashcode generated the same?: {ordinal.GetHashCode(empty) == ordinal.GetHashCode(nullChars)}");
Console.WriteLine($"Hashcode of String.Empty and null characters: {ordinal.GetHashCode(empty)}, {ordinal.GetHashCode(nullChars)}");
Console.WriteLine(separator);
Console.WriteLine($"Equality comparison using OrdinalIgnoreCase.Equals: {ordinalIgnoreCase.Equals(empty, nullChars)}");
Console.WriteLine($"Is the hashcode generated the same?: {ordinalIgnoreCase.GetHashCode(empty) == ordinalIgnoreCase.GetHashCode(nullChars)}");
Console.WriteLine($"Hashcode of String.Empty and null characters: {ordinalIgnoreCase.GetHashCode(empty)}, {ordinalIgnoreCase.GetHashCode(nullChars)}");
Console.WriteLine(separator);
Console.WriteLine();
Console.WriteLine($"Current Culture: {System.Globalization.CultureInfo.CurrentCulture}");
Console.WriteLine(separator);
Console.WriteLine($"Equality comparison using CurrentCulture.Equals: {current.Equals(empty, nullChars)}");
Console.WriteLine($"Is the hashcode generated the same?: {current.GetHashCode(empty) == current.GetHashCode(nullChars)}");
Console.WriteLine($"Hashcode of String.Empty and null characters: {current.GetHashCode(empty)}, {current.GetHashCode(nullChars)}");
Console.WriteLine(separator);
Console.WriteLine($"Equality comparison using CurrentCultureIgnoreCase.Equals: {currentIgnoreCase.Equals(empty, nullChars)}");
Console.WriteLine($"Is the hashcode generated the same?: {currentIgnoreCase.GetHashCode(empty) == currentIgnoreCase.GetHashCode(nullChars)}");
Console.WriteLine($"Hashcode of String.Empty and null characters: {currentIgnoreCase.GetHashCode(empty)}, {currentIgnoreCase.GetHashCode(nullChars)}");
```
Result:
![mono](https://user-images.githubusercontent.com/42944058/51428143-9930a780-1c43-11e9-917c-cc212bcbef82.png)
Somewhat interestingly, StringComparer.Ordinal seems to be behaving as expected; however for other cases values returned from GetHashCode does not match the behaviour of Equals method.

Similar problem happens in .NET Core and .NET Framework as well, but all three implementations do not behave the same.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[v] Windows

**Version Used**: 5.18.0

**Comment by Gnbrkm41** [comment]
Pasted as text instead of image.
```
Equality comparison using InvariantCulture.Equals: True
Is the hashcode generated using StringComparer the same?: False
Hashcode of String.Empty and null characters: 0, 15
--------------------
Equality comparison using InvariantCultureIgnoreCase.Equals: True
Is the hashcode generated the same?: False
Hashcode of String.Empty and null characters: 0, 15
--------------------
Equality comparison using Ordinal.Equals: False
Is the hashcode generated the same?: False
Hashcode of String.Empty and null characters: -1235634588, 1666813079
--------------------
Equality comparison using OrdinalIgnoreCase.Equals: False
Is the hashcode generated the same?: True
Hashcode of String.Empty and null characters: 0, 0
--------------------

Current Culture: ko-KR
--------------------
Equality comparison using CurrentCulture.Equals: True
Is the hashcode generated the same?: False
Hashcode of String.Empty and null characters: 0, 15
--------------------
Equality comparison using CurrentCultureIgnoreCase.Equals: True
Is the hashcode generated the same?: False
Hashcode of String.Empty and null characters: 0, 15
```
Just as a side note, it behaves the same on both x64 and x86.

**Comment by MaximLipnin** [comment]
<table border=0 cellpadding=0 cellspacing=0 width=1043 style='border-collapse:
 collapse;table-layout:fixed;width:781pt'>
 <col width=207 style='mso-width-source:userset;mso-width-alt:7367;width:155pt'>
 <col width=211 style='mso-width-source:userset;mso-width-alt:7509;width:158pt'>
 <col width=98 style='mso-width-source:userset;mso-width-alt:3470;width:73pt'>
 <col width=116 style='mso-width-source:userset;mso-width-alt:4124;width:87pt'>
 <col width=411 style='mso-width-source:userset;mso-width-alt:14620;width:308pt'>
 <tr height=19 style='height:14.4pt'>
  <td rowspan=2 height=38 class=xl66 width=207 style='height:28.8pt;width:155pt'>Culture</td>
  <td rowspan=2 class=xl66 width=211 style='width:158pt'>Are empty string and
  '\0' equal?</td>
  <td colspan=2 class=xl65 width=214 style='width:160pt'>Hashcode</td>
  <td class=xl66 width=411 style='width:308pt'>Source code (Mono 6.1)</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 class=xl65 style='height:14.4pt'>empty string</td>
  <td class=xl65>'\0'</td>
  <td></td>
 </tr>
 <tr height=24 style='height:18.0pt'>
  <td colspan=4 height=24 class=xl68 style='height:18.0pt'><i>Net Core</i></td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>InvariantCulture</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>1440101716</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>InvariantCultureIgnoreCase</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>1440101716</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>Ordinal</td>
  <td align=center>FALSE</td>
  <td align=right>464195944</td>
  <td align=right>2084451177</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>OrdinalIgnoreCase</td>
  <td align=center>FALSE</td>
  <td align=right>464195944</td>
  <td align=right>2084451177</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>CurrentCulture(en-US)</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>1440101716</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>CurrentCultureIgnoreCase(en-US)</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>1440101716</td>
  <td></td>
 </tr>
 <tr height=24 style='height:18.0pt'>
  <td colspan=4 height=24 class=xl68 style='height:18.0pt'><i>Mono 5.18</i>/<font
  class="font8"><i><b>6.1</b></i></font></td>
  <td></td>
 </tr>
 <tr height=38 style='height:28.8pt'>
  <td height=38 style='height:28.8pt'>InvariantCulture</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>15</td>
  <td class=xl67 width=411 style='width:308pt'><a
  href="https://github.com/mono/mono/blob/master/mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127"
  target="_parent">mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127</a></td>
 </tr>
 <tr height=38 style='height:28.8pt'>
  <td height=38 style='height:28.8pt'>InvariantCultureIgnoreCase</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>15</td>
  <td class=xl67 width=411 style='width:308pt'><a
  href="https://github.com/mono/mono/blob/master/mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127"
  target="_parent">mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127</a></td>
 </tr>
 <tr height=38 style='height:28.8pt'>
  <td height=38 style='height:28.8pt'>Ordinal</td>
  <td align=center>FALSE</td>
  <td align=right>-1235634588</td>
  <td align=right>1666813079</td>
  <td class=xl67 width=411 style='width:308pt'><a
  href="https://github.com/mono/corefx/blob/master/src/Common/src/CoreLib/System/String.Comparison.cs#L858"
  target="_parent">src/Common/src/CoreLib/System/String.Comparison.cs#L858</a></td>
 </tr>
 <tr height=38 style='height:28.8pt'>
  <td height=38 style='height:28.8pt'>OrdinalIgnoreCase</td>
  <td align=center>FALSE</td>
  <td>0/<font class="font6"><b>-1235634588</b></font></td>
  <td>0/<font class="font6"><b>1666813079</b></font></td>
  <td class=xl67 width=411 style='width:308pt'><a
  href="https://github.com/mono/corefx/blob/master/src/Common/src/CoreLib/System/Globalization/CompareInfo.cs#L1232"
  target="_parent">src/Common/src/CoreLib/System/Globalization/CompareInfo.cs#L1232</a></td>
 </tr>
 <tr height=38 style='height:28.8pt'>
  <td height=38 style='height:28.8pt'>CurrentCulture(en-US)</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>15</td>
  <td class=xl67 width=411 style='width:308pt'><a
  href="https://github.com/mono/mono/blob/master/mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127"
  target="_parent">mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127</a></td>
 </tr>
 <tr height=38 style='height:28.8pt'>
  <td height=38 style='height:28.8pt'>CurrentCultureIgnoreCase(en-US)</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>15</td>
  <td class=xl67 width=411 style='width:308pt'><a
  href="https://github.com/mono/mono/blob/master/mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127"
  target="_parent">mcs/class/corlib/Mono.Globalization.Unicode/SortKey.cs#L127</a></td>
 </tr>
 <tr height=24 style='height:18.0pt'>
  <td colspan=4 height=24 class=xl68 style='height:18.0pt'><i>Net FX</i></td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>InvariantCulture</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>-1644535362</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>InvariantCultureIgnoreCase</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>-1644535362</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>Ordinal</td>
  <td align=center>FALSE</td>
  <td align=right>757602046</td>
  <td align=right>-692740997</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>OrdinalIgnoreCase</td>
  <td align=center>FALSE</td>
  <td align=right>5381</td>
  <td align=right>5381</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>CurrentCulture(en-US)</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>-1644535362</td>
  <td></td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'>CurrentCultureIgnoreCase(en-US)</td>
  <td align=center>TRUE</td>
  <td align=right>0</td>
  <td align=right>-1644535362</td>
  <td></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=207 style='width:155pt'></td>
  <td width=211 style='width:158pt'></td>
  <td width=98 style='width:73pt'></td>
  <td width=116 style='width:87pt'></td>
  <td width=411 style='width:308pt'></td>
 </tr>
 <![endif]>
</table>
