### ISSUE TITLE
SslStream does not implement some connection-info properties (CipherStrength).

### ISSUE THREAD

**Issue by Octoate** [mono/mono#12552]
Hi,
I am currently having problems to run a project under Linux. The project itself contains an ASP.NET Core webserver to provide a REST API, SSL usage is enabled. It works on my Windows machine without any problems, but on Linux it throws a System.NotImplementedException on any access. It seems that the Mono.Net.Security.SslStream.CipherStrength is not implemented by the current Mono version but used by Kestrel.

## Steps to Reproduce

1. Integrate an ASP.NET Core webserver into your .NET 4.7 project.
2. Enable SSL certificate usage.
3. Run the program with Mono
4. Open a page of the webserver in the browser

### Current Behavior

On any access to the webserver, you will get the following NotImplementedException:

`
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
System.NotImplementedException: The method or operation is not implemented.
  at Mono.Net.Security.MobileAuthenticatedStream.get_CipherStrength () [0x00000] in <707293861b9c49cf8f99c3b74fe2930c>:0
  at System.Net.Security.SslStream.get_CipherStrength () [0x00006] in <707293861b9c49cf8f99c3b74fe2930c>:0
  at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync (Microsoft.AspNetCore.Server. <708a61b06ae647a09457b7bb52b351ad>:0
`

### Expected Behavior

The code should just work without throwing an exception.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.16.0 (makepkg/bb3ae37d71a Tue Dec 18 03:32:00 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

## Stacktrace

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
System.NotImplementedException: The method or operation is not implemented.
  at Mono.Net.Security.MobileAuthenticatedStream.get_CipherStrength () [0x00000] in <707293861b9c49cf8f99c3b74fe2930c>:0
  at System.Net.Security.SslStream.get_CipherStrength () [0x00006] in <707293861b9c49cf8f99c3b74fe2930c>:0
  at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync (Microsoft.AspNetCore.Server. <708a61b06ae647a09457b7bb52b351ad>:0
```

**Comment by baulig** [comment]
We never implemented those properties.

**Comment by baulig** [comment]
So, adding an API to retrieve the cipher algorithm from the native backend - that literally takes like half an hour.

The returned cipher algorithm uniquely and unambiguously defines the cipher strength as well as the other "Connection Info" properties.  But a mapping table will be needed.

A design decision must be made as to where and how this mapping table should be implemented - should we try to reuse some of the relevant CoreFx code or duplicate it in Mono?

Since the algorithm id is defined by the TLS spec, the general logic of mapping algorithm id to "Connection Info" properties (which include cipher strength and others) is reusable across all implementations.

**Comment by migueldeicaza** [comment]
Can you link to the CoreFX code?

**Comment by baulig** [comment]
Trying to find it.

**Comment by baulig** [comment]
Okay, here it is: https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslConnectionInfo.OSX.cs.

This won't work out-of-the-box, we'd have to replace their `SafeSslHandle` and `Interop.AppleCrypto.SslGetProtocolVersion()` / `Interop.AppleCrypto.SslGetCipherSuite()` with custom APIs.  The remapping table at the end of that file looks reusable, though.

**Comment by baulig** [comment]
Working on it: https://github.com/mono/mono/pull/12687.

**Comment by Octoate** [comment]
Thanks a lot 👍!
