### ISSUE TITLE
Cannot marshal ptr to struct (Marshal.PtrToStructure) with embedded generic struct

### ISSUE THREAD

**Issue by brianradunity** [mono/mono#12568]
[Program.zip](https://github.com/mono/mono/files/2784160/Program.zip)

## Steps to Reproduce

1. Compile and run attached code with current Mono.
2. Notice error messages:
marshaling type 15 not implemented
* Assertion: should not be reached at ..\mono\metadata\marshal-ilgen.c:1098
3. Microsoft .NET does not exhibit this issue.

### Current Behavior

Code crashes when trying to marshal a struct with an embedded generic struct.

### Expected Behavior

Code succeeds, just as it does in Microsoft .NET.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[x] Windows

**Version Used**: 

5.18.0

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by joncham** [comment]
Tracked by Unity issue: https://issuetracker.unity3d.com/issues/if-marshal-dot-ptrtostructure-raises-an-exception-the-editor-crashes
