### ISSUE TITLE
Corlib not in sync with this runtime: The runtime did not find the mscorlib.dll it expected.

### ISSUE THREAD

**Issue by HenriqueMisson** [mono/mono#12578]
## Steps to Reproduce

I'm trying to launch the Tracealyzer software (https://percepio.com/2018/09/11/running-tracealyzer-4-on-linux-hosts/) and Mono is nedded for that. the step is simply execute the script ```launch-tz.sh```

### Current Behavior

The software doesn't open and the stacktrace below is reported

### Expected Behavior

Open the software

## On which platforms did you notice this

[ ] macOS
[x ] Linux - Ubuntu 16.04 LTS
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)

## Stacktrace

```
Corlib not in sync with this runtime: The runtime did not find the mscorlib.dll it expected.
Expected interface version F602B559-7639-49B6-97EE-C433CE7A56F2 but found CA4932AE-2294-4ECD-B863-BF98FDD84F33.
Check that your runtime and class libraries are matching.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
Could anyone help me?

**Comment by migueldeicaza** [comment]
Your installation is busted.   Hard to diagnose from the data you provided, it is best to start from a clean install.

**Comment by AhmedSamy7** [comment]
I faced a similar problem with Tracealyzer software.
The solution is 
-in Tracealyzer software folder, open the  Tracealyzer.exe.config file
-go to the line <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
-comment that line like that

-save the file
-run the launch-tz.sh file

**Comment by Varun-Rajasekaran** [comment]
Hello Ahmed,
@AhmedSamy7 
I am facing a similar issue while launching Tracealyzer 4.3.5.

And I tried commenting the line suggested by you in the Tracealyzer.exe.config.

But it didn't work for me.

Was it the only workaround done by you?

Is there anything else to be done?

Thanks and Best Regards,
Varun Rajasekaran

**Comment by AhmedSamy7** [comment]
Hello Varun,
@Varun-Rajasekaran 
i have wrote a note for myself on 05.07.2019 on how to install and launch Tracealyzer on linux.
here it is, it has all the steps i went through to let Tracealyzer launchs properly.

> For linux :
> - Extract the "Tracealyzer-4.3.2-linux64.tgz" file
> - Install mono version 5.14 or higher
>   - go to [https://www.mono-project.com/download/stable/#download-lin-ubuntu](url)  for more info 
>   - after adding the suitable key and certificates
>   `sudo apt update`
>   `sudo apt-get install mono-complete `
> - install libgconf-2-4
> ` sudo apt-get install libgconf-2-4`
> - Go to the program folder, open the file "Tracealyzer.exe.config" and comment the line  `<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />` , by adding `<!--` at the beginning and `-->` at the end, it should be like that
 `<!-- <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" /> -->`
> - Save the file before exit
> - To run the program, go to the program folder, then run the file "launch-tz.sh" , or run it from the terminal, go to the program folder, open the terminal, then `./launch-tz.sh`
> # Important Notes
> - If you faced a problem with mono,  may be you need to reinstall a clean mono instalation, to delete mono
 `sudo apt remove --purge --auto-remove mono-runtime`
> - Reinstall it a gain as mentioned before.
> - If you face any problem at the begenning, you have to know that the program make a folder named ".tz4" at /home/YourUserName/ , just delete this folder to erase any preconfiguration.

**Comment by Varun-Rajasekaran** [comment]
Hello Ahmed,
@AhmedSamy7 

Thanks for Your suggestion,It worked.
It worked after deleting ".tz4" directory and launching it.

Best Regards,
Varun Rajasekaran
