### ISSUE TITLE
How to get a class variable like vec3 or an array of 3 floats

### ISSUE THREAD

**Issue by christoskaramou** [mono/mono#12608]
This might be a silly question, but how can i get the value (or the ptr) to a variable of a class type like the bellow?

```
public class vec3
{
	public vec3()
	{
		x = 0.0f;
		y = 0.0f;
		z = 0.0f;
	}
	public float x;
	public float y;
	public float z;
}

public class TestCSharp
{
	public vec3 position = new vec3();
	private float s = 0.0f;
	public float rotation = 0.0f;
	public float scale = 1.0f;
		
	private void Update(float delta)
	{
		//System.Console.WriteLine("TestCSharp Update call! delta = " + delta);
		s += delta;
		rotation = (float)Math.Sin(s);
		scale = Math.Abs((float)Math.Sin(s));
		rotation *= 90.0f;
		position.y += 0.1f;
	}
}
```

I do get the MonoClassField* like this
```
for (auto& f : fields) {
	if (mono_field_get_flags(f) & PUBLIC_FLAG) { // get only public fields
		std::string fieldName(mono_field_get_name(f));
		uint32_t mtype = mono_type_get_type(mono_field_get_type(f));
		if (fieldName == "position" && mtype & MONO_TYPE_CLASS)
			position = f;
		else if (fieldName == "scale" && mtype & MONO_TYPE_R4)
			scale = f;
		else if (fieldName == "rotation" && mtype & MONO_TYPE_R4)
			rotation = f;
	}
}
```
but after that how do i get the value of the position?
This is how i get the other standard type values like floats
```
template<class T>
T getValue(const char* name)
{
	T value;
	MonoClassField* idField = mono_class_get_field_from_name(entityClass, name);
	mono_field_get_value(entityInstance, idField, &value);
	return value;
}
```

**Comment by lambdageek** [comment]
You can still use `mono_field_get_value`, but with a `MonoObject*` as the field type:
```
  MonoObject *position = getValue<MonoObject*> ("TestClass");
```

**Comment by christoskaramou** [comment]
I tried that, but the results are not correct, what is the proper way to get a vec3 out of the MonoObject*?
mono_object_unbox will give me fatal error and the straight cast of MonoObject*  to float* or vec3* will give me wrong numbers. Maybe a working example will save me :D. Sorry again i m new to this.

**Comment by christoskaramou** [comment]
> You can still use `mono_field_get_value`, but with a `MonoObject*` as the field type:
> 
> ```
>   MonoObject *position = getValue<MonoObject*> ("TestClass");
> ```

I tried that, but the results are not correct, what is the proper way to get a vec3 out of the MonoObject*?
mono_object_unbox will give me fatal error and the straight cast of MonoObject* to float* or vec3* will give me wrong numbers. Maybe a working example will save me :D. Sorry again i m new to this.

**Comment by lambdageek** [comment]
In your example, `vec3` is a class, not a struct, so it is laid out in memory with some values that belong to `System.Object` before the fields of the `vec3` itself. So you have to access its fields again using the Mono API.  Something like this:

```
   MonoClass *vec3_class; /* get this the same way you get entityClass */
   MonoClassField *vec3_x_field = mono_class_get_field_from_name (vec3_class, "x");
   int32_t x_value;
   mono_field_get_value (position, vec3_x_field, &x_value);
```

---

Alternately, if you can change your `vec3` to be a `struct`, something like this:
```
[StructLayout(LayoutKind.Sequential)]
public struct vec3 
{
   public int x;
   public int y;
   public int z;
}   
```

Then you could access it from native code like this:

```

struct native_vec3 {
   int32_t x;
   int32_t y;
   int32_t z;
}

...

   native_vec3 position_value;
   MonoClassField* idField = mono_class_get_field_from_name(entityClass, "position");
   mono_field_get_value(entityInstance, idField, &position_value);
```


(I'm sorry I don't have a more complete example, but I don't have your full code available, so i'm just guessing here...)

**Comment by christoskaramou** [comment]
> In your example, `vec3` is a class, not a struct, so it is laid out in memory with some values that belong to `System.Object` before the fields of the `vec3` itself. So you have to access its fields again using the Mono API. Something like this:
> 
> ```
>    MonoClass *vec3_class; /* get this the same way you get entityClass */
>    MonoClassField *vec3_x_field = mono_class_get_field_from_name (vec3_class, "x");
>    int32_t x_value;
>    mono_field_get_value (position, vec3_x_field, &x_value);
> ```
> Alternately, if you can change your `vec3` to be a `struct`, something like this:
> 
> ```
> [StructLayout(LayoutKind.Sequential)]
> public struct vec3 
> {
>    public int x;
>    public int y;
>    public int z;
> }   
> ```
> Then you could access it from native code like this:
> 
> ```
> 
> struct native_vec3 {
>    int32_t x;
>    int32_t y;
>    int32_t z;
> }
> 
> ...
> 
>    native_vec3 position_value;
>    MonoClassField* idField = mono_class_get_field_from_name(entityClass, "position");
>    mono_field_get_value(entityInstance, idField, &position_value);
> ```
> (I'm sorry I don't have a more complete example, but I don't have your full code available, so i'm just guessing here...)

Thank you, the [StructLayout(LayoutKind.Sequential)] worked fine. Cheers!
