### ISSUE TITLE
How are JIT improvements in particular related to .net core?

### ISSUE THREAD

**Issue by rikimaru0345** [mono/mono#12636]
Hi,

I'm writing a library that **heavily** profits from this so called devirtualization optimization in .net core 2.1:
https://blogs.msdn.microsoft.com/dotnet/2017/06/29/performance-improvements-in-ryujit-in-net-core-and-net-framework/

I was wondering how the mono jit is related to all of this.
Does mono have its completely separate jit? I'm guess so at least...

Are those devirtualization improvements coming to mono as well?
Or is mono maybe already more advanced than the .net core jit?

Also, what is the general state of the mono jit when it comes to performance?
From my earlier tests I'm guessing it's around as fast as the jit that .net core 1.x uses. (?)

**Comment by marek-safar** [comment]
Mono has its own JIT which does not use any .NET Core JIT optimizations. For the best performance, we are recommending to use AOT with LLVM backend.
