### ISSUE TITLE
[wasm] Can't get Roslyn Compiler to work in browser

### ISSUE THREAD

**Issue by nbarkhina** [mono/mono#12646]
I'm trying to make a page where I can use the Microsoft.CodeAnalysis API's to compile a syntax tree in the browser. I wanted to see if it would be possible to compile C# code at runtime using mono-wasm and I've seen some demo's on the web who have had success in this. I almost got it working except the part where I start constructing all of the references. Since Webassembly doesn't have a file system I am using the CreateFromStream method to load all of the references using this command - 

references.Add( MetadataReference.CreateFromStream(await this._http.GetStreamAsync(url)) );

Unfortunately it's throwing an error in the browser saying the Stream must support read and seek operations - 

System.AggregateException: One or more errors occurred. (Stream must support read and seek operations.
Parameter name: peStream) ---> System.ArgumentException: Stream must support read and seek operations.
Parameter name: peStream
  at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream (System.IO.Stream peStream, System.Reflection.PortableExecutable.PEStreamOptions options) <0x2e6d700 + 0x00052> in <ea8ec50ace3444bf8cd3e1b3faf05225>:0 
  at Microsoft.CodeAnalysis.AssemblyMetadata.CreateFromStream (System.IO.Stream peStream, System.Reflection.PortableExecutable.PEStreamOptions options) <0x2e6d350 + 0x00010> in <ea8ec50ace3444bf8cd3e1b3faf05225>:0 
  at Microsoft.CodeAnalysis.MetadataReference.CreateFromStream (System.IO.Stream peStream, Microsoft.CodeAnalysis.MetadataReferenceProperties properties, Microsoft.CodeAnalysis.DocumentationProvider documentation, System.String filePath) <0x2e6d1c8 + 0x0001a> in <ea8ec50ace3444bf8cd3e1b3faf05225>:0 

Any ideas as to how I could fix this?

Thanks!

**Comment by Suchiman** [comment]
The simplest solution would be to `HttpStream.CopyTo(MemoryStream)` and then load that

**Comment by nbarkhina** [comment]
Thank you! That solved that problem, now another problem has emerged. I've tried with many different versions of Microsoft.CodeAnalysis.. 2.8, 2.11 beta, 3.0 beta and none of them work. Is there one that is designed for wasm?

For some reason in Blazor it works. Does the Blazor build pipeline do something with these Mono wasm dlls? Ideally I wanted to get this working with just Mono Wasm and without the overhead of Blazor in this scenario. Does the Blazor team just use unmodified version of the mono.wasm or is there some secret sauce they are adding?

Thanks


System.AggregateException: One or more errors occurred. (Method not found: void Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind,bool,string,string,string,System.Collections.Generic.IEnumerable`1<string>,Microsoft.CodeAnalysis.OptimizationLevel,bool,bool,string,string,System.Collections.Immutable.ImmutableArray`1<byte>,System.Nullable`1<bool>,Microsoft.CodeAnalysis.Platform,Microsoft.CodeAnalysis.ReportDiagnostic,int,System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<string, Microsoft.CodeAnalysis.ReportDiagnostic>>,bool,bool,Microsoft.CodeAnalysis.XmlReferenceResolver,Microsoft.CodeAnalysis.SourceReferenceResolver,Microsoft.CodeAnalysis.MetadataReferenceResolver,Microsoft.CodeAnalysis.AssemblyIdentityComparer,Microsoft.CodeAnalysis.StrongNameProvider,bool,Microsoft.CodeAnalysis.MetadataImportOptions,System.Nullable`1<bool>)) ---> System.MissingMethodException: Method not found: void

**Comment by Suchiman** [comment]
@nbarkhina are you running the linker?

**Comment by nbarkhina** [comment]
I'm not sure - i'm running the commands from the wasm starter documentation - 

csc /target:library -out:sample.dll /noconfig /nostdlib /r:C:\mono-sdk\ClassLibrary1.dll /r:C:\mono-sdk\DLL\Microsoft.CodeAnalysis.CSharp.dll /r:C:\mono-sdk\DLL\Microsoft.CodeAnalysis.dll  /r:C:\mono-sdk\DLL\System.Collections.Immutable.dll /r:C:\mono-sdk\DLL\System.Reflection.Metadata.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/wasm-bcl/wasm/mscorlib.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/wasm-bcl/wasm/System.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/wasm-bcl/wasm/System.Core.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/wasm-bcl/wasm/Facades/netstandard.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/wasm-bcl/wasm/Facades/System.Runtime.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/wasm-bcl/wasm/System.Net.Http.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/framework/WebAssembly.Bindings.dll /r:C:\Users\nbarkhina\Desktop\mono-wasm/framework/WebAssembly.Net.Http.dll dependency.cs sample.cs


and then I run the packager tool - 


mono C:\mono-sdk\packager.exe --copy=always --out=./publish sample.dll

**Comment by kjpou1** [comment]
@nbarkhina The packager tool may not be able to find and publish all the necessary assemblies.  It feels like you are missing an assembly somewhere.

**Comment by nbarkhina** [comment]
@kjpou1 here is my sample.cs file 

https://github.com/nbarkhina/mono-compile-in-browser/blob/master/sample.cs

The build script is in that project too, maybe you can let me know what I'm missing

Thanks

**Comment by kjpou1** [comment]
@nbarkhina 

Try using the `--search-path` parameter in your `publish.bat` file.

`mono C:\Users\nbarkhina\Desktop\mono-wasm\packager.exe --copy=always --out=./publish --search-path=C:\Users\nbarkhina\Desktop\mono-example\DLL sample.dll`

Hopefully, that works.  If not then will need to try this on windows but that is the first thing I see.

**Comment by nbarkhina** [comment]
@kjpou1 Ok I used the --search-path parameter and interestingly I did get different results this time. Instead of throwing an error this time it got up to the part of the code in sample.cs at line 157 where it prints "Parse SyntaxTree Success". Unfortunately after that Chrome just hangs and starts utilizing 100 percent of the CPU.so it doesn't look like it works past that line of code. For reference here is the output after I used the search-path parameter - 

C:\Users\nbarkhina\Desktop\mono-example>publish

C:\Users\nbarkhina\Desktop\mono-example>mono C:\Users\nbarkhina\Desktop\mono-wasm\packager.exe --copy=always --out=./publish --search-path=C:\Users\nbarkhina\Desktop\mono-example\DLL sample.dll
Processing C:\Users\nbarkhina\Desktop\mono-example\sample.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\mscorlib.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Net.Http.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Mono.Security.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Xml.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Numerics.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Core.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-example\DLL\Microsoft.CodeAnalysis.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Facades\netstandard.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Data.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Transactions.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Drawing.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.IO.Compression.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.IO.Compression.FileSystem.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.ComponentModel.Composition.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Runtime.Serialization.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.ServiceModel.Internals.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Web.Services.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Xml.Linq.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-example\DLL\System.Collections.Immutable.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-example\DLL\System.Reflection.Metadata.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Facades\System.Threading.Tasks.Extensions.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Facades\System.Text.Encoding.CodePages.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-example\DLL\Microsoft.CodeAnalysis.CSharp.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\framework\WebAssembly.Bindings.dll debug False
Processing C:\Users\nbarkhina\Desktop\mono-wasm\framework\WebAssembly.Net.Http.dll debug False
cp: Always - C:\Users\nbarkhina\Desktop\mono-example\sample.dll -> ./publish\managed\sample.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\mscorlib.dll -> ./publish\managed\mscorlib.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Net.Http.dll -> ./publish\managed\System.Net.Http.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.dll -> ./publish\managed\System.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Mono.Security.dll -> ./publish\managed\Mono.Security.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Xml.dll -> ./publish\managed\System.Xml.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Numerics.dll -> ./publish\managed\System.Numerics.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Core.dll -> ./publish\managed\System.Core.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-example\DLL\Microsoft.CodeAnalysis.dll -> ./publish\managed\Microsoft.CodeAnalysis.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Facades\netstandard.dll -> ./publish\managed\netstandard.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Data.dll -> ./publish\managed\System.Data.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Transactions.dll -> ./publish\managed\System.Transactions.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Drawing.dll -> ./publish\managed\System.Drawing.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.IO.Compression.dll -> ./publish\managed\System.IO.Compression.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.IO.Compression.FileSystem.dll -> ./publish\managed\System.IO.Compression.FileSystem.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.ComponentModel.Composition.dll -> ./publish\managed\System.ComponentModel.Composition.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Runtime.Serialization.dll -> ./publish\managed\System.Runtime.Serialization.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.ServiceModel.Internals.dll -> ./publish\managed\System.ServiceModel.Internals.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Web.Services.dll -> ./publish\managed\System.Web.Services.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\System.Xml.Linq.dll -> ./publish\managed\System.Xml.Linq.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-example\DLL\System.Collections.Immutable.dll -> ./publish\managed\System.Collections.Immutable.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-example\DLL\System.Reflection.Metadata.dll -> ./publish\managed\System.Reflection.Metadata.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Facades\System.Threading.Tasks.Extensions.dll -> ./publish\managed\System.Threading.Tasks.Extensions.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\wasm-bcl\wasm\Facades\System.Text.Encoding.CodePages.dll -> ./publish\managed\System.Text.Encoding.CodePages.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-example\DLL\Microsoft.CodeAnalysis.CSharp.dll -> ./publish\managed\Microsoft.CodeAnalysis.CSharp.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\framework\WebAssembly.Bindings.dll -> ./publish\managed\WebAssembly.Bindings.dll
cp: Always - C:\Users\nbarkhina\Desktop\mono-wasm\framework\WebAssembly.Net.Http.dll -> ./publish\managed\WebAssembly.Net.Http.dll

**Comment by kjpou1** [comment]
@nbarkhina WebAssembly is single threaded and what you are seeing is it blocking because of the task threads.  Blazor has some plumbing up front in their platform to allow this.  

Let me come up with some project code.  Need to drag my windows machine out to get it working on windows though.  

You are following this code here right? https://github.com/BlazorComponents/CompileBlazorInBlazor

**Comment by kjpou1** [comment]
@nbarkhina 

Here is a link with the code running: https://kjpou1.github.io/WasmRoslyn/

I need to get the code out in a repo with build for windows.

**Comment by nbarkhina** [comment]
@kjpou1 that's really cool! do you have the source code so I could see how you did it? or is that what you're assembling now

**Comment by kjpou1** [comment]
@nbarkhina 

Here is the source for the sample: https://github.com/kjpou1/Mono.Wasm.Samples/tree/master/WasmRoslyn

Hope this helps

**Comment by nbarkhina** [comment]
@kjpou1 thank you so much!! I was able to successfully compile your version and it runs just like in your demo. I'm going to examine what you did and incorporate the changes into my code. Thanks again!

**Comment by kjpou1** [comment]
No problem.  Glad it helped.

**Comment by a7medkamel** [comment]
@nbarkhina can you or @kjpou1 elaborate on what exactly solved this problem? I'm running into the same issue and it's not clear to me what specifically in the shared example solved the dead lock.

I changed the compilation to a Task<> which correctly returned a promise, but the promise is never resolving.

Thank you

**Comment by nbarkhina** [comment]
I honestly can't remember, it was a lot of little things. But if you follow his example as I did line by line it finally did work for me.

**Comment by a7medkamel** [comment]
@nbarkhina + @kjpou1 I am able to run the example in browser. I am however unable to run it in node -- specifically; running into issue where the compilation.emit never runs / returns.

@nbarkhina Thanks

**Comment by kjpou1** [comment]
This is a node project?  Could you open a new issue regarding this and supply a reproducable project for this.

**Comment by a7medkamel** [comment]
Will do / Thanks
