### ISSUE TITLE
Can't install older version of Mono on Debian Stretch

### ISSUE THREAD

**Issue by maxtheking** [mono/mono#12662]
Hi, I'm trying to install Mono version 5.14.0.177 on my Debian 9 x64 VM which is running Jackett, Sonarr and Radarr. The reason that i want to install an older version is that the latest stable version doesn't work that well for me, and the older version is known to be working well with Sonarr, Radarr and Jackett. I added `deb https://download.mono-project.com/repo/debian/dists/stable-stretch/snapshots/5.14.0.177/ main` to my mono-official-stable.list file, but when i try to apt-update, i get a error message telling me this: 
![err1](https://user-images.githubusercontent.com/43993269/51859291-15f40d80-2337-11e9-96c0-056bc112ad1b.JPG)

Am i missing something here?

**Comment by baulig** [comment]
I don't really know much about this, but it might be helpful if you could provide the contents of your `/etc/apt/sources.list.d/mono-official-stable.list` - I'm just thinking does this file look reasonable or is there something in it that's really messed up.

**Comment by directhex** [comment]
`deb https://download.mono-project.com/repo/debian/dists/stable-stretch/snapshots/5.14.0.177/ main`

This is wrong.

Please use

`deb https://download.mono-project.com/repo/debian/ stable-stretch/snapshots/5.14.0.177 main`

The exact format of the URL, including trailing slashes, matters.

**Comment by maxtheking** [comment]
> `deb https://download.mono-project.com/repo/debian/dists/stable-stretch/snapshots/5.14.0.177/ main`
> 
> This is wrong.
> 
> Please use
> 
> `deb https://download.mono-project.com/repo/debian/ stable-stretch/snapshots/5.14.0.177 main`
> 
> The exact format of the URL, including trailing slashes, matters.

Thanks, that did the trick!
