### ISSUE TITLE
Support rid specific libraries

### ISSUE THREAD

**Issue by tmds** [mono/mono#12669]
Some NuGet packages, like [Mono.Posix.NETStandard](https://www.nuget.org/packages/Mono.Posix.NETStandard/) and [Libuv](https://www.nuget.org/packages/Libuv/), contain managed and native libraries that differ per [rid](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog). .NET Core picks the proper libraries based on the platform it is running on. Does mono support this feature?

**Comment by marek-safar** [comment]
No, there are no mono specific RIDs available right now

**Comment by tmds** [comment]
The mechanism allows to provide different compilations of the libraries. The proper library is selected based on the system it is running on.

For example, Libuv packages has these:
```
── libuv.1.10.0.nupkg
├── libuv.1.10.0.nupkg.sha512
├── libuv.nuspec
├── License.txt
├── _rels
└── runtimes
    ├── linux-arm
    │   └── native
    │       └── libuv.so
    ├── linux-arm64
    │   └── native
    │       └── libuv.so
    ├── linux-armel
    │   └── native
    │       └── libuv.so
    ├── linux-x64
    │   └── native
    │       └── libuv.so
    ├── osx
    │   └── native
    │       └── libuv.dylib
    ├── win-arm
    │   └── native
    │       └── libuv.dll
    ├── win-x64
    │   └── native
    │       └── libuv.dll
    └── win-x86
        └── native
            └── libuv.dll
```
The Libuv package contains different native libraries for windows, mac, linux-x64, linux-arm64, ...
