### ISSUE TITLE
Net472 cannot be used to compile net core apps

### ISSUE THREAD

**Issue by hardhub** [mono/mono#12785]
I am getting error in console during building my project with Mono and msbuild:

`
 error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [/home/gitlab-runner/builds/.../MyLogging.csproj]
`

If I am using net462 as TargetFramework (in csproj file) and 4.6.2-api from Mono then I can build project successfully, but not 471/472.

It is tested on mono-5.18.0.240 and CentOS7.
Also I tried version compiled from latest sources.
Result is the same.

**Comment by radical** [comment]
Could you please share a test project? Also, a full diagnostic log would be helpful. build with:

`$ msbuild /fl /flp:v=diag <sln/project file>`

.. and then attach the generated `msbuild.log`.

**Comment by radical** [comment]
I tried with a regular csproj with `TargetFrameworkVersion=v4.7.2` and a SDK project with `TargetFramework=net472`, and I was able to build both successfully with mono `5.18.0.240`.

**Comment by hardhub** [comment]
I tried to build real solution where > 30 projects.  
To get exactly desired sample I will need to make some work to find and reproduce.  
It will take some valuable time.

**Comment by radical** [comment]
> I am using net462 as TargetFramework (in csproj file) and 4.6.2-api from Mono then I can build project successfully, but not 471/472.

- Why did you mention `4.6.2-api` here? Are you using any specific paths to mono?
- Using HintPaths?
- Editing references?
- Is it a SDK project (if it is, then it will have `<Project Sdk="..." >` at the top) ?

Could you share this particular project file, `MyLogging.csproj`? You can remove the list of sources from it, if you want.

**Comment by marek-safar** [comment]
Closing, please reopen if you can provide requested details
