### ISSUE TITLE
[DevCom] GC no longer compacts LOH with Xamarin.Android since Visual Studio 15.9

### ISSUE THREAD

**Issue by grendello** [mono/mono#12820]
Developer Community issue: https://developercommunity.visualstudio.com/content/problem/431561/gc-no-longer-compacts-loh-with-xamarinandroid-sinc.html

Original post:

> In Visual Studio 15.8.*, I was using the following to force compaction of the large object heap:
> 
> GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
> GC.Collect();
> 
> This no longer works with Visual Studio 15.9.5 or Visual Studio 2019 and my app runs out of memory.
>

**Comment by BrzVlad** [comment]
Closing this as we never had LOH compaction on mono and the issue seems to be around false pinning
