### ISSUE TITLE
[DevCom] Android application crashes with socket error

### ISSUE THREAD

**Issue by grendello** [mono/mono#12821]
Developer Community issue: https://developercommunity.visualstudio.com/content/problem/427874/android-crashes-with-socket-error.html

Original post:

> App is opening sockets that are bound to a wifi network adapter (using ConnectivityManager.BindProcessToNetwork). If the app loses the wifi connection (e.g. out of range) 
> an error is occuring which is expected. However, this error is not always the same. (I believe it depends on the exact timing of events). The crash occurs in the Mono code in 
> method mono_w32socket_convert_error().
> 
> the relevant log output is
> Abort message: 'mono_w32socket_convert_error: no translation into winsock error for (64) "Machine is not on the network"'
> 
> It would seems the method is missing an entry to convert to a proper winsock error code.

**Comment by BrunoVT1992** [comment]
Is there an update for this issue. This is blocking for us.

**Comment by marek-safar** [comment]
@MaximLipnin that should be quite easy to resolve any update on that?

**Comment by MaximLipnin** [comment]
@marek-safar I'm Iooking at this issue

**Comment by BrunoVT1992** [comment]
My above mentioned fix only works sometimes. We still have the issue.
