### ISSUE TITLE
[iOS] JitTests.GShared fails on devices

### ISSUE THREAD

**Issue by lewurm** [mono/mono#12831]
## Steps to Reproduce

Either current master on xamarin-macios or mono iOS SDK. Started to fail with 2018-08.

### Current Behavior
```
test_0_arm64_small_stack_args failed: got 7, expected 0
```

**Comment by lewurm** [comment]
FYI result of that computation is `res7 = 71`:
https://github.com/mono/mono/blob/b4c66a1d59298d64c75a8470e106847d1a9eb70f/mono/mini/gshared.cs#L1774-L1776

**Comment by marek-safar** [comment]
@vargaz @lewurm can we get this fixed quickly if it's 2018-08 regression?
