### ISSUE TITLE
wasm  var co = new System.Net.CookieContainer(); error System.DllNotFoundException: libc

### ISSUE THREAD

**Issue by iosub** [mono/mono#12871]
## Steps to Reproduce

1. create a wasm project
2. add this code 
3.   var co = new System.Net.CookieContainer();

### Current Behavior

You get error:
System.DllNotFoundException: libc
mono.js:1   at (wrapper managed-to-native) System.Net.NetworkInformation.CommonUnixIPGlobalProperties.getdomainname(byte[],int)
mono.js:1   at System.Net.NetworkInformation.CommonUnixIPGlobalProperties.get_DomainName () [0x0000b] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/System/System.Net.NetworkInformation/UnixIPGlobalProperties.cs:60 
mono.js:1   at System.Net.CookieContainer..ctor () [0x0003a] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/referencesource/System/net/System/Net/cookiecontainer.cs:122 

### Expected Behavior

this code works on Android, IOS, Unix but does not work on wasm

## On which platforms did you notice this

[ ] macOS
[ X] Linux
[X ] Windows
[X] WebAssembly

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by iosub** [comment]
System.DllNotFoundException: libc assembly:<unknown assembly> type:<unknown type> member:(null)
mono.js:1   at (wrapper managed-to-native) System.Net.NetworkInformation.CommonUnixIPGlobalProperties.getdomainname(byte[],int)
mono.js:1   at System.Net.NetworkInformation.CommonUnixIPGlobalProperties.get_DomainName () [0x0000b] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/System/System.Net.NetworkInformation/UnixIPGlobalProperties.cs:60 
mono.js:1   at System.Net.CookieContainer..ctor () [0x0003a] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/referencesource/System/net/System/Net/cookiecontainer.cs:122

**Comment by kjpou1** [comment]
Fixed by https://github.com/mono/mono/pull/13705
