### ISSUE TITLE
BadImageFormatException: Cannot load method from token 0x2b000001 for callvirt at 0x000b

### ISSUE THREAD

**Issue by sbrl** [mono/mono#12900]
## Steps to Reproduce
1. Download this test case project: [StrongNameException.tar.gz](https://github.com/mono/mono/files/2845680/StrongNameException.tar.gz)
2. Compile it with `msbuild`.
3. Try to run the program.

### Current Behavior

If the program is invoked with `mono TestProject.exe`, the following exception is thrown:

```
Unhandled Exception:
System.MissingMethodException: Method not found: !!0 System.Security.Policy.Evidence.GetHostEvidence<!0>()
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method not found: !!0 System.Security.Policy.Evidence.GetHostEvidence<!0>()
```

This is to be expected I think, because the security module isn't enabled. However, if one invokes it with `mono --security TestProject.exe`, the following exception is thrown:

```
Unhandled Exception:
System.BadImageFormatException: Error verifying Sandbox.TextPrograms.StrongNameException.Program:Main (string[]): Cannot load method from token 0x2b000001 for callvirt at 0x000b
[ERROR] FATAL UNHANDLED EXCEPTION: System.BadImageFormatException: Error verifying Sandbox.TextPrograms.StrongNameException.Program:Main (string[]): Cannot load method from token 0x2b000001 for callvirt at 0x000b
```

### Expected Behavior

Since this test project is not signed with a _StrongName_, I'd expect it to return `null`, or perhaps throw an appropriate exception.

Even if the project _is_ signed with a StrongName, the same exception gets thrown. In addition, it doesn't even matter if the method is _actually_ called or not (e.g. if it's in an if statement), or even called via reflection - the same exception is thrown.

On Windows with the official .NET runtime, this functions as expected - returning an instance of the `StrongName` class.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:10:16 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```

## Stacktrace
See above.

**Comment by marek-safar** [comment]
Mono does not support CAS and it's very unlikely it will in the future

**Comment by sbrl** [comment]
I see. In that case, the documentation is misleading then. I was using `man mono` here, where it says this:

```
--security, --security=mode
                     Activate the security manager, a  currently  experimental
                     feature  in  Mono  and it is OFF by default. The new code
                     verifier can be enabled with this option as well.

                     Using security without parameters is equivalent as  call‐
                     ing it with the "cas" parameter.
```

This implies that CAS is and should be fully supported. Futhermore, [this official documentation page](https://www.mono-project.com/docs/advanced/cas/) states that CAS is a new and experimental feature that's coming soon to Mono.

To this end, @marek-safar, I believe that even if Mono isn't going to support CAS, this issue should be left open until such time that all the official documentation is updated to reflect this decision, so as to not mislead users.

Out of curiosity, why was this decision made? Why won't Mono support CAS?

**Comment by marek-safar** [comment]
I have updated the doc and will update the man page as well

**Comment by sbrl** [comment]
Thanks, @marek-safar!
