### ISSUE TITLE
[2018-10] mscorlib tests don't compile for watchOS

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#12956]
## Steps to Reproduce

1. Clone & build the 2018-10 integration branch: https://github.com/xamarin/xamarin-macios/pull/4904
2. Try to build the mscorlib device for watchOS/device (using xharness or `make -C tests build-watchos-dev-mscorlib`).

### Current Behavior

Build failure:

```
  Undefined symbols for architecture armv7k: (TaskId:274)
    "_pinvoke", referenced from: (TaskId:274)
        _mscorlibtests_wrapper_managed_to_native_MonoTests_System_Reflection_CustomAttributeDataTest_pinvoke in mscorlibtests-1a529f.o (TaskId:274)

```

Full build log: https://gist.github.com/rolfbjarne/31f33d45566ebdda2c42cdab557cee0e

This is because there's a P/Invoke to a function that doesn't exist: https://github.com/mono/mono/blob/4a7563ff852a94b15d1779cd3dee046be6bbcd50/mcs/class/corlib/Test/System.Reflection/CustomAttributeDataTest.cs#L84

### Expected Behavior

No build failure

## On which platforms did you notice this

[x] watch
[ ] Linux
[ ] Windows

**Version Used**:

https://github.com/xamarin/xamarin-macios/pull/4904

**Comment by akoeplinger** [comment]
Fixed by https://github.com/mono/mono/commit/78f05bcfa3038dd7d9a20384dc53e9d8a423b2aa
