### ISSUE TITLE
[debugger][wasm] Assertion at mono/metadata/loader.c:2500, condition '<disabled>' not met

### ISSUE THREAD

**Issue by thaystg** [mono/mono#12964]
## Steps to Reproduce
This is the sample I'm using: 
- https://github.com/nventive/Uno.Xaml-Controls-Gallery
- You can change the runtime used there: https://github.com/nventive/Uno.Xaml-Controls-Gallery/blob/1c19aa424e0aa507cdf0d99d1fa308ce52d32a09/XamlControlsGallery.Wasm/XamlControlsGallery.Wasm.csproj#L13 it's the urls out of the Jenkins CI
- The extracted mono path will be in /tmp/mono-xxxx, it's not overwritten on each build
- The used debugger proxy is here `obj/Debug/netstandard2.0/wasm-debugger/mono-wasm-xxx` it's written only once if the folder is not present, you can change the `Mono.WebAssembly.DebuggerProxy.dll` at will.
- Launching the debugger is similar to blazor, with `Shift+Alt+D` with the instructions to follow that you're most certainly familiar with :)
- After that, for this specific runtime issue, put a breakpoint https://github.com/nventive/Uno/blob/d10ec0242b0343cf9ca8e35da9917b773d091144/src/Uno.UI/UI/Xaml/DependencyObjectStore.cs#L1189, I'm clicking on items on the navigation menu, break and expand `instance` or `prevInstance`

And to build the sample, `msbuild /r` in the `XamlControlsGallery.Wasm` folder is enough, the resulting website is in `bin/Debug/netstandard2.0/dist`

And if you run under linux, you'll need to remove this otherwise it'll produce an AOT build

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Comment by thaystg** [comment]
@jeromelaban , here is the issue that we talked last week, I'll work on it right now! :)

**Comment by jeromelaban** [comment]
@thaystg thanks! Let me know if you need help.
