### ISSUE TITLE
[WASM] VTable setup of type Windows.UI.Xaml.ObservableVectorListWrapper failed

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#12987]
_Note: I tried to create a repo sample, but with the exact same hierarchy that fails in the solution, the repro does not._

## Steps to Reproduce

1. Clone [this solution](https://github.com/nventive/Uno.Xaml-Controls-Gallery/blob/uno/XamlControlsGallery.Windows/XamlControlsGallery.sln) at commit https://github.com/nventive/Uno.Xaml-Controls-Gallery/commit/f1be090d0183f49c9ad697b90215e69324f99285.
2. In the folder `XamlControlsGallery.Wasm`, under linux run `msbuild /r`

### Current Behavior
LLVM fails to compile with the following error: 
```
[227/258] [AOT] ./linker-out/Uno.UI.dll -> ./Uno.UI.dll.bc
  Unable to compile method 'Windows.Foundation.Collections.IObservableVector`1<object> Windows.UI.Xaml.ObservableVectorWrapper:Create (object)' due to: 'VTable setup of type Windows.UI.Xaml.ObservableVectorListWrapper failed assembly:/home/nvdevops/vsts.agent01/_work/2/s/XamlControlsGallery.Wasm/obj/Release/netstandard2.0/workAot/linker-out/Uno.UI.dll type:ObservableVectorListWrapper member:(null)'.
  Mono Ahead of Time compiler - compiling assembly /home/nvdevops/vsts.agent01/_work/2/s/XamlControlsGallery.Wasm/obj/Release/netstandard2.0/workAot/linker-out/Uno.UI.dll
  AOTID 30D1EF30-CAAB-8D70-B63E-1882FCAE31A9
  Compiled: 15884/15885
  Output file: '/tmp/mono_aot_aswc2B'.
  Linking symbol: 'mono_aot_module_Uno_UI_info'.
  LLVM output file: './Uno.UI.dll.bc'.
  JIT time: 3190 ms, Generation time: 1812 ms, Assembly+Link time: 0 ms.
```

### Expected Behavior
The assembly is built properly.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] WebAssembly

**Version Used**: 5f65ce9f7dfa6404219c90b6b82ba586fabb2e1c

**Comment by vargaz** [comment]
This is a linker problem, it removes the 
ObservableVectorWrapper::add_VectorChanged method, which is needed by a subclass (ObservableVectorEnumerableWrapper) to implement the IObservableVector interface.

**Comment by vargaz** [comment]
https://github.com/mono/linker/issues/465

**Comment by kjpou1** [comment]
@jeromelaban is this now working?

**Comment by jeromelaban** [comment]
This is fixed in latest mono, most probably due to an update of the linker. Thanks!
