### ISSUE TITLE
Internal obsolete `System.Net.Http.StreamContent` constructor and Mono-specific cancellation behavior.

### ISSUE THREAD

**Issue by kg** [mono/mono#12996]
Edit (Martin): Let's use this issue to consolidate and track all the status of this issue.   I will keep this updated with the current status.

------------------------------------------------------------------------------------------------------

Looks like we probably changed StreamContent around and as a result the .ctor this code needs is missing?

```
2019-02-13T15:44:36.9309840Z    System.AggregateException : One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (An error occurred while retrieving package metadata for 'NUnit.2.6.4' from source 'https://api.nuget.org/v3/index.json'.)))
2019-02-13T15:44:36.9311010Z   ----> System.AggregateException : One or more errors occurred. (One or more errors occurred. (An error occurred while retrieving package metadata for 'NUnit.2.6.4' from source 'https://api.nuget.org/v3/index.json'.))
2019-02-13T15:44:36.9311850Z   ----> System.AggregateException : One or more errors occurred. (An error occurred while retrieving package metadata for 'NUnit.2.6.4' from source 'https://api.nuget.org/v3/index.json'.)
2019-02-13T15:44:36.9312660Z   ----> System.InvalidOperationException : An error occurred while retrieving package metadata for 'NUnit.2.6.4' from source 'https://api.nuget.org/v3/index.json'.
2019-02-13T15:44:36.9313530Z   ----> NuGet.Protocol.Core.Types.FatalProtocolException : An error occurred while retrieving package metadata for 'NUnit.2.6.4' from source 'https://api.nuget.org/v3/index.json'.
2019-02-13T15:44:36.9314340Z   ----> System.MissingMethodException : Method not found: void System.Net.Http.StreamContent..ctor(System.IO.Stream,System.Threading.CancellationToken)
2019-02-13T15:44:36.9314590Z 
```

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=256966&environmentId=1116110

**Comment by baulig** [comment]
See my comment in https://github.com/mono/monodevelop/issues/7155#issuecomment-463743960.

**Comment by marek-safar** [comment]
@baulig we need to bring it back as it's breaking things

**Comment by baulig** [comment]
We also need to carefully distinguish between the _constructor_ and the _behavior_ (*) here.

Bringing back the constructor alone is unacceptable - it's either a trivial fix for them to change their code or they're relying on the _behavior_; in which case we'd artificially cause trouble and make people waste their time by hiding a problem.

So the only thing that really makes sense is to bring back the old _behavior_ (which would obviously include that constructor).  However, before doing so, I would like to understand where this is used, how it is used and why this cancellation is needed.

Long-term, our goal should be not to rely on internal Mono APIs or Mono-specific behavior, and I would like to take this as an opportunity to either fix the relevant code in MonoDevelop or discuss this behavior with the CoreFX team and possibly upstream it.

We can do a quick temporary hot-fix with an `[Obsolete ("FIXME: Please talk to Martin to resolve this!")]` to unblock people, though.

(*) The behavior is the assumption that you can cancel `SerializeToStreamAsync()` by using that internal constructor - but `SerializeToStreamAsync()` is `protected internal`, so it's called by some internal code.

**Comment by baulig** [comment]
PR for a _temporary_ hot-fix is up: https://github.com/mono/mono/pull/13032.

Please keep this issue open even after that PR is merged, so we can discuss and work towards a more permanent solution.

**Comment by baulig** [comment]
See also https://github.com/mono/monodevelop/issues/7155#issuecomment-463969423.

**Comment by baulig** [comment]
Do you still have this issue or need any help from me on this?

**Comment by marek-safar** [comment]
I think this was fixed during the integration

**Comment by directhex** [comment]
Reopening and putting on the 2019-06 milestone, since this breaks VS in 2019-06: https://github.com/xamarin/md-addins/pull/4758

**Comment by marek-safar** [comment]
@baulig please address the issue

/cc @steveisok

**Comment by directhex** [comment]
The proposal on the Xam.Mac side is to stop using the constructor in question. I have no strong feelings on whether the fix should be on their side or ours. https://github.com/mono/monodevelop/issues/7155

**Comment by steveisok** [comment]
if we are saying it's obsolete and Xam.Mac are willing to change it, then let's allow them.  Unless I'm missing something?

**Comment by baulig** [comment]
I have asked a couple of times over the past few weeks and the answer has been that the problem is already fixed, apparently that was incorrect.

**Comment by directhex** [comment]
If it was fixed in Xam.Mac, do we know where? Maybe VSM needs a newer version

**Comment by baulig** [comment]
@directhex Alexander (don't want to ping him here as he's currently enjoying his vacations) told me that it was fixed as part of the 2019-02 and 2019-06 integration.

I'll have a look at the xamarin-macios source code (am also currently building that locally) to figure out.

**Comment by baulig** [comment]
https://github.com/xamarin/xamarin-macios/commit/6197899ebd51dfc64574074850d6c343fc6a7232

**Comment by directhex** [comment]
Yeah, so the issue as I see it is https://github.com/xamarin/xamarin-macios/commit/6197899ebd51dfc64574074850d6c343fc6a7232#diff-7f619be41b43eaaed811ff8b330f769cR809 is recycling the internal constructor, but it is not working, hence the spew on https://github.com/xamarin/md-addins/pull/4758#issuecomment-501021623 and friends. I wonder if the issue is InternalsVisibleTo related...

**Comment by baulig** [comment]
Okay, disregard what I said before - turns out that the issue is not fixed after all.

**Comment by baulig** [comment]
The internal constructor has to go away.  Let me take care of this.

**Comment by baulig** [comment]
@directhex Expect a PR from my by hopefully end-of-day today.

**Comment by directhex** [comment]
I'm pretty sure it's InternalsVisibleTo. VS is using System.Net.Http from Mono, not from Xam.Mac, and only the Xam.Mac version has InternalsVisibleTo[Xam.Mac] - i.e. NSUrlSessionDataTaskStreamContent only works with Xam.Mac System.Net.Http.

**Comment by baulig** [comment]
PR is up: https://github.com/xamarin/xamarin-macios/pull/6277
