### ISSUE TITLE
I still have this issue - can someone tell me how to get the fix?

### ISSUE THREAD

**Issue by msollicito** [mono/mono#13011]
## Steps to Reproduce
See https://github.com/mono/mono/issues/9996

## On which platforms did you notice this

[ ] macOS
[ x] Linux  Raspbian Pi
[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by EgorBo** [comment]
@msollicito could you please share more details on your environment, mono version and logs/stacktraces?
The fix is available in Mono 5.18

**Comment by marek-safar** [comment]
@msollicito please share the details on the original issue tracking issue
