### ISSUE TITLE
AV inside mono_local_emulate_ops+0x43

### ISSUE THREAD

**Issue by bwadswor** [mono/mono#13057]
## Steps to Reproduce

1. Assemble this app.  ("ilasm mono_local_emulate_ops_av.il")

```
.assembly mono_local_emulate_ops_av{}
.assembly extern mscorlib{auto}
.class mono_local_emulate_ops_av{
.method static int32 Main() {
.entrypoint
.maxstack       32

    ldc.r8 42.58279566

Start_Orphan:
    ldc.i8 33
    ldc.i8 32
   cgt
  pop
End_Orphan:

   conv.ovf.i4
  ret
 }
}
```
2. run said app..  "mono-sgen.exe mono_local_emulate_ops_av.exe"
3. observe AV

### Current Behavior

Hits an access violation.

### Expected Behavior

exit code 42.
Expected behavior occurs on full .net framework and coreclr.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X86] Windows

**Version Used**:

Freshly locally built x86 Windows Debug build.  Also repros on 5.18.0.240 Release, but stack isn't so nice...

Mono JIT compiler version 6.1.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

## Stacktrace

```
 # ChildEBP RetAddr  
00 00afefb4 5036a918 mono_2_0_sgen!mono_local_emulate_ops+0x43 [...\mono\mini\decompose.c @ 1928]
01 00aff1b0 50368edc mono_2_0_sgen!mini_method_compile+0x13b8 [...\mono\mini\mini.c @ 3534]
02 00aff214 5037b1cb mono_2_0_sgen!mono_jit_compile_method_inner+0x3c [...\mono\mini\mini.c @ 4021]
03 00aff2a4 50378067 mono_2_0_sgen!mono_jit_compile_method_with_opt+0x6cb [...\mono\mini\mini-runtime.c @ 2479]
04 00aff2c0 5037c051 mono_2_0_sgen!mono_jit_compile_method_jit_only+0x27 [...\mono\mini\mini-runtime.c @ 2542]
05 00aff318 502b41ee mono_2_0_sgen!mono_jit_runtime_invoke+0x1c1 [...\mono\mini\mini-runtime.c @ 3082]
06 00aff33c 502af619 mono_2_0_sgen!do_runtime_invoke+0x7e [...\mono\metadata\object.c @ 2993]
07 00aff358 502b53af mono_2_0_sgen!mono_runtime_invoke_checked+0x49 [...\mono\metadata\object.c @ 3161]
...

```

**Comment by lewurm** [comment]
Submitted a PR. Thanks for those good repros! 👍

**Comment by lewurm** [comment]
Fixed by https://github.com/mono/mono/pull/13127
