### ISSUE TITLE
`--response` does not handle path separators on Windows.

### ISSUE THREAD

**Issue by dellis1972** [mono/mono#13081]
As part of the Xamarin.Android effort to reduce the length of our command line arguments when calling the cross compilers we have tried to use `--response`. It seems to have a a few problems.
The first is that in order to use path separators within the response file you need to delimit them. 
So `c:\Foo\Bar.dll` would need to be written as `c:\\Foo\\Bar.dll`. While this is not a huge problem it does mean that we need to have some special processing between windows and Unix based systems. 

## Steps to Reproduce (Assumes you have latest stable mono for windows installed)

1. Download [ResponsePaths.zip](https://github.com/mono/mono/files/2884129/ResponsePaths.zip) and extract it on windows. 
2. Open a mono command prompt and navigate to when you extracted the file.
3. run `mono --response=resp.txt`

### Current Behaviour

Current you will get the following 

`Cannot open assembly 'ExecutableProgram.exe': No such file or directory.`

### Expected Behaviour

What should happen is the `Program.exe` should run and print `Hello`
## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

Mono JIT compiler version 5.18.0 (Visual Studio built mono)

**Comment by dellis1972** [comment]
This might also be a problem on Mac given the following.
```
MININT-G351LDI:ResponseUnicode dean$ mono Execütable/Program.exe 
Hello
MININT-G351LDI:ResponseUnicode dean$ mono --response=resp.txt
Cannot open assembly '﻿Execütable/Program.exe': No such file or directory.
MININT-G351LDI:ResponseUnicode dean$ file resp.txt 
resp.txt: UTF-8 Unicode (with BOM) text
```

**Comment by jaykrell** [comment]
Please consider trying to use forward slashes instead.
Win32 supports them.
c:/foo/bar.txt

etc.

Pasting them into an open file dialog might not work, but CreateFile, GetFileAttributes, etc., all support them (unless you use the \\? long path support).

**Comment by lateralusX** [comment]
Should be fixed by https://github.com/mono/mono/pull/13132.
