### ISSUE TITLE
tvOS app submission failing with mono 2018-10: "Invalid Bundle Structure - The binary file 'ODRsTVOS.app/PlugIns/ODRsTVOSExt.appex/libmono-native-unified.dylib' is not permitted

### ISSUE THREAD

**Issue by VincentDondain** [mono/mono#13107]
### Test Name: Submission 'tvos_ext' ###
Failure Summary: Submission attempt failed!
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'ODRsTVOS.app/PlugIns/ODRsTVOSExt.appex/libmono-native-unified.dylib' is not permitted. Your app canâ€™t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the tvOS app bundle structure."

### Supplemental Info ###
Log File #1:	http://xqa.blob.core.windows.net/gist/log-424eff429e074404a0a633881d13366e.txt

### Environment ###
Operating System: Mac OS X 10.13.6
Bot Name: XQA-XI-HighSierra-11
Mono version: _[not indicated but that's 2018-10]_
XA version: 9.1.8.0 (HEAD/9bf5bd5ca) 
XI version: 12.7.0.270 (PR-4904): fa387839) 
XM version: 5.7.0.270 (PR-4904: fa387839)  (2019-02-19 15:59:27 -05:00)
XVS version: 
XS version: 7.8.0.1624 (a89c818)  (2019-02-15 10:52:03 -05:00)

-----

Extra bits of info around this issue:

- dylibs are not allowed outside frameworks
- In the _old days_ dynamic linking on user code was not allowed (at all). In iOS 8.x that was _relaxed_ to allow user frameworks (which are dynamically linked). However the old restriction on .dylibs remains the app store will reject them. So either it’s statically linked (.a) or it’s included inside a (codesigned…) `.framework` inside the .app. _Note: it’s an appstore (not OS) requirement so it’s fine to use .dylibs for debug builds_
- Is there a way to check this locally? Check if there’s `.dylib` inside the produced `.app[ex]` directories

**Comment by VincentDondain** [comment]
Note: the iOS submission tests somehow didn’t fail. I will update if tonight’s tests report something different.

**Comment by VincentDondain** [comment]
@akoeplinger watchOS submission test is also failing now (same issue): https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=261614&environmentId=1145490&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension

**Comment by akoeplinger** [comment]
Fixed in mono-2018-10 on xamarin-macios.
