### ISSUE TITLE
System.TypeLoadException: VTable setup of type FFImageLoading.Forms.Platform.CachedImageFastRenderer failed

### ISSUE THREAD

**Issue by kingces95** [mono/mono#13112]
## Steps to Reproduce
Build and launch the android application found here:

https://github.com/kingces95/SmartHotel360-Mobile/tree/vtable-fail

### Current Behavior
Sucker crashes at launch with `System.TypeLoadException: VTable setup of type FFImageLoading.Forms.Platform.CachedImageFastRenderer failed`

### Expected Behavior
Launch in to the full glory of Hotel 360. 

## On which platforms did you notice this
Android

**Comment by samhouts** [comment]
This turned out to be a type mismatch between FFImageLoading and Xamarin.Forms. It can be closed, unless we can think of a better error message. Thanks!

**Comment by uptickguru** [comment]
This is still occuring with the lastest version of Xamarin Forms

**Comment by tonholis** [comment]
Hi guys, I updated FFIL to 2.4.10.972 and I'm facing the same issue with XF 3.4.0.1039999 running on a real device (Huawei P10 Lite) with Android 8.0.0.

I've deleted obj&bin folders, cleared the nuget cache, restarted VS, rebuilt the app but no luck.

Any ideas?

**Comment by MuhammadHamzaRajput** [comment]
commit your code or take a copy of your project.
After the apply this command on package manager console "update-package".
After this clean build your project, then restart visual studio and rebuild your project.
This procedure work for me.

**Comment by nbsoftware** [comment]
Hello,
This is still happening with latest XF 4.6.0.800.
Please see the issue I've created in the FFImageLoading project and mentioned just above.

**Comment by nbsoftware** [comment]
From the error message:

`[Mono] no implementation for interface method Xamarin.Forms.Internals.IPlatformServices::GetNamedColor(string) in class Xamarin.Forms.Forms/AndroidPlatformServices`

It seems someone is missing a concrete implementation of GetNamedColor in class AndroidPlatformServices.

Most likely an XF issue after all, right?
