### ISSUE TITLE
[perf] Major array copying performance difference 

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#13133]
The test `System.Tests.Perf_Array.ArrayCopy2D`(https://github.com/dotnet/performance/blob/0c626c0de72e9e018bb02d0f92b97117098f1fee/src/benchmarks/micro/corefx/System.Runtime/Perf.Array.cs#L236) shows a big slowdown in our array copy compared to .NET core. 

- This takes `3284214.702 ns` on Mono
- This takes only `342.3348056 ns`  for .NET core. This is 00.0104% of the time it takes Mono.

A reproduction of this has been made with the executable here: https://gist.github.com/alexanderkyte/3cc2522a0b7391a1326dc65afcd4a3db

When profiled with Instruments, we see a slowdown due to some handle manipulation. It doesn't seem to be falling back to any intrinsic. 

![array2dslowdown](https://user-images.githubusercontent.com/700530/53198451-74d13d80-35ea-11e9-9c07-bed98bd6c6d1.jpeg)

**Comment by lambdageek** [comment]
It looks like `System.Array.FastCopy` (called from `System.Array.Copy (Array sourceArray, int sourceIndex, Array destinationArray, int destinationIndex, int length)`) is returning FALSE here.  The test is a copies a rank 2 int32 array to another rank 2 int32 array.  That ought to work.

**Comment by BrzVlad** [comment]
This looks fixed. The two runtimes are comparable in performance on the attached benchmark on linux.
