### ISSUE TITLE
Task: Use async DNS resolution in Socket and web stack code.

### ISSUE THREAD

**Issue by hex11** [mono/mono#13163]
https://github.com/mono/mono/blob/b936c531018a354c92103cc9b7cf401231063725/mcs/class/System/System.Net.Sockets/Socket.cs#L975

It causes that `BeginConnect()` doesn't return immediately but returns until the name resolving completes, then unexpected blocking will happen in some async code calling this method.

**Comment by marek-safar** [comment]
@baulig I think this was reported also elsewhere. We should look into using Async or BeginGetHostAddresses versions

**Comment by baulig** [comment]
It is a common pattern in our entire web stack that we're using sync DNS.  I'm not sure whether there was a specific reason for it or whether it's just historic.

**Comment by marek-safar** [comment]
@MaximLipnin Dns.GetHostAddresses (host) is sync method but we are calling it from method (async) which should not block. We need to update this to use async version of GetHostAddresses
