### ISSUE TITLE
Module Initializer does not get called if program has unresolved assemblies (Breaks Costura.Fody)

### ISSUE THREAD

**Issue by HumanGamer** [mono/mono#13193]
## Steps to Reproduce

1. Create a c# project in Visual Studio 2017
2. Use nuget to install the ModuleInit.Fody (this allows you to add code to the module initializer but you could also use Mono.Cecil for this or any other similar library)
3. In the Main method call a function from a custom referenced dll.
4. Copy the referenced library to your output folder with a different name.
5. Make an internal class called ModuleInitializer with a public static void Initialize (if using ModuleInit.Fody, steps are different for different libraries)
6. In the Initialize function add an event handler for AppDomain.CurrentDomain.AssemblyResolve which calls Assembly.LoadFrom and pass in the filename of the library you referenced in Main but with the different name you set the file to earlier.
7. Build the project and delete the referenced dll with the original name.
8. Running the program with regular Microsoft.NET, should work, but it will not work with Mono.
9. Edit Main to have the first line as ```AppDomain.CurrentDomain.AssemblyResolve += (sender, eventArgs) => null;``` and it will now work in both Mono and Microsoft.NET. (however this should not be necessary)

Source Code Example:
[Source.zip](https://github.com/mono/mono/files/2903503/Source.zip)

Debug Build of above Source Code (ready to try with mono or Microsoft.NET):
[DebugBuild.zip](https://github.com/mono/mono/files/2903505/DebugBuild.zip)

Edit: Just a quick note, downloading the build and running may fail in Windows with Microsoft.NET, if so, right click on the exe and unblock it (do the same for the dll) and then it will work. (I just noticed this myself)

### Current Behavior

The module initialization code is not reached when there is an unresolved assembly unless there is an event handler for AppDomain.CurrentDomain.AssemblyResolve returning null at the beginning of Main.

### Expected Behavior

The module initialization code should be reached even when there is an unresolved assembly.

## On which platforms did you notice this

[ ] macOS
[\*] Linux
[\*] Windows

**Version Used**:
4.6.2

## Stacktrace

A stacktrace is not applicable for this issue.

**Comment by lambdageek** [comment]
Fixed by #13242

**Comment by lambdageek** [comment]
Fix backported to 2018-10 (#13303), 2018-12 (#13300) and 2019-02 (#13299)
