### ISSUE TITLE
Metadata file `System.XML.dll' could not be found

### ISSUE THREAD

**Issue by wxtripoder** [mono/mono#13194]
I using Mono version 4.6.2 in Debian 9 system for Raspberry, the details is as following:
![image](https://user-images.githubusercontent.com/47806326/53390315-bd636f00-39cd-11e9-96b3-67fdcd022124.png)

The following is my c# code(under .net frame work 4.0):
public static bool invokeWebService(ref object resData, string url, string methodname, object[] args, ref string err)
        {
            if(!webServiceHelper.invokeWebService(ref resData, url, null, methodname, args,ref err))
            {
                return false;
            }
            return true;
        }
        
        public static bool invokeWebService(ref object resData, string url, string classname, string methodname, object[] args,ref string err)
        {

            string @namespace = "EnterpriseServerBase.WebService.DynamicWebCalling";
            if ((classname == null) || (classname == ""))
            {
                classname = webServiceHelper.GetWsClassName(url);
            }
            try
            {
                WebClient wc = new WebClient();
                Stream stream = wc.OpenRead(url + "?WSDL");
                ServiceDescription sd = ServiceDescription.Read(stream);
                classname = sd.Services[0].Name;

                ServiceDescriptionImporter sdi = new ServiceDescriptionImporter();
                sdi.AddServiceDescription(sd, "", "");
                CodeNamespace cn = new CodeNamespace(@namespace);

                CodeCompileUnit ccu = new CodeCompileUnit();
                ccu.Namespaces.Add(cn);
                sdi.Import(cn, ccu);
                CSharpCodeProvider icc = new CSharpCodeProvider();

				CompilerParameters cplist = new CompilerParameters();
                cplist.GenerateExecutable = false;
                cplist.GenerateInMemory = true;
                cplist.ReferencedAssemblies.Add("System.dll");
                cplist.ReferencedAssemblies.Add("System.XML.dll");
                cplist.ReferencedAssemblies.Add("System.Web.Services.dll");
                cplist.ReferencedAssemblies.Add("System.Data.dll");
                CompilerResults cr = icc.CompileAssemblyFromDom(cplist, ccu);
                if (true == cr.Errors.HasErrors)
                {
                    System.Text.StringBuilder sb = new System.Text.StringBuilder();
                    foreach (System.CodeDom.Compiler.CompilerError ce in cr.Errors)
                    {
                        sb.Append(ce.ToString());
                        sb.Append(System.Environment.NewLine);
                    }
                    throw new Exception(sb.ToString());
                }
                System.Reflection.Assembly assembly = cr.CompiledAssembly;
                Type t = assembly.GetType(@namespace + "." + classname, true, true);
                object obj = Activator.CreateInstance(t);
                System.Reflection.MethodInfo mi = t.GetMethod(methodname);
                
                resData = mi.Invoke(obj, args);
                return true;
            }
            catch (Exception ex)
            {
                err = ex.ToString();
                return false;
            }
        }
When i calling the function, the application always show an error said:
System.Exception: error CS0006: Metadata file `System.XML.dll' could not be found

  at winAccess.webServiceHelper.invokeWebService (System.Object& resData, System.String url, System.String classname, System.String methodname, System.Object[] args, System.String& err) [0x0019e] in <ee9680c937a84ec2803ccf56f5669a0d>:0 

I want to know that does the `System.XML.dll' can be used in Mono? or any other issues?

**Comment by marek-safar** [comment]
The file is actually called `System.Xml.dll`
