### ISSUE TITLE
Can't compile Mono 5.18.0.240 on Linux

### ISSUE THREAD

**Issue by monoluser** [mono/mono#13209]
## Steps to Reproduce

1.  Try to compile Mono 5.18.0.240 on Linux.

### Current Behavior
```
[...]
AOT     [build-linux] Microsoft.CodeAnalysis.CSharp.dll.so
AOT of image /home/luser/download/mono-5.18.0.240/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.8.2/tools//Microsoft.CodeAnalysis.CSharp.dll failed.
Mono Ahead of Time compiler - compiling assembly /home/luser/download/mono-5.18.0.240/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.8.2/tools/Microsoft.CodeAnalysis.CSharp.dll
AOTID CEC98077-BDAD-0BB8-DC32-83D8E39DE0AF
Using profile data file './../../class/lib/build/csc.System.Core.dll.aotprofile'
Using profile data file './../../class/lib/build/csc.corlib.dll.aotprofile'
Added 0 methods from profile.
Added 0 methods from profile.
Code: 5678956(58%) Info: 179380(1%) Ex Info: 3009903(31%) Unwind Info: 22629(0%) Class Info: 300091(3%) PLT: 175130(1%) GOT Info: 220244(2%) Offsets: 122796(1%) GOT: 248616
Compiled: 29760/29760 (100%), No GOT slots: 16151 (54%), Direct calls: 0 (0%)
Executing the native assembler: "as" --64  -o /tmp/mono_aot_O5oRI1.o /tmp/mono_aot_O5oRI1
make[7]: *** [Makefile:67: ../../class/lib/build-linux//Microsoft.CodeAnalysis.CSharp.dll.so] Error 1
make[6]: *** [../../build/rules.make:216: do-all] Error 2
make[5]: *** [build/rules.make:237: all-recursive] Error 1
make[4]: *** [Makefile:54: profile-do--build--all] Error 2
make[3]: *** [Makefile:50: profiles-do--all] Error 2
make[2]: *** [Makefile:590: all-mcs] Error 2
make[2]: Leaving directory '/home/luser/download/mono-5.18.0.240/runtime'
make[1]: *** [Makefile:532: all-recursive] Error 1
make[1]: Leaving directory '/home/luser/download/mono-5.18.0.240'
make: *** [Makefile:461: all] Error 2
```

### Expected Behavior

That `make` completes successfully

## On which platforms did you notice this

I have only tried on Linux.

**5.18.0.240**:

**Comment by lewurm** [comment]
please paste the `./autogen.sh`/`./configure` invocation

**Comment by monoluser** [comment]
I hadn't to call `./autogen.sh` and called `./configure` without any options/arguments. With `./configure --enable-minimal=aot` however, everything works!

**Comment by lewurm** [comment]
That's weird. Could you run `make V=1` and paste ~30 lines before the failure?

Also, wild guess: How large is your `/tmp`? Check with `df -h /tmp`.

**Comment by monoluser** [comment]
Your wild guess wasn't that wild at all! Problem solved! ;)

**Comment by lewurm** [comment]
nice 🙂

**Comment by GobGeeklord** [comment]
Hi guys, 
I'm having this same problem compiling mono on **mono-5.14.0.177**, and i wonder what you have done to solve it.
I'm compiling inside a ARMv7 system with a limited amount of RAM (512MB).
Saw your tip about the /tmp folder size, and tried to point /tmp to flash instead but it doesn't work here. How did you managed to solve it guys? 

Thanks in advance!

make[7]: Entering directory `/opt/mono_git/mono/mcs/class/aot-compiler'
MONO_PATH='./../../class/lib/build-linux/' > build-linux_aot.log 2>&1 /opt/mono_git/mono/runtime/mono-wrapper --aot=bind-to-runtime-version,profile=./../../class/lib/build/csc.corlib.dll.aotprofile,profile=./../../class/lib/build/csc.System.Core.dll.aotprofile,outfile=./../../class/lib/build-linux//Microsoft.CodeAnalysis.CSharp.dll.so --debug /opt/mono_git/mono/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.7.0/tools//Microsoft.CodeAnalysis.CSharp.dll || (cat build-linux_aot.log; exit 1)
AOT of image /opt/mono_git/mono/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.7.0/tools//Microsoft.CodeAnalysis.CSharp.dll failed.
Mono Ahead of Time compiler - compiling assembly /opt/mono_git/mono/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.7.0/tools/Microsoft.CodeAnalysis.CSharp.dll
AOTID C256DC23-1398-9A55-5DB8-1A1FCAF2564F
Using profile data file './../../class/lib/build/csc.corlib.dll.aotprofile'
Using profile data file './../../class/lib/build/csc.System.Core.dll.aotprofile'
Added 1748 methods from profile.
Added 1811 methods from profile.
Code: 8127048(65%) Info: 190740(1%) Ex Info: 3200700(25%) Unwind Info: 239130(1%) Class Info: 294115(2%) PLT: 18790(0%) GOT Info: 265237(2%) Offsets: 129462(1%) GOT: 133288
Compiled: 31437/31437 (100%), No GOT slots: 17035 (54%), Direct calls: 0 (0%)
Executing the native assembler: "as"   -o /tmp/mono_aot_NXESyB.o /tmp/mono_aot_NXESyB
make[7]: *** [../../class/lib/build-linux//Microsoft.CodeAnalysis.CSharp.dll.so] Error 1
make[7]: Leaving directory `/opt/mono_git/mono/mcs/class/aot-compiler'
make[6]: *** [do-all] Error 2
make[6]: Leaving directory `/opt/mono_git/mono/mcs/class/aot-compiler'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/opt/mono_git/mono/mcs'
make[4]: *** [profile-do--build--all] Error 2
make[4]: Leaving directory `/opt/mono_git/mono/mcs'
make[3]: *** [profiles-do--all] Error 2
make[3]: Leaving directory `/opt/mono_git/mono/mcs'
make[2]: *** [all-local] Error 2
make[2]: Leaving directory `/opt/mono_git/mono/runtime'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/mono_git/mono'
make: *** [all] Error 2

**Comment by schloegl** [comment]
In my case, /tmp was not the issue (it was large enough). 
I fixed this by using  "--enable-minimal=aot" to configure. 

`./configure --help 
`   
explains 
```
  --enable-minimal=LIST      drop support for LIST subsystems.
     LIST is a comma-separated list from: aot, profiler, decimal, pinvoke, debug, appdomains, verifier,
     reflection_emit, reflection_emit_save, large_code, logging, com, ssa, generics, attach, jit, interpreter, simd, soft_debug, perfcounters, normalization, desktop_loader, shared_perfcounters, remoting,
         security, lldb, mdb, sgen_marksweep_conc, sgen_split_nursery, sgen_gc_bridge, sgen_debug_helpers.

```
I did not check which of these options is the culprit.  I used 5.18.1.28  and 5.20.1.34
