### ISSUE TITLE
CGPattern causes "Attempting to JIT compile method" exception since VS 7.5

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#13231]
Running the attached application results in a run time error.   

> Application.Main(): Attempting to JIT compile method '(wrapper managed-to-native) CoreGraphics.ReleaseInfoCallback:wrapper_aot_native (object,intptr)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

## Steps to Reproduce

1. Run the attached project on a device.
2. Wait for crash.

[JitErrorTest.zip](https://github.com/mono/mono/files/2916157/JitErrorTest.zip)

### Current Behavior

Application crashes after running for a while. It is hard to know when it will happen.

### Expected Behavior

Application not crashing.

## On which platforms did you notice this

[x] iOS/macOs
[  ] Linux
[  ] Windows

**Version Used**:

Current xamarin master: 564628a289f807289ae6ef75e0bc10f3f0f89bec (hash)

**Comment by marek-safar** [comment]
@vargaz could you look into this regression?

**Comment by vargaz** [comment]
@rolfbjarne Did anything change around that area in x.ios ?

**Comment by rolfbjarne** [comment]
@vargaz no, the `CGPattern` code hasn't changed in years.

**Comment by vargaz** [comment]
@mandel-macaque I can't reproduce this, the app is supposed to run for a while, then crash ?

**Comment by mandel-macaque** [comment]
@vargz correct, In my tests, I ran the application in an iPhone 8+ with iOS 12.1.4 (16D57). It takes an unknown about of time to crash.  I created the issue following the information provided by a user in https://developercommunity.visualstudio.com/content/problem/463933/cgpattern-causes-attempting-to-jit-compile-method.html which followed an issue that was described in the forums (all the information of the original issue can be found in the developer community url).

**Comment by lewurm** [comment]
I can reproduce, it took around a minute on an iPhone 7. native stack trace in a debugger: https://gist.github.com/lewurm/2535b2a5d4edc9e25971351676994724

looks like we run out of some kind of trampoline, probably caused by this delegate in the repro:
```csharp
using (CGPattern pattern = new CGPattern(rect, CGAffineTransform.MakeIdentity(), rect.Width, rect.Height, CGPatternTiling.NoDistortion, true, ctx =>
{
    ctx.SetStrokeColor(color.CGColor);
    ctx.SetLineWidth(2f);
    [...]
}))
```

I'm not familiar with this API: Is it possible to rewrite it so that the `CGPattern` object is only allocated once?

**Comment by marek-safar** [comment]
@vargaz @lewurm does it mean we have a leak somewhere that it does not reproduce reliably?
