### ISSUE TITLE
Current mono tarballs (5.18.0.240, 5.18.0.268) contain prebuilt x86_64 object files

### ISSUE THREAD

**Issue by berolinux** [mono/mono#13253]
Current mono tarballs contain some prebuilt Linux x86_64 object files (with a timestamp equal or newer to their source files), causing the build to fail on non-x86_64 (and probably non-Linux) platforms unless they're removed first.

This has happened before and been marked fixed (https://github.com/mono/mono/issues/11501) -- but it looks like the problem has come back.

**Comment by berolinux** [comment]
$ tar tf mono-5.18.0.268.tar.bz2 |grep -E '\.[ls]?o$'
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_tcpstate.lo
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_errno.lo
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.lo
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_memory.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networking.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_tcpstate.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_errno.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_random.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_maphardwaretype.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_networkstatistics.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/.libs/libmono_system_native_la-pal_io.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_memory.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networking.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_tcpstate.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_errno.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_memory.lo
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networking.lo
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_random.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_random.lo
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_maphardwaretype.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networkstatistics.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.o
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networkstatistics.lo
mono-5.18.0.268/external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_maphardwaretype.lo

**Comment by directhex** [comment]
It is fixed, but only in 5.22 and later.

@akoeplinger do we want to backport 7184737beed16f3091e8ee75cb0e11bd73d872fe anywhere?

**Comment by akoeplinger** [comment]
@directhex 	if people are hitting it in 5.18 then we need to backport it there.

**Comment by akoeplinger** [comment]
Should be fixed by #13256. @directhex I think we automatically produce new tarballs right?

**Comment by directhex** [comment]
Not from 5.18 any more
