### ISSUE TITLE
ref structs are not visible on the stack

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#13269]
## Steps to Reproduce

1. compile following sample
```c#
using System;

ref struct ValueStringBuilder
{
	public void Test ()
	{
		throw new ApplicationException ();
	}
}

class X
{
	public static void Main ()
	{
		ValueStringBuilder vsb = new ValueStringBuilder();
		vsb.Test ();
	}
}
```
 
2. mono --debug foo.exe

### Current Behavior

```
System.ApplicationException: Error in the application.
  at X.Main () [0x00009] in x.cs:16
```

### Expected Behavior

One more frame with ValueStringBuilder::Test

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**: master

**Comment by vargaz** [comment]
It was just inlined. mono -O=-inline foo.exe produces the correct stack trace.
