### ISSUE TITLE
MemberInfo.ReflectedType returns wrong reflected type for an event method

### ISSUE THREAD

**Issue by non-conformances-research** [mono/mono#13350]
According to specification of MemberInfo.ReflectedType (https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.reflectedtype?view=netcore-2.1), it "gets the class object that was used to obtain this instance of MemberInfo". But using the following program the output is different:

```
using System;
using System.Reflection;

public class A
{
    public event Action Event { add { } remove { } }
}

public class B : A
{
    public static void Main(string[] args)
    {
        Type type = typeof(B);
        EventInfo eventInfo = type.GetEvent(nameof(A.Event));
        MemberInfo memberInfo = eventInfo.AddMethod;
        Console.WriteLine(memberInfo.ReflectedType);
    }
}
```

**Steps to reproduce:**

1. Compile above program
2. Run it using mono

**Current result:**

```
A
```

**Expected result:**

```
B
```

**On which platforms did you notice this**:

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

5.4.1

**Comment by MaximLipnin** [comment]
https://github.com/mono/mono/issues/10277 related
