### ISSUE TITLE
Random crash when compiling code (worked previously)

### ISSUE THREAD

**Issue by devvoid** [mono/mono#13380]
## Steps to Reproduce

1. Not sure how to reproduce this, it just started happening today.
2. Clone daerogami/opentk and try to compile with Mono(?)

### Current Behavior

When I run Mono to compile a project, it crashes with exit code 134.

### Expected Behavior

Mono should compile the project correctly.

The code in question targets .net standard 2.0, and compiling with .net core works perfectly. It worked fine with Mono until just now.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.18.0.268 (tarball Thu Feb 28 15:24:08 UTC 2019)

## Stacktrace

[Crash log](https://github.com/mono/mono/files/2948597/crash.log)

## Additional info

I've tried clearing the aot cache, since that caused a similar crash for me in the past. I also tried uninstalling Mono and reinstalling, but that didn't work.

**Comment by knocte** [comment]
With "worked previously" you mean it's a regression? If yes, would be good to specify the version of mono that didn't have this bug.

**Comment by devvoid** [comment]
I mean that I started up my computer one day and it just stopped working. Didn't change my Mono version at all.

**Comment by devvoid** [comment]
Uninstalled Mono and reinstalled, and it worked. Turns out I was missing a cache when I first tried uninstalling.
