### ISSUE TITLE
IPv6 support broken on FreeBSD because AF_INET6 is 28 on FreeBSD not 30 like it is on MacOS

### ISSUE THREAD

**Issue by psaab** [mono/mono#13400]
The change is pretty simple.  FreeBSD uses MacOsNetworkInterfaceAPI which statically defines AF_INET6 to 30 but on FreeBSD AF_INET6 is 28, resulting in various places where mono checks if the OS supports IPv6 (Socket.OSSupportsIPv6) to fail even when IPv6 is supported.

I submitted a patch to FreeBSD here: https://bz-attachments.freebsd.org/attachment.cgi?id=201988, but this should probably be fixed in a much better way and probably not reproduce the entire MacOsNetworkInterface.cs.

## Steps to Reproduce

1. On FreeBSD do sharp -e 'new System.Net.WebClient ().DownloadString ("http://www.v6.facebook.com/status.php")'

### Current Behavior

Connections to IPv6 only hosts fails on FreeBSD

### Expected Behavior

Connections succeed.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] FreeBSD

**Version Used**:
5.10.1.57

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by cemeyer** [comment]
Also reported in a FreeBSD PR here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235716
