### ISSUE TITLE
Bump netstandard.dll assembly version to 2.1

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#13412]
Following #13198 we follow NS2.1 so we should bump our netstandard.dll to assembly version 2.1.

**Comment by marek-safar** [comment]
@steveisok @EgorBo any progress on this?

**Comment by steveisok** [comment]
I had mistakenly thought we bumped w/ the missing API work we did a few sprints ago.  We'll bump and sync with the latest 2.1 updates.
