### ISSUE TITLE
Fork regression in Mojave due to MAP_JIT

### ISSUE THREAD

**Issue by migueldeicaza** [mono/mono#13445]
Since Mono started using `MAP_JIT` on Mojave, this causes `fork()` to break, as the child process does not get access to the JITed code pages.   Those pages seem to have been removed after fork.

`MAP_JIT` is only needed for application bundles, so it would make sense that we only use this in combination with Xamarin.Mac, and not in other scenarios.   This means that we should probably surface an API on the embedding interface that Xamarin.Mac can call to enable this.

## Steps to Reproduce

The following example shows the problem, this crashes the child process with Mono, works with .NET Core:

```
using System;
using System.Runtime.InteropServices;


class X {
        [DllImport ("libc")]
        extern static int fork ();

        [DllImport ("libc")]
        extern static int execv (string process, string [] args);

        static void Main ()
        {
                var d = fork ();

                if (d == 0){
                        execv ("/bin/bash", new string [] { "/bin/bash", "-c", "/bin/ls" });
                } else {
                        Console.WriteLine ("parent got: " + d);
                        Console.ReadLine ();
                }
        }
}
```

### Current Behavior
```
parent got: 53446

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x10a867887):0x10a867877
```

### Expected Behavior

If I remove the MAP_JIT flag, this works and produces a file listing:
```
$ mono test.exe
[ File listed removed]
parent got: 12345
$
```

This works as expected in .NET Core.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.18.0.273 (2018-08/89d7665e281 Wed Mar  6 20:53:39 PST 2019)
```

And also:

```
Mono JIT compiler version 6.1.0 (master/5f5ef1efe50 Wed Mar 13 11:11:18 EDT 2019)
```

# More details

It is possible to confirm that the pages are not mapped on the child process by using `MONO_DEBUG=suspend-on-sigsegv` and attaching to the child process, the context pointer will point to the wrapper code for `fork`, and the crash happens exactly on the instruction after the call is made to `libc` to call into fork.

Also, running `vmmap` shows that the mapping for the code pages that were done with MAP_JIT are gone, only the mmap() region that is allocated from `mono_shared_area_for_pid` survives.

**Comment by migueldeicaza** [comment]
Confirmed, on the XNU source code, the support for mmap explicitly prevents pages mapped with MAP_JIT from being inherited across fork:

osfmk/vm/vm_map.c

The code looks like this:

```
                                (entry_for_jit)? VM_INHERIT_NONE: inheritance,
```

**Comment by akoeplinger** [comment]
Fixed by https://github.com/mono/mono/pull/13958
