### ISSUE TITLE
404 when trying to download win32-bit version

### ISSUE THREAD

**Issue by mclillill** [mono/mono#13441]
I'm trying to download 32-bit mono for windows but get a 404 Not Found:

https://download.mono-project.com/archive/5.18.0/windows-installer/mono-5.18.0.268-gtksharp-2.12.%E2%80%8B45-win32-0.msi

> 
> Not Found
> 
> The requested URL /archive/5.18.0/windows-installer/mono-5.18.0.268-gtksharp-2.12.â€‹45-win32-0.msi was not found on this server.
> Apache/2.4.29 (Ubuntu) Server at download.mono-project.com Port 443
>

**Comment by mclillill** [comment]
I should add this is the link i get when coming from:
https://www.mono-project.com/download/stable/

**Comment by mclillill** [comment]
@marek-safar thanks! I'm going to close the issue then.

**Comment by directhex** [comment]
Fixed. Looks like a BOM crept in, somehow
