### ISSUE TITLE
MSBuild error after side installing into master

### ISSUE THREAD

**Issue by steveisok** [mono/mono#13487]
## Steps to Reproduce

1. Pull mono master, build, and install
2. Pull mono msbuild, build, and install into master
3. Point VS for mac at master install folder
4. Create a console .net app and try to build

### Current Behavior

Project fails to build with the following error:

```
/Users/steveman/Library/Caches/VisualStudio/7.0/MSBuild/41999_2//Microsoft.CSharp.Core.targets"
was not found. Confirm that the path in the <Import> declaration is correct, and that the file 
exists on disk.
```

### Expected Behavior

Build should work 

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

VS for Mac 7.8.3 build 2

```
Mono JIT compiler version 6.1.0 (refsrc-webforms-switch/d5d60b40a9e Wed Mar 13 20:59:48 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by steveisok** [comment]
@radical Where did the break happen?  Is this within mono master or do I have to switch VS channels?

**Comment by steveisok** [comment]
@radical Do you have an idea of when this is going to be fixed?  No rush as I can work around it.

**Comment by radical** [comment]
https://github.com/mono/monodevelop/pull/7381

**Comment by steveisok** [comment]
Terrific!  Thank you.

**Comment by radical** [comment]
Merged to `master-vnext`: https://github.com/mono/monodevelop/pull/7381#issuecomment-481149271

**Comment by steveisok** [comment]
@radical - Is master v-next a closed repo?  I can't seem to find it.
