### ISSUE TITLE
The repl (monotouch_tv_runtime) assemblies don't work for tvOS

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#13526]
## Steps to Reproduce

1. Clone & build xamarin-macios from master (or get it using a recent master package).
2. Create a new tvOS solution, and add `--enable-repl` to the additional mtouch arguments (either simulator or device configuration, both fails).
3. Build.

### Current Behavior

> error MT5214: Native linking failed, undefined symbol: _mono_pal_init. This symbol was referenced by the managed member Interop.mono_pal_init. Please verify that all the necessary frameworks have been referenced and native libraries linked.

[Full build log](https://gist.github.com/rolfbjarne/3f2b556cd40e9d00c4aa78ac73f606d5)

### Expected Behavior

No build error.

**Comment by alanmcgovern** [comment]
For reference - the 16.1 builds are fine so this is not a problem for the upcoming release

**Comment by akoeplinger** [comment]
Fixed by https://github.com/mono/mono/pull/14077

**Comment by rolfbjarne** [comment]
This is still an issue in `2019-02`/`d16-2`.

**Comment by kg** [comment]
Did we need to backport that PR to 2019-02?

**Comment by alanmcgovern** [comment]
Yes - it needs to go into all release branches which are intended for platform consumption :) This would include both 2019-04 and 2019-02 at a minimum as the 'mono monthly integration' work is blocked on both of those branches.

**Comment by marek-safar** [comment]
@steveisok could you please take care of this

**Comment by steveisok** [comment]
Sure, @akoeplinger is working on the backport
