### ISSUE TITLE
how can I reload assembly with embed mono

### ISSUE THREAD

**Issue by srxqds** [mono/mono#13557]
I want reload assembly?

** Mono Init Code **

``` c++
mono_set_signal_chaining(1);
mono_install_assembly_preload_hook(assembly_preload_hook, NULL);
mono_trace_set_log_handler(MonoLog, nullptr);
mono_trace_set_print_handler(MonoPrintf);
mono_trace_set_printerr_handler(MonoPrintf);
mono_set_dirs(lib_path, config_path);
//Required for mdb's to load for detailed stack traces etc.
mono_debug_init(MONO_DEBUG_FORMAT_MONO);
MonoDomain* domain = mono_jit_init_version("UnrealMono", "v4.0.30319");
```

** Load Assembly **

``` c++
MonoAssembly* LoadAssembly(const char* assName)
{
    MonoImageOpenStatus status;
     MonoAssembly* assembly = ono_assembly_load_with_partial_name(TCHAR_TO_ANSI(*assName), &status);
    return assembly;
}
```

** UnLoad Assembly**

``` c++
void UnloadAssembly(const char* assemblyName)
{
    mono_assembly_close(assemblyName);
}
```
When reload assembly call below:

``` c++
LoadAssembly("test.dll);
UnloadAssembly("test.dll");
LoadAssembly("test.dll");  // it throw except

```

the exception trace:
![image](https://user-images.githubusercontent.com/5187024/54686296-e782f980-4b53-11e9-9b8f-6321ef33dd31.png)
![image](https://user-images.githubusercontent.com/5187024/54686353-0ed9c680-4b54-11e9-9ca2-fb34433a8815.png)

** mono version **
5.18.0.225

how can i do with it?

**Comment by millinon** [comment]
I believe that `mono_assembly_close` takes a `MonoAssembly*` not a `const char*`. That should be a compile-time error. Can you try storing the `MonoAssembly*` returned by your `LoadAssembly` function, and then passing that to your `UnloadAssembly` function instead of the name of the assembly?

**Comment by lambdageek** [comment]
Note that `mono_assembly_close` will not necessarily cause the assembly to be unloaded.  If the assembly was referenced by an appdomain (for example if code from the assembly was running), the domain may retain a reference to the assembly.

You should think of `MonoAssembly` as having some kind of reference counting inside. Your call to load the assembly will increment the reference count (from 0 to 1, if it hasn't been loaded before) and `mono_assembly_close` will decrement it.  If the reference count goes back to 0 it will be unloaded.  If not, it won't be.

In general, to reload assemblies you should be running the assembly in a new appdomain (this will affect how you organize your application) and then unloading the domain to unload the old assemblies.  Anything else is not supported by Mono and you may have unpredictable results.

**Comment by srxqds** [comment]
> I believe that `mono_assembly_close` takes a `MonoAssembly*` not a `const char*`. That should be a compile-time error. Can you try storing the `MonoAssembly*` returned by your `LoadAssembly` function, and then passing that to your `UnloadAssembly` function instead of the name of the assembly?

hi, The UnloadAssembly code I wrote wrong, the actual is right:

``` c++

void UnloadAssembly(const char* assName)
{
    MonoAssembly* ass = GetAssembly(assName);// GetAssembly is implement my self 
    mono_assemlby_close(ass);
}
```

**Comment by srxqds** [comment]
> Note that `mono_assembly_close` will not necessarily cause the assembly to be unloaded. If the assembly was referenced by an appdomain (for example if code from the assembly was running), the domain may retain a reference to the assembly.
> 
> You should think of `MonoAssembly` as having some kind of reference counting inside. Your call to load the assembly will increment the reference count (from 0 to 1, if it hasn't been loaded before) and `mono_assembly_close` will decrement it. If the reference count goes back to 0 it will be unloaded. If not, it won't be.
> 
> In general, to reload assemblies you should be running the assembly in a new appdomain (this will affect how you organize your application) and then unloading the domain to unload the old assemblies. Anything else is not supported by Mono and you may have unpredictable results.

hi, Thankyou @lambdageek 
I have another confused: what are different between return from ** mono_domain_create_appdomain ** and ** mono_domain_create**?

As I understanding ** mono_jit_init_version ** had created AppDomain,  can I use ** mono_domain_create_appdomain ** create another child AppDomain ?
what is difference when use **  mono_domain_create_appdomain ** or ** mono_domain_create**?

**Comment by srxqds** [comment]
hi, @lambdageek 

I try the implement:

``` c++
void ScriptingAssemblyManager::CreateDomain()
{
	MonoDomain* newDomain = mono_domain_create_appdomain("UnrealDomain", NULL);
	//mono_thread_push_appdomain_ref(newDomain);
	if (!mono_domain_set(newDomain, false))
	{
	}
}

void ScriptingAssemblyManager::UnloadDomain()
{
	MonoDomain* domainToUnload = mono_domain_get();
	if (domainToUnload && domainToUnload != mono_get_root_domain())
	{
		//mono_thread_pop_appdomain_ref();
		mono_domain_unload(domainToUnload);
	}
	//mono_gc_collect(mono_gc_max_generation());
}

```
And It call:

``` c++
void FUnrealMonoRuntimeModule::OnPreBeginPIE(const bool value)
{
	ScriptingAssemblyManager::Get().CreateDomain();
	ScriptingAssemblyManager::Get().LoadAssembly("UnrealEngine.dll");
	MonoAssembly* gameAssembly = ScriptingAssemblyManager::Get().LoadAssembly(FString("UnrealEngine.Game.dll"));
	MonoImage* testImage = mono_assembly_get_image(gameAssembly);
	MonoClass* monoFooClass = mono_class_from_name(testImage, "UnrealEngine.Game", "TestCShap");
	MonoMethod* staticMethod = mono_class_get_method_from_name(monoFooClass, "Entry", 0);
	mono_runtime_invoke(staticMethod, NULL, NULL, NULL);
}

void FUnrealMonoRuntimeModule::OnEndPIE(const bool value)
{
	//ScriptingAssemblyManager::Get().UnLoadAssembly(FString("UnrealEngine.Game.dll"));
	//ScriptingAssemblyManager::Get().UnLoadAssembly(FString("UnrealEngine.dll"));
	ScriptingAssemblyManager::Get().UnloadDomain(); // crash here
}
```

I crash in gc:
![image](https://user-images.githubusercontent.com/5187024/54738248-66c50b80-4bee-11e9-968d-340707a06ee6.png)

**Comment by srxqds** [comment]
I found the solution: 
1.create domain
2.mono_image_open_from_data_with_name from memory data
