### ISSUE TITLE
[DIM] Mono is throwing the old exception for ambiguous dispatch

### ISSUE THREAD

**Issue by thaystg** [mono/mono#13582]
Mono should throw this exception: System.Runtime.AmbiguousImplementationException

Example: 
https://github.com/dotnet/coreclr/blob/master/tests/src/Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape.cs

**Comment by marek-safar** [comment]
@thaystg was the exception updated?

**Comment by lambdageek** [comment]
This was fixed by https://github.com/mono/mono/pull/14127
