### ISSUE TITLE
[wasm][aot] method calls inside try/finally blocks are expensive

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#13653]
## Steps to Reproduce

Given:
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
static void MyWorkload() { }

void TryMethod() { 
  try { 
    EmptyMethod(); 
    EmptyMethod();
  }
  finally { }
}

void DirectMethod() { 
  EmptyMethod(); 
  EmptyMethod();
}
```

`TryMethod` executes about slower around 5x in FF and 6.5x in Chrome than `DirectMethod`.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] WebAssenbly

**Version Used**: 0b58483fa814707b8a98833a48153ac389d9d933

**Comment by jaykrell** [comment]
Doesn't C++ have similar problems/perf targeting WebAssembly, even though it is the primary original use-case?

**Comment by jeromelaban** [comment]
Issue moved to https://github.com/dotnet/runtime/issues/50783
