### ISSUE TITLE
build mono-1.0.6 failed on windows with cygwin

### ISSUE THREAD

**Issue by yulingjie** [mono/mono#13668]
## Steps to Reproduce

1. down mono-1-0-6 branch
2.  enter the directory on cygwin32 and run ./autogen.sh
3.  create a new dir names "build-cross-windows", enter this dir and type 
`../configure --prefix=/usr/local --build=i686-w64-mingw32 --with-gc=included --enable-parallel-mark `
4. run `make`

### Current Behavior

when it began to compile libgc, I got an error which said **"libgc/include/private/gc_priv.h:1010:27: error: initializer element is not constant #   define GC_objfreelist GC_arrays._objfreelist"**
## On which platforms did you notice this

[ ] macOS
[ ] Linux
[*] Windows

**Version Used**:  
gcc 7.4 on win10 with cygwinx86-64

## Stacktrace

```
../../libgc/include/private/gc_priv.h:1010:27: error: initializer element is not constant
 #   define GC_objfreelist GC_arrays._objfreelist
                           ^
../../libgc/include/private/gc_priv.h:1010:27: note: in definition of macro 'GC_objfreelist'
 #   define GC_objfreelist GC_arrays._objfreelist
                           ^~~~~~~~~
../../libgc/include/private/gc_priv.h:1011:28: error: initializer element is not constant
 #   define GC_aobjfreelist GC_arrays._aobjfreelist
                            ^
../../libgc/include/private/gc_priv.h:1011:28: note: in definition of macro 'GC_aobjfreelist'
 #   define GC_aobjfreelist GC_arrays._aobjfreelist
                            ^~~~~~~~~
../../libgc/include/private/gc_priv.h:1014:26: error: initializer element is not constant
 # define GC_uobjfreelist GC_arrays._uobjfreelist
                          ^
../../libgc/include/private/gc_priv.h:1014:26: note: in definition of macro 'GC_uobjfreelist'
 # define GC_uobjfreelist GC_arrays._uobjfreelist
                          ^~~~~~~~~
../../libgc/include/private/gc_priv.h:1016:29: error: initializer element is not constant
 #   define GC_auobjfreelist GC_arrays._auobjfreelist
                             ^
../../libgc/include/private/gc_priv.h:1016:29: note: in definition of macro 'GC_auobjfreelist'
 #   define GC_auobjfreelist GC_arrays._auobjfreelist
                             ^~~~~~~~~
../../libgc/mallocx.c:72:12: warning: 'GC_realloc' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
     GC_PTR GC_realloc(GC_PTR p, size_t lb)
            ^~~~~~~~~~
../../libgc/mallocx.c:225:10: warning: 'GC_malloc_ignore_off_page' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
   void * GC_malloc_ignore_off_page(size_t lb)
          ^~~~~~~~~~~~~~~~~~~~~~~~~
../../libgc/mallocx.c:235:10: warning: 'GC_malloc_atomic_ignore_off_page' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
   void * GC_malloc_atomic_ignore_off_page(size_t lb)
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
I don't know why and I wish I can get some help here. I have been searching the google for a long time and I don't get any useful answer.
I use gcc 7.4 . Maybe this be the problem?

-- update after several try
If I compiled with out : `--with-gc=included --enable-parallel-mark`, I got ```configure: error: "GC requested but libgc not found! Install libgc or run configure with --with-gc=none."``` instead. Apparently it doesn't work.

**Comment by jaykrell** [comment]
Try without these switches:
`--with-gc=included --enable-parallel-mark`

and more generally look in scripts\ci for how CI builds?

**Comment by lateralusX** [comment]
You are building a mono runtime for Windows using cygwin, right? If so no need to cross compile and just follow the configuration steps here, https://www.mono-project.com/docs/compiling-mono/windows/, similar to what's done on CI.

**Comment by lateralusX** [comment]
Any reason why you would like to use boehm instead of sgen? Boehm has been depricated fro a long time and only available on 32-bit builds.

**Comment by lateralusX** [comment]
You also want to use `--host=i686-w64-mingw32` (as in the build documentation) or you won't pick up mingw compiler but default gcc (or what ever has been setup on the system) causing issues.
