### ISSUE TITLE
Roslyn bump prerequisites and related issues

### ISSUE THREAD

**Issue by kg** [mono/mono#13755]
We recently attempted to bump our roslyn binaries to a recent version and ran into multiple problems that didn't appear in commit-blocking CI results and weren't obvious in local builds at all. Going to try to collect a list of them here - I'm guessing I'm missing some.

* Users run csc and msbuild in various ways, and each method has different behavior when it comes to resolving roslyn dependencies. An incorrect bump may break some of them but not others.
* The dependency tree for roslyn assemblies is invisible in tools like dnSpy because the dependencies do not appear to all be assembly references.
* Roslyn assemblies we use have a target framework of net472, which also makes it non-obvious that they might have new dependencies.
* We ship some facades for roslyn dependencies but it seems as if (?) some of them are not compatible
* Shipping some of the roslyn dependencies included in its DLL will cause issues as they will conflict with our facades and we deploy its DLLs directly with ours.
* msbuild directly relies on roslyn DLLs (and thus roslyn's DLL dependencies) but we appear to in some cases deploy msbuild directly next to our csc, so if we bump roslyn without bumping msbuild, msbuild will break.
* there are multiple ways to compile msbuild and the result does not appear to behave in the same way. this can make it difficult to identify or reproduce issues.
* csc-dim has its binaries deployed in a different fashion from regular csc, so a roslyn build we test as csc-dim may not work correctly once we promote it to csc.
* in general, from-source builds of mono and msbuild do not appear to replicate the user experience of most mono users in regards to roslyn. I install from a prefix and never observed any of the user-facing problems the bump created. (A from-source build also does not have msbuild at all.)

**Comment by kg** [comment]
CCing some people with relevant expertise or information (though i don't think any of these problems are directly or indirectly your responsibility):
@directhex @marek-safar @akoeplinger

**Comment by borgdylan** [comment]
@kg The latest msbuild form xplat-master seems to work with a pre-bump version of mono:
msbuild : 16.0.42-preview+g804bde742b (8b3a694c2c419582108588a7bd1133630a1b8077)
mono :  6.1.0 (master/92b435d6fe7 Tue 12 Mar 18:25:17 CET 2019) (92b435d6fe7c27593f791eb2bc8d77ba4b7fc17d)

**Comment by steveisok** [comment]
I don't know if this is exclusive to VS for Mac / MD, but it probably should be noted along w/ this...

https://github.com/mono/mono/issues/13213

**Comment by steveisok** [comment]
More specifically, if you build/install from-source master with xplat-master msbuild, then both VS+mac and MD can't build projects.  I don't know if that begins / ends w/ the IDE or goes further.

**Comment by directhex** [comment]
@kg I have a PR I'm working on to add a new test to verify that mcs and csc work on prefix-installed Mono (also that AOT and LLVM AOT work).

**Comment by kg** [comment]
@directhex cool. I got the impression from one report that installing to a custom prefix - i.e. my ~/.mono/ - behaves differently from installing at system level into /bin or what have you. Maybe due to the directory layout? Does it make sense that would be different and if so should we have a test for that too?

**Comment by kg** [comment]
This appears to be the full set of dependencies for a modern csc.exe. The question is which ones we ship compatible versions of (so we can drop the dlls when we bundle the csc), which ones are compatible and can be bundled with csc, and which ones have compatibility issues (I'm under the impression some of these dlls are windows-only).

![image](https://user-images.githubusercontent.com/198130/55376459-5867d100-54c5-11e9-82e5-41e010b3d09c.png)

**Comment by kg** [comment]
Out of the csc dependencies that showed up through walking assembly references, we have Facades for:
- [x] System.Buffers
- [ ] System.Collections.Immutable
- [x] System.Memory
- [ ] System.Numerics
- [ ] System.Numerics.Vectors
- [ ] System.Reflection.Metadata
- [x] System.Runtime
- [ ] System.Runtime.CompilerServices.Unsafe
- [x] System.Threading.Tasks.Extensions
- [x] System.Text.Encoding.CodePages

netstandard2 was previously not available in monolite, but current mono builds have it and I think we might have bumped monolite recently to have it (I don't remember).

So the unmarked assemblies above probably need to be shipped with csc. Numerics.Vectors and CompilerServices.Unsafe both seem like they are not necessarily going to be portable across platforms and runtimes.

**Comment by marek-safar** [comment]
System.Numerics and System.Numerics.Vectors are full assemblies which we ship as well so that leaves you with only `System.Runtime.CompilerServices.Unsafe` as additional assembly to what we shipped before

**Comment by borgdylan** [comment]
@kg In light of recent changes, is master expected to compile and work ok? I will be trying on my home machine anyway and revert if things go awry. In any case I will report back to this thread.

**Comment by borgdylan** [comment]
Building the latest mono, no System.Buffers or System.Memory get written to the facades folder. Are these only for roslyn or are they meant to be available to all applications?

**Comment by borgdylan** [comment]
Noting that msbuild is looking for ```csc.exe``` in ```/usr/local/lib/mono/msbuild/15.0/bin/Roslyn``` (note 15.0 and not Current, on my install Current is not a symlink to 15.0)

Made roslyn work with latest mono and msbuild:
```
dylan@ubuntu-server:/usr/local/lib/mono/msbuild/15.0/bin/Roslyn$ sudo ln -s /usr/local/lib/mono/4.5/System.Memory.dll System.Memory.dll
dylan@ubuntu-server:/usr/local/lib/mono/msbuild/15.0/bin/Roslyn$ sudo ln -s /usr/local/lib/mono/4.5/System.Runtime.CompilerServices.Unsafe.dll System.Runtime.CompilerServices.Unsafe.dll
dylan@ubuntu-server:/usr/local/lib/mono/msbuild/15.0/bin/Roslyn$ sudo ln -s /usr/local/lib/mono/4.5/System.Numerics.Vectors.dll System.Numerics.Vectors.dll
```

All three DLLs were found in ```/usr/local/lib/mono/4.5``` as regular non-link files after installing.

**Comment by directhex** [comment]
I thought ece0f7cc26104e5e15e111a134775eade4cbda60 had been reverted when we backed out of the Roslyn update - that's me blindly adding a couple of assemblies from Roslyn's NuGets which are probably wrong.

**Comment by kg** [comment]
We have System.Runtime in Facades, as far as I know, but if I enable compiler server right now it fails to compile because it can't find System.Runtime:

```
--- PID=22151 TID=15 Ticks=149019178: Exception 'One or more errors occurred. 
(System.TypeInitializationException: The type initializer for 'System.MemoryExtensions' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
  at System.MemoryExtensions..cctor () [0x00000] in <ead79779b2484629b72a74757c91b215>:0 
   --- End of inner exception stack trace ---
  at Roslyn.Utilities.StringTable.Add (System.Char[] chars, System.Int32 start, System.Int32 len) [0x00000] in <60997ce90a30420487c7aa6f76c23d63>:0 
```

What can explain this?

**Comment by marek-safar** [comment]
@kg is this issue still relevant?

**Comment by kg** [comment]
Some of the issues mentioned aren't fixed but this is basically a tracking/info bug so you can close it if you like
