### ISSUE TITLE
Android SDK test failures still show up as "green" on CI

### ISSUE THREAD

**Issue by alexischr** [mono/mono#13779]
[Example on PR job](https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-android/10447) (look at e.g. `corlib` results)
![Screen Shot 2019-04-01 at 17 36 04](https://user-images.githubusercontent.com/480437/55361314-dd8ebe00-54a4-11e9-9ce3-4b563005e126.png)

**Comment by marek-safar** [comment]
@directhex could you check what is going on there?

**Comment by directhex** [comment]
There are actually two failure conditions here (because of course there are) - the "build step" not failing, and the overall job not failing.

The latter is already fixed, by this change from @luhenry:

```
- <pattern>mcs/class/**/TestResult*.xml, mono/**/TestResult*.xml, runtime/**/TestResult*.xml, acceptance-tests/**/TestResult*.xml</pattern>
+<pattern>mcs/class/**/TestResult*.xml, mono/**/TestResult*.xml, runtime/**/TestResult*.xml, acceptance-tests/**/TestResult*.xml,sdks/android/TestResult*.xml</pattern>
```

I'll try digging into why the former isn't failing.

**Comment by directhex** [comment]
OK, the per-step failures come from a groovy script looking at output from a plugin called "Build Failure Analyzer" and using it as the source of truth - no failures from BFA -> no failures in this build results window.

In the job you linked to, BFA did not run. It ran on the last jobs in this lane (e.g. https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-android/11005/parsed_console/ shows a WARNING), so I'm going to close this issue as apparently resolved. Please reopen if it happens again?
