### ISSUE TITLE
LLVM AOT (loadedllvm) broken on Linux

### ISSUE THREAD

**Issue by directhex** [mono/mono#13820]
`llvm load failed: /usr/local/lib/libmono-llvm.so: undefined symbol: mono_patch_info_equal`

**Comment by vargaz** [comment]
You probably need:
https://github.com/mono/mono/pull/13110

**Comment by directhex** [comment]
@vargaz  You're right, that's an out of date report.

Today, it's:

```

**Comment by directhex** [comment]
looks like adding `MONO_LLVM_INTERNAL` to `mono_threads_suspend_policy` in `mono/utils/mono-threads-coop.h` is a sufficient fix. Sending a PR.
