### ISSUE TITLE
another concerning privacy issue

### ISSUE THREAD

**Issue by j0shval3r0** [mono/mono#13870]
I was recently using mcs (with the /deterministic flag), compiling test1.cs, and an exact copy test2.cs, and I noticed that the MD5 hashes were different.  On further inspection, I noticed that there was an attribute, "Original Filename", that changed according to the filename that I was compiling from.  This is concerning.  Is there a way that compiling test1.cs and test2.cs can produce the exact same file?
Thanks in advance!

**Comment by migueldeicaza** [comment]
It is best to use Roslyn, as that is the supported compiler (csc rather than mcs).

This capability might or might not be implemented in mcs completely.

**Comment by j0shval3r0** [comment]
Ok, thank you.
