### ISSUE TITLE
[netcore] DynamicSecurityMethod attribute is not respected by runtime

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#13904]
The `DynamicSecurityMethod` is placed on methods with stack marks. It signifies that the method and its caller should not be inlined.

**Comment by vargaz** [comment]
Note that this is an internal convention in coreclr, its not part of any public api.

**Comment by filipnavara** [comment]
I am aware of that, but the shared code depends on it. All methods using stack marks are decorated with the attribute.

**Comment by vargaz** [comment]
It would be nice to add a separate attribute for this, its not really obvious why its on certain methods.

**Comment by filipnavara** [comment]
I checked CoreCLR source and there's exactly 1-to-1 mapping between methods with `DynamicSecurityMethod` and `StackCrawlMark` local variable. In most of the places there's a comment next to the attribute. For checked builds there are asserts to ensure that any method with `StackCrawlMark` has the attribute specified.

**Comment by vargaz** [comment]
What I mean is the naming of the attribute, it should be something like [HasStackCrawl] or something.

**Comment by filipnavara** [comment]
Oh, yeah, I can certainly agree on that :-)

**Comment by filipnavara** [comment]
Fixed by https://github.com/mono/mono/pull/13906
