### ISSUE TITLE
mono_add_internal_call add internal call with generic class

### ISSUE THREAD

**Issue by srxqds** [mono/mono#13900]
The Test code:
``` c#
public class Test<T>
{
    [MethodImpl(MethodImplOptions.InternalCall)]
    public extern static void Add(int self);
    
}

public class Vector
{

}
// call 

Test<Vector> testGeneric = new Test<Vector>();
Test<Vector>.Add(1);
```

``` c++
void Internal_Test_Add(int self)
{
	int a = 1;
}

mono_add_internal_call("UnrealEngine.Game.Test`1[UnrealEngine.Game.Vector]::Add", Internal_Test_Add);

```

## Stacktrace

[2019.04.07-10.05.58:106][242]LogMono: Unhandled Exception:
[2019.04.07-10.05.58:106][242]LogMono: System.MissingMethodException: Attempted to access a missing method.
[2019.04.07-10.05.58:107][242]LogMono:   at (wrapper managed-to-native) UnrealEngine.Game.Test`1[UnrealEngine.Game.Vector].Add(int)
[2019.04.07-10.05.58:107][242]LogMono:   at UnrealEngine.Game.TestCShap.Entry () [0x00007] in <73c19fd0f73948b2acdc88cd57e9556d>:0 

how can I made it?

**Comment by KosmicTask** [comment]
Experiment with these:

```
mono_add_internal_call("UnrealEngine.Game.Test`1<UnrealEngine.Game.Vector>::Add", Internal_Test_Add);

mono_add_internal_call("UnrealEngine.Game.Test`1<T>::Add", Internal_Test_Add);
```

**Comment by vargaz** [comment]
Using "UnrealEngine.Game.Test`1::Add" would probably work.

**Comment by srxqds** [comment]
@vargaz **UnrealEngine.Game.Test`1::Add**  it work, thank you

**Comment by srxqds** [comment]
@vkargov I hava another question: Can I override the method for special generic type, for example the ** Test<Vector>.add** call the native function ** Internal_Test_Add_For_Vector** and other common type **Test<T>.add** call the native function ** Interal_Test_Add**

```c++
void Internal_Test_Add(int a)
{}

mono_add_internal_call("UnrealEngine.Game.Test`1::Add", Internal_Test_Add);

void Internal_Test_Add_For_Vector(int a)
{}

mono_add_internal_call("UnrealEngine.Game.Test`1<UnrealEngine.Game.Vector>::Add, Internal_Test_Add_For_Vector);  // this can't work
```
``` c#
class OtherType
{}

void Main()
{
    Test<Vector>.Add(1);
    Test<OtherType>.Add(2);// 
}

``` 

Can it implement and how to ?

Thank you!

**Comment by KosmicTask** [comment]
I don't think you can do this. If you could I think some of the other method signatures you tried would have worked. You could pass the type parameter as a second internal call parameter. Not very elegant but you are just calling a static method so there is not much choice.

**Comment by Terrydaktal** [comment]
I think with this you need to pass the type as a parameter System.Type typeof(T) and then have it call a single C++ function with MonoReflectionType* as the parameter and then mono_reflection_type_get_type () to get the MonoType (here are the types: https://github.com/samneirinck/cemono/blob/master/src/native/inc/mono/mono/metadata/blob.h), or for object types you can get the MonoClass from MonoType using mono_class_from_mono_type(). The function then needs to delegate the call to functions that handle the different types
