### ISSUE TITLE
mono: symbol lookup error: /usr/lib/libmono-llvm.so: undefined symbol: mono_class_get_generic_class

### ISSUE THREAD

**Issue by brianrob** [mono/mono#13974]
## Steps to Reproduce

1. Build an image from this dockerfile: https://gist.github.com/brianrob/8f3110afcac6d66f00013e9077ccdf1b.
2. Run a container based on the image created in step 1.

### Current Behavior

Running the container, which runs the TechEmpower PlatformPlaintext benchmark against mono produces this error:

```
mono: symbol lookup error: /usr/lib/libmono-llvm.so: undefined symbol: mono_class_get_generic_class
```

### Expected Behavior

The app starts successfully.

## On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.3.0.107 (tarball Tue Apr  9 10:42:04 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by brianrob** [comment]
@directhex, @alexanderkyte, @marek-safar

**Comment by directhex** [comment]
Where do I find PlatformBenchmarks to repro the build?

```
Step 3/12 : COPY PlatformBenchmarks .
COPY failed: stat /var/lib/docker/tmp/docker-builder267172719/PlatformBenchmarks: no such file or directory
```

**Comment by alexanderkyte** [comment]
@directhex I think that's from https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/CSharp/aspnetcore-corert/PlatformBenchmarks/PlatformBenchmarks.csproj

**Comment by brianrob** [comment]
Ah, sorry about that.  It's here: https://github.com/brianrob/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnetcore-mono/PlatformBenchmarks

**Comment by directhex** [comment]
It looks like this might be another case where the symbol isn't needed for a basic sanity check, but _is_ for a more advanced app

```
root@breakfast:/tmp/FrameworkBenchmarks/frameworks/CSharp/aspnetcore-mono/PlatformBenchmarks# mono --llvm bin/Debug/net471/PlatformBenchmarks.exe
mono: symbol lookup error: /usr/lib/libmono-llvm.so: undefined symbol: mono_class_get_generic_class
root@breakfast:/tmp/FrameworkBenchmarks/frameworks/CSharp/aspnetcore-mono/PlatformBenchmarks# mono --llvm /tmp/hello.exe 
Hello World!
```

**Comment by brianrob** [comment]
That sounds right.  Not all of the apps I've run have hit this as well.

**Comment by directhex** [comment]
It might be a 1-line fix. Giving it a shot.

**Comment by directhex** [comment]
Fine then, stay closed. Bloody github.

This is gonna need 6.3.0.134, by my maths. Maybe by tomorrow morning if we're lucky? :man_shrugging:

**Comment by brianrob** [comment]
Thanks @directhex.  Let me know and I'll give it a whirl.
