### ISSUE TITLE
how can I create generic instance in embedded mono?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14008]
I define the class in c# code:
```c#

namesapce 
{
    public classs Test<T>
    {
    }

    public class Vector
   {
   }
}
```

I want to create the instance of Test\<Vector\> in native c side, how can I do it?

**Comment by srxqds** [comment]
can someone help me ?

**Comment by lambdageek** [comment]
Doesn't look like there's a way to do it directly from a `MonoClass*`.

You could use the reflection API ``mono_reflection_type_from_name ("Test`1[Vector]", image)`` where `image` is the `MonoImage` for the assembly that contains those two definitions.  (You may need to use the [Assembly Qualified Names](https://docs.microsoft.com/en-us/dotnet/api/system.type.assemblyqualifiedname?view=netframework-4.7.2#remarks) for the types, rather than the short names.)

**Comment by srxqds** [comment]
I get the method **Type.MakeGenericType** and it work:
```c++
MonoReflectionType* GetMonoReflectionType(MonoClass* cls)
{
	MonoType* monoType = mono_class_get_type(cls);
	return mono_type_get_object(mono_domain_get(), monoType);
}
ScriptingObjectPtr CreateGenericInstance(const char* defineType, ...)
{
	ScriptingAssemblyManager& assemblyManager = ScriptingAssemblyManager::Get();
	FString definteTypeStr = FString(defineType);
	int index = 0;
	bool isFound = definteTypeStr.FindLastChar('`', index);
	if (!isFound)
		return nullptr;
	int genericCount = FCString::Atoi(*definteTypeStr.Mid(index + 1));
	MonoClass* defineClass = assemblyManager.GetTypeFromFullName(defineType);
	if (defineClass == nullptr)
		return nullptr;
	MonoReflectionType* reflectionType = GetMonoReflectionType(defineClass);
	MonoClass* typeClass = mono_object_get_class(reinterpret_cast<MonoObject*>(reflectionType));
	MonoMethod* makeTypeMethod = mono_class_get_method_from_name(typeClass, "MakeGenericType", -1);
	
	va_list va;
	va_start(va, defineType);
	bool argsError = false;
	MonoClass* sysType = assemblyManager.GetTypeFromFullName("System.Type");
	void* args[1];
	MonoArray* typeArgs = CreateScriptingArray(sysType, genericCount);
	args[0] = typeArgs;
	for (index = 0; index < genericCount; index++)
	{
		const char* genericArgus = va_arg(va, const char*);
		MonoClass* genericClass = assemblyManager.GetTypeFromFullName(genericArgus);
		if (genericClass == nullptr)
		{
			argsError = true;
			break;
		}
		SetScriptingArrayElement(typeArgs, index, GetMonoReflectionType(genericClass));
	}
	MonoObject* result = nullptr;
	if (!argsError)
	{
		MonoObject* exception = nullptr;
		result = mono_runtime_invoke(makeTypeMethod, reflectionType, args, &exception);
		RaiseIfException(exception);
	}
	va_end(va);
	return result;
}
```

and use:
CreateGenericInstance("System.Collections.Generic.List`1", "System.Int32");

**Comment by ffbh123456** [comment]
> I get the method **Type.MakeGenericType** and it work:
> 
> MonoReflectionType* GetMonoReflectionType(MonoClass* cls)
> {
> 	MonoType* monoType = mono_class_get_type(cls);
> 	return mono_type_get_object(mono_domain_get(), monoType);
> }
> ScriptingObjectPtr CreateGenericInstance(const char* defineType, ...)
> {
> 	ScriptingAssemblyManager& assemblyManager = ScriptingAssemblyManager::Get();
> 	FString definteTypeStr = FString(defineType);
> 	int index = 0;
> 	bool isFound = definteTypeStr.FindLastChar('`', index);
> 	if (!isFound)
> 		return nullptr;
> 	int genericCount = FCString::Atoi(*definteTypeStr.Mid(index + 1));
> 	MonoClass* defineClass = assemblyManager.GetTypeFromFullName(defineType);
> 	if (defineClass == nullptr)
> 		return nullptr;
> 	MonoReflectionType* reflectionType = GetMonoReflectionType(defineClass);
> 	MonoClass* typeClass = mono_object_get_class(reinterpret_cast<MonoObject*>(reflectionType));
> 	MonoMethod* makeTypeMethod = mono_class_get_method_from_name(typeClass, "MakeGenericType", -1);
> 	
> 	va_list va;
> 	va_start(va, defineType);
> 	bool argsError = false;
> 	MonoClass* sysType = assemblyManager.GetTypeFromFullName("System.Type");
> 	void* args[1];
> 	MonoArray* typeArgs = CreateScriptingArray(sysType, genericCount);
> 	args[0] = typeArgs;
> 	for (index = 0; index < genericCount; index++)
> 	{
> 		const char* genericArgus = va_arg(va, const char*);
> 		MonoClass* genericClass = assemblyManager.GetTypeFromFullName(genericArgus);
> 		if (genericClass == nullptr)
> 		{
> 			argsError = true;
> 			break;
> 		}
> 		SetScriptingArrayElement(typeArgs, index, GetMonoReflectionType(genericClass));
> 	}
> 	MonoObject* result = nullptr;
> 	if (!argsError)
> 	{
> 		MonoObject* exception = nullptr;
> 		result = mono_runtime_invoke(makeTypeMethod, reflectionType, args, &exception);
> 		RaiseIfException(exception);
> 	}
> 	va_end(va);
> 	return result;
> }
> and use: CreateGenericInstance("System.Collections.Generic.List`1", "System.Int32");

Hello,
Then how can you create an instance of the generic type in native code? I use mono_object_new, but the app crashes when I call it.
