### ISSUE TITLE
[WASM] Build mono with emscripten Dynamic Linking enabled

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#14010]
## Steps to Reproduce

1. Use mono-master
2. Update https://github.com/mono/mono/blob/0d6f7a9e6f5dd5ce99a5e55cb4a529e4767f7436/sdks/wasm/Makefile#L103 to add `-s MAIN_MODULE=1`
3. Build the mono-wasm SDK

### Current Behavior
The build fails with :
```
error: Linking globals named 'monoeg_g_array_new': symbol multiply defined!
```

The only similar reference I could find is #8287.

### Expected Behavior
The build completes successfully.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] WebAssembly

**Version Used**: 22bbf4416a64beb12ec2b0b5c7293892a12f0660

**Comment by jeromelaban** [comment]
Poking at it further, this symbol (at least) also seems to be defined multiple times:

`error: Linking globals named 'mono_atomic_cas_i32': symbol multiply defined!`

**Comment by jaykrell** [comment]
But it is `static inline`. Huh.

**Comment by jaykrell** [comment]
Oh
```
#define WAPI_NO_ATOMIC_ASM

extern gint32 mono_atomic_cas_i32(volatile gint32 *dest, gint32 exch, gint32 comp);
```

**Comment by vargaz** [comment]
This is because of these lines in metadata/Makefile.am:
libmono_ilgen_la_LIBADD = $(glib_libs) ../utils/libmonoutils.la ../sgen/libmonosgen.la libmonoruntimesgen.la
For some reason, this will cause these helper libs to contain the object files for the libraries in LIBADD.
It only seems to cause a problem with MAIN_MODULE=1.

**Comment by jeromelaban** [comment]
It looks like emscripten is exporting all symbols when in that mode, so the side modules can pick those up. 

Removing `$(glib_libs)` from the line above indeed made the build go down to `mono_atomic_cas_i32`.

**Comment by jeromelaban** [comment]
This was fixed in master.
