### ISSUE TITLE
Mono 5.20.1.19 / httpcfg on Linux fails with "Operation is not supported on this platform."

### ISSUE THREAD

**Issue by alvarengasv** [mono/mono#14152]
Registration of a certificate/port with httpcfg fails with mono 5.20.1.19 with error "Operation is not supported on this platform". The previous stable version worked correctly. If the certificate/port was registered with a previous mono version it is still usable with HttpListener after updating to 5.20.

## Steps to Reproduce
1. Create a certificate and private key
`makecert -r -sv test.pvk test.cer`
2. register the certificate with any port.
`httpcfg -add -port 9999 -cert test.cer -pvk test.pvk`

### Current Behavior
Fails with this output:
error loading certificate or private key [Operation is not supported on this platform.]

### Expected Behavior
Success

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:07:22 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by blastagator** [comment]
Same problem here.  Anyone had any luck working around this?  I just updated to Ubuntu 19.04 and encountered this.

**Comment by Martidjen** [comment]
Also seeing this issue. Started having issues with certificates after updating to mono 5.20.1.19. Tried to reinstall certificates but got the issue as described here.

**Comment by blastagator** [comment]
If you really need this I was able to revert to my 18.10 build (VM backup) and do the following to downgrade (You should BACKUP your machine BEFORE attempting this, in case it goes wrong):

sudo vi /etc/apt/sources.list.d/<mono file.list>
	Change only line to:
	deb http://download.mono-project.com/repo/ubuntu stable-bionic/snapshots/5.18.1.3 main
sudo apt update
sudo apt-get install apt-show-versions
Run regex command to downgrade all:
	sudo apt-get install $(apt-show-versions | grep -P 'newer than version in archive' | awk -F: '{print $1"/bionic"}')

I was able to get back to 5.18.1.3 doing this.  I broke my machine once while trying to flesh this out, so you've been warned.

**Comment by steveisok** [comment]
@MaximLipnin I'm curious if there are related issues.

**Comment by MaximLipnin** [comment]
I see this issue on mac os for latest master.

**Comment by MaximLipnin** [comment]
On macos with latest master `httpcfg -add -port 9999 -cert test.cer -pvk test.pvk` tries to add a private key and calls `X509Certificate2.PrivateKey` property setter which, in its turn, throws PlatformNotSupportedException. Possibly the same happens on linux.

**Comment by MaximLipnin** [comment]
After aligning with CoreFX (https://github.com/mono/mono/pull/9719)

> The X509Certificate2.PrivateKey setter unconditionally throws PlatformNotSupportedException () on all platforms.

CoreFX initial work: https://github.com/dotnet/corefx/issues/12369
Other work has been done in https://github.com/dotnet/corefx/pull/18344:

> This change also adds
CopyWithPrivateKey(this X509Certificate2 cert, {RSA|DSA|ECDSA} key)
to enable scenarios where a public cert and private key are held independently
but a unification is desired. This makes UNIX-style .pem/.key loading easier,
but still requires users understand how to load the .key file.

Probably it could help but I'm not sure if we (will) support those APIs.
@baulig Does the use of mentioned APIs make sense or there is a better/simpler way to resolve the issue?

**Comment by MaximLipnin** [comment]
@bartonjs Could you please help here? Is this the case which can be covered by work from https://github.com/dotnet/corefx/pull/18344 in private key part?

**Comment by bartonjs** [comment]
Yeah, the recommended way on .NET Framework and (the only way on) .NET Core is to use `var certWithKey = cert.CopyWithPrivateKey(key)`.

**Comment by baulig** [comment]
@MaximLipnin Are you currently working on this or can I take this over?

**Comment by baulig** [comment]
Since I've done all the relevant code in the past, I'm going to have a look at this and should have a PR ready shortly.

**Comment by baulig** [comment]
All the code in `httpcfg.cs` does is to check whether the private key is valid, we don't really need to assign it to the `X509Certificate2` at all.

However, I already have something that does both - PR coming up shortly.

**Comment by MaximLipnin** [comment]
@baulig Thank you for helping here, looks like this fix will be useful for other related issue - https://github.com/mono/mono/issues/14721. It hits other place where X509Certificate2.PrivateKey property gets assigned - https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/System/System.Net/HttpListener.Mono.cs#L83

**Comment by baulig** [comment]
That looks like an easy fix, I'll add it to my https://github.com/mono/mono/pull/14860.

**Comment by CraftyMongoose** [comment]
Any sense for when this will be released?

**Comment by lawred2** [comment]
> Yeah, the recommended way on .NET Framework and (the only way on) .NET Core is to use `var certWithKey = cert.CopyWithPrivateKey(key)`.

Where is CopyWithPrivateKey(key)? I can't find it in .NET Framework 4.7.2 despite the documentation saying that it's available.
