### ISSUE TITLE
Can't cross-compile 5.20.1.19: libmono_native_la-pal_errno built on the wrong platform

### ISSUE THREAD

**Issue by angeloc** [mono/mono#14179]
Cross-compiling 5.20.1.19 with Buildroot:

```
../../external/corefx/src/Native/Unix/System.Native/.libs/libmono_native_la-pal_errno.o: file not recognized: File format not recognized
```

```
$ ls build/mono-5.20.1.19//external/corefx/src/Native/Unix/System.Native/.libs/
libmono_native_la-pal_errno.o            libmono_native_la-pal_networking.o
libmono_native_la-pal_io.o               libmono_native_la-pal_networkstatistics.o
libmono_native_la-pal_maphardwaretype.o  libmono_native_la-pal_random.o
libmono_native_la-pal_memory.o           libmono_native_la-pal_tcpstate.o
$ file build/mono-5.20.1.19/external/corefx/src/Native/Unix/System.Native/.libs/libmono_native_la-pal_errno.o 
build/mono-5.20.1.19/external/corefx/src/Native/Unix/System.Native/.libs/libmono_native_la-pal_errno.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

Issue is related to https://github.com/mono/mono/issues/11744

**Comment by mikaelj** [comment]
My solution for Buildroot, excerpt from mono.mk:

    # fix broken tarballs with old cruft, which is not cleaned by makefiles. (e.g. 5.20.1.19)
    define MONO_REMOVE_BAD_OBJECT_FILES
    	rm -rf `find $(@D)/external -path '*\.libs'`
    	rm -rf `find $(@D)/external -path '*\.deps'`
    	rm -f `find $(@D)/external -path '*\.o'`
    	rm -f `find $(@D)/external -path '*\.so'`
    	rm -f `find $(@D)/external -path '*\.lo'`
    	rm -f `find $(@D)/external -path '*\.Plo'`
    	rm -f `find $(@D)/external -name '\.dirstamp'`
    endef
    
    MONO_POST_EXTRACT_HOOKS += MONO_REMOVE_BAD_OBJECT_FILES

**Comment by angeloc** [comment]
@mikaelj : I don't really want to do anything like that, moreover it's not acceptable for buildroot mainline. I think the mono project should definitely fix a problem persisting from many months now ...

**Comment by directhex** [comment]
Looks like it went into 2018-08 and 2018-12 onwards, but was missed in 2018-10. https://github.com/mono/mono/pull/14185

**Comment by angeloc** [comment]
@directhex : could you repackage a fixed 5.20.1.something please?

**Comment by directhex** [comment]
Maybe https://jenkins.mono-project.com/view/Releases/job/release-tarball-mono/1306/console will spit something out. This job is _intended to fail_, but should fail after building/uploading a tarball (`.27`)

**Comment by directhex** [comment]
https://download.mono-project.com/sources/mono/mono-5.20.1.27.tar.bz2

Go nuts. I'm going home now.
