### ISSUE TITLE
[wasm] Concrete example of passing strings

### ISSUE THREAD

**Issue by kjpou1** [mono/mono#14193]
From #mono-community / @tomdowdell

find a faster way to pass very large strings from C# -> JS. Presently they are passed as plain old strings and received as plain old strings. However, these strings can contain 500k+ JSON and I've been told that there's a way to do it with pointers. Would you be able to provide a concrete example demonstrating how to do this?

**Comment by jeromelaban** [comment]
A string can be passed in via a [fixed pointer](https://github.com/nventive/Uno.RoslynQuoter/blob/2633b934c2d5b3a3943ba907697663698108a0c7/src/uno/RoslynQuoter.Shared/MainPage.xaml.cs#L112), then converted to a string via [UTF8ToString or similar](https://github.com/nventive/Uno.RoslynQuoter/blob/uno/src/uno/RoslynQuoter.Wasm/WasmScripts/CreateDownload.js#L10). There are faster ways to copy linear memory, though, this code dates a bit.

**Comment by kjpou1** [comment]
@tomdowdell Here are some samples for string.

https://github.com/kjpou1/Mono.Wasm.Samples/tree/master/WasmString

Live sample here:  https://kjpou1.github.io/wasmstring/
