### ISSUE TITLE
Suggestion: switch to 7z native format instead of ZIP for Mono archives

### ISSUE THREAD

**Issue by grendello** [mono/mono#14215]
Since Mono already uses `7zip` to create the Mono archives, it might be beneficial to take advantage of superior 7z compression ratio. The difference in sizes is self-evident:

```shell
$ ls -lh android-debug-Linux-e66c76674243826a8d127f0261f0fb64f8d59757.*
-rw-rw-r-- 1 grendel grendel 373M Apr 24 23:34 android-debug-Linux-e66c76674243826a8d127f0261f0fb64f8d59757.7z
-rw-rw-r-- 1 grendel grendel 2,1G Apr 24 23:24 android-debug-Linux-e66c76674243826a8d127f0261f0fb64f8d59757.zip

$ ls -lh ios-release-Darwin-c7ae31177728ebc594eb55c10c40a39aa3681514*
-rw-rw-r-- 1 grendel grendel 164M Apr 24 23:59 ios-release-Darwin-c7ae31177728ebc594eb55c10c40a39aa3681514.7z
-rw-rw-r-- 1 grendel grendel 530M Apr 24 23:54 ios-release-Darwin-c7ae31177728ebc594eb55c10c40a39aa3681514.zip
```

The `7z` archives were created with the following options: `-t7z -mx=9`

**Comment by marek-safar** [comment]
@akoeplinger is this something we can easily do?

**Comment by akoeplinger** [comment]
@marek-safar yes this is very easy to do, we already use the `7z` tool to create the archive, just in .zip format instead of .7z.

I'm in favor of this change, the only question is whether we should create/upload both formats or only have .7z.

**Comment by marek-safar** [comment]
Having only single .7z format should be fine

**Comment by akoeplinger** [comment]
Ok, let's do it for 2019-04.
