### ISSUE TITLE
jay.exe (ILASM): Incorrect loop indexing in generated tokenizer

### ISSUE THREAD

**Issue by glenn-slayden** [mono/mono#14241]
In the **jay.exe** source code (the yacc-like tool for pre-processing the IL grammar in the ILASM build), the C# template file has incorrect loop indexing in a diagnostic function. This gives a fatal crash when the debugging function is enabled.

https://github.com/mono/mono/blob/19387b1f413ebb66451eb58604d97140216472d3/mcs/jay/skeleton.cs#L94-L95

Notice that this is guaranteed to fail since the index `n` into managed array `tokens` is incremented twice per iteration, once in the assignment left-hand-side, and then again in the `for` continuation clause.

**Comment by glenn-slayden** [comment]
yes, I do realize that even though **jay.exe** is a C++ build, this is the (one-and-only) C# file *that it writes out...,* so it would seem to count as a bug against jay.

**Comment by marek-safar** [comment]
Could you submit PR with the proposed fix?

**Comment by glenn-slayden** [comment]
Don't know how to do that. But the fix is:

     .    for (int n = 0; n < tokens.Length;  n++) 
     .      result[n] = yyNames[tokens [n]]; 

Notice the "dot" characters in the first column, which are necessary.
