### ISSUE TITLE
[Wasm] Assertion at mini-llvm.c:2106, condition `clause->flags == MONO_EXCEPTION_CLAUSE_NONE || clause->flags == MONO_EXCEPTION_CLAUSE_FINALLY || clause->flags == MONO_EXCEPTION_CLAUSE_FAULT' not met

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#14243]
## Steps to Reproduce

1. Using mixed mode, build this code: ~~https://github.com/nventive/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.MixedModeSample/Program.cs~~ https://github.com/nventive/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.MixedModeRoslynSample/Program.cs (edit, it was not the right project)
2. AOT all assemblies [except those](https://github.com/nventive/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.MixedModeRoslynSample/Uno.Wasm.MixedModeRoslynSample.csproj#L46-L51)

### Current Behavior

The build fails with:
```
  [90/211] [AOT] ./linker-out/System.dll -> ./System.dll.bc
  FAILED: System.dll.bc 
  MONO_PATH=./linker-out /tmp/mono-wasm-d44e45c32ec/wasm-cross-release/bin/wasm32-unknown-none-mono-sgen --debug  --aot=dedup-skip,interp,llvmonly,asmonly,no-opt,static,direct-icalls,llvm-outfile=./System.dll.bc ./linker-out/System.dll
  Mono Ahead of Time compiler - compiling assembly /__w/1/s/src/Uno.Wasm.MixedModeRoslynSample/obj/Release/netstandard2.0/workAot/linker-out/System.dll
  AOTID C11D10A0-2777-2E11-4E64-BC8951D2E31E
  LLVM failed for 'WebClient.DownloadDataInternal': non-finally/catch/fault clause.
  LLVM failed for 'WebClient.DownloadFile': non-finally/catch/fault clause.
  LLVM failed for 'WebClient.OpenRead': non-finally/catch/fault clause.
  LLVM failed for 'WebClient.OpenWrite': non-finally/catch/fault clause.
  LLVM failed for 'WebClient.UploadDataInternal': non-finally/catch/fault clause.
  LLVM failed for 'WebClient.UploadValues': non-finally/catch/fault clause.
  * Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/mini/mini-llvm.c:2106, condition `clause->flags == MONO_EXCEPTION_CLAUSE_NONE || clause->flags == MONO_EXCEPTION_CLAUSE_FINALLY || clause->flags == MONO_EXCEPTION_CLAUSE_FAULT' not met
  
  Aborted (core dumped)
```

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] WebAssembly

**Version Used**: d44e45c32ec1315f5ab97b2e2ec5104ccad6e868

**Comment by jeromelaban** [comment]
Aos, the test above is about running roslyn in a mixed mode environment.

Also as a workaround, adding excluding `System.dll` from being AOTed works.

**Comment by lewurm** [comment]
The problem is some BCL code is using exception filters which aren't supported by the bitcode backend aka. llvmonly aka. AOT on WebAssembly. For example stuff like this:
https://github.com/mono/corefx/blob/013137ea53490c63f1c8cb7683a7c3c7aea1cfa8/src/System.Net.WebClient/src/System/Net/WebClient.cs#L299-L300
There are a couple more exception filters in this file.

FWIW, the Xamarin.iOS team has a managed linker step to rewrite exception filters to runtime errors:
https://github.com/xamarin/xamarin-macios/blob/4300aa8d03b9e9b7444913e01ba2e86ab92e9eb3/tools/linker/MonoTouch.Tuner/RemoveBitcodeIncompatibleCodeStep.cs#L54-L90

**Comment by akoeplinger** [comment]
This also happens on the 2019-06 integration in Xamarin.iOS and is a regression in behavior from 2019-02. Before it just printed the warnings about exception filters but didn't crash mono.

**Comment by marek-safar** [comment]
@SamMonoRT this is blocking Mono integration, please prioritize it

**Comment by akoeplinger** [comment]
I attached a repro .zip with the failure from XI:

```
$ MONO_PATH=. ./armv7k-unknown-darwin-mono-sgen --debug --llvm -O=float32 --aot=mtriple=armv7k-ios,data-outfile=System.aotdata.armv7k,static,asmonly,direct-icalls,llvmonly,nodebug,dwarfdebug,direct-pinvoke,msym-dir=System.mSYM,llvm-path=llvm,llvm-outfile=System.dll.bc System.dll
Mono Ahead of Time compiler - compiling assembly /Users/alexander/Desktop/repro/System.dll
AOTID E9A83D18-D383-518B-489E-F80C1761656E
LLVM failed for 'WebClient.DownloadDataInternal': non-finally/catch/fault clause.
LLVM failed for 'WebClient.DownloadFile': non-finally/catch/fault clause.
LLVM failed for 'WebClient.OpenRead': non-finally/catch/fault clause.
LLVM failed for 'WebClient.OpenWrite': non-finally/catch/fault clause.
LLVM failed for 'WebClient.UploadDataInternal': non-finally/catch/fault clause.
LLVM failed for 'WebClient.UploadValues': non-finally/catch/fault clause.
* Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-06/ios/release/mono/mini/mini-llvm.c:2114, condition `clause->flags == MONO_EXCEPTION_CLAUSE_NONE || clause->flags == MONO_EXCEPTION_CLAUSE_FINALLY || clause->flags == MONO_EXCEPTION_CLAUSE_FAULT' not met

Abort trap: 6
```

[repro.zip](https://github.com/mono/mono/files/3261405/repro.zip)
