### ISSUE TITLE
Interpreter crashes when running monotouch-test

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#14246]
## Steps to Reproduce

1. Build xamarin-macios/master as of today (for instance https://github.com/xamarin/xamarin-macios/commit/6c3674658aa39e95bbe83cb6a7d5dfccfea7dd3d)
2. `cd tests && make runner` to launch the test runner in the browser
3. Run any of the `monotouch-test/iOS Unified 64-bits - device/*interpreter*` tests.

### Current Behavior

The tests run for a while, then crashes with:

> monotouchtest[810:229200] error: MonoTouchFixtures.CoreGraphics.RectTest:Inflate (): CEE_RET: value type stack: 96 vs. 0

[Application Output](https://gist.github.com/rolfbjarne/35403ad5228e6ae41fdd7f3dc280a171)
[Crash report](https://gist.github.com/rolfbjarne/eff2b7b9701da07653e95e974eaeea49)

### Expected Behavior

No crash

**Comment by lewurm** [comment]
output of `env MONO_VERBOSE_METHOD=Inflate`: https://gist.github.com/lewurm/7aae267515fa979ceadb8696c48e24df
