### ISSUE TITLE
Fix/Port Mono Log profiler to Windows.

### ISSUE THREAD

**Issue by lateralusX** [mono/mono#14258]
After refactoring done to profiler, the default log provider is not working on Windows anymore:

https://github.com/mono/mono/issues/14225

This has been a known issue for a while, but something we should include on the backlog and get fixed. Did a quick investigation on what work that needs to be done in order to port it over to Windows.

- [x] Add profiler log sources to build dynamic library.
- [ ] Add option to include log profiler directly into mono runtime library.
- [ ] Change mechanism to load default pofiler symbols from current executable, since that pattern doesn't work on Windows (only in the DLL case).
- [x] Log profiler is depending on an anonymous pipe for internal communication. That needs to be ported over to Windows CreatePipe API + rewrite of current select usage since that won't work on both sockets and pipes on Windows.
- [ ] Seems to be some issues with the sampling on Windows. It uses timer ending up on thread pool using threads not attached to runtime. Internals of the profiler uses hazards pointers, so that will cause problems.

**Comment by markmwilkinson** [comment]
Is it possible to get a time estimate for when these fixes will be available in a new build please?

**Comment by lateralusX** [comment]
@markmwilkinson, just getting the profiler included in build and working, is currently on its way, https://github.com/mono/mono/pull/14425. Since the profiler has not been run on Windows in the past I could just try basic scenarios so there might still be areas not fully ported/working, but the PR at least makes it possible to start experiment with it on Windows.

**Comment by srxqds** [comment]
any plan about it？why still not fixed

**Comment by lateralusX** [comment]
No more development will be done on this in mono/mono, Mono in dotnet/runtime have full support for EventPipe including a EventPipe provider emitting same set of events as Mono log profiler.
