### ISSUE TITLE
ClientWebSocket ReceiveAsync doesn't respect KeepAliveInterval when Internet Connection is lost

### ISSUE THREAD

**Issue by cosminstirbu** [mono/mono#14299]
## Steps to Reproduce

[WebSocketDisconnect.zip](https://github.com/mono/mono/files/3134414/WebSocketDisconnect.zip)

1. Run the attached iOS / Android application on a device / simulator
2. Tap on the button & check in the Application Output that the message was successfully sent to / received from wss://echo.websocket.org
3. Add a breakpoint to `OnFailed`, cut the internet connection and wait for the breakpoint to be hit.
4. Notice that it takes around 1-2 minutes for the breakpoint to be hit (even if `KeepAliveInterval` is configured for 5 seconds)

### Current Behavior

`ReceiveAsync` throws exception at apparently 1-2  minutes after the connection was interrupted

### Expected Behavior

`ReceiveAsync` should throw exception based on the `KeepAliveInterval` value

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
Visual Studio Enterprise 2019 for Mac
Version 8.0.5 (build 9)
Installation UUID: 9306d817-30f1-4788-b341-52b7a8e09de5
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

NuGet
Version: 4.8.2.5835

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.9
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Version: 2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.2 (14490.120)
Build 10E125

Xamarin.Mac
Version: 5.8.0.0 (Visual Studio Enterprise)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

Xamarin.iOS
Version: 12.8.0.0 (Visual Studio Enterprise)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

Xamarin Designer
Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

Xamarin.Android
Version: 9.2.3.0 (Visual Studio Enterprise)
Android SDK: /Users/cosminstirbu/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

Microsoft Mobile OpenJDK
Java SDK: /Users/cosminstirbu/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 800050009
Git revision: d9d7eed60cb59740ba55c04bfe9c39ac57014c12
Build date: 2019-04-26 10:08:19+00
Build branch: master
Xamarin extensions: 5efedb990d786142d3b54351c01ce867af7b7680

Operating System
Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

**Comment by cosminstirbu** [comment]
@marek-safar 

Can you guys please have a look at this? The user experience caused by this scenario is poor, as we rely on that exception being thrown in order to let the user know that he's not connected any longer.

Thank you,
Cosmin

**Comment by MaximLipnin** [comment]
What I see here is that from 2018-08 up to master branches already use corefx implementation of ManagedWebSocket class where KeepAliveInterval is actually used.
https://github.com/mono/corefx/blob/master/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L198-L202

Looks like this code is not supposed to react to any issues:
https://github.com/mono/corefx/blob/master/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L490-L516
so we cannot now rely on KeepAliveInterval in case of lost connection.

@stephentoub Sorry for bothering here, maybe you could give any advise on this issue?

**Comment by stephentoub** [comment]
ReceiveAsync should return/fail the moment the connection is closed, regardless of the keep-alive interval (the keep-alive interval is just about sending pings to the server to make sure it knows the client is still there and paying attention).  It sounds like the internet connection being interrupted isn't actually causing the connection to be closed at the OS level, which means the higher-level code receiving/sending also has no knowledge it's been closed.  I'm not sure what if anything ManagedWebSocket could do about that.  Can you set a breakpoint inside the delegate at https://github.com/mono/corefx/blob/f7f78ac89c6acd60ffa7807fb62885ad2edd8f13/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L505 ?  If you see that being hit when the keep-alive fires, then there's potentially something that could be done, but from the description I'm not sure if you actually will.

**Comment by MaximLipnin** [comment]
@stephentoub Thank you for reply. 
I can see with WireShark that keepalive-pings work but a breakpoint inside the mentioned delegate was hit neither before connection interrupting not after that.

**Comment by stephentoub** [comment]
> I can see with WireShark that keepalive-pings work but a breakpoint inside the mentioned delegate was hit neither before connection interrupting nor after that.

Thanks. Yeah.  Which means that as far as the sockets layer is concerned, the connection is still alive and working fine: the receive is still pending (the OS hasn't signaled to the socket that there's any activity worth checking), and the send isn't failing.  I don't know what else could reasonably be done at the app level.

**Comment by stephentoub** [comment]
You might experiment with TCP keep-alives, to see if enabling keep-alives at the TCP level would cause the OS to notice the downed connection more quickly.  If it did, a workaround would be to configure that broadly for the OS or maybe the process if there are knobs for that somewhere.  We could look at enabling TCP keep-alives as part of ManagedWebSocket as well, but that would require APIs from SocketsHttpHandler that we don't yet have, e.g. there are several issues open relating to exposing a delegate that enables creating or configuring the underlying Socket used, and that could be used to enable/configure keep-alives on the employed connection.
