### ISSUE TITLE
Split more public API's into public/internal called during init to avoid additional GC unsafe enter/exit calls.

### ISSUE THREAD

**Issue by lateralusX** [mono/mono#14376]
During work, porting hybrid/cooperate suspend over to Windows, I looked at the number of GC unsafe enter/exit just happening during runtime init. Turns out that there is quite a few of those transitions steaming from the fact that we call a couple of Mono public API's, like (there are probably more):

mono_g_hash_table_new_type
mono_g_hash_table_insert
mono_class_is_subclass_of
mono_domain_set
mono_config_for_assembly

In similar situation we split a public API into a public version doing the GC unsafe transition and an internal function just doing a check included in checked build that current thread is already in GC unsafe mode. We should investigate if we could apply the same pattern to at least some of the above methods and switch to calling the internal method during boot if we already know that the thread is in GC unsafe mode.

**Comment by jaykrell** [comment]
Right, I did not finish that work.

**Comment by lambdageek** [comment]
@CoffeeFlux This is another good task to do to get familiar with the code in the runtime.
