### ISSUE TITLE
set unhandle_exception_hook will assert, how can I handle unhandle exception？

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14381]
I want to handle unhandle exception and not crash, how can I do it?

I use **mono_install_unhandled_exception_hook** set exception hook, but it will call **g_assert_not_reached()** at the end of function **mono_invoke_unhandled_exception_hook**

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:
5.18.0.225

## Stacktrace

![image](https://user-images.githubusercontent.com/5187024/57294803-5cf25b80-70fb-11e9-8c38-d8aee3be0f69.png)

**Comment by lewurm** [comment]
do you have a full stack trace?  are you sure that you call `mono_install_unhandled_exception_hook ()` _before_ this happens?

**Comment by srxqds** [comment]
Yeah. the code below I write:

```c++
mono_install_unhandled_exception_hook(mono_unhandled_exception_hook, nullptr);

static void mono_unhandled_exception_hook(MonoObject *exc, void *user_data)
{
// just empty
}
```

and the c# code
```c#
void test()
{
int a =0;
int c =1/a;
}
```

and The stack trace:
**"* Assertion: should not be reached at ..\\mono\\metadata\\exception.c:1282\n" **

![image](https://user-images.githubusercontent.com/5187024/57454407-5864a900-729b-11e9-9a11-fbc0f759af7b.png)

**Comment by srxqds** [comment]
@lewurm My need is that : just catch the exception but not crash(exit), how can make it?

**Comment by lewurm** [comment]
does a breakpoint hit on `mono_install_unhandled_exception_hook` ?

**Comment by srxqds** [comment]
> does a breakpoint hit on `mono_install_unhandled_exception_hook` ?

yes, it will call the hook
it can find it in the stack trace in above picture.

**Comment by lewurm** [comment]
Ah, I thought your problem was that your hook is never called.

You are supposed to shut down the program in the unhandled exception hook, it is not supposed to return.

**Comment by srxqds** [comment]
> Ah, I thought your problem was that your hook is never called.
> 
> You are supposed to shut down the program in the unhandled exception hook, it is not supposed to return.

Or There is some global excpetion catch solution to make it?

**Comment by lewurm** [comment]
It's probably easier to catch the exception in managed code and, if you want to handle it in native code, call that code from the exception handler.

**Comment by srxqds** [comment]
got it, thank you
