### ISSUE TITLE
[netcore] CoreLib mirror out-of-sync / broken Windows build

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#14419]
At least one file in the shared CoreLib files is out of sync again which causes Windows builds to fail.

Mono version of Path.Windows.cs:

https://github.com/mono/mono/blob/c7697e06438ebb66d74e2ec20dd90d08773b2f4b/netcore/System.Private.CoreLib/shared/System/IO/Path.Windows.cs#L132-L134

CoreCLR version of Path.Windows.cs:

https://github.com/dotnet/coreclr/blob/aa494182a1b005674619c0177f238840812db6cd/src/System.Private.CoreLib/shared/System/IO/Path.Windows.cs#L132-L134

/cc @Anipik @marek-safar @directhex

**Comment by marek-safar** [comment]
I am aware of the out of date file and will update that in separate PR
