### ISSUE TITLE
can direct pass method to native side not define delegate?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14441]
I am embeding mono with UE4, I want to c# callback to c side, I found the solution of this showing below:
```c#
public static delegate void OnEndPlay(Actor actor, Reason reason)

void RegisteOnEndPlay(OnEndPlay method)
{
    Internal_RegisterOnEndPlay(method);
}

[MethodImpl(MethodImplOptions.InternalCall)]
public static extern void Internal_RegisterOnEndPlay(OnEndPlay method);
```

```c++
typedef void (*OnEndPlay)(Actor actor, Reason reason)
Internal_RegisterOnEndPlay(OnEndPlay method)
{
// some code
}

```

But, there so many delegate define in ue4 that I don't define all of them.
Is there some solution I can pass MonoMethod direct to c side? 
code like:

```c#

void RegisteOnEndPlay(MonoMethod? method)
{
    Internal_RegisterOnEndPlay(method);
}
```
``` c++
Internal_RegisterOnEndPlay(MonoMethod* method)
{
// some code
}
```

**Comment by vargaz** [comment]
For a large api surface its better to generate the bindings using some kind of tool than writing it by hand.

**Comment by srxqds** [comment]
> For a large api surface its better to generate the bindings using some kind of tool than writing it by hand.

But I want to register dynamic from script not generate code static.
Is there some solution about it?

**Comment by srxqds** [comment]
I found the solution: if the method is static pass the type and the method name to native, if the method is instance pass the instance and method name to native 
thank you very match!
