### ISSUE TITLE
How can I reload dll on iOS with interpreter mode?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14465]
I have two question:
1.Does mono can reload dll on iOS so that we can update code?
2.If it can reload, how can I do it? 

Is there some example or idea?

On window, my solution is: unload old domain and create new domain to reload the new dll, but I try it on iOS with interpreter mode it not work(the unloadmono will enter in a looping cycle). 

I tried hot reloading DLL on iOS but it was blocked at function mono_os_event_wait_multiple which waits for mono_os_cond_wait to return

![image](https://user-images.githubusercontent.com/5187024/57684837-2cfe0780-7669-11e9-8d25-f25f2aeffe1c.png)

**Comment by srxqds** [comment]
My code:
```c++
void mono_ios_register_modules (void)
{
	mono_aot_register_module (mono_aot_module_mscorlib_info);
}

void mono_ios_setup_execution_mode (void)
{
	mono_icall_table_init ();
	mono_marshal_ilgen_init ();
	mono_method_builder_ilgen_init ();
	mono_sgen_mono_ilgen_init ();
	mono_ee_interp_init (0);
	mono_jit_set_aot_mode (MONO_AOT_MODE_INTERP);
}

mono_ios_runtime_init()
{
    mono_ios_register_modules();
    mono_ios_setup_excution_mode();
    mono_debug_init (MONO_DEBUG_FORMAT_MONO);
    mono_install_assembly_preload_hook (assembly_preload_hook, NULL);
	mono_install_load_aot_data_hook (load_aot_data, free_aot_data, NULL);
	mono_install_unhandled_exception_hook (unhandled_exception_handler, NULL);
	mono_trace_set_log_handler (log_callback, NULL);
	mono_set_signal_chaining (TRUE);
	mono_set_crash_chaining (TRUE);

	//setenv ("MONO_LOG_LEVEL", "debug", TRUE);

	MonoDomain* domain = mono_jit_init_version ("Mono.ios", "v4.0.30319");

    MonoDomain* newDomain = mono_domain_create_appdomain("UnrealDomain", NULL);
    //mono_thread_push_appdomain_ref(newDomain);
    bool value = mono_domain_set(newDomain, false);
    //executable = "test-runner.dll";
	MonoAssembly *assembly = load_assembly (executable, NULL);
MonoImage* testImage = mono_assembly_get_image(assembly);
MonoClass* monoFooClass = mono_class_from_name(testImage, "", "TestRunner");
    MonoMethod* staticMethod = mono_class_get_method_from_name(monoFooClass, "static_method", 0);
mono_runtime_invoke(staticMethod, NULL, NULL, NULL);


MonoDomain* domainToUnload = mono_domain_get();
    if (domainToUnload && domainToUnload != mono_get_root_domain())
    {
        mono_domain_set(mono_get_root_domain(), false);
        //mono_thread_pop_appdomain_ref();
        mono_domain_unload(domainToUnload);
    }
    newDomain = mono_domain_create_appdomain("UnrealDomain", NULL);
    //mono_thread_push_appdomain_ref(newDomain);
    value = mono_domain_set(newDomain, false);
    assembly = load_assembly (executable, NULL);
    assert (assembly);
    testImage = mono_assembly_get_image(assembly);
    monoFooClass = mono_class_from_name(testImage, "", "TestRunner");
    staticMethod = mono_class_get_method_from_name(monoFooClass, "static_method", 0);
    mono_runtime_invoke(staticMethod, NULL, NULL, NULL);
}
```

**Comment by srxqds** [comment]
![image](https://user-images.githubusercontent.com/5187024/57669321-0a55f980-763d-11e9-8d26-82fed7e739de.png)

**Comment by srxqds** [comment]
We want to embed mono with ue4, this is most importance for us.
And I work hard with embdeding for serveral months.

May someone help me?
Thankyou very much.

**Comment by vargaz** [comment]
We don't have support for reloading code on ios at the moment. mono on ios doesn't even support domains.

**Comment by srxqds** [comment]
> We don't have support for reloading code on ios at the moment. mono on ios doesn't even support domains.

so sad, but is there some solution to patch update code?
and when can it support os iOS?
this is what we need in game development.

**Comment by vargaz** [comment]
Not in the near future.

**Comment by vargaz** [comment]
Xamarin.ios will have live reload support, but thats specific to that product.
https://marketplace.visualstudio.com/items?itemName=Xamarin.XamarinLiveReload

**Comment by srxqds** [comment]
This is so bad for our project, It means we should give up using mono for game scripting develop.
It is real nothing to do with it ?

**Comment by vargaz** [comment]
ios is designed for static apps. Apple also has restrictions on interpreters.

**Comment by srxqds** [comment]
> ios is designed for static apps. Apple also has restrictions on interpreters.

yeah, but you can think the scripting code is also resource not execute binary. It is so frequently for game app version update.

I have a idea to implement to update code: 
0. there are two assembly A and B, load A first and then B
1.when app start ,we load assembly A, check whether should update and download B, and the B
2.if assembly A is updated, where should reload A or use new A assembly.
It can restart mono virtual machine or unload assembly A only ?
@vargaz

**Comment by srxqds** [comment]
@marek-safar Is there a plan to support reload assembly with isolation domain? 
And when can it complete?

**Comment by vargaz** [comment]
Long term, we plan on adding support for unloadable assemblies, but there is no ETA for that. So short term, there is no support for that.

**Comment by srxqds** [comment]
@vargaz thank you for reply.
Another question: We are embedding mono use interpreter mode, will it violate **Apple Review Guideline** and **Apple Develop Program license agreement** and reject the product by Apple?

This is a risk of using mono when it has jit run code, Can you give some clear answer about it.
