### ISSUE TITLE
Perf: TechEmpower PlatformPlaintext Benchmark Throughput is Much Lower Using LLVM-JIT

### ISSUE THREAD

**Issue by brianrob** [mono/mono#14471]
On Linux x64, the TechEmpower PlatformPlaintext benchmark throughput is significantly slower when using LLVM-JIT vs. Mini-JIT:

LLVM-JIT: 52,676 req/sec.
Mini-JIT: 569,263 req/sec.

This is using the default configuration where mscorlib.dll is AOT and everything else is IL.  I would have expected better results on LLVM-JIT vs. Mini-JIT.  Note that this measurement warms-up the server so we are not including start-up or first request JIT time in these numbers.  These numbers are captured once the server is warm.

## Steps to Reproduce
1. Copy the source for https://github.com/brianrob/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnetcore-mono/PlatformBenchmarks to a local directory.
2. Copy the contents of https://gist.github.com/brianrob/78c2f4ae69229ab86d7f8ddb34af7197 to a dockerfile next to PlatformBenchmarks from step 1.
3. Build and boot the docker container from step 2.
4. Start the app using the following command:
```
mono --llvm --server --gc=sgen --gc-params=mode=throughput PlatformBenchmarks.exe
```
5. Exec into the container and run the client:
```
wrk -t 10 --header "Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7" --header "Connection: keep-alive" http://localhost:8080/plaintext
```

## On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 6.3.0.570 (tarball Thu May  9 11:20:57 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

## Trace Data

I captured a CPU trace using perf_events.  The list below is from a diff of two runs (LLVM-JIT vs. Mini-JIT).  All positive numbers mean that the time was spent in the regressed (LLVM-JIT) case.  Negative numbers mean the time was spent in the baseline case (Mini-JIT).  Units are milliseconds.

What you can see is that the LLVM-JIT case spends a bunch more of its CPU time in runtime functions - 6.2 seconds in ```mono_get_hazardous_pointer```, ~5 seconds in ```jit_infotable_*```, etc.  This CPU time replaces things like ```kernel.kallsyms!_raw_spin_unlock_irqrestore``` and ```kernel.kallsyms!do_syscall_64``` which without the stack are hard to really understand, but are likely attributed to actual work being done.  You can view the [full diff](https://github.com/mono/mono/files/3174816/mono_llvm_wrk_10_10.View1.perfView.xml.zip) in [PerfView](https://github.com/microsoft/perfview/releases) on Windows.

Name |  Exc
-- |  --
mono-sgen!mono_get_hazardous_pointer | 6,267
kernel.kallsyms!_raw_spin_unlock_irqrestore | -3,830
mono-sgen!mono_jit_info_table_find_internal | 1,402
mono-sgen!jit_info_table_chunk_index | 1,389
mono-sgen!jit_info_table_index | 1,228
mono-sgen!jit_info_table_find | 1,047
libpthread-2.24.so!pthread_mutex_lock | 943
kernel.kallsyms!do_syscall_64 | -665
libpthread-2.24.so!__pthread_mutex_unlock_usercnt | 561
mono-sgen!mono_jit_compile_method_with_opt | 512
kernel.kallsyms!finish_task_switch | -473
mono-sgen!monoeg_g_hash_table_lookup_extended | 472
mono-sgen!jit_info_key_extract | 465
libpthread-2.24.so!__lll_lock_wait | 297
mono-sgen!mono_threads_suspend_policy | 290
mono-sgen!mono_magic_trampoline | 287
libpthread-2.24.so!__lll_unlock_wake | 265
mscorlib.dll.so!System_Threading_ThreadPoolWorkQueue_Dispatch | -254
mono-sgen!common_call_trampoline | 243
libc-2.24.so!sched_getaffinity@@GLIBC_2.3.4 | -241
mono-sgen!mono_internal_hash_table_lookup | 238
unknown!/tmp/perf-1249.map | 223
libc-2.24.so!__memmove_avx_unaligned_erms | 221
libc-2.24.so!__getpid | -220
kernel.kallsyms!__fget | -198
mscorlib.dll.so!string_memset_byte__int_int | -186
mono-sgen!mono_method_get_context_general | 168
mono-sgen!mini_jit_info_table_find_ext | 160
mono-sgen!mono_monitor_enter_v4_fast | -137
libpthread-2.24.so!do_futex_wait | -136
mono-sgen!mini_add_method_trampoline | 125
mono-sgen!worker_callback | -119
kernel.kallsyms!__set_current_blocked | -118
vdso!__vdso_clock_gettime | -112
kernel.kallsyms!get_signal | -108

**Comment by brianrob** [comment]
FYI @alexanderkyte, @marek-safar

**Comment by marek-safar** [comment]
@vargaz did you look into reasons behind the slowdown?

/cc @migueldeicaza @SamMonoRT

**Comment by brianrob** [comment]
@marek-safar it sounds like #14520 should make a difference here.

@directhex can you trigger a nightly that includes this?  I'll re-run once we have a new build.

**Comment by directhex** [comment]
Triggered.

**Comment by brianrob** [comment]
Thanks much!

**Comment by marek-safar** [comment]
I believe this has been resolved

**Comment by lewurm** [comment]
@brianrob can you confirm that this issue is resolved? could you provide updated numbers?

**Comment by directhex** [comment]
It was resolved, new numbers went out yesterday

**Comment by brianrob** [comment]
Yes, this is now resolved.  Thanks!
