### ISSUE TITLE
ole32.dll 

### ISSUE THREAD

**Issue by JJImenezna** [mono/mono#14487]
## Steps to Reproduce

1. mono MaxquantCmd.exe file.xml

### Current Behavior

The app hangs with execution external process 5243

In the log of the app appears some errors as follows 
The file  appears to be corrupt. Try to open it with vendor software. Error message: ole32.dll_  

### Expected Behavior
The software works succesfully in windows. In adittion the input file is the same.

## On which platforms did you notice this

 Linux

**Version Used**:

Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 08:39:50 UTC 2019)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
ole32.dll is windows specific dependency, it won't run cross-platform

**Comment by Greenn0** [comment]
I'd like to know whether have you solved the problem?

**Comment by JJImenezna** [comment]
Hello Greenn0

Eventually we were able to download a new versión of the software and with a newer release of mono it is working succesfully. Hope it helps.
Regards

**Comment by Greenn0** [comment]
Thank you JJImenezna.
Recently I have downloaded the new version of Maxquant and mono，but it still couldn't work, and just like what you had described before. 
![搜狗截图19年09月09日2312_1](https://user-images.githubusercontent.com/54265403/64543211-6153ad00-d357-11e9-9508-c56cd88139a8.png)
