### ISSUE TITLE
Add an easy way to print the version number by itself

### ISSUE THREAD

**Issue by aaronfranke** [mono/mono#14491]
### Current Behavior

If you type `mono --version`, you get an output that looks like this:

```
$ mono --version
Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:02:17 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

### Expected Behavior

I would like the ability to do something like this:

```
$ mono --version-number
5.20.1.19
```

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

5.20.1.19

**Comment by lewurm** [comment]
I like this idea, however keep in mind that it will take some while until such an option is useful in the real world, as older mono versions do not understand this flag.

https://github.com/mono/mono/pull/14538
