### ISSUE TITLE
[runtime] Pointers are not Objects

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#14555]
## Steps to Reproduce
```csharp
using System;
using System.Runtime.CompilerServices;

class Program
{
    static unsafe void Main()
    {
        Console.WriteLine(Test(new int*[0]));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static unsafe bool Test(Array a)
    {
        return a is object[];
    }
}
```
### Current Behavior

```
True
```

### Expected Behavior

```
False (CoreCLR)
```

## On which platforms did you notice this

[v] macOS
[ ] Linux
[ ] Windows

**Version Used**:

6.3.0.120

I guess the fix should be somewhere here https://github.com/mono/mono/blob/master/mono/mini/type-checking.c#L684-L689
Related xunit tests (netcore):
```
-nomethod System.Tests.ArrayTests.LastIndexOf_ArrayOfPointers_ThrowsNotSupportedException
-nomethod System.Tests.ArrayTests.Reverse_ArrayOfPointers_ThrowsNotSupportedException
-nomethod System.Tests.ArrayTests.IndexOf_ArrayOfPointers_ThrowsNotSupportedException
```

**Comment by marek-safar** [comment]
@lambdageek please assign

**Comment by lambdageek** [comment]
@CoffeeFlux please take a look at this

**Comment by filipnavara** [comment]
@CoffeeFlux I believe the xunit exclusions were not updated in https://github.com/mono/mono/blob/a5a26a2f92d00ab174d794f077007faaab5d3843/netcore/CoreFX.issues.rsp#L545-L548

**Comment by CoffeeFlux** [comment]
Ah, yeah, totally forgot about that since I just added my own tests. I'll make a second PR; thanks for the heads-up!
