### ISSUE TITLE
why config enable-minimal=interpreter in ios.mk?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14563]
why config enable-minimal=interpreter in ios.mk?
It means mono does not support interpreter on ios at this moment?

**Comment by srxqds** [comment]
@marek-safar @vargaz

**Comment by lewurm** [comment]
@srxqds it means that the interpreter won't be included in `libmonosgen.dylib`/`libmonosgen.a`. However you can link it in on demand, that is what is done today on Xamarin.iOS, see:
https://github.com/xamarin/xamarin-macios/blob/aa18ad3f9200d463edb19ca61acc9e98fa8ef965/tools/mtouch/Target.cs#L1582-L1589
https://github.com/xamarin/xamarin-macios/blob/aa18ad3f9200d463edb19ca61acc9e98fa8ef965/tools/mtouch/mtouch.cs#L581-L587
This is useful to reduce the application size if the interpreter is not needed.

**Comment by srxqds** [comment]
@lewurm so it is not effect embeded mono with interpreter?

**Comment by srxqds** [comment]
ok, thank you @lewurm
