### ISSUE TITLE
[tests] Don't send HTTP requests to Google

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#14585]
See for example https://github.com/mono/mono/pull/14541#issuecomment-494993168

The tests `HttpWebRequestTest.Sync` and `WebClientTest.DownloadTwice` send requests to google.com and if we run enough tests simultaneously, Google starts responding with `(429) Too Many Requests`.

It would be better if we could identify some friendly site for testing (or startup a local server) so that we can rely on a predictable response.

**Comment by baulig** [comment]
The same pattern probably exists in far more tests.  We could for instance block all outgoing network traffic on one bot then run the tests to see which.
