### ISSUE TITLE
what is difference between monotouch and monotouch_runtime?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14588]
what is difference between **monotouch** and **monotouch_runtime**?
I found that **monotouch_runtime** has define macro **FULL_AOT_RUNTIME**, but monotouch not.

Can we use monotouch on iOS at this time?
And is **System.Reflection.Emit** supported on iOS with interpreter at this time?

**Comment by lewurm** [comment]
We have a custom branch to enable `System.Reflection.Emit` in the iOS profiles:
https://github.com/mono/mono/commits/spouliot-2018-08-intr

Specifically check out those commits:
https://github.com/mono/mono/commit/9ba5128ef59e222451728982aa0d0bc7f8b31b57
https://github.com/mono/mono/commit/502980edba374ce54b94d190952137b655a9ab7a
https://github.com/mono/mono/commit/c84f4b0468eb88b92e025e77475f93e8a3618594

**Comment by awattar** [comment]
@lewurm Sorry for bumping the old thread but what is the answer for the main question - "what is difference between monotouch and monotouch_runtime"?

**Comment by lewurm** [comment]
@awattar if I recall correctly, `monotouch` is used on devices and `monotouch_runtime` is used on the simulator. Best have a look at the source: https://github.com/mono/mono/blob/master/mcs/build/profiles/monotouch.make
Note that this includes the definitions of [`monotouch_runtime`](https://github.com/mono/mono/blob/master/mcs/build/profiles/monotouch.make)

/cc @spouliot I hope I got that right 🙂
