### ISSUE TITLE
* Assertion at /mono/mono/mini/interp/interp.c:2585, condition `is_ok (error)' not met, function:interp_create_method_pointer, Attempting to JIT compile method '

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14592]
I am updating my MonoEmbeded test project replace mono-5.18.0.225 with mono-5.20.1.19

## Steps to Reproduce

1. build mono-5.20.1.19
2. replace ios-target64-release and bcl assembly
3. run

### Current Behavior
Assertion!

### Expected Behavior
what's wrong with it?
what is the exactly reason about the problem?
How can I fix it.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] iOS

**Version Used**:
mono 5.20.1.19

## Stacktrace
2019-05-23 20:23:41.908883+0800 RunMonoOniOS[87140:7365474] assembly_preload_hook: mscorlib  /var/containers/Bundle/Application/C553834E-9D03-4F7F-8DD6-8DB0EFBC9CBC/RunMonoOniOS.app
2019-05-23 20:23:41.945727+0800 RunMonoOniOS[87140:7365474] * Assertion at /Volumes/ssd2/mono/MonoEmbedded/mono/mono/mini/interp/interp.c:2585, condition `is_ok (error)' not met, function:interp_create_method_pointer, Attempting to JIT compile method '(wrapper unknown) object:__interp_lmf_mono_interp_entry_from_trampoline (intptr,intptr)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
 assembly:<unknown assembly> type:<unknown type> member:(null)

![image](https://user-images.githubusercontent.com/5187024/58252583-080c4180-7d99-11e9-8706-617ac077c27a.png)

![image](https://user-images.githubusercontent.com/5187024/58252555-fb87e900-7d98-11e9-8af2-573488b1c186.png)

thank you

**Comment by srxqds** [comment]
the mono setting
```c++
typedef enum {
	MONO_AOT_MODE_NONE,
	MONO_AOT_MODE_NORMAL,
	MONO_AOT_MODE_HYBRID,
	MONO_AOT_MODE_FULL,
	MONO_AOT_MODE_LLVMONLY,
	MONO_AOT_MODE_INTERP,
	MONO_AOT_MODE_INTERP_LLVMONLY
} MonoAotMode;

void mono_jit_set_aot_mode (MonoAotMode mode);

extern void mono_aot_register_module (char *name);

extern void mono_ee_interp_init (const char *);
extern void mono_icall_table_init (void);
extern void mono_marshal_ilgen_init (void);
extern void mono_method_builder_ilgen_init (void);
extern void mono_sgen_mono_ilgen_init (void);

extern void *mono_aot_module_mscorlib_info;

void mono_ios_register_modules (void)
{
	mono_aot_register_module (mono_aot_module_mscorlib_info);
}

void mono_ios_setup_execution_mode (void)
{
	mono_icall_table_init ();
	mono_marshal_ilgen_init ();
	mono_method_builder_ilgen_init ();
	mono_sgen_mono_ilgen_init ();
	mono_ee_interp_init (0);
	mono_jit_set_aot_mode (MONO_AOT_MODE_INTERP);
}


```

**Comment by srxqds** [comment]
@marek-safar @lewurm what problem with it?

**Comment by lewurm** [comment]
@srxqds you still need to run the AOT compiler with `--aot=interp` for `mscorlib.dll` and link the resulting object file with the final binary. Xamarin.iOS code:
https://github.com/xamarin/xamarin-macios/blob/2a42a35ba4aaf988df86f62ae2aa7d5408cc1836/tools/mtouch/mtouch.cs#L412-L415

**Comment by srxqds** [comment]
> @srxqds you still need to run the AOT compiler with `--aot=interp` for `mscorlib.dll` and link the resulting object file with the final binary. Xamarin.iOS code:
> https://github.com/xamarin/xamarin-macios/blob/2a42a35ba4aaf988df86f62ae2aa7d5408cc1836/tools/mtouch/mtouch.cs#L412-L415

Thank you @lewurm  I found the problem, I has not recompiled mscorllib aotdata with mono-5.20.1.19.
