### ISSUE TITLE
[wasm] debugger missing locals

### ISSUE THREAD

**Issue by lewing** [mono/mono#14608]
The blazor team isn't seeing locals after taking the lastest debug proxy.

![image](https://user-images.githubusercontent.com/24063/58284058-6f150080-7d6f-11e9-9974-3c9d3eade826.png)

**Comment by lewing** [comment]
It at first glance it looks like this may be related locating sequence points in the razor files.

**Comment by lewing** [comment]
Verified that locals work in some cases (and fixed some issues) in https://github.com/mono/mono/pull/14621

**Comment by lewing** [comment]
I did some more digging locals are working fine in a similar non async method.

**Comment by marek-safar** [comment]
Async methods are special in the way that local variables can be lifted to generated class fields (similar applies to iterators and lambdas). VS4M has code to map them as the whole logic is based on names matching with certain prefixes
