### ISSUE TITLE
download llvm-llvm64 error

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14620]
![image](https://user-images.githubusercontent.com/5187024/58302816-a0e5a000-7e1f-11e9-846a-8d898b71b814.png)

**Comment by lewurm** [comment]
is `/Volumes/ssd2/mono/MonoEmbedded` a git repository?

**Comment by srxqds** [comment]
> is `/Volumes/ssd2/mono/MonoEmbedded` a git repository?

/Volumes/ssd2/mono/MonoEmbedded/mono" is the git repository.

**Comment by lewurm** [comment]
For some reason this part of the `Makefile` doesn't work in your case:
https://github.com/mono/mono/blob/5f87cb724f51b04928189b71f0d0364aaa9e59d9/sdks/builds/llvm.mk#L17
