### ISSUE TITLE
Can we reduce the mscorlib.dll aot compiler generated size?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14647]
I found the mscorlib.dll aot compiler generate mscorlib.o file which is too large(40+m）.

![image](https://user-images.githubusercontent.com/5187024/58366296-c697a580-7f02-11e9-8826-ce7c90e388d0.png)

Can we reduce the size of aot compiler generated files(mscorlib.o)?

**Comment by lewurm** [comment]
you can do this by using the managed linker

**Comment by alexanderkyte** [comment]
If you're using static linking, you may want to try dedup.

Otherwise, I recommend the managed linker as the best way to get sizes down.
