### ISSUE TITLE
Windows/cygwin/CI callstacks inoperational.

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#14645]
Windows/cygwin callstacks inoperational.

https://jenkins.mono-project.com/job/w/22779/parsed_console/log.html

generic-synchronized.2.exe        passed, time: 00:00.032
generic-tailcall2.2.exe           passed, time: 00:00.032
generic-interface-methods.2.exe   passed, time: 00:00.034
/cygdrive/d/j/workspace/w/scripts/ci/babysitter: Sending SIGABRT to `make`
Stack trace:
Frame        Function    Args
000FFFFBD10  0018005FAE9 (00000000000, 00000000000, 00000000000Stack trace:
Frame        Function    Args
000FFFFC240  0018005FAE9 (00000000000, 00000000000, 00000000000, 000FFFFDE50)
00000000002  0018006195A (00000000000, 00180121736, 000FFFFC3E0, 00000000002)
Stack trace:
Frame        Function    Args
000FFFFAD30  0018005FAE9 (00000000000, 00000000007, 0018015DA2A, 000FFFFDE50)
00000000002  0018006195A (000FFFFAF30, 00000000000, 001801221A9, 001802D56B8)
Stack trace:
Frame        Function    Args
000FFFFAD30  0018005FAE9 (00000000000, 00000000007, 0018015DA2A, 000FFFFDE50)
00000000002  0018006195A (000FFFFAF30, 00000000000, 001801221A9, 001802D56B8)
Stack trace:
Frame        Function    Args
000FFFFAD30  0018005FAE9 (00000000000, 006FFFFFFB9, 301F400004B48, 000FFFFDE50)
00000000002  0018006195A (00000000000, 1F800000037F, 00000000000, 000FFFFB058)
Stack trace:
Frame        Function    Args
000FFFFBD10  0018005FAE9 (00000000000, 00000000000, 00000000000, 000FFFFDE50)
00000000002  0018006195A (00000000000, 00180121736, 000FFFFBEB0, 00000000002)
Stack trace:
Frame        Function    Args
000FFFFAD30  0018005FAE9 (00000000000, 00000000007, 0018015DA2A, 000FFFFDE50)
00000000002  0018006195A (000FFFFAF30, 00000000000, 001801221A9, 001802D56B8)
0018022DE30  00180159431 (000FFFFC598, 00000000002, 000FFFFC590, 000FFFFC5B0)
00000000001  0018011DEBB (000FFFFC598, 00000000002, 000FFFFC590, 000FFFFC5B0)
00000000001  001004281C0 (00100484BC0, 0060004C430, 0018011DEBB, 00000000000)
001004B4930  001004297F1 (0060000001F, 00000000008, 00000000000, 0060004C080)
0060004C4D0  001004175EC (00000000000, 00000000000, 000FFFFFFFF, 0060004C510)
00000000000  0010041887E (00000000000, 000FFFFFFFF, 00100482580, 00180324C20)
00000000000  00100417D73 (000FFFFC910, 00000000000, 0018014B3D8, 0060004C0B0)
00000000000  0010045CFC8 (001004822C5, 00000000004, 00000000000, 00000000000)
00000000000  0010047B3BD (0018005B61F, 001801D47A0, 000FFFFCBC0, 00300000001)
00000000000  0010047C468 (000FFFFCC60, 00600000160, 00000000030, FF0700010302FF00)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047A24 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
0018022DE30  00180159431 (000FFFFB080, 000FFFFB160, 00100433360, 006000D9587)
00000000001  0018011DEBB (000FFFFB080, 000FFFFB160, 00100433360, 006000D9587)
00000000001  0010040E939 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFB160  0010040F6FC (00000000000, 173A1F7CA0DBD4EB, 000000020A0, 00600000001)
00000000001  0010041ABE6 (00000000000, 6176652D2A2D2824, 2D7367616C662D6C, 00000292D2A)
00100433594  0010041AE03 (00000000000, 00600016E21, 001004234D7, 00000000000)
000FFFFB3F0  001004245B4 (000FFFFCC70, 00600000160, 00180049DAA, 00180048DF0)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047A24 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
0018022DE30  00180159431 (000FFFFB080, 000FFFFB160, 00100433360, 0060005ABEB)
00000000001  0018011DEBB (000FFFFB080, 000FFFFB160, 00100433360, 0060005ABEB)
00000000001  0010040E939 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFB160  0010040F6FC (00000000000, 173A1F7CA0DBD4EB, 000000020A0, 00600000001)
00000000001  0010041ABE6 (00000000000, 6176652D2A2D2824, 2D7367616C662D6C, 00000292D2A)
00100433594  0010041AE03 (00000000000, 00600016E21, 001004234D7, 00000000000)
000FFFFB3F0  001004245B4 (000FFFFCC70, 00600000160, 00180049DAA, 00180048DF0)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047A24 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
0018022DE30  00180159431 (000FFFFB080, 000FFFFB160, 00100433360, 006000D8ED0)
00000000001  0018011DEBB (000FFFFB080, 000FFFFB160, 00100433360, 006000D8ED0)
00000000001  0010040E939 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFB160  0010040F6FC (00000000000, 173A1F7CA0DBD4EB, 000000020A0, 00600000001)
00000000001  0010041ABE6 (00000000000, 6176652D2A2D2824, 2D7367616C662D6C, 00000292D2A)
00100433594  0010041AE03 (00000000000, 00600016E21, 001004234D7, 00000000000)
000FFFFB3F0  001004245B4 (000FFFFCC70, 00600000160, 00180049DAA, 00180048DF0)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047A24 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
0018022DE30  00180159431 (000FFFFB080, 000FFFFB160, 00100433360, 0060005B920)
00000000001  0018011DEBB (000FFFFB080, 000FFFFB160, 00100433360, 0060005B920)
00000000001  0010040E939 (00000000000, 00000000006, 0000000006E, 00000000000)
000FFFFB160  0010040F6FC (00000000000, 00000000001, 000000020A0, 00600000001)
00000000001  0010041ABE6 (00000000000, 6176652D2A2D2824, 2D7367616C662D6C, 00000292D2A)
00100433594  0010041AE03 (00000000000, 00600016E21, 001004234D7, 00000000000)
000FFFFB3F0  001004245B4 (000FFFFCC70, 00600000160, 00180049DAA, 00180048DF0)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047A24 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
0018022DE30  00180159431 (000FFFFC068, 00000000002, 000FFFFC060, 000FFFFC080)
00000000001  0018011DEBB (000FFFFC068, 00000000002, 000FFFFC060, 000FFFFC080)
00000000001  001004281C0 (00100484BC0, 0060004C600, 0018011DEBB, 00000000000)
001004B4930  001004297F1 (0060000001F, 0000004BEE0, 000FFFFFFFF, 0060004C430)
0060004C8C0  001004175EC (00000000000, 00000000000, 000FFFFFFFF, 0060004DAA0)
00000000000  0010041887E (000FFFFFFF9, 000FFFFC570, 000FFFFC470, 00000000003)
00000000000  0010041B3A7 (00000000000, 0000004C160, 000FFFFFFFF, 0060004C380)
00000000000  00100417E67 (000FFFFC4A0, 00600045A41, 000FFFFC550, 0060004C380)
00000000000  0010041AE29 (00000000000, 00000000000, 000FFFFFFFF, 0060004C380)
00000000000  00100417E67 (00600048320, 006000481F0, 00600048320, 0060004C380)
00000000000  0010041887E (0010041EB87, 0060004AFC0, 0000000002F, 00600039230)
00000000000  0010041ADDD (00000000000, 000FFFFFFFF, 001FFFFFFFF, 0060004C2A0)
00000000000  00100417E67 (000FFFFC910, 00000000000, 0018014B3D8, 0060004C2A0)
00000000000  0010045CFC8 (001004822C5, 00000000004, 00000000000, 00000000000)
End of stack trace (more stack frames may be present)
, 000FFFFDE50)
00000000002  0018006195A (00000000000, 00180121736, 000FFFFBEB0, 00000000002)
0018022DE30  00180159431 (000FFFFC068, 00000000002, 000FFFFC060, 000FFFFC080)
00000000001  0018011DEBB (000FFFFC068, 00000000002, 000FFFFC060, 000FFFFC080)
00000000001  001004281C0 (00100484BC0, 0060004C470, 0018011DEBB, 00000000000)
001004B4930  001004297F1 (0060000001F, 0000004BD40, 00000000000, 00000000000)
0060004C6B0  001004175EC (00000000000, 00000000000, 000FFFFFFFF, 0060004A7A0)
00000000000  0010041887E (000FFFFFFF9, 000FFFFC570, 000FFFFC470, 00000000003)
00000000000  0010041B3A7 (00000000000, 0000004BFD0, 000FFFFFFFF, 0060004C1F0)
00000000000  00100417E67 (00180139357, 000FFFFC530, 000FFFFC750, 0060004C1F0)
00000000000  0010041AE29 (00000000000, 00000000000, 000FFFFFFFF, 0060004C1F0)
00000000000  00100417E67 (00600048320, 006000481F0, 00600048320, 0060004C1F0)
00000000000  0010041887E (0010041EB87, 00600048A60, 0000000002F, 00600039230)
00000000000  0010041ADDD (00000000000, 000FFFFFFFF, 001FFFFFFFF, 0060004C110)
00000000000  00100417E67 (000FFFFC910, 00000000000, 0018014B3D8, 0060004C110)
00000000000  0010045CFC8 (001004822C5, 00000000004, 0000000000

**Comment by marek-safar** [comment]
@jaykrell please follow the requested template to report the issues
