### ISSUE TITLE
mempool allocate bug?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14669]
In the function **mono_mempool_alloc0** why not  reduce **pool->pos** with size if **G_UNLIKELY (pool->pos >= pool->end)** is true?

```c
gpointer
(mono_mempool_alloc0) (MonoMemPool *pool, guint size)
{
	gpointer rval;

	// For the fast path, repeat the first few lines of mono_mempool_alloc
	size = ALIGN_SIZE (size);
	rval = pool->pos;
	pool->pos = (guint8*)rval + size;

	// If that doesn't work fall back on mono_mempool_alloc to handle new chunk allocation
	if (G_UNLIKELY (pool->pos >= pool->end)) {
		rval = mono_mempool_alloc (pool, size);
	}
#ifdef TRACE_ALLOCATIONS
	else if (pool == mono_get_corlib ()->mempool) {
		mono_backtrace (size);
	}
#endif

	memset (rval, 0, size);
	return rval;
}

```

It may a bug of wasting memory?
I think it should add **pool->pos -= size;** after if statement.

```c
if (G_UNLIKELY (pool->pos >= pool->end)) {
                pool->pos -= size;
		rval = mono_mempool_alloc (pool, size);
	}
```

**Comment by jaykrell** [comment]
It's not as bad as it seems.

If the allocation is not large, the memory is going to be lost anyway.

It is only wasted if this is a large `(>= MONO_MEMPOOL_PREFER_INDIVIDUAL_ALLOCATION_SIZE`) allocation but there is room for more small (`< MONO_MEMPOOL_PREFER_INDIVIDUAL_ALLOCATION_SIZE`) allocations.

It does seem to be what was intended though, and the non-0 case does this.

**Comment by jaykrell** [comment]
Even that might not be true. There really might be nothing lost here at all.
But the code could be clearer.
