### ISSUE TITLE
mono 5.20 hangs when called from native thread

### ISSUE THREAD

**Issue by hdornemann** [mono/mono#14725]
I have a application that invokes mono from native code using threads.  Within the managed code it is utilizing generated code to access a soap web service.  This has been working initially implemented against mono 5.02 and was last working with mono 5.18.  With mono 5.20 I see it hanging when creating the soap client object; but only when called from an separate thread, which is calling mono_thread_attach.

## Steps to Reproduce

1. Run the uploaded example 'vSphereTest-Native' 
This is expected to fail as it cannot connect to the web service; It will first execute the managed code from the main thread which will return.  It will then start a thread and execute the same managed code which will get stuck in "Connecting..

[vSphereTest-Native.zip](https://github.com/mono/mono/files/3241224/vSphereTest-Native.zip)

### Current Behavior (output from test program with 5.20)

Starting!
MonoVersion = 5.20.1.19 (tarball)
Method: vSphereTestLibMono.vSphereTest:Test ()
Method: vSphereTestLibMono.vSphereTest:.ctor ()
Calling TestMethod
Connecting
Connected
Returned from TestMethod
thread running
threadArgs d = 0x556dd813aae0, c= 0x556dd81a5d18, obj = (nil)
Calling TestMethod
Connecting
^C <- hangs here

### Expected Behavior (Output from test program with 5.16)

Starting!
MonoVersion = 5.16.0.220 (tarball)
Method: vSphereTestLibMono.vSphereTest:Test ()
Method: vSphereTestLibMono.vSphereTest:.ctor ()
Calling TestMethod
Connecting
Connected
Returned from TestMethod
thread running
threadArgs d = 0x55905c1a9830, c= 0x55905c216d58, obj = (nil)
Calling TestMethod
Connecting
Connected
Returned from TestMethod
thread exiting
Complete!!

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 08:37:52 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by lewurm** [comment]
does running with `MONO_THREADS_SUSPEND=preemptive` fixes your issue? we switched to `hybrid` recently.
