### ISSUE TITLE
eglib g_shell_parse_argv() treats \ in ' quote differently from glib

### ISSUE THREAD

**Issue by steffen-kiess** [mono/mono#14724]
eglib `g_shell_parse_argv()` currently treats a \ in a single quote (') as an escape character, while glib (and POSIX shell) will treat it as a normal character (everything except ' is treated as a normal character inside single quotes).

The following code shows the difference:

````
#include "glib.h"
#include <stdio.h>
/*
gcc test.c -o test-glib $(pkg-config --cflags --libs glib-2.0)
gcc test.c -o test-eglib -Imono/eglib/src mono/eglib/src/.libs/libeglib.a
*/
int main () {
  gint argc;
  gchar** argv;
  if (g_shell_parse_argv("' a \\\\ b '", &argc, &argv, 0)) {
    printf ("%d %s\n", argc, argv[0]);
  }
  return 0;
}
````

With glib this will output:
````
1  a \\ b 
````

With eglib it will output:
````
1  a \ b 
````

The effect of this is that backslashes have to be escaped even in single quotes when launching processes with `Process.Start()`. This behaviour should either be changed to match glib/shell, or the difference should be documented (changing the behaviour might break C# applications which rely on the current behaviour).

**Comment by CoffeeFlux** [comment]
With the following C program (which I've called printout.c):
```
#include <stdio.h>

int main (int argc, char *argv[]) {
	printf("%s\n", argv[1]);
}
```
and the following C# program:
```
using System;
using System.Diagnostics;

class Program {
	static void Main() {
		Process.Start("printout.o", "'a\\\\b'");
		Process.Start("printout.o", "'a \\\\ b'");
	}
}
```
you get different results between Mono and .NET Core in VS4M, at least on OSX.
Mono output:
```
a\b
a \ b
```
Core output:
```
'a\\b'
'a
```

**Comment by jaykrell** [comment]
Sorry to be negative but there are no good answers here.

Every solution will have holes.

If you want an array of strings, use an array.

Smushing the array into a string cannot be done unambiguously.

There are too many quoters and unquoters to have any chance.

If you want to pass it across a process boundary, use an RPC mechanism with some level of typing.

Posix exec does actually pass "split" arrays losslessly, an array of pointers.
This is something it does better.

Windows "GetCommandLine" and "CreateProcess" are unfortunately messed up, dealing with a flattened string, and this might have infected BCL interface.

To be fair, the NT kernel has no notion of a command line at all.
It just runs .exe w/o parameters.
The brokenness is a usermode construct.

**Comment by CoffeeFlux** [comment]
There's definitely no perfect solution, but eglib not handling single quotes with escape characters properly is an easy fix. We'll probably never perfectly align with Core, but we should at least try to have consistent behavior for common cases, which is currently not the case.
