### ISSUE TITLE
Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-02/mac/release/mono/utils/strenc.c:184, condition `utf8!=NULL' not met

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#14730]
## Steps to Reproduce

Unfortunately I don't have a way to reproduce this, it's a random issue and it's hit twice today, with two different Xamarin.Mac tests.

Reference: https://github.com/xamarin/maccore/issues/1685

I have the crash info dumped to the terminal:

* https://gist.github.com/rolfbjarne/9c294a19c1a0fc9fd4883263a5cae1d3
* https://gist.github.com/rolfbjarne/56220c52d47db8bde35dfedbfc717386

and the native stack trace looks identical in both:

```
0x11001f3cf - test.app/Contents/MacOS/test : monoeg_assertion_message
0x110017dbe - test.app/Contents/MacOS/test : mono_unicode_to_external
0x1100090bf - test.app/Contents/MacOS/test : mono_pe_file_map
0x10ffa5bb1 - test.app/Contents/MacOS/test : mono_w32process_get_fileversion_info
0x10ffa7cc1 - test.app/Contents/MacOS/test : mono_w32process_get_fileversion
0x10ffa8a6b - test.app/Contents/MacOS/test : ves_icall_System_Diagnostics_Process_GetModules_internal
```

This is with xamarin-macios [from today](https://github.com/xamarin/xamarin-macios/commit/8e2bbe8d2dc8ddb74106504981ae58970a0263b1
); mono hash is bab25c0a80f7a9ad8f1f18be227119384e3ec0a0 (2019-02).

**Comment by marek-safar** [comment]
@lambdageek any ideas about this?

**Comment by lambdageek** [comment]
After #14879 and #15064 we should get better reports (including the raw hex bytes of the string that we're failing to convert) if this shows up again.

**Comment by rolfbjarne** [comment]
We got a crash with the improved information:

```
...
16:33:30.7090040 	[PASS] ProcessTest.HasExitedCurrent
16:33:30.8075180 ??2019-06-28 16:33:30.807 com.xamarin.bcltests.Mac OS X BCL tests group 2[10755:118302539] error: * Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-06/mac/release/mono/utils/mono-proclib.c:1038, condition `filename_ext != NULL' not met, function:mono_pe_file_map, mono_pe_file_map: unicode conversion returned NULL; Illegal byte sequence encounted in the input. assembly:<unknown assembly> type:<unknown type> member:(null); input was: 2F 
```

[Complete log file](http://xamarin-storage/jenkins/xamarin-macios/PR-6196/4a8f86eacbc0a4535877a94242c23d4420325211/30/jenkins-results/tests/%5bNUnit%5d%20Mono%20Mac%20OS%20X%20BCL%20tests%20group%202/302/execute-Mac-20190628_163241.txt)

Reference: https://github.com/xamarin/xamarin-macios/pull/6196#issuecomment-506890478

**Comment by lewurm** [comment]
@CoffeeFlux @lambdageek does the improved report posted by Rolf help to diagnose the issue?
