### ISSUE TITLE
[bug]method_to_ir results in out-of-memory

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14742]
https://github.com/mono/mono/blob/886c49017470112af1a73034d8951d6ca00b641e/mono/mini/method-to-ir.c#L7364

f = (float *)mono_domain_alloc (cfg->domain, sizeof (float));

If there are many float args with a lot of method, it results in out-of-memory because the memory return from **mono_domain_alloc** don't free util the domain unloaded.

why not use 
``` c
f = (float*)mono_mempool_alloc(cfg->mempool, sizeof(float));
```

**Comment by lewurm** [comment]
The address of the allocated `float` is embedded into native code, therefore it has the same lifetime as the generated machine code. We need to store those floats somewhere.

**Comment by srxqds** [comment]
@lewurm Can I restore it in the **cfg->mempool** because store it in domain->mp can't not free, it can free with cfg->mempool destroy, We want to make the jit code can be free.

**Comment by srxqds** [comment]
And If we have a lot of float argument method it will lead to out of memory If the domain don't unload.
So I think it should a bug should to solve.
@lewurm
