### ISSUE TITLE
[optimization]	cache runtime_invoke 

### ISSUE THREAD

**Issue by srxqds** [mono/mono#14751]
The runtime_invoke may create repate for the same invoke method.
https://github.com/mono/mono/blob/e27cda23e0ff7d2427e12e27329a3bb012d9b744/mono/mini/mini-runtime.c#L2877

If we cache the runtime_invoke, it can reduce create jit method repeatly and save a lot memory.

**Comment by marek-safar** [comment]
Please submit such suggestions via PRs

**Comment by srxqds** [comment]
@marek-safar  ok ，I will try to pull request later.
thank you !

**Comment by lewurm** [comment]
`info` is cached in `domain_info->runtime_invoke_hash`
