### ISSUE TITLE
[sdks][ios] Perform the appropriate cast of objc_msgSend and friends

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#14792]
With the new Xcode 11 the objc_msgSend we have OBJC_OLD_DISPATCH_PROTOTYPES == 0 which enforces the rule that the dispatch functions must be cast to an appropriate function pointer type.

This means that we need to perform the cast in several methods, specially the ones found in mono/utils/mono-threads-mach-helper.c 

A workaround is to #define OBJC_OLD_DISPATCH_PROTOTYPES 1 but a much better approach is to find the calls and cast.

**Comment by akoeplinger** [comment]
Undo the -DOBJC_OLD_DISPATCH_PROTOTYPES=1 workaround that was landed as part of #14820 once this is fixed
