### ISSUE TITLE
Dynamic Basic Block Profiling with Clang Instrumentation

### ISSUE THREAD

**Issue by t-takhan** [mono/mono#14817]
I am trying to use llvm instrumentation and corresponding profile guided optimization infrastructure to generate dynamic execution frequency for each basic block of a given workload. Usually, I use this infrastructure using the following commands to generate the profile for a bitcode file, `example.bc`:

```
# adding instrument logic to the example.bc intermediate representation
opt -pgo-instr-gen -instrprof example.bc -o example.inst.bc
# generate binary executable with profiler embedded
clang -fprofile-instr-generate example.inst.bc -o example.inst
# run the instrumented program to collect profile data. After this run, a filed named default.profraw is created, which contains the profile data
./example.inst
```

I am trying to do that for mono aot compiled binary to generate the profile of instrumented execution. When I run `mono --aot=llvm MicroBenchmarks.exe` , I see the following output,

```
Mono Ahead of Time compiler - compiling assembly /home/takhandipu/tmp/performance/artifacts/bin/MicroBenchmarks/Release/net461/MicroBenchmarks.exe
AOTID 27D0BA68-F8CA-299B-9DA8-37A0612FF258
Executing opt: "/usr/lib/mono/llvm/bin/opt" -f -O2 -disable-tail-calls -o "mono_aot_LDlXli/temp.opt.bc" "mono_aot_LDlXli/temp.bc"
Executing llc: "/usr/lib/mono/llvm/bin/llc"  -march=x86-64 -mattr=sse4.1 -asm-verbose=false -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=mono_aot_MicroBenchmarks_eh_frame -disable-tail-calls -no-x86-call-frame-opt -relocation-model=pic -filetype=obj -o "mono_aot_LDlXli/temp-llvm.o" "mono_aot_LDlXli/temp.opt.bc"
Code: 11010(3%) Info: 57127(20%) Ex Info: 56193(20%) Unwind Info: 291(0%) Class Info: 17454(6%) PLT: 42180(15%) GOT Info: 71120(25%) Offsets: 25495(9%) GOT: 34136
Compiled: 6491/6491 (100%), LLVM: 6473 (99%), No GOT slots: 0 (0%), Direct calls: 0 (0%)
Executing the native assembler: "as" --64  -o /tmp/mono_aot_ZskRM2.o /tmp/mono_aot_ZskRM2
Executing the native linker: "ld"  -shared -o /home/takhandipu/tmp/performance/artifacts/bin/MicroBenchmarks/Release/net461/MicroBenchmarks.exe.so.tmp "mono_aot_LDlXli/temp-llvm.o" /tmp/mono_aot_ZskRM2.o
JIT time: 1618 ms, Generation time: 18705 ms, Assembly+Link time: 383 ms.
```

It seems to me that, mono aot with llvm does not even use clang. While I can run the `opt -pgo-instr-gen -instrprof -o temp.inst.bc temp.opt.bc` command (first step to add instrumentation logic) on the mono-generated bitcode, I am not able to run clang with `-fprofile-instr-generate ` for this build (the second step).
 
I tried to find what are the subsequent llc or ld flag that `clang -fprofile-instr-generate` uses so that I can use those flags on mono workflow’s llc or ld command. It turns out ` clang -fprofile-instr-generate` only uses ld with flags ` -u__llvm_profile_runtime /home/takhandipu/llvm/build/lib/clang/8.0.0/lib/linux/libclang_rt.profile-x86_64.a `. However adding this flag to ld command on mono’s aot workflow didn’t work either.
 
In this scenario, can anyone of you tell me how I can pass clang `-fprofile-instr-generate` flag to mono workflow so that mono runs my instrumented aot binary and produce the profile data?
 
Alternatively, is there any mono-specific framework or infrastructure through which I can get this dynamic execution frequency for each basic block of a given workload?
 
Apologies for such a long message. I am not fully aware of mono workflow and may miss something very obvious in the llvm based aot compilation. Apologies for that as well. I really appreciate your time and consideration.

**Comment by lewurm** [comment]
That sounds interesting!

Instead of `clang` we use `llc` to turn LLVM bitcode to the target machine code. You can control the flags passed to `llc` with `--aot=llvmllc=[options],llvm`, or see here: https://github.com/mono/mono/blob/e548a7d231e936562fcc301826034c14e4bc9d7b/man/mono.1#L237-L248

Unfortunately it looks like that `llc` itself doesn't understand `-fprofile-instr-generate`. Maybe you find something that you could pass there instead, for example I would have a look at `clang -v` vs. `clang -v -fprofile-instr-generate`. Note that also additional linker flags can be passed for the `ld` invaction (that happens after `llc`) via `--aot=ld-flags=[...],[...]`.

I hope this helps. Let us know what results you get out of it.

**Comment by alexanderkyte** [comment]
Checking out the history of that option here: 
https://github.com/llvm-mirror/clang/commit/88cb08718ca2f4f8e07dfcb5c1d8fbb31f08d1ab
and
https://github.com/llvm-mirror/clang/commit/d19add92787c0c2cf53f24ac0d3e33a4a7cb88ee#diff-40655b7bc362d33b3bc08bb39e303651R777

It seems likely to be currently emitted by clang's C compiler frontend, and incompatible with a bitcode workflow. 

It may be worth seeing what the format of this file format is, and if there are any C libraries for working with it. If so, Mono could interop with it the way that clang does.

**Comment by t-takhan** [comment]
Thanks @lewurm and @alexanderkyte for your suggestions.

I actually have tried finding subsequent `llc` or `ld` flag that `clang -fprofile-instr-generate` uses with `-v` flag. For example, `clang++ -v -fprofile-instr-generate test.cpp.prof.bc -o test.prof` generates the following output. Even though, this for `clang++`, I think `clang` output would be similar as well.

```
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/takhandipu/llvm/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/takhandipu/llvm/build/bin/clang-8" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp.prof.bc -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -fprofile-instrument=clang -resource-dir /home/takhandipu/llvm/build/lib/clang/8.0.0 -fdebug-compilation-dir /tmp/delete -ferror-limit 19 -fmessage-length 111 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/test-6110fa.o -x ir test.cpp.prof.bc -faddrsig
clang -cc1 version 8.0.0 based upon LLVM 8.0.0 default target x86_64-unknown-linux-gnu
 "/usr/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o test.prof /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7.4.0/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/7.4.0 -L/usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../.. -L/home/takhandipu/llvm/build/bin/../lib -L/lib -L/usr/lib /tmp/test-6110fa.o -u__llvm_profile_runtime /home/takhandipu/llvm/build/lib/clang/8.0.0/lib/linux/libclang_rt.profile-x86_64.a -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/7.4.0/crtend.o /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../x86_64-linux-gnu/crtn.o
```

Just like both of you pointed out, this compilation is not even using llc. And only `ld` flag relevant to `-fprofile-instr-generate` is `-u__llvm_profile_runtime /home/takhandipu/llvm/build/lib/clang/8.0.0/lib/linux/libclang_rt.profile-x86_64.a`, I think. I could be wrong and that's why I am logging the output of `clang -v` here. However, adding just this `-u__llvm_profile_runtime /home/takhandipu/llvm/build/lib/clang/8.0.0/lib/linux/libclang_rt.profile-x86_64.a` flag to ld didn't result into profile generation. 

@alexanderkyte can you explain I little bit more on the 

> seeing what the format of this file format is, and if there are any C libraries for working with it. If so, Mono could interop with it the way that clang does

Sorry for my lack of understanding. Can you give me a bit more information on how to interop clanged way to mono llc. I think the solution approach you suggested is the right way of doing that. I just need to know a little bit more on how I can achieve that.

**Comment by alexanderkyte** [comment]
I am not sure what clang does there, and that would be some work.

If you can get clang++ to generate the files from IR, you could try using our bitcode AOT configuration. It's a bit slower, but it generates IR that is valid LLVM IR for a certain version of LLVM.

**Comment by t-takhan** [comment]
Another related query I had is that, I found `mono` itself has options like [code coverage](https://www.mono-project.com/docs/debug+profile/profile/code-coverage/) and [log profiler](https://www.mono-project.com/docs/debug+profile/profile/profiler/). I was wondering could any of these two options generate execution frequency for higher level (e.g., C#) code? In that case, I could have used the Debug information from the generated IR to count execution frequency for each IRs. Specially, code coverage seems to be very relevant to execution frequency as well and the same infrastructure should be used in a way to generate the execution frequency. I could be wrong and that's why, I am wondering whether it's possible.

**Comment by t-takhan** [comment]
> I am not sure what clang does there, and that would be some work.
> If you can get clang++ to generate the files from IR, you could try using our bitcode AOT configuration. It's a bit slower, but it generates IR that is valid LLVM IR for a certain version of LLVM.

So what you suggesting is something like this, I will generate only the llvm bitcode file for the dotnet program. Then, I will convert the generated bitcode into binary executable with clang along with my required flag `-fprofile-instr-generate`. Then, I will run the generated binary without mono to get my dynamic execution frequency profile. Is this what you are suggesting?

> It is used by passing "llvmonly" to the AOT line.

When I run `mono --aot=llvmonly,llvm-outfile=mine.bc MicroBenchmarks.exe`, I get following error:

```
Mono Ahead of Time compiler - compiling assembly /home/takhandipu/tmp/performance/artifacts/bin/MicroBenchmarks/Release/net461/MicroBenchmarks.exe
AOTID BC438FD4-B530-A707-7D20-410C891BFBD7
mono: symbol lookup error: /usr/lib/libmono-llvm.so: undefined symbol: mono_rgctx_info_type_to_str
```

I have not installed mono after building from source. Instead, I have installed mono via apt along with `mono-llvm-dev`, `mono-llvm-support`, and `mono-llvm-tools`. Is this why, `llvmonly` option cannot find the symbol `mono_rgctx_info_type_to_str` on `libmono-llvm.so`. My mono version is 5.20.1.19.

**Comment by vargaz** [comment]
Mono currently emits a mix of llvm and non-llvm code when running with --aot=llvm, since our llvm backend can't handle some .net constructs like filter clauses. This implemented by running opt+llc to generate a .s and linking it with the .s file generated by non-llvm compiler. This means its kinda hard to integrate pgo into this workflow, since that seems to be done by clang.

As for the error in the previous section, thats already fixed in mono master.

**Comment by vargaz** [comment]
There should be newer debian packages here:
https://www.mono-project.com/download/preview/#download-lin

**Comment by t-takhan** [comment]
> There should be newer debian packages here:
> https://www.mono-project.com/download/preview/#download-lin

Thank you @vargaz I am updating my mono via newer Debian packages. Sorry for the inconvenience.

**Comment by t-takhan** [comment]
> There should be newer debian packages here:
> https://www.mono-project.com/download/preview/#download-lin

I upgraded my mono installation using the Debian packages (I have tried the ubuntu package as well with similar error) listed on the above link. However, after upgrading the mono installation, even `--aot=llvm` option (`mono --aot=llvm hello.exe`) results into following error described in [this issue](https://github.com/mono/mono/issues/13820),

```
...
llvm load failed: /usr/lib/libmono-llvm.so: undefined symbol: mono_patch_info_equal
...
```

I am guessing, my installed version from Debian package is not stable. Instead, I will build mono from source with llvm-support. My version is,

```
Mono JIT compiler version 6.0.0.277 (tarball Tue Jun  4 10:14:29 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

**Comment by t-takhan** [comment]
Hello @lewurm @alexanderkyte and @vargaz  

If I use `mono --aot=llvmonly`, it actually uses `clang++` instead of `llc` and `ld` to compile the `.bc` file into `.o` file and `.o` file to `.so.tmp` file respectively. However, I could not find any `aot` flag to add my required `-fprofile-instr-generate` into `clang++` replacement of `llc`. For example, the command `mono --aot=llvmonly,llvmopts='-pgo-instr-gen -instrprof',llvmllc='-fprofile-instr-generate',ld-flags='-fprofile-instr-generate',save-temps,keep-temps hello.exe` generates the following output,

```
Mono Ahead of Time compiler - compiling assembly /home/t-takhan/tmp/hello/hello.exe
AOTID 98EAF6AA-2FB0-AE89-EA1C-B0369CBAEAF8
Executing opt: "/usr/lib/mono/llvm/bin/opt" -f -pgo-instr-gen -instrprof -o "mono_aot_5JAmKy/temp.opt.bc" "mono_aot_5JAmKy/temp.bc"
Executing clang: clang++ -fexceptions -march=x86-64 -fpic -msse -msse2 -msse3 -msse4 -O2 -fno-optimize-sibling-calls -Wno-override-module -c -o "mono_aot_5JAmKy/temp-llvm.o" "mono_aot_5JAmKy/temp.opt.bc"
Code: 0(0%) Info: 14(1%) Ex Info: 20(2%) Unwind Info: 0(0%) Class Info: 22(2%) PLT: 1(0%) GOT Info: 597(71%) Offsets: 177(21%) GOT: 200
Compiled: 4/4 (100%), LLVM: 0 (0%), No GOT slots: 2 (50%), Direct calls: 0 (100%)
Executing the native assembler: "as" --64  -o /tmp/mono_aot_1zOmh5.o /tmp/mono_aot_1zOmh5
Executing the native linker: clang++  -shared -o /home/t-takhan/tmp/hello/hello.exe.so.tmp "mono_aot_5JAmKy/temp-llvm.o" /tmp/mono_aot_1zOmh5.o -fprofile-instr-generate -lstdc++
Retained input file.
JIT time: 0 ms, Generation time: 154 ms, Assembly+Link time: 196 ms.
```

Unfortunately, adding `-fprofile-instr-generate` to `clang++` replacement of `ld` does not generate the dynamic profile output of executable.

Even though `ld-flags` append my required `-fprofile-instr-generate` flag to the `clang++` replacement of `ld`, doing the same for `llvmllc` does not work. Can any of you tell me which flag I can use in case of `llvmonly` so that my `clang++` replacement of `llc` uses ``-fprofile-instr-generate`` flag? 

Thank you in advance for your help.

**Comment by alexanderkyte** [comment]
To help you understand this, it is running this code here: 
https://github.com/mono/mono/blob/master/mono/mini/aot-compiler.c#L9691-L9699

```
	if (acfg->aot_opts.llvm_only) {
		/* Use the stock clang from xcode */
		// FIXME: arch
		command = g_strdup_printf ("%s -fexceptions -fpic -O2 -fno-optimize-sibling-calls -Wno-override-module -c -o \"%s\" \"%s.opt.bc\"", acfg->aot_opts.clangxx, acfg->llvm_ofile, acfg->tmpbasename);

		aot_printf (acfg, "Executing clang: %s\n", command);
		if (execute_system (command) != 0)
			return FALSE;
		return TRUE;
	}
```

which makes me fear that you may have to recompile Mono if you're hoping to use that workflow. 

You may have an easier time passing `--aot=asmonly,llvm-outfile=foo.bc` and then running clang++ on it yourself. That will give you all of the freedom here to use our bitcode files as you want.

**Comment by t-takhan** [comment]
Hello @alexanderkyte 
Thank you very much for describing both the ways. I will try the first ways.

I have already tried the second approach with flag `--aot=asmonly,llvmonly,llvm-outfile=foo.bc`. Unfortunately, the generated `foo.bc` does not contain any `main` function and could not be compiled into a standalone executable. It can only be compiled as a shared library with `-fpic -shared`. However, if compile with `-fpic -shared` the pgo profile generation of clang does not work. I mean if I generate mono's aot shared file `foo.exe.so` using `clang -fprofile-instr-generate foo.opt.bc -fpic -shared  -o foo.exe.so` and run `mono foo.exe` to generate the profile data, no profile data is created.

Thanks any way for your help. I really appreciate it.

**Comment by alexanderkyte** [comment]
@t-takhan if you check out the above code sample, our usage of clang uses 

```
-fpic -c 
```

which may be closer to what you want than

```
-fpic -shared
```

**Comment by SamMonoRT** [comment]
Closing this issue. If you encounter the same using dotnet\runtime repo, please re-open in that repo.
