### ISSUE TITLE
[netcore]Implement Environment.FailFast

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14827]
See the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.environment.failfast?view=netcore-3.0) for full description.

Couple of call outs:
1.) The process should write out a crash dump before terminating.  It would be nice if we could use our crash reporter as I think it does that plus a bunch of other useful things.
2.) On windows, we should write to the event log.  I don't know what the behavior is on other platforms.

**Comment by NattyNarwhal** [comment]
windows event log would probably be closest to syslog(3) for unix (pretend-unices will redirect to system natve logging, and unix systems often have remote log servers set up). android/iOS have equivalent, but unsure.

producing a dump might be helpful, but since a program's logic might be using FailFast for its own reasons, it could be unexpected/undesirable

**Comment by NattyNarwhal** [comment]
> producing a dump might be helpful, but since a program's logic might be using FailFast for its own reasons, it could be unexpected/undesirable

ahhh yes, i didn't read [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.environment.failfast?view=netframework-4.8) - that's documented API surface

**Comment by EgorBo** [comment]
As a quick implementation: `this.Exit(134)` 🙂

**Comment by filipnavara** [comment]
Anyone working on it? I'd just move the CoreRT implementation to shared and reuse it.

**Comment by marek-safar** [comment]
I don't think anyone is working on this task

**Comment by filipnavara** [comment]
I didn't know about `__failfast`. It is interesting option but unfortunately it's available only on Windows 8+.

**Comment by NattyNarwhal** [comment]
Doesn't `_exit` quite without proper termination on POSIX?

**Comment by jaykrell** [comment]
“Fast” means “proper termination” is dangerous and best to skip it.

**Comment by NattyNarwhal** [comment]
Which is what I'm saying; `_exit` exits without calling any termination handlers.

The only caveat though, is I think `_exit` is not declared in system headers, (being a libc impl detail) so you get a warning from the compiler. C99 *does* standardize `_Exit` though, which is functionally equivalent, and systems sometimes have their own implementation too (like AIX and `quick_exit` though it supports the C99 way too). Example:

```c
#include <stdio.h>
#include <stdlib.h>

void x(void) {
        printf("atexit handler reached\n");
}

int main(void){
        atexit(x);
        printf("exiting\n");
#ifdef _EXIT
        _exit(0);
#else
        exit(0);
#endif
        return 1;
}
```

```
$ gcc -maix64 -o atexit-exit atexit.c
$ gcc -maix64 -o atexit-_exit -D_EXIT atexit.c
atexit.c: In function 'main':
atexit.c:12:2: warning: implicit declaration of function '_exit' [-Wimplicit-function-declaration]
  _exit(0);
  ^~~~~
atexit.c:12:2: warning: incompatible implicit declaration of built-in function '_exit'
```

```
aix$ ./atexit-_exit
exiting
aix$ ./atexit-exit
exiting
atexit handler reached
```

**Comment by jaykrell** [comment]
Ah. I thought you were criticizing it, not advocating yes. Yes, those are all good
 candidates. Abort, _exit, _Exit, quick_exit.
There is tension between error reporting, esp. in-proc, safely (w/o crash or undefined) & actually exiting.

**Comment by jaykrell** [comment]
Oops I missed that, darn:
`Support for the native fast fail mechanism began in Windows 8`.
It is just an instruction, not a function, but yeah, the handling of it.

**Comment by filipnavara** [comment]
I reevaluated the idea of using the CoreRT code and I no longer think it's a wise idea. While the code itself it quite similar to what CoreCLR does the idea of using managed code is problematic. The method should be as fail-safe as possible and involving JIT partially defies the purpose. In CoreRT it is not a problem as there's a guarantee that everything is precompiled. There is no such guarantee in Mono and pessimistically precompiling the FailFast code path seems like an overkill.

I'll try to take an approach with regular InternalCall much like it works in CoreCLR today.
