### ISSUE TITLE
[netcore]Implement Monitor.LockContentionCount

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14828]
This may or may not help, but here's the link to coreclr's implementation

https://github.com/dotnet/coreclr/blob/82bd51f001c8df3def3b327bb31fc7611539cbd8/src/vm/threads.h#L3966

**Comment by filipnavara** [comment]
And CoreRT implementation (managed code) for reference: https://github.com/dotnet/corert/pull/7066

**Comment by filipnavara** [comment]
Returning 0 allows BDN to proceed as a temporary measure. It looks like implementing the counter should not be too hard though.

**Comment by lambdageek** [comment]
We're going to try to schedule @alexischr to do this follow-up work: https://github.com/mono/mono/pull/16538#issuecomment-529388153:
> Unfortunately the [test](https://github.com/dotnet/corefx/blob/34fe566b6f6bd739a876e7e1dc48cf631647e5d7/src/System.Threading/tests/MonitorTests.netcoreapp.cs) would not work yet. Performance counters are globally disabled in netcore build in configure script. We'd either need to re-enable it or offer an alternate implementation here.
