### ISSUE TITLE
[xamarin] TimeZoneInfo.Local always returns "Local" name

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#14839]
## Steps to Reproduce

1.  `Console.WriteLine(TimeZoneInfo.Local.Id);`

### Current Behavior

Always returns "Local".

### Expected Behavior

Returns the name of the current time zone.

## On which platforms did you notice this

[x] macOS
[x] iOS
[ ] Linux
[ ] Windows

**Version Used**:

5.18.1, 6.0, 6.5 (master)

## Description

Essentially this is the same issue as https://github.com/mono/mono/issues/8267. It was fixed on desktop but it remains an issue on Xamarin macOS/iOS platforms due to this code:

https://github.com/mono/mono/blob/515234a128318cc199df0cca9cccdbf06fe72fdb/mcs/class/corlib/System/TimeZoneInfo.MonoTouch.cs#L49-L51

**Comment by artur-malendowicz-gain** [comment]
@jonpryor any ETA for this?
