### ISSUE TITLE
LLVM extremely slow for unlinked Xamarin.iOS.dll in 2019-06

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#14843]
The "don't link" test application takes almost 25 minutes to compile in 2019-06 for the iOS 64 bit Device Release configuration, compared to about 3 minutes in 2019-02.

The bulk of the time is spent in Xamarin.iOS.dll.

2019-02:

```
14:59:29.1461680   Mono Ahead of Time compiler - compiling assembly /Users/alexander/dev/xamarin-macios/xamarin-macios-master/tests/xharness/tmp-test-dir/dont link587/obj/iPhone/Release64-unified/mtouch-cache/3-Build/Xamarin.iOS.dll (Aufgaben-ID: 112)
14:59:29.1462630   AOTID F8D95594-6050-30F7-D04C-E63BFD3C081E (Aufgaben-ID: 112)
14:59:29.1462820   Executing opt: "/Users/alexander/dev/xamarin-macios/xamarin-macios-master/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/LLVM/bin/opt" -f -O2 -disable-tail-calls -o "/Users/alexander/dev/xamarin-macios/xamarin-macios-master/tests/xharness/tmp-test-dir/dont link587/obj/iPhone/Release64-unified/mtouch-cache/arm64/Xamarin.iOS.dll.s.opt.bc" "/Users/alexander/dev/xamarin-macios/xamarin-macios-master/tests/xharness/tmp-test-dir/dont link587/obj/iPhone/Release64-unified/mtouch-cache/arm64/Xamarin.iOS.dll.s.bc" (Aufgaben-ID: 112)
14:59:29.1463120   Executing llc: "/Users/alexander/dev/xamarin-macios/xamarin-macios-master/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/LLVM/bin/llc"  -march=aarch64 -asm-verbose=false -mtriple=arm64-ios -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=_mono_aot_Xamarin_iOS_eh_frame -disable-tail-calls -relocation-model=static -filetype=obj -o "/Users/alexander/dev/xamarin-macios/xamarin-macios-master/tests/xharness/tmp-test-dir/dont link587/obj/iPhone/Release64-unified/mtouch-cache/arm64/Xamarin.iOS.dll-llvm.o" "/Users/alexander/dev/xamarin-macios/xamarin-macios-master/tests/xharness/tmp-test-dir/dont link587/obj/iPhone/Release64-unified/mtouch-cache/arm64/Xamarin.iOS.dll.s.opt.bc" (Aufgaben-ID: 112)
14:59:29.1463290   Compiled: 93058/93058 (Aufgaben-ID: 112)
14:59:29.1463520   Output file: '/Users/alexander/dev/xamarin-macios/xamarin-macios-master/tests/xharness/tmp-test-dir/dont link587/obj/iPhone/Release64-unified/mtouch-cache/arm64/Xamarin.iOS.dll.s'. (Aufgaben-ID: 112)
14:59:29.1463670   Linking symbol: '_mono_aot_module_Xamarin_iOS_info'. (Aufgaben-ID: 112)
14:59:29.1463910   LLVM output file: '/Users/alexander/dev/xamarin-macios/xamarin-macios-master/tests/xharness/tmp-test-dir/dont link587/obj/iPhone/Release64-unified/mtouch-cache/arm64/Xamarin.iOS.dll-llvm.o'. (Aufgaben-ID: 112)
14:59:29.1464060   JIT time: 17264 ms, Generation time: 158812 ms, Assembly+Link time: 0 ms. (Aufgaben-ID: 112)
```

2019-06:

```
14:34:14.7011550   JIT time: 16719 ms, Generation time: 1334801 ms, Assembly+Link time: 10 ms. (Aufgaben-ID: 112)
```

**Comment by vargaz** [comment]
Probably fixed by:
https://github.com/mono/mono/pull/14714

**Comment by akoeplinger** [comment]
Ok cool, I issued a backport for that PR :)

**Comment by akoeplinger** [comment]
@vargaz so I tried the fix but it doesn't seem to help in this case. Note that I'm seeing `llc` taking a long time, not `opt`.

**Comment by akoeplinger** [comment]
Here's the repro dir:

[2-PreBuild.zip](https://github.com/mono/mono/files/3262084/2-PreBuild.zip)

**Comment by lewurm** [comment]
output of `llc -time-passes`:
```

===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 1250.5806 seconds (1251.2161 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  886.8886 ( 73.2%)  24.5277 ( 62.9%)  911.4164 ( 72.9%)  911.7388 ( 72.9%)  Simple Register Coalescing
  150.1114 ( 12.4%)   0.1650 ( 0.4%)   150.2764 ( 12.0%)  150.2972 ( 12.0%)  Branch Probability Basic Block Placement
[...]
```
full output: https://gist.github.com/lewurm/da82a493b86c914e1505ebe2215029c1
not sure what is going on. did we start to generate an unreasonable amount of variables?

**Comment by lewurm** [comment]
I bisected it down to this 04d65f29866cc7cfdcfced9a04ec54b4d7e2637e

@alexanderkyte any idea?

**Comment by alexanderkyte** [comment]
@lewurm you're looking for a second-derivative diff.

You should do an `llvm-diff` after doing an `llvm-dis` on the bitcode with that change enabled and disabled (MONO_DEBUG="llvm-disable-self-init"). See if you see any differences other than the init check basic block added.

**Comment by alexanderkyte** [comment]
If you don't see those differences, it probably indicates that the init check itself is introducing some locals or phi nodes that are problematic.

**Comment by lewurm** [comment]
@alexanderkyte `MONO_DEBUG="llvm-disable-self-init"` segfaults for me 😕 

Could you please have a look at it? It's pretty easy to reproduce with the repro from https://github.com/mono/mono/issues/14843#issuecomment-499520634 and `make -C sdks/builds package-ios-cross64 -j` on master.

**Comment by alexanderkyte** [comment]
What I think might be happening is inlining. 

That PR makes calls direct, so LLVM has the opportunity to inline them. Inlined calls cause the caller to have the inlined functions locals inserted into the body. More locals puts the register allocator under more pressure.

**Comment by alexanderkyte** [comment]
We can disable inlining separately from the direct calls here to confirm: 

Still getting this building and reproducing @akoeplinger @lewurm 
https://github.com/mono/mono/pull/14880

**Comment by alexanderkyte** [comment]
@akoeplinger if https://github.com/mono/mono/pull/14880/commits/7f9909b95d24e6e2b9421c65ed074af478d7c35a can fix it, I see a route for a quick workaround for this release

**Comment by alexanderkyte** [comment]
We can disable inlining on this release while keeping direct calls, and then enable inlining conditionally (disable if more than N number of local variables in callee) to avoid stressing the register allocator. I think if we do that, we'll still want to let people enable the lengthy compile in "release mode" or something.

**Comment by alexanderkyte** [comment]
@akoeplinger I think we can close this
