### ISSUE TITLE
[netcore]Make System.Collections.Tests.*.ICollection_NonGeneric_CopyTo_ArrayOfEnumType Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14857]
This is a common error to a whole bunch of tests, so ideally one fix should fix them all. 

Here is the output of one failure:

```
System.Collections.Tests.ArrayListReadOnlyTests.ICollection_NonGeneric_CopyTo_ArrayOfEnumType(count: 1) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.InvalidCastException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.Collections.Tests.ICollection_NonGeneric_Tests.ICollection_NonGeneric_CopyTo_ArrayOfEnumType(Int32 count)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

According to @filipnavara , the reason for the failures is:

_**Mono currently supports Array.Copy from object[] array containing boxed ints to float[] array with primitive widening**_

Determine if these tests are passable and pass them.

**Comment by EgorBo** [comment]
It's @filipnavara's comment :)

**Comment by steveisok** [comment]
HA!  Sorry @filipnavara, I will change :-)
