### ISSUE TITLE
[corlib] Mark `PropertyInfo` `[Serializable]`

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#14864]
In the [.NET Framework documentation](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.propertyinfo?view=netframework-4.8) it's `[Serializable]`,
but in [our fork of CoreFX](https://github.com/mono/corefx/blob/master/src/Common/src/CoreLib/System/Reflection/PropertyInfo.cs) it isn't.

Also it's not `partial` so we can't just stick it in a separate `mcs/class/corlib/corefx/PropertyInfo.cs`.  Have to modify the submodule.

**Comment by marek-safar** [comment]
I am wondering if it matters for abstract type

**Comment by lambdageek** [comment]
@marek-safar I think yes... I'm pretty sure I've seen errors when a subclass needs to serialize and its base class is not Serializable.
