### ISSUE TITLE
Could not load file or assembly 'netstandard, Version=2.0.0.0...

### ISSUE THREAD

**Issue by Josvds** [mono/mono#14902]
## Steps to Reproduce

1. Create a dotnet standard project
2. Attach this project to a .NET Framework 4.8 project
3. Build the application on Windows
4. Use mono to run this application on a Raspberry Pi 2 with Mono 5.4

### Current Behavior

I get the following error:
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### Expected Behavior

I expected the application to run

## On which platforms did you notice this

[ ] macOS
[X ] Linux (Raspberry)
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:28:30 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

## Stacktrace
See current behavior

**Comment by marek-safar** [comment]
could you please include the produced folder with binaries or another way to reproduce this?

**Comment by Josvds** [comment]
Sorry, I did figure out installing "mono-complete" solved my issue. I don't know which package I need to install a side to the runtime/develop version. But this works for me.

**Comment by OmidID** [comment]
> 
> 
> Sorry, I did figure out installing "mono-complete" solved my issue. I don't know which package I need to install a side to the runtime/develop version. But this works for me.

I have the same problem and `mono-complete` is installed.

**Comment by ChrisProlls** [comment]
@OmidID same for me, have you found a solution ?
