### ISSUE TITLE
[netcore] Make System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToUIntTest Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14931]
The test currently fails with:

```
System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToUIntTest(useInterpreter: True) [FAIL]
      Assert.Equal() Failure
      Expected: 2147483648
      Actual:   0
      Stack Trace:
           at System.Linq.Expressions.Tests.ConvertTests.VerifyFloatToUInt(Single value, Boolean useInterpreter)
           at System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToUIntTest(Boolean useInterpreter)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by EgorBo** [comment]
C# spec: If the value of the operand is NaN or infinite, the result of the conversion is an unspecified value of the destination type.

```
float value = float.NaN;
return (uint) value;
```

CoreCLR: 0
Mono: 2147483648

**Comment by filipnavara** [comment]
@EgorBo I can reproduce your finding. I don't understand it though. It seems that Mono and CoreCLR have essentially the [same code gen here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunHjykDAK4BLAHYYGAWQAUASg5ceygCYQhwADYwGAN2yahOgLwM1G7QDoActmsBuGgEgnxAOwMZoiQv2GYjtTKAL5K3GFMpKSKQco8/ACcMrJycoEhNMFAA). The `vcvttsd2si` instruction and `cvttsd2si` instructions in Mono [should behave the same](https://www.felixcloutier.com/x86/cvttsd2si).

In both cases they are documented with the following note:
> If a converted result exceeds the range limits of signed doubleword integer (in non-64-bit modes or 64-bit mode with REX.W/VEX.W/EVEX.W=0), the floating-point invalid exception is raised, and if this exception is masked, the indefinite integer value (80000000H) is returned.

That matches the Mono behaviour but not the CoreCLR one.

**Comment by EgorBo** [comment]
@filipnavara btw, mono in LLVM mode behaves like CoreCLR and prints 0.
```csharp
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static uint M(float v) {
        return (uint) v;
    }
    
    public static void Main() {
        Console.WriteLine(M(float.NaN));
    }
```
```
Mono-LLVM:
```asm
_C_M_single:
	vcvttss2si	%xmm0, %rax
	retq
	nopw	%cs:(%rax,%rax)
```
Mono (non-LLVM AOT):
```asm
C_M_single:
	subq	$8, %rsp
	movss	%xmm0, (%rsp)
	movss	(%rsp), %xmm0
	cvttss2si	%xmm0, %eax
	addq	$8, %rsp
	retq
	nopw	(%rax,%rax)
```

**Comment by filipnavara** [comment]
Now I see what I missed. All the other versions of the code use 64-bit register and hence get 0x8000_0000_0000_0000 from the conversion.

**Comment by filipnavara** [comment]
Changing 

https://github.com/mono/mono/blob/3e432663cde4283fc7fa7f81b20bc3d0a9333b38/mono/mini/mini-amd64.c#L3494

to `if (size == 8 || !is_signed)` aligns the behavior to return 0.

**Comment by filipnavara** [comment]
My favourite part:
```
csharp> float value = float.NaN;
csharp> (uint)value 
2147483648
csharp> unchecked((uint)float.NaN)                                                                                                                                                                                                            0                                                                                                                                                                                                                                             
```

Apparently Mono is not even consistent with itself which is why the tests fail.
