### ISSUE TITLE
[2019-06][iOS][tests] All SSL related test cases block on iOS

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#14938]
While working on https://github.com/xamarin/xamarin-macios/pull/6196 the following BCL tests failed on iOS simulator and device:

* All tests in class System.Net.Security.Tests.SslStreamSniTest
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Tls)
* System.Net.Security.Tests.ClientDefaultEncryptionTest.ClientDefaultEncryption_ServerRequireEncryption_ConnectWithEncryption
* System.Net.Security.Tests.ClientDefaultEncryptionTest.ClientDefaultEncryption_ServerAllowNoEncryption_ConnectWithEncryption
* System.Net.Security.Tests.ServerRequireEncryptionTest.ServerRequireEncryption_ClientRequireEncryption_ConnectWithEncryption
* System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientAllowNoEncryption_ConnectWithEncryption
* System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok
* System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientRequireEncryption_ConnectWithEncryption
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Default)
* System.Net.Security.Tests.ServerRequireEncryptionTest.ServerRequireEncryption_ClientAllowNoEncryption_ConnectWithEncryption
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Ssl3)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls12, clientProtocol: Tls, expectedException: typeof(System.Security.Authentication.AuthenticationException))
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls11, clientProtocol: Tls12, expectedException: typeof(System.IO.IOException))
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerAllClient_Success
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls12, expectedException: typeof(System.IO.IOException))
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Tls11)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls11, clientProtocol: Tls, expectedException: typeof(System.Security.Authentication.AuthenticationException))
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Tls)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Tls12)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_ServerRequireEncryption_ConnectWithEncryption
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success(clientProtocol: Tls)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success(clientProtocol: Ssl3)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success(clientProtocol: Default)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls12, clientProtocol: Tls11, expectedException: typeof(System.Security.Authentication.AuthenticationException))
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol: Tls, clientProtocol: Tls11, expectedException: typeof(System.IO.IOException))
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Ssl3)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Tls12)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Tls11)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Default)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success(clientProtocol: Tls12)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success(clientProtocol: Tls11)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success(clientProtocol: Tls11)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_AllServerVsIndividualClientSupportedProtocols_Success(clientProtocol: Tls11)
* System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_SslStreamClientServerNone_UseStrongCryptoSet

During the execution of the tests, the following [crash](https://gist.github.com/mandel-macaque/129bcdac41e4b1df54c54352b1e416c5) was shown in the logs (which looks to be related to the network stack code).

Tests have been ignored in the xamarin-macios 2019-06 branch, but should be re-enabled.

**Comment by baulig** [comment]
I spent some time investigating this and they're all failing in the static constructor of the internal `Configuration.Certificates` class here: https://github.com/mono/mono/blob/f87af4bfefb6a9c13f20920ac6cc80009aedfa53/mcs/class/test-helpers/Configuration.Certificates.cs#L34.

**Comment by baulig** [comment]
Something very weird is going on here ...

Using this test local work branch: https://github.com/baulig/mono/tree/martin-2019-06 and https://github.com/baulig/xamarin-macios/tree/martin-2019-06.

**Comment by baulig** [comment]
First, create a test project in `xamarin-macios` such as for instance https://github.com/baulig/xamarin-macios/tree/martin-2019-06/tests/martin-test/BCL%20tests%20group%204, remove everything except for `monotouch_System_xunit-test.dll` - but switch that to your Mono build.

Edit `mcs/class/System/System_xtest.dll.sources` to remove everything, but add `MartinTest.cs` like this:

```
../test-helpers/Configuration.Http.cs
../test-helpers/Configuration.Certificates.cs
../test-helpers/TestConfiguration.cs
../test-helpers/MartinTest.cs

../../../external/corefx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs

../../../external/corefx/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs
../../../external/corefx/src/Common/tests/System/Collections/ICollection.NonGeneric.Tests.cs
../../../external/corefx/src/Common/tests/System/Collections/IEnumerable.NonGeneric.Tests.cs
../../../external/corefx/src/Common/tests/System/Collections/IList.NonGeneric.Tests.cs
../../../external/corefx/src/Common/tests/System/Collections/TestBase.NonGeneric.cs
../../../external/corefx/src/Common/tests/System/IO/DelegateStream.cs
../../../external/corefx/src/Common/tests/System/Net/Capability.Security.cs
../../../external/corefx/src/Common/tests/System/Net/Configuration.cs
../../../external/corefx/src/Common/tests/System/Net/Configuration.Security.cs
../../../external/corefx/src/Common/tests/System/Net/HttpsTestClient.cs
../../../external/corefx/src/Common/tests/System/Net/HttpsTestServer.cs
../../../external/corefx/src/Common/tests/System/Net/SslStreamCertificatePolicy.cs
../../../external/corefx/src/Common/tests/System/Net/VirtualNetwork/*.cs
../../../external/corefx/src/Common/tests/System/Net/WebSockets/WebSocketCreateTest.cs
../../../external/corefx/src/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs
../../../external/corefx/src/Common/tests/System/Net/Http/LoopbackServer.cs
../../../external/corefx/src/Common/tests/System/Net/Configuration.cs
../../../external/corefx/src/Common/tests/System/Net/Configuration.Http.cs
../../../external/corefx/src/Common/tests/System/Net/Configuration.WebSockets.cs
../../../external/corefx/src/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs
../../../external/corefx/src/Common/src/System/Net/Logging/NetEventSource.Common.cs
../../../external/corefx/src/Common/tests/System/Net/Capability.Sockets.cs
../../../external/corefx/src/Common/tests/System/Net/EventSourceTestLogging.cs
../../../external/corefx/src/Common/tests/System/Net/TestLogging.cs
../../../external/corefx/src/Common/tests/System/Net/VerboseTestLogging.cs
../../../external/corefx/src/Common/src/System/Threading/Tasks/TaskToApm.cs
../../../external/corefx/src/Common/tests/System/ShouldNotBeInvokedException.cs
../../../external/corefx/src/Common/tests/System/Net/Configuration.cs
../../../external/corefx/src/Common/tests/System/Net/Configuration.Sockets.cs
../../../external/corefx/src/Common/tests/System/Net/Sockets/Fletcher32.cs
../../../external/corefx/src/Common/tests/System/Net/Sockets/SocketImplementationType.cs
../../../external/corefx/src/Common/tests/System/Net/Sockets/SocketTestExtensions.cs
../../../external/corefx/src/Common/tests/System/Net/Sockets/SocketTestServer.cs
../../../external/corefx/src/Common/tests/System/Net/Sockets/SocketTestServerAPM.cs
../../../external/corefx/src/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs
../../../external/corefx/src/Common/tests/System/Net/Sockets/TestSettings.cs
../../../external/corefx/src/Common/src/System/Net/Logging/NetEventSource.Common.cs
../../../external/corefx/src/Common/src/System/Net/InternalException.cs
../../../external/corefx/src/Common/tests/System/Net/SslProtocolSupport.cs
```

Add `../test-helpers/MartinTest.cs` like this:

```
using System.Threading.Tasks;
using Xunit;

namespace System.Net.Security.Tests
{
	public class MartinTest
	{
		[Theory]
		[InlineData(false)]
		[InlineData(true)]
		public async Task Run(bool dummy)
		{
			// var a = Task.Delay(TimeSpan.FromSeconds(5));
			// var b = Task.Delay(TimeSpan.FromSeconds(8));
			// await MartinTaskTest(a, b);

			throw new InvalidTimeZoneException("I LIVE ON THE MOON!");
		}

		public static async Task MartinTaskTest(Task a, Task b)
		{
			Console.Error.WriteLine($"MARTIN TASK TEST!");
			try
			{
				var ac = a.ContinueWith(ar =>
				{
					Console.Error.WriteLine($"MARTIN TASK TEST #1: {ar.Status} - {a} {ar}");
				});

				var bc = b.ContinueWith(br =>
				{
					Console.Error.WriteLine($"MARTIN TASK TEST #2: {br.Status} - {b} {br}");
				});

				await TestConfiguration.WhenAllOrAnyFailedWithTimeout(ac, bc).ConfigureAwait(false);
			}
			catch (Exception ex)
			{
				Console.Error.WriteLine($"MARTIN TASK TEST ERROR: {ex}");
				throw;
			}
			finally
			{
				Console.Error.WriteLine($"MARTIN TASK TEST DONE");
			}
		}
	}
}
```

**Comment by baulig** [comment]
Now run that and it will finish with

```
2019-06-13 15:16:55.012917-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] Failed tests:
2019-06-13 15:16:55.013004-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 
2019-06-13 15:16:55.013285-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 1) 	[FAIL] System.Net.Security.Tests.MartinTest.Run(dummy: False)   Test name: System.Net.Security.Tests.MartinTest.Run(dummy: False)
   Assembly:  [monotouch_System_xunit-test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]
   Exception messages: System.InvalidTimeZoneException : I LIVE ON THE MOON!   Exception stack traces:   at System.Net.Security.Tests.MartinTest.Run (System.Boolean dummy) [0x00000] in /Workspace/mono-playground/mcs/class/test-helpers/MartinTest.cs:17 
   Execution time: 0.0046617
2019-06-13 15:16:55.013378-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 
2019-06-13 15:16:55.013439-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 
2019-06-13 15:16:55.013516-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 2) 	[FAIL] System.Net.Security.Tests.MartinTest.Run(dummy: True)   Test name: System.Net.Security.Tests.MartinTest.Run(dummy: True)
   Assembly:  [monotouch_System_xunit-test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]
   Exception messages: System.InvalidTimeZoneException : I LIVE ON THE MOON!   Exception stack traces:   at System.Net.Security.Tests.MartinTest.Run (System.Boolean dummy) [0x00000] in /Workspace/mono-playground/mcs/class/test-helpers/MartinTest.cs:17 
   Execution time: 0.0000915
2019-06-13 15:16:55.013592-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 
2019-06-13 15:16:55.013652-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 
2019-06-13 15:16:55.113276-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] Xml result can be found /Users/mabaul/Library/Developer/CoreSimulator/Devices/777E5833-B2E0-4FD5-A321-26627A0873B0/data/Containers/Data/Application/2C413AB9-DC1D-4EF0-A10F-8CB3407AC0DB/Documents/.config/TestResults.xUnit.xml
2019-06-13 15:16:55.113387-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 
2019-06-13 15:16:55.114087-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] Tests run: 2 Passed: 0 Inconclusive: 0 Failed: 2 Ignored: 0
2019-06-13 15:16:55.114151-0400 com.xamarin.bcltests.BCL tests group 4[37735:1848362] 
```

**Comment by baulig** [comment]
Now edit the `MartinTest.cs` and uncomment

```
			var a = Task.Delay(TimeSpan.FromSeconds(5));
			var b = Task.Delay(TimeSpan.FromSeconds(8));
			await MartinTaskTest(a, b);
```

then run again

```
2019-06-13 15:19:04.631050-0400 com.xamarin.bcltests.BCL tests group 4[37820:1852295] 
Test collection for System.Net.Security.Tests.MartinTest
2019-06-13 15:19:04.631191-0400 com.xamarin.bcltests.BCL tests group 4[37820:1852295] 
Thread started:  #10
2019-06-13 15:19:04.673643-0400 com.xamarin.bcltests.BCL tests group 4[37820:1852295] MARTIN TASK TEST!
2019-06-13 15:19:09.673596-0400 com.xamarin.bcltests.BCL tests group 4[37820:1852500] MARTIN TASK TEST #1: RanToCompletion - System.Threading.Tasks.Task+DelayPromise System.Threading.Tasks.Task+DelayPromise
2019-06-13 15:19:12.673988-0400 com.xamarin.bcltests.BCL tests group 4[37820:1852489] MARTIN TASK TEST #2: RanToCompletion - System.Threading.Tasks.Task+DelayPromise System.Threading.Tasks.Task+DelayPromise
2019-06-13 15:19:12.675911-0400 com.xamarin.bcltests.BCL tests group 4[37820:1852489] MARTIN TASK TEST DONE
```

and there it hangs ...

**Comment by baulig** [comment]
So something must be wrong with that `TestConfiguration.WhenAllOrAnyFailedWithTimeout()` it seems ...

Now edit it into

```
		[Theory]
		[InlineData(false)]
		[InlineData(true)]
		public async Task Run(bool dummy)
		{
			var a = Task.Delay(TimeSpan.FromSeconds(5));
			var b = Task.Delay(TimeSpan.FromSeconds(8));
			await Task.WhenAll(a, b);

			// throw new InvalidTimeZoneException("I LIVE ON THE MOON!");
		}
```

That should finish in a bit over 8 seconds - and since it's running twice, give it even a full minute.  But it's hanging:

```
2019-06-13 15:21:04.385411-0400 com.xamarin.bcltests.BCL tests group 4[37906:1855771] 
Test collection for System.Net.Security.Tests.MartinTest
2019-06-13 15:21:04.385532-0400 com.xamarin.bcltests.BCL tests group 4[37906:1855771] 
```

it is now

```
Thu Jun 13 15:22:13 EDT 2019
```

**Comment by baulig** [comment]
Next experiment: add `.ConfigureAwait(false)` to it:

```
		[Theory]
		[InlineData(false)]
		[InlineData(true)]
		public async Task Run(bool dummy)
		{
			var a = Task.Delay(TimeSpan.FromSeconds(5));
			var b = Task.Delay(TimeSpan.FromSeconds(8));
			await Task.WhenAll(a, b).ConfigureAwait (false);

			// throw new InvalidTimeZoneException("I LIVE ON THE MOON!");
		}
```

Same thing, it's hanging.

**Comment by baulig** [comment]
Next experiment: put back the exception.

```
		[Theory]
		[InlineData(false)]
		[InlineData(true)]
		public async Task Run(bool dummy)
		{
			var a = Task.Delay(TimeSpan.FromSeconds(5));
			var b = Task.Delay(TimeSpan.FromSeconds(8));
			await Task.WhenAll(a, b);

			throw new InvalidTimeZoneException("I LIVE ON THE MOON!");
		}
```

and it hangs again.

**Comment by baulig** [comment]
Now trying

```
		[Theory]
		[InlineData(false)]
		[InlineData(true)]
		public async Task Run(bool dummy)
		{
			Console.Error.WriteLine($"MARTIN TEST");
			var a = Task.Delay(TimeSpan.FromSeconds(5));
			var b = Task.Delay(TimeSpan.FromSeconds(8));
			await Task.WhenAll(a, b);

			Console.Error.WriteLine($"MARTIN TEST #1");
			throw new InvalidTimeZoneException("I LIVE ON THE MOON!");
		}
```

and it's hanging again!

```
2019-06-13 15:33:40.666892-0400 com.xamarin.bcltests.BCL tests group 4[38328:1877597] 
Test collection for System.Net.Security.Tests.MartinTest
2019-06-13 15:33:40.667095-0400 com.xamarin.bcltests.BCL tests group 4[38328:1877597] 
2019-06-13 15:33:40.730968-0400 com.xamarin.bcltests.BCL tests group 4[38328:1877597] MARTIN TEST
Thread started:  #10
Thread finished: <Thread Pool> #8
Thread finished: <Thread Pool> #5
Thread finished: <Thread Pool> #7
Thread finished: <Thread Pool> #4
Thread finished: <Thread Pool> #3
Thread started: <Thread Pool> #11
```

it is now

```
Thu Jun 13 15:35:34 EDT 2019
```

**Comment by baulig** [comment]
Okay, let's add `.ConfigureAwait(false)`.

```
		[Theory]
		[InlineData(false)]
		[InlineData(true)]
		public async Task Run(bool dummy)
		{
			Console.Error.WriteLine($"MARTIN TEST");
			var a = Task.Delay(TimeSpan.FromSeconds(5));
			var b = Task.Delay(TimeSpan.FromSeconds(8));
			await Task.WhenAll(a, b).ConfigureAwait(false);

			Console.Error.WriteLine($"MARTIN TEST #1");
			throw new InvalidTimeZoneException("I LIVE ON THE MOON!");
		}
```

Now it's actually printing the "MARTIN TEST #1" - and then it's hanging:

```
2019-06-13 15:36:26.092688-0400 com.xamarin.bcltests.BCL tests group 4[38428:1884397] 
Test collection for System.Net.Security.Tests.MartinTest
2019-06-13 15:36:26.092808-0400 com.xamarin.bcltests.BCL tests group 4[38428:1884397] 
2019-06-13 15:36:26.137114-0400 com.xamarin.bcltests.BCL tests group 4[38428:1884397] MARTIN TEST
Thread started:  #12
2019-06-13 15:36:34.140571-0400 com.xamarin.bcltests.BCL tests group 4[38428:1884598] MARTIN TEST #1
Thread finished: <Thread Pool> #4
Thread finished: <Thread Pool> #7
Thread finished: <Thread Pool> #5
Thread finished: <Thread Pool> #9
Thread finished: <Thread Pool> #6
Thread finished: <Thread Pool> #10
Thread finished: <Thread Pool> #3
Thread started: <Thread Pool> #13
Thread finished: <Thread Pool> #8
Thread started: <Thread Pool> #14
Thread started: <Thread Pool> #15
Thread finished: <Thread Pool> #15
Thread finished: <Thread Pool> #14
Thread started: <Thread Pool> #16
```

**Comment by mandel-macaque** [comment]
AMAZING work, I'll look at what is going on in the runner, I might be able to find a fix there.

**Comment by akoeplinger** [comment]
Fixed by https://github.com/xamarin/xamarin-macios/pull/6291.
