### ISSUE TITLE
Non-web exception. Exception origin (name of application or object): mscorlib. - MAC

### ISSUE THREAD

**Issue by Sturtuk** [mono/mono#14941]
###System.NotImplementedException

##The method or operation is not implemented.
##Description: HTTP 500.Error processing request.

Details: Non-web exception. Exception origin (name of application or object): mscorlib.

![Screenshot 2019-06-10 at 9 26 09 PM](https://user-images.githubusercontent.com/5758731/59208458-c2d47600-8bc6-11e9-934f-739fb7ec60ac.png)

**Comment by marek-safar** [comment]
System.Transaction is quite windows specific assembly and we don't have full cross-platform implementation
