### ISSUE TITLE
[bockbuild] Non-git sources (like Nuget) don't have their cache invalidated properly

### ISSUE THREAD

**Issue by alexischr** [mono/mono#14957]
(Opening issue here as we disabled issues from https://github.com/mono/bockbuild)

This issue mostly shows up at https://github.com/mono/mono/blob/master/packaging/MacSDK/nuget.py#L7 , where changing the URL does not trigger a re-processing of the package as expected.

Bockbuild uses a "buildstring" (saved as `artifacts/packagename.buildstring`) to decide if it will re-build a package or not. The nuget.py URL update does indeed trigger "needing rebuilding" by comparing the current buildstring with the one saved on the file by the previous build. (Buildstring example: my `artifacts/NuGet-darwin-universal.buildstring` has a single line: `NuGet 5.0.2 <https://dist.nuget.org/win-x86-commandline/v5.0.2/nuget.exe> md5: c8461c00db2b16f5ce4671423768bf24`)

However by that time, the fetch code that downloads the sources has already ran, and having found a file with the same name under `cache/nuget.exe`, gives up on re-downloading it.

https://github.com/mono/bockbuild/blob/master/bockbuild/package.py#L134 is where fetching (processing of `sources`) happens, and https://github.com/mono/bockbuild/blob/master/bockbuild/package.py#L304 is the code path that `nuget.py` follows.

Note that we should not just delete everything in `cache` if the source needs rebuilding; caching in bockbuild also includes git repositories often just need to just do a fetch and a checkout.

**Comment by lewing** [comment]
ono JIT compiler version 6.0.0.283 (2019-02/240aa5b900f Wed Jun  5 17:25:57 EDT 2019) shipped with the wrong version of nuget.exe because of this bug

**Comment by lewing** [comment]
see https://github.com/mono/mono/pull/15121
