### ISSUE TITLE
[netcore] Make System.Net.Sockets.Tests.UdpClientTest.Finalize_NoExceptionsThrown Run & Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15009]
The test is not run due Mono not supporting a precise GC.  

Here's what is returned:

```
System.Net.Sockets.Tests.UdpClientTest.Finalize_NoExceptionsThrown [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
```

Once (or if) the precise GC is supported, rerun the test and make it pass.

**Comment by marek-safar** [comment]
This is normal exclusion condition (we have several of them), we won't have IsPreciseGcSupported anytime soon.
