### ISSUE TITLE
How can I re-inject a new version of a DLL with mono?

### ISSUE THREAD

**Issue by hongde88** [mono/mono#15011]
Hi everyone, I run into some issue when trying to re-inject a new version of a DLL into a target process. Basically, I injected a DLL into a target process with embedding mono APIs. I then modified my DLL and wanted to re-inject into the same process. However, it seems like the target process won't be able to pick up my new DLL until I restart it. So I'm wondering if there's a way to re-inject different versions of a DLL to a target process with mono and the target should be able to pick up the latest version. Thank you!

## Steps to Reproduce

1. Inject a DLL with embedding mono APIs into a target process and then eject it.
2. Modify the DLL and re-inject it.

### Current Behavior

The target process only picks up the old DLL even though a modified version of the DLL is re-injected.

### Expected Behavior

The target process should pick up the modified DLL.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x ] Windows

**Comment by jaykrell** [comment]
What do you mean by "inject"?

And to the wider mono audience, independent of this "injection" thingy, does mono cleanup enough after itself and its embedded user, in order to support an orderly unloading and loading a new one? It is both normal expected behavior (dlclose/FreeLibrary), and rarely implemented/used behavior, of code in general. I don't think desktop CLR supports it for example.

A lot of code is prepared to be loaded "later" with dlopen/LoadLibrary, but dlclose/FreeLibrary are relatively rare.

**Comment by hongde88** [comment]
Hi Jay, I know this use case rarely happens. However, I just wanted to be able to test my DLL without having to restart the process each time I modify my DLL :(

**Comment by lambdageek** [comment]
@hongde88 The short answer is that this is currently not supported by Mono.

The longer answer is: if you're willing to do something relatively awkward, you can probably make it work.  If you are loading the DLL into a new appdomain, then you can unload that appdomain and create a new one and it should pick up the new version of the DLL.  To be sure that the new version is loaded, you would need to make sure the DLL is only loaded in a single appdomain at a time.

**Comment by hongde88** [comment]
@lambdageek I tried to load my DLL into another domain and it crashed the app because my DLL is dependant on some of the assemblies loaded in the root domain. Do you know how to resolve this problem by any chance? Thank you in advance!

**Comment by jaykrell** [comment]
Only load in non-root domain.
Unload the domain.
Update the .dll.
Create a new domain.
Load .dll.
