### ISSUE TITLE
[netcore] Make System.Reflection.Tests.TypeInfoTests.FindMembers Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15029]
The test currently fails with:

```
System.Reflection.Tests.TypeInfoTests.FindMembers [FAIL]
      Assert.Equal() Failure
      Expected: 28
      Actual:   30
      Stack Trace:
           at System.Reflection.Tests.TypeInfoTests.FindMembers()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

It appears we have two extra instance methods on Object, which makes this test fail.  If that can't change, we may want to modify the tests to detect which VM is running and act accordingly.

**Comment by CoffeeFlux** [comment]
The extra methods:
```
Byte& GetRawData()
System.Object CloneInternal()
```

**Comment by marek-safar** [comment]
We move them out of object type. CloneInternal is used only once and it's trivial to implement in MarshalAsAttribute. GetRawData should probably live in RuntimeHelpers
