### ISSUE TITLE
[MacOS][2019-06] System.Runtime.CompilerServices.UnsafeTests.ReadWriteDoublePointe Fails on Mac

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#15040]
On Mac OS X Full the System.Runtime.CompilerServices.UnsafeTests.ReadWriteDoublePointe fails with the following assertion:

> Exception messages: Assert.Equal() Failure
> Expected: 20
> Actual:   10   Exception stack traces:   at System.Runtime.CompilerServices.UnsafeTests.ReadWriteDoublePointer () [0x00020] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:96 
> at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
> at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 

This test does not fail on master, but it might be a new test.

The tests was ignored in PR https://github.com/xamarin/xamarin-macios/pull/6196

**Comment by marek-safar** [comment]
@mandel-macaque is it same as #14872 ?

**Comment by mandel-macaque** [comment]
@marek-safar ha, I missed it, let's mark it as a duplicate.
