### ISSUE TITLE
[aot] Duplicate .fnstart Directive Compiler Error

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15048]
When building https://github.com/xamarin/xamarin-android/pull/3155, we're noticing AOT compilation failures on Windows & Mac (both Release & Debug builds).  Specifically for mac:

```
[AOT] MONO_PATH="/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/android/assets/shrunk" MONO_ENV_OPTIONS="" /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/cross-arm --llvm --aot=outfile=/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/libaot-System.dll.so,asmwriter,mtriple=armv7-linux-gnueabi,tool-prefix=/Users/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-,ld-flags=/Users/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a;/Users/builder/android-toolchain/ndk/platforms/android-16/arch-arm/usr/lib/libc.so;/Users/builder/android-toolchain/ndk/platforms/android-16/arch-arm/usr/lib/libm.so,llvm-path=/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Darwin,temp-path=/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/android/assets/shrunk/System.dll (TaskId:212)
  [aot-compiler stdout] Mono Ahead of Time compiler - compiling assembly /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/android/assets/shrunk/System.dll (TaskId:212)
  [aot-compiler stdout] AOTID 2747FE38-E4BB-00A3-B590-5A06611A18D7 (TaskId:212)
  [aot-compiler stdout] Executing opt: "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/opt" -f -O2 -disable-tail-calls -place-safepoints -spp-all-backedges -o "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp.opt.bc" "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp.bc" (TaskId:212)
  [aot-compiler stdout] Executing llc: "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/llc"  -march=arm -mattr=+vfp2,-neon,+d16 -asm-verbose=false -mtriple=armv7-linux-gnueabi -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=mono_aot_System_eh_frame -disable-tail-calls -relocation-model=pic -o "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s" "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp.opt.bc" (TaskId:212)
  [aot-compiler stdout] Compiled: 114/114 (TaskId:212)
  [aot-compiler stdout] Executing the native assembler: "/Users/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-as"   -mfpu=vfp3 -o /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp.s.o /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp.s (TaskId:212)
  [aot-compiler stdout] Executing the native assembler: "/Users/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-as"   -mfpu=vfp3 -o /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.o /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s (TaskId:212)
  [aot-compiler stderr] /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s: Assembler messages: (TaskId:212)
  [aot-compiler stderr] /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s:54: Error: duplicate .fnstart directive (TaskId:212)
  [aot-compiler stderr] /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s:66: Error: duplicate .fnstart directive (TaskId:212)
  [aot-compiler stderr] /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s:5989: Error: duplicate .fnstart directive (TaskId:212)
  [aot-compiler stderr] AOT of image /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/android/assets/shrunk/System.dll failed. (TaskId:212)
```

The workspace that contain the .s files and other artifacts is forthcoming once I know the best way to provide them.

**Comment by lambdageek** [comment]
The three functions that have a `.fnstart` but not an `.fnend` are `gc.safepoint_poll`, `llvm_code_start` and `llvm_code_end`.


excerpt from `temp-llvm.s`
<details>
<pre>
	.file	"aot"
	.weak	gc.safepoint_poll
	.p2align	2
	.type	gc.safepoint_poll,%function
	.code	32
gc.safepoint_poll:
.Lfunc_begin0:
	.fnstart
	ldr	r0, .LCPI0_0
.LPC0_0:
	add	r0, pc, r0
	ldr	r1, [r0, #28]
	ldr	r1, [r1]
	cmp	r1, #0
	moveq	pc, lr
	.save	{r11, lr}
	push	{r11, lr}
.Ltmp0:
.Ltmp1:
.Ltmp2:
	ldr	r0, [r0, #100]
	mov	lr, pc
	mov	pc, r0
	pop	{r11, lr}
	mov	pc, lr
	.p2align	2
.LCPI0_0:
	.long	mono_aot_System_llvm_got-(.LPC0_0+8)
.Lfunc_end0:
	.size	gc.safepoint_poll, .Lfunc_end0-gc.safepoint_poll

	.p2align	2
	.type	llvm_code_start,%function
	.code	32
llvm_code_start:
.Lfunc_begin1:
	.fnstart
	mov	pc, lr
.Lfunc_end1:
	.size	llvm_code_start, .Lfunc_end1-llvm_code_start

	.hidden	mono_aot_Systeminit_method
	.globl	mono_aot_Systeminit_method
	.p2align	2
	.type	mono_aot_Systeminit_method,%function
	.code	32
mono_aot_Systeminit_method:
.Lfunc_begin2:
	.fnstart
	.save	{r4, lr}
	push	{r4, lr}
.Ltmp3:
.Ltmp4:
.Ltmp5:
	ldr	r1, .LCPI2_0
	mov	r4, r0
.LPC2_0:
	add	r1, pc, r1
	ldr	r0, [r1, #16]
	ldr	r2, [r1, #76]
	mov	r1, r4
	mov	lr, pc
	mov	pc, r2
	ldr	r0, .LCPI2_1
	mov	r1, #1
.LPC2_1:
	add	r0, pc, r0
	strb	r1, [r0, r4]
	pop	{r4, lr}
	mov	pc, lr
	.p2align	2
.LCPI2_0:
	.long	mono_aot_System_llvm_got-(.LPC2_0+8)
.LCPI2_1:
	.long	mono_inited-(.LPC2_1+8)
.Lfunc_end2:
	.size	mono_aot_Systeminit_method, .Lfunc_end2-mono_aot_Systeminit_method
.Lexception0:
	.fnend
</pre>
</details>

The corresponding piece of `temp.opt.ll` is:
<details>
<pre>
declare void @mono_personality() #0

; Function Attrs: nounwind
define weak_odr void @gc.safepoint_poll() local_unnamed_addr #1 {
gc.safepoint_poll.entry:
  %0 = load i32*, i32** getelementptr inbounds (%MONO_GOT_System.dll, %MONO_GOT_System.dll* @mono_aot_System_llvm_got, i32 0, i32 7), align 4
  %1 = load i32, i32* %0, align 4
  %2 = icmp eq i32 %1, 0
  br i1 %2, label %gc.safepoint_poll.exit, label %gc.safepoint_poll.poll

gc.safepoint_poll.poll:                           ; preds = %gc.safepoint_poll.entry
  %3 = load void ()*, void ()** getelementptr inbounds (%MONO_GOT_System.dll, %MONO_GOT_System.dll* @mono_aot_System_llvm_got, i32 0, i32 25), align 4
  call void %3() #8
  br label %gc.safepoint_poll.exit

gc.safepoint_poll.exit:                           ; preds = %gc.safepoint_poll.poll, %gc.safepoint_poll.entry
  ret void
}

; Function Attrs: norecurse nounwind readnone
define internal void @llvm_code_start() #2 {
ENTRY:
  ret void
}

; Function Attrs: noinline
define hidden cc18 void @mono_aot_Systeminit_method(i32) #3 {
ENTRY:
  %1 = load i32, i32* bitcast (i32** getelementptr inbounds (%MONO_GOT_System.dll, %MONO_GOT_System.dll* @mono_aot_System_llvm_got, i32 0, i32 4) to i32*), align 16
  %2 = load void (i32, i32)*, void (i32, i32)** getelementptr inbounds (%MONO_GOT_System.dll, %MONO_GOT_System.dll* @mono_aot_System_llvm_got, i32 0, i32 19), align 4
  call void %2(i32 %1, i32 %0)
  %3 = getelementptr [113 x i8], [113 x i8]* @mono_inited, i32 0, i32 %0
  store i8 1, i8* %3, align 1
  ret void
}
</pre>
</details>

Some observations / wild guesses:
1. Note that both `gc.safepoint_poll` and `llvm_code_start` have the `nounwind` property.  I would expect that there wouldn't be an `.fnstart` at all in that case.
2.  They also don't have the Mono calling convention set.

**Comment by vargaz** [comment]
Need to bump llvm to the above version for the fix.
