### ISSUE TITLE
[2019-06][iOS] Several tests on iOS fail on a 32b device

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#15058]
After upgrading to mono 2019-06 the following tests fail on a 32b iOS device in the following configurations:

* AssemblyBuildTarget: SDK framework (release) (Sample [run log](https://gist.github.com/mandel-macaque/b57168cef60004b2477d4f3744cb6fe6))(Sample [build log](https://gist.github.com/mandel-macaque/af234a06d95d554aa1cd028e08039980)) (Sample [crash report](https://gist.github.com/mandel-macaque/07c0a376e5485344c1a89010d0591784)).
* Release (Sample [run log](https://gist.github.com/mandel-macaque/c88a30c4886e19ff654edc2add275eb8))(Sample [build log](https://gist.github.com/mandel-macaque/c3b2079faa769960a657d468e54b928f)) Sample [crash report](https://gist.github.com/mandel-macaque/9be6abee6a70f6340c79c030cc590b65)).

And timeout in the following ones:

* AssemblyBuildTarget: dylib (debug) (Sample [rung log](https://gist.github.com/mandel-macaque/656d12d061d11d17cf1d540dfc84f5ee)) (Sample [build log](https://gist.github.com/mandel-macaque/8dd02eac9b60768a357de1e1f80d4ff4)).
* AssemblyBuildTarget: dylib (debug, profiling) (Sample [run log](https://gist.github.com/mandel-macaque/c2041d0ce1e21224bfb743b7cb9471db)) (Sample [build log](https://gist.github.com/mandel-macaque/112316e3c065010b1eec48595d4756f1)).
* AssemblyBuildTarget: SDK framework (debug) (Sample[ run log](https://gist.github.com/mandel-macaque/bd129f517bdc7aa839e9f03e8fbf8bda)) (Sample [build log](https://gist.github.com/mandel-macaque/89cb4aacc40d5aa6363943059a87445f)).
* AssemblyBuildTarget: SDK framework (debug, profiling) (Sample [run log](https://gist.github.com/mandel-macaque/304e3d8b8e613b9623b81ee5bc962a28)) (Sample [build log](https://gist.github.com/mandel-macaque/714c9d3e2c109f62949f04671295e979)).
* Debug (Sample [run log](https://gist.github.com/mandel-macaque/f823f45422639474df9d8938fe1b3aed)) (Sample [build log](https://gist.github.com/mandel-macaque/16315f4bba0588e462144f3cceb5e914)).

Interestingly, the Release configuration **USING** thumb does work and passed. The build logs contain the exact information for the configurations used.

A good test in the *don't link* or *framework-test* tests since you might get issues on debug for the BCL test apps which are too large to be executed without linking (debug mode)

**Comment by mandel-macaque** [comment]
After bumping mono from b96e5036909b7b410ef85b27868d63eeffb131cf to 46f7a64e382da1eaa4f4478a672b684bfdfda9c7 all the timeout configurations crash.

**Comment by marek-safar** [comment]
@vargaz could you please investigate, this looks like something caused by the recent AOT change

**Comment by lewurm** [comment]
It's due to https://github.com/mono/mono/commit/fed776b88689f1343698805111e6b99f4e0e093d see commit message.

I'll look into it.

**Comment by jaykrell** [comment]
Searching for 'host_mgreg_t'...
```
c:\s\mono2\mono\mini\mini-arm.c(6996):		mono_add_unwind_op_def_cfa_offset (unwind_ops, code, start, 4 * sizeof (host_mgreg_t));
c:\s\mono2\mono\mini\mini-arm.c(6999):		mono_add_unwind_op_def_cfa_offset (unwind_ops, code, start, 2 * sizeof (host_mgreg_t));
c:\s\mono2\mono\mini\mini-arm.c(7077):						mono_add_unwind_op_def_cfa_offset (unwind_ops, code, start, 2 * sizeof (host_mgreg_t));
c:\s\mono2\mono\mini\mini-arm.c(7078):						ARM_ADD_REG_IMM8 (code, ARMREG_SP, ARMREG_SP, 2 * sizeof (host_mgreg_t));
c:\s\mono2\mono\mini\mini-arm.c(7092):				ARM_STR_IMM (code, ARMREG_R1, ARMREG_SP, 3 * sizeof (host_mgreg_t));
c:\s\mono2\mono\mini\mini-arm.c(7162):host_mgreg_t
c:\s\mono2\mono\mini\mini-arm.c(7169):mono_arch_context_set_int_reg (MonoContext *ctx, int reg, host_mgreg_t val)
````
?

**Comment by jaykrell** [comment]
Looks like those are runtime, not compile-time (and I filtered others).
