### ISSUE TITLE
[netcore] Make System.Reflection.Tests.AssemblyTests.LoadFile Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15074]
The test currently fails with:

```
System.Reflection.Tests.AssemblyTests.LoadFile [FAIL]
      Assert.NotEqual() Failure
      Expected: Not System.Reflection.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
      Actual:   System.Reflection.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
      Stack Trace:
           at System.Reflection.Tests.AssemblyTests.LoadFile()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by lambdageek** [comment]
https://github.com/dotnet/corefx/blob/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Reflection/tests/AssemblyTests.cs#L298

On netcore, `S.R.Assembly.LoadFile` is supposed to create a new assembly load context which will then load the assembly, so the newly loaded assembly should be not equal to the currently loaded one (which is in the default ALC).
