### ISSUE TITLE
[netcore] Make System.Reflection.Tests.AssemblyTests.LoadFrom_SameIdentityAsAssemblyWithDifferentPath_ReturnsEqualAssemblies Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15076]
The test appears to return the same string, but still fails:

```
System.Reflection.Tests.AssemblyTests.LoadFrom_SameIdentityAsAssemblyWithDifferentPath_ReturnsEqualAssemblies [FAIL]
      Assert.Equal() Failure
      Expected: System.Reflection.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
      Actual:   System.Reflection.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
      Stack Trace:
           at System.Reflection.Tests.AssemblyTests.LoadFrom_SameIdentityAsAssemblyWithDifferentPath_ReturnsEqualAssemblies()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make it pass.

**Comment by CoffeeFlux** [comment]
"If an assembly with the same identity is already loaded, LoadFrom returns the loaded assembly even if a different path was specified."

We're presumably violating this, and that requirement exists in both Framework and Core.

**Comment by lambdageek** [comment]
hm. yea, I don't think our loader does that right now.

**Comment by lambdageek** [comment]
Actually, I'm wrong.  We do have code that's supposed to do this: https://github.com/mono/mono/blob/9bf703b031bf81fa621c3d2318a4fc4333b80d3b/mono/metadata/assembly.c#L3009-L3024

So one of 3 problems:
1. We reuse the `MonoAssembly*` but somehow end up creating a new `MonoReflectionAssembly*` (managed `Assembly` object).
2. This code gets called, but `mono_assembly_invoke_search_hook_internal` never returns an assembly to reuse
3. This code never gets called.
