### ISSUE TITLE
[netcore] Make System.Reflection.Tests.AssemblyTests.GetType_DoesntSearchMscorlib Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15075]
The test currently fails with:

```
Starting:    System.Reflection.Tests (parallel test collections = on, max threads = 12)
    System.Reflection.Tests.AssemblyTests.GetType_DoesntSearchMscorlib [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.TypeLoadException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.Reflection.Tests.AssemblyTests.GetType_DoesntSearchMscorlib()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by CoffeeFlux** [comment]
"This method only searches the current assembly instance. The name parameter includes the namespace but not the assembly. To search other assemblies for a type, use the Type.GetType(String) method overload, which can optionally include an assembly display name as part of the type name."
In this case, it's searching the Assembly containing the test class, and thus should fail to locate `System.Object`.
