### ISSUE TITLE
[netcore] Implement System.Runtime.InteropServices.Marshal Fully

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15085]
The following methods throw PNE exceptions and should be implemented:

- [ ] ReadByte

- [ ] ReadInt16

- [ ] ReadInt32

- [ ] ReadInt64

- [ ] WriteByte

- [ ] WriteInt16

- [ ] WriteInt32

- [ ] WriteInt64

- [ ] GetExceptionCode

- [ ] GetExceptionPointers

**Comment by marek-safar** [comment]
This is expected, we don't plan to implement them please disable the test with conditional

**Comment by steveisok** [comment]
Sure, noted in the rsp file.

**Comment by MaximLipnin** [comment]
Because those APIs are obsolete, the related xunit tests will be skipped on mono (https://github.com/dotnet/runtime/pull/2087)
