### ISSUE TITLE
[Xamarin.Android] Missing Mono public symbol declarations in the headers shipped with the Mono archive

### ISSUE THREAD

**Issue by grendello** [mono/mono#15099]
`Xamarin.Android` is switching away from `dlopen/dlsym` to link the Mono runtime directly and therefore we need to be able to include Mono header files that declare the functions we use. Most of them are already there, however there is a small set that isn't:

- [mono_aot_register_module](https://github.com/mono/mono/blob/e6e9d5f6eb5488d9f87ab39727d76fb2ca81702c/mono/mini/aot-runtime.h#L272)
- [mono_set_use_llvm](https://github.com/mono/mono/blob/e6e9d5f6eb5488d9f87ab39727d76fb2ca81702c/mono/mini/mini-runtime.c#L126) (perhaps it would be better to introduce a function to set the flag?)
- [mono_jit_thread_attach](https://github.com/mono/mono/blob/e6e9d5f6eb5488d9f87ab39727d76fb2ca81702c/mono/mini/mini-runtime.h#L455)

**Comment by lambdageek** [comment]
Keeping it open until the 2019-06 PR is merged

**Comment by lambdageek** [comment]
Fixed in 2019-06 with #15132. closing.
