### ISSUE TITLE
[netcore] Make System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15164]
The test currently fails with:

```
System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Our initial thoughts were that tests for ThreadPool.SetMaxThreads(-1, -1) == true, which only happens to work on CoreCLR because the managed SetMaxThreadsNative prototype uses "int"s while the unmanaged code uses "DWORD"s and
thus it interprets it as large positive numbers.

The goal is to make the test pass.

**Comment by MaximLipnin** [comment]
It was asked in https://github.com/dotnet/corefx/issues/36885 and fixed in https://github.com/dotnet/coreclr/pull/24163 but the test was excluded.

**Comment by MaximLipnin** [comment]
@filipnavara After the mentioned fix coreclr has the same behavior as mono does. Does it make sense to fix that test or maybe create simpler one?

**Comment by filipnavara** [comment]
Yep, the test in CoreFX should be fixed. AFAIK nobody did that yet.

**Comment by MaximLipnin** [comment]
This issue doesn't seem actual anymore, at least in mono repo. Should we close it?

**Comment by filipnavara** [comment]
The implementation was fixed for CoreCLR as stated above. The test was fixed in https://github.com/dotnet/runtime/commit/0cdec7a83e0ed1a1df0b37cf12c9266d4205bd15. This should be closed.
