### ISSUE TITLE
[netcore] System.Drawing.Drawing2D.Tests.ColorBlendTests.Ctor_LargeCount_ThrowsOutOfMemoryException

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15189]
The test currently fails with:

```
System.Drawing.Drawing2D.Tests.ColorBlendTests.Ctor_LargeCount_ThrowsOutOfMemoryException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.OutOfMemoryException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.Drawing.Drawing2D.Tests.ColorBlendTests.Ctor_LargeCount_ThrowsOutOfMemoryException()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why an OOM isn't being thrown and make the test pass.

**Comment by filipnavara** [comment]
Mono supports large arrays, this should be fixed with proper condition on the CoreFX test.

**Comment by jaykrell** [comment]
Large arrays is a configure option though, I think.
Maybe it should be the default??

**Comment by filipnavara** [comment]
@jaykrell On Mono the default is that large arrays are enabled, on CoreCLR/CoreRT they are not. We are gradually fixing the CoreFX tests to properly apply the correct conditions on the tests depending on whether the runtime supports it or not.

**Comment by jaykrell** [comment]
@filipnavara I don't think so, not in the default configure. Though I wish so -- I was trained to use `size_t`. Maybe in the Xamarin configurations though?

**Comment by marek-safar** [comment]
There is already setting `IsLargeArrayNotSupported` in corefx which we just apply to this test

**Comment by filipnavara** [comment]
Should be fixed with the next CoreFX version bump.
