### ISSUE TITLE
[netcore] Make System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15195]
The test currently fails with:

```
System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.IO.FileNotFoundException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by CoffeeFlux** [comment]
Failure is unchanged as of now.

**Comment by CoffeeFlux** [comment]
This now passes outside of the initial failure, which is the result of the assembly being loaded before the test is actually run. Unsure of why this happens, but it's the only remaining issue.

**Comment by CoffeeFlux** [comment]
The initial failure appears to be our preload hook finding the test noop assembly via the domain search path when it shouldn't(?)
