### ISSUE TITLE
Client-side Blazor local time zone is always UTC

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#15260]
_From @xJonathanLEI on Wednesday, June 19, 2019 10:11:41 AM_

### Describe the bug
In client-side Blazor, the local TimeZoneInfo is always set to UTC, rending methods like `.ToLocalTime()` in `DateTime` useless.

### To Reproduce
1. Using this version of ASP.NET Core `3.0.0-preview6-27804-01`
2. Create a client-side Blazor project
3. Run the following code:

        Console.WriteLine(TimeZoneInfo.Local.BaseUtcOffset);

4. The output is always `00:00:00`

### Expected behavior
The output should reflect the machine timezone settings, retrieved from the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions) api.

### Additional context
.NET Core SDK Version: `3.0.100-preview6-012264`

_Copied from original issue: aspnet/AspNetCore#11367_

**Comment by mkArtakMSFT** [comment]
_From @xJonathanLEI on Wednesday, June 19, 2019 10:12:04 AM_

Is this a Mono issue? I'm not sure. Submitting anyways.

**Comment by xJonathanLEI** [comment]
@mkArtakMSFT Weird enough. I just tried compiling the following lines with mono locally and it works fine:

    using System;

    namespace TimeZoneTest
    {
        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine(TimeZoneInfo.Local.BaseUtcOffset);
            }
        }
    }

Prints:

    08:00:00

I don't really know how things work here. Maybe it's the WebAssembly runtime? Just providing context.

**Comment by Andrzej-W** [comment]
I think it is a dup of #6368

**Comment by mkArtakMSFT** [comment]
@xJonathanLEI, just for clarification, I've just moved these issues from the `aspnet/Blazor` repo. The original posters of the comments are listed at `From @[originalPoster]` in each post.

**Comment by seriouz** [comment]
@mkArtakMSFT Somebody developed a workaround for this issue https://dev.to/j_sakamoto/workaround-how-to-resolve-local-time-zone-on-blazor-spa-v05x-foi

**Comment by lewing** [comment]
This has ben resolved in newer versions

**Comment by Bittrex1354** [comment]
nastia1828Aas
