### ISSUE TITLE
[MacOS][Tests] Several tests fail due to a System.IO exception

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#15328]
The following tests with not much info but with a System.IO.Exception.

Failing tests:

> System.Text.RegularExpressions.Tests.RegexConstructorTests.StaticCtor_InvalidTimeoutObject_ExceptionThrown
> System.Text.RegularExpressions.Tests.RegexConstructorTests.StaticCtor_InvalidTimeoutRange_ExceptionThrown
> System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Throws
> System.Text.RegularExpressions.Tests.RegexMatchTests.Match_SpecialUnicodeCharacters_Invariant
> System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix
> System.Text.RegularExpressions.Tests.RegexMatchTests.Match_SpecialUnicodeCharacters_enUS
> System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_culture_and_options
> System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries
> System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw
> System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Second_drops_first
> System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Shrink_cache
> System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsEnUS
> System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsDanish
> System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsAzeriLatin
> System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsTurkish
> System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsBasic
> System.Text.RegularExpressions.Tests.RegexGroupTests.GroupsCzech
> RemoteExecutorTests.RemoteInvokeWritesToFil

**Comment by akoeplinger** [comment]
These tests are using the remote executor to run tests in a new process. Probably something goes wrong when starting the process.

**Comment by marek-safar** [comment]
@akoeplinger can this be closed now?

**Comment by akoeplinger** [comment]
Yes, they're fixed.
