### ISSUE TITLE
macOS Catalina Support

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#15333]
The upcoming macOS version called Catalina is coming with more restrictions and requirements. The release is scheduled for the fall of this year and with the preview version available already.

Together with Catalina, a new version of xcode is available and we need to ensure they both work correctly with Mono.

- [x] Setup macOS Catalina bots with the latest preview available
- [x] Compile Mono on macOS Catalina with xcode11 on a dedicated lane: https://jenkins.mono-project.com/job/test-mono-mainline-catalina/label=osx-catalina-amd64/
- [x] Ensure all tests pass as expected
- [x] Verify Mono installer runs successfully on macOS Catalina

**All fixes for macOS Catalina need to be backported to at least 2019-06 branch**

/cc @chamons

**Comment by directhex** [comment]
I don't think our Catalina lane is very useful yet.

We've confirmed that we can compile with Xcode 11, but we need to care about notarization, and notarization mandates hardened runtime, and we don't CI that

**Comment by directhex** [comment]
We're still running experiments to see what exactly is or isn't acceptable to the notarization service

**Comment by akoeplinger** [comment]
We landed the notarization and hardened runtime changes in 2019-06 and I did some checks on a Catalina 10.15 beta4 machine to verify the behavior:

- unsigned .pkg -> GateKeeper complains about unidentified developer and prevents opening (*)
- signed, but not notarized .pkg -> GateKeeper complains about not being able to check for malware and prevents opening (*)
- **signed and notarized .pkg -> no GateKeeper dialog and the installer opens normally**

(*) you can still bypass the check by doing the Control+Open trick

2019-06 packages after 6.4.0.135 should be fully ready for Catalina.

**Comment by akoeplinger** [comment]
For reference, these are the entitlements we're currently adding to the mono binary included in the Mono .pkg installer:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>com.apple.security.cs.allow-jit</key>
		<true/>
		<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
		<true/>
		<key>com.apple.security.cs.allow-dyld-environment-variables</key>
		<true/>
		<key>com.apple.security.cs.disable-library-validation</key>
		<true/>
	</dict>
</plist>
```
