### ISSUE TITLE
StringBuilder marshalling bug

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#15366]
## Steps to Reproduce

1. Compile:
```csharp
using System;
using System.Runtime.InteropServices;
using System.Text;

class Program
{
    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    static extern uint CharLowerBuffW([In, Out] StringBuilder lpsz, uint cchLength);

    static void Main()
    {
        var sb = new StringBuilder().AppendLine("HELLO").AppendLine("WORLD").AppendLine("FROM MONO");
        CharLowerBuffW(sb, (uint)sb.Length);
        Console.WriteLine(sb); // sb is corrupted/freed at this step
    }
}
```

### Expected Behavior

```
hello
world
from mono
```

### Actual Behavior

Segfault
or sometimes StringBuilder contains some random chars at the end after marshalling.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Comment by filipnavara** [comment]
There are two separate bugs triggered by this and one more bug related to it:

1) `mono_string_builder_to_utf16_impl` doesn't properly NULL terminate the strings. It appends a terminating zero at the location specified by `capacity`, not by `length`. Workaround: Add `str [mono_string_builder_string_length (sb)] = 0;`.
2) `mono_string_utf16_to_builder_copy` corrupts memory when trying to marshal data back into multi-chunk `StringBuilder`. Adding `g_assert (mono_array_handle_length (chunkChars) >= string_len);` to it helps tracking down to a place where the memory corruption actually happens.
3) Even when the `StringBuilder` is marshalled only with the `[In]` attribute the code in 2) is still triggered and causes memory corruption.

**Comment by filipnavara** [comment]
Confirmed to be the underlying cause of #15306. Big thanks for tracking it down!

**Comment by EgorBo** [comment]
@steveisok btw, this issue reproduces on regular mono too 🙂

**Comment by filipnavara** [comment]
Yep, affects regular Mono too. I have a fix for some of the issues in the pipeline but I need to clean it up before submitting.

**Comment by steveisok** [comment]
Thanks, labeled (I think) correctly.

**Comment by filipnavara** [comment]
@marek-safar While it is most visible on Windows it affects all systems. Bug 1 is UTF-16 specific, bug 2 happens with UTF-8 too AFAICT, bug 3 affects everything.
