### ISSUE TITLE
Socket.EndConnect throws ambigiously described exception if its argument is not SocketAsyncResult

### ISSUE THREAD

**Issue by NattyNarwhal** [mono/mono#15364]
Trying to track this vague but reproducible error. This could very well be my own (or MailKit's) stupidity, but I have a user encountering a regression versus a build from October (I know....) and this month. It seems trying to connect to a mail server with MalKit bombs with some ambigious messages at first glance. 

Side note: the message [here](https://github.com/mono/mono/blob/068e8fe0424806753d7ab72a7b9bf0e54b58408b/mcs/class/System/System.Net.Sockets/Socket.cs#L2789) should include `methodName` and say that it couldn't cast.

## Steps to Reproduce
I have a minimal viable example, but I cannot reproduce it; only within the context of MailKit [which has some extra little complications](https://github.com/jstedfast/MailKit/blob/0fabc1bac4f234f30bf211ae8d6617dffa52b0fc/MailKit/Net/SocketUtils.cs#L38). But the flow of it is:

1. Call BeginConnect and get an IAsyncResult.
2. await on it from the task completion source
3.  Call EndConnect with the IAsyncResult you were given.

My sample program which can't reproduce but follows the same logic:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace asynctest
{
    class Program
    {
        // https://github.com/jstedfast/MailKit/blob/0fabc1bac4f234f30bf211ae8d6617dffa52b0fc/MailKit/Net/SocketUtils.cs#L38
        // https://github.com/mono/mono/blob/068e8fe0424806753d7ab72a7b9bf0e54b58408b/mcs/class/System/System.Net.Sockets/Socket.cs#L2789
        static async Task Main(string[] args)
        {
            var doAsync = bool.Parse(args[2]);
            var host = args[0];
            IPAddress[] dns;
            if (doAsync)
            {
                dns = await Dns.GetHostAddressesAsync(host).ConfigureAwait(false);
            }
            else
            {
                dns = Dns.GetHostAddressesAsync(host).GetAwaiter().GetResult();
            }
            var port = int.Parse(args[1]);
            Console.WriteLine("* Ctor");
            var ct = new CancellationToken();
            var tcs = new TaskCompletionSource<bool>();

            for (int i = 0; i < dns.Length; i++)
            {
                Console.WriteLine(" * Begin {0}", dns[i]);
                ct.ThrowIfCancellationRequested();
                var socket = new Socket(dns[i].AddressFamily, SocketType.Stream, ProtocolType.Tcp);
                if (doAsync || ct.CanBeCanceled)
                {
                    using (var registration = ct.Register(() => tcs.TrySetCanceled(), false))
                    {
                        var ar = socket.BeginConnect(dns[i], port, e => tcs.TrySetResult(true), null);
                        Console.WriteLine(" * ar type {0}", ar.GetType());
                        Console.WriteLine("* BeginConnect");
                        if (doAsync)
                            await tcs.Task.ConfigureAwait(false);
                        else
                            tcs.Task.GetAwaiter().GetResult();
                        socket.EndConnect(ar);
                        Console.WriteLine("* EndConnect");
                    }
                }
                else
                {
                    socket.Connect(dns[i], port);
                }
                socket.Close();
                Console.WriteLine("* Close");
            }
        }
    }
}
```

### Current Behavior

[This line of code](https://github.com/mono/mono/blob/068e8fe0424806753d7ab72a7b9bf0e54b58408b/mcs/class/System/System.Net.Sockets/Socket.cs#L2787) which is called by EndConnect is being given a `Task<System.Net.IPAddress[]>` instead of the expected `SocketAsyncResult `. BeginConnect should provide this, but somehow it's being given a Task? I'm using a prebuilt MailKit here, so it is a bit hard to debug here, though I am recompiling the runtime to poke it.

### Expected Behavior

The IAsyncResult returned from BeginConnect should work with EndConnect. Is the API surface too vague, and should be constricted, or is it not flexible enough to deal with this case?

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] i

**Version Used**:

```
Mono JIT compiler version 6.5.0.93 (tarball Sat Jun  8 15:08:04  2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  ppc
        Disabled:      shared_perfcounters
        Misc:          softdebug
        Interpreter:   yes
        Suspend:       preemptive
        GC:            sgen
```

## Stacktrace
With a trace set to only print exceptions, from the user:

```
[1:] EXCEPTION handling: System.NotSupportedException: No data is available
[1:] EXCEPTION handling: System.NotSupportedException: No data is available
Adding From <redact>
Adding To <redact>
Adding subject:Subject
No body text:
Auth type:auto
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
Auth type:auto
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
[1:] EXCEPTION handling: System.ArgumentException: Invalid IAsyncResult
Parameter name: asyncResult
Email error: Invalid IAsyncResult
Parameter name: asyncResult
Stack: at System.Net.Sockets.Socket.ValidateEndIAsyncResult (System.IAsyn
at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult)
at MailKit.Net.SocketUtils.ConnectAsync (System.String host, System.Int32
at MailKit.Net.SocketUtils.ConnectAsync (System.String host, System.Int32
at MailKit.MailService.ConnectSocket (System.String host, System.Int32 po
at MailKit.Net.Smtp.SmtpClient.ConnectAsync (System.String host, System.I
Parameter name: asyncResult
Stack: at System.Net.Sockets.Socket.ValidateEndIAsyncResult (System.IAsyn
at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult)
at MailKit.Net.SocketUtils.ConnectAsync (System.String host, System.Int32
at MailKit.Net.SocketUtils.ConnectAsync (System.String host, System.Int32
at MailKit.MailService.ConnectSocket (System.String host, System.Int32 po
at MailKit.Net.Smtp.SmtpClient.ConnectAsync (System.String host, System.I
at MailKit.Net.Smtp.SmtpClient.Connect (System.String host, System.Int32
at MonoMailSend.Program.Main (System.String[] args) [0x0046b]
```

Interesting excerpt from me trying to reproduce with [their example code](https://github.com/richardschoen/MonoOniSamples/tree/master/MonoMailSend/MonoMailSend):

```
[1: 31.12857 33] LEAVE: System.Net.Sockets.Socket:BeginConnect (string,int,System.AsyncCallback,object)[System.Threading.Tasks.Task`1:700000000505540]
```

**Comment by NattyNarwhal** [comment]
Actually, [this line](https://github.com/mono/mono/blob/068e8fe0424806753d7ab72a7b9bf0e54b58408b/mcs/class/System/System.Net.Sockets/Socket.cs#L980) looks pretty interesting considering the fact it's returning a task; coming from [this commit](https://github.com/mono/mono/commit/068e8fe0424806753d7ab72a7b9bf0e54b58408b#diff-33b28a9dc0b8032650ed77213481a99f). I haven't checked if this is the root cause, but it seems interesting...

**Comment by NattyNarwhal** [comment]
I can confirm two workarounds for this issue:

1. Get rid of the conditions on ifdef in MailKit, so just we [use the normal Connect](https://github.com/jstedfast/MailKit/blob/0fabc1bac4f234f30bf211ae8d6617dffa52b0fc/MailKit/Net/SocketUtils.cs#L77) (not a real workaround, so we don't trigger the behaviour)

2. Revert https://github.com/mono/mono/commit/068e8fe0424806753d7ab72a7b9bf0e54b58408b because it introduces the issue. (likely real issue, because the issue at hand makes sense when you realize this probably returns a Task)

**Comment by NattyNarwhal** [comment]
FWIW, I can reproduce this running the same test program on FreeBSD/amd64; so not an i-specific problem.

**Comment by baulig** [comment]
There are various problems, incompatibilities and other issues in the Socket class - especially the Begin/End code.  Since this is only a mostly cosmetic issue and we're likely going to replace the entire class with the CoreFX version in near future, it doesn't make much sense to change anything in the old implementation.

**Comment by DevEddy** [comment]
Hey,

I am experiencing the same issue with the latest update. 
What is the workaround for this?
When I use the .Connect it works - But how can I define the connection timeout?

Thanks in advance,
Eddy

**Comment by digocesar** [comment]
I'm having this problem at a Xamarin project and a mono-service project in Raspberry Pi.
What is the proposed workaround?
The code `ConnectionSocket.ConnectAsync(Hostname, Port);` doesn't exists to me.
When is scheduled to release a CoreFX version of this class?
