### ISSUE TITLE
Named Mutex Throwing NotSupportedException on iOS/Android Tests 

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15379]
## Steps to Reproduce

1. Build targeting Android or iOS off of 2019-06 branch  
2. Run System.Net.Security tests

### Current Behavior

Some tests will fail w/ NotSupportedExceptions because named mutexes are not 
supported on the mobile profile.

### Expected Behavior

Tests should not throw 

## On which platforms did you notice this

[X] macOS
[X] Linux
[ ] Windows

**Version Used**:

2019-06

**Comment by mandel-macaque** [comment]
We have the following [errors on iOS](https://gist.github.com/mandel-macaque/2e818763368add9c78b7699c80c5fcd7).

**Comment by baulig** [comment]
> We have the following [errors on iOS](https://gist.github.com/mandel-macaque/2e818763368add9c78b7699c80c5fcd7).

That's the same error - which is good news :-)

Thanks a lot for the information, I will have a PR up shortly!
