### ISSUE TITLE
Crash in UnixStream Finalizer

### ISSUE THREAD

**Issue by Therzok** [mono/mono#15394]
## Steps to Reproduce

No repro steps sadly, crashes in finalizer thread:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937032

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
5.18.1.28

## Stacktrace

```
Mono.Unix.UnixMarshal.ThrowExceptionForLastError()
Mono.Unix.UnixMarshal.ThrowExceptionForLastErrorIf(Int32)
Mono.Unix.UnixStream.Close()
Mono.Unix.UnixStream.Finalize()
```

**Comment by alexischr** [comment]
I see a possible race here: https://github.com/mono/mono/blob/master/mcs/class/Mono.Posix/Mono.Unix/UnixStream.cs#L401

(fileDescriptor gets closed from another thread but not yet assigned InvalidFileDescriptor, causing a second close - or it is set to InvalidFileDescriptor by another thread after the `if`, and the close is called on -1)

**Comment by alexischr** [comment]
I see how now: https://blogs.msdn.microsoft.com/bclteam/2005/03/15/safehandle-a-reliability-case-study-brian-grunkemeyer/ - We are not using SafeHandles in UnixStream, it is a pretty old-school class.

A fast solution is `lock(obj)` on Close(), but we probably need more evidence it's not something else

**Comment by alexischr** [comment]
@Therzok do you know if this is still happening?

**Comment by Therzok** [comment]
Haven't had any hits in 8.4+. Upstream bug is closed. Could probably close this and we'll reopen if we see it again

**Comment by Therzok** [comment]
Haven't seen this recently. Will close, please reopen if you want to fix the underlying issue.
