### ISSUE TITLE
Unity-Mono building problem

### ISSUE THREAD

**Issue by solovina** [mono/mono#15419]
I tried to compile Unity-Mono from https://github.com/Unity-Technologies/mono.
My operation follows the Mono official and Unity-Mono Readme Page. After installing necessary packages and setting environment vars,  I run ./autogen.sh, and try to execute the shells in ./external/buildscripts.
After editing some scripts, I successfully run build_runtime_android.sh, build the android runtime, but other builds still not working.  
My purpose is to build the full contents of UnityEditor's Mono and MonoBleedingEdge folder. How can I get the results? Is it true to execute build_all_osx.sh?
   
Here is some information:
macOS Mojave(10.14.5)
XCode 10.2.1
The 3rd-party packages such as automake and libtool are installed by brew, so they should be latest.
Android SDK and NDK r10e installed.

The mono branch being checkout is unity-4.6(Because of our outdated game project), after run build_all_osx.sh, it print errors:

```
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -D_THREAD_SAFE -DGC_MACOSX_THREADS -DPLATFORM_MACOSX -DUSE_MMAP -DUSE_MUNMAP -DGetCurrentProcess=MonoGetCurrentProcess -DGetCurrentThread=MonoGetCurrentThread -DCreateEvent=MonoCreateEvent -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.5 -arch i386 -g -O0 -D_XOPEN_SOURCE=1 -DMONO_DISABLE_SHM=1 -DDISABLE_SHARED_HANDLES=1 -mstackrealign   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.5 -arch i386 -g -O0 -D_XOPEN_SOURCE=1 -DMONO_DISABLE_SHM=1 -DDISABLE_SHARED_HANDLES=1 -mstackrealign -static -arch i386 -o libmonogc-static.la  allchblk.lo alloc.lo blacklst.lo checksums.lo dbg_mlc.lo dyn_load.lo finalize.lo gc_dlopen.lo gcj_mlc.lo headers.lo malloc.lo mallocx.lo mark.lo mark_rts.lo misc.lo new_hblk.lo obj_map.lo os_dep.lo pcr_interface.lo ptr_chck.lo real_malloc.lo reclaim.lo solaris_pthreads.lo solaris_threads.lo specific.lo stubborn.lo typd_mlc.lo backgraph.lo win32_threads.lo pthread_support.lo pthread_stop_world.lo darwin_stop_world.lo  mach_dep.lo -lpthread  

libtool:   error: 'mach_dep.lo' is not a valid libtool object

make[3]: *** [libmonogc-static.la] Error 1
```

**Comment by lambdageek** [comment]
Hi @solovina thanks for reaching out.  The best place to ask about Unity's fork of Mono is on the [Unity Forums](https://forum.unity.com/).  If you believe that there is a bug, please report to [Unity QA](https://unity3d.com/unity/qa/bug-reporting).
