### ISSUE TITLE
System.IO.Path.GetPathRoot(" ") doesn't behave the same as in CoreCLR

### ISSUE THREAD

**Issue by Therzok** [mono/mono#15434]
## Steps to Reproduce

1. See attached project
[fsw-whitespace.zip](https://github.com/mono/mono/files/3332199/fsw-whitespace.zip)

2. Runs fine on dotnetcore, crashes on Mono

### Current Behavior
App crashes due to file being named <whitespace>. See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937705

### Expected Behavior
App doesn't crash. Whitespace is a perfectly valid file name. It should only throw [ArgumentException when string is Empty](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getpathroot?view=netframework-4.8#System_IO_Path_GetPathRoot_System_String_)

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
```
Mono JIT compiler version 6.0.0.296 (2019-02/1e9f3bfbc5a Wed Jun 12 04:07:25 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Stacktrace

```
System.IO.Path.GetPathRoot(String)
System.IO.Path.GetFileName(ReadOnlySpan`1)
System.IO.CoreFX.FileSystemWatcher.MatchPattern(ReadOnlySpan`1)
System.IO.CoreFX.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes,ReadOnlySpan`1)
System.IO.CoreFX.FileSystemWatcher.RunningInstance.ProcessEvents(Int32,Byte**,FSEventStreamEventFlags[],UInt64[],FileSystemWatcher)
System.IO.CoreFX.FileSystemWatcher.RunningInstance.<>c__XXX.<FileSystemEventCallback>b__XXX(Object)
System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object)
System.IO.CoreFX.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr,IntPtr,IntPtr,Byte**,FSEventStreamEventFlags[],UInt64[])
System.IO.CoreFX.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.WatchForFileSystemEventsThreadStart(Object)
System.Threading.ThreadHelper.ThreadStart_Context(Object)
System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object)
System.Threading.ThreadHelper.ThreadStart(Object)
```

**Comment by lambdageek** [comment]
Standalone repro:

```csharp
using System;
using System.IO;

namespace pathy
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Path.GetPathRoot(" "));
        }
    }
}
```

**Comment by steveisok** [comment]
On mono I get an ArgumentException, while on Core I get an empty string.

**Comment by steveisok** [comment]
https://github.com/mono/mono/blob/19bb89805ac2eb56b09fed40cab1dd342f97a5e3/mcs/class/corlib/System.IO/Path.cs#L436-L442

**Comment by steveisok** [comment]
Now, if I run the same thing on netfx, I'll get an ArgumentException.  So, it appears that mono and netfx are the same here.  Do we want to change compat at this level?

**Comment by Therzok** [comment]
@steveisok Did you try my repro project or @lambdageek's ? I think they work differently on .NET Framework.

**Comment by steveisok** [comment]
Both.  The File.Delete in the netfx project just needed a File.Exists check and then FSW will throw the same exception.

**Comment by Therzok** [comment]
It's a crasher in VSMac. Importing corefx code ended up causing this, so converging to corefx behaviour would be best for us.

**Comment by steveisok** [comment]
@Therzok To check my understanding, you're saying this regressed on you?

**Comment by Therzok** [comment]
The old Mono FileSystemWatcher was unreliable, but we've migrated over time to use the FileSystemWatcher more and more after it was imported from CoreFX.

We have no way to handle this crash on our side. If we're using the watcher code from CoreFX and it expects Path APIs to behave the same way, I think we should go with that.

Another thing to consider is that ` ` is a valid filename character, and I would expect the Path APIs to support this.

Going on a Windows machine:
```
D:\>type nul > " "
The system cannot find the path specified.

D:\>type nul > "a.txt"

D:\>type nul > " .txt"
```

A file name as just ` ` is invalid on Windows. So that's why the APIs threw an exception on Windows.

**Comment by Therzok** [comment]
I say it’s a Windows behaviour, not a netfx compatibility one, as it is the OS that does not allow files to be named that way, meaning that this is a limitation of Mono on any unix platform.

On the other hand, I understand the point, but I don’t see how relying on an exception to be thrown in a perfectly okay scenario to be a concern. In fact, it’s possible people haven’t hit this yet.

The crash rate is low because it’s also a rare scenario to encounter, but definitely possible, so this should still tilt the scales in favour of allowing ” ” to not throw.

```csharp> Directory.GetFiles(".")
{ "./ProgressMonitor.cs", "./ErrorHelper.cs", "./gccrash.csproj.user", "./gccrash.csproj", "./LogTextWriter.cs", "./gccrash.sln", "./ ", "./Program.cs" }```

Other methods allow this file name to be processed.

```csharp> File.Exists(" ")
false
csharp> File.Exists("./ ")
true```

In the exists example above, I have 2 methods giving me conflicting results because GetPathRoot is broken.

**Comment by jaykrell** [comment]
Space is valid on Windows too.
Try this:
```
mkdir t
cd t
dir
echo > "\\?\%cd%\ "
dir
echo > "\\?\%cd%\  "
dir
```

Also keep in mind that all file systems are usable remotely. So the rules are not what you might think.
That is, you can create these files via SMB or NFS to Windows without any special syntax.

**Comment by jaykrell** [comment]
Basically you should avoid any path validation. You will get it wrong. Leave it to the next layer down.

**Comment by steveisok** [comment]
@Therzok You guys are right, but I don't think it's a good idea to modify Path for the desktop.  Yes, it's confusing, but we should still try to maintain netfx compat.  

I am considering a fix in our FSW fork by wrapping a try catch around:

https://github.com/mono/corefx/blob/d5f406ea037710aaf2c6b1bd4fe92fa723068a3a/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs#L399-L401

**Comment by marek-safar** [comment]
I agree with @steveisok, we pulled corefx version of FSW and that's the part which should be adjusted to work with .NET Framework Path. 

Note: we don't need to try/catch just avoid calling the API with a value which we know will fail

**Comment by Therzok** [comment]
The fix broke any path containing spaces now...

**Comment by steveisok** [comment]
Yeah, I noticed that too :-).  I'll fix.

**Comment by Therzok** [comment]
Can we reopen the issue until then?

**Comment by Therzok** [comment]
Was fixed in https://github.com/mono/corefx/pull/308/files
