### ISSUE TITLE
"pos undeclared" compilation error

### ISSUE THREAD

**Issue by volo-zyko** [mono/mono#15441]
This code doesn't compile since 20c06cc0f40167a388be2f939b44d838876a979f when in `mono_arch_emit_epilog_sub` was removed `int pos = 0`

https://github.com/mono/mono/blob/886c49017470112af1a73034d8951d6ca00b641e/mono/mini/mini-mips.c#L5300

**Comment by marek-safar** [comment]
@jaykrell could you please address the build breakage
