### ISSUE TITLE
[wasm][sdk] Threading support.

### ISSUE THREAD

**Issue by kjpou1** [mono/mono#15481]
Add threading support to the SDK when it becomes available.

> If code is compiled with -s USE_PTHREADS=1 and the current browser does not support multithreading, then an exception will be thrown at page load time. It is not possible to build one binary that would be able to leverage multithreading when available and fall back to single threaded when not. For such backwards compatibility, two separate builds must be done, one with -s USE_PTHREADS=1 and the other with -s USE_PTHREADS=0.

The SDK will need to deliver two different binaries one that includes threading and one that does not.

----------

Added threads directories PR:  https://github.com/mono/mono/pull/15543

**Comment by YordanYanakiev** [comment]
Waiting for Threading support as well.

**Comment by lewing** [comment]
We're close to being able to reenable support
