### ISSUE TITLE
[2019-06][iOS] monotouch-tests fail on iOS in all configurations on today extensions

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#15508]
The following tests fail on all configurations when they do not fail on mono 2019-02:

> [FAIL] MessageHandlerTest.AcceptSslCertificatesServicePointManager(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.AcceptSslCertificatesServicePointManager(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.CFNetworkHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RedirectionWithAuthorizationHeaders(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RedirectionWithAuthorizationHeaders(System.Net.Http.CFNetworkHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RedirectionWithAuthorizationHeaders(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RejectSslCertificatesServicePointManager(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RejectSslCertificatesServicePointManager(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.TestNSUrlSessionHandlerCookies() : System.NullReferenceException : Object reference not set to an instance of an object 

Useful info:

* [Build log](https://gist.github.com/mandel-macaque/1404de407572b830ab7e82a3ded04975)
* [Run log](https://gist.github.com/mandel-macaque/d84e9f0147372628e4ad3f9ca6f6cde2)
* [Test run log](https://gist.github.com/mandel-macaque/60ccc908d56d3370be9c809077e4c6eb)

**Comment by steveisok** [comment]
@baulig Please take a look and fix if possible.

**Comment by akoeplinger** [comment]
This doesn't seem related to Http, I get the same error in other tests. The NullReferenceException comes from https://github.com/xamarin/xamarin-macios/blob/a7cb29a4b72405e62100babcc14645a6b6fe207f/tests/monotouch-test/AppDelegate.cs#L78

`window` is null there, which sounds like it might be as expected in a today extension?

**Comment by akoeplinger** [comment]
I just built xamarin-macios master and see the same issue there, so I don't think this is a 2019-06 issue.

**Comment by mandel-macaque** [comment]
@akoeplinger confirmed on my side, we can remove it from the mono 2019-06 (it was not a blocker nevertheless)
