### ISSUE TITLE
[Android][2019-02][AOT] Opt.exe crashes when the linker is disabled

### ISSUE THREAD

**Issue by pjcollins** [mono/mono#15546]
## Steps to Reproduce

1. Create a new Android project in VS 2019 16.2.
2. Enable the Release configuration.
3. Open the Project Properties and select Android Options -> Linking -> None
Deploy, or select Build -> Archive...

### Current Behavior
opt.exe crashes - https://gist.github.com/pjcollins/bd2d29d13416e9bb952cfbb237fb4d57

[binlog-opt-dump.zip](https://github.com/mono/mono/files/3355899/binlog-opt-dump.zip)

**Workaround Options** 
1. Enable Android Options -> Linking -> Sdk Assemblies Only.
2. Disable Android Options -> Use LLVM Optimizing Compiler.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:
VS 2019 16.2 Preview 3.

**Comment by lambdageek** [comment]
@lateralusX Is this `opt.exe` running out of memory? Have we seen crashes like this before while AOTing large assemblies?

**Comment by lateralusX** [comment]
When build largest libraries on Windows using msvc build LLVM tools I don't get higher than 725 MB of any instance of opt.exe/llc.exe and these are 64-bit binaries as well.

The above looks like an OOM situation and looking briefly into the dmp files for opt.exe show that there is at least one heap that has a size of 1.6 GB and I guess that opt.exe is still a 32-bit binary produced from gcc build (at least looking at an older install that was the case). Could be interesting to build the failing assembly using msvc build opt.exe as well and monitor behavior. Possible to share the failing opt.exe and assembly from above build (or point me to where I can download them) and I can do a test run locally and monitor memory usage (both under opt.exe part of Android build) but also using 64 bit msvc build version of opt.exe.

**Comment by pjcollins** [comment]
@lateralusX This is occurring on macOS as well, this should hopefully produce a simple enough repro for macOS if you don't have access to a windows machine: 

1. Download and install the latest [XA d16-3 .pkg](https://dl.internalx.com/vsts-devdiv/Xamarin.Android/2970086/d16-3/080eaac1e6aa835f97de3dc134f074d45c13e307/signed/metadata.json) (will install opt into `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/opt`).
2. Download and restore NuGets for https://github.com/xamarin/monodroid-samples/tree/master/android-o/AutofillFramework.
3. `msbuild /t:SignAndroidPackage /p:Configuration=Release /p:AotAssemblies=True /p:EnableLlvm=True /p:AndroidLinkMode=None AutofillFramework/AutofillFramework/AutofillFramework.csproj`

**Comment by lateralusX** [comment]
@pjcollins I didn't look more into details of this issue (except what mentioned above) and since #16568 seems to be hitting the same/similar issue (on both Mac and Windows) the question is if you want to keep this issue open? Since we have a work around for the problem (using linker) that I assume is the recommended way of building when building highly optimized builds using LLVM anyways for Android, I assume this issue currently has low priority?

**Comment by marek-safar** [comment]
Closing in favour of #16568
