### ISSUE TITLE
Hitting g_assert/g_error in MERP reporting code

### ISSUE THREAD

**Issue by leculver** [mono/mono#15555]
During MERP reporting for VS for Mac we are seeing the following message in VS for Mac logs:

`mono_os_sem_post: semaphore_signal failed with error 15`
`* Assertion at mono-state.c:220, condition 'out_level == next' not met, function:mono_summarize_timeline_phase_log, Log Error: Log transition to 2, actual expected next step is 7`

This kills the process and means we do not get a crash report.

@alexanderkyte @alexischr @SamMonoRT 

This is the version I am seeing from the reports:

    INFO [2019-07-03 16:15:36Z]: Starting Visual Studio 2019 for Mac 8.1.4 (build 5)
    INFO [2019-07-03 16:15:36Z]: Build Information
    Release ID: 801040005
    Git revision: 9c98f365cacfac65fbbaf0a77b2ea7864abef759
    Build date: 2019-06-28 21:07:05+00
    Build branch: release-8.1
    Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

    INFO [2019-07-03 16:15:36Z]: Running on Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
    INFO [2019-07-03 16:15:36Z]: Operating System: Mac OS X 10.14.5

**Comment by lambdageek** [comment]
@leculver which version of VS, which version of Mono?

**Comment by leculver** [comment]
@lambdageek Ah sorry, added that to the bug.  Also here is full spew from the point at which VS for Mac crashed:


    =================================================================
        Native Crash Reporting
    =================================================================
    Got a SIGSEGV while executing native code. This usually indicates
    a fatal error in the mono runtime or one of the native libraries 
    used by your application.
    =================================================================

    =================================================================
        Basic Fault Adddress Reporting
    =================================================================
    Memory around native instruction pointer (0x7fc5cea3f370):0x7fc5cea3f360  de b1 5e 01 01 00 00 00 ec b1 5e 01 01 00 00 00  ..^.......^.....
    0x7fc5cea3f370  d8 c9 f4 c7 c5 7f 00 00 7a 00 00 00 00 00 00 00  ........z.......
    0x7fc5cea3f380  b0 67 65 c5 c5 7f 00 00 10 ff b4 13 01 00 00 00  .ge.............
    0x7fc5cea3f390  c0 53 0c cb c5 7f 00 00 f1 1d 00 00 00 01 00 00  .S..............

    =================================================================
        Native stacktrace:
    =================================================================
         (No frames) 


    =================================================================
        Telemetry Dumper:
    =================================================================
    Pkilling 0x700010e5d000 from 0x10467d5c0
    Pkilling 0x7000101c8000 from 0x10467d5c0
    Pkilling 0x70000fe3c000 from 0x10467d5c0
    Pkilling 0x700011466000 from 0x10467d5c0
    Pkilling 0x700012a90000 from 0x10467d5c0
    Pkilling 0x700011a6f000 from 0x10467d5c0
    Pkilling 0x700013dba000 from 0x10467d5c0
    Pkilling 0x700015058000 from 0x10467d5c0
    Pkilling 0x700012078000 from 0x10467d5c0
    Pkilling 0x700010145000 from 0x10467d5c0
    Pkilling 0x7000143c3000 from 0x10467d5c0
    Pkilling 0x70000fdb9000 from 0x10467d5c0
    Pkilling 0x700012a0d000 from 0x10467d5c0
    Pkilling 0x700015661000 from 0x10467d5c0
    Pkilling 0x700012681000 from 0x10467d5c0
    Pkilling 0x7000149cc000 from 0x10467d5c0
    Pkilling 0x700013d37000 from 0x10467d5c0
    Pkilling 0x700015c6a000 from 0x10467d5c0
    Pkilling 0x70001044e000 from 0x10467d5c0
    Pkilling 0x7000130a2000 from 0x10467d5c0
    Pkilling 0x700010a57000 from 0x10467d5c0
    Pkilling 0x70001298a000 from 0x10467d5c0
    Pkilling 0x7000136ab000 from 0x10467d5c0
    Pkilling 0x700011060000 from 0x10467d5c0
    Pkilling 0x700011669000 from 0x10467d5c0
    Pkilling 0x700012907000 from 0x10467d5c0
    Pkilling 0x700014c52000 from 0x10467d5c0
    Pkilling 0x700011c72000 from 0x10467d5c0
    Pkilling 0x700013fbd000 from 0x10467d5c0
    Pkilling 0x70001525b000 from 0x10467d5c0
    Pkilling 0x70001227b000 from 0x10467d5c0
    Pkilling 0x7000145c6000 from 0x10467d5c0
    Pkilling 0x700013931000 from 0x10467d5c0
    Pkilling 0x700012884000 from 0x10467d5c0
    Pkilling 0x700015864000 from 0x10467d5c0
    Pkilling 0x700015e6d000 from 0x10467d5c0
    Pkilling 0x700010651000 from 0x10467d5c0
    Pkilling 0x7000132a5000 from 0x10467d5c0
    Pkilling 0x700010c5a000 from 0x10467d5c0
    Pkilling 0x700012c19000 from 0x10467d5c0
    Pkilling 0x700011263000 from 0x10467d5c0
    Pkilling 0x70001186c000 from 0x10467d5c0
    Pkilling 0x700014e55000 from 0x10467d5c0
    Pkilling 0x700011e75000 from 0x10467d5c0
    Pkilling 0x700012b96000 from 0x10467d5c0
    Pkilling 0x7000141c0000 from 0x10467d5c0
    Pkilling 0x70001545e000 from 0x10467d5c0
    Pkilling 0x70001247e000 from 0x10467d5c0
    Pkilling 0x7000147c9000 from 0x10467d5c0
    Pkilling 0x700013b34000 from 0x10467d5c0
    Pkilling 0x700015a67000 from 0x10467d5c0
    Pkilling 0x70001024b000 from 0x10467d5c0
    Pkilling 0x700012e9f000 from 0x10467d5c0
    Pkilling 0x700012b13000 from 0x10467d5c0
    Pkilling 0x700010854000 from 0x10467d5c0
    Pkilling 0x7000134a8000 from 0x10467d5c0
    Entering thread summarizer pause from 0x10467d5c0
    Finished thread summarizer pause from 0x10467d5c0.

    Waiting for dumping threads to resume

    Debug info from gdb:

    mono_os_sem_post: semaphore_signal failed with error 15* Assertion at mono-state.c:220, condition `out_level == next' not met, function:mono_summarize_timeline_phase_log, Log Error: Log transition to 2, actual expected next step is 7

**Comment by lambdageek** [comment]
It's moving to state `MonoSummarySuspendHandshake` but the expected next step is `MonoSummaryMerpWriter`

**Comment by alexanderkyte** [comment]
That sounds like a double fault in a stage of the crash reporter that it cannot handle a double fault.

**Comment by leculver** [comment]
Ah I get it then.  I think the first error is the first message.  This is what we need to fix: 
 `mono_os_sem_post: semaphore_signal failed with error 15`

While creating a MERP error report, we likely tried to take a semaphore, which failed due to the reason the process is crashing to begin with.

While processing _that_ SIGABRT (or whatever g_error does), we tried to go down the MERP path again, hitting the second assert in log_transition because we were already processing the previous one.

The issue here is we shouldn't be taking the semaphore in MERP reporting because it might be held by a dead thread (or dead semaphore in this case?).  Or some other way to avoid this issue.

**Comment by alexischr** [comment]
@leculver Do you happen to have any reproduction steps for this issue? And am I reading this right in that this happens on _any_ native crash?

**Comment by leculver** [comment]
@alexischr Unfortunately I don't have any repro steps, this is only information I learned when reading through crash logs from some random person's VS for Mac logs folder.  I also don't think it happens on _any_ native crash...

I was out sick most of last week, let me dig in some this week and see if I can find more info.

**Comment by alexischr** [comment]
Starting with https://github.com/mono/mono/pull/17537, this scenario should no longer be possible, as the process is only allowed to enter 'dump mode' once, and entering dump mode is always done before running any MERP code. The `mono_os_sem_post: semaphore_signal failed with error 15` error is also most probably a consequence of MERP code getting running concurrently with itself.

Will close this issue as this should no longer be coming from VS4Mac/Mono environments that include the above change.
