### ISSUE TITLE
Crash in FileSystemWatcher processing code

### ISSUE THREAD

**Issue by Therzok** [mono/mono#15575]
## Steps to Reproduce

No repro steps available, see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/916147

### Current Behavior
Crash in FSW processing code

### Expected Behavior
No crash.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
5.18.1.28 (15), 6.0.0.296 (6), 6.0.0.283 (4), 5.18.1.24 (2)

## Stacktrace

```
System.ThrowHelper.ThrowArgumentOutOfRangeException()
System.IO.CoreFX.FileSystemWatcher.RunningInstance.ProcessEvents(Int32,Byte**,FSEventStreamEventFlags[],UInt64[],FileSystemWatcher)
System.IO.CoreFX.FileSystemWatcher.RunningInstance.<>c__XXX.<FileSystemEventCallback>b__XXX(Object)
System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object)
System.IO.CoreFX.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr,IntPtr,IntPtr,Byte**,FSEventStreamEventFlags[],UInt64[])
System.IO.CoreFX.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.WatchForFileSystemEventsThreadStart(Object)
System.Threading.ThreadHelper.ThreadStart_Context(Object)
System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object,Boolean)
System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object)
System.Threading.ThreadHelper.ThreadStart(Object)
```

**Comment by steveisok** [comment]
@alexischr Can you think of a reason why this happens?  If it's out of bounds on an array, the two passed in to the function are the only candidates I see.

**Comment by marek-safar** [comment]
We should at least throw a better exception

**Comment by slluis** [comment]
FYI, this is the 3rd top crash in VS for Mac 8.2.

**Comment by steveisok** [comment]
@alexischr Please take a closer look

**Comment by slluis** [comment]
Reopening since the crash is still happening.

See https://github.com/xamarin/md-addins/pull/5159. Two test stages failed with the System.ArgumentOutOfRangeException exception in the file watcher. 

Logs are here: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=411604&_a=release-environment-logs&environmentId=1972738
