### ISSUE TITLE
Crash in HttpConnection.SendAsync

### ISSUE THREAD

**Issue by Therzok** [mono/mono#15672]
## Steps to Reproduce

1. N/A - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943490

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

6.0.0.296 (13), 6.0.0.302 (1)

## Stacktrace

```

14 hits

System.Net.Http.HttpConnection.<SendAsyncCore>d__XXX.MoveNext()
```

**Comment by steveisok** [comment]
@baulig Please have a look

**Comment by steveisok** [comment]
@Therzok The underlying AZDO issue is marked resolved.

@baulig Please indicate if you think https://github.com/mono/corefx/pull/312 (backported into 2019-06) is enough to close this issue.

**Comment by Therzok** [comment]
> @Therzok The underlying AZDO issue is marked resolved.

We've added a try/catch around what we think is the failing code. Hopefully it should prevent us crashing, but it can definitely surface in other areas depending on the usage of the API.

**Comment by steveisok** [comment]
I also think https://github.com/mono/mono/pull/15947 is going to help.  I'm going to close since you have a fix on your end and we pushed a few changes.  Should the crash reappear, please reopen.
