### ISSUE TITLE
There is something weird with the GC

### ISSUE THREAD

**Issue by mattleibow** [mono/mono#15688]
## Steps to Reproduce

1. Download and run these unit tests (https://github.com/mattleibow/TestingMonoGC)

### Current Behavior

The .NET Core tests pass, and mono ones do not. They are the same code.

### Expected Behavior

Both projects should pass.

## On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 6.0.0.311 (2019-02/494641b300c Mon Jul  1 20:30:26 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```

## Stacktrace

No stack trace as this is not a crash.

**Comment by mattleibow** [comment]
Crazy thing, if I add a line  to return `return new WeakReference("");`, then it passes:

https://github.com/mattleibow/TestingMonoGC/blob/master/TestingGarbage/Program.cs#L21-L27

**Comment by EgorBo** [comment]
Probably can be explained in https://github.com/dotnet/corefx/pull/37358#discussion_r280442394

**Comment by SamMonoRT** [comment]
@BrzVlad - please can you verify if this is working as expected

**Comment by mattleibow** [comment]
What is also interesting is that the return type seems to influence how the GC runs. Is there an actual reason? I ran the tests a few times with the same result.

**Comment by BrzVlad** [comment]
As Egor mentioned this is not fixable unless we have precise scanning for references. Either the test is tweaked to work with mono (which I doubt if it is in corefx), or disabled

**Comment by mattleibow** [comment]
Thanks for the confirmation, adjusting my tests.
