### ISSUE TITLE
Unable to install MSBuild dependency when installing mono-complete on Ubuntu 19.04

### ISSUE THREAD

**Issue by NathanHannon** [mono/mono#15709]
## Steps to Reproduce

1. sudo apt install mono-complete
2. Get dpkg error: dpkg: error processing archive /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+ubuntu1804b1_all.deb (--unpack):
 trying to overwrite '/usr/lib/mono/msbuild/15.0', which is also in package mono-roslyn 5.20.1.19-0xamarin2+ubuntu1804b1
Selecting previously unselected package mono-complete.
Preparing to unpack .../mono-complete_5.20.1.19-0xamarin2+ubuntu1804b1_amd64.deb ...
Unpacking mono-complete (5.20.1.19-0xamarin2+ubuntu1804b1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+ubuntu1804b1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

### Current Behavior

fails to install msbuild, and thus all of mono-complete

### Expected Behavior

Expected Mono to install.

## On which platforms did you notice this

[ ] macOS
[*] Linux
[ ] Windows

**Version Used**: Mono Stable  5.20.1

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by enricoreich** [comment]
Same problem on Debian Stretch 9.9

```
> apt install msbuild
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  msbuild
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
Need to get 0 B/6.924 kB of archives.
After this operation, 41,9 MB of additional disk space will be used.
(Reading database ... 36301 files and directories currently installed.)
Preparing to unpack .../msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1_all.deb ...
Unpacking msbuild (1:16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1) ...
dpkg: error processing archive /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1_all.deb (--unpack):
 trying to overwrite '/usr/lib/mono/msbuild/15.0', which is also in package mono-roslyn 5.20.1.19-0xamarin2+debian9b1
Errors were encountered while processing:
 /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by NathanHannon** [comment]
> Same problem on Debian Stretch 9.9
> 
> ```
> > apt install msbuild
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following NEW packages will be installed:
>   msbuild
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> 2 not fully installed or removed.
> Need to get 0 B/6.924 kB of archives.
> After this operation, 41,9 MB of additional disk space will be used.
> (Reading database ... 36301 files and directories currently installed.)
> Preparing to unpack .../msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1_all.deb ...
> Unpacking msbuild (1:16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1) ...
> dpkg: error processing archive /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1_all.deb (--unpack):
>  trying to overwrite '/usr/lib/mono/msbuild/15.0', which is also in package mono-roslyn 5.20.1.19-0xamarin2+debian9b1
> Errors were encountered while processing:
>  /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+debian9b1_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

My Workaround for Ubuntu was just to install 5.18 from the Ubuntu Repos. There's a way to install older versions for Debian: https://www.mono-project.com/docs/getting-started/install/linux/#accessing-older-releases

**Comment by djrm05** [comment]
Same error in ubuntu 18.02

**Comment by marek-safar** [comment]
@directhex any thoughts on this?

**Comment by enricoreich** [comment]
Thank you @NathanHannon for the hint. It works.
Now, I guess, we have to wait until the team fixed the broken thing.

**Comment by Sanaki** [comment]
Same on Mint 19. This has made a mess.

**Comment by NathanHannon** [comment]
The Ubuntu version of mono doesn't work with Jetbrains rider... so much for that workaround

**Comment by CoffeeFlux** [comment]
I believe there are some issues with msbuild as a result of a directory being moved with 16, but it's known and being worked on.

**Comment by MattL0** [comment]
any news ??

**Comment by chenzhekl** [comment]
The same on Ubuntu 18.04 when installing `mono-devel`

**Comment by MattL0** [comment]
what worked here : 

-removed mono package 

-Completly removed all trace of mono on my system ( each file with xamarin, mono or msbuild in it).

-installed the ppa file

- installed msbuild first. 

-rerun the mono install

**Comment by RamaSpaceShip** [comment]
I got the same error when updating:
- Debian Buster Amd64
- Raspbian 10 
Reinstalling mono is not an option now as it will take hours (on summer times, my internet bandwith is quite low)

**Comment by privatesam** [comment]
Same problem on Raspbian 9 tried some other solutions I found but no dice:

`sudo dpkg -i --force-depends /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+raspbian9b1_all.deb
(Reading database ... 60508 files and directories currently installed.)
Preparing to unpack .../msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+raspbian9b1_all.deb ...
Unpacking msbuild (1:16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+raspbian9b1) ...
dpkg: error processing archive /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+raspbian9b1_all.deb (--install):
 trying to overwrite '/usr/lib/mono/msbuild/15.0', which is also in package mono-roslyn 5.20.1.19-0xamarin2+raspbian9b1
Errors were encountered while processing:
 /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+raspbian9b1_all.deb
`

**Comment by Konard** [comment]
Same problem with Travis CI:
```
Errors were encountered while processing:
 /var/cache/apt/archives/msbuild_1%3a16.0+xamarinxplat.2019.05.07.15.32-0xamarin2+ubuntu1604b1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .
```
Full log at: https://travis-ci.org/Konard/LinksPlatform/builds/559646783

**Comment by directhex** [comment]
Apologies to all.

Quoting from my social media last night:

> Mono `stable` and `vs` repos might be mildly fucky for a few hours. This is largely due to backporting MSBuild 16 there, which moves directories around in a way which requires multiple package rebuilds in tandem.
>
> RHEL `vs` is fixed. Debian/Ubuntu `vs` and `stable`, and RHEL `stable`, are screwed until an updated Mono package lands. Apologies! My packaging pipeline doesn't support multiple packages publishing at once, and that caused the situation
>
> As a rule, RPM fixes are quick once I know the problem, because I only build 4 times (RHEL6 i386, RHEL 6/7/8 amd64) on fast Azure VMs. Debian/Ubuntu builds happen 24 times across currently supported releases/arches. And ARM is slow!
>
> Oh, and the pipeline is *intentionally* brittle in places, in that if any of those 24 builds fails, the whole build will not publish. If an ARM server glitches, the build fails.
>
> Meanwhile, `preview` and `nightly` now support Debian & Raspbian 10 (buster). I intend to add buster support to `stable` by the end of the week.
>
> RHEL `stable` fix is published. Debian/Ubuntu is close to finished.
>
> "close" in this context means "the `vs` build is only blocking on the Raspbian 9 build, which is very likely to succeed and publish within 2 or 3 hours"
> The `stable` build is less close to finished.

Annoyingly, replacing a directory with a symlink, when that directory has files written to it from binary packages produced by multiple source packages, is the singular most difficult thing to express in either RPM or Debian packaging metadata. Changes were needed to `msbuild`, `mono` and `core-setup` all together.

In the end, the raspbian builds took _9.5 hours_, rather than the more usual 2 or 3, which is why the fixed packages took so long to publish.

5.20.1.34 published to `stable` at 5:50am Boston time (about 4 hours ago)

5.18.1.28 published to `vs` at 4:35am Boston time (about 5 hours ago)

**Comment by 440z** [comment]
why is it closed but not  solved  ?!?!?
same problem on rasperian os
