### ISSUE TITLE
WebAssembly build fails when using System.IO.Packaging

### ISSUE THREAD

**Issue by jfizz** [mono/mono#15714]
## Steps to Reproduce

1. create `sample.cs` file using `System.IO.Packaging`
2. compile with
```
csc /target:library -out:sample.dll /noconfig /nostdlib /r:$WASM_SDK/wasm-bcl/wasm/mscorlib.dll /r:$WASM_SDK/wasm-bcl/wasm/System.dll /r:$WASM_SDK/wasm-bcl/wasm/System.Core.dll /r:$WASM_SDK/wasm-bcl/wasm/Facades/System.IO.dll /r:$WASM_SDK/wasm-bcl/wasm/Facades/netstandard.dll /r:$WASM_SDK/wasm-bcl/wasm/System.Net.Http.dll /r:$WASM_SDK/framework/WebAssembly.Bindings.dll /r:$WASM_SDK/framework/WebAssembly.Net.Http.dll sample.cs
```

### Current Behavior
Error
```
The type or namespace name 'Packaging' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)
```

### Expected Behavior
No error

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] WebAssembly

**Version Used**:
mono-wasm
3316/ubuntu-1804-amd64/sdks/wasm/mono-wasm-43f1a268045.zip
mono --version
5.20.1.19

Maybe I am missing a reference flag? However, I don't see a ref for System.IO.Packaging in `$WASM_SDK/wasm-bcl/wasm/`.

**Comment by marek-safar** [comment]
You need to add System.IO.Packaging nuget to get access to Packaging
