### ISSUE TITLE
Cannot use RoslynCodeTaskFactory with MSBuild

### ISSUE THREAD

**Issue by mrward** [mono/mono#15711]
Originally posted on Developer Community:

https://developercommunity.visualstudio.com/content/problem/641636/roslyncodetaskfactory-does-not-work.html

## Steps to Reproduce

1. msbuild test.proj

test.proj contents:

```
<Project ToolsVersion="4.0" DefaultTargets="TestBuild" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<!-- Works -->
<UsingTask TaskName="Hello" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll" >
  <ParameterGroup />
  <Task>
    <Code Type="Fragment" Language="cs">
      Log.LogMessage("Hello, CodeTaskFactory world!", MessageImportance.High);
    </Code>
  </Task>
</UsingTask>
<!-- Does not work -->
<UsingTask TaskName="Hello2" TaskFactory="RoslynCodeTaskFactory"
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
  <ParameterGroup />
  <Task>
<Reference Include="mscorlib" />
    <Code Type="Fragment" Language="cs">
      Log.LogMessage("Hello, RoslynCodeTaskFactory world!", MessageImportance.High);
    </Code>
  </Task>
</UsingTask>
<Target Name="TestBuild">
  <Hello />
  <Hello2 />
</Target>
</Project>
```

CodeTaskFactory works but the RoslynCodeTaskFactory does not.

### Current Behavior

CodeTaskFactory works OK.

RoslynCodeTaskFactory fails with errors:

test.proj(23,3): error MSB3755: Could not find reference "mscorlib". If this reference is required by your code, you may get compilation errors.
test.proj(23,3): error MSB3755: Could not find reference "netstandard". If this reference is required by your code, you may get compilation errors.
test.proj(23,3): error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.

### Expected Behavior

Project should build and RoslynCodeTaskFactory should be used to generate a message written to the console.

On Windows using the VS 2019 developer command prompt - running `msbuild test.proj` you see:

TestBuild:
  Hello, CodeTaskFactory World!
  Hello, RoslynCodeFactory World!

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.0.0.296 (2019-02/1e9f3bfbc5a Wed Jun 12 04:07:25 EDT 2019)

**Comment by paveliak** [comment]
Are there any workarounds? This issue makes Visual Studio for Mac unusable for building projects.

**Comment by marek-safar** [comment]
@radical why is this happening?
