### ISSUE TITLE
[netcore] Implement System.Runtime.Loader.AssemblyDependencyResolver

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#15723]
Is there any reason why we couldn't just import [the CoreCLR definition](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyDependencyResolver.cs) in its entirety?  Looks like it delegates most of the work to a pinvoke into an unmanaged library.

**Comment by filipnavara** [comment]
No reason as far as I can see, looks like the CoreCLR implementation can be moved to shared partition and used in Mono as is.
