### ISSUE TITLE
Unable to add reference to NS2.1 library from Xamarin.Mac app

### ISSUE THREAD

**Issue by Therzok** [mono/mono#15742]
@marek-safar asked me to file a bug against Mono with this.

Given the attached sample below:
[iasyncenumerable.zip](https://github.com/mono/mono/files/3407135/iasyncenumerable.zip)

A user cannot add a reference to a NS2.1 library from a Xamarin.Mac modern app. The attached sample has a .netcore application which can successfully reference it, while Xamarin.Mac says incompatible target framework.

Looking at the [version table](https://github.com/dotnet/standard/blob/master/docs/versions.md), the version matrix for this to be supported is satisfied by my local machine:

```
➜  cat /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version
5.16.0.5
➜  mono --version
Mono JIT compiler version 6.4.0.81 (2019-06/f55e0a671c0 Mon Jul  1 13:17:57 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by Therzok** [comment]
Also, same problem for Xamarin.iOS with 12.16. Don't have new enough Xamarin.Android SDK to test.

**Comment by marek-safar** [comment]
@radical could you please investigate (/cc @lewing)

**Comment by akoeplinger** [comment]
I think this is because the mapping table in NuGet is still mapping us to NS2.0: https://github.com/NuGet/NuGet.Client/blob/3472b01df9577554c536791fc0d848c70a763e4c/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs#L482-L485

**Comment by marek-safar** [comment]
@akoeplinger could you make PR for the fix there?

**Comment by akoeplinger** [comment]
PR is here: https://github.com/NuGet/NuGet.Client/pull/2948

I verified that I can reference the NS2.1 library from the XM project after I replaced the NuGet.Frameworks.dll in `/Applications/Visual Studio.app/Contents//Resources/lib/monodevelop/AddIns/MonoDevelop.PackageManagement`.

**Comment by akoeplinger** [comment]
@Therzok the NuGet PR was merged, how do we get this into VSMac? :D

**Comment by Therzok** [comment]
@slluis we need to bump nuget in VSMac.

**Comment by Therzok** [comment]
Should be fixed in master: https://github.com/mono/monodevelop/pull/8527

8.3 pending merge: https://github.com/mono/monodevelop/pull/8528

**Comment by Therzok** [comment]
Thanks for fixing this!
