### ISSUE TITLE
Memory leak in mono 6.0.0.313  for delegates with target that are passed to native code

### ISSUE THREAD

**Issue by MattL0** [mono/mono#15751]
Hi, 

I have tested the 6.x.x.x preview a couple of time. ( first time at 6.0.0.171, and there was already this memory leak!)

I know 5.0.1.34 has been a ''nightmare', and you have my empathy ! I  believe you had to push this version as  the stable one, under the circumstances

But here , i use mono to run Homeseer. So Homeseer is completely dependent of mono to run.

Before 6.x.x.x  the HOMESEER  process was not eating memory like this before. 
after 1 hour , it was  more like 130-140 mo. And could eat 250-275 mo after 1.5-2 days. There was already a small leak on mono 5.x.x.x  (70-80mb/day), but it was nothing compared to now.

I did run my install of HomeSeer on windows for testing  , and there is no memory leak at all. Homeseer  officially support Linux via mono 

  So, now it ( the memory) just keep raising,  How can i track this down?

Thanks 
![Capture](https://user-images.githubusercontent.com/27497561/61498477-6c124700-a991-11e9-897d-133cace5d8ee.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61499002-8ea55f80-a993-11e9-8bbb-929510f0038e.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61499640-f5c41380-a995-11e9-9a11-65602e1cca91.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61499865-b944e780-a996-11e9-9b88-822ce0087aaf.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61500083-b39bd180-a997-11e9-873b-917684771784.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61500636-2312c080-a99a-11e9-8e97-ceae34611463.PNG)

![mono](https://user-images.githubusercontent.com/27497561/61500640-2b6afb80-a99a-11e9-8251-41f4fa85a2a9.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61500732-84d32a80-a99a-11e9-8d56-f96ecc9845e1.PNG)

I send via mqtt, to nodered dashboard ,the memory consumption of hs3 process every 20 minutes

![mono](https://user-images.githubusercontent.com/27497561/61500766-a207f900-a99a-11e9-8026-ca4e718460c0.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61501213-62421100-a99c-11e9-98f1-3b715eebe6d8.PNG)

I send via mqtt, to nodered dashboard ,the memory consumption of hs3 process every 20 minutes.
![mono](https://user-images.githubusercontent.com/27497561/61501224-6b32e280-a99c-11e9-8095-48bc32f6d8ff.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61501324-e09eb300-a99c-11e9-939d-69a6d0372ed7.PNG)

I send via mqtt, to nodered dashboard ,the memory consumption of hs3 process every 20 minutes.

![mono](https://user-images.githubusercontent.com/27497561/61501329-e5fbfd80-a99c-11e9-8deb-a5a0d6b1a08b.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61502111-77b93a00-a9a0-11e9-9cf5-dbfa909e73a7.PNG)

I am sending every 20 mins  via mqtt, HOMESEER memory usage to Nodered dashboard ui. 


![mono](https://user-images.githubusercontent.com/27497561/61502160-b0591380-a9a0-11e9-90c0-93f07a3f30b4.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61502819-6f163300-a9a3-11e9-9dd2-7a2b9ca2079e.PNG)

I am sending every 20 mins via mqtt, HOMESEER memory usage to Nodered dashboard ui.

![mono](https://user-images.githubusercontent.com/27497561/61502834-789f9b00-a9a3-11e9-9b28-7c3fc6dd2016.PNG)

**Comment by MattL0** [comment]
Here I have downgrade the the VS build  mono 5.18.0.28. 

will post again tomorrow
![Capture](https://user-images.githubusercontent.com/27497561/61506756-31b8a200-a9b1-11e9-8cf4-bbdb1beb826a.PNG)
..

**Comment by MattL0** [comment]
Here I have downgraded to the VS build  mono 5.18.0.28. 

will post again tomorrow
![Capture](https://user-images.githubusercontent.com/27497561/61507887-983fbf00-a9b5-11e9-9377-cbd9d2a9ef11.PNG)

**Comment by MattL0** [comment]
![Capture](https://user-images.githubusercontent.com/27497561/61566832-67aa6480-aa4b-11e9-8f92-820fe5c37476.PNG)

as you can see, there seems to be a memory leak, but not as big as on mono 6.0.0.313

**Comment by MattL0** [comment]
Anyone? there must have been a change in mono 6 x.x.x.x concerning memory? This is with the exact same setup

**Comment by marek-safar** [comment]
There has been a lot of changes for that reason it's not trivial to confirm this. Could you share with some any repro we could use to see the memory leak?

**Comment by MattL0** [comment]
Thanks,

The only thing you could do to reproduce is to get a homeseer system running under mono ?


Is there anything i can send you and there here so i can send you logs?

**Comment by MattL0** [comment]
This is a link to download HomeSeer for Linux : http://homeseer.com/updates3/hs3_linux_3_0_0_534.tar.gz


Here is a procedure : 
https://forums.homeseer.com/forum/homeseer-products-services/system-software-controllers/hs3-hs3pro-software/hs3-pro-beta-releases/77288-hs3-linux-installation-instructions



You will nedd to get a 30 day free trial key  here : https://shop.homeseer.com/collections/smart-home-software/products/hs3pro-trial  you will receive credential by email.


finally please install all the plugin i have like in the picture from this tab Your_IP:Port/interfaces : 

![Capture](https://user-images.githubusercontent.com/27497561/61665240-7fc7f100-aca2-11e9-8af4-d194f68f781a.PNG)

**Comment by MattL0** [comment]
to find the plugin click on the yellow triangle at the bottom '' additional interfaces''. Some can be in the beta section

**Comment by MattL0** [comment]
Mcsmqtt , and Jowihue plugin are the two major contributor the the homeseer memory leak here . I guess you can install two 2 plugin only on top of hs3 install.

**Comment by MattL0** [comment]
Hi @marek-safar , I have prepared a Virtual machine for your with vm ware. 

Installed mono 6.0.0.313.

Loaded my config on it but removed as much as i can my  personal info. I have loaded a 30 days trial with it. 

1. Run it on vmware 
2. username : root
3. password : 1234567
4. cd /HomeSeer
 5. then run ./HSConsole.exe --log ( if you close this homeseer will close ( you can add a systemd service, but you won't see the detailed log like that )

6. to access the web interface go to your navigator :  Machine_ip:80 


Do you have an email I can send the link to ?

**Comment by MattL0** [comment]
The link is ready. Just need an email address to sent it to you.

**Comment by BrzVlad** [comment]
@MattL0 I could take a look at this. vlbrez@microsoft.com

**Comment by MattL0** [comment]
Thanks @BrzVlad Sent you the link via email .

**Comment by MattL0** [comment]
Hi thanks a lot for this !

I have tested mono 6.0.0.319 binary ( precompiled with llvm I think) and it still leaks.
![htop](https://user-images.githubusercontent.com/27497561/62827908-3cc5b300-bba8-11e9-87ef-a0d5180adbf2.PNG)


I have compiled mono 6.7 ( without llvm compilation since i was not able to use it see : https://github.com/mono/mono/issues/16099)   yesterday and it does not leak. I think it is leaking but way less. This is something that was present in mono 5.x.x.x.


![htop2](https://user-images.githubusercontent.com/27497561/62827915-6c74bb00-bba8-11e9-8395-6d61ed61d7f9.PNG)

Mono JIT compiler version 6.7.0 (master/b52830cf112 Fri 09 Aug 2019 04:58:30 PM EDT)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)


Would it be possible to test the Virtual machine again?

thanks.

**Comment by MattL0** [comment]
@BrzVlad

**Comment by MattL0** [comment]
@marek-safar @BrzVald please reopen.

Thanks

**Comment by AllHailJ** [comment]
While @ MattL0 is moving I am watching.  the 6.7.0.99 nightly build worked nearly perfect.  I upgrade to .105 and the nightly build was not allowing the z-wave module to function (could not turn on/off devices).

**Comment by MattL0** [comment]
Why is this issue closed ? Thanks

**Comment by BrzVlad** [comment]
I ran the repro for almost two days and I didn't see any unreasonable increases in memory consumption / leaks.

The small leak is fixed by https://github.com/mono/mono/commit/e49be5b9ec63e526d6bec04a957cbe48753b651b

**Comment by MattL0** [comment]
Thanks @BrzVlad
