### ISSUE TITLE
Mac Download doesn't work

### ISSUE THREAD

**Issue by dkids** [mono/mono#15762]
URL: https://download.mono-project.com/archive/6.0.0/macos-10-universal/http://download.mono-project.com/archive/6.0.0/macos-10-universal/MonoFramework-MDK-6.0.0.313.macos10.xamarin.universal.pkg

Not Found

The requested URL /archive/6.0.0/macos-10-universal/http:/download.mono-project.com/archive/6.0.0/macos-10-universal/MonoFramework-MDK-6.0.0.313.macos10.xamarin.universal.pkg was not found on this server.
Apache/2.4.29 (Ubuntu) Server at download.mono-project.com Port 443

I'd have reported this to the webmaster but I can't find anywhere on the site to do that.

**Comment by directhex** [comment]
Fixed

**Comment by akoeplinger** [comment]
Thanks for the report, as Jo mentioned it should be fixed now after a refresh of the website 😄

Filing an issue here is fine, or on the website's GitHub repo: https://github.com/mono/website
