### ISSUE TITLE
broken after update to V.6.0.0 on Linux

### ISSUE THREAD

**Issue by Rude-Boy** [mono/mono#15764]
## Steps to Reproduce

1. old version 5.xx installed
2. updating to the latest Mono release 6.0.0

### Current Behavior
i had an old version of Mono and i needed the latest release because of a bug. I tried to install it following the instructions:
https://www.mono-project.com/download/stable/#download-lin
now there are 3 updates left:
ca-certificates-mono
cli-common
libmono-btls-interface4.0-cil
Mono is not working anymore

when i do "sudo apt-get upgrade" i get
[upgrade.txt](https://github.com/mono/mono/files/3412528/upgrade.txt)

when i do "sudo apt --fix-broken install" i get
[fix-broken install.txt](https://github.com/mono/mono/files/3412529/fix-broken.install.txt)

### Expected Behavior

no updates left
Mono is working

## On which platforms did you notice this

[ ] macOS
[x] Linux Kubuntu 19.04
[ ] Windows

**Version Used**:

6.00

## Stacktrace

```
i dont kow what a Stacktrace is, but if you tell me how to do it, I'll upload it. 
```

**Comment by MattL0** [comment]
Updating mono is a pain. 

Try these these step :

https://askubuntu.com/questions/644938/how-to-completely-remove-mono


The last post is usefull if you have a broken install like here .

**Comment by Rude-Boy** [comment]
yep, that helped. Thank you!
