### ISSUE TITLE
what ref and out type declaration at internal call?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#15800]
I have confused that when I use ref or out keyword in c# side, What is type declaration in c++ side, and is there difference between the value types(int, struct) and class type?

The c# code
```c#
struct FVector
{
int x;
int y;
}
class FObject
{
int X;
}

public external static void TestStructRef(ref FVector Value)
public external static void TestStructOut(out Fecrotr Value)
public external static void TestStructRef(ref FObject Value)
public external static void TestStructOut(out FObject Value)

```

The c++ code 
```c++
struct FVector
{
int x;
int y;
}

Is the internal call argument type declaration corretly?

static void TestStructRef(FVector& Value)
static void TestStructOut(Fecrotr* Value)
static void TestStructRef(FObject& Value)
static void TestStructOut(FObject* Value)
```

**Comment by lambdageek** [comment]
All functions should be `extern "C"` on the unmanaged side.

Both `ref` and `out` valuetypes are just passed by address: `static void TestStructRef (FVector *value)`.

For reference types the argument is passed by address of the object: `static void TestObjectRef (FObject **value)`.

The difference between `ref` and `out` is semantic: if it's `ref` the struct may have a sensible value on input to the function, if it's `out` there is potentially garbage in the fields until you assign to them.
