### ISSUE TITLE
how can I debug using visual studio with embedded mono?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#15817]
how can I debug using visual studio with embedded mono?
Is there some blog or tutorial?

**Comment by MaximLipnin** [comment]
Please first take a look at these links:
- https://devblogs.microsoft.com/xamarin/debugging-xamarin-mono/
- https://www.mono-project.com/docs/advanced/bcl-debugging/

**Comment by srxqds** [comment]
> Please first take a look at these links:
> 
> * https://devblogs.microsoft.com/xamarin/debugging-xamarin-mono/
> * https://www.mono-project.com/docs/advanced/bcl-debugging/

But there is no .net runtime setting option on windows

**Comment by MaximLipnin** [comment]
You might want to ask about any details in the mono gitter: https://gitter.im/mono/mono
