### ISSUE TITLE
[wasm][sdk] Error referencing System.CodeDom

### ISSUE THREAD

**Issue by kjpou1** [mono/mono#15824]
Hey there,

We're facing a similar issue:

![imagen](https://user-images.githubusercontent.com/1142782/61291529-05453000-a7cf-11e9-95a9-457a35c23d46.png)

Here you can repro it —just build and run, you can serve the web with `xsp4`, for instance:

https://github.com/MarcosCobena/WasmApp1/tree/bug-missing-system-codedom-dll

Our guess comes from System.CodeDom having a small piece bundled with mscorlib.dll (or System.dll), thus doesn't like the incoming System.CodeDom.dll NuGet. Does it make sense? In such case, would there be any workaround or similar to get it working? We're not so much interested in compiling code actually, but it's somewhat used for generating C# on the fly.

Thanks in advance!

—@sescalada & @MarcosCobena

_Originally posted by @MarcosCobena in https://github.com/mono/mono/issues/15404#issuecomment-511781275_

**Comment by kjpou1** [comment]
See issue: https://github.com/mono/mono/issues/15823

**Comment by MarcosCobena** [comment]
Thanks guys! :-)
