### ISSUE TITLE
[wasm][sdk] WasmLinkAssemblies task wrongly uses reference assemblies

### ISSUE THREAD

**Issue by kjpou1** [mono/mono#15823]
Referencing `System.CodeDom` package from the SDK produces the following error.

```
Uncaught (in promise) Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'System.CodeDom, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
    at Object.call_method (mono.js:8687)
    at Object.call_static_method (mono.js:8752)
    at Object.init ((index):105)
    at runtime.js:9
    at mono.js:7981
```

---

The cause of this is that during the `WasmLinkAssemblies` the  resolved references from the msbuild task `ResolveAssemblies` references the `/ref/netstandard2.0` library instead of the actual `/lib/netstandard2.0` library path.

---

Example:

`       _MonoWasmLink:
         Running monolinker from /Users/Jimmy/websharp/projects/mono/sdks/out/wasm-bcl/wasm_tools/monolinker.exe.
         InvokeLinkerUsingMono True
         /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/Jimmy/websharp/projects/mono/sdks/out/wasm-bcl/wasm_tools/monolinker.exe --verbose --exclude-feature remoting --exclude-feature com --exclude-feature etw -c copyused -u copy -p copyused WebAssembly.Bindings -p copyused WebAssembly.Net.Http -p copyused WebAssembly.Net.WebSockets -out bin/Debug/netstandard2.0/managed/ -d /Users/Jimmy/websharp/projects/mono/sdks/out/wasm-bcl/wasm/ -d /Users/Jimmy/websharp/projects/mono/sdks/out/wasm-bcl/wasm/Facades -b True -v True -a /Users/Jimmy/websharp/projects/WasmCoreObjects/WasmCoreObjects/obj/Debug/netstandard2.0/WasmCoreObjects.dll -r /Users/Jimmy/.nuget/packages/system.codedom/4.6.0-preview7.19362.9/ref/netstandard2.0/System.CodeDom.dll -r /Users/Jimmy/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref/System.Drawing.dll -r /Users/Jimmy/.nuget/packages/system.io.packaging/4.5.0/ref/netstandard2.0/System.IO.Packaging.dll -r /Users/Jimmy/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref/System.Web.dll -r /Users/Jimmy/websharp/projects/mono/sdks/wasm/framework/WebAssembly.Bindings.dll -r /Users/Jimmy/websharp/projects/mono/sdks/wasm/framework/WebAssembly.Net.Http.dll -r /Users/Jimmy/websharp/projects/mono/sdks/wasm/framework/WebAssembly.Net.WebSockets.dll -l None `

---

The `System.CodeDom` package and a number of other packages use the same nuget packaging strategy.

    ```
        .
        |--- system.codedom 
            |--- 4.5.0                         
                |--- lib               - Contains the framework library .dlls.
                      |--- net461
                      |--- netstandard2.1
                |--- ref               - Contains the framework reference .dlls. 
                      |--- net461
                      |--- netstandard2.1

    ```

In the `WasmLinkAssemblies` we should be referencing the modules from the `/lib/` instead of the `/ref/`.  Doing this creates an published application that runs correctly.

**Comment by marek-safar** [comment]
I think we had similar issue for SDKs. @radical do you remember if that just mattered passing the right variable to the tool or something else?

**Comment by kjpou1** [comment]
My findings so far on this is that the package references are resolved in the MSBuild [ResolvePackageAssets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs#L205.)

Those are then remapped from [here](https://github.com/dotnet/sdk/blob/ec9f5fc673f798dd6a89c7d11a4e62727837757c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets#L270) to the `RuntimeCopyLocalItems`.

What I did was pass the `RuntimeCopyLocalItems` to the `WasmLinkAssemblies` task and do a remap to the runtime versions.  This works against everything I have thrown at it so far.

Of course this could fail if the nuget has somehow set `copy to local` false maybe but I do not see anything in the code referenced above checking for that.

@radical Do you see anything with the above process?  Or maybe there is a setting I am not familiar with?
