### ISSUE TITLE
Issues with IOMAP on mono 6.0.0.311

### ISSUE THREAD

**Issue by alexeybannov** [mono/mono#15845]
With the release of the new version 6.0.0.311 iomap functionality does not work.
The MONO_IOMAP parameter has no effect.

export MONO_IOMAP=all

[ ] macOS
[x] Linux
[ ] Windows

**Comment by filipnavara** [comment]
This is direct result of https://github.com/mono/mono/issues/7246 / https://github.com/mono/mono/pull/12000. The documentation was not updated but it's no longer supported option and it's unlikely that it will be brought back.

**Comment by uzer-ua** [comment]
Are there any other options? Or do we now have to ensure paths case consistency?

**Comment by akoeplinger** [comment]
You have to ensure paths case consistency as it's not likely we're going to port IOMAP to corefx.

**Comment by AlexRixhardson** [comment]
What is the equivalent replacement for IOMAP now?

How can we now handle different scenarios where case insensitivity is required (e.g. handling different cases in URLs that visitors of mod_mono sites use for the same views?)?

**Comment by akoeplinger** [comment]
You have to handle this at the application layer as there's no similar feature to IOMAP in the corefx code.

**Comment by rogierrietdijk** [comment]
why has the iomap function been removed?
