### ISSUE TITLE
[suggestion] Add a debug option to the GC to dump the global gc handles at every collection

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#15885]
For diagnosing issues like https://github.com/mono/mono/issues/15825 it would be helpful if we could set `MONO_GC_DEBUG=print-gchandles` which would be similar to `print-pinning` and would print out a summary of each MonoClass and the number of gchandles of that class, maybe broken down by gchandle type.
Something like:

```
GC Handles
Class                 Count (strong/pinned/weak)
-------------------------------------------------------
System.String                                100/0/100
Program.SomeObject                           1/0/0
Program.OtherObject                          0/0/1
```

**Comment by lewurm** [comment]
I assume this was fixed by #17074 (please re-open otherwise).
