### ISSUE TITLE
Question: Debug spew coming out at mono start

### ISSUE THREAD

**Issue by borgdylan** [mono/mono#15897]
## Steps to Reproduce

1. Run something that uses mono such as msbuild from xplat-master.

### Current Behavior

Three lines starting with "ves_icall_System_Globalization_CultureInfo_internal_get_cultures_raw USED" get printed out on the console as mono starts. Is this supposed to happen or is there an error in my install?

## On which platforms did you notice this

[ ] macOS
[ x] Linux
[ ] Windows

**Version Used**:

master/f1958bacaad

**Comment by jaykrell** [comment]
This will fixed by https://github.com/mono/mono/pull/15862/commits/19e0c58a3812505c33ea25b1539951022584f8fe.

**Comment by jaykrell** [comment]
ps this only regressed a few days ago, People are using daily builds, for better and worse.

**Comment by jaykrell** [comment]
Fix is part of https://github.com/mono/mono/pull/15862.
It isn't a bug. The number is bounded. But it is not intended.

**Comment by akoeplinger** [comment]
#15862 was merged so this should be fixed, please reopen if it still happens.
