### ISSUE TITLE
[bug] internal_call return struct value error.

### ISSUE THREAD

**Issue by srxqds** [mono/mono#15923]
I define three struct FVector2D, FVector3D and FVector4D, but FVector2D return from internal call will be error.

follow are test code:

the c# code
```c#
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace TestCSharp
{

    [StructLayout(LayoutKind.Sequential)]
    public partial struct FVector2D
    {
        public float X;
        public float Y;
    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct FVector3D
    {
        public float X;
        public float Y;
        public float Z;
    }

    [StructLayout(LayoutKind.Sequential)]
    public partial struct FVector4D
    {
        public float X;
        public float Y;
        public float Z;
        public float W;
    }
    public class Main
    {

        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern FVector2D TestReturn2D();
        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern FVector3D TestReturn3D();
        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern FVector4D TestReturn4D();

        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern void TestReturn2DIn(FVector2D In);
        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern void TestReturn3DIn(FVector3D In);
        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern void TestReturn4DIn(FVector4D In);

        public static void Entry()
        {
            TestReturn2DIn(TestReturn2D());
            TestReturn3DIn(TestReturn3D());
            TestReturn4DIn(TestReturn4D());
        }
    }
}
```

the c++ code

```c++
struct FVector2D
{
	/** Vector's X component. */
	float X;

	/** Vector's Y component. */
	float Y;

	FVector2D(float x, float y)
	{
		this->X = x;
		this->Y = y;
	}
};

struct FVector3D
{
	float X;
	float Y;
	float Z;
	FVector3D(float x, float y, float z)
	{
		this->X = x;
		this->Y = y;
		this->Z = z;
	}

};

struct FVector4D
{
	float X;
	float Y;
	float Z;
	float W;
	FVector4D(float x, float y, float z, float w)
	{
		this->X = x;
		this->Y = y;
		this->Z = z;
		this->W = w;
	}
};

FVector2D TestReturn2D()
{
	return FVector2D(1, 0);
}

FVector3D TestReturn3D()
{
	return FVector3D(1, 0, 2);
}

FVector4D TestReturn4D()
{
	return FVector4D(1, 0, 2, 3);
}

void TestReturn2DIn(FVector2D A)
{
	FVector2D B = A;
}

void TestReturn3DIn(FVector3D A)
{
	FVector3D B = A;
}

void TestReturn4DIn(FVector4D A)
{
	FVector4D B = A;
}

int
main(int argc, char* argv[]) {
	MonoDomain* domain = mono_jit_init_version("UnrealMono", "v4.0.30319");
	mono_thread_set_main(mono_thread_current());

	mono_add_internal_call("TestCSharp.Main::TestReturn2D", TestReturn2D);
	mono_add_internal_call("TestCSharp.Main::TestReturn3D", TestReturn3D);
	mono_add_internal_call("TestCSharp.Main::TestReturn4D", TestReturn4D);
	mono_add_internal_call("TestCSharp.Main::TestReturn2DIn", TestReturn2DIn);
	mono_add_internal_call("TestCSharp.Main::TestReturn3DIn", TestReturn3DIn);
	mono_add_internal_call("TestCSharp.Main::TestReturn4DIn", TestReturn4DIn);

	MonoDomain* newDomain = mono_domain_create_appdomain("UnrealDomain", NULL);
	mono_domain_set(newDomain, false);
	MonoImageOpenStatus status;
       // this is my test dll path
	MonoAssembly* firtAssembly = mono_assembly_open("F:\\G111\\client\\TestCSharp\\TestCSharp\\bin\\Debug\\TestCSharp.dll", &status);
	MonoDomain* domainToUnload = mono_domain_get();
	MonoImage* firstImage = mono_assembly_get_image(firtAssembly);
	MonoClass* firstClass = mono_class_from_name(firstImage, "TestCSharp", "Main");
	MonoMethod* firstStaticMethod = mono_class_get_method_from_name(firstClass, "Entry", 0);
	mono_runtime_invoke(firstStaticMethod, NULL, NULL, NULL);

	return 0;
}
```

### Current Behavior

FVector2D value return error

![image](https://user-images.githubusercontent.com/5187024/62183490-fc3a8e00-b38c-11e9-8cba-1941b2f3b3f4.png)

### Expected Behavior

return FVector2D correctly.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:
mono5.20.1.19

**Comment by srxqds** [comment]
@jaykrell dou you know what problem is ?

**Comment by jaykrell** [comment]
What happens if you remove the constructors from the C++?
I understand they serve a purpose and if you remove then you'll have to add something back.

**Comment by srxqds** [comment]
> What happens if you remove the constructors from the C++?
> I understand they serve a purpose and if you remove then you'll have to add something back.
Ok， I will try that remove the constructor, but the FVector3D and FVector4D also have the constructor and they are return correctly.

**Comment by jaykrell** [comment]
Hm, I guess AMD64 does not have HFAs, so it should not matter.
Still maybe worth a quick try.
Maybe a calling convention mismatch.

**Comment by jaykrell** [comment]
This makes sense, I think.
Structs of size 1, 2, 4, 8 can be passed in registers.
So Vector2D is 8 bytes and can be passed in registers.
Adding the constructor though probably takes away that rule, on the C++ side.

**Comment by srxqds** [comment]
> Hm, I guess AMD64 does not have HFAs, so it should not matter.
> Still maybe worth a quick try.
> Maybe a calling convention mismatch.

I remove the constructor from FVector2D, The value return correctly, But What is the exactly reason about it? And how can I fixed with define FVecotor2D constructor

**Comment by jaykrell** [comment]
I gave the reason (out of order, granted). This is surely the correct behavior.
When you duplicate declarations in C++ and C# they have to match.
These don't match, for reasons maybe you cannot tell the compiler.

I dislike this entire scheme of duplicate declarations -- I suggest managed C++ for interop. It can read the headers w/o incorrect duplication.

**Comment by srxqds** [comment]
> I gave the reason (out of order, granted). This is surely the correct behavior.
> When you duplicate declarations in C++ and C# they have to match.
> These don't match, for reasons maybe you cannot tell the compiler.
> 
> I dislike this entire scheme of duplicate declarations -- I suggest managed C++ for interop. It can read the headers w/o incorrect duplication.

Ok， Thank you, How can I do managed c++ for interop?

**Comment by jaykrell** [comment]
You'd have to use coreclr/desktopclr.
You use C++ instead of C#, or between native C++ and C#.
Managed C++ is the only language that can read metadata, write metadata, and read C++ headers.
You end up *not* having to write your types more than once.
You might write code to do extra copies, might. but there is never a mismatch like this. Also the native/managed calls are faster than any other way.
MSDN should have lots of samples and documentation.

**Comment by srxqds** [comment]
> You'd have to use coreclr/desktopclr.
> You use C++ instead of C#, or between native C++ and C#.
> Managed C++ is the only language that can read metadata, write metadata, and read C++ headers.
> You end up _not_ having to write your types more than once.
> You might write code to do extra copies, might. but there is never a mismatch like this. Also the native/managed calls are faster than any other way.
> MSDN should have lots of samples and documentation.

It means It can't do with mono runtime?

**Comment by srxqds** [comment]
@marek-safar 
Is there some solution for us to solve it? The constructor of FVector2 is defined by ue4, we can't modify it. So If we keep the constructor how can can we fixed it?

It is very import for us?
Thank you very much.

**Comment by jaykrell** [comment]
Is there `#ifdef __cplusplus` around the constructor, etc.? i.e. can you include the headers from C code, and then build a small wrapper (LTCG so it inlines)? Otherwise we might need to invent an attribute or something.

Also, while less efficient, you could pass it by `ref` or `out` instead of by value. That will work. That is probably what to do.

I don't see that UE4 is downloadable w/o an additional login so I can't see it easily enough.

**Comment by srxqds** [comment]
> LTCG



> Is there `#ifdef __cplusplus` around the constructor, etc.? i.e. can you include the headers from C code, and then build a small wrapper (LTCG so it inlines)? Otherwise we might need to invent an attribute or something.
> 
> Also, while less efficient, you could pass it by `ref` or `out` instead of by value. That will work. That is probably what to do.
> 
> I don't see that UE4 is downloadable w/o an additional login so I can't see it easily enough.


I found a solution for it.
I redefine a proxy class like FVector2DProxy without constructor:
```c++
struct FVector2DProxy
{
    float X;
    float Y;
   operator FVector2D();
   
};
```

But why "Vector2D is 8 bytes and can be passed in registers and with constructor will get wrong", Can you help me figure it out?

Thank you

**Comment by srxqds** [comment]
> > Is there `#ifdef __cplusplus` around the constructor, etc.? i.e. can you include the headers from C code, and then build a small wrapper (LTCG so it inlines)? Otherwise we might need to invent an attribute or something.
> > Also, while less efficient, you could pass it by `ref` or `out` instead of by value. That will work. That is probably what to do.
> > I don't see that UE4 is downloadable w/o an additional login so I can't see it easily enough.
> 
> I found a solution for it.
> I redefine a proxy class like FVector2DProxy without constructor:
> 
> ```c++
> struct FVector2DProxy
> {
>     float X;
>     float Y;
>    operator FVector2D();
>    
> };
> ```
> 
> But why "Vector2D is 8 bytes and can be passed in registers and with constructor will get wrong", Can you help me figure it out?
> 
> Thank you

**Comment by jaykrell** [comment]
Because that is the calling convention of the compiler.
One is pass by value, the other is pass by reference.

```
C:\s>type 1.cpp

extern "C"
{

struct type1
{
float a,b;
};

struct type2
{
float a,b;
type2() : a(0), b(0) { }
type2(const type2& c) { a = c.a; b = c.b; }
};

void f1(type1);
void f2(type2);

type1 t1;
type2 t2;

void test1() { f1(t1); }
void test2() { f2(t2); }
}

C:\s>cl /c /FAsc /O2 1.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64


C:\s>type 1.cod


test2   PROC
	sub     rsp, 40                   
	movss   xmm0, DWORD PTR t2
	lea     rcx, QWORD PTR $T1[rsp]       ; this is the parameter to f2
	movss   xmm1, DWORD PTR t2+4
	movss   DWORD PTR $T1[rsp], xmm0
	movss   DWORD PTR $T1[rsp+4], xmm1
	call    f2
	add     rsp, 40                   
	ret     0
test2   ENDP


test1   PROC  
	mov     rcx, QWORD PTR t1
	jmp     f1
test1   ENDP
```

**Comment by srxqds** [comment]
@jaykrell Thank you!

**Comment by jaykrell** [comment]
I think an attribute might be nice here btw.
But it'd be obscure.
People wouldn't know when to use it.
It'd be possibly platform and/or CPU specific.
At a high level, it could be "HasCxxConstructor" or "PassLikeCxx" or "IsNotCxxPod", that isn't so obscure, and then Mono would have to know more rules, which aren't all that tricky, really.
