### ISSUE TITLE
key 1 not an armored public key error

### ISSUE THREAD

**Issue by xer-rex** [mono/mono#15955]
the issue happens recently. We have a CI system to build a docker image using mono; however, key 1 not an armored public key error happens recently

## Steps to Reproduce

1. curl -v "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" -okey
2. rpm --import key
3.  console output shows "error: key: key 1 not an armored public key."

### Current Behavior
Failed to Add the Mono repository to your system as described at https://www.mono-project.com/download/stable/#download-lin-centos

### Expected Behavior
Add the Mono repository to your system successfully

## On which platforms did you notice this

[ ] Linux/Centos7

**Comment by stevegoossens** [comment]
This happens to me too:
```
[~]# uname -a
Linux server1-amazinggoose-lan 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

**Comment by marek-safar** [comment]
@directhex any thoughts on this?

**Comment by rkivisto** [comment]
This appears to be due to a missing newline at the end of the key file. If you open the key with vi and save it, without making any changes (this is one way to ensure there is a newline at the end of the file), the import works.

```
curl -v "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" -okey
vi key
# don't modify, just save it with ":wq"
rpm --import key
```

**Comment by rkivisto** [comment]
Another way to add the newline to the end of the file: https://unix.stackexchange.com/a/31955

```
sed -i -e '$a\' key
```

**Comment by directhex** [comment]
I'm super uncomfortable with any solution which involves grabbing the key from some rando service, rather than from the keyserver network. I'll need to assess viable alternatives.

**Comment by directhex** [comment]
Resolved via changing keyserver in the instructions

**Comment by hloeung** [comment]
This happened because we've switched from SKS to hockeypuck. A fix to this landed yesterday and should be rolled out shortly to keyserver.u.c. This will make RPM happy again.
