### ISSUE TITLE
Mono Releases are out of order for appcast

### ISSUE THREAD

**Issue by robertleeblairjr** [mono/mono#15961]
## Steps to Reproduce

1. Visit Releases Page or query appcast reference
2. 6.0.0.311 and 6.0.0.313 are in non-sequential order for release
3. One known problem is that Visual Studio is attempting to pull 6.0.0.311 as the latest release which is incorrect. It should be 6.0.0.313.

### Current Behavior
Update frameworks used by other applications which use the mono framework either notify or will install an older version than the latest, stable.

Incorrect pull of latest, stable version.
### Expected Behavior
As of the date of this submission, the latest stable on releases is 6.0.0.311 and not 6.0.0.313.

The latest, stable version for releases should be in descending order in the build string identifier.
## On which platforms did you notice this

[X] macOS
[X] Linux
[X] Windows

**Version Used**:
6.0.0.313

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by directhex** [comment]
Sorry, what page isn't working? URL please?

**Comment by directhex** [comment]
GH releases page just shows tag in order creation date. We don't control the ordering on the page, and sometimes tags are legit created out of order.
