### ISSUE TITLE
 error CS0246

### ISSUE THREAD

**Issue by Camker46** [mono/mono#15980]
Hi, 

I type 

csc Form1.cs -r:System.Windows.Forms.dll

I then get the following errors

Form1.cs(8,7): error CS0246: The type or namespace name 'Renci' could not be found (are you missing a using directive or an assembly reference?)
Form1.cs(9,7): error CS0246: The type or namespace name 'Renci' could not be found (are you missing a using directive or an assembly reference?)
Form1.cs(427,47): error CS0246: The type or namespace name 'SftpClient' could not be found (are you missing a using directive or an assembly reference?)
Form1.cs(449,42): error CS0246: The type or namespace name 'SftpClient' could not be found (are you missing a using directive or an assembly reference?)
Form1.cs(449,61): error CS0246: The type or namespace name 'SftpFile' could not be found (are you missing a using directive or an assembly reference?)

Yet I have Renci as reference as a namespace

using Renci.SshNet;
using Renci.SshNet.Sftp;

This app compiles fine on Visual studio, yet only when I type csc Form1.cs -r:System.Windows.Forms.dll and try to turn this app into a mono app do I get this error.

I have tried switching the Target framework to various versions of .NET Framework N.N.N to no avail, and it is not set to .Net * Client Profile (which most internet forums seem to suggest checking for CS0246 errors).

Would anyone have any idea why I am getting this errors? 

Note: I have compile a version of the app in Mono successfully once before.

A month or so has passed, and then all of the sudden it seems like I cannot compile this app in Mono any more, might this have something to do with time passing and versions of software or something becoming obsolete or something else?

**Comment by marek-safar** [comment]
You need to add an assembly, which implements or exposes Renci namespace as a reference (-r:foo.dll)
