### ISSUE TITLE
[wasm] Safari Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kjpou1** [mono/mono#15981]
Here is a demo https://github.com/jfizz/mono-wasm-safari-issue.
- Download the repo as a zip, unzip, then run `python server.py`
- Go to http://localhost:8000/index.html
- Use the file input to choose `doc.docx` (included in the repo)
- Wait a few seconds for the `Maximum call stack size exceeded`

A few things to note:
- The demo works in Chrome/Firefox/Edge
- The demo worked in Safari when ran outside the worker context (main thread). So maybe the issue is related to Safari Web Workers.
- Oddly, adding a `debugger;` statement in `_mono_wasm_invoke_method` resolved the issue (with the devtools open and breakpoints enabled)

_Originally posted by @jfizz in https://github.com/mono/mono/issues/8374#issuecomment-517119296_

**Comment by kjpou1** [comment]
@jfizz How did you create the worker.js file?

The actual error seems to be coming from using (WordprocessingDocument wDoc = WordprocessingDocument.Open(memoryStream, true)) { inside the code from WordprocessingDocument. Is there any way to actually see what is failing in there?

**Comment by kjpou1** [comment]
Humm, wondering if this is coming from converting the memoryStream byte array to a string within the WordprocessingDocument.

**Comment by jfizz** [comment]
The worker.js file was created by concatenating my custom code (at the top), with `mono-config.js`, `runtime.js`, and `mono.js` which are generated when running `mono $WASM_SDK/packager.exe`.

The source for the line in question can be found here https://github.com/OfficeDev/Open-XML-SDK/blob/master/src/DocumentFormat.OpenXml/Packaging/WordprocessingDocument.cs#L306.

**Comment by kjpou1** [comment]
I have been able to recreate the project here locally from master but not the error.  Can you make sure the project is outputting the correct files.

Using these packages:

```
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.9.1" />
    <PackageReference Include="OpenXmlPowerTools-NetStandard" Version="4.4.21" />
    <PackageReference Include="System.IO.Packaging" Version="4.5.0" />
  </ItemGroup>
```

Both release and debug versions seem to be running correctly.

**Comment by jfizz** [comment]
Using the latest SDK did the trick. Thanks for the help!

**Comment by kjpou1** [comment]
Great to hear!!

**Comment by jfizz** [comment]
Unfortunately, I spoke too soon. The latest sdk fixes the issue for the sample `doc.docx` provided in the repo, but moving to a slightly larger document (still just one page) leads to more `Maximum call stack size exceeded` in Safari.

I have uploaded the failing doc as `doc2.docx` to the repo. Not sure if anything more can be done for Safari. Let me know if I can help.

**Comment by kjpou1** [comment]
I ended up opening a bug for this one:  https://bugs.webkit.org/show_bug.cgi?id=200918

Hopefully they can provide a little assistance.

**Comment by kjpou1** [comment]
I also checked this on mobile safari and it works correctly.  Add that to the comments in the bug opened.

**Comment by Daddoon** [comment]
Just to note that there will be surely a regression with Safari 13 / iOS 13, if Apple doesn't fix their Safari memory problems on their release the 2019/09/19.

I tested with:

- Blazor 3.0.0-preview9.19457.4 (released yesterday, 2019/09/16)
- iOS 13.1 Beta 8
- Blazor sample project

With this configuration, Blazor doesn't start at all.
First error is:

```
Unhandled Promise Rejection: TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.
```

Workarounded by adding:

```javascript
<script>var Module;</script>
```
before the **blazor.webassembly.js** script tag.

Then we fall in:

```
Unhandled Promise Rejection: RangeError: Maximum call stack size exceeded.
```
Unfortunatly, the only way i have found at the moment is to modify **blazor.webassembly.js** file, and add somehow a setTimeout mecanism on line 1707.

[blazor.webassembly.ios13.fix.zip](https://github.com/mono/mono/files/3620747/blazor.webassembly.ios13.fix.zip)

Here my current workaround. With this fix the Blazor startup process will loose 2 seconds at boot time.

Except that, i didn't have fallen in new regression about Network call and Tasking at boot time, at least on my iPad it works. I mean, i tested also with a Task.Delay of 5 seconds and without this, and my app was working on both case.

Will test on iPhone 6s tomorrow.

This is post is just informational. In my opinion, this is mainly a Safari defect.

**Comment by kjpou1** [comment]
@Daddoon Hello Daddoon

This regression is a little different and involves booting emscripten from a worker.  All communications with mono wasm is then handed off to the worker.  This is also not using Blazor but using the WebAssembly bindings.  

Although, your are right about the other regressions.  There has been a PR submitted to rectify the `<script>var Module;</script>` as you pointed out.

**Comment by Kukunin** [comment]
Have the same issue with `ffmpeg.js` and Safari 13. It works fine on Safari 12. Oddly, can confirm, that adding `debugger;` solves the problem.

**Comment by Kukunin** [comment]
Solved for ffmpeg.js by removing a couple of inline attributes. Now, it reports only

```
warning: Output contains some very large functions (4946 lines in _ff_epzs_motion_search), consider building source files with -Os or -Oz)
```

but Safari 13 works fine. This is good evidence that huge functions might cause the problem

**Comment by lewing** [comment]
Should be fixed now
