### ISSUE TITLE
Tiered compilation for Mono runtime

### ISSUE THREAD

**Issue by migueldeicaza** [mono/mono#16018]
This issue is intended to be a location where we can discuss the specifics needed for tiered compilation in Mono.

# Background

Mono today offers two code generation engines, one that produces code very quickly, but performs poorly in various CPU intensive benchmarks and one powered by LLVM that is very slow, but incredibly efficient code.  Additionally, Mono can either just-in-time compile, or ahead-of-time compile.    On the desktop, ahead-of-time compilation is mostly used to reduce startup time, and reduce memory usage, and rarely to produce better code - as AOT code pays a price that JIT code does not pay.  Additionally, AOT can be a slow process.

Mobile users for example use the fast compiler during development, and use LLVM for Release builds.   But desktop users tend to not do this, as the cost of using LLVM for running their applications is too high.

CoreCLR calls the code generated quickly with low quality the Tier0, and the code generated with a higher optimization level Tier1.  It makes sense to embrace the same naming convetion.

One useful scenario to support would be tiered compilation.   One where we use the Mono built-in code generator for the startup sequence, and based on a heuristic that determines just how important a method is, we recompile the code with LLVM.

One specific user that could benefit from this is VSMac, which currently only uses the quick code generator, where using LLVM on startup is deemed too slow.   This would also help the Unity editor ([an example showing Unity](https://tirania.org/blog/archive/2018/Apr-11.html))

# Strategies

Tiered compilation is made up of a couple of pieces:

* Instrumenting the slow code to track candidates to be recompiled.
* Heuristics that determine when a method is suitable for recompilation.
* The actual recompilation changes.
* Redirecting any calls to the original low-quality generated code to the high-quality generated code.

While there are many different approaches for instrumenting the code, and many difference heuristics that can be used, we could start by embracing the current  [heuristics and processes used by the CoreCLR](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/tiered-compilation.md), saving us design and experimentation time.   We could later adjust those parameters to better suit the Mono workloads.

While there are some very advanced use cases for tiered compilation that allow replacements of methods on the stack.   For interactive applications like VSMac, where control goes back to a mainloop to process events, the need to replace live methods is not as important.  Because even the mainloop is ran by unmanaged code.

The CoreCLR implementation replaces methods during a GC pause, ensuring that it can patch existing code without requiring atomic changes.

# Plan

- [x] Implement instrumentation that counts the number of invocations to a method.
- [x] Implement code generation in tier0 compilation that can transfer control to tier1
- [ ] Implement the heuristic/policy to recompile (currently does 100 counts, needs to do some sort of slow start like CoreCLR does)
- [x] Make the tiered buffer dynamic, currently it only tracks 1000 or so methods.
- [x] Implement recompilation machinery
- [ ] Compiler domain-appropriate code (currently we do not switch the domain on recompilation)
- [ ] Make patching code be arch-independent, rather than hardcoding amd64
- [ ] Register rejit thread with runtime
- [ ] Avoid GC pauses, like CoreCLR does, see below for a couple of strategies and links to documents.
- [ ] Should disable tier0 flag if --nollvm is passed.  
- [ ] If tier0 is disabled, probably should not enabled LLVM by default.

# Additional Ideas

The heuristics from CoreCLR might not apply as well to Mono+LLVM, as our LLVM pass is considerably slower than CoreCLR's optimizing pass.   I will make the parameters configurable and try this against different scenarios (in particular, the VSMac startup, which takes around 25-bounces to startup).

* Load average: this is a difficult metric to obtain reliably, but would be useful to determine whether there is additional capacity to reJIT with our slower LLVM while the application is starting up.

* Prioritizing methods to reJIT: Once a set of methods have been identified for recompilation, it might be useful to sort those in a priority list.   We could sort by number of times the method has been invoked (which means that we should keep incrementing the counter).

* Taking number of CPUs into consideration: we could take the number of CPUs for consideration, if there are enough available CPUs, we might want to reduce the time it takes for us to determine that a method should be reJITed.

* We might end up reJITing methods that could have been inlined with a more aggressive optimization, so we could record the calling methods and flag those for recompilation instead.

 # Optimizations

We do not need to stop the world to patch all the targets, as seen on the discussion below, we could patch with a single atomic instruction some of the entry points (see the discussion below) and also update existing vtable slots with the new location.

# Open Questions

* Should we track every call site to a Tier0 method be tracked, so we can directly patch those call sites to the Tier1 method?   Or should we patch the entry point of tier0 to insert a jump to the tier1 method?   This is a balance between memory usage and performance.

**Comment by migueldeicaza** [comment]
Ongoing prototype: https://github.com/migueldeicaza/mono/tree/mono-tiered-compilation

**Comment by noahfalk** [comment]
Coreclr doesn't require a GC pause to update the methods btw, it overwrites one or more function pointers asynchronously.

**Comment by migueldeicaza** [comment]
It works - modulo some bits.   When a method has `save_lmf` set, I do not instrument the method.   Need to move the instrumentation elsewhere so those do not trample each other.

It also has an ugly hardcoded amd64 jump in the middle of the patching code, rather than a cross-platform patch.

@noahfalk - I only did GC pause, because I could swear I read somewhere that this is what CoreCLR did - I should change that to whatever other method CoreCLR is using.   And now that I went to read, I can not find anything.   I must have made that up.

In that case, does CoreCLR keep a list of every call site that did a call the method, or is it using some sort of trampoline for every method, even those that were already compiled?

**Comment by migueldeicaza** [comment]
This is what made me think that CoreCLR paused the GC:

https://github.com/dotnet/coreclr/blob/060c8a228fbe397b4207eaed2aedff7bbbf32586/src/vm/codeversion.cpp#L2250

**Comment by noahfalk** [comment]
Yeah the code is a little sneaky. CoreCLR currently supports three different techniques: JumpStamping, Precodes, and slot backpatching (https://github.com/dotnet/coreclr/blob/master/src/vm/method.hpp#L1187-L1237)

CodeVersionManager has code paths supporting all three options but TieredCompilation never uses JumpStamp, only the last two. JumpStamp is the only technique which requires the GC suspend so by not using it TieredCompilation avoids the GC suspends.

As a quick overview: JumpStamp involves patching a jmp instruction in place of the jitted code prologue, Precodes are dedicated per-method patchable trampolines, and the slot backpatching technique records and updates the locations where function pointers used in indirect calls are stored. Slot backpatching is used for virtual methods or other scenarios where the runtime is already required to use an indirect calling pattern to invoke the method. This eliminates the need to double indirect those calls. For remaining methods that would have been invokable directly we use the Precode technique to insert one layer of indirection.

In the past we've contemplated alternate mechanisms that would allow direct calls with no indirections (presumably via some form of caller backpatching) but we haven't looked at it too deeply. For now we are depending on the compiler to inline non-virtual calls in hot code though we know there are pathological cases where there won't happen.

**Comment by jaykrell** [comment]
@noahfalk How do you ensure the jmp can reach, and is written atomically?
i.e. a direct amd64 jmp is 5 bytes and can reach +- 2GB.
Atomicity could be achieved by leaving 8 bytes of nops and padding the 5 bytes with 3 bytes of nops.

Atomicity and reachability can be achieved via indirection, having it be a jmp through a full pointer and only patching the pointer.
The pointer can initially point right after the jmp, to the "real" start of the function.

You can do both.
The initial instruction could be a 5 byte direct jmp forward, followed by 3 bytes of nop, preceded by 8 byte pointer. Write the pointer then write the instruction.

Or really, in the interest of read only code pages, I'd think best is an indirect jmp through "far away" , on a separate page, but within 2GB, initially pointing right after the jmp.

This way as JIT code pages fill up, make them readonly, and never patch code.

Or is code patching, direct instead of indirect call/jmp, too important for perf, despite writable pages? I work more in native where code inspection and writing are very rare, but function pointers not so rare.

**Comment by noahfalk** [comment]
> How do you ensure the jmp can reach, 

We make some effort to allocate all code within a 2GB region of VM, but failing that we set up a short jmp to a longer jmp.

> and is written atomically?

In the case of JumpStamp if the target doesn't span the machine integer size we can use CompareInterlockedExchange to replace it. If it does span the integer boundary then we can escalate to a full EESuspend, effectively taking a lock.

**Comment by jaykrell** [comment]
The x86/amd64 direct jmp instruction size is nominally 5 bytes. Do you compare exchange 8 instead? Padded with nops or just whatever code bytes follow?
I guess don’t need nops, can be useful code.

Any benchmarking on indirect jmps instead?
I guess no need?

**Comment by jaykrell** [comment]
And what does an unpatched code look like? 5 byte nop? Jmp +0? Presumably 5 byte nop is best/faster but either work.

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/blob/master/Documentation/botr/method-descriptor.md#precode is the design doc for this. It has examples of what the code looks like before/after patch.

Note that this scheme was fine-tuned to minimize private working set of fragile NGen images for x86/x64 around 2005. It suspect that it is sub-optimal in number of ways today:
- We do not have fragile NGen anymore in CoreCLR
- The hardware performance characteristics changed quite a bit since 2005 (e.g. the relative cost of indirect jump)
- We are supporting more platforms than x86/x64 where the tricks that took advantage of specific instruction encodings do not work well.

**Comment by noahfalk** [comment]
Ninja'ed by @jkotas (while he is on vacation no less ;p) but adding this in case it is useful:

> Do you compare exchange 8 instead?

Yep : ) For a little additional detail you can also check out the code starting from: https://github.com/dotnet/coreclr/blob/060c8a228fbe397b4207eaed2aedff7bbbf32586/src/vm/codeversion.cpp#L2250

> I guess don’t need nops, can be useful code.

Yeah, we grab the adjacent bytes as-is, update the subset of those 8 that are needed, then CompExchange the whole 8 bytes.


> Any benchmarking on indirect jmps instead?
I guess no need?

In the past I believe some other developers have looked at call indirect vs call + jmp with patchable target. Results varied based on hardware as you might expect, I think indirect call was concluded to be a little faster typically.

> And what does an unpatched code look like? 5 byte nop? Jmp +0? Presumably 5 byte nop is best/faster but either work.

In the case of JumpStamp the unpatched code is the method's original prologue, then it becomes jmp Precode, then jmp target. The precode in this case is pointing at the Prestub which will generate the next jitted code and then backpatch the JumpStamp to the target.
In the case of Precode patching it starts as jmp Prestub and patches to jmp target. In the case of slot backpatching the slots start off with address of Pretub and then are replaced by native_code_addr.


I found this doc which describes part of Precode backpatching as its used for normal jitting: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/method-descriptor.md 

I'm not sure we have a good doc describing all the different mechanisms - we should probably write one. If it helps here is the PR that added the slot backpatching (https://github.com/dotnet/coreclr/pull/21292)

**Comment by jkotas** [comment]
>  Results varied based on hardware as you might expect, I think indirect call was concluded to be a little faster typically.

Also, it depends on how many indirect calls you got on the hot path. If there is less than 10, the indirect call is faster thanks to indirect call predictor. More than 10 and less than 1000, direct call to direct jump is faster because of the indirect call predictor gets filled in and does not help anymore. More than 1000, the performance becomes equal. L0/L1 caches are filled in and the performance is dominated by cache misses. 10 and 1000 thresholds vary based on hardware.

**Comment by migueldeicaza** [comment]
It looks like tiered compilation has been formally integrated by @BrzVlad closing this version
