### ISSUE TITLE
[netcore] FullAOT does not work 

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#16026]
Currently this codes assumes the existence of `Array.InternalEnumerator` class, which is not present in System.Private.CoreLib:

https://github.com/mono/mono/blob/17b35dc4fc96144e19078a5fca965cb8c4c75805/mono/mini/aot-compiler.c#L5227

**Comment by marek-safar** [comment]
@vargaz could we remove that dependency?

**Comment by vargaz** [comment]
Yes, but we don't need full aot + netcore right now afaik.

**Comment by filipnavara** [comment]
I am setting up dotnet/performance benchmarks runs with Mono/netcore to get some idea about the bottlenecks. I certainly don't need this to be fixed now but I cannot run FullAOT runs before it gets fixed. Then again, I believe the regular AOT runs will keep me busy for a while.

I just wanted to log the issue for future reference.
