### ISSUE TITLE
Transition to official llvm git repo

### ISSUE THREAD

**Issue by vargaz** [mono/mono#16022]
The LLVM project is transitioning to github, to this monorepo:

https://github.com/llvm/llvm-project

We should make a fork of this, push our changes there and switch our submodule to use this repo.

**Comment by vargaz** [comment]
We have a fork here:
https://github.com/mono/llvm-project
The only branch which needs to be ported over from the old repo is 'release_60'.

**Comment by vargaz** [comment]
The commit hashes have changed and llvm is now under the 'llvm' subdir, so the branch cannot simply be merged into the new repo.

**Comment by SamMonoRT** [comment]
@vargaz @imhameed - what are the next steps here ?

**Comment by SamMonoRT** [comment]
@vargaz @imhameed - please update

**Comment by vargaz** [comment]
This is not something that needs to be done, just something which would be nice to have.

**Comment by EgorBo** [comment]
Can be closed now?
