### ISSUE TITLE
IOException: Sharing violation on path ...

### ISSUE THREAD

**Issue by andreysavihin** [mono/mono#16032]
Hello!
I got exception in my code when i try to copy files using FileStream with FileShare parameter.

## Steps to Reproduce

1. create Program.cs file

```
using System;
using System.IO;

namespace FileCopy
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                File.WriteAllText("source.txt", "text");
                var fileStream = new FileStream("source.txt", FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.ReadWrite, 2048, FileOptions.DeleteOnClose);
                File.Copy(fileStream.Name, "target.txt", true);
            }
            catch (Exception e)
            {
                File.WriteAllText("error.txt", e.Message + Environment.NewLine + e.StackTrace);
            }
        }
    }
}
```

2. run build command

`mcs -out:Test.exe Program.cs`

3. execute 

`mono Test.exe`

### Current Behavior

got file error.txt with error & stack trace 
IOException: Sharing violation on path .../source.txt

### Expected Behavior

got file target.txt with "text" content.
file source.txt will be removed, because used FileOptions.DeleteOnClose parameter

[ ] macOS
[x] Linux
[ ] Windows

**Comment by andreysavihin** [comment]
Mono JIT compiler version 6.0.0.313

**Comment by tobiasschulz** [comment]
We are encountering this issue with several customers now. (Xamarin.Android 9.4, Mono 2019-02)

Is there any workaround? How can something like this break?

**Comment by steveisok** [comment]
The first thing I did was look to see if we have a test for this.  *Seems* that we do not.  

I'll take a closer look and let you know.

**Comment by steveisok** [comment]
And I can at least reproduce the same exception in regular mono, so this may be easier to track down.

**Comment by steveisok** [comment]
So it appears before 6.0, File.Copy was more or less a direct line to MonoIO.CopyFile:

https://github.com/mono/mono/blob/3a07bd426d3dae0d9b6c7891e7bb11f487b18484/mcs/class/corlib/System.IO/File.cs#L72-L111

In 6.0, we switched more to CoreFX, which tries to create two FileStreams in order to pass handles into the file copy:

https://github.com/mono/corefx/blob/dbfa00cdb2f6e8423f805f9abffe94665cd5c22f/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs#L41-L59

FileStream in mono then throws an exception when it hits this line:

https://github.com/mono/mono/blob/1f4ac5d767570b5c4c73ce75b6c9c49bfcb5fc56/mcs/class/corlib/System.IO/FileStream.cs#L235-L240

I need to understand a little better why MonoIO.Open fails here to be able to determine what we can do about it.  Definitely smells like a regression.

**Comment by steveisok** [comment]
Info for MonoIO.Open that throws the error:

```
Mono: mono_w32file_create: Opening /Users/steve/Projects/copytest/bin/Debug/source.txt with share 0x1 and access 0x80000000
Mono: share_allows_open: Access mode prevents open: requested share: 0x1, file has access: 0xc0000000
```

**Comment by steveisok** [comment]
I think I see the problem w/ MonoIO.Open at least.  In the example provided:

`var fileStream = new FileStream("source.txt", FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.ReadWrite, 2048, FileOptions.DeleteOnClose);`

Results in Mono opening the file w/ 

```
Mono: mono_w32file_create: Opening /Users/steve/dev/test-branches/TestManyFileWatchers/TestManyFileWatchers/bin/Debug/source.txt with share 0x3 and access 0xc0000000
```

And the File.Copy opens a stream that contains the info in the previous comment.  If you look at the rules we have for opening shared files, I *think* there's an issue when we first open w/ ReadWrite share and follow it up w/ Read.  

https://github.com/mono/mono/blob/ff77b427f4f0c9ef7f926a302564ee239619e471/mono/metadata/w32file-unix.c#L1864-L1875

Notice how we're seeing if file_existing_share == Read || file_existing_share == Write.  It's going to bomb when it's both (0x00000003).

**Comment by brendanzagaeski** [comment]
Internal cross-referencing link for the Microsoft team:

> VS bug [#965685](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/965685)

**Comment by thassin** [comment]
also see: https://github.com/mono/mono/issues/19461
