### ISSUE TITLE
Problem updating mono-core on CentOS7 server

### ISSUE THREAD

**Issue by legrandtimonier1951** [mono/mono#16040]
I can't get mono-core to update on a CentOS7 system without a slew of errors when trying to via the command line. Others having this problem?

## Steps to Reproduce

1. 
2. 
3. 

## On which platforms did you notice this

[ ] macOS
[ ]** Linux
[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by legrandtimonier1951** [comment]
mono-core = 6.0.0.313-0.xamarin.10.epel7
           Available: mono-core-6.0.0.313-0.xamarin.11.epel7.x8
6_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.0.0.313-0.xamarin.11.epel7
           Available: mono-core-6.0.0.313-0.xamarin.12.epel7.x8
6_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.0.0.313-0.xamarin.12.epel7
           Available: mono-core-6.0.0.313-0.xamarin.13.epel7.x8
6_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.0.0.313-0.xamarin.13.epel7
           Available: mono-core-6.0.0.313-0.xamarin.14.epel7.x8
6_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.0.0.313-0.xamarin.14.epel7
           Available: mono-core-6.0.0.316-0.xamarin.1.epel7.x86
_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.0.0.316-0.xamarin.1.epel7
           Available: mono-core-6.4.0.137-0.xamarin.1.epel7.x86
_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.4.0.137-0.xamarin.1.epel7
           Available: mono-core-6.4.0.137-0.xamarin.2.epel7.x86
_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.4.0.137-0.xamarin.2.epel7
           Available: mono-core-6.4.0.142-0.xamarin.1.epel7.x86
_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.4.0.142-0.xamarin.1.epel7
           Available: mono-core-6.4.0.145-0.xamarin.1.epel7.x86
_64 (download.mono-project.com_repo_centos-beta_)
               mono-core = 6.4.0.145-0.xamarin.1.epel7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@mpowr-me gary]#

**Comment by legrandtimonier1951** [comment]
These are the last lines after the fail of mono-core update.

**Comment by marek-safar** [comment]
@directhex any input on this?

**Comment by legrandtimonier1951** [comment]
Hi,

A few minutes after writing my message I managed to fix the problem by
first yum-removing mono-core and mono-devel and then yum-reinstalling. Once
I did this no problem.

Thanks for getting back to me.

Regards
