### ISSUE TITLE
[bug] mono_custom_attrs_get_attr_checked 

### ISSUE THREAD

**Issue by srxqds** [mono/mono#16047]
This is bug of **mono_custom_attrs_get_attr** 
if **ainfo->num_attrs > 0** but the class not **match attr_klass**, then **centry != null*

it will create_custom_attr  

mono-version: mono-5.20.1.19

```c++
MonoObject*
mono_custom_attrs_get_attr_checked (MonoCustomAttrInfo *ainfo, MonoClass *attr_klass, MonoError *error)
{
	int i;
	MonoCustomAttrEntry *centry = NULL;

	g_assert (attr_klass != NULL);

	error_init (error);

	for (i = 0; i < ainfo->num_attrs; ++i) {
		centry = &ainfo->attrs[i];
		if (centry->ctor == NULL)
			continue;
		MonoClass *klass = centry->ctor->klass;
		if (attr_klass == klass || mono_class_is_assignable_from_internal (attr_klass, klass))
			break;
	}
	if (centry == NULL)
		return NULL;

	HANDLE_FUNCTION_ENTER ();
	MonoObjectHandle result = create_custom_attr (ainfo->image, centry->ctor, centry->data, centry->data_size, error);
	HANDLE_FUNCTION_RETURN_OBJ (result);
}
```

**Comment by jaykrell** [comment]
I think I see you point, the code does look suspicious.
After `break;` it should say `centry = NULL`.
Or instead of `break` should have the last three lines of the function.
One subtelty however is if the `if (attr_klass…` line can be true more than once.
At least you want to prefer equality over assignability.
If assignable is true more than once, then what is best?

**Comment by srxqds** [comment]
> I think I see you point, the code does look suspicious.
> After `break;` it should say `centry = NULL`.
> Or instead of `break` should have the last three lines of the function.
> One subtelty however is if the `if (attr_klass…` line can be true more than once.
> At least you want to prefer equality over assignability.
> If assignable is true more than once, then what is best?

Yeah, I think the correct maybe implement below:
```c++
MonoObject*
mono_custom_attrs_get_attr_checked (MonoCustomAttrInfo *ainfo, MonoClass *attr_klass, MonoError *error)
{
	int i;
	MonoCustomAttrEntry *centry = NULL;

	g_assert (attr_klass != NULL);

	error_init (error);

	for (i = 0; i < ainfo->num_attrs; ++i) {
		centry = &ainfo->attrs[i];
		if (centry->ctor == NULL)
			continue;
		MonoClass *klass = centry->ctor->klass;
		if (attr_klass == klass || mono_class_is_assignable_from_internal (attr_klass, klass))
		{
			HANDLE_FUNCTION_ENTER();
			MonoObjectHandle result = create_custom_attr(ainfo->image, centry->ctor, centry->data, centry->data_size, error);
			HANDLE_FUNCTION_RETURN_OBJ(result);
		}
	}
	return NULL;

	
}

```

**Comment by jaykrell** [comment]
Probably I have the sense of it backwards, and that line can only be true once.

**Comment by jaykrell** [comment]
Agreed. I will PR that shortly.
Imho `break` is overused when the logic following the loop can go into the loop, as you have.

**Comment by jaykrell** [comment]
Code looks like the last already in my tree. Huh?

**Comment by srxqds** [comment]
> Code looks like the last already in my tree. Huh?

https://github.com/mono/mono/blob/886c49017470112af1a73034d8951d6ca00b641e/mono/metadata/custom-attrs.c#L1942 
I use mono5.20.1.19 

which version is right?

**Comment by jaykrell** [comment]
Fixed October last year.
https://github.com/mono/mono/pull/10739
commit 5fa2df8b4d4a

**Comment by srxqds** [comment]
> Fixed October last year.
> #10739
> commit [5fa2df8](https://github.com/mono/mono/commit/5fa2df8b4d4a4c5178d1931a780910314f8125f9)

Ok I will try the new version

**Comment by srxqds** [comment]
@jaykrell which is the base branch of the mono-5.20.1.19 ? How can i find it?

**Comment by jaykrell** [comment]
I don't know, sorry.

**Comment by srxqds** [comment]
> I don't know, sorry.

Thank you very much
