### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented.   

### ISSUE THREAD

**Issue by Bereket-G** [mono/mono#16060]
Debuging with mono 

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:
6.0.0

## Stacktrace
```System.NotImplementedException: The method or operation is not implemented.```

``` at System.Web.HttpResponseBase.AddOnSendingHeaders (System.Action`1[T] callback) [0x00000] in /build/mono-6.0.0.313/mcs/class/referencesource/System.Web/Abstractions/HttpResponseBase.cs:298```

**Comment by migueldeicaza** [comment]
This will need a test case, the reason is because something has instantiated `HttpResponseBase` which is an empty outline, and needs to subclass osmething else instead.

**Comment by uguruysal0** [comment]
I still have this issue, can you provide information about how did you solve the problem?

**Comment by heinsk** [comment]
I have the same issue:

**On which platforms did you notice this**

[X ] macOS
[ ] Linux
[ ] Windows

Version Used:
6.0.0.327
**Stacktrace**
System.NotImplementedException: The method or operation is not implemented.
  at System.Web.HttpResponseBase.AddOnSendingHeaders (System.Action`1[T] callback) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Web/Abstractions/HttpResponseBase.cs:298

The exceptions occurs when i trying to run my ASP.NET project.

**Comment by rochapablo** [comment]
Same here on macOS.

**Comment by Bereket-G** [comment]
I am using Rider and trying to run it on debug mode an ASP.NET application...

I solved this issue on by changing the debug setting of Rider.
  **Uncheck  
          [ ] Break on unhandled exceptions**
 
![image](https://user-images.githubusercontent.com/19642322/64149773-81eba680-ce2f-11e9-88ea-a113f15e7de6.png)

**Comment by SalamBhai** [comment]
What is the solution please
