### ISSUE TITLE
macOS hardening DllImport fails

### ISSUE THREAD

**Issue by mikkeljohnsen** [mono/mono#16084]
## Steps to Reproduce

1. Running a hardened app on macOS (Mojave)
2. DllImport of ex "libc" fails.

### Current Behavior

Mono is not detecting that you are running on macOS, an exception DllNotFound is thrown

### Expected Behavior

Mono should be able to use DllImport with "libc", since DYLD_LIBRARY_PATH is dropped in hardened apps. It must be a full path.

## On which platforms did you notice this

[x ] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono 5.20.1.19

## Source

https://github.com/mono/mono/blob/master/mcs/class/System/System/Platform.cs:57
```
		[DllImport ("libc")]
		static extern int uname (IntPtr buf);
```

**Comment by mikkeljohnsen** [comment]
I guess you have to use
'''
<key>com.apple.security.cs.allow-dyld-environment-variables</key>
<true/>
'''

**Comment by akoeplinger** [comment]
Yes this is expected (see also other reports like https://github.com/MonoGame/MonoGame/issues/6816).

You need to add the entitlements mentioned in https://github.com/mono/mono/issues/15333#issuecomment-514997034 when `codesign`'ing your mono binary if you're not using the Mono from the .pkg installer we ship.

**Comment by marek-safar** [comment]
@akoeplinger I think it'd be useful to have mono-project page with required steps for this

**Comment by akoeplinger** [comment]
@marek-safar sure, any suggestion where?

**Comment by marek-safar** [comment]
@akoeplinger perhaps add a new section under https://www.mono-project.com/docs/#advanced-topics
