### ISSUE TITLE
What tools are available for analyzing log profiler output?

### ISSUE THREAD

**Issue by omfgicbf** [mono/mono#16102]
The Ubuntu [mono-profiler](https://packages.ubuntu.com/bionic/mono-profiler) package (which seems to be required for operating the log profiler) includes the `emveepee`, `mprof-decoder` and `mprof-heap-viewer` GUI tools, however, none of these appear to read profile logs from recent versions of Mono.

https://github.com/mono/emveepee has been archived and has had no updates for 10 years. I assume this version would not work per the above.

The current [Mono docs](https://www.mono-project.com/docs/) lists "[HeapShot](https://www.mono-project.com/docs/debug+profile/profile/heapshot/)", however, that page says "This page is likely outdated", and redirects you back to the same docs page.

The last update to https://github.com/mono/heap-shot in Jan 2018, was to add "WARNING: This tool has been deprecated and is not actively maintained." to the README.

Are there any current tools (other than `mprof-report`) for analysing log profiler output?

**Comment by alexrp** [comment]
There is `mprof-report` and the [Xamarin Profiler](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=windows). I'm not aware of any other tools that can read output from recent log profiler versions.

**Comment by omfgicbf** [comment]
Thank you @alexrp.
