### ISSUE TITLE
cannot import Centos 7 key

### ISSUE THREAD

**Issue by deusoz** [mono/mono#16101]
Centos 7 VPS Solaris OpenVZ Kernel 2.6

Cannot install key

 Steps to Reproduce

1. rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

### Current Behavior
error: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF: key 1 not an armored public key.

### Expected Behavior

no error, why is it saying key is "not an armored public key" ?

[ ] Linux

**Comment by deusoz** [comment]
Also tried from a different VPS at Ionos Host with Centos 7 and kernel 3.1... 
Same error

**Comment by stevegoossens** [comment]
I imported the `xamarin.gpg` key as a workaround in #16025

**Comment by akoeplinger** [comment]
Actually this is a duplicate of https://github.com/mono/mono/issues/16025 so let's discuss over there.
