### ISSUE TITLE
mono_method_invoke usage

### ISSUE THREAD

**Issue by SindelarPetr** [mono/mono#16113]
Hello, we are currently looking for a way to call methods of .NET object instances from javascript. We found a method "mono_method_invoke" which should do exactly what we need to. The problem is that there is no documentation for the usage of the method so we have no idea what parameters to provide.

Would you please help us with this issue? An example would help a lot.

Thanks a lot for your time and working on this project.

**Comment by migueldeicaza** [comment]
You can find a walk through here:

https://www.mono-project.com/docs/advanced/embedding/
