### ISSUE TITLE
Update Mono Synology

### ISSUE THREAD

**Issue by Durschti** [mono/mono#16117]
## Steps to Reproduce

1. 
2. 
3. 

### Current Behavior

4.6.2 have problems with http.
Can you update mono on synology?

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
@directhex do you know who did packaging for synology?

**Comment by directhex** [comment]
No idea, sorry. It's not us.
