### ISSUE TITLE
Package `mono-runtime-common 6.0.0.319` is broken in `debian stretch`

### ISSUE THREAD

**Issue by codekandis** [mono/mono#16110]
## Steps to Reproduce

1. OS: `Linux 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-4~bpo9+1 (2019-06-19) GNU/Linux`
2. Update package `ca-certificates-mono (5.18.1.28-0xamarin5+debian9b1)`, which depends on `/usr/lib/libmono-system-native.so` to `ca-certificates-mono (6.0.0.319-0xamarin1+debian9b1)`
3. `/usr/lib/libmono-system-native.so` is missing, while it's installed with `mono-runtime-common (5.18.0.240+dfsg-3)` in `Debian Buster`
  - **`buster`** https://packages.debian.org/search?suite=buster&arch=amd64&mode=exactfilename&searchon=contents&keywords=libmono-system-native.so
    Refs:
  - **`stretch`** https://packages.debian.org/search?suite=stretch&arch=amd64&mode=exactfilename&searchon=contents&keywords=libmono-system-native.so
  - **`stretch-updates`** https://packages.debian.org/search?suite=stretch-updates&arch=amd64&mode=exactfilename&searchon=contents&keywords=libmono-system-native.so
  - **`stretch-backports`** https://packages.debian.org/search?suite=stretch-backports&arch=amd64&mode=exactfilename&searchon=contents&keywords=libmono-system-native.so
  - **`stretch-backports-sloppy`** https://packages.debian.org/search?suite=stretch-backports-sloppy&arch=amd64&mode=exactfilename&searchon=contents&keywords=libmono-system-native.so

### Current Behavior

The update fails while `/usr/lib/libmono-system-native.so` cannot be found.

### Expected Behavior

The `/urs/lib/libmono-system-native.so` is installed or at least symlinked to `/usr/lib/libmono-native.so` and the update can be performed successfully.

## On which platforms did you notice this

[ X ] Linux (Debian Stretch)

## Stacktrace

`apt install ca-certificates-mono`
```shell
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 mono-complete : Depends: ca-certificates-mono (= 6.0.0.319-0xamarin1+debian9b1) but 5.18.1.28-0xamarin5+debian9b1 is installed
 mono-devel : Depends: ca-certificates-mono (= 6.0.0.319-0xamarin1+debian9b1) but 5.18.1.28-0xamarin5+debian9b1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

`dpkg -L mono-runtime-common | grep libmono`
```shell
/usr/lib/libmono-btls-shared.so
/usr/lib/libmono-llvm.a
/usr/lib/libmono-native.so.0.0.0
/usr/lib/libmono-native.so
/usr/lib/libmono-native.so.0
```

## Current Workaround

```shell
ln -s /usr/lib/libmono-native.so /usr/lib/libmono-system-native.so
```

**Comment by marek-safar** [comment]
@directhex please have a look

**Comment by directhex** [comment]
What does `dpkg -l mono-runtime-common` report as the installation status (the first two letters)?

I know why the issue is happening, but I haven't been able to reproduce the environment that causes it to happen:

* The mapping from System.Net.Security.Native to libmono-native.so is defined in /etc/mono/config
* Because this file is in /etc, dpkg regards it as a user-editable config file
* dpkg will overwrite unmodified config files with new versions on update, but will leave modified config files alone (and put the new one in a new file, e.g. /etc/mono/config.dpkg-new)
* So why does dpkg consider your /etc/mono/config to be modified, not pristine?

It works fine in the simple case:

```
root@breakfast:/# apt install ca-certificates-mono
[..]
Unpacking mono-runtime-common (4.6.2.7+dfsg-1ubuntu1) ...
[..]
root@breakfast:/# apt dist-upgrade
[..]
Unpacking mono-runtime-common (6.0.0.319-0xamarin1+ubuntu1804b1) over (4.6.2.7+dfsg-1ubuntu1) ...
[..]
Setting up mono-runtime-common (6.0.0.319-0xamarin1+ubuntu1804b1) ...
[..]
Installing new version of config file /etc/mono/config ...
```

Why is dpkg not installing the new file? Why does it consider the old file to not be replaceable?

FWIW, the "correct" workaround is to move /etc/mono/config.dpkg-new over /etc/mono/config.

If you have debsums installed, can you run `debsums -e mono-runtime-common`?

**Comment by directhex** [comment]
`dpkg --status mono-runtime-common` will give better data

**Comment by directhex** [comment]
Sorry, looking back, I"m confused by one thing - are you using buster or stretch? You seem to imply both, in your report?

**Comment by Algorithman** [comment]
i'm stuck also with a broken install. apt install --fix-broken doesn't help either.

My installation was standard mono and monodevelop on linuxmint 19.2.
Updating did not install the ca-certificates in the first place, they were still on 5.something

maybe this helps to figure it out:
[aptoutput.txt](https://github.com/mono/mono/files/3482022/aptoutput.txt)

**Comment by directhex** [comment]
Sorry, that apt output doesn't help me, since it's from _after_ the problem would be visible in the logs.

`ca-certificates-mono` is a bit of a red herring here - it looks like the problem package, as it runs after install, and it fails if `/etc/mono/config` is obsolete. `/etc/mono/config` comes from `mono-runtime-common`. The issue is trying to determine why the obsolete conffile is kept.

**Comment by codekandis** [comment]
@directhex
I'm using Stretch. With a little help from my friend I was introduced in the package search engine of debian.org.

Sry, I don't have anything else from the state before my fix. I copied what I could from my terminal buffer after I fixed the problem and decided to open an issue.

What I can tell is

1. I had the same .Net Exceptions as @Algorithman attached above.
2. I remember I tried to changed my dist from `vs-stretch` to `stable-stretch` today after I took a look at the mono-project website. May this is the hint you need: I initially installed `monodevelop` once.
  - **`monodevelop.com`** https://www.monodevelop.com/download/#fndtn-download-lin-debian
  - **`mono-project.org`** https://www.mono-project.com/download/stable/#download-lin-debian

There may is an issue with these different dists.

**Comment by directhex** [comment]
The failure case is basically known, and seems to happen to a bunch of people on different distributions: apt thinks /etc/mono/config is not pristine and OS-provided (i.e. the md5sum of /etc/mono/config does not match the stored value from /var/lib/dpkg/status).

I have yet to determine _why_ it thinks that. It knows when the file's checksum matches that of an older package, that's how it knows it's safe to replace. Why does it think the file has been edited?

**Comment by curiosity-a** [comment]
Would this old config file help? I'm running Ubuntu 18.04, but I figure it hardly matters.
[config.txt](https://github.com/mono/mono/files/3485410/config.txt)
".txt" extension added to appease GitHub.

**Comment by curiosity-a** [comment]
Also, the output of `dpkg --status mono-runtime-common` you have mentioned in the other issue:
```Package: mono-runtime-common
Status: install ok unpacked
Priority: optional
Section: cli-mono
Installed-Size: 3515
Maintainer: Debian Mono Group <pkg-mono-group@lists.alioth.debian.org>
Architecture: amd64
Source: mono
Version: 6.0.0.319-0xamarin1+ubuntu1804b1
Config-Version: 5.18.1.28-0xamarin5+ubuntu1804b1
Replaces: libmono0 (<< 2.4), mono-common (<< 2.4), mono-jit (<< 2.4), mono-runtime (<< 3.2.1)
Provides: cli-runtime, cli-virtual-machine
Depends: libc6 (>= 2.16), zlib1g (>= 1:1.1.4), binutils, mono-gac (= 6.0.0.319-0xamarin1+ubuntu1804b1)
Recommends: binfmt-support (>= 1.1.2), mono-llvm-support
Suggests: xdg-utils | libgnome2-0 | konqueror
Conflicts: mono-1.0-runtime (<< 2.4), mono-2.0-runtime (<< 2.4), mono-common (<< 2.4), mono-jit (<< 2.4), mono-runtime (<< 3.2.1)
Conffiles:
 /etc/mono/2.0/Browsers/Compat.browser 0d831c1264b5b32a39fa347de368fe48
 /etc/mono/2.0/DefaultWsdlHelpGenerator.aspx f7be9f1841ff92f9d4040aed832e0c79
 /etc/mono/2.0/machine.config 5b791b8493c4e9a55d8c5ee522ce1cef
 /etc/mono/2.0/settings.map 22c818a23169e12bd3c8587b6394c731
 /etc/mono/2.0/web.config 2b6303c4f12762b71051db6e947f90a4
 /etc/mono/4.0/Browsers/Compat.browser 0d831c1264b5b32a39fa347de368fe48
 /etc/mono/4.0/DefaultWsdlHelpGenerator.aspx f7be9f1841ff92f9d4040aed832e0c79
 /etc/mono/4.0/machine.config 32bf879734966ef6659d914a217691e0
 /etc/mono/4.0/settings.map ba17ade8a8e3ee221377534c8136f617
 /etc/mono/4.0/web.config b127480ee9f0b8dab6a3f73ad79dd332
 /etc/mono/4.5/Browsers/Compat.browser 0d831c1264b5b32a39fa347de368fe48
 /etc/mono/4.5/DefaultWsdlHelpGenerator.aspx f7be9f1841ff92f9d4040aed832e0c79
 /etc/mono/4.5/machine.config 25ff1ec49e3ac9285bd943cf036bd813
 /etc/mono/4.5/settings.map ba17ade8a8e3ee221377534c8136f617
 /etc/mono/4.5/web.config 08101241b15b53ef0ab908f6d388881f
 /etc/mono/browscap.ini 378be809df7d15aac75a175693e25fbb
 /etc/mono/config dc9d7e7fbd83e76c7c7956f392a6ee6f
Description: Mono runtime - common files
 Mono is a platform for running and developing applications based on the
 ECMA/ISO Standards. Mono is an open source effort led by Xamarin.
 Mono provides a complete CLR (Common Language Runtime) including compiler and
 runtime, which can produce and execute CIL (Common Intermediate Language)
 bytecode (aka assemblies), and a class library.
 .
 This package contains common files for the Virtual Machine, JIT (Just-in-Time) and
 AOT (Ahead-of-Time) code generator "mono".
 "mono" executes applications for the CLI (Common Language Infrastructure).
 Mono currently only supports the X86, PowerPC, ARM, S/390x, AMD64 and
 MIPS architectures. Optionally this package configures BINFMT support.
Homepage: http://www.mono-project.com/```

**Comment by directhex** [comment]
And `md5sum /etc/mono/config`?

**Comment by directhex** [comment]
I've just dispatched a build with the fix: https://github.com/mono/linux-packaging-mono/commit/f7fdb81e0250bb366100c80f4b35d7494b98e8a0

**Comment by curiosity-a** [comment]
md5sum is `dc9d7e7fbd83e76c7c7956f392a6ee6f`.

**Comment by directhex** [comment]
The fix is available in the `stable` package repos, and is in the process of republishing to `vs`

**Comment by Algorithman** [comment]
updated, no issues

**Comment by codekandis** [comment]
I first deleted my symbolic link mentioned as workaround in my Opener.

I can confirm the update run well.

Thx alot.

**Comment by codekandis** [comment]
`mono-develop (6.0.0.319-0xamarin4+debian9b1)` has been rolled out correctly today.
