### ISSUE TITLE
Cannot update monodevelop due to unmet dependencies

### ISSUE THREAD

**Issue by lalkerala** [mono/mono#16130]
## Steps to Reproduce

1. Click on Software Updater then install available updates

### **The package system is broken**
Check if you are using third party repositories. If so disable them, since they are a common source of problems.
Furthermore run the following command in a Terminal: apt-get install -f
Transaction failed: The package system is broken
 The following packages have unmet dependencies:

mono-devel: Depends: mono-mcs (= 6.0.0.319-0xamarin1+ubuntu1604b1) but 6.0.0.319-0xamarin1+ubuntu1604b1 is installed
            Depends: mono-roslyn (= 6.0.0.319-0xamarin1+ubuntu1604b1) but 6.0.0.319-0xamarin1+ubuntu1604b1 is installed
            Depends: mono-gac (= 6.0.0.319-0xamarin1+ubuntu1604b1) but 6.0.0.319-0xamarin1+ubuntu1604b1 is installed
            Depends: mono-xbuild (= 6.0.0.319-0xamarin1+ubuntu1604b1) but 6.0.0.319-0xamarin1+ubuntu1604b1 is installed
            Depends: libmono-cil-dev (= 6.0.0.319-0xamarin1+ubuntu1604b1) but 6.0.0.319-0xamarin1+ubuntu1604b1 is installed
            Depends: libmono-2.0-dev (>= 6.0.0.319-0xamarin1+ubuntu1604b1) but 6.0.0.319-0xamarin1+ubuntu1604b1 is installed
            Depends: ca-certificates-mono (= 6.0.0.319-0xamarin1+ubuntu1604b1) but 5.18.1.28-0xamarin5+ubuntu1604b1 is installed

### Current Behavior

monodevelop does not open

### Expected Behavior

monodevelop opens

## On which platforms did you notice this

Linux Ubuntu 16.04

**Version Used**:

version 6.0.0.319

**Comment by directhex** [comment]
I need the output of 

dpkg --status mono-runtime-common

**Comment by javatript** [comment]
(Ubuntu 18.04) Having same problem
dpkg --status mono-runtime-common

Package: mono-runtime-common
Status: install ok unpacked
Priority: optional
Section: cli-mono
Installed-Size: 3515
Maintainer: Debian Mono Group <pkg-mono-group@lists.alioth.debian.org>
Architecture: amd64
Source: mono
Version: 6.0.0.319-0xamarin1+ubuntu1804b1
Config-Version: 5.18.1.28-0xamarin5+ubuntu1804b1
Replaces: libmono0 (<< 2.4), mono-common (<< 2.4), mono-jit (<< 2.4), mono-runtime (<< 3.2.1)
Provides: cli-runtime, cli-virtual-machine
Depends: libc6 (>= 2.16), zlib1g (>= 1:1.1.4), binutils, mono-gac (= 6.0.0.319-0xamarin1+ubuntu1804b1)
Recommends: binfmt-support (>= 1.1.2), mono-llvm-support
Suggests: xdg-utils | libgnome2-0 | konqueror
Conflicts: mono-1.0-runtime (<< 2.4), mono-2.0-runtime (<< 2.4), mono-common (<< 2.4), mono-jit (<< 2.4), mono-runtime (<< 3.2.1)
Conffiles:
 /etc/mono/2.0/Browsers/Compat.browser 0d831c1264b5b32a39fa347de368fe48
 /etc/mono/2.0/DefaultWsdlHelpGenerator.aspx f7be9f1841ff92f9d4040aed832e0c79
 /etc/mono/2.0/machine.config 5b791b8493c4e9a55d8c5ee522ce1cef
 /etc/mono/2.0/settings.map 22c818a23169e12bd3c8587b6394c731
 /etc/mono/2.0/web.config 2b6303c4f12762b71051db6e947f90a4
 /etc/mono/4.0/Browsers/Compat.browser 0d831c1264b5b32a39fa347de368fe48
 /etc/mono/4.0/DefaultWsdlHelpGenerator.aspx f7be9f1841ff92f9d4040aed832e0c79
 /etc/mono/4.0/machine.config 32bf879734966ef6659d914a217691e0
 /etc/mono/4.0/settings.map ba17ade8a8e3ee221377534c8136f617
 /etc/mono/4.0/web.config b127480ee9f0b8dab6a3f73ad79dd332
 /etc/mono/4.5/Browsers/Compat.browser 0d831c1264b5b32a39fa347de368fe48
 /etc/mono/4.5/DefaultWsdlHelpGenerator.aspx f7be9f1841ff92f9d4040aed832e0c79
 /etc/mono/4.5/machine.config 25ff1ec49e3ac9285bd943cf036bd813
 /etc/mono/4.5/settings.map ba17ade8a8e3ee221377534c8136f617
 /etc/mono/4.5/web.config 08101241b15b53ef0ab908f6d388881f
 /etc/mono/browscap.ini 378be809df7d15aac75a175693e25fbb
 /etc/mono/config dc9d7e7fbd83e76c7c7956f392a6ee6f
Description: Mono runtime - common files
 Mono is a platform for running and developing applications based on the
 ECMA/ISO Standards. Mono is an open source effort led by Xamarin.
 Mono provides a complete CLR (Common Language Runtime) including compiler and
 runtime, which can produce and execute CIL (Common Intermediate Language)
 bytecode (aka assemblies), and a class library.
 .
 This package contains common files for the Virtual Machine, JIT (Just-in-Time) and
 AOT (Ahead-of-Time) code generator "mono".
 "mono" executes applications for the CLI (Common Language Infrastructure).
 Mono currently only supports the X86, PowerPC, ARM, S/390x, AMD64 and
 MIPS architectures. Optionally this package configures BINFMT support.
Homepage: http://www.mono-project.com/

**Comment by directhex** [comment]
And `md5sum /etc/mono/config`?

**Comment by javatript** [comment]
md5sum /etc/mono/config
dc9d7e7fbd83e76c7c7956f392a6ee6f  /etc/mono/config

**Comment by directhex** [comment]
OK, so the md5sum lines up, the status is _unpacked_ but not _installed_.

So what's with the order packages are being configured in? Hm.

**Comment by directhex** [comment]
OK, I think I have a permanent workaround, I'm just discussing it with some other Debian developers.

**Comment by directhex** [comment]
I've just dispatched a build with the fix: https://github.com/mono/linux-packaging-mono/commit/f7fdb81e0250bb366100c80f4b35d7494b98e8a0

**Comment by javatript** [comment]
Thanks
https://github.com/mono/monodevelop/issues/8356#issuecomment-519926539

**Comment by directhex** [comment]
The fix is available in the `stable` package repos, and is in the process of republishing to `vs`
