### ISSUE TITLE
System.Linq.Dynamic.Core OrderBy not working in Blazor

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#16148]
_From @JoelW187 on Thursday, August 8, 2019 3:08:27 PM_

### Describe the bug
Calling System.Linq.Dynamic.Core.OrderBy(string) in a client-side Blazor component throws an exception (see attached image).

### To Reproduce
This code works on the server (Projects is a simple POCO class with a Description string field):

Projects.AsQueryable().OrderBy("Description")

In a Blazor component it throws the exception.

### Screenshots
![DynamicOrderBy](https://user-images.githubusercontent.com/15229643/62714763-2dd6d900-b9cd-11e9-8d3e-d0ba1b9e159d.png)

### Additional context
I'm using Core 3 Preview 7. This used to work (way back in Blazor 3 or 4) and broke sometime around 5, I beleive.

_Copied from original issue: aspnet/AspNetCore#12972_

**Comment by marek-safar** [comment]
The user code has quite complex reflection discovery code which linker cannot statically determine. This needs to be fixed on the user library side.
