### ISSUE TITLE
Class libraries compiled with VS2019 are not guaranteed to work in applications compiled with VS2017

### ISSUE THREAD

**Issue by dotMorten** [mono/mono#16162]
## Steps to Reproduce
Reproduces on both iOS and Android (albeit slightly different behavior but same error). Repro steps for Android here:

1.  Create a Xamarin.Android class library in VS2019. Add the following class:
```cs
    public static class MyClass
    {
        public static string CombineStringsHelper(params string[] values)
        {

            StringBuilder sb = new StringBuilder();
            sb.Append('{');
            if(values != null)
            {
                StringBuilder sb2 = new StringBuilder();
                foreach (var value in values)
                    sb2.Append(values);
                sb.Append(sb2); //Appending a stringbuilder to a stringbuilder causes a problem in Xamarin + VS2017. OK in 2019
            }
            sb.Append('}');
            return sb.ToString();
        }
    }
```
2. Compile it with VS2019 
3. In VS2017, create a new Xamarin.Android application and reference the assembly you produced with VS2019, and call the above method. You'll see this exception:
`System.MissingMethodException: Method not found:
System.Text.StringBuilder System.Text.StringBuilder.Append(System.Text.StringBuilder).
`
![image](https://user-images.githubusercontent.com/1378165/62829098-181f0a80-bbab-11e9-8aa4-b1848eea6a25.png)

4. Repeat 3, but this time use VS2019, and things will work.

5. Now compile the class-library in Step 2 with VS2017, and repeat step 3+4. No crash will occur in either case.

The error seems to indicate that it doesn't automatically pick the string overload through the implicit string conversion. The work-around is to change ` sb.Append(sb2); ` to ` sb.Append(sb2.ToString())';`. 

It appears to me that Mono class libraries created with VS2019 are not guaranteed to work in applications compiled with VS2017. This is very worrying, as many library authors often use 2019, but many customers are still stuck on 2017 and are at risk of hitting problems like this.

The same behavior has also been observed with iOS. .NET Framework and UWP doesn't exhibit this behavior, so I assume it's Mono-specific.

### Current Behavior

Crash when compiling class library with VS2019, but using it in an app in 2017. Only works when class library is created with VS2017, or application is built using 2019.

### Expected Behavior

The class library works in any supported IDE, regardless of which version it was compiled with.

## On which platforms did you notice this

[x] iOS
[x] Android

**Version Used**:
VS2017  15.9.3 (for app)
VS2019 16.2.1 (for class library)

**Comment by dotMorten** [comment]
The string builder overload for append appears to have been added in 2.1.
Could the problem here be that because we still don't have a way to compile against a specific Xamarin version, we easily get into the backwards compatibility issues?
If so this is yet another (VERY) good reason to get the Xamarin binaries shipped as nuget instead of shipping with VS versions. It's going to be a minefield ensuring you don't hit issues like this. As in completely impossible to handle.

**Comment by marek-safar** [comment]
This is not VS related but you are mixing two different versions of Xamarin iOS or Android which is not supported setup.

**Comment by dotMorten** [comment]
> This is not VS related but you are mixing two different versions of Xamarin iOS or Android which is not supported setup.

Well first of all, that's a theory I wrote above. Did you confirm that is actually what is happening?
Second, it's not a question, but a valid bug. It might be the reason is version mixing, but there's no solution to avoiding that, other than compiling with a very old version of Visual Studio, because there's no way to pick a version.

Please reopen and keep open until this issue is addressed.

**Comment by marek-safar** [comment]
It's not a theory but the fact that most Xamarin.iOS versions add a new API (this one was introduced in https://docs.microsoft.com/en-us/xamarin/ios/release-notes/api-changes/ios-12-4-0-12-8-0). If you take a dependency on new APIs it will not work on previous Xamarin.iOS versions.

I'm not sure Xamarin.iOS is tied to VS version but @chamons or @spouliot can confirm.

**Comment by jonpryor** [comment]
Both Xamarin.Android and Xamarin.iOS are *associated* with a VS version: Android and iOS (attempt to) use the  same mono commit hash for a given release series.  The forthcoming Visual Studio 16.3 release will be using the [mono/2019-06](https://github.com/mono/mono/commits/2019-06) branch, the current Visual Studio 16.2 release uses the [mono/2019-02](https://github.com/mono/mono/commits/2019-02) branch, Visual Studio 16.1 used the [mono/2018-08](https://github.com/mono/mono/commits/2018-08) branch, etc.

Each bump to a different mono branch means a potentially different (more expansive) `mscorlib.dll`.  `mscorlib.dll` is *backwards-compatible* -- older code will work on newer versions -- but it is *not* [foward compatible](https://en.wikipedia.org/wiki/Forward_compatibility).

If you need to compile code which runs with Visual Studio 2017, then you either need to use Visual Studio 2017 to compile that code, *or* you need to move the relevant code into a [Portable Class Library](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library) or [.NET Standard project](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

Portable Class Libraries and .NET Standard versions are *invariant*: new `mscorlib.dll`/etc. methods will not be added to *existing* PCL targets or .NET Standard versions.  This in turn means that if you want to use a newly added method, you'll need to specify a different PCL profile or .NET Standard version which contains the added method (if one exists).

**Comment by dotMorten** [comment]
> if you take a dependency on new APIs it will not work on previous Xamarin.iOS versions.

There's not a way to not do this. That's the problem. It's a pitfall for everyone building class libraries.

> If you need to compile code which runs with Visual Studio 2017, then you either need to use Visual Studio 2017 to compile that code,

Come on. You can't be serious. That's not really the solution here. No other target has this problem that Xamarin does, because you forgot to handle versioning the same way as everyone else.

>  you need to move the relevant code into a Portable Class Library or .NET Standard project

While we do support that, we of course use multi-targeting to tailor better for the individual platform so that's really not possible either.
