### ISSUE TITLE
Optimize Enum.HasFlag for compile time constants

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16175]
Benchmark snippet:
```csharp
using System;

class Program
{
    static void Main(string[] args) {}


    Colors _greenAndRed = Colors.Green | Colors.Red;

    public bool TestHasFlag() => _greenAndRed.HasFlag(Colors.Green);
}

[Flags]
public enum Colors
{
    Red = 0x1,
    Orange = 0x2,
    Yellow = 0x4,
    Green = 0x8,
    Blue = 0x10
}
```
CoreCLR:
```asm
Program.TestHasFlag()
    L0000: mov eax, [rcx+0x8]
    L0003: test al, 0x8
    L0005: setnz al
    L0008: movzx eax, al
    L000b: ret
```
Mono-LLVM-AOT:
```asm
_Program_TestHasFlag:
	mov	eax, dword ptr [rdi + 16]
	shr	al, 3
	and	al, 1
	ret
	nop
	nop
	nop
	nop
	nop
	nop
	nop
```

**Comment by EgorBo** [comment]
Turns out it's a different issue - the optimization doesn't work with fields? Updated the description.

**Comment by vargaz** [comment]
I get this:
_Program_TestHasFlag:
0000000000000a20        movl    0x10(%rdi), %eax
0000000000000a23        shrb    $0x3, %al
0000000000000a26        andb    $0x1, %al
0000000000000a28        retq

**Comment by EgorBo** [comment]
@vargaz oops yes, my verbose codegen was for static field (init).
So I am not sure it's an issue or not -- CoreCLR seems generates `test + setnz` instead of `shrb` and `and`. It's probably not important.
