### ISSUE TITLE
Use explicit IP addresses instead of localhost with TcpClient

### ISSUE THREAD

**Issue by rodrmoya** [mono/mono#16234]
## Steps to Reproduce

This code in monodevelop (https://github.com/mono/monodevelop/blob/master/main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs#L89) that hasn't been changed in years, started failing after we bumped to Mono 6.4.0.159.

A repro program:
```
using System;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Threading.Tasks;

namespace TcpClientBug
{
	class MainClass
	{
		class Server
		{
			HttpListener listener;

			public void Start (string host)
			{
				listener = new HttpListener ();
				listener.Prefixes.Add (host);

				Task.Run (() => {
					listener.Start ();
					Console.WriteLine ("Web server running...");
					while (listener.IsListening) {
						var context = listener.GetContext ();
						var buffer = System.Text.Encoding.UTF8.GetBytes ("<HTML><BODY> Hello world!</BODY></HTML>");
						context.Response.ContentLength64 = buffer.Length;
						var output = context.Response.OutputStream;
						output.Write (buffer, 0, buffer.Length);
						output.Close ();
					}
				});
			}

			public void Stop ()
			{
				listener.Stop ();
				listener.Close ();
			}
		}

		public static void Main (string[] args)
		{
			const string url = "http://localhost:5001/";

			// Start server
			var server = new Server ();
			server.Start (url);

			Task.Delay (1000).Wait ();

			// Connect with TcpClient
			using (var tcpClient = new TcpClient ()) {
				for (int i = 0; i < 5; i++) {
					try {
						tcpClient.Connect ("localhost", 5001);
						break;
					} catch (Exception ex) {
						Console.WriteLine ($"TcpClient FAILED: {ex}");
					}

					Task.Delay (100).Wait ();
				}
			}

			// Connect with HttpClient
			using (var httpClient = new HttpClient ())  {
				try {
					for (int i = 0; i < 5; i++) {
						using (var response = httpClient.GetAsync (url, HttpCompletionOption.ResponseHeadersRead).Result) {
							if (response.StatusCode == System.Net.HttpStatusCode.OK) {
								break;
							}
						}
					}
				} catch (Exception ex) {
					Console.WriteLine ($"HttpClient FAILED: {ex}");
				}

				Task.Delay (100).Wait ();
			}

			server.Stop ();
		}
	}
}
```

### Current Behavior

The call to `Connect`/`ConnectAsync` fails with:

```
TcpClient FAILED: System.Net.Sockets.SocketException (0x80004005): Invalid arguments
  at System.Net.Sockets.TcpClient.Connect (System.String hostname, System.Int32 port) [0x0019d] in <118907f5eb5f4e538f3e3bdd8361378f>:0 
  at TcpClientBug.MainClass.Main (System.String[] args) [0x0002d] in <8c15240288494c87a0ec7ca428f4df66>:0 
```

### Expected Behavior

Connect successfully, as it used to do before.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
$ mono --version
Mono JIT compiler version 6.4.0.159 (2019-06/8c035c21449 Thu Aug  8 01:15:04 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by steveisok** [comment]
@baulig Please have a look.

**Comment by steveisok** [comment]
In trying this local, the first underlying mono error was:

```
Mono: mono_w32socket_connect: connect error: Connection refused
```

After that, I got invalid arguments.

**Comment by baulig** [comment]
Be extremely careful with using `localhost` and Mono's ancient `HttpListener` implementation!

There are some important limitations in our implementation:

1.  You will almost certainly not want to use `localhost` as it's behavior is undefined.  It will semi-randomly choose either `127.0.0.1` or `::1` (but not both).
2. You cannot explicitly specify any IPv6 addresses.
3. Using anything that does not DNS-resolve will silently fall back to `IPAddress.Any`.
3. Using `+` is not supported (but the fallback in 3. still applies).
4. Using `*` means `IPAddress.Any`.

**Comment by baulig** [comment]
Adding to that list of limitations:

6. Using any invalid certificate with `https://` endpoints will silently fail.

**Comment by migueldeicaza** [comment]
Did the implementation change recently that affected this?

**Comment by baulig** [comment]
@migueldeicaza We did not change the HttpListener implementation - that code was actually last touched 6 years ago: https://github.com/mono/mono/blob/a103b78163bc4a7c7852272e0a391557b9d32ff7/mcs/class/System/System.Net/EndPointManager.cs#L85-L97

Calling `Dns.GetHostByName()` on something that has multiple IP Addresses can return them in any random order - and that code simply picks the first one.

I've just had my 1:1 with @steveisok and we decided to give this code some love.

**Comment by rodrmoya** [comment]
The problem is in TcpClient, just used HttpListener to simulate the issue we get in vsmac, where the server side is is .net core kestrel server. You can also reproduce by starting a asp.ner core app and remove the HttpListeneer part

**Comment by baulig** [comment]
As a workaround, you should be able to explicitly bind to the IP address - either `127.0.0.1` or `::1` - instead of `localhost`.

**Comment by baulig** [comment]
We are likely going to replace TcpClient with the CoreFX version (which has the same problem), so it should be addressed and fixed there.  Since there is an easy workaround, I'm going to close this here.
