### ISSUE TITLE
mono_thread_set_name_internal needs to be optimized for multi-thread

### ISSUE THREAD

**Issue by fanyang-mono** [mono/mono#16248]
### Current Behavior

I profiled mono-netcore with AOT=LLVM on macOS with the following benchmark.
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnetcore/PlatformBenchmarks

After discussing with the team, we found that mono_thread_set_name_internal needs to be optimized to improve the performance of Mono-netcore. We probably don't need to set a new name for every thread.

<img width="656" alt="Screen Shot 2019-08-14 at 3 47 35 PM" src="https://user-images.githubusercontent.com/52458914/63051370-202cc200-beab-11e9-9c79-93b85e74a760.png">

**Mono version used**:
36af44e3be4a0f73586e886b96f86ee500f8ab32

## Steps to Reproduce
Reproduce by following **Profiling workflow (Method 1)** from the following link:
https://paper.dropbox.com/doc/Profile-Mono-on-macOS--Aijv~7jvs5XNRvKUtb_7UzTYAg-ryHeobv8okzUs1Fa9TfBG

**Comment by jaykrell** [comment]
How about just not setting it in a loop, but just once per thread?

**Comment by jaykrell** [comment]
After https://github.com/mono/mono/pull/16250

introduce a local variable so that this:
```
C:\s\mono4\mono\metadata\threadpool.c(357):		mono_thread_set_name_internal (thread, thread_name, MonoSetThreadNameFlag_Reset, error);
```
is only once instead every time the loop runs.

Setting a thread name *once per thread* will be cheap. Setting it per threadpool work item, not so much. I suggested this long ago but was told it is per-spec or something -- threadpool is specified to be slow.

Really I suggest removing it from non-netcore and will PR that now.

**Comment by jaykrell** [comment]
I also have an optimization in a PR that removes the extra copying and string conversion here.
I was waiting for other PRs to be commited first.

See here:
https://github.com/mono/mono/pull/15859


which was requested to be split up.
The next in line for the split has been sitting for weeks here:

https://github.com/mono/mono/pull/15859

After that we'd just retain the constant w/o copying, for threadpool.

**Comment by lambdageek** [comment]
> Setting a thread name _once per thread_ will be cheap. Setting it per threadpool work item, not so much. I suggested this long ago but was told it is per-spec or something -- threadpool is specified to be slow.

We discussed offline that instead of setting it each time through the loop, we can reset it only if it changes.

**Comment by jaykrell** [comment]
Maintain an atomic counter in the thread? Yeah that sounds ok. Still a little wonky to do anything in the thread.

**Comment by jaykrell** [comment]
This should be much better now, and will get a *little* more better.

**Comment by vargaz** [comment]
-> FIXED.
