### ISSUE TITLE
Thread management issue: Mono opens up many threads

### ISSUE THREAD

**Issue by fanyang-mono** [mono/mono#16258]
## Current Behavior

I profiled mono-netcore with AOT=LLVM on macOS with the following benchmark.
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnetcore/PlatformBenchmarks

Mono seems to open a bunch new threads every few miliseconds. We need to find out why Mono needs to do it that often.
<img width="1396" alt="Screen Shot 2019-08-14 at 6 43 34 PM" src="https://user-images.githubusercontent.com/52458914/63061525-73ab0a00-bec3-11e9-8650-735fd0b25de5.png">

**Mono version Used**:
36af44e3be4a0f73586e886b96f86ee500f8ab32

## Steps to Reproduce
Reproduce by following **Profiling workflow (Method 1)** from the following link:
https://paper.dropbox.com/doc/Profile-Mono-on-macOS--Aijv~7jvs5XNRvKUtb_7UzTYAg-ryHeobv8okzUs1Fa9TfBG

**Comment by jaykrell** [comment]
Aside: Dropbox content maybe good for GitHub/web site? Too many places for things.

**Comment by marek-safar** [comment]
We could also look into porting the latest CoreCLR native version of TP. Our current version is based on some old version of it so it might not be that complicated.

**Comment by filipnavara** [comment]
I can resurrect my PRs for using CoreRT thread pool. It is itself a managed rewrite of the CoreCLR thread pool but with way less dependencies.

**Comment by marek-safar** [comment]
@filipnavara I think that would be great and we can help you with that work as well.

/cc @vargaz

**Comment by filipnavara** [comment]
I'll look into it next week once I return back to Prague.

**Comment by filipnavara** [comment]
@fanyang-mono would it be feasible for you to try the same scenario with #17387?

**Comment by fanyang-mono** [comment]
> @fanyang-mono would it be feasible for you to try the same scenario with #17387?

Yes. I will do it now and report back when I have the results.

**Comment by fanyang-mono** [comment]
I collected the profile trace with instruments with Filip's change. Now Mono doesn't periodically open up new threads any more.

**Comment by filipnavara** [comment]
Should be fixed by #17387 that was just merged.

**Comment by pr0vieh** [comment]
> What about non-netcore?

That's a good question I would like to have answered!
