### ISSUE TITLE
mono_rand_try_get_uint32 takes too long to get a random value

### ISSUE THREAD

**Issue by fanyang-mono** [mono/mono#16260]
### Current Behavior

I profiled mono-netcore with AOT=LLVM on macOS with the following benchmark.
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnetcore/PlatformBenchmarks

After discussing with the team, we found that mono_rand_try_get_uint32 took too much time to just get a random number. We need to find a faster way to do that.

<img width="813" alt="Screen Shot 2019-08-14 at 6 58 41 PM" src="https://user-images.githubusercontent.com/52458914/63062144-c980b180-bec5-11e9-853a-5e8673c4daca.png">

**Mono version used**:
36af44e3be4a0f73586e886b96f86ee500f8ab32

## Steps to Reproduce
Reproduce by following **Profiling workflow (Method 1)** from the following link:
https://paper.dropbox.com/doc/Profile-Mono-on-macOS--Aijv~7jvs5XNRvKUtb_7UzTYAg-ryHeobv8okzUs1Fa9TfBG

**Comment by jaykrell** [comment]
Good catch.
Probably a misconfigure here:

```
#if defined(HAVE_GETRANDOM) || defined(HAVE_GETENTROPY)
#ifdef HAVE_GETRANDOM
	gint const res = mono_getrandom (buffer, buffer_size, 0, error);
#else
	gint const res = mono_getentropy (buffer, buffer_size, error);
#endif
…
read

```

**Comment by jaykrell** [comment]
`arc4random`?

**Comment by fanyang-mono** [comment]
> `arc4random`?

Yeah, we were talking about this function during the meeting.

**Comment by jaykrell** [comment]
```
C:\s\mono4>dir /s/b pal*rand*
C:\s\mono4\external\corefx\src\Native\Unix\System.Native\pal_random.c
C:\s\mono4\external\corefx\src\Native\Unix\System.Native\pal_random.h
C:\s\mono4\external\corefx\src\Native\Unix\System.Security.Cryptography.Native.Apple\pal_random.c
C:\s\mono4\external\corefx\src\Native\Unix\System.Security.Cryptography.Native.Apple\pal_random.h
```
arc4random on non-Apple and something Apple-specific.
