### ISSUE TITLE
Fresh install - Ubuntu 18.04 stable - monodoc misconfigured?

### ISSUE THREAD

**Issue by rehierl** [mono/mono#16290]
- Linux Mint 19.1 (base is Ubuntu 18.04 bionic)
- `mono --version` is 6.0.0.319

After having spent a couple of hours on trying to get monodoc to work, I start to believe that there is something wrong with it's package configuration, but I just can't seem to figure out how to solve it. Some help would be greatly appreciated since I'd hate having to rely upon online resources ...

Here is a short summary of what works and what doesn't - follow the two pastebin.com links for more details - https://pastebin.com/WUE2vH6c - https://pastebin.com/7yypuTPW - accessible for 2 weeks.

I'm using the repository "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" on Linux Mint 19.1 (base is Ubuntu 18.04 bionic). Monodevelop works just fine as far as I can tell, which includes compiling and running the ASP.NET sample projects. The same applies to compiling and running all the [mono basics](https://www.mono-project.com/docs/getting-started/mono-basics/) examples.

And here is what does not work:

(1) When I try to run `/usr/bin/monodoc-http` from within a terminal, the browser window will pop open giving me a 404 error about being unable to find the resource (/). And yes, the /usr/share/monodoc/web folder does exist and contains a index.aspx file. However, not even appending /index.aspx to the url within the browser will work - even though the file/folder permissions seem fine.

(2) From within MonoDevelop, without having opened a solution beforehand, when I use the menu to open the "Help / Api Documentation", a dialog tells me that "You need a newer monodoc to use it". Well, if I'm using the mono-project.com repository, then there is nothing I can do here.

(3) From within MonoDevelop, while having a solution open and after a fresh restart, I get a dialog telling me the same what you can see next under point (4).

(4) When I try to run `/usr/bin/monodoc` from a terminal, monodoc seems to pop open and then crash while printing the following error messages to the terminal: (4.1) node 'nunit' is not defined on the documentation map, (4.2) libgluezilla not found and (4.3) Couldn't find html renderer!

- 4.1 - There is nothing more I can do about nunit since I have installed all the packages I can find when searching for "nunit" using the synaptic package manager.
- 4.2 - The only package I can find when searching for "libgluezilla" is "libmono-webbrowser4.0-cil" and that package is installed.
- 4.3 - I have no clue as to how resolve that one.

(5) After having run all the mono-basics examples I tried to give running "xsp4 --port 9000" from within "/usr/share/monodoc/web" a go. Trying to open "http://localhost:9000" from within my browser does not give me the error as shown in (1), but a http-500 error telling me that `/mono/lib/monodoc-ios/` does not exist.

- Well, that folder shouldn't even exist since mono isn't installed directly under the root folder. What does exist are /usr/lib/mono and /usr/share/mono folders.
- And a "monodoc-ios" folder or package is, unless I have missed it, nowhere to be found.

So, all in all, and due to (5) I believe there is some package misconfiguration. Either way I'm stuck since I don't know what I could try next.

**Comment by directhex** [comment]
`monodoc-browser`, the standalone doc reader, is dead - it needs Webkit for Gtk#2, which is long dead. That's what Monodevelop is trying to spawn.

`monodoc-http` ought to be working out of the box, so I'll have to investigate why it isn't.

**Comment by rehierl** [comment]
> the standalone doc reader, is dead

I see. So I guess you will update the "Help / Api Documentation" menu entry to trigger `monodoc-http` instead. If that is the case, you might also want to also take a look at the "Help / Report Problem ..." menu entry beneath it since that tries to open `http://xamar.in/r/file_studio_bug`, which no longer seems to work.

Either way, thanks for your quick feedback.

**Comment by directhex** [comment]
OK, I'm pushing an updated package to the preview branch, which _gets monodoc-http running_, but isn't what I'd call "good". It's an upgrade of the state of affairs from "disastrous" to "bad" - e.g. broken images, not cleaning up temp directory. https://github.com/mono/linux-packaging-mono-tools/compare/master@%7B1day%7D...master

**Comment by rehierl** [comment]
I did give the preview branch a try and can confirm that the `monodoc-http` command does indeed work. However, I can't really use it since selecting the "Base Class Library" entry (and others) will give me error messages - e.g. - Error: Your request has found no candidate provider [hs="(null)", id="(null)"]

However, the displayed link in my browser's addressbar does confirm that `docs.go-mono.com` seems to be the goto online reference. On that site I can open the "Base Class Library" entry without issues.

But don't take the above as a complaint since, as you implied, its just a quick hotfix.

Thanks for your efforts.

**Comment by directhex** [comment]
The links in the main window rather than the nav bar seem to work better, and kick-start the navbar into doing something
