### ISSUE TITLE
Change netcore package to be using release builds

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#16308]
We need to add release configuration for netcore lanes and we need to change the netcore packages to be produced from release configs not debug ones.

**Comment by EgorBo** [comment]
Don't we use Release by default for everything in .NET Core?

**Comment by filipnavara** [comment]
We do it at least for the managed part.

**Comment by akoeplinger** [comment]
Correct, we build the native bits with `-O2`: https://github.com/mono/mono/blob/9f3effc1775f2889e43dd3888abf6081c354ee59/netcore/build.sh#L96-L99
