### ISSUE TITLE
LLVM: "".AsSpan()[0] doesn't throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16310]
```csharp
char c = "".AsSpan()[0];
```
CoreCLR:
Mono:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

Mono-LLVM (both AOT and JIT):
```
(no exception was thrown)
```

**Comment by imhameed** [comment]
This is caused by the unconditional use of abcrem when compiling with LLVM; the same problem occurs when using abcrem without LLVM. I should have a PR out for this soon.
