### ISSUE TITLE
[Blazor client-side preview 8] memory issue wich cause code terminated

### ISSUE THREAD

**Issue by pranavkm** [mono/mono#16365]
_From @julienGrd on Saturday, August 17, 2019 6:11:18 PM_

Hello guys, I actually develop an app with blazor, in server side for development and client side on production.

My app consist of rewriting a silverlight app and reuse all the existing viewModel and suscribe to the event launched by the viewModel to update my views (essentially things like propertyChanged, collectionChanged, and eventHandler).

In server-side, it works perfectly.

Now i trying to make the app working on client side and i meet some trouble with that.
Indeed, i felt not all the code was executed sometimes. (and the app definitively not working as expected).

I also see some "debug" message in the chrome console like this :
````
WASM: GC_MINOR: (Nursery full) time 3.63ms, stw 3.70ms promoted 508K major size: 9408K in use: 5635K los size: 1024K in use: 229K
````
when i put some console.writeline in the code to see whats happen, i begin to understand my code is shutdown when these message appear. (for example i put 5 console.writeline in the code, i see the first three appear in the console, then the wasm debug message, and don't see the two other)

so it seem definitively a memory problem.

So the question are :
- is it for you a memory problem ?
- if yes, how i can solve it ? assuming i can't change the code of the existing viewModels runing in my app. there is any way to increase the memory limit?

it's really a big deal for me, i work on this app since 6 month, and i can't use the server-side on production because there is a lot of static access in the existing viewModels.

The complexity of my app make i can't propose a reproduction scenario.  

there is some other wasm message in the console, if it can help you
````
WASM: GC_MINOR: (Nursery full) time 4.11ms, stw 4.13ms promoted 742K major size: 1824K in use: 1123K los size: 1024K in use: 149K
WASM: GC_MAJOR_SWEEP: major size: 9168K in use: 23867K
WASM: GC_MAJOR: (LOS overflow) time 12.42ms, stw 12.47ms los size: 1024K in use: 63K
````

thanks for your help !

_Copied from original issue: aspnet/AspNetCore#13218_

**Comment by kjpou1** [comment]
The messages above are the garbage collector kicking in.  Something may be getting garbage collected and causing problems.

If the client side runs out of memory you will get a message saying something about "memory can not be expanded".

**Comment by LokiMidgard** [comment]
Any idea to find out what's causing the problem?

I have the same problem with some test project I'm playing with. My current aproach woud be to comment parts out and see if I can reproduce the error.

**Comment by julienGrd** [comment]
OK guys, I finally find what's happen.

It was not a memory problem as kjpou1 say. Actually I find two reason wich cause the code "shutdown" :
- I was running a code suppose to run only on server side, this code was suppose to read the appsetting.json to retrieve the settings of my app. Obviously it not work on client-side
````
var builder = new ConfigurationBuilder()
                            .SetBasePath(Directory.GetCurrentDirectory())
                            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                            .AddEnvironmentVariables();
=> code after that never execute
````
- I also see when you try to "wait" an async method the code shutdown too (in some situation i have to do something like that but i find an another way)
````
var result = MyAsyncMethod().Result;
=> code after that never execute
````
So the garbage collector message seem to be only coincidence in my case

But can be really nice to have better way to identify these situation because actually we have no information and it's really hard to find where the probem is.

**Comment by kjpou1** [comment]
Great to hear.
