### ISSUE TITLE
Relocations in .text on arm

### ISSUE THREAD

**Issue by radekdoulik** [mono/mono#16369]
It looks like AOT compiler produces shared libraries on XA/arm, which contains relocations in .text section.

Discussed it with @vargaz on slack and he thinks it was introduced recently by https://github.com/mono/mono/commit/9ff3b0d65ee4

I have tried older XA d16.1 and it indeed didn't contain relocations in `.text`, while current XA with mono-2019-06 does.

d16.1:

```
arm-linux-androideabi-readelf  -a /Users/rodo/git/monodroid-samples/android5.0/Topeka/Topeka/obj/Release/aot/armeabi-v7a/libaot-Topeka.dll.so |grep TEXT
```
Relevant part of source
```
.text 1
        .align 3
method_addresses:
        .local method_addresses
        .type method_addresses,#function
bl .Lm_0
bl .Lm_1
bl .Lm_2
...
```
No relocations in .text:
```
Section Headers:
...
  [ 5] .text             PROGBITS        00000240 000240 022a30 00  AX  0   0 16
...
Relocation section '.rel.dyn' at offset 0x178 contains 24 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
00024008  00000017 R_ARM_RELATIVE   
0002401c  00000017 R_ARM_RELATIVE   
00024020  00000017 R_ARM_RELATIVE   
00024024  00000017 R_ARM_RELATIVE   
00024028  00000017 R_ARM_RELATIVE   
0002402c  00000017 R_ARM_RELATIVE   
00024030  00000017 R_ARM_RELATIVE   
00024034  00000017 R_ARM_RELATIVE   
00024038  00000017 R_ARM_RELATIVE   
0002403c  00000017 R_ARM_RELATIVE   
00024040  00000017 R_ARM_RELATIVE   
00024044  00000017 R_ARM_RELATIVE   
0002404c  00000017 R_ARM_RELATIVE   
00024050  00000017 R_ARM_RELATIVE   
00024054  00000017 R_ARM_RELATIVE   
00024058  00000017 R_ARM_RELATIVE   
0002405c  00000017 R_ARM_RELATIVE   
0002407c  00000017 R_ARM_RELATIVE   
00024080  00000017 R_ARM_RELATIVE   
00024084  00000017 R_ARM_RELATIVE   
00024088  00000017 R_ARM_RELATIVE   
0002408c  00000017 R_ARM_RELATIVE   
00024090  00000017 R_ARM_RELATIVE   
00024094  00000017 R_ARM_RELATIVE   
```
master (which uses mono-2019-06):
```
arm-linux-androideabi-readelf  -a /Users/rodo/git/monodroid-samples/android5.0/Topeka/Topeka/obj/Release-master/aot/armeabi-v7a/libaot-Topeka.dll.so |grep TEXT
 0x00000016 (TEXTREL)                    0x0
 0x0000001e (FLAGS)                      TEXTREL
```
Relevant part of source:
```
.text 1
        .align 3
method_addresses:
        .local method_addresses
        .type method_addresses,#function
ldr pc,=.Lm_0
.ltorg
ldr pc,=.Lm_1
.ltorg
ldr pc,=.Lm_2
```
Relocations in `.text`
```
Section Headers:
...
  [ 5] .text             PROGBITS        00001580 001580 022e78 00  AX  0   0 16
...
Relocation section '.rel.dyn' at offset 0x178 contains 640 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
00020fe4  00000017 R_ARM_RELATIVE   
00020fec  00000017 R_ARM_RELATIVE   
00020ff4  00000017 R_ARM_RELATIVE   
00020ffc  00000017 R_ARM_RELATIVE
...
```
This probably affects the performance and will potentially cause problems on Android as the shared libs should not contain `.text` relocations on API >= 23. (https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html)

**Comment by grendello** [comment]
The requirement for the DSO not to contain text relocations will become a problem with the upcoming Android Q, which [will enforce (with SELinux)](https://developer.android.com/preview/behavior-changes-all#textrel) the requirement and AOT-ed apps will, therefore, stop working there.

**Comment by lewurm** [comment]
So I see two solutions to this problem:
1) We keep it like it is right now, support larger assemblies on arm32 with AOT but it won't work on Android Q. The reason why we need those relocations is that GNU `ld` errors out on too large offsets. Unfortunately the AOT compiler can't know with what offsets the linker will end up. FWIW on iOS the linker is smart enough to insert branch islands.
2) We revert all those changes introduced for "big assemblies".

I'm voting for 2) because
* Big assemblies are not _that_ common (basically you refuse to use the IL linker for some reason).
* The suggested workaround would be to switch to arm64 or don't use AOT if you really care about big assemblies.

Does that sound good @radekdoulik @grendello ?

**Comment by jaykrell** [comment]
Can you not output 32bit relative link-time constant addresses?
What do large C/C++ programs do?
I should experiment..

**Comment by radekdoulik** [comment]
2) sounds good to me, if we don't find other solution.

Couldn't we try to generate the branch islands ourselves? How do they look, wouldn't they also introduce relocations?

**Comment by grendello** [comment]
2. sounds good for now

@radekdoulik branch islands are basically interim locations within the branch limit range that let the program jump between two distant locations exceeding the limit. They shouldn't introduce relocations.

**Comment by radekdoulik** [comment]
Well, I am not sure as this llvm test looks like it expects the linker to create branch island and relocation as well. I don't know that much about it, so thus asking :-) https://github.com/microsoft/llvm-1/blob/master/test/MC/MachO/ARM/long-call-branch-island-relocation.s

**Comment by grendello** [comment]
I should have been more clear - they shouldn't create `.text` relocations (which is what we're trying to avoid)

@lewurm linker on iOS is GNU ld.gold right? Or is it ldd? In either case, we're dealing with similar tooling as the NDK Is currently clang-only + ld.gold/ldd, so I suppose it should be possible to get the same functionality out of the linker on Android as on iOS? Or did you mean the dynamic linker on the runtime?

**Comment by jaykrell** [comment]
Apple linker is ancient GNU ld fork I believe.

**Comment by jaykrell** [comment]
I don't think we are in a position to create branch islands.
I think it belongs in a linker.
I think it'd involve interleaving just enough extra .text and .rdata sections (instead of one each), so that each neighbor is reachable from anywhere in each neighbor. So that there is always .rdata reachable from .text, and so that .rdata contains full pointers, relocations.
It'd require a global view, that a linker has.
But maybe I'm way off.

**Comment by lewurm** [comment]
Jay is right, we (the AOT compiler) do not have the necessary information to emit branch islands.  We could, but that requires a lot of work and in the end would make us a linker :-)

iOS uses `ld64`. Whatever that is, but it doesn't seem to be ld.gold. The mentioned test by @radekdoulik is specifically for `MachO`, so it's using the Apple specific linker. The last time I tried for Android (a couple months ago), its linker did not automatically generate branch islands and I also didn't find any hints for it in the documentation.
