### ISSUE TITLE
how can I iterate all alive object?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#16376]
how can I iterate all alive object?

We want to iterate all object in gc root. How can we do it?

**Comment by alexrp** [comment]
You can do this with the profiler API. Install a `gc_event` callback and call `mono_gc_walk_heap` when `event` is `MONO_GC_EVENT_PRE_START_WORLD`.

There's some code in the log profiler showing how this can be done:

https://github.com/mono/mono/blob/935d0a54e7100c24c41f597174a78aab94836cab/mono/profiler/log.c#L1448-L1464

**Comment by srxqds** [comment]
ok, thank you
