### ISSUE TITLE
ARM back ends are not turning System.Math functions into intrinsics

### ISSUE THREAD

**Issue by jspohr-ubi** [mono/mono#16438]
When profiling AOT code generated by Mono on an ARM64 device, I noticed that calls to `System.Math.Sqrt` were translated to icalls which ended up calling libc `sqrt`.
Needless to say, doing a native function call instead of the corresponding intrinsic causes performance issues for math-heavy code, e.g. games that do a lot of 3D vector computations.

I'm using `-O=float32,intrins`, among others. Searching for the opcode in the Mono source code, I noticed that all back ends implement OP_SQRT and emit an instruction similar to fsqrt when a call to System.Math.Sqrt is detected (see `mono_arch_emit_inst_for_method`, for example [here](https://github.com/mono/mono/blob/278fd48274231c4b7737618d54a276b97ab17cf7/mono/mini/mini-amd64.c#L8231)).
For ARM and ARM64, this function [returns NULL](https://github.com/mono/mono/blob/278fd48274231c4b7737618d54a276b97ab17cf7/mono/mini/mini-arm64.c#L5265). Additionally, OP_SQRT is not handled in `mono_arch_output_basic_block`, which is fair given that the opcode is never used.

It's possible that I'm missing something, so maybe there's an alternative for the ARM architecture that I don't know about? NEON instruction set is not supported by System.Numerics API, is it? Does using the LLVM back end enable intrinsics on ARM?

**Comment by vargaz** [comment]
The mono JIT is not an optimizing compiler and doesn't generate highly optimized code in all cases. Using LLVM will enables these intrinsics, however llvm can still decide to do a function call if the cpu it targets doesn't have a hw sqrt instruction.

**Comment by jspohr-ubi** [comment]
Would you expect it to be a difficult task to implement for someone who has never worked on the back end? ARM64 does have fsqrt, so naively I would assume we could just look at the code for the other platforms and start from there. Details like proper alignment could get tricky though, I guess.
We're embedding a custom build of Mono, so I don't have a good estimate on the work required to switch to LLVM, that's why I'm weighing my options right now.

**Comment by marek-safar** [comment]
It should not be very difficult to implement and you can look at recent Mono commits in this area to get ideas about where to start. However, if you are serious about performance switching to LLVM codegen is better option
