### ISSUE TITLE
Fatal error in IL Linker Blazor Client Microsoft.AspNetCore.Mvc.Core

### ISSUE THREAD

**Issue by mfitconsultants** [mono/mono#16437]
I am getting the following error when trying to run Blazor client project which has been ported over form `preview7` to `preview8`. I have followed the steps from the Microsoft blog;

[https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/](url)

I am running on Visual Studio 2019 16.2.3

when running `dotnet build` I am getting the following linker error;
 
>  Fatal error in IL Linker
>   
>   Unhandled Exception: Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified> ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>      at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
>      at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
>      at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
>      --- End of inner exception stack trace ---
>      at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
>      at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
>      at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
>      at Mono.Linker.Steps.ResolveFromXmlStep.Process()
>      --- End of inner exception stack trace ---
>      at Mono.Linker.Steps.ResolveFromXmlStep.Process()
>      at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
>      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
>      at Mono.Linker.Pipeline.Process(LinkContext context)
>      at Mono.Linker.Driver.Run(ILogger customLogger)
>      at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
>      at Mono.Linker.Driver.Main(String[] args)
>   OakfieldLeasing.Data -> C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Data\bin\Debug\netcoreapp3.0\OakfieldLeasing.Data.dll
>   OakfieldLeasing.Data.EF -> C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Data.EF\bin\Debug\netcoreapp3.0\OakfieldLeasing.Data.EF.dll
> C:\Users\matt\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview8.19405.7\targets\Blazor.MonoRuntime.targets(441,5): error MSB3073: The command "dotnet "C:\Users\matt\.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview8.19380.1\build\netstandard1.0\../../tools/illink/illink.dll" -l none --disable-opt unreachablebodies --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\matt\.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview8.19380.1\build\netstandard1.0\../../tools/mono/bcl/" -d "C:\Users\matt\.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview8.19380.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" -o "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\obj\Debug\netcoreapp3.0\blazor\linker/" -x "C:\Users\matt\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview8.19405.7\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\obj\Debug\netcoreapp3.0\blazor\linker.descriptor.xml" -a "C:\Users\matt\.nuget\packages\blazored.localstorage\2.0.12\lib\netstandard2.0\Blazored.LocalStorage.dll" -a "C:\Users\matt\.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview8.19405.7\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\matt\.nuget\packages\microsoft.aspnetcore.blazor.httpclient\3.0.0-preview8.19405.7\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.HttpClient.dll" -a "C:\Users\matt\.nuget\packages\mono.webassembly.interop\3.0.0-preview8.19405.4\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\matt\.nuget\packages\newtonsoft.json\12.0.3-beta1\lib\netstandard2.0\Newtonsoft.Json.dll" -a "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Shared\bin\Debug\netstandard2.1\OakfieldLeasing.Blazor.Shared.dll" -a "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\obj\Debug\netcoreapp3.0\OakfieldLeasing.Blazor.Client.dll"" exited with code -532462766. [C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\OakfieldLeasing.Blazor.Client.csproj]
> 

[x] Windows

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

The `.csproj`;

```

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>7.3</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath></OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="2.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview8.19405.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview8.19405.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OakfieldLeasing.Blazor.Shared\OakfieldLeasing.Blazor.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>
  
</Project>
```

**Comment by laurence73** [comment]
Getting same issues on an existing preview8 Blazor app too where the build corrupts the path at random points

Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Windows\**ServicePrfiles**\NetworkService

this path should read "ServiceProfiles"

You can bypass the issue by adding <BlazorLinkOnBuild>false</BlazorLinkOnBuild> to your project file <PropertyGroup>. We experience this issue when we link with projects using EF.

**Comment by mfitconsultants** [comment]
Yes I can confirm this suppresses the error but then this causes the following error to occur at runtime;

> > blazor.webassembly.js:1 Uncaught (in promise) Error: Could not find type "MonoWebAssemblyJSRuntime" in namespace "Mono.WebAssembly.Interop" in assembly "Mono.WebAssembly.Interop"
>     at y (blazor.webassembly.js:1)
>     at g (blazor.webassembly.js:1)
>     at blazor.webassembly.js:1
>     at callRuntimeCallbacks (mono.js:1)
>     at postRun (mono.js:1)
>     at doRun (mono.js:1)
>     at run (mono.js:1)
>     at runCaller (mono.js:1)
>     at removeRunDependency (mono.js:1)
>     at blazor.webassembly.js:1

I too am also using EF in the Server side WebApi. any idea why this would occur at this point?

**Comment by laurence73** [comment]
stab in the dark but is your Mono.WebAssembly.Interop version in the referenced EF project on latest preview 8 too? (3.0.0-preview8.19405.4)

**Comment by ar0311** [comment]
Sound the same as the issue I lodged a few weeks ago here: #16063

**Comment by kjpou1** [comment]
The command line below looks pretty sparse and not referencing `Microsoft.AspNetCore.Mvc.Core` .dll anywhere.

Could you totally clean and restore the nugets of project so that the project is totally rebuilt from scratch?

``` 

"dotnet "C:\Users\matt.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview8.19380.1\build\netstandard1.0../../tools/illink/illink.dll" 
-l none 
--disable-opt unreachablebodies --verbose --strip-security true --exclude-feature com --exclude-feature sre 
-v false -c link -u link -b true 
-d "C:\Users\matt.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview8.19380.1\build\netstandard1.0../../tools/mono/bcl/" 
-d "C:\Users\matt.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview8.19380.1\build\netstandard1.0../../tools/mono/bcl/Facades/" 
-o "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\obj\Debug\netcoreapp3.0\blazor\linker/" 
-x "C:\Users\matt.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview8.19405.7\targets\BuiltInBclLinkerDescriptor.xml" 
-x "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\obj\Debug\netcoreapp3.0\blazor\linker.descriptor.xml" 
-a "C:\Users\matt.nuget\packages\blazored.localstorage\2.0.12\lib\netstandard2.0\Blazored.LocalStorage.dll" 
-a "C:\Users\matt.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview8.19405.7\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" 
-a "C:\Users\matt.nuget\packages\microsoft.aspnetcore.blazor.httpclient\3.0.0-preview8.19405.7\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.HttpClient.dll" 
-a "C:\Users\matt.nuget\packages\mono.webassembly.interop\3.0.0-preview8.19405.4\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" 
-a "C:\Users\matt.nuget\packages\newtonsoft.json\12.0.3-beta1\lib\netstandard2.0\Newtonsoft.Json.dll" 
-a "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Shared\bin\Debug\netstandard2.1\OakfieldLeasing.Blazor.Shared.dll" 
-a "C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\obj\Debug\netcoreapp3.0\OakfieldLeasing.Blazor.Client.dll"" 

exited with code -532462766. [C:\Users\matt\Source\Repos\OakfieldLeasing\OakfieldLeasing.Blazor.Client\OakfieldLeasing.Blazor.Client.csproj]

```

**Comment by SteveSandersonMS** [comment]
@kjpou1 It doesn't look right to me. It's trying to run the linker on some `netcoreapp3.0` assemblies. AFAIK that should never happen, because we only support `netstandard2.0`.

Perhaps the application itself has been changed to target `netcoreapp3.0`, which would be invalid.

**Comment by SteveSandersonMS** [comment]
@mfitconsultants I see in your csproj you have this:

```
<TargetFramework>netcoreapp3.0</TargetFramework>
```

That's not valid because Mono WebAssembly runs as `netstandard2.0`, not `netcoreapp3.0`. You'll need to change `TargetFramework` to `netstandard2.0`, which will probably resolve the linker issue (as well as making it possible to actually execute at runtime).

**Comment by kjpou1** [comment]
@SteveSandersonMS @danroth27

According to the docs at the following link it does tell users to update to `<TargetFramework>netcoreapp3.0</TargetFramework>`.  That may be the cause.

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio

**Comment by SteveSandersonMS** [comment]
That doc is about upgrading from ASP.NET Core 2.2 to 3.0, which isn't the situation for anyone doing Blazor, since that has never run on ASP.NET Core 2.2 :)

**Comment by ar0311** [comment]
The repo I linked on my issue reproducing my error is targetting netstandard2.0..... Or does the server project also need to target netapp2.0 not 3.0?

**Comment by mfitconsultants** [comment]
@SteveSandersonMS Correct changing this fixed the issue. I Apologize as I followed the following blog

[https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/](url)

which referenced your link and I from this I updated the client.csproj to netcoreapp3.0 in error. 

Thanks for all the help.
