### ISSUE TITLE
System.IO.Path.GetFullPath("\\\\.\\pipe\\pipename"): different results on Mono and .NET

### ISSUE THREAD

**Issue by jspam** [mono/mono#16460]
## Steps to Reproduce

1. Compile the following test program:
```cs
class MainClass
{
    public static void Main (string[] args) {
        System.Console.WriteLine(System.IO.Path.GetFullPath("\\\\.\\pipe\\pipename"));
    }
}
```
2. Execute it with `mono Program.exe`
3. Execute it with `Program.exe` (using .NET)

### Current Behavior

Output with `mono Program.exe` is: `\\.\pipe\\pipe\pipename`
Output with `Program.exe` is: `\\.\pipe\pipename`

### Expected Behavior

Output is the same in both cases. The output by .NET (leaving the path unchanged) seems the correct one.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:

Mono 6.7.0 (nightly)

## Note

`GetFullPath` is used in this fashion internally by `NamedPipeClientStream`, so this behavior basically makes `NamedPipeClientStream` unusable for me.

**Comment by directhex** [comment]
Looks like some bad assumptions in CanonicalizePath in Path.cs which don't account for the named pipe naming format (UNC in the broad sense works, it's a specific mishandling of the syntax used for pipes)

**Comment by directhex** [comment]
```
c:\Users\joshield\Desktop>mono test.exe
UNC pipe name (should be \\.\pipe\pipename): \\.\pipe\\pipe\pipename
UNC network name (should be \\servername\sharename\dirname): \\servername\sharename\dirname
UNC DOS name (should be \\?\C:\Users): \\?\C:\Users

c:\Users\joshield\Desktop>test.exe
UNC pipe name (should be \\.\pipe\pipename): \\.\pipe\pipename
UNC network name (should be \\servername\sharename\dirname): \\servername\sharename\dirname
UNC DOS name (should be \\?\C:\Users): \\?\C:\Users

c:\Users\joshield\Desktop>type test.cs
using System.Runtime.Versioning;

[assembly:TargetFramework(".NETFramework,Version=v4.7")]

class MainClass
{
    public static void Main (string[] args) {
        System.Console.WriteLine("UNC pipe name (should be \\\\.\\pipe\\pipename): {0}", System.IO.Path.GetFullPath("\\\\.\\pipe\\pipename"));
        System.Console.WriteLine("UNC network name (should be \\\\servername\\sharename\\dirname): {0}", System.IO.Path.GetFullPath("\\\\servername\\sharename\\dirname"));
        System.Console.WriteLine("UNC DOS name (should be \\\\?\\C:\\Users): {0}", System.IO.Path.GetFullPath("\\\\?\\C:\\Users"));
    }
}
```
