### ISSUE TITLE
System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by reisier** [mono/mono#16491]
A SslStream from a TcpClient, after AuthenticateAsServer, should polulate the sslStream.RemoteCertificate  property. In Windows works, in linux don't.
The server is IIS10.

## On which platforms did you notice this
[ ] Linux
**Version Used**:
mono --version
Mono JIT compiler version 6.0.0.319 (tarball Mon Aug 12 23:46:26 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by baulig** [comment]
This has been fixed a long time ago.
