### ISSUE TITLE
[netcore] Implement DllMap

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16521]
Run the following snippet on macOS:
```csharp
using System;
using System.Runtime.InteropServices;

class Program
{
    [DllImport("msvcrt")]
    public static extern int rand();

    static void Main(string[] args)
    {
        Console.WriteLine("Rand: " + rand());
    }
}
```

legacy mono will redirect "msvcrt" to "libc" (see https://github.com/mono/mono/blob/master/data/config.in#L18) and return some random value,

Mono-netcore:
```
Unhandled Exception:
System.DllNotFoundException: msvcrt assembly:<unknown assembly> type:<unknown type> member:(null)
   at HelloWorld.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: msvcrt assembly:<unknown assembly> type:<unknown type> member:(null)
   at HelloWorld.Program.Main(String[] args)
```

**Comment by EgorBo** [comment]
@lambdageek @CoffeeFlux related doc in CoreCLR https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/dllmap.md

**Comment by EgorBo** [comment]
@jkotas yeah I don't think this specific redirection is needed but it exists in our legacy config (it makes sense to strip it for System.Private.CoreLib.dll.config)

**Comment by marek-safar** [comment]
@EgorBo where did you hit this issue? The netcore packaging storey is quite different that what desktop Mono has and I am not sure DllMap is the right choice for BCL

**Comment by EgorBo** [comment]
@marek-safar some libs in nuget or msbuild have `[DllImport("libc")]` pinvokes which crash on Linux (we use dllmap for libc -> libc.so.6 transitions.

**Comment by lambdageek** [comment]
> some libs in nuget or msbuild have [DllImport("libc")] pinvokes which crash on Linux (we use dllmap for libc -> libc.so.6 transitions.

@EgorBo how do those nugets behave on CoreCLR?  Does it rely on the events that we don't have wired up yet?

**Comment by jkotas** [comment]
CoreCLR has the libc transition hardcoded for Unix: https://github.com/dotnet/coreclr/blob/6b0dab793260d36e35d66c82678c63046828d01b/src/pal/src/loader/module.cpp#L555 . It is one and only transition it has. We do not plan to ever extend it for other libraries.

**Comment by marek-safar** [comment]
@lambdageek could we do something very similar here?
