### ISSUE TITLE
Blazor MissingMethodException in published/release mode

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#16565]
_From @lertoo on Wednesday, August 28, 2019 10:38:43 PM_

.NET 3.0 Preview 8 for Blazor (Client) aap.

### To Reproduce
1. Use any of the following method in code:
- System.Net.Http.HttpClient.GetByteArrayAsync()
- List<T>.ForEach()
- Enum.GetValues()
2. Publish the Blazor app then run it. Calling those methods cause MissingMethodException.

### Expected behavior
It should be working as in debug mode.

### Additional context
It seems that Blazor release runtime (wasm) miss some .NET Standard methods.

_Copied from original issue: aspnet/AspNetCore#13529_

**Comment by lewing** [comment]
Does this still happen if you disable the linker?

**Comment by lertoo** [comment]
Yes. It is working by disabling the linker.
Thanks Lewing.

**Comment by marek-safar** [comment]
Is there repro or at least stacktrace of what is crashing?

**Comment by kjpou1** [comment]
I have tried to recreate these with no success and should be tried by the OP with the current Blazor preview.

The `System.Net.Http.HttpClient.GetByteArrayAsync()` now uses the mono http interface.
`List.ForEach()` can not recreate.
`Enum.GetValues()` can not recreate.

If this is closed error please reopen or create a new issue.
