### ISSUE TITLE
mono does not suspend on unhandled exception

### ISSUE THREAD

**Issue by messani** [mono/mono#16588]
## Steps to Reproduce

1. Code
```csharp
using System;

namespace Test
{
  class MainClass
  {
    public static void Main(string[] args)
    {
      throw new Exception("blabla");
    }
  }
}
```
2. Run:
MONO_DEBUG=suspend-on-unhandled mono ./Test.exe

### Current Behavior

Unhandled Exception:
System.Exception: blabla
  at Test.MainClass.Main (System.String[] args) [0x00001] in <36e3bc63485340bfbb0ade4f561e1edc>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: blabla
  at Test.MainClass.Main (System.String[] args) [0x00001] in <36e3bc63485340bfbb0ade4f561e1edc>:0

and then mono process ends.

### Expected Behavior

mono process should suspend so I can attach to it for example with gdb.

## On which platforms did you notice this

[ ] macOS
[*] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.0.0.327 (tarball Thu Aug 29 21:19:42 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

**Comment by BaibhaVatsa** [comment]
I tried looking into this issue. The following line of code (![link to it](https://github.com/mono/mono/blob/481b3005c63daa38d163e46ef5bb43288b1403b7/mono/mini/mini-exceptions.c#L2690)) returns `MONO_FIRST_PASS_HANDLED` even when it is not handled. 
```c
res = handle_exception_first_pass (&ctx_cp, obj, &first_filter_idx, &ji, &prev_ji, non_exception, &catch_frame, &has_perform_wait_callback_method);
```
I couldn't find beyond that why `handle_exception_first_pass` returns incorrect value. Any further pointers will be very helpful.

**Comment by naricc** [comment]
Pull request fixing this issue: https://github.com/mono/mono/pull/18095

**Comment by naricc** [comment]
It seems that this issue is subsumed by changes @thaystg  is making to the debug handlers, so I have added her to the issue. My proposed changes here here: https://github.com/mono/mono/pull/18095, but I have abandoned that PR.
