### ISSUE TITLE
`make distclean` fails after build w/ embedded zlib

### ISSUE THREAD

**Issue by akien-mga** [mono/mono#16605]
## Steps to Reproduce

Steps specific to my environment, I did not check how reproducible they would be in other conditions.

1. On a Fedora 30 docker image, install Mono build deps, mingw-w64 and download the `mono-6.0.0.319` source tarball.
2. Configure with: `./configure --prefix=/root/dependencies/mono-64 --host=x86_64-w64-mingw32 --disable-boehm --disable-mcs-build --disable-executables`.
3. Build with `make -j && make install`, works fine.
4. Attempt `make distclean`, errors out at some point with `Makefile:778: .deps/zutil.Plo: No such file or directory`.

Dockerfile: https://github.com/godotengine/build-containers/blob/master/Dockerfile.windows#L11-L17

### Current Behavior

`make distclean` errors out at some steps:
```
# make distclean
...
Making distclean in support
make[1]: Entering directory '/root/mono-6.0.0.319/support'
Makefile:778: .deps/zutil.Plo: No such file or directory
make[1]: *** No rule to make target '.deps/zutil.Plo'.  Stop.
make[1]: Leaving directory '/root/mono-6.0.0.319/support'
make: *** [Makefile:584: distclean-recursive] Error 1

# make distclean
Making distclean in m4
make[1]: Entering directory '/root/mono-6.0.0.319/m4'
make[1]: *** No rule to make target 'distclean'.  Stop.
make[1]: Leaving directory '/root/mono-6.0.0.319/m4'
make: *** [Makefile:584: distclean-recursive] Error 1
```

### Expected Behavior

It should clean things properly without error.
I'm updating a container where this used to work fine with a 5.18.1.3 release tarball.

## On which platforms did you notice this

[ ] macOS
[x] Linux, cross-compiling for Windows with mingw-w64
[ ] Windows

**Version Used**:

6.0.0.319 source tarball.

**Comment by directhex** [comment]
Great, more random zlib fallout.

**Comment by directhex** [comment]
OK, not actually fallout, this issue is in versions with the new zlib and the old one. It's a general issue with how we do our conditionals.

**Comment by directhex** [comment]
I think the problem is distclean is trying to delete the same .Plo files twice, once in `mono/metadata` and once in `support`

**Comment by directhex** [comment]
Yep, problem is here:

```
directhex@breakfast:/tmp/mono-6.7.0.493/mono/metadata$ make distclean
test -z "mono-bundle.stamp" || rm -f mono-bundle.stamp
test -z " " || rm -f  
rm -rf .libs _libs
rm -rf ../../support/.libs ../../support/_libs
test -z "libmonoruntime-config.la libmonoruntime-support.la  libmonoruntimesgen.la" || rm -f libmonoruntime-config.la libmonoruntime-support.la  libmonoruntimesgen.la
rm -f ./so_locations
rm -f *.o
rm -f ../../support/*.o
rm -f ../../support/*.lo
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f ../../support/.deps/.dirstamp
rm -f ../../support/.dirstamp
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ../../support/.deps ./.deps
rm -f Makefile
```

`mono/metadata/` is removing `.deps` from `support/`

**Comment by directhex** [comment]
Here's the same bug in VLC. Their fix is... terrifying to consider. https://trac.videolan.org/vlc/ticket/9367

**Comment by directhex** [comment]
There might be something worth stealing in https://github.com/videolan/vlc/commit/bca1bc25f20914814da5bad3aafa2510c2bbcee6, will look in the AM.

**Comment by directhex** [comment]
There's a second distclean issue with netcore/
