### ISSUE TITLE
Missing caching for Activator.CreateInstance<T>

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#16615]
CoreCLR has cache for creating instances of generic type: https://github.com/dotnet/coreclr/blob/f07c13cadc378649f10d024bb8a40a3878fa661f/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L4053-L4082

Mono does not have it which could, in some instances, result in vastly different performance characteristics (up to 1739x slower in micro benchmarks).

**Comment by Therzok** [comment]
Can we do this for non-.netcore too?

**Comment by filipnavara** [comment]
Likely yes. I prefer to do netcore first and backport if necessary.

**Comment by marek-safar** [comment]
I recall seeing even some intrinsic for value-type(s) to be hooked there.

**Comment by filipnavara** [comment]
We still have performance gap here but it's no longer >1500x slower:

| Slower                                                                           | diff/base | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| -------- |
| System.Reflection.Activator<EmptyClass>.CreateInstanceType                       |     13.22 |            44.05 |           582.23 |         |
| System.Reflection.Activator<EmptyStruct>.CreateInstanceType                      |     11.39 |            40.53 |           461.81 |         |
| System.Reflection.Activator<EmptyStruct>.CreateInstanceGeneric                   |     11.02 |             0.36 |             3.97 |         |
| System.Reflection.Activator<EmptyClass>.CreateInstanceGeneric                    |      8.76 |            45.54 |           399.08 |         |
| System.Reflection.Activator<EmptyClass>.CreateInstanceNames                      |      1.78 |          9940.35 |         17657.10 |         |
| System.Reflection.Activator<EmptyStruct>.CreateInstanceNames                     |      1.46 |          8779.70 |         12806.73 |         |
