### ISSUE TITLE
LLVM: false == true

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16621]
The following snippet returns an unexpected result (or even crashes if LLVM optimizations are disabled) for LLVM JIT mode:
```csharp
using System;
using System.Runtime.CompilerServices;

class P
{
    static unsafe void Main()
    {
        Console.WriteLine(Test(true, 256)); // true is for [1..255] range
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static unsafe bool Test(bool x, int n)
    {
        *((int*)&x) = n;
        return x == true;
    }
}
```
CoreCLR, Mono:
```
False
```

Mono-LLVM-JIT:
```
True
```

Mono-LLVM-JIT with `MONO_LLVM_OPT=" "` (no optimizations):
```
Got a SIGSEGV while executing native code.
```

MONO_VERBOSE_METHOD=Test:
```llvm
*** Unoptimized LLVM IR for P:Test ***

; Function Attrs: noinline uwtable
define monocc i8 @"P:Test (bool,int)"(i32 %arg_x, i32 %arg_n) #0 {
BB0:
  %0 = alloca i8, align 1
  %1 = trunc i32 %arg_x to i8
  store i8 %1, i8* %0
  br label %BB3

BB3:                                              ; preds = %BB0
  br label %BB2

BB2:                                              ; preds = %BB3
  %2 = bitcast i8* %0 to i32*
  %3 = getelementptr i32, i32* %2, i32 0
  store i32 %arg_n, i32* %3
  %4 = load volatile i8, i8* %0
  %5 = zext i8 %4 to i32
  br label %BB1

BB1:                                              ; preds = %BB2
  %6 = trunc i32 %5 to i8
  ret i8 %6
}
***


*** Optimized LLVM IR for P:Test ***

; Function Attrs: noinline uwtable
define monocc i8 @"P:Test (bool,int)"(i32 %arg_x, i32 %arg_n) #0 {
BB0:
  %0 = alloca i8, align 1
  %1 = trunc i32 %arg_x to i8
  store i8 %1, i8* %0, align 1
  %.0. = load volatile i8, i8* %0, align 1
  ret i8 %.0.
}
***
```
`%arg_n` is not even used in the optimized IR 😐 
```asm
0000000000000000	movb	%dil, -0x1(%rsp)
0000000000000005	movb	-0x1(%rsp), %al
0000000000000009	retq
```
CoreCLR:
```asm
P.Test(Boolean, Int32)
    L0000: mov [rsp+0x8], ecx
    L0004: mov [rsp+0x8], edx
    L0008: mov eax, [rsp+0x8]
    L000c: movzx eax, al
    L000f: ret
```

PS: some netcore tests fail with `Expected: true, Actual: true` for LLVM

**Comment by EgorBo** [comment]
I suspect optimizations did it, e.g. unoptimized IR had:
```llvm
  %5 = zext i8 %4 to i32
  %6 = trunc i32 %5 to i8
```

**Comment by EgorBo** [comment]
Ok, turns out the IR we generate is wrong and even crashes with stack corruption if optimizations are disabled (we write i32 into i8 we just allocated on stack)
Optimizer sees UB and fixes it (so it doesn't crash but doesn't return the expected result neither).

**Comment by EgorBo** [comment]
Reproduces with stable Mono 6.0 too:
```
csc -O p.cs
mono --llvm p.exe
```
Output:
```
Got a SIGSEGV while executing native code.
```

**Comment by jaykrell** [comment]
This looks like incorrect unsafe code to me and is supposed to crash.
Bool is of size one. You are corrupting memory.
Maybe it is the other local, ok. Maybe it is the return address. Maybe it is a saved nonvolatile register.

Seems like ByDesign to me.

**Comment by EgorBo** [comment]
@jaykrell it is incorrect indeed, BUT we pass bool as Int32 (note i32 argument)

**Comment by jaykrell** [comment]
Maybe we should pass it as i8.

**Comment by jaykrell** [comment]
How does C++ pass bool?
How does C pass char/unsigned char/signed char?
i.e. can parameters be passed as smaller than i32? I hope so and suspect they should be.

**Comment by imhameed** [comment]
Yeah; I'm not entirely sure what we should do here. We could widen allocas used for sub-int sized data, I suppose, but I don't think adding workarounds for code like this is a good idea. What netcore tests failed?
