### ISSUE TITLE
Buffer.BlockCopy is slow

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16678]
see https://github.com/mono/mono/blob/master/netcore/System.Private.CoreLib/src/System/Buffer.cs#L19-L56
this method does 4 icalls (`IsPrimitiveTypeArray`, `IsPrimitiveTypeArray`, `ByteLength`, `ByteLength`) before calling Memmove (which is fast itself). At least we can merge these 4 calls.

Also, note https://github.com/mono/mono/blob/master/netcore/System.Private.CoreLib/src/System/Buffer.cs#L58-L65

Related benchmarks:
![image](https://user-images.githubusercontent.com/523221/64333063-77bbda80-cfde-11e9-8226-1ac4884a3a11.png)

**Comment by marek-safar** [comment]
@vargaz @BrzVlad is this something you would like to look at?

**Comment by EgorBo** [comment]
@marek-safar I think I can fix it
