### ISSUE TITLE
Can't build wasm on linux by following directions from the SDKs directory

### ISSUE THREAD

**Issue by kg** [mono/mono#16693]
I did an ```autogen --with-wasm=yes``` and it said WASM is enabled. Doing a make in the root succeeded, so mono built.

```
kate@reeir-debian2:~/Projects/mono$ make -C sdks/builds archive-wasm  NINJA=
make: Entering directory '/home/kate/Projects/mono/sdks/builds'
make setup-custom-wasm-runtime
make[1]: Entering directory '/home/kate/Projects/mono/sdks/builds'
mkdir -p /home/kate/Projects/mono/sdks/out/wasm-runtime-release
make[1]: Leaving directory '/home/kate/Projects/mono/sdks/builds'
mkdir -p /home/kate/Projects/mono/sdks/builds/wasm-runtime-release
cd /home/kate/Projects/mono/sdks/builds/wasm-runtime-release && source /home/kate/Projects/mono/sdks/builds/toolchains/emsdk/emsdk_env.sh && emconfigure /home/kate/Projects/mono/configure ac_cv_func_shm_open_working_with_mmap=no --disable-mcs-build --disable-nls --disable-boehm --disable-btls --with-lazy-gc-thread-creation=yes --with-libgc=none --disable-executables --disable-support-build --disable-visibility-hidden --enable-maintainer-mode --enable-minimal=ssa,com,jit,reflection_emit_save,portability,assembly_remapping,attach,verifier,full_messages,appdomains,security,sgen_marksweep_conc,sgen_split_nursery,sgen_gc_bridge,logging,remoting,shared_perfcounters,sgen_debug_helpers,soft_debug,interpreter,assert_messages,cleanup,mdb,gac --host=wasm32 --enable-llvm-runtime --enable-icall-export --disable-icall-tables --disable-crash-reporting --with-bitcode=yes  --cache-file=/home/kate/Projects/mono/sdks/builds/wasm-runtime-release.config.cache --prefix=/home/kate/Projects/mono/sdks/out/wasm-runtime-release  CFLAGS="-fexceptions -Os -g " CXXFLAGS="-fexceptions -Os -g -s DISABLE_EXCEPTION_CATCHING=0 "
Adding directories to PATH:
PATH += /home/kate/Projects/mono/sdks/builds/toolchains/emsdk
PATH += /home/kate/Projects/mono/sdks/builds/toolchains/emsdk/upstream/emscripten
PATH += /home/kate/Projects/mono/sdks/builds/toolchains/emsdk/node/12.9.1_64bit/bin

Setting environment variables:
EMSDK = /home/kate/Projects/mono/sdks/builds/toolchains/emsdk
EM_CONFIG = /home/kate/Projects/mono/sdks/builds/toolchains/emsdk/.emscripten
EM_CACHE = /home/kate/Projects/mono/sdks/builds/toolchains/emsdk/.emscripten_cache
EMSDK_NODE = /home/kate/Projects/mono/sdks/builds/toolchains/emsdk/node/12.9.1_64bit/bin/node

configure: loading cache /home/kate/Projects/mono/sdks/builds/wasm-runtime-release.config.cache
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `wasm32': machine `wasm32' not recognized
configure: error: /bin/bash /home/kate/Projects/mono/config.sub wasm32 failed
wasm.mk:149: recipe for target '.stamp-wasm-runtime-release-configure' failed
make: *** [.stamp-wasm-runtime-release-configure] Error 1
make: Leaving directory '/home/kate/Projects/mono/sdks/builds'
```

**Comment by lewurm** [comment]
Not sure what instructions you are referring to. You shouldn't need to run `./autogen.sh` at all for an SDK build, it's all done by the `archive-wasm` target. The `README.md` is (surprisingly) accurate:
https://github.com/mono/mono/blob/f5717d21bbf4a98a2e1b8c431617590aec1d68f8/sdks/wasm/README.md#commands-for-compiling-mono

In fact, if you do `./autogen.sh` in the root directory first, it potentially messes with the SDK build system, so I recommend to start from a clean repository again (`git clean -xffd`).

**Comment by kg** [comment]
I followed the three steps there, yes. They didn't work. Some notes from slack troubleshooting:

* I needed an entirely clean checkout, can't do anything wasm in a regular checkout (is it really that weird to expect that i could build multiple targets in one checkout?). It's still unclear to me what the --enable-wasm flag on autogen is for.
* I needed a make.config because I'm not on OS X and by default it needs Xcode (I think this might be fixed now?)
* I needed to update my python to latest python 3, then install pip 3 because for some reason it's used to install clang

When I left off I was getting issues with the build failing due to attempts to use some sort of mingw cross build, I didn't get a chance to troubleshoot that. I assume I need to disable that in make.config as well.

**Comment by kg** [comment]
```git clean -xffd``` seems to have completely hosed the checkout, as I suspected it might somehow.

```
kate@reeir-debian2:~/Projects/mono-wasm$ make -C sdks/builds provision-wasm
make: Entering directory '/home/kate/Projects/mono-wasm/sdks/builds'
make: *** No rule to make target 'provision-wasm'.  Stop.
make: Leaving directory '/home/kate/Projects/mono-wasm/sdks/builds'
```

Maybe it was already broken, but when I tried this yesterday before bumping my checkout to master + doing a git clean the provision step was working.

**Comment by kg** [comment]
The no rule to make target is because we changed Make.config without changing the Make.config.sample file, so that part of the directions is wrong. ```ENABLE_WASM = 1``` in the Make.config got me further.

```
In file included from /home/kate/Projects/mono-wasm/mono/utils/mono-codeman.c:22:
/home/kate/Projects/mono-wasm/mono/utils/dlmalloc.h:226:17: error: 'mono_dlmallinfo' has C-linkage specified, but returns incomplete type 'struct mallinfo' which could be incompatible with C [-Werror,-Wreturn-type-c-linkage]
struct mallinfo dlmallinfo(void);
                ^
/home/kate/Projects/mono-wasm/mono/utils/dlmalloc.h:62:32: note: expanded from macro 'dlmallinfo'
#define dlmallinfo             mono_dlmallinfo
                               ^
1 error generated.
```

```
make[7]: *** [Makefile:1312: libmonoutils_la-mono-codeman.lo] Error 1
make[7]: Leaving directory '/home/kate/Projects/mono-wasm/sdks/builds/wasm-runtime-release/mono/utils'
make[6]: *** [Makefile:2003: all-recursive] Error 1
```

**Comment by kg** [comment]
Current Make.config:
```
DISABLE_CXX = 1
ENABLE_CXX = 0
DISABLE_WASM = 0
ENABLE_WASM = 1
DISABLE_DESKTOP = 1
ENABLE_DESKTOP = 0
DISABLE_IOS = 1
ENABLE_IOS = 0
DISABLE_MAC = 1
ENABLE_MAC = 0
DISABLE_ANDROID = 1
ENABLE_ANDROID = 0
CONFIGURATION = Debug
```

```
checking for wasm32-gcc... /home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/emscripten/emcc
checking for wasm32-gcc... (cached) /home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/emscripten/emcc
checking whether the C compiler works... no
configure: error: in `/home/kate/Projects/mono-wasm/sdks/builds/wasm-runtime-Debug':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [wasm.mk:150: .stamp-wasm-runtime-Debug-configure] Error 77
make: Leaving directory '/home/kate/Projects/mono-wasm/sdks/builds'
```

Alas it seems like forcing C++ off just means I can't build, vs failing to build because our source is apparently not C++ compatible

**Comment by kg** [comment]
Running emcc directly shows the error, which is inexplicably not in the log file.
```
kate@reeir-debian2:~/Projects/mono-wasm$ /home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/emscripten/emcc
shared:ERROR: llc executable not found at /usr/bin/llc
```
Unfortunately installing llvm from apt-get provides an old llvm, so I guess I will need to install llvm from source:
```
kate@reeir-debian2:~/Projects/mono-wasm$ /home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/emscripten/emcc
shared:WARNING: LLVM version appears incorrect (seeing "7.0", expected "10.0")
shared:INFO: (Emscripten: Running sanity checks)
emcc:WARNING: no input files
```

**Comment by kg** [comment]
Zoltan made some bug fixes to the build flow today, the remaining issues were caused by the way we parse Config.make. ```ENABLE_CXX = 0``` actually enables C++ just like ```ENABLE_CXX = 1``` which results in the build failing because our code isn't C++ compatible, even if 'emcc' is being used - emcc does not imitate clang or gcc here.

I also had to run the extra commands jenkins runs - provision, configure, build, archive - but doing that on a clean checkout with a carefully crafted Config.make (just ENABLE_WASM=1 and nothing else from the sample) finally worked.

**Comment by lewing** [comment]
Are we able to close this now or do the docs still need an update?

**Comment by kg** [comment]
Can confirm that the instructions in the docs actually work now, as long as your checkout is completely clean. ```git clean -xffd``` on a copy of an existing checkout won't suffice. The docs say you need a separate checkout explicitly (and not just a clean one) so i think we're fine here.
