### ISSUE TITLE
Disposing the FileSystemWatcher does not close associated file descriptors

### ISSUE THREAD

**Issue by mrward** [mono/mono#16709]
## Steps to Reproduce

Related problem - https://github.com/mono/mono/issues/15931

1. Sample project - https://github.com/mrward/test-file-watcher-dispose - multi-target project that builds .NET 4.7.2 and .NET Core 2.1
2. Build this project.
3. From the command line run `mono bin/debug/net472/FileWatcherDisposeTest.exe`
4. Run `lsof -p pid`. Process id is output from the console app.
5. See that the file watcher creates file descriptors for several directories.
6. After 10 seconds the file watcher will be disposed.
7. Run `lsof -p pid` again.

### Current Behavior

lsof still lists the directories.

```
mono-sgen 3972 user    4r DIR   1,12      170   51740695 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest/bin/Debug/net472
mono-sgen 3972 user    5r DIR   1,12      136   51740600 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest/bin/Debug
mono-sgen 3972 user    6r DIR   1,12      102   51740599 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest/bin
mono-sgen 3972 user    7r DIR   1,12      204   51740594 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest
mono-sgen 3972 user    8r DIR   1,12      170   51740593 /Volumes/Drive/projects/tests/FileWatcherDisposeTest
mono-sgen 3972 user    9r DIR   1,12     6324     185300 /Volumes/Drive/projects/tests
mono-sgen 3972 user   10r DIR   1,12     2312        278 /Volumes/Drive/projects
mono-sgen 3972 user   11r DIR   1,12      646          2 /Volumes/Drive
mono-sgen 3972 user   12r DIR    1,4      160     420284 /Volumes
```
If you change the console project to run GC.Collect after the dispose then lsof will not list the directories.

Also affects .NET Core 2.1 (bug the GC.Collect does not workaround the problem there)

### Expected Behavior

File watcher directories not listed by lsof.

Note that 

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.4.0.188 (2019-06/2c3aeaf3780 Tue Sep  3 15:10:54 EDT 2019)

**Comment by steveisok** [comment]
@mrward Did you create an upstream corefx issue as well?

**Comment by mrward** [comment]
No, I have not done that. Was investigating Mono since this affects VS Mac. I can open one against dotnet/corefx and reference this.

**Comment by mrward** [comment]
Opened this also against corefx - https://github.com/dotnet/corefx/issues/40888

**Comment by lambdageek** [comment]
This is fixed on `master` and on `2019-08` now.

**Comment by Therzok** [comment]
@slluis do we want this in 8.3 too?
