### ISSUE TITLE
[llvm] Emit intrinsics for mini_emit_memset/mini_emit_memcpy

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#16716]
LLVM has intrinsics for memset/memcpy:

[‘llvm.memset.*’ Intrinsics](https://llvm.org/docs/LangRef.html#llvm-memset-intrinsics)
[‘llvm.memcpy’ Intrinsic](https://llvm.org/docs/LangRef.html#llvm-memcpy-intrinsic)

Currently Mono emits unrolled loops which are not too bad. However, it lacks vectorization which could improve the performance significantly.

Furthermore, `string.memset` should be made into intrinsic similarly to `Buffer.Memmove`.

**Comment by EgorBo** [comment]
In theory LLVM is able to recognize some patterns and replace them with memset/memmove/memcpy :) see https://github.com/mono/mono/issues/16251 (`ZeroArray` sample)

**Comment by filipnavara** [comment]
@EgorBo Aside from the volatile load/store we are also hitting manually unrolled loops here.

**Comment by SamMonoRT** [comment]
Seems like we don't want to port this to dotnet\runtime repo. Fixes for mono\mono seem completed by issue linked above. Closing this issue. We'll work on any more Intrinsics in the runtime repo.
