### ISSUE TITLE
XmlSerializer not Using UTF-8 as Default Encoding (.NET 4.8 Mac)

### ISSUE THREAD

**Issue by chamons** [mono/mono#16741]
_From @vsfeedback on Mon, 09 Sep 2019 18:30:19 GMT_

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/722323/xmlserializer-not-using-utf-8-as-default-encoding.html)._

---
I’ve been using .NET Framework 4.7.x for my Xamarin.Mac app quite a while.
And my apps are using XmlSerializer for storing configurations and other data.
Couple of days ago I upgraded them to .NET Framework 4.8 hoping that will somehow … ease future migration path to the upcoming .NET 5…
Since then all XMLs created by XmlSerializer are encoded as us-ascii instead of utf-8 resulting entire data broken!!! (e.g. all asian texts are unanimously replaced by question mark(?) …) 
Currently I hot-fixed the issue by implementing XmlWriter’s Settings manually but this should absolutely be addressed ASAP!!!

(By the way, I am fortunate that I had implemented auto-backup solution a month ago so I was able to restore the important a year-worth data.)

---
#### Visual Studio Feedback System on 9/5/2019, 01:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

_Copied from original issue xamarin/xamarin-macios#6944_

**Comment by chamons** [comment]
Was this a expected behavior change @marek-safar ?

**Comment by steveisok** [comment]
@chamons Do you know if this is happening through VS on Windows?

**Comment by marek-safar** [comment]
That's very strange because the underlying implementation is identical for 4.7 and 4.8 (only reference assemblies are different). Is there any repro for this behaviour?

**Comment by chamons** [comment]
@steveisok It's Xamarin.Mac, which is macOS only for applications. It can't be VS Windows I don't believe. 

I don't have a repro - I'll ask on the closed devcom ticket.

**Comment by xfortin-devolutions** [comment]
@chamons Any news on this? I have the same problem, and now I have to rewrite all my XmlSerializer code, which is quite frustrating.

**Comment by chamons** [comment]
No, I don't have any update, as this is a runtime issue. @steveisok might, but it may not be prioritized currently.

**Comment by steveisok** [comment]
@xfortin-devolutions I can't reproduce, so if you have a sample, I can look into this further. 

And what is your environment / versions?

**Comment by xfortin-devolutions** [comment]
Here's the code used in a Mono console application:

```
class MainClass
{
    public static void Main(string[] args)
    {
        Information information = new Information { Name = "Lüther", Description = "Dëscription" };

        XmlSerializer serializer = new XmlSerializer(typeof(Information));

        Console.WriteLine("Test with default encoder:");
        using (MemoryStream stream = new MemoryStream())
        {
            serializer.Serialize(stream, information);
            string result = Encoding.UTF8.GetString(stream.ToArray());
            Console.WriteLine(result);
        }

        Console.WriteLine();

        Console.WriteLine("Test by overriding default encoder with UTF8:");
        using (MemoryStream stream2 = new MemoryStream())
        {
            using (XmlWriter writer = XmlWriter.Create(stream2, new XmlWriterSettings { Indent = true, Encoding = new UTF8Encoding(false, false) }))
            {
                serializer.Serialize(writer, information);
                string result = Encoding.UTF8.GetString(stream2.ToArray());
                Console.WriteLine(result);
            }
        }
    }
}

public class Information
{
    public string Name { get; set; }

    public string Description { get; set; }
}
```

Here's my result with Mono 6.6.0.155:

```
Test with default encoder:
<?xml version="1.0"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>L?ther</Name>
  <Description>D?scription</Description>
</Information>

Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>L?ther</Name>
  <Description>D?scription</Description>
</Information>

```
Note that the ü and ë have been replaced with "?" and that, even in the test with the UTF8 encoder.

Here's my result with Mono 5.18.1.28:

```
<?xml version="1.0"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Lüther</Name>
  <Description>Dëscription</Description>
</Information>

Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Lüther</Name>
  <Description>Dëscription</Description>
</Information>
```

No problem whatsoever. Same problem with Mono 6.8.0.96.

**Comment by steveisok** [comment]
@xfortin-devolutions Double checking my understanding.... Is this still a Xamarin.Mac application?  And are you trying to run it from a mac or from Windows?  

FWIW - It outputted correctly against desktop mono 6.8.0.96.

**Comment by xfortin-devolutions** [comment]
@steveisok It's on Mac, but the previous example was specifically in a purely Mono console application (i.e. not a Xamarin.Mac application). I originally noticed this issue in a Xamarin.Mac application though.

I've been trying different version of Mono so I can be a bit more precise. The latest version of Mono I've tried that worked is 5.18.1.28. When I download 5.20.1.34, the bug start to occur again.

**Comment by steveisok** [comment]
Interesting.  What osx version are you using?  And is there anything special about your setup to note?

And to make sure we're on the same page, I built the sample w/ `csc` and then ran the application.  Is that they way you did it too? Or did you use VS (if so, what version)?

**Comment by xfortin-devolutions** [comment]
I'm running on macOS 10.15.3 (19D76). I'm not aware of anything special about my setup.

I used Visual Studio to build the application (here's the exact project: [TestXmlSerializerEncoding.zip](https://github.com/mono/mono/files/4160007/TestXmlSerializerEncoding.zip)). I've used different version of VS (because of the Mono requirement of the different version). The one I used with Mono 6.6 and above is 8.4 (build 2657) and the one I used with previous version of Mono is 8.1.1 (build 27).

**Comment by xfortin-devolutions** [comment]
Ah! For the example I provided it appears that the issue is the Encoding of the Console that is the problem. If I add the following line at the top of the Main method:

`Console.OutputEncoding = new UTF8Encoding(false, false);`

The code seems to work as expected, outputting the character properly. In my Xamarin.Mac application, the problem seemed to lie with the XmlSerializer though. I'll prepare a new sample.

That being said, I do not believe that the default encoding of the Console was ASCII before Mono 5.20 (as it is now in Mono 5.20+).

**Comment by xfortin-devolutions** [comment]
@steveisok @chamons I confirm that the behavior is not the same between Mono and Xamarin.Mac. With Xamarin.Mac 6.8.3.0 and Mono 6.6.0 (2019-08/bef1e633581) the same code as [above](https://github.com/mono/mono/issues/16741#issuecomment-582413102) give me the following result:

```
Test with default encoder:
<?xml version="1.0" encoding="us-ascii"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>L?ther</Name>
  <Description>D?scription</Description>
</Information>

Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Lüther</Name>
  <Description>Dëscription</Description>
</Information>
```

While the Console.OutputEncoding is also wrong (ASCII instead of UTF8), the problem is not only in the console output but really with the serialized data itself. We can see in the output of the serialization where I did not change the Encoding that the 'encoding="us-ascii" is appended to the "xml" tag and the tréma character get replaced with "?". If I change the Encoding (with the XmlWriter), the problem is resolved.

Here's the project I used: 
[TestXmlSerializerEncoderXamMac.zip](https://github.com/mono/mono/files/4161382/TestXmlSerializerEncoderXamMac.zip)

**Comment by chamons** [comment]
There are a few paths in that same that need changing to run:
```
                File.WriteAllText("/Users/Devolutions33/Desktop/TestSerialize/NoEncoding.txt", result);
```
XM Modern:
```
Test with default encoder:
<?xml version="1.0" encoding="us-ascii"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>L?ther</Name>
  <Description>D?scription</Description>
</Information>

Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Lüther</Name>
  <Description>Dëscription</Description>
</Information>
```
XM Full
```

Test with default encoder:
<?xml version="1.0"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Lüther</Name>
  <Description>Dëscription</Description>
</Information>

Test by overriding default encoder with UTF8:
<?xml version="1.0" encoding="utf-8"?>
<Information xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Lüther</Name>
  <Description>Dëscription</Description>
</Information>
```

So it appears to be a Mobile vs Desktop profile issue @steveisok ?
