### ISSUE TITLE
Targeting Blazor WebAssembly project to .NET Standard 2.1 breaks at runtime

### ISSUE THREAD

**Issue by danroth27** [mono/mono#16765]
Repro steps:

- Create a new Blazor WebAssembly app
- Update the client project to target netstandard2.1
- Build and run.

Expected result: Runs successfully

Actual result:

```
WASM: System.AggregateException: One or more errors occurred. (VTable setup of type System.Text.Json.Utf8JsonWriter failed) ---> System.TypeLoadException: VTable setup of type System.Text.Json.Utf8JsonWriter failed
WASM:   at System.Text.Json.JsonSerializer.WriteCoreString (System.Object value, System.Type type, System.Text.Json.JsonSerializerOptions options) <0x1ce3bf0 + 0x00044> in <81e9245ca982431695a55cc67ffb3b86>:0 
WASM:   at System.Text.Json.JsonSerializer.ToStringInternal (System.Object value, System.Type inputType, System.Text.Json.JsonSerializerOptions options) <0x1ce3880 + 0x0000c> in <81e9245ca982431695a55cc67ffb3b86>:0 
WASM:   at System.Text.Json.JsonSerializer.Serialize[TValue] (TValue value, System.Text.Json.JsonSerializerOptions options) <0x1ce37c0 + 0x0000c> in <81e9245ca982431695a55cc67ffb3b86>:0
WASM:   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[TValue] (System.String identifier, System.Object[] args) <0x1ce3678 + 0x0001e> in <b57783c7fafa47088562351a82800d2f>:0
WASM:   at Microsoft.AspNetCore.Blazor.Rendering.WebAssemblyRenderer.AddComponentAsync (System.Type componentType, System.String domElementSelector) <0x1c859d8 + 0x00064> in <3914758d3a6d4113a921804c5fa45f6c>:0
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRendererAsync () <0x1c427e8 + 0x000dc> in <3914758d3a6d4113a921804c5fa45f6c>:0
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsyncAwaited () <0x1c29e38 + 0x001ec> in <3914758d3a6d4113a921804c5fa45f6c>:0
WASM:    --- End of inner exception stack trace ---
WASM: ---> (Inner Exception #0) System.TypeLoadException: VTable setup of type System.Text.Json.Utf8JsonWriter failed
WASM:   at System.Text.Json.JsonSerializer.WriteCoreString (System.Object value, System.Type type, System.Text.Json.JsonSerializerOptions options) <0x1ce3bf0 + 0x00044> in <81e9245ca982431695a55cc67ffb3b86>:0
WASM:   at System.Text.Json.JsonSerializer.ToStringInternal (System.Object value, System.Type inputType, System.Text.Json.JsonSerializerOptions options) <0x1ce3880 + 0x0000c> in <81e9245ca982431695a55cc67ffb3b86>:0
WASM:   at System.Text.Json.JsonSerializer.Serialize[TValue] (TValue value, System.Text.Json.JsonSerializerOptions options) <0x1ce37c0 + 0x0000c> in <81e9245ca982431695a55cc67ffb3b86>:0
WASM:   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[TValue] (System.String identifier, System.Object[] args) <0x1ce3678 + 0x0001e> in <b57783c7fafa47088562351a82800d2f>:0
WASM:   at Microsoft.AspNetCore.Blazor.Rendering.WebAssemblyRenderer.AddComponentAsync (System.Type componentType, System.String domElementSelector) <0x1c859d8 + 0x00064> in <3914758d3a6d4113a921804c5fa45f6c>:0
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRendererAsync () <0x1c427e8 + 0x000dc> in <3914758d3a6d4113a921804c5fa45f6c>:0
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsyncAwaited () <0x1c29e38 + 0x001ec> in <3914758d3a6d4113a921804c5fa45f6c>:0 <---
```

Workaround:

Disable the IL linker by setting `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>`.

**Comment by danroth27** [comment]
@lewing

**Comment by BenjaminCharlton** [comment]
Don't mean to hassle, but I was just wondering if this will be complete by the time the final release of .NET Core 3.0 comes out later in the month?

**Comment by danroth27** [comment]
@BenjaminCharlton No, this fix won't be ready in time for the next preview Blazor Webassembly release that's going out with the NET Core 3.0 release. It will be a few more weeks until we have a fix for this.

**Comment by BenjaminCharlton** [comment]
Ok thanks for the information. Keep up the great work!

**Comment by Herdo** [comment]
Will this be fixed with .NET Core 3.1, the Blazor WASM release in May 2020, or at a different point in time?

**Comment by Herdo** [comment]
Related to #15833 ?

**Comment by Rauce** [comment]
Just came across this issue myself and found it here.

Until this is fixed, we cannot use C# 8 language features in a Blazor app, as to do so requires targeting .NET Standard 2.1 :-(

**Comment by mkArtakMSFT** [comment]
@marek-safar what's the latest on this?

**Comment by lewing** [comment]
I spent some time looking at this today and it appears to be related to assembly resolution when the linker is used.  In particular after the linker has run we appear to be ending up with a version of System.Threading.Tasks.Extensions.dll that the mono runtime can't handle.

**Comment by mkArtakMSFT** [comment]
Thanks @lewing. Is this something you have control over of is this something we break somewhere in Blazor?

**Comment by lewing** [comment]
https://github.com/aspnet/AspNetCore/compare/master...lewing:resolve-with-linker is a quick workaround that demonstrates the problem.  In the linker case _BlazorDependencyInput references assemblies that have been resolved against the wrong bcl.  The workaround uses the linker to resolve the assemblies and orders the directories so that we resolve against the wasm bcl first.

/cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Thanks Larry! It seems clear then that this is not a Mono issue, but rather is something we need to update in Blazor, which I'm doing based on your approach at https://github.com/aspnet/AspNetCore/pull/16808.

This can be closed IMO.

**Comment by kjpou1** [comment]
Closing this based on issue discussions

**Comment by ebbypeter** [comment]
So is this issue fixed? or moved to a dofferent repo?

**Comment by danroth27** [comment]
Hi @ebbypeter. Targeting .NET Standard 2.1 should be working with the latest Blazor WebAssembly previews. If you're finding otherwise, please let us know by opening a new issue with details about the problem you're seeing.
