### ISSUE TITLE
Fail to build 6.0.0.327 on FreeBSD

### ISSUE THREAD

**Issue by igorzigorz** [mono/mono#16776]
It's modified FreeBSD port mono.
With 5.20.1.34 no problem.
With 6.0.0.327 errors:

../../doltlibtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../..  -I../.. -I../../mono -I../../libgc/include -I../../mono/eglib -I../../mono/eglib -fvisibility=hidden -Wall -Wunused -Wmissing-declarations -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Qunused-arguments -Wno-unused-function -Wno-tautological-compare -Wno-parentheses-equality -Wno-self-assign -Wno-return-stack-address -Wno-constant-logical-operand -Wno-zero-length-array -DLIBICONV_PLUG -DGC_FREEBSD_THREADS -DHOST_BSD -D_WITH_GETLINE -g  -DUSE_COMPILER_TLS -DHAVE_BOEHM_GC  -Wall -Wunused -Wmissing-declarations -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Qunused-arguments -Wno-unused-function -Wno-tautological-compare -Wno-parentheses-equality -Wno-self-assign -Wno-return-stack-address -Wno-constant-logical-operand -Wno-zero-length-array -O2 -pipe -O3 -march=ivybridge -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wno-format-zero-length -std=gnu99 -fno-strict-aliasing -fwrapv -DMONO_DLL_EXPORT -g -Werror=incompatible-pointer-types -Werror=return-type -Werror-implicit-function-declaration -MT libmonoruntime_la-mono-route.lo -MD -MP -MF .deps/libmonoruntime_la-mono-route.Tpo -c -o libmonoruntime_la-mono-route.lo `test -f 'mono-route.c' || echo './'`mono-route.c
In file included from mono-route.c:13:
In file included from ../../mono/metadata/mono-route.h:17:
/usr/include/net/route.h:82:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_locks;      /* Kernel must leave these values alone */
        ^
/usr/include/net/route.h:83:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_mtu;        /* MTU for this path */
        ^
/usr/include/net/route.h:84:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_hopcount;   /* max hops expected */
        ^
/usr/include/net/route.h:85:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_expire;     /* lifetime for route, e.g. redirect */
        ^
/usr/include/net/route.h:86:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_recvpipe;   /* inbound delay-bandwidth product */
        ^
/usr/include/net/route.h:87:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_sendpipe;   /* outbound delay-bandwidth product */
        ^
/usr/include/net/route.h:88:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_ssthresh;   /* outbound gateway buffer limit */
        ^
/usr/include/net/route.h:89:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_rtt;        /* estimated round trip time */
        ^
/usr/include/net/route.h:90:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_rttvar;     /* estimated rtt variance */
        ^
/usr/include/net/route.h:91:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_pksent;     /* packets sent using this route */
        ^
/usr/include/net/route.h:92:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_weight;     /* route weight */
        ^
/usr/include/net/route.h:93:2: error: unknown type name 'u_long'; did you mean
      'long'?
        u_long  rmx_filler[3];  /* will be used for T/TCP later */
        ^
/usr/include/net/route.h:112:18: error: unknown type name 'u_int'
typedef volatile u_int rt_gen_t;        /* tree generation (for adds) */
                 ^
In file included from mono-route.c:13:
In file included from ../../mono/metadata/mono-route.h:17:
In file included from /usr/include/net/route.h:132:
/usr/include/net/radix.h:57:2: error: unknown type name 'u_char'; did you mean
      'char'?
        u_char  rn_flags;               /* enumerated next */
        ^
/usr/include/net/radix.h:63:4: error: unknown type name 'caddr_t'
                        caddr_t rn_Key;         /* object of search */
                        ^
/usr/include/net/radix.h:64:4: error: unknown type name 'caddr_t'
                        caddr_t rn_Mask;        /* netmask, if present */
                        ^
/usr/include/net/radix.h:94:2: error: unknown type name 'u_char'; did you mean
      'char'?
        u_char  rm_flags;               /* cf. rn_flags */
        ^
/usr/include/net/radix.h:97:3: error: unknown type name 'caddr_t'
                caddr_t rmu_mask;               /* the mask */
                ^
In file included from mono-route.c:13:
In file included from ../../mono/metadata/mono-route.h:17:
/usr/include/net/route.h:250:2: error: unknown type name 'u_short'; did you mean
      'short'?
        u_short rtm_msglen;     /* to skip over non-understood messages */
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
gmake[5]: *** [Makefile:2548: libmonoruntime_la-mono-route.lo] Error 1
gmake[5]: *** Waiting for unfinished jobs....

**Comment by igorzigorz** [comment]
If add to mono/metadata/mono-route.h #include <sys/types.h> no errors.

**Comment by rootwyrm** [comment]
This issue is fixed at [31d74177ca2df63df2bc395421b9a6ba29071044](https://github.com/mono/mono/commit/31d74177ca2df63df2bc395421b9a6ba29071044). @marek-safar it may be a good idea to cherry-pick it for next release since it's low-impact.

@igorzigorz can you please add [this specific patch](https://github.com/rootwyrm/freebsd-mono/blob/master/lang/mono6.0/files/patch-31d74177ca2df63df2bc395421b9a6ba29071044.diff) from my ports repo and see if this persists in the meantime?

**Comment by igorzigorz** [comment]
Now is Ok.
