### ISSUE TITLE
mkbundle linux - undefined reference to `__cxa_begin_catch'

### ISSUE THREAD

**Issue by Clodo76** [mono/mono#16829]
## Steps to Reproduce

1. - Steps of Mono Basics / Hello World https://www.mono-project.com/docs/getting-started/mono-basics/#console-hello-world
2.  mkbundle hello.exe -o hello --i18n all -L /usr/lib/mono/4.5

### Current Behavior

/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__gxx_personality_v0'
/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `typeinfo for int*'
collect2: error: ld returned 1 exit status
ERROR: [Fail] 256

## On which platforms did you notice this

Linux Ubuntu 19.04
Mono JIT compiler version 6.0.0.319
and 6.0.0.345

**Comment by directhex** [comment]
Can you try this instead:

```
mkbundle --fetch-target mono-6.0.0-ubuntu-18.04-x64
mkbundle hello.exe -o hello --cross mono-6.0.0-ubuntu-18.04-x64 --i18n all
```

**Comment by Clodo76** [comment]
Ok thanks, cross compile at least have another issue,
https://github.com/mono/mono/issues/7454
how i can tell to mkbundle to ignore Mono.WebBrowser assembly? I don't use it in any C# code.

**Comment by directhex** [comment]
Is it a Forms app?

**Comment by directhex** [comment]
OK, that's an easier fix.

**Comment by Clodo76** [comment]
Yes
`ERROR: Unable to load assembly `Mono.WebBrowser' referenced by `/home/clodo/.mono/targets/mono-5.10.0-debian-7-x64/lib/mono/4.5/System.Windows.Forms.dll'
`

I don't find the fix yet, how i can tell to mkbundle to ignore this dependencies? Or 'fake' it? Thx

**Comment by directhex** [comment]
You can fake a fix by just copying Mono.WebBrowser.dll from /usr/lib/mono/4.5/ into /home/clodo/.mono/targets/mono-5.10.0-debian-7-x64/lib/mono/4.5/

**Comment by Clodo76** [comment]
Thanks! 'Fake' Mono.WebBrowser works.


Now, i'm try to mkbundle a WinForms App from Ubuntu 19.04 and try the result on a fresh (without mono of course) Debian 10 x64.
(i know it's not maintainer anymore, i'm working on GTK# version of the app, but for the moment i need to deploy the old WinForms version)

It throw this error:

`[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeEngine' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeWin32Classic' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.so.0`

I found a libgdiplus.so.0 file that works placed in the same mkbundle-output directory.

Now, it throw the same error about another .so, but this time search it in / path, so a simple copy don't work. 
Set LD_LIBRARY_PATH and/or MONO_PATH don't work.
I'm studying ldd/chrpath to understand what i can do.

`[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Mono.Unix.Native.Syscall' threw an exception. ---> System.DllNotFoundException: /libMonoPosixHelper.so`

**Comment by directhex** [comment]
OK, now we're in the weeds

`mkbundle` bundles a config file, from `/home/clodo/.mono/targets/mono-5.10.0-debian-7-x64/etc/mono/config`, which has some special-casing for a small handful of libraries.

Take a local copy of that file, remove the special casing (i.e. `$mono_libdir/libMonoPosixHelper.so` -> `libMonoPosixHelper.so`) and pass `--config /path/to/new/mono/config`.

**Comment by directhex** [comment]
Also, you can embed libraries with `--library path/to/foo.so`

**Comment by Clodo76** [comment]
I resolved all issues, thanks thanks thanks!

**Comment by vikasjag** [comment]
I am also facing the same issue/ what's resolution ?

[execute cmd]: cc -ggdb -o 'QUTSStatus' -Wall  temp.c `pkg-config --cflags --libs mono-2`  temp.o
/usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__cxa_end_catch'
/usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `typeinfo for int*'
/usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__gxx_personality_v0'
/usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__cxa_begin_catch'
collect2: error: ld returned 1 exit status
ERROR: [Fail] 256


I am using ubuntu 16.0, I tried  
mkbundle --fetch-target mono-6.0.0-ubuntu-16.04-x64

and then added --cross mono-6.0.0-ubuntu-16.04-x64

ERROR: The specified SDK path does not exist: /usr2/vikasj/.mono/targets/mono-6.0.0-ubuntu-16.04-x64

my command for building is 
sudo mkbundle AppName.exe -o AppName --i18n all -L /usr/lib/mono/2.0-api/ --cross mono-6.0.0-ubuntu-16.04-x64 -v
