### ISSUE TITLE
what difference between mono_array_set and mono_array_setref?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#16845]
what difference between **mono_array_set** and **mono_array_setref**?

```c
MonoObject* Obj;
MonoArray* Array;
mono_array_set(Array, MonoObject*, 0, Obj);
mono_array_setref(Array, 0, Obj);
```

I am confused this two method difference, and which is the correct way to set?

**Comment by jaykrell** [comment]
"ref" means "managed pointer" means barrier

```
#define mono_array_set_internal(array,type,index,value)	\
	do {	\
		type *__p = (type *) mono_array_addr_internal ((array), type, (index));	\
		*__p = (value);	\
	} while (0)
#define mono_array_setref_internal(array,index,value)	\
	do {	\
		void **__p = (void **) mono_array_addr_internal ((array), void*, (index));	\
		mono_gc_wbarrier_set_arrayref_internal ((array), __p, (MonoObject*)(value));	\
		/* *__p = (value);*/	\
	} while (0)
```

**Comment by srxqds** [comment]
> "ref" means "managed pointer" means barrier
> 
> ```
> #define mono_array_set_internal(array,type,index,value)	\
> 	do {	\
> 		type *__p = (type *) mono_array_addr_internal ((array), type, (index));	\
> 		*__p = (value);	\
> 	} while (0)
> #define mono_array_setref_internal(array,index,value)	\
> 	do {	\
> 		void **__p = (void **) mono_array_addr_internal ((array), void*, (index));	\
> 		mono_gc_wbarrier_set_arrayref_internal ((array), __p, (MonoObject*)(value));	\
> 		/* *__p = (value);*/	\
> 	} while (0)
> ```


If I use **mono_array_setref**, It means that the **Obj** lifetime is depend on the **Array**, it is that If the **Array** became free than the **Obj** must be freed?

And if I **use mono_array_set**, It means that the **Array** don't keep the **Obj** references, it is said that the **Obj** gc will not rely on the **Array**?

**Comment by jaykrell** [comment]
The array always keeps alive objects it has pointers to.
Setref is needed for correct GC behavior.

**Comment by srxqds** [comment]
> eded for correct GC be

Ok, Thank you!
but what scenarios do you need using **mono_array_setref** api?

**Comment by jaykrell** [comment]
When the array contains objects (instead of, like, ints, floats).
