### ISSUE TITLE
[Wasm] Switch to PNSE FileWatcher & Exclude Tests

### ISSUE THREAD

**Issue by steveisok** [mono/mono#16876]
The FileWatcher accounts for most of the failures found in System w/ xunit.  We need to a version that throws PNSE.

- [ ] Create PNSE version of the FileWatcher class
- [ ] Exclude the FileWatcher tests (both xunit and nunit if applicable)

**Comment by MaximLipnin** [comment]
Part of https://github.com/mono/mono/issues/16858
