### ISSUE TITLE
Upgrade LLVM to 9.0

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#16893]
We need to upgrade to LLVM 9.0 to be able to use some of the new features.

We already have version in our fork https://github.com/mono/llvm/commits/release_90

**Comment by imhameed** [comment]
Related: https://github.com/mono/mono/issues/8791

**Comment by vargaz** [comment]
How should we maintain our changes on top of upstream when switching to llvm 9.0 ?
We can either:
- just rebase them on top of 9.0.
- clean them up by merging changes together etc. so the set of patches is smaller.

**Comment by vargaz** [comment]
Made a new branch which merges some of the commits from release_60:
https://github.com/mono/llvm/tree/release_90-2
It should in sync with 76f65d611fbf31890d79fd278e89cd889bf1c497 of the release_60 branch, need to add the rest.

**Comment by SamMonoRT** [comment]
@imhameed - with your recent PR, close this out.

**Comment by SamMonoRT** [comment]
This is completed few months ago. Closing this issue.
