### ISSUE TITLE
XmlSerializer Deserializing Property with same name as its enum type no longer works

### ISSUE THREAD

**Issue by devobra** [mono/mono#16918]
## Steps to Reproduce

Android
1. Download attached project and launch debug for BugReproduction-Deserialize-Android
2. Press the + floating action button to serialize/deserialize the test class that has 5 enum properties with the same name as the enum.
3. A toast will inform you which of the 5 properties deserialized properly and which didn't.

iOS
Same as Android, just debug BugReproduction-Deserialize-iOS and press the Button

[BugReproduction-Deserialize.zip](https://github.com/mono/mono/files/3627930/BugReproduction-Deserialize.zip)

### Current Behavior

Deserializing an Object Property which has the same name as the type of enum it contains has unpredictable results. It can succeed or fail depending on the specific number of fields in the Class and whether those fields have the same name as their type.

In addition, if the object being created has a Property that accepts objects, the XmlSerializer may set one of the XmlNodes it failed to read as the value of such a Property.

### Expected Behavior

Deserializing an Object Property which has the same name as the type of enum it contains works like any other property.

## On which platforms did you notice this

[X] Xamarin iOS
[X] Xamarin Android
[X] Xamarin Mac
[  ] .Net Console Project on Visual Studio for Mac

**Version Used**:

Mono Framework MDK
Runtime:
	Mono 6.0.0.334 (2019-02/6256b82d62f) (64-bit)
	Package version: 600000334

This specific problem with deserialization appears to be new. I do not know when it broke exactly but I believe it was working with Mono 5.14 Commit 000780ca. It does not happen on a .Net console project that uses Mono, so it may be specific to the Mono version that is bundled with Xamarin.

## Stacktrace

no stack trace.

The XmlSerializer fires the UnknownElement event for each Property that fails to deserialize.

Edit : updated to add that the bug also occurs on Xamarin Mac but not in a Dot Net console application that uses Mono.

**Comment by marek-safar** [comment]
@steveisok, please check if it's a regression

**Comment by devobra** [comment]
Just a hunch, but given that :

-the Serializer code doesn't seem to have changed in a long time
-the bug can cause objects to end up in the wrong field (an XmlNode ends up in one of the fields of the object being created)

The problem could be a bug with Reflection rather than with the Serializer itself.

**Comment by steveisok** [comment]
We think the bug was at least surfaced w/ this commit and are trying to figure out if it applies the mobile profile only.

https://github.com/mono/mono/pull/11194/files#diff-ae54d9565e735005686191de0f19ed50R431-R435

TBH @devlead, I wondered the same thing re: reflection.
