### ISSUE TITLE
Reopen #9883, mono-basic repository is inactive

### ISSUE THREAD

**Issue by FalcoGer** [mono/mono#16932]
Reopening: https://github.com/mono/mono/issues/9883
Reason:
The issue was closed and directed to https://github.com/mono/mono-basic/issues/52
However the issue (or any other issue there) has not been addressed in nearly a year. the repository had no commits for a very long time.

Related:
https://github.com/mono/mono/issues/9883
https://github.com/mono/mono/issues/10066
https://github.com/mono/mono-basic/issues/52

## Steps to Reproduce

1. Use Apache with ModMono to run aspx.vb code
2. Try and call it
3. Receive #ExternalChecksum error

### Current Behavior

Page does not compile

### Expected Behavior

Page Compiles

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Comment by MattL0** [comment]
+ 1 needs a fix...

**Comment by marek-safar** [comment]
Closing, original issue is still active
