### ISSUE TITLE
ves_icall_System_Globalization_CultureInfo_internal_get_cultures allocates handles in a loop

### ISSUE THREAD

**Issue by CoffeeFlux** [mono/mono#16957]
Found by running `make prepare-external-git-dependencies` in xamarin-android.

Log:
```
ves_icall_System_Globalization_CultureInfo_internal_get_cultures_raw USED 266 handles

ves_icall_System_Globalization_CultureInfo_internal_get_cultures_raw USED 416 handles

ves_icall_System_Globalization_CultureInfo_internal_get_cultures_raw USED 680 handles
```

**Comment by jaykrell** [comment]
Is this up to date?

**Comment by jaykrell** [comment]
Most likely fixed here:

ommit 2f0cbb5aa5801144aa887a164f4c95ef146686a8
Author: Aleksey Kliger (<CE><BB>geek) <alklig@microsoft.com>
Date:   Mon Aug 19 11:01:09 2019 -0400

    [coop] Add a handle frame in construct_culture (#16299)

    Otherwise we see warnings like these:

    ```
    ves_icall_System_Globalization_CultureInfo_internal_get_cultures_raw USED 680 handles
    ```

**Comment by CoffeeFlux** [comment]
Huh, I installed a freshly built mono last night. Wonder if it wasn't using that for some reason.

**Comment by CoffeeFlux** [comment]
Okay, issue was versioning-related on my end. This is indeed fixed.
