### ISSUE TITLE
[RFC] Improve vector allocation pattern compatibility

### ISSUE THREAD

**Issue by nsivov** [mono/mono#16988]
Found this issue while trying to make Quest for Wartorn Brotherhood game [1] run with wine + wine-mono.

Game is doing unsafe access to byte vector returned from Encoding.UTF8.GetBytes(string). That pointer is later assumed to be null-terminated utf-8 string. In mono is not the case, leading additional garbage data to be read past vector size. As a result game is unable to find its assets.

Below there's a fix attached for all GC implementations, I'm filing issue here instead of a PR to get some feedback if such fix will be conceptually acceptable. 

### Current Behavior

Allocation of byte[] array on alignment boundary gives exactly number of bytes requested.

### Expected Behavior

Allocated vector has some zero-filled padding after requested size.

## On which platforms did you notice this

This would be consistent on all platform, and is different from .NET 4.x behavior.

Attaching proposed solution that allocates additional sizeof(void*)/sizeof(native int) bytes, for simplicity it affects only vectors, regardless of element type. It was tested, game is playable with it.

[0001-mono-Pad-vector-data-with-additional-sizeof-void-of-by.txt](https://github.com/mono/mono/files/3640999/0001-mono-Pad-vector-data-with-additional-sizeof-void-of-by.txt)

[1] https://store.steampowered.com/app/1076830/Quest_For_Wartorn_Brotherhood/

**Comment by jaykrell** [comment]
It seems a slippery slope. Growing some allocations by some amount to accommodate buffer over reads and writes.

**Comment by marek-safar** [comment]
@BrzVlad your thoughts on this?

**Comment by BrzVlad** [comment]
The GC is of no relevance in this issue, so your fix wouldn't be accepted. If any fix were to happen on mono side, it would be related to the UTF8 encoding on the bcl class. As far as I can tell, mono and .net use the same encoding implementation, which would mean it doesn't add a null terminator. If that is the case, even on .net the game accesses an array past its `bytes.Length` which is wrong. They should fix their unsafe usage.

I don't understand why they would do that though. In managed you can just access the string and, if passed to native code, the string is marshaled by default to a C string (which is null terminated).

**Comment by nsivov** [comment]
It's relevant to how array memory is allocated, not specific to garbage collection in particular of course. It's not a problem on encoding classes side, but just some implementation details level of difference that application depends on. Regarding marshalling aspect, I don't think it applies here because GetBytes() returns byte[] array, not a string, unless marshalling logic is being extra smart to always assume byte arrays to be C strings.

**Comment by BrzVlad** [comment]
We shouldn't simple allocate unused memory for objects just because somebody might use unsafe code and expect data after it. Assuming the access happens in native, they would marshal the string directly instead (as a normal C string) not the bytes array.

**Comment by nsivov** [comment]
Just to make sure I understand, you're suggesting to stay clear from passing pointer to byte[] array, and use regular char[] string, filled with GetChars() perhaps or some other way. Or, alternatively, passing length along with pointer. Either way moving such fixup to application code?

**Comment by BrzVlad** [comment]
I'm suggesting that the fix should happen on the application code. I don't know exactly what their scenario is, but I'm assuming they have a string in c# code and they want to pass it to some native code (as a C string) which uses the string to load some files and stuff. If that is the case they shouldn't use any encoding stuff. They can have on native side a method that receives as an argument as a C string. While on the C# side they would do something like this : 

```
[DllImport("libtest.so")]
public static extern int native_method (string str);
```

And that's it. Calling `native_method` does the marshaling behind the scenes for you (converting from C# string to ansi string)

**Comment by nsivov** [comment]
Ok, thank you for your feedback. I'm going to close this.
