### ISSUE TITLE
Why I upgrade so slow?

### ISSUE THREAD

**Issue by erikaemma** [mono/mono#16983]
I run `sudo apt dist-upgrade -y` on my Ubuntu 16.04, I have tried all my proxy on ShadowSocksR from China, but no one work, a 21.7mb size file download 5 hours and not finish.
All proxy works fine with dropbox, browsers and other package by apt.

**Comment by marek-safar** [comment]
We are not hosting any distros packages and I don't think we can do much about this.

/cc @directhex

**Comment by directhex** [comment]
Our repos are behind Azure CDN (Edgecast-backed). I think there are gaps in China coverage on that, but not a lot we can do as a team (we can't get service via Azure China, and the separate CDN used for capital-P Products isn't suitable for us)
