### ISSUE TITLE
[merp] crash reports have Darwin kernel version in OSVersion field

### ISSUE THREAD

**Issue by kdubau** [mono/mono#17004]
## Steps to Reproduce

1. Induce a crash from VSM (so merp is enabled)
2. Look at the merp payload available in the merp dialog

### Current Behavior

The parameters field currently looks something like this: 
```	"parameters" : 
        {
		"ApplicationBundleId" : "com.microsoft.visual-studio",
		"ApplicationVersion" : "8.5.0.114",
		"ApplicationBitness" : "x64",
		"ApplicationName" : "Visual Studio",
		"BlameModuleName" : "Mono Exception",
		"BlameModuleVersion" : "6.7.0.562 (master/db626fe9d37 Thu Sep  5 00:00:34 EDT 2
                 .....
		"OSVersion" : "18.7.0",
		"LanguageID" : "0x7f",
		"SystemManufacturer" : "apple",
		"SystemModel" : "MacBookPro15,1",
		"EventType" : "AppleAppCrash"
	}
```

Notice OS Version is `18.7.0` which is actually the kernel version.

### Expected Behavior

I expected the OS Version to be the macOS version, for example `10.14.6`.   There is no clear mapping of kernel version to OS version as some macOS versions share kernel versions.   

I would also be okay with capturing both versions!

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Comment by kdubau** [comment]
@leculver if we add another param for the real OS version (or rather add a KernelVersion field) would we need to bump the protocol version?

**Comment by leculver** [comment]
No.  As long as it goes into the .json file (not .xml) and doesn't fundamentally change how we use the file we don't need to bump version.  Just adding extra parameters and info does not need a version bump.

________________________________

**Comment by lambdageek** [comment]
Turns out it's actually pretty non-trivial to get the product version of OSX from C.

There are two workable options:
1. Use the deprecated CoreServices `Gestalt` API 
2. On OSX 10.13.6 or newer use `sysctlbyname ("kern.osproductversion", ...)`

Source: [this SO answer](https://stackoverflow.com/a/54486355/570682)

Here's a sample I cooked up:
```c
/* clang -o uname-test uname-test.c -framework CoreServices */

#include <sys/utsname.h>
#include <stdio.h>
#include <sys/errno.h>
#include <string.h>

#include <CoreServices/CoreServices.h>

#include <sys/sysctl.h>

int GetGestaltProductVersion (void)
{
	SInt32 major,minor,bugFix;

	Gestalt(gestaltSystemVersionMajor, &major);
	Gestalt(gestaltSystemVersionMinor, &minor);
	Gestalt(gestaltSystemVersionBugFix, &bugFix);

	printf("gestalt: %d.%d.%d\n",major,minor,bugFix);    

	return 0;
}

void
GetSysVer (void)
{
	/* 10.13.6 or later */
	const char *q = "kern.osproductversion";
	size_t len = 0;
	if (sysctlbyname (q, NULL, &len, NULL, 0) == -1) {
		printf ("sysctl error: %s\n", strerror (errno));
	} else {
		char *s = malloc (len+1);
		if (sysctlbyname (q, s, &len, NULL, 0) == -1) {
			printf ("2nd sysctl error: %s\n", strerror (errno));
		} else {
			printf ("sysctl version: %s\n", s);
		}
		free (s);
	}
}

int
main (void)
{
	struct utsname name;

	if (uname (&name) >= 0) {
		printf ("release: %s\n", name.release);
		printf ("version: %s\n", name.version);
	} else {
		printf ("%s\n", strerror (errno));
	}

	GetGestaltProductVersion();

	GetSysVer ();
}
```

Prints this on my machine:
```
release: 18.7.0
version: Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
gestalt: 10.14.6
sysctl version: 10.14.6
```

**Comment by lambdageek** [comment]
@kdubau It would probably be easier for VSfM to drop grab the OSX product version from C# using `NSProcessInfo` and pass it to crash reporting in the extra info blob via `AnnotateMicrosoftTelemetry`.

Apparently in Obj-C it's as simple as:

```objc
[[NSProcessInfo processInfo] operatingSystemVersion]
```

But I don't think we have any Obj-C code in mono proper, not sure how much work it would be to add to our build scripts.

**Comment by leculver** [comment]
We are about to have to do some work in Mono + VS4M to change the eventtype and other parameters for MERP reporting.  We could probably wrap this change into our work when we work on the startup path here.  Can we leave this issue open for another day or two without resolution?

I’m just coming back from vacation and trying to the complicated work we have to do here planned and scheduled.

Thanks!

**Comment by jaykrell** [comment]
What happens if you just put that snippet in an `.m` file?

**Comment by kdubau** [comment]
@lambdageek how about something simple like this? https://github.com/mono/mono/pull/17130

If we only use `AnnotateMicrosoftTelemetry` from VSM, we would have to have a well-known key to look it up when uploading, because this value is needed in the XML payload for proper bucketing on the backend. 

I think this implementation is a bit cleaner than relying on looking it up in the annotations. For older OS's we will only have the `{major}.{minor}` but I think it's okay.  If we ever needed the patch version for technical reasons, we can additionally use the `AnnotateMicrosoftTelemetry` to add a full version if we really need it.

**Comment by kdubau** [comment]
Newer macOS versions will have `kern.osproductversion` and thus give the full version.
