### ISSUE TITLE
Release notes for 6.4 are missing

### ISSUE THREAD

**Issue by rmunn** [mono/mono#17021]
It's happened again. Just as with the Mono 6.0 release (#16147, https://github.com/mono/website/issues/452), Mono 6.4 was [pushed to the stable channel](https://github.com/mono/website/commit/c9504c14855b6217925f0a130ec44f8cb45ab3da) without any release notes being ready. Once could be a coincidence, but twice in a row is starting to look like there's a mistake somewhere in the build process, which allows releases to be pushed out before they're actually considered ready. I've opened https://github.com/mono/website/issues/459 to help track the release notes for 6.4, and I'm opening this issue on the main repo to track figuring out the problem in the build process, so that someone can figure out what is allowing releases to go out with no release notes.

**Comment by akoeplinger** [comment]
I've just published the release notes, thanks for keeping us honest :)

We missed it this time due to this release being coupled with the .NET Core 3.0 and Visual Studio for Mac 8.3 releases and some misunderstanding about who would cover the Mono release notes.
