### ISSUE TITLE
[Linux] Add initial perf jitdump support

### ISSUE THREAD

**Issue by migueldeicaza** [mono/mono#17024]
This is a duplicate of an issue filed for CoreCLR, that makes plenty of sense, and would help us track down the performance issues that Mono has on Linux.

The rest of this text is a copy of the original bug: https://github.com/dotnet/coreclr/issues/26842

Linux uses the perf tools to profile application. The linux 4.10 kernel added support for a `perf jitdump` format.

It has allows better JIT support for perf. Specifically allowing adding:

* native code so perf can show disassembly of JIT functions.
* adding debug info to support source line annotation.
* adding unwind info to better support stack unwind.

The app must:

* create the jitdump file [Specification](https://elixir.bootlin.com/linux/v4.10/source/tools/perf/Documentation/jitdump-specification.txt)
* Inform perf inject of its presence by calling `mmap` with the filename.
* Add `JIT_CODE_LOAD` records
* Optionally add `JIT_DEBUG_INFO` records
* Optionally add `JIT_CODE_UNWINDING_INFO` records

It is used like this

```
perf record <app>
perf inject --jit
perf report
```

**Comment by SamMonoRT** [comment]
@fanyang-mono - this is something you should start understanding and working on. We can talk more tomorrow.

**Comment by fanyang-mono** [comment]
Documented the requirements here (in progress): https://paper.dropbox.com/doc/Mono-jitdump-support--AveQ59UM3bsLUncndIqKPfsOAg-R1vzCl2CWdeWeac1uyP2X
