### ISSUE TITLE
LLVM JIT doesn't use -place-safepoints pass

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#17059]
Let's say I have a simple method:
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
static int Foo()
{
    int x = 0;
    for (int i=0; i<10; i++) 
        x++;
    return x;
}
```
As you can see it's pretty simple and LLVM should be able to replace it all with just `return 10;`
If I run it with `--llvm` (JIT) it compiles to:
```asm
0000000000000000 <loWorld_Program_Foo___>:
<BB>:1
   0:   50                      push   %rax
   1:   48 b9 68 fe 9c b0 57    movabs $0x7f57b09cfe68,%rcx
   8:   7f 00 00
   b:   48 83 39 00             cmpq   $0x0,(%rcx)
   f:   75 1a                   jne    2b <loWorld_Program_Foo___+0x2b>
  11:   ba 0a 00 00 00          mov    $0xa,%edx
  16:   48 be 38 44 60 02 00    movabs $0x2604438,%rsi
  1d:   00 00 00
  20:   85 d2                   test   %edx,%edx
  22:   75 33                   jne    57 <loWorld_Program_Foo___+0x57>
  24:   b8 0a 00 00 00          mov    $0xa,%eax
  29:   59                      pop    %rcx
  2a:   c3                      retq
  2b:   48 b8 30 44 60 02 00    movabs $0x2604430,%rax
  32:   00 00 00
  35:   ff 10                   callq  *(%rax)
  37:   ba 0a 00 00 00          mov    $0xa,%edx
  3c:   48 be 38 44 60 02 00    movabs $0x2604438,%rsi
  43:   00 00 00
  46:   85 d2                   test   %edx,%edx
  48:   75 0d                   jne    57 <loWorld_Program_Foo___+0x57>
  4a:   eb d8                   jmp    24 <loWorld_Program_Foo___+0x24>
  4c:   0f 1f 40 00             nopl   0x0(%rax)
  50:   83 c2 ff                add    $0xffffffff,%edx
  53:   85 d2                   test   %edx,%edx
  55:   74 cd                   je     24 <loWorld_Program_Foo___+0x24>
  57:   48 83 39 00             cmpq   $0x0,(%rcx)
  5b:   74 f3                   je     50 <loWorld_Program_Foo___+0x50>
  5d:   ff 16                   callq  *(%rsi)
  5f:   eb ef                   jmp    50 <loWorld_Program_Foo___+0x50>
```
It happens because we emit `mono_threads_state_poll` twice (including the loop) and LLVM is not able to optimize it anymore. This problem was solved in our LLVM AOT mode by using a special pass to place the safepoints in the end after all optimization finished (see https://github.com/mono/mono/pull/11789).
So the same codegen in LLVM AOT looks like this:
```asm
0000000000000000 <loWorld_Program_Foo___>:
<BB>:1
   0:   b8 0a 00 00 00          mov    $0xa,%eax
   5:   c3                      retq
```

The problem can be also solved for LLVM JIT by enabled `MONO_THREADS_SUSPEND=preemptive` (doesn't emit state polls) so it also will generate:
```asm
0000000000000000 <loWorld_Program_Foo___>:
<BB>:1
   0:   b8 0a 00 00 00          mov    $0xa,%eax
   5:   c3                      retq
```

So we should either use `preemptive` mode by default in LLVM JIT or use `-place-safepoints` pass (e.g. to put `-place-safepoints -spp-all-backedges` [here](https://github.com/mono/mono/blob/master/mono/mini/llvm-jit.cpp#L293)).

PS: when I benchmark Mono-LLVM I usually use `preemptive` mode.

**Comment by filipnavara** [comment]
I don't think we should go back to `preemptive` suspends. It is very hard to reason about its correctness. Switching to the `-place-safepoints` pass sounds reasonable as long as all the cases like mini JIT fallback are handled correctly.

**Comment by migueldeicaza** [comment]
I still think that until coop mode is good enough, we should default to `preemptive` across the board, and that includes the AOT mode with LLVM.   

That said, I wonder if there is some way of annotating the call to the `mono_threads_state_poll` in a way that would allow LLVM to remove it

**Comment by migueldeicaza** [comment]
Zoltan has explained to me that the LLVM place-safepoints pass is responsible for this.
