### ISSUE TITLE
Regression: when debugger encounters a not-unhandled exception, it stops and shows "Dns.cs file not found" (Dns being the BCL class used)

### ISSUE THREAD

**Issue by knocte** [mono/mono#17083]
I believe this is a regression because I haven't seen this behaviour in previous versions of VisualStudio for Mac (now using 8.2.4; not sure the exact version when this started happening, possibly when Mono 6.0 was bundled).

Steps to reproduce:
1. Open VS4Mac, create new project/solution, Console type, language: C#.
2. Use this simple snippet:

```
using System;
using System.Linq;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Threading.Tasks;

namespace TestResolveCSharpConsole
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            try
            {
                var results = ResolveAsync().GetAwaiter().GetResult();
            }
            catch (SocketException sockEx)
            {
                Console.WriteLine("correctly handled");
            }
        }

        public static async Task<List<string>> ResolveAsync()
        {
            var addresses = await System.Net.Dns.GetHostAddressesAsync("foo.bar.baz");
            return new List<string>(addresses.Select(addr => addr.ToString()));
        }
    }
}
```

3. Compile it. (If you run it outside VS4Mac, result should just be the printing of the string "correctly handled".)
4. Run it with the debugger inside VS4Mac.

Expected results:
Should just run it and not stop, finish execution at the end like it's the case when being run outside of VS4Mac.

Current results:
Debugger seems to bomb when a `SocketException` is thrown, even if it's properly handled with a try-catch (this is the first bug). Then it tries to open the source code of the BCL where this exception happened (Dns.cs), telling the weird error "Source Not Found" to the user.

See screenshot:
<img width="1270" alt="Screenshot 2019-08-28 at 3 56 16 PM" src="https://user-images.githubusercontent.com/331303/63837030-46735700-c9ad-11e9-9d23-c24a2e133601.png">

> VS bug [#973786](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/973786), VS bug [#989287](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/989287)

**Comment by marek-safar** [comment]
Is this really regression? It feels to me from the description the sourcelink made this more likely happen, right?

**Comment by knocte** [comment]
> Is this really regression?

I've been running VS4Mac debugging sessions many times in the past with handled exceptions, and never got this behaviour, until recently.

**Comment by nosami** [comment]
@marek-safar this is a regression in Mono, not VSMac. I know this because the bug  reproduces with an old VSMac (before Source link)  with Mono 6.4.0.198
