### ISSUE TITLE
Marshalling managed exception contains cut off stacktraces

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#17084]
_From @Therzok on Thu, 26 Sep 2019 15:12:34 GMT_

### Steps to Reproduce

1. Run the sample zip
2. Click on the window.

### Expected Behavior
There should be an exception logged by the application
```
System.Exception: e
  at bubbleexception.ViewController.MouseDown () [0x00009] in /Users/therzok/Projects/bubbleexception/bubbleexception/ViewController.cs:25 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.2.0.42/src/Xamarin.Mac/AppKit/NSApplication.cs:100 
  at bubbleexception.MainClass.Main (System.String[] args) [0x00005] in /Users/therzok/Projects/bubbleexception/bubbleexception/Main.cs:14 
```

### Actual Behavior
The exception is only partly shown, seemingly only for the inner exception

```
System.Exception: e
  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.2.0.42/src/Xamarin.Mac/AppKit/NSApplication.cs:100 
  at bubbleexception.MainClass.Main (System.String[] args) [0x00008] in /Users/therzok/Projects/bubbleexception/bubbleexception/Main.cs:14 
```

### Environment

<!--
1.
```

Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]
2. Paste into the code block below (between ```)
-->

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.3.1 (build 6)
Installation UUID: 010a6a17-65d7-44f0-9e3d-48e5afe82e81
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 606000082

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.82 (2019-08/70d69030534) (64-bit)
	Package version: 606000082

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	3.0.100-rc1-014190
	3.0.100-preview9-014004
	3.0.100-preview8-013656
	3.0.100-preview6-012264
	2.2.203
	2.1.701
	2.1.700
	2.1.603
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	3.0.0-rc1-19456-20
	3.0.0-preview9-19423-09
	3.0.0-preview6-27804-01
	2.2.7
	2.2.4
	2.1.12
	2.1.11
	2.1.10

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Enterprise)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Enterprise)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.244
Hash: e15b2ee97
Branch: remotes/origin/d16-3
Build date: 2019-09-25 00:03:16 UTC

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Enterprise)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/therzok/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.0

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/therzok/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803010006
Git revision: e4b65219fee9cb778751f3bae5b305111c51c46b
Build date: 2019-09-25 18:56:10+00
Build branch: release-8.3
Xamarin extensions: 17def12334dfec3725cc3b26d3f79b621182e4a1

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Log Monitor 0.2

```

### Build Logs

<!--
1. Place cursor below this comment block.
2. Attach build log or link to gist (https://gist.github.com/) of the log.
3. Logs can be found in the Build Output tab of the Errors pad in Visual Studio
To get full build logs, set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run
On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
-->

### Example Project (If Possible)

<!--
1. Place cursor below this comment block.
2. Drag and drop the compressed project or files needed to reproduce.
-->

<!--
Switch to the "Preview" tab to ensure your issue renders correctly.
-->
[bubbleexception.zip](https://github.com/xamarin/xamarin-macios/files/3658472/bubbleexception.zip)


_Copied from original issue xamarin/xamarin-macios#7117_

**Comment by rolfbjarne** [comment]
_From @Therzok on Thu, 26 Sep 2019 15:16:24 GMT_

Curious to note, is that if I put it in ViewDidLoad, I get the following results:
```
System.Exception: e.outer ---> System.Exception: e.inner
  at bubbleexception.AppDelegate.ThrowInner () [0x00000] in /Users/therzok/Projects/bubbleexception/bubbleexception/AppDelegate.cs:45 
  at bubbleexception.AppDelegate.ThrowExceptionWithInner () [0x00000] in /Users/therzok/Projects/bubbleexception/bubbleexception/AppDelegate.cs:36 
   --- End of inner exception stack trace ---
  at bubbleexception.AppDelegate.ThrowExceptionWithInner () [0x00009] in /Users/therzok/Projects/bubbleexception/bubbleexception/AppDelegate.cs:39 
  at bubbleexception.AppDelegate.WillTerminate (Foundation.NSNotification notification) [0x00000] in /Users/therzok/Projects/bubbleexception/bubbleexception/AppDelegate.cs:24 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.2.0.42/src/Xamarin.Mac/AppKit/NSApplication.cs:100 
  at bubbleexception.MainClass.Main (System.String[] args) [0x00005] in /Users/therzok/Projects/bubbleexception/bubbleexception/Main.cs:14 
```

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Thu, 26 Sep 2019 15:32:18 GMT_

This only happens when debugging.

If I run without the debugger, I get: 

```
System.Exception: e
  at bubbleexception.ViewController.MouseDown (AppKit.NSEvent theEvent) [0x00009] in /Users/rolf/Downloads/bubbleexception/bubbleexception/ViewController.cs:25 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /work/maccore/master/xamarin-macios/src/AppKit/NSApplication.cs:100 
  at bubbleexception.MainClass.Main (System.String[] args) [0x00008] in /Users/rolf/Downloads/bubbleexception/bubbleexception/Main.cs:14 
```

**Comment by rolfbjarne** [comment]
_From @Therzok on Thu, 26 Sep 2019 15:34:02 GMT_

We run vsmac with `--debug` always!

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Thu, 26 Sep 2019 15:35:07 GMT_

Also in this particular case we're not catching the managed exception and re-throwing it, we're letting mono handle everything.

Adding just this to the additional mtouch arguments: `--marshal-managed-exceptions=unwindnativecode` (and not passing `--marshal-objectivec-exceptions=...`) makes us catch and re-throw the exception, and the output turns out as expected:

```
System.Exception: e
  at bubbleexception.ViewController.MouseDown (AppKit.NSEvent theEvent) [0x00009] in /Users/rolf/Downloads/bubbleexception/bubbleexception/ViewController.cs:25 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /work/maccore/master/xamarin-macios/src/AppKit/NSApplication.cs:100 
  at bubbleexception.MainClass.Main (System.String[] args) [0x00008] in /Users/rolf/Downloads/bubbleexception/bubbleexception/Main.cs:14 
```

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Thu, 26 Sep 2019 15:37:38 GMT_

Since this is only an issue when debugging (and besides we're not catching and re-throwing the exception), I'm transferring it to mono.

**Comment by marek-safar** [comment]
@lambdageek please priority this

**Comment by jtorres** [comment]
we have few bugs depending on this, any update @lambdageek?

**Comment by Therzok** [comment]
Also, most likely we want this in 2019-06, as we don't have actionable bugs.

**Comment by Therzok** [comment]
Hey folks, I managed to pin it down to a simple determinant factor:
https://github.com/mono/monodevelop/pull/8833

preemptive suspend works fine. hybrid suspend behaves weirdly. `--debug` and having a debugger attached had no impact.

**Comment by Therzok** [comment]
Most likely that running the app under a debugger makes the app inherit environment variables from vsmac.

Here's the matrix of tests I've done, below:

| --debug | MONO_THREADS_SUSPEND | xammac registrar | stacktrace         |
|---------|----------------------|------------------|--------------------|
| yes     | default (hybrid)     | partial static   | :heavy_check_mark: |
| yes     | default (hybrid)     | full static      | :x:                |
| no      | default (hybrid)     | partial static   | :heavy_check_mark: |
| no      | default (hybrid)     | full static      | :x:                |
| yes     | preemptive           | partial static   | :heavy_check_mark: |
| yes     | preemptive           | full static      | :heavy_check_mark: |

**Comment by Therzok** [comment]
This leads me to believe that either hybrid suspend has some more requirements on exception throwing/rethrowing while preserving exceptions which xammac isn't satisfying, or there is an actual bug in mono.

Corresponding code in xammac that is handling exceptions (@rolfbjarne please correct me if I'm wrong):
https://github.com/xamarin/xamarin-macios/blob/04a4c3f2ce12907e13c67307c5b2247445026400/runtime/runtime.m#L2417-L2445

Another interesting read, which lead me to test preemptive suspend:
https://github.com/mono/mono/pull/10468

**Comment by lambdageek** [comment]
If I modify 'bubbleexception > Run > Configurations > Default' and explicitly add a 'MONO_THREAD_SUSPEND=xxxxx' option here's what I see when I run with debugging:

- `MONO_THREADS_SUSPEND=hybrid`
   - after I click on the view, the VS debugger stops at `throw new Excpeption ("e")`
   - I click Continue
   - I get the cut off stack trace in the output window
- `MONO_THREADS_SUSPEND=preemptive`
   - after I click on the view, the VS debugger doesn't stop
   - I get the full stack trace in the output window.

---

The same thing happens if I start the app with
```
MONO_THREADS_SUSPEND=xxxx MONO_ENV_OPTIONS="--debug --debugger-agent=address=127.0.0.1:8882,transport=dt_socket,server=y" open -a bubbleexception.app
```
and then connect with `sdb "connect 127.0.0.1 8882"`.  Preemptive suspend just exits without stopping in the debugger; hybrid suspend stops for an unhandled exception in the debugger and then I can continue.

---

However, if I do this:
```
   cd bubbleexception.app
   cd Contents/MacOS
   cp `which mono` .
   MONO_THREADS_SUSPEND=xxxxx MONO_PATH=../MonoBundle DYLD_LIBRARY_PATH=/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/ ./mono --debug --debugger-agent=address=127.0.0.1:8882,transport=dt_socket,server=y ../MonoBundle/bubbleexception.exe
```
and then `sdb "connect 127.0.0.1 8882"`

with both hybrid and preemptive suspend I get the expected behavior: exception is caught in the debugger and after I continue the full stack trace is shown.

So it's something about how the app bundle starts up mono that is affected by the suspend mechanism and/or debugging.

**Comment by lambdageek** [comment]
> Adding just this to the additional mtouch arguments: `--marshal-managed-exceptions=unwindnativecode` (and not passing --marshal-objectivec-exceptions=...) makes us catch and re-throw the exception, and the output turns out as expected

Can confirm that with 'bubbleexception > Run > Configurations > Default' setting `MONO_THREADS_SUSPEND` to either `hybrid` or `preemptive` makes the debugger behave as expected if we build with `unwindnativecode`.

If I explicitly set `--marshal-managed-exceptions=default`, I get the bad behavior again.

I thought `unwindnativecode` **is** the default.

**Comment by Therzok** [comment]
So, given the xammac dynamic registrar is the only difference I've seen, here is:

* Our stub launcher: https://github.com/mono/monodevelop/blob/master/main/build/MacOSX/monostub.mm#L3-L348

* xammac: https://github.com/xamarin/xamarin-macios/blob/master/runtime/runtime.m#L2411-L2412

xamarin_create_classes only contains static registrar code, not sure if it's relevant here.

**Comment by rolfbjarne** [comment]
> I thought `unwindnativecode` **is** the default.

Kind of. The default is to not catch managed exceptions (i.e. pass NULL as the last argument to mono_runtime_invoke). With `unwindnativecode` we catch managed exceptions, but re-throw them. In theory the behavior should be the same (since in both cases we're letting mono unwind native code).

**Comment by thaystg** [comment]
We are working on this, we already understand what is going on and we are near to get a fix.
There is a draft open that maybe is the final fix.

**Comment by lambdageek** [comment]
Reopening until the backports land
