### ISSUE TITLE
System.Data.dll for Linux doesn't contain DbColumn class

### ISSUE THREAD

**Issue by ArsenShnurkov** [mono/mono#17096]
It is necessary to compile npgsql.dll

Schema/NpgsqlDbColumn.cs(23,35): error CS0246: The type or namespace name 'DbColumn' could not be found (are you missing a using directive or an assembly reference?)

See also:
https://github.com/mono/mono/blob/master/mcs/class/System.Data/linux_net_4_x_System.Data.dll.sources
https://github.com/mono/mono/blob/master/mcs/class/System.Data/unix_net_4_x_System.Data.dll.sources
https://github.com/mono/mono/blob/master/mcs/class/System.Data/net_4_x_System.Data.dll.sources
https://github.com/mono/mono/blob/master/mcs/class/System.Data/corefx.unix.sources

https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcolumn?view=netframework-4.8
Applies to
.NET Framework
4.8 4.7.2 4.7.1

https://www.mono-project.com/docs/about-mono/releases/5.18.0/
Reference assemblies for .NET 4.7.2 are included to allow targeting .NET Framework 4.7.2 using MSBuild on Mono.

**Comment by ArsenShnurkov** [comment]
https://www.npgsql.org/doc/api/Npgsql.Schema.DbColumn.html
is "used only in .NET Framework where we don't have it"

**Comment by marek-safar** [comment]
@akoeplinger thoughts on this?

**Comment by rjvdboon** [comment]
Shouldn't DbColumn be in System.Data as it is always included from corefx in https://github.com/mono/mono/blob/master/mcs/class/System.Data/corefx.common.sources#L85?

**Comment by ArsenShnurkov** [comment]
I already wrote that Microsoft have this class in the frameworks 
4.8
4.7.2
4.7.1
If mono claims that it implements 4.7.2, then the DbColumn class should be present.

**Comment by steveisok** [comment]
@ArsenShnurkov What version of mono and what version of linux are you using?  I've confirmed DbColumn is fully present on ubuntu.

**Comment by ArsenShnurkov** [comment]
1) I provided links to source codes, where the line DbColumn.cs it is clearly missed.
2) $ mono -V
Mono JIT compiler version 6.0.0.313 (tarball Wed Sep  4 18:12:17 MSK 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
3) Sabayon LInux

**Comment by directhex** [comment]
This is where it gets pulled in to the build: https://github.com/mono/mono/blob/master/mcs/class/System.Data/corefx.common.sources#L85

**Comment by ArsenShnurkov** [comment]
@directhex, but I am talking about mono, not about core.

**Comment by directhex** [comment]
@ArsenShnurkov https://github.com/mono/mono/blob/master/mcs/class/System.Data/net_4_x_System.Data.dll.sources#L1
