### ISSUE TITLE
System.Net.Security.SslStream for instance field 

### ISSUE THREAD

**Issue by tickwudi** [mono/mono#17107]
Exception:System.Net.Security.SslStream for instance field ServiceStack.Redis.RedisNativeClient:sslStream

mono:6.0.0.334

Last I delete code“protected SslStream sslStream;”

**Comment by tickwudi** [comment]
Centos 7

**Comment by marek-safar** [comment]
What does this mean?

**Comment by tickwudi** [comment]
Now exception:Could not load type of field 'System.Net.HttpWebRequest:tlsProvider' (49) due to: Could not resolve type with token 01000030 from typeref (expected class 'Mono.Security.Interface.MonoTlsProvider' in assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756') assembly:Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756 type:Mono.Security.Interface.MonoTlsProvider member:(null)

**Comment by tickwudi** [comment]
@marek-safar I don't know why!

**Comment by marek-safar** [comment]
This looks like some misconfiguration. You could try to run it with MONO_LOG_LEVEL=deug to get more details

**Comment by baulig** [comment]
This has been in "needs more info" for over two months, closing for now.
