### ISSUE TITLE
Application exception System.PlatformNotSupoorted: The FriendlyName value cannot be set on Unix

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17112]
The traceback:
![image](https://user-images.githubusercontent.com/5187024/65824660-321dc500-e29f-11e9-8af2-a74ce11b1ac5.png)

The new mono version not support it?

**Comment by baulig** [comment]
Our implementation closely follows CoreFX's code: https://github.com/dotnet/corefx/blob/7e9a177824cbefaee8985a9b517ebb0ea2e17a81/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/AppleCertificatePal.cs#L260

Where do you get that?

**Comment by directhex** [comment]
The throw comes from https://github.com/mono/mono/blob/master/mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2ImplUnix.cs#L110-L116

Which I assume comes from https://github.com/mono/mono/blob/master/mcs/class/System/System.Security.Cryptography.X509Certificates/X509Certificate2.cs#L205 

Is this a MonoUE-specific issue? Do we need @mhutch?

**Comment by baulig** [comment]
Yeah, but what's calling that?  The OP's screenshot lists `iPhonePackager.CodeSignatureBuilder.FindCertificates ()` - I was wondering where that code comes from as it needs to be changed to not use that unsupported API.

Moving forward, I do not want to implement an API that is not supported in CoreFX - if there are strong reasons to have that API, then we should discuss them with CoreFX and upstream those changes.

**Comment by mhutch** [comment]
@directhex this isn't MonoUE - UE uses Mono to run its build system

**Comment by directhex** [comment]
Oh, good point, I forgot about that

**Comment by directhex** [comment]
Setting up a UE dev environment on my Macbook. :sleeping:

**Comment by directhex** [comment]
This is worked around in UnrealEngine 4.23.1 https://github.com/EpicGames/UnrealEngine/commit/394886b4b0bd1e28fd1c008f1e505d9afeac4ca2 - please either:

* Downgrade Mono to 5.x
* Wait for UnrealEngine 4.23.1
* Build UnrealEngine from git (`4.23` branch)

**Comment by directhex** [comment]
I can't offer anything better than that. UE doesn't let me work on this stuff without signing up for an iOS developer account, and I don't have the energy to try & expense it

**Comment by srxqds** [comment]
We build ue4.23.2 source code and install mono-6..4.0.198 versions.
This is ue4 forums said:
https://forums.unrealengine.com/development-discussion/ios-development/1654462-friendlyname-value-cannot-be-set-on-unix-can-t-find-any-profiles-or-certificates
