### ISSUE TITLE
LLVM: --enable-llvm-asserts doesn't enable asserts

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#17115]
`--enable-llvm --enable-llvm-asserts` seems doesn't enable LLVM asserts, if I set `ON` here: https://github.com/mono/mono/blob/master/llvm/build.mk#L32 by hands - it works.
So I suspect `INTERNAL_LLVM_ASSERTS` is not passed to build.mk correctly.

**Comment by imhameed** [comment]
See also: https://github.com/mono/mono/issues/15565

**Comment by EgorBo** [comment]
Ah, dup
