### ISSUE TITLE
mono_threads_exit_gc_safe_region_unbalanced [0x3f8000003f800000] Cannot exit GC safe region on a different thread

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17117]
## Steps to Reproduce
I embedded mono, but on macos it crash. but windows correct.

### Current Behavior

crash

### Expected Behavior
what wrong with it and how to fixed it?

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
mono-6.0.0334

## Stacktrace

![image](https://user-images.githubusercontent.com/5187024/65844175-b63b7f80-e367-11e9-8e2a-2586f07bd390.png)

**Comment by srxqds** [comment]
what reason cause it? or what wrong we do cause it?

**Comment by srxqds** [comment]
I found the reason is like this issue said https://github.com/mono/mono/issues/15923

```c++
__declspec(align(n)) struct FPlane
{
float X;
float Y;
float Z;
float W;
FORCEINLINE FPlane();
FORCEINLINE FPlane(const FPlane& P);
FORCEINLINE FPlane(float InX, float InY, float InZ, float InW);
};

FPlane Internal_UKismetMathLibrary_MakePlaneFromPointAndNormal(FVector Point, FVector Normal)
{
	return UKismetMathLibrary::MakePlaneFromPointAndNormal(Point, Normal);
}
```

it crashed above when return from call **Internal_UKismetMathLibrary_MakePlaneFromPointAndNormal**.

I think it breaks the call stack ? But I don't know what is the exactly reason about it?

**Comment by lambdageek** [comment]
Not sure what is the cause.   The call to `mono_threads_exit_gc_safe_region_unbalanced` happens in the wrapper that Mono generates when a managed method is calling into unmanaged C/C++ code.  In this case the MonoThreadInfo before your C++ code runs and after your C++ code runs must match.  I don't know why it does not.  (The most common situation is if the native C/C++ code calls `mono_thread_detach` and then `mono_thread_attach` - but you're probably not doing that).

Is your code throwing a C++ exception?  I don't know if that would cause a problem like this, but it's possible that it would mess up some of Mono's internal bookkeeping.  (you should catch all C++ exceptions before returning from C++ to C#).

**Comment by srxqds** [comment]
hi, @lambdageek The code **MakePlaneFromPointAndNormal** don't throw a C++ exception. 

I make a proxy for **FPlane** which have not constructor, The crash disappear.

```c++
struct UNREALMONORUNTIME_API FPlane_Proxy
{
public:
	float X;
	float Y;
	float Z;
	float W;

    operator FPlane()
	{
		FPlane data;
		data.X = this->X;
		data.Y = this->Y;
		data.Z = this->Z;
		data.W = this->W;

		return data;
	}

	static FPlane_Proxy Proxy(const FPlane& data)
	{
		FPlane_Proxy proxy;
		proxy.X = data.X;
		proxy.Y = data.Y;
		proxy.Z = data.Z;
		proxy.W = data.W;

		return proxy;
	}
};

FPlane_Proxy Internal_UKismetMathLibrary_MakePlaneFromPointAndNormal(FVector Point, FVector Normal)
{
	return FPlane_Proxy::Proxy(UKismetMathLibrary::MakePlaneFromPointAndNormal(Point, Normal));
}
```
But I don't know what happens.
