### ISSUE TITLE
isolate mempool and code_mp by monoimage

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17121]
As we know on iOS platform don't support multiple domain, but we want to update our game script so we should unload the old assembly and reload the new one.

I think there are two problem should be solved:
  1. free the  **MonoMemPool(mp)**  and **MonoCodeManager(code_mp)** related with assembly alloc on MonoDomain.
  2. free the gc memory which are related with the assembly.

for the problem 1, my idea is that: The assembly of our script use it own **MonoMemPool(mp)** and **MonoCodeManager(code_mp)**, when I should unload the assembly I free the **mp** and **code_mp** directly. I use **mono_image_alloc** and **mono_image_code_reserve** replace of **mono_domain_alloc**、 **mono_domain_code_reserve** . But current problem is that how can I judge which one I can replace.

for the problem 2: I want to free the **MonoObject** owned by the assembly and then execute **mono_gc_collect**. But how can I iterate **MonoObject** at root? and how to free them?

may you help me or give some advice?

**Comment by BrzVlad** [comment]
I don't think you should mess with these internal structures. Unloading assemblies is part of the new set of features (AssemblyLoadContext), mainly for .NETCore. @lambdageek Any insight on this, does it work on iOS now ?

**Comment by lambdageek** [comment]
This doesn't work on iOS right now.  I do not think modifying the Mono runtime in an ad-hoc way to get it working will be very productive.

ALC support is currently being worked on in desktop Mono in the .NET Core-compatible configuration only.  At some future date after that, we may add it to the mobile platforms in some form.  Unloadable AssemblyLoadContext is also ongoing/future work.

**Comment by srxqds** [comment]
> This doesn't work on iOS right now. I do not think modifying the Mono runtime in an ad-hoc way to get it working will be very productive.
> 
> ALC support is currently being worked on in desktop Mono in the .NET Core-compatible configuration only. At some future date after that, we may add it to the mobile platforms in some form. Unloadable AssemblyLoadContext is also ongoing/future work.

Thank you for reply. Do the Unlloadable AssemblyLoadContext have the release version or date?
Is there some milestore or issues I can follow for the state?

**Comment by srxqds** [comment]
@marek-safar can you give me a confirm answer, thank you very much.

**Comment by srxqds** [comment]
> @marek-safar can you give me a confirm answer, thank you very much.

We have another idea to make **Assembly** unloadable: Can we make the appdomain unloadable on iOS? which is diffcult to do it?

@lambdageek @BrzVlad

**Comment by vargaz** [comment]
Unloading code is not supported by the mono runtime on ios, neither assembly unloading or appdomain unloading. A future version will hopefully support it, but there is no target date for that.
Your best bet is probably using the interpreter and simply loading new code, the old code will be kept by the runtime so memory usage will increase, but it will work for a while.

**Comment by srxqds** [comment]
@vargaz If we want to port code on iOS to support appdomain unloading, AssemblyLoadContext or free the memory used by MonoAssembly, which solution is more simple?
What problem we should consider to solve?
Why mono runtime on iOS not supoort it? How did you think about it?

**Comment by srxqds** [comment]
as this issuse said ios don't support multiple domain. https://github.com/mono/mono/issues/14465

But I find that there is only one place use the **DISABLE_APPDOMAINS** macro in **ves_icall_System_AppDomain_createDomain**. https://github.com/mono/mono/blob/6a1ac97dc757f7004f0d6160c4a9c8c19c587ae0/mono/metadata/appdomain.c#L1270

I means it seems not  restrict useing multi-domains at c/c++  sides when we embed mono?

If we just use multi-domains at c++ side what problem may occurs?

**Comment by srxqds** [comment]
> @vargaz If we want to port code on iOS to support appdomain unloading, AssemblyLoadContext or free the memory used by MonoAssembly, which solution is more simple?
> What problem we should consider to solve?
> Why mono runtime doesn't support that on iOS? How did you think about it?

@lambdageek can you help me? I want modify code to support multiple domain on ios and android, What should I do?

**Comment by srxqds** [comment]
use mult-domain can work
