### ISSUE TITLE
DriveInfo return empty space for system volume on MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by kirill-erastov-distillery** [mono/mono#17151]
## Steps to Reproduce

1. Create instance of DriveInfo class with path "/". 
2. Check .AvailableFreeSpace property (as well as all other disk space related properties)

Test.cs with test case attached

### Current Behavior

available space is set to 0.
Test.exe output:

/: 0
/dev: 0
/System/Volumes/Data: 54000906240
/private/var/vm: 54000906240
/System/Volumes/Data/home: 0

### Expected Behavior

appropriate available size should be returned

### Additional Info

Please note, that in macOS Catalina, Apple introduced new filesystem security feature, called volume replication. It means that System volume now mounts with read only permissions. And real system volume with write permissions is mounted as mirror volume at /System/Volumes/Data location (amd it shows real ).

I've also tried to run simple C programm to figure out if statfs and statvfs system calls are working fine. This test code attached as test.c

and output:

54006734848, 54006734848

so POSIX calls are working just fine

### Attachment

[Tests.zip](https://github.com/mono/mono/files/3681222/Tests.zip)

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
6.4.0.198
macOS 10.15 beta 10

**Comment by lambdageek** [comment]
@kirill-erastov-distillery thanks for the bug report!

Does `TotalFreeSpace` return a number that you expect?

The .NET documentation makes a fine distinction between [`TotalFreeSpace`](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo.totalfreespace?view=netframework-4.8#remarks) and [`AvailableFreeSpace`](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo.availablefreespace?view=netframework-4.8#remarks):
> This property indicates the amount of free space available on the drive. Note that this number may be different from the `TotalFreeSpace` number because this property takes into account disk quotas.

**Comment by lambdageek** [comment]
Oh actually I see that we'll probably give 0 for `TotalFreeSpace` too:

https://github.com/mono/mono/blob/d8040ba86520ae584f36628bd7eece1558970f41/mono/metadata/w32file-unix.c#L4446-L4450

**Comment by kirill-erastov-distillery** [comment]
@lambdageek thanks for a quick response.
No, both properties are set to 0
Here is printed class from vs console:
drive
{/}
	AvailableFreeSpace: 0
	DriveFormat: "apfs"
	DriveType: System.IO.DriveType.Fixed
	IsReady: true
	Name: "/"
	RootDirectory: {/}
	TotalFreeSpace: 0
	TotalSize: 250685575168
	VolumeLabel: "/"
	Non-public members: 
>

**Comment by kirill-erastov-distillery** [comment]
Ok, this volume is marked as read-only.
Is it expected behavior, that for read-only volumes both, TotalFreeSpace and AvailableFreeSpace is set to zero? It looks like a bug for me.
Can we expect it will be fixed or, should I use some workaround here?

**Comment by CoffeeFlux** [comment]
No, TotalFreeSpace should be returning a nonzero value even if the drive is set to read-only. Should be an easy fix.

**Comment by CoffeeFlux** [comment]
Our logic around readonly drives is interesting, since what corefx seems to do is much simpler: 

https://github.com/dotnet/corefx/blob/96fccd3abda252d781a447fe801c8b389fa0055f/src/Native/Unix/System.Native/pal_mount.c#L97

I wonder if it's needed for some mobile platform? The history indicates it's existed since the initial implementation, but maybe we can just take all that out...

**Comment by CoffeeFlux** [comment]
Hmm, it seems that even `GetDiskFreeSpaceEx` on Windows is going to return nonzero values for write-protected drives, so we probably shouldn't have the readonly logic at all. I'm a bit confused why it was included in the first place, but hopefully no one is relying on the current behavior.

**Comment by spouliot** [comment]
@marek-safar any plan to backport this to stable (mono 6.4) ? since it affects people who updates to 10.15 (now stable) and `d16-4` is still a long way from stable

**Comment by marek-safar** [comment]
@spouliot we can backport if that fits into your plans for servicing
