### ISSUE TITLE
[merp] mono_summarize_unmanaged_stack tries to take a lock while calling decode_exception_debug_info

### ISSUE THREAD

**Issue by CoffeeFlux** [mono/mono#17180]
Probably could be better titled but I haven't looked at what exactly is going on.

Job: https://jenkins.mono-project.com/job/test-mono-pull-request-i386/30466/

Error: `mono_coop_mutex_lock Cannot transition thread 0xf7cae700 from STATE_BLOCKING with DO_BLOCKING`

Relevant part of the stack trace: https://gist.github.com/CoffeeFlux/31704a1568f8a230cf6ecef0b17ccefd

From slack:
>Aleksey Kliger  Oh no - it's allocating (and trying to take a domain lock in the crash reporter)

**Comment by CoffeeFlux** [comment]
I've now seen this on two separate PRs when I hadn't seen it before, so this might be a fairly recent regression. Triggered by `MonoTests.System.ExceptionTest.DumpICallTotalAsync` on `Linux i386`. cc @alexischr

**Comment by lambdageek** [comment]
We need to `mono_thread_info_set_is_async_context (TRUE)` somewhere around `mono_summarize_unmanaged_stack`.  Or possibly even earlier in the callstack in `sigterm_signal_handler`

**Comment by lambdageek** [comment]
Yea this is probably recent due to https://github.com/mono/mono/pull/17090
