### ISSUE TITLE
[cosmetic]: Mono throws wrong Exception message on Socket timeouts.

### ISSUE THREAD

**Issue by Reelix** [mono/mono#17198]
## Steps to Reproduce

1. Create a new .NET Framework Console app with the following code
```csharp
            Byte[] buffer = new Byte[512];
            using (Socket mySocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
            {
                // In milliseconds - Super low so that the timeout is triggered
                mySocket.ReceiveTimeout = 1;
                mySocket.SendTimeout = 1;
                mySocket.Connect("google.com", 443);
                try
                {
                    int bytes = mySocket.Receive(buffer, buffer.Length, 0);
                }
                catch (Exception ex)
                {
                    if (ex.Message == "Operation on non-blocking socket would block")
                    {
                        Console.WriteLine("Mono Exception Message");
                    }
                    else if (ex.Message == "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond")
                    {
                        Console.WriteLine(".NET Exception Message");
                    }
                }
            }
```

### Current Behavior

Run it on Windows - Note the ".NET Exception Message"
Run it through Mono - Note the "Mono Exception Message"

### Expected Behavior

Running it on Windows and Mono have the same outcome

## On which platforms did you notice this

[ ] macOS
[x] Linux (For Mono - Ubuntu 19.10)
[x] Windows (For .NET - Windows 10 Pro 1903)

**Version Used**:

Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:21:28 UTC 2019)

**Comment by baulig** [comment]
There are various incompatibilities between Mono, .NET Framework and CoreFX.  You will find a lot more of these if you only start looking and changing the particular type of exception message that's being thrown is not something I'd consider worth fixing.  It's merely cosmetic and there are a lot of far more important problems in the socket code.

**Comment by Reelix** [comment]
Note to anyone coming across this in the future: It seems that this behavior is noted as a difference between Windows / Linux in the tests, resulting in the specific section of the test being commented out.

https://github.com/mono/mono/blob/master/mcs/class/System/Test/System.Net.Sockets/NetworkStreamTest.cs#L71-L72
