### ISSUE TITLE
return MonoArray С++ to С#

### ISSUE THREAD

**Issue by Jacellen** [mono/mono#17200]
How can I send MonoArray from C ++ to C #?

**Comment by srxqds** [comment]
mono_array_new to create MonoArray and then use mono_array_set or mono_array_setref set element to the array

**Comment by Jacellen** [comment]
@srxqds I successfully did this only when I install this array for C # and access the 0 index I get crash

**Comment by Jacellen** [comment]
@srxqds 

```
const auto data = mono_array_new(hooks::current_domain, mono_get_object_class(), 2);
mono_array_setref(data, 0, mono_string_new(hooks::current_domain, hwid_generation().to_string()));
mono_array_setref(data, 1, mono_string_new(hooks::current_domain, utils::get_time()));

SetValue("ClientLibrary.Bootstrap.GetWidgets", nullptr, data);

public static List<string> GetWidgets;

Debug.Log(GetWidgets.Count); = 2 GOOD

Debug.Log(GetWidgets[0]); - Crash
```

**Comment by srxqds** [comment]
@Jacellen The MonoArray is the C# is array not List, in your sample it is string[];

you should use mono_array_new(hooks::current_domain, mono_get_string_class(), 2)

and on the C# side it is
> public static string[] GetWigets;

**Comment by Jacellen** [comment]
@srxqds Thanks, but how can I pass a List?

**Comment by srxqds** [comment]
> @srxqds Thanks, but how can I pass a List?

You can create generic instance of **System.Collection.Generic.List<System.String>** and then call the method **Add** to add element.
