### ISSUE TITLE
ConvertTimeFromUtc returns an invalid time in the hour after a DST change

### ISSUE THREAD

**Issue by mfeingol** [mono/mono#17218]
## Steps to Reproduce

1. Generate a UTC time that falls within the hour subsequent to a DST change
2. Convert that time to the local time in America/Chicago
3. Call IsInvalidTime, returns true
4. Call ConvertTimeToUtc again, which throws because the time is in fact invalid

```
            DateTime time = new DateTime(2020, 3, 8, 1, 0, 0);

            TimeZoneInfo localTz = TimeZoneInfo.FindSystemTimeZoneById("America/Chicago");

            DateTime utcTime = TimeZoneInfo.ConvertTimeToUtc(time, localTz);
            DateTime localTime = TimeZoneInfo.ConvertTimeFromUtc(utcTime + TimeSpan.FromHours(1.5), localTz);

            // Returns true, even though localTime is 2:30 AM
            bool isValid = localTz.IsInvalidTime(localTime);

            // Throws **System.ArgumentException:** 'dateTime parameter is an invalid time'
            utcTime = TimeZoneInfo.ConvertTimeToUtc(localTime, localTz);
```

### Current Behavior

ConvertTimeFromUtc returns an invalid time in the hour after a DST change

### Expected Behavior

ConvertTimeFromUtc takes DST into account and returns a valid time.

## On which platforms did you notice this

[x] Android

**Version Used**:

The version of Mono that comes with Visual Studio 16.3.2 + Xamarin, which appears to be 6.4.

**Comment by CoffeeFlux** [comment]
Duplicate of #10014?

**Comment by mfeingol** [comment]
It does look similar, yes.

I'll note that it would be great if this could be fixed. The workaround is pretty ugly (checking for invalid times, finding the appropriate adjustment rule, applying it by hand...)

**Comment by MaximLipnin** [comment]
@mfeingol You mentioned Visual Studio 16.3.2. Could you please check it with VS 16.3.3 ([Xamarin.Android 10.0.3.0](https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.0#october-7-and-8-2019--xamarinandroid-10030)) because it includes the fix for the similar issue reported in https://github.com/mono/mono/issues/16395 ?

**Comment by mfeingol** [comment]
@MaximLipnin: I installed 16.3.3 and re-ran my test case. `ConvertTimeFromUtc` continues to return `3/8/2020 2:30:00 AM`, which is an invalid time for the `America/Chicago` timezone.

**Comment by MaximLipnin** [comment]
I used VS 16.3.4 to create new mobile app and put your sample in the android project.
Below is a debug snapshot where `ConvertTimeFromUtc` returns 3/8/2020 3:30:00 AM to `localTime`:

![image](https://user-images.githubusercontent.com/3258267/66632210-97af7100-ec10-11e9-8a94-c296cb6d1aa9.png)

The full .Net framework works the same way.

Did I miss anything?

**Comment by mfeingol** [comment]
@MaximLipnin: can confirm, and it's possible 16.3.4 has a fix. I'll try that tonight on the original repro machine.

**Comment by mfeingol** [comment]
@MaximLipnin: this is strange. I tried it with a Xamarin Forms Android project at work with VS 16.3.4 and got 3:30am, i.e. the right value.

At home, after updating VS, rebuilding a project, and running the same code, I'm still seeing 2:30am, i.e. an invalid value.

What else might be influencing the result?

![image](https://user-images.githubusercontent.com/218865/66693019-10d2b680-ec59-11e9-8bcf-8467f49275da.png)

**Comment by MaximLipnin** [comment]
@mfeingol Could you disable shared runtime in android project options and rebuild/republish the project?

**Comment by mfeingol** [comment]
@MaximLipnin: you guessed it. With shared runtime enabled, the problem occurs. With shared runtime disabled, it doesn't.

**Comment by jaykrell** [comment]
Why is that? Is shared a newer version, with a bug fix?

**Comment by CoffeeFlux** [comment]
Shared is probably cached on the device with an older version that does not include the fix.

**Comment by mfeingol** [comment]
If that's the case, shouldn't a deployment with a newer version update it?

**Comment by steveisok** [comment]
Yes, it should.  Seems there might be a bug in the version checking.  That's a different team, so we should log a bug in https://github.com/xamarin/xamarin-android

**Comment by mfeingol** [comment]
Can confirm resetting the emulator image to factory settings fixes the issue.

Looks like I filed a duplicate. I'll close mine. :-)
