### ISSUE TITLE
Loading function pointers for statically linked native libraries

### ISSUE THREAD

**Issue by Perksey** [mono/mono#17258]
Let's say I have a native library, `libMyLibrary.a` that exposes an entrypoint entitled `MLMyEntryPoint`.

If I were to load this entrypoint via P/Invoke on a MonoAOT platform where the library is statically linked, the signature would look like this:

```cs
[DllImport("__Internal", EntryPoint = "MLMyEntryPoint")]
public static extern void MyEntryPoint();
```

However, I need to get the function pointer as part of a calli system we use for our native interop. Is there a way to do this without using external libraries such as libdl which are banned from the app store as of iOS 8?

**Comment by jaykrell** [comment]
Can you get a function to return the function pointer?
And a function to call function pointers?

**Comment by Perksey** [comment]
Yeah, we use a platform abstraction for the platform-specific loading logic.

Functions for obtaining the function pointer:

![image](https://user-images.githubusercontent.com/11160611/66506361-1c8d7400-eac5-11e9-8da7-0fae08f6923e.png)

As for the function to call the function pointer, we manually emit hand-written IL ahead of time that uses an array to obtain the function pointers, which is then passed to `calli`

**Comment by Perksey** [comment]
If we were allowed to use libdl I'd already have a solution by now, but the Apple App Store has blocked this since iOS 8 so we need to find an alternative method for obtaining the function pointers.

**Comment by Perksey** [comment]
cc @mellinoe regarding NativeLibraryLoader

**Comment by lambdageek** [comment]
If `MyEntryPoint` is a pinvoke, `Marshal.GetFunctionPointerForDelegate (MyEntryPoint)` will return the pointer to the native function `MLMyEntryPoint`

**Comment by Perksey** [comment]
Okay I'll try that, but this also involves creating an internal P/Invoke instance of all functions on MonoAOT platforms, whereas on the other platforms where dynamic loading is supported, we're just using kernel32 and libdl. Is there no way to get a function pointer without going through P/Invoke first?

Another concern is the reason we're avoiding P/Invoke in the first place is because of all the overhead that its marshalling has, will using your method not reintroduce that indirectly?

**Comment by lambdageek** [comment]
There's no marshalling overhead - you get a pointer to the native function, not to any sort of marshalling wrapper around it.

I'm not sure if there's a more straight-forward way to get the relevant pointer other than Jay's suggestion: write a native function that gets some kind of enumeration value as an argument (one per function that you care about) and then returns the address of that function. 

```c
/* in C */
int foo (void);
int bar (void);

typedef int (*IntVoidFunc)(void);

enum {
      WANT_FOO = 0,
      WANT_BAR = 1,
}

IntVoidFunc selector (int32_t which)
{
        switch (which) {
          case WANT_FOO:
               return &foo;
          case WANT_BAR:
               return &bar;
        }
 }
```

```csharp
// In C#
class Selector {
   [DllImport ("__Internal", EntryPoint="selector")]
   private IntPtr Selector_native (int which);
   public enum Which {
      WantFoo = 1,
       WantBar = 2,
   }
  
   public IntPtr Selector (Which w) {
      return Selector_native ((int)w);
   }
}
```

**Comment by Perksey** [comment]
I decided to make an internal P/Invoke class to __Internal, and then just use `ldftn` to get a function pointer to the symbol. Thanks for all the help!
