### ISSUE TITLE
Exception handling error with llvm

### ISSUE THREAD

**Issue by laszk** [mono/mono#17285]
# Steps to Reproduce

1. The sample C# program below demonstrates how when using llvm a trivial exception is not caught.
2. The application was compiled on Windows 10 with Visual Studio 2017 and .Net 4.6.1.
3. It was run with the 6.4 release and the  6.9.0.30 (tarball Thu Oct 10 10:43:53 UTC 2019) nightly on CentOS 7.

The sample:

```csharp
using System;

namespace ConsoleApp2
{
    class Program
    {
        class C
        {
            public void f(int i1, int i2, int i3, int i4, int i5, int i6, int i7)
            {
                throw new Exception("exception from f()");
            }
        }

        static void Main()
        {
            try
            {
                C c = new C();
                int i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0, i6 = 0, i7 = 0;
                c.f(i1, i2, i3, i4, i5, i6, i7);
            }
            catch (Exception e)
            {
                Console.WriteLine("caught: " + e);
            }
        }
    }
}
```

### Current Behavior

Running the compiled application with "mono --llvm" the following error is generated:

Unwind failure. Illegal value for switch statement, assertion at unwind.c 682

Unhandled Exception:
System.Exception: exception from f()
  at ConsoleApp2.Program+C.f (System.Int32 i1, System.Int32 i2, System.Int32 i3, System.Int32 i4, System.Int32 i5, System.Int32 i6, System.Int32 i7) <0x41b81d80 + 0x00050> in <91c75590816648359a114ac0814d3503>:0
Unwind failure. Illegal value for switch statement, assertion at unwind.c 682
.
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: exception from f()
  at ConsoleApp2.Program+C.f (System.Int32 i1, System.Int32 i2, System.Int32 i3, System.Int32 i4, System.Int32 i5, System.Int32 i6, System.Int32 i7) <0x41b81d80 + 0x00050> in <91c75590816648359a114ac0814d3503>:0

If I comment out the last parameter from the function (i7), effectively using it with 6 parameters only, the error does not happen and the exception is caught correctly in Main().

There is no issue without --llvm on the cli.

### Expected Behavior

The exception should be caught correctly and there should be no unwind error.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.9.0.30 (tarball Thu Oct 10 10:43:53 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

## Stacktrace

Unhandled Exception:
System.Exception: exception from f()
  at ConsoleApp2.Program+C.f (System.Int32 i1, System.Int32 i2, System.Int32 i3, System.Int32 i4, System.Int32 i5, System.Int32 i6, System.Int32 i7) <0x41b81d80 + 0x00050> in <91c75590816648359a114ac0814d3503>:0
Unwind failure. Illegal value for switch statement, assertion at unwind.c 682
.
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: exception from f()
  at ConsoleApp2.Program+C.f (System.Int32 i1, System.Int32 i2, System.Int32 i3, System.Int32 i4, System.Int32 i5, System.Int32 i6, System.Int32 i7) <0x41b81d80 + 0x00050> in <91c75590816648359a114ac0814d3503>:0

**Comment by imhameed** [comment]
I did a bit of debugging on this. This program causes an internal LLVM assertion (related to https://github.com/mono/mono/issues/8791#issuecomment-538104806) to trip when using LLVM with assertions enabled.
