### ISSUE TITLE
--arch=32 failed to switch (Mac)

### ISSUE THREAD

**Issue by MonkeyMan1122** [mono/mono#17301]
So i wanted to open "Save wizard for PS4 Max" on my Mono on mac, but i'm always getting the error message

 "Error: --arch=32 Failed to switch to '/Library/Frameworks/Mono.framework/Versions/Current/bin/mono32'."

I really, really need the help because i payed for the software.

Regards.

**Comment by jaykrell** [comment]
Try `mono` or `mono64'. Or try Windows or Linux or an older MacOS.
`mono32` is probably a losing battle on Mac.

**Comment by filipnavara** [comment]
What version of macOS sre you running? macOS Catalina completely dropped support for 32-bit programs.

**Comment by directhex** [comment]
macOS Catalina cannot run `mono32`, and will fail on the `--arch=32` flag. Apple have entirely removed support for i386 apps.

**Comment by akoeplinger** [comment]
Closing until we get more info about the macOS version.

**Comment by milefork** [comment]
I can answer it, because I've the same problem. Running Catalina(10.15)
Installed Mono Version: `MonoFramework-MDK-6.4.0.198.macos10.xamarin.universal`

➜  bin pwd
/Library/Frameworks/Mono.framework/Versions/Current/bin
➜  bin ./mono64 --arch=32
Error: --arch=32 Failed to switch to './mono32'.
➜  bin ./mono --arch=32
Error: --arch=32 Failed to switch to './mono32'.
➜  bin ./mono32
zsh: bad CPU type in executable: ./mono32
➜  bin uname -a
Darwin MacBook-Pro-Retina.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

**Comment by vargaz** [comment]
32 bit mono will not run on catalina, apple removed 32 bit support.

**Comment by milefork** [comment]
So combined with this limitation here #6701 . There is no way to run Windows Forms apps on Catalina with mono?

**Comment by filipnavara** [comment]
Correct.

**Comment by bogdandanielb** [comment]
Any update on this? Or it can be called the end of the WinForms era on MAC?

**Comment by ZetiG** [comment]
This is really unfortunate.

**Comment by jasthema** [comment]
uninstall mono via terminall:
sudo rm -rf /Library/Frameworks/Mono.framework
sudo pkgutil --forget com.xamarin.mono-MDK.pkg
sudo rm /etc/paths.d/mono-commands

dowload last version of mono:
https://www.mono-project.com/download/stable/

then go back on termial and type:
ln -sf /Library/Frameworks/Mono.framework/Commands/mono /usr/local/bin/mono

worked for me on catalina 10.15.2

**Comment by owlmylove** [comment]
hi guys, any updates on mono --arch=32 on Catalina for fiddler?

**Comment by lambdageek** [comment]
@owlmylove macos Cataline dropped support for 32-bit apps.  `mono --arch=32` will not and cannot work on Catalina.

**Comment by rapito** [comment]
Bumping to see if there's any update about running windows forms apps with mono

**Comment by lambdageek** [comment]
There is no update.

1. 64-bit builds of Mono don't support WinForms
2. Apple dropped support for 32-bit x86 apps years ago, so 32-bit Mono won't work on recent macOS.
