### ISSUE TITLE
Installing mono on ubuntu 18.04 VM: "gpg: keyserver receive failed: No name"

### ISSUE THREAD

**Issue by cacti77** [mono/mono#17306]
I want to install mono on an ubuntu 18.04 VM.  (It's running inside a Windows 10 host with Oracle VirtualBox 6.0.8.)  I'm trying to follow the instructions at https://www.mono-project.com/download/stable/#download-lin-ubuntu . Installing the certificates appears to work but the next step fails with:

```
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
Executing: /tmp/apt-key-gpghome.o9yvYg5UKK/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: keyserver receive failed: No name
```
I'm behind a corporate proxy so I tried the idea suggested for [issue 12144](https://github.com/mono/mono/issues/12144) but that failed too:

```
$ sudo curl http://download.mono-project.com/repo/xamarin.gpg | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0E: This command can only be used by root.
100  2125  100  2125    0     0   2607      0 --:--:-- --:--:-- --:--:--  2604
(23) Failed writing body
```

Telling curl about my proxy server also fails (proxy server name changed to dummy name):

```
$ sudo curl -x https://my.proxy.com:80 http://download.mono-project.com/repo/xamarin.gpg | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0E: This command can only be used by root.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to my.proxy.com:80
```

Do you have any ideas how I can resolve this so I can install mono successfully please?

**Comment by akoeplinger** [comment]
The second one should work but you need to add the `sudo` next to `apt-key` otherwise it only applies to the `curl` part of the command.

So try this:

```bash
curl https://download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -
```

**Comment by cacti77** [comment]
Ok thanks - oops! That would explain why it still said `This command can only be used by root.` then:).  I'm out for a few days but I should be able to try this next week...

**Comment by akoeplinger** [comment]
Cool, I'll close this issue for now but please feel free to follow up if you hit more problems :)

**Comment by akoeplinger** [comment]
@cacti77 it looks like your proxy server is interfering with HTTPS connections. You need to fix that before things will work as expected.

**Comment by cacti77** [comment]
Well as I've now got NuGet running well enough under mono (as long as I'm not on the corporate network at the time) that's good enough for me for now. Thanks for your help!
