### ISSUE TITLE
does android platform support Multiple domain?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17323]
Does android platform support Multiple domain?

**Comment by knocte** [comment]
Do you mean if Xamarin.Android supports multiple AppDomains? If yes, I guess this question would be more appropriate in the xamarin-android repo or stackoverflow.

**Comment by srxqds** [comment]
> Do you mean if Xamarin.Android supports multiple AppDomains? If yes, I guess this question would be more appropriate in the xamarin-android repo or stackoverflow.

embed mono
