### ISSUE TITLE
Console.ForegroundColor on RedHat 7

### ISSUE THREAD

**Issue by wvannoordt** [mono/mono#17332]
###Steps to Reproduce

1. Compile and run the following:
```csharp
using System;
public class Program
{
	public static int Main(string[] args)
	{
		ConsoleColor initial_color = Console.ForegroundColor;
		for (int i = 0; i < 16; i++)
		{
			ConsoleColor current = (ConsoleColor)i;
			Console.ForegroundColor = current;
			Console.WriteLine("This is " + current.ToString() + "!");
		}
		Console.ForegroundColor = initial_color;
		return 0;
	}
}
```

### Current Behavior
![colors](https://user-images.githubusercontent.com/47154608/66846474-cbb8c800-ef69-11e9-9b26-0b8a2e6a2834.png)

### Expected Behavior

Proper colors.

## On which platforms did you notice this

[ ] macOS
[x ] Linux (RedHat 7)
[ ] Windows

**Version Used**:Mono JIT compiler version 6.4.0.198

**Comment by rjvdboon** [comment]
@wvannoordt I tried on a couple of terminal emulators in RH7 on an out-of-the-box unchanged VM, and for me the colors are exactly as expected.
Can you check your terminal settings? Mono outputs ansi escape sequences, and your terminal is responsible for translating it to the colors you see. The colors in your screenshot are exactly those I get when I customize the terminal colors in Xfce (through Edit->Preferences->Colors) to "Solarized (dark)" with a black background, but on a normal "white on black" or "Linux" colorscheme the test program has the expected output.

**Comment by wvannoordt** [comment]
Yep, looks good. Will have to fix in terminal. Thanks!
