### ISSUE TITLE
Isolate aot_runtime by MonoDomain will make multi-domain work?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17353]
I find that there is only one place use the **DISABLE_APPDOMAINS** macro in **ves_icall_System_AppDomain_createDomain**. https://github.com/mono/mono/blob/6a1ac97dc757f7004f0d6160c4a9c8c19c587ae0/mono/metadata/appdomain.c#L1270

The AOT code is only used in root domain, so it should handle correctly about the domain args, such as:
https://github.com/mono/mono/blob/957e6fa4ddb9a4cdae818b49850a7b6949a5e6a2/mono/mini/aot-runtime.c#L5083

https://github.com/mono/mono/blob/957e6fa4ddb9a4cdae818b49850a7b6949a5e6a2/mono/mini/aot-runtime.c#L4510

If I handle correct the domain, can it make use multiple domain work?

anther big problem is **gc**, the issue:
https://github.com/mono/mono/issues/17360
Any other problem should I to solve, anyone who know can list for me?

thank you very much

**Comment by srxqds** [comment]
I made it!
than you very much!

**Comment by dj4156003** [comment]
> I made it! than you very much!

Did you make the aot use multiple domain work?Any experience could share?
