### ISSUE TITLE
Blazor Client Side (Wasm), Crashes for Arabic/Farsi Google Chrome Localization

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#17363]
_From @smjltd on Wednesday, October 16, 2019 10:45:32 AM_

### Describe the bug
Blazor Client Side (Wasm), Crashes for Arabic/Farsi Google Chrome Localization, when using DateTime even though its converted to string.

there should be a global way in startup file to ignore localizations. 

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100'
2. Run Blazor Client Side Wasm with Arabic or Farsi Google Chrome Localization.
3. Use Datetime.ToShortString(); somewhere.

### Expected behavior
Not A Valid Calendar for the given culture in F12: Developer Tools -> Console

### [Screenshots]
![vcs](https://user-images.githubusercontent.com/8701960/66912359-1e05f180-f01b-11e9-8dd7-aeda9271580d.png)

_Copied from original issue: aspnet/AspNetCore#15051_

**Comment by mkArtakMSFT** [comment]
_From @javiercn on Wednesday, October 16, 2019 12:29:39 PM_

@smjltd Thanks for contacting us.

This seems like a mono issue in `DateTime.ToShortString()` we will make sure we route the issue to the right place.

**Comment by smjltd** [comment]
for time being use @ DateTime.Day.ToString()-@DateTime.Month.ToString()-@DateTime.Year.ToString() in  your views or however you want to arrange

**Comment by kjpou1** [comment]
Just a couple of thoughts here and may need to confirm with Blazor.

You might want to try not using the linker on the Blazor app to see if that works for you.  It might be that globalization tables are being stripped out by default to save space.

If that helps with the crash then when building your Blazor app using the linker you may need to include the specific calendar for your locale.  Blazor uses ILLink and may be able to specify which i18n assemblies can be included in the linked code by using the `ExtraArgs` parameters on the ILLink task.

[Mono Specific i18n Assemblies Linker options ](https://github.com/mono/linker/tree/master/src/linker#mono-specific-options)  

```
The i18n Assemblies

Mono has a few assemblies which contains everything region specific:

I18N.CJK.dll
I18N.MidEast.dll
I18N.Other.dll
I18N.Rare.dll
I18N.West.dll

illinker -l choice

Where choice can either be: none, all, cjk, mideast, other, rare or west. You can combine the values with a comma.

Example:

illinker -a assembly -l mideast,cjk

```

cc: @mkArtakMSFT @SteveSandersonMS @danroth27 @lewing

**Comment by SteveSandersonMS** [comment]
We do have a build option to configure this, but it's not yet documented. I've filed https://github.com/aspnet/AspNetCore.Docs/issues/15679 to track the need to document this.
