### ISSUE TITLE
[llvm] Performance issue with serialization benchmarks

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#17365]
Some of the [dotnet/performance](https://github.com/dotnet/performance) benchmarks run consistently slower on LLVM JIT than on mini JIT:

| Slower                                                                           | diff/base | Base Median (ns) | Diff Median (ns) | Modality|
| -------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| -------- |
| MicroBenchmarks.Serializers.Json_FromStream<LoginViewModel>.JsonNet_             |      8.39 |          4432.31 |         37204.50 | bimodal |
| MicroBenchmarks.Serializers.Json_FromStream<LoginViewModel>.DataContractJsonSeri |      4.43 |         10623.91 |         47081.50 | several?|
| MicroBenchmarks.Serializers.Xml_FromStream<LoginViewModel>.XmlSerializer_        |      3.67 |         18160.12 |         66676.50 |         |

We should investigate why is that the case and whether there could be something done about it. Full logs from separate runs available at https://filipnavara.visualstudio.com/mono-performance/_build/results?buildId=195. Note that BDN detects some abnormal distributions in the tests which could be caused by garbage collector kicking in or some other similar event. The individual run times are available in the logs linked above.

**Comment by filipnavara** [comment]
The serializers offer different strategies for implementation (eg. IL generation, reflection). My assumption is that it could be taking the IL generation. That could either result in seeing JITing overhead or possible failure and fallback to slower path.

**Comment by SamMonoRT** [comment]
@naricc  - we should check recent microbenchmark runs against the runtime repo and if needed move this issue over to the new repo. This is much lower priority that current work on your plate.

**Comment by naricc** [comment]
@SamMonoRT It looks like we are still off by similar amounts, compared to coreclr, in dotnet runtime:

mono: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dfalse_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fMicroBenchmarks.Serializers.Xml_FromStream(ClassImplementingIXmlSerialiable).XmlSerializer_.html

coreclr:
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fMicroBenchmarks.Serializers.Xml_FromStream(ClassImplementingIXmlSerialiable).XmlSerializer_.html

**Comment by SamMonoRT** [comment]
@naricc - create an issue in dotnet\runtime and close this one.

**Comment by SamMonoRT** [comment]
All new work is tracked in dotnet\runtime repo. We have implemented many optimizations in diff compilation engines for mono there. Please re-open there if necessary. Closing this one.
