### ISSUE TITLE
Cannot access a disposed object. Object name: 'MobileAuthenticatedStream'.

### ISSUE THREAD

**Issue by clintonrocksmith** [mono/mono#17381]
We are seeing this on a lot of Android phones in our crash reporting.  We are unsure of what the problem is and cannot faithfully reproduce it.

However, we are using the latest Visual Studio for Mac for building our releases, the latest Mono as well.

The build we are using is a Managed Http Client, not the NativeClient in the options.

The other settings include....

- Use incremental Android packaging system aapt2
- Enable Multi-Dex
Dex compiler = dx
Code shrinker = none

All supported ABI's are selected.
armeabi-v7a
x86
arm64-v8a
x86_64

## Stacktrace

Mono.Net.Security.MobileAuthenticatedStream.StartOperation(Mono.Net.Security.MobileAuthenticatedStream+OperationType type, Mono.Net.Security.AsyncProtocolRequest asyncRequest, System.Threading.CancellationToken cancellationToken) in <a439f2db70374e8b9fab869c7be1af66

**Comment by steveisok** [comment]
Related to https://github.com/mono/mono/issues/15462

We are actively working on a fix.

**Comment by baulig** [comment]
Closing as duplicate.
