### ISSUE TITLE
[wasm] Can't get Async Tasks (ex: Roslyn Compiler) to work in nodejs (or d8)

### ISSUE THREAD

**Issue by a7medkamel** [mono/mono#17398]
## Steps to Reproduce

1. create a project with mono-wasm
2. create a simple c# dll / function that returns a Task<string>
3. call said function from javascript

-- clone https://github.com/a7medkamel/Mono.Wasm.Samples
-- forked from @kjpou1 
1. cd into `WasmRoslynNode` and run `node index.js`
-- all packages, bin, published content is checked into the repo already

Note: I kept @kjpou1 's original Roslyn .cs files as is and emulated the necessary js / dom parts as necessary (to simplify / minimize the changes to the original example) - this issue however seems to repro whenever there is a `Task` involved.

### Current Behavior

1. all async Tasks in c# code just 'hang' / never return
2. they correctly return a `Promise` to JS; the `Promise` is never resolved

### Expected Behavior

1. Tasks should return and their JS `Promise` stubs should resolve

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
### mono-wasm
4043/ubuntu-1804-amd64/sdks/wasm/mono-wasm-e5721bbb233.zip
https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/

-- patched mono.js with https://github.com/a7medkamel/Mono.Wasm.Samples/blob/master/WasmRoslynNode/publish/mono.js#L2 to expose the `MONO` object in nodejs on the `global` object

### Mono
```
Mono JIT compiler version 6.0.0.334 (tarball Fri Sep 13 17:58:23 BST 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
## Stacktrace

It hangs

**Comment by a7medkamel** [comment]
@kjpou1 created this new issue and forked your example with the setup required to make it work in node.

Looks like Tasks in general are not working outside of the browser.

I have tried to make this work in both nodejs and d8 - can only make it work in browser)

**Comment by kjpou1** [comment]
Thanks for the repro.  Will take a look.

**Comment by kjpou1** [comment]
@a7medkamel again thanks for the repro.  There have been two PR's opened to address this issue.  When they are applied you can test them out.

One problem you will have in this scenario is the use of the HttpClient.  Right now it only supports `fetch` through the browser.  A new `HttpMessageHandler` would need to be created to work with nodejs's fetch.  If you would like to take on this effort let us know.  The help would be greatly appreciated.

**Comment by a7medkamel** [comment]
Thanks @kjpou1 I'll give the latest builds a try.

**Comment by a7medkamel** [comment]
@kjpou1 still experimenting with the fix, seems to work -- Thank you!

Regarding '`HttpMessageHandler` would need to be created'

Do you have an example where the wasm sdk handles NodeJS specifically instead of assuming that it is running in the browser? For example, most of the code assumes the presence of the window object.

If not, how would you envision the code either detecting or be told that it's in NodeJS world?

Should we create a new assembly just for Node? say `WebAssembly.Net.Http.NodeJS` or `WebAssembly.NodeJS.Net.Http`

Thanks

**Comment by a7medkamel** [comment]
Without altering `WebAssembly.Net.Http` or creating a fork for `NodeJS`; Node developers can do the following to polyfill for the missing browser specific functions. The following will allow the currently implemented `WebAssembly.Net.Http` functions to work.

```js
const self = this; // where this is the top level scope in which mono will be loaded.

global.window = self;

self.location = {
  origin: 'http://www.randomtext.me',
  pathname: '/lorem/ul-8/5-15'
}

const { AbortController, abortableFetch } = require('abortcontroller-polyfill/dist/cjs-ponyfill');
const { fetch } = abortableFetch({ fetch: require('node-fetch') });

global.Headers = require('node-fetch').Headers;

global.AbortController = AbortController;

global.fetch = fetch;
```

Then...
```js
// load mono.js
```

**Comment by kjpou1** [comment]
Thank you for the information.  Forgot about the polyfill and will need to try it.

Will close this out as resolved for now.  Create a new issue for other problems that arise.
