### ISSUE TITLE
PerfLabTests.GetMember.GetMethod3 Microbenchmark is slow

### ISSUE THREAD

**Issue by naricc** [mono/mono#17403]
These benchmarks from the Dotnet performance suite are 60-70 times slower on mono-net5-llvm than dotnetcore 3.0. This issue is to investiage why. 

PerfLabTests.GetMember.GetMethod3
PerfLabTests.GetMember.GetMethod12
PerfLabTests.GetMember.GetMethod20
PerfLabTests.GetMember.GetMethod4
PerfLabTests.GetMember.GetMethod5
PerfLabTests.GetMember.GetMethod1
PerfLabTests.GetMember.GetMethod10
PerfLabTests.GetMember.GetMethod2
PerfLabTests.GetMember.GetMethod15

See this sheet for all benchmark resuts: 
https://microsoft-my.sharepoint.com/:x:/r/personal/naricc_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B0D4F2502-78E4-453B-B738-0112BDF3F2B1%7D&file=Mono%20Microbench%20Marks.xlsx&action=default&mobileredirect=true

**Comment by filipnavara** [comment]
CoreCLR has cache for these.

**Comment by naricc** [comment]
This is still happening in dotnet/runtime, should I create a new issue there? @SamMonoRT

**Comment by filipnavara** [comment]
This is somewhat important scenario for serialization/deserialization, so I guess it would be reasonable to track it. There may already be some issue for unifying the Mono/CoreCLR reflection APIs due to .NET 7 changes in behavior.

**Comment by SamMonoRT** [comment]
> This is still happening in dotnet/runtime, should I create a new issue there? @SamMonoRT

Yes, please create issue in dotnet/runtime and track there.

**Comment by SamMonoRT** [comment]
All new work is tracked in dotnet\runtime repo. We have implemented many optimizations in diff compilation engines for mono there. Please re-open there if necessary. Closing this one.
