### ISSUE TITLE
Investigate Why IsPrefix_DifferentFirstChar Microbenchmark is slow on llvm mono

### ISSUE THREAD

**Issue by naricc** [mono/mono#17402]
All of the IsPrefix_DifferentFirstChar micro benchmarks from the Dotnet Performance suite are between 80 and 100 times slower on mono-net5-llvm than on dotnetcore3.0. This issue is to investigate why.

The benchmarks are named as follows:

System.Globalization.Tests.StringSearch.IsPrefix_DifferentFirstChar(Options: (en-US; IgnoreCase; True)
System.Globalization.Tests.StringSearch.IsPrefix_DifferentFirstChar(Options: (; None; True)) 
System.Globalization.Tests.StringSearch.IsPrefix_DifferentFirstChar(Options: (; IgnoreCase; True)) 
System.Globalization.Tests.StringSearch.IsPrefix_DifferentFirstChar(Options: (en-US; None; True))
System.Globalization.Tests.StringSearch.IsPrefix_DifferentFirstChar(Options: (pl-PL; None; False)) 

See this sheet for all benchmark results:
https://microsoft-my.sharepoint.com/:x:/r/personal/naricc_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B0D4F2502-78E4-453B-B738-0112BDF3F2B1%7D&file=Mono%20Microbench%20Marks.xlsx&action=default&mobileredirect=true

**Comment by filipnavara** [comment]
Last time I looked into it I think it pinned it to be caused by #16243. Related PR #16954.

**Comment by naricc** [comment]
It seems like mono is now only about 50 % slower on these compared to the most recent CoreCLR, so I am closing this.

mono: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dfalse_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Globalization.Tests.StringSearch.IsPrefix_DifferentFirstChar(Options%3a%20(%2c%20IgnoreCase%2c%20True)).html

Coreclr:
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fSystem.Globalization.Tests.StringSearch.IsPrefix_DifferentFirstChar(Options%3a%20(%2c%20IgnoreCase%2c%20True)).html
