### ISSUE TITLE
System.Collections.Sort microbenchmarks are slow

### ISSUE THREAD

**Issue by naricc** [mono/mono#17406]
The following microbenchmakrs from the Dotnet Performance suite are about 30 times slower on mono-net5-llvm compared to dotnetcore 3.0:

System.Collections.Sort<Int32>.List(Size: 512)
System.Collections.Sort<Int32>.Array(Size: 512)
System.Collections.Sort<IntStruct>.Array(Size: 512)

This isssue is to investigate why.

**Comment by filipnavara** [comment]
A possible cause could be missing bounds check elimination (#16243).

**Comment by EgorBo** [comment]
Also, a missing `Array.TrySZSort` fast path for primitive arrays

**Comment by filipnavara** [comment]
Oh, right, I forgot about that one :-)

**Comment by naricc** [comment]
It looks like we have closed the gap to about 10x slower: 

Mono:
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dfalse_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Collections.Sort(Int32).List(Size%3a%20512).html

Coreclr: 
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fSystem.Collections.Sort(Int32).List(Size%3a%20512).html

I'm not sure what the threshold for acceptable is here. @SamMonoRT?

**Comment by SamMonoRT** [comment]
Closing this.
