### ISSUE TITLE
mono-reference-assemblies-2.0 gets deleted by mono-devel or mono-complete package on raspbian

### ISSUE THREAD

**Issue by MindPainter** [mono/mono#17439]
I am trying to install mono-reference-assemblies-2.0 alongside with mono-devel to get an application running on the Raspberry Pi 4 B with Raspbian Buster as the OS on it.

## Steps to Reproduce

I've tried to reproduce it on:

Ubuntu 18
Raspberry Pi Desktop OS

It can't be reproduced on the desktop systems – there I can install both packages alongside each other.

### Current Behavior

When installing the needed packages:

mono-devel --deletes--> mono-reference-assemblies-2.0
mono-reference-assemblies-2.0 --deletes--> mono-devel

The overall dependencies in both packages seem to set up so in some way
they both break each other.

### Expected Behavior

Installing mono-reference-assemblies alongside with mono-devel, just like on the
desktop systems.

## On which platforms did you notice this

Rasbian Buster (Debian based ARM specific distro)

**Version Used**:

Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3)

TLS:
SIGSEGV: normal
Notifications: epoll
Architecture: armel, vfp+hard
Disabled: none
Misc: softdebug
Interpreter: yes
LLVM: supported, not enabled.
Suspend: preemtive
GC: sgen (concurrent by default)

**Comment by directhex** [comment]
mono-reference-assemblies-2.0 has been superseded by mono-devel, which now includes the API facades in question. This is the intended behaviour. See all the -api directories on https://packages.debian.org/sid/all/mono-devel/filelist
