### ISSUE TITLE
Will app be banned by applestore?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17446]
Hi, this is a worry about app upload for apple store.

I found that mono implement aot or pinvoke with using the api **dlopen** and **dlsym**.

These api have forbidden by apple store for App Store Review Guideline 2.5.2

Is there any risks of the app be banned by apple store?

Will apple store reject the app?

**Comment by migueldeicaza** [comment]
Just follow the requirements in that section:

> 2.5.2 Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps. Educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code provided that such code is not used for other purposes. Such apps must make the source code provided by the Application completely viewable and editable by the user.
