### ISSUE TITLE
[netcore][interp] System.Reflection.Tests.ModuleTests.GetField fails

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#17440]
Running System.Runtime.Tests under interpreter currently fails one test:

```
    System.Reflection.Tests.ModuleTests.GetField [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   123145302310914
      Stack Trace:
        /_/src/System.Runtime/tests/System/Reflection/ModuleTests.cs(158,0): at System.Reflection.Tests.ModuleTests.GetField()
        /Users/filipnavara/Documents/mono/netcore/System.Private.CoreLib/src/System.Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by lewurm** [comment]
note:
```console
$ printf "0x%x\n" 123145302310914
0x700000000002
```

**Comment by vargaz** [comment]
This happens because of this code in src/System.Runtime/tests/TestModule/System.Reflection.TestModule.il
in corefx:

    ldc.i4.2
    stsfld int64 TestLong

The JIT adds a conversion here, but the interpreter doesn't, so it tries to load a 64 bit value from the stack value, but only 32 bits are initialized.

**Comment by filipnavara** [comment]
Hmm, that does not sound like a valid code to me.

**Comment by vargaz** [comment]
coreclr and the mono jit allow a lot of non-valid code.

**Comment by filipnavara** [comment]
They do allow it but here it looks like a consequence of storing variables in registers that are wider |(x64) or widened (x86).

**Comment by lewurm** [comment]
fixed by https://github.com/mono/mono/commit/1b2407a4ce9ad99588b58dc048aeb0869cd8daa9
