### ISSUE TITLE
[netcore] Slow debug code in lookup_intrins

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#17457]
There's leftover debug code in `lookup_intrins` method:

https://github.com/mono/mono/blob/9f50bdb2d944793d30ea2d052cdad96feb282003/mono/mini/simd-intrinsics-netcore.c#L87-L92

We should disable it at least for release builds, possible all builds except for some checked one.

/cc @vargaz

**Comment by EgorBo** [comment]
heh, good point!

**Comment by vargaz** [comment]
Its ok to just ifdef-it out.
