### ISSUE TITLE
Support System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#17479]
CoreRT "supports" a `System.Runtime.InteropServices.NativeCallableAttribute`, which can be used to cause a managed method to be "exported" into a native library, with a specifiable name:

  * https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Runtime/InteropServices/NativeCallableAttribute.cs
  * https://github.com/dotnet/corert/tree/master/samples/NativeLibrary
  * https://medium.com/@chyyran/calling-c-natively-from-rust-1f92c506289d

Note the "supports" scare-quotes: I don't know how much of that is *in* CoreCLR vs. in the Microsoft.DotNet.ILCompiler NuGet package from https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json.

The `NativeCallableAttribute` type is *not* a publicly exported type.  All samples wind up copying this type into the sample.

In short, things are not necessarily stable...

That said, I would like Mono Full/Hybrid/"Regular" AOT to support `NativeCallableAttribute`, such that when given:

```csharp
partial class Example {
    [NativeCallable (EntryPoint="Java_com_example_Type_add")]
    public static int Add (IntPtr jnienv, IntPtr klass, int a, int b)
    {
        return a + b;
    }
}
```

After generating e.g. `libExample.so` via `mono --aot`, `nm -D libExample.so` will show `Java_com_example_Type_add` as an exported dynamic symbol, *and* this symbol would be a C-callable symbol, such that this works as expected:

```c
void* h = dlopen("libExample.so");
void *m = dlsym (h, "Java_com_example_Type_add");
typedef int (*Adder)(void*, void*, int, int);
Adder a = (Adder) m;
int r = m (NULL, NULL, 1, 2);
assert (r == 3);
```

## Background & Rationale

When using Java `native` methods, there are two different ways for a JVM to associated a Java method with native code:

 1. Via [`JNIEnv::RegisterNatives()`](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#wp17734), or
 2. By looking through all modules in the current address space, looking for a specially-named symbol of `Java_` + the Java package name, with `.` replaced with `_`, followed by the Type name, followed by the method name (and possibly other "name mangling information" to support method overloading).

Xamarin.Android currently uses (1).

The Xamarin.Android team would like to use (2), because it would reduce the amount of Reflection and other overhead during process startup, instead delaying native method lookup to an "on-demand" fashion controlled by the JVM, instead of a class-at-a-time fashion controlled by the Xamarin.Android toolchain.  (We *think* this will help speed things up, but don't actually know this for sure.)

In order to do (2), we need `NativeCallableAttribute` *or something like it*: *some* way to cause a native symbol to be exported from a native library with a name that we control.

**Comment by lambdageek** [comment]
So this is just like `MonoPInvokeCallbackAttribute` except it also has an `EntryPoint` property to supply a name for the symbol?

**Comment by vargaz** [comment]
Do we want to support this attribute, or add an EntryPoint field to our existing attribute ?

**Comment by marek-safar** [comment]
Yes, it's part of netcore

**Comment by filipnavara** [comment]
Technically it's part of CoreRT that was externally contributed. I don't think CoreCLR supports it. We use it though and I was not aware about Mono offering any alternative (MonoPInvokeCallbackAttribute).

**Comment by vargaz** [comment]
Note that our MonoPInvokeCallbackAttribute also specifies a delegate type which allows the specification of marshalling behavior etc.

**Comment by rolfbjarne** [comment]
This would be great for Xamarin.iOS as well.

Ref: https://trello.com/c/RPsMqkz0/32-add-support-for-direct-n2m-wrappers-when-calling-from-native-to-managed-code

**Comment by vargaz** [comment]
Turns out our MonoPInvokeAttribute already supports this, it has an 'ExportSymbol' property.

**Comment by vargaz** [comment]
So this is somewhat difficult to implement, since the runtime needs to associate a delegate class with the method, and since none is given explicitly, it needs to use Func/Action etc, which might be linked away, or it might not exist for lots of parameters etc.

**Comment by alexischr** [comment]
@vargaz If preserving Func/Action classes is the main issue, could we just whitelist them since they are pretty general?

**Comment by vargaz** [comment]
Will post a PR.

**Comment by vargaz** [comment]
The attribute is now called UnmanagedCallersOnlyAttribute and there are a bunch of other behavior changes as well.

**Comment by SamMonoRT** [comment]
@vargaz - do we still need to track this issue ?

**Comment by CoffeeFlux** [comment]
Nope, this is now good to go.
