### ISSUE TITLE
MONO_VERBOSE_METHOD does not trigger when trying on a generic type

### ISSUE THREAD

**Issue by Therzok** [mono/mono#17561]
## Steps to Reproduce

1. https://gist.github.com/Therzok/e96a8e9ca450ec2d67a2b98c91937d58
2. MONO_VERBOSE_METHOD="C:MethodMagic" mono sample.exe
3. MONO_VERBOSE_METHOD="C:MethodGeneric" mono sample.exe

### Current Behavior
Prints asm for MethodMagic, but not for MethodGeneric.

### Expected Behavior
Works for both.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 6.6.0.140 (2019-08/1b2e536b223 Wed Oct 23 17:31:53 EDT 2019)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by EgorBo** [comment]
@Therzok can you put `[MethodImpl(MethodImplOptions.NoInlining)]` on top of those methods and try again?

**Comment by lewurm** [comment]
or run with `-O=-inline,-aot`

**Comment by Therzok** [comment]
That worked, thanks!

**Comment by Therzok** [comment]
Context: https://twitter.com/konradkokosa/status/1186230906983538688

Fun fact, `mono --llvm` optimizes both, `mono` optimizes none of the two versions.
