### ISSUE TITLE
Key problems when installing on debian 10

### ISSUE THREAD

**Issue by martinwag** [mono/mono#17575]
## Steps to Reproduce

1. follow instructions from https://www.mono-project.com/download/stable/#download-lin-debian for Debian 10
2. modify key install command to 
`sudo apt-key adv --keyserver keyserver.ubuntu.com --keyserver-options http-proxy=http://localhost:3128 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF`
because of corporate firewall / using cntlm
3. Getting error 
>gpg: keyserver receive failed: No data

### Current Behavior

> E: The repository 'https://download.mono-project.com/repo/debian vs-buster Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

on apt update

### Expected Behavior

Key should be installed, allowing installing using apt

Alternative for installing/direct download of apt package when instructions do not work. I would prefer directly installing the apt file over using tarballs scattered in my system.

## On which platforms did you notice this

[ ] macOS
[ x] Linux
[ ] Windows

**Version Used**:

package repository as of 28.10.2019

**Comment by martinwag** [comment]
When searching for the key on [keyserver.ubuntu.com](keyserver.ubuntu.com) I get a "Not Found" response. Is there some problem with the key itselve?

**Comment by martinwag** [comment]
Is this going to be fixed anytime soon? Is there a workaround to this?

**Comment by directhex** [comment]
I hoped it would get fixed up with the Ubuntu folks, I'll start poking people

**Comment by directhex** [comment]
OK, looks like this might be an issue with your proxy?

```
directhex@breakfast:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
[sudo] password for directhex: 
Executing: /tmp/apt-key-gpghome.3bqWoN3FuW/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: key A6A19B38D3D831EF: 2 signatures not checked due to missing keys
gpg: key A6A19B38D3D831EF: "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

We do have a copy of the key on http/https, but we don't document its use as it's strongly disrecommended to get a GPG key from outside the keyserver network (http://download.mono-project.com/repo/xamarin.gpg)

**Comment by martinwag** [comment]
Thanks. I've downloaded and installed the key, this works. After I changed the repo path from "https" to "http" I was also able to download packages.

Company proxies are always a pain. Especially if they break the command that is there to get trough the proxy...
