### ISSUE TITLE
File does not contain a valid CIL image.

### ISSUE THREAD

**Issue by seejeegee** [mono/mono#17585]
Hello,

I'm trying to run the program OverwolfInstaller.exe on my mac but keep getting errors, which are basically meaningless to me since I don't know much of how my computer works.

Here are the commands I tried (mostly blindly, off of proposed solutions from several forums) and the following errors
~/Desktop/GAME/TFT> mono OverwolfInstaller.exe
\Cannot open assembly 'OverwolfInstaller.exe': File does not contain a valid CIL image.

 ~/Desktop/GAME/TFT> mcs Porofessor.exe
error CS2015: Source file `Porofessor.exe' is a binary file and not a text file
Compilation failed: 1 error(s), 0 warnings

 ~/Desktop/GAME/TFT> mcs Porofessor.cs 
error CS2001: Source file `Porofessor.cs' could not be found
Compilation failed: 1 error(s), 0 warnings

I use mono version 6.4.0.198
And mac.OS Mojave 10.14.2  

Thanks in advance,
Sinan

EDIT: Just in case anyone needs it, the file I'm trying to run can be found [here](https://www.overwolf.com/app/TFTactics.gg-TFTactics).

**Comment by lewurm** [comment]
Mono can only run .NET programs. They happen to have the same file extension as Windows executables aka `.exe`

You can give Wine a try: https://wiki.winehq.org/MacOS

**Comment by JasonXiaoSpace** [comment]
@

> Hello,
> 
> I'm trying to run the program OverwolfInstaller.exe on my mac but keep getting errors, which are basically meaningless to me since I don't know much of how my computer works.
> 
> Here are the commands I tried (mostly blindly, off of proposed solutions from several forums) and the following errors
> ~/Desktop/GAME/TFT> mono OverwolfInstaller.exe
> \Cannot open assembly 'OverwolfInstaller.exe': File does not contain a valid CIL image.
> 
> ~/Desktop/GAME/TFT> mcs Porofessor.exe
> error CS2015: Source file `Porofessor.exe' is a binary file and not a text file
> Compilation failed: 1 error(s), 0 warnings
> 
> ~/Desktop/GAME/TFT> mcs Porofessor.cs
> error CS2001: Source file `Porofessor.cs' could not be found
> Compilation failed: 1 error(s), 0 warnings
> 
> I use mono version 6.4.0.198
> And mac.OS Mojave 10.14.2
> 
> Thanks in advance,
> Sinan
> 
> EDIT: Just in case anyone needs it, the file I'm trying to run can be found [here](https://www.overwolf.com/app/TFTactics.gg-TFTactics).

so have u resolved your issue? and how?
