### ISSUE TITLE
how can I execute string as code on iOS like python exec

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17597]
how can I execute string as code on iOS like python **exec**?
I found **cs-script** https://github.com/oleg-shilo/cs-script, but it seems only work on windows.
and http://continuous.codes/ app.
Is there other idea or solution?

**Comment by lewurm** [comment]
Check out `Mono.CSharp.Evaluator`: http://docs.go-mono.com/index.aspx?link=T%3aMono.CSharp.Evaluator

One user of this API is `csharp` that we ship with mono: https://github.com/mono/mono/blob/e4cc70f4b5038ec5d6500ba988d0bb67143658bc/mcs/tools/csharp/repl.cs#L76

Note this will only work with the interpreter on iOS.

**Comment by srxqds** [comment]
hi,  @lewurm 
I try with the code:
```c#
CompilerSettings settings = new CompilerSettings();

CompilerContext context = new CompilerContext(settings, new ConsoleReportPrinter());
Evaluator evalutor = new Evaluator(context);
evalutor.InteractiveBaseClass = typeof(InteractiveBase);
evalutor.Run(Code);
```
But it throw the exception:

> MonoVM: Error: Unhandled Exception:

MonoVM: Error: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
MonoVM: Error: Type '<InteractiveExpressionClass>' is not finished
MonoVM: Error:   at System.Reflection.Emit.AssemblyBuilder.GetTypes (System.Boolean exportedOnly) [0x00115] in E:\mono\mono-6.0.0.334\mcs\class\corlib\System.Reflection.Emit\AssemblyBuilder.cs:797 
MonoVM: Error:   at System.Reflection.Assembly.GetTypes () [0x00000] in E:\mono\mono-6.0.0.334\mcs\class\corlib\System.Reflection\Assembly.cs:411 
MonoVM: Error:   at UnrealEngine.Game.Net.Game2Client+<>c.<InitResponseClass>b__1_0 (System.Reflection.Assembly a) [0x00000] in F:\G111\client\game\Content\Script\Game\Net\Game2Client.cs:37 
MonoVM: Error:   at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].ToArray () [0x00028] in <5c9ecf2d8301463599360e42885089f9>:0 
MonoVM: Error:   at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <5c9ecf2d8301463599360e42885089f9>:0 
MonoVM: Error:   at UnrealEngine.Game.Net.Game2Client.InitResponseClass () [0x00001] in F:\G111\client\game\Content\Script\Game\Net\Game2Client.cs:36 
MonoVM: Error:   at UnrealEngine.Game.Net.NetManager.Init () [0x00001] in F:\G111\client\game\Content\Script\Game\Net\NetManager.cs:190 
MonoVM: Error:   at UnrealEngine.Game.UCustomGameInstance.OnInit (UnrealEngine.Game.UCustomGameInstance+InitReason reason) [0x0001a] in F:\G111\client\game\Content\Script\Game\Gameplay\CustomGameInstance.cs:51 
MonoVM: Error:   at UnrealEngine.Game.UCustomGameInstance.ReceiveInit () [0x0000c] in F:\G111\client\game\Content\Script\Game\Gameplay\CustomGameInstance.cs:40 
MonoVM: Error: System.TypeLoadException: Type '<InteractiveExpressionClass>' is not finished

**Comment by srxqds** [comment]
hi，@lewurm
Thank you!
I can make it on windows, I will try on iOS later.
But how to **using** namespace.

```c#
// this can work
CodeEvaluator.Run("UnrealEngine.UKismetMathLibrary.Abs(-30f); UnrealEngine.UELog.Log(\"I am Test\");");

// but it can't 
CodeEvaluator.Run("using UnrealEngine; UKismetMathLibrary.Abs(-30f); UELog.Log(\"I am Test\");");
```

**Comment by srxqds** [comment]
@lewurm  I can't run on iOS because **AssemblyDefinitionDynamic** not supported.
![image](https://user-images.githubusercontent.com/5187024/67926164-429fc300-fbf0-11e9-8807-4526962a59f8.png)

**Comment by srxqds** [comment]
I found that I sholud remove **FULL_AOT_RUNTIME** to support it.
But is there any side effect when I remove **FULL_AOT_RUNTIME** macro building MONOTOUCH

**Comment by srxqds** [comment]
@lewurm  How can I make it work?
remove the 
> PROFILE_MCS_FLAGS += \
	-d:FULL_AOT_RUNTIME

NO_SRE = yes

in the monotouch.make file?

what other should I handle?

I use mono code is mono-6.0.0.334 tags

**Comment by lewurm** [comment]
I think this was answered here: https://github.com/mono/mono/issues/14588#issuecomment-495234781
