### ISSUE TITLE
can't use Method "NameValueHeaderValue" and "ReadAsMultipartAsync" correct.

### ISSUE THREAD

**Issue by VISUS-Li** [mono/mono#17655]
## Steps to Reproduce

1. recommend System.Net.Http.Formatting.dll in my project.
2. use ReadAsMultipartAsync as this: 

```
var provider = Request.Content.ReadAsMultipartAsync();
var contents = provider.Result.Contents; 
```
Then use "foreach" to traversal this contents got just now.

3. I used postman to send a post form request.This form contains 3 params (TaskId,AlgName,Threshold, format like this: TaskId:123-123), and multiple images.
If I run my project in Windows, it worked well and no error returned.But If I run it in Linux(Mono),it worked incorrect and returned an error like this:

```
 Invalid 'HttpContent' instance provided.It does not have a 'Multpart' content-type header with a 'boundary' parameter.\nParameter name:content.
```

4. and When I using method "NameValueHeaderValue" like this: 

```
var mthv = new MediaTypeHeaderValue("aaaa");
mthv.Parameters.Add(new NameValueHeaderValue("bbb"));
```

it returned an error like this: `Invalid format.`
and stackTrace recorded: at 
```
System.Net.Http.Headers.NameValueHeaderValue.set_Value(System.String value) [0x00000] in <filename unknow>:0 \n at System.Net.Http.Headers.NameValueHeaderValue..ctor(System.String name, System.String value) [0x00000] in <filename unknow>:0 \n
```

## On which platforms did you notice this

[ ] macOS
[·] Linux
[ ] Windows

**Version Used**:
mono-opt-3.10.0-1.1.x86_64

## Stacktrace

```
System.Net.Http.Headers.NameValueHeaderValue.set_Value(System.String value) [0x00000] in <filename unknow>:0 \n at System.Net.Http.Headers.NameValueHeaderValue..ctor(System.String name, System.String value) [0x00000] in <filename unknow>:0 \n
```

**Comment by VISUS-Li** [comment]
please anybody can help me

**Comment by lambdageek** [comment]
@VISUS-Li 

1. Could you provide a complete runnable example, please.

2. The version of Mono that you are using 3.10.0 is quite old.  If possible, could you run your project using the "stable" version of Mono from https://www.mono-project.com/download/stable/#download-lin-centos

**Comment by baulig** [comment]
This has been in "needs more info" state for over a month, closing for now.
