### ISSUE TITLE
some problem about build android on macOS

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17714]
## Steps to Reproduce

1. make -C sdks/builds provision-android && make -C sdks/android accept-android-license
2. make sdks/builds provision-mxe
3. make -C sdks/builds archive-android NINJA= IGNORE_PROVISION_ANDROID=1 IGNORE_PROVISION_MXE=1

### Current Behavior

build cross-arm64-win ld not found
ld not found

![image](https://user-images.githubusercontent.com/5187024/68217640-e983c500-001d-11ea-8cb6-6e77ffda325a.png)

build bcl error: no rule to make target
![image](https://user-images.githubusercontent.com/5187024/68218266-010f7d80-001f-11ea-8625-49502188d589.png)

### Expected Behavior

build correctly.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
mono-6.0.0.334

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by srxqds** [comment]
I solved it by undefined **DISABLE_MAC** and ungenerated **host_arm64_win**

**Comment by lewurm** [comment]
I think we didn't have this in the 6.0 release yet:
https://github.com/mono/mono/blob/1e8e3578310f5183ba692c125bfd85d596335ee0/sdks/builds/Makefile#L79-L89

you need to limit the allowed number of open files by executing `ulimit -n 1024`.
