### ISSUE TITLE
Mono Framework not 100% Catilina Compatible

### ISSUE THREAD

**Issue by jwalker5006** [mono/mono#17720]
MacOSX is 100% 64bit now and there is a 32bit file mono-boehm32. 

Not sure if this is causing an issue but thought it should be noted.
![image](https://user-images.githubusercontent.com/6217843/68231014-d6420c80-ffbf-11e9-81ac-2396e29200c9.png)

**Comment by akoeplinger** [comment]
This is expected. We only ship a single Mono .pkg for all supported macOS versions so until we drop 32bit support everywhere the installation will still contain 32bit binaries. You just have to make sure not to use them on Catalina :)
