### ISSUE TITLE
Q: is using loader lock for domain seq_points access correct? (mono runtime)

### ISSUE THREAD

**Issue by takayuki-kazama** [mono/mono#17737]
Question: Is it intentional to use `mono_loader_lock` in `mono_setq_points()` in `seq-points.c`?

Stroy:
I ran into a runtime crash around g_hash_table_lookup called from `mono_get_seq_points`.
It seemed `(domain)->seq_points` was invalid on the call. It looks like locking is inconsistent among places and that could be the root cause of the crash.
I'd like to make sure of the reason of the inconsistent (bug or intentional/spec)

Here's an observation.

mono_get_seq_points https://github.com/mono/mono/blob/bda239f44ca8068c3a6d6cbcb10704c2387ad2f2/mono/mini/seq-points.c#L270-L278
uses `mono_loader_lock` to guard for accessing `(domain)->seq_points`.

But according to `mini-runtime.h` `seq_points` in `MonoJitDomainInfo` should be done by `domain lock`.
https://github.com/mono/mono/blob/bda239f44ca8068c3a6d6cbcb10704c2387ad2f2/mono/mini/mini-runtime.h#L38-L39

For instance, a part of `aot-runtime.c` uses `mono_domain_lock` to access `(domain)->seq_points` 
https://github.com/mono/mono/blob/bda239f44ca8068c3a6d6cbcb10704c2387ad2f2/mono/mini/aot-runtime.c#L3369-L3375

I wonder if mistakenly `mono_get_seq_points` uses `mono_loader_lock`.
Or intentionally using these different locaking object in each places?

Note:
By the way, although the platform & based mono version are different, but my *crash* is quite similar with https://github.com/mono/mono/issues/15518

**Comment by vargaz** [comment]
Yes, it should probably use the domain lock.

**Comment by takayuki-kazama** [comment]
Thanks for the comment, I will try to test it locally even though the reproducible rate is quite low.

**Comment by vargaz** [comment]
Thanks for the report.

**Comment by lambdageek** [comment]
Great research @takayuki-kazama ! 🎉

**Comment by takayuki-kazama** [comment]
Technically the research & the report were done by my co-worker -- so the credit is not on me, haha.

**Comment by takayuki-kazama** [comment]
I will close this question because I see the PR relating to this.
Thanks for your comments & help.

**Comment by lambdageek** [comment]
I'd like to keep the issue opened until the PR is merged.

**Comment by lambdageek** [comment]
For posterity, I think the origin of this bug is that 4ea0323445a89ae2ff47b940ae703903fefccedb was an incomplete revert of 6f41607cc3b9c34e54716efe35d22d31132545d9 which left one instance of `MonoDomainJitInfo:seq_points` protected by the loader lock instead of the domain lock.
