### ISSUE TITLE
Blazor: Debugging broken if project folder path contains spaces

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#17764]
_From @amewsaj on Monday, June 17, 2019 12:35:05 PM_

### Describe the bug
When attempting to add breakpoints in the browser debug tools, the breakpoint immediately disappears if the project folder path contains spaces (like the Users folder). 

### To Reproduce
Create a Blazor project in a folder with a path containing spaces.
Enable Blazor debugging
Start debugging in the browser (Alt+Shift+D)
Go to Blazor code in the browser debugging tools
Attempt to add breakpoint
Breakpoint is instantly removed again

### Expected behavior
Debugging should work as usual, even if a path contains spaces,

_Copied from original issue: aspnet/AspNetCore#11285_

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Monday, June 17, 2019 4:26:16 PM_

Thanks for contacting us, @amewsaj.
We're going to handle this issue post 3.0 release as we're focused on most critical issues for that release only.

**Comment by CoffeeFlux** [comment]
cc: @thaystg

**Comment by lewing** [comment]
@tqiu8 can you test this case

**Comment by tqiu8** [comment]
Breakpoint hit in Blazor code, with project path being `~/Desktop/Desktop/Hello World/`

![Screen Shot 2020-04-09 at 4 36 06 PM](https://user-images.githubusercontent.com/16296328/78938616-8391e280-7a80-11ea-871b-4ff84b572b08.png)

![Screen Shot 2020-04-09 at 4 36 36 PM](https://user-images.githubusercontent.com/16296328/78938634-88569680-7a80-11ea-9e0f-00ff0313caaf.png)
