### ISSUE TITLE
can mono support enable bitcode on iOS?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17776]
can I enable bitcode on iOS? with this line?

https://github.com/mono/mono/blob/5bc4944bf09ccf0a56a28c8e5a957d6001f51063/sdks/builds/ios.mk#L201

and how aot code (.s) support bitcode?

I open uncommented it but also occurred the problem:
UATHelper: Packaging (iOS):   ld: bitcode bundle could not be generated because '/Users/g111_test/g111_root/trunk_branch/code/client/game/Plugins/UnrealMono/platforms/iOS/custom/ios-target64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-icall.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Arc
hive or Install build for architecture arm64

**Comment by srxqds** [comment]
I add the define **ios-target64_CONFIGURE_FLAGS = --enable-llvm-runtime --with-bitcode=yes** also occurred the error.

**Comment by srxqds** [comment]
@marek-safar  hi, could you give me an answer?

**Comment by lewurm** [comment]
we probably miss `-no-undefined` somewhere in `./mono/mini/Makefile.am.in`

The real question: Why do you want to build with bitcode on iOS? I recommend not doing that.

**Comment by srxqds** [comment]
> we probably miss `-no-undefined` somewhere in `./mono/mini/Makefile.am.in`
> 
> The real question: Why do you want to build with bitcode on iOS? I recommend not doing that.

The ue4 build ship default with enable bitcode
