### ISSUE TITLE
System.DllNotFoundException: __Internal on monodroid

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17771]
## Steps to Reproduce

1. build with static lib **libmonosgen.a**, **libmono-native.a** and **libMonoPosixHelper.a**
2. remap dll use:
```c
void register_dllmap()
{
    mono_dllmap_insert (NULL, "System.Native", NULL, "__Internal", NULL);
    mono_dllmap_insert (NULL, "System.Net.Security.Native", NULL, "__Internal", NULL);
}
```
3. 

### Expected Behavior

Find it correctly.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] Android

**Version Used**:

mono-6.0.0.334
## Stacktrace

```
```

error: System.TypeInitializationException: The type initializer for 'AndroidTimeZones' threw an exception. ---> System.DllNotFoundException: __Internal
11-11 09:20:13.747 22942 22981 D UE4     :   at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
11-11 09:20:13.747 22942 22981 D UE4     :   at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.IO.File.Exists (System.String path) [0x00043] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.TimeZoneInfo+AndroidTimeZones.GetDefaultTimeZoneDB () [0x0000a] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.TimeZoneInfo+AndroidTimeZones..cctor () [0x00000] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :    --- End of inner exception stack trace ---
11-11 09:20:13.747 22942 22981 D UE4     :   at System.TimeZoneInfo.CreateLocal () [0x00000] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.TimeZoneInfo.get_Local () [0x00009] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.CurrentSystemTimeZone..ctor () [0x00011] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 09:20:13.747 22942 22981 D UE4     :   at System.TimeZone.get_CurrentTimeZone () [0x00024] in <f1f88364e2ba4120a3e31590c1ecfd00>:0

**Comment by lambdageek** [comment]
@srxqds it is not clear to me, are you using Xamarin.Android or are you building Mono yourself for Android? 

If you are using Xamarin.Android, this is a possible duplicate of #17693 

If you are building Mono yourself, please try setting the environment variables MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll and run your sample and provide the output.
Also please provide source code to a complete example that demonstrates the issue, if possible.

**Comment by srxqds** [comment]
> @srxqds it is not clear to me, are you using Xamarin.Android or are you building Mono yourself for Android?
> 
> If you are using Xamarin.Android, this is a possible duplicate of #17693
> 
> If you are building Mono yourself, please try setting the environment variables MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll and run your sample and provide the output.
> Also please provide source code to a complete example that demonstrates the issue, if possible.


I use building mono myself with embedd

**Comment by srxqds** [comment]
11-11 21:22:22.619 14754 14801 D Mono    : DllImport attempting to load: '__Internal'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library './__Internal': 'undefined symbol: Java_com_epicgames_ue4_GameActivity_nativeHandleSensorEvents___3F_3F_3F_3F'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '/system/lib64/__Internal': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '__Internal': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '__Internal': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library './lib__Internal': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library 'lib__Internal': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.619 14754 14801 D Mono    : DllImport error loading library 'lib__Internal': '(null)'.
11-11 21:22:22.619 14754 14801 W Mono    : DllImport unable to load library '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport attempting to load: '__Internal'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library './__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '/system/lib64/__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library './lib__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library './lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library '/system/lib64/lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library 'lib__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library 'lib__Internal.so': '(null)'.
11-11 21:22:22.622 14754 14801 D Mono    : DllImport error loading library 'lib__Internal': '(null)'.
11-11 21:22:22.622 14754 14801 W Mono    : DllImport unable to load library '(null)'.
11-11 21:22:22.641 14754 14801 D UE4     : [2019.11.11-13.22.22:641][222]LogMono: Error: TriggerEvent call event callback error: System.TypeInitializationException: The type initializer for 'AndroidTimeZones' threw an exception. ---> System.DllNotFoundException: __Internal
11-11 21:22:22.641 14754 14801 D UE4     :   at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
11-11 21:22:22.641 14754 14801 D UE4     :   at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.IO.File.Exists (System.String path) [0x00043] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.TimeZoneInfo+AndroidTimeZones.GetDefaultTimeZoneDB () [0x0000a] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.TimeZoneInfo+AndroidTimeZones..cctor () [0x00000] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :    --- End of inner exception stack trace ---
11-11 21:22:22.641 14754 14801 D UE4     :   at System.TimeZoneInfo.CreateLocal () [0x00000] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.TimeZoneInfo.get_Local () [0x00009] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.CurrentSystemTimeZone..ctor () [0x00011] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 
11-11 21:22:22.641 14754 14801 D UE4     :   at System.TimeZone.get_CurrentTimeZone () [0x00024] in <f1f88364e2ba4120a3e31590c1ecfd00>:0 

hi, @lambdageek  this is the all traceback

**Comment by srxqds** [comment]
@lambdageek We emebeded mono with ue4, I found that ue4 will build mono library into libUE4.so file whether I linked with dynamic (.so) or static (.a) libray.

But how can I fixed it?

**Comment by CoffeeFlux** [comment]
`11-11 21:22:22.619 14754 14801 D Mono : DllImport error loading library './__Internal': 'undefined symbol: Java_com_epicgames_ue4_GameActivity_nativeHandleSensorEvents___3F_3F_3F_3F'.`
Seems like your library is missing the symbol you're trying to call? I don't know much about our interaction with UE4.

**Comment by srxqds** [comment]
I solved it by linke with .so and use ** mono_dl_fallback_register**.
thank you @CoffeeFlux  @lambdageek
