### ISSUE TITLE
UnixSignals.WaitOne(_timeout_) throws ObjectDisposedException on dotnet core 3.0.100

### ISSUE THREAD

**Issue by Musashi178** [mono/mono#17812]
## Steps to Reproduce

1. Unzip the attached project console_3
2. Call "dotnet run" in the folder

This is the code that gets executed

```
using System;
using System.Threading;
using Mono.Unix;
using Mono.Unix.Native;

  class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var signal = new UnixSignal(Signum.SIGHUP);

            signal.WaitOne(TimeSpan.FromSeconds(1));
            
            Console.WriteLine("Done");
        }
    }
```

[console_3.zip](https://github.com/mono/mono/files/3852108/console_3.zip)

### Current Behavior

A `System.ObjectDisposedException` is thrown when calling the `WaitOne`

### Expected Behavior

The `WaitOne` should wait for one second and then the execution should be continued

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
dotnet 3.0.100

## Stacktrace

```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout)
```

**Comment by marek-safar** [comment]
Please report .NET Core issues at https://github.com/dotnet/coreclr
