### ISSUE TITLE
suggestion: System.Net.Http.dll in monotouch remove Xmarin.iOS.dll reference

### ISSUE THREAD

**Issue by srxqds** [mono/mono#17819]
The code : https://github.com/mono/mono/blob/18dd48cad81592f66ce7d21a5293c76d69864501/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs#L48

xamarin/macios can make another api in Xmarain.iOS.dll for RuntimeOptions.CreateDefaultHandler.

I think it is friendly to move to xamarin/macios, if do it there are two advantages:
1. the **System.Net.Http.dll** don't need depending on **Xamrain.iOS.dll**, when embed mono without **xamarin/xamarin-macios built. it breaks the defulat constructor behavie.
2. the **xamarin-macios** should not linker process for RuntimeOptions.CreateDefaultHandler:
https://github.com/xamarin/xamarin-macios/blob/481d5ef9ab54129826856347d20bd35eb975ce56/tools/linker/CoreHttpMessageHandler.cs#L69

**Comment by marek-safar** [comment]
We actually want to do the opposite (not to do any BCL updates in Xamarin.iOS)

**Comment by srxqds** [comment]
> We actually want to do the opposite (not to do any BCL updates in Xamarin.iOS)

But the **xamarin-macios** also linker to rewrite the **RuntimeOptions.CreateDefaultHandler** method in https://github.com/xamarin/xamarin-macios/blob/481d5ef9ab54129826856347d20bd35eb975ce56/tools/linker/CoreHttpMessageHandler.cs#L69 
I think it is also doing to modify the BCL.
