### ISSUE TITLE
Japanese font not display completely on Windowsform at Linux

### ISSUE THREAD

**Issue by ginga81** [mono/mono#17824]
## Steps to Reproduce

1.Using the Japanese font with Windowsform.(UTF-8)
2.Run the program.

Linux(Ubuntu 18.04LTS):not perfectly
![open-menu-broken](https://user-images.githubusercontent.com/22734699/69006805-ed95d800-0977-11ea-9f5a-49dbd696157b.jpg)
Windows:perfectly displaying
![openbve-mono-broken-windows](https://user-images.githubusercontent.com/22734699/69006810-00a8a800-0978-11ea-93f2-37aa7e8ac19c.jpg)

### Current Behavior
Jpanese fonts that used to be displayed perfectly on the WindowsForm, that are no longer displayed correctly.
I looked this trouble at Button and Labels.

### Expected Behavior

I want to restore so that it is displayed correctly.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.6.0.154 (tarball Fri Nov  8 11:01:23 UTC 2019)

**Comment by filipnavara** [comment]
What is your installed version of libgdiplus?

**Comment by ginga81** [comment]
Sorry.
I do not know how to check the libgdiplus's version.
If this is not an answer, please tell me how to check.

user@~$ apt list | grep libgdiplus
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
libgdiplus/preview-bionic,now 6.0.4-0xamarin1+ubuntu1804b1 amd64 [インストール済み、自動]

**Comment by filipnavara** [comment]
Thanks, it's the correct answer. I was mainly checking because lot of machines run a 2+ year old builds of the library. Version 6.0.4 is the most recent one and it should be built with Pango layout engine to handle complex scripts like Japanese. That said, it is not thoroughly tested because none of the recent contributors have first hand experience with these scripts.

Note that the WinForms code is supported only by community so there's no guarantee when, or if, the problem will get fixed. It may help if you attach a small test application to the issue to reproduce the issue.

**Comment by ginga81** [comment]
I created a simple sample program.
Can I attach sample exe file (with zip) here ?
Or a sample code write here?

**Comment by filipnavara** [comment]
Just attach a .zip file with the project here. No need to include pre-compiled .exe. Thanks

**Comment by ginga81** [comment]
This is a sample windows form program.
Please check it.
[windowsfoorm-test.zip](https://github.com/mono/mono/files/3857946/windowsfoorm-test.zip)

**Comment by ginga81** [comment]
After this post, I test and fallbacked to the old libgdiplus, at the Ubuntu18.04, this problem is not happen.
I downloaded from
https://packages.ubuntu.com/bionic/amd64/libgdiplus/download
libgdiplus_4.2-2_amd64.deb.
At Fedora, my frend faces the same issue, and posted to libgdiplus's github.
So, we are consider to be libgdiplus's ploblem.
Please check it also.
mono/libgdiplus#628

**Comment by ginga81** [comment]
https://github.com/mono/libgdiplus/pull/628
has been merged.
So, this issue is closed.
Thank you very much.
