### ISSUE TITLE
[WASM] Using mono_call_assembly_entry_point results in an uninitialized args array being passed to Program.Main

### ISSUE THREAD

**Issue by pranavkm** [mono/mono#17831]
Noticed this when I attempted to [upgrade Blazor](https://github.com/aspnet/AspNetCore/pull/17050/files) to use the `mono_call_assembly_entry_point` API. In our case, we always pass in an empty array as the value of the `args` array. If I print the length of `args` parameter in `Program.Main` or access one of the indices it prints out random values. Here's the PR in question if that helps figure out if we're doing something incorrect: https://github.com/aspnet/AspNetCore/commit/ff4791ea903481e3f6c52ce0d0dc0315aecc9ae5

**Comment by kjpou1** [comment]
Thanks for letting us know.  

Instead of an empty array `[]` call with the following: 
```
Module.call_assembly_entry_point("YourAssemblyHere.exe", [null]);
```

**Comment by SteveSandersonMS** [comment]
Thanks @kjpou1. Could you clarify what the null means in this case? Is it intentional that you need to pass it? And what would be the way to pass a nonempty set of params?

This isn’t urgent. I’m just curious!

**Comment by pranavkm** [comment]
To add to @SteveSandersonMS 's question, would we also need to do this if we were to use `mono_method_invoke` i.e. determine the method signature and pass the `null` value if the value for an argument isn't available? Could the runtime be changed to throw an error if values for all arguments aren't supplied? Having it point to what looks like uninitialized memory seems really strange.

**Comment by kjpou1** [comment]
Sorry thought I referenced this in the issue that I set up for this.  The new issue will throw an error if the arguments provided do not match the signature.
