### ISSUE TITLE
how to build fsharpc, fsharpi?

### ISSUE THREAD

**Issue by jwaldmann** [mono/mono#17830]
Hi. Please forgive the simple-minded question: 

how to build fsharpc, fsharpi under GNU/Linux from source?

I was directed here by https://github.com/dotnet/fsharp/issues/7879#issuecomment-554850620

I have been searching this (mono/mono) repo, hoping to find something like  `./configure --enable-fsharp`, or some mention in some README.

I found https://github.com/mono/mono/commit/c16b4cff44e6580e650c31b0b00b6865f4e4b8da but it seems Mac-specific.

The only mention of "fsharpi" is in "packaging/Windows/defs/managed-components" but I don't know what that means and how I would enable it. "./configure --help" says nothing about components (or I don't recognize it).

NB: in case you're wondering why: in my lecture I am showing "units of measure" types https://www.imn.htwk-leipzig.de/~waldmann/edu/ws19/pps/folien/#(93) and I want to encourage students to play with them. So I want to provide an up-to-date F# compiler in our computer pool.

**Comment by directhex** [comment]
F# is a separate repo to Mono, but is bundled in to the Mac/Windows installers. The bundle happens via this script: https://github.com/mono/mono/blob/master/packaging/MacSDK/fsharp.py

Roughly speaking, the equivalent we use on Linux is https://github.com/mono/linux-packaging-fsharp/blob/master/debian/rules
