### ISSUE TITLE
Problem with apt-get on debian 10 arm64

### ISSUE THREAD

**Issue by jgilbert2017** [mono/mono#17840]
delete

**Comment by directhex** [comment]
Are you behind some kind of firewall or proxy?

**Comment by jgilbert2017** [comment]
no http proxy.

**Comment by jgilbert2017** [comment]
some additional info: also tried beta-buster, nightly-buster, stable-xenial which exhibit identical messages.

the standard debian apt sources do not generate these messages and removing the mono apt source removes the error messages so it could be something specific about the mono Packages file that is causing the issue.

**Comment by directhex** [comment]
My suspicion, reading the Apt source, is whatever mechanism you used to copy-paste the repo into your sources, also caused it to copy-paste an invisible control character of some kind, like a non-breaking space, or a newline, or something.

**Comment by jgilbert2017** [comment]
interesting... i will investigate.  thank you.

**Comment by jgilbert2017** [comment]
i ran the following test and still have the issue:
rm /etc/apt/sources.list.d/*
apt-get update # ok, no errors
cat - > /etc/apt/sources.list.d/mono-official-stable.list
(typed) deb https://download.mono-project.com/repo/debian stable-buster main

^D (eof)
cat -v /etc/apt/sources.list.d/mono-official-stable.list
(no weird chars shown)

apt-get update
<same error messages>
:-(

when i looked at the apt sources yesterday i thought those errors were from parsing the Packages file which seems to be <tag>:<value> if there are control chars in one of those.

**Comment by directhex** [comment]
`curl -sLD - https://download.mono-project.com/repo/debian/dists/stable-buster/Release` ?

**Comment by jgilbert2017** [comment]
see attached.
curl output looks ok to my naked eye.

i also did "strace -o strace.txt -f -F apt-get update" and captured the failure.  i've included only an excerpt but it think the error should be in there.

[strace-partial.txt](https://github.com/mono/mono/files/3871209/strace-partial.txt)
[curl.txt](https://github.com/mono/mono/files/3871210/curl.txt)

**Comment by jgilbert2017** [comment]
hmm, a real head scratcher.  the strace looks like it grabs /var/lib/apt/lists/download.mono-project.com_repo_debian_dists_stable-buster_InRelease .

i don't see anything obviously wrong with the contents of the file.

**Comment by julian-klode** [comment]
Hey guys, to debug this further, it needs a log with `-o Debug::pkgAcquire::Worker=1` and `-o Debug::Acquire::http=1`, maybe `-o Debug::Acquire::https=1`.

The error happens when the server is sending an redirect URL that contains an invalid character (not printable, not tab, not newline, not unicode).

**Comment by jgilbert2017** [comment]
Julian!  thanks for joining!!! debug log attached.

[aptdebug.txt](https://github.com/mono/mono/files/3871386/aptdebug.txt)
