### ISSUE TITLE
[wasm] System.InvalidCastException with HttpClient.GetStringAsync and WasmHttpMessageHandler

### ISSUE THREAD

**Issue by cradle77** [mono/mono#17874]
I'm developing a Blazor WebAsembly app, using VS2019 16.4.0 Preview 6.0

I have migrated the project from `3.1.0-preview2.19528.8` to `3.1.0-preview3.19555.2`.

No changes in code, just the references, reverting back to `3.1.0-preview2.19528.8`  works just fine.

Here's a project in GitHub that reproduces it:
[Branch referencing `3.1.0-preview3.19555.2`](https://github.com/cradle77/Blazor.Msal/tree/features/Preview3): has the issue
[Master branch referencing `3.1.0-preview2.19528.8`](https://github.com/cradle77/Blazor.Msal): same code, no issue

Stack trace:
```blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: System.InvalidCastException: Specified cast is not valid.
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.doFetch (System.Threading.Tasks.TaskCompletionSource`1[TResult] tcs, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x20db010 + 0x0085e> in <ba6f8206dad14230ab6c0c01a98cb097>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x20b12c8 + 0x00176> in <ba6f8206dad14230ab6c0c01a98cb097>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) <0x20ea8e8 + 0x0011c> in <bda5d5640ced47338fc44edd4c047f3b>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpClient.GetStringAsyncCore (System.Threading.Tasks.Task`1[TResult] getTask) <0x20f4770 + 0x000e0> in <bda5d5640ced47338fc44edd4c047f3b>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 
```

I've tried disabling the browser cache and cleaning up the solution, no effect.

Possibly related to https://github.com/mono/mono/issues/17845

**Comment by cradle77** [comment]
Hi @kjpou1,

I've dug further into this and I've realized that it's ultimately caused by a reference to Bluebird I was originally using.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js"></script>
```

I could remove it as I'm not using it anymore, but I'd probably investigate why it is clashing with the new `WasmHttpMessageHandler`.

I'll keep the branch alive for you to investigate, if it helps.

**Comment by kjpou1** [comment]
Hello @cradle77 was wondering how to get past this screen when running.

![image](https://user-images.githubusercontent.com/640466/69418603-4cae7080-0d1b-11ea-840d-ee35f9b80699.png)

**Comment by cradle77** [comment]
Hi @kjpou1, if you get to that point, it means that you've clicked the Login button and `WasmHttpMessageHandler` is working :)

When you load the first page of that application, there's a XHR to `config/appsetting.json` that fails in the repro branch and succeeds in the master branch.

If you clone the repository and switch to the /features/Preview3 branch, you'll see the error as soon as the application launches.

Please do let me know if you need further info on how to reproduce it.

**Comment by kjpou1** [comment]
Oh, great I thought it was further in.  Thanks.

**Comment by kjpou1** [comment]
Indeed it is the Bluebird Promise library.  I have set up a tracking issue for this in the bindings:  https://github.com/mono/mono/issues/17895 as this also affects more than just the http handler.

**Comment by cradle77** [comment]
Thanks Kenneth.

**Comment by kjpou1** [comment]
I still need to test this specific fix on Blazor and your repro project.  Could you leave that available until this is closed.  

Also, thank you very much for the repro.

**Comment by cradle77** [comment]
No problem at all, it doesn’t cost me anything 😉
