### ISSUE TITLE
HttpClientHandler: redirection to relative URL does not work

### ISSUE THREAD

**Issue by aliriomendes** [mono/mono#17897]
## Steps to Reproduce

1. Execute this code:
```
var client = new HttpClient(new HttpClientHandler());
var res = await client.GetAsync("https://oaa365.sharepoint.com/:x:/s/Development/ESKK8ZI2L2NEvKCM-4rN6rcB3a2i3245l_7uw3mERhNcVw?e=GExumW&download=1");
```

If I use the legacy implementation  it works
```
var monoHandlerType = typeof(HttpClientHandler).Assembly.GetType("System.Net.Http.MonoWebRequestHandler");

var monoHandler = monoHandlerType.GetConstructor(BindingFlags.NonPublic | BindingFlags.Instance, null, Type.EmptyTypes, null).Invoke(null);

var handler = (HttpClientHandler)typeof(HttpClientHandler).GetConstructor(BindingFlags.NonPublic | BindingFlags.Instance, null, new[] { monoHandlerType }, null).Invoke(new[] { monoHandler });

handler.AllowAutoRedirect = true;

var client = new HttpClient(handler);

var res = await client.GetAsync("https://oaa365.sharepoint.com/:x:/s/Development/ESKK8ZI2L2NEvKCM-4rN6rcB3a2i3245l_7uw3mERhNcVw?e=GExumW&download=1");
```

### Expected Behavior
HttpClientHandler handles the redirect and the file is downloaded correctly.

### Actual Behavior
The redirect is not fallowed, just the first request is sent.

## On which platforms did you notice this

[x] Xamarin.Android

**Version Used**:
Visual Studio Community 2019 for Mac
Version 8.3.10 (build 2)

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

NuGet
Version: 5.3.0.6192

Xamarin.Android
Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/aliriomendes/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 28.0.3

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Operating System
Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

## Stacktrace

```
12|2019-11-25T10:58:23.1820870+00:00|ERROR|1|TelemetryServiceBase|FormAppPage2 LoadContent --> System.Net.Http.HttpRequestException: Response status code does not indicate success: 302 (Found).
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () [0x00040] in <c85119bf7e3e421490ae6b5487992fff>:0 
  at System.Net.Http.HttpClient.GetStringAsyncCore (System.Threading.Tasks.Task`1[TResult] getTask) [0x00096] in <c85119bf7e3e421490ae6b5487992fff>:0 
  at wunderapp.Core.DataProviders.DefaultDataProvider.DownloadFileAsync (System.String appId, System.String fileId, System.Boolean includeData, System.Boolean nonInteractive) [0x001f8] in /Users/aliriomendes/OpenAsApp/Clients/wunderapp/wunderapp/wunderapp.Core/DataProviders/DefaultDataProvider.cs:53 
  at wunderapp.Core.Services.DataProviderService.DownloadAsync (System.String appId, System.String url, System.Boolean includeData, System.Boolean nonInteractive) [0x000a5] in /Users/aliriomendes/OpenAsApp/Clients/wunderapp/wunderapp/wunderapp.Core/Services/DataProviderService.cs:29 
  at wunderapp.Core.Services.DataProviderService.DownloadAsync (System.String appId, System.String url, System.Boolean nonInteractive) [0x00032] in /Users/aliriomendes/OpenAsApp/Clients/wunderapp/wunderapp/wunderapp.Core/Services/DataProviderService.cs:15 
  at wunderapp.Core.Services.Installation.AppInstaller.LoadContentAsync (wunderapp.Core.AppParameters parameters) [0x002b5] in /Users/aliriomendes/OpenAsApp/Clients/wunderapp/wunderapp/wunderapp.Core/Services/Installation/AppInstaller.cs:47 
  at wunderapp.FormAppPage.LoadContent () [0x001c4] in /Users/aliriomendes/OpenAsApp/Clients/wunderapp/wunderapp/wunderapp/Pages/FormAppPage.cs:361 
```

**Comment by baulig** [comment]
I debugged this and it looks like something goes wrong when parsing the server's response headers.  The redirection is then rejected because of the prohibited target URL.

**Comment by aliriomendes** [comment]
> I debugged this and it looks like something goes wrong when parsing the server's response headers. The redirection is then rejected because of the prohibited target URL.

The second URL needs a FedAuth token, this token comes in the cookies of the first request. If the cookies are not forwarded, the second request will not work.

**Comment by baulig** [comment]
Okay, this is actually the header parsing code as I expected.  The server returns

```
Location: /sites/....
```

we then call [`UriHeaderParser.TryParseValue`](https://github.com/mono/corefx/blob/1cdb9c20946c74a88a7fa507215556fadc2c2b27/src/System.Net.Http/src/System/Net/Http/Headers/UriHeaderParser.cs#L25) with

```
value = "/sites/Development/..."
storeValue = null
index = 0
```

which then calls `Uri.TryCreate()` with `UriKind.RelativeOrAbsolute`.

This returns a `file:///` URI.  Since any redirection from `https` to something else is prohibited, the redirect is then rejected.

**Comment by baulig** [comment]
There must be _some_ kind of a subtle difference either in our `Uri` implementation or between our corefx fork and their latest master.

It is perfectly fine for a server to return `Location: /some/path` - that must be correctly interpreted as a relative link.

**Comment by baulig** [comment]
Now that I identified the problem, it shouldn't be too difficult for me to write a stand-alone test case for it.  And then I'll investigate what exactly is going on in .NET Core.

**Comment by baulig** [comment]
Found the problem!

```
var result = Uri.TryCreate ("/some/path", UriKind.RelativeOrAbsolute, out var uri);
Console.WriteLine ($"RESULT: {result} {uri} {uri.IsAbsoluteUri}");
```

on .NET Core this prints

```
RESULT: True /some/path False
```

on Mono, it prints

```
RESULT: True file:///some/path True
```

This then breaks here: https://github.com/mono/corefx/blob/1cdb9c20946c74a88a7fa507215556fadc2c2b27/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs#L98.

**Comment by baulig** [comment]
Now as a workaround, if you set the `MONO_URI_DOTNETRELATIVEORABSOLUTE=true` environment variable, this will work.
