### ISSUE TITLE
Blazor: Obfuscation

### ISSUE THREAD

**Issue by GerritBergen** [mono/mono#17987]
[Original thread](https://github.com/aspnet/AspNetCore/issues/17494)

**Describe the bug**

I read that obfuscation is technically possible, because the blazor files are just .dll files. So I built a project, and obfuscated the Client/dist/_framework/_bin/client.dll file, but running it just crashes:

    WASM: ﻿System.AggregateException: One or more errors occurred. (Method not found: int System.BitConverter.ToInt32(byte[],int)) ---> System.MissingMethodException: Method not found: int System.BitConverter.ToInt32(byte[],int) blazor_web.js:2046:68

And:

    WASM: Unknown heap type: #YoCUQ blazor_web.js:2046:68

Any ideas?

**Comment by kjpou1** [comment]
Can you try disabling the linker and see whether that works?
Simply set the `BlazorLinkOnBuild` property to `false` as shown below:
```xml
<PropertyGroup>
  <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
</PropertyGroup>
```

**Comment by GerritBergen** [comment]
Still getting the unknown heap type messages, but it runs with linking turned off

**Comment by ChristianWeyer** [comment]
Did you ever get anything to work with regard to obfuscation @GerritBergen ?

**Comment by GerritBergen** [comment]
@ChristianWeyer Obfuscation worked fine for me without turning off linker on Blazor WebAssembly 3.2.0 Preview 3. Haven't tried on Preview 4.

**Comment by ChristianWeyer** [comment]
Nice. Which tool are you using?

**Comment by GerritBergen** [comment]
Any obfuscator that supports .Net Standard should obfuscate it as far as I'm aware
