### ISSUE TITLE
[Blazor WASM] Uncatched Http Exception when using AWS Cognito with v3.1.0-preview4

### ISSUE THREAD

**Issue by daniel-rck** [mono/mono#18005]
EDIT: Original issue came up with v3.1.0-preview3, same problem is with v3.1.0-preview4.

## Steps to Reproduce

I'm running Blazor and using AWS Cognito for authentication. When I try to login with wrong credentials in v3.1.0-preview3 there is an unhandled exception. Doing the same in v3.1.0-preview2 the exception is catched correctly:

1. Running Blazor Webassembly in .NET Core v3.1.0-preview3
2. Using AWS Cognito for authentication like this:
```
    @inject HttpClient http

    <div>
        <button type="button" class="btn btn-danger bg-red" @onclick="@(() => LoginAsync())">Login</button>
    </div>

    @code{
        public async Task LoginAsync()
        {
            var service = new AuthenticationServiceOnBlazor(http);
            await service.TryLoginAsync(Email, Password);            
        }
    }
```

See `AuthenticationServiceOnBlazor` here: https://gist.github.com/Daniel-NP/b83dd830eec94b044e135abf3d0cf533

3. Try Login with false credentials and run into Error HTTP 400. LogFiles:
[localhost-1575277118676_working.log](https://github.com/mono/mono/files/3915155/localhost-1575277118676_working.log)
[localhost-1575277316689_failing.log](https://github.com/mono/mono/files/3915156/localhost-1575277316689_failing.log)

### Current Behavior
The exception that comes from AWS isn't catched and the blazor application hangs without responding. Even the chrome debugging process doesn't react and needs to be killed from taskmanager.

### Expected Behavior
Exception beeing catched in try-catch-clause within my AuthenticationService to display the problem.
On Blazor v3.1.0-preview2 this works as expected. v3.1.0-preview3 is failing.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:

- ASP.NET Core version 3.1.0-preview3
- Visual Studio 2019 v16.4.0 Preview 6

 I already submitted an issue on aspnetcore, but it's probably not a blazor specific issue: https://github.com/aspnet/AspNetCore/issues/17514

**Comment by lewing** [comment]
@kjpou1 can you verify that this is working in current/preview4?

**Comment by Daniel-NP** [comment]
@kjpou1 Same problem with preview 4.

**Comment by kjpou1** [comment]
Hey @Daniel-NP thanks for testing that.  Is there any way you can explain how to recreate the problem.  Maybe a small project that we can reference that demonstrates the use AWS Cognito?

**Comment by Daniel-NP** [comment]
@kjpou1
I created a small sample-repo for testing: https://github.com/Daniel-NP/AwsCognitoExample
Moreover I added comments in https://github.com/Daniel-NP/AwsCognitoExample/blob/master/AwsCognitoExample.csproj to clarify which versions are working.

It doesn't matter what credentials you enter, the problem occurs on wrong credentials anyway.

**Comment by kjpou1** [comment]
Thanks @Daniel-NP we will take a look at it.

**Comment by daniel-rck** [comment]
I'll bury this one. 4 years since creation. Dotnet 3.1 EOL. Bye bye isse.
