### ISSUE TITLE
patch configure.ac to build on FreeBSD/PowerPC64

### ISSUE THREAD

**Issue by igorzigorz** [mono/mono#18009]
[patch-freebsd-powerpc64-configure_ac.txt](https://github.com/mono/mono/files/3917296/patch-freebsd-powerpc64-configure_ac.txt)

Patch configure.ac to build on powerpc64.

FreeBSD
Mono version 6.4.0.198

**Comment by lambdageek** [comment]
Hi @igorzigorz - it's better to [open a Pull Request](https://github.com/mono/mono/compare) when you have a patch for us.  If you need help, [talk to us on Gitter](https://gitter.im/mono/mono) and the folks there can help you to make a fork of Mono and make a pull request.

For this patch, I created a new pull request here: https://github.com/mono/mono/pull/18015

**Comment by lambdageek** [comment]
I'm going to close this issue. Let's move discussion to #18015
