### ISSUE TITLE
mono-io-layer-error (-1) exception on Android with Mono6.4 and AdGuard used

### ISSUE THREAD

**Issue by jonathanantoine** [mono/mono#18030]
## Steps to Reproduce

1. Install AdGuard on your Android device
2. Perform an http request using the native client handler on Android release version with mono 6.4

### Current Behavior

The request fail with this error message : mono-io-layer-error (-1)

### Expected Behavior
The request works as before

## On which platforms did you notice this

[ x] Android
[ ] Linux
[ ] Windows

**Version Used**:

Mono 6.4 from App center
## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by CoffeeFlux** [comment]
It looks like AdGuard sets up a local VPN and uses that to filter the traffic? So either we don't handle having a VPN enabled well or it's modifying the requests in a way we can't handle?

**Comment by jonathanantoine** [comment]
If it can help, I want to access this URL : 
```
https://itunes.apple.com/us/rss/toppodcasts/genre=1401/limit=30/json
```

**Comment by CoffeeFlux** [comment]
@jonathanantoine is there any chance you could upload a standalone repro and include the full error?

**Comment by omsting** [comment]
We had the same bug and I managed to reproduce it by activating DNS Filtering in AdGuard.

**Comment by CoffeeFlux** [comment]
Is there any chance you can give me a repro app and exact AdGuard settings?

**Comment by omsting** [comment]
I'm sorry, but I don't have a repro app. I do have more information more information. We use Xamarin and we started to have this issue when we upgraded to mono 6.4. Here is a snippet of what I get in my output:
`FFImageLoading.Exceptions.DownloadAggregateException: One or more errors occurred. (mono-io-layer-error (-1)) ---> System.Net.Http.HttpRequestException: mono-io-layer-error (-1) ---> System.Net.Sockets.SocketException: mono-io-layer-error (-1)
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x000c8] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:65 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00180] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:84 
  at System.Threading.Tasks.ValueTask1[TResult].get_Result () [0x0001b] in /Users/builder/j12-17 16:01:55.618 I/mono-stdout(30091): FFImageLoading.Exceptions.DownloadAggregateException: One or more errors occurred. (mono-io-layer-error (-1)) ---> System.Net.Http.HttpRequestException: mono-io-layer-error (-1) ---> System.Net.Sockets.SocketException: mono-io-layer-error (-1)`

About AdGuard, I only had DNS Filtering activated and it was the difference. We asked our users who reported a problem related to this issue and so far no one used such software.

**Comment by CoffeeFlux** [comment]
I don't even see a DNS Filtering setting when installing the app on a fairly new Android phone, and just having the app installed is not breaking the following code:

```
            var clientHandler = new Xamarin.Android.Net.AndroidClientHandler { Proxy = null, AllowAutoRedirect = false, AutomaticDecompression = DecompressionMethods.None };
            var client = new HttpClient(clientHandler);
            var response = client.GetStringAsync("http://google.com");
```

What Android device and AdGuard version are you using?

**Comment by omsting** [comment]
You have to install the apk from their site, because Google does not allow this type of app.
https://adguard.com/en/adguard-android/overview.html
The app on the store is only an ad blocker for web browsers.
For the Android version, I'm on 7.0

**Comment by omsting** [comment]
We managed to reproduce with this code and DNS Filtering:
`var  httpClient = new HttpClient {BaseAddress = new Uri("https://itunes.apple.com/us/rss/toppodcasts/genre=1401/limit=30/json") };`
`var request = new HttpRequestMessage(HttpMethod.Get, "ready");`
`var response = await httpClient.SendAsync(request);`
`var stream = await response.Content.ReadAsStreamAsync();`

**Comment by CoffeeFlux** [comment]
Got the apk from the site, enabled protection/the vpn and dns filtering, and still no crash. I've uploaded the sample I'm testing with here - can you give it a try? I'd like to isolate whether this is an issue with my device, my adguard config, or the sample I'm using.
[networky.zip](https://github.com/mono/mono/files/3984530/networky.zip)

**Comment by omsting** [comment]
It does work with the Android HttpClient impementation `<AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>`, but not with default one `<AndroidHttpClientHandlerType>System.Net.Http.HttpClientHandler</AndroidHttpClientHandlerType>`. In our app it still does not work properly because it seems that third-party libs like FFImageLoading use System.Net.Http.HttpClientHandler

**Comment by steveisok** [comment]
@baulig If you can help here, please do.

**Comment by CoffeeFlux** [comment]
Ahhhh, my bad. Able to repro, thanks for the sample.

**Comment by jonathanantoine** [comment]
Yeah that's exactly what I got !

**Comment by steveisok** [comment]
This doesn't seem like a runtime issue, so switching assignees.

**Comment by baulig** [comment]
The issue is that `itunes.apple.com` resolves to 5 IP addresses - one IPv4 and 4 IPv6.  When using AdGuard, the DNS query returns the IPv6 addresses first - but IPv6 seems to be disabled, so the first connection attempt fails with a "Network is down" exception.

This is a _synchronous_ connection failure - and we did not correctly set the internal `SocketAsyncEventArgs.in_progress` field in the synchronous code path.

The "special" thing here seems to be that the connect is synchronously failing - whereas in the typical scenario or the host not listening on that port, it seems to be an async failure (which does reset that flag).

**Comment by baulig** [comment]
I could actually reproduce this with Desktop Mono - with a few little hacks.

First, you have to somehow intercept the DNS query and make sure it returns IPv6 first (I did that by editing the DNS query code) - and then turn off IPv6 on the machine.

**Comment by baulig** [comment]
The `mono-io-layer-error` is actually some generic exception code for "unknown" failures - such as the `InvalidOperationException` in `SocketAsyncEventArgs.SetLastOperation()`.

**Comment by akoeplinger** [comment]
Reopening until it flows to all branches.

**Comment by jonathanantoine** [comment]
Thanks a lot for this fix and explanation !!!
