### ISSUE TITLE
how to detect MonoMethod is override for class?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#18060]
how to detect MonoMethod is override full class?

I have got MonoMethod and I want to know whether it is **override** modifer?
for example
```c#
class Test
{
public void virtual TestVirtual()
{
}

public void override TestOverride()
{
}
}
```

The method **TestVirtual** is not override method but **TestMethod** is.

**Comment by srxqds** [comment]
If the method->flags has ** METHOD_ATTRIBUTE_NEW_SLOT** is virtual?

**Comment by lambdageek** [comment]
Please see section II.10.3 of the [ECMA-335 standard document](https://www.ecma-international.org/publications/standards/Ecma-335.htm).

The newslot attribute affects virtual method layout, but the overall algorithm is quite complex.

If you have a parent `MonoMethod`, and some child `MonoClass` you will need to look at the `slot` of the parent method and see what method the vtable of the child has in that slot.  (This is an oversimplification - see the implementation of `mono_class_get_virtual_method` for the details).

**Comment by srxqds** [comment]
I think METHOD_ATTRIBUTE_NEW_SLOT is meet my need. I can check the method is virtual which meanse it not override.

thank you.
