### ISSUE TITLE
PowerPC linux build is broken

### ISSUE THREAD

**Issue by alexeydk78** [mono/mono#18064]
Hello. I trying to build git version on my PowerPC mac mini, running gentoo linux. Build stopped with error:

```
make[4]: Entering directory '/root/monobuild/mono/mono/mini'
  CC       libmini_la-exceptions-ppc.lo
exceptions-ppc.c: In function 'mono_arch_handle_altstack_exception':
exceptions-ppc.c:696:9: error: 'MonoContext' {aka 'struct <anonymous>'} has no member named 'uc_mcontext'
  696 |  uc_copy->uc_mcontext.uc_regs = (gpointer)((char*)uc_copy + ((char*)uc->uc_mcontext.uc_regs - (char*)uc));
      |         ^~
```

I quick browse code and found, that struct MonoContext really missing member uc_mcontext, but my C skills is quite low to fix it.

**Comment by lambdageek** [comment]
This is 32-bit PPC, I guess, based on the defines.

**Comment by alexeydk78** [comment]
It is definitely ppc32 - I am building on 7447A - it's PowerPC G4, so label is wrong.

**Comment by alexeydk78** [comment]
@lewurm Thank you, your patch helped, I finish build succesfully!

**Comment by lewurm** [comment]
@alexeydk78 thanks for confirming
