### ISSUE TITLE
xbuild contains absolute path to mono executable

### ISSUE THREAD

**Issue by derived-coder** [mono/mono#18084]
## Steps to Reproduce
Compile mono from source

1. compile it with a custom prefix
I followed guide here: 
https://www.mono-project.com/docs/compiling-mono/linux/

### Current Behavior

Following output I get when executing xbuild.
```
 ./xbuild
./xbuild: line 2: /data/jenkins/workspace/_mono-installer_stable_6.0.0.327/conan-clang8-1-20-3e786531a-224b-4fb5-9acc-fbcdd108f849@tmp/artifactory/conan.tmp4636225651001529715/.conan/data/mono-installer/6.0.0.327/company/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/mono: No such file or directory
```

### Expected Behavior

No error when executing `xbuild`
## On which platforms did you notice this

[ ] macOS
[ X] Linux
[ ] Windows

6.0.0.327

**Comment by marek-safar** [comment]
xbuild is deprecated please upgrade to msbuild

**Comment by derived-coder** [comment]
@marek-safar 
Is MSBuild a 1:1 replacement of xbuild?
How to I compile it, in my mono compilation I do not see it in the bin folder.

**Comment by derived-coder** [comment]
Actually what I need is a portable prebuild version of mono for ubuntu linux, maybe you know more?

**Comment by marek-safar** [comment]
msbuild is available is a package for Ubuntu, see https://www.mono-project.com/download/stable/#download-lin-ubuntu

**Comment by derived-coder** [comment]
@marek-safar 
I know. But this is not a tar ball. I need a portable installation. Do you know what I mean?

**Comment by derived-coder** [comment]
please see following issue:
https://github.com/mono/mono/issues/18200
