### ISSUE TITLE
"No compatible code running" after repeated breakpoint in Android.OS.AsyncTask.RunInBackground()

### ISSUE THREAD

**Issue by brendanzagaeski** [mono/mono#18106]
This report is motivated by a secondary symptom I encountered when attempting to reproduce <https://github.com/xamarin/xamarin-android/issues/3222>.

I'm not sure yet where the root of this problem is. One thought I had based on the involvement of `Android.OS.AsyncTask` was that it might involve the Java interop layer. But I'll submit it here in Mono first based on a guess that it might be possible to fix the issue by adjusting the debugger in some way.

### Steps to reproduce

 1. Open the attached test case in Visual Studio.
 2. Set a breakpoint on the first line of `AsyncTask1.RunInBackground()` (at *MainActivity.cs* line 16).
 3. Debug the app on device or emulator.
 4. Tap the envelope icon button in the lower right of the app.
 5. After Visual Studio pauses on the breakpoint, run **Debug > Continue**;
 6. Attempt to repeat steps 4 and 5 five times. 

Test case: [RepeatedBreakpointAsyncTask.zip](https://github.com/xamarin/xamarin-android/files/3943429/RepeatedBreakpointAsyncTask.zip)

(This is just a new template Xamarin.Android app with a minimal example `AsyncTask`.)

### Current behavior

On one of the repetitions of step 6, Visual Studio opens a **Break Mode** tab that says:

```
No compatible code running

The selected debug engine does not support any code executing on the current thread (e.g. only native runtime code is executing).
```

When that happens, Visual Studio doesn't highlight the current execution line in the editor or show any information in the **Call Stack** window.

(In Visual Studio for Mac, there isn't a Break Mode tab, but the other behaviors are the same.)

The number of repetitions of step 6 to see the behavior varied for me across devices:

  * Android 7.1 Nougat (API level 25) armeabi-v7a, Motorola Moto E4

    So far always 4.

  * Android 7.1 Nougat (API level 25) x86, Google APIs emulator (`system-images;android-25;google_apis;x86`)

    So far always 3.

  * Android 7.1 Nougat (API level 25) x86_64, Google APIs emulator (`system-images;android-25;google_apis;x86_64`)

    So far always 3.

  * Android 9.0 Pie (API level 28) arm64-v8a, Google Pixel 3:
  
    So far always 5.

  * Android 10 (API level 29) x86_64, Google Play emulator (`system-images;android-29;google_apis_playstore;x86_64`):
  
    Usually 2. Sometimes 3.

    Perhaps also interesting, the `new System.Threading.Thread(() => { }).Start()` line in the test case was only needed for this Android 10 x86_64 emulator. On the other devices and emulators, I could remove that line and still reproduce the issue.

### Expected behavior

The first time the breakpoint is hit, the debugger behaves as expected. For example, Visual Studio highlights the current execution line in the editor, and **Debug > Step Over** allows stepping to the next line.

## On which platforms did you notice this

\[x\] Xamarin.Android

**Version Used**:

Visual Studio 2019 version 16.5 IntPreview
16.5.0-pre.2.0+29608.14.master

Mono Debugging for Visual Studio   16.5.506 (c3636c8)
Xamarin   16.5.000.363 (d16-5@a40bf8d)

Xamarin.Android SDK   10.2.0.16 (d16-5/48f0fe7), which uses mono/mono/2019-08@062f0ab8cae60d1d347e4d722884c065c9f34484

**Not a recent regression**:

I was able to reproduce the same behavior with Visual Studio 2019 version 16.1.6.

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Xamarin   16.1.0.545 (d16-1@db7c858e8)

Xamarin.Android SDK   9.3.0.23 (monodroid/d16-1@d0b48056f), which uses mono/mono/2018-08@3a07bd426d3dae0d9b6c7891e7bb11f487b18484

**Comment by brendanzagaeski** [comment]
Likely related reports (oldest to newest):

  * https://developercommunity.visualstudio.com/content/problem/716868/visual-studio-xamarin-debugger-doesnt-show-source.html
  * https://developercommunity.visualstudio.com/content/problem/731179/cannot-debug-code-invoked-by-javascriptinterface-m.html
  * https://developercommunity.visualstudio.com/content/problem/833888/unable-to-step-into-async-code.html
  * https://developercommunity.visualstudio.com/content/problem/833938/unable-to-debug-async-code-in-visual-studio-in-our.html

**Regression between Visual Studio 2017 version 15.9 and Visual Studio 2019 version 16.1:**

After seeing these Visual Studio Developer Community reports, I thought it would be interesting to check the behavior of this test case on Visual Studio 2017 too.

Indeed, I was *not* able to reproduce this problem in Visual Studio 2017 version 15.9. I performed at least 12 repetitions of steps 4 and 5 on each of the following devices, and the breakpoint worked as expected every time.

  * Android 7.1 Nougat (API level 25) armeabi-v7a, Motorola Moto E4
  * Android 7.1 Nougat (API level 25) x86, Google APIs emulator (`system-images;android-25;google_apis;x86`)
  * Android 7.1 Nougat (API level 25) x86_64, Google APIs emulator (`system-images;android-25;google_apis;x86_64`)
  * Android 9.0 Pie (API level 28) arm64-v8a, Google Pixel 3
  * Android 10 (API level 29) x86_64, Google Play emulator (`system-images;android-29;google_apis_playstore;x86_64`):

**Next steps:**

I will try a few experiments to see if I can narrow down which specific component has changed behavior.

**Comment by brendanzagaeski** [comment]
The change in behavior was introduced between:
mono/2018-06@b63e5378e389f675640fba97999b82f3ca7a44c2
and
mono/2018-08@9f72a46b41fc8985a1062275f90b57fb54f01347

**Steps tested:**

 1. Build and deploy using Visual Studio 2017 version 15.9.18.
 2. Push a different *libmonosgen-2.0.so* and *mscorlib.dll* to the test app's *files/.\_\_override\_\_* directory.
 3. Complete the other steps to reproduce.

**Results with libraries from mono/2018-06@b63e5378:**

The breakpoint always behaved as desired.

**Results with libraries from mono/2018-08@9f72a46b:**

The *No compatible code running* window appeared.

**Comment by barmouta** [comment]
I'm facing this exact issue since upgrading my xamarin forms app to VS2019, but only happens for the Android version of the app; iOS version hits break points just fine. 

Any ETA on the fix? Or do you suggest to manually revert to a previous versions of the mono and mscorlib?

**Comment by lambdageek** [comment]
Keeping open until the backports land

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.2.0.99.

Fix included on Windows in Visual Studio 2019 version 16.5 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version of Xamarin.Android has now been published on macOS that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 6. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 Preview 3 and higher. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version of Xamarin.Android has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on Windows in Visual Studio 2019 version 16.5. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 6 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version of Xamarin.Android has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)

**Comment by MitchBomcanhao** [comment]
I've been observing similar errors for a while now - not sure if it started with VS 16.5 or one of its updates. VS 16.6 also has the same problem.
Debugging android stops on breakpoints but says that no compatible code is running. this code comes from another package that we build, and this has never been an issue beforehand. The same breakpoint works fine when running a different platform like UWP.

This has made debugging on android pretty much impossible as most of the actual logic lives in the shared package across platforms. 

Any ideas on how to diagnose this?

**Comment by winstonpang** [comment]
@MitchBomcanhao exactly the same situation.

We have setup external packages and they can no longer debug or breakpoints resolved. I do believe this started in 16.5.0, it's annoying as it's impossible to debug Xamarin issues in our projects now.

**Comment by thaystg** [comment]
Does anyone has an open project that can tell me where to set the breakpoint then I can use it to reproduce?

**Comment by jeffjag681** [comment]
I have been trying to resolve the same issue.  Just updated to  VS 2019 V16.5 in the hopes it would fix the problem.  Building and debugging an Xamarin Android app is now very difficult.     I did all of the standard things including deleting the .obj and .bin files from the project, reloading it and restarting (as suggested on another thread) but still results are the same.   I am now running a "repair" on my VS instance to see if that makes any difference.

**Comment by thaystg** [comment]
Can anyone help me to reproduce it?

**Comment by jeffjag681** [comment]
Yes.  The project built and ran correctly in vs 2017
 In 2019 the breakpoints are not hit.  When I insert one programmaticly  it
breaks but I get the incomparable code message.  Breakpoints set in vs are
ignored

**Comment by thaystg** [comment]
This is happening in any simple project? Running in an emulator or in the device?

**Comment by jeffjag681** [comment]
Any sample project, emulated or physical device

All work fine in VS 2017
VS is running on windows 10.   I just updated the VS 2019 today to the
current rev hoping that would address the problem as stated in the forum.

Jeff Schwartz
Chief Technical Officer
Symptelligence Medical Informatics LLC

**Comment by jeffjag681** [comment]
Breakpoints are not working in emulator or when physical device attached.   All breakpoints set in VS are ignored, Symbols are loaded, breakpoints set with no errors.    I can force a break by inserting a  call to Debugger.Break();  to force a breakpoint but that only generates the "no compatible code running message.

Below is the configuration I have loaded on my development machine:

Microsoft Visual Studio Community 2019
Version 16.5.5
VisualStudio.16.Release/16.5.5+30104.148
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.96.24460
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.5.514 (c4f36a9)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.533 (d16-5@9152e1b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b


Xamarin.iOS and Xamarin.Mac SDK   13.16.0.13 (b75deaf)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by thaystg** [comment]
This issue was about getting "No Compatible code running" message when trying to debug async code. 
This is the other issue https://developercommunity.visualstudio.com/content/problem/998764/xamarin-ios-breakpoints-not-working-in-a-custom-nu.html that is about getting "No compatible code running" when trying to debug external code.
So I'll keep this issue closed.

**Comment by jeffjag681** [comment]
Thank you for your kind response.  However I am NOT debugging external code.  Breakpoints are not occurring in my project code.  I am setting breakpoints in my application, not in the external package.

**Comment by thaystg** [comment]
Hi, @jeffjag681 , could you create a project and share it on github that we can reproduce?
I tried a lot to reproduce it, I'm with the same version as you are and I cannot get the same message.

**Comment by jeffjag681** [comment]
Interesting....I can try that and will post it.   I also have VS2017 installed, should I uninstall this version?

**Comment by thaystg** [comment]
I don't think so, I have both installed here too.

**Comment by jeffjag681** [comment]
Thanks for all your help.  I just built the simplest project I could build.  Just a raw Xamarin Android app.   Here the breakpoints are hit.   so while this doesn't solve the issue.  It does clarify that it is not directly caused by Visual Studio 2019 V16.5.   Now the question is what configuration or other items could cause this to occur.  I would post it but the zip file is too large.

**Comment by jeffjag681** [comment]
I notice in my project that fails to break that when I look in Debug->Windows->Modules, I see that symbols are loaded for the project but it extension for the file is .mdb, not .pdb   My configuration is set to debug and exceptions are set to the default settings.    Could this be an indication of what the problem is?

**Comment by joj** [comment]
Maybe it's an indication. If you have control over the code creating that dll/symbols, switch the DebugType to Portable (it will be Full right now). Portable in general works way better than Full. It's a more modern (and better supported) format.

**Comment by jeffjag681** [comment]
Done.  Now it loads the PDB file as expected, but the behavior is the same.  Breakpoint is ignored.   I inserted a call to Debugger.break; just above my breakpoint to verify that the code is following the expected path and it hits that fine.  But still comes up with "no compatible code running"
I did port this code over from VS 2017 and then had issues building it. But that was resolved by installing Xamarin into my 2019 configuration.

**Comment by joj** [comment]
Can you copy your callstack on the break? At least the first few lines, until you see something you can recognize, and with "External Code" enabled (you can enable/disable it by right-clicking on the call stack). Also, go watch build! :)

**Comment by jeffjag681** [comment]
Here is the call stack:

 	0x22 in weShareAndroid.TrackTimeFragment.OnCreateView	C#
 	0x26 in Android.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_	C#
 	0x23 in Android.Runtime.DynamicMethodNameCounter.22	C#

**Comment by joj** [comment]
The part I'm most interested here is the file path of those frames, if you can see it in the stack. And then if that path makes sense to you, and if you have those files in those places.

**Comment by jeffjag681** [comment]
I notice when I try to copy with source paths I don't get any additional information.  However when I look at the break point itself it is pointing to the correct file and line and source and indicates that is it set (solid red dot)

**Comment by jeffjag681** [comment]
I have another clue as to what is happening (but not a solution) When I set
a breakpoint in my code (I have updated to 16.6) I notice that I get a
build error that the resource layout does not contain a definition for the
fragment or activity where the breakpoint is set.  The build error goes
away when I remove the breakpoint.


Jeff Schwartz
Chief Technical Officer
Symptelligence Medical Informatics LLC

**Comment by joj** [comment]
You mean like an xml build error? That shouldn't happen at all :)

**Comment by jeffjag681** [comment]
Agreed, but that is what I am seeing.  This did not happen in vs 2017.  I
can load and build the project there and it works fine with all breakpoints
functioning g

**Comment by bill2004158** [comment]
it seems I still get
```
No compatible code running

The selected debug engine does not support any code executing on the current thread (e.g. only native runtime code is executing).
```
when trying to debug xamarin.forms code.

it hit the break point in XF code, but shows that message. and cannot step into/over.
pdb file is loaded.
"Enable just my code" is unchecked.
```
Microsoft Visual Studio Enterprise 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

ASP.NET and Web Tools 2019   16.6.954.58314
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.954.58314
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.954.58314
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.954.58314
Azure Functions and Web Jobs Tools

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.2.3   Build 192.0.20191016.60459
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SonarLint for Visual Studio   4.22.0.18519
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1062 (d16-6@41e1f0e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3


Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by brendanzagaeski** [comment]
@bill2004158, if you get a chance, I'd recommend submitting a new [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html/) feedback item via [**Help > Send Feedback > Report a Problem**](https://docs.microsoft.com/visualstudio/ide/feedback-options?view=vs-2019) in Visual Studio for the behavior you are seeing. That will allow a dedicated discussion for your specific scenario. Feedback items submitted via Visual Studio also allow private attachments, which might be useful in this case for sharing details about your scenario.

Thanks in advance!

**Comment by muteddisk** [comment]
I had the same error after trying to rename my app from app4 to something else.
