### ISSUE TITLE
Issues with mono --aot=llvm-outfile

### ISSUE THREAD

**Issue by m7nu3l** [mono/mono#18126]
I guess I'm must be doing something wrong but I'm not able to figure it out. I also tried to copy examples in other issues but I had no luck.

## Steps to Reproduce

1. mono --aot=llvmonly,llvm-outfile=bla.ll,save-temps Console.exe

### Current Behavior

The command outputs:

> Mono Ahead of Time compiler - compiling assembly /home/manuel/dev/analysis-net/Console/bin/Debug/Console.exe
> AOTID 698FE5E7-DAE2-6725-8A07-A2E046BD69D1
> Executing opt: "/usr/lib/mono/llvm/bin/opt" -f  -o "mono_aot_3EEb8R/temp.opt.bc" "mono_aot_3EEb8R/temp.bc"
> Executing clang: clang++ -fexceptions -fpic -O2 -fno-optimize-sibling-calls -Wno-override-module -c -o "mono_aot_3EEb8R/temp-llvm.o" "mono_aot_3EEb8R/temp.opt.bc"
> Compiled: 88/88
> Executing the native assembler: "as" --64  -o /tmp/mono_aot_h34PnU.o /tmp/mono_aot_h34PnU
> Executing the native linker: clang++  -shared -o /home/manuel/dev/analysis-net/Console/bin/Debug/Console.exe.so.tmp "mono_aot_3EEb8R/temp-llvm.o" /tmp/mono_aot_h34PnU.o  -lstdc++
> Retained input file.
> JIT time: 48 ms, Generation time: 1341 ms, Assembly+Link time: 165 ms.

In the mono_aot_3EEb8R folder I can see .bc files. However, there is no file bla.ll created as indicated in llvm-outfile=bla.ll

### Expected Behavior
I expect to see the indicated file (bla.ll)

## On which platforms did you notice this

[ ] macOS
[ x] Linux
[ ] Windows

**Version Used**:

> Mono JIT compiler version 6.6.0.161 (tarball Tue Dec 10 10:36:32 UTC 2019)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           __thread
> 	SIGSEGV:       altstack
> 	Notifications: epoll
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug 
> 	Interpreter:   yes
> 	LLVM:          yes(610)
> 	Suspend:       hybrid
> 	GC:            sgen (concurrent by default)

**Comment by lewurm** [comment]
I think `llvm-outfile=` only works in combination with `asmonly`, so it would be
```console
$ mono --aot=llvmonly,llvm-outfile=bla.ll,save-temps,asmonly Console.exe
```

**Comment by m7nu3l** [comment]
Thank you so much, it worked.

> mono --aot=llvmonly,llvm-outfile=bla.bc,save-temps,asmonly Console.exe

It generated:

> Mono Ahead of Time compiler - compiling assembly /home/manuel/dev/analysis-net/Console/bin/Debug/Console.exe
> AOTID 5CFFFE51-452F-7E7C-6504-9ECC4C5FED56
> Executing opt: "/usr/lib/mono/llvm/bin/opt" -f  -o "bla.bc" "/home/manuel/dev/analysis-net/Console/bin/Debug/Console.exe.bc"
> Compiled: 88/88
> Output file: '/tmp/mono_aot_zEMkqT'.
> LLVM output file: 'bla.bc'.
> JIT time: 49 ms, Generation time: 129 ms, Assembly+Link time: 0 ms.

If by any chance someone needs to have the readable form of the llvm code, he should run llvm-dis on bla.bc
