### ISSUE TITLE
bug: mini_get_shared_gparam get wrong MonoImage?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#18127]
We use **Newtonsoft.Json.dll** on iOS. The Newtonsoft.Json.dll define the **StructMultiKey** struct:
```c#
// Newtonsoft.Json.Utilities.StructMultiKey<T1,T2>
using Newtonsoft.Json.Utilities;
using System;

internal readonly struct StructMultiKey<T1, T2> : IEquatable<StructMultiKey<T1, T2>>
{
	public readonly T1 Value1;

	public readonly T2 Value2;

	public StructMultiKey(T1 v1, T2 v2)
	{
		Value1 = v1;
		Value2 = v2;
	}

	public override int GetHashCode()
	{
		T1 value = Value1;
		ref T1 reference = ref value;
		T1 val = default(T1);
		int num;
		if (val == null)
		{
			val = reference;
			reference = ref val;
			if (val == null)
			{
				num = 0;
				goto IL_0038;
			}
		}
		num = reference.GetHashCode();
		goto IL_0038;
		IL_0038:
		T2 value2 = Value2;
		ref T2 reference2 = ref value2;
		T2 val2 = default(T2);
		int num2;
		if (val2 == null)
		{
			val2 = reference2;
			reference2 = ref val2;
			if (val2 == null)
			{
				num2 = 0;
				goto IL_0070;
			}
		}
		num2 = reference2.GetHashCode();
		goto IL_0070;
		IL_0070:
		return num ^ num2;
	}

	public override bool Equals(object obj)
	{
		object obj2;
		if ((obj2 = obj) is StructMultiKey<T1, T2>)
		{
			StructMultiKey<T1, T2> key = (StructMultiKey<T1, T2>)obj2;
			return Equals(key);
		}
		return false;
	}

	public bool Equals(StructMultiKey<T1, T2> other)
	{
		if (object.Equals(Value1, other.Value1))
		{
			return object.Equals(Value2, other.Value2);
		}
		return false;
	}
}

```

It  will create **.ctor** method for class **System.Collections.Generic.GenericEqualityComparer`1** with the constraint class **StructMultiKey**.
![image](https://user-images.githubusercontent.com/5187024/70597549-99eb7700-1c23-11ea-9fb7-9868c7e846ab.png)

above the screenshot, the **mono_get_image_for_generic_param** return **mscorlib** MonoImage without consider with constraint of class **StructMultiKey** which is int the **Newtonsoft.Json** MonoImage.

I think it should be **Newtonsoft.Json** image because store it with mscorlib image will crash if will unload **Newtonsoft.Json** image.

**Comment by lambdageek** [comment]
@vargaz I think `mini_get_shared_gparam` needs to put the shared parameter into a `MonoImageSet` that includes the generic container's image and also the constraint type's image.  We don't scrub `MonoImage:gshared_types` of one image when we unref another one, so there could be junk in there.  What do you think?

**Comment by vargaz** [comment]
Its possible, we mostly use this code on platforms without domains, so its not tested with unloading.

**Comment by joncham** [comment]
Very likely same issue as Unity one here: https://issuetracker.unity3d.com/issues/editor-crash-when-entering-and-exiting-playmode-for-a-few-times-with-microsoft-maps-sdk
