### ISSUE TITLE
ldflda crashing wilth unsupported IL code if "this" is a value on the stack

### ISSUE THREAD

**Issue by xoofx** [mono/mono#18136]
## Steps to Reproduce

1.  https://gist.github.com/xoofx/c4a9777eaafb47ca70ff30c64f314137

As per the spec, `ldflda` can be used on a value instance on the stack, but it seems that `ldflda` in Mono is expecting only a pointer type for "this".

### Current Behavior

```
CheckLdFldLdFlda

Unhandled Exception:
System.InvalidProgramException: Invalid IL code in PlayIL.Program:CheckLdFldLdFlda (PlayIL.Program/RootStruct): IL_0006: ldflda    0x0a000004


  at PlayIL.Program.Main (System.String[] args) [0x0004b] in <5cd1d0b45a8f4b03b56221d0e2065d86>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in PlayIL.Program:CheckLdFldLdFlda (PlayIL.Program/RootStruct): IL_0006: ldflda    0x0a000004


  at PlayIL.Program.Main (System.String[] args) [0x0004b] in <5cd1d0b45a8f4b03b56221d0e2065d86>:
```

### Expected Behavior

```
CheckLdFldLdFlda
10
CheckLdFldLdFldaWithCall
11
CheckLdFldLdFldaWithLdElem
12
```
## On which platforms did you notice this

[NOT TESTED] macOS 
[x] Linux
[x] Windows

**Version Used**:

Mono 5.21 and 6.4.0+

**Comment by fanyang-mono** [comment]
This is reproducible on macOS as well.

**Comment by fanyang-mono** [comment]
According to ECMA-335, a value type is not an object, type O, a
managed pointer, type &, or an unmanaged pointer, type native int. Mono's current behavior is in line with the spec.

> The ldflda instruction pushes the address of a field of obj. obj is either an object, type O, a
managed pointer, type &, or an unmanaged pointer, type native int. The use of an unmanaged
pointer is not allowed in verifiable code. The value returned by ldflda is a managed pointer
(type &) unless obj is an unmanaged pointer, in which case it is an unmanaged pointer (type
native int).

cc @davidwrighton

**Comment by fanyang-mono** [comment]
No action is needed for this issue. Closing it now.

**Comment by xoofx** [comment]
> According to ECMA-335, a value type is not an object, type O, a
managed pointer, type &, or an unmanaged pointer, type native int. Mono's current behavior is in line with the spec.

The problem is that Roslyn is generating such a code, and CoreCLR is supporting it.
I will try to raise the issue to Roslyn to understand why it is departing from ECMA-335 (Note that it's not the first time their are small gaps like this with ECMA-335)

**Comment by davidwrighton** [comment]
Please provide an example of C# for which Roslyn generates this problematic code. We could in theory expand the ECMA 335 spec to allow this, but as written a ldfld followed by ldflda doesn't really make sense.
