### ISSUE TITLE
Incorrect name for MIT license in LICENSE file

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [mono/mono#18133]
## Steps to Reproduce

1. View the LICENSE file in the root of this repository.
2. Observe there is a license labelled "MIT X11 License".
3. Compare the license body from step 2 to the MIT license (also called the Expat license), https://spdx.org/licenses/MIT.html
4. Compare the license body from step 2 to the X11 license (also called the MIT X11 license), https://spdx.org/licenses/X11.html

### Current Behavior

The license name ("MIT X11 License") does not reflect the license body (which appears to be the regular MIT license, a.k.a. Expat).
This makes it unclear how I'm supposed to cite Mono in my product's third party licenses file.

Differences in these license variants explained:

* https://opensource.stackexchange.com/a/8586
* https://en.wikipedia.org/wiki/MIT_License#Variants

### Expected Behavior

The license name should reflect the license body (either by the license name or body being updated).

## On which platforms did you notice this

N/A

**Version Used**: 0e05bda2356e453e6ab5ae8745c86bddf82b9ce6

## Stacktrace

N/A

**Comment by marek-safar** [comment]
@migueldeicaza do you happen to know the reasons?

**Comment by migueldeicaza** [comment]
Yes - I keep making that mistake.  I keep calling the MIT license the “MIT X11” license incorrectly.

We should remove the name X11 - as it is wrong and not the license that was approved historically.

You can see me making that mistake recently on some repo and having to edit my comment to remove the name :-)
