### ISSUE TITLE
[wasm] change mono_wasm_invoke_method to not swallow the exceptions

### ISSUE THREAD

**Issue by lewing** [mono/mono#18134]
mono_wasm_invoke_method doesn't surface the exceptions properly which can make problems difficult to diagnose

**Comment by lewing** [comment]
Fixed in #18135

Blazor wraps it here https://github.com/aspnet/AspNetCore/blob/master/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L49 and while I think it should still work it looks like that wrapper could use more general fixes

/cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
> it looks like that wrapper could use more general fixes

If you could let me know what general fixes you have in mind (perhaps even by means of a PR :smile:) I'd be very interested!
