### ISSUE TITLE
[Question] Executing aoted program

### ISSUE THREAD

**Issue by m7nu3l** [mono/mono#18144]
I'm a little confused about the --aot=full capabilities. When it is executed on a console application, I would expect to have a standalone binary runnable on the target architecture.

I also checked the intermediate llvm code. I can't compile to an executable because there is no main function. Even if it is a .NET console application.

Thanks in advance for your time!

## Steps to Reproduce

1.  Create your sample.exe
2.  Execute mono --aot=full sample.exe (as described [here](https://www.mono-project.com/docs/advanced/aot/))
3. It generates a sample.exe.so it not executable.

### Current Behavior

I can't directly execute it.

### Expected Behavior

I would like to have a binary such that I can do ./result to run it.
 
## On which platforms did you notice this

[ ] macOS
[ x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.6.0.161 (tarball Tue Dec 10 10:36:32 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by lambdageek** [comment]
Mono's FullAOT mode does not generate a standalone executable.  Rather, it generates native code for each managed method.  The way to run the application is with `mono --full-aot program.exe`. A few caveats:
1. All of the base class libraries (ie the libraries installed in <prefix>/lib/mono/4.5/) that your application depends on must also be compiled with `mono --aot=full` and the .so files have to be next to the BCL assemblies. 
2. You still have to have the .dll and .exe files - Mono doesn't include the assembly metadata in the AOT .so files.
3. There are [limitations](https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations) to what APIs your program may use when you use FullAOT mode

If you are interested in producing a single binary that bundles the BCL and your application into a single .exe you may want to look at `mkbundle`

**Comment by m7nu3l** [comment]
@lambdageek  Thanks for your detailed answer. 

If the original assemblies must be only kept for the metadata, can we for instance remove the class's methods in there? It would help reducing its size.

**Comment by lambdageek** [comment]
@m7nu3l You need to keep the method definitions, but you can drop the method bodies (with something like `mono-cil-strip`).  You can also remove methods and classes that definitely won't get used by your program using the [Mono IL Linker](https://github.com/mono/linker/blob/master/README.md)

**Comment by m7nu3l** [comment]
Thanks again!
