### ISSUE TITLE
MONO_IOMAP does not work anymore

### ISSUE THREAD

**Issue by AlexRixhardson** [mono/mono#18173]
Since MONO_IOMAP was removed (see https://github.com/mono/mono/issues/15845), what is the equivalent replacement for it? What should we use now, if we want to access files in a case insensitive manner, e.g. to map URLs that are manually typed into a browser (with random cases) to their corresponding view files?

**Comment by akoeplinger** [comment]
It needs to be handled at the application or web framework level, e.g. by using the case-insensitive string comparison APIs.
