### ISSUE TITLE
[Question] How a .o file is generated when --aot=llvm is used?

### ISSUE THREAD

**Issue by m7nu3l** [mono/mono#18189]
I'm playing with mono full AOT feature. When I run:

> mono --aot=llvm,llvmonly,save-temps Main.exe

It outputs:

> Mono Ahead of Time compiler - compiling assembly /home/manuel/dev/Main.exe
> AOTID 348A1F30-1037-23F4-ADD2-38A85D27EB22
> Executing opt: "/usr/lib/mono/llvm/bin/opt" -f  -o "mono_aot_dAnQ3z/temp.opt.bc" "mono_aot_dAnQ3z/temp.bc"
> Executing clang: clang++ -fexceptions -fpic -O2 -fno-optimize-sibling-calls -Wno-override-module -c -o "mono_aot_dAnQ3z/temp-llvm.o" "mono_aot_dAnQ3z/temp.opt.bc"
> Compiled: 8/8
> Executing the native assembler: "as" --64  -o /tmp/mono_aot_thUOCC.o /tmp/mono_aot_thUOCC
> Executing the native linker: clang++  -shared -o /home/manuel/dev/Main.exe.so.tmp "mono_aot_dAnQ3z/temp-llvm.o" /tmp/mono_aot_thUOCC.o  -lstdc++
> Retained input file.

My question is how **/tmp/mono_aot_thUOCC** is generated. Where does it come from?

I'm sorry I didn't follow the issue template. This is just a question not a bug report.

Thanks!

**Comment by vargaz** [comment]
Its generated by the aot compiler in aot-compiler.c, it contains the code for methods that llvm can't handle etc.

**Comment by m7nu3l** [comment]
Thanks for your answer @vargaz
