### ISSUE TITLE
Type.FullName : on Mono = System.ReadOnlyMemory`1[T]& : on .Net core = null

### ISSUE THREAD

**Issue by KosmicTask** [mono/mono#18180]
Take Program.cs

```csharp
using System;
using System.Buffers;

namespace typetest
{
    class Program
    {
        static void Main(string[] args)
        {
            var t = typeof(ReadOnlySequence<>);
            var m = t.GetMethod("TryGet");
            var p = m.GetParameters()[1];
            Console.WriteLine($"Type.Name: {p.ParameterType.Name}");
            Console.WriteLine($"Type.FullName: {p.ParameterType.FullName}");
        }
    }
}
```

With Mono 6.4 

```console
$ mcs Program.cs
$ mono Program.exe
Type.Name: ReadOnlyMemory`1&
Type.FullName: System.ReadOnlyMemory`1[T]&
```

With dotnet core 3.1

```console
$ dotnet run
Type.Name: ReadOnlyMemory`1&
Type.FullName: 
```

This showed up when generating binding code for one of our Obj-C tools. Not sure it is of any real import, it just happened to break our parser.

**Comment by CoffeeFlux** [comment]
Thanks for the report! Mono's behavior appears to be the same when built in netcore mode.

I think Mono's name is a lot more helpful here, though. Going to open an issue with the .NET Core folks to see if this is a bug on their end.

**Comment by CoffeeFlux** [comment]
This is indeed a Mono bug per the documentation (https://github.com/dotnet/runtime/issues/1276#issuecomment-570725219), but it's not really tested anywhere. I'll fix it on our end and add to the corefx tests next week.

**Comment by CoffeeFlux** [comment]
Seems we tried fix this a while back the fix was too specific: https://github.com/mono/mono/pull/5920

CoreCLR's logic here is actually fairly simple, so maybe we can just take that and add tests: https://github.com/dotnet/runtime/blob/f23e2796ab5f6fea71c9fdacac024822280253db/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L1473
