### ISSUE TITLE
* Assertion at mono/mono/mini/interp/transform.c:2889, condition `cbb' not met

### ISSUE THREAD

**Issue by srxqds** [mono/mono#18204]
## Steps to Reproduce

1.  we use **System.IO.Compression.dll** and **System.IO.Compression.FileSystem.dll** on iOS embeded with mono. 
2. call ZipFile.ExtractToDirectory(localZipPath, topDirPath);

### Current Behavior
assert failed

mono/mono/mono/mini/interp/transform.c:2889, condition `cbb' not met

### Expected Behavior

work crrectly.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] iOS

**Version Used**:
mono-6.0.0.334

## Stacktrace
The imethod is **ParseFileName** and the zipfilenam is **/private/var/containers/Bundle/Application/2FA8F342-361F-40F7-B8E6-13F3087F5B68/game.app/cookeddata/small_file.zip**
and the output folder is **/var/mobile/Containers/Data/Application/2CDF1BE3-7F52-4651-905C-58EE7BEF9BE0/Documents/game/Documents/small_files**
![image](https://user-images.githubusercontent.com/5187024/70884303-a2bbbe80-2010-11ea-866d-afb892178714.png)

**Comment by lewurm** [comment]
We hit the same assert for an internal customer. Alas the resolution was "update to a newer mono" (6.4) as that was something anyway on their agenda. If upgrading isn't an option for you, you can try to disable the managed debugger, i.e. do not call `mono_debug_init ()` on startup.
