### ISSUE TITLE
Some unit tests (e.g. mscorlib) are too big to run in every configuration and needs to be split

### ISSUE THREAD

**Issue by spouliot** [mono/mono#18213]
## Steps to Reproduce

This happens in different situations.

1. Building `mscorlib` creates binaries that are too large for Apple's native linker, giving *tons of* build errors like:

```
00:40:50.1289540 /Users/xamarinqa/agent/_work/2/s/tests/xharness/tmp-test-dir/mscorlib358/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_corlib_xunit-test.dll.s(1448169,8): error GDC116A36: can not encode offset '0x100001C' in resulting scattered relocation. [/Users/xamarinqa/agent/_work/2/s/tests/xharness/tmp-test-dir/mscorlib358/mscorlib.csproj] 
```

logs from 2019-12: http://xamarin-storage/jenkins/xamarin-macios/pull-request/5fb8f4e3e574389acaff76cecf5766013cb8ef07/3321015/device-tests/jenkins-results/tests/index.html
tracking issue: https://github.com/xamarin/maccore/issues/2080

This also affects other tests but we can split them on our (macios) side.

2. Building `mscorlib` unit tests w/release for tvOS -> warnings (so far)

This is due _largely_ to bitcode being part of the output.

logs from 2019-12: http://xamarin-storage/jenkins/xamarin-macios/pull-request/5fb8f4e3e574389acaff76cecf5766013cb8ef07/3321016/device-tests/jenkins-results/tests/index.html
tracking issue: https://github.com/xamarin/maccore/issues/1896

### Current Behavior

Warnings and build failures.

### Expected Behavior

Build, without error, and execution of the tests.

## On which platforms did you notice this

[x] iOS
[x] tvOS
[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

2019-12 - but this existed before (it just becoming more common).

We used (before using pre-built tests binaries) to have mscorlib unit tests split into 2 assemblies (for watchOS). That worked well for us.

**Comment by spouliot** [comment]
c.c. @SamMonoRT for 2019-12 integration

**Comment by mandel-macaque** [comment]
Same issue happens with the dll monotouch_System.Core_xunit-test.dll which is too large and will give the same errors on 32b:

> 8:32:59.3083210 /Users/mandel/Xamarin/master/xamarin-macios/tests/xharness/tmp-test-dir/BCL tests group 5250/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_System.Core_xunit-test.dll.s(1464840,8): error GDC116A36: can not encode offset '0x1000040' in resulting scattered relocation. [/Users/mandel/Xamarin/master/xamarin-macios/tests/xharness/tmp-test-dir/BCL tests group 5250/BCL tests group 5.csproj]

**Comment by steveisok** [comment]
@akoeplinger Is it fairly trivial to split up the test assemblies?
