### ISSUE TITLE
[wasm][debugger] debugger should allow enable/disabling of breakpoints

### ISSUE THREAD

**Issue by lewing** [mono/mono#18229]
the DevTools protocol includes setPauseOnExceptions and setBreakpointsActive that controls the behavior when a breakpoint is hit.  We should track those and respond appropriately

- [ ] {"method":"Debugger.setPauseOnExceptions","params":{"state":"uncaught"}}
- [ ] {"method":"Debugger.setPauseOnExceptions","params":{"state":"all"}}
- [ ] {"method":"Debugger.setPauseOnExceptions","params":{"state":"none"}}
- [ ] {"method":"Debugger.setBreakpointsActive","params":{"active":true}}
- [ ] {"method":"Debugger.setBreakpointsActive","params":{"active":false}}

**Comment by baulig** [comment]
I am a bit confused what "respond appropriately" means in this context, could you please explain?
