### ISSUE TITLE
Deinstall mono

### ISSUE THREAD

**Issue by tinizzz** [mono/mono#18235]
Hi,

i am trying to deinstall mono from my mac - but i have no clue how.
can anyone help me please?

thanks a lot,
tini

**Comment by MaximLipnin** [comment]
Please try this link: https://www.mono-project.com/docs/about-mono/supported-platforms/macos/#uninstalling-mono-on-macos

**Comment by tinizzz** [comment]
THANKS A LOT!

**Comment by anodynos** [comment]
What about Linux? Link?
