### ISSUE TITLE
[wasm][debugger] test debugger features

### ISSUE THREAD

**Issue by lewing** [mono/mono#18237]
This is a tracking issue for wasm debugger testing

- [x] create test harness
- [x] create initial tests
- [x] fix harness reliabity
- [x] enable test harness in CI
- [ ] add tests for all p0 features
   - [x] Add breakpoints in .cs/.razor files
   - [x] Remove individual/all breakpoints
   - [x] Break when hitting breakpoint
   - [ ] Stop debugging / detach debugger
   - [x] Step into
   - [x] Step over
   - [ ] [Step out](https://github.com/mono/mono/issues/18736)
   - [x] Continue execution
   - [x] Call stack: show call stack frames with correct method names, filenames, and line numbers
   - [x] Call stack: inspect other frames
   - [ ] Support displaying: (u)int*/decimal/double/float/(u)long/(u)short, bool, string, DateTime, DateTimeOffset, Guid, (s)byte, char and nullables thereof
  - [x] Support displaying: delegates as type+methodname
  - [x] Support displaying: arbitrary class/struct instances as type name
  - [x] Read source code from local files on disk
  - [x] Support PDBs as external files
- [ ] add tests for all supported p1 features
   - [ ] Enable/disable individual/all breakpoints
   - [ ]  Step over 'await'
   - [ ]  Immediate window: evaluate basic variables (e.g., 'myvar', not 'myvar.subfield')
   - [ ]  Immediate window: evaluate basic fields (same as basic variables, but for this.* fields)
   - [ ]  Immediate window: evaluate basic properties { get; set; } on 'this'
   - [ ]  Immediate window: changing context to respect chosen call stack frame
   - [ ]  Hover mouse to evalulate variable/field/property
  - [ ]  Watch window: show evaluation of basic variables (e.g., 'myvar', not 'myvar.subfield')
  - [ ]  Watch window: show evaluation of basic fields (same as basic variables, but for this.* fields)
  - [ ]  Watch window: show evaluation of basic properties { get; set; } on 'this'
  - [ ]  Watch window: changing context to respect chosen call stack frame
  - [ ]  Locals/autos window: displaying properties as properties, not compiler-generated backing fields
  - [x]  Support PDBs embedded into .dlls (mono/mono#18236 - @thaystg)

**Comment by radical** [comment]
Most of these are already fixed, or being tracked in other current issues.
