### ISSUE TITLE
TLS errors from download.mono-project.com in UAE

### ISSUE THREAD

**Issue by piwi3910** [mono/mono#18244]
Since a couple of days the ubuntu 18.04 repo is having issues

## Steps to Reproduce

apt update says there is no longer a release file

apt upgrade works but really slow with these messages:

  Could not handshake: The TLS connection was non-properly terminated. [IP: 152.199.19.161 443]
Err:106 https://download.mono-project.com/repo/ubuntu stable-bionic/main amd64 libmono-relaxng4.0-cil all 6.6.0.161-0xamarin7+ubuntu1804b1
  Could not handshake: The TLS connection was non-properly terminated. [IP: 152.199.19.161 443]
Err:107 https://download.mono-project.com/repo/ubuntu stable-bionic/main amd64 libmono-simd4.0-cil all 6.6.0.161-0xamarin7+ubuntu1804b1
  Could not handshake: The TLS connection was non-properly terminated. [IP: 152.199.19.161 443]
Err:108 https://download.mono-project.com/repo/ubuntu stable-bionic/main amd64 libmono-system-servicemodel-internals0.0-cil all 6.6.0.161-0xamarin7+ubuntu1804b1
  Could not handshake: The TLS connection was non-properly terminated. [IP: 152.199.19.161 443]
Err:109 https://download.mono-project.com/repo/ubuntu stable-bionic/main amd64 libmono-smdiagnostics0.0-cil all 6.6.0.161-0xamarin7+ubuntu1804b1
  Could not handshake: The TLS connection was non-properly terminated. [IP: 152.199.19.161 443]
Err:110 https://download.mono-project.com/repo/ubuntu stable-bionic/main amd64 libmono-system-componentmodel-composition4.0-cil all 6.6.0.161-0xamarin7+ubuntu1804b1
  Could not handshake: The TLS connection was non-properly terminated. [IP: 152.199.19.161 443]

**Comment by directhex** [comment]
Are you seeing this on any other systems on the same network as you? That's coming from our CDN, so all I can really do is file a ticket

**Comment by piwi3910** [comment]
Tried it from multiple systems all coming from UAE even from different networks

Sent from Workspace ONE Boxer

On Dec 19, 2019 23:25, Jo Shields <notifications@github.com> wrote:

[EXTERNAL EMAIL]

Are you seeing this on any other systems on the same network as you? That's coming from our CDN, so all I can really do is file a ticket

-

**Comment by directhex** [comment]
I've opened a ticket in Azure for you.

**Comment by piwi3910** [comment]
I can confirm from today, the issue is resolved
