### ISSUE TITLE
[arm32][thumb] Assertion at mono/mini/tramp-arm.c:1148, condition `((guint16*)target) [0] == 0xf8df' not met

### ISSUE THREAD

**Issue by spouliot** [mono/mono#18254]
https://github.com/xamarin/maccore/issues/2082

## Steps to Reproduce

1. Run mscorlib unit tests, with Release configuration, Use Thumb

### Current Behavior

crash with
```
06:59:45.1143840 Dec 19 06:59:45 XQAiPad4a com.xamarin.bcltests.mscorlib[12075] <Notice>: error: * Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-10/ios/release/mono/mini/tramp-arm.c:1148, condition `((guint16*)target) [0] == 0xf8df' not met
```
http://xamarin-storage/jenkins/xamarin-macios/master/01f6710a1518a53ad04df9f6bdadb55984e0f9e7/3333481/device-tests/jenkins-results/tests/mscorlib/1623/device-XQAiPad4a-20191219_065932.log

### Expected Behavior

No crash

## On which platforms did you notice this

[x] iOS
[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

2019-10 and 2019-12
likely 2019-08 and earlier but I don't have bots logs for them

## Stacktrace

Symbolicated crash report
http://xamarin-storage/jenkins/xamarin-macios/master/01f6710a1518a53ad04df9f6bdadb55984e0f9e7/3333481/device-tests/jenkins-results/tests/mscorlib/1623/com.xamarin.bcltests.mscorlib-2019-12-19-065945.symbolicated.log

**Comment by spouliot** [comment]
c.c. @SamMonoRT for 2019-12 integration

**Comment by spouliot** [comment]
dupe

**Comment by lewurm** [comment]
for reference: duplicate of https://github.com/mono/mono/issues/18247
