### ISSUE TITLE
some questions about profiler 

### ISSUE THREAD

**Issue by srxqds** [mono/mono#18263]
1. ProfolerLog not build on windows: https://github.com/mono/mono/issues/14258

2. I want to write profiler by myself, but I found many define or api using in **profiler/log.c** not export, I can't use.

3. Is there any tools can output data for flame graph?

**Comment by alexrp** [comment]
Which APIs do you want to use?

**Comment by srxqds** [comment]
> Which APIs do you want to use?

for example **MonoCallSpec callspec** in the log.h file:
https://github.com/mono/mono/blob/1587c49f5f593f9ca53ef5d46084c7b5c6b7d13a/mono/profiler/log.h#L525

And I found the **method_enter** and **method_leave** event only trigger in interp.c file, but how can it do in jit mode?

![image](https://user-images.githubusercontent.com/5187024/71341900-2e47c900-2596-11ea-9559-eef48f9bb32b.png)

**Comment by srxqds** [comment]
If found it can use **--trace** open method trace in jit mode but, the next code will never call.
https://github.com/mono/mono/blob/d274cfbacdb2aeab0184662997882f3d78991e48/mono/mini/mini-profiler.c#L161

I cause the **method_enter** and **method_leave** will not trigge. 
Is it a bug of mono?
@marek-safar  @alexrp

**Comment by alexrp** [comment]
> for example **MonoCallSpec callspec** in the log.h file:

Someone would have to make the decision on whether to export that API. But it's not something that's inherently tied to runtime internals, so you could implement similar functionality yourself, or even just copy the code with some adjustments to use public-facing APIs in the `callspec.c` file.

> I cause the **method_enter** and **method_leave** will not trigge.

Did you install an instrumentation filter at startup with `mono_profiler_set_call_instrumentation_filter_callback` and return the correct flags?

**Comment by srxqds** [comment]
ok， thankyou @alexrp

**Comment by srxqds** [comment]
@alexrp hi,
I found that I can't call **mono_profiler_enable_call_context_introspection** function because if if I call it after **mini_init** function the **mono_profiler_state.startup_done** is true, otherwise **mono_profiler_state.context_enable** will not inited.

```c
mono_bool
mono_profiler_enable_call_context_introspection (void)
{
	if (mono_profiler_state.startup_done)
		return FALSE;

	mono_profiler_state.context_enable ();

	return mono_profiler_state.call_contexts = TRUE;
}
```

how can I work around it?

**Comment by alexrp** [comment]
What do you mean? Your profiler startup function should be called before `startup_done` is set:

https://github.com/mono/mono/blob/a3f4def8b6951fed5c248bd1875e90a7ab748d15/mono/mini/mini-runtime.c#L4306-L4310

**Comment by srxqds** [comment]
> What do you mean? Your profiler startup function should be called before `startup_done` is set:
> 
> https://github.com/mono/mono/blob/a3f4def8b6951fed5c248bd1875e90a7ab748d15/mono/mini/mini-runtime.c#L4306-L4310

but the **mono_profiler_state.context_enable ** not set, it will crash

**Comment by srxqds** [comment]
@alexrp 
https://github.com/mono/mono/blob/ffdffa54f2494cfdf390fabfc76e353fbe59405a/mono/metadata/profiler.c#L640-L649

it should the **context_enable** callback whether is inited.

**Comment by alexrp** [comment]
Are you using the API in a loaded profiler module (`libmono-profiler-<name>.so`) or as an embedder?

**Comment by srxqds** [comment]
> Are you using the API in a loaded profiler module (`libmono-profiler-<name>.so`) or as an embedder?

as an embedder.

**Comment by srxqds** [comment]
And anthoer question is: we call **mono_profiler_call_context_get_argument** get the void* data, how can I transfer it to a MonoObject which is a object on cs side?

**Comment by alexrp** [comment]
> as an embedder.

That would be a problem then. Either the callback assignments would need to be moved somewhere earlier, or a new profiler callback would need to be added to the API which is invoked right after the callback assignments. The latter is probably easier/better.

> And anthoer question is: we call **mono_profiler_call_context_get_argument** get the void* data, how can I transfer it to a MonoObject which is a object on cs side?

The buffer will contain the raw representation of the parameter/local/return value. So in this case, you would do:

```c
void *buf = mono_profiler_call_context_get_argument (ctx, 0);
MonoObject *obj = *(MonoObject **) buf;
mono_profiler_call_context_free_buffer (buf);
// do stuff with `obj`...
```

**Comment by srxqds** [comment]
> > as an embedder.
> 
> That would be a problem then. Either the callback assignments would need to be moved somewhere earlier, or a new profiler callback would need to be added to the API which is invoked right after the callback assignments. The latter is probably easier/better.
> 
> > And anthoer question is: we call **mono_profiler_call_context_get_argument** get the void* data, how can I transfer it to a MonoObject which is a object on cs side?
> 
> The buffer will contain the raw representation of the parameter/local/return value. So in this case, you would do:
> 
> ```c
> void *buf = mono_profiler_call_context_get_argument (ctx, 0);
> MonoObject *obj = *(MonoObject **) buf;
> mono_profiler_call_context_free_buffer (buf);
> // do stuff with `obj`...
> ```

Thank you @alexrp 

And how to get the **struct** type ToString and print it?
for example
```c#
struct FVector
{
int X;
int Y;
int Z;
public ovrride string ToString()
{
return string.Format("X:{0}, Y:{1}, Z:{2}", this.X, this.Y, this.Z);
}
}
```c
void *fector_buf = mono_profiler_call_context_get_argument (ctx, 0);
// how call ToString method get string ?
```

**Comment by alexrp** [comment]
Structs don't carry a vtable so you will have to find out some other way, e.g. by hardcoding type names and looking them up through the general embedding API, or maybe by inspecting the `MonoMethod` when your instrumentation filter callback is invoked, etc.

**Comment by srxqds** [comment]
> Structs don't carry a vtable so you will have to find out some other way, e.g. by hardcoding type names and looking them up through the general embedding API, or maybe by inspecting the `MonoMethod` when your instrumentation filter callback is invoked, etc.

hi, @alexrp 
I have an idea that if it can box struct data to object, I think it make it. but how to make api like **mono_object_box**
