### ISSUE TITLE
IOException when writing to Console.Out after the other end of the standard output pipe has been closed

### ISSUE THREAD

**Issue by madelson** [mono/mono#18279]
## Steps to Reproduce

1. Create a simple .NET exe which writes to standard out, like this:
```csharp
using System;

namespace Test
{
    internal static class Program
    {
        public static void Main(string[] args)
        {
                    string pipeLine;
                    while ((pipeLine = Console.In.ReadLine()) != null)
                    {
                        Console.Out.WriteLine(pipeLine);
                        Console.Out.Flush();
                    }
         }
    }
}
```

2. From another program, run the above exe as a process and close it's standard output, for example:
```csharp
var process = new Process { /* redirect all streams */ };
process.Start();
var errorTask = process.StandardError.ReadToEndAsync();
process.StandardOutput.Dispose(); // close stdout
process.StandardInput.WriteLine("hello");
process.StandardInput.Dispose();
process.WaitForExit();
Console.WriteLine(process.ExitCode); // 1
Console.WriteLine(errorTask); // IOException
```
Here's the exception I see written to stderr:
```
System.IO.IOException: Write fault on path /home/travis/build/.../[Unknown]
  at System.IO.FileStream.WriteInternal (System.Byte[] src, System.Int32 offset, System.Int32 count) [0x00077] in <d2ec5c92492f4d6ba8c422bdf574b786>:0 
  at System.IO.FileStream.Write (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00090] in <d2ec5c92492f4d6ba8c422bdf574b786>:0 
  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00080] in <d2ec5c92492f4d6ba8c422bdf574b786>:0 
  at System.IO.StreamWriter.WriteSpan (System.ReadOnlySpan`1[T] buffer, System.Boolean appendNewLine) [0x0016b] in <d2ec5c92492f4d6ba8c422bdf574b786>:0 
  at System.IO.StreamWriter.WriteLine (System.String value) [0x0000d] in <d2ec5c92492f4d6ba8c422bdf574b786>:0 
  at System.IO.TextWriter+SyncTextWriter.WriteLine (System.String value) [0x00000] in <d2ec5c92492f4d6ba8c422bdf574b786>:0 
  at (wrapper synchronized) System.IO.TextWriter+SyncTextWriter.WriteLine(string)
  at Test.Program.Main (System.String[] args) [0x00362] in <b0622494334f429285beb7ed5d4b60c8>:0
```

### Current Behavior

Console.WriteLine fails with IOException.

### Expected Behavior

Console.WriteLine succeeds; output is effectively discarded

## On which platforms did you notice this

[ ] macOS
[ x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.6.0.161

## Stacktrace

See above.

**Comment by knocte** [comment]
Is this a regression?

**Comment by madelson** [comment]
@knocte it might be. I noticed this when my TravisCI tests for mono started failing unexpectedly after several months without having made any code changes. They are set up to run on "latest" mono.

**Comment by baulig** [comment]
I would argue this is functioning exactly as intended.  Why should the output be "effectively discarded" on a broken pipe?  That doesn't make any sense and also isn't consistent with how things work in the Unix world.

**Comment by steveisok** [comment]
@baulig Can you determine if this was a regression and what the netfx behavior is?

**Comment by baulig** [comment]
Just had a quick chat over lunch about this and we realized it's behaving as intended.

**Comment by madelson** [comment]
Not Trying to argue against the stance that this is working as intended, but it is not consistent with .NET core on linux

**Comment by Nabile-Rahmani** [comment]
I second @madelson.
My update system filters the first line of the program's help to extract the version number, and while it still manages to fetch the information, this regression (?) creates some (spooky at first) noise that wasn't there in previous versions.

Could we have a definitive answer on which implementation makes the most sense ? It's not like I can't replace the `--help` by a `--version`, but I'd like to know for sure since this is a weird dilemma.

On .NET Core 2.2 on Linux, this program will not crash:

```csharp
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("Line 2 ! ");
        }
```

```
$ dotnet NetCore.dll          
Hello World!
Line 2 !
```

```
$ dotnet NetCore.dll | head -1
Hello World!
```
