### ISSUE TITLE
`condition `!rgctx_arg || !imt_arg' not met` when AOTing iOS project using Default Interface Method

### ISSUE THREAD

**Issue by chamons** [mono/mono#18276]
An interface with a DIM that is defined inside a generic class causes a crash during AOTing.  [See comment below for standalone repro](https://github.com/mono/mono/issues/18276#issuecomment-568102830) steps.

Original bug report below.

---

_From @cosminstirbu on Fri, 20 Dec 2019 11:43:34 GMT_

Hello,

After adding `<LangVersion>8.0</LangVersion>` and creating an interface with default implementation, I get the following exception in Release mode: `MTOUCH : error MT3001: Could not AOT the assembly`

Please note that in Debug mode everything works as expected.

## Steps to Reproduce

- git clone git@github.com:FortechRomania/xamarin-training-sample-app.git
- cd xamarin-training-sample-app
- git checkout feature/weakify-tableview-datasource
- open TrainingPreparation.sln and build for iOS Device
- Comment out iOS/ObservingPlainTableViewSource.cs (124) and the problem will disappear.

```
Visual Studio Enterprise 2019 for Mac
Version 8.3.11 (build 1)
Installation UUID: 3564627f-be3d-4606-9bfb-522ee1e2f762
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.0.101/Sdks
SDK Versions:
	3.0.101
	3.0.100
	3.0.100-preview9-014004
	3.0.100-preview8-013656
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.1
	3.0.0
	3.0.0-preview9-19423-09
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9

Xamarin.Profiler
Version: 1.6.11.16
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.2.1 (15526.1)
Build 11B500

Xamarin.Mac
Version: 6.6.0.12 (Visual Studio Enterprise)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:07-0400

Xamarin.iOS
Version: 13.6.0.12 (Visual Studio Enterprise)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

Xamarin Designer
Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

Xamarin.Android
Version: 10.0.6.2 (Visual Studio Enterprise)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/cosminstirbu/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Microsoft Mobile OpenJDK
Java SDK: /Users/cosminstirbu/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:22 UTC

Android Device Manager
Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:42 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803110001
Git revision: 6ee6ad2ec46ae5a08a1999ee4c815ac656a35b91
Build date: 2019-12-05 16:09:27+00
Build branch: release-8.3
Xamarin extensions: 56bd70ef2e327f71c615cfc29a47fd50685fadcb

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
DeepClean 1.2.5
Straight8's SpecFlow Integration 1.11.3.0
FileNesting 0.1.2
StyleCop Support 1.1.0.4
NuGet Package Management Extensions 0.20
```

Thank you,
Cosmin

_Copied from original issue xamarin/xamarin-macios#7632_

**Comment by chamons** [comment]
_From @chamons on Fri, 20 Dec 2019 19:53:53 GMT_

I tried a simple example, adding a interface and class, and DIM, and adding calls to invoke, and I can't reproduce this.

Please attach a project showing the issue so we can track this down.

**Comment by chamons** [comment]
_From @cosminstirbu on Fri, 20 Dec 2019 20:42:57 GMT_

Hello,

You can reproduce the issue on this branch: https://github.com/FortechRomania/xamarin-training-sample-app/tree/feature/weakify-tableview-datasource by selecting the Release configuration and building it for a device (not simulator).

Thanks,
Cosmin

**Comment by chamons** [comment]
_From @chamons on Fri, 20 Dec 2019 21:25:48 GMT_

@cosminstirbu Thanks for the sample. It appears that this line:

var cellReuseIdentifier = WeakDelegate?.GetCellIdentifierForIndexPath(tableView, indexPath) ?? CellReuseIdentifier;

iOS/ObservingPlainTableViewSource.cs (124) is causing the miscompile.

**Comment by chamons** [comment]
_From @chamons on Fri, 20 Dec 2019 21:26:01 GMT_

```    * Assertion at /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mono/mini/calls.c:317, condition `!rgctx_arg || !imt_arg' not met```

**Comment by lambdageek** [comment]
Standalone repro: compile this with `mono --aot=full`
```csharp
using System;

public class WD<T> {
	T obj;
	public WD () {}
	public WD (T obj) { this.obj = obj; }
	public T Get () { return obj; }
}

public class Outer<Q> {
	public interface ID {
		public string Foo () {
			return null;
		}
	}

	public class C {
		private WD<ID> prop;
		public ID Prop {
			get => prop.Get ();
			set => prop = new WD<ID> (value);
		}
		
		public C () {
		}

		public int Foo () {
			return Prop?.Foo()?.Length ?? 0;
		}
	}

	public class H : ID {
		string ID.Foo () {
			return "abcd";
		}
	}
}


public class M {
	public static void Main ()
	{
		var c = new Outer<object>.C ();
		c.Prop = new Outer<object>.H ();
		Console.WriteLine (c.Foo ());
	}
}
```

**Comment by cosminstirbu** [comment]
Thanks for looking into this.

Is there a sensible workaround for my initial `ObservingPlainTableViewSource` scenario that doesn't require dropping the default interface member feature?

I've tried pulling the interface into its own file, but the issue still reproduces.

**Comment by chamons** [comment]
From my limited testing - it appears the combination of DIM and generics is the problem. Dropping one or the other makes it work. I understand that is not a great workaround.

I'll let @lambdageek chime in if I missed something, I'm not a compiler hacker.

**Comment by lambdageek** [comment]
Leaving open until backports land

**Comment by lambdageek** [comment]
Fix backported to 2019-12 and 2019-10

**Comment by cosminstirbu** [comment]
@chamons - what would be the easiest way to monitor when this lands in the next Xamarin.iOS / Mono stable release?

**Comment by chamons** [comment]
This fix will very likely be in d16-5 Preview 3, in preview likely mid-February and stable a month or two later.

If you'd like, I can point you to a build hot off our build machines if you want to try it sooner.
