### ISSUE TITLE
[Regression] DirectoryInfo does not update its instance state when calling Create/Delete (can throw exceptions)

### ISSUE THREAD

**Issue by Nabile-Rahmani** [mono/mono#18291]
When I reinstalled my software on Linux, I was surprised to see my updater initially fail with a `FileNotFoundException` when it created the temporary update folder when it used to work a year ago on Mono 5 and MS' .NET. Weirdly enough, running the program a second time worked.

On the first run, the `.update` folder doesn't exist, so `DirectoryInfo.Create()` creates it, but setting `DirectoryInfo.Attributes` throws a `FileNotFoundException`. This is because `Create()` doesn't update the `Exists` property.

The program crashes, and we can see it left behind a new `.update` folder.

So, on the second run, `DirectoryInfo.Exists` is true, and the program recursively deletes it with `DirectoryInfo.Delete(true)` (to ensure we clean up from a previous update), and it immediately recreates it, and now setting `DirectoryInfo.Attributes` works.

Stepping through a debugger, it's clear that even when calling `Delete()`, the `Exists` property isn't updated to reflect the file system either.

Interestingly, [the update code that I wrote](https://github.com/Nabile-Rahmani/DotN64/blob/a4d06cef67d2cc3fa36dfcd472699b702b671bbf/DotN64.Desktop/Updater.cs#L62-L73) demonstrated both anomalies thanks to it deleting the folder if it already exists. Though, in my case, this regression was only fatal because of `Create()` not updating the instance's state.

But here is a similar reproduction sample along with a couple tables showing the timeline of events:

```csharp
using System.IO;

static class Program
{
    // Run this twice.
    // The first time around, updateDirectory.Exists == false, so subsequent operations throw an exception.
    // The second time around, however, updateDirectory.Exists == true as the first run left behind the newly created folder, and it stays true despite calling Delete().
    static void Main()
    {
        var updateDirectory = new DirectoryInfo(".update");
        
        if (updateDirectory.Exists)
            updateDirectory.Delete(true); // Clears old update files if still there.
            
        updateDirectory.Create(); // Recreate the directory.
        updateDirectory.Attributes = FileAttributes.Directory | FileAttributes.Hidden; // Cosmetic for Windows users. On Linux, the attributes are already that way as it's a dotfolder, so nothing's new.
    }
}
```

First run:

| Source | updateDirectory.Exists | Exists in the file system |
|---|---|---|
| `if (updateDirectory.Exists)` | false | false |
| `updateDirectory.Create();` | false | false |
| `updateDirectory.Attributes = FileAttributes.Directory \| FileAttributes.Hidden;` | false | true |

```System.IO.FileNotFoundException has been thrown```

Second run:

| Source | updateDirectory.Exists | Exists in the file system |
|---|---|---|
| `if (updateDirectory.Exists)` | true | true |
| `updateDirectory.Delete(true);` | true | true |
| `updateDirectory.Create();` | true | false |
| `updateDirectory.Attributes = FileAttributes.Directory \| FileAttributes.Hidden;` | true | true |

Execution proceeds as normal this time.

### Current Behavior

`DirectoryInfo` instances aren't consistent with the file system when calling methods with side effects such as `Create()` and `Delete()`, which will result in exceptions being thrown when accessing the file system entries.

### Expected Behavior

These method calls should update the instance's members.

## On which platforms did you notice this

- [ ] macOS
- [x] Linux
- [ ] Windows

**Version Used**:

`Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:20:06 UTC 2019)`

## Stacktrace

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not find file '/tmp/Bug report/.update'.
File name: '/tmp/Bug report/.update'
  at System.IO.FileSystemInfo.ThrowNotFound (System.String path) <0x7fc98ce939b0 + 0x00073> in <285579f54af44a2ca048dad6be20e190>:0 
  at System.IO.FileStatus.SetAttributes (System.String path, System.IO.FileAttributes attributes) <0x7fc98ce8f130 + 0x00221> in <285579f54af44a2ca048dad6be20e190>:0 
  at System.IO.FileSystemInfo.set_Attributes (System.IO.FileAttributes value) <0x7fc98ce92e90 + 0x00031> in <285579f54af44a2ca048dad6be20e190>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileSystemInfo.set_Attributes(System.IO.FileAttributes)
  at Program.Main () [0x00025] in <3660ac717b7e48c6ab2924d3b0c6679d>:0
```

**Comment by steveisok** [comment]
Looks like this was a problem upstream and they fixed it 3 months ago.  The DirectoryInfo wasn't being invalidated after the directory was created.

https://github.com/dotnet/runtime/commit/db671a853e3c7a3eea5016b2dedf7b1977a17002

Will be trivial to backport.

**Comment by Nabile-Rahmani** [comment]
It's a weird inconsistency that `Delete()` doesn't invalidate the state like `Create()` does. It's a thing on the non-corefx .NET Framework too:

```
C:\Users\Nabile\Desktop\a>main.exe
DeleteMe exists.
Deleted DeleteMe.
DirectoryInfo.Exists = True
```

The API docs don't state which members automatically update the instance state.

**Comment by steveisok** [comment]
Delete in DirectoryInfo may not invalidate by design.  Check out this test:

https://github.com/dotnet/runtime/blob/07d35274e35e4f347d43939d8527fbf93736bd36/src/libraries/System.IO.FileSystem/tests/DirectoryInfo/Delete.cs#L16-L29

I'll double check upstream.

**Comment by steveisok** [comment]
OK, looks like this is sort of ongoing, so I'll only touch Create to mirror upstream.

see -> https://github.com/dotnet/corefx/pull/40677
