### ISSUE TITLE
How to install in Ubuntu 19.10

### ISSUE THREAD

**Issue by shag00** [mono/mono#18319]
The installation instructions at:
https://www.mono-project.com/docs/compiling-mono/linux/
seem to be some years out of date and do not install anything. I wonder if someone might update them so the less computer literate among us can install it.

PS. Is mono-mono-6.6.0.161.tar.gz the complete mono package?

**Comment by nagytech** [comment]
Those instructions are for compiling mono from source which is not something that the average person will want to do.  As you hinted towards computer literacy, I'm assuming that you're not wanting to compile this yourself - correct me if I'm wrong.

There are some installation instructions which use precompiled binaries here:

https://www.mono-project.com/download/stable/#download-lin

**Comment by shag00** [comment]
Jonathon,

if I understand correctly, if I download, mono-mono-6.6.0.161 from, https://github.com/mono/mono and follow the commands on the page I linked I should be right to go. I may not be very computer literate but I think I can follow reasonable instructions. To answer your question directly I am not keen to compile myself because I'm not that sure of what I am doing but I feel it would not be appropriate to ask the world at large to compile things for me.

I saw the pre compiled page you linked but it is for 18.04 and there is not a 19.10 version available in the repository. I think that package is available in a couple of places including the Ubuntu repository and is version 5.18 from memory. The reason I want 6.6.0 is because I am trying to get a program to work on linux but it is missing some essential functionality using the 5.18 version. The author of the program says his program works with mono and I can only assume he is using an up to date version (6.6.0).

Notwithstanding how, I am keen to get my hands on a version 6.6.0 of mono.

I hope this is a comprehensible reply.

Thanks for responding,

Scott
[https://avatars2.githubusercontent.com/u/53395?s=400&v=4]<https://github.com/mono/mono>
GitHub - mono/mono: Mono open source ECMA CLI, C# and .NET implementation.<https://github.com/mono/mono>
Mono is a software platform designed to allow developers to easily create cross platform applications. It is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
github.com


________________________________

**Comment by nagytech** [comment]
> I saw the pre compiled page you linked but it is for 18.04 and there is not a 19.10 version available in the repository.

There's a note on that page which reads "Note: the packages should work on newer Ubuntu versions too but we only test the ones listed below."  So it should work for you.

Out of curiosity, I ran it myself and there's no issues using 18.04 packages on 19.10:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/8542033/71613024-2c19e600-2bf8-11ea-8fd8-687e6ec20e74.png">

**Comment by shag00** [comment]
Well thank you very much for your trouble, I appreciate it. One of the pit falls of being illiterate, I only have a production environment with a lot of Wine based programs and I was terrified I might lose the lot by doing something when i don't really know what it is I am doing.

To be a real PITA how do you do what you did from the Ubuntu terminal when I do not have Docker?

I got:
scott@scottubuntu:~$ echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
[sudo] password for scott:
deb https://download.mono-project.com/repo/ubuntu stable-bionic main

Not sure what this did but it did not install anything.

Regards,

________________________________

**Comment by nagytech** [comment]
@shag00 The commands from the docker file are directly from the page I linked earlier (sans the `sudo` command).

```
sudo apt install gnupg ca-certificates
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
```

And then, 

```
sudo apt install mono-devel
```

**Comment by shag00** [comment]
Thanks, successfully installed:
scott@scottubuntu:~$ mono --version
Mono JIT compiler version 6.6.0.161 (tarball Tue Dec 10 10:36:32 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)


________________________________
