### ISSUE TITLE
Error MT2101: Can't resolve the reference 'System.Security.Cryptography.Pkcs.SignedCms'

### ISSUE THREAD

**Issue by chamons** [mono/mono#18323]
_From @vsfeedback on Mon, 30 Dec 2019 18:27:53 GMT_

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/861186/error-mt2101-cant-resolve-the-reference-systemsecu.html)._

Steps to reproduce:

- Download and extract sample from user (reduced in size)
[ErrorSample.zip](https://github.com/xamarin/xamarin-macios/files/4010640/ErrorSample.zip)
- Build
- Error:

```
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2126,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
MTOUCH : warning MT0109: The assembly 'System.Security.Cryptography.Pkcs.dll' was loaded from a different path than the provided path (provided path: /Users/donblas/.nuget/packages/system.security.cryptography.pkcs/4.7.0/runtimes/win/lib/netstandard2.1/System.Security.Cryptography.Pkcs.dll, actual path: /Users/donblas/Programming/macios/master/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/lib/mono/Xamarin.iOS/Facades/System.Security.Cryptography.Pkcs.dll).
MTOUCH : error MT2002: Failed to resolve "System.Security.Cryptography.Pkcs.SignedCms" reference from "System.Security.Cryptography.Pkcs, Version=4.0.3.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
```

Full Log: https://gist.github.com/chamons/53339ab1b25b0ca533b04525a6c62027

---
When I add the nuget package System.Security.Cryptography.Pkcs version 4.7.0 found here:

https://www.nuget.org/packages/System.Security.Cryptography.Pkcs/

I get the following build error:

Error MT2101: Can't resolve the reference 'System.Security.Cryptography.Pkcs.SignedCms'

I didn’t notice this until I tried to deploy to my phone as it all worked fine on the emulator.  However, I’ve found if I turn off Linking it all works - even on my phone.  However, this seems dangerous and I’m afraid of issues it could cause down the road.

---
#### Stephen Huff on 12/18/2019, 00:20 PM: 

<p>BTW this is the full error:</p><p>/Users/shuff/Development/shuff_Branch/DocExMobile/DocExMobile.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Security.Cryptography.Pkcs.SignedCms', referenced from the method 'System.Void MsgReader.Outlook.Storage/Message::ProcessSignedContent(System.Byte[])' in 'System.Security.Cryptography.Pkcs, Version=4.0.3.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (MT2101) (DocExMobile.iOS)
</p><p>I tried adding the following to "Additional mtouch arguments"</p><p>--linkskip=System.Security.Cryptography.Pkcs</p><p>but it still errors with "Link Framework SDKs Only" picked.  The only work around is "Don't Link"</p>

#### Visual Studio Feedback System on 12/19/2019, 01:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Chris Hamons [MSFT] on 12/23/2019, 04:40 PM: 

<p>I have attempted to reproduce your issue in the current stable with:</p>
<ul>
<li>New iOS Single View Project</li>
<li>Add System.Security.Cryptography.Pkcs nuget</li>
<li>Build Release (Generic Device)</li>
</ul>
<p>and it builds fine for me.</p>
<p>Please attach a sample project showing the issue.</p>

#### Stephen Huff on 12/24/2019, 10:45 PM: 

<p>I've tried reproducing it in a sample project and have not been able to - is there a way I can privately share the entire project that produces the error with you?</p>

#### Stephen Huff on 12/24/2019, 11:18 PM: 

<p>I got it to error in a test project after all by creating it in the same way and adding all the same references.  I originally created my project in Visual Studio 2019 on Windows and then moved it to the Mac - I did the same for this project.  I then added all the exact same references but didn't get the error until I added the using statement and created the line:</p><p> var signedCms = new SignedCms()</p><p>in MainPage.Xaml.cs . That and the using statement are the only differences between what Visual Studio 2019 created in Windows and what I changed on the Mac (other then setting the Debug project to "Link Framework SDKs Only").<a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/111377-errorsample.zip">errorsample.zip</a></p>

---
### Original Solutions
(no solutions)

_Copied from original issue xamarin/xamarin-macios#7663_

**Comment by sehuff** [comment]
Should this fix be in Mono 6.8.0.87 because I'm still getting the error?

**Comment by chamons** [comment]
@sehuff - No, this was fixed a 21 days ago, it would need to be integration with a new Xamarin iOS or Mac release for you to likely see the fix.

@steveisok - Is this worth/safe for 2019-08 or does it need to be -10 only?

**Comment by steveisok** [comment]
re: 2019-08, that is up to @marek-safar

**Comment by marek-safar** [comment]
This will be 20190-10+ only

**Comment by chamons** [comment]
Thanks @marek-safar!

**Comment by chamons** [comment]
@sehuff - It depends upon if you are using Xamarin.Mac/iOS or mono directly. It won't be until late spring/summer until we have a release based on 2019-10 or later.

**Comment by sehuff** [comment]
@chamons I'm using Xamarin.iOS so I assume it's going to be awhile.

**Comment by jaspervanmegroot** [comment]
When is this fix available? I really need this for my project because I am using MSGReader library for Xamarin.iOS.

**Comment by chamons** [comment]
@jaspervanmegroot - As I noted before:

``` It won't be until late spring/summer until we have a release based on 2019-10 or later.```

If you are on VS for Mac, and don't mind testing unstable master, our latest builds from master should have the fix.

As the fix was declared `2019-10+ only`, it would be exceptionally difficult to back port to the mono runtime used by current releases.

**Comment by jaspervanmegroot** [comment]
@chamons Thanks for the info!
