### ISSUE TITLE
Memory leak in threadpool

### ISSUE THREAD

**Issue by ayushm007** [mono/mono#18343]
## Steps to Reproduce

1. Install Mono version 6.6.0.161 
2. export MONO_GC_PARAMS=major=marksweep,max-heap-size=16m
3. Run attached program 
Note: program run on ARM target on linux.

[MemoryLeakThreadPool.zip](https://github.com/mono/mono/files/4025397/MemoryLeakThreadPool.zip)

### Current Behavior

"Insufficient memory to continue the execution of the program." shown after 5-10 minutes.
## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.6.0.161 (tarball Wed Dec 25 16:09:44 IST 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by ayushm007** [comment]
Any suggestions about this issue?

**Comment by lewurm** [comment]
When using such a small heap you need to adjust the nursery size too. For example `nursery-size=512k` makes it work for me for your provided repro. By the way, use `MONO_LOG_LEVEL=debug MONO_LOG_MASK=gc` to see the GC at work.

@BrzVlad do you have any better advice?
