### ISSUE TITLE
Make the PR Bot Come Alive

### ISSUE THREAD

**Issue by steveisok** [mono/mono#18358]
In order to make the move to dotnet/runtime sucessful, we need to bring online the PR bot and make sure to test it out.  

- [x] Create the PR bot 
- [x] Test a PR from mono/mono, does it create a draft PR in dotnet/runtime?
- [x] Test a PR from dotnet/runtime, does it create a draft PR in mono/mono?
- [x] Test a push on an existing PR in mono/mono, does it update the draft PR in dotnet/runtime?
- [x] Test a push on an existing PR in dotnet/runtime, does it update the draft PR in mono/mono?

Feel free to add more testing scenarios should they be discovered.

**Comment by akoeplinger** [comment]
Done.
