### ISSUE TITLE
ThreadLocal<T> not using the JIT fast path for TLS access

### ISSUE THREAD

**Issue by fanyang-mono** [mono/mono#18370]
## Steps to Reproduce

Make the following change to mono/netcore/build.sh
<img width="512" alt="Screen Shot 2020-01-07 at 11 20 17 AM" src="https://user-images.githubusercontent.com/52458914/71910411-dc7b7300-313f-11ea-9676-8355de742a4b.png">

Then run the following script by following the instructions in it.
[profileMonoScript.sh.zip](https://github.com/mono/mono/files/4031426/profileMonoScript.sh.zip)

### Current Behavior

System_Threading_ThreadLocal_1_T_REF_get_Value/mono_class_static_field_address is one of the hotspots according to the following flamegraph
<img width="1203" alt="Screen Shot 2020-01-07 at 10 29 24 AM" src="https://user-images.githubusercontent.com/52458914/71907150-6bd15800-3139-11ea-93b1-ca6588dfb805.png">

### Expected Behavior

System_Threading_ThreadLocal_1_T_REF_get_Value/mono_class_static_field_address should take a small portion of time of the whole program.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

mono master: 61eb2be2e10c228c5915d90a90b52e7d410c0f25 from Dec 30th, 2019

**Comment by fanyang-mono** [comment]
Quote from @lambdageek:
"It looks like there is contention for the domain lock which protects the hash table that contains the offsets of the special static fields.
We could investigate using a concurrent hash table – ie replace GHashTable by MonoConcGHashTable which is lock free and would perform better for concurrent lookups."

**Comment by vargaz** [comment]
The JIT is supposed to emit optimized code for TLS access, mono_class_static_field_address () is the slow path. It looks like the fast path is not used in some cases like generic shared methods which is what ThreadLocal<T> is.
