### ISSUE TITLE
msbuild fails with csc.exe exited with code 1

### ISSUE THREAD

**Issue by w4mmp** [mono/mono#18400]
Here is an extremely simple VS2019 project that has only one form.  It will not build with Mono msbuild.   This is with the Windows version of Mono. (The same issue happens on Raspbian (Buster release).
## Steps to Reproduce

1.  unzip the included VS 2019 project
2. run - msbuild Mono-test.sln
3. 

### Current Behavior

 build fails with C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc
.exe" exited with code 1. [G:\Ham Radio\ominaSDR\Hardware\Linux\test\Mono-test\Mono-test\Mono-test.csproj]

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[x] Windows

**Version Used**: mono -V
Mono JIT compiler version 6.6.0 (Visual Studio built mono)

## Stacktrace

```
Please paste the stack trace here if available.
```

[mono-msbuild-output.txt](https://github.com/mono/mono/files/4040407/mono-msbuild-output.txt)

[Mono-test.zip](https://github.com/mono/mono/files/4040412/Mono-test.zip)

**Comment by klara-zielinska** [comment]
I have exactly the same. Mono 6.6.0. xbuild works correctly.

Maybe you should not remove xbuild. At least it is an option in such situations.

**Comment by w4mmp** [comment]
Hello,
Thank for responding.  Unfortunately xbuild does not build successfully either.  
I am really hoping the Mono development team responds to this.  I am really hoping to use Mono to port my Visual Studio 2017 application to the Raspberry PI 4.   So far this does not look promising.

Regards,
Ron
[mono-msbuild-output.txt](https://github.com/mono/mono/files/4060866/mono-msbuild-output.txt)

**Comment by marek-safar** [comment]
There is not a great level of detail. Could you please run msbuild with verbose logging? It's also worth trying to run with disabled msbuild compiler server.

/cc @radical

**Comment by w4mmp** [comment]
Hello,
Attached is msbuild with verbose logging.   " It's also worth trying to run with disabled msbuild compiler server.".  I don't know what that means.
Regards, Ron
[mono-1.txt](https://github.com/mono/mono/files/4065416/mono-1.txt)

**Comment by radical** [comment]
```
  C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform
  :AnyCPU /errorreport:prompt /warn:4 /define:TRACE /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemb
  lies\Microsoft\Framework\.NETFramework\v4.0\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemb
  lies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Mic
  rosoft\Framework\.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsof
  t\Framework\.NETFramework\v4.0\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemb
  lies\Microsoft\Framework\.NETFramework\v4.0\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\
  Microsoft\Framework\.NETFramework\v4.0\System.Deployment.dll" /reference:"C:\Program Files (x86)\Reference Assemblies
  \Microsoft\Framework\.NETFramework\v4.0\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft
  \Framework\.NETFramework\v4.0\System.Drawing.dll" /reference:"C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\
  Assemblies\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFrame
  work\v4.0\System.Windows.Forms.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETF
  ramework\v4.0\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramewo
  rk\v4.0\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:\Release\Mono-test.exe /resource:\Release\
  Mono_test.Properties.Resources.resources /target:winexe /utf8output /deterministic+ /langversion:7.3 Form1.cs Form1.D
  esigner.cs Program.cs Properties\AssemblyInfo.cs Properties\Resources.Designer.cs Properties\Settings.Designer.cs "C:
  \Users\Ron\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cs" (TaskId:20)
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn (
  TaskId:20)

  Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03
  f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. (TaskId:20)
C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.e
xe" exited with code 1. [G:\Ham Radio\ominaSDR\Hardware\Linux\test\Mono-test\Mono-test\Mono-test.csproj]
```

**Comment by radical** [comment]
@w4mmp what does `mono --version` and `msbuild -version` say?

**Comment by w4mmp** [comment]
C:\Program Files (x86)\Mono>mono --version
Mono JIT compiler version 6.6.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

C:\Program Files (x86)\Mono>msbuild -version
Microsoft (R) Build Engine version 16.4.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.4.0.57901
C:\Program Files (x86)\Mono>

**Comment by w4mmp** [comment]
Folks,
This is very easy to test yourselves.   Simply submit the Mono-test.sln to msbuild and see the results. (The entire VS2017 solution/project has been included as part of the bug report).  Just be sure the PC is running Windows 10 (fully updated).

**Comment by radical** [comment]
Where did you get this mono from? It doesn't seem to have the full version, for some reason.

**Comment by w4mmp** [comment]
From here: https://www.mono-project.com/download/stable/.   I downloaded and installed the 32bit version.

**Comment by radical** [comment]
Hm this seems to be failing because msbuild uses `System.Diagnostics.Process` to run `csc.exe`, and mono on windows, IIUC, just runs that with the win32 api - which runs `csc.exe` with .net (https://github.com/mono/mono/blob/2019-08/mono/metadata/w32process-win32.c#L155) instead of Mono. On unix, mono executes managed binaries with mono itself (https://github.com/mono/mono/blob/2019-08/mono/metadata/w32process-unix.c#L1719-L1736).
And this is how the .net `csc.exe` invocation fails:

```
*** Assembly Binder Log Entry  (1/15/2020 @ 8:04:53 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = csc.exe
Calling assembly : csc, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.1.1.0 redirected to 4.1.1.0.
LOG: Post-policy reference: System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages/System.Text.Encoding.CodePages.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages/System.Text.Encoding.CodePages.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (1/15/2020 @ 8:04:53 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = csc.exe
Calling assembly : csc, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.1.1.0 redirected to 4.1.1.0.
LOG: Post-policy reference: System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages/System.Text.Encoding.CodePages.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Mono/lib/mono/msbuild/15.0/bin/Roslyn/System.Text.Encoding.CodePages/System.Text.Encoding.CodePages.EXE.
LOG: All probing URLs attempted and failed.
```

@marek-safar What's the expectation here? Should we be running mono's copy of `csc.exe` with .net?
/cc @lewing

**Comment by marek-safar** [comment]
@radical no, we should use mono to run csc even on windows

**Comment by w4mmp** [comment]
Here is my Windows path configuration, if it helps:
C:\Program Files (x86)\Mono>path
PATH=C:\Program Files (x86)\Mono\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Users\Ron\AppData\Local\Microsoft\WindowsApps;C:\Users\Ron\AppData\Roaming\npm;C:\FCIV;

C:\Program Files (x86)\Mono>csc
Microsoft (R) Visual C# Compiler version 3.4.0-beta4-19569-03 (82f2e254)
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS2008: No source files specified.
error CS1562: Outputs without source must have the /out option specified

C:\Program Files (x86)\Mono>

**Comment by radical** [comment]
Opened an issue for this - https://github.com/mono/mono/issues/18484

**Comment by radical** [comment]
@w4mmp meanwhile, you can add this to your msbuild command line to use csc correctly: `/p:CscToolPath="c:\Program Files (x86)\Mono\bin" /p:CscToolExe=csc.bat`

**Comment by w4mmp** [comment]
Folks,
I added the above switches and the original failure does not occur.  However, now a new error is presented.   Sorry for the rant, but I can't understand how this version of Mono was released when it can't even build the most basic of a VS 2019 solution.   
[mono-2.txt](https://github.com/mono/mono/files/4073443/mono-2.txt)

**Comment by radical** [comment]
Hm could you also add `/p:DebugType=portable` to that command line?

Also, you mentioned that you hit the same issue on Raspbian? Which version of mono was that? I was able to build your project on Ubuntu 18.04 with `6.8.0.96`.

Could you try the latest stable versions? Windows also has 6.8.0x available now. (https://www.mono-project.com/download/stable/#download-win)

**Comment by w4mmp** [comment]
Hello,
Adding the above switch allowed msbuild to complete successfully.  Thank you!
I am downloading and installing the latest stable version now.  I will update after I have a chance to test.

**Comment by w4mmp** [comment]
Hello,
The latest stable version was installed.  Success!  The test solution builds successfully with no warnings or errors.  Thanks so much!  You may close this bug report.  As for the Linux,  should I find it errors, I will start a new bug report specifically for Linux (Raspbian Buster).  
Regards,
Ron
