### ISSUE TITLE
Thread.VolatileRead(ref Object) causes assertion failure

### ISSUE THREAD

**Issue by madewokherd** [mono/mono#18418]
## Steps to Reproduce

1. Run attached testcase: [test.zip](https://github.com/mono/mono/files/4047510/test.zip)

### Current Behavior

* Assertion at /home/meh/work/wine-mono/mono/mono/mini/intrinsics.c:1047, condition `mini_type_is_reference (fsig->params [0])' not met

### Expected Behavior

Prints "test" and "test 2".

## On which platforms did you notice this

[ ] macOS
[x] Linux
[x] Windows

**Version Used**: Wine Mono's fork (master/90db1018120) based on 6f248326465cb8c887f3c59672343155689faa79.

**Comment by madewokherd** [comment]
It seems `mini_type_is_reference` doesn't behave the way it's expected here. For any byref parameter it will return FALSE, because `mini_type_get_underlying_type` for any byref returns IntPtr.

**Comment by ptupitsyn** [comment]
I still get a similar error on `6.8.0.123`:
`Assertion at intrinsics.c:1005, condition `mini_type_is_reference (fsig->params [0])' not met`.

Is this a different issue?

**Comment by madewokherd** [comment]
Looks like the same issue, the fix isn't in that tag.

**Comment by ptupitsyn** [comment]
Tried on today's nightly:

```
> mono --version
Mono JIT compiler version 6.10.0.105 (tarball Mon May 18 08:30:37 UTC 2020)
```

Still get this:
```
* Assertion at intrinsics.c:1039, condition `mini_type_is_reference (fsig->params [0])' not met
```

This happens during JVM calls in Apache Ignite project:
https://github.com/apache/ignite/tree/master/modules/platforms/dotnet

Let me know if a detailed reproducer is needed.

**Comment by vargaz** [comment]
There is a problem with that build, there is no assertion on line 1039 in intrinsics.c in mono master.

**Comment by ptupitsyn** [comment]
@vargaz I foolishly upgraded to Ubuntu 20, now I can't install Mono 5, and all builds of Mono 6 that I tried have this bug. Any advice?

Thanks.

**Comment by vargaz** [comment]
This is not a recent version, the current version is 6.13.x, 6.10 is from December:
Mono JIT compiler version 6.10.0.105 (tarball Mon May 18 08:30:37 UTC 2020)

**Comment by ptupitsyn** [comment]
@vargaz 

> not a recent version
Hmm, May 18 2020 is literally today?

I followed the instructions from https://www.mono-project.com/download/nightly/. How do I get the most recent version on Ubuntu 20?

**Comment by akoeplinger** [comment]
Yeah the nightly build on Linux is broken at the moment so you get the builds from the `preview` branch at the moment which is based on a Mono branch from December.

**Comment by pigsi** [comment]
Having exactly the same issue, I've managed to overcome this by pinpoint mono version 6.4.0.198 (Ubuntu 18.04) which seems to work correctly also with Ubuntu 20.04. Any time plan when this will be corrected?

**Comment by ptupitsyn** [comment]
@pigsi 6.4.0.198 does not seem to be available for Ubuntu 20, how did you install it?
https://download.mono-project.com/repo/ubuntu/dists/stable-focal/snapshots/
