### ISSUE TITLE
Blazor WASM Cast<T> Error

### ISSUE THREAD

**Issue by JulienM28** [mono/mono#18419]
I have this class:

````csharp
  public class SupplierDto : INavigationListItem
````
I have a list of SupplierDto Deserilized from a json string:
````csharp
List<SupplierDto> dto = JsonSerializer.Deserialize<List<SupplierDto>>(responseString);
````
And i want to cas it do I did that:
````csharp
List<INavigationListItem> Items = _entities..Cast<INavigationListItem>().ToList();
````

I get this error:

blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: System.InvalidCastException: Specified cast is not valid.
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () <0x2271278 + 0x00068> in <b51c1933184d4dceadd1b43b1badf1d6>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) <0x2270ed8 + 0x00084> in <781da9efd6db41878e0251092c3ff5e1>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) <0x2270d18 + 0x00092> in <781da9efd6db41878e0251092c3ff5e1>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) <0x2270b38 + 0x0002a> in <b51c1933184d4dceadd1b43b1badf1d6>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Client.Pages.Settings.SuppliersBase.OnInitializedAsync () [0x00166] in C:\Team Foundation\Graphene\Client\Pages\Settings\Suppliers.razor.cs:32 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x1eb6968 + 0x0014c> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x21c1668 + 0x000c2> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0 
h.printErr @ blazor.webassembly.js:1

I tried some variant like 

````csharp
List<INavigationListItem> Items = _entities.AsEnumerable()..Cast<INavigationListItem>().ToList();
````

but the result is the same;

both of these solutions are working:

````csharp
Items = _entities.OfType<INavigationListItem>().ToList();
Items = _entities.Select(s => s).ToList<INavigationListItem>();
````

I opened an issue on AspNet Core GitHub : 
https://github.com/dotnet/aspnetcore/issues/18245

But they told me to open an issue here.

Thanks

**Comment by vargaz** [comment]
Can't reproduce this with:

public interface AIface
{
}

public class AClass : AIface
{
}

		var l = new List<AClass> ();
		l.Add (new AClass ());
		List<AIface> iface = l.Cast<AIface> ().ToList ();

**Comment by kjpou1** [comment]
Am closing this as not heard back for OP.  If you feel this has been closed in error please reopen and provide more information.
