### ISSUE TITLE
[utils] Thread state transitions are expensive

### ISSUE THREAD

**Issue by CoffeeFlux** [mono/mono#18431]
When looking at the flame graph for the latest TechEmpower benchmark run, I noted the transitions were taking longer than a glance through the code makes me think they should be. State transitions are 5.8% of the cpu time for the total run and 9.1% after we enter `mono_jit_runtime_invoke`. We can probably do better, and any improvement should be significant.

My naive assumption is that we're spinning in one of the retry loops for too long, but further profiling should probably make clear what's going on.

Apparently this has historically been known to be an issue, but I'm still inclined to investigate and see if there's any low-hanging fruit now that we have concrete numbers on the perf impact.

**Comment by lambdageek** [comment]
This is likely related to `copy_stack_data`.  We previously tried to avoid using `copy_stack_data` on some platforms https://github.com/mono/mono/commit/ad90ebd3abf06a33174ebf0979950025e7381f50) but we had to revert that code (https://github.com/mono/mono/pull/17150).

As noted in https://github.com/mono/mono/pull/17110#issuecomment-537830112 (that PR should also be revisited) - we need to have better test coverage (particularly the embedder scenarios) before we go to change the behavior.

**Comment by CoffeeFlux** [comment]
Got an updated flame graph on the actual hardware, as opposed to a VM, and their perf looks as expected. Something about running a Linux VM on OSX causes them to take an insane perf hit. Either way, not a concern given the scenario we care about is running directly on the hardware.

**Comment by jaykrell** [comment]
That's weird to deprioritize running in a VM, considering The Cloud.
Granted, you'd have to compare with Xen and HyperV.

**Comment by CoffeeFlux** [comment]
That's a fair point, though 'Linux in Virtualbox on OSX' isn't exactly a common cloud scenario. I guess someone could just spin up an Azure VM and benchmark on there for more realistic numbers. If the same issue is present, probably worth re-opening the issue and changing the title. I don't personally have time to investigate this much further though :(

**Comment by jaykrell** [comment]
Using Azure should be so easy for us, but seeming it is not.
