### ISSUE TITLE
[merp] Add thread state flags to the crash report

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#18451]
For investigating shutdown hangs it would be useful to know if a thread is foreground or background, if it has any flags set, etc.  (Basically this stuff: https://github.com/mono/mono/blob/08bb5660f6b2cc87ec59fb77c01a1f8cdeda183f/mono/metadata/threads.c#L3577-L3600)

Specifically it would be nice to include `MonoInternalThread:state` (or some encoding of it) in `MonoThreadSummary` as well as `MonoInternalThread:flags`.

(We have a lot of thread state and flags fields elsewhere.  There's also `MonoInternalThread:thread_state`, `MonoThreadInfo:flags`, `MonoThreadInfo:thread_state`, and maybe others. It would be useful to include them too, for investigating other kinds of threading issues. But we should make sure to use really distinct names so that it's easy to decode the crash report.)

**Comment by SamMonoRT** [comment]
Low priority

**Comment by SamMonoRT** [comment]
MERP has been deprioritized given newer releases off dotnet\runtime. Closing this issue.
