### ISSUE TITLE
Poor Support for Digit Separators

### ISSUE THREAD

**Issue by Alexhuszagh** [mono/mono#18467]
There are two errors, one has been previously reported:
1. Digit Separator Copies Digits
2. Digit Separator Doesn't Work In Fraction

## Steps to Reproduce

In the REPL:

```csharp
> 1_2;             // 122
> 122.3_4;     // Fails, (1,6): error CS1525: Unexpected symbol `_4'
```

### Current & Expected Behavior

There are 2 issues, 1). the digit separator should be valid in the fraction component of a number, and 2). the digit separator should not change the value of the number.

## Platforms

**System Information**

I am running Linux, with the following system information:

```bash
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 30 (Thirty)
Release:	30
Codename:	Thirty
$ mono --version
Mono JIT compiler version 6.8.0.96 (tarball Wed Jan 15 09:00:57 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default
```

## Other Related Issues

https://github.com/mono/mono/issues/16648
https://github.com/dotnet/csharplang/issues/55#issuecomment-574901596

**Comment by lewurm** [comment]
probably related: https://github.com/mono/mono/issues/16648

FWIW `csharp` is using the same code as `mcs`.
