### ISSUE TITLE
System.Reflection.Emit no longer works on WebAssembly

### ISSUE THREAD

**Issue by SteveSandersonMS** [mono/mono#18473]
When attempting to upgrade to the latest build of Mono, Blazor's E2E test suite fails with:

![stack](https://user-images.githubusercontent.com/1101362/72513876-96ac6200-3845-11ea-9796-fd0645aa9236.jpg)

@marek-safar suggests the issue may be that SRE is disabled in the latest builds of Mono WebAssembly.

Unfortunately we won't be able to update to versions of Mono with this issue.

**Comment by lewing** [comment]
This was caused by a linker change https://github.com/mono/linker/commit/e022a3b138868d5ea896ea62dcdda45302ea43b9#diff-aa8a3be2f8fa8b613c0a319e0d6bf20c
because you are passing --exclude-feature sre

**Comment by pranavkm** [comment]
Neat. We should be able to fix this on our end.

**Comment by SteveSandersonMS** [comment]
Closing as fixed
