### ISSUE TITLE
msbuild fails with:  MSBUILD : Configuration error MSB4136

### ISSUE THREAD

**Issue by w4mmp** [mono/mono#18498]
Here is an extremely simple VS2017 project that has only one form. It will not build with Mono msbuild. This is with the Linux version of Mono on a Raspberry Pi 3 running Raspbian Buster.
**_Please NOTE:  This is the same VS2017 solution as presented in Issue 18400._**
-->

## Steps to Reproduce

1.  tar -xvf mono.tar.gz
2. msbuild Mono-test.sln
3. OR
4. msbuild-test.bat
[mono.tar.gz](https://github.com/mono/mono/files/4077100/mono.tar.gz)

### Current Behavior
ron@multus:~/src/mono/test $ ./msbuild-test.bat
Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/lib/mono/msbuild/15.0/bin/MSBuild.dll -t:Rebuild -verbosity:diag /p:CscToolPath=c:\Program Files (x86)\Mono\bin /p:CscToolExe=csc.bat -p:Configuration=Release /p:DebugType=portable Mono-test.sln
MSBUILD : Configuration error MSB4136: Error reading the toolset information from the configuration file "System.Configuration (6)". Unrecognized configuration section <startup>
ron@multus:~/src/mono/test $

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:
You can use `mono --version` or About dialog to obtain this information.
ron@multus:~/src/mono/test $ msbuild -version
Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.5.0.6501ron@multus:~/src/mono/test $ mono -V
Mono JIT compiler version 6.8.0.96 (tarball Wed Jan 15 10:23:49 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
ron@multus:~/src/mono/test $

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by w4mmp** [comment]
[mono.tar.gz](https://github.com/mono/mono/files/4077120/mono.tar.gz)

**Comment by radical** [comment]
You don't need the `CscTool*` bits, that was required on windows. The command line can be:
`msbuild /t:Rebuild /verbosity:diag /p:Configuration=Release Mono-test.sln`

.. assuming that you have `msbuild` in path, which based on your msbuild.dll, should be in `/usr/bin/msbuild`.

If this still fails, then could you share the output of the above command?
And the output of `$ cat /usr/lib/mono/msbuild/15.0/bin/MSBuild.dll.config`

**Comment by w4mmp** [comment]
ron@multus:~/src/mono/test $ ls
Mono-test  Mono-test.sln  msbuilddll.out  msbuild-test
ron@multus:~/src/mono/test $ ./msbuild-test
Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/lib/mono/msbuild/15.0/bin/MSBuild.dll -p:Configuration=Release -t:Rebuild -verbosity:diag Mono-test.sln
MSBUILD : Configuration error MSB4136: Error reading the toolset information from the configuration file "System.Configuration (6)". Unrecognized configuration section <startup>
ron@multus:~/src/mono/test $

[msbuilddll.txt](https://github.com/mono/mono/files/4081731/msbuilddll.txt)

**Comment by w4mmp** [comment]
BTW:
The version of Mono was obtained here:https://www.mono-project.com/download/stable/#download-lin-raspbian.   I used the Raspbian 10 instructions.

**Comment by radical** [comment]
I don't access to a raspbian box right now, so I can't test this myself.
Can you share the contents of your `msbuild-test` script?

Also, can you try this:

`$ MONO_LOG_LEVEL=debug MONO_LOG_MASK=cfg msbuild -p:Configuration=Release -t:Rebuild -verbosity:diag Mono-test.sln 2>&1 | tee cfg-log`

.. and share the `cfg-log` file?

**Comment by w4mmp** [comment]
ron@multus:~/src/mono/test $ more msbuild-test
msbuild  -t:Rebuild -p:Configuration=Release -verbosity:diag  Mono-test.sln
ron@multus:~/src/mono/test $


[cfg-log.txt](https://github.com/mono/mono/files/4082248/cfg-log.txt)

**Comment by w4mmp** [comment]
This is the script.
msbuild  -t:Rebuild -p:Configuration=Release -verbosity:diag  Mono-test.sln

**Comment by radical** [comment]
Ah, now it mentions a specific bit that it can't read `Unrecognized configuration section <startup>`. IIUC, this might be because it didn't read machine.config .

Can you run:
`$ MONO_LOG_LEVEL=debug MONO_LOG_MASK=all MONO_ENV_OPTIONS=--trace=E:System.Configuration.ConfigurationErrorsException msbuild -t:Rebuild -p:Configuration=Release -verbosity:diag Mono-test.sln 2>&1 | tee log`

.. and share the `log` file?

**Comment by w4mmp** [comment]
Here is the log file you requested.
[log.txt](https://github.com/mono/mono/files/4087675/log.txt)

**Comment by w4mmp** [comment]
Here is the Mono Environment you requested.
ron@multus:~/src/mono/test $ env | grep MONO
MONO_ENV_OPTIONS=--trace=E:System.Configuration.ConfigurationErrorsException
MONO_LOG_LEVEL=debug
MONO_LOG_MASK=all
ron@multus:~/src/mono/test $

**Comment by w4mmp** [comment]
I have changed to a Raspberry PI 4B and as part of moving the RPi 4, needed to perform a clean install of Raspbian.  After installing the latest stable release,  the test program now builds successfully.   There must have been something wrong with the previous installation of Mono on the RPi 3.
Regards,
Ron

**Comment by radical** [comment]
Thanks, closing this now.

**Comment by unhammer** [comment]
I also had this issue on Ubuntu. Fixed by `apt purge 'libmono*' nuget 'libnunit*' 'mono-*' 'dotnet*' 'aspnet*'` (and removing leftovers in /etc/mono, /usr/lib/mono, /usr/share/dotnet, ~/.mono) and reinstalling `dotnet-sdk-3.1 mono-complete nuget`.
