### ISSUE TITLE
Mono 6.8.0 XSP m.TypeLoadException: Could not load type of field 'Mono.WebServer.XSP.Server:<>f__mg$cache1'

### ISSUE THREAD

**Issue by alvarengasv** [mono/mono#18500]
## Steps to Reproduce

1. Install or update Mono 6.8.0 and XSP
2. execute: xsp

### Current Behavior
Fails with this error:
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'Mono.WebServer.XSP.Server:<>f__mg$cache1' (3) due to: Could not resolve type with token 0100000b from typeref (expected class 'Mono.Security.Protocol.Tls.PrivateKeySelectionCallback' in assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756') assembly:Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756 type:Mono.Security.Protocol.Tls.PrivateKeySelectionCallback member:(null)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'Mono.WebServer.XSP.Server:<>f__mg$cache1' (3) due to: Could not resolve type with token 0100000b from typeref (expected class 'Mono.Security.Protocol.Tls.PrivateKeySelectionCallback' in assembly 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756') assembly:Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756 type:Mono.Security.Protocol.Tls.PrivateKeySelectionCallback member:(null)

### Expected Behavior
Start without errors.

## On which platforms did you notice this

[X ] Linux

**Version Used**:

Mono JIT compiler version 6.8.0.96 (tarball Wed Jan 15 10:08:18 UTC 2020)

**Comment by steveisok** [comment]
Looks like this was merged into XSP yesterday https://github.com/mono/xsp/pull/88

**Comment by akoeplinger** [comment]
@directhex can you please trigger an updated xsp for Linux?

**Comment by directhex** [comment]
We'll need to ship a version bumped tarball. Any preferences on version number? 6.8 I guess?

**Comment by akoeplinger** [comment]
@directhax I already created a tag for it: https://github.com/mono/xsp/releases/tag/4.7

**Comment by scherenhaenden** [comment]
Same probleme hier :(. Is it already available?

**Comment by scherenhaenden** [comment]
Installed. 
For those needing the "libtool"
sudo apt-get install libtool-bin

**Comment by MHBrand61** [comment]
I have the same problem. How did you install it. Tried 
./autogen.sh
./configure --prefix=/usr
make
sudo make install
but got the error 
cannot open assemly '/usr/bin/lib/mono/4.5/xsp4.exe'

**Comment by lytico** [comment]
This worked for me, thanks to comments from @scherenhaenden and @MHBrand61:

Uninstall:

sudo  apt remove mono-xsp
sudo  apt remove mono-xsp4
sudo  apt remove mono-xsp4-base 

**then manualy** (eg. search with `locate xsp`)  **remove** everything you think it could be mono-xsp

reboot

get
https://github.com/mono/xsp/releases/tag/4.7.1

**sudo apt-get install libtool-bin**
./autogen.sh
./configure --prefix=/usr
make
sudo make install

AND THEN (see message from make install):

**sudo libtool --finish /usr/local/lib**

**Comment by scherenhaenden** [comment]
your welcome. 

Now that i think, I shoud have remove it first. But it works... so. It is ok.

**Comment by lytico** [comment]
ubuntu 18.04 got package-update to 
xsp - 4.7.1
this solves the problem, xsp 
i think this issue can be closed.

**Comment by simonegli8** [comment]
Still have the same problem on Ubuntu 24, don't know how to fix this.

Also building xsp from source fails with (I've installed libtool & libtool-bin via apt):

when I call make:
```
...
/bin/bash: ../libtool: No such file or directory
make[1]: *** [Makefile:479: libfpm_helper_la-fpm_helper.lo] Error 127
make: *** [Makefile:431: all-recursive] Error 1
```
