### ISSUE TITLE
Download the latest stable Mono for Linux CentOS 7 failed

### ISSUE THREAD

**Issue by lhdeng300** [mono/mono#18518]
## Steps to Reproduce

1. rpmkeys --import "http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x3fa7e0328081bff6a14da29aa6a19b38d3d831ef"

2. su -c 'curl https://download.mono-project.com/repo/centos7-stable.repo | tee /etc/yum.repos.d/mono-centos7-stable.repo'

3. yum install mono-complete

### Current Behavior

[root@localhost ~]# yum install mono-complete
Loaded plugins: fastestmirror, langpacks
http://download.opensuse.org/repositories/home%3A/tpokorra%3A/mono/CentOS_CentOS-7/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

### Expected Behavior

No Errors 
## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:
[root@localhost ~]# mono -V
Mono JIT compiler version 5.14.0.177 (tarball Sat Aug  4 08:32:47 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by directhex** [comment]
That's not our error, that's an error from http://download.opensuse.org/repositories/home%3A/tpokorra%3A/mono/CentOS_CentOS-7/
