### ISSUE TITLE
Blazor WASM Enumerable.Append() Issue

### ISSUE THREAD

**Issue by JulienM28** [mono/mono#18515]
I have this code:

````csharp
 var liste = (propertyInfo.GetValue(Entity) as IEnumerable<object>);
Enumerable.Append(liste, val);
````
It doesn't Add anything to my collection.

But this code does:
````csharp
 var liste = (propertyInfo.GetValue(Entity) as IEnumerable<object>).ToList();
liste.Add(val);
````
I tried Append in differents cases, it nevers worked.

Thanks.

Issue openend on Blazor repository : https://github.com/dotnet/aspnetcore/issues/18452

**Comment by vargaz** [comment]
Enumerable.Append returns a new sequence with the new element added to the end of it, it doesn't modify the original IEnumerable:
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.append?view=netframework-4.8

**Comment by kjpou1** [comment]
Closing this as answered.  Please reopen if you feel differently.
