### ISSUE TITLE
[autoconf] inotify broken on FreeBSD; --disable-inotify not working

### ISSUE THREAD

**Issue by rootwyrm** [mono/mono#18528]
## Steps to Reproduce

1. Any FreeBSD 11.3+ will do ya...
2. Use https://reviews.freebsd.org/D23300 on your ports tree
3. If `libinotify` is installed on the system, `autoconf` will ignore `--disable-inotify` 
4. If `libinotify` is installed (or not installed) on the system, and is desired, `autoconf` will fail to pull in correctly as dotnet/corefx#40202 was not fully ported (missing the cmake fixes.)

### Current Behavior

a. `autoconf` ignores --disable-inotify and aggressively detects on FreeBSD
b. `autoconf` does not compile correctly with `libinotify`

```
./configure --with-csc=mcs --disable-btls --disable-dtrace --disable-boehm --disable-inotify --disable-ninja --disable-nls --with-x --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/share/info/ --build=aarch64-portbld-freebsd13.0
...
checking sys/inotify.h usability... no
checking sys/inotify.h presence... no
checking for sys/inotify.h... no
checking for inotify_init in -linotify... yes
checking for inotify_rm_watch with unsigned wd... no
checking for inotify_init... yes
checking for inotify_add_watch... yes
checking for inotify_rm_watch... yes


gmake[5]: Entering directory '/usr/ports/lang/mono/work/mono-6.8.0.96/mono/native'
../../doltlibtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../..  -Wall -Wunused -Wmissing-declarations -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Qunused-arguments -Wno-unused-function -Wno-tautological-compare -Wno-parentheses-equality -Wno-self-assign -Wno-return-stack-address -Wno-constant-logical-operand -Wno-zero-length-array -DLIBICONV_PLUG -DGC_FREEBSD_THREADS -DHOST_BSD -D_WITH_GETLINE -g  -DUSE_COMPILER_TLS -I../.. -I../../mono  -Wall -Wunused -Wmissing-declarations -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Qunused-arguments -Wno-unused-function -Wno-tautological-compare -Wno-parentheses-equality -Wno-self-assign -Wno-return-stack-address -Wno-constant-logical-operand -Wno-zero-length-array -O2 -pipe  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wno-format-zero-length -std=gnu99 -fno-strict-aliasing -fwrapv -DMONO_DLL_EXPORT -g -U_FORTIFY_SOURCE -I/usr/ports/lang/mono/work/mono-6.8.0.96/external/corefx/src/Native/Unix/Common -I/usr/ports/lang/mono/work/mono-6.8.0.96/external/corefx/src/Native/Unix/System.Native -I/usr/ports/lang/mono/work/mono-6.8.0.96/external/corefx/src/Native/AnyOS/brotli/include -I../../mono/eglib -I../../mono/eglib -fvisibility=hidden -DBROTLI_BUILD_NO_RBIT -Wno-typedef-redefinition  -MT libmono_native_la-pal_io.lo -MD -MP -MF .deps/libmono_native_la-pal_io.Tpo -c -o libmono_native_la-pal_io.lo `test -f '../../external/corefx/src/Native/Unix/System.Native/pal_io.c' || echo './'`../../external/corefx/src/Native/Unix/System.Native/pal_io.c
../../external/corefx/src/Native/Unix/System.Native/pal_io.c:37:10: fatal error: 'sys/inotify.h' file not found
#include <sys/inotify.h>
         ^~~~~~~~~~~~~~~
1 error generated.
gmake[5]: *** [Makefile:2119: libmono_native_la-pal_io.lo] Error 1
gmake[5]: Leaving directory '/usr/ports/lang/mono/work/mono-6.8.0.96/mono/native'
```

### Expected Behavior

Should respect `--disable-inotify` (rely on kqueue) and should also correctly detect the location of `inotify.h`

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] FreeBSD (ports)

**Version Used**:

6.8.0.96 (dl.mono-project.org tarball)

## Stacktrace

N/A

**Comment by akoeplinger** [comment]
Looks like on CI we pass `ac_cv_header_sys_inotify_h=no ac_cv_func_inotify_init=no ac_cv_func_inotify_add_watch=no ac_cv_func_inotify_rm_watch=no` to get inotify to be ignored in https://github.com/mono/mono/blob/c4aa3277375f62eeba7d13d862f2c563cb10a285/scripts/ci/run-jenkins.sh#L98

We should fix the configure.ac script to correctly recognize --disable-inotify

**Comment by rootwyrm** [comment]
Also missed the upper-level error (earlier in process): 

```
filewatcher.c:61:10: fatal error: 'sys/inotify.h' file not found
#include <sys/inotify.h>
         ^~~~~~~~~~~~~~~
```

**Comment by rootwyrm** [comment]
Many thanks to @akoeplinger for his help when autoconf kicked my butt. (Pointy-hat to: rootwyrm, who used notes from a wildly wrong version.) We now have a patch suitable for FreeBSD ports to give us desired `--disable-inotify` behavior.

This also helped me identify more clearly what the specific problem is; it actually appears to be an autotools vs. cmake issue. cmake behaves better on FreeBSD and correctly identifies the additional requirement for `-I/usr/local/include` when used in CoreFX. Which actually helped me to identify _another_ problem in autoconf.

`./configure --includedir=/usr/include --includedir=/usr/local/include --disable-dtrace --disable-boehm --disable-ninja --with-x --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/share/info/ --build=amd64-portbld-freebsd12.1` 

This should produce a working result, we would think. Instead, autotools does this:
```
configure:27323: clang -o conftest -Wall -Wunused -Wmissing-declarations -Wpointer-arith -Wno-cast-q
ual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Qunused-argument
s -Wno-unused-function -Wno-tautological-compare -Wno-parentheses-equality -Wno-self-assign -Wno-ret
urn-stack-address -Wno-constant-logical-operand -Wno-zero-length-array -g -O2 -Wmissing-prototypes -
Wstrict-prototypes -Wnested-externs -Wno-format-zero-length -std=gnu99 -fno-strict-aliasing -fwrapv
-DMONO_DLL_EXPORT -g -Werror=sign-conversion -Wall -Wunused -Wmissing-declarations -Wpointer-arith -
Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Qunuse
d-arguments -Wno-unused-function -Wno-tautological-compare -Wno-parentheses-equality -Wno-self-assig
n -Wno-return-stack-address -Wno-constant-logical-operand -Wno-zero-length-array  -DGC_FREEBSD_THREA
DS -DHOST_BSD -D_WITH_GETLINE -g   -lutil -pthread -L/usr/local/lib conftest.c -lm -lintl   -linotif
y -pthread >&5
conftest.c:313:12: fatal error: 'sys/inotify.h' file not found
                #include <sys/inotify.h>
                         ^~~~~~~~~~~~~~~
```

Notice the lack of `-I/usr/local/include`; that's the problem. So it's looking only in `/usr/include` which is why it can't find `sys/inotify.h` (which as you guessed, lives at `/usr/local/include/sys/inotify.h`). Which cmake automatically handles, but autotools seems not to handle correctly. This reproduced when run via `./autogen.sh` as well. 
I took an initial swing at bodging the include in there, but it didn't work as expected, so I'm not sure what I'm missing here. (Other than a lot of warnings about autotools not really handling this sort of need gracefully.) And since this is a more significant change to the autotools portion, I'd definitely like to get some feedback from more experienced folks on the correct way to address the root cause.

**Comment by saper** [comment]
> ./configure --includedir=/usr/include --includedir=/usr/local/include --disable-dtrace

One small note: [--includedir](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html#index-includedir-162) is to set the destination location when installing the header files, not to search for them. If `CPPFLAGS` is set in the environment it should work (FreeBSD ports is setting this for you) but we should fix it for people not using the port.

**Comment by rootwyrm** [comment]
Apologies for the seeming radio silence; I believed I could shuffle this to the back-burner and focus on getting the port itself functional without inotify. Unfortunately, real world app testing has revealed that the lack of inotify is actually breaking Unix permission reading somehow on FreeBSD. Not permission setting - just reading. (It could be a red herring and a general file read issue but the debugs have been unclear.) So I turned my attention back to looking over the inotify issue, because this obviously presents a less disruptive fix than addressing native `kqueue`.

@akoeplinger I've come up with what I believe is a suitable fix, but it's going to require some structural changes. Within the autoconf infrastructure, I will need to add `METADATA_CFLAGS` and `COREFX_CFLAGS`. Adding a blanket `-I/usr/local/include` breaks several other things due to conflicts. I can handle `mono/metadata` but I don't see where the CMake translation for `external/corefx` is.

The cliff's notes of the fix is:
```
if test "x$ac_cv_lib_inotify_inotify_init" = "xyes" ; then
    dnl Use targeted flags to avoid several collisions from ports.
    METADATA_CFLAGS="-I/usr/local/include"
    COREFX_CFLAGS="-I/usr/local/include"
```

**Comment by saper** [comment]
@rootwyrm do you have a simple test for kqueue-only system breaking permission reading?

Also would be good what kind of conflict do we get with a plain `-I/usr/local/include`...

**Comment by rootwyrm** [comment]
@saper Unfortunately, no, the test conditions to reproduce with the most reliability are anything _but_ simple. (Requires a specific application, two supporting applications, UFS, ZFS, and NFSv4 with sec=krb5p.) The exact cause is reliance on `IN_ATTRIB`; Mono doesn't have any implementation or use of the kqueue analog `NOTE_ATTRIB`. More comprehensive native use of `kqueue` is probably a separate discussion though.

I didn't try to track down all of the issues, but the 'big whammy' is `devel/glib20` which is required to build. This collides with `mono/eglib`. I'm certain there's going to be more lurking in there, since a 'pure ports' build of Mono brings in a very large number of ports and three compilers. Most would never be observed on CI because it's specifically run with `pkg` and outside of ports.

**Comment by jaykrell** [comment]
Why is glib / eglib a problem?
The external symbols are all renamed, to avoid some problems.
Is it the header or library name?
The header can surely be renamed.

**Comment by jaykrell** [comment]
The ideal way to build a repro, I think, would be via Docker (assuming some kind of Docker FreeBSD-guest support), or else a VHD/VHDX, etc.

**Comment by saper** [comment]
There is no Docker for FreeBSD. We've had similar issues resolved in the past so I think we'll get there...

**Comment by rootwyrm** [comment]
It's a name collision - both have a `glib.h`. The fix I've proposed will definitely resolve our problem here (library linking was already resolved) even if it is not the greatest and partial testing has been successful. But I haven't been able to locate the corefx cmake 'translator'. This was already fixed upstream in corefx but the cmake hinting portion of the fix wasn't brought back to `external/corefx`.

**Comment by jaykrell** [comment]
So we should just rename it eglib.h or mono-glib.h or something.
I kinda think we should just call everything "mono" and no more this "g" or "eg" stuff, not even macrod away.
