### ISSUE TITLE
Mono Interpreter Losses some Command Line Arguments to Microbenchmarks

### ISSUE THREAD

**Issue by naricc** [mono/mono#18530]
Platform: Linux

Repro:

1. Clone the performance microbencharks from here: https://github.com/dotnet/performance

2.  > cd <git root>/src/benchmarks/micro

3. Build the microbenchmarks; let MONO_DOTNET be a netcore mono:
 
    > $MONO_DOTNET build -c release -f netcoreapp5.0 MicroBenchmarks.csproj 

4. Set mono to use the interpreter (it must be exported so that subprocess the benchmark suite uses inherit it).
   
    > export MONO_ENV_OPTIONS="--interpreter"

5. Run the microbenchmark suite:

   > $MONO_DOTNET run -c Release -f netcoreapp5.0 MicroBenchmarks.csproj --filter "*Perf_Basic*" --cli $MONO_DOTNET

Expected Behavior:

The benchmark suite runs those benchmarks that have "Perf_Basic" in the name.

Actual Behavior:

The benchmark suite seems to ignore the --filter option, and enters interactive mode where you may choose a benchmark interactively.

This only happens when using the interpreter, so I think it is a mono bug (as opposed to a bug in the benchmark suite).

**Comment by BrzVlad** [comment]
This was very painful to track down and, in the end, it was simply reproduced by : 
```
using System;

enum MyEnum { Value1, Value2 }

class Program
{
        static int Main(string[] args)
        {
                MyEnum pl = MyEnum.Value2;
                return pl.Equals (MyEnum.Value2) ? 0 : 1;
        }
}
```

@akoeplinger @SamMonoRT What is our situation on netcore + interpreter testing ? I'm pretty sure such a basic test has to be part of mini/runtime/basic libraries suites.

**Comment by akoeplinger** [comment]
@BrzVlad interpreter tests are still running in mono/mono so you'd have to add the test here.
