### ISSUE TITLE
Move Skipped Netcore Tests Out of .rsp Files

### ISSUE THREAD

**Issue by steveisok** [mono/mono#18538]
In order to be consistent in dotnet/runtime, we need to move our skipped netcore tests out of rsp files and into their respective xUnit tests.  

For each rsp file under `src/mono/netcore`:
- [x] For tests that are failing because a specific feature is missing / doesn't work, use or extend [PlatformDetection](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/PlatformDetection.cs) and apply it to the corresponding test method or class. 
- [x] Apply `[ActiveIssue]` attributes for all skipped tests that have mono issues open.
- [x] Apply `[SkipOnMono]` for tests that do not have a feature specific problem
- [x] For `-nonamespace`, go into each class and use `[PlatformDetection]` or `[SkipOnMono]`
- [ ] Test each platform on CI to ensure the tests are skipped.

Important notes:
- This should not apply to the CoreFX_issues_interpreter.rsp as it's not clear how that will apply (is it a TestPlatform?)
- We added some extra traits, so keep them in the existing rsp files for now and we will address separately.

Here is an example of PlatformDetection: https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Runtime.WindowsRuntime/tests/System/IO/CreateSafeFileHandleTests.cs#L11-L19

Here is an example of ActiveIssue: https://github.com/dotnet/runtime/blob/04f22268efb4434b7cd81e8ae2c3354be99fd4a7/src/libraries/System.Composition/tests/InheritanceTests.cs#L28-L35

The tracking issue in dotnet/runtime: https://github.com/dotnet/runtime/issues/1980

**Comment by MaximLipnin** [comment]
We could close it as completed.
