### ISSUE TITLE
[autotools] Weak -mminimal-toc testing causes fallthrough

### ISSUE THREAD

**Issue by rootwyrm** [mono/mono#18554]
## Steps to Reproduce

Identified on `freebsd-ppc64` by Piotr Kubaj @ FreeBSD; 
"head uses ELFv2 ABI, which doesn't use -mminimal-toc parameter. However, configure.ac forces -mminimal-toc if the compiler binary (CC) doesn't contain "clang" string (our compiler binary is named "cc")."
This can also occur on other OSes when the compiler is also named differently from clang but is a fully functioning compiler.

### Current Behavior

Failure to build due to use of an unsupported flag, based on an erroneous assumption.

### Expected Behavior

autoconf should more robustly test and properly detect whether the given compiler supports `-mminimal-toc`, instead of making an assumption based on strings.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] FreeBSD

**Version Used**:

6.8.0.96

## Stacktrace

N/A

**Comment by pkubaj** [comment]
The check in question should query ELF ABI version by checking the value of `_CALL_ELF` compiler macro like:
```
$ echo | cc -dM -E - | grep _CALL_ELF
#define _CALL_ELF 2
```
To get actual number, you can just do:
```
$ echo | cc -dM -E - | awk '/_CALL_ELF/ {print $NF}'
```

If the value is 2, ELFv2 ABI is used and it's not necessary to use `-mminimal-toc`. In fact, this will break the build.

If the value is 1 or _CALL_ELF is not defined, ELFv1 ABI is used and specifying `-mminimal-toc` is perfectly fine.

**Comment by rootwyrm** [comment]
@pkubaj Good to see you! (Couldn't find your github name to tag you in properly, sorry about that.) Since I don't have ppc64 test hardware, it's very difficult for me to test this. Is the `-mminimal-toc` flag actually present on ELFv2 or will a check for support of `-mminimal-toc` fail on the ELFv2 systems?

**Comment by pkubaj** [comment]
It will fail, the flag is just not present. You need to check `_CALL_ELF` macro.

**Comment by CoffeeFlux** [comment]
cc: @directhex
