### ISSUE TITLE
[wasm][debugger] step out fails at managed boundry

### ISSUE THREAD

**Issue by lewing** [mono/mono#18558]
if you try to step out of a managed function that was invoked by js the breakpoint is never hit and execution continues but the single step stays active an any new attempt to do something that requires single stepping fails with the message:
```
mono_wasm_setup_single_step 1Received a single step request while the previous one was still active.
```

**Comment by lewing** [comment]
It is pretty easy to reproduce by breaking in IntAdd in debug_sample and stepping out

**Comment by lewing** [comment]
part of https://github.com/mono/mono/issues/18237

**Comment by steveisok** [comment]
I could be wrong, but when you step out the first time, `mono_de_ss_create` is called and `the_ss_req = ss_req;` is set.   

After you do another cycle, `mono_wasm_breakpoint_hit` will be called.

https://github.com/mono/mono/blob/14570f14acc0153ab0273a9788ed8768ca26f8bc/mono/mini/mini-wasm-debugger.c#L469-L473

Eventually, `process_breakpoint_events` will be raised and cancel will not be called.  

https://github.com/mono/mono/blob/14570f14acc0153ab0273a9788ed8768ca26f8bc/mono/mini/mini-wasm-debugger.c#L236-L246

The debugger stops and when you try to step, `mono_de_ss_create` is invoked again.  This time `the_ss_req` check will be true and cause the issue we're seeing. 

https://github.com/mono/mono/blob/14570f14acc0153ab0273a9788ed8768ca26f8bc/mono/mini/debugger-engine.c#L1491-L1494

**Comment by steveisok** [comment]
I'm not sure what's supposed to happen?  In the sample, you are stepping out into JS.  If I call `mono_de_cancel_ss()` in `mono_de_ss_create` the problem goes away, but I don't know if that's the best place to put it or not?
