### ISSUE TITLE
[netcore] Get Corerun Working for the MonoVM on dotnet/runtime

### ISSUE THREAD

**Issue by steveisok** [mono/mono#18568]
As a post migration task, we need to enable Corerun to use the MonoVM and be able to run our [samples](https://github.com/mono/mono/tree/master/netcore/sample).

- [x] Make Corerun execute using the MonoVM
- [x] Make the samples run in dotnet/runtime easily
- [x] Add any necessary shortcuts to make execution easier

**Comment by marek-safar** [comment]
We already have everything in place under netcore/corerun it just needs to be included in the build

**Comment by SamMonoRT** [comment]
@steveisok @EgorBo  - can we close this ?

**Comment by steveisok** [comment]
I moved it to 'Done', but didn't close it :-).
