### ISSUE TITLE
Performance regression since Switch to CharUnicodeInfo from corefx

### ISSUE THREAD

**Issue by pr0vieh** [mono/mono#18572]
## Steps to Reproduce

1. Compile Mono
2. Compile Mono with git revert --no-commit 9cc751d61835603d8c5598f0e9e4015a9814a442 #revert CharUnicodeInfo
3. Find Test Repro and Compare Results

### Current Behavior
in my case Massive Performance regression!

with this change:
real 0m24.739s
user 0m19.112s
sys 0m5.046s

[profiler-sample.log](https://github.com/mono/mono/files/4110545/profiler-sample.log) (19 Thread Pool Worker)
[log-mono-master.txt](https://github.com/mono/mono/files/4110547/log-mono-master.txt)

with revert 9cc751d61835603d8c5598f0e9e4015a9814a442:
real 0m14.521s
user 0m12.670s
sys 0m0.315s

[profiler-sample-withrevert.log](https://github.com/mono/mono/files/4110550/profiler-sample-withrevert.log) (2 Thread Pool Worker)
[log-mono-master-withrevert.txt](https://github.com/mono/mono/files/4110549/log-mono-master-withrevert.txt)

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.11.0 (master/8d699659199 Thu Jan 23 20:45:59 CET 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
I might be wrong on this but it look to me the code is faster and causing a lot more contention. However, some stats like `Page Faults` are odd.

@vargaz any thoughts about this?

**Comment by CoffeeFlux** [comment]
Did that commit result in heavier use of our threadpool than before? The legacy threadpool is known to have major lock contention issues/poor perf, so if this is making heavier use of it maybe we should consider porting back the managed threadpool we use in netcore. The log shows a ton of threadpool activity at least, but without the repro it's speculation on my part.

**Comment by pr0vieh** [comment]
hmm this is very strange for sure...
this Set of Benchmarks https://github.com/mono/mono/pull/16954#issuecomment-553816313 looks good to figure out which of this Functions spawn the Threads?
some of this stuff i see in the logs...

how i can find them ? 
i have tested again with JIT and --nollvm instead of FullAOT+Interpreter+LLVM but the same behavior

**Comment by jaykrell** [comment]
Can the data be moved back to .nlp?
Or is there another more efficient way to store it in C# source?

**Comment by pr0vieh** [comment]
i have filtered the AOT loading stuff out and the Diff looks equivalent to line 
`Line 1070 System.Globalization.CharUnicodeInfo:GetUnicodeCategory`

[log-mono-master-filterAOT.txt](https://github.com/mono/mono/files/4175599/log-mono-master-filterAOT.txt)
[log-mono-master-withrevert-filterAOT.txt](https://github.com/mono/mono/files/4175600/log-mono-master-withrevert-filterAOT.txt)

and the Profiler has other differences:

mono | with revert
--------|----------
Compiled methods: 2116 | Compiled methods: 2166
Generated code size: 625731 | Generated code size: 701629
Methods from AOT  : 255 | Methods from AOT: 254

maybe this helps ?

**Comment by vargaz** [comment]
Testcase:
```
System.Globalization.CharUnicodeInfo.GetUnicodeCategory ('A');
var w = System.Diagnostics.Stopwatch.StartNew ();
for (int i = 0; i < 100000; ++i)
System.Globalization.CharUnicodeInfo.GetUnicodeCategory ('A');
w.Stop ();
Console.WriteLine (w.ElapsedMilliseconds);
```
Old version: 1ms
New version: 800ms

**Comment by vargaz** [comment]
.method private hidebysig specialname static 
          valuetype System.ReadOnlySpan`1<uint8> 
          get_CategoryLevel1Index() cil managed
  {
    // Code size       27 (0x1b)
    .maxstack  8
    IL_0000:  ldc.i4     0x880
    IL_0005:  newarr     System.Byte
    IL_000a:  dup
    IL_000b:  ldtoken    field valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=2176' '<PrivateImplementationDetails>'::B55F94CD2F415D0279D7A1AF2265C4D9A90CE47F8C900D5D09AD088796210838
    IL_0010:  call       void System.Runtime.CompilerServices.RuntimeHelpers::InitializeArray(class System.Array,
                                                                                              valuetype System.RuntimeFieldHandle)
    IL_0015:  call       valuetype System.ReadOnlySpan`1<!0> valuetype System.ReadOnlySpan`1<uint8>::op_Implicit(!0[])
    IL_001a:  ret
  } // end of method CharUnicodeInfo::get_CategoryLevel1Index

There is no caching in this method.

**Comment by vargaz** [comment]
The /features:peverify-compat argument to csc causes it to generate this code.
