### ISSUE TITLE
msbuild on Windows 10:  Build fails

### ISSUE THREAD

**Issue by w4mmp** [mono/mono#18588]
[mscc-manual-bias.zip](https://github.com/mono/mono/files/4112379/mscc-manual-bias.zip)
[mono-build-output.txt](https://github.com/mono/mono/files/4112394/mono-build-output.txt)

Hello,
This a follow up bug report on msbuild on Windows 10.  The previous bug report is 184000.   The test case in that bug report did build once the latest version of Mono was installed.   However now I am attempting to build the actual application and the build fails.  Everything is in the attached zip file to allow you to reproduce the issue.
## Steps to Reproduce

1. unzip the included zip file
2. cd to mscc-manual-bias
3. execute msbuild-test.bat
4. Observe the output of msbuild

"G:\Ham Radio\ominaSDR\Hardware\Linux\ms-sdr-MFC-Waterfall\mscc-manual-bias\mscc-core.sln" (Rebuild target) (1) ->
"G:\Ham Radio\ominaSDR\Hardware\Linux\ms-sdr-MFC-Waterfall\mscc-manual-bias\mscc.csproj" (Rebuild target) (2) ->
(CoreCompile target) ->
  C:\Program Files (x86)\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc
.exe" exited with code 1. [G:\Ham Radio\ominaSDR\Hardware\Linux\ms-sdr-MFC-Waterfall\mscc-manual-bias\mscc.csproj]

    2 Warning(s)
    1 Error(s)

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x ] Windows

**Version Used**:
G:\Ham Radio\ominaSDR\Hardware\Linux\ms-sdr-MFC-Waterfall\mscc-manual-bias>msbuild -version
Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.5.0.6201

G:\Ham Radio\ominaSDR\Hardware\Linux\ms-sdr-MFC-Waterfall\mscc-manual-bias>mono --version
Mono JIT compiler version 6.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
[mscc-manual-bias.zip](https://github.com/mono/mono/files/4112354/mscc-manual-bias.zip)

-->

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by w4mmp** [comment]
The msbuild output.
[mono-build-output.txt](https://github.com/mono/mono/files/4112398/mono-build-output.txt)

**Comment by nemerle** [comment]
It's likely I've encountered the same problem as well. 
From investigating things, I've noticed that the likely culprit is the csc.exe called by msbuild.
The following can be simply verified by running the csc.exe from the mono prompt.
```
C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\csc.exe
Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

**Comment by w4mmp** [comment]
Hello,
Any status updates
