### ISSUE TITLE
mono process in background 

### ISSUE THREAD

**Issue by 9ofe** [mono/mono#18592]
Hello,

i want to run mono process in background forever on my vps
how can i do that  ?

i tried
mono file.exe &
mono file.exe&

but that didn't work 

thanks.

## On which platforms did you notice this

Linux Ubuntu 16.04

**Version Used**:

Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Comment by 9ofe** [comment]
i found a way using $ setsid mono file.exe

**Comment by lewurm** [comment]
This is a general unix question unrelated to mono. Please ask google "how do I run a background process on my server?", those results should help you.
