### ISSUE TITLE
Investigate LLVM-related performance regressions

### ISSUE THREAD

**Issue by imhameed** [mono/mono#18599]
I reran some benchmarks from https://github.com/xamarin/benchmarker and noticed some regressions (as of aa87d3db6d981426ecca6e2637238c8a211689a8) relative to an older version of Mono (552869711702e70e677737e36975e77d4e718679). Some numbers are available [here](https://microsoft-my.sharepoint.com/:x:/p/imhameed/EZ3MevtMiFREimv_b4KzzccBRWYdhXUcK-KdMEi0jWsU_Q?e=cjsUih).

Additionally, there are other lingering performance regressions that are nonsensical; see https://github.com/mono/mono/pull/16954#issuecomment-553816313 and https://github.com/mono/mono/pull/16954#issuecomment-541137530.

It would be useful to know why regressions happened--in particular, did codegen quality actually suffer (this seems unlikely for scimark-mm or for [KnownSizeArray](https://gitter.im/mono/mono?at=5dcd4f2535889012b10854b5)), or are there incidental effects related to the benchmark setup that caused this (e.g. as in "Producing Wrong Data Without Doing Anything Obviously Wrong!").

**Comment by SamMonoRT** [comment]
Closing this old issue. We'll focus on issues coming from dotnet\runtime repo if any
