### ISSUE TITLE
Detecting the underlying OS when running on WebAssembly

### ISSUE THREAD

**Issue by danroth27** [mono/mono#18627]
This is related to https://github.com/mono/mono/issues/13002.

Sometimes in a client web app you want to detect the underlying OS. For example, the https://dot.net site does this to show appropriate getting started info for your platform. How should you do this when running on WebAssembly.

Currently `RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))` returns `true` when running on WebAssembly. Should it instead reflect the actual underlying OS?

`Environment.OSVersion` always returns "Unix 1.0.0.0". Again, should it reflect the underlying OS?

**Comment by steveisok** [comment]
My vote is to defer to `navigator.platform` or `process.platform`.  From what you're saying, I don't think uname (what I think we're using) is able to give the right info. 

With respect to `RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))`, does the developer actually care they're running under webassembly?  Should they?  It's kind of odd to me, but I don't know the original motivation.

**Comment by BrennanConroy** [comment]
> does the developer actually care they're running under webassembly

Yes, for example in SignalR we need to know if we should be using Headers or a query string fallback based on being run in the browser or not.

**Comment by lewing** [comment]
Wouldn't throwing PNSE when you attempt to use headers here be enough though?

**Comment by anurse** [comment]
@lewing it could work, but it means using Exceptions for control-flow and spamming debuggers with first-chance exceptions which is undesirable. Throwing PNSE in this kind of place has generally been [problematic in the past](https://github.com/dotnet/aspnetcore/issues/14706#issuecomment-542843755).

I'm OK with `IsOSPlatform` returning the actual **OS** platform, but I still think we need a way to detect if we're running in a browser. Either that or we need detailed feature detection flags for things we use. For example, it goes beyond WebSockets header support. There are issues with binary protocols, streaming transports (like Server-Sent Events, which is implemented natively in our .NET Client but our implementation won't actually work in many browsers). We do failover-based detection (where if a transport fails we try a different one that may work) but it's not perfect and being able to detect that we're in a browser environment will help us avoid even trying the transports we know won't work.

There are also browser-specific features that we are considering for our JavaScript client and I'd like us to be able to enable those when we are running on WASM. 

Feature-detection over platform-detection is a nice ideal, but in our experience nobody has been able to put in the work to make it sufficiently broad. We're used to dealing with the variety of browsers and doing detection well. I'm not worried about that, as long as we have a way to know we're actually in a browser. TBH, we can do most of our feature detection through JS interop once we know where we are (though I'm not yet sure how we'd abstract that and avoid a dependency from the client to some kind of JS interop library).

**Comment by BrennanConroy** [comment]
Can we get some discussion/decision on this? We're trying to write code around headers and would like to not be randomly broken in the future if the way to detect wasm changes.

**Comment by marek-safar** [comment]
This is an ongoing discussion I have with @terrajobst as well. The idea of feature detection flags for everything looks good on paper but it just does not scale well for platforms which are limited on many APIs. 

However, the original question was if `RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))` is API to use for wasm detection and Environment.OSVersion for host version and both of them make sense to me.

**Comment by kg** [comment]
Note that going forward the ```navigator``` properties will no longer be usable for OS detection: https://github.com/WICG/ua-client-hints

> We can ratchet this deprecation over time, beginning by freezing the version numbers in the header, then removing platform and model information as developers migrate to the alternative mechanisms proposed below.
> Similarly, user agents would freeze the navigator.appVersion, navigator.platform, navigator.productSub, navigator.vendor, and navigator.userAgent attributes to appropriate values for the frozen User-Agent string.

So a maintainable solution to this will need to support the use of client hints if available.

**Comment by danroth27** [comment]
When I last discussed this with @lewing and @SteveSandersonMS I believe  the conclusion was that we didn't want to provide a mechanism for detecting the underlying OS when running on WebAssembly in a browser because there wasn't a reliable way to do so and there were potential privacy concerns. The best we could report was that the underlying platform was a web browser.
