### ISSUE TITLE
Blazor wasm SignalR does not close the connection

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#18628]
_From @campersau on Wednesday, January 29, 2020 8:26:57 AM_

### Describe the bug
Closing or Disposing a SignalR connection in Blazor wasm does not close the actual websocket connection in the browser.

### To Reproduce
- Create a new Blazor wasm app
- Add SignalR client
- Create a HubConnection and start it
- Add button and code to stop the connection
- The network trace in the browser shows that the connection is still pending after clicking the close button

![image](https://user-images.githubusercontent.com/4009570/73342118-3b836200-427e-11ea-8952-cc7aebd04860.png)

```razor
@using Microsoft.AspNetCore.SignalR.Client

@page "/"

<button @onclick="Close">Close SignalR Connection</button>

@code {

    private HubConnection _hubConnection;

    protected override async Task OnInitializedAsync()
    {
        _hubConnection = new HubConnectionBuilder()
            .WithUrl("https://signalrserver/pathtohub")
            .Build();

        await _hubConnection.StartAsync();
    }

    private async Task Close()
    {
        // try both of them
        await _hubConnection.StopAsync();
        await _hubConnection.DisposeAsync();
    }

}
```

I think the problem is that the `WebSocketsTransport` only disposes the client websocket
https://github.com/dotnet/aspnetcore/blob/76b0dffb647d9799e4548882215bcc6c1237d458/src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/WebSocketsTransport.cs#L413
and the current wasm mono websocket implementation does not close the connection on dispose but on `CloseAsync` only.
https://github.com/mono/mono/blob/883162e861c95b7be7c3e830f1d70ff1c8e74fa9/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L479

Because of that feel free to move this issue to the mono repro.

### Further technical details
- ASP.NET Core version 3.2.0-preview1.20073.1
- Microsoft Visual Studio Enterprise 2019 Version 16.4.3

<details>
<summary>dotnet --info</summary>

```
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.101
 Commit:    b377529961

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

_Copied from original issue: dotnet/aspnetcore#18654_

**Comment by mkArtakMSFT** [comment]
_From @conficient on Wednesday, January 29, 2020 2:34:07 PM_

Just encountered this same issue upgrading my [BlazorChatSample](https://github.com/conficient/BlazorChatSample) demo to use the .NET SignalR client. I call `.StopAsync()` and `.DisposeAsync()` as well, but only when I close the browser tab does it drop.

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Wednesday, January 29, 2020 5:43:34 PM_

Thanks for contacting us.
@anurse is this SignalR specific or should I move this to the mono team?

**Comment by mkArtakMSFT** [comment]
_From @anurse on Wednesday, January 29, 2020 9:07:22 PM_

Well, it's a little of both. We should probably call `CloseAsync` but mono should *also* be terminating the connection when the socket is disposed (even if `CloseAsync` wasn't called). We'll take a look at our logic but @mkArtakMSFT I think you should go ahead and move this to mono.

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Thursday, January 30, 2020 1:28:07 AM_

Thanks @anurse. Do you want to file a separate issue (if you haven't yet) to track the work we need to do on our side?

**Comment by lewing** [comment]
The proper fix here appears to be to properly subclass a JSWebSocket from HostObject and call close in Dispose there

**Comment by campersau** [comment]
I took a closer look at the code and it looks like there was an attempt to call `CloseAsync` in `Dispose` by
cancelling this `CancellationTokenSource`
https://github.com/mono/mono/blob/1317cf06da06682419f8f4b0c9810ad5d5d3ac3a/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L314-L316

for which an `AbortRequest` callback got registered in `ConnectAsyncJavaScript`

https://github.com/mono/mono/blob/1317cf06da06682419f8f4b0c9810ad5d5d3ac3a/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L171-L172

which then tries to call `CloseAsync`

https://github.com/mono/mono/blob/1317cf06da06682419f8f4b0c9810ad5d5d3ac3a/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L340-L348

But this somehow does not work correctly.
I have also tried to use the `ClientWebSocket` in Blazor directly and can confirm that calling just `Dispose` does not close the websocket connection but calling `CloseAsync` directly does.
In addition I have also tried out `Abort` which internally calls `Dispose` and this also does not close the websocket connection.
https://github.com/mono/mono/blob/1317cf06da06682419f8f4b0c9810ad5d5d3ac3a/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L448-L458

```razor
@using System.Net.WebSockets
@using System.Threading

<button @onclick="Connect">Connect</button>
<button @onclick="Close">Close</button>

@code {

    private ClientWebSocket webSocket;

    private async Task Connect()
    {
        webSocket = new ClientWebSocket();

        await webSocket.ConnectAsync(new Uri("ws://websocketserver/"), CancellationToken.None);
    }

    private async Task Close()
    {
        // this will close the websocket
        //await webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Closing", CancellationToken.None);

        // this does not
        //webSocket.Abort();

        // this does not
        webSocket.Dispose();
    }

}
```

**Comment by campersau** [comment]
The issue is with this line:
https://github.com/mono/mono/blob/a6707bfeb9bf02b3f665889e0d564d78268ab35e/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L462

Because `CloseAsync` is called from within `Dispose` (see above) the `state` is already set to `disposed` when reaching `ThrowIfNotConnected`
https://github.com/mono/mono/blob/a6707bfeb9bf02b3f665889e0d564d78268ab35e/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L490-L497
