### ISSUE TITLE
Getting a 504-Gateway Timeout Error

### ISSUE THREAD

**Issue by timothygilbertson** [mono/mono#18639]
## Steps to Reproduce

1. Open the Mono Framework Archive.
2. Select any of the folders.
3. Get the error.

### Current Behavior

504-Gateway Timeout Error.

### Expected Behavior

The folders should load with the files necessary.

## On which platforms did you notice this

[x ] macOS
[ ] Linux
[x] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by avboivin** [comment]
Also getting a 504 error when trying to `wget` the packages.
Are the servers temporarily down ?

**Comment by Bhodges94** [comment]
@avboivin  - I managed to install updating the link to: 

https://download.mono-project.com/repo/ubuntu/dists

unsure if it's fully working yet though

**Comment by avboivin** [comment]
Seems the servers are backup now.

**Comment by akoeplinger** [comment]
We had an outage on the download servers that should be resolved now, please open a new issue if it still happens. Thanks :)
