### ISSUE TITLE
Runtime may still throw OverflowException in unchecked context

### ISSUE THREAD

**Issue by Nabile-Rahmani** [mono/mono#18640]
This affects all common language runtimes (Mono, .NET Framework & Core).

![image](https://user-images.githubusercontent.com/15223353/73502359-0df6ff80-43c9-11ea-89fe-bb70e8213134.png)

On x86-based processors, computing `int.MinValue / -1` will make the hardware generate an overflow exception, but the runtime will forward this exception regardless of if we're in an unchecked overflow context.

The C# specifications and MSDN documentation state that unchecked is the default context, and that no overflow exception should occur in this context. This issue manifests itself even with the explicit usage of the `unchecked` keyword and `-checked-` compiler flag. We've confirmed no `ovf` instruction is present in the disassembly.

C# programs assuming no overflow exceptions happen unless `checked` is used will crash when encountering this corner case.

Credits go to https://github.com/PeterLemon/N64/pull/29 for making me aware of this issue.

## Steps to Reproduce

Compile the following sample code (or run it in the `csharp` REPL) and run it on an x86-based machine:

```csharp
static class Program
{
    static void Main()
    {
        var rs = int.MinValue;
        var rt = -1;
        var rd = 0ul;
 
        // Both of these statements trigger the exception.
        rd = unchecked((ulong)(rs / rt));
        rd = unchecked((ulong)(rs % rt));
    }
}
```

### Current Behavior

`OverflowException` is thrown in unchecked contexts.

### Expected Behavior

The runtime checks which overflow context it is in, and doesn't throw the exception if it is unchecked.

## On which platforms did you notice this

- [ ] macOS
- [x] Linux
- [x] Windows

**Version Used**:

`Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:20:06 UTC 2019)`

## Stacktrace

```
System.OverflowException: Arithmetic operation resulted in an overflow.
  at <InteractiveExpressionClass>.Host (System.Object& $retval) [0x00000] in <b67aa04c822243df9deed096478353a0>:0 
  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object& result, System.Boolean& result_set) [0x00038] in <0d152378608d403c93cdd2bf52f259d3>:0 
  at Mono.CSharpShell.Evaluate (System.String input) [0x00000] in <b302e50c0d1a4e6ab9d80adb91e4372b>:0
```

**Comment by 616E64726173** [comment]
@migueldeicaza could you find someone to take a quick look at this? it's a very oddball behavior.

**Comment by EgorBo** [comment]
@Nabile-Rahmani @616E64726173 I believe the answer for this behavior can be found here: https://stackoverflow.com/questions/26594645/why-dividing-int-minvalue-by-1-threw-overflowexception-in-unchecked-context/26595255

**Comment by Nabile-Rahmani** [comment]
I know why it behaves this way: dividing by -1 inverts the sign, and because the minimum value is always 1 more than the maximum value representable, it causes an overflow.

Depending on the architecture, it may generate an exception (like on x86), or not (like on MIPS).

The thing is, if the runtime bothers to forward the hardware exception, it means it can also decide to prevent it from happening if it is in an unchecked context, which is what should be done to comply with the specifications.

See:
- https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf (chapter 12.7.14, page 164)
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/unchecked

**Comment by EgorBo** [comment]
> I know why it behaves this way: dividing by -1 inverts the sign, and because the minimum value is always 1 more than the maximum value representable, it causes an overflow.
> 
> Depending on the architecture, it may generate an exception (like on x86), or not (like on MIPS).
> 
> The thing is, if the runtime bothers to forward the hardware exception, it means it can also decide to prevent it from happening if it is in an unchecked context, which is what should be done to comply with the specifications.
> 
> See:
> 
> * https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf (chapter 12.7.14, page 164)
> * https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/unchecked

in the same spec you linked there is 
```
12.9.3 Division operator

If the left operand is the smallest representable int or long value and the right operand is –1, an
overflow occurs. In a checked context, this causes a System.ArithmeticException (or a subclass
thereof) to be thrown. In an unchecked context, it is implementation-defined as to whether a
System.ArithmeticException (or a subclass thereof) is thrown or the overflow goes unreported
with the resulting value being that of the left operand.
```

So the behavior doesn't violate the spec actually.
I don't think you can just swallow that exception -- you won't be able to calculate the valid value.

**Comment by Nabile-Rahmani** [comment]
Well I'll be damned. Reading the unchecked paragraph makes it seem like there is no way `OverflowException` can be produced (which would make more sense), yet the division paragraph lets it be implementation-defined regardless of context.

That's pretty weird. Though the fact that the computation itself is undefined is not surprising, it's just that throwing an overflow exception in an unchecked context makes little sense.

**Comment by EgorBo** [comment]
Anyway if you want more context on this/have suggestions I'd recommend to file an issue against `dotnet/runtime` or `dotnet/csharplang` repos since it's not mono-specific.
