### ISSUE TITLE
Environment.GetFolderPath throws undocumented exception

### ISSUE THREAD

**Issue by Therzok** [mono/mono#18652]
## Steps to Reproduce

1. Remove read permissions on `~/.config/user-dirs.dirs` 
2. `Environment.GetFolderPath(Environment.SpecialFolder.Templates)`

### Current Behavior

An exception is thrown, but it is not [documented](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=netframework-4.8)

### Expected Behavior

It only throws documented exceptions.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 6.8.0.104 (2019-10/1cca0cfebfc Tue Jan 28 09:49:56 EST 2020)

## Stacktrace

```
System.UnauthorizedAccessException
Access to the path "/Users/$USER/.config/user-dirs.dirs" is denied.

System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,Boolean,FileOptions)
System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,FileOptions)
System.IO.StreamReader..ctor(String,Encoding,Boolean,Int32)
System.IO.StreamReader..ctor(String,Boolean)
System.IO.StreamReader..ctor(String)
System.Environment.ReadXdgUserDir(String,String,String,String)
System.Environment.UnixGetFolderPath(SpecialFolder,SpecialFolderOption)
System.Environment.GetFolderPath(SpecialFolder,SpecialFolderOption)
System.Environment.GetFolderPath(SpecialFolder)
```

**Comment by Therzok** [comment]
Can someone add it to the VSM tracker?

**Comment by steveisok** [comment]
This should be something we can streamline / fix unless there's something historical I don't know about.
