### ISSUE TITLE
Generated application with mkbundle depends libintl.8.dylib

### ISSUE THREAD

**Issue by durswd** [mono/mono#18661]
Hello.

I uses mkbundle to execute an application without mono on other computer.
But generated application with mkbundle depends libintl.8.dylib

## Steps to Reproduce

```
export PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig
export AS="as -arch i386"
export CC="clang -arch i386 -mmacosx-version-min=10.6"

mkbundle -o MyApp MyApp.exe --deps --sdk /Library/Frameworks/Mono.framework/Versions/Current
```

Copy it to other  computer which doesn't contain mono.

./MyApp

### Current Behavior

It causes an error.

```
dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
```

### Expected Behavior

It runs.

## On which platforms did you notice this

[ x ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

6.6.0

**Comment by akoeplinger** [comment]
Could you please try with https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2019-10/107/1cca0cfebfcbd019c6f2bdd3e5b99f769f1e2e0c/MonoFramework-MDK-6.8.0.104.macos10.xamarin.universal.pkg ?

This should be fixed with https://github.com/mono/mono/pull/18531

**Comment by durswd** [comment]
I got other error.

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: /libmono-native-compat.dylib assembly:<unknown assembly> type:<unknown type> member:(null)

**Comment by akoeplinger** [comment]
Ok then the fix from https://github.com/mono/mono/pull/18531 works and what you're seeing is a different issue: https://github.com/mono/mono/issues/16991

Since the original issue was fixed I'm closing this here.
