### ISSUE TITLE
Mono crashes with a SIGSEV

### ISSUE THREAD

**Issue by tyronx** [mono/mono#18677]
I'm working on a PC game and a player has been reporting it crashes in a certain case.

## Steps to Reproduce

1. Download and unpack, sorry its pretty large - https://cdn.vintagestory.at/gamefiles/pre/vs_archive_1.12.0-pre.17.tar.gz
2. Run with "mono Vintagestory.exe", you'll end up in a login screen. Close application again.
3. Open ~/.config/VintageStoryData/clientsettings.json and set glDebugMode to true
4. Run "mono Vintagestory.exe" again. SIGSEV appears for the aformentioned player

## On which platforms did you notice this

Reported to happen on Linux.
Mono Version: Mono 6.4.0 (makepkg/fe64a4765e6 Sat 16 Nov 2019 04:59:42 PM UTC)

## Stacktrace

[message.txt](https://github.com/mono/mono/files/4148896/message.txt)
[mono_crash.0.0.json.txt](https://github.com/mono/mono/files/4148897/mono_crash.0.0.json.txt)

**Comment by lewurm** [comment]
```
Thread 1 (Thread 0x7f8defdd5780 (LWP 72276)):
#0  0x00007f8deffcf256 in waitpid () from /usr/lib/libpthread.so.0
#1  0x0000556dbd3eafa6 in ?? ()
#2  0x0000556dbd3eb151 in ?? ()
#3  0x0000556dbd3961f3 in ?? ()
#4  0x0000556dbd352a17 in ?? ()
#5  <signal handler called>
#6  0x00007f8def6f2720 in ?? ()
#7  0x00007f8de2329108 in ?? () from /usr/lib/libnvidia-glcore.so.440.44
#8  0x00007f8de2329250 in ?? () from /usr/lib/libnvidia-glcore.so.440.44
#9  0x00007f8de2329512 in ?? () from /usr/lib/libnvidia-glcore.so.440.44
#10 0x00007f8de2700b6f in ?? () from /usr/lib/libnvidia-glcore.so.440.44
#11 0x00007f8de27059d9 in ?? () from /usr/lib/libnvidia-glcore.so.440.44
#12 0x00007f8de2303fd7 in ?? () from /usr/lib/libnvidia-glcore.so.440.44
#13 0x00007f8de2306062 in ?? () from /usr/lib/libnvidia-glcore.so.440.44
```
looks like the SIGSEGV comes from a third party library. Does that ring any bell for you?

**Comment by tyronx** [comment]
Oh, wicked. I'll forward it to the player. Thanks for figuring that out. I suppose we can close this issue then, as its not related to mono
