### ISSUE TITLE
[merp] ves_icall_Mono_Runtime_SendMicrosoftTelemetry reports signal SigTerm which conflicts with the actual SigTerm handler

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#18681]
When VSM catches a managed exception and reports it to Watson with MERP, Mono denotes this as a SigTerm as seen here: https://github.com/mono/mono/blob/master/mono/metadata/icall.c#L6527-L6528

This is a problem because now we actually have a SigTerm handler and get real SigTerm reports, and we can't distinguish between them properly with this in place. 

From @kdubau:
I suggest that this icall should instead use a more accurate value for the signal, such as `"SigManaged"` or something of the like? As far as I know this is only a string value to help MERP determine the `MERPExcType` and just needs to be supported here: https://github.com/mono/mono/blob/master/mono/utils/mono-merp.c#L273 and subsequently here: https://github.com/mono/mono/blob/master/mono/utils/mono-merp.c#L241 - something like `MERP_EXC_MANAGED_EXCEPTION` makes sense to me

When we make this change we will *need* to bump the MERP protocol version https://github.com/mono/mono/blob/master/mono/utils/mono-state.h#L21

---

This is https://work.azdo.io/1060870

**Comment by alexischr** [comment]
Closed by https://github.com/mono/mono/pull/18723
