### ISSUE TITLE
Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2019-10/ios/release/mono/mini/mini-arm64.c:2041

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#18689]
## Steps to Reproduce

1. Build and install [xamarin-macios](http://github.com/xamarin/xamarin-macios) from `master` or `d16-5` (I haven't tried earlier branches)
2. Download, extract and build test project: [WatchkitAotcrash2.zip](https://github.com/mono/mono/files/4150507/WatchkitAotcrash2.zip)

```shell
unzip -d WatchkitAotcrash2 WatchkitAotcrash2.zip
cd WatchkitAotcrash2
msbuild /p:Platform=iPhone /p:Configuration=Debug /verbosity:diag MyWatchKit2Extension/*.csproj
```

### Current Behavior

```
  AOT Compilation exited with code 134, command: (TaskId:129)
  MONO_PATH=/Users/rolf/test/WatchkitAotcrash2/MyWatchKit2IntentsExtension/obj/iPhone/Debug/mtouch-cache/3-Build /work/maccore/master/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/bin/arm64_32-darwin-mono-sgen --debug -O=gsharedvt -O=float32 --aot=mtriple=arm64_32-ios,data-outfile=/Users/rolf/test/WatchkitAotcrash2/MyWatchKit2IntentsExtension/obj/iPhone/Debug/mtouch-cache/arm64_32/mscorlib.aotdata.arm64_32,static,asmonly,direct-icalls,full,dwarfdebug,no-direct-calls,direct-pinvoke,outfile=/Users/rolf/test/WatchkitAotcrash2/MyWatchKit2IntentsExtension/obj/iPhone/Debug/mtouch-cache/arm64_32/mscorlib.dll.s /Users/rolf/test/WatchkitAotcrash2/MyWatchKit2IntentsExtension/obj/iPhone/Debug/mtouch-cache/3-Build/mscorlib.dll (TaskId:129)
  Mono Ahead of Time compiler - compiling assembly /Users/rolf/test/WatchkitAotcrash2/MyWatchKit2IntentsExtension/obj/iPhone/Debug/mtouch-cache/3-Build/mscorlib.dll (TaskId:129)
  AOTID 6FC06451-22E0-E6A0-DCF7-25DA2C8D62C8 (TaskId:129)
  * Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2019-10/ios/release/mono/mini/mini-arm64.c:2041 (TaskId:129)
   (TaskId:129)
```

This is the line where it asserts: https://github.com/mono/mono/blob/2edccc52a78d90fea7bcbd37844164663e712397/mono/mini/mini-arm64.c#L2041

### Expected Behavior

Successful build

**Version Used**:

xamarin-macios master or d16-5 (I haven't tried earlier branches)

## Stacktrace

Full build log: https://gist.github.com/rolfbjarne/e152c1fd9d05d279ee9642dd9dd82114

**Comment by marek-safar** [comment]
@vargaz could you please look into this one

**Comment by vargaz** [comment]
This is because of:
#define MONO_ARCH_EMULATE_DIV 1

in mini-arm64.h for the watchos case. I'm not sure thats needed.
@lewurm ?

**Comment by lewurm** [comment]
> This is because of:
> #define MONO_ARCH_EMULATE_DIV 1
> 
> in mini-arm64.h for the watchos case. I'm not sure thats needed.
> @lewurm ?

It is needed for Release, because we use the `armv7k` cross compiler to generate bitcode (which assumes `MONO_ARCH_EMULATE_DIV 1`) and then uses it with a `arm64_32` runtime. It's hacky.

Anyways, Debug uses interpreter-only, thus the AOT compiler only needs to do minimal work there, so I'm surprised we hit that.

**Comment by vargaz** [comment]
So mono_arch_opcode_needs_emulation () decides whenever to really emulate the opcode, not sure what it should return in this case.

**Comment by lewurm** [comment]
The problem is that the AOT compiler is invoked with `--aot=[...],full,[...]` instead of `--aot=[...],interp,[...]`.  Judging from the provided msbuild log file, it only happens for the "Intents" extension, which I don't know what it is, but it seems to be something we have missed when we have initially landed `arm64_32` Debug support in `mtouch`.

Does that make sense @rolfbjarne ?

**Comment by rolfbjarne** [comment]
Turns out I actually fixed this myself earlier this week: https://github.com/xamarin/xamarin-macios/pull/7781.
