### ISSUE TITLE
Aggressive inlining doesn't call static ctor on AOT.

### ISSUE THREAD

**Issue by lateralusX** [mono/mono#18701]
Looks like static ctor's are not run on AOT when using aggressive inlining on a method:

https://github.com/mono/mono/blob/edb18739cb3df898279a952fd70f91a05191c4ef/mono/mini/method-to-ir.c#L3881

https://github.com/mono/mono/blob/edb18739cb3df898279a952fd70f91a05191c4ef/mono/mini/method-to-ir.c#L3889

We will need to inline the init check + call to init method (out of line) to make sure static ctor has been run before executing any of the code for the inlined method.

This will lead to races that can trigger NullReferenceExceptions or other undefined behaviour.

**Comment by lateralusX** [comment]
https://github.com/mono/mono/pull/18706

**Comment by akoeplinger** [comment]
Should be fixed by https://github.com/mono/mono/pull/18706.
