### ISSUE TITLE
TCPListener not working in Blazor Mono wasm

### ISSUE THREAD

**Issue by sps014** [mono/mono#18716]
I need to create HTTP server in blazor wasm
, I am using TCP listeners to create a web server. I am getting a platform not supported error.
How can I get an HTTP web server working on blazor??

I asked the same question on ASP Core they asked me to ask on mono, hence asking here
[Issue on Blazor](https://github.com/dotnet/aspnetcore/issues/18776)

**Comment by sps014** [comment]
Is anyone interested in responding to the issue?

**Comment by vargaz** [comment]
Not an expert, but webassembly apps have the similar restrictions to javascript apps, you can't run tcp servers in a web page.

**Comment by lewing** [comment]
Like @vargaz said, when running inside the browser you are subject to all the normal browser sandbox restrictions which means PlatformNotSupportedException is correct

**Comment by mlbaker171** [comment]
What about on a server app?
