### ISSUE TITLE
gRPC cancellation of an in-progress call is broken in Blazor WebAssembly

### ISSUE THREAD

**Issue by danroth27** [mono/mono#18717]
_From @JamesNK on Wednesday, February 5, 2020 10:05:52 AM_

### Describe the bug
Canceling a gRPC-Web call that has returned headers but has not finished returning a response is broken in Blazor WebAssembly. Cancellation of a `HttpClient` request that has returned headers is done by calling `HttpResponseMessage.Dispose`. This should abort the HTTP request and set ASP.NET Core's `HttpContext.RequestAborted.IsCancellationRequested` to true. It appears that nothing happens currently.

Note that canceling a request that hasn't finished sending response headers (using the `SendAsync(request, ct)` cancellation token) does work.

### To Reproduce
I have a sample that attempts to do Blazor WA server streaming here. Clicking stop will cancel the call with the gRPC client. It calls `HttpResponseMessage.Dispose` internally

Source: https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/blazor-serverstreaming (Blazor sample)

### Further technical details
- Blazor 3.2.0-preview1.20073.1

_Copied from original issue: dotnet/aspnetcore#18817_

**Comment by danroth27** [comment]
_From @javiercn on Wednesday, February 5, 2020 11:17:58 AM_

@SteveSandersonMS @JamesNK I assume one of you will be taking care of this?

**Comment by danroth27** [comment]
_From @campersau on Wednesday, February 5, 2020 12:12:01 PM_

I think the problem is that the HttpResponseMessage is not subclassed to provide the cancellation on dispose functionally via the AbortController.
https://github.com/mono/mono/blob/ab2321c1dc1bf0293dadd7e52436b2bd87f2b7c3/sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs#L169

You can try changing the code and can test it like I have described here: https://github.com/mono/mono/pull/18647

**Comment by danroth27** [comment]
@lewing

**Comment by lewing** [comment]
closed in https://github.com/mono/mono/pull/18647

**Comment by campersau** [comment]
@lewing I don't think that #18647 fixed this becaus this was about websockets and not http.

I have submitted a fix for this issue here #18765

**Comment by lewing** [comment]
agreed

**Comment by JamesNK** [comment]
Users running into this issue - https://twitter.com/J_aa_p/status/1234373766056153089

**Comment by JeepNL** [comment]
@JamesNK Yep, that's me (Jaap) on Twitter. FYI: I used James' Blazor/gRPC [github example](https://github.com/grpc/grpc-dotnet/tree/master/examples/Blazor) for my (live prototype) website: https://openwiki.com - The Static Blazor Client Side (WASM) is hosted with Nginx on Ubuntu 18.04. The Kestrel gRPC service is running on the same server (VPS). You can check there when you stop the counter, the streaming doesn't stop. When you start the counter again, a second stream is added. And so on.
