### ISSUE TITLE
[merp] Add log message/breadcrumb/file with signal type

### ISSUE THREAD

**Issue by kdubau** [mono/mono#18715]
Original issue below.  Going to track the tasks:

- [x] Log a breadcrumb with the crash reason (#19072 - master)
- [x] Add a managed API to extract the crash reason from a directory containing breadcrumbs (not sure about this - @kdubau I think this bit belongs in some library outside the runtime (but kept in sync with the runtime)
- [x] Log a breadcrumb with the stack hash once we know it (#19240)
- [x] Add a managed API to extract the stack hash from a directory containing breadcrumbs (same caveat)

---

Currently MERP logs the crash phase breadcrumb/files during MERP report generation. We use this to measure MERP success rate with VSM telemetry (as seen in https://work.azdo.io/1060810).

However, we do not know what _type_ of report was being generated. It would be helpful if Mono could log the signal type (SigAbrt, SigSegv, SigTerm, SigManaged, etc.) so we can also send via telemetry the _type_  of crash that was being worked on. 

This should happen as early in the `mono_summarize_phase` timeline as possible. 

-----

This is https://work.azdo.io/1062126

**Comment by kdubau** [comment]
@alexischr can we prioritize this first? I hope it shouldn't be too hard and quick to implement so we can get it in VSM 8.5 GA release. This will really help reporting.

**Comment by kdubau** [comment]
@lambdageek @alexischr could we also log the StackHash? In fact, can we just log all the "upload parameters" to a file?

**Comment by lambdageek** [comment]
@kdubau @alexischr I was thinking about how the breadcrumbs are consumed. I wonder if we need a library outside the runtime to look in a directory that may contain breadcrumbs and extract the usable info: crash stage, crash reason, stack hash, etc.

I know the runtime currently has the API that understands the crash level, but I don't think it should be the runtime's job - we should have a standalone managed library and just keep it in sync with the levels that the runtime can produce.

**Comment by kdubau** [comment]
@lambdageek yea, I think you are right. We discussed this recently when the VSMac installer added MERP support, as much of the code to enabled it and consume the breadcrumbs was duplicated. 
cc @Therzok

**Comment by kdubau** [comment]
@lambdageek regarding the managed API being in a library outside the runtime, I definitely agree, but can we track and implement it separately? I suspect to do that right it'll take some additional time. 

Right now, Mono is giving us the breadcrumbs... `crash_hash_0x..` and `crash_reason_abrt` but there is no API to read them. 

VSMac uses this runtime API to get the `crash_stage_#` breadcrumbs: https://github.com/mono/mono/blob/master/mcs/class/corlib/Mono/Runtime.cs#L258

For immediate term, and we add a `CheckCrashReportHash` and `CheckCrashReportReason` ?

cc @Therzok

**Comment by alexischr** [comment]
Done on master and `2020-02`
