### ISSUE TITLE
gRPC server streaming is broken in Blazor WebAssembly

### ISSUE THREAD

**Issue by danroth27** [mono/mono#18718]
_From @JamesNK on Wednesday, February 5, 2020 9:57:20 AM_

### Describe the bug
gRPC server streaming is broken in Blazor WebAssembly because `WasmHttpContent.ReadAsStreamAsync` doesn't return a `Stream` until the response has completed. The .NET gRPC client needs to be able to read messages from the response stream as they are received for server streaming to work.

### To Reproduce
I have a sample that attempts to do Blazor WA server streaming here...

Source: https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/blazor-serverstreaming (Blazor sample)

### Further technical details
- Blazor 3.2.0-preview1.20073.1

_Copied from original issue: dotnet/aspnetcore#18813_

**Comment by danroth27** [comment]
_From @campersau on Wednesday, February 5, 2020 11:09:37 AM_

It might be because streaming is disabled by default here https://github.com/mono/mono/blob/ab2321c1dc1bf0293dadd7e52436b2bd87f2b7c3/sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs#L37

See https://github.com/mono/mono/pull/17328 for reasons.

You can try set it to `true` via reflection.

**Comment by danroth27** [comment]
@lewing

**Comment by JamesNK** [comment]
I can confirm server streaming works if reflection is used to set the hidden `WasmHttpMessageHandler.StreamingEnabled` variable:

```csharp
var wasmHttpMessageHandlerType = System.Reflection.Assembly.Load("WebAssembly.Net.Http").GetType("WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler");
var streamingProperty = wasmHttpMessageHandlerType.GetProperty("StreamingEnabled", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);
streamingProperty.SetValue(null, true, null);
```

As a workaround it works, but we shouldn't make users jump through this hoop. Server streaming should just work.

**Comment by lewing** [comment]
As mentioned in https://github.com/mono/mono/pull/17328 Streaming support is currently disabled by default for compatibility because some libraries do sync reads on the stream (which the browser doesn't support) and the streaming binding doesn't have sync over async emulation.

**Comment by JamesNK** [comment]
What do you recommend gRPC users do at the moment?

Is the real fix here to implement the sync methods on the HTTP request stream?

**Comment by lewing** [comment]
Implementing sync reads in the single threaded browser context is difficult if not impossible.  What may work is making the option per request then using something like the ideas in https://github.com/dotnet/aspnetcore/pull/19253 to allow gRPC users to set enable streaming on the gRPC requests.

**Comment by JamesNK** [comment]
If you enable streaming when a HttpRequestMessage.Property is present then I can change the gRPC client to set that property.

**Comment by kjpou1** [comment]
A way to surface the properties are being discussed and evaluated in the dotnet repo issue:  https://github.com/dotnet/runtime/issues/34168
