### ISSUE TITLE
[wasm] List failing tests and PNSE coverage

### ISSUE THREAD

**Issue by steveisok** [mono/mono#18735]
We need to run the latest round of skipped tests against wasm so that the wasm / blazor teams know what they are and why they are being skipped.  Additionally, we would like to know the areas in the bcl that are throwing PNSE.

- [x] Run skipped tests and gather raw data 
- [x] Construct doc and hand it off to the wasm team.  Might be easiest to throw it into a spreadsheet - format TBD.
- [x] Ensure all skipped tests are throwing PNSE (~75 aren't)
- [x] Scan wasm bcl and gather PNSE coverage data

**Comment by MaximLipnin** [comment]
Current raw output can be extracted from https://github.com/mono/mono/pull/18752

**Comment by MaximLipnin** [comment]
We could close it as completed.
