### ISSUE TITLE
Mono6.6 missing of "libgdiplus0-6.0.4-0.xamarin.1.epel7.src.rpm" on CentOS 7.7

### ISSUE THREAD

**Issue by 29217321** [mono/mono#18768]
Hi there,
I got the error of missing "libgdiplus0-6.0.4-0.xamarin.1.epel7.src.rpm" when I build and install Mono 6.6 from RPM on CentOS 7.7, can some body suggest please? thanks.

Regards

**Comment by directhex** [comment]
```
Running transaction
  Installing : libgdiplus0-6.0.4-0.xamarin.1.epel7.x86_64
```

Sorry, I'm having real trouble reproducing an issue. What are you trying to do, exactly?

**Comment by 29217321** [comment]
The errors are as below:
```
+ echo 'File libgdiplus0-6.0.4-0.xamarin.1.epel7.src.rpm not found'
File libgdiplus0-6.0.4-0.xamarin.1.epel7.src.rpm not found
```
I am using Mono as runtime, and I am building the source files as well of whole components (that include Mono's source). Where can I download this source RPM so that I can include into my source packages together?

**Comment by directhex** [comment]
https://download.mono-project.com/repo/centos7/libg/libgdiplus0/libgdiplus0-6.0.4-0.xamarin.1.epel7.src.rpm ?
