### ISSUE TITLE
SignalR client in Blazor app should throw meaningful exception on connection fail

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#18780]
_From @duracellko on Sunday, February 9, 2020 1:47:26 PM_

### Describe the bug
Using SignalR (Microsoft.AspNetCore.SignalR.Client ver 3.1.1) client in Blazor (3.2.0-preview1.20073.1) application reports wrong exception, when connection fails. `HubConnection.StartAsync()` throws exception:

```text
WebAssembly.JSException:
TypeError: Failed to fetch
at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.doFetch
```

### To Reproduce
1. Follow example from [Blazor WebAssembly 3.2.0 Preview 1 release now available]
(https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/)
2. Change line `.WithUrl(NavigationManager.ToAbsoluteUri("/chatHub"))` in **Index.razor** to not existing URL `.WithUrl("http://localhost:5005/chatHub")`
3. Run application and check console log in browser. There is error: `WASM: WebAssembly.JSException: TypeError: Failed to fetch`

### Actual behavior

There are 2 problems with the exception.

1. `WebAssembly.JSException` is internal type, so it is not possible to catch the specific exception.
2. `TypeError: Failed to fetch` is not very clear error message.

### Expected behavior

I would expect `System.Net.Http.HttpRequestException` or something similar to report that connection was not successful.

### Further technical details
- ASP.NET Core version 3.1.1
- Microsoft.AspNetCore.SignalR.Client: 3.1.1
- Blazor client side:
  - Microsoft.AspNetCore.Blazor: 3.2.0-preview1.20073.1
  - Microsoft.AspNetCore.Blazor.Build: 3.2.0-preview1.20073.1
  - Microsoft.AspNetCore.Blazor.HttpClient: 3.2.0-preview1.20073.1
- `dotnet --info`
```text
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

_Copied from original issue: dotnet/aspnetcore#18914_

**Comment by mkArtakMSFT** [comment]
_From @javiercn on Monday, February 10, 2020 9:41:53 AM_

@duracellko thanks for contacting us.

We believe this issue belongs in the [mono/mono](https://github.com/aspnet/aspnetcore) repo. We will discuss the issue within the team and re-route appropriately.

**Comment by kjpou1** [comment]
The PR above throws System.Net.Http.HttpRequestException.

The outstanding problem of `TypeError: Failed to fetch` is not under our control.  This is the actual error returned by the javascript fetch API.  The actual message is output to the javascript console and not able to catch the actual error.  The same result using plain javascript.

**Comment by duracellko** [comment]
That was my expectation. JSException wrapped in HttpRequestException.
