### ISSUE TITLE
[loader] Adjust loader logging to debug level where appropriate

### ISSUE THREAD

**Issue by grendello** [mono/mono#18795]
With `MONO_LOG_LEVEL=info` (the default in Xamarin.Android) Mono runtime produces a lot of output in logcat:

```
02-11 17:35:56.821  5996  5996 D Mono    : Image addref mscorlib[0xe6802ec0] (asmctx DEFAULT) -> mscorlib.dll[0xf1272300]: 2
02-11 17:35:56.821  5996  5996 D Mono    : Prepared to set up assembly 'mscorlib' (mscorlib.dll)
02-11 17:35:56.821  5996  5996 D Mono    : Config attempting to parse: 'mscorlib.dll.config'.
02-11 17:35:56.821  5996  5996 D Mono    : Config attempting to parse: '/mnt/jenkins/workspace/archive-mono/2019-12/android/debug/sdks/out/android-x86-debug/etc/mono/assemblies/mscorlib/mscorlib.config'.
02-11 17:35:56.831  5996  5996 D Mono    : Assembly mscorlib[0xe6802ec0] added to domain RootDomain, ref_count=1
02-11 17:35:56.831  5996  5996 D Mono    : Image addref SmartHotel.Clients.Android[0xe6802f80] (asmctx DEFAULT) -> SmartHotel.Clients.Android.dll[0xf1272d00]: 2
02-11 17:35:56.831  5996  5996 D Mono    : Prepared to set up assembly 'SmartHotel.Clients.Android' (SmartHotel.Clients.Android.dll)
02-11 17:35:56.831  5996  5996 D Mono    : Assembly SmartHotel.Clients.Android[0xe6802f80] added to domain RootDomain, ref_count=1
02-11 17:35:56.831  5996  5996 D Mono    : Config attempting to parse: 'SmartHotel.Clients.Android.dll.config'.
02-11 17:35:56.831  5996  5996 D Mono    : Config attempting to parse: '/mnt/jenkins/workspace/archive-mono/2019-12/android/debug/sdks/out/android-x86-debug/etc/mono/assemblies/SmartHotel.Clients.Android/SmartHotel.Clients.Android.config'.
02-11 17:35:56.831  5996  5996 D Mono    : Image addref Acr.UserDialogs[0xe6802fe0] (asmctx DEFAULT) -> Acr.UserDialogs.dll[0xf1273200]: 2
02-11 17:35:56.831  5996  5996 D Mono    : Prepared to set up assembly 'Acr.UserDialogs' (Acr.UserDialogs.dll)
02-11 17:35:56.831  5996  5996 D Mono    : Assembly Acr.UserDialogs[0xe6802fe0] added to domain RootDomain, ref_count=1
02-11 17:35:56.844  5996  5996 D Mono    : Requesting loading reference 0 (of 8) of Mono.Android.dll
02-11 17:35:56.844  5996  5996 D Mono    : Loading reference 0 of Mono.Android.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
```

Most of those messages shouldn't be `info` level but rather `debug`.  Potentially the only valuable `info` level message is the last line in the excerpt above (but **just** for reference no. 0). Xamarin.Android runtime initializes Mono in a single thread and each call to post a message in Android logger's queue is, effectively, synchronous, negatively affecting the startup performance (the exact impact is unknown, but with hundreds of messages printed it can reach millisecond levels and milliseconds is what we're trying to gain :D). It would be nice if the loader logging was reviewed and reduced to `debug` severity where appropriate.

Full startup log (for Debug build of the [SmartHotel360](https://github.com/microsoft/SmartHotel360-Mobile/) sample) is attached. /cc @CoffeeFlux 
[log.txt](https://github.com/mono/mono/files/4186954/log.txt)

**Comment by lambdageek** [comment]
@grendello Why is reference 0 special?

**Comment by grendello** [comment]
@lambdageek it's because `0` means that's it's the first time the assembly is referenced, all the other instances are redundant for that particular assembly.

**Comment by lambdageek** [comment]
That's not what "loading reference 0" means.

If assembly A uses types from assemblies B and C, then A has 2 references.  When we load "B" on behalf of A we will print
```
  Loading reference 0 of assembly A looking for B
```
when we load C on behalf of A, we will print
```
  Loading reference 1 of assembly A looking for C
```

**Comment by grendello** [comment]
OK then, let's rephrase it - "whenever the first time this particular assembly is loaded". The application won't change over time and there's going to be just a single instance of the assembly, so no need to mention it more than once.
