### ISSUE TITLE
codesigned mkbundled executable never ends with xmonkeysloveplay

### ISSUE THREAD

**Issue by shinya-terasaki** [mono/mono#18826]
## Steps to Reproduce

1. create a self-contained application with mkbundle e.g. console app
2. codesign the self-contained application
3. run the signed app, but it shows mono usage

### Current Behavior

The codesigned application shows mono usage.

### Expected Behavior

The codesigned application runs as the same behavior as the mkbundled application.

According to the source code, mkbundled executable is expected to be terminated with `xmonkeysloveplay`.
https://github.com/mono/mono/blob/master/mono/mini/main.c#L182

However after codesigning, the executable is terminated with code signature. So it doesn't end with `xmonkeysloveplay` anymore.

I supposed to relocate code signature section by tweaking the binary, but it will break the signature verification. (I haven't tried though)

Possible solution would be to refer only string table section of the executable to find `xmonkeysloveplay`.

I appreciate any tentative solution to avoid the problem. Since codesign is required for notarization. Because of technical reason (to avoid app from crash), I need to use mkbundle.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
5.2.0, but it should happen on recent version too.

## Stacktrace
No stacktrace since it is expected behavior according to the source code.

```
Please paste the stack trace here if available.
```

**Comment by HinTak** [comment]
@migueldeicaza - can you please review this and see if this is appropriate to add to the loader code? I am having trouble cross-compile the whole of mono for mac os x, so I took the middle part of probe_embeded() from mono/mini/main.c and wrote a small wrapper around it for testing.

It needs two pairs of "#ifdef __APPLE__" "'#endif", for other platforms, but I can polish this and submit a pull request.  

[mono-mini-main-codesign.diff.txt](https://github.com/mono/mono/files/4450188/mono-mini-main-codesign.diff.txt)

I use this script ( see https://github.com/mono/mono/issues/17881 ) to adjust the binary first; ideally this should be done by mkbundle : 

[mono-codesign-fix.py.txt](https://github.com/mono/mono/files/4450249/mono-codesign-fix.py.txt)

**Comment by HinTak** [comment]
@migueldeicaza by the way, I chose to look up the end of the symtab section rather than just before  the beginning of the code signature section, because it looks like apple can pad the symtab section to the next 8-byte boundary - comparing the unsigned and signed binary, there are 4 extra bytes of nulls after "xmonkeysloveplay" (plus changes in the headers). I can write a proper log entry for the patch if that is okay.
