### ISSUE TITLE
[interpreter] make `MonoEEMode` useable for embedders

### ISSUE THREAD

**Issue by lewurm** [mono/mono#18893]
Currently an embedder can't use interpreter-only in an official way, except with hacks
1. make `mono_use_interpreter` extern and set that to true.
2. call `mono_jit_set_aot_mode (1000);` which is the constant used for `MONO_EE_MODE_INTERP`

or by using the FullAOT mode (as done on iOS), which however requires some AOT machinery to precompile needed trampolines/wrappers by the interpreter.

_Originally posted by @lewurm in https://github.com/mono/mono/pull/18855/review_comment/create_

**Comment by lambdageek** [comment]
This was fixed by https://github.com/mono/mono/pull/20159 which added `MONO_AOT_MODE_INTERP_ONLY` which is a distinct value from `MONO_AOT_MODE_LAST = 1000` and is used for `MONO_EE_MODE_INTERP`

**Comment by lambdageek** [comment]
Successfully used the new MONO_AOT_MODE_INTERP_ONLY in an embedder (XA).
