### ISSUE TITLE
Mac installation uses wrong permissions

### ISSUE THREAD

**Issue by yb66** [mono/mono#18901]
Good morning,

## Steps to Reproduce

1. Install via the [pkg](https://download.mono-project.com/archive/6.8.0/macos-10-universal/MonoFramework-MDK-6.8.0.105.macos10.xamarin.universal.pkg) downloaded via the **Download Mono 6.8.0 (Stable channel)** link on https://www.mono-project.com/download/stable/
2. Look at the permissions
3. Realise they're wrong, maybe because you get a host of errors pop up in a new terminal. If you don't, you're running an admin level account.

### Current Behavior

The installer places the `/etc/paths.d/mono-commands` and `/Library/Frameworks/Mono.framework` into the system with permissions of 700 when they should be 755.

I don't mean to sound harsh _but_ not developing/building things under an admin account is pretty basic, the build process needs a look.

### Expected Behavior

That the permissions are 755 (like every other framework placed in `/Library/Frameworks`, 3rd party or not), and hence, non-admin accounts aren't faced with errors caused by the paths.d file read and the framework is accessible and loaded into the PATH correctly.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.8.0.105 (2019-10/82fffe07497 Tue Feb  4 10:09:51 EST 2020)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by lambdageek** [comment]
Hi @yb66 thanks for the bug report.

I just deleted the Mono files (path.d/mono-commands and all of Mono.framework) and re-installed 6.8.0.105 and this is what I see:

```
$ ls -l /etc/paths.d/mono-commands
-rw-r--r--  1 root  wheel  61 Feb 17 21:31 /etc/paths.d/mono-commands
$ ls -ld /Library/Frameworks/Mono.framework
drwxr-xr-x  8 root  admin  256 Feb 17 21:31 /Library/Frameworks/Mono.framework
```

This is with Catalina (10.15.3)

What version of macos are you on?
Are you installing the package by double-clicking on the pkg, or using `pkgutil` or `installer`?  Or was the new version of Mono installed by the VSMac updater?  Did oyu have any previous versions of Mono installed - either via a previous pkg or via `brew`?

**Comment by yb66** [comment]
Hi @lambdageek,

Thanks for the prompt response and forgive me for the grumpy tone of my initial post, it's been one of those weeks, my sincere apologies.

Mac OS is version 10.14.6

I let the pkg automatically open on download using the `Installer`. I run an unprivileged account and let the system prompt to nudge me for admin rights during the install.

I haven't used Mono in, I don't know, 10+ years? (Glad to see it's going strong, btw). The likelyhood it's on this laptop prior to today is low, but I suppose it's possible. There is only 6.8.0 (and Current, obviously) in `/Library/Frameworks/Mono.framework/Versions` though.

I have installed (for the first time) and opened Visual Studio Code today too. I don't know if that's related.

I just removed the framework and paths.d and reinstalled the same way:

```
$ l /Library/Frameworks/Mono.framework                                  
ls: cannot read symbolic link '/Library/Frameworks/Mono.framework/Home': Permission denied
ls: cannot read symbolic link '/Library/Frameworks/Mono.framework/Libraries': Permission denied
ls: cannot read symbolic link '/Library/Frameworks/Mono.framework/Headers': Permission denied
ls: cannot read symbolic link '/Library/Frameworks/Mono.framework/Mono': Permission denied
ls: cannot read symbolic link '/Library/Frameworks/Mono.framework/Commands': Permission denied
total 0
drwxr-xr-x  8 root 256 Feb 18 12:30 .
drwxr-xr-x 16 root 512 Feb 18 12:30 ..
lrwx------  1 root  55 Feb 18 12:30 Commands
lrwx------  1 root  59 Feb 18 12:30 Headers
lrwx------  1 root  52 Feb 18 12:30 Home
lrwx------  1 root  55 Feb 18 12:30 Libraries
lrwx------  1 root  73 Feb 18 12:30 Mono
drwxr-xr-x  4 root 128 Feb 18 12:30 Versions
```

```
$ l /etc/paths.d 
total 20K
drwxr-xr-x   7 root   224 Feb 18 12:30 .
drwxr-xr-x 136 root  4.3K Feb 14 12:43 ..
-rw-r--r--   1 root    27 Jan 24  2018 10-pkgsrc
-rw-r--r--   1 iainb   14 Mar  8  2018 15-macports
-rw-r--r--   1 root    23 Jun  4  2018 MacGPG2
-rw-r--r--   1 root    17 Feb 17  2018 go
-rw-------   1 root    61 Feb 18 12:30 mono-commands
```

```
$ installer -vers
	Command line installer (installer) v. 1.5.0
```

```
$ sudo /Library/Frameworks/Mono.framework/Commands/mono --version
Password:
Mono JIT compiler version 6.8.0.105 (2019-10/82fffe07497 Tue Feb  4 10:09:51 EST 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

Anything else I can do, just let me know.

Regards,
iain

**Comment by lambdageek** [comment]
@yb66 What do you mean by " I run an unprivileged account and let the system prompt to nudge me for admin rights during the install."?

Less privilege than in the screenshot below?

![Screen Shot 2020-02-18 at 14 21 57](https://user-images.githubusercontent.com/480437/74770497-5f710c80-525a-11ea-94bc-e2c55547e491.png)

**Comment by yb66** [comment]
Aleksey,

Yes, I run 2 accounts: a standard user account and an admin account, the standard user is my everyday account and I increase privileges as needed. During the install I’m prompted for admin credentials, which I provide. It’s the principle of least privilege.

Regards, 
iain

**Comment by akoeplinger** [comment]
I tried with a standard user account and can't reproduce the issue on my macOS 10.14 machine. After installation the permissions are what we expect (755).

Do you happen to have any other non-standard configuration or security settings that might affect this?

**Comment by yb66** [comment]
Hi @akoeplinger,

> Do you happen to have any other non-standard configuration or security settings that might affect this?

I'd need a hint as to what they could be because I'm stumped. I run the pkg, it asks for my admin credentials, I give them and it installs. Running as a standard user isn't non-standard, it's best practice.

> After installation the permissions are what we expect (644 on /etc/paths.d/mono-commands).

What permissions do you have for `/Library/Frameworks/Mono.framework`? Upon installation it's the only framework on my system in /Library or /System with a 700.

I've checked the [postinstall script](https://github.com/mono/mono/blob/72fe53a2ee79563a8b25875415d78eeb4abbe250/packaging/MacSDK/packaging/resources/postinstall#L118) (and locally by expanding the package, just in case) and the closest it gets to touching the permissions is the `chown` on the last line. Can't see why it'd be a bad thing to be explicit about the permissions you'd want with a `chmod` too.

Regards,
iain

**Comment by akoeplinger** [comment]
> Running as a standard user isn't non-standard, it's best practice.

Yes and I didn't mean to imply the contrary, using a standard user account should work :)
I was trying to figure out if there are any special settings that aren't used out of the box like setting a custom `umask`: https://support.apple.com/el-cy/HT201684

> What permissions do you have for /Library/Frameworks/Mono.framework? Upon installation it's the only framework on my system in /Library or /System with a 700.

I get 755 here.

> Can't see why it'd be a bad thing to be explicit about the permissions you'd want with a chmod too.

Yeah but we should first try to understand what exactly happened here. It's the first report of this issue I'm aware of in over a decade of shipping the Mono .pkg.

**Comment by yb66** [comment]
> Yes and I didn't mean to imply the contrary, using a standard user account should work :)

Sure, didn't mean to imply any implication :)

> I was trying to figure out if there are any special settings that aren't used out of the box like setting a custom umask

Well, you've hit a winner. I set a custom umask for system and *completely* forgot I'd done it. You can close the issue while I find a corner to hide in from embarrassment.

Thanks for the help. If you need any help with a bit of drudgery like bug triage or something, let me know, it'll salve my conscience.

Regards,
iain

**Comment by akoeplinger** [comment]
Haha no worries, glad you figured it out 🎉
