### ISSUE TITLE
[merp] StackHash upload parameter not calculated with native frames

### ISSUE THREAD

**Issue by kdubau** [mono/mono#18941]
## Steps to Reproduce

1. Create a console app
2. Enable MERP
3. Deadlock two foreground threads (not the main thread)
4. Run it and force quit

### Current Behavior

You get a MERP report with `"StackHash" : "0x0"` .. 

https://gist.github.com/kdubau/21f6de69482619b62ffa0fd5eb9740df#file-gistfile1-txt-L576

### Expected Behavior

The main thread (which caught the sigterm) has native frames, so I would not expect the hash *not* to be 0x0. I suspect only managed frames are considered for the hash (because in this case the crashing thread has no managed frames)?

**Version Used**:

(6.8.0.104) (2019-10/1cca0cfebfc) 

## MERP report

https://gist.github.com/kdubau/21f6de69482619b62ffa0fd5eb9740df

**Comment by alexischr** [comment]
Fixed by https://github.com/mono/mono/pull/18943
