### ISSUE TITLE
Mono not updating Settings.Default

### ISSUE THREAD

**Issue by w4mmp** [mono/mono#18950]
Hello,
Mono  on a Raspberry PI 4B running Raspbian Buster will not keep variables values stored in Settings.Default.  
Below is the contents of user.config:
mscc@multus:~/.local/share/Multus/mscc.exe_Url_d4ff23de252129dffedba9c27162653fd157563a
 $ more user.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <userSettings />
</configuration>
mscc@multus:~/.local/share/Multus/mscc.exe_Url_d4ff23de252129dffedba9c27162653fd157563a $

I have placed Settings.Default.Save() in multiple places within the code (when the application starts, withing a timer (1 second interval) and when the application stops.  None this has the effect of Mono storing the Settings.Default.{variable name} in the user.config file. 

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:

ron@multus:~ $ mono -V
Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:51:48 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
ron@multus:~ $ 

-->

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by pischky** [comment]
I have same issue (I guess). I have a application created with VS2008 (.net 3.5) using user settings. It runs fine on Windows Win7 with .net 3.5. Settings are saved and restored. When I run on ubuntu 16.04. LTS with latetest mono installation (from yesterday) no settings are restored. I do not see any exception thrown. Will try to add sample code today.

**Comment by pischky** [comment]
Finde here attached a simple console application that shows the problem. Output on windows and linux are includes in files output.*.test in zip file.

Short summery:
In Main:
```
String currentValue = Settings.Default.TheSetting;
Console.WriteLine("currentValue=" + currentValue);
String newValue = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");
Console.WriteLine("newValue=" + newValue);
Settings.Default.TheSetting = newValue;
Settings.Default.Save();
```
Output on windows changes on every run:
```
>SettingsBugTest.exe
currentValue=theValue
newValue=2020-02-20 09:20:12
>SettingsBugTest.exe
currentValue=2020-02-20 09:20:12
newValue=2020-02-20 09:20:17
>SettingsBugTest.exe
currentValue=2020-02-20 09:20:17
newValue=2020-02-20 09:20:20
>
```

Output on linux did not change:
```
$ mono SettingsBugTest.exe
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
currentValue=theValue
newValue=2020-02-20 09:44:56
$ mono SettingsBugTest.exe
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
currentValue=theValue
newValue=2020-02-20 09:45:01
$ 
```

[SettingsBugTest.zip](https://github.com/mono/mono/files/4230059/SettingsBugTest.zip)

I'm new to mono so I do not know haw to debug. Is there any other way I can help to fix this?

**Comment by w4mmp** [comment]
Hello Martin,
Thanks much for the test program.  Hopefully the Mono folks will take a look at this and provide a fix. I have about 30 variables maintained in Settings.Default.  I really don't want to create a routine to store these variables in an external storage file.
Regards,
Ron

**Comment by w4mmp** [comment]
Hello,
Is anyone looking at these issue, or is Mono dead?

**Comment by w4mmp** [comment]
Hello,
It is now April 4, 2020.   Please will someone respond?
