### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException, Could not load type of field 'Microsoft.Owin.Security.DataProtection.DpapiDataProtector:_protector' 

### ISSUE THREAD

**Issue by MelihSevsay** [mono/mono#19008]
using System.Configuration;
using System.Net.Http.Formatting;
using System.Text;
using System.Web.Http;
using Microsoft.IdentityModel.Tokens;
using Microsoft.Owin;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Jwt;
using Owin;

[assembly: OwinStartup(typeof(Api.Hosting.Startup))]
namespace Api.Hosting
{
    public class Startup
    {

        public void Configuration(IAppBuilder app)
        {

            var tokenFromConfig = ConfigurationManager.AppSettings["SecretTokenKey"];
            app.UseJwtBearerAuthentication(
                new JwtBearerAuthenticationOptions
                {
                    AuthenticationMode = AuthenticationMode.Active,
                    TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidateIssuer = false,
                        ValidateAudience = false,
                        ValidateIssuerSigningKey = true,

                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII
                            .GetBytes(tokenFromConfig))
                    }
                });
        }

    }

}

I want to use simple UseJwtBearerAuthentication with AspNet WebApi2  in mono, but i am having following error;

Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'Microsoft.Owin.Security.DataProtection.DpapiDataProtector:_protector' (0) due to: Could not resolve type with token 0100000a from typeref (expected class 'System.Security.Cryptography.DpapiDataProtector' in assembly 'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Security.Cryptography.DpapiDataProtector member:(null)

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**: 6.8

What is going wrong? how could i make it work?
Thanks.

**Comment by rjvdboon** [comment]
You'll have to implement your own IDataProtectionProvider and set it as the data protection provider in your Startup class' `public void Confirugation(IAppBuilder app)` method:
```
using Microsoft.Owin.Security.DataProtection;
internal class Startup {
  public void Configuration(IAppBuilder app) {
    app.SetDataProtectionProvider(new CustomDataProtectionProvider(app.GetAppName()));
  }
}
public class CustomDataProtectionProvider : IDataProtectionProvider {
 // Implement IDataProtectionProvider and IDataProtector
}
```

See also https://stackoverflow.com/a/23946374

**Comment by MelihSevsay** [comment]
Hi thank you,
but i am having this error now, How could i solve it ?
I am using Microsoft.Owin.Host.SystemWeb to target my startup.cs, and getting this error.

Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'Microsoft.Owin.Host.SystemWeb.OwinCallContext+<AcceptCallback>d__29:webSocketContext' (2) due to: Could not resolve type with token 01000042 from typeref (expected class 'System.Web.WebSockets.AspNetWebSocketContext' in assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Web.WebSockets.AspNetWebSocketContext member:(null)

Thanks in advance.

**Comment by rjvdboon** [comment]
@MelihSevsay This one I don't know, as I never tried to use WebSockets with Mono. Your best bet might be to convert to Asp.Net Core 2.2 instead (although I've not tried that myself either...).

**Comment by MelihSevsay** [comment]
actually i am just trying to use simple jwtoken authentication for webapi2 end using mono. i just need authentication, if is there any solution about how to cope above problem in mono it will make it.
If there is no solution then i spend more time to convert it to .net core :(
Thanks.

**Comment by rjvdboon** [comment]
@MelihSevsay I don't know if there is a solution. I'm using webapi2 with mono as well, but without any JwtToken or WebSocket usage. As WebApi2 is (as far as I know) not officially supported on Mono you are a bit on your own here. If you do find out though please update the issue with your resolution.

**Comment by MelihSevsay** [comment]
Hi, i have found a way JWT token with webapi2 on mono, 
here is the link, https://github.com/cuongle/WebApi.Jwt
i have implemented this approach to my webapi2 and it works without getting any error :)
