### ISSUE TITLE
ResourceManager loading and keeping all satellite assembly file handles open

### ISSUE THREAD

**Issue by Therzok** [mono/mono#19047]
## Steps to Reproduce

1. Open VSMac
2. `lsof -p` on the instance

### Current Behavior

All the satellite assemblies (all cultures) are opened and have a file handle used.

### Expected Behavior

Only active culture is loaded.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 6.10.0.77 (2019-12/cec38fcfc83 Wed Feb 19 08:17:48 EST 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Stacktrace

Example `lsof -p` https://gist.github.com/netonjm/19916caf0713c486b326138eaa664aaa

**Comment by Therzok** [comment]
To expand a bit further on the implications, as more and more extensions and integrated assemblies start using ResX for localization, this ends up with 13 different satellite assemblies for each shipped assembly.

Due to file handle limits on macOS (256, which we bump to 1024), this will end up exhausting our handle space pretty quickly.

In example, in the gist above, during startup we already load 39 of them (3% of total).

**Comment by Therzok** [comment]
As a note, we do set Thread.CurrentThread.CurrentUICulture to a specific culture on startup.

**Comment by mdh1418** [comment]
@Therzok Would you happen to have a simple sample app that encounters this issue? We haven't been able to reproduce the satellite assemblies loading outside of VSMac.

**Comment by Therzok** [comment]
I've just tried to create a sample app, and the self contained app behaviour is fine.

I'll have to check if anything on our side is force loading these assemblies. I know of some scenarios where we do (i.e. Unity has runtime imports for that) but for example, we have nothing triggering loads of the analyzers localization resources.

**Comment by Therzok** [comment]
Okay, confirming that Mono is behaving properly. VSMac extensions and somehow analyzers from nuget are force loading the satellite assemblies. I did not expect the former to be the case, but I've got proof now that it is a problem in vsmac/extensions.

Will close this issue, thanks for double checking this!
