### ISSUE TITLE
Inheriting references from other domains

### ISSUE THREAD

**Issue by Jacellen** [mono/mono#19042]
The problem is that if I create a new domain №2 and load the assembly into it, then when downloading it complains about the absence of dll links, although the dll links are already loaded into domain №1. Can I take them from existing domains without load from the file?

**Comment by Jacellen** [comment]
Here is an example: 2 assemblies are loaded in 2 different domains, but when vkauth accesses userdata it again loads it from a file, not from a domain

[https://imgur.com/a/f8GIoeM](IMGUR)

**Comment by lambdageek** [comment]
Hi @Jacellen, here is how I understood your question:

1.  You have a domain Domain1 that loaded assembly A.dll
2.  You create a new domain Domain2 that loads assembly B.dll.  The code in assembly B.dll has references to code that should come from A.dll
3.  You would like to know if there is a way for Domain2 to avoid trying to load B.dll itself and to somehow point at A.dll that was already loaded in Domain1.

The answer is that this is not possible.   Each domain loads assemblies independently.

(This is not the complete story - internally if mono sees that both Domain1 and Domain2 are trying to find A.dll in the exact same location on disk, it will share some of the resources for the two copies of A.dll under some circumstances.)

**Comment by Jacellen** [comment]
@lambdageek thanks for the answer! I chose for my project a solution to calling methods and so on through reflection

> public(bool, string) Call(string name, params object[] args) {
    if (Assembly == null) return (false, "fail load plugin");
    foreach(var type in Assembly.GetTypes())
    foreach(var method in type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic |
        BindingFlags.Instance | BindingFlags.Static)) {
        var methodName =
            (MethodNameAttribute) Attribute.GetCustomAttribute(method, typeof(MethodNameAttribute));
        if (methodName == null || methodName.Name != name) continue;
        method.Invoke(method, args);
        return (true, string.Empty);
    }
    return (false, $ "not found {name}");
}

Thus, I completely got rid of the links and can freely unject and inject my plugins
