### ISSUE TITLE
[wasm] OutOfMemory Exception

### ISSUE THREAD

**Issue by MontoyaTech** [mono/mono#19061]
Hello,

I was trying a few benchmarks for the mono wasm sdk and ran into the following snippet that does not run as expected. I'm wondering if I'm doing something wrong or if there is a setting I should be checking. Either way, I would love to learn more about why I'm getting an out of memory exception.

Thanks!

## Steps to Reproduce

1. Using the latest Mono Wasm SDK run the following code snippet in AOT or Interpretation mode
<pre>
            while (true)
            {
                Console.WriteLine("Allocating 256mb..");
                var temp = new byte[1024 * 1024 * 256];
                temp[0] = 7;
                temp[7] = 7;

                temp = null;

                GC.Collect();
            }
</pre>
2. 
3. 

### Current Behavior
Currently an out of memory exception is thrown. It appears a 2GB or 1GB limit is enforced even though the host system has 32GB of ram available.

<pre>
Uncaught (in promise) Error: System.OutOfMemoryException: Insufficient memory to continue the execution of the program.

    at Object.call_method (dotnet.js:7088)
    at Object.call_static_method (dotnet.js:7152)
    at Object.init ((index):4)
    at runtime.js:10
    at dotnet.js:6327
dotnet.js:1998 L: GC_MAJOR_SWEEP: major size: 608K in use: 53K
dotnet.js:1998 L: GC_MAJOR: (LOS overflow) time 651.61ms, stw 651.66ms los size: 0K in use: 0K
</pre>

![image](https://user-images.githubusercontent.com/48062411/75421828-fd667600-58ef-11ea-9bd5-9cbde53296c4.png)

### Expected Behavior

The code snippet should not have ran out of memory, on Windows using .Net Framework (No WASM) this snippet runs just fine.

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[x] Windows

**Version Used**:

Latest version of mono and wasm sdk.

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by kjpou1** [comment]
2GB is a webassembly limit as per emscripten: https://github.com/emscripten-core/emscripten/issues/6566#issuecomment-391120333

> In theory there should be no limit, but in practice, 2GB is a practical limit because many (all?) browsers apply that limit, in particular I know Chrome and Firefox do.

> This should get fixed eventually once browsers get around to it. First, 2GB => 4GB is just a bugfix they need to do. Second, wasm64 will allow accessing more than 4GB by design.

There looks to be some recent work going on to extend the limits in some browsers.
