### ISSUE TITLE
Print array

### ISSUE THREAD

**Issue by cup** [mono/mono#19073]
I can create a program like this:

~~~cs
using System;
class App {
   static void Main() {
      string[] a1 = {"sun", "mon tue"};
      Console.WriteLine(a1);
   }
}
~~~

but it doesnt give expected output:

~~~cs
System.String[]
~~~

Other languages work as expected, like Go:

~~~go
package main
import "fmt"
func main() {
   a1 := []string{"sun", "mon tue"}
   fmt.Printf("%q\n", a1)
}
~~~

Nim:

~~~nim
var a1 = ["sun", "mon tue"]
echo a1
~~~

D:

~~~d
import std.stdio;
void main() {
   auto a1 = ["sun", "mon tue"];
   a1.writeln;
}
~~~

Python:

~~~py
a1 = ['sun', 'mon tue']
print(a1)
~~~

PHP:

~~~php
$a1 = ['sun', 'mon tue'];
var_export($a1);
~~~

**Comment by akoeplinger** [comment]
This is because Array doesn't override the `ToString()` method so the object base class falls back to returning `GetType()`.

Changing this now would probably break countless applications so I doubt it would be changed at this point. You can file an issue on https://github.com/dotnet/runtime if you want to try 😄 

The equivalent code in C# would be `Console.WriteLine(String.Join(Environment.NewLine, a1))`

**Comment by cup** [comment]
@akoeplinger that would fail if one of the element contains a newline...

**Comment by akoeplinger** [comment]
It wouldn't fail, it would just print the additional newline as well and that's the same as in all the other languages.

**Comment by cup** [comment]
@akoeplinger no, its not the same as other languages.

A more correct statement would be "using join with newline, when one of the elements contains a newline, will produce the same result in C# as other languages"

buts thats not what my original examples do. they dont join an array. in each and every example, they unambiguously print the array, so that regardless of the input, you can differentiate between an element an a separator.

**Comment by akoeplinger** [comment]
yeah I see your point but there's nothing we can do about it here :) As I said if you want a better Array.ToString() then you should propose that over in https://github.com/dotnet/runtime.

**Comment by cup** [comment]
@akoeplinger thanks for you time. I did post to dotnet/runtime back in december, but feedback was neutral to strongly negative, even if implement in a backward compatible way (new method).

I dont want to bother you much more, but I will ask do any other C# runtime exist? That might be a better option for me then dealing with DotNet politics.

**Comment by akoeplinger** [comment]
Mono and .NET Core are the only two relevant runtimes. Both are open-source so you can always fork them and implement the behavior you want :)

**Comment by cup** [comment]
That is confusing. You say 2 runtime exist, but you say I most post this issue
to the dotnet runtime.

Why cant I post issue to the Mono runtime, and if so, where would that be.
Here?

**Comment by akoeplinger** [comment]
There's some historical details about Mono vs. NET (you can read about it on Wikipedia and elsewhere) but nowadays the overall roadmap for .NET is driven by dotnet/runtime.
