### ISSUE TITLE
Some files missing when debugging Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [mono/mono#19099]
_From @danroth27 on Saturday, August 24, 2019 8:44:18 PM_

When I debug a Blazor WebAssembly app using the latest preview9 build I see a view in the browser dev tools of the files in my project, but some of the files appear to be missing:

![image](https://user-images.githubusercontent.com/1874516/63642517-3558dc00-c675-11e9-830b-91c067fdf566.png)

Is there a reason why *Index.razor* or *App.Razor* don't show up?

_Copied from original issue: dotnet/aspnetcore#13417_

**Comment by danroth27** [comment]
_From @mkArtakMSFT on Monday, March 2, 2020 5:15:33 PM_

Closing as this may not apply any more.

**Comment by danroth27** [comment]
_From @danroth27 on Monday, March 2, 2020 5:20:07 PM_

It still applies. Here are the files that show up with our latest builds:

![image](https://user-images.githubusercontent.com/1874516/75700473-f8465580-5c66-11ea-9b2b-a294b5d0bc9d.png)

**Comment by lewing** [comment]
I suspect that this is happening because there are no sequence points in the pdb for these methods but we should verify that this is the case

**Comment by danroth27** [comment]
I think we concluded this was by design, so closing.
