### ISSUE TITLE
The Mono Linker strips methods that are used via reflection

### ISSUE THREAD

**Issue by akorchev** [mono/mono#19194]
A continuation of https://github.com/mono/mono/issues/12917.

## Steps to Reproduce

1. Install .NET Core 3.1.102
2. Clone https://github.com/akorchev/blazor-wasm-datagrid
3. Publish in production `dotnet publish -c Release`
4. Go to the output directory `cd Server/bin/Release/netcoreapp3.1/publish/`
5. Run `dotnet blazor-wasm-datagrid.Server.dll`
6. Open `https://localhost:5001` and click on a header of the DataGrid.

![blazor-wasm](https://user-images.githubusercontent.com/454726/76491188-cd61bb80-6435-11ea-9055-6482203bc02d.gif)

### Current Behavior

Exception is thrown because the Mono linker has stripped code that was used via reflection.

### Expected Behavior

The code is not stripped and the application runs as in development mode.

This application uses Radzen.Blazor which in turn relies on https://github.com/StefH/System.Linq.Dynamic.Core to create expression trees from strings. System.Linq.Dynamic.Core [uses reflection](https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs#L2434) to do its thing.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[x] Windows

**Version Used**: .NET Core 3.1.102

## Stacktrace

```
System.TypeInitializationException: The type initializer for 'System.Linq.Dynamic.Core.DynamicQueryableExtensions' threw an exception. ---> System.Exception: Specific method not found: All ---> System.InvalidOperationException: Sequence contains no matching element
```

**Comment by marek-safar** [comment]
This is for now by design. Linker is not able to recognize reflection calls and you need to keep the methods manually. One of doing that is using XML descriptors as described at https://github.com/mono/linker#link-xml-file-examples and passing them in.

**Comment by danroth27** [comment]
I've put together a sample on how to embed the XML linker config file into a library here: https://github.com/danroth27/ComponentLibWithXmlLinkerConfig.
