### ISSUE TITLE
Blazor WASM debugging prevents hitting breakpoint in .NET Core server project

### ISSUE THREAD

**Issue by danroth27** [mono/mono#19227]
@lewing @SteveSandersonMS 

Repro steps:

- Use latest VS dogfood build (16.6.0 Preview 2.0 [29913.155.master]) and latest internal Blazor WebAssemby 3.2 Preview 3 build (3.2.0-preview3.20163.13)
- Create an ASP.NET Core hosted Blazor WebAssembly app
- In the Server project set a breakpoint in `WeatherForecastController.Get`
- Hit F5 to run the app in the debugger
- Navigate to the FetchData tab

Expected results:
- Breakpoint hit in `WeatherForecastController.Get`. 

Actual result:
- Execution pauses, but the breakpoint isn't visibly hit in VS

![image](https://user-images.githubusercontent.com/1874516/76694020-a4564c00-662a-11ea-9d11-eda71aff75ba.png)

**Comment by danroth27** [comment]
Closing and reopening VS seemed to fix this problem.

**Comment by lewing** [comment]
@danroth27 can we get the mono versions for both the runtime and debug proxy for this build?  At first glance it seems like a strange case where the managed breakpoint is being set but the frontend isn't recognizing it.

/cc @digeff

**Comment by lewing** [comment]
my best guess is that the breakpoint request is coming in before the scriptParsed event has fired and VS is ignoring the Debugger.breakpointResolved event?

**Comment by steveisok** [comment]
@danroth27 Did you mean to create a client side blazor app?  If not, this probably isn't a wasm issue.

**Comment by danroth27** [comment]
> Did you mean to create a client side blazor app

Yes

**Comment by baulig** [comment]
Where did you get these templates from?  Latest version I could I find doesn't include the stand-alone `WeatherForecastController.cs`.

**Comment by danroth27** [comment]
The Blazor WebAssembly 3.2 Preview 3 builds can be found at https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3.1-blazor/nuget/v3/index.json. But I only saw this particular issue once. I haven't been able to reproduce it with newer builds.

@lewing Unless you think there's something worth investigating here I think we can go ahead and close this issue. If user's report this, we can investigate.
