### ISSUE TITLE
Strange behavior when stepping after stepping (F10) in a Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [mono/mono#19228]
@lewing @SteveSandersonMS 

Repro steps:

- Use latest VS dogfood build (16.6.0 Preview 2.0 [29913.155.master]) and latest internal Blazor WebAssemby 3.2 Preview 3 build (3.2.0-preview3.20163.13)
- Create an ASP.NET Core hosted Blazor WebAssembly app
- In the Client project set a breakpoint in `FetchData.OnInitializedAsync` on the line that makes the HTTP request
- Hit F5 to run the app in the debugger
- Navigate to the FetchData tab
- The breakpoint should hit
- Hit F10 to step after the HTTP request completes

Expected results:
- Step to the next line of code after the breakpoint

Actual result:
- Execution appears to continue. The weather data table is rendered. But then when you try to then browse to a different tab, execution is paused in the NavMenu component:

![image](https://user-images.githubusercontent.com/1874516/76694120-06fc1780-662c-11ea-989c-06d565f3add5.png)

**Comment by lewing** [comment]
@danroth27 @SteveSandersonMS can you let us know what version of the runtime and debug proxy this corresponds to?  @thaystg once we know the versions can you please try to replicate this?

**Comment by lewing** [comment]
This was fixed in https://github.com/mono/mono/pull/19140
