### ISSUE TITLE
Unable to inspect local array values when debugging a Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [mono/mono#19229]
@lewing @SteveSandersonMS 

Repro steps:

- Use latest VS dogfood build (16.6.0 Preview 2.0 [29913.155.master]) and latest internal Blazor WebAssemby 3.2 Preview 3 build (3.2.0-preview3.20163.13)
- Create an ASP.NET Core hosted Blazor WebAssembly app
- In the Client project set a breakpoint in `FetchData.OnInitializedAsync` on the line *after* the HTTP request
- Hit F5 to run the app in the debugger
- Navigate to the FetchData tab
- The breakpoint should hit
- Inspect the forecasts array local variable

Expected results:
- See the expanded elements of the array

Actual result:
- No elements of the array are visible:

![image](https://user-images.githubusercontent.com/1874516/76694280-2dbb4d80-662e-11ea-8b2a-adbea302c086.png)

**Comment by lewing** [comment]
It turns out array values aren't actually hooked up yet, @radical  can you look into this once you finish your other value type work?

**Comment by radical** [comment]
So, turns out that VS uses a different method to get the array elements. I got it just about working last night.
<img width="261" alt="Screen Shot 2020-04-05 at 11 04 43 PM" src="https://user-images.githubusercontent.com/1472/78590700-390a2f00-7810-11ea-9e59-406c7cce5264.png">

**Comment by lewing** [comment]
Array values work in inspector now, we're still working on VS* expansion
