### ISSUE TITLE
[WASM] No rule to make target 'package-wasm-runtime-threads'

### ISSUE THREAD

**Issue by emepetres** [mono/mono#19293]
After compiling mono from source (master), I cannot compile wasm with threading support.

## Steps to Reproduce

2. cd mono
3. make -j -C sdks/wasm runtime-threads

### Current Behavior

make cannot find target 'package-wasm-runtime-threads'

### Expected Behavior

Build finishes and there are two new directories "threads-debug" and "threads-release" under "sdks/wasm/builds" as it is stated in docs.

## On which platforms did you notice this

[x] Linux -> Windows 10 x64 WSL (Ubuntu 18 LTS)

**Version Used**:

Latest master as of today:

commit 93457ec8c3047645ff842b9dd635dacfb6b910f7
Author: Jay Krell <jaykrell@microsoft.com>
Date:   Mon Mar 23 04:38:37 2020 -0700

## Stacktrace

```
~/mono$ make -j -C sdks/wasm runtime-threads
make: Entering directory '/home/jcarnero/mono/sdks/wasm'
make -C ../builds package-wasm-runtime-threads
make[1]: Entering directory '~/mono/sdks/builds'
make[1]: *** No rule to make target 'package-wasm-runtime-threads'.  Stop.
make[1]: Leaving directory '~/mono/sdks/builds'
Makefile:344: recipe for target 'runtime-threads' failed
make: *** [runtime-threads] Error 2
make: Leaving directory '~/mono/sdks/wasm'
```

**Comment by vargaz** [comment]
Add
```
ENABLE_WASM_THREADS=1
```
to ```sdks/Make.config```.
