### ISSUE TITLE
Capture `g_assert` message in MERP crash reports

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#19295]
When we hit a `g_assert`we should capture its message into the MERP report.

**Comment by alexischr** [comment]
It turns out we already had that, but it never worked - see discussion in https://github.com/mono/mono/pull/19523#issuecomment-614111505

**Comment by SamMonoRT** [comment]
MERP has been deprioritized given newer releases off dotnet\runtime. Closing this issue.
