### ISSUE TITLE
Memory management for unloadable ALCs

### ISSUE THREAD

**Issue by vargaz** [mono/mono#19312]
Memory management for metadata/code memory is as follows in current mono:
- metadata memory is allocated from MonoImage mempools.
- metadata memory for generic instances is allocated ImageSet mempools.
- domain-specific memory (like vtables) is allocated from domain mempools.
- code memory is allocated from domain code managers.

Unloadable ALCs need the following changes:
- metadata/code memory for generic instances needs to be allocated from a mempool owned
  by a set of ALCs.

I.e. if Foo is from ALC A, and Bar is from ALC B, then all memory associated with Foo<Bar> needs
to be owned by the <A, B> set. It cannot be owned by A or B themselves, since unloading the
other would leak it.

Would suggest adding a LoaderAlloc structure similar to coreclr. It would own all the memory associated with either an ALC or a set of ALCs. The allocator functions would take 2 arguments to
specify ownership:
- a domain for current mono
- an assembly/class/method for netcore

I.e.:
```
/*
 * Allocate code memory belonging to a method.
 */
static inline gpointer
m_method_alloc_code (MonoDomain *domain, MonoMethod *method, int size)
```

In normal mode, this would allocate from the domain code manager.
In netcore mode, this would allocate from the LoaderAlloc belonging to METHOD's ALC, and
the domain argument would be ignored. It would be fairly easy to adapt the existing JIT code
to use this api.

**Comment by jaykrell** [comment]
Is it then the case, that if ALC A and B are both unloaded, that the memory from imageset(A, B) is freed?
That each ALC maintains what all sets it is a member of?
And that set is unbounded?

**Comment by lambdageek** [comment]
the memory for `imageset(A,B)` is freed when either A or B is freed.

**Comment by srxqds** [comment]
will this make work when .net5 release?

**Comment by vargaz** [comment]
This is just an internal implementation proposal.

**Comment by srxqds** [comment]
> This is just an internal implementation proposal.

if this is not work,  the ALC will not support?

**Comment by srxqds** [comment]
we need update assembly on android and ios, so we need ALC feature, when can it support?
@vargaz

**Comment by srxqds** [comment]
we are waiting for the ALC support.

**Comment by srxqds** [comment]
Is there any progress or conclusion about it. we are worry about it will implement delay.
We hope it can implement with .net5 release (November this year). Our project will block by without this features.
We should upgrade for .net5 with many improvement.

**Comment by vargaz** [comment]
This is very unlikely to be in net5.

**Comment by srxqds** [comment]
> This is very unlikely to be in net5.

but @marek-safar  said it will be supported on .net5 platform. https://github.com/mono/mono/issues/19968#issuecomment-644620914

**Comment by marek-safar** [comment]
ALC are already supported in .net5 based Mono. We still need to fully support the collectable assemblies in ALC and that might not be fully supported in net5 timeframe.

/cc @CoffeeFlux

**Comment by srxqds** [comment]
> ALC are already supported in .net5 based Mono. We still need to fully support the collectable assemblies in ALC and that might not be fully supported in net5 timeframe.
> 
> /cc @CoffeeFlux

Hi, but the alc without colletable assemblies is less meanful. we need using alc to unloadable assembly.
Is there any specific detail schedule about this work, which we can follow.
we are waiting for it. Is the fully support already in your timetable?
Thank you

**Comment by CoffeeFlux** [comment]
The API surface will be mostly supported in .NET 5, but not the backend assembly unloading functionality. There's an initial PR up with the current state of affairs (though I need to push to it), and that briefly outlines the remaining work as well. I'll be adding a more detailed document on that once the PR is finished and merged. @srxqds

**Comment by srxqds** [comment]
thank you, @CoffeeFlux. This is a good news for us. 
> The API surface will be mostly supported in .NET 5, but not the backend assembly unloading functionality. 
I have some confused about these said( I feel sorry that my english is so poor)： it said that the AssemblyLoaderContext can be load in .net5 but the assembly( the backend assembly) who create the AssemblyLoaderContext can't not unloading?

Thank you, it is so exciting to get your work prorgess.

**Comment by CoffeeFlux** [comment]
We support AssemblyLoadContext in master right now, and that includes ones created with `isCollectible = true`. However, even when you set the ALC to be collectible, it will not actually unload anything/free the memory right now. Long-term we intend to have proper unloading support, and my current PR is the first steps towards that, but it isn't ready yet. Hopefully that's clearer!

**Comment by srxqds** [comment]
ok, but if it not actually unload anything/free the memory, it is likely making memory leak.
Is there a support schedule for implementing it? because if we know the exact date it came out, we can do some pre-work firstly.
@CoffeeFlux

**Comment by CoffeeFlux** [comment]
No exact date for now beyond that it should be supported before .NET 6, sorry.

**Comment by srxqds** [comment]
> No exact date for now beyond that it should be supported before .NET 6, sorry.

Can it still use multi-domain for assembly unload in .net5? will it be compatiable with .net5?

**Comment by CoffeeFlux** [comment]
No, with .NET 5 we only allow a single domain with a default ALC. Most of that API surface is gone completely.

**Comment by srxqds** [comment]
I think it is not so diffcult to implement, why not make it work immediately?

**Comment by vargaz** [comment]
This was mostly implemented in dotnet/runtime.
