### ISSUE TITLE
[Wasm] ResourceManager fails running on AOT

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#19314]
### Current Behavior

This line fails when building with AOT:
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/referencesource/mscorlib/system/resources/resourcemanager.cs#L375

It's expected that `ves_icall_GetCurrentMethod` fails under AOT: 

https://github.com/mono/mono/blob/7d33bd36f1bc1ea195d16b16e272b69763e84d34/mono/metadata/icall.c#L5836

But `ResourceManager` would most likely work properly, considering the reason `GetCurrentMethod` is used.

Would it be acceptable to exclude:

https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/referencesource/mscorlib/system/resources/resourcemanager.cs#L375-L383

from WebAssembly builds ?

## On which platforms did you notice this

**Version Used**: 61830e01f6a32fefb0d34113c77c9c2af1680147

## Stacktrace

`Stack walks are not supported on this platform.`

**Comment by lewing** [comment]
@jeromelaban how important is this use case? I'm hesitant to put this change in the mono bcl now without it first landing in dotnet/runtime

**Comment by jeromelaban** [comment]
It means that libraries that have localized resources fail with a very cryptic message as there is no stack trace available. It guess it could wait to be integrated in dotnet/runtime as it's been like that for a while.
