### ISSUE TITLE
The vm is not suspended?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#19311]
## Steps to Reproduce

1. 
2. 
3. 

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:
6.0.0.334

## Stacktrace

```
Please paste the stack trace here if available.
```

![image](https://user-images.githubusercontent.com/5187024/77524449-5232e780-6ec2-11ea-81e4-5d49afd76e3b.png)

**Comment by hamzaoubouzid** [comment]
do you get solution about this probleme mr ?

**Comment by srxqds** [comment]
just ignore the exception

**Comment by hamzaoubouzid** [comment]
i show this exeption just when add source in mediaElement as like video
