### ISSUE TITLE
[wasm][debugger] Spurious "failed to lookup sequence point" messages

### ISSUE THREAD

**Issue by chucker** [mono/mono#19336]
## Steps to Reproduce

1. create a fresh ASP.NET-hosted `blazorwasm` project
2. in `NavMenu.razor`, set a breakpoint inside `ToggleNavMenu()` on line 35:

```csharp
  collapseNavMenu = !collapseNavMenu;
```

3. hit F5
4. make the browser small enough that the responsive design kicks in (the nav sidebar disappears; a hamburger menu button in the top right appears)
5. click the menu button

### Current Behavior

The breakpoint gets hit as expected. However, the output window gives various "Failed to lookup sequence point" messages:

```
CLEAR BREAKPOINTS
>>>mono_wasm_get_loaded_files
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
SET BREAKPOINT: assembly BlazorApp4.Client.dll method c offset 1
[dbg] Setting breakpoint at BlazorApp4.Client.Shared.NavMenu:ToggleNavMenu ():0x1.
NEW BP 0x2bd0198 has id 1
[dbg] Inserted breakpoint at BlazorApp4.Client.Shared.NavMenu:ToggleNavMenu ():[il=0x1,native=0x6] [0x2c967be](0).
[0x1] Breakpoint hit, method=ToggleNavMenu, ip=0x2c967be, [il=0x1,native=0x6].
ss_reqs 0 bp_reqs 1
mono_wasm_fire_bp
COMPUTING breapoint ID
Found BP 0x2bd0198 with id 1
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
Failed to lookup sequence point
```

(There are also some minor typos here, such as "COMPUTING breapoint ID".)

### Expected Behavior

It's not clear how severe this message is, so I don't know.

## On which platforms did you notice this

[x] Windows

### Versions used

**.NET Core SDK** 3.1.300-preview-015048
**Blazor** 3.2.0-preview3-20168.3

**Comment by lewing** [comment]
These are unmanaged DEBUG statements

https://github.com/mono/mono/search?q=%22Failed+to+lookup+sequence+point%22&unscoped_q=%22Failed+to+lookup+sequence+point%22

We can disable them for release runtimes but it would limit our ability to debug the runtime because blazor still cannot load debug builds of the runtime.

/cc @SteveSandersonMS
