### ISSUE TITLE
Question regarding register spilling during parameter list building

### ISSUE THREAD

**Issue by nealef** [mono/mono#19337]
I am trying to work out why I am seeing register spilling and reloading from an uninitialized area. The problem is peculiar to s390x and involves the passing of 6 or more structures that don't fit in a register. 

In s390x the 1st 5 parameters are passed as values or addresses in registers 2, 3, 4, 5, 6. All other parameters are placed on the stack starting at SP+160.

The test program is very simple:
```
using System;

class NullTest
{

	struct Q {
		public long a;
		public long b;
	};

	[MethodImplAttribute (MethodImplOptions.NoInlining)]
	static long QQ(Q a, Q b, Q c, Q d, Q e, Q f) {
		return(a.a + b.b + c.a + d.b + e.a + f.b);
	}

	static int Main (string[] args) {
		Q q;
		q.a = 5; q.b = 45;
		var s = QQ(q,q,q,q,q,q);
		if (s != 150) return (2);
		return (0);
	}
}
```
This snippet of code is the result of the emit_call function.  A couple of notes to help interpret:
1. ```aghik - r1,r2,<val>``` - adds ```r2``` to ```<val>``` and places the result in ```r1```
2. ```mvc d1(l,r1),d2(r2)``` - Moves ```l``` bytes from ```r2+d2``` to ```r1+d1``` (```dx``` is a displacement in range 0->4095)
```
  de:   ec 7f 02 58 00 d9       aghik   %r7,%r15,600 <- Area where a copy of q had been created
  e4:   ec 2f 00 a8 00 d9       aghik   %r2,%r15,168 <- A place on the stack where that copy is going as parameter 1 ('a')
  ea:   d2 0f 20 00 70 00       mvc     0(16,%r2),0(%r7) <- Value moved to the parameter location
  f0:   ec 2f 02 68 00 d9       aghik   %r2,%r15,616 
  f6:   ec 3f 00 b8 00 d9       aghik   %r3,%r15,184 <- r3 is pointed at parameter 2 ('b')
  fc:   d2 0f 30 00 20 00       mvc     0(16,%r3),0(%r2) <- Value moved to the parameter location
 102:   ec 2f 02 78 00 d9       aghik   %r2,%r15,632
 108:   ec 4f 00 c8 00 d9       aghik   %r4,%r15,200 <- r4 is pointed at parameter 3 ('c')
 10e:   d2 0f 40 00 20 00       mvc     0(16,%r4),0(%r2)
 114:   ec 2f 02 88 00 d9       aghik   %r2,%r15,648
 11a:   ec 5f 00 d8 00 d9       aghik   %r5,%r15,216 <- r5 is pointed at parameter 4 ('d')
 120:   d2 0f 50 00 20 00       mvc     0(16,%r5),0(%r2)
 126:   ec 2f 02 98 00 d9       aghik   %r2,%r15,664
 12c:   ec 6f 00 e8 00 d9       aghik   %r6,%r15,232 <- r6 is pointed at parameter 5 ('e')
 132:   d2 0f 60 00 20 00       mvc     0(16,%r6),0(%r2)
 138:   ec 2f 02 a8 00 d9       aghik   %r2,%r15,680
 13e:   ec 7f 00 f8 00 d9       aghik   %r7,%r15,248 <- r7 is pointed at parameter 6 ('f')
 144:   d2 0f f0 f8 20 00       mvc     248(16,%r15),0(%r2)
```
At this stage we have:
 
* r2 - pointing at where 'f' was copied from
* r3 - &b
* r4 - &c
* r5 - &d
* r6 - &e

At this stage r2 needs to be set to &a but it loads from a spilled area but that location has not been set to any value. The spill (if required) should have occurred after location 0xe4 but before 0xf0. 
```
 14a:   e3 20 f2 b8 00 04       lg      %r2,696(%r15)
 150:   e3 70 f0 a0 00 24       stg     %r7,160(%r15) <- The address of parameter 6 ('f') is placed in the 1st slot of the stack
```
So now we have:

* r2 - ???
* r3 - &b
* r4 - &c
* r5 - &d
* r6 - &e
* SP+160 - &f

What I am trying to determine is how the spilling should have worked. I assume it happened because r2 is being used as a work register for building the parameter list but I am not sure why it wasn't saved when it's required value was set.

**Comment by nealef** [comment]
Further information. Running with the ```-v -v -v -v``` option the debug output shows the spill store (and the loads):
```
processing:     51 move R92 <- R91
        SPILLED STORE (1 at 0x000002b8(%ebp)) R92 (from s390_r2)
        assigned dreg s390_r2 to dest R92
        freeable s390_r2 (R92) (born in 51)
        assigned sreg1 s390_r2 to R91
        SPILLED STORE (4 at 0x000002d0(%ebp)) R91 (from s390_r2)
        51 move s390_r2 <- s390_r2
```
However, there is no evidence of the store instruction being instantiated. 

Speculation: Would there be any need to spill/reload if the parameters were processed from last to first? In s390x this wouldn't cause any problems but for push/pop stacks this would not be doable.

**Comment by vargaz** [comment]
Note that the local register allocator works backwards. So when it says 'spill store', it means a
previously processed instruction (which will be executed later during execution) expects the given vreg in the given stack location. Can you attach the whole output (use MONO_VERBOSE_METHOD=<method name>) to limit the output.

**Comment by nealef** [comment]
Output available at https://pastebin.com/P3ipXsFw. I can post here if preferred.

**Comment by vargaz** [comment]
Not familiar with the s390x calling convention, but if r2 is used to pass the first argument, then
this IR should exist:
long_add_imm s390_r2 <- s390_r15 [168]
    37 s390_move [s390_r2] <- [R64 + 0x0]

The way the local register allocator works, is that when it processes the call instruction:
lcall R33 <- [long NullTest:QQ (NullTest/Q,NullTest/Q,NullTest/Q,NullTest/Q,NullTest/Q,NullTest/Q)] [s390_r2 <- R65] [s390_r3 <- R67] [s390_r4 <- R69] [s390_r5 <- R71] [s390_r6 <- R73] clobbers: c
It assigns R65 to r2 etc. And later, when it encounters a previous
mov R65, Rsomething
it converts it into mov r2, Rsomething

I.e. the IR should not contain registers like r2 until after local register allocation.

**Comment by nealef** [comment]
Briefly, in calls involving integer registers or structures the rules are:
1. R2-R6 are used to contain integer values, structures of length 1, 2, 4, or 8, or addresses of structures of other lengths
2. After registers are exhausted then parameters are placed on the stack starting at SP+160

I am wondering if I am overdoing things in the call. Is the call process already creating copies of the variables for me and that the OP_S390_MOVE instructions are unnecessary (as well as reserving space on the stack)? That is, I see this group of instructions in the Nulltest:Main trace:

1. Initialize the structure components to 0 - 
```
  1a:   a7 29 00 00                lghi    %r2,0
  1e:   e3 20 f2 30 00 24     stg     %r2,560(%r15)
  24:   e3 20 f2 38 00 24     stg     %r2,568(%r15)
```
2. Set the components of 'q' to the values '5' and '45':
```
  2a:   a7 29 00 05                 lghi    %r2,5
  2e:   e3 20 f2 30 00 24       stg     %r2,560(%r15)
  34:   a7 29 00 2d                 lghi    %r2,45
  38:   e3 20 f2 38 00 24.      stg     %r2,568(%r15)
```
3. It appears it now is creating a copy for each of the entities to be passed by value that won't fit into a register:
```
# Parameter 1 ('a' as it is seen by the ZZ method) - The address of this will go into R2 for the call
  3e:   e3 20 f2 30 00 04       lg      %r2,560(%r15) 
  44:   e3 20 f2 40 00 24       stg    %r2,576(%r15).    
  4a:   e3 20 f2 38 00 04       lg      %r2,568(%r15)
  50:   e3 20 f2 48 00 24       stg    %r2,584(%r15)

# Parameter 2 ('b') - R3
  56:   e3 20 f2 30 00 04       lg      %r2,560(%r15)
  5c:   e3 20 f2 50 00 24       stg    %r2,592(%r15)
  62:   e3 20 f2 38 00 04       lg      %r2,568(%r15)
  68:   e3 20 f2 58 00 24       stg    %r2,600(%r15)

# Parameter 3 ('c') - R4
  6e:   e3 20 f2 30 00 04       lg      %r2,560(%r15)
  74:   e3 20 f2 60 00 24       stg    %r2,608(%r15)
  7a:   e3 20 f2 38 00 04       lg      %r2,568(%r15)
  80:   e3 20 f2 68 00 24       stg    %r2,616(%r15)

# Parameter 4 ('d') - R5
  86:   e3 20 f2 30 00 04       lg      %r2,560(%r15)
  8c:   e3 20 f2 70 00 24       stg     %r2,624(%r15)
  92:   e3 20 f2 38 00 04       lg      %r2,568(%r15)
  98:   e3 20 f2 78 00 24       stg     %r2,632(%r15)

# Parameter 5 ('e') - R6
  9e:   e3 20 f2 30 00 04       lg      %r2,560(%r15)
  a4:   e3 20 f2 80 00 24       stg    %r2,640(%r15)
  aa:   e3 20 f2 38 00 04       lg      %r2,568(%r15)
  b0:   e3 20 f2 88 00 24       stg    %r2,648(%r15)

# Parameter 6 ('f') - The address of this will be placed on the stack
  b6:   e3 20 f2 30 00 04       lg      %r2,560(%r15)
  bc:   e3 20 f2 90 00 24       stg    %r2,656(%r15)
  c2:   e3 20 f2 38 00 04       lg      %r2,568(%r15)
  c8:   e3 20 f2 98 00 24       stg    %r2,664(%r15)
```
That is, there is no need for me to do the OP_S390_MOVE as Mono has done the work already. All I need is for the address of those parameters to be placed in the right register for the call. So I would expect to see something like this for the call:
```
aghik %r2, %r15,576
aghik %r3,%r15,592
aghik %r4,%r15,608
aghik %r5,%r15,624
aghik %r6,%r15,640
aghik %r7,%r15,656 (It is not important what register is used here other than r2-r6)
stg     %r7,160(%r15) - Place the address of Parameter 6 on the stack
[call to ZZ]
```

**Comment by vargaz** [comment]
Look at what other platforms are doing in mono_arch_emit_call (), s390x needs to do approx the same.

**Comment by nealef** [comment]
Thanks, just putting this down on "paper" helped me get my head around the problem and see what I was doing wrong. It appears fixed though I'm sure there'll be some strange edge cases.
