### ISSUE TITLE
[wasm][debugger] document debugging with VS* without blazor

### ISSUE THREAD

**Issue by lewing** [mono/mono#19338]
The debug proxy still supports standalone mode. We need to document how to run the proxy outside of blazor.

**Comment by danwalmsley** [comment]
@lewing @radical this was closed, but even wasm app host, there seems to be no documentation on how to do this?

**Comment by radical** [comment]
The WasmAppHost is meant for the new experimental console, and browser templates which don't use Blazor. @thaystg is working  hard on a PR for debugging those with VS!
