### ISSUE TITLE
Installing VSSDK

### ISSUE THREAD

**Issue by alexreg** [mono/mono#19345]
Is it possible to install the VSSDK for Mono? I see some MSBuild files (e.g., `csproj` files) try to find the `/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/VSSDK` dir (specifically `/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/xbuild/Microsoft/VisualStudio/v16.0/VSSDK/Microsoft.VsSDK.targets` in my case), but cannot due so, because there is no `VSSDK` dir under its parent dir (which does exist). Is there any way to install this on Mono? I presume it would only be the targets and possibly a few other parts of the VSSDK, not necessarily the whole thing.

**Comment by akoeplinger** [comment]
I think nowadays you're using the https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools to build VS extensions but as far as I know the package is still Windows-specific (might be worth a try).

The old .MSI based VSSDK is definitely not supported on Windows.

**Comment by alexreg** [comment]
Thanks. That would make sense.
