### ISSUE TITLE
[Debugging] Local variables from a previous stack-frame don't show in the `Locals` window

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19379]
As you can see in the screenshot below, I'm on the second stack frame and neither `this` nor `v` locals aren't shown:
![image](https://user-images.githubusercontent.com/34246760/77981277-55611580-72be-11ea-854d-125a94a52361.png)

**Comment by lewing** [comment]
Verified there is still an issue here something is going on with the scope expansion that is causing this.
