### ISSUE TITLE
[Debugging] Delegates show only type name in the Locals window

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19382]
This is what I see in the Locals window:
![image](https://user-images.githubusercontent.com/34246760/77982464-4039b600-72c1-11ea-91f1-1d6463be9bde.png)

The very same delegate shows the referenced method name too:
![image](https://user-images.githubusercontent.com/34246760/77982497-547db300-72c1-11ea-968d-25997fec0519.png)

**Comment by radical** [comment]
I have this working locally. It shows a `Target` property also, but I'm not sure whether to show the `MethodInfo` object also like VS does.

**Comment by lewing** [comment]
@radical how far away from a pr are you?  can you open a draft pr?
