### ISSUE TITLE
[Debugging] Immediate Windows is not working at all

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19383]
Even very simple evaluations like `5+5` print an empty line.
Same story for any other type of variable.

**Comment by lewing** [comment]
immediate window isn't currently supported on managed frames

**Comment by lewing** [comment]
Basic expressions are working now

**Comment by thaystg** [comment]
Basic expressions are working now, for example:
-this.property
-local variables
-constants
-arithmetic operation with the values above
Not working:
- assignment
- method calls
- nested property

**Comment by lewing** [comment]
calling this fixed
