### ISSUE TITLE
[Debugging] `decimal`-s are treated as `object` rather than `Number`

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19380]
In my complex type `v10` is a `decimal` property, however in the Locals window it shows up as `object` (hence `null` by default):

```csharp
        public decimal v10 { get; set; }
        public float v11 { get; set; }
        public double v12 { get; set; }
```

![image](https://user-images.githubusercontent.com/34246760/77981657-6a8a7400-72bf-11ea-819c-90b9905e6f80.png)

**Comment by lewing** [comment]
requires the value type work

**Comment by lewing** [comment]
number is a double, decimal is a struct mean to not be floating point.  We should put the string value in the description but it shouldn't act like a normal number

**Comment by tqiu8** [comment]
With the latest wasm build (4953) `decimal` displays value as `System.Decimal` and type as `object` with constituent parts displayed correctly on expansion. 

![19380](https://user-images.githubusercontent.com/16296328/78725580-e4dd7880-78fd-11ea-939a-d352a5197763.jpg)
