### ISSUE TITLE
[WASM] No rule to make target 'runtime-dynamic'

### ISSUE THREAD

**Issue by emepetres** [mono/mono#19409]
After compiling mono from source (master), I cannot compile wasm with dynamic support. I even tried with ``ENABLE_WASM_DYNAMIC=1` on sdks/Make.config.

## Steps to Reproduce

1. cd mono
2. make -j -C sdks/wasm runtime-dynamic

### Current Behavior

*** No rule to make target 'runtime-dynamic'. Stop.

### Expected Behavior

Build finishes and the directory "release-dynamic" is under "sdks/wasm/builds" as it is stated in docs.

## On which platforms did you notice this

[x] Linux -> Windows 10 x64 WSL (Ubuntu 18 LTS)

**Version Used**:

Mono master:

commit d525e3d5a38d7150a2fa920670b8bf1e908ffdd3
Author: Kenneth Pouncey <kjpou@pt.lu>
Date: Tue Mar 31 06:33:30 2020 +0200

## Stacktrace

```
make -j -C sdks/wasm runtime-dynamic
make: Entering directory '/home/jcarnero/mono/sdks/wasm'
make: *** No rule to make target 'runtime-dynamic'.  Stop.
make: Leaving directory '/home/jcarnero/mono/sdks/wasm'
```

**Comment by kjpou1** [comment]
try with ENABLE_WASM_DYNAMIC_RUNTIME=1

and build using

make -j -C sdks/wasm
