### ISSUE TITLE
[Debugging] DateTime and DateTimeOffset are not supported

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#19411]
Values of `DateTime` and `DateTimeOffset` values always shows up as `null` in Locals/Watch windows:
![image](https://user-images.githubusercontent.com/34246760/78158519-32d21800-73f6-11ea-80a1-fa0b9065233b.png)

**Comment by lewing** [comment]
This is very different after https://github.com/mono/mono/pull/19232 but we may want to do more work on it.

**Comment by tqiu8** [comment]
With the latest wasm build, `DateTime `and `DateTimeOffset `are displayed as `System.DateTime` and `System.DateTimeOffset`. 

![19411](https://user-images.githubusercontent.com/16296328/78724393-5bc54200-78fb-11ea-970b-f224faecd81e.jpg)
