### ISSUE TITLE
Instruction optimized out of outarg_vt sequence

### ISSUE THREAD

**Issue by nealef** [mono/mono#19417]
I have found a problem with my JIT code that I can't seem to solve. This is for the case where a structure of 12 bytes is being passed to another method.

The ```outarg_vt``` sequence for structures which won't fit in a register is to copy the structure to a place on the stack, pass the address of that structure on the stack as a parameter to the called method. This sequence  is:
```
MONO_EMIT_NEW_BIALU_IMM (cfg, OP_ADD_IMM, tmpr, ainfo->reg, ainfo->offparm); <- Set the address of the structure copy area in a register
emit_new_move (cfg, 0, tmpr, 0, src->dreg, 0, size); <- Move a copy of the structure to that area
MONO_EMIT_NEW_STORE_MEMBASE(cfg, OP_STORE_MEMBASE_REG, ainfo->reg, ainfo->offset, tmpr); <- Place that address on the stack as a parameter to the method
```
The IR code at  https://pastebin.com/Ki0fQKPz shows the instruction being processed but it is  being optimized out.
```
	1  add_imm R60 <- s390_r15 [392]
 add_imm R61 <- s390_r15 [208]
	 ii  61 15
	1  add_imm R61 <- s390_r15 [208]
 s390_move [R61] <- [R60 + 0x0]
	 ii  61 60
	1  s390_move [R61] <- [R60 + 0x0]
 store_membase_reg [s390_r15 + 0xc0] <- R61
	  ii -1 61
	1  store_membase_reg [s390_r15 + 0xc0] <- R61
 store_membase_imm [s390_r15 + 0xc8] <- [11]
```

I would expect that the instruction after location 0xd0 would be ```aghi %r7,%r15,208``` which corresponds to the BIALU_IMM above. The subsequent two instructions are produced. 

I ran the program with ```--optimize=-all,<xxxx>``` where I cycled through all the optimization modes and found that the instruction doesn't get optimized away when only the following optimization is specified - 

- abcrem
- aot (equivalent of -all on s390x I assume)
- branch
- cfold
- cmov

All other modes get rid of that instruction.

**Comment by nealef** [comment]
@vargaz I have been trying to find where the instruction is being deleted. I assumed it would somewhere be the argument of the MONO_[DELETE|REMOVE|NULLIFY] macro but I can't see it being used.

**Comment by vargaz** [comment]
I can't read s390x assembly, which instruction was deleted ?

**Comment by nealef** [comment]
Actually, I can see why it thinks it needs to delete the instruction:
```
 ldaddr R68 <- R67
 s390_move [R68] <- [R65 + 0x0]
```
The above sequence appears to overwrite R68 where the intent is for the s390_move to move data to the address specified by R68. Is there a hint I can pass to tell it?

**Comment by vargaz** [comment]
If s390_move is some kind of copy instruction, its better to define it so it uses sreg1 and sreg2 as the destination and source, not dreg and sreg1.
Alternatively, defining it as:
s390_move: len:48 dest:b src1:i
_might_ fix it.

**Comment by nealef** [comment]
Thanks for the tips I will experiment.

**Comment by nealef** [comment]
The sreg2/sreg1 option appears to have worked the latter didn't. Thank you yet again.
