### ISSUE TITLE
Out-of-date libgc in recent releases

### ISSUE THREAD

**Issue by mcneish1** [mono/mono#19436]
libgc packaged into (at least) 5.18.0.240 through 6.8.0.105 on https://download.mono-project.com/sources/mono/ contain configure.ac with broken `--disable-parallel-mark`, fixed in https://github.com/Unity-Technologies/bdwgc/commit/e3bfd10510d1c33736165295853df7f125f57a17.

I see this repo now has new-enough bdwgc in `external`, since https://github.com/mono/mono/commit/cc137237d86b0553e844dc34c9a3cbc5b20782c0, but releases since that commit still use the old libgc.

Do you know when bdwgc will be included into a mono release?

**Comment by akoeplinger** [comment]
Release from the 2020-02 branch will have the bdwgc, so Mono 6.12.x versions. You can get them as nightly builds page currently: https://www.mono-project.com/download/nightly/
