### ISSUE TITLE
[Wasm] Linker fails searching for WebAssembly.Net.Http

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#19481]
After https://github.com/mono/mono/pull/19260, the linker step fails searching for `WebAssembly.Net.Http` that has been renamed to `System.Net.Http.WebAssemblyHttpHandler`. It looks like some of the SDK assemblies are still using this previous assembly reference.

**Comment by lewing** [comment]
cc @pranavkm

**Comment by kjpou1** [comment]
jeromelaban could you make sure your packages are cleared and make sure that the reference to `WebAssembly,Net.Http` are changed to `System.Net.Http.WebAssemblyHttpHandler`.

The naming changes were prompted by upcoming changes to the system.

**Comment by jeromelaban** [comment]
This is caused by another issue, apologies for the incorrect report.
