### ISSUE TITLE
Debugger crash when inspecting element

### ISSUE THREAD

**Issue by UnityAlex** [mono/mono#19492]
## Steps to Reproduce

1. Compile repro code with symbols and including a reference to the System.Runtime.CompilerServices.Unsafe.dll. I used: `csc.bat /unsafe Program.cs -r:C:\<Path to my project dir>\System.Runtime.CompilerServices.Unsafe.dll -debug:portable`
    - Note: If I used full debug symbols I hit an assert: `* Assertion: should not be reached at ..\mono\metadata\marshal-ilgen.c:6205`
2. Run repro executable: `"C:\Program Files\Mono\bin\mono.exe" --debug --debugger-agent=transport=dt_socket,embedding=1,server=y,suspend=n,address=127.0.0.1:50000 Program.exe`
3. Reproducible with both Rider and VS. Attach to process, Put a breakpoint on 2nd Console.ReadKey(); Hit enter in process window to trigger breakpoint.
4. Inspect access->MyAccessor
5. Observe crash: ``* Assertion at ..\mono\mini\debugger-agent.c:6490, condition `is_ok (error)' not met, function:do_invoke_method, Invalid generic instantiation assembly:<path to exe> type:FiskDebugView`1 member:(null)``

```C#
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace DebuggerCrash
{
    unsafe struct Blah
    {
        public void* Ptr;
    }
    [DebuggerTypeProxy(typeof(FiskDebugView<>))]
    unsafe struct Fisk<T> where T : unmanaged
    {
        public T* Ptr;
    }
    unsafe struct Accessor
    {
        public Blah blah;
        public ref Fisk<GCHandle> MyAccessor
        {
            get
            {
                fixed (void* ptr = &blah)
                {
                    return ref System.Runtime.CompilerServices.Unsafe.AsRef<Fisk<GCHandle>>(ptr);
                }
            }
        }
    }
    internal sealed class FiskDebugView<T> where T : unmanaged, IEquatable<T>
    {
        Fisk<T> Data;
        public FiskDebugView(Fisk<T> data)
        {
            Data = data;
        }
        public unsafe T[] Items
        {
            get
            {
                T[] result = new T[1];
                result[0] = Data.Ptr[0];
                return result;
            }
        }
    }
    class Program
    {
        public unsafe Program()
        {
            GCHandle test = default;
            var access = new Accessor { blah = new Blah { Ptr = &test } };
            Console.WriteLine((IntPtr)access.MyAccessor.Ptr);
            Console.ReadKey();
            Console.ReadKey();
        }

        static void Main(string[] args)
        {
            new Program();
        }
    }
}
```

### Current Behavior
Crashes with:
``* Assertion at ..\mono\mini\debugger-agent.c:6490, condition `is_ok (error)' not met, function:do_invoke_method, Invalid generic instantiation assembly:<path to exe> type:FiskDebugView`1 member:(null)``

### Expected Behavior
No crash - looks like there are different constraints between production code and proxy?

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:

```
Mono JIT compiler version 6.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

## Stacktrace

```
Let me know if you need a stacktrace. I can grab one with the latest master branch if need be.
```

**Comment by UnityAlex** [comment]
cc @jbevain

**Comment by thaystg** [comment]
As I understand we try to instantiate a FiskDebugView<GCHandle>, and we get this error:
The type 'System.Runtime.InteropServices.GCHandle' cannot be used as type parameter 'T' in the generic type or method 'FiskDebugView<T>'. There is no boxing conversion from 'System.Runtime.InteropServices.GCHandle' to 'System.IEquatable<System.Runtime.InteropServices.GCHandle>'. (CS0315) 
This makes sense for you?
This DebuggerTypeProxy doesn't work for netcore too. 
If you remove the IEquatable<T> of the where T, then it works for mono, but still doesn't work for netcore. 
I will remove the assert because we don't need to stop the debug, we are not able to show the value of the DebuggerTypeProxy, but we still can show the Raw View.
Is it okay for you?

**Comment by UnityAlex** [comment]
Yes we had discovered that if you removed the IEquatable that things would work again. I noticed that in .Net runtime seemed to treat it in the way you just mentioned so I believe that would be a reasonable solution instead of hitting the assert. The lack of a boxing conversion is interesting however, is this something that should be possible?

**Comment by thaystg** [comment]
I don't think that this should be possible. I will do the PR without the assert.
