### ISSUE TITLE
mono_wasm: Problems with 'Getting started' guide, 'Error: Parameter count mismatch.' in dotnet.js

### ISSUE THREAD

**Issue by johanndev** [mono/mono#19653]
I'm trying to follow the mono_wasm sample from
https://github.com/mono/mono/blob/master/sdks/wasm/docs/getting-started/sample.md and having some problems executing it.

It's probably a simple mistake, but after investing some time I'm unable to locate my error.

## Steps to Reproduce

1. Download latest WebAssembly SDK (https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/processDownloadRequest/5036/ubuntu-1804-amd64/sdks/wasm/mono-wasm-aff8690a9b4.zip), unzip, and source it to `$WASM_SDK`
2. Create and change to directory `my-app`
3. Copy files from `$WASM_SDK` to `my-app` directory
4. Compile sample: `csc /target:library -out:sample.dll /noconfig /nostdlib /r:$WASM_SDK/wasm-bcl/wasm/mscorlib.dll /r:$WASM_SDK/wasm-bcl/wasm/System.dll /r:$WASM_SDK/wasm-bcl/wasm/System.Core.dll /r:$WASM_SDK/wasm-bcl/wasm/Facades/netstandard.dll /r:$WASM_SDK/wasm-bcl/wasm/System.Net.Http.dll /r:$WASM_SDK/framework/WebAssembly.Bindings.dll /r:$WASM_SDK/framework/System.Net.Http.WebAssemblyHttpHandler.dll dependency.cs sample.cs`
5. First obstacle:
```
Compilation error: `sample.cs(26,3): error CS0103: The name `DebuggerTests' does not exist in the current context`
```
As the `Math.Run` which references the `DebuggerTests` class is not referenced anywhere, I simply removed it from `sample.cs` and was able to compile:

```
dependency.cs(7,10): warning CS0414: The private field `Simple.Complex.c' is assigned but its value is never used
Compilation succeeded - 1 warning(s)
```
6. Package and publish: `mono $WASM_SDK/packager.exe --copy=always --out=./publish --asset=./sample.html --asset=server.py sample.dll` - Working
7. `cd publish` && `python3 server.py`: `python 3 serving at port 8000`
8. Navigate to http://localhost:8000/sample.html in browser and open developer console:
```
MONO_WASM: Initializing mono runtime
dotnet.js:1 Uncaught (in promise) Error: Parameter count mismatch.
    at Object.call_method (dotnet.js:1)
    at Object.call_static_method (dotnet.js:1)
    at Object.init (sample.html:40)
    at runtime.js:10
    at dotnet.js:1
```
8. Click on the `Run` button produces output `26`, `Show my location` prints `Geolocation is not supported by your browser`, no GeoLocation Prompt was shown before/after pressing the button.

### Current Behavior
Sample does not work as described in the docs, errors during runtime of the published output.

### Expected Behavior
Successful compilation, sample working as described in the docs.

## On which platforms did you notice this

[ ] macOS
[x] Linux (Ubuntu 18.04. on WSL)
[ ] Windows

Browsers (on Windows 1909): 
Microsoft Edge Version 84.0.488.1 (Official build) dev (64-bit)
Firefox Developer Edition 76.0b8 (64-Bit)

**Version Used**:
Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:20:20 UTC 2020)

**Comment by lewing** [comment]
We've been reworking a lot of the test logic and it look like we accidentally broke the sample code.

**Comment by radical** [comment]
I've included the fix in https://github.com/mono/mono/pull/19647 .

**Comment by radical** [comment]
You can fix it locally as in - https://github.com/radical/mono/commit/833f2013d05d54c3a0ea94c0b71c099a9c04a677 .

**Comment by johanndev** [comment]
Thank you!

**Comment by geogiam-net** [comment]
Hello Guys,

The bug is still happening, compilation works but when running the sample it still throws an error. 

when loading page:
dotnet.js:1 Unhandled exception in _finalize_startup Error: Parameter count mismatch.
    at Object.call_method (dotnet.js:1)
    at Object.call_static_method (dotnet.js:1)
    at Object.init ((index):40)
    at Object.loaded_cb (runtime.js:10)
    at Object._finalize_startup (dotnet.js:1)
    at onPendingRequestComplete (dotnet.js:1)
    at processFetchResponseBuffer (dotnet.js:1)
onPendingRequestComplete @ dotnet.js:1
dotnet.js:1 Uncaught (in promise) Error: Parameter count mismatch.
    at Object.call_method (dotnet.js:1)
    at Object.call_static_method (dotnet.js:1)
    at Object.init ((index):40)
    at Object.loaded_cb (runtime.js:10)
    at Object._finalize_startup (dotnet.js:1)
    at onPendingRequestComplete (dotnet.js:1)
    at processFetchResponseBuffer (dotnet.js:1)

When clicking the button to show my location
Geolocation is not supported by your browser

I tested in google chrome, firefox and vivaldi
