### ISSUE TITLE
Error while installing: llvm disabled due to missing sse4.1

### ISSUE THREAD

**Issue by Bande11a** [mono/mono#19663]
Im trying to install Mono-devel on a raspberry pi. When i go to install it, it gets stuck on this llvm disabled due to missing sse4.1 and then it crashes

**Comment by TheMomoro** [comment]
I'm having this problem too, is there _any fix?_

**Comment by NBubb** [comment]
Me too.  I can't see a fix is this uncommon?

**Comment by Bande11a** [comment]
Im Pretty sure its a matter of waiting. It takes a while but it got there eventually for me

**Comment by VladPutinEu** [comment]
> Im Pretty sure its a matter of waiting. It takes a while but it got there eventually for me

Same. I had the message, waited a while for the installation to complete. And it worked fine!
