### ISSUE TITLE
[interpreter] add x86 support

### ISSUE THREAD

**Issue by lewurm** [mono/mono#19669]
Currently we only support x86_64.

Why is it needed?

* x86/Android. Also see https://github.com/xamarin/xamarin-android/pull/4618#discussion_r416599308
* iOS 32bit simulator runs on x86/Darwin. I think this is fairly uncommon, but technically it's still around.
* watchOS simulator runs on x86/Darwin.

What needs to be done:
* implement the arch specific trampolines and parameter jugling code.
  - arm64 version of `mono_arch_get_native_to_interp_trampoline`: https://github.com/mono/mono/blob/b74bbe92693430b41ddc4cdb6c5d94c27c650aea/mono/mini/tramp-arm64.c#L728-L731
  - arm64 version of `mono_arch_get_interp_to_native_trampoline`: https://github.com/mono/mono/blob/b74bbe92693430b41ddc4cdb6c5d94c27c650aea/mono/mini/tramp-arm64.c#L623-L625
  - arm64 version of `mono_arch_set_native_call_context_args`: https://github.com/mono/mono/blob/c683499ad322e379b936f0f4fa34171ee3a7d6d1/mono/mini/mini-arm64.c#L1448-L1451
  - arm64 version of `mono_arch_set_native_call_context_ret`: https://github.com/mono/mono/blob/c683499ad322e379b936f0f4fa34171ee3a7d6d1/mono/mini/mini-arm64.c#L1496-L1499
  - arm64 version of `mono_arch_get_native_call_context_args`: https://github.com/mono/mono/blob/c683499ad322e379b936f0f4fa34171ee3a7d6d1/mono/mini/mini-arm64.c#L1528-L1531
  - arm64 version of `mono_arch_get_native_call_context_ret`: https://github.com/mono/mono/blob/c683499ad322e379b936f0f4fa34171ee3a7d6d1/mono/mini/mini-arm64.c#L1561-L1564
* add a CI lane. I think x86/Linux would be good enough.

/cc @SamMonoRT @BrzVlad

**Comment by pjcollins** [comment]
@BrzVlad @lewurm I see that this was closed, do you know if this was implemented or was it cut?

**Comment by BrzVlad** [comment]
it was implemented
