### ISSUE TITLE
no object of size error

### ISSUE THREAD

**Issue by srxqds** [mono/mono#19681]
we found the error **no object of size** in https://github.com/mono/mono/blob/e93468757541bb166b72267c0ef1ae4a282262fe/mono/sgen/sgen-marksweep.c#L317

because we can't make it repeatly.
what situation will cause these?
we should kown what problem is it and to solve it.

## Steps to Reproduce

it was caused from create raw string.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:
6.0.0.334

## Stacktrace

![image](https://user-images.githubusercontent.com/5187024/81276113-28560e80-9085-11ea-9866-cff0c45bb743.png)

**Comment by BrzVlad** [comment]
This is a crash in the GC. If you are using embedded mono, the most likely explanation is that you are storing references of a managed object inside another managed object without going through a write barrier. Do you have such cases in your code ?
