### ISSUE TITLE
[wasm][debugger]: PI over E

### ISSUE THREAD

**Issue by baulig** [mono/mono#19702]
Using

```
	var test = "Hello World";
	var piOverE = Math.PI / Math.E;
	var message = $"PI divided by E: {piOverE}";
	Console.WriteLine (message);
	Console.WriteLine (test);
```

the variable `piOverE` is incorrectly displayed as integer in the locals window.

<img width="1680" alt="Screen Shot 2020-05-04 at 7 55 16 PM" src="https://user-images.githubusercontent.com/346113/80997269-5a772e80-8e41-11ea-8108-6eb3b9e19f87.png">

I'll investigate and should hopefully have a PR for it.

**Comment by lewing** [comment]
This was a regression introduced where that caused floating point types to display as int, the bug is fixed in 19704 but  I'll leave this open until the tests are added.

**Comment by lewing** [comment]
https://github.com/mono/mono/pull/19712
