### ISSUE TITLE
Performance Issues with Pointer Arithmetics

### ISSUE THREAD

**Issue by mf-RDP** [mono/mono#19721]
Hi All,

I do a lot of stuff in unsafe code with normal (C-style) pointer arithmetics.
Mono has, compared to RyuJIT, a poor performance in simple pointers arithmetics.

e.g.
        public static unsafe void test_0_perf_ptr1() // slow - mono
        {
            ptr0 = (some struct*)0x0;
            while (ptr0 < (some struct*)100000000000)
                ptr0++;
        }
 - MS .NET implementation is nearly 2x faster, this is related to the pointer arithmetics, I came down to this. (i.e. not other optimizations). Tested on x64 w and w/o AOT.

When using IntPtr, the performance issue is not present, so it appears to be related to the ptr element size (sizeof(some struct)).

Is there any chance to get this fixed?

Many Thanks otherwise
Sascha

**Comment by vargaz** [comment]
Running csc with the -O argument would make it generate better IL code which would make mono's JIT to generate better code.

**Comment by mf-RDP** [comment]
Many Thanks. So this is optimize. Yes, I have this on of course. 

As said, it appears related to the element size. The issue is not present when using void* or IntPtr.

**Comment by mf-RDP** [comment]
Sorry - I was mislead in my performance testing, the 'performance flaw' (of couse not a real one, just a difference) was in CompilerServices.Unsafe.CopyBlock / cpblk. So everything is fine.

I was wondering, as the type of the pointer does not influence the IL much either...

Thanks, you guys are great.
