### ISSUE TITLE
bug: delegate_bound_static_invoke_cache should consider MonoMethodInflated case?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#19754]
we embed mono on iOS for multi-domain for unloading assembly with mscolib.dll is aoted-code.

## Steps to Reproduce

1. root domain load mscorlib.dll (not unload)
2. create game domain load game assembly.
3. unload game domain and re-create game domain and load game assembly

### Current Behavior

crash

### Expected Behavior

work right.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] iOS embeded

**Version Used**:

6.0.0.334

## Stacktrace

![image](https://user-images.githubusercontent.com/5187024/81554447-63c04800-93b9-11ea-89c2-6dfd9e0a75a0.png)

and some value:
![image](https://user-images.githubusercontent.com/5187024/81555070-725b2f00-93ba-11ea-8ec2-d88b8a443e8c.png)

**Comment by srxqds** [comment]
who can I help me figuring out what problm is?

**Comment by srxqds** [comment]
@vargaz  can you help me? thank you.

**Comment by BrzVlad** [comment]
@srxqds You seem to be encountering a delegate invocation issue, the likes of which I've fixed in the past. I wouldn't be surprised if your issue doesn't reproduce on master, given you use an older interpreter. I would recommend sticking with basic delegate patterns like creating new `Action` and `Func` passing method as argument and avoid more complicated API like `Delegate.CreateDelegate`. In your case you seem to create such a delegate that has its declaration signature different from the invocation one.

**Comment by srxqds** [comment]
> @srxqds You seem to be encountering a delegate invocation issue, the likes of which I've fixed in the past. I wouldn't be surprised if your issue doesn't reproduce on master, given you use an older interpreter. I would recommend sticking with basic delegate patterns like creating new `Action` and `Func` passing method as argument and avoid more complicated API like `Delegate.CreateDelegate`. In your case you seem to create such a delegate that has its declaration signature different from the invocation one.
> 
> If you can extract this delegate invocation pattern into a standalone repro case, I can look at it.

thank you for reply, can you give me the issue you solving past. I will check it.

**Comment by BrzVlad** [comment]
Can't really find a good candidate fix. https://github.com/mono/mono/pull/12762/ is what I would have expected to fix your issue based on the crash, but if your mono version is correct, then you already have this fix. I'd really suggest to see if you have any `CreateDelegate` in your code and see if removing it fixes the issue, at least to have that confirmation.

**Comment by vargaz** [comment]
Its possible that some delegate wrappers are not placed in the correct image/image set.

**Comment by srxqds** [comment]
> Its possible that some delegate wrappers are not placed in the correct image/image set.

I also think so, but I found the delegate wrappers always save with MonoImage not ImageSet, this case sholud with ImageSet.

Can you try to solving it?

**Comment by srxqds** [comment]
> Can't really find a good candidate fix. #12762 is what I would have expected to fix your issue based on the crash, but if your mono version is correct, then you already have this fix. I'd really suggest to see if you have any `CreateDelegate` in your code and see if removing it fixes the issue, at least to have that confirmation.

This is used by RuntimePropertyInfo:
https://github.com/mono/mono/blob/735489b10bc6f839ddde7d8debea92c70d506b67/mcs/class/corlib/System.Reflection/RuntimePropertyInfo.cs#L395

**Comment by srxqds** [comment]
does **delegate_bound_static_invoke_cache** move to wrapp_caches?
 https://github.com/mono/mono/blob/07febe2bb0e7fbd9abc461090762420f0115fe79/mono/metadata/metadata-internals.h#L505

so that it can use between with MonoImage and MonoImageSet?

@vargaz

**Comment by vargaz** [comment]
The Getter () method is when the crash happens, its probably not the method with the problem. Does your app uses Delegate.CreateDelegate () to create 'bound delegates', i.e.:
```
public delegate void D3();

public static void M2(string s) {}

Delegate.CreateDelegate(typeof(D3), "Hello", M2);
```

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/19766

Not sure this will fix the problem.

**Comment by srxqds** [comment]
> #19766
> 
> Not sure this will fix the problem.

we had modify and fixed the problem.
