### ISSUE TITLE
Can't run .NET Core 3.1 WinForms apps on Linux

### ISSUE THREAD

**Issue by ekolis** [mono/mono#19752]
## Steps to Reproduce

1. Create a .NET Core 3.1 WinForms app in Visual Studio.
2. Build the app.
3. Copy it to a Linux machine.
4. Run the app using Mono.

### Current Behavior

Error message:

> Cannot open assembly 'CoreFormsAppExperiment.exe': File does not contain a valid CIL image

### Expected Behavior

The app runs. I expect this to work because Mono can run .NET Framework WinForms apps, so why not .NET Core?

## On which platforms did you notice this

Linux (Ubuntu)

**Version Used**:

6.8.0.105

## Stacktrace

N/A

**Comment by Disidente** [comment]
I think you just started with Mono. 

Mono is not Net Core!
Mono isn't Net Framework (for Windows...) either. Although it looks a lot like it, but without "Windows!!!" ;-P

It is only supported at the Language level (C# 7.x), not with Forms (Windows Applications). 

I suggest you install the mono-develop package in your Linux distribution, you will be able to develop and use Forms, but with GTK+. Not with WinForms! 
(It's similar but not the same)

**Comment by ekolis** [comment]
Really? I swear I used to be able to run WinForms apps on Mono... was that feature removed?

**Comment by akoeplinger** [comment]
You can run WinForms apps built against .NET Framework on Mono.
.NET Core's WinForms is different so it won't work.

**Comment by ekolis** [comment]
I see; that's disappointing. Are there plans to add support for .NET Core WinForms to Mono, or will I have to stay on Framework or try some other UI framework (such as Xamarin) if I want to port to Core? (Xamarin works with GTK#, right?)

**Comment by akoeplinger** [comment]
It's kind of the other way round, the .NET Core WinForms implementation would need to be made cross-platform (right now it's Windows-only and that's why it crashes on Mono on Linux)

There are now plans on the Mono our side to do that right now.

**Comment by davidbuckleyni** [comment]
This has never been the point he hence the name space winforms
