### ISSUE TITLE
[netcore] Split AssemblyBuilder into AssemblyBuilder+InternalAssembly

### ISSUE THREAD

**Issue by alexischr** [mono/mono#19775]
CoreCLR uses a class `InternalAssemblyBuilder`, separate from `AssemblyBuilder`. `InternalAssemblyBuilder` is the type of object returned when `DefineDynamicAssembly` is called.  `AssemblyBuilder` proxies mosts of its calls to that object.

The rationale is detailed here: https://github.com/dotnet/runtime/blob/5c667210d0f41b8e0ba94eeee2c29eb3d07bb0f0/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/Emit/AssemblyBuilder.cs#L35-L50

**Comment by vargaz** [comment]
Does 'trusted code' still exist in net5 ?

**Comment by marek-safar** [comment]
I don't think so, this separation looks like code from framework which has not been cleaned up

**Comment by alexischr** [comment]
The type mismatch is the only problem, see https://github.com/dotnet/runtime/pull/36367/. So far it's been okay unsafe-casting AssemblyBuilder to RuntimeAssembly (they have the same memory layout) and avoiding introducing this proxy. I will close unless this becomes a problem again
