### ISSUE TITLE
Running llvm/build.mk in a WSL environment will segfault

### ISSUE THREAD

**Issue by andy-noisyduck** [mono/mono#19784]
## Steps to Reproduce
Run a `make` of `llvm/build.mk`. For example (notice `-j1`) ....

```
make -j1 -C ~/mono-2019-12/llvm -f build.mk install-llvm LLVM_BUILD=~/mono-configs/llvm-llvm64 LLVM_PREFIX=mono-installs=~/llvm-llvm64 LLVM_CMAKE_ARGS=
```

Wait for enough process to spawn to crash (or observe ram, or number of `make` sub-processes). On my platform
`$ ps aux | grep make | wc -l` reports >400.

### Current Behavior
The build script will spawn a large number of `make` sub-processes until all memory is exhausted and the compiler begins segfaulting. On my platform I get to around 400 sub-makes, and around 64GB of memory used before the faults start.

I believe this was introduced by https://github.com/mono/mono/commit/4728cec01fc490b850607a161342ee0927d5c057 which added the `-j` flag for unlimited parallel jobs. Changing to a fixed number of jobs (e.g. `-j8` on my platform) fixes the problem.

Given that this change was 6 months ago and no one else has reported this issue (at least, that I can find), I suspect that it might be WSL specific. I am not familiar enough with sub-make communication to know if the default behavior of `-j` includes inheriting the max jobs from the parent make. If this is meant to be the case, then it would seem that method of communication is not working under WSL.

WSL also does a bunch of other funky stuff around load average (open issues in the WSL repo suggest it's hardcoded), so specifying `-l` also doesn't seem to help in this case.

Not sure whether this bug report should be for WSL, or here, or probably both.

### Expected Behavior
Build process should have enough sensible defaults to not crash.

## On which platforms did you notice this
Ubuntu 20 via WSL 2 on Win 10

[ ] macOS
[x] Linux
[x] Windows

**Version Used**:
Built from the 2019-12 branch

**Comment by akoeplinger** [comment]
Hmm we usually compile with Ninja so it's likely that nobody noticed that issue. I'd be happy to accept a PR which improves this.

You can use something like this:

```Makefile
CPU_COUNT := $(shell getconf _NPROCESSORS_ONLN || echo 2)

build-llvm: configure-llvm
	DESTDIR="" $(if $(NINJA),$(NINJA),$(MAKE) -j$(CPU_COUNT)) -C $(LLVM_BUILD)
```
