### ISSUE TITLE
Fail to build newer Visual Studio project

### ISSUE THREAD

**Issue by guoyunhe** [mono/mono#19790]
## Steps to Reproduce
```
git clone git@github.com:Ryujinx/Ryujinx.git
cd Ryujinx
xbuild
```
### Current Behavior

```
Ryujinx.csproj: error : /home/abuild/rpmbuild/BUILD/ryujinx-0~git20200516/Ryujinx/Ryujinx.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
...
```

### Expected Behavior

Should build successfully

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
6.8.0

## Stacktrace

```
Please paste the stack trace here if available.
```

## See also

https://stackoverflow.com/a/42509354/4699409

**Comment by akoeplinger** [comment]
You're using the deprecated xbuild to build the project, please switch to `msbuild`.

**Comment by guoyunhe** [comment]
msbuild isn't available in official openSUSE repository. It requires a lot of network download during build process so it cannot be packaged...

**Comment by akoeplinger** [comment]
Then your only other options are to use classic .csproj or install .NET Core and build with that: https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-opensuse15
