### ISSUE TITLE
Regression in mono 6.8 creates deadlock in SslStream

### ISSUE THREAD

**Issue by Odirb** [mono/mono#19797]
## Steps to Reproduce

A recent change in SslStream create some deadlocks in one of our products. The problem is reproductible with this test project : https://github.com/Odirb/BugSuperSocketMono

1. Create a WebSocketServer using SuperSocket
2. Inside NewMessageReceived event, send a response to the client on a different thread

SuperSocket 1.6.6.1 source code hang on a call to BeginWrite :
```
        protected override void SendAsync(SendingQueue queue)
        {
            try
            {
                var item = queue[queue.Position];
                m_Stream.BeginWrite(item.Array, item.Offset, item.Count, OnEndWrite, queue);
            }
            catch (Exception e)
            {
                LogError(e);
                OnSendError(queue, CloseReason.SocketError);
            }
        }
```

### Current Behavior
The test project hang, client websocket never receive it response.

### Expected Behavior
Websocket client receives the response, program didn't hang.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[X] Windows

**Version Used**:
 Mono JIT compiler version 6.8.0.123 (2019-10/1d0d939dc30 Thu Mar 12 23:19:08 EDT 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

This problem seems very similar to this issue https://github.com/mono/mono/issues/18865, but it is not fixed with mono 6.10 nightly build that is supposed to include the fix.

You can also notice that this test program works perfectly with mono 6.6.0

**Comment by michaldobrodenka** [comment]
I would try 6.13 night builds

**Comment by Odirb** [comment]
Thanks you, with 6.13 it works!
