### ISSUE TITLE
Hover over a List of complex type doesn't show the properties properly

### ISSUE THREAD

**Issue by mkArtak** [mono/mono#19810]
I have a Blazor WASM 3.2 app.
When debugging it in VS 16.7 Preview 1, and hovering over a List<FactorInfo> in my case, I see the `Count` property not show it's value, rather than only the type:
![image](https://user-images.githubusercontent.com/7347708/82413070-960d1d80-9a29-11ea-9f2e-289eaf63fabf.png)

**Comment by lewing** [comment]
Should be fixed in https://github.com/mono/mono/pull/19726

@radical can you verify?

**Comment by tqiu8** [comment]
<img width="1316" alt="Screen Shot 2020-06-08 at 12 06 50 PM" src="https://user-images.githubusercontent.com/16296328/84053862-83c73500-a980-11ea-9f16-f201bb43868d.png">

Now working with latest runtime build and debug proxy.

**Comment by radical** [comment]
Verified as fixed by @tqiu8, so closing this.
