### ISSUE TITLE
XSP4 SSL doesn't seem to work on linux

### ISSUE THREAD

**Issue by panManfredini** [mono/mono#19816]
Hi all,

I'm following the instructions reported on [this page](https://www.mono-project.com/docs/web/using-clientcertificates-with-xsp/), the server starts but does not use the certificate, the connection is not secure. I'm not sure what I'm doing wrong, please let me know if there is anything I'm missing.

## Steps to Reproduce

```bash
makecert -r -n "CN=Test CA" -sv root.key root.cer
certmgr --add -c Trust root.cer
makecert -iv root.key -ic root.cer -eku 1.3.6.1.5.5.7.3.1 -n "CN=Test CA" -p12 pollux.p12 s3kr3t
xsp4 --https --port 4433 --p12file pollux.p12 --pkpwd s3kr3t
```

**Output:**

```bash
Warning: unparsed command line arguments: --https 
Warning: unparsed command line arguments: --https 
xsp4
Listening on address: 0.0.0.0
Root directory: ~/work/mono_ssl_test
Listening on port: 4433 (non-secure)
Hit Return to stop the server.
```

It seems is not accepting the "--https" flag, but it is in the manual, so, am I missing something?

## On which platforms did you notice this

[ ] macOS
[x] Linux  - Ubuntu 18.04
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.8.0.105
xsp4 Mono.WebServer2.dll 0.4.0.0

### installed libraries:
**mono-devel  mono-complete  ca-certificates-mono  mono-xsp4**

Thanks a lot!
cheers

**Comment by akoeplinger** [comment]
We removed the TLS authentication stack that xsp was using for this in Mono: https://github.com/mono/mono/pull/17391

My recommendation would be to use a reverse proxy like nginx/apache in front of xsp instead for TLS since those are much more suitable to modern day TLS requirements.

I'll update the docs page.
