### ISSUE TITLE
[Wasm] PGAOT and AOT Compilation failed for method 'System.Threading.Tasks.Task System.Net.Http.HttpContent:LoadIntoBufferAsync (long,System.Threading.CancellationToken)'.

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#19824]
##  Steps to Reproduce

A while back when building a project with FullAOT, AOTing a method that contained an exception filter would show an error message saying that compiling the method failed.

When building with PGAOT, no errors appears during build, but at runtime, using the HttpClient fails with the following:

```
AOT Compilation failed for method 'System.Threading.Tasks.Task System.Net.Http.HttpContent:LoadIntoBufferAsync (long,System.Threading.CancellationToken)'.
```

Is there a way to flag such methods to be excluded from AOT ?

**Version Used**: https://github.com/mono/mono/commit/cec64d9b7f4c0ca478f2913dacb766d8ff092d61

**Comment by lewing** [comment]
You can manually exclude them by modifying the aot profile using aprofutil.  You can also try out the exception filter rewriting work in https://github.com/mono/mono/pull/19400

cc @kg

**Comment by jeromelaban** [comment]
This issue is fixed in net7.0
