### ISSUE TITLE
Timer in Blazor WebAssembly

### ISSUE THREAD

**Issue by Schoch85** [mono/mono#19827]
As I know, if I want to call a method in Blazor WebAssembly every x seconds then I have to use the timer class, implemented somehow like this:

var startTimeSpan = TimeSpan.Zero;
var periodTimeSpan = TimeSpan.FromSeconds5);

var timer = new System.Threading.Timer((e) =>
{
    MyMethod();   
}, null, startTimeSpan, periodTimeSpan);

The problem is I can't get rid of the timer after usage. I tried these things:
timer.DisposeAsync();
timer = null;

The timer is always still active. When I open the same page again and again, every time a new timer is created. Now I changed to JavaScript interop, there I can use the function "clearInterval(timer)" to get rid of it. 

How can I get rid of the timer in native Blazor?

**Comment by kjpou1** [comment]
Just out of curiosity does this happen in all browsers or certain ones?

**Comment by Schoch85** [comment]
OK I have tested it again with a new Project and different Browsers.
It works as expected, seems this was a problem with a faulty project.

**Comment by Schoch85** [comment]
OK I have tested it again with a new Project and different Browsers.
It works as expected, seems this was a problem with a faulty project.

**Comment by Schoch85** [comment]
OK I have tested it again with a new Project and different Browsers.
It works as expected, seems this was a problem with a faulty project.
