### ISSUE TITLE
Future of Mono Tooling After .NET 6 Merge?

### ISSUE THREAD

**Issue by nkosi23** [mono/mono#19834]
Mono has a mature tooling suite that is with many regards well ahead of what .NET Core (and even the .NET Full Framework) have had. I have in mind tools such as the C# REPL, or even the many runtime options of Mono (AOT, LLVM, etc...).

i am worried that the ecosystem of tools around mono could be dropped as Mono is rebranded and integrated with .NET Core. Can you guarantee that this ecosystem of tools will not be dropped at least until feature parity is achieved? We are quite invested in leveraging the scripting capabilities introduced by the C# REPL and this is just one example.

There is also a platform support concern adding to this service continuity concern. Mono has been working fine on FreeBSD since 2002  (even before the 1.0 release has been shipped). Mono is stable and mature on this platform at this point, however to this day .NET Core still does not have  FreeBSD support (managed libraries still cannot be built, and there is still no official FreeBSD port):

https://github.com/dotnet/coreclr/blob/master/Documentation/building/freebsd-instructions.md

My goal is not to discuss .NET Core progress but just to highlight that this is also another reason, it would be quite reassuring to see mono binaries to continue to stick around for the next 5 to 10 years until the situation with .NET Core becomes credible. 

The continuous availability of Mono's tooling is essential, both with regards to the tools/capabilities that are unique to Mono, and with regard to platform support. Microsoft has a reputation for treating backward compatibility seriously, and here this is one of these moments. It would be critical not to rush the transition to .NET 6 for the reasons mentioned in this post.

**Comment by marek-safar** [comment]
We have no plan to remove existing tooling as it exists today. What and when will be ported to .NET Core like is a different matter and if you are missing Mono tool on .NET Core or there is no equivalent available please create an issue at dotnet/runtime
