### ISSUE TITLE
Support for WebAssembly preview APIs in the Mono wasm runtime?

### ISSUE THREAD

**Issue by cveld** [mono/mono#19835]
I was wondering if there is any way now from .NET consumer code that runs on top of the mono wasm runtime to address the WebAssembly preview APIs in a way Rust web-sys is already doing? 

See this Rust WebAssembly example: https://rustwasm.github.io/wasm-bindgen/examples/2d-canvas.html

E.g. from Rust WebAssembly code they get the Window object:
`let document = web_sys::window().unwrap().document().unwrap();`

These html5 interop apis are baked into the Rust web_sys library.

**Comment by marek-safar** [comment]
We have plans to address this in the future - #19650
