### ISSUE TITLE
Blazor wasm not working on Safari IOS 13.5

### ISSUE THREAD

**Issue by rafaelguinho** [mono/mono#19848]
Showing the message "This browser does not support WebAssembly." on console.

**Comment by Stryxus** [comment]
Nothing can be done. This is the browsers lack of support. This isnt a Mono issue.

**Comment by jaykrell** [comment]
Huh? Sounds kinda right, but it was working on earlier 13.x.
There was the stack problem, but we fixed it.
Did Apple pull support overall from 13.x???
