### ISSUE TITLE
python ImportError: undefined symbol: __cxa_begin_catch

### ISSUE THREAD

**Issue by Inetov** [mono/mono#19840]
I'm trying to run [pythonnet](https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX) on Debian 9. I have installed mono as dependency.

## Steps to Reproduce
Following the instructions I installed:
apt install mono-devel
apt install clang
apt install libglib2.0-dev
python3.7 -m pip install wheel
python3.7 -m pip install pythonnet

next I launched:
```
18:32:01 root@my-test-host [/tmp/test/my_python_project]# python3.7
Python 3.7.6 (default, Jan 24 2020, 14:19:34)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/libmonosgen-2.0.so.1: undefined symbol: __cxa_begin_catch
>>>
```
All logs: [pythonnet_logs.txt](https://github.com/mono/mono/files/4678032/pythonnet_logs.txt) (but it's in Russian)

I found a [similar error](https://github.com/mono/mono/issues/16829), but I don't understand what can help me from there.

### Current Behavior

Getting error when try `import clr` (pythonnet):
/usr/lib/libmonosgen-2.0.so.1: undefined symbol: __cxa_begin_catch

## On which platforms did you notice this

Debian GNU/Linux 9.6 (stretch)

**Version Used**:

6.8.0.123

**Comment by akoeplinger** [comment]
Sounds like a duplicate of https://github.com/mono/mono/issues/19628

**Comment by Inetov** [comment]
> Sounds like a duplicate of #19628

maybe so, but is there a workaround or advice for me?

**Comment by akoeplinger** [comment]
Hm I don't think so unless you can recompile pythonnet using a C++ compiler.

**Comment by Inetov** [comment]
@akoeplinger @filmor Is this a problem on pythonnet side?

**Comment by filmor** [comment]
Can you try the current master of pythonnet? We changed the setup-routines to use a C++ compiler for the module, that should do the trick.

**Comment by Inetov** [comment]
> current master of pythonnet

yes! it works with `pythonnet-2.4.1.dev0`!
thanks guys
