### ISSUE TITLE
[Wasm] tuner generates invalid table for sqlite3_config

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#19869]
##  Steps to Reproduce

```csharp
[DllImport("e_sqlite3", CallingConvention = CallingConvention.Cdecl, EntryPoint = "sqlite3_config", ExactSpelling = true)]
public static extern int sqlite3_config_none(int op);

[DllImport("e_sqlite3", CallingConvention = CallingConvention.Cdecl, EntryPoint = "sqlite3_config", ExactSpelling = true)]
public static extern int sqlite3_config_int(int op, int val);

[DllImport("e_sqlite3", CallingConvention = CallingConvention.Cdecl, EntryPoint = "sqlite3_config", ExactSpelling = true)]
public static extern int sqlite3_config_log(int op, callback_log func, IntPtr pvUser);
```

For this C signature:
```c
SQLITE_API int sqlite3_config(int, ...);
```

### Current Behavior

The compilation fails as there are three functions named `sqlite3_config` in `pinvoke-table.h`. 

### Expected Behavior

The compilation succeeds, and all three functions can be invoked through P/Invoke.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**: dcfa0ec293498f316a805679f40f23059581fa7c

**Comment by vargaz** [comment]
Not sure that vararg functions can be called from c#, especially not on webassembly, which requires exact signatures, so every function needs to have 1 signature.

**Comment by jeromelaban** [comment]
I'm wondering as well. How does mono work in that case in other targets ?

**Comment by vargaz** [comment]
On other platforms, the calling convention allows the same function to be called with different signatures.

**Comment by vargaz** [comment]
We can add a better error message for this through.

**Comment by jeromelaban** [comment]
At runtime, or compile time ?

**Comment by vargaz** [comment]
Compile time.

**Comment by jeromelaban** [comment]
I wonder how this works though, because this C code compiles properly. Does LLVM do some kind of special magic with regards to varargs ?

**Comment by vargaz** [comment]
In wasm+c, you can't create a function pointer to a function, cast it to another type, and call it, which is what pinvoke does.

**Comment by jeromelaban** [comment]
I see. I'm looking for a way for this to fail at runtime instead of compile time, so that at least the existing SQLite nuget packages builds, but may fail at runtime for some very narrow scenarios.

**Comment by jaykrell** [comment]
emscriptem does treat varargs specially, yes.
It passes a pointer to some locals or something.
It also maintains a stack.
i.e. it is effectively emulated.
WebAssembly does not natively support varargs.

**Comment by vargaz** [comment]
It might be possible to do that.

**Comment by vargaz** [comment]
Looked at it, it looks pretty compilated to detect this at runtime, the pinvoke lookup code only looks up using names.

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/19873

**Comment by vargaz** [comment]
So with that PR, we will print a warning, and error out at runtime if one of the conflicting declarations is called.

**Comment by jeromelaban** [comment]
Thanks for the update! It will definitely help running applications this way.
