### ISSUE TITLE
Running OctoPack causes System.EntryPointNotFoundException: GetDiskFreeSpaceEx

### ISSUE THREAD

**Issue by PapoyEdits** [mono/mono#19861]
Hi, I’m currently in the process of migrating the CI/CD process of one of our .NET Framework Web Application solutions from TeamCity (which runs on Windows) to Jenkins (which runs on RHEL).
We’ve gotten as far as being able to build the solution successfully using Mono. The problem we’ve encountered is when running OctoPack as it crashes.

I’ve created a post on Octopus's help forum about this as well since this sort of falls in between Mono and OctoPack.
https://help.octopus.com/t/msbuild-octopack-causes-octopack-error-oct-151917342/25161

## Steps to Reproduce

1. Create a new Empty Project (.NET Framework) with simple Hello World main class
2. Add OctoPack 3.6.4 to packages.config
3. Add reference to OctoPack.Tasks in csproj
`<Reference Include="OctoPack.Tasks">
  <HintPath>..\packages\OctoPack.3.6.4\build\OctoPack.Tasks.dll</HintPath>
</Reference>`
4. Import OctoPack.targets in csproj
`<Import Project="..\packages\OctoPack.3.6.4\build\OctoPack.targets" Condition="Exists('..\packages\OctoPack.3.6.4\build\OctoPack.targets')" />`
5. Run `mono nuget restore SOLUTION` and
`msbuild SOLUTION /t:Rebuild /p:Configuration=Release /p:RunOctoPack=true /p:OctoPackPackageVersion=VERSION`

Zip-file containing the project-files
[octopack-test.zip](https://github.com/mono/mono/files/4689405/octopack-test.zip)

### Current Behavior

The build/packaging crashes with the following error:

> MSBUILD : OctoPack error OCT-151917342: GetDiskFreeSpaceEx assembly:<unknown assembly> type:<unknown type> member:(null) [/home/jenkins/workspace/myproject/test/Project.Web/Project.Web.csproj]
> MSBUILD : OctoPack error OCT-151917342: System.EntryPointNotFoundException: GetDiskFreeSpaceEx assembly:<unknown assembly> type:<unknown type> member:(null) 

### Expected Behavior

Expected to run OctoPack without error and to produce a .nupkg

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.8.0.123 (tarball Tue May 12 15:15:28 UTC 2020)

Mono MSBuild
Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

## Stacktrace

> "/home/jenkins/workspace/octopack-test_pipeline_develop/Project1.sln" (Rebuild target) (1) ->
> 16:35:31  "/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj" (Rebuild target) (2) ->
> 16:35:31  (OctoPack target) -> 
> 16:35:31    MSBUILD : OctoPack error OCT-151917342: GetDiskFreeSpaceEx assembly:<unknown assembly> type:<unknown type> member:(null) [/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj]
> 16:35:31    MSBUILD : OctoPack error OCT-151917342: System.EntryPointNotFoundException: GetDiskFreeSpaceEx assembly:<unknown assembly> type:<unknown type> member:(null) [/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj]
> 16:35:31  MSBUILD : OctoPack error OCT-151917342:   at (wrapper managed-to-native) OctoPack.Tasks.Util.OctopusPhysicalFileSystem.GetDiskFreeSpaceEx(string,ulong&,ulong&,ulong&) [/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj]
> 16:35:31  MSBUILD : OctoPack error OCT-151917342:   at OctoPack.Tasks.Util.OctopusPhysicalFileSystem.EnsureDiskHasEnoughFreeSpace (System.String directoryPath, System.Int64 requiredSpaceInBytes) [0x00000] in <fce00e62136a41d4b1c2afa3f3802571>:0  [/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj]
> 16:35:31  MSBUILD : OctoPack error OCT-151917342:   at OctoPack.Tasks.Util.OctopusPhysicalFileSystem.EnsureDiskHasEnoughFreeSpace (System.String directoryPath) [0x00000] in <fce00e62136a41d4b1c2afa3f3802571>:0  [/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj]
> 16:35:31  MSBUILD : OctoPack error OCT-151917342:   at OctoPack.Tasks.CreateOctoPackPackage.CreateEmptyOutputDirectory (System.String name) [0x00041] in <fce00e62136a41d4b1c2afa3f3802571>:0  [/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj]
> 16:35:31  MSBUILD : OctoPack error OCT-151917342:   at OctoPack.Tasks.CreateOctoPackPackage.Execute () [0x00040] in <fce00e62136a41d4b1c2afa3f3802571>:0  [/home/jenkins/workspace/octopack-test_pipeline_develop/Project1/Project1.csproj]

Build Log: [logs.txt](https://github.com/mono/mono/files/4689459/logs.txt)

**Comment by filipnavara** [comment]
This is OctoPack issue, not Mono issue. It uses P/Invoke to call API that is available only on Windows.

**Comment by PapoyEdits** [comment]
@filipnavara yeah, sort of figured it was more on their end. The response from their side was that running on Linux isn't something they support or test, so I guess we'll look into an alternate solution. 
Thanks for your response!
