### ISSUE TITLE
Mono CIL REPL

### ISSUE THREAD

**Issue by marto1** [mono/mono#19862]
Hi,

I'm searching for a Mono CIL REPL to try to learn more about .NET. I only found:  https://www.mono-project.com/docs/tools+libraries/tools/repl/ , but can't see an option to execute CIL instructions instead.

Is there another tool that could maybe help me if it's not possible with `csharp`? Thanks!

**Comment by akoeplinger** [comment]
We don't have a REPL that would allow you to run IL instructions directly and I'm not aware of one in the wider .NET ecosystem.

I guess you could build one yourself by using the DynamicMethod APIs:  https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-define-and-execute-dynamic-methods

**Comment by marto1** [comment]
Alright, thank you for the quick response. I'll keep digging.
