### ISSUE TITLE
Centos 7 - [Errno 14] curl#6 - "Could not resolve host: download.mono-project.com; Unknown error"

### ISSUE THREAD

**Issue by acaciochinato** [mono/mono#19877]
## Steps to Reproduce

1. yum update

![err](https://user-images.githubusercontent.com/60407483/83267397-89f82d00-a19a-11ea-83a4-ee782e4f8f38.png)

### Current Behavior

Can't update mono

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.8.0.123 

The problem started a few days a go. I notice that there's a thread closed with this problem but the link provided in the ticket is broken.

**Comment by akoeplinger** [comment]
Are you still seeing this? It doesn't look like something we control since it looks like it's a DNS problem.

**Comment by acaciochinato** [comment]
Hi! Yes, I'm still having this issue.

**Comment by akoeplinger** [comment]
It looks like an issue with DNS in your network, tools on the internet can resolve the domain fine: https://mxtoolbox.com/SuperTool.aspx?action=a%3adownload.mono-project.com&run=toolpage
