### ISSUE TITLE
Blazor Console.WriteLine color

### ISSUE THREAD

**Issue by pranavkm** [mono/mono#19933]
---
**Issue moved from dotnet/aspnetcore#22637**
- Please respond to @imtrobin.

---

_From @imtrobin on Sunday, June 7, 2020 2:59:55 AM_

Hi, I like to ask for color in console output e.g

```
Console.ForegroundColor = consoleColor;
Console.WriteLine (message);
```
The javascript console.log can do colors via console.log (%cmessage", "color: blue");

**Comment by lewing** [comment]
We don't plan to implement any extended console features for wasm.  It would be an interesting project.
