### ISSUE TITLE
[Wasm] Support for MonoPInvokeCallback

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#19944]
## Steps to Reproduce

The following method cannot be used ([Source](https://github.com/mono/SkiaSharp/blob/d16fd524b0e4c8715fc89abaca3ccfd6fb103b93/binding/Binding/SKAbstractManagedStream.cs#L85)):

```csharp
[MonoPInvokeCallback (typeof (SKManagedStreamReadProxyDelegate))]
private static IntPtr ReadInternal (IntPtr s, void* context, void* buffer, IntPtr size)
{
	var stream = DelegateProxies.GetUserData<SKAbstractManagedStream> ((IntPtr)context, out _);
	return stream.OnRead ((IntPtr)buffer, size);
}
```

when marshaled to native code as follows:

```csharp
delegates = new SKManagedStreamDelegates {
	fRead = ReadInternal,
};
#endif

SkiaApi.sk_managedstream_set_procs (delegates);
```

**Version Used**: fdb5e61a5b6982cd7c6f5afb5933e0db0c1d8948

**Comment by vargaz** [comment]
How does it fail ? Also, is this with AOT or the interpreter ?

**Comment by jeromelaban** [comment]
At this point, the current mono build from the CI returns the same function pointer for all methods marshaled this way, and invoking the function from unmanaged code fails with mismatched parameters.

I'm working around this in a custom mono build using this: 
`EXTRA_EXPORTED_RUNTIME_METHODS` with `'addFunction'` and `-s ALLOW_TABLE_GROWTH=1`, and manual `addFunction` invocations to get pointers to javascript proxy functions.

**Comment by jeromelaban** [comment]
And I think it's on both interpreter and AOT.

**Comment by vargaz** [comment]
Not sure how this can be fixed. The native code expects a function pointer which needs to transfer control to the interpreter, which means it needs to be unique wrt to the method it will invoke, but wasm doesn't have support for generating assembly trampolines/thunks etc. at runtime. Maybe we need to pregenerate these thunks based on the MonoPInvokeCallback attribute.

**Comment by vargaz** [comment]
The reason the function pointer are all the same is because they point to the no_llvmonly_interp_method_pointer function which will assert when called, but because of the different signatures, wasm aborts before it can be called.

**Comment by mattleibow** [comment]
What happens with iOS? Isn't this a similar case and the reason we use the attribute? If I recall, this is just for the iOS world, so maybe the same thing is for WASM?

**Comment by vargaz** [comment]
iOS doesn't use the interpreter by default, its mainly AOT, so this code path is not hit.

**Comment by mattleibow** [comment]
But, will the code that @jeromelaban posted (https://github.com/mono/mono/issues/19944#issuecomment-642004492) work in AOT? Or is this a case of either AOT or the JS interop with interpreter?

**Comment by vargaz** [comment]
The AOT case should work out of the box, the interpreter case needs that workaround.

**Comment by vargaz** [comment]
So to implement complete support for this in the interpreter would require the pinvoke generator to know about all the marshalling conventions etc. Does Skia depend on complex marshalling i.e. passing/returning valuetypes by value etc, or does it only use simple stuff like passing/returning scalars ?

**Comment by mattleibow** [comment]
It is mostly simple. Scalars (int, float, byte), ValueTypes by reference (SKMatrix*, SKPoint*) and then pointers as either (void*, IntPtr).

All my exports are here: https://github.com/mono/SkiaSharp/blob/v2.80.0-preview.14/binding/Binding/SkiaApi.generated.cs

**Comment by lambdageek** [comment]
Related: https://github.com/dotnet/runtime/issues/38573  any two calls to `GetFunctionPointerForDelegate` anywhere in the program will trigger an assertion

**Comment by jeromelaban** [comment]
Issue implemented in dotnet/runtime
