### ISSUE TITLE
Creating a bound delegate to a virtual method without using IL

### ISSUE THREAD

**Issue by pardeike** [mono/mono#19964]
## Steps to Reproduce

The library [Harmony](https://github.com/pardeike/Harmony) (cross platform patcher and toolbox) has a helper class for reflection and other tasks accessing and calling members that are not easily accessible.

That said, I recently tried to make a wrapper for generating delegates from MethodInfo. One of its features is to call base methods and skip late bindings. This works well for non-mono environments but fails under mono.

Here is the method and the place for the workaround: [AccessTools.CreateDelegate](https://github.com/pardeike/Harmony/blob/4955e213da3e390c1fc7815a2e6d3f488a37b3af/Harmony/Tools/AccessTools.cs#L1036)

### Current Behavior

Under mono, the overwriting method is called instead of the virtual base method.

### Expected Behavior

Just as with .NET if you specify a MethodInfo of a virtual base method to a delegate, it shouldn't use the late bindings. Or at least provide an easy and fast way to do so.

Here is the test that fails if one would remove the mono workaround pointed out in the link above: [Test_AccessTools_CreateDelegate](https://github.com/pardeike/Harmony/blob/4955e213da3e390c1fc7815a2e6d3f488a37b3af/HarmonyTests/Tools/TestAccessTools.cs#L306)

And here is the travis test that failed: [Build #458](https://travis-ci.org/github/pardeike/Harmony/builds/697262485)

## On which platforms did you notice this

All mono platforms.

**Comment by pardeike** [comment]
This example
```csharp
using System;

delegate void TestDelegate(Foo foo, string s);

class Program {
	static void Main(string[] args) {
		var del = (TestDelegate)Delegate.CreateDelegate(typeof(TestDelegate), null, typeof(Foo).GetMethod("Test"));
		var instance = new Bar();
		del(instance, "hello");
	}
}

public class Foo
{
	public virtual void Test(string s)
	{
		Console.WriteLine($"Foo.Test {s}");
	}
}

public class Bar : Foo
{
	public override void Test(string s)
	{
		Console.WriteLine($"Bar.Test {s}");
	}
} 
```
prints `Bar.Test hello` instead of `Foo.Test hello`. Code [here](https://tio.run/##lZDPTsMwDMbPy1NYFYdUKn0AEBeG4MIkJJA4IA6h9bpIaTzFadE09dmLQ7vxTxx2SuTvs3@fXfF5S57GsWPrG3jcccT2UqkaHTYmIvRka3hCjjdzRd8SwZqoAI4h9XAu/soZZngI1ATTwl4tOJpoq6l9ZazXk/vlFUxoOE@WRW8CCAiuQH8n5IdPuQwoz5Ecd1uk9U9vAb5zroBZk3B5eYdxhXFDtc6SN8sl4USzXnL5CgXp8R2uTdCfmqTQB62AbIPOUZaUQQ1Kbbs3J7tMOwpBSfi51tsQO@O@zqSPV1GLtOOSPJPD8jnYiPfWoz7LZESZvLDn4R@KJIOLXyzqMQRb42kwmfQHNo4f)

I understand that it is *unusual* to call a base method from outside the overwriting method but that does not mean that there are *no* legitimate cases to do so. In our case, Harmony offers monkey patching with static methods and passes the instance to the patch and users of Harmony want to call the base method (just like the original could call it).

**Comment by pardeike** [comment]
Edited the source code example to clarify that the problem is for *bound* delegates.

**Comment by vargaz** [comment]
This got broken by
https://github.com/mono/mono/commit/7704bd1b9260d0f6434ca02a2e7341f7c94113d8
@lambdageek

**Comment by lambdageek** [comment]
Reopening until the 2020-02 backport is merged.

**Comment by pardeike** [comment]
Transparency appreciated

**Comment by lambdageek** [comment]
Fixed on 2020-02 by https://github.com/mono/mono/commit/20bb4f9a6d310d4aae1529776ff45291ed676e51
