### ISSUE TITLE
question about .net5 and support .netcore?

### ISSUE THREAD

**Issue by srxqds** [mono/mono#19968]
hi, we are using mono for game scripting with unreal engine. 
we are using 6.0.0 version. we use multiple domain for code reload, even if on ios we are modifying to support it.

we are waiting for .net5 and some .netcore feature such as **AssemblyLoadContext**, when it come out, we can upgrade the runtime.

these days I found mono is in slow progress development(the last release branch is 2020-02, other than 2020-04 or 2020-06), maybe you are focus on wasm.

is these schedule about mono to support ALC? as https://github.com/mono/mono/issues/19312 said, I think there are so many work to make it work. what progress about it now, when can it support in all support platform?

we are waiting for it.

thank you for your work!

**Comment by marek-safar** [comment]
The plan is to support ALC like features only in .NET5 mode of Mono VM.

**Comment by srxqds** [comment]
> The plan is to support ALC like features only in .NET5 mode of Mono VM.

It means the **ALC** feature will be supported on all platform when .net5 release?

**Comment by marek-safar** [comment]
Yes, ALC is not really platform-specific so it will be supported equally on all .NET5 platforms

**Comment by srxqds** [comment]
thank you
