### ISSUE TITLE
How do I get Newtonsoft.json into MonoDev so I can convert JSON to XML?

### ISSUE THREAD

**Issue by redpathdesign** [mono/mono#19997]
## Steps to Reproduce

1. code and compile a sample file (2)
2. code: 

using System;
using System.IO;
using System.Xml;
using Newtonsoft.Json;

namespace test{

    class sample {
       
        static void Main(string[] args){
            Console.Out.WriteLine("Hello...");
        string jsonStr= "{sample:red}";
	XmlDocument xml = (XmlDocument)(Newtonsoft.Json.JsonConvert.DeserializeXmlNode(jsonStr));

        }
    }
}

### Current Behavior

Compile error

### Expected Behavior

Should compile as this is a major function, also allows for the using with no error.

## On which platforms did you notice this

[x] macOS
[x ] Linux (Docker)
[ ] Windows

**Version Used**:

On Mac
Mono JIT compiler version 6.8.0.123 (2019-10/1d0d939dc30 Thu Mar 12 23:19:08 EDT 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

## Stacktrace

```
$ csc test.cs
test.cs(24,34): error CS0234: The type or namespace name 'JsonConvert' does not exist in the namespace 'Newtonsoft.Json' (are you missing an assembly reference?)

```

I see there is a DEB file 
	nupkg-newtonsoft.json.6.0.8_6.0.8+dfsg-1_all.deb
and did  a
  docker run  -it -v /Users/richardredpath/Desktop/monodev/secude:/etc/secude/  mono:latest bash
   dpkg -i ./nupkg-newtonsoft.json.6.0.8_6.0.8+dfsg-1_all.deb

to add it to the running container and yet nothing. The DEB package is at 
https://packages.debian.org/sid/nupkg-newtonsoft.json.6.0.8

**Comment by akoeplinger** [comment]
The usual way is to use NuGet to get Newtonsoft.Json: https://nuget.org/packages/Newtonsoft.Json
