### ISSUE TITLE
Apple Silicon/ARM64 Support on macOS

### ISSUE THREAD

**Issue by lemonmojo** [mono/mono#20007]
So, now that the cat's out of the bag, I guess it's time to start talking about Mono's support plans for the Apple Silicon/ARM64 transition on macOS.

**Comment by lemonmojo** [comment]
![B6890DA4-8854-454C-903F-3A075A434B94](https://user-images.githubusercontent.com/186198/85336625-34841700-b4df-11ea-9ef8-7cba2b837811.png)

Just grabbed this from the Platforms State of the Union stream. Sounds promising!

**Comment by lemonmojo** [comment]
PR with patches from Apple: https://github.com/mono/mono/pull/20014

**Comment by KosmicTask** [comment]
We use the embedded API and our app loads and runs on Apple ARM64 using the Rosetta emulator with out apparent issues. I thought that jitting might rock the boat but it seems not. Not just got to sort out the native ARM64 side of things...

**Comment by lemonmojo** [comment]
@KosmicTask Same here! Rosetta 2 is a piece of art! I haven't yet had time but will soon attempt to build mono for ARM64 using the patches from the referenced PR.

**Comment by lambdageek** [comment]
The support for Apple Silicon was added to mono `master` with https://github.com/mono/mono/pull/20166
