### ISSUE TITLE
[macos] (mono-dl-posix.c) don't probe for .dylib files using g_file_test

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#20012]
From the [macOS Big Sur 11 Beta Release notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes)

> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

So we can't use our "`g_file_test` then `dlopen`" approach on Macs anymore.

https://github.com/mono/mono/blob/master/mono/utils/mono-dl-posix.c#L87

**Comment by CoffeeFlux** [comment]
We don't do this on OSX, that code is unique to Android. I think this should still work fine on Big Sur.
