### ISSUE TITLE
Mono does not save Settings.Default values

### ISSUE THREAD

**Issue by w4mmp** [mono/mono#20055]
Hello,

Mono does not properly save a VS2019 Winforms application's Settings.Default values.   
## Steps to Reproduce

1. Run any VS Winforms application on a Raspberry Pi running Buster that user Settings.Default variables. 
2. Close the application.
3. A user.config file is created in $HOME/.local/share/<Company>/<assembly-name_Url_xxxxxxxxxxx>/user.config

### Current Behavior

The user.config file is created but contains only:
more user.config
See attached file:
[user.zip](https://github.com/mono/mono/files/4859959/user.zip)

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <userSettings />
</configuration>

### Expected Behavior

The user.config should contain all the defined Settings.Default variables such as (an example):
See attached file.
[user-correct.zip](https://github.com/mono/mono/files/4859939/user-correct.zip)
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <OmniaGUI.Properties.Settings>
            <setting name="Main_Window_Location" serializeAs="String">
                <value>264, 110</value>
            </setting>
            <setting name="Panadapter_Location" serializeAs="String">
                <value>264, 695</value>
            </setting>
            <setting name="Panadapter_Size" serializeAs="String">
                <value>800, 182</value>
            </setting>
            <setting name="Waterfall_Location" serializeAs="String">
                <value>264, 553</value>
            </setting>
            <setting name="Waterfall_Size" serializeAs="String">
                <value>800, 182</value>
            </setting>
            <setting name="Main_Window_Size" serializeAs="String">
                <value>800, 480</value>
            </setting>
            <setting name="Background_Color" serializeAs="String">
                <value>Black</value>
            </setting>
           </OmniaGUI.Properties.Settings>
    </userSettings>
</configuration>

## On which platforms did you notice this

[ ] macOS
[X ] Linux Raspian Buster
[ ] Windows

**Version Used**:
mono -V
Mono JIT compiler version 6.10.0.105 (tarball Wed Jul  1 08:49:32 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

Regards,
Ron

**Comment by cheesionz** [comment]
Thanks for raising this, we're facing the same issue.

I see #18950 is basically a duplicate of this?

**Comment by w4mmp** [comment]
Hello,
Thanks for examining the issue.  Yes, 18950 is basically the same issue.  I will close it and leave this issue open.
Regards,
Ron

**Comment by w4mmp** [comment]
Hello,
I would like to take a look at the mono source and take shot at fixing this issue.  Would someone be so kind who is  familiar with the mono source point me in the right direction?

**Comment by cheesionz** [comment]
I had a little look but the configuration code is rather complicated.

Hopefully someone more familiar with it can help.

**Comment by w4mmp** [comment]
I have now learned that Win Forms is no longer supported (see issue 20141 ).   I have developed a routine that emulates this feature of Visual Studio / Win Forms.   I am closing this issue.
