### ISSUE TITLE
help with setting up (Commands: No such file or directory)

### ISSUE THREAD

**Issue by snowowlneedshelp** [mono/mono#20162]
Hi, I'm new to Mono and I'm having trouble setting it up. I'm on a Mac and downloaded the correct version, but when I checked the path ($echo $PATH), it said this:

-bash: /Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands: **No such file or directory**

From what I've seen, it is supposed to stop at Commands. Regardless of why, the gist is that it isn't working. 
Can anyone help?

**Comment by akoeplinger** [comment]
You need to use `echo $PATH`, not `$echo`. What you're seeing is the shell trying to _run_ the value returned from the `PATH` variable which will obviously not work.
