### ISSUE TITLE
Corlib not in sync with this runtime: expected corlib string

### ISSUE THREAD

**Issue by Kettle3D** [mono/mono#20165]
## Steps to Reproduce

1. Create a console app that references a class library, both in C#.
2. Compile it with the latest version of MonoDevelop.
3. Run `mkbundle <program>.exe -o <program> --cross mono-6.0.0-ubuntu-18.04-x64 --i18n none`

### Current Behavior

Compiling produces an executeable, but when I run it on my computer with Ubuntu 20.04 and the latest version of mono-complete, it prints out this:
```
Corlib not in sync with this runtime: expected corlib string (d0aa6798-834d-11e9-b38a-3b0d70487d01) but not found or not string
Loaded from: mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
I have the latest runtime.

### Expected Behavior

I would expect that the console app would run the method contained in the DLL.

## On which platforms did you notice this

Ubuntu 20.04

**Version Used**:

```
Mono JIT compiler version 6.10.0.104 (tarball Fri Jun 26 19:38:44 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Stacktrace

I showed you the error.

**Comment by HinTak** [comment]
If you run mkbundle with `-v` , you may see that it is picking up parts from the host install rather than the cross install. I filed a bug about it some years ago, and been doing matching versions since, to avoid it.

**Comment by HinTak** [comment]
The issue I failed on this https://github.com/mono/mono/issues/10479

**Comment by Kettle3D** [comment]
Oh, okay. So should I just leave the `--cross mono-6.0.0-ubuntu-18.04-x64` bit out?

**Comment by HinTak** [comment]
I do --cross same-version these days.

**Comment by Kettle3D** [comment]
Okay, I'll try that.

**Comment by Kettle3D** [comment]
That gave me an error saying that the target SDK didn't exist.

**Comment by Kettle3D** [comment]
When I left the `--cross` bit out, it gave me this error:
```
/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__gxx_personality_v0'
/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `__cxa_end_catch'
/usr/bin/ld: /usr/lib/pkgconfig/../../lib/libmono-2.0.so: undefined reference to `typeinfo for int*'
collect2: error: ld returned 1 exit status
ERROR: [Fail] 256
```

**Comment by HinTak** [comment]
Oh, apparently 6.10 is not available from fetch-target yet?

**Comment by Kettle3D** [comment]
Nah, I tried that. I tried `6.10`, `6.10.0`, `6.10.0.0`, `ubuntu`, `debian`, `18.04`, `20.04`, `x86`, `x64`, `arm` and `i386`.

**Comment by Kettle3D** [comment]
I found Mono 6.8 support for Ubuntu 16.04, I'm trying that.

**Comment by Kettle3D** [comment]
Okay, now it says the file doesn't exist. I used `ls -la` and it came up. I opened it in Files and it showed the file, it's size and the mime type. It opened in gedit fine, but I go back to terminal and it says this:
```
kettle@LAPTOP:~/Programming/fishScript/fishScript-.NET-Standard/FS/bin$ ls
Debug  fS  Release
kettle@LAPTOP:~/Programming/fishScript/fishScript-.NET-Standard/FS/bin$ ./fS
bash: ./fS: No such file or directory
```

**Comment by Kettle3D** [comment]
Okay, I fixed it now. It's compiled for 16.04, guess that'll have to do. The reason it couldn't find it earlier seems to somehow be linked to the fact my computer's x64. Not sure why, but if it works it works.

**Comment by Kettle3D** [comment]
I guess that means this is solved!
