### ISSUE TITLE
[Wasm] RuntimeError: function signature mismatch (RuntimeError: function signature mismatch)

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#20195]
```
Unhandled dispatcher exception: RuntimeError: function signature mismatch (RuntimeError: function signature mismatch
    at Uno_UI_Windows_UI_Xaml_Controls_NavigationView_UpdatePaneTitleMargins (<anonymous>:wasm-function[7691]:0x403f39)
    at Uno_UI_Windows_UI_Xaml_Controls_NavigationView_OnApplyTemplate (<anonymous>:wasm-function[7688]:0x402572)
    at aot_wrapper_gsharedvt_out_sig_pinvoke_void_this_ (<anonymous>:wasm-function[12176]:0x5c3d11)
    at jit_call_cb (<anonymous>:wasm-function[16671]:0x64c77f)
    at dynCall_vi (<anonymous>:wasm-function[26333]:0x78a6f7)
    at invoke_vi (http://localhost:63866/package_2f70f2adac48514d70efd83f71a8604eeb7fcbee/dotnet.js:11831:5)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[18184]:0x6904be)
    at do_jit_call (<anonymous>:wasm-function[16622]:0x64b3d7)
    at interp_exec_method (<anonymous>:wasm-function[16566]:0x63d4b4)
    at interp_entry (<anonymous>:wasm-function[16608]:0x64ab1a))
```

## Steps to Reproduce

Unknown. This is the call site:
https://github.com/unoplatform/uno/blob/34fbc75998593fc9f5018fb3775a0e2b2176d0d3/src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs#L3112

This is a regression as this worked in fdb5e61a5b6982cd7c6f5afb5933e0db0c1d8948.

dotnet.wasm file: 
[dotnet.zip](https://github.com/mono/mono/files/5009120/dotnet.zip)
Aot work directory: 
[workAot.zip](https://github.com/mono/mono/files/5009126/workAot.zip)

**Version Used**: 71307187cb1

**Comment by vargaz** [comment]
Its this line:
				var buttonSize = ResourceResolver.ResolveTopLevelResource<double>(key: "PaneToggleButtonWidth", fallbackValue: c_paneToggleButtonWidth);

**Comment by vargaz** [comment]
I can't find the ResourceResolver class in any of the .bc files.

**Comment by jeromelaban** [comment]
That's very curious indeed. It's in the Uno.UI.dll assembly. I can provide you with the full workspace if that helps.

This is the Uno.UI.dll file after the linker:
[Uno.UI.dll.zip](https://github.com/mono/mono/files/5009481/Uno.UI.dll.zip)

**Comment by vargaz** [comment]
That would be helpful.

**Comment by jeromelaban** [comment]
There it is: https://nventive-my.sharepoint.com/:u:/p/jerome_laban/ERLSKdGzSt1OtU74b3kWIt8BRF3kCNxO-bUNZ1bJaQg6IQ?e=xIeJXg

**Comment by vargaz** [comment]
Looks like a profiled aot problem, the called method is not in the aot profile.

**Comment by jeromelaban** [comment]
Shouldn't the AOT compiler transition to the interpreter in that case ?

**Comment by vargaz** [comment]
Its a bug.

**Comment by vargaz** [comment]
There are multiple problems here:
- some generic instances are not AOTed even through they are in the aot profile. This is because of some weird interactions with the dedup code.
- the call should instead go to the interpreter, but it fails instead.

**Comment by jeromelaban** [comment]
@vargaz would you know if there a way around it? such as removing the profile file for the assemblies? Or is it because the profile is generated at an incorrect time ?

**Comment by vargaz** [comment]
I can't reproduce the failure itself, but it seems related to generic instances.  Maybe removing the offending method from the profile would help.

**Comment by jeromelaban** [comment]
Here's the repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug20195

It's about the invocation of :
https://github.com/jeromelaban/Wasm.Samples/blob/cf4c4219b4d4d2981fd2637a722572ac13f48749/Bug20195/OtherLibrary/Class.cs#L32 

in both the main assembly and the other assembly.
