### ISSUE TITLE
MT3001 Could not AOT the assembly

### ISSUE THREAD

**Issue by whitneyschmidt** [mono/mono#20237]
_From @groege on Thu, 06 Aug 2020 10:02:38 GMT_

### Steps to Reproduce

Build iOS Project with Debug provisioning for a iPhone device

Additional hint: When trying to use a custom aot profile on android I also get the "Could not AOT the assembly" but for another dll.

### Expected Behavior
Successful Build (or at least not the AOT error, did test the project with Android only before, this is the first iOS build)

### Actual Behavior
Build Error:
Could not AOT the assembly '<path>/CarrierMobile/CarrierMobile.iOS/obj/iPhone/Debug/device-builds/iphone8.2-13.3.1/mtouch-cathe/3-Build/CarrierMobile.Model.dll' (MT3001)

According to the info when clicking on it this should be a bug in xamarin iOS 
Therefore according to the following link I'm posting this issue.
https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#MT3001

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.7 (build 2037)
Installation UUID: 7b7318cc-9615-463f-b3c2-732e584e9e6c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000089

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.89 (2020-02/e59c1cd70f4) (64-bit)
	Package version: 612000089

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.302/Sdks
SDK Versions:
	3.1.302
	3.1.102
	3.1.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.6
	3.1.2
	3.1.1
	2.1.20
	2.1.16
	2.1.15

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-7/aca845b
Android SDK: Not found

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Build Information ===

Release ID: 807002037
Git revision: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c
Build date: 2020-07-31 04:14:15-04
Build branch: release-8.7
Xamarin extensions: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
```

### Build Logs

[BuildLog.zip](https://github.com/xamarin/xamarin-macios/files/5034065/BuildLog.zip)

### Example Project (If Possible)

I'm not allowed to share this project publicly, is it possible to PM it to someone?
If yes I'd remove the not referenced projects from the solution, zip it and PM it.
Thank you!

_Copied from original issue xamarin/xamarin-macios#9289_

**Comment by whitneyschmidt** [comment]
_From @whitneyschmidt on Thu, 06 Aug 2020 16:35:45 GMT_

@groege Thank you for filing this issue! To more forward, an example project would be great :)

The best way to privately share solution files is to create an issue in the VS dev community: https://developercommunity.visualstudio.com/spaces/8/index.html

Paste a link to that here on GH and we'll be able to direct the internal ticket to our team's area path and track it there.

After you've done that, it's possible to limit the visibility of files/comments that you upload. More info on that [here](https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2019).

We look forward to hearing back from you!

**Comment by whitneyschmidt** [comment]
_From @groege on Fri, 07 Aug 2020 13:21:30 GMT_

> @groege Thank you for filing this issue! To more forward, an example project would be great :)
> 
> The best way to privately share solution files is to create an issue in the VS dev community: https://developercommunity.visualstudio.com/spaces/8/index.html
> 
> Paste a link to that here on GH and we'll be able to direct the internal ticket to our team's area path and track it there.
> 
> After you've done that, it's possible to limit the visibility of files/comments that you upload. More info on that [here](https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2019).
> 
> We look forward to hearing back from you!

Thank you!!
I will strip the Project of all unnecessary projects and should be able to upload it to the dev community by Tuesday.

**Comment by whitneyschmidt** [comment]
_From @groege on Fri, 07 Aug 2020 14:28:45 GMT_

https://developercommunity.visualstudio.com/content/problem/1141834/mt3001-could-not-aot-the-assembly-1.html

Attached the ZIP

**Comment by whitneyschmidt** [comment]
_From @groege on Tue, 11 Aug 2020 06:17:18 GMT_

@whitneyschmidt If there is anything else I can do to speed up this process, please let me know.
Thank you!!

**Comment by whitneyschmidt** [comment]
_From @whitneyschmidt on Tue, 11 Aug 2020 22:21:25 GMT_

@groege I ran into issues with dependencies when I tried to build your project. I suspect that this is a runtime issue, not an SDK issue since the problem is at AOT time.

**Could you upload (privately) the entire bin directory of a build?**

I know that you already stripped the project, but if it's reasonable to make an even smaller and simpler sample that reproduces the issue that could be useful too.

A rough description of how our build works:

`Source Code --csc compiler--> Dll & EXE files (IL) --AOT compiler--> native executable`

The problem is that an input to the AOT compiler (CarrierMobile.Model.dll) is causing the AOT compiler to fault.

For us to investigate further, a bin download is the bare minimum we need to reproduce the issue.

From what I can see of the Developer Community thread, you solution is marked [private] and only visible internally (you can confirm this too by opening a private browsing window and viewing the thread) 👍

**Comment by whitneyschmidt** [comment]
_From @groege on Wed, 12 Aug 2020 07:02:35 GMT_

> For us to investigate further, a bin download is the bare minimum we need to reproduce the issue.

@whitneyschmidt  Uploaded the zipped bin folder at the community: https://developercommunity.visualstudio.com/content/problem/1141834/mt3001-could-not-aot-the-assembly-1.html

Thanks again!

**Comment by whitneyschmidt** [comment]
_From @groege on Wed, 12 Aug 2020 08:01:13 GMT_

>I know that you already stripped the project, but if it's reasonable to make an even smaller and simpler sample that reproduces the issue that could be useful too.

I have further stripped the project and uploaded it to the same thread.
EDIT: also added the bin folder of the iOS project

**Comment by whitneyschmidt** [comment]
_From @whitneyschmidt on Wed, 12 Aug 2020 19:33:42 GMT_

Thanks @groege! I was able to try out AOT compiling the dll and observed the following failure:

```
* Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mono/mini/aot-compiler.c:3394, condition `p2 - buf2 < 1024' not met
```

Full log here: https://gist.github.com/whitneyschmidt/7ba9e81d3c1558ed9b2bc93c3f803084

To compile the dll, I followed these steps:

- Download bin dir upload from the DevCom thread here: https://developercommunity.visualstudio.com/content/problem/1141834/mt3001-could-not-aot-the-assembly-1.html
- If anyone has trouble viewing the issue, let me know and I can look into making sure that permissions are correct
- Run command below from bin/iPhone/Debug to build `CarrierMobile.Model.dll`:

`MONO_LOG_LEVEL=debug MONO_PATH=/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=float32 --aot=mtriple=arm64-ios,data-outfile=CarrierMobile.Model.aotdata.arm64,static,asmonly,direct-icalls,interp,full,nodebug,dwarfdebug,msym-dir=Msym,outfile=CarrierMobile.Model.dll.s CarrierMobile.Model.dll`

I'm not able to build the project, but trying to compile the .dll is enough to confirm that this is a mono AOT issue, not an SDK problem.

This looks similar to https://github.com/mono/mono/issues/7637

**Comment by groege** [comment]
@vargaz Wow that was quick awesome thanks!
@whitneyschmidt  Any idea when this fix will be available for Visual Studio Mac?

**Comment by vargaz** [comment]
@whitneyschmidt xam.ios needs to pick this change up.

**Comment by whitneyschmidt** [comment]
@groege @vargaz We expect to pick up the fix in the next d16-8 preview of Xamarin.iOS/Mac.

**Comment by groege** [comment]
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.8 Preview (8.8 build 2120)
Installation UUID: cf8b9f20-e5a9-4ec3-a8af-446979359eb0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.8.0-2.20414.4+beada51586dedc46a7fe5ca381ffb10e2b177070

=== NuGet ===

Version: 5.8.0.6783

=== Xamarin Designer ===

Version: 16.8.0.471
Hash: ce5800ecd
Branch: remotes/origin/d16-8
Build date: 2020-09-02 19:21:16 UTC

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.401
	3.1.302
	3.1.102
	3.1.101
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.7
	3.1.6
	3.1.2
	3.1.1
	2.1.22
	2.1.21
	2.1.20
	2.1.16
	2.1.15

=== .NET Core 2.1 SDK ===

SDK: Not installed

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-8/b352be8
Android SDK: Not found

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.20
Hash: fdef874
Branch: remotes/origin/master
Build date: 2020-09-03 22:22:24 UTC

=== Android Device Manager ===

Version: 16.8.0.28
Hash: 8522e27
Branch: remotes/origin/master
Build date: 2020-09-03 22:22:50 UTC

=== Apple Developer Tools ===

Xcode 12.0 (17219)
Build 12A7209

=== Xamarin.Mac ===

Version: 6.22.1.23 (Visual Studio Community)
Hash: 8318026f1
Branch: d16-8
Build date: 2020-09-01 14:15:21-0400

=== Xamarin.iOS ===

Version: 13.22.1.23 (Visual Studio Community)
Hash: 8318026f1
Branch: d16-8
Build date: 2020-09-01 14:15:22-0400

=== Build Information ===

Release ID: 808002120
Git revision: 3925df4356a7f10b6951f10e0f88ceecb8e66a23
Build date: 2020-09-09 08:15:50-04
Build branch: release-8.8
Xamarin extensions: 3925df4356a7f10b6951f10e0f88ceecb8e66a23

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

@whitneyschmidt 
MT3001 Problem still persists in this Version, did I miss something?

I also tried this on Android (Visual Studio 2019 Windows) where it says in the patch notes that this fix should be included as well but it also doesn't work.
