### ISSUE TITLE
Xamarin.Android Designer Crashes with mono/mono/2020-02@66e2b840

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#20275]
The Xamarin.Android team is attempting to bump to a more recent mono: https://github.com/xamarin/xamarin-android/pull/5014

The bump includes this mono commit range: https://github.com/mono/mono/compare/83105ba22461455f4343d6bb14976eba8b0b3f39...66e2b84002f037d7fd07d399f31196f05bd19597

Unfortunately, this mono bump experiences crashes when running the Designer integration tests: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3979329&view=logs&jobId=db00894d-3ef4-5d97-073c-254fbd613a41&j=db00894d-3ef4-5d97-073c-254fbd613a41&t=379a81d4-3138-5f28-ec7b-ce4074947b64

```
=================================================================
    Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
    Native stacktrace:
=================================================================
    0x128d57058 - /Library/Frameworks/Xamarin.Android.framework/Versions/11.1.99.56/lib/xamarin.android/xbuild/Xamarin/Android/lib/host-Darwin/libmonosgen-2.0.dylib : mono_dump_native_crash_info
    0x128cf197e - /Library/Frameworks/Xamarin.Android.framework/Versions/11.1.99.56/lib/xamarin.android/xbuild/Xamarin/Android/lib/host-Darwin/libmonosgen-2.0.dylib : mono_handle_native_crash
    0x128c4e71a - /Library/Frameworks/Xamarin.Android.framework/Versions/11.1.99.56/lib/xamarin.android/xbuild/Xamarin/Android/lib/host-Darwin/libmonosgen-2.0.dylib : mono_sigsegv_signal_handler_debug
    0x7fff70cabb5d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
    0x400 - Unknown
```

@garuma *thinks* this might be due to the inclusion of: https://github.com/mono/mono/commit/2ff424be293

## Steps to Reproduce

1. Build xamarin-android using mono/mono/2020-02@66e2b840; see also https://github.com/xamarin/xamarin-android/pull/5014
2. Run the Designer integration tests.

### Current Behavior

With mono/mono/2020-02@66e2b840, the tests crash.

### Expected Behavior

With mono/mono/2020-02@83105ba2, the tests do *not* crash.  (This is the mono commit Xamarin.Android is currently using.)

## On which platforms did you notice this

- [X] macOS
- [ ] Linux
- [X] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by SamMonoRT** [comment]
cc @imhameed @naricc @BrzVlad

**Comment by BrzVlad** [comment]
I confirm this is caused by https://github.com/mono/mono/commit/2ff424be293. I think we should revert it so android bumping can continue.

For repro : 
- build xamarin/designer according to readme instructions
- build xamarin/android with mono hash in .external
- install the build xam.android package on system
- build Xamarin.AndroidDesigner.sln in VSMac
- run Xamarin.AndroidDesigner.Tests project from VSMac

**Comment by naricc** [comment]
@rolfbjarne Are you ok with reverting this change? https://github.com/mono/mono/issues/19860. It seems to be causing a larger issue than it solved.

**Comment by rolfbjarne** [comment]
@naricc yes, of course, feel free to revert that fix if it causes crashes.

**Comment by SamMonoRT** [comment]
@naricc -please re-open the original issue to pursue a better fix.

**Comment by SamMonoRT** [comment]
@jonpryor @rolfbjarne  - do you think old issue is worth revisiting now that MAUI is almost out of the door now ?

**Comment by rolfbjarne** [comment]
@SamMonoRT assuming this does not happen with the mono runtime in dotnet/runtime, I'm fine with not fixing this.

**Comment by SamMonoRT** [comment]
Don't see issues with dotnet\runtime, @naricc will verify and close with a Preview 5 build bits.

**Comment by naricc** [comment]
Not an issue in dotnet/runtime.
