### ISSUE TITLE
mono_thread_detach does not unregister thread from Garbage Collection

### ISSUE THREAD

**Issue by Boulougou** [mono/mono#20290]
I have a thread in C++ that occasionally (every a couple of minutes) invokes methods in mono runtime. Since mono runtime is rarely called, I would like to avoid blocking the thread when GC runs. Trying to achieve that I have wrapped `mono_runtime_invoke` calls around `mono_thread_attach`/`mono_thread_detach` like this:
```cpp
MonoThread* thread = mono_thread_attach(mono_get_root_domain());

... // find method, create args etc.
MonoObject* exception = nullptr;
mono_runtime_invoke(method, obj, args, &exception);

mono_thread_detach(thread);
```

But even with the thread detached, the garbage collector tries to suspend it which leads to the whole application hanging until the thread calls mono again.

Debugging through mono code it seems that `mono_thread_detach` does not call `mono_thread_info_detach`, which is the method that unregisters the thread from GC. Is there any other way to achieve this?

I usually work around this issue by creating a secondary thread that does the calls to mono, so that the original thread is never attached to the mono runtime. But in that particular case this is not possible since the C# code triggered by `mono_runtime_invoke` touches resources in GPU that are not thread safe.

**Comment by fmoraes74** [comment]
@CoffeeFlux Any plan to fix this for the next release?

**Comment by CoffeeFlux** [comment]
I'm currently planning to leave this for @lambdageek when he gets back in a couple weeks since I'm a bit busy right now, sorry. He's the most familiar with our threading and coop suspend, so once he's back you'll hopefully see a resolution for this.

**Comment by fmoraes74** [comment]
@CoffeeFlux Thanks for the update. I will be trying it out once the fix is available so that I can remove the preemptive work around.
