### ISSUE TITLE
Is Mono 5.10 missing .NET 4.5 CLR?

### ISSUE THREAD

**Issue by imranazad** [mono/mono#20311]
I'm running an F# app targeting the .NET 4.5 framework. However when I run this in Mono 5.10 I'm getting the following warning:

```
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
```
Mono 5.10 ships with .NET framework 4.7.1 so I'm rather confused that it has v4.0.30319 which is the CLR for the .NET 4.0 Framework and not any of the following CLR versions 4.0.30319.17001 to 4.0.3019.18400 for NET 4.5 framework. See here https://docs.microsoft.com/en-gb/archive/blogs/rodneyviana/identifying-the-net-version-you-are-running-2-0-4-5-4-5-1-or-4-5-2

Why does it default to running under the CLR for .NET framework 4.0 when it ships with .NET framework 4.7.1?

**Comment by lextm** [comment]
"WARNING: The runtime version supported by this application is unavailable." That means Mono cannot tell what is the runtime version of your app. First you need to check your main assembly as well as its app.config file, or share them so others can review.

**Comment by imranazad** [comment]
@lextm Ah I see. Thanks so it doesn't necessarily mean that the .NET 4.5 CLR is missing. 

In my app config I have:

`<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />`

I've inspected the main assembly using dotPeak 2020.2 and it reports the assembly as `msil, .Net Framework v4.0`

**Comment by akoeplinger** [comment]
As you probably already figured out the distinction is mainly between using the "2.0" and "4.0" versions of the CLR behavior since there were breaking changes in between. Every subsequent 4.x release was an in-place upgrade and mono mimicks this behavior so you can just ignore this warning message.
