### ISSUE TITLE
Ubuntu bionic repo failing?

### ISSUE THREAD

**Issue by drunet** [mono/mono#20343]
## Steps to Reproduce

1. apt-get update
2. 
3. 

W: Failed to fetch https://download.mono-project.com/repo/ubuntu/dists/stable-bionic/InRelease  Something wicked happened resolving 'download.mono-project.com:https' (-5 - No address associated with hostname)

### Current Behavior

When running apt-get update on Ubuntu the mono repo is not resolving.

### Expected Behavior

Updates for mono through apt repo failing.

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.10.0.104 (tarball Fri Jun 26 19:38:24 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by akoeplinger** [comment]
> Something wicked happened resolving 'download.mono-project.com:https' (-5 - No address associated with hostname)

This looks like it's an issue with DNS in your network. What happens if you run `nslookup download.mono-project.com` ?

**Comment by drunet** [comment]
Good call. I run a PiHole on my local network and whitelisted the domain and magically it works now. Had the PiHole several years and this was a first. No idea why it happened but thank you for the advice.
