### ISSUE TITLE
incorrect marshalling for pinvoke byte array return type 

### ISSUE THREAD

**Issue by UnityAlex** [mono/mono#20367]
This bug is two bugs more or less. The main problem is that mono allows users to run with incorrect marshalling which leads to the second problem which is where the debugger crashes because of it.

## Steps to Reproduce

1. Compile native plugin sample. I used: `clang -shared -fpic -fdeclspec getchars.cpp -o libgetchars.dylib` on osx
2. Compile program: `csc /debug:portable Program.cs`
3. Open Program.cs and put a breakpoint on the second `Console.ReadLine` (line 20)
4. Launch the program with the soft debugger enabled: `mono --debug --debugger-agent=transport=dt_socket,address=127.0.0.1:5004,server=y,suspend=y Program.exe`
5. Attach your favorite managed debugger, I was able to repro with both VS and Rider
6. Hit enter once in the terminal with the running mono runtime to hit the breakpoint
7. Inspect bytes array. Crash happens

getchars.h
```
#ifndef _ADD_H
#define _ADD_H

extern "C"
{
	__declspec(dllexport) unsigned char* getData_uchar();
}

#endif
```

getchars.cpp
```
#include "getchars.h"

extern "C"
{
    static unsigned char dbase64[] =
    {
        128, 128, 128, 128, 128, 128, 128
    };

    __declspec(dllexport) unsigned char* getData_uchar()
    {
        return dbase64;
    }
}
```

Program.cs
```
using System;
using System.Runtime.InteropServices;
using System.Security.Cryptography;

namespace repro_1274470_pinvoke_getbytes
{
    class Program
    {
        [DllImport("getchars.dll")]
        static extern byte[] getData_uchar();

        static void Main(string[] args)
        {
             byte[] bytes = getData_uchar();
            //byte[] bytes = new byte[10];
            //IntPtr inputBuffer = getData_uchar();
            //Marshal.Copy(inputBuffer, bytes, 0, 7);

            Console.ReadLine();
            Console.ReadLine();
        }
    }
}
```
### Current Behavior

Debugger crashes when inspecting `bytes` object

### Expected Behavior
The .Net Framework throws a `MarshalDirectiveException` on line 14 `byte[] bytes = getData_uchar();` which would be preferrable to match this. Ideally the debugger should be able to handle this gracefully and not crash as well.

## On which platforms did you notice this

[X ] macOS
[ ] Linux
[X ] Windows

**Version Used**:

Mono JIT compiler version 6.10.0.104 (2019-12/5d03a6fe116 Wed Apr 29 20:51:09 EDT 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

## Stacktrace

```
=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10aaffad9 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_dump_native_crash_info
	0x10aa97fb5 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_handle_native_crash
	0x10aaf9c56 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : altstack_handle_and_restore
	0x10ab36bf7 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : buffer_add_value_full
	0x10ab4b14e - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : add_var
	0x10ab470ac - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : frame_commands
	0x10ab3c296 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : debugger_thread
	0x10ac2e6ed - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : start_wrapper
	0x7fff71641109 - /usr/lib/system/libsystem_pthread.dylib : _pthread_start
	0x7fff7163cb8b - /usr/lib/system/libsystem_pthread.dylib : thread_start

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x11a500dc0 from 0x700009809000
Pkilling 0x700009606000 from 0x700009809000
Entering thread summarizer pause from 0x700009809000
Finished thread summarizer pause from 0x700009809000.
Failed to create breadcrumb file (null)/crash_hash_0x0

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10ab36bf7):0x10ab36be7  8b 6d 00 4d 85 ed 0f 84 81 09 00 00 49 8b 45 00  .m.M........I.E.
0x10ab36bf7  48 8b 38 f6 47 20 04 0f 85 12 08 00 00 80 7f 1a  H.8.G ..........
0x10ab36c07  00 44 8b a7 b8 00 00 00 4c 89 6d c8 0f 85 cf 09  .D......L.m.....
0x10ab36c17  00 00 44 89 e0 25 00 00 ff 00 3d 00 00 15 00 0f  ..D..%....=.....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
Abort trap: 6
```

**Comment by UnityAlex** [comment]
cc @jbevain

**Comment by UnityAlex** [comment]
Bug on Unity side for tracking: https://issuetracker.unity3d.com/issues/crash-while-inspecting-byteslist-values-of-a-dictionary-in-vs-debugger-when-using-arucounity-plugin

**Comment by lambdageek** [comment]
I think this is the code in `emit_marshal_array_ilgen` that is supposed to do something with a `byte[]` return type on a pinvoke:

https://github.com/mono/mono/blob/3c7db3b5c42a2ed9ab9b18f16a60d556e8e00604/mono/metadata/marshal-ilgen.c#L2740-L2743

So... yea... it just returns the pointer to the native array.

I'm not sure the debugger can be adequately guarded here - we expect to inspect a MonoArray and we get a pointer to some junk.  I think @thaystg did some work previously to guard the debugger from accessing invalid memory, but here the memory is valid - just not a managed object.

---

The marshalling code needs to be fixed

**Comment by vargaz** [comment]
What was the error message of the MarshalDirectiveException ?

**Comment by UnityAlex** [comment]
```
Cannot marshal 'return value': Invalid managed/unmanaged type combination.
```
Was the message content of the exception.
