### ISSUE TITLE
Preview version deployed from stable release channel

### ISSUE THREAD

**Issue by qhaas** [mono/mono#20398]
Per the [documentation page](https://www.mono-project.com/docs/about-mono/releases/), the latest stable version of mono is: `6.10.0.104`.  However, when using the stable channel apt repository for Ubuntu 18.04, 6.12.x gets deployed.

## Steps to Reproduce

1. Deploy `mono-devel` in Ubuntu 18.04 using the stable apt repository [per the documentation](https://www.mono-project.com/download/stable/)

### Current Behavior
The preview version 6.12.0 is deployed from the stable channel.
```
# apt-cache policy mono-devel | grep Candidate
  Candidate: 6.12.0.90-0xamarin1+ubuntu1804b1
# grep PRETTY /etc/os-release 
PRETTY_NAME="Ubuntu 18.04.5 LTS"
# grep bionic /etc/apt/sources.list
sources.list    sources.list.d/ 
# grep bionic /etc/apt/sources.list.d/mono-official-stable.list 
deb https://download.mono-project.com/repo/ubuntu stable-bionic main
```

### Expected Behavior

The stable version of 6.10.0.104 is deployed.

## On which platforms did you notice this

[ ] Linux

**Version Used**:

N/A

## Stacktrace

N/A

**Comment by CoffeeFlux** [comment]
cc: @directhex

**Comment by qhaas** [comment]
6.12 is now listed as the stable version, this is now OBE
