### ISSUE TITLE
Type.Namespace returns `null` for arrays of a nested type.

### ISSUE THREAD

**Issue by jpobst** [mono/mono#20420]
Context: https://github.com/xamarin/xamarin-android/issues/5127

Given this program which uses `Type.Namespace`:

```
using System;

namespace ConsoleApp2
{
	class Program
	{
		static void Main (string [] args)
		{
			var a = Array.Empty<Foo.Bar> ();
			Console.WriteLine (a.GetType ().Namespace);

			var b = Array.Empty<Bar> ();
			Console.WriteLine (b.GetType ().Namespace);
		}
	}

	public class Foo
	{
		public class Bar { }
	}

	public class Bar { }
}
```

.NET Framework prints out:
```
C:\code\temp\ConsoleApp2\bin\Debug\net472>ConsoleApp2.exe
ConsoleApp2
ConsoleApp2
```

Mono prints out:
```
C:\code\temp\ConsoleApp2\bin\Debug\net472>mono ConsoleApp2.exe

ConsoleApp2
```

That is, `Type.Namespace` is incorrectly returning `null` for arrays of a nested type.

```
Mono JIT compiler version 6.6.0 (Visual Studio built mono)
```

**Comment by CoffeeFlux** [comment]
This affects netcore as well, I'm surprised we don't have a test covering this in dotnet/runtime (or maybe we do and it's failing). cc: @lambdageek

**Comment by CoffeeFlux** [comment]
Moved to https://github.com/dotnet/runtime/issues/42633
