### ISSUE TITLE
build broken on s390x after recent commit

### ISSUE THREAD

**Issue by sharkcz** [mono/mono#20437]
Build on s390x is broken recent change to `tramp-s390x.c` in commit 9623156cfdfdfcc55230160942a45baff98083b8
````
make[4]: Entering directory '/home/jenkins/workspace/Mono/label/s390x/mono/mini'
  CC       libmini_la-tramp-s390x.lo
tramp-s390x.c: In function ‘mono_arch_get_unbox_trampoline’:
tramp-s390x.c:106:69: error: ‘m’ undeclared (first use in this function); did you mean ‘tm’?
  106 |  MonoMemoryManager *mem_manager = m_method_get_mem_manager (domain, m);
      |                                                                     ^
      |                                                                     tm
tramp-s390x.c:106:69: note: each undeclared identifier is reported only once for each function it appears in
...
````
seems the fix is to `s/m/method/`, I'll prepare a PR

CC: @vargaz @nealef

**Comment by nealef** [comment]
Tks for handling. I was just going to do a build for some cmake-related work on s390x so I'll build with your suggested fix.

**Comment by sharkcz** [comment]
I have renamed `method` to `m` to be in sync with other arches, it should be better in the long term.

**Comment by nealef** [comment]
> I have renamed `method` to `m` to be in sync with other arches, it should be better in the long term.

+1
