### ISSUE TITLE
Incorrect rounding for Math.Round(0.5)

### ISSUE THREAD

**Issue by tgjones-unity3d** [mono/mono#20449]
## Steps to Reproduce

Use this program:

``` csharp
using System;

public static class Program
{
	public static void Main()
	{
		Console.WriteLine(Math.Round(0.5));
	}
}
```

### Current Behavior

The output is

```
1
```

### Expected Behavior

The expected output is 

```
0
```

The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.math.round?view=netframework-4.8#System_Math_Round_System_Double_) for `Math.Round` says:

> If the fractional component of a is halfway between two integers, one of which is even and the other odd, then the even number is returned.

Mono 5.11.0 and .NET Core return the expected value of 0 from `Math.Round(0.5)`. Mono 6.8.0 returns 1.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**: 6.8.0

**Comment by EgorBo** [comment]
hm.. reproduces for dotnet/runtime mono as well (when argument is a constant)

**Comment by tgjones-unity3d** [comment]
Thank you for the quick turnaround!
