### ISSUE TITLE
mono_w32socket_convert_error doesn't handle ENOKEY (126) errno

### ISSUE THREAD

**Issue by RamaSpaceShip** [mono/mono#20503]
## Steps to Reproduce

1. start a Wireguard connection
2. regularly send udp messages through that connection
3. remove the peer from wireguard
4. get (Mono unknown) socket error => SIGABRT

### Current Behavior
The application ends immediately due to SIGABRT and no exception is thrown
As SIGABRT cannot be handled, there is no workaround.

### Expected Behavior
On such unknown socket error, an exception would be welcome, or SIGIO sent at most.
But using SIGABRT in such a case leaves no chance of handling any error not (yet) known by Mono.

## On which platforms did you notice this
[ ] macOS
[x ] Linux
[ ] Windows
RaspberryPi OS and Debian Buster Amd64

**Version Used**:
6.12.0.90

## Stacktrace
no stack trace

**Comment by RamaSpaceShip** [comment]
Hi Lambdageek,

I installed mono-dbg and reproduced the error and I only got:
mono_w32socket_convert_error: no translation into winsock error for (126) "Required key not available"
I will try to attached under gdb to try to get a stack trace.

**Comment by RamaSpaceShip** [comment]
Hi Lambdageek,

I got a stack trace with gdb. See attached file:
[SigabrtTrace.txt](https://github.com/mono/mono/files/5424473/SigabrtTrace.txt)

**Comment by lambdageek** [comment]
> mono_w32socket_convert_error: no translation into winsock error for (126) "Required key not available"

ah ok. that's `ENOKEY`

**Comment by RamaSpaceShip** [comment]
You changed the title because you fixed the initial error,  but the previous title was showing that there is a major issue with this.
In your post on the other thread, you indicated that SIGABRT is a too fatal response to such error.
Do you plan to convert the g_error default handling by a managed exception, or at most SIGIO?

**Comment by lambdageek** [comment]
> Do you plan to convert the g_error default handling by a managed exception, or at most SIGIO?

It would be a pretty invasive change. I added a new task to keep track of it https://github.com/mono/mono/issues/20509
