### ISSUE TITLE
Mono.WebAssembly.Sdk linker culling ConcurrentBag.TryTake() internals

### ISSUE THREAD

**Issue by AshleighAdams** [mono/mono#20531]
## Steps to Reproduce

Under a WebAssembly compiled project, call `ConcurrentBag<T>.TryTake()`:

```csharp
internal class TestClass
{
}
// ...
var bag = new ConcurrentBag<TestClass>();
bool got = bag.TryTake(out var value);

Console.WriteLine($"got: {got} value: {value}");
```

A fully working minimal example is available here: https://github.com/AshleighAdams/Mono.WebAssembly-Test

### Current Behavior

Throws a `NotSupportedException` upon calling `TryTake()`.

Tested with both NetStandard 2.0 and NetStandard 2.1 with both showing identical behavior.

### Expected Behavior

`ConcurrentBag<T>.TryTake()` internals should not be culled, and in the example above, should return false/null.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] WebAssembly

**Version Used**: Latest Mono.WebAssembly.Sdk/0.2.3

## Stacktrace

```
dotnet.js:2314 Unhandled Exception:
dotnet.js:2314 System.NotSupportedException: Linked away
dotnet.js:2314   at System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentBag_TryTakeSteals () <0x1dfa9f0 + 0x00010> in <filename unknown>:0 
dotnet.js:2314   at System.Collections.Concurrent.ConcurrentBag`1[T].TrySteal (T& result, System.Boolean take) [0x00003] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/exte…lections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:177 
dotnet.js:2314   at System.Collections.Concurrent.ConcurrentBag`1[T].TryTake (T& result) [0x00008] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/exte…lections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:105 
dotnet.js:2314   at Test.Program.Main () [0x00007] in C:\Git\Mono.WebAssembly-Test\src\Test\Program.cs:15
```

**Comment by AshleighAdams** [comment]
To add some further information, I tried with `<EnableMonoWasmThreads>true</EnableMonoWasmThreads>` and yielded the same result.

If you add something to the bag, then the `TryTake()` succeeded as expected.

**Comment by vargaz** [comment]
@lewing Do we still support this configuration ?

**Comment by AshleighAdams** [comment]
> @lewing Do we still support this configuration ?

Given there has been no reply as of yet, is there a different way to do wasm builds now?

**Comment by lewing** [comment]
net5.0 is the official configuration now (as of today).  This looks like a linker error that you could probably resolve by disabling linking in the application.

**Comment by lewing** [comment]
I'm going to close this but I'm happy to continue providing guidance here if you are still having problems.

**Comment by AshleighAdams** [comment]
@lewing Is that official configuration Blazor WebAssembly? If so, then that won't suffice for me. I'm using WebGLDotNET, and it's my understanding that Blazor doesn't export the necessary functionality to interact with the DOM or such?

**Comment by lewing** [comment]
We're not doing any additional support for wasm here.  net5.0 isn't blazor specific but it might not support your requirements.  If you need additional apis please open issues in dotnet/runtime with your requests.

**Comment by AshleighAdams** [comment]
Ah, okay, thanks, before I take it over there:

>net5.0 isn't blazor specific

Do you mind clarifying that point?

**Comment by lewing** [comment]
Nothing about the dotnet Wasm runtime relies on Blazor and nothing is specific to it, it is simply the currently supported scenario.  See https://platform.uno/blog/uno-platform-3-2-net-5-c-9-support-and-net-5-webassembly-aot-support/ for an example.  Opening issue with your use cases and requirements will help us allocation development resources appropriately for net6.0.
