### ISSUE TITLE
[WASM] initialization doesn't work in electron from file://

### ISSUE THREAD

**Issue by 0x53A** [mono/mono#20592]
I have an electron app that uses mono wasm.

In DEV mode, everything is loaded from http:// and it works.
In Release mode, it's supposed to be loaded from file://, but doesn't even attempt it.

Here it (correctly) skips fetch because of the file uri check.

![image](https://user-images.githubusercontent.com/4236651/99597240-fc362580-29f7-11eb-8db2-b63d4dfa9423.png)

It then goes into ``getBinary`` ...

![image](https://user-images.githubusercontent.com/4236651/99597511-651d9d80-29f8-11eb-833c-0de687cd6ad9.png)

but ``readBinary`` is undefined, so it just does ... nothing ... and fails.

``readBinary`` is undefined because this is the environment initialization.

```js

if (ENVIRONMENT_IS_NODE) {
    // snip
} else
    if (ENVIRONMENT_IS_SHELL) {
        // snip
    } else

        // Note that this includes Node.js workers when relevant (pthreads is enabled).
        // Node.js workers are detected as a combination of ENVIRONMENT_IS_WORKER and
        // ENVIRONMENT_IS_NODE.
        if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {


            // Differentiate the Web Worker from the Node Worker case, as reading must
            // be done differently.
            if (ENVIRONMENT_IS_NODE) {

                // snip

            } else {
                if (ENVIRONMENT_IS_WORKER) {
                    readBinary = function readBinary(url) {
                        var xhr = new XMLHttpRequest();
                        xhr.open('GET', url, false);
                        xhr.responseType = 'arraybuffer';
                        xhr.send(null);
                        return new Uint8Array(/** @type{!ArrayBuffer} */(xhr.response));
                    };
                }
                // !! else missing here!
                //  ^^^^^^^^^^^^^^
            }

            setWindowTitle = function (title) { document.title = title };
        } else {
            throw new Error('environment detection error');
        }
```

I believe that if an else path was added there using an asynchronous XMLHttpRequest (sync XHR seems to fail on main thread), then it should work.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows
[x] Web

**Version Used**:

``mono-wasm-646d877d006``

**Comment by 0x53A** [comment]
It seems to work with the following changes to ``dotnet.js``: https://gist.github.com/0x53A/9549e482928632f3266324e9a9d9715e/revisions

Can you advise me where in the repo the original version of ``dotnet.js`` is? Then I can try to send a pull request.

**Comment by kjpou1** [comment]
This looks like it was fixed in emscripten
