### ISSUE TITLE
* Assertion at ..\\mono\\metadata\\reflection.c:1392, condition `idx != -1' not met

### ISSUE THREAD

**Issue by srxqds** [mono/mono#20600]
## Steps to Reproduce

1. 
2. 
3. 

## On which platforms did you notice this

[x] macOS
[ ] Linux
[x] Windows

**Version Used**:
6.12.0.93 desktop
6.0.0.334 embeded

## Stacktrace

the call stack:
![image](https://user-images.githubusercontent.com/5187024/99747713-0cdcbd80-2b16-11eb-9018-67859abb930d.png)

and the method value:

![image](https://user-images.githubusercontent.com/5187024/99747645-ed459500-2b15-11eb-8d6e-3df85889f818.png)

but the real method is show below:

why it get the wrong MonoMethod* param in *get_parameter_info** method?

**Comment by srxqds** [comment]
hi, @SamMonoRT  can you help me?
how can I figure out the problme.
thank you

**Comment by srxqds** [comment]
how can It get wrong MonoMethod* IntPtr

**Comment by srxqds** [comment]
I figure out the problem is caused by new StackTrace in the **InternalCall** with default argument value method.
the Pseudo code is：
```c#
class UUserWidget
{
     [MethodImpl(MethodImplOptions.InternalCall)]
     private static extern bool Internal_AddToPlayerScreen(UUserWidget self, int ZOrder = 0);

   public void Init()
   {
        StackTrace st = new StackTrace(); // this line will hit the assert.
   }

}
```

the test flow is:
1. Internal_AddToPlayerScreen
2. and then the native will call **Init** method through **mono_runtime_invoke** 
3. hit the assert.


you can reproduce and fix it.

**Comment by lambdageek** [comment]
Thanks for the bug report @srxqds - I have been able to reproduce the crash on Windows and Mac.

repro for mac/unix is here: https://gist.github.com/lambdageek/beb8e9672fc7b196145164fe0507f534

**Comment by srxqds** [comment]
hi，thank you.
i have a qestion about: why should create a wrapper monomethod in build method?
