### ISSUE TITLE
WCF rejects PATCH http verb

### ISSUE THREAD

**Issue by digocesar** [mono/mono#20611]
I am implementing a Restful API using a WCF bind. However, in mono, the verb PATCH is not being processed.

**Comment by digocesar** [comment]
Any update about accept the pull request that fix this issue? I need it to my project!

**Comment by digocesar** [comment]
@akoeplinger Do you know in which version of Mono this fix was released?

**Comment by akoeplinger** [comment]
It didn't make it into a release yet since our focus has been on the mono runtime in the dotnet/runtime repository.
