### ISSUE TITLE
Environment.MachineName returns different values depending on VPN being on or off

### ISSUE THREAD

**Issue by xfortin-devolutions** [mono/mono#20649]
## Steps to Reproduce

I'm testing with SonicWall Mobile Client as a VPN client on macOS. I'm not setup to test with other VPNs.

1. Run the code below in a Mono Console project
2. Take note of the output beside 'Environment.MachineName: '
3. Turn on the VPN
4. Run the code below in a Mono Console project a second time
5. Take note of the output beside 'Environment.MachineName: '

```
public static void Main(string[] args)
{
    Debug.WriteLine(GetMonoVersion());
    Debug.WriteLine($"Environment.MachineName: '{Environment.MachineName}'");
}

[System.Runtime.InteropServices.DllImport("__Internal", EntryPoint = "mono_get_runtime_build_info")]
private static extern string GetMonoVersion();
```

### Current Behavior

The first run (without the VPN) and the second run (with the VPN) do not return the same values. For instance, in my case the first time, it returned 'Devolutions253' which is the proper name of my device while the second time (with the VPN on), it returned 'devolutions115' which is NOT the name of my device (actually no clue where it gets this).

### Expected Behavior

The state of the VPN should have no impact on the return value of Environment.MachineName. The relatively equivalent macOS method [[NSHost currentHost] localizedName] does not exhibit this issue, it always returns the proper name of the device regardless of the VPN being on or off.

## On which platforms did you notice this

[ ✔︎] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono version 6.12.0.107 (2020-02/a22ed3f094e Wed Oct 28 07:48:22 EDT 2020)

**Comment by xfortin-devolutions** [comment]
This is still happening. Also, the same issue occurs with Dns.GetHostName().

**Comment by akoeplinger** [comment]
Can you try running `hostname` in Terminal? I'm pretty sure this is not Mono-related but the VPN client doing this (I'm seeing the same behavior with a GlobalProtect VPN)

**Comment by xfortin-devolutions** [comment]
Ah! Indeed, `hostname` exhibit the same behaviour. Well, I guess I'll keep my fix of using NSHost instead.

**Comment by Whiletru3** [comment]
I'm facing the same issue but it is not systematic
