### ISSUE TITLE
Online Mono Documentation not working.

### ISSUE THREAD

**Issue by JohnyM01** [mono/mono#20719]
Hi,

I am having trouble accessing the online mono documentation in the last week via
http://docs.go-mono.com/
http://docs.go-mono.com/index.aspx

ping to docs.go-mono.com fails to respond.

Can someone in Mono confirm that the online documentation is down? 

Since the monodoc in Ubuntu is not working, I cannot use the monodoc access via MonoDevelop or from command line. Thankfully, I can use Zeal <https://zealdocs.org/> which has a docset for Mono. It is god send when Mono's documentation is not working. Anyone wanting an offline Mono doc is recommended to have a try. It also works in Windows.

Johny

**Comment by akoeplinger** [comment]
Thanks, it works again now.
