### ISSUE TITLE
Got an error `Parameter count mismatch` or `NullReferenceException` in in _finalize_startup when using mono-wasm

### ISSUE THREAD

**Issue by zwcloud** [mono/mono#20723]
## Steps to Reproduce

1. Follow the [mono-wasm sample tutorial](https://github.com/mono/mono/blob/master/sdks/wasm/docs/getting-started/sample.md) to fetch a workable WebAssembly SDK and run the sample.
2. Modify the sample to run custom C# code
  ```c#
  namespace MyApp
  {
      public class Program
      {
          public static void Main(string[] args)
          {
              Console.WriteLine("inside C#");
          }
      }
  }
  ```
  ```js
  var App = {
      init: function () {
          // call main
          BINDING.call_static_method("[MyApp] MyApp.Program:Main", []);//Error A
          BINDING.call_static_method("[MyApp] MyApp.Program:Main", [], []);//Error B
          console.log("inside js");
      }
  };
  ```

3. See the error

**Error A**
> Unhandled exception in _finalize_startup Error: Parameter count mismatch.

**Error B**
> Unhandled exception in _finalize_startup Error: System.NullReferenceException: Object reference not set to an instance 

### Current Behavior

Error occurred and no output from C# and js.

### Expected Behavior

No error happens and following text is printed in browser console:

> inside C#
> inside js

## On which platforms did you notice this

Windows

**Version Used**:

https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/processDownloadRequest/5546/ubuntu-1804-amd64/sdks/wasm/mono-wasm-5bf7d8ba96d.zip

## Stacktrace

Error A:
[Error-A.log](https://github.com/mono/mono/files/5775104/Error-A.log)
![image](https://user-images.githubusercontent.com/6965758/103755643-1d56e200-5049-11eb-9d6e-c755629b1ea4.png)

Error B:
[Error-B.log](https://github.com/mono/mono/files/5775034/localhost-1609926567976.log)
![image](https://user-images.githubusercontent.com/6965758/103754724-b4229f00-5047-11eb-9984-d49b06497653.png)

**Comment by kjpou1** [comment]
Parameter count is that you are expecting a string[] args but not passing an argument for it.

One thing to take notice is that we do not at this time support passing string array as parameters.  You can pass a JS Array and reference it as the Bindings for a JS array but not dotnet native elements.

**Comment by zwcloud** [comment]
OK, so the problem is the `string[] args` arguement of `MyApp.Program:Main`. I'll try it later, thanks!

**Comment by kjpou1** [comment]
Closing this for now.  Please reopen or create a new issue.
