### ISSUE TITLE
Hardware issue with Nvidia card

### ISSUE THREAD

**Issue by mrlobaker** [mono/mono#20729]
Hello. Looks like I have some hardware issues with Mono.
I installed a new graphics card a few days ago (Palit GeForce GTX 1650), and then played Vintage Story (written in C#), and it worked just fine. Today, I launched the game as usual (no hardware or software changes happened) and got a Mono native crash. I attached it as a file (captured with > log.txt 2>&1, mono-runtime-dbg installed).
[log.txt](https://github.com/mono/mono/files/5786973/log.txt)

I tried reinstalling Mono, upgrading/downgrading drivers - no difference.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:22:56 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by migueldeicaza** [comment]
Not likely Mono related, the crash comes from the graphics drivers, try the vendor for this game to help you debug
