### ISSUE TITLE
Unable to set capabilities on mono project

### ISSUE THREAD

**Issue by Fox4148** [mono/mono#20738]
## Steps to Reproduce

1.  Install latest debian, mono-complete
2. Try to run the command `sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/mono`

 ##Current behavior
`Failed to set capabilities on file /usr/bin/mono (Invalid argument)`
`The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file`

Linux
Debian buster
mono 6.12.0.107

**Comment by lambdageek** [comment]
Try setting capabilities on the `mono-sgen` binary. `mono` is a symlink.
