### ISSUE TITLE
How to access Monolite

### ISSUE THREAD

**Issue by rochus-keller** [mono/mono#20734]
The description in https://www.mono-project.com/docs/advanced/monolite/ seems not to be current (or I just didn't get it). 

Could you please provide an up-to-date description - or even better a persistent link - on how to download the monolite executable. I also didn't understand from the description whether this is a pre-compiled binary, or whether it has to be built. A pre-compiled binary for Linux i386 and Windows x86 would be preferred of course.

Thanks

**Comment by madewokherd** [comment]
As I understand it, monolite is only really designed to be used as part of Mono's build process to build the base libraries and compiler.

**Comment by rochus-keller** [comment]
https://www.mono-project.com/docs/advanced/monolite/ states that "Monolite is a minimal binary distribution of mcs" which is exactly what I'm looking for. Unfortunately the provided link doesn't lead to the "latest build". So my original question is still open.

**Comment by sancheolz** [comment]
https://www.mono-project.com/docs/compiling-mono/windows/#use-monolite-instead-of-pre-installed-mono-distribution

**Comment by rochus-keller** [comment]
Well, there is also a similar (even more detailed) hint in the regular README.md, see https://github.com/mono/mono#if-you-dont-have-a-working-mono-installation.

Meanwhile I was able to download a source release on Linux and run `./autogen.sh` and then `make get-monolite-latest`. The log output then led me to this site, where pre-compiled versions of Monolite for different operating systems can be downloaded: https://download.mono-project.com/monolite. But apparently these archives only include the assemblies, not the `mono` executable, and the `make get-monolite-latest` command neither does seem to create it.

So the issue still applies to the `mono` executable. Is a pre-compiled version supposed to be downloadable for each platform (as it is with the assemblies)? Or how do I get the executable otherwise? Just by regular make?

It would be helpful if  https://www.mono-project.com/docs/advanced/monolite/ could explain that and make appropriate references (e.g. to the URLs mentioned).

**Comment by madewokherd** [comment]
When building Mono, it's assumed that you already have a C/C++ compiler, so the C components are not included in monolite.

**Comment by rochus-keller** [comment]
Meanwhile I could run a complete build of Mono 3.12.1 on Linux. The source release downloaded from https://download.mono-project.com/sources/mono/ already includes a monolite subdirectory with some dll and an exe assembly. According to the Makefiles generated by configure these assemblies are used by the regular mono executable built earlier by the Makefiles. There is no indication of a special build for a Monolite executable. 

So "Monolite" seems like a misnomer; what it includes are rather the minimal, platform specific assemblies to run MCS, but without the mono executable. So it's (unfortunately) not a full binary distribution in contrast to the claim in the documentation.

I still think that a true (i.e. complete, including a minimal mono executable and shared library) Monolite binary distribution would be something very useful for people (like me) who don't need the DotNet framework but still want to use and embedd Mono as a compiler backend, without being forced to do install the full package or built their own version.

In any case the documentation at https://www.mono-project.com/docs/advanced/monolite/ should be fixed and expanded. I'm not familiar with the project organisation, but I can support this task if need be.

**Comment by akoeplinger** [comment]
Yeah as you found out monolite is only really designed to support bootstrapping the mono source build. To build the managed BCL assemblies you need a C# compiler but that one itself relies on the BCL assemblies. Monolite provides prebuilt versions of these assemblies that the build can run with the locally built `mono` to bootstrap this process.

We currently don't have plans to make monolite into a minimal package for the other use cases you mentioned but updating the website would be appreciated, you can send a PR by clicking on the `Edit page on GitHub` link on that page :smile:

**Comment by rochus-keller** [comment]
Ok, that confirms my findings that Monolite is not a "minimal binary distribution"; since you don't plan to support a true minimal binary distribution, I would **recommend to simply delete the page referenced by https://www.mono-project.com/docs/advanced/monolite/**. It doesn't make sense to explicitly mention and name something which is an implementation detail of the build process and not meant to be of use outside of it. That only leads more people like me on the wrong track

**Comment by akoeplinger** [comment]
Yup, I moved it to the archived docs so it doesn't show up in the index.
