### ISSUE TITLE
Unable to compile mono for 32-bit, pedump missing dependency.

### ISSUE THREAD

**Issue by jbatt33** [mono/mono#20735]
## Steps to Reproduce

The following build steps were used for mono 6.4 to generate a 32-bit output on ubuntu. 

> export LDFLAGS="-m32 -march=i686 -I/usr/include/i368-linux-gnu"
export CXXFLAGS=$LDFLAGS
export CFLAGS=$LDFLAGS
echo $CFLAGS
./autogen.sh --prefix=/opt/edison/out/target/edison/rootfs/mono --host=i386-linux-gnu --with-runtime_preset=net_4_x mono_cv_uscore=no --with-sigaltstack=no --with-mcs-docs=no --disable-gtk-doc --with-ikvm-native=no --with-moonlight=no--disable-boehm
make

This is no longer working with mono 6.12.0.107
I believe it's a configuration issue since I see the following: in the configuration log (but not sure): 

> SUPPORT_SGEN_FALSE='#'
SUPPORT_SGEN_TRUE=''

### Current Behavior

This is the error at compile time. 

>Making install in pedump
make[2]: Entering directory '/home/builduser/Mono/mono-6.12.0.107/tools/pedump'
  CC       libpedump_a-pedump.o
  AR       libpedump.a
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: *** No rule to make target '../../mono/metadata/libmonoruntimesgen.la', needed by 'pedump'.  Stop.
make[2]: Leaving directory '/home/builduser/Mono/mono-6.12.0.107/tools/pedump'
Makefile:522: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1

## On which platforms did you notice this

[ ] macOS
[ X] Linux
[ ] Windows

**Version Used**:
mono 6.12.0.107

I have the complete configuration log, but not sure I should include all of this here. Let me know how I can resolve this issue. Thanks.

**Comment by akoeplinger** [comment]
Hm that's weird, does it compile other parts of the build fine? you can try removing `pedump` from tools/Makefile.am as a hacky workaround.

**Comment by jbatt33** [comment]
I agree it is very strange. It was working find for mono 6.8 as well. Let me try removing pedump...

**Comment by jbatt33** [comment]
I took pedump out of the make time... seems to be getting much further into the build.  What is pedump used for?

**Comment by jbatt33** [comment]
Spoke too soon, looks like the "CodeAnalysis" library is also not available. 

`Makefile:64: recipe for target '../../class/lib/build-linux//Microsoft.CodeAnalysis.dll.so' failed
make[7]: *** [../../class/lib/build-linux//Microsoft.CodeAnalysis.dll.so] Error 1
ld: i386 architecture of input file `/tmp/mono_aot_P8q0KT.o' is incompatible with i386:x86-64 output
AOT of image ./../../class/lib/build-linux//mscorlib.dll failed.
Mono Ahead of Time compiler - compiling assembly /home/builduser/Mono/mono-6.12.0.107/mcs/class/lib/build-linux/mscorlib.dll
AOTID 5A7FDB35-1165-953A-3664-2E3BAFB6BD8D
Compiled: 24458/24458
Executing the native assembler: "as" --32  -o /tmp/mono_aot_P8q0KT.o /tmp/mono_aot_P8q0KT
Executing the native linker: "ld" -shared -o /home/builduser/Mono/mono-6.12.0.107/mcs/class/lib/build-linux/mscorlib.dll.so.tmp  /tmp/mono_aot_P8q0KT.o 
-shared -o ./../../class/lib/build-linux//Microsoft.CodeAnalysis.dll.so.tmp  /tmp/mono_aot_78Hch4.o 
XN9ePX.o 
BB.o 
Makefile:61: recipe for target '../../class/lib/build-linux//mscorlib.dll.so' failed
make[7]: *** [../../class/lib/build-linux//mscorlib.dll.so] Error 1
../../build/rules.make:220: recipe for target 'do-all' failed
`

**Comment by jbatt33** [comment]
Let me try also disabling AOT support.

**Comment by akoeplinger** [comment]
`pedump` isn't used by the build at all, it's just a tool that's part of the mono install.

The issue you're seeing with Microsoft.CodeAnalysis.dll is because it's trying to AOT (precompile) the .dll to native code and apparently there's some architecture mismatch going on here. We usually don't compile the class libraries when we cross compile, no idea how it worked before but maybe this helps: https://stackoverflow.com/questions/19200333/architecture-of-i386-input-file-is-incompatible-with-i386x86-64

In general it might be better to compile in a x86 chroot.

**Comment by jbatt33** [comment]
Ok, instead of using chroot. I did a compile on a 32-bit ubuntu and this worked. I guess something in my other environment isn't exactly setup correctly anymore. Thanks for taking the time to look at this. Closing it out.
