### ISSUE TITLE
https://download.mono-project.com/repo/ is unavailable (504 gateway timeout)

### ISSUE THREAD

**Issue by thzinc** [mono/mono#20770]
When trying to run `apt-get update` on the `mono` Docker image (a Debian buster distro), the command fails because download.mono-project.com via HTTPS returns an HTTP 504 error after a long time.

### _In situ_ steps

1. Run the `mono:6.6.0` Docker image
2. Execute `apt-get -qy update`

#### Current Behavior

The command fails with a series of log messages like the ones below:

```
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [649 kB]
Get:5 http://deb.debian.org/debian stretch Release [118 kB]
Get:6 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [2596 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
Ign:9 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161 InRelease
Ign:10 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161 Release
Ign:11 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main amd64 Packages
Ign:12 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main all Packages
Ign:11 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main amd64 Packages
Ign:12 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main all Packages
Ign:11 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main amd64 Packages
Ign:12 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main all Packages
Ign:11 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main amd64 Packages
Ign:12 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main all Packages
Ign:11 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main amd64 Packages
Ign:12 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main all Packages
Err:11 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main amd64 Packages
  504  Gateway Timeout
Ign:12 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161/main all Packages
Fetched 7998 kB in 3min 29s (38.1 kB/s)
Reading package lists...
W: The repository 'http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.6.0.161 Release' does not have a Release file.
E: Failed to fetch http://download.mono-project.com/repo/debian/dists/stable-stretch/snapshots/6.6.0.161/main/binary-amd64/Packages  504  Gateway Timeout
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
#### Expected Behavior

`apt-get update` completes successfully.

### Specific steps

1. Using `curl`, request http://download.mono-project.com/repo/debian/ and note that it successfully returns an HTML page with a listing of folders
2. Using `curl`, request https://download.mono-project.com/repo/debian/

#### Current behavior

The request fails with an HTTP 504 error after some time.

#### Expected behavior

The request completes with a listing equivalent to that of the non-HTTPS request.

## On which platforms did you notice this

[X] macOS (curl)
[X] Linux 
[X] Windows (curl)

**Version Used**: 6.6.0 and 6.12.0

**Comment by thzinc** [comment]
I realize this may be the wrong place for a report like this. Any help in getting it to the right people is appreciated.

**Comment by growupforever-fx** [comment]
+1 waiting for solution,thanks a lot

**Comment by growupforever-fx** [comment]
it works now , you can retry it

**Comment by thzinc** [comment]
Amazing. Thanks for the heads up @growupforever-fx!

Since this appears to be resolved, I will close this issue.

**Comment by Bhodges94** [comment]
this is still an issue.. 
on the documentation (https://www.mono-project.com/download/stable/#download-lin) it says to go to ttps://download.mono-project.com/repo/ubuntu stable-focal main which doesn't exist..

but this link exists, maybe documentation isn't up-to-date?
https://download.mono-project.com/repo/ubuntu/dists/stable-focal/

still get a 504 gateway error when going into the main folder though:
https://download.mono-project.com/repo/ubuntu/dists/stable-focal/main
