### ISSUE TITLE
Missing EINTR handling on macOS for opendir/readdir/closedir syscalls

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#20799]
(Thanks to @Therzok for filing a related issue to dotnet/runtime: https://github.com/dotnet/runtime/issues/47584 )

**Note the issue is different in mono/mono due to Thread.Abort and Thread.Interrupt**

### Description

It seems that under certain conditions, the `opendir`, `readdir`, `closedir` can set `errno` to `EINTR`.

The 3 syscalls are the only ones in pal_io.c that are not handling EINTR in native, but they also don't handle it in managed.

https://github.com/mono/corefx/blob/7c24bb0756fd39fbf09b8777f25c15d21d78eb46/src/Native/Unix/System.Native/pal_io.c#L468

Note: it is not documented in the man pages, but it seems to be a problem in practice.

### Configuration

Mono 2020-02, macOS, x64. Not specific to this.

### Regression?

Only started happening with macOS Big Sur.

### Other information

See [this gist](https://gist.github.com/rmarinho/29070bb92c688f9ee1f6df55faaa1c73) for an exception being bubbled on mono which is using the same source as dotnet/runtime.

**Comment by lambdageek** [comment]
For mono/mono, due to thread aborts and interrupts, this has ot be handled in a similar way to https://github.com/mono/mono/pull/7255

We can't just look in native checking for `EINTR`.  The loop has to be moved up to the C# layer so that the thread can be interrupted.

**Comment by Therzok** [comment]
@lambdageek dotnet/runtime PR has been merged.

**Comment by lambdageek** [comment]
Fixed on mono main and 2020-02
