### ISSUE TITLE
The default branch was renamed from 'master' to 'main'

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#20926]
On Monday, March 15th 2021, we're going to rename the default branch in this repository to `main`.

For more details, see [our earlier announcement](https://github.com/dotnet/announcements/issues/172).

**Comment by akoeplinger** [comment]
The rename is now done. You can update your local clone with the following commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by leezer3** [comment]
Should https://github.com/mono/mono/commits/master be returning a 404?

I was under the impression that Github should automatically be redirecting if you renamed the branch.

**Comment by akoeplinger** [comment]
@leezer3 looks like that's a gap in GitHub's redirects, e.g. https://github.com/mono/mono/blob/master/README.md does correctly redirect
