### ISSUE TITLE
"Hash Sum Mismatch" with https://download.mono-project.com/repo/ubuntu/dists/preview-xenial/main/binary-armhf/Packages

### ISSUE THREAD

**Issue by MattGal** [mono/mono#20920]
@directhex FYI.

## Steps to Reproduce
(See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/426)

1. Get an ARM32v7 machine running docker
2. Copy down https://raw.githubusercontent.com/dotnet/dotnet-buildtools-prereqs-docker/6616c63298d6fe23e6aec2f1f5b6c4b82cedb026/src/ubuntu/16.04/helix/arm32v7/Dockerfile locally
3. Docker build it (or just do the steps from it if you have the hardware but don't feel like dockering)

### Current Behavior

apt fails with "Hash Sum Mismatch".  Trying other feeds such as nightly works.

### Expected Behavior

Dockerfile builds cleanly and ends up with libgdiplus installed.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

N/A:  This is a an apt package source problem.

## Stacktrace

N/A the only error message comes from Ubuntu's package manager

**Comment by directhex** [comment]
This was resolved a while back with infra changes
