### ISSUE TITLE
Jenkins is unreachable

### ISSUE THREAD

**Issue by mtopf** [mono/mono#20952]
## Steps to Reproduce

I'm trying to follow the [wasm sample](https://github.com/mono/mono/blob/main/sdks/wasm/docs/getting-started/sample.md) which depends on the WebAssembly SDK.
In the [obtaining the WebAssembly SDK document](https://github.com/mono/mono/blob/main/sdks/wasm/docs/getting-started/obtain-wasm-sdk.md#download-webassembly-sdk) it says that developers may get the data [from mono's jenkins server](https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/).

Unfortunately me and some of my peers are only getting an `ERR_CONNECTION_TIMED_OUT` trying to access the server. If this is not yet known I just wanted to make you aware of it. 
And if there's an alternative way to get the prebuilt WebAssembly SDK I'd love to find out.
Thanks!

**Comment by legistek** [comment]
I would like to get the SDK as well.

**Comment by mtopf** [comment]
Closing this myself. I missed [Important Note About Our CI Infrastructure](https://github.com/mono/mono/issues/20841).

**Comment by peter0302** [comment]
Yes but they still won't give us a public link to download the wasm ask.

**Comment by mtopf** [comment]
Sure but that's also mentioned multiple times in the original CI ticket.
