### ISSUE TITLE
Fix OpenBSD/arm64 build (BoringSSL part)

### ISSUE THREAD

**Issue by bluerise** [mono/mono#21005]
mono does not yet work on OpenBSD/arm64. A few small patches are needed for it to build. One part is patching BoringSSL. Unfortunately mono/boringssl is archived, so there is no way to open a Pull Request on that project.

It would be nice if this commit could be added to the mono/boringssl repo, and the git submodule update to include it as well: https://github.com/mono/boringssl/compare/mono...bluerise:obsd

**Comment by bluerise** [comment]
@steveisok Mind having a look at this diff? I can't open a pull-request on the boringssl repo because it is archived. I saw you being the last one committing to it?

**Comment by akoeplinger** [comment]
Pushed it to the boringssl submodule, thanks :)
