### ISSUE TITLE
[interp] interpreter is disabled on iOS

### ISSUE THREAD

**Issue by zhuopeng-tan** [mono/mono#21045]
https://github.com/mono/mono/blob/4545a50416e9a748ce03e616dc61064ec7609e95/sdks/builds/ios.mk#L117

As @migueldeicaza wrote in [Mono's New .NET Interpreter](https://www.mono-project.com/news/2017/11/13/mono-interpreter/)
> iOS was the main driver for this

But interpreter has been disabled on iOS since 3 years ago, even it's stable from Mono v6.0.0, which was released ~2 years ago.

From [Mono 6.0.0 Release Notes](https://www.mono-project.com/docs/about-mono/releases/6.0.0/)
> Mono Interpreter is feature complete and stable

Visual Studio for Mac has an option to enable interpreter, so Xamarin.iOS builds Mono on iOS with interpreter enabled, but Mono itself does not.

I'd like to know: do you have a plan to enable interpreter on iOS in the near future?

**Comment by migueldeicaza** [comment]
Odd, what makes you think the interpreter is disabled?

**Comment by zhuopeng-tan** [comment]
@migueldeicaza 

From [Mono building Configuration Options](https://github.com/mono/mono#configuration-options)
> --enable-minimal=LIST
The list is a comma-separated list of components that should be removed, these are:
...

So [this](https://github.com/mono/mono/blob/4545a50416e9a748ce03e616dc61064ec7609e95/sdks/builds/ios.mk#L117) means interpreter is removed when building Mono for iOS
> --enable-minimal=ssa,com,**interpreter**,jit...

**Comment by zhuopeng-tan** [comment]
It seems that I was wrong, actually mono interpreter works, but we need to link some other libraries (e.g., `libmono-ee-interp.a`) which contain interpreter utilities, previously I just linked `libmonosgen-2.0.a`, 🤦
