### ISSUE TITLE
Add `System.ServiceModel.Discovery.dll` to the binary package consumed by Xamarin.Mac

### ISSUE THREAD

**Issue by spouliot** [mono/mono#21062]
Request for VSfM. ref: https://github.com/xamarin/xamarin-macios/issues/11568

This would need to be back ported to `2020-02` so it can be shipped with newer (legacy) Xamarin.Mac SDK.

c.c. @akoeplinger

**Comment by akoeplinger** [comment]
@spouliot does this only apply to the xammac 4.5 profile or the "mobile" one too?

**Comment by spouliot** [comment]
@akoeplinger fairly sure it will be xammac_4_5 profile - but it can be added to both (mobile too) as we can ship it (or not) depending on vs4m needs.

**Comment by akoeplinger** [comment]
it'd be more complicated to add it to mobile profile, so I'll keep it for XM4.5 for now since afaik that is what VSMac uses.

**Comment by Therzok** [comment]
Yup, we use net4x profile

**Comment by akoeplinger** [comment]
I talked to @KirillOsenkov offline and it turns out that System.ServiceModel.Discovery.dll was pulled in by some dependency that's not actually used and can be removed which means we don't need to do anything here :)
