### ISSUE TITLE
jenkins.mono-project.com is down 

### ISSUE THREAD

**Issue by alimhabib** [mono/mono#21075]
## Steps to Reproduce

1. open https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/ wither in edge or chrome 
2.  you will see that the page not opened 
 

### Current Behavior
 I got This site can’t be reached  

### Expected Behavior

 I should be able to download the latest WASM SDK 

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ X] Windows

**Version Used**:

**Comment by akoeplinger** [comment]
Please see https://github.com/mono/mono/issues/20841
