### ISSUE TITLE
[interp][iOS] Can't use interpreter in iOS

### ISSUE THREAD

**Issue by zhuopeng-tan** [mono/mono#21088]
We've been trying to embed mono in our iOS application (internal project so cann't be disclosed) for a few months, until now we are still fighting with errors, 😓

At the beginning, interpreter was enabled by following `mono_main`
https://github.com/mono/mono/blob/c621c35ffa03273dbfb83055c7587c6a6617295a/mono/mini/driver.c#L2441-L2442

However we got error `tid_303 (1): EXC_BAD_ACCESS (code=2, address=...` when running the app in Xcode, the error threw when executing this line
https://github.com/mono/mono/blob/c621c35ffa03273dbfb83055c7587c6a6617295a/mono/mini/interp/interp.c#L1595

`entry_func` is assigned by calling `mono_code_manager_reserve` which is protected by `jit lock`
https://github.com/mono/mono/blob/c621c35ffa03273dbfb83055c7587c6a6617295a/mono/mini/mini-runtime.c#L387-L389

After checking the code, I found that `MONO_EE_MODE_INTERP` mode still uses JIT which is unavailable in iOS, we had to try another way
https://github.com/mono/mono/blob/c621c35ffa03273dbfb83055c7587c6a6617295a/mono/mini/mini-runtime.h#L413-L414

Then we tried `MONO_AOT_MODE_INTERP` mode, and we got another error that showed mono failed to get mscorlib aot data, but I don't know how to generate mscorlib aot data for iOS, nor am I sure if it's going to work if I get mscorlib aot data
https://github.com/mono/mono/blob/c621c35ffa03273dbfb83055c7587c6a6617295a/mono/mini/jit.h#L61-L63

That's frustrating 😢, could anyone help to make interpreter work in iOS?

Additional info:

> Env: iOS 14.4 & MacOS 11.4
> Mono version: [6.12.0.122](https://github.com/mono/mono/tree/mono-6.12.0.122/mono)
> Xcode version: 12.5

**Comment by lambdageek** [comment]
The interpreter on ios on Mono 6.12 has only been tested as a FullAOT fallback.

> Then we tried MONO_AOT_MODE_INTERP mode, and we got another error that showed mono failed to get mscorlib aot data, but I don't know how to generate mscorlib aot data for iOS, nor am I sure if it's going to work if I get mscorlib aot data

You need to compile `mscorlib.dll` with something like:

```
mono --aot=full,interp,data-outfile=mscorlib.dll.aotdata,asmonly,outfile=mscorlib.dll.s
```

To run, use the `MONO_AOT_MODE_INTERP`.

**Comment by zhuopeng-tan** [comment]
@lambdageek Thanks for your reply.

I'm not sure which way do you mean
1. Compile `mscorlib.dll` manually and link it in Xcode project
2. Compile `mscorlib.dll` and load it on the fly

(1) failed, `mscorlib.dll.s` fails to compile
(2) succeeded in MacOS with an example, I will try it in iOS

**Comment by zhuopeng-tan** [comment]
Just found `mtriple` to generate mscorlib.dll.s (arm64 version) in mono/sdks/ios.

**Comment by zhuopeng-tan** [comment]
The compilation issue resolved by calling `${MONO_REPO}/sdks/out/ios-cross64-release/bin/aarch64-darwin-mono-sgen` with the same arguments, I compiled `mscorlib.dll.s`, made the obj file an static library and linked it in Xcode.

But we get new issue when running the app, it crashed in function `mono_class_setup_vtable_full()`
https://github.com/mono/mono/blob/c621c35ffa03273dbfb83055c7587c6a6617295a/mono/metadata/class-init.c#L2442-L2452
Where `kclass` points to an invalid MonoClass object, so it crashes on the line
```C
if (klass->vtable)
```

LLDB shows
```llvm
(lldb) p klass
(MonoClass *) $9 = 0x000000000105c034
(lldb) p *(_MonoClass*)klass
error: Couldn't apply expression side effects : Couldn't dematerialize a result variable: couldn't read its memory
```

I tracked the call stack and found that the `klass` is `this_arg->vtable->klass`, so it's already invalid when we got `this_arg`, 
@vargaz I can see that you commited this piece of code, could you please kindly share some insights about this crash?
https://github.com/mono/mono/blob/c621c35ffa03273dbfb83055c7587c6a6617295a/mono/mini/interp/interp.c#L3904-L3906

Additional info:
> Env: iOS 14.4 & MacOS 11.4
> Mono version: 6.12.0.122
> Mode: AOT(mscorlib only) + interpreter
> Xcode version: 12.5

**Comment by zhuopeng-tan** [comment]
We've found the root cause: a forced GC is called which causes memory corruption, the app runs well after removing the GC call.

@lambdageek Thanks for your help.
