### ISSUE TITLE
Broken Checklist in GitHub Issue Template

### ISSUE THREAD

**Issue by adamsmd** [mono/mono#21113]
This is an issue having to do with the GitHub issue template used by https://github.com/mono/mono on GitHub.

## Steps to Reproduce

1. Create a new issue (e.g., go to https://github.com/mono/mono/issues/new).
2. Click the "Preview" tab to preview the issue.

### Current Behavior

Under the "On which platforms did you notice this" section, the output
shows the checkbox as text (e.g., "[ ] macOS") as seen in the following example.

[ ] macOS
[ ] Linux
[ ] Windows

### Expected Behavior

Under the "On which platforms did you notice this" section, the output
shows the checkbox as a proper checkbox as seen in the following example.

- [ ] macOS
- [ ] Linux
- [ ] Windows

## Suggested Fix

In the GitHub template for https://github.com/mono/mono/, change the following

    ## On which platforms did you notice this
    
    [ ] macOS
    [ ] Linux
    [ ] Windows

to the following

    ## On which platforms did you notice this

    - [ ] macOS
    - [ ] Linux
    - [ ] Windows

**Comment by marek-safar** [comment]
This is expected. If we turn the selection into proper checkboxes GH would use them for progress tracking which is wrong.

**Comment by adamsmd** [comment]
I was not aware of that consideration.  Closing this issue as what you say makes sense.
