### ISSUE TITLE
mcs complier support for C# 8.0

### ISSUE THREAD

**Issue by hanyutan** [mono/mono#21135]
Thanks for the amazing project! I just want to confirm that whether mcs compiler supports new features in C# 8.0, such as Switch Expression?

This [link](https://stackoverflow.com/questions/3334138/combine-return-and-switch) mentions Switch Expression in C# 8.0
![image](https://user-images.githubusercontent.com/41721073/123925055-1dfb8000-d9bd-11eb-91de-b3a304484681.png)

And the introduction on [mono website](https://www.mono-project.com/docs/about-mono/languages/csharp/) seems not to mention C# 8.0
>The Mono C# compiler is considered feature complete for C# 1.0, C# 2.0, C# 3.0, C# 4.0, C# 5.0 and C# 6.0 (ECMA) and it has partial support for C# 7.

Thanks a lot!

**Comment by marek-safar** [comment]
Mono C# compiler does not support C#8 and has only partial support for C#7. It's recommended to switch to csc compiler when you need newer language constructs.

**Comment by hanyutan** [comment]
> Mono C# compiler does not support C#8 and has only partial support for C#7. It's recommended to switch to csc compiler when you need newer language constructs.

@marek-safar Thanks! By the way, is there any difference among dlls compiled by different compiler? (such as mcs, csc, and in visual stuidio) When C++ calls C# dll through mono, is there any possibility that dll compiled by mcs is called successfully, while the dll compiled by visual studio (build a class library) crashed?

Really appreaciate :-)

**Comment by marek-safar** [comment]
Yes, both C# compilers (mcs and csc) can produce different IL and also different metadata. The difference will be relatively small and it really depends on the C# code.
