### ISSUE TITLE
Can't download (older) packages from apt repositories

### ISSUE THREAD

**Issue by veer0318** [mono/mono#21230]
Hi, I'm working on Ubuntu 16.04 and trying to install Mono following the guidelines at https://www.mono-project.com/download/stable/#download-lin. There appears to be an issue with the repository at download.mono-project.com; if I run `apt-get install mono-devel` I get these errors:

`E: Failed to fetch https://download.mono-project.com/repo/ubuntu/pool/main/m/mono/monodoc-manual_6.12.0.122-0xamarin1+ubuntu1604b1_all.deb  504  Gateway Timeout`

I tried manually accessing the rep at the URL and tried two other VPS'es, to no avail. My suspicion is that there is an issue with the IPv6 config at download.mono-project.com.

Not sure if this is an appropriate bug report here...

**Comment by avboivin** [comment]
Same as https://github.com/mono/mono/issues/18639
