### ISSUE TITLE
System.Drawing.Common/Primitives facades and Color related types

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#21239]
The facades for the System.Drawing.[Common/Primitives] assemblies placed types like `Color`/`SystemColors` in the wrong assembly. In turn libraries linked against these facades expect the types to exist in `System.Drawing.Common`. This breaks once the libraries are used in the .NET 6 context.

I recently workarounded that on Xamarin.Forms iOS build but hit it again with Xamarin.Essentials. It should be fixed here once and for all.

**Comment by akoeplinger** [comment]
Yeah I don't think we'll be fixing this in mono/mono at this point given the net6 changes. Thanks!
