### ISSUE TITLE
504-Gateway Timeout Error

### ISSUE THREAD

**Issue by casstait** [mono/mono#21297]
## Steps to Reproduce

1. build from Dockerfile
```
RG BASE_IMAGE=ubuntu:xenial
FROM ${BASE_IMAGE}

# Install base pre-reqs
RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        curl \
        tzdata \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Mono
RUN apt-key update && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
    echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots 4.6.0.245/main" | tee /etc/apt/sources.list.d/mono-xamarin.list && \
    apt-get update && \
    apt-get install -y --allow-unauthenticated \
        mono-complete \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
```
2. Error during build
[docker build step failure.log](https://github.com/mono/mono/files/7494622/docker.build.step.failure.log)

### Current Behavior

504  Gateway Timeout

### Expected Behavior

Expect install steos to succeed. 

## On which platforms did you notice this

[ ] macOS
[x] Linux - Debian 10
[ ] Windows

**Version Used**: 
- deb http://download.mono-project.com/repo/debian wheezy/snapshots 4.6.0.245/main
- deb https://download.mono-project.com/repo/debian stable-buster main

**Comment by akoeplinger** [comment]
Should be fixed now, see https://github.com/mono/mono/issues/21273#issuecomment-963127516
