### ISSUE TITLE
Cannot pass byte pointer to array from rust runime to wasm: TypeError: Buffer is already detached

### ISSUE THREAD

**Issue by tmarkovski** [mono/mono#21308]
I'm trying to invoke a function in a rust library from blazor using the native file reference functionality in net 6.
I'm able to pass arrays into the native library, but not return them back to wasm.

I have a test project setup here https://github.com/tmarkovski/rust-blazor-test

My goal is to be able to pass byte array from blazor wasm and get back another byte array from the native rust library. This already works fine when using P/Invoke with non-wasm .net runtimes, I'm trying to adopt it for wasm.

My rust function is defined as
```rust
#[repr(C)]
pub struct ByteBuffer {
    len: i64,
    data: *mut u8,
}

#[no_mangle]
pub extern "C" fn buffer_in_out(buffer: &ByteBuffer, buffer_out: &mut ByteBuffer) {
}
```
and the C#
```cs
[StructLayout(LayoutKind.Sequential)]
public struct ByteBuffer
{
    public long Length;
    public IntPtr Data;
}

[DllImport("libmath")]
public static extern void buffer_in_out(ByteBuffer buffer, out ByteBuffer out_buffer);
```

It appears that I have issues marshaling the pointers back to wasm. Even if I create a byte array in Rust and force it to be leaked using `Box::leak()` or `mem::forget()`, I cannot seem to return a pointer back to wasm. My sample project has few different scenarios that I played with using different method signatures, but any use of vec or slice in Rust seems to throw the errors below about object being disposed. Even if the return result doesn't reference any of the data used in the function.

## Steps to Reproduce

1. Clone https://github.com/tmarkovski/rust-blazor-test
2. Build Rust using `cargo build --target wasm32-uknown-unknown`
3. Run Blazor project using `dotnet run` requires (net6)

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

dotnet 6.0.100

## Stacktrace

```
Unhandled Promise Rejection: Error: JS object instance with ID NaN does not exist (has it been disposed?).

Unhandled Promise Rejection: TypeError: Underlying ArrayBuffer has been detached from the view

TypeError: Buffer is already detached

[Error] Error
	_handle_exception_for_call (dotnet..2lu21tdpyb.js:8518)
	managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle (managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle:16)
	_js_owned_object_finalized (dotnet..2lu21tdpyb.js:7389)
	_js_owned_object_finalized
```

**Comment by lambdageek** [comment]
hi @tmarkovski, please report .NET 6 issues to https://github.com/dotnet/runtime.  I went ahead and copied this issue over there dotnet/runtime#61600

**Comment by lambdageek** [comment]
Closing this one in favor of dotnet/runtime#61600
