### ISSUE TITLE
.NET 6 Android, The certificate data cannot be read with the provided password, the password may be incorrect

### ISSUE THREAD

**Issue by amarthere** [mono/mono#21300]
I created sample application in VS 2022 with .NET 6.0 for both Android and iOS.
In that application I am creating X509Certificate object using pfx file and password.
The application is running fine on iOS but on Android i am getting below error:
Can you please look into it?

I am attaching sample application which reproduces the issue:
[MauiApp1.zip](https://github.com/mono/mono/files/7509160/MauiApp1.zip)

Exception: The certificate data cannot be read with the provided password, the password may be incorrect.
[DOTNET] Exception:    at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
[DOTNET]    at Internal.Cryptography.Pal.AndroidCertificatePal.ReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean ephemeralSpecified)
[DOTNET]    at Internal.Cryptography.Pal.AndroidCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[DOTNET]    at Internal.Cryptography.Pal.AndroidCertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[DOTNET]    at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[DOTNET]    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
[DOTNET]    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
[DOTNET]    at MauiApp1.App.ECDSACertificateTest() in C:\Users\jadhaa01\source\repos\MauiApp1\MauiApp1\App.xaml.cs:line 154

**Comment by jonpryor** [comment]
FYI "mono" moved into [dotnet/runtime](https://github.com/dotnet/runtime) ages ago, so this issue wasn't known about until 2023-May-16.

**Comment by lewing** [comment]
moved to https://github.com/dotnet/runtime/issues/86349
