### ISSUE TITLE
WASM Browser Error mono/mono/mini/aot-runtime.c:2038

### ISSUE THREAD

**Issue by SeanLeitzinger** [mono/mono#21370]
## Steps to Reproduce

1. Publish Blazor .NET 6.0 with AOT compilation enabled.
2. Follow the instructions here https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#compression for enabling brotli compression in Blazor standalone using the brotli decode.min.js
3. Serve application and note the brotli files are now served correctly.

![image](https://user-images.githubusercontent.com/24277209/146057509-26a51188-6d17-4a4a-9e08-81f5e0419e47.png)

4. Console throws error displayed below:
![image](https://user-images.githubusercontent.com/24277209/146057639-194eaa71-b34e-403a-94da-0b6da525f9dc.png)

### Current Behavior
Blazor app fails to load after enabling brotli compression according to MS documentation.
### Expected Behavior
Blazor App loads successfully and serves brotli files without mono AOT error.
## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X ] Windows Server 2019

**Version Used**:
I'm not sure what mono version Blazor on .NET 6 is using.

## Stacktrace
  | 16412802 | @ | dotnet.6.0.0.9h8pz7bqtg.js:1
-- | -- | -- | --
  | _emscripten_asm_const_int | @ | dotnet.6.0.0.9h8pz7bqtg.js:1
  | $func56082 | @ | 1589c21e:0x1781185
  | $func78944 | @ | 1589c21e:0x182ca19
  | $func19753 | @ | 1589c21e:0x98e765
  | $func3892 | @ | 1589c21e:0x1cde5d
  | $func220 | @ | 1589c21e:0xd3a50
  | $func20423 | @ | 1589c21e:0x9af373
  | $func12894 | @ | 1589c21e:0x54b4a6
  | $func12889 | @ | 1589c21e:0x54970e
  | $func19672 | @ | 1589c21e:0x98a9ce
  | $func5240 | @ | 1589c21e:0x251eb2
  | $func3532 | @ | 1589c21e:0x1a7e4f
  | $func20423 | @ | 1589c21e:0x9afdf4
  | $func12894 | @ | 1589c21e:0x54b4a6
  | $func12889 | @ | 1589c21e:0x54970e
  | $func19672 | @ | 1589c21e:0x98a9ce
  | $func5240 | @ | 1589c21e:0x251eb2
  | $Hd | @ | 1589c21e:0x98ec28
  | ccall | @ | dotnet.6.0.0.9h8pz7bqtg.js:1
  | (anonymous) | @ | dotnet.6.0.0.9h8pz7bqtg.js:1
  | bind_assembly_entry_point | @ | dotnet.6.0.0.9h8pz7bqtg.js:1
  | call_assembly_entry_point | @ | dotnet.6.0.0.9h8pz7bqtg.js:1
  | callEntryPoint | @ | blazor.webassembly.js:1
  | St | @ | blazor.webassembly.js:1
  | await in St (async) |   |  
  | (anonymous) | @ | (index):19

**Comment by lambdageek** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/62806
