### ISSUE TITLE
[LoongArch64] I want to add a new architecture of LoongArch64

### ISSUE THREAD

**Issue by shushanhf** [mono/mono#21381]
I want to add a new architecture of LoongArch64 for Mono.

Now I had finished the backend for LoongArch64, and some parts of the mini.

Now I plan to push them to the mono and develop the LoongArch64 on the github until I finish it.

**Comment by shushanhf** [comment]
First, I create a new issue #21388 `genmdesc.py supports the “#else” for “mini-ops.h”`.
Then I had pushed the first patch for LoongArch64 #21389

**Comment by lambdageek** [comment]
@shushanhf New work on mono (in .NET 6 and newer) is being done in https://github.com/dotnet/runtime.

This repository https://github.com/mono/mono is for the version of Mono that is compatible with .NET Framework 4.x

Is your goal to build a .NET Framework compatible Mono for LoongArch64?  Or do you want to add this support only to .NET 7 Mono?

If you want to update .NET Framework-compatible mono to support LoongArch64, we will need patches for the `main` branch in this repo, and also for the `2020-02` branch which produces the [Mono 6.12 stable packages](https://www.mono-project.com/download/stable/#download-lin).  (There is no release from the `main` branch right now)

If you also want to update .NET 7 Mono, we can take patches in the `dotnet/runtime` repo on the `main` branch.

**Comment by shushanhf** [comment]
> @shushanhf New work on mono (in .NET 6 and newer) is being done in https://github.com/dotnet/runtime.
> 
> This repository https://github.com/mono/mono is for the version of Mono that is compatible with .NET Framework 4.x
> 
> Is your goal to build a .NET Framework compatible Mono for LoongArch64? Or do you want to add this support only to .NET 7 Mono?
> 
> If you want to update .NET Framework-compatible mono to support LoongArch64, we will need patches for the `main` branch in this repo, and also for the `2020-02` branch which produces the [Mono 6.12 stable packages](https://www.mono-project.com/download/stable/#download-lin). (There is no release from the `main` branch right now)
> 
> If you also want to update .NET 7 Mono, we can take patches in the `dotnet/runtime` repo on the `main` branch.

Thanks for your guidance!!!

I think we need both .NET7 and mono  because some tools needs mono supporting LoongArch64.

Now I pushed the LoongArch64 for .NET7 first and then I will push the .NET7-runtime-mono, is this ok ?

**Comment by shushanhf** [comment]
> @shushanhf New work on mono (in .NET 6 and newer) is being done in https://github.com/dotnet/runtime.
> 
> This repository https://github.com/mono/mono is for the version of Mono that is compatible with .NET Framework 4.x
> 
> Is your goal to build a .NET Framework compatible Mono for LoongArch64? Or do you want to add this support only to .NET 7 Mono?
> 
> If you want to update .NET Framework-compatible mono to support LoongArch64, we will need patches for the `main` branch in this repo, and also for the `2020-02` branch which produces the [Mono 6.12 stable packages](https://www.mono-project.com/download/stable/#download-lin). (There is no release from the `main` branch right now)
> 
> If you also want to update .NET 7 Mono, we can take patches in the `dotnet/runtime` repo on the `main` branch.

Hi, @lambdageek 
Now we have pushed all the patches to support LoongArch64 for mono.
And our local mono had been tested by many mono's apps during the past two years, even the unity3D can run on LoongArch64-linux. There are some screenshot-pictures.
![Uploading 图片3.png…]()

**Comment by shushanhf** [comment]
![图片1](https://github.com/mono/mono/assets/35673267/a1c441bf-2e57-4fa8-b1ac-1dfdf200b8ca)

![图片2](https://github.com/mono/mono/assets/35673267/31a854ad-0939-4548-9481-12de5ece58b6)

![图片3](https://github.com/mono/mono/assets/35673267/5708dc99-06f1-4993-8eb0-fefad160c9cc)

**Comment by shushanhf** [comment]
> > Next we will push these PRs to `2020-02`.
> 
> @shushanhf, thanks for the contribution. Unfortunately, we aren't taking changes in the 2020-02 branch. Keeping them in main is the way to go.

What you means is that we push these patches to the branch `2020-02`, there is no need to push them to the main branch, is it right?
Thanks.

**Comment by steveisok** [comment]
> What you means is that we push these patches to the branch `2020-02`, there is no need to push them to the main branch, is it right? Thanks.

The opposite. We'll take the changes in the main branch only.

**Comment by shushanhf** [comment]
> > What you means is that we push these patches to the branch `2020-02`, there is no need to push them to the main branch, is it right? Thanks.
> 
> The opposite. We'll take the changes in the main branch only.

Ok, Thanks very much.

**Comment by shushanhf** [comment]
Hi, @steveisok @akoeplinger 
How to push the submodules within the external directory?
```
     external/bdwgc
     external/boringssl
     external/corefx
```

**Comment by shushanhf** [comment]
> Hi, @steveisok @akoeplinger How to push the submodules within the external directory?
> 
> ```
>      external/bdwgc
>      external/boringssl
>      external/corefx
> ```

These submodules don't belong to mono.
