### ISSUE TITLE
Invoking function pointer with type argument of Class that calls Environment.StackTrace fails

### ISSUE THREAD

**Issue by UnityAlex** [mono/mono#21478]
In Unity this code causes a crash while walking the callstack. I suspect mono is also crashing but silently. It appears that when `mono_walk_stack_full` attempts to call `get_method_from_stack_frame` when the frame is `MyManagedFunction`. It appears that the `generic_info` passed to `get_method_from_stack_frame` is just random memory and the generic context for the jitted function was never filled out.

## Steps to Reproduce

1. Build & Run repro code

```
using System;

public class Program
{
    public unsafe class TEST
    {
        public static void ManagedGenericCall()
        {
            ((delegate*<void>)&MyGenericClass<MyClass>.MyManagedFunction)();
        }
    }

    public class MyGenericClass<T>
    {
        public static void MyManagedFunction()
        {
            Console.WriteLine("printed from MyManagedFunction: "+ Environment.StackTrace);
        }
    }

    public class MyClass
    {

    }

    public static void Main (string[] args)
	{
		Console.WriteLine("Foo");
        TEST.ManagedGenericCall();
	}
}
```

### Current Behavior

No callstack printed. Possible silent crash.

### Expected Behavior

Callstack printed to console.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:

```
Mono JIT compiler version 6.13.0 (Visual Studio built mono)
Copyright (C) Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

**Comment by UnityAlex** [comment]
Corresponding Unity bug: https://issuetracker.unity3d.com/issues/crash-on-invoking-function-pointer-runtime-invoke-object-when-type-argument-is-a-class

**Comment by UnityAlex** [comment]
Duplicate of: https://github.com/mono/mono/issues/20962 -- closing

**Comment by UnityAlex** [comment]
Actually it looks like we have the fix for that bug and despite the similarities it is still occurring in this scenario unfortunately.

**Comment by bholmes** [comment]
@lambdageek I believe that this PR in runtime addresses this issue... 

https://github.com/dotnet/runtime/pull/66350

Can you guys look into bringing this back to Mono?  
cc: @vargaz
