### ISSUE TITLE
Cannot update mono

### ISSUE THREAD

**Issue by Vytzia** [mono/mono#21473]
Whenever I type "sudo apt update" in the terminal, I get this message:

N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.mono-project.com/repo/ubuntu stable-focal InRelease' doesn't support architecture 'i386'

What should I do to fix this?

**Comment by ffirenze** [comment]
Check if in your repository list file, depending the OS it can be located in "/etc/apt/sources.list.d/", has defined a custom architecture. 
 It should have a line like: "deb https://download.mono-project.com/repo/ubuntu stable-$CODENAME main" with the realo codename.

**Comment by directhex** [comment]
That's a note, not an error. We don't build for i386 any more (we wanted to, but packages in the official 20.04 repo we needed were gone). It's harmless if you only want x64 packages, it just means your system is configured for i386 packages
