### ISSUE TITLE
Monodevelop installation failed on RH8

### ISSUE THREAD

**Issue by laurentAPPIC** [mono/mono#21547]
Hello,
I try to install Monodevelop on Linux RH8 and I have this message when I execute yum install mono-devel
ImportError: /usr/lib64/python3.6/site-packages/libcomps/_libpycomps.so: undefined symbol: crc32
Thanks for your help

**Comment by siwatanejo** [comment]
MonoDevelop is deprecated in favour of dotdevelop.

**Comment by akoeplinger** [comment]
Correct.
