### ISSUE TITLE
mono 6.12.0.182 fails to build on macOS Ventura

### ISSUE THREAD

**Issue by fxcoudert** [mono/mono#21567]
## Steps to Reproduce

1. Build mono 6.12.0.182 from source as part of Homebrew on macOS Ventura (Apple Silicon):

```
brew install -svd mono
```

### Current Behavior

Failure to compile, with the following error message:

```
mono-threads-mach-helper.c:63:8: error: no member named 'class' in 'struct objc_super'
          super.class = nsobject;
```

### Expected Behavior

On previous macOS Monterey, the same build was successful.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**: macOS 13.0 (released version)

**Comment by lambdageek** [comment]
It's an Xcode 14 issue, I think.  We need to bring over https://github.com/dotnet/runtime/pull/76433
