### ISSUE TITLE
dead link for downloads in readme.md - https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/

### ISSUE THREAD

**Issue by vsix27** [mono/mono#21595]
## Steps to Reproduce

1.  open https://github.com/mono/mono/blob/main/sdks/wasm/docs/getting-started/obtain-wasm-sdk.md#download-webassembly-sdk
2. click on [WebAssembly Last Successful Build](https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/)

### Current Behavior

page is is not loading

### Expected Behavior

should see build/s to download

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x ] Windows

**Version Used**:

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by akoeplinger** [comment]
Yes the webassembly SDK in mono/mono is no longer maintained, please check out Blazor WASM in .NET6+ or the dotnet/runtime repo.
