### ISSUE TITLE
Non open source files in the Mono repo

### ISSUE THREAD

**Issue by CsatariGergely** [mono/mono#21596]
## Steps to Reproduce

1. Search for [this text](https://github.com/mono/mono/search?p=1&q=Information+Contained+Herein+is+Proprietary+and+Confidential.) in the repo 

### Current Behavior
It is great, that Mono was open sourced, but I believe some files do still have the proprietary header in them. It would be more clear to either remove these files or ask the copyright holder to open source them. 

### Expected Behavior

Remove non open source files form the repo or open source them.

## On which platforms did you notice this

[x] macOS
[x] Linux
[x] Windows

**Version Used**: Current upstream [master](https://github.com/mono/mono/commit/e2c5f4b0ad1a6b21ca0735f0b35b8611d4ad87b3)

## Stacktrace

N/A

**Comment by akoeplinger** [comment]
Those are from the Microsoft referencesource repo (originally at https://github.com/Microsoft/referencesource) which are licensed under MIT: https://github.com/mono/mono/blob/5b51d9ceeeb9bd8097c95946fd74189abda0b944/mcs/class/referencesource/LICENSE.txt

**Comment by CsatariGergely** [comment]
@akoeplinger thanks for the clarification. The copyright header in the files look like they are propitiatory and it is often debated if the repo declared license have precedence over the file level licenses or vice versa, plus license scanning tools detect these files as propriatory licensed. It would be more clear if these files would get an MIT copyright header if they are licensed as MIT. Would it be possible to update the files?

**Comment by akoeplinger** [comment]
To be honest I don't think anyone cares at this point. The future of Mono is in the dotnet/runtime repo.
