### ISSUE TITLE
UART / Serialport problem with BreakState On raspberry pi 3

### ISSUE THREAD

**Issue by Sebbasstt** [mono/mono#21626]
Hi, I have a code that works well on windows 7/10 with multiple USB/SERIAL drivers used for DMX512 (sending 512 bytes continuously with a small pause of 40 ms from the thread.

code !
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Threading;
using System.IO.Ports;
using System.Diagnostics;

namespace ECL_GUI
{
    public class DMXCommunication
    {
        private Thread _th_SendToDmx;
        private SerialPort _SerialPort;
        private string _ComPort = "COM5";

        private bool _ComError = false;
        private bool _ComOk = false;
        private int _CommOpenCount = 0;
        private int _CommTxCount = 0;
        private int _CommErrorCount = 0;
        private string _CommErrorString = "";
        private string _CommDebug = "";

        // public property *********************************************************************************
        public string ComPort
        {
            get { return _ComPort; }
        }

        public bool ComError
        {
            get { return _ComError; }
            set
            {
                _ComError = value;
            }
        }

        public string CommErrorString
        {
            get { return _CommErrorString; }
        }

        public string CommDebug
        {
            get { return _CommDebug; }
        }

        public bool ComOk
        {
            get
            {
                return _ComOk; }
            set
            {
                _ComOk = value;
            }
        }

        public int CommOpenCount
        {
            get { return _CommOpenCount; }
        }

        public int CommTxCount
        {
            get { return _CommTxCount; }
        }

        public int CommErrorCount
        {
            get { return _CommErrorCount; }
        }

        // constructor *************************************************************************************
        public DMXCommunication(string comPort)
        {
            _ComPort = comPort;
            _th_SendToDmx = new Thread(Thread_Communication);
            _th_SendToDmx.IsBackground = true;
            _th_SendToDmx.Start();
        }

        private void Thread_Communication()
        {
            Stopwatch swt = new Stopwatch();
            string str = "";
            while (_th_SendToDmx.IsAlive)
            {
                try
                {
                    if (_SerialPort == null || ComError)
                    {
                        try
                        {
                            ComError = false;
                            _SerialPort = null;
                            _SerialPort = new SerialPort(_ComPort, 250000, Parity.None, 8, StopBits.Two);
                            _SerialPort.RtsEnable = false;
                            _SerialPort.Handshake = Handshake.None; 
                            _SerialPort.WriteBufferSize = 512;
                            _SerialPort.Open();

                            //_SerialPort.BreakState = true;

                            //_SerialPort.BreakState = false;

                            _CommOpenCount++;
                        }
                        catch (IOException ex2)
                        {
                            ComError = true;
                            _CommErrorString = ex2.Message;
                            _CommErrorCount++;
                            try
                            {
                                string filepath = "ERROR3_DMX.txt";
                                if (File.Exists(filepath))
                                {
                                    File.Delete(filepath);
                                }
                                using (StreamWriter sw = new StreamWriter(filepath))
                                {
                                    sw.WriteLine(ex2.Message);
                                    sw.WriteLine(ex2.StackTrace);
                                    sw.Close();
                                }
                            }
                            catch { }
                        }
                        catch (InvalidOperationException ex3)
                        {
                            ComError = true;
                            _CommErrorString = ex3.Message;
                            _CommErrorCount++;
                            try
                            {
                                string filepath = "ERROR4_DMX.txt";
                                if (File.Exists(filepath))
                                {
                                    File.Delete(filepath);
                                }
                                using (StreamWriter sw = new StreamWriter(filepath))
                                {
                                    sw.WriteLine(ex3.Message);
                                    sw.WriteLine(ex3.StackTrace);
                                    sw.Close();
                                }
                            }
                            catch { }
                        }
                        catch (Exception ex)
                        {
                            ComError = true;
                            _CommErrorString = ex.Message;
                            _CommErrorCount++;
                            try
                            {
                                string filepath = "ERROR_DMX.txt";
                                if (File.Exists(filepath))
                                {
                                    File.Delete(filepath);
                                }
                                using (StreamWriter sw = new StreamWriter(filepath))
                                {
                                    sw.WriteLine(ex.Message);
                                    sw.WriteLine(ex.StackTrace);
                                    sw.Close();
                                }
                            }
                            catch { }
                        }
                    }
                    //  serial not null
                    if (_SerialPort != null)
                    {
                        if (_SerialPort.IsOpen)
                        {
                            swt.Reset();
                            swt.Start();
                            _SerialPort.BreakState = true;
                            swt.Stop();
                            str = " A: " + swt.ElapsedMilliseconds.ToString() + " ms ";

                            swt.Reset();
                            swt.Start();
                            _SerialPort.BreakState = false;
                            swt.Stop();
                            str += " B: " + swt.ElapsedMilliseconds.ToString() + " ms ";

                            swt.Reset();
                            swt.Start();
                            _SerialPort.Write(DMXChannels.Channels, 0, DMXChannels.Channels.Length);
                            swt.Stop();
                            str += " C: " + swt.ElapsedMilliseconds.ToString() + " ms ";

                            swt.Reset();
                            swt.Start();
                            _CommTxCount++;
                            _SerialPort.DiscardOutBuffer();
                            _SerialPort.DiscardInBuffer();
                            swt.Stop();
                            str += " D: " + swt.ElapsedMilliseconds.ToString() + " ms ";

                            ComOk = true;
                        }
                        else
                        {
                            ComError = true;
                            ComOk = false;
                            _CommErrorString = "Comm port close !";
                            _CommErrorCount += 10;
                        }
                    }
                    else
                    {
                        ComError = true;
                        ComOk = false;
                    }
                    if (ComError)
                    {
                        System.Threading.Thread.Sleep(1000);
                        _CommErrorCount++;
                    }

                }
                catch (Exception ex)
                {
                    ComError = true;
                    _CommErrorCount += 100;
                    string filepath = "ERROR2_DMX.txt";
                    if (File.Exists(filepath))
                    {
                        File.Delete(filepath);
                    }
                    using (StreamWriter sw2 = new StreamWriter(filepath))
                    {
                        sw2.WriteLine(ex.Message);
                        sw2.WriteLine(ex.StackTrace);
                        sw2.Close();
                    }
                }
                _CommDebug = str;
                Thread.Sleep(40);
            }

            _CommErrorString = "Thread Not Alive !";
        }
    }
}

You will notice code for debugging as it is running on a raspberry pi and I am trying to figure out what is my problem.. the problem is that I have to _SerialPort.BreakState = true; and _SerialPort.BreakState = false; otherwise nothing is sent to you on the port.. as I say the same code has been running on windows for years... when I do _SerialPort.BreakState = true; there is a delay of 270 ms exactly at point       A: 270ms.. ..    looking at the code, you will understand.

only with mono that I have this problem, I use the same USB / Serial converter an enttec open dmx

thanks

**Comment by Sprocket1979** [comment]
@Sebbasstt I am having the same problem. Did you find a solution ?
Thanks in advance.

**Comment by Sebbasstt** [comment]
unfortunately I couldn't find a solution in .net, I created a code in C++ for the serial port and made a UDP link between the two applications

**Comment by sancheolz** [comment]
Did you tried this implementation?https://github.com/jcurl/RJCP.DLL.SerialPortStream

**Comment by Sebbasstt** [comment]
> Did you tried this implementation?https://github.com/jcurl/RJCP.DLL.SerialPortStream

Thank you !

**Comment by Sebbasstt** [comment]
> @Sebbasstt I am having the same problem. Did you find a solution ? Thanks in adva
