### ISSUE TITLE
missing release tarballs for newer releases

### ISSUE THREAD

**Issue by rnagy** [mono/mono#21674]
The last release tarball on the website is 6.12.0.182 however the current
release is 6.12.0.199. No problem, you think, you can get the archives from
github, which is correct, but mono is using submodules which are not included
in the archive tarball, so you are shit out of luck.

Do people really have to clone multiple gigabytes of git repos? (~5.8G at the moment). 

Just think about distro packagers, if they need to clone all these repositories
every time their packages get built, because they will not cache the pulled repositories
like you would cache tarballs to avoid downloading it every time.
Obviously they can hand-roll their own tarballs if they want, but I think the
upstream project should take care of this and do it once properly.

I am sorry but this way of distributing source code is simply bad, but if
mono insists on going this way, then please fix the website so that it does
not try to tell people to download tarballs which are simply not available.

Thanks!

**Comment by akoeplinger** [comment]
Sorry, this was just an oversight. The tarball is available on https://download.mono-project.com/sources/mono/mono-6.12.0.199.tar.xz now.

**Comment by alucryd** [comment]
The tarball for the latest 6.12.0.206 release is also missing.

**Comment by tnAuth** [comment]
Just switch to WineHQ for having both mono and gdiplus updated.
