### ISSUE TITLE
Unable to access Gtk# Online API Documentation 

### ISSUE THREAD

**Issue by nishanthkp** [mono/mono#21688]
http://docs.go-mono.com/monodoc.ashx?link=root:/classlib-gnome

Trying to access Gtk# online API Documentation in page https://www.mono-project.com/docs/gui/gtksharp/

![IMG_20230728_133340](https://github.com/mono/mono/assets/65843011/cca6202c-378f-4c9e-a0e6-1ea46165ef08)

**Comment by nick-morhun** [comment]
Same as https://github.com/mono/mono/issues/21637

**Comment by akoeplinger** [comment]
This was fixed.
