### ISSUE TITLE
gpg: CRC error; C18FEB - E39330

### ISSUE THREAD

**Issue by bbfjumper** [mono/mono#21756]
Hi all, 

I tried to install mono on my RPI 5. When I use the command: `sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF`

I get the following error: 

`gpg: CRC error; C18FEB - E39330` 
`gpg: read_block: read error: Invalid keyring`

If you need more information, dont hesitate to inform me :) 

I would be very happy If anybody could help me,
thanks!

**Comment by fedeserral** [comment]
hi! same issue #21753

**Comment by bbfjumper** [comment]
thanks for the quick answer! sadly nothing changed. 

`ls /usr/share/keyrings/` finds:
`mono-official-archive-keyring.gpg`, after deleting it and execute `sudo wget https://download.mono-project.com/repo/xamarin.gpg -O /usr/share/keyrings/mono-official-archive-keyring.gpg` 

I get: 

`2024-03-26 10:27:58 (75.1 MB/s) - ‘/usr/share/keyrings/mono-official-archive-keyring.gpg’ saved [2125/2125]`

But then apt update gives me: 


`Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease                   
Hit:3 http://archive.raspberrypi.com/debian bookworm InRelease                            
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease                             
Get:5 https://download.mono-project.com/repo/ubuntu stable-focal InRelease [4,416 B]
Hit:6 https://download.mono-project.com/repo/debian wheezy InRelease
Err:5 https://download.mono-project.com/repo/ubuntu stable-focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A6A19B38D3D831EF
Reading package lists... Done
W: GPG error: https://download.mono-project.com/repo/ubuntu stable-focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A6A19B38D3D831EF
E: The repository 'https://download.mono-project.com/repo/ubuntu stable-focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://download.mono-project.com/repo/debian wheezy InRelease' doesn't support architecture 'arm64'`

gnupg was already up to date and installed.

**Comment by bbfjumper** [comment]
I asked a collegue and his solution works fine for me: 

`rm /usr/share/keyrings/mono-official-archive-keyring.gpg`

`gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF`

`echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list`

`sudo apt update`

**Comment by memnoch** [comment]
Old I know, but:

Using plain xamarin_ring gave me errors, so I ended up using https://download.mono-project.com/repo/xamarin_ring.gpg instead and that fixed all my problems

Hope that helps if anyone is still struggling with this..
