### ISSUE TITLE
Mono Update in Ubuntu 24.05 amd64 - The specified blob does not exist

### ISSUE THREAD

**Issue by Danrancan** [mono/mono#21767]
I have installed mono repositories on an AMD64 PC running Ubuntu 24.04. I used the following command to download the key and install the sources.list file:

```
sudo mkdir -p /etc/apt/keyrings && sudo gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && echo -e "\n### Mono Official Repository for Ubuntu 24.04 (amd64) on PC \n### https://www.mono-project.com/download/stable/#download-lin-ubuntu \n\ndeb [arch=amd64 signed-by=/etc/apt/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" \
	| sudo tee /etc/apt/sources.list.d/mono-official-stable.list
```

After, I do a `sudo apt update` which returns the following:
```
Err:19 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 Packages
  404  The specified blob does not exist. [IP: 13.107.213.51 443]
Err:19 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 Packages
  404  The specified blob does not exist. [IP: 13.107.213.51 443]
Fetched 11.2 kB in 1s (10.2 kB/s)
Reading package lists... Done
E: Failed to fetch https://download.mono-project.com/repo/ubuntu/dists/stable-focal/main/binary-amd64/Packages  404  The specified blob does not exist. [IP: 13.107.213.51 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Is the repository down or is this happening because I am using an Ubuntu 20.04 repository when on Ubuntu 24.04?  

Please let me know! Thanks!

**Comment by 3bbbeau** [comment]
There is currently an issue it seems. I experienced what you described 15 hours ago building an image. PPA was fine earlier this week.

**Comment by gewentao** [comment]
same here trying to install mono on x64 pc with ubuntu 20.04

**Comment by akoeplinger** [comment]
Apologies for the issue, we changed something on the backend of the download server that caused this issue. I've reverted the change for now, it should take a bit for the CDN nodes to catch up and things should start working again.

**Comment by 3bbbeau** [comment]
I can confirm that rollback has fixed it for me, thank you.

**Comment by jeffschwMSFT** [comment]
@Danrancan and @3bbbeau sorry that y'all ran into this issue, though glad we were able to correct it.  Would you mind sharing what y'all are using the legacy mono for?  From your posts, it looks like both of y'all are using Ubuntu 20.04 X64.  Thanks.  Happy to take this off-line if that works better for y'all.

**Comment by directhex** [comment]
Is it currently working?

**Comment by spragatiprag** [comment]
Err:8 http://download.mono-project.com/repo/debian stable-buster/snapshots/6.12 Release   
  404  Not Found [IP: X.X.X.X]
Hit:9 http://apt.newrelic.com/debian newrelic Release               
Hit:11 http://deb.debian.org/debian buster-updates InRelease
Reading package lists... Done
E: The repository 'http://download.mono-project.com/repo/debian stable-buster/snapshots/6.12 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
