### ISSUE TITLE
Trouble download mono 6.12 installer from download.mono-project.com

### ISSUE THREAD

**Issue by theJenix** [mono/mono#21771]
Not sure if this is the right place, but following the instructions on www.mono-project.com it seemed like it was worth discussion.  I am having trouble downloading the mono installer for 6.12 for Windows 64-bit from a browser, wget, or thru chocolatey.

## Steps to Reproduce

1. Browse to www.mono-project.com
2. Click download, then Windows
3. Click Download Mono 64-bit (no GTK#)

3b. Or, right click on Download Mono 64-bit (no GTK#), copy the link, and in a terminal execute `wget <copied link>`
3c. Or, on a Windows machine with Chocolatey installed, run `choco install mono -y` in an Administrator terminal.

### Current Behavior

Varying degrees of ending too early, failing and retrying, or downloading a partial file.

On Linux with wget, I get something that looks like:

<img width="1174" alt="2024-05-10_14-07-41" src="https://github.com/mono/mono/assets/1337080/2896124e-9260-41bc-b0f5-281f5278b088">

It seems to hang like that indefinitely.

In Edge on Windows, it just hangs.

`choco` claims the download is successful but then it fails the checksum

These results were observed on several machines in several hosting configurations (local/residential cable internet, AWS EC2, cloud hosted CI server, to name a few).

Incidentally, Safari on macOS downloads the file just fine.

### Expected Behavior

The file should download successfully in all cases.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[x] Windows

**Version Used**:

6.12.0.206-x64

## Stacktrace

N/A

**Comment by admalledd** [comment]
For what it is worth, it seems that the https://download.mono-project.com server(s) are having a bit of an issue. Here is a screengrab of the error if attempted to use a browser:
![image](https://github.com/mono/mono/assets/161795/c71b871c-5afc-4568-9c40-b11bba4a884f)

and for the network guru numbers: `20240510T223815Z-17c65945bcbjfc8b4eu0eadc6000000006mg00000002bz7u`

I am intermittently getting successful pages/downloads again so I think things are coming back up?

**Comment by theJenix** [comment]
I think things have improved, but my `choco` install from my CI (circleCI, Windows server 2019 image) is still failing its checksum test which suggests the connection is being closed before the download is complete.

**Comment by directhex** [comment]
Any improvement?

**Comment by michaelosthege** [comment]
Yes. The HTTP link now runs into a `The account being accessed does not support http` error, but switching to HTTPS works just fine.

**Comment by alexiaizenberg** [comment]
Every time it's a different issue:

`<Error>`
`<Code>BlobNotFound</Code>`
`<Message>`
`The specified blob does not exist. RequestId:fe01150d-101e-008a-6b02-a84ba2000000 Time:2024-05-17T02:29:22.4767384Z`
`</Message>`
`</Error>`

**Comment by directhex** [comment]
> Yes. The HTTP link now runs into a `The account being accessed does not support http` error, but switching to HTTPS works just fine.

OK, is HTTP working again?

**Comment by alexiaizenberg** [comment]
> > Every time it's a different issue:
> > `<Error>` `<Code>BlobNotFound</Code>` `<Message>` `The specified blob does not exist. RequestId:fe01150d-101e-008a-6b02-a84ba2000000 Time:2024-05-17T02:29:22.4767384Z` `</Message>` `</Error>`
> 
> I don't know what file is being referred to here, so there's nothing for me to investigate.

Anything under snapshots:
https://download.mono-project.com/repo/ubuntu/dists/stable-focal/snapshots/index.html

**Comment by directhex** [comment]
I'll see what I can do about at least a portion of the missing index.html files

**Comment by directhex** [comment]
OK, index.html files to a folder depth of _9_ have been created, rather than the wget default of 5
