### ISSUE TITLE
Error when trying to install Mono - Hash Sum mismatch

### ISSUE THREAD

**Issue by jackfoulkes-integra** [mono/mono#21819]
## Steps to Reproduce

1.  Following steps on https://www.mono-project.com/download/stable/#download-lin for Ubuntu
2. Upon doing sudo apt install mono-complete the installation fails with the following error:

>  Hash Sum mismatch
>   Hashes of expected file:
>    SHA256:2c819e6575dece4882f21d442c27c22df1198cb3acdb3c057ab9fecb7655a509
>    SHA1:486c60996e25f261d5935e07846c0b47b07b4041 [weak]
>    MD5Sum:f1763f848696bccbbb52a722cf0fbc79 [weak]
>    Filesize:17392560 [weak]
>   Hashes of received file:
>    SHA256:df14be90a9c2f229ab3e1600ac723257c4d0e8f888a4ccc0e3ead538937c87dc
>    SHA1:ba1e4726e2966c227e432a95e3f3e48373bc9435 [weak]
>    MD5Sum:001241deb636347c36ed82cb902928c8 [weak]
>    Filesize:17392560 [weak]
>   Last modification reported: Wed, 15 May 2024 20:45:00 +0000

![image](https://github.com/user-attachments/assets/097e8717-3520-4e37-adb3-56c4f5b1e8a7)

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Comment by akoeplinger** [comment]
I just tried and I don't see the issue here. Can you try again and see if it was just an intermittent issue?

**Comment by jackfoulkes-integra** [comment]
> I just tried and I don't see the issue here. Can you try again and see if it was just an intermittent issue?

Thanks for the reply, I was getting the issue throughout the entire day, I have tried again and it seems to have resolved itself. Thanks.
