### ISSUE TITLE
Compile problem - error CS0006: Metadata file './../../../external/api-snapshot/profiles/net_4_x/System.Net.Http.dll' could not be found  

### ISSUE THREAD

**Issue by shevegen** [mono/mono#6150]
Hello.

Not sure if this is the right place to report this; please close this if it is the wrong place.

Upon trying to compile:

  http://download.mono-project.com/sources/mono/mono-5.9.0.569.tar.bz2

I ran into an error:
 
make[3]: Leaving directory '/Depot/Temp/mono-5.9.0.569/data'  
make[2]: Leaving directory '/Depot/Temp/mono-5.9.0.569/data'  
make[1]: Leaving directory '/Depot/Temp/mono-5.9.0.569/data'  
Making install in runtime
make[1]: Entering directory '/Depot/Temp/mono-5.9.0.569/runtime'  
cd /Depot/Temp/mono-5.9.0.569/mcs && make NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_x xbuild_12 xbuild_14 ' RUNTIME_HAS_CONSISTENT_GACDIR=yes prefix=/Programs/Mono/5.9.0.569 install-profiles 
make[2]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs'  
make profile-do--binary_reference_assemblies--install profile-do--net_4_x--install profile-do--xbuild_12--install profile-do--xbuild_14--install  
make[3]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs'  
make PROFILE=basic install  
make[4]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs'  
make[5]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/build'  
make install-local  
make[5]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/build' 
make[5]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/jay'  
make install-local  
make[6]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/jay'  
make[6]: Nothing to be done for 'install-local'.  
make[6]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/jay' 
make[5]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/jay' 
make[5]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/class'  
make[6]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/class/corlib' 
make install-local  
make[6]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/class/corlib'  
make[6]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/class/Mono.Security'  
make install-local  
make[7]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/class/Mono.Security'  
(cd ../System; make ../../class/lib/basic/bare/System.dll)  
make[8]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/class/System' 
make intermediate=bare/ ./../../class/lib/basic/bare/System.dll 
make[9]: Entering directory '/Depot/Temp/mono-5.9.0.569/mcs/class/System' 
CSC [bare/basic] System.dll 
error CS0006: Metadata file './../../../external/api-snapshot/profiles/net_4_x/System.Net.Http.dll' could not be found  
make[9]: *** [../../build/library.make:342: ../../class/lib/basic/bare/System.dll] Error 1  
make[9]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/class/System'  
make[8]: *** [Makefile:160: ../../class/lib/basic/bare/System.dll] Error 2  
make[8]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/class/System'  
make[7]: *** [Makefile:31: ../../class/lib/basic/bare/System.dll] Error 2 
make[7]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/class/Mono.Security' 
make[6]: *** [../../build/rules.make:211: do-install] Error 2 
make[6]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/class/Mono.Security' 
make[5]: *** [../build/rules.make:232: install-recursive] Error 1 
make[5]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs/class' 
make[4]: *** [build/rules.make:232: install-recursive] Error 1  
make[4]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs' 
make[3]: *** [Makefile:54: profile-do--basic--install] Error 2  
make[3]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs' 
make[2]: *** [Makefile:50: profiles-do--install] Error 2
make[2]: Leaving directory '/Depot/Temp/mono-5.9.0.569/mcs'
make[1]: *** [Makefile:601: install-exec] Error 2
make[1]: Leaving directory '/Depot/Temp/mono-5.9.0.569/runtime'
make: *** [Makefile:541: install-recursive] Error 1

My system is slackware, linux, 64 bit, gcc version is 7.2.0

I was able to compile mono from source a few weeks ago, on the
same system, so I am almost absolutely sure that the problem is
related to something in mono. But I have too little domain specific
knowledge to really tell what went wrong. Hopefully you guys can
spot the problem. I'll try with another release perhaps in 2 weeks
or so - if you don't hear another report from me then that should
mean that the release in 2 weeks or so, worked. :)

To make the error more explicit, it was:

**error CS0006: Metadata file './../../../external/api-snapshot/profiles/net_4_x/System.Net.Http.dll' could not be found**

**Comment by alexischr** [comment]
Hello @shevegen , please use https://bugzilla.xamarin.com/ to report issues/bugs or mono-devel-list@lists.dot.net to discuss Mono development topics . The 'Issues' Github feature seems to have been enabled by accident. We don't currently use it.
