### ISSUE TITLE
fork() - Mono.Unix.Native

### ISSUE THREAD

**Issue by gene-l-thomas** [mono/mono#6151]
I have noticed that in [mono/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs](https://github.com/mono/mono/blob/master/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs) fork() is #if'd out with the message "_DO NOT directly call fork(2); it bypasses essential shutdown code. Use System.Diagnostics.Process instead_".

What happens specifically? `fork()` starts a process, it does not shut anything down? `fork()` should just work, does it not (effectively (copy on write)) copy the entire VM which then each shuts down independently? `fork()` does work in Python on Unix (multiprocessing module). 

`fork()` is powerful, it supports using processes as an alternative to threads. One can not test for a one in a million race condition. `System.Diagnostics.Process` only replaces `fork()` then `exec()`. I wish to use `fork()` to support replicated processes, starting with a complete copy of the application's state greatly simplifies this.

**Comment by alexischr** [comment]
Hello @gene-l-thomas, please use https://bugzilla.xamarin.com/ to report issues/bugs or mono-devel-list@lists.dot.net to discuss Mono development topics . The 'Issues' Github feature seems to have been enabled by accident. We don't currently use it.

**Comment by migueldeicaza** [comment]
Please use the mailing list to discuss these topics, we will answer on `mono-devel-list` the reasons for that.

**Comment by lewurm** [comment]
that's where you find `mono-devel-list`: https://lists.dot.net/mailman/listinfo/mono-devel-list
