### ISSUE TITLE
Potential bug in HttpContext.RewritePath

### ISSUE THREAD

**Issue by polterguy** [mono/mono#6153]
I have created my own URL rewriting logic, by making sure I invoke `HttpContext.Current.ReWritepath("~/Default.aspx", true)` in my Global.asax.cs inside of `Application_BeginRequest`. This should map all requests to a single page, my `Default.aspx` that is.

The problem comes later during the setting of my `ASP.NET_SessionId` cookie, and also the resolving of my `WebResouce.axd` files, but only if my first HTTP request goes towards a double nested folder inside of my webapp. E.g. `/foo/bar`.

If I access my webapp with my first request being `/`, the resolving of my cookie paths and WebResource.axd inclusions are correctly mapped, and they go towards `path=/` and `/WebResource.axd?xxx`.

Notice, the really weird thing, is that if I access my site first with e.g. `/`, then all later cookie paths and WebResource inclusions, also in a double folder becomes correct ... :P

If I however create my first HTTP request towards e.g. `/foo/bar`, then my WebResource.axd inclusion tries to include my inclusion as `/foo/WebResource.axd?xxx`, and my `ASP.NET_SessionId` cookie path becomes `/foo`, which of course is not correct ...

I have tried to look at the source code for `HttpRequest` and `HttpContext`, to try to determine what they do, and where the bug could be, without success. However, I suspect it is related to the setting of `_clientBaseDir` within `HttpRequest. InternalRewritePath`, which I assume is later referenced during inclusion of scripts, and the setting of the path for the session cookie, etc ...

For the record, I have tried tons of different variations, including `HttpContext.Current.ReWritepath("~/Default.aspx", false)`, and many others. And I am pretty confident in that this is somehow a bug in Mono ...

I am going to attempt to use reflection to physically change the internal state of some of your hidden fields, to try to find out more about this, but obviously it's important I believe that a more permanent fix is somehow provided ...

Please advice :)

Thomas

**Comment by kumpera** [comment]
Hi,

Providing a test case would help people trying to fix your issue to validate it.

**Comment by polterguy** [comment]
Sorry, I should have given you feedback. I dropped mod_mono_auto, and used a more "manual configuration", and it magically vanished. I assume mod_mono_auto seems to believe I have multiple websites with my folder structure. Which seems the natural explanation, since it seems to JIT compile some additional stuff in my subfolders, since it spends 500MS the first request, and some 50-70MS on consecutive requests ...

Even though other folders are actually accessed, and most of the CLR should have been already compiled ...

Thanks anyways :)

**Comment by kumpera** [comment]
Hi @polterguy,

I'm a bit confused, are you still seeing this issue? Is there something we could help you with to produce a test case?

**Comment by polterguy** [comment]
Not really, the bugs was highly likely due to me using mod_mono_auto, in a site, where it did not fit. My bad :)
