### ISSUE TITLE
Consolidate the concept of a tools thread and a thread that has opted out of STW

### ISSUE THREAD

**Issue by alexrp** [mono/mono#6188]
Right now, we have two ways of opting out of participating in STW:

* Attach as a tools thread (call `mono_threads_attach_tools_thread`).
* Attach normally and opt out (call `mono_gc_set_skip_thread`).

I believe that it would be completely fine for us to consolidate these two. Currently, a tools thread is basically just a thread that's attached through the `MonoThreadInfo` infrastructure *only* (i.e. it has no `MonoInternalThread` set, no domain, etc). Only the profiler uses tools threads. In reality, all the profiler needs is that tools threads do not participate in STW and are not considered for statistical sampling - nothing else. Having a `MonoInternalThread` and a domain set for these threads is not a problem at all.

In fact, *not* having a domain set for tools threads is proving to be a problem. The tools threads in the profiler sometimes call into runtime functions that end up wanting to use `mono_domain_get`, thus crashing since no domain is set. For example, using the log profiler with an AOT-compiled Roslyn results in this crash:

```
	0   mono                                0x0000000101a5fd91 mono_handle_native_crash + 257
	1   mono                                0x00000001019b334c mono_sigsegv_signal_handler + 220
	2   libsystem_platform.dylib            0x00007fffcf037b3a _sigtramp + 26
	3   ???                                 0x00007fb1cd479810 0x0 + 140401629960208
	4   mono                                0x0000000101ae61e7 mono_assembly_load_full_nosearch + 439
	5   mono                                0x0000000101ae22a8 mono_assembly_load_full_internal + 40
	6   mono                                0x0000000101ae1f17 mono_assembly_load_reference + 519
	7   mono                                0x0000000101ae8c5d mono_class_from_typeref_checked + 573
	8   mono                                0x0000000101af767d mono_class_get_checked + 173
	9   mono                                0x0000000101b4ac16 mono_metadata_parse_type_internal + 1238
	10  mono                                0x0000000101b4b5ee mono_metadata_parse_method_signature_full + 590
	11  mono                                0x0000000101b25aa3 mono_method_signature_checked + 483
	12  mono                                0x0000000101b05c46 mono_method_get_name_full + 726
	13  libmono-profiler-log.0.dylib        0x0000000101ecaf3d handle_writer_queue_entry + 205
	14  libmono-profiler-log.0.dylib        0x0000000101ecad98 writer_thread + 568
	15  libsystem_pthread.dylib             0x00007fffcf04193b _pthread_body + 180
	16  libsystem_pthread.dylib             0x00007fffcf041887 _pthread_body + 0
	17  libsystem_pthread.dylib             0x00007fffcf04108d thread_start + 13
```

So, my plan to fix this is as follows:

* Remove the whole tools thread concept.
* Remove `mono_gc_set_skip_thread` (it's not public API).
* Move the `gc_disabled` field to `MonoThreadInfo`.
* Introduce `mono_thread_info_set_skip_suspend` (replaces `mono_gc_set_skip_thread`) and `mono_thread_info_set_skip_sample`.
* Attach profiler background threads normally (possibly even start them using `mono_thread_create_internal`).
* Use the new functions to make the runtime skip STW and sampling on profiler background threads.
* Make the rest of the runtime check these bits where needed.

---

Originally filed at: https://bugzilla.xamarin.com/show_bug.cgi?id=59024

**Comment by alexrp** [comment]
cc @luhenry @kumpera

**Comment by kumpera** [comment]
Hi Alex,

Do we need to care about making those flags be set at attach time? IE, have a `mono_attach_with_flags`? This is to make sure we don't accidentally STW/sample those threads.

Beyond that detail, this proposal looks good.

**Comment by alexrp** [comment]
That would probably be a good idea.
