### ISSUE TITLE
[Unix] w32process-unix.c mono_w32process_signal_finished breaks all child process status queries

### ISSUE THREAD

**Issue by PeteLewisUnity** [mono/mono#6200]
This issue refers to this code here: https://github.com/mono/mono/blob/dd34edb9076b05cefd37b53bb8f0fb1b8f1884a3/mono/metadata/w32process-unix.c#L1408-L1414

This change severely impacts process management for Unix-based applications.

`waitpid(-1,...)` reaps _all_ zombie child processes of the calling process. See `man waitpid`. After a child process is reaped, it can no longer be queried. Because this reaping step is [invoked via the `SIGCHLD` signal](https://github.com/mono/mono/blob/dd34edb9076b05cefd37b53bb8f0fb1b8f1884a3/mono/metadata/w32process-unix.c#L1383), all zombie children of the calling process are reaped every time any child process terminates, regardless of whether that child process was tracked by Mono. 

The impact of this is that apps using Mono that spawn their own child processes (outside of Mono's `w32process` API) cannot call `wait` on children, cannot query exit codes, and so on. A call to `waitpid(my_child_pid,...)` will return `ECHILD` for "no such child" because Mono has already cleaned up the child the moment `SIGCHLD` was raised.

A suggested fix would be to only wait on processes that Mono owns, rather than all child processes for the calling process:

```c
	for (process = processes; process; process = process->next) {
		do {
			pid = waitpid (process->pid, &status, WNOHANG);
		} while (pid == -1 && errno == EINTR);

		if (process->pid != pid) // catches both no-change status (0) and error codes (-1)
			continue;
		if (process->signalled)
			continue;

		process->signalled = TRUE;
		process->status = status;
		mono_os_sem_post (&process->exit_sem);
		mono_memory_barrier ();
		/* Mark this as freeable, the pointer becomes invalid afterwards */
		process->freeable = TRUE;
		break;
	}
```

**Comment by lewurm** [comment]
Hey @PeteLewisUnity, that sounds useful. Can you submit a PR with your suggested change, so we can give it a try on CI?

**Comment by PeteLewisUnity** [comment]
Absolutely! I've already made the change locally and am about to verify it. Expect it in the next few hours. Thanks!

**Comment by luhenry** [comment]
Hi @PeteLewisUnity sounds indeed like a great idea, please submit a PR and assign it to me. Thank you!

**Comment by PeteLewisUnity** [comment]
Sweet, thanks. Done. I don't know if you can see it before I've signed the CLA? Just waiting on legal to clear me to sign that (shouldn't be a problem).
