### ISSUE TITLE
XBuild fails with "Error executing task CreateCSharpManifestResourceName: String literal not closed"

### ISSUE THREAD

**Issue by ahzf** [mono/mono#6213]
Hi... I found a strange little bug I really do not understand:

If have a .NET framework project serving files via HTTP(S). I also have some time script files which are Embedded Resources and get complied with the help of the tsconfig.json file. In Visual Studio 2017 CE everything is fine. But even with yesterdays mono version from GitHub I get the following error:

```
/home/ahzf/SWUpdatesAPI/CAUpdates.sln (default targets) ->
(Build target) -> /home/ahzf/SWUpdatesAPI/CAUpdates/CAUpdates.csproj (default targets) ->
/usr/local/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CreateManifestResourceNames target) ->
                                        /usr/local/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets: error : Error executing task CreateCSharpManifestResourceName: String literal not closed
                                         4 Warning(s)
                                         1 Error(s)
```

The problem seems to be the following bit stupid line of code in one of the type script files:

`(versionDiv.querySelector("#repositoryId") as HTMLDivElement).innerHTML = "<a href=\"../../" + repositoryId + "\">" + repositoryId + "</a>";`

When I change the double quotation marks into single ones xbuild accepts everything and the complie error goes away:

`(versionDiv.querySelector("#repositoryId") as HTMLDivElement).innerHTML = '<a href=\"../../' + repositoryId + '\">' + repositoryId + '</a>';`

I'm not sure if this is really the mono source causing all the trouble:
[https://github.com/mono/mono/blob/master/mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks/CreateCSharpManifestResourceName.cs](https://github.com/mono/mono/blob/master/mcs/class/Microsoft.Build.Tasks/Microsoft.Build.Tasks/CreateCSharpManifestResourceName.cs)

Does anyone know which intent lies behind CreateCSharpManifestResourceName.cs? Why is it parsing files? And why seems VS and tsc not having a problem with this line of code?

Best...
  Achim

**Comment by akoeplinger** [comment]
`xbuild` is deprecated, please try using `msbuild` instead.

**Comment by ahzf** [comment]
"msbuild" is unknown in my mono build (from GitHub / Debian 9).
Is there anywhere a good documentation how to build msbuild for a mono build?

I'm only idea would be to install dotnet core, but "dotnet msbuild" leads to other errors regarding the missing ".NET 4.7 SDK or Targeting Pack".

**Comment by akoeplinger** [comment]
Please see https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild for instructions on how to build msbuild for mono.
