### ISSUE TITLE
pdb2mdb crashes on .net 4.6 dll

### ISSUE THREAD

**Issue by jsteinich** [mono/mono#6250]
## Steps to Reproduce

1. Create .net 4.6 c# library project in VS
2. Add a single class with no functionality
3. Build project
4. Run pdb2mdb on build dll

## Current Behavior

Crash

## Expected Behavior

mdb file created

### On which platforms did you notice this

- [ ] macOS
- [ ] Linux 
- [x] Windows

**Version Used**:

pdb2mdb 4.2.3.4 from mono.unofficial.pdb2mdb nuget
VS 2017

### Stacktrace

```
Fatal error:
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings)
   at Pdb2Mdb.Driver.Convert(AssemblyDefinition assembly, Stream pdb, MonoSymbolWriter mdb)
```

I also tried using the pdb2mdb bundled with Unity at Data\MonoBleedingEdge\lib\mono\4.5\pdb2mdb.exe. That just printed the usage with no error.

**Comment by akoeplinger** [comment]
This happens when you have a Portable PDB which isn't supported for conversion. You can add `<DebugType>Full</DebugType>` to the .csproj to make sure you get a legacy PDB in VS.

Newer versions of pdb2mdb have a check for this and print an error.

**Comment by jsteinich** [comment]
Thanks. That worked.
