### ISSUE TITLE
Switch the JIT --trace code to using call context introspection

### ISSUE THREAD

**Issue by alexrp** [mono/mono#6271]
Now that the profiler API has full support for selective enter/leave instrumentation and simple/portable inspection of stack frames (arguments, locals, return value), we could implement the `mono --trace` functionality using this API. This would allow us to get rid of the arch-specific `mono_arch_instrument_prolog` and `mono_arch_instrument_epilog`, both of which are known to be somewhat unreliable (the reason we switched enter/leave instrumentation to using internal calls in the first place).

**Comment by vargaz** [comment]
The current profiler instrumentation changes generated code by disabling optimizations etc., that could interfere from --trace.

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/6285

**Comment by alexrp** [comment]
This was done long ago in https://github.com/mono/mono/pull/10885.
