### ISSUE TITLE
update F# Compiler in Mono to >= VS 15.5.2 

### ISSUE THREAD

**Issue by ctaggart** [mono/mono#6281]
The F# Compiler for Mono on Mac is from June. Can you please update it to be the same as VS 15.5.2 that just shipped or newer? I opened up the corresponding issue in the Visual F# repo so ya'll can coordinate. https://github.com/Microsoft/visualfsharp/issues/4143 cc @directhex and @nosami 

May be the version bump goes into Mono 5.6. I'm not sure about the timeline on that. 

https://github.com/mono/mono/blob/master/packaging/MacSDK/fsharp.py
https://github.com/mono/mono/blob/2017-12/packaging/MacSDK/fsharp.py

**Comment by nosami** [comment]
Mono is shipping with F# 4.1.25 which is from 5th August. The latest tag is 4.1.29 from 3rd November. https://github.com/fsharp/fsharp/tags

I can bump Master to 4.1.29. Provided that CI stays green across the board, I can look at getting the bump backported.
