### ISSUE TITLE
Miliseconds information in datetime properties from FileInfo  are not available on MONO

### ISSUE THREAD

**Issue by csances** [mono/mono#6282]
## Steps to Reproduce
===================================================

Scenario: We are running on Linux (Mono) a set of tests developed in Windows (c# .Net).
Some tests fail only in Linux.

1. Create a file,
2. initialize a FileInfo object mapping to the newly created file,
3. make some changes in the file (add some content for example) from the code (in the first second after the file's creation)
4. initialize another FileInfo object mapping to the updated file,
5. compare the LastWriteTime properties from the two FileInfo objects.

In Mono datetime properties are not taking in account miliseconds information. If you compare both FileInfo objects  you will have the same information in LastWriteTime property.

## Current Behavior:
===================================================

newFileInfo.LastWriteTime:  13:36:56.000
lastFileInfo.LastWriteTime: 13:36:56.000

## Expected Behavior:
===================================================

newFileInfo.LastWriteTime:  13:36:56.262
lastFileInfo.LastWriteTime: 13:36:56.118

We need to have the miliseconds information in Mono.

### On which platforms did you notice this
===================================================

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

5.4.1.6
4.6.1.5

Same behaviour in both versions

### Stacktrace

N/A

**Comment by csances** [comment]
FYI

Only to be clear.
The original code is on C#, and all the tests are running propertly under Windows.
The problem with the miliseconds appears when we run the same test  on Linux. In this case the datetime properties do not have miliseconds information.

I really appreciate your help.

**Comment by akoeplinger** [comment]
This is fixed by https://github.com/mono/mono/pull/6307
