### ISSUE TITLE
Mono is not able to notice a file change in a FileInfo object

### ISSUE THREAD

**Issue by csances** [mono/mono#6283]
## Steps to Reproduce

Scenario: We are running on Linux (Mono) a set of tests developed in Windows (c# .Net).
Some tests fail only in Linux.

1. Create programatically a file  and add some content inside,
2. create a FileInfo object with the current status of the file, 
3. update again this file,
4. created another FileInfo object with the current status of the file, 
5. compare both instances of the FileInfo.

## Current Behavior

Both instances of the file are the same.
It seems like the event in charge to notice the changes does not work properly under Mono. If we iterate through  the properties of the second FileInfo using reflection before the comparasion we will have the correct snapshot of the file in the second FileInfo.  But it's a non desired workaround.

## Expected Behavior

The two instances must be different after the update, becasue we are adding some content to the file.

### On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

5.4.1.6
4.6.1.5

### Stacktrace

N/A

**Comment by lambdageek** [comment]
@csances thanks for reporting this issue.  Could you provide us with some code the demonstrates the problem?
Thanks!

**Comment by migueldeicaza** [comment]
Patch:

https://github.com/mono/mono/pull/6307

To reproduce:

With the current code on Mac:

```
$ csharp -e 'Console.WriteLine (new System.IO.FileInfo ("/etc/passwd").LastAccessTime.Ticks)'
636493820550000000
```

With the pull request applied on Mac:
```
$ csharp -e 'Console.WriteLine (new System.IO.FileInfo ("/etc/passwd").LastAccessTime)'
636493820391074624
$
```

Not all filesystems have nanosecond precision, so you might not see it.

**Comment by csances** [comment]
Hi @migueldeicaza:

I think your suggestion is related with the bug number 6282 (Miliseconds information in datetime properties from FileInfo are not available on MONO). It was created by me too.
I will review your proposal.

Thank you for your help.

**Comment by csances** [comment]
Hi @lambdageek:

It's enough for you if a paste a piece of code here in a post?.

It is an example of our current situation:

 var tracker = new ContentTracker(this.folderName, filePattern);
 this.AddFile(fileName);
// AddFile code Method:
System.IO.File.WriteAllText(Path.Combine(this.folderName, fileName), "Created");
Thread.Sleep(100);
// Next method review if we have added or changed file in a folder using a FileInfo object to do this
 tracker.GetChangedContent();
 this.UpdateFile(fileName);
// UpdateFile code Method:
System.IO.File.AppendAllText(Path.Combine(this.folderName, fileName), "Updated");
Thread.Sleep(100);
// Next method review if we have added or changed file in a folder using a FileInfo object to do this
var lastChanges = tracker.GetChangedContent();

The first time we call GetChangedContent, we notice the creation of the file when we compare the FileInfo object instances.
The second time we want to know how many changes we have done. Unfortunatelly Mono is not able to notice all these changes.

Then we decided to add some tricky code in order to catch the changes. We call a method to iterate through the FileInfo properties using reflection:

private static void RefreshContentFromFileInfoList(List<FileInfo> listFileInfo)
{
    if (OperatingSystem.IsUnixPlatform())
    {
        foreach (var fileInfo in listFileInfo)
        {
            if (fileInfo != null)
            {
                foreach (var p in fileInfo.GetType().GetProperties())
                {
                    p.GetValue(fileInfo, null).ToString();
                }
            }
        }
    }
}

Once we have executed this method, Mono is able to be noticed about the changes.

Please, don't hesitate to request more information if you need it.

I really appreciate your help.

**Comment by akoeplinger** [comment]
@csances I'm a bit confused by this issue: are you saying you expect the FileInfo object to automatically notice changes to the file? That's not how it works, you need to call the `Refresh()` method.

If I'm missing something please provide a self-contained code sample that shows the problem, i.e. I assume the interesting logic is behind `ContentTracker` in your code sample :)

**Comment by csances** [comment]
Hi @akoeplinger:

I really appreciate your comments.
The thing is using this code in a windows environment I do not need to use a Refresh() command in C# code nor something similar.
When code compares the old file and the new file information in windows environment is able to detect the different value on the properties of fileinfo objects; using the same approach in Linux both objects contain the same information (I have to use RefreshContentFromFileInfoList custom method to force Linux to realize about the differences inside).
I think it is an issue in the way that Mono realizes about the changes inside a folder regarding a file.

Please don't hesitate in asking me if you need furhter explanation.

Thank you ;)

**Comment by csances** [comment]
[TestFileInfoProperties.zip](https://github.com/mono/mono/files/1626226/TestFileInfoProperties.zip)

[ResultsFromTests.txt](https://github.com/mono/mono/files/1626222/ResultsFromTests.txt)
@akoeplinger  sorry for the delay.

I am attaching here a sample project. 
You will find a C# solution with three projects:

- Port.File: class library with the source code
- Port.Helper: class library with some needed classes
- Port.File.UnitTests: test project running NUnit tests. You have to exectute these tests.

Under Windows all the tests are running well, but under Linux we started to receive some errors.
We have added too an xml file with the results of execution in Linux.

Linux distribution: Ubuntu 17.10
Mono release: 5.4.1.6deb

We really appreciate your help.
Please, let us know if you need anything else.

Thank you.

**Comment by csances** [comment]
@akoeplinger sorry for the delay.

[TestFileInfoProperties.zip](https://github.com/mono/mono/files/1626394/TestFileInfoProperties.zip)


I am attaching here a sample project.
You will find a C# solution with three projects:

- Port.File: class library with the source code
- Port.Helper: class library with some needed classes
- Port.File.UnitTests: test project running NUnit tests. You have to exectute these tests.

Under Windows all the tests are running well, but under Linux we started to receive some errors.

Linux distribution: Ubuntu 17.10
Mono release: 5.4.1.6deb

We really appreciate your help.
Please, let us know if you need anything else.

Thank you.

**Comment by csances** [comment]
# @akoeplinger 

Thank you for your help. Finally we have been able to fix the problem using Refresh method from FileInfo object.
We were not using it on Windows environment but once we have remove our own "Refresh" method for the Refresh from FileInfo object everything was ok.

**Comment by akoeplinger** [comment]
Ok good to hear although I still don't understand why it worked on Windows without calling `Refresh()` :)
