### ISSUE TITLE
mono什么版本能支持net4.5的程序

### ISSUE THREAD

**Issue by congciyizu** [mono/mono#6290]
## Steps to Reproduce

1. 
2. 
3. 

## Current Behavior

What is the current behavior?

## Expected Behavior

Please describe the behavior you are expecting

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

You can use `mono --version` or About dialog to obtain this information.

### Stacktrace

```
Please paste the stacktrace here if available.
```

  <configuration>     <system.web>         <customErrors mode="Off"/>     </system.web> </configuration>
--

**Comment by akoeplinger** [comment]
I assume https://github.com/mono/mono/issues/6291 is the real issue, closing this one.
