### ISSUE TITLE
mono哪个版本支持.net4.5的程序

### ISSUE THREAD

**Issue by congciyizu** [mono/mono#6291]
Runtime Error
A runtime error has occurred
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed (for security reasons).

Details: To enable the details of this specific error message to be viewable, please create a `<customErrors>` tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".

```xml
  <!-- Web.Config Configuration File -->
  <configuration>
     <system.web>
         <customErrors mode="Off"/>
     </system.web>
 </configuration>
```

**Comment by akoeplinger** [comment]
We'll need more info on which error you're hitting exactly (it might be an issue in your application). Since this seems to be an ASP.NET app please add the attributes as the error message tells you to get a stack trace.

**Comment by evincarofautumn** [comment]
Title should be changed to English, “Which version of Mono supports .NET 4.5 programs?” (or something similar).

**Comment by akoeplinger** [comment]
I'm closing this issue since we didn't get a response in a while. Please reopen once more details are available :)
