### ISSUE TITLE
Mono.Posix.NETStandard erronously (?) includes Framework reference to Mono.Posix

### ISSUE THREAD

**Issue by damageboy** [mono/mono#6341]
## Steps to Reproduce

1. git clone https://github.com/damageboy/mprefbug
2. export FrameworkPathOverride=/usr/lib/mono/4.6.2-api
3. Build fails

## Current Behavior
Currently when building for mono (net462) with dotnet on Linux/Mac, the Mono.Posix.NETStandard nuget adds an explicit reference to Mono.Posix.dll while also providing the same implementation inside the nuget.

As such, when building, msbuild will add references both to the nuget implementation and the Mono.Posix.dll provided as part of `/usr/lib/mono/4.6.2-api` for example, and fails thusly:

```
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Class1.cs(8,9): error CS0433: The type 'Syscall' exists in both 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' [/tmp/mpref/mpref.csproj]

Build FAILED.

Class1.cs(8,9): error CS0433: The type 'Syscall' exists in both 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' [/tmp/mpref/mpref.csproj]
    0 Warning(s)
    1 Error(s)
```

This doesn't no happen on Windows where Mono.Posix is not located in the reference assemblies folder(s).

## Expected Behavior

Build should work....

It is my suspicion that there is an error (?) on the Mono.Posix.NETStandard.nuspec as part of the nuget, which contains the following xml tags:
```xml
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Mono.Posix" targetFramework=".NETFramework4.0" />
    </frameworkAssemblies>
```

I believe this is an error on the packaging side, which once removed should/would solve this issue, and the relevant Mono.Posix bits are already delivered INSIDE the nuget...

### On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:42:04 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

**Comment by damageboy** [comment]
Just so its clear, I've created my own hack version of Mono.Posix.NETStandard which does not use the framework assemblies and it work perfectly well on Linux where one would reasonably expect `Mono.Posix` as part of the mono installation...

**Comment by marek-safar** [comment]
@bholmes where do you want to track nuget bugs?

**Comment by bholmes** [comment]
@marek-safar https://github.com/xamarin/XamarinComponents

**Comment by damageboy** [comment]
Do you want me to reopen it there?

**Comment by marek-safar** [comment]
This issue was moved to xamarin/XamarinComponents#282
