### ISSUE TITLE
messages during make dist: "file name is too long"

### ISSUE THREAD

**Issue by ArsenShnurkov** [mono/mono#6349]
## Steps to Reproduce

```
#!/bin/bash

#WORKDIR=/var/tmp/tarballs/dotnet/dev-lang/mono
WORKDIR=/1

rm -rf ${WORKDIR}
mkdir -p ${WORKDIR}
git clone https://github.com/mono/mono.git ${WORKDIR}
cd ${WORKDIR}
git submodule update --init --recursive
git reset --hard f93caff1c85d74db8561d951b96d5dde9dea8bd5
./autogen.sh
#./configure
make
make dist
```

## Current Behavior

```
test -n "" \
|| find "mono-5.11.0" -type d ! -perm -755 \
	-exec chmod u+rwx,go+rx {} \; -o \
  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -444 -exec /bin/sh /1/install-sh -c -m a+r {} {} \; \
|| chmod -R a+r "mono-5.11.0"
tardir=mono-5.11.0 && tar --format=ustar -chf - "$tardir" | BZIP2=${BZIP2--9} bzip2 -c >mono-5.11.0.tar.bz2
tar: mono-5.11.0/external/linker/linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase.cs: file name is too long (cannot be split); not dumped
tar: mono-5.11.0/external/linker/linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase2.cs: file name is too long (cannot be split); not dumped
tar: mono-5.11.0/external/linker/linker/Tests/Mono.Linker.Tests.Cases/Generics/DerivedClassWithMethodOfSameNameAsBaseButDifferentNumberOfGenericParametersUnusedBaseWillGetStripped.cs: file name is too long (cannot be split); not dumped
tar: Exiting with failure status due to previous errors
```

## Expected Behavior

I expect these files to be included into archive

### On which platforms did you notice this

Sabayon Linux

**Versions Used**:

1) tar 1.29
(the same with tar 1.30)

2) Mono JIT compiler version 5.11.0.132 (tarball Thu Dec 28 02:37:15 MSK 2017)

### Other thoughts

```
# file external/linker/linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase.cs
external/linker/linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase.cs: C++ source, UTF-8 Unicode (with BOM) text
```
they are not symlinks and should not be limited by 99 characters
https://www.gnu.org/software/tar/manual/html_node/Formats.html#SEC133

https://github.com/mono/mono/blob/master/configure.ac#L12-L14

https://savannah.gnu.org/support/?107095

**Comment by akoeplinger** [comment]
Could you please try the following patch which removes these files from the tarball (we don't use them during the build, only tests) and should workaround the problem:

```diff
diff --git a/Makefile.am b/Makefile.am
index f9dd1784c83..7e3f093f20a 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -50,6 +50,7 @@ dist-hook:
        rm -rf `find $(top_distdir)/external -path '*\.git'`
        rm -f `find $(top_distdir)/external -path '*\.exe' -not -path '*/roslyn-binaries/*'`
        rm -f `find $(top_distdir)/external -path '*\.dll' -not -path '*/binary-reference-assemblies/*' -not -path '*/roslyn-binaries/*'`
+       rm -rf "$(top_distdir)/external/linker/linker/Tests"

 pkgconfigdir = $(libdir)/pkgconfig
 noinst_DATA = mono-uninstalled.pc
```

**Comment by ArsenShnurkov** [comment]
I retested on recent mono, the problem is still here:

make[3]: выход из каталога «/1»
test -n "" \
|| find "mono-6.13.0" -type d ! -perm -755 \
	-exec chmod u+rwx,go+rx {} \; -o \
  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -444 -exec /bin/sh /1/install-sh -c -m a+r {} {} \; \
|| chmod -R a+r "mono-6.13.0"
make[2]: выход из каталога «/1»
tardir=mono-6.13.0 && tar --format=ustar -chf - "$tardir" | XZ_OPT=${XZ_OPT--e} xz -c >mono-6.13.0.tar.xz
tar: mono-6.13.0/external/llvm-project/lldb/packages/Python/lldbsuite/test/functionalities/thread/concurrent_events/breakpoints_delayed_breakpoint_one_watchpoint/TestConcurrentBreakpointsDelayedBreakpointOneWatchpoint.py: имя файла слишком длинное (не может быть разделено); не сброшено
tar: Завершение работы с состоянием неисправности из-за возникших ошибок
make[1]: выход из каталога «/1»
if test -d "mono-6.13.0"; then find "mono-6.13.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "mono-6.13.0" || { sleep 5 && rm -rf "mono-6.13.0"; }; else :; fi
