### ISSUE TITLE
Keepass crashes when editing an entry notes field in a specific way

### ISSUE THREAD

**Issue by RepNex** [mono/mono#6357]
I reported this problem first to the Keepass developer [here](https://sourceforge.net/p/keepass/bugs/1696/). But he says, it's caused by Mono.

## Steps to Reproduce

1. Open appended test.kdbx with password "123456" (without quotes)
2. Edit "Sample Entry"
3. Scroll down completely in notes field
4. Select text exactly as shown in screenshot 1
5. Press Backspace
Keepass is crashing, notes field is disappearing and "Edit Entry" window is remaining as seen in screenshot 2, completely unresponsive.

Screenshot 1 - Text Selection:
<a href="https://ibb.co/d3ON0R"><img src="https://thumb.ibb.co/d3ON0R/1_Text_Selection.png" alt="1 Text Selection" border="0" /></a>

Screenshot 2 - Crashed:
<a href="https://ibb.co/ghejEm"><img src="https://thumb.ibb.co/ghejEm/2_Crash.png" alt="2 Crash" border="0" /></a>
[test.zip](https://github.com/mono/mono/files/1596055/test.zip)

## Current Behavior

When editing an entry's notes field in a specific way, Keepass crashes.

## Expected Behavior

Not crashing...

### On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

More detailed:
Ubuntu 17.10 (default desktop environment), Keepass 2.36 (from official Ubuntu repositories)

**Version Used**:
```
mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
[...]
```

### Stacktrace

```
Please paste the stacktrace here if available.
```
How do I get this?

**Comment by akoeplinger** [comment]
You should be able to get a stacktrace by launching KeePass from the terminal, e.g. via `mono /path/to/keepass.exe` and then making it crash, it should print the stacktrace to the terminal.

**Comment by RepNex** [comment]
Alright, here the results.
1. `~$ mono /usr/lib/keepass2/KeePass.exe`
2. steps from above
3. stacktrace:
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>   at System.Windows.Forms.Document.Invalidate (System.Windows.Forms.Line start, System.Int32 start_pos, System.Windows.Forms.Line end, System.Int32 end_pos) [0x00082] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Document.InvalidateSelectionArea () [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Document.CaretHasFocus () [0x000e8] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.TextBoxBase.vscroll_ValueChanged (System.Object sender, System.EventArgs e) [0x000d5] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ScrollBar.OnValueChanged (System.EventArgs e) [0x0001c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ScrollBar.SetValue (System.Int32 value) [0x00041] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ScrollBar.UpdatePos (System.Int32 newPos, System.Boolean update_thumbpos) [0x000b8] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ScrollBar.SetValues (System.Int32 minimum, System.Int32 maximum, System.Int32 small_change, System.Int32 large_change) [0x000c8] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.ScrollBar:SetValues (int,int,int,int)
>   at System.Windows.Forms.TextBoxBase.CalculateScrollBars () [0x000fa] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.TextBoxBase.document_HeightChanged (System.Object sender, System.EventArgs e) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Document.RecalculateDocument (System.Drawing.Graphics g, System.Int32 start, System.Int32 end, System.Boolean optimize) [0x0027d] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Document.ResumeRecalc (System.Boolean immediate_update) [0x00062] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Document.ReplaceSelection (System.String s, System.Boolean select_new) [0x0025d] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.TextBoxBase.HandleBackspace (System.Boolean control) [0x0002c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.TextBoxBase.WndProc (System.Windows.Forms.Message& m) [0x001a9] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.RichTextBox.WndProc (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>   at System.Windows.Forms.Document.Draw (System.Drawing.Graphics g, System.Drawing.Rectangle clip) [0x00382] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.TextBoxBase.Draw (System.Drawing.Graphics g, System.Drawing.Rectangle clippingArea) [0x0000d] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.TextBoxBase.OnPaintInternal (System.Windows.Forms.PaintEventArgs pevent) [0x0000d] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control.WmPaint (System.Windows.Forms.Message& m) [0x00078] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x0015f] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.TextBoxBase.WndProc (System.Windows.Forms.Message& m) [0x0020f] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.RichTextBox.WndProc (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0

**Comment by filipnavara** [comment]
Reproduced on OS X with X11 driver. The fix should be as simple as moving one line, but it maybe a bit tricky to write a unit test for it.

**Comment by adamryczkowski** [comment]
I can confirm the problem is fixed in the KeePass2 with the most recent mono.
