### ISSUE TITLE
Allow AOT .so files to contain output of multiple assemblies

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#6370]
Context: https://github.com/xamarin/xamarin-android/issues/1146

Xamarin.Android [allows assemblies to be AOT'd by setting `$(AotAssemblies)` to True](https://developer.xamarin.com/guides/android/advanced_topics/building-apps/build-process/). When this is enabled, each `.dll` contained within the application will have a corresponding AOT `.so` generated, for either/both "normal" AOT and Hybrid/Full AOT mechanisms (`$(AndroidAotMode)='Hybrid'`).

Unfortunately, Android 4.3 and earlier only allow 128 native libraries to be loaded into a process, and the default process address space has ~65 already loaded (`libc.so`, etc.), giving us "headroom" of only 63 native libraries. That's ridiculously easy to hit: the [`Xamarin.Forms-Performance-Integration` project](https://github.com/xamarin/xamarin-android/tree/master/tests/Xamarin.Forms-Performance-Integration/Droid) contains *55* assemblies, and is largely a bog-standard Xamarin.Forms app. 8 more assemblies, and you hit the limit.

What is desired is a way to emit only *one* `.so` for *all* of the assembly AOT data, not one `.so` per `.dll`, as is currently done.

## Steps to Reproduce

1. [Create a Xamarin.Android app which contains ~65 assemblies](https://github.com/xamarin/xamarin-android/files/1593964/lib.zip) and sets `$(AotAssemblies)`=True.
2. Build, Deploy, and Run the Xamarin.Android app on an Android 4.3 or earlier device which supports armeabi-v7a binaries:

        cd lib
        msbuild /t:SignAndroidPackage /p:Configuration=Release
        msbuild /t:Install /p:Configuration=Release
        msbuild /t:_Run /p:Configuration=Release

        # How many native libs does this .apk contain?
        unzip -l bin/Release/*-Signed.apk | grep .so$ | wc -l
             146

3. Launch the app

## Current Behavior

App (eventually?) crashes, as it can't load the `.so`:

```
D/Mono    ( 6456): DllImport error loading library './libUnluckyLibName.so': 'Cannot load library: alloc_info[268]:   195 too many libraries when loading libUnluckyLibName.so'.
```

## Expected Behavior

App launches and runs.

### On which platforms did you notice this

- [X ] Android

**Version Used**:

mono/2017-10

**Comment by alexanderkyte** [comment]
Closing this for the same reason that https://github.com/mono/mono/pull/6703 was closed. The code branches will remain up here on Github if someone wants to revive them.
