### ISSUE TITLE
Optimize implementation of string indexer

### ISSUE THREAD

**Issue by Therzok** [mono/mono#6398]
## Steps to Reproduce

1. Disassemble mscorlib.dll
2. Observe that string indexer `get_Chars` is 0x23 code size
3. Observe that it's above JIT inline limit
4. Observe that .NETFramework/CoreCLR have the string indexing implemented as an icall

## Current Behavior

It seems that mono generates a lot more ASM code for this than Windows .NET:
https://gist.github.com/Therzok/fdc39e06db53898520a9af702d08b098

The .NET JIT code:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgBgARYCMA3ALABQuBhAdAEoCuAdjAJZhw0DCA9mAA6sANogDKiAG6sAxnChlK+IvWZsONAJItEPfuIRTZ8ihSwAmagA4uQ6FAoBvCnmoA2AgBYrACgCUzvCdyAEgifFYmfgYYPABePAAiaAATADMEhWDpAAsIBDwADzi8CKiYAG0cAF0FFwBfCgbyIA

## Expected Behavior

Probably would be better performing. Current marks the method as unsafe code, which might not optimize contents:
https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/string.cs#L675-L691

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.11.0.26 (pull-request-6203/f74a01add57 Tue Dec 12 18:08:19 EST 2017)

**Comment by marek-safar** [comment]
We could force inline it but as it throws it would throw from frame which could confuse the users

**Comment by migueldeicaza** [comment]
We already inline the call, and based on the extensive disucssion today, this was not the performance source of problems.
