### ISSUE TITLE
Invalid array cast is supported

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6401]
## Steps to Reproduce

Compile & Run
```csharp
using System.Collections.Generic;

class Program {
	static void Main (string [] args)
	{
		object intArray = new[] { 1, 2, 3 };
		IList<int?> oo = (IList<int?>)intArray;
	}
}
```

## Current Behavior

No invalid cast exception

## Expected Behavior

```System.InvalidCastException: Unable to cast object of type 'System.Int32[]' to type 'System.Collections.Generic.IList`1[System.Nullable`1[System.Int32]]'.```

### On which platforms did you notice this

[x ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.11.0 (master/1b249d561e8 Tue Jan  2 14:16:34 CET 2018)

**Comment by vargaz** [comment]
Fixed.
