### ISSUE TITLE
Implement Retpoline as a mitigation for CPU speculative execution issue

### ISSUE THREAD

**Issue by lewurm** [mono/mono#6407]
## Context

Google's Project Zero team released information about three attack scenarios around speculative execution on modern CPUs. There are three variants [(described here)](https://security.googleblog.com/2018/01/more-details-about-mitigations-for-cpu_4.html) where Variant 2 `branch target injection` is an issue for user space programs such as Mono. "Luckily" it only seems to apply to x86/amd64.

## Mitigation
There are two strategies:
1. wait for a microcode update by the CPU vendor (such as [IRBS microcode](https://lkml.org/lkml/2018/1/4/615) by Intel).
2. implement [Retpoline](https://support.google.com/faqs/answer/7625886) in our code generator.

**Comment by migueldeicaza** [comment]
Why would we need to implement this?

Mono no longer has any sandbox or setup that provides a safe execution environment, any user of Mono has complete access to the current process and can do anything they want (using raw pointers, using Marshal.Read/Write APIs, P/Invoke and so on).

**Comment by joshpeterson** [comment]
It might still be necessary to implement this. And executable which need to protect itself from an attack can use the retpoline mitigation. Likewise, the runtime would need to be compiled with the same mitigation (when available in C compilers).

For reference here are related LLVM patches:
https://reviews.llvm.org/D41723 (retpoline)
https://reviews.llvm.org/D41761, https://reviews.llvm.org/D41760 (add a builtin __builtin_load_no_speculate instrinsic)

**Comment by lewurm** [comment]
related: https://github.com/mono/mono/pull/6740
