### ISSUE TITLE
System.Numerics structs are incorrect sizes

### ISSUE THREAD

**Issue by mellinoe** [mono/mono#6411]
Many of the structures in the System.Numerics namespace are being padded out to an incorrectly-large size in memory. Although this was likely done as a kind of performance optimization, it has widespread side effects that break many of the main use cases for the types. This behavior is also different from .NET Core and .NET Framework.

The types affected:

Type | Expected Size | Actual Size
----- | -------------- | -----------
Vector2 | 8 | 16
Vector3 | 12 | 16
Plane | 16 | 20

Plane is probably larger because it contains a Vector3, but I've listed it anyways.

There are some test cases in corefx which ensure that these structures are the expected physical size in memory. [For example](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/tests/Vector3Tests.cs#L1146-L1154)

**Comment by Therzok** [comment]
Seems like the types are constrained to having at least SIMD register size.

https://github.com/mono/mono/blob/6b58f1317732b9cbf6ec61921e76d7d48e362104/mono/metadata/class.c#L1988-L1990

**Comment by akoeplinger** [comment]
I remembered this Bugzilla bug where @kumpera indicated this is expected: https://bugzilla.xamarin.com/show_bug.cgi?id=56602

**Comment by kumpera** [comment]
SIMD support was originally designed to support 16bytes only types.
The new types were added without considering this. It's something we could improve for Vector2 and Vector3.

**Comment by vargaz** [comment]
We can make them have a non-16 byte size, but then we can't do SIMD operations like loads/stores on them.

**Comment by mellinoe** [comment]
The size in memory of these structures is more important than individual SIMD optimizations, because there is a lot of code in the wild that works only under the assumption that these types are tightly-packed in memory. It is not a problem if the results of intermediate operations are expanded to a 16-byte form in order to better utilize SIMD operations -- this is what CoreCLR and .NET Framework do -- but the in-memory representation cannot change.

As a comparison, if this same behavior was observed in the analogous MonoGame structures, then everything using them would cease to function.

**Comment by kumpera** [comment]
@vargaz we can emit simd load/store for Vector2. Vector3 is a bit trickier since it can live at the edge of a page.

**Comment by mellinoe** [comment]
@kumpera @vargaz Is there any workaround for this at the moment? Some way to disable the optimizations / special codegen handling, for example? This is a pretty hard blocker for my projects working on mono.
