### ISSUE TITLE
sbyte comparison broken by optimization

### ISSUE THREAD

**Issue by arneg** [mono/mono#6414]
## Steps to Reproduce

The following code executes correctly in visual studio and with mono with all optimizations turned off (`-O=-all`). However, when run with optimization on it will incorrectly print `BAD`.

```
using System;

class foo {
  static byte encode(sbyte v) {
    byte tmp = (byte)v;
    return tmp;
  }

  static void decode(byte buf, out sbyte v) {
    byte tmp = buf;
    v = (sbyte)tmp;
  }

  static int Main(string[] argv) {
    byte tmp;

    sbyte v = -122;

    tmp = encode(v);

    sbyte t;

    decode(tmp, out t);

    if (t == v) {
      Console.WriteLine("OK");
      return 0;
    } else {
      Console.WriteLine("BAD");
      return 1;
    }
  }
}
```

## Current Behavior

`mcs test.cs`
`mono test.exe`
prints `BAD`

## Expected Behavior

`t` and `v` should be equal and `OK` should be printed.

### On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**: `Debian 4.6.2.7+dfsg-1ubuntu1`

**Comment by lewurm** [comment]
thanks for your report @arneg, I can reproduce the bug. FWIW the interpreter prints "OK" 🙂

**Comment by vargaz** [comment]
-O=-inline alone fixes it.

**Comment by vargaz** [comment]
Seems to be an alias analysis problem, we remove an implicit sign/zero extension by removing a load/store, -O=-alias-analysis works around it.

**Comment by jaykrell** [comment]
Peanut gallery asks: Can the load/store be removed, but retain casts to the stored/loaded types, and then the casts' presence inhibits the incorrect optimization, unless the sequence of casts is identical on either side, or maybe somehow equivalent. I'm not sure what equivalence is possible, other than identical. Perhaps runs of casts to same type could be removed (int)(int)i == (int)i.
