### ISSUE TITLE
Update Mono we use in CI

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#6450]
Currently we use mono 4.6 in the chroot-based build jobs which causes some confusing messages to be produced (https://github.com/mono/mono/issues/6430). We should update to later 5.x which should just be a config change on Jenkins.

**Comment by directhex** [comment]
55 jobs are using a Mono 4.6 chroot to build. I'll prioritize the main test-* jobs

**Comment by directhex** [comment]
All jobs except old ones where 4.6 is relevant, and three with "special" OS images bumped to `${label}-stable`, which reflects whatever mono-project.com says is stable. will look at outliers next

**Comment by akoeplinger** [comment]
Thank you!
