### ISSUE TITLE
http://download.mono-project.com/repo/ubuntu/dists/nightly/main/ not updated

### ISSUE THREAD

**Issue by oddball** [mono/mono#6482]
I reported this at https://gitter.im/mono/mono before but wanted to track any progress.

The last update of http://download.mono-project.com/repo/ubuntu/dists/nightly/main/  is from 2017-11-27

New builds are not put into the repo.

**Comment by marek-safar** [comment]
@directhex could you look into it

**Comment by akoeplinger** [comment]
As it happens, this was just fixed and should contain a build from last night now :)

Please note that you should generally use `nightly-<releasename>` like shown at http://www.mono-project.com/download/nightly/#download-lin-ubuntu as the legacy `nightly` repo just points to Ubuntu precise to keep the existing consumers working.

**Comment by oddball** [comment]
Is this broken again @akoeplinger ? Or are there just not any new builds?

The last update of http://download.mono-project.com/repo/ubuntu/dists/nightly/main/ is from 2018-02-06 and corresponds to 
``` 
Mono JIT compiler version 5.13.0.8 (tarball Tue Feb  6 10:43:13 UTC 2018)
```

refs #7067

**Comment by marek-safar** [comment]
@directhex did we stop updating this location?

**Comment by akoeplinger** [comment]
This is because of

```bash
dpkg-gensymbols: warning: debian/tmp/DEBIAN/symbols doesn't match completely debian/libmonoboehm-2.0-1.symbols.amd64
--- debian/libmonoboehm-2.0-1.symbols.amd64 (libmonoboehm-2.0-1_5.13.0.136-0nightly1+debian7b1_amd64)
+++ dpkg-gensymbolszntqbC	2018-02-19 10:39:16.460584900 +0000
@@ -993,6 +993,7 @@
  mono_guid_to_string@Base 4.1.0.1738
  mono_guid_to_string_minimal@Base 4.5.2.618
  mono_hazard_pointer_get@Base 4.7.0.488
+ mono_icall_table_init@Base 5.13.0.136-0nightly1+debian7b1
  mono_image_add_to_name_cache@Base 4.1.0.1738
  mono_image_addref@Base 4.1.0.1738
  mono_image_close@Base 4.1.0.1738
make: *** [binary-arch] Error 2
```

Every time a new runtime public API is added we need to update a file in the .deb packaging. This one was added by https://github.com/mono/mono/pull/6905.

I've updated the packaging file with https://github.com/mono/linux-packaging-mono/commit/ad76f5a318d1be242c1cb7d2357ddf712dbdf538 so new nightly builds should show up again soon. I'll close this issue once they are.

**Comment by oddball** [comment]
confirmed working with
``` 
Mono JIT compiler version 5.13.0.208 (tarball Fri Feb 23 11:16:28 UTC 2018)
```
