### ISSUE TITLE
Reenable weak-fields.exe test

### ISSUE THREAD

**Issue by luhenry** [mono/mono#6490]
Extracted from https://bugzilla.xamarin.com/show_bug.cgi?id=60973

It fails with the following output

```
Finalized. 0
Finalized. 0
Finalized. 0
Finalized. 16946264
```

@vargaz noted that it's the test that seems flaky since it doesn't expect the object to be randomly retained.

It was disabled with https://github.com/mono/mono/pull/6191

**Comment by vargaz** [comment]
It also fails on osx with aot:
mono --aot weak-fields.exe
mono weak-fields.exe

**Comment by vargaz** [comment]
This looks like a real bug and not a test failure.
