### ISSUE TITLE
Heap-Shot does not build

### ISSUE THREAD

**Issue by hutchdan** [mono/mono#6499]
## Steps to Reproduce

1. Download https://github.com/mono/heap-shot
2. Install GTK# from http://www.mono-project.com/download/#download-win
3. Build in Visual Studio 2017

## Current Behavior

Compilation fails

Severity	Code	Description	Project
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetObjectCountForType' and no extension method 'GetObjectCountForType' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetObjectsByType' and no extension method 'GetObjectsByType' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetObjectSizeForType' and no extension method 'GetObjectSizeForType' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetObjectTypeName' and no extension method 'GetObjectTypeName' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetObjectTypeName' and no extension method 'GetObjectTypeName' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetReferencers' and no extension method 'GetReferencers' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetTypeFromName' and no extension method 'GetTypeFromName' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetTypeName' and no extension method 'GetTypeName' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'GetTypes' and no extension method 'GetTypes' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1061	'ObjectMapReader' does not contain a definition for 'RemoveData' and no extension method 'RemoveData' accepting a first argument of type 'ObjectMapReader' could be found 	HeapShot
Error	CS1503	Argument 1: cannot convert from 'HeapShot.Reader.ObjectMapReader' to 'HeapShot.Reader.HeapSnapshot'	HeapShot

## Expected Behavior

Compilation succeeds

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[X ] Windows

**Version Used**:

N/A

### Stacktrace

N/A

**Comment by alexrp** [comment]
This tools is very, very outdated. It can't even read log files produced by recent versions of the log profiler.

**Comment by hutchdan** [comment]
Alex

Thanks for you quick response.

The reason I am trying to use it is that Xamarin Profiler cannot compare snapshots. The guidance on the Xamarin pages is to use HeapShot to perform these comparisons.

**Comment by migueldeicaza** [comment]
Not a Mono bug.

**Comment by migueldeicaza** [comment]
The Xamarin profiler can compare snapshot, just the last two.

**Comment by rodrmoya** [comment]
@hutchdan what page in the Xamarin docs has that guidance?

Indeed the Xamarin Profiler allows comparing snapshots, just in a different way than HeapShot, so if you want, let me know what you find missing on it so that we can improve it.

**Comment by hutchdan** [comment]
https://developer.xamarin.com/guides/ios/deployment,_testing,_and_metrics/monotouch_profiler/

[cid:800338b9-19a5-478c-a9b1-fa2bc778b7b7]


Monotouch Profiler - Xamarin<https://developer.xamarin.com/guides/ios/deployment,_testing,_and_metrics/monotouch_profiler/>
developer.xamarin.com
This article shows how to set up and use the profiler that is included in Xamarin Studio and Xamarin.iOS. Using a given sample, we’ll run this tool through its ...

In Xamarin Profiler for Android I cannot see how to compare snapshots. I would much prefer to perform detailed snapshot comparisons within Xamarin Profiler but I can't work out how to do it.


________________________________

**Comment by rodrmoya** [comment]
in the xamarin profiler the diff between the current and the previous snapshot is just shown by default. That is, on the snapshots list, double click on one of them and that would display the objects present in the selected snapshot grouped by class. On the right-side panel there is a 'only new objects' checkbox. When checked, it just displays the objects added to the selected snapshot compared to the previous one, when unselected, it lists all objects present in the snapshot.

Another way to look at it is at the 'Allocations' view. Again, double clicking on one of the classes will display the allocations for that class, and there's a column specifying whether the object is still live (i.e., it was present in the last snapshot) or not.

We don't support comparing arbitrary snapshots yet, but we're working on that as we speak.

**Comment by hutchdan** [comment]
Rodrigo


Thanks for your explanation. I will use Xamarin Profiler going forward and forget about Heap-Shot.


Daniel

________________________________
