### ISSUE TITLE
Missing counters/perf counters in Mono 5.8 with new profiler arguments

### ISSUE THREAD

**Issue by rodrmoya** [mono/mono#6512]
## Steps to Reproduce

1. Run any desktop mono app with: `/Library/Frameworks/Mono.framework/Versions/Current/bin/mono --gc=sgen --profile=log:heapshot=ondemand,nolegacy,jit,gc,nogcalloc,gcroot,gcmove,counter,output="/var/folders/rd/w957krqd3rn1zps5z6r75kz00000gn/T/n4rhtedd.mlpd" app.exe`
2. Let it run for a few seconds and stop
3. `mprof-report /var/folders/rd/w957krqd3rn1zps5z6r75kz00000gn/T/n4rhtedd.mlpd` shows no counters

## Current Behavior

Using the old runtime arguments (`alloc,heapshot=ondemand,counters`) produces a MLPD with counters on it.

## Expected Behavior

Counters should be emitted in the MLPD file

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```$ mono --version
Mono JIT compiler version 5.8.0.103 (2017-10/1359c52fc6e Wed Dec 20 10:52:54 EST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by alexrp** [comment]
The option you want is almost certainly `nodefaults` which has to come first, so like this:

```
$ mono --profile=log:nodefaults,heapshot=ondemand,jit,gc,gcroot,gcmove,counter app.exe
```

This outputs all the events you expect.

That said, I think there is still a bug here. In your original invocation, `gc`, `counter`, etc come *after* the `nolegacy`, so I would expect them to take effect. @kumpera can you confirm if this is the intended behavior?

**Comment by rodrmoya** [comment]
The problem was indeed the `nolegacy` option, removing that fixed the problem
