### ISSUE TITLE
Mono's MSBuild is slow on Mac due to constant IO

### ISSUE THREAD

**Issue by Therzok** [mono/mono#6530]
## Steps to Reproduce

1. See https://github.com/Microsoft/msbuild/blob/30b19e9f2cefb6d9675d660c8bb8b317c06ff9a1/src/Shared/NativeMethodsShared.cs#L553-L556

## Current Behavior

IO is done to check whether the platform is OS X.

## Expected Behavior

IO should be done at most once, or some other detection mechanism should be used. (pinvoke libc and get OS name)

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.11.0.168 (pull-request-6404/6f02ba66ba8 Thu Jan  4 16:11:23 EST 2018)

Probably should be backported to all releases

**Comment by marek-safar** [comment]
@radical We should just remove #if Mono and get it to 2017-10 and newer versions

**Comment by Therzok** [comment]
The same problem plagues the path without `#if MONO`
https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Runtime.InteropServices.RuntimeInformation/RuntimeInformation.cs#L44-L57

**Comment by marek-safar** [comment]
@vargaz could you make the OSX check faster in RuntimeInformation

**Comment by migueldeicaza** [comment]
Pull request submitted: https://github.com/Microsoft/msbuild/pull/2864

**Comment by akoeplinger** [comment]
This was fixed and backported to 2017-10, 2017-12 and master.
