### ISSUE TITLE
Bug report give up https://bugzilla.xamarin.com

### ISSUE THREAD

**Issue by Rombersoft** [mono/mono#6572]
Why does bug report give up https://bugzilla.xamarin.com?
And who does support mono project now?

1. 
2. 
3. 

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by marek-safar** [comment]
https://bugzilla.xamarin.com still works and can be used for search for existing bugs. However, it was closed for any new one as we switched to github issues instead
