### ISSUE TITLE
Cannot access disposed object (System.Net.Sockets.NetworkStream)

### ISSUE THREAD

**Issue by piejanssens** [mono/mono#6601]
Mono 5.4

Radarr/Radarr#1416
Radarr/Radarr#1556
Radarr/Radarr#1003
Sonarr/Sonarr#2296
linuxserver/docker-radarr#17
linuxserver/docker-sonarr#62

Related: https://bugzilla.xamarin.com/show_bug.cgi?id=58641

Comment from  Martin Baulig:
```
Ok, I spent some time playing around with this and it looks like .NET only cancels _pending_ requests when HttpClient.Dispose() is called.

It will not actually close the underlying connection as Mono's implementation currently does.
```

**Comment by marek-safar** [comment]
We are not moving already reported issue to gitbub, please stay with the original bug report
