### ISSUE TITLE
build on cygwin, have error

### ISSUE THREAD

**Issue by wuguanxi** [mono/mono#6615]
I do it according to the instructions by http://www.mono-project.com/docs/compiling-mono/windows/
PATH=$PREFIX/bin:$PATH
git clone https://github.com/mono/mono.git
cd mono
do shell cmd ./autogen.sh --prefix=$PREFIX --host=x86_64-w64-mingw32 --disable-boehm
Git submodules updated successfully

        mcs source:    mcs
        C# Compiler:   roslyn

   Engine:
        Host:          x86_64-w64-mingw32
        Target:        x86_64-w64-mingw32
        GC:            sgen (concurrent by default)
        TLS:           pthread
        SIGALTSTACK:   no
        Engine:        Building and using the JIT
        BigArrays:     no
        DTrace:        no
        LLVM Back End: no (dynamically loaded: no)

   Libraries:
        .NET 4.x:        yes
        Xamarin.Android: no
        Xamarin.iOS:     no
        Xamarin.WatchOS: no
        Xamarin.TVOS:    no
        Xamarin.Mac:     no
        Windows AOT:     no
        Orbis:           no
        Unreal:          no
        WebAssembly:     no
        Test profiles:   AOT Full (no), AOT Hybrid (no)
        JNI support:     no
        libgdiplus:      assumed to be installed
        zlib:
        BTLS:            no
        jemalloc:        no (always use: no)

Now type `make' to compile

---------------------------then make have error------------------------------
akefile:27: 警告：覆盖关于目标“test-local”的配方
../../build/library.make:216: 警告：忽略关于目标“test-local”的旧配方
Makefile:27: 警告：覆盖关于目标“test-local”的配方
../../build/library.make:216: 警告：忽略关于目标“test-local”的旧配方
CSC     [basic] System.Security.dll
CSC     [basic] System.Configuration.dll
CSC     [basic] System.Xml.dll
CSC     [basic] System.dll
CSC     [basic] System.Core.dll
CSC     [basic] System.ComponentModel.Composition.dll
CSC     [basic] System.Numerics.dll
CSC     [basic] System.Xml.Linq.dll
CSC     [basic] Mono.Cecil.dll
CSC     [basic] Mono.CompilerServices.SymbolWriter.dll
CSC     [basic] PEAPI.dll
Converting cil-stringreplacer.exe.sources to ../../build/deps/cil-stringreplacer.exe.sources.response ...
CSC     [basic] cil-stringreplacer.exe
Converting ilasm.exe.sources to ../build/deps/ilasm.exe.sources.response ...
CSC     [basic] ilasm.exe
C:/cygwin64/home/Administrator/mono/mono/mini/mono-sgen.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
make[8]: *** [il.make:4：../../../class/lib/basic/corlib.unsafe.dll.tmp] 错误 127
make[7]: *** [../../../build/rules.make:211：do-all] 错误 2
make[6]: *** [../build/rules.make:232：all-recursive] 错误 1
make[5]: *** [build/rules.make:232：all-recursive] 错误 1
make[4]: *** [Makefile:54：profile-do--basic--all] 错误 2
make[3]: *** [Makefile:50：profiles-do--all] 错误 2
make[2]: *** [Makefile:613：all-local] 错误 2
make[2]: 离开目录“/home/Administrator/mono/runtime”
make[1]: *** [Makefile:558：all-recursive] 错误 1

**Comment by marek-safar** [comment]
You need to `make` in root folder of mono tree

**Comment by jaykrell** [comment]
Could be .dll not found. I had saw some similar and had to add unusual directories to %PATH%.
To debug this you install the Windows debuggers (not Visual Studio), use gflags to "set loader snaps" on mono-sgen.exe and then just run it. You'll see a lot of debugprint and maybe buried in there some .dlls not found, something about pthread and libgcc.
