### ISSUE TITLE
StepOver on methods with more than 1 arguments

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6621]
## Steps to Reproduce

1. Follow #6617 

## Current Behavior

If the method has two arguments and we step into in the first argument evaluation then "step over" we cannot step into in second arguments because debugger skip the whole method execution. I created the test to reproduce this problem.

## Expected Behavior

Tests Passes

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

mono master

**Comment by marek-safar** [comment]
@alexanderkyte are you working on the issue?

**Comment by thaystg** [comment]
The same thing that #7326, that is already closed.
