### ISSUE TITLE
Jagged arrays cannot be cast to IList<>

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6647]
## Steps to Reproduce

```csharp
using System;
using System.Collections.Generic;
using System.Linq;

interface IInterface {
}

class A {
}

class B : A {
}

class Program {

	static void Main ()
	{
		object d = new [] { new [] { new B () } };
		var e2 = (IList<A> []) d;
	}
}
```

## Current Behavior

```
System.InvalidCastException: Unable to cast object of type 'B[][]' to type 'System.Collections.Generic.IList`1[A][]'.
```

## Expected Behavior

No exception

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

master/6dd4ff09f6f

**Comment by luhenry** [comment]
Which test was disabled due to this breakage?

**Comment by luhenry** [comment]
I can reproduce with Mono 5.15.0.45 (master/df33c092de3)

**Comment by marek-safar** [comment]
Disabled tests are in mono/corefx@12dd5629148dc826392d9f79256a45e5cd005593
