### ISSUE TITLE
 System.Diagnostics.Process.GetProcesses () doesn't show FileName and Arguments from a Process.StartInfo

### ISSUE THREAD

**Issue by netonjm** [mono/mono#6663]
## Steps to Reproduce

1. Open a Console Application
2. Call System.Diagnostics.Process.GetProcesses ();
3. Check FileName and Arguments from any Process.StartInfo

## Current Behavior

the string is empty

## Expected Behavior

the string must show the executable and arguments, same like ps does.

### On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.8.0.103 (2017-10/1359c52fc6e Wed Dec 20 10:52:54 EST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

**Comment by marek-safar** [comment]
That's what .net does, `System.Diagnostics.Process.GetProcesses().Where (l => l.StartInfo.FileName.Length > 0);` gives me nothing on windows
