### ISSUE TITLE
Invalid cast is not checked for nullable types

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6666]
## Steps to Reproduce

```c#
using System;

class Program {
	static void Main (string [] args)
	{
		DayOfWeek enumValue = DayOfWeek.Monday;
		object value = (int)enumValue;
		var res = (DayOfWeek?)value; // Should throw
		return;
	}
}
```

## Current Behavior

No exception

## Expected Behavior

System.InvalidCastException

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by kumpera** [comment]
https://github.com/mono/mono/pull/6958/commits
