### ISSUE TITLE
Running PHP in sub-folder of MONO causes 100% CPU

### ISSUE THREAD

**Issue by mysteryx93** [mono/mono#6716]
This 100% CPU issue has been lingering for a very long time now. I'm getting close to identifying the problem. At first I had MONO taking 100% CPU on a Ubuntu server. I re-installed a fresh new server on Debian and had the same problem. Tried many different versions of MONO; problem somehow went away in v5.0 and came back in a later version.

I created a server clone and disabled all websites but one. The issue ONLY happens if the website is configured for MONO and has a sub-folder configured for PHP!

To reproduce the problem

Running Debian 8, MONO 5.4.1.7 (latest, tried many versions)

Running a single website under apache with this config

    <VirtualHost *:80>
      ServerName www.spiritualselftransformation.com
      ServerAlias spiritualselftransformation.com
      DocumentRoot /var/www/spiritualselftransformation
    
      Redirect permanent / https://www.spiritualselftransformation.com/
    </VirtualHost>
    
    <VirtualHost *:443>
      ServerName spiritualselftransformation.com
      ServerAlias www.spiritualselftransformation.com
      DocumentRoot /var/www/spiritualselftransformation
      DirectoryIndex default.aspx index.aspx index.php index.html
    
      <IfModule mod_mono.c>
        MonoServerPath spiritualselftransformation.com "/usr/bin/mod-mono-server4"
        MonoApplications spiritualselftransformation.com "/:/var/www/spiritualselftransformation"
      </IfModule>
    
      <Location "/">
        Allow from all
        Order allow,deny
        <IfModule mod_mono.c>
        MonoSetServerAlias spiritualselftransformation.com
        SetHandler mono
        </IfModule>
        SetOutputFilter DEFLATE
        SetEnvIfNoCase Request_URI "\.(?:gif|jpe?g|png)$" no-gzip dont-vary
      </Location>

      # Problem disappears if you comment this section!
      <Location "/blog">
        SetHandler None
        AddHandler application/x-httpd-php .php
      </Location>
    
      SSLEngine on
      SSLCertificateFile /etc/apache2/SSL-KEYS/www.spiritualselftransformation.com/www_spiritualselftransformation_com.2016-2019.crt
      SSLCertificateKeyFile /etc/apache2/SSL-KEYS/www.spiritualselftransformation.com/privateKey.key
      SSLCertificateChainFile /etc/ssl/certs/comodo.bundle
    </VirtualHost>

Then simply type "sudo service apache2 reload" and "htop". Repeat a few times and the CPU will stick at 100% when sub-folder is configured for PHP. Note that the website code hasn't even run nor compiled yet.

If I comment the PHP sub-folder section, I am unable to reproduce the issue. When reloading apache2, sometimes MONO starts and ends instantly, sometimes it takes 10 second, and sometimes it stays at 100% CPU for up to 2 minutes (??) but it always ends eventually. With the PHP sub-folder section, sooner or later, the CPU will peak at 100% and remain there until the process is killed.

This is definitely a bug in MONO... it's surprising not more people have reported it, and that it remained for so many versions.

Now how can I fix or work-around the issue?

**Comment by lewurm** [comment]
It first reminded me of this bug: https://bugzilla.xamarin.com/show_bug.cgi?id=42606
but you seem to use a version that has already the fix. You should try to get a repro without the apache hull around it, so it's easier to identify the problem.

**Comment by mysteryx93** [comment]
What do you mean without the apache hull, and how would I do that?

As an update, my clone server with only 1 server activated, with the BLOG section commented, has gone into 100% CPU as well. So now I'm with a basic single website on a fresh OS still causing the issue. How come not everybody is getting that problem?

**Comment by mysteryx93** [comment]
After trying all options, it seems MONO just doesn't work well with Apache2 with mod_mono. The only solution I found is to switch Apache2 from prefork to worker mode, where the MONO server needs to be started manually and Apache2 simply forwards the requests to it -- and thus Apache2 doesn't directly touch MONO at all.  So far it's perfectly stable.

**Comment by lewurm** [comment]
Glad you found a workaround. It could be that mono inherits some environment variables in prefork mode that it doesn't like, but it's hard to tell what is going on without an easy repro.

I'm closing this issue, feel free to reopen if you experience a problem.
