### ISSUE TITLE
Reason for the interpreter support explicitly disabled in platforms other than AMD64 / ARM

### ISSUE THREAD

**Issue by stephen422** [mono/mono#6735]
I am currently working on porting the Mono runtime on an RISC-V environment with full glibc and Linux toolchain.
Upon writing some mono/arch code to make the cross-compile succeed, I discovered this code snippet that explicitly disables --interpreter support for all platforms other than AMD64 / ARM / ARM64 (``mono/mini/driver.c``):

```
#if !defined(TARGET_AMD64) && !defined(TARGET_ARM) && !defined(TARGET_ARM64)                                                                                                                                
    g_error ("--interpreter not supported on this architecture.\n");                                                                                                                                        
#endif 
```

Is there a reason the interpreter is explicitly disabled on those other platforms? Is the interpreter runtime not yet completely decoupled from native code generation, so that it needs some of the JIT/AOT functionality? In any case, I think this would make one of the main strength of the interpreter that enables easy porting of the runtime onto devices with no codegen support a bit weak.

**Comment by mderoy** [comment]
I browsed the interpreter code in our fork a while back and noticed a per platform trampoline function between the interpreter and native code that needed to be implemented on each platform the interpreter runs on. I'd speculate thats why these platforms are the only ones that are supported.
see mono_arch_get_interp_to_native_trampoline
https://github.com/mono/mono/blob/master/mono/mini/tramp-amd64.c
function asserts on ppc for example
https://github.com/mono/mono/blob/master/mono/mini/tramp-ppc.c

**Comment by lewurm** [comment]
yeah, @mderoy is right. It's a bit of an unfortunate situation imho. You have to support two kinds of scenarios:
* transition from interpreter to native code: This is done by `mono_arch_get_interp_to_native_trampoline`. For the architectures we support at the moment (amd64, arm, arm64) we use the mono assembler, but could also be handcrafted via inline assembler I guess. This transition is needed for calls into the runtime and pinvoke.
* transition from native code to interpreter: This is a bit different, and will likely change sometime soon. We use so-called "wrappers" which are handcrafted snippets in IL code and then use the JIT to turn them into machine code. Good news for you: You need that kind of transition late in the porting process and, as already mentioned, we wanna change that. In the future it's going to be similar to the other transition in the sense you only need an assembler.

I think it's simpler to get the interpreter up and running than porting the JIT. Feel free to ping me on our [gitter channel](https://gitter.im/mono/mono) if you need any help 🙂

**Comment by stephen422** [comment]
I see. So the code will actually not compile at all with link errors for platforms without ``mono_arch_get_interp_to_native_trampoline`` (eg. MIPS and PowerPC), but the ifdef is there as a temporary safe guard.
Is there any plans to remove the need for the transition to native code in the interpreter runtime though? Even when the runtime needs to call into precompiled assembly libraries, as IL assembly is supposed to be completely platform-indepedent, can't they just be interpreted by the interpreter without having to generate any native instructions?

**Comment by lewurm** [comment]
Actually wo do have something "generic" in place for WebAssembly, here: https://github.com/mono/mono/blob/master/mono/mini/aot-runtime-wasm.c

It's plain C, so it should work on any target. The downside are (1) it only works on a limited set of method signatures (if some is missing, you have to add it and recompile the runtime) and (2) performance isn't that great.

**Comment by stephen422** [comment]
Thanks for the point-out! I'll look into it. I'll leave the issue for you guys to close if needed.
