### ISSUE TITLE
Mono upgrade to 5.8 breaks msbuild on Ubuntu Linux 17.10

### ISSUE THREAD

**Issue by eugeneduvenage** [mono/mono#6756]
## Steps to Reproduce

1. Start with a working mono 5.4.X from the mono ubuntu ppa ("http://download.mono-project.com/repo/ubuntu xenial" )
2. Attempt to upgrade to mono 5.8, or just do a system update

## Current Behavior

```apt-get install mono-complete``` fails with ```mono-complete : Depends: msbuild but it is not going to be installed```.
```apt-get install msbuild``` fails with ```msbuild : Depends: mono-xbuild (>= 1.0) but it is not going to be installed```.
```apt-get install mono-xbuild``` fails with ```mono-xbuild : Breaks: msbuild (< 1:15.4+xamarinxplat.2017.11.27.11.23) but 1:15.4+xamarinxplat.2017.09.14.16.14-0xamarin2+ubuntu1404b1 is to be installed```

The result is that no msbuild will be available on the system after the upgrade,
```Unable to correct problems, you have held broken packages.```

## Expected Behavior

installing mono-complete should work and msbuild should be correctly installed.

### On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

**Version Used**:

Before: 5.4.1.X (think it was .7)
After: 5.8.0.108

**Comment by Sector14** [comment]
Similar issue on debian stretch when upgrading from 5.4.1.7 to 5.8.

For now I've switched back to the 5.4 branch via

`deb http://download.mono-project.com/repo/debian stretch/snapshots/5.4 main`

**Comment by akoeplinger** [comment]
This packaging issue should now be fixed, please try again. Sorry for the inconvenience.

**Comment by davidscherf** [comment]
Happening again on mono 5.12

**Comment by akoeplinger** [comment]
@phagunbaya @davidscherf are you hitting the same issue/error messages as in the original post?

**Comment by akoeplinger** [comment]
Thanks.

@directhex can you please check why the msbuild package upgrade is broken again?

**Comment by directhex** [comment]
Which distribution and architecture, exactly? What do all relevant sources.list(.d) entries look like?

**Comment by directhex** [comment]
(I can't reproduce an issue with a clean Debian 9 system, using stable repositories.)

**Comment by phagunbaya** [comment]
I'm using python:3.6-stretch base docker images and this is my install command
```
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
 	echo "deb http://download.mono-project.com/repo/ubuntu stable-xenial main" | tee /etc/apt/sources.list.d/mono-official-stable.list && \
 	apt-get -y update && \
 	apt-get -y install mono-complete
```

**Comment by akoeplinger** [comment]
@phagunbaya you're trying to use the Ubuntu Xenial package repository on Debian Stretch (the underlying OS of your docker image).

Try using `https://download.mono-project.com/repo/debian stable-stretch main` instead as mentioned on http://www.mono-project.com/download/stable/#download-lin-debian

**Comment by phagunbaya** [comment]
Yeah. This could be the reason. Thanks for the help. Wondering how it worked before.
