### ISSUE TITLE
Failure to AOT System.Data for watchOS

### ISSUE THREAD

**Issue by luhenry** [mono/mono#6766]
The `Interop.NetSecurityNative` DllImports depends on the `System.Net.Security.Native` which is not shipped as part of Mono. This creates multiple problems:
1. When running on platforms which depends on this  `Interop.NetSecurityNative`, it will crash with a "library not found exception" since it won't be able to find `System.Net.Security.Native`.
2. When compiling on platforms which needs direct pinvoke calls, it fails to build with a linking error.

We should get rid of any call to `Interop.NetSecurityNative`.

/cc @EgorBo

**Comment by lewurm** [comment]
I run into this issue as well on iOS/arm64 during the `2018-02` integration:
```
[...]
MTOUCH: error MT5210: Native linking failed, undefined symbol: _NetSecurityNative_DeleteSecContext. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: _NetSecurityNative_InitiateCredWithPassword. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: _NetSecurityNative_InitSecContext. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
[...]
```

from https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/6223/testReport/junit/Xamarin/MTouch/BuildTestProject_Dev_iOS__link_all___Release64__/
