### ISSUE TITLE
[Feature Request] Add support for typedef?

### ISSUE THREAD

**Issue by aaronfranke** [mono/mono#6772]
Currently, in C#, there is no `typedef` like in C++. `typedef` is useful, for example, when creating a game engine with simultaneous support for `float` and `double` (an abstract type, via `typedef`, would be used in place of either type). Or when creating a descriptive short-hand for types without objects.

Would it be possible to add this functionality in the Mono framework? I don't think the C# language spec specifies `typedef` functionality, but I don't think it prevents it either, does it?

If there is a place where I can propose this to the ECMA C# language spec itself, please post a link. Perhaps the Mono project itself could propose it, if you all think it is worth implementing `typedef`.

**Comment by alexrp** [comment]
You probably want to go here: https://github.com/dotnet/csharplang

In general, we don't implement non-standard language features - especially now that we're using Roslyn as the default C# compiler.

**Comment by aaronfranke** [comment]
Thanks for that link. Proposed here: https://github.com/dotnet/csharplang/issues/1300
