### ISSUE TITLE
Regression: Leading zero-value-byte in TCP stream on Windows

### ISSUE THREAD

**Issue by madsjohnsen** [mono/mono#6789]
On Windows I am observing leading zero-value bytes in data when sending it over a TCP stream.

I have spend some time tracking down this issue, and it appears to have been introduced in Mono 5.0.0 as 4.8.1.0 does not produces this error.
And I can reliably reproduce the problem on Mono versions >= 5.

The issue seems to only appears upon sending a certain (undetermined) amount of data over the same stream, but split into small chunks (or buffered).

This is obviously a huge problem in basically all situations, and originally I ran into the problem because of corrupted email attachments (0x00 does not mix with base64).

## Steps to Reproduce

[Issue6789Repro.zip](https://github.com/mono/mono/files/1695892/Issue6789Repro.zip)

1. Execute the Server on any machine. (could be the same as the client)
2. Execute the Client program on a Windows machines (7 or 10 has been tested) and send a sufficiently large file (e.g. https://tools.ietf.org/pdf/rfc4648.pdf)
3. Observe that the server receives multiple zero-bytes in the TCP payload.

## Current Behavior

Looking at the TCP stream produced by the test program, the zero-bytes appear one at a time, as the first byte of the TCP payload but, only for some packages.
These affected packages seems to be packages sent directly after an ACK is received, but not consistently.

This means (or at least it appears) that if instead of the current behavior of the test-program, of sending "blocks", all data is written at once, (line 51) the problem does not appear.

A bit more curiously, it appears that a delay of some form also removes the problem (either form of line 58,59,63,64).

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:
5.8.0

**Comment by joncham** [comment]
I wonder if this is fixed by https://github.com/mono/mono/commit/6c9339dd805b163f69de875439628d0c9cf34645#diff-0ff844e784e15d2542b71c85d2c0133e

**Comment by madsjohnsen** [comment]
@joncham Would that be included in 5.10.0.79? I see the same thing using that version.

**Comment by mikkeljohnsen** [comment]
@joncham This is a VERY serious bug, and makes Mono almost useless on Windows. Will there be a 5.8.1 release soon, and I mean very soon ?

**Comment by lewurm** [comment]
@mikkeljohnsen @madsjohnsen can you try current master? https://xamjenkinsartifact.azureedge.net/build-package-win-mono/master/377/63652bfc2590ee33d85202069a16a9f1e3b6981e/mono-5.13.0.7-x64-0.msi

**Comment by madsjohnsen** [comment]
@lewurm That version does actually fix the issue. (at least for the repro example)

Given that, do you have any idea about where the fix appears in the history? and is there a chance it could be back-ported.

**Comment by lewurm** [comment]
@madsjohnsen good 🙂  can you try the latest package of 5.10 too? https://xamjenkinsartifact.azureedge.net/build-package-win-mono/2017-12/60/71fdb336b826cd4b37984904f7a70e1197b4500c/mono-5.10.0.88-x64-0.msi

I don't know what commit fixed it, I'm assuming the commit that @joncham mentioned above. If the latest 5.10 build fails for your repro, we can try to backport that commit.

**Comment by madsjohnsen** [comment]
@lewurm That package (5.10.0.88) has the issue.

**Comment by lewurm** [comment]
hey @madsjohnsen, can you test https://xamjenkinsartifact.azureedge.net/build-package-win-mono-pullrequest/pr/3/24f13ba7021837245684ce78f2e4c356dc29370c/mono-5.10.0.95-x64-0.msi if it fixes your issue? it's the package built from https://github.com/mono/mono/pull/6814#issuecomment-363606503 (thanks to @akoeplinger ❤️  )

**Comment by madsjohnsen** [comment]
@lewurm Certainly does!

Is there a chance it could be backported to 5.8 ?

**Comment by lewurm** [comment]
Great, thanks for testing! 🙂 

I merged it for 5.10 (our `2017-12` branch), I'm afraid it's already too late for backporting it to 5.8 (`2017-10`). @marek-safar @luhenry @brendanzagaeski is that right?

**Comment by brendanzagaeski** [comment]
Since the change (as [verified](https://github.com/mono/mono/issues/6789#issuecomment-363720820) based on https://github.com/mono/mono/pull/6814) only involves the Windows specific socket code, it won't affect the embedded Mono version in either [xamarin-android](https://github.com/xamarin/xamarin-android) or [xamarin-macios](https://github.com/xamarin/xamarin-macios). So I'll leave it to @marek-safar and @luhenry to highlight any backporting guidelines to follow for a Windows-only change to the `2017-10` branch.

**Comment by lewurm** [comment]
Thanks @brendanzagaeski. I'll close this issue, let's move any further discussion about backporting to its PR https://github.com/mono/mono/pull/6867

**Comment by marek-safar** [comment]
Backported up to 2017-10
