### ISSUE TITLE
Mono crashes when enumerating generic type constraints with modreq through reflection

### ISSUE THREAD

**Issue by OmarTawfik** [mono/mono#6804]
I’m working on a new C# langauge feature, unmanaged generic type constraints: https://github.com/dotnet/csharplang/blob/master/proposals/blittable.md

To prevent older compilers from abusing this constraint, we’re putting a `modreq(System.Runtime.InteropServices.UnmanagedType)` on the type constraint itself.

This can be done by using a CLR TypeSpec that has the modreq followed by the actual type (System.ValueType in this case). Here is an example:

```csharp
public class MyOwnUnmanagedType<T> where T : unmanaged
{
}
```

Becomes:

```csharp
.class public auto ansi beforefieldinit MyOwnUnmanagedType`1<valuetype ([System.Runtime]System.ValueType modreq([System.Runtime.InteropServices]System.Runtime.InteropServices.UnmanagedType) ) T>
    extends [System.Runtime]System.Object
{
}
```
We tested using reflection (`Type.GetTypeInfo().GenericTypeParameters.Single().GetGenericParameterConstraints()`) to enumerate constraints, on the following platforms:

* .Net Desktop: works fine
* .Net Core: works fine
* mono with a .Net Desktop assembly: works fine
* mono with a .Net Core assembly: crashes with the following exception:

```
System.TypeLoadException: Could not resolve type with token 0100000e (from typeref, class/assembly System.Reflection.Assembly, System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 0100000e (from typeref, class/assembly System.Reflection.Assembly, System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
```
Here is the full IL of the assembly for repro:
```
// Metadata version: v4.0.30319
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly repro
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 )
  .custom instance void [mscorlib]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                             63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.

  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [mscorlib]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 07 01 00 00 00 00 )

  .hash algorithm 0x00008004
  .ver 0:0:0:0
}
.module repro.dll
// MVID: {B0514198-7F2C-440F-927F-6486AC8CCF09}
.imagebase 0x10000000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000001    //  ILONLY
// Image base: 0x04A10000


// =============== CLASS MEMBERS DECLARATION ===================

.class public auto ansi beforefieldinit MyOwnUnmanagedType`1<valuetype (class [mscorlib]System.ValueType modreq([mscorlib]System.Runtime.InteropServices.UnmanagedType)) T>
       extends [mscorlib]System.Object
{
  .method public hidebysig specialname rtspecialname
          instance void  .ctor() cil managed
  {
    // Code size       8 (0x8)
    .maxstack  8
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
    IL_0006:  nop
    IL_0007:  ret
  } // end of method MyOwnUnmanagedType`1::.ctor

} // end of class MyOwnUnmanagedType`1
```

**Comment by lambdageek** [comment]
Hi @OmarTawfik , thanks for the bug report.

What do you mean by "mono with a .net core assembly" - are you compilling the IL, above, with the .net core toolchain and then inspecting it from a mono program using reflection?  Could you tell me how to compile the IL to a .net core assembly - I'm not too familiar with the dotnet.

I'm assuming the reflection code is roughly:

```csharp
public class TestProgram {
  public static void Main() {
     var a = Assembly.LoadFrom ("my.dll");
     var t = a.GetType ("MyOwnUnmanagedType`1`");
     var m = t.GetTypeInfo().GenericTypeParameters.Single().GetGenericParameterConstraints();
     Console.WriteLine (m);
  }
}
```

also could you show us the output for your example if you set the `MONO_LOG_LEVEL=debug` and `MONO_LOG_MASK=asm` environment variables.  Something like:
```bash
MONO_LOG_LEVEL=debug MONO_LOG_MASK=asm mono testprogram.exe
```

Thanks!

**Comment by lambdageek** [comment]
Actually I'm really curious what "mono with a .net desktop assembly" is and how it worked.  If I just take the repro IL and do the following (using Mono tools) I get a crash:

```bash
ilasm /dll repro.il
monodis repro.dll
* Assertion at metadata.c:1118, condition `idx >= 0' not met
```

likewise from
```bash
mcs tester.cs
mono tester.exe
* Assertion at metadata.c:1118, condition `idx >= 0' not met
```
where `tester.cs` is my code from [my previous comment](https://github.com/mono/mono/issues/6804#issuecomment-363236082)

So it really looks like we're not prepared to deal with `modreq` in a generic parameter constraint.

**Comment by lambdageek** [comment]
`ikdasm` doesn't like it either:
```
ikdasm repro.dll
...
Unhandled Exception:
System.ArgumentOutOfRangeException: Token 0x02000000 is not valid in the scope of module Dummy.
Parameter name: metadataToken
  at IKVM.Reflection.Reader.ModuleReader.ResolveType (System.Int32 metadataToken, IKVM.Reflection.IGenericContext context) [0x00015] in <c680542e770549afa4b401c6826009fa>:0 
  at IKVM.Reflection.Reader.GenericTypeParameter.GetGenericParameterConstraints () [0x00046] in <c680542e770549afa4b401c6826009fa>:0 
  at Ildasm.Disassembler.WriteGenericParameterDef (Ildasm.LineWriter lw, IKVM.Reflection.Type[] parameters, System.Boolean wrap) [0x000b3] in <c680542e770549afa4b401c6826009fa>:0 
  at Ildasm.Disassembler.WriteType (Ildasm.LineWriter lw, IKVM.Reflection.Type type) [0x0021b] in <c680542e770549afa4b401c6826009fa>:0 
  at Ildasm.Disassembler.WriteTypes (Ildasm.LineWriter lw) [0x00039] in <c680542e770549afa4b401c6826009fa>:0 
  at Ildasm.Disassembler.Save (System.IO.TextWriter writer) [0x00082] in <c680542e770549afa4b401c6826009fa>:0 
  at Ildasm.Program.Main (System.String[] args) [0x003ca] in <c680542e770549afa4b401c6826009fa>:0 
```

**Comment by OmarTawfik** [comment]
@lambdageek there are two steps here:
1. For the reflected assembly, just use `ilasm` on the IL I attached to create your `repro.dll`.
2. Create a dotnet core console app that has the reflection code you mentioned, and compile it with the dotnet toolchain (CLI) into lets say `ConsoleApp.dll`.

If you try to run it using `mono ConsoleApp.dll`, it will throw on the `.GetGenericParameterConstraints()` call (when reflecting `repro.dll`).

This is the log output requested:

```
Mono: Assembly Loader probing location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'.
Mono: Image addref mscorlib[0000021CB523BAA0] -> C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll[0000021CB52654C0]: 2
Mono: Prepared to set up assembly 'mscorlib' (C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll)
Mono: Assembly Loader loaded assembly from location: 'C:\Program Files\Mono\lib\mono\4.5\mscorlib.dll'.
Mono: Assembly mscorlib[0000021CB523BAA0] added to domain ConsoleApp25.dll, ref_count=1
Mono: Assembly Loader probing location: 'C:\Users\otawfik\source\repos\ConsoleApp25\ConsoleApp25\bin\Debug\netcoreapp2.0\ConsoleApp25.dll'.
Mono: Image addref ConsoleApp25[0000021CB52EB250] -> C:\Users\otawfik\source\repos\ConsoleApp25\ConsoleApp25\bin\Debug\netcoreapp2.0\ConsoleApp25.dll[0000021CB52635A0]: 3
Mono: Prepared to set up assembly 'ConsoleApp25' (C:\Users\otawfik\source\repos\ConsoleApp25\ConsoleApp25\bin\Debug\netcoreapp2.0\ConsoleApp25.dll)
Mono: Assembly ConsoleApp25[0000021CB52EB250] added to domain ConsoleApp25.dll, ref_count=1
Mono: Assembly Loader loaded assembly from location: 'C:\Users\otawfik\source\repos\ConsoleApp25\ConsoleApp25\bin\Debug\netcoreapp2.0\ConsoleApp25.dll'.
Mono: Assembly Loader probing location: 'C:\Users\otawfik\source\repos\ConsoleApp25\ConsoleApp25\bin\Debug\netcoreapp2.0\ConsoleApp25.dll'.
Mono: Assembly System.Runtime is a framework Facade asseembly
Mono: Assembly System.Runtime is a framework Facade asseembly
Mono: Assembly Loader probing location: 'C:\Program Files\Mono\lib\mono\gac\System.Runtime\4.2.0.0__b03f5f7f11d50a3a\System.Runtime.dll'.
Mono: Assembly Loader probing location: 'C:\Program Files\Mono\lib\System.Runtime.dll'.
Mono: Assembly Loader probing location: 'C:\Program Files\Mono\lib\mono\4.5\/Facades\System.Runtime.dll'.
Mono: Image addref System.Runtime[0000021CB52EAC20] -> C:\Program Files\Mono\lib\mono\4.5\Facades\System.Runtime.dll[0000021CB5306540]: 2
Mono: Prepared to set up assembly 'System.Runtime' (C:\Program Files\Mono\lib\mono\4.5\Facades\System.Runtime.dll)
Mono: Assembly System.Runtime[0000021CB52EAC20] added to domain ConsoleApp25.dll, ref_count=1
Mono: Assembly Loader loaded assembly from location: 'C:\Program Files\Mono\lib\mono\4.5\/Facades\System.Runtime.dll'.
Mono: Assembly Ref addref ConsoleApp25[0000021CB52EB250] -> System.Runtime[0000021CB52EAC20]: 2
Mono: Found assembly remapping for mscorlib and was for the same version 4.0.0.0
Mono: Found assembly remapping for mscorlib and was for the same version 4.0.0.0
Mono: Assembly Ref addref System.Runtime[0000021CB52EAC20] -> mscorlib[0000021CB523BAA0]: 2

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 0100000e (from typeref, class/assembly System.Reflection.Assembly, System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 0100000e (from typeref, class/assembly System.Reflection.Assembly, System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
```

**Comment by lambdageek** [comment]
So there are several tasks here:

- [ ] Enhance mono metadata loader not to crash if there's a modreq constraint on a generic type parameter.
- [ ] Make `monodis` print it back out.
- [ ] Make IKVM support loading a type with a modreq constraint on a a generic type parameter.
- [ ] Make `System.Type. GetGenericParameterConstraints()` do something sensible with a modreq constraint.  (I need to read the proposal to find out what that sensible thing might be)

**Comment by OmarTawfik** [comment]
@lambdageek .NET runtime so far doesn't do anything with the modreq I'll be placing from the C# compiler. This is mainly for other compilers usage.

**Comment by lambdageek** [comment]
@OmarTawfik well as far as I can tell there is _no_ reflection API proposal at all - if I have ``C`1<valuetype (class [mscorlib]System.ValueType modreq([mscorlib]System.Runtime.InteropServices.UnmanagedType)) T>`` there is **no** reflection function I can call to discover that the modreq is there?  Is that right?  So it will suffice for now just to read and ignore the modifier?

**Comment by OmarTawfik** [comment]
Yes. I believe that the CLR is discarding them as well. @MichalStrehovsky please let me know if I missed something.

**Comment by lambdageek** [comment]
Actually looks like mono's `ilasm` (in `mcs/ilasm`) is miscompiling the repro.il file.  Specifically it generates a GENERICPARAMCONSTRAINT table with an entry like this:
```
Generic Param Constraint (1..1)
1: gen-par=1, Constraint=0
```
Note the `0` constraint.

On the other hand, if I use ilasm.exe from VS 2017 on Windows to compile repro.il to repro.dll, and then run the test program, everything works fine.  The generic param constraint table looks like this:

```
Generic Param Constraint (1..1)
1: gen-par=1, Constraint=6
```
and the typespec table is:
```
Typespec Table
1: class [mscorlib]System.ValueType modreq ([mscorlib]System.Runtime.InteropServices.UnmanagedType) 
```

So looks like mono can read these assemblies just fine. Its ilasm just needs an update.

**Comment by lambdageek** [comment]
`monodis` still needs work, though, because it prints:

```
  .class public auto ansi beforefieldinit MyOwnUnmanagedType`1<valuetype (class [mscorlib]System.ValueType) T>
  	extends [mscorlib]System.Object
```

By contrast, `ikdasm` works fine:
```
.class public auto ansi beforefieldinit MyOwnUnmanagedType`1<valuetype (class [mscorlib]System.ValueType modreq([mscorlib]System.Runtime.InteropServices.UnmanagedType)) T>
       extends [mscorlib]System.Object
{
```

**Comment by MichalStrehovsky** [comment]
Note that this IL is illegal per II.23.2.14 of the ECMA-335 spec. C# compiler team would like to emit invalid metadata and have tools deal with it. We have internal email threads where we're trying to find a solution that doesn't break the ecosystem. Mono is one of few places that don't handle it, but there are many other places and runtimes (.NET Native doesn't cope either)

**Comment by lambdageek** [comment]
@MichalStrehovsky thanks.  For now I'm just trying to catalog all the tasks that would have to be done on the Mono side.

**Comment by lambdageek** [comment]
Looks like Roslyn shipped `class F<T> where T : unmanaged`. (Thanks for the heads up @michaldobrodenka)

TODO:
- [ ] Get my hands on a recent version of Roslyn and build some examples
- [ ] Verify that mono can load and execute the examples sensibly
- [ ] Verify that `monodis` _cannot_ disassemble the examples properly
- [ ] hand write some IL and verify that mono's `ilasm` _cannot_ assemble it properly
- [ ] Find out what the mono verifier thinks about this; fix it if it crashes.
- [ ] Fix `monodis`
- [ ] Fix `ilasm`

**Comment by marek-safar** [comment]
I am closing this as the original issue was fixed and we are tracking the task in a separate ticket
