### ISSUE TITLE
Handle icall linking with interpreter and FullAOT workload

### ISSUE THREAD

**Issue by kumpera** [mono/mono#6808]
Problem:

Under FullAOT, the runtime is usually compiled using `--disable-icall-tables` and FullAOT codegen emits direct calls to icalls. This allows the native linker to eliminate unused icalls and thus producing a smaller binary.

This workflow breaks when we try to use the interpreter from FullAOT workloads. The interpreter needs the icall table to be able to locate which functions to call plus learn their signatures. This is not possible if we disable their generation.

Proposed solution:

Move icall table to a different module and include it in the interpreter static module when the runtime is built with --disable-icall-tables. We'll need some additional wiring to have in installed, but that's all.

**Comment by lewurm** [comment]
The additional wiring can be done by the embedded, e.g. in the Xamarin.iOS case it should be done by `mtouch`.

**Comment by lewurm** [comment]
https://github.com/mono/mono/pull/6905
