### ISSUE TITLE
MonoProfilerCoverageData::column is equal 0

### ISSUE THREAD

**Issue by evgn** [mono/mono#6812]
I'm trying to use mono_profiler_get_coverage_data(). And I want to get information about source code as well. Mono profiling API provides MonoProfilerCoverageData structure with source file path, code line and column. But column value is always equal 0 (or 1 in some cases). It seems that this value must contain a valid column of begin or end of the statement in source code. Or I'm not right?

**Comment by alexrp** [comment]
@vargaz any idea why this is happening?

**Comment by evgn** [comment]
The same situation with old profiling API: MonoProfileCoverageEntry::col is always equal 0. Is there any way to make this value usable?

**Comment by alexrp** [comment]
Since the profiler API just gets this information from the debug info, that's probably where the issue lies.

**Comment by vargaz** [comment]
The above PR will fix it, but only when using .pdb debug info (roslyn/csc).
