### ISSUE TITLE
Libgnome not installed with Mono

### ISSUE THREAD

**Issue by gt3mike** [mono/mono#6816]
## Steps to Reproduce

1. Install Mono on Mac OS High Sierra 10.13.3
2. Attempt to run GTK-Sharp app that uses libgnome.so
3. Get error "libglade-WARNING **: Could not load support for `gnome': dlopen(libgnome.so, 9): image not found"
4. File system search for "libgnome.so" finds no matches 

## Current Behavior

The Mono install doesn't seem to have installed Gnome libraries. The GTK# sample runs properly, but apparently it doesn't use libgnome.so.

## Expected Behavior

GTK# app should find libgnome.so and run without 

### On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.8.0.108 (2017-10/9aa78573ee2 Wed Jan 10 04:30:03 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

### Stacktrace

```
$ mono alarmdecodergui.exe
Checking Gtk#
Gtk# is good.
MyLCD init
Application Exception ige_mac_menu_set_global_key_handler_enabled ]

(alarmdecodergui:8347): libglade-WARNING **: Could not load support for `gnome': dlopen(libgnome.so, 9): image not found
[ERROR] FATAL UNHANDLED EXCEPTION: System.EntryPointNotFoundException: ige_mac_menu_set_global_key_handler_enabled
  at (wrapper managed-to-native) IgeMacIntegration.IgeMacMenu.ige_mac_menu_set_global_key_handler_enabled(bool)
  at IgeMacIntegration.IgeMacMenu.set_GlobalKeyHandlerEnabled (System.Boolean value) [0x00000] in <819aec55fcc84f71b5731cc780673066>:0 
  at ad2usbgui.MainWindow..ctor () [0x00073] in <819aec55fcc84f71b5731cc780673066>:0 
  at ad2usbgui.MainClass.Main (System.String[] args) [0x0002e] in <819aec55fcc84f71b5731cc780673066>:0 
```

**Comment by akoeplinger** [comment]
@Therzok should we add libgnome to bockbuild?

**Comment by migueldeicaza** [comment]
This is out of scope.

We do not distribute Gnome, we only distribute the Gtk# stack.

It would be unproductive for us to ship Gnome, as modern Gnome is Gtk# 3 based, and we merely ship Gtk# for the sake of keeping existing apps that were built running and for MonoDevelop/Visual Studio for Mac purposes.

Users that want Gnome, should collaborate with someone like Brew or the Gnome community to have those SDKs distributed.
