### ISSUE TITLE
Can't install mono-debugger

### ISSUE THREAD

**Issue by spphinslove** [mono/mono#6828]
## Steps to Reproduce

1. git clone and ./autogen.sh

2. configure: error: Can't find "mcs" in your PATH   //but mcs in /usr/bin

3. $ which mcs 
4. $ /usr/bin/mcs

$ uname -a
$ Linux linux 4.15.0-1-MANJARO #1 SMP PREEMPT Mon Jan 29 06:13:26 UTC 2018 x86_64 GNU/Linux

mono version:

Mono JIT compiler version 5.4.1 (makepkg/e66d9abbb27 Thu Nov  9 22:28:33 CET 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

**Comment by lewurm** [comment]
I don't think `mcs` is required in your `$PATH` to build mono. Can you post the full output of `./autogen.sh`?

**Comment by spphinslove** [comment]
@lewurm 
**Warning**: I am going to run `configure' with no arguments.
If you wish to pass any to it, please specify them on the
`./autogen.sh' command line.

Running libtoolize...
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.in,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
Running aclocal  ...
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
Running autoheader...
Running automake --gnu  ...
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:5: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:5: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:9: installing './compile'
configure.in:5: installing './missing'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
build/Makefile.am: installing './depcomp'
sysdeps/bfd/Makefile.am:47: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
sysdeps/bfd/libiberty/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
sysdeps/bfd/opcodes/Makefile.am:16: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
test/misc/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
test/src/Makefile.am:37: warning: '%'-style pattern rules are a GNU make extension
test/src/Makefile.am:40: warning: '%'-style pattern rules are a GNU make extension
test/src/Makefile.am:5: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
Running autoconf ...
Running ./configure --enable-maintainer-mode --enable-build-warnings ...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gcc... gcc
checking for gcc... (cached) gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
Setting warning flags = -W -Wall -Wstrict-prototypes -Wmissing-prototypes
checking host platform characteristics... ok
checking for ar... ar
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... (cached) ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking size of void *... 8
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib-2.0 >= 2.0.0... yes
checking Whether we're using Mono from trunk... yes
checking for glib-2.0 >= 2.0.0 ... yes
"Found cecil.pc"
checking for mono-2 >= 2.0 glib-2.0 >= 2.0.0... yes
checking for gacutil... /usr/bin/gacutil
checking for mono... /usr/bin/mono
checking for gmcs... no
checking for monodis... /usr/bin/monodis
configure: error: Can't find "mcs" in your PATH

**Comment by akoeplinger** [comment]
It looks like this is trying to build https://github.com/mono/debugger which does check for "mcs" in its [configure.in](https://github.com/mono/debugger/blob/626f825e1ecb856cfb7ea8c341dd9cfdfa18d889/configure.in#L193) but actually checks for `gmcs` which we no longer provide.

As far as I know the hard debugger is no longer supported, right?

**Comment by luhenry** [comment]
The hard debugger was never really supported and never actually worked. We have the soft debugger which works and is supported. What is it you are trying to do?

**Comment by akoeplinger** [comment]
Closing the issue but please feel free to post any questions you have.
