### ISSUE TITLE
mono --gc-params=minor=simple-par fails to start on Linux machine with 16 logical CPUs due to hardcoded limit

### ISSUE THREAD

**Issue by anttirt** [mono/mono#6831]
## Steps to Reproduce

1. Get mono 5.8.0.108 on a 16-logical-core Linux machine (e.g. Ryzen 1800x)
```
$ grep -c ^processor /proc/cpuinfo 
16
```
2. 
```bash
$ echo 'using System; class Program { public static void Main(string[] args) { Console.WriteLine("Hello, world!"); } }' > HelloWorld.cs
$ csc HelloWorld.cs
Microsoft (R) Visual C# Compiler version 2.3.2.61928 (ec1cde8b)
Copyright (C) Microsoft Corporation. All rights reserved.

$ mono --gc-params=minor=simple-par HelloWorld.exe 2>&1 | head -3
```

## Current Behavior

```
Maximum sgen thread pool threads exceeded
/proc/self/maps:
00400000-007bd000 r-xp 00000000 08:11 19661323                           /usr/bin/mono-sgen
```

## Expected Behavior

```
Hello, world!
```

### On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

5.8.0.108

### Additional info

The max number of threads is hardcoded at https://github.com/mono/mono/blob/master/mono/sgen/sgen-thread-pool.h#L16 to be 8, but it looks like `minor=simple-par` tries to use the number of available logical CPUs: https://github.com/mono/mono/blob/master/mono/sgen/sgen-simple-nursery.c#L173.

I don't know if it's safe to just increase the limit to the expected number of logical cores (which may be more than 16 on server hardware) or if there is a deeper reason for the limit of 8 and the number should be capped to 8.

This also breaks `mode=throughput` and `mode=pause:x` because both automatically enable `minor=simple-par`.

**Comment by lewurm** [comment]
as far as I know, `simple-par` is still experimental. /cc @BrzVlad

**Comment by anttirt** [comment]
http://www.mono-project.com/docs/about-mono/releases/5.8.0/ documents `mode` for which two out of three options will internally select `minor=simple-par`.

**Comment by marek-safar** [comment]
@BrzVlad are you working on this issue?

**Comment by BrzVlad** [comment]
I'll take a look this week

**Comment by BrzVlad** [comment]
https://github.com/mono/mono/pull/7180

**Comment by akoeplinger** [comment]
@BrzVlad can we close this now that the above PR was merged or is there still work to do?
