### ISSUE TITLE
netstandard facade dlls have different public key tokens

### ISSUE THREAD

**Issue by mrvoorhe** [mono/mono#6848]
## Steps to Reproduce

1.  Open `lib\mono\4.5\Facades\netstandard.dll` in ILSpy and note

// netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

2.  Open `lib\mono\4.7.1-api\Facades\netstandard.dll` in ILSpy and note 

// netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Because the PublicKeyTokens are different, compiling an assembly against the netstandard from 4.7.1-api and mixing it with an assembly compiled against the netstandard from 4.5 with result in errors such as

 
error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

## Expected Behavior

The PublicKeyToken should match

### On which platforms did you notice this

All

**Version Used**:

master

**Comment by marek-safar** [comment]
@akoeplinger this looks bad, could you check this

**Comment by akoeplinger** [comment]
Indeed this is wrong. There are the following public key mismatches:

- Facades/netstandard.dll: ~b03f5f7f11d50a3a~ cc7b13ffcd2ddd51
- Facades/System.ValueTuple.dll: ~b03f5f7f11d50a3a~ cc7b13ffcd2ddd51
- Facades/System.IO.Compression.ZipFile.dll: ~b03f5f7f11d50a3a~ b77a5c561934e089

Those are all new in v4.7.1. I have a script I use to verify the assembly identity matches when I update reference-assemblies but I must've missed running it against the Facades this time. Will fix.
