### ISSUE TITLE
Update gtksharp dependency 

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6879]
We need to bump the gtk dependency to bring a fix via https://github.com/mono/gtk-sharp/pull/218/files

Original tracking bug is at https://bugzilla.xamarin.com/show_bug.cgi?id=61202

**Comment by Aguilex** [comment]
@spouliot @jonpryor @AdrianMurphy FYI... at this time, for 15.6, I don't think we need to bump the SDKs once this mono fix lands in 2017-10

**Comment by akoeplinger** [comment]
Bockbuild was bumped, build is in progress here: https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=5533&host_id=440&revision_id=928286

**Comment by spouliot** [comment]
@Aguilex right, we don't ship the gtk bits.

**Comment by marek-safar** [comment]
Fixed by https://github.com/mono/mono/commit/33652b57ebbaa9a26ba5d67b602536061e9e898e
