### ISSUE TITLE
 Console.OutputEncoding = Encoding.UTF8

### ISSUE THREAD

**Issue by s2quake** [mono/mono#6901]
## Steps to Reproduce

1. Console.OutputEncoding = System.Text.Encoding.UTF8;            
    Console.WriteLine("123");
2. build and run : mono ConsoleApp1.exe > text.json
text.json encoding is UTF-8 with BOM
I think text.json encoding must be UTF-8
but if it runs using default encoding(without encoding setting), text.json is UTF-8

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

**Comment by akoeplinger** [comment]
This is working as expected, `System.Text.Encoding.UTF8` is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.utf8?view=netframework-4.7.1#Remarks) as having a BOM.

The default Console.OutputEncoding on the contrary uses UTF8 without BOM.
