### ISSUE TITLE
Build the interpreter as a separate library

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6918]
We want the customers to be able to opt-in for interpreter without paying the price in terms of size all the time

We will need systems that are not part of the fullAOT build but are needed by the Interpreter to run:
 - [x] icall table - https://github.com/mono/mono/pull/6905 + https://github.com/mono/mono/pull/7141
 - [x] marshaling - https://github.com/mono/mono/pull/7375

**Comment by lewurm** [comment]
Partially done. If mono is configured with `--enable-minimal=interpreter`, the build will still produce a interpreter library that isn't linked into `libmonosgen`, but can be linked into the application by the embedder. However, the interpreter pulls some other things into the runtime, that aren't usually available in a FullAOT configured runtime: 

* make icall tables available as shared library: https://github.com/mono/mono/pull/6905
* include wrapper generation code always in the runtime: https://github.com/mono/mono/pull/6688. An arguable better solution would be to do something similar as in the icall PR.

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/6667

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/7141
