### ISSUE TITLE
Some PNGCodecTest fail on CI

### ISSUE THREAD

**Issue by alexischr** [mono/mono#6919]
Disabled by both https://github.com/mono/mono/commit/dcda4c77bc910bc3ece378007a3c79a14294b15d and https://github.com/mono/mono/pull/6909

Example: https://jenkins.mono-project.com/job/test-mono-pull-request-armel/10435/testReport/junit/(root)/PngCodecTest/Bitmap2bitData/

**Comment by akoeplinger** [comment]
Already filed as https://github.com/mono/mono/issues/6908, closing this :)
