### ISSUE TITLE
Mono runtime doesn't check modreqs for overriding methods

### ISSUE THREAD

**Issue by OmarTawfik** [mono/mono#6936]
If a virtual method has a `modreq` on one of the parameters, but a child type overrides this method without having the `modreq`, the CLR considers them two different signatures, and they don't override each other, which leads to the following behavior:

Signature of the virtual `Parent.M(in int)`:
```
.method public hidebysig newslot virtual instance string M ([in] int32& modreq([mscorlib]System.Runtime.InteropServices.InAttribute) x) cil managed
```
Signature of the overriding `Child.M(in int)`:
```
.method public hidebysig virtual instance string M ([in] int32& x) cil managed
```
User code:
```csharp
namespace clrbug
{
    class Program
    {
        static void Main(string[] args)
        {
            Test(new Parent());
            Test(new Child());
        }
        static void Test(Parent obj)
        {
            Console.WriteLine(obj.M(0));
        }
    }
}
```
On CoreCLR:
```
dotnet clrbug.dll
Parent
Parent
```
On Mono:
```
mono clrbug.dll
Parent
Child
```
Here are the two binaries, the one that has that IL, and the console application: [monobug.zip](https://github.com/mono/mono/files/1712962/monobug.zip)

**Comment by alexanderkyte** [comment]
With https://github.com/mono/mono/pull/7012 I now get 

```mono-sgen clrbug.dll  
Parent
Parent```

**Comment by alexanderkyte** [comment]
@OmarTawfik Since this compares mono against the CLR as an "expected value" I wanted to notify you here that mono's going to deviate from CLR behavior. The CLR completely ignores modifiers when using SRE in a non-Save+Assembly.LoadFrom workflow. Our SRE will respect assigned modifiers.

**Comment by OmarTawfik** [comment]
@marek-safar can you please mention the version for which the fix will be shipped in?

**Comment by marek-safar** [comment]
@OmarTawfik it'll be available in the future Mono 5.16 release

**Comment by lambdageek** [comment]
#11134 broke this again.

**Comment by lambdageek** [comment]
This works again on mono master after c0b4879
