### ISSUE TITLE
[XI]WatchOS apps fail to  build with error "Undefined symbols for architecture armv7k" using XI with mono-2017-12 support

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#6948]
_From @GouriKumari on February 6, 2018 20:47_

### Steps to Reproduce

1. Open or create a new watchOS sample
2. Build it with Release|iPhone config

### Expected Behavior
App should build successfully

### Actual Behavior
App fails to build with error: https://gist.github.com/GouriKumari/66f9a07284774f479ebea69877922ac6 .
This issue occurs only with Release|iPhone config.

### Environment

Test Env: https://gist.github.com/GouriKumari/af3f4d4338773d389c4091230574f4f8

### Build Logs
Sample: http://xqa.blob.core.windows.net/gist/report-929e3b199cb1436cafe0172abb4f6e76.txt
Sample: http://xqa.blob.core.windows.net/gist/report-54386a93871c4158bd7954bd60c731c9.txt
Template: https://gist.github.com/GouriKumari/f85e3aaf7d56e32b9d4701a341576700

## Example Project: https://github.com/olegoid/SubmissionSamples/tree/master/WatchOS

_Copied from original issue: xamarin/xamarin-macios#3406_

**Comment by spouliot** [comment]
switched target so we (macios) can track this issue
/cc @vargaz
