### ISSUE TITLE
mkbundle regression

### ISSUE THREAD

**Issue by migueldeicaza** [mono/mono#6980]
## Steps to Reproduce

This was a regression introduced in ca8b8bd346a66b5a5a7bd1b5410421588f5af599:

## Current Behavior

```
mac$ git reset --hard ca8b8bd346a66b5a5a7bd1b5410421588f5af599
mac$ make; make install
mac$ /mono/bin/mkbundle --simple a.exe
Failure to load i18n assemblies, the following directories were searched for the assemblies:
   Path: .
ERROR: Couldn't load one or more of the i18n assemblies: Failed to load I18N.dll
```

## Expected Behavior

```
mac$ git reset --hard d49e8c32c4a0460009c6ffe0ab9eb362af8c8670
mac$ make; make install
mac$ /mono/bin/mkbundle --simple a.exe
Using runtime: /mono/bin/mono
     Assembly: /private/tmp/a.exe
     Assembly: /mono/lib/mono/4.5/mscorlib.dll
     Assembly: /mono/lib/mono/4.5/I18N.West.dll
     Assembly: /mono/lib/mono/4.5/I18N.dll
Generated a.out
```

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Master, but generally, ca8b8bd346a66b5a5a7bd1b5410421588f5af599 introduced the regression.

**Comment by marek-safar** [comment]
@alexanderkyte could you investigate the regression

**Comment by alexanderkyte** [comment]
Looks like a duplicate of https://github.com/mono/mono/pull/6687

**Comment by migueldeicaza** [comment]
It is a different manifestation of the other issue, and with the merge of the other fix, this bug is now gone.
