### ISSUE TITLE
Make float32 the default setting

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6985]
We think float32 got enough exposure and it’s a better default due to being faster and being more compatible with .NET

It also makes sense to do so as iOS already defaults to it while Android doesn’t.

The x86 port is needed for both since ios and android use it for simulators, and Android uses it for devices as well.

### Requires
- [ ] Figure out the breakages with corefx test suite.
- [ ] Introduce float64 to enable the current behavior.

**Comment by migueldeicaza** [comment]
Given that the simulators are not supposed to be exact replicas of the hardware, I do not think that we need to complete x86 support for us to proceed with this change.

**Comment by vargaz** [comment]
Fixed in master.
