### ISSUE TITLE
Hitting g_assert_not_reached (unknown opcode storei8_membase_reg) in mini-arm.c:5924 on AOT+Linux

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#6989]
This is being observed in the [xamarin-android-linux](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/) Jenkins job, for multiple unit test failures, e.g. [Xamarin.Android.Build.Tests.BuildTest.CheckSequencePointGeneration(True,True,True,True,"PdbOnly",False,"release") / Debug](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/783/testReport/Xamarin.Android.Build.Tests.BuildTest/CheckSequencePointGeneration/Xamarin_Android_Build_Tests_BuildTest_CheckSequencePointGeneration_True_True_True_True__PdbOnly__False__release_____Debug/):

```
[AOT] MONO_PATH="/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/android/assets" MONO_ENV_OPTIONS="" /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Linux/cross-arm --aot=msym-dir=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/aot/armeabi-v7a,outfile=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/aot/armeabi-v7a/libaot-UnnamedProject.dll.so,asmwriter,mtriple=armv7-linux-gnueabi,tool-prefix=/home/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-,ld-flags=,llvm-path=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Linux,temp-path=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/aot/armeabi-v7a/UnnamedProject.dll /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/android/assets/UnnamedProject.dll
[aot-compiler stdout] Mono Ahead of Time compiler - compiling assembly /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/android/assets/shrunk/System.dll
[aot-compiler stdout] AOTID 1C512E38-4EF8-E26C-2771-39AE345EA87F
[aot-compiler stdout] unknown opcode storei8_membase_reg in mono_arch_output_basic_block()
[aot-compiler stdout] 
[aot-compiler stdout] * Assertion: should not be reached at /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/external/mono/mono/mini/mini-arm.c:5924
```

This is currently against the mono/2017-10 branch: https://github.com/mono/mono/blob/1eac626536b401a5eb5352db1af8c35b4b825996/mono/mini/mini-arm.c#L5924

### On which platforms did you notice this

 [ ] macOS
 [X] Linux
 [ ] Windows

**Version Used**:

mono/2017-10

**Comment by marek-safar** [comment]
Do you know if it happens with 2017-10 only and not with 2017-12 ?

/cc @luhenry

**Comment by jonpryor** [comment]
> Do you know if it happens with 2017-10 only and not with 2017-12 ?

We'll find out in roughly 8 hours. :-)

**Comment by jonpryor** [comment]
@marek-safar, @luhenry:

> Do you know if it happens with 2017-10 only and not with 2017-12 ?

It appears to happen on 2017-12 as well. This build is post mono/2017-12 merge: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/793/

The [Xamarin.Android.Build.Tests.BuildTest.CheckSequencePointGeneration.Xamarin.Android.Build.Tests.BuildTest.CheckSequencePointGeneration(True,True,True,True,"PdbOnly",False,"release") / Debug](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/793/testReport/junit/Xamarin.Android.Build.Tests.BuildTest/CheckSequencePointGeneration/Xamarin_Android_Build_Tests_BuildTest_CheckSequencePointGeneration_True_True_True_True__PdbOnly__False__release_____Debug/) test still contains an assert failure:

```
[aot-compiler stdout] unknown opcode storei8_membase_reg in mono_arch_output_basic_block()
[aot-compiler stdout] * Assertion: should not be reached at /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/external/mono/mono/mini/mini-arm.c:5924
```

Related: https://github.com/mono/mono/blob/b232a3929b0487cd00ee0828cf5928dcea712448/mono/mini/mini-arm.c#L5923-L5924

**Comment by jonpryor** [comment]
Note that the invoking command is:

```
MONO_PATH="/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/android/assets" MONO_ENV_OPTIONS="" /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Linux/cross-arm --aot=msym-dir=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/aot/armeabi-v7a,outfile=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/aot/armeabi-v7a/libaot-UnnamedProject.dll.so,asmwriter,mtriple=armv7-linux-gnueabi,tool-prefix=/home/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-,ld-flags=,llvm-path=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Linux,temp-path=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/aot/armeabi-v7a/UnnamedProject.dll /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/android/assets/UnnamedProject.dll
```

I see `armeabi-v7a` in the paths, and thus I assume it's emitting **target-arm32** output for this particular test.

**Comment by marek-safar** [comment]
@luhenry could @lewurm help to track this down?

**Comment by vargaz** [comment]
Could you upload the obj/Release directory ?

**Comment by lewurm** [comment]
wild guess: There is something off about how XA builds cross-compilers on Linux. Reminder: A cross-compiler for a 32-bit target needs to be configured itself as 32bit (i.e. for armv7 target, the cross-compiler must be compiled so that it runs on x86, _NOT_ amd64).

Relevant code: https://github.com/xamarin/xamarin-android/blob/f7b24f7cc39cff6b1086049b3aade1a73a87a0b5/build-tools/mono-runtimes/mono-runtimes.props#L93-L100
Not sure if I understand it correctly, but it looks like to me there is only _one_ cross compiler in the XA build, and depending on the bitness of the host, it's either 32bit or 64bit.

@jonpryor can you shed some light onto how runtimes are built in `xamarin-android`?

/cc @grendello

**Comment by vargaz** [comment]
I can look at it if somebody uploads the obj/Release directory.

**Comment by luhenry** [comment]
@lewurm there are 4 cross compilers created for XA: `cross-x86`, `cross-x86_64`, `cross-arm` and `cross-arm64`. They are respecting the limitation that only 32bits cross-compilers can generate for 32bits targets, and they are passed the `--build` parameter properly https://github.com/xamarin/xamarin-android/blob/f7b24f7cc39cff6b1086049b3aade1a73a87a0b5/build-tools/mono-runtimes/mono-runtimes.props#L103-L104

**Comment by luhenry** [comment]
@lewurm there are 4 cross compilers created for XA: `cross-x86`, `cross-x86_64`, `cross-arm` and `cross-arm64`. They are respecting the limitation that only 32bits cross-compilers can generate for 32bits targets, and they are passed the `--build` parameter properly https://github.com/xamarin/xamarin-android/blob/f7b24f7cc39cff6b1086049b3aade1a73a87a0b5/build-tools/mono-runtimes/mono-runtimes.props#L103-L104 and https://github.com/xamarin/xamarin-android/blob/f7b24f7cc39cff6b1086049b3aade1a73a87a0b5/build-tools/mono-runtimes/mono-runtimes.projitems#L313-L407

**Comment by lewurm** [comment]
@luhenry thanks for the explanation, that looks indeed good. Do you know where `_CrossConfigureBuildHost32`/`_CrossConfigureBuildHost64` is set for Linux?

**Comment by luhenry** [comment]
@lewurm that's a good question, looks like it's not. @jonpryor ?

**Comment by jonpryor** [comment]
@luhenry, @lewurm: It's not set for Linux. Looks like an oversight in the build process.

That said, *how did this ever build* if `$(_CrossConfigureBuildHost32)` and `$(_CrossConfigureBuildHost64)` aren't set? It looks to me like we'd be invoking `configure --build="" ...`; shouldn't that flag an error?

**Comment by luhenry** [comment]
@jonpryor I think the automake magic comes into play and just set the build value to default which is the current host (most likely 64bits).

**Comment by vargaz** [comment]
We have an assert in the runtime so 64 bit and 32 bit is not mixed, so the problem is probably somewhere else. Can somebody upload the obj/Release directory from the failing build ?

**Comment by jonpryor** [comment]
@vargaz: here is the build tree for a failing [`BuildAotApplication_armeabi_True_True.zip`](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/ws/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi_True_True/) test, which has the same assertion message.

[BuildAotApplication_armeabi_True_True.zip](https://github.com/mono/mono/files/1752994/BuildAotApplication_armeabi_True_True.zip)

**Comment by jonpryor** [comment]
@vargaz: here is the build tree for the failing [`CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease`](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/ws/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/) test.

[CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease.zip](https://github.com/mono/mono/files/1753006/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease.zip)

**Comment by vargaz** [comment]
I can reproduce it on linux but not on osx. The cross-arm executable at least looks like a normal 32 bit process, so the problem is either in the build of the cross compiler, or some linux specific problem, since the cross compilers were never built or tested on linux.
Unfortunately, there are no build logs, since the android-linux build uses cached mono binaries.

**Comment by jaykrell** [comment]
As much as I like autoconf's ability to detect its surroundings, maybe we should hardcode more? Or are we misusing autoconf? Just need to be crisper about build vs. host?

**Comment by jonpryor** [comment]
> Unfortunately, there are no build logs, since the android-linux build uses cached mono binaries

That's not entirely true. You "just" need to find the build which built the cached mono binaries, as that build will also contain the build logs for the cached mono binaries.

A "just so crazy it might work" way to do *that* is to hit the [**Build Time Trend**](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/buildTimeTrend) link and find a non-failing build which took about 6 hours (or more) to finish (without timing out).

For example, https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/796/

**Comment by vargaz** [comment]
It does look like the 32 bit cross compiler is compiled as a 64 bit exe:

<span class="timestamp"><b>03:14:34</b> </span>						Executing:  /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/external/mono/configure LDFLAGS="" CFLAGS="-DDEBUG_CROSS -DXAMARIN_PRODUCT_VERSION=0" CXXFLAGS="-DDEBUG_CROSS -DXAMARIN_PRODUCT_VERSION=0" CC="gcc -m32" CXX="g++ -m32" CPP="" CXXCPP="cpp" LD="ld" AR="ar" AS="as" RANLIB="ranlib" STRIP="strip" DLLTOOL="" OBJDUMP="" --cache-file=../cross-arm.config.cache --target=armv5-linux-androideabi --cache-file=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/build-tools/mono-runtimes/obj/Debug/cross-arm.config.cache --with-cross-offsets=armv5-none-linux-androideabi.h --build= --disable-boehm --enable-mcs-build=no --enable-nls=no --enable-maintainer-mode --enable-extension-module --with-tls=pthread --with-llvm=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/build-tools/mono-runtimes/obj/Debug//llvm/installed-32/usr
<span class="timestamp"><b>03:14:34</b> </span>						Environment variables being passed to the tool:
<span class="timestamp"><b>03:14:34</b> </span>						configure: creating cache /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/build-tools/mono-runtimes/obj/Debug/cross-arm.config.cache
<span class="timestamp"><b>03:14:34</b> </span>						checking build system type... x86_64-pc-linux-gnu
<span class="timestamp"><b>03:14:34</b> </span>						checking host system type... x86_64-pc-linux-gnu
<span class="timestamp"><b>03:14:34</b> </span>						checking target system type... armv5-unknown-linux-androideabi

**Comment by vargaz** [comment]
Note the empty --build= argument to configure.
