### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform always thinks it is running on Windows if a .NET Standard library is referenced from a .NET 4.7 project

### ISSUE THREAD

**Issue by surban** [mono/mono#7011]
## Steps to Reproduce

1. Create an empty .NET Standard 2.0 library.
2. Create a .NET 4.7 console app.
3. Reference the library from the app.
4. Call `System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform` from the console app.

See attached solution [OsDetTest.zip](https://github.com/mono/mono/files/1721847/OsDetTest.zip) for an example.

## Current Behavior

`RuntimeInformation.IsOSPlatform(OSPlatform.Windows)` returns `true` on MacOS and Linux.
`RuntimeInformation.IsOSPlatform(OSPlatform.OSX)` and `RuntimeInformation.IsOSPlatform(OSPlatform.Linux)` return `false` on all platforms.

## Expected Behavior

`RuntimeInformation.IsOSPlatform` behaves according to the OS platform.

### On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 18:15:21 UTC 2018)

**Comment by marek-safar** [comment]
You are running .NET/Windows specific version we had to hack around this and #6926 resolved this
