### ISSUE TITLE
VSfM update checks are broken after updating to 2018-02

### ISSUE THREAD

**Issue by kg** [mono/mono#7015]
## Steps to Reproduce

1. Install Mono 2018-02 build on OS X
2. Start VSfM
3. Open the 'check for updates' screen if it did not already open

## Current Behavior

Multiple exception backtraces are dumped to stdout, like this:
https://gist.github.com/kg/f6823d2093c981c7f61aaf7c5eeced3f
And the update checker hangs without ever showing the list of available updates. If you change update channels sometimes the list will then appear.

![image](https://user-images.githubusercontent.com/198130/36180609-04999d9e-10d6-11e8-8bde-97272a1f550d.png)

## Expected Behavior

The update checker should work and there should not be any error messages in the log. This works in 2017-12.

### On which platforms did you notice this

macOS 10.12.6

Version Used:
Mono JIT compiler version 5.12.0.11 (2018-02/f3c1fcd7c92 Thu Feb 8 18:32:17 EST 2018)

### Stacktrace

https://gist.github.com/kg/f6823d2093c981c7f61aaf7c5eeced3f

Typically I see multiple exceptions like this. The response is a 304, which should not be terminating execution or be causing a failure - it's a normal 'content has not changed' response for cacheable requests. The weird message attached to it is an Azure thing and does not seem to indicate a server side failure or bad request.

**Comment by marek-safar** [comment]
@baulig that looks most likely as async web requests refactoring regression

**Comment by kg** [comment]
I should mention that I've managed to get the update check to fail stuck on 'checking for updates' once in 2017-12, but the error is different:

```
INFO [2018-02-14 06:05:06Z]: .NET Core SDK not found.

INFO [2018-02-14 06:05:06Z]: Checking for updates: https://software.xamarin.com/Service/Updates?v=2&m=fe29e1eb-0b54-496b-9257-efb883016963&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=510000091&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=2040100107&pv4569c276-1397-4adb-9485-82a7696df22e=2110500092&pvd1ec039f-f3db-468b-a508-896d7c382999=1505924079&pvc07628e8-5521-4c1a-aa3a-f860e664f0a9=0&os=osx-10.12.6&env=MonoTouchInstalled,MonoDroidInstalled,iphsdk11.2

ERROR [2018-02-14 06:05:06Z]: An unhandled exception has occured. Terminating Visual Studio? False

System.Net.Sockets.SocketException (0x80004005): Success

  at Microsoft.ServiceHub.Utility.SocketClient+<ConnectAsync>d__0.MoveNext () [0x00231] in <77315aa4fd5d49b8add7ad003b8a13a2>:0 

INFO [2018-02-14 06:05:06Z]: Add-in loaded: MonoDevelop.VersionControl.Subversion
```

So it's possible something was already wrong here... however, it doesn't spit out a spew of 304 errors like 2018-02 does, and it doesn't seem to fail every time.

**Comment by baulig** [comment]
Is there an easy way of running just that Update Checker code from the command-line - do they have some kind of automated test for that which I could run?

**Comment by kg** [comment]
Something odd here is that the logic for running monodevelop's automated tests should be disabling the updater:
```Runtime.Preferences.EnableUpdaterForCurrentSession = false;```
https://github.com/mono/monodevelop/blob/9b425b18fe8605fb6c5e998c33075e099283231f/main/tests/TestRunner/Runner.cs#L69

But for some reason I can occasionally see the updater pop up anyway and stall the test run (since the modal is blocking).

**Comment by kg** [comment]
According to @Therzok the monodevelop code is not configuring caching for updater-related requests, so it should be getting the default caching behavior:
https://github.com/mono/monodevelop/blob/8b17d75ff2dc26c5aa1a6246f6a2ce7d4f65e3be/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Web/RequestHelper.cs#L67

The code being used is originally from nuget. It sounds like what should be happening here is that either the request is made with no caching at all, or the 304 results in the application getting the cached content. We seem to be issuing a request with caching headers but then not yielding the cached result to the application?

**Comment by kg** [comment]
https://github.com/mono/mono/pull/7256 Improves the state of things here (no exceptions in the log when the updater runs) but does not fix the update hang.

The best way to manually reproduce this I've found is to launch md (```make run```), then manually open 'check for updates', then quit out. Then, set your date into the future and launch md with make run again. The updater should manually trigger and then hang. I can't figure out where md stores the update data (it's not in my mac's homedir) so you'll have to set the date further forward each time...

**Comment by kg** [comment]
OK, one other way to reproduce this is to blow away any monodevelop/vsfm-related folders in your homedir's Library/Cache folder. This seems to trigger an update check on next launch every time if you launch, quit, set date forward, launch again. The downside is it seems to download an update first and they're quite large...

**Comment by marek-safar** [comment]
Seems to work fine with the recent update
