### ISSUE TITLE
Hybrid AOT is not working for some generic methods

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#7016]
## Steps to Reproduce

1. Open the attached LurchTableTest project
[LurchTableTest.zip](https://github.com/mono/mono/files/1722140/LurchTableTest.zip)
2. Build the Release configuration
3. Run the resulting executable "bin/Release/LurchTableTest.app/Contents/MacOS/LurchTableTest"

## Current Behavior

The application crashes because it couldn't locate an AOTed method and the IL code is stripped.

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in System.Drawing.LurchTable`2<string, LurchTableTest.MainClass/Entry>:InternalInsert<System.Drawing.LurchTable`2/AddInfo<string, LurchTableTest.MainClass/Entry>> (int,string,int&,System.Drawing.LurchTable`2/AddInfo<string, LurchTableTest.MainClass/Entry>&): IL_0000: ret       


  at System.Drawing.LurchTable`2[TKey,TValue].Insert[T] (TKey key, T& value) [0x0002c] in <4bca31772cc24f93bb11f33848657c2b>:0 
  at (wrapper unknown) System.Object.gsharedvt_in()
  at System.Drawing.LurchTable`2[TKey,TValue].set_Item (TKey key, TValue value) [0x0001a] in <4bca31772cc24f93bb11f33848657c2b>:0 
  at LurchTableTest.MainClass.Main (System.String[] args) [0x0002c] in <4bca31772cc24f93bb11f33848657c2b>:0 
```

## Expected Behavior

The program should not crash.

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.8.0.123 (2017-10/38502063cac Thu Feb  1 12:58:29 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

**Comment by vargaz** [comment]
The LurchTable class uses some complicated generics with valuetypes, so we fail back to valuetype based sharing, which still has some restrictions around constrained calls, i.e. this one in
  .method private hidebysig instance valuetype System.Drawing.LurchTable`2/InsertResult<!TKey,!TValue> 
          InternalInsert<(class System.Drawing.ICreateOrUpdateValue`2<!TKey,!TValue>) T>(int32 hash,
                                                                                         !TKey key,
                                                                                         [out] int32& added,
                                                                                         !!T& 'value') cil managed
:

    IL_009d:  ldarg.s    'value'
    IL_009f:  ldarg.2
    IL_00a0:  ldloca.s   V_1
    IL_00a2:  constrained. !!T
    IL_00a8:  callvirt   instance bool class System.Drawing.IUpdateValue`2<!TKey,!TValue>::UpdateValue(!0,
                                                                                                       !1&)

**Comment by filipnavara** [comment]
Are the restrictions documented somewhere? I don't see a big problem with the fact that the AOT fails, but there's no warning/error. Neither is there an option to keep the IL unstripped for the problematic calls.

**Comment by vargaz** [comment]
The restrictions are hard to describe at a user level. We should probably keep the IL for these methods.

**Comment by filipnavara** [comment]
I don't quite understand why `InsertResult Insert<T>(TKey key, ref T value) where T : ICreateOrUpdateValue<TKey, TValue>` works and `InsertResult InternalInsert<T>(int hash, TKey key, out int added, ref T value) where T : ICreateOrUpdateValue<TKey, TValue>` doesn't. The constraints look identical to me.

**Comment by vargaz** [comment]
The problem is the AddInfo struct, generics + structs don't work very well in an AOT environment. As a workaround, I'd suggest getting rid of it and passing the 2 parameters normally.
