### ISSUE TITLE
Add CI lane for iOS SDK

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7030]

**Comment by vargaz** [comment]
https://jenkins.mono-project.com/job/test-mono-mainline-product-sdks-ios/

**Comment by akoeplinger** [comment]
A PR trigger is also available for this via `@monojenkins build OS X x64 iOS SDK` so I think we should be done here.

**Comment by marek-safar** [comment]
This needs to be PR lane, could you add it there

**Comment by luhenry** [comment]
@marek-safar the PR lane already exist at https://jenkins.mono-project.com/view/Pull%20requests/job/test-mono-pull-request-amd64-osx-products-sdks-ios/ and https://jenkins.mono-project.com/view/Pull%20requests/job/test-mono-pull-request-amd64-osx-products-sdks-android/

**Comment by marek-safar** [comment]
@luhenry cool, why is it not included in the default set?

**Comment by luhenry** [comment]
Because they mostly don't work, take too many resources and are waiting for the dedicated bots with the devices attached.

**Comment by vargaz** [comment]
The ios lane works mostly, and the x.ios build now use the same code, so we should try to keep it running. It runs on the osx-64 bots and one build/test run takes about 50 min.

**Comment by vargaz** [comment]
The only problem is that it runs on the limited osx-64 bot pool.

**Comment by luhenry** [comment]
Dedicated bots are being provisioned with devices attached. It would make a lot of sense to wait for these bots to be online and to tests on devices then.

**Comment by akoeplinger** [comment]
I agree with Ludovic, it's better to wait for the dedicated bots.
