### ISSUE TITLE
Mono Compilation issue on Windows 7

### ISSUE THREAD

**Issue by vikashkumar** [mono/mono#7033]
## Steps to Reproduce

Any solution of this error:
https://stackoverflow.com/questions/48375000/mono-build-on-cygwin-have-error-how-to-do-build?rq=1

### On which platforms did you notice this

[ ] Windows

**Version Used**:

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by marek-safar** [comment]
We are working on making Windows build better. See #6857

**Comment by akoeplinger** [comment]
That said the cygwin build is currently still the supported way of building Mono on Windows. See this StackOverflow answer which explains in more detail what you're seeing.
