### ISSUE TITLE
PtrToStructure fails to Marshal LPWstr/wchar_t*

### ISSUE THREAD

**Issue by rincewound** [mono/mono#7036]
## Steps to Reproduce

I have  legacy application that uses a native buffer to communicate with a native dll. The native DLL will drop structs into the buffer which are then deserialized in the C# application using Marshal.PtrToStructure. Primitive types seem to work okay, however when we try to pass strings by way of wchar_t* the Marshal fails to honor the encoding and only grabs the first byte of the string, if the second byte is 0x00 (as is the case for most english texts)

example struct:
Native:
```
struct foo
{
  wchar_t * attrib1;
  wchar_t* attrib2;
  int attrib3;
  //...
}
```

Managed:
```
[StructLayout(LayoutKind.Sequential)]
struct foo_managed
{
  [MarshalAs(UnmanagedType.LPWStr)] public string attrib1;
  [MarshalAs(UnmanagedType.LPWStr)] public string attrib2;
 public int attrib3;
//...
}
```

Code to deserialize:
`foo_managed f = Marshal.PtrToStructure(bufferStartPtr, typeof(foo_managed));`

If attrib1 were to be filled with the string "ABCD" we only get to see "A" after retrieving the data with PtrToStructure, the reason probably being, that the representation of the (w) string is in fact:
**0x41 0x00 0x42 0x00 0x43 0x00 0x44 0x00 0x00 0x00**
and the deserializer will stop reading when it encounters the first 0x00.

## Expected Behavior
PtrToStructure should be aware of the encoding and honor it.

### On which platforms did you notice this

[ ] macOS
[x] Linux/**ARM**
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 19:36:28 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

**Comment by kumpera** [comment]
Hi, I tried this on OSX and linux with a recent version (5.13) and I cannot repro. Please try again if you hit it.

For reference, this is the test case I used:
```c#
using System;
using System.Runtime.InteropServices;


[StructLayout(LayoutKind.Sequential)]
struct Foo
{
	[MarshalAs(UnmanagedType.LPWStr)] public string str;
	public int ival;
}

class Driver {
	static void Main () {
		IntPtr str = Marshal.AllocHGlobal (20);
		Marshal.WriteByte (str + 0, 0x41);
		Marshal.WriteByte (str + 1, 0x0);

		Marshal.WriteByte (str + 2, 0x42);
		Marshal.WriteByte (str + 3, 0x0);

		Marshal.WriteByte (str + 4, 0x0);
		Marshal.WriteByte (str + 5, 0x0);
		
		IntPtr ptr = Marshal.AllocHGlobal (IntPtr.Size * 2);
		Marshal.WriteIntPtr (ptr + 0, str);
		Marshal.WriteInt32 (ptr + IntPtr.Size, 99);

		var res = Marshal.PtrToStructure (ptr, typeof (Foo));
		Console.WriteLine ("res {0}", res == null);

		var f = (Foo)res;

		Console.WriteLine ($"f str: '{f.str}' is null: {f.str == null} ival: {f.ival}");
	}
}
```
