### ISSUE TITLE
Add CI trigger for failed jobs

### ISSUE THREAD

**Issue by kumpera** [mono/mono#7051]
A very common task when dealing with a PR is to retry failed jobs due to flakiness or a failure that was addressed on master.

This is pretty repetitive so having something like `@monojenkins build failed` would be amazing.

**Comment by marek-safar** [comment]
@akoeplinger how difficult would be to have `@monojenkins build retry` which triggers build only on failed lanes ?

**Comment by akoeplinger** [comment]
That should be fairly easy to do, about half a day.

**Comment by akoeplinger** [comment]
This is done now, took a bit longer than expected since the retry function isn't accessible from the REST API so I had to add a proxy job on Jenkins which uses Groovy to do the retry.

We now trigger that one when you comment `@monojenkins build failed` on a PR.
