### ISSUE TITLE
System.Security.Cryptography.Encryption.ECDiffieHellman.dll facade is now flagged as a threat by Windows Defender

### ISSUE THREAD

**Issue by pjcollins** [mono/mono#7052]
The `System.Security.Cryptography.Encryption.ECDiffieHellman.dll` facade assembly currently bundled in mono-2017-12 Xamarin.Android packages is now seen as a threat by Windows Defender. There appears to be a change between mono-2017-10 and mono-2017-12 that results in this file being flagged by Windows Defender. I am unable to reproduce using a recent Xamarin.Android build from master (before the mono-2017-12 bump was merged).

## Steps to Reproduce
(The following steps should be executed on Windows 10)
1. Download the following .vsix file from a recent OSS XA build tracking the mono-2017-12 integration PR:
https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/2517/Azure/processDownloadRequest/xamarin-android/bin/BuildDebug/Xamarin.Android.Sdk-OSS-8.2.99.111_HEAD_392f355.vsix

2. Ensure your Windows Defender Firewall is enabled, as shown below:

![image](https://user-images.githubusercontent.com/2000163/36229532-8b0b72e2-11a5-11e8-9073-8f483bc7463d.png)

3. Rename the file extension from .vsix to .zip, and attempt to extract it ~anywhere.
4. Windows defender should (presumably falsely) detect a threat within `System.Security.Cryptography.Encryption.ECDiffieHellman.dll`.

![image](https://user-images.githubusercontent.com/2000163/36230330-13b3261a-11a8-11e8-8374-6a8c814ac2d7.png)

Alternatively, you can install the .vsix file and then navigate to the installation location listed below. The facade in question will be removed by Windows Defender when navigating to this directory in Windows Explorer.
 >C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades

## Current Behavior

The `System.Security.Cryptography.Encryption.ECDiffieHellman.dll` facade is flagged as a threat by Windows Defender, and it is removed from the file system.

Additionally, I was able to compile against this assembly previously before it was deleted, and encountered an MSBuild error along the following lines:

```
CSC : error CS0009: Metadata file 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Security.Cryptography.Encryption.ECDiffieHellman.dll' could not be opened -- Operation did not complete successfully because the file contains a virus or potentially unwanted software. [xamarin-android\tests\BCL-Tests\LocalTests.NUnit\LocalTests.NUnit.csproj]
```

## Expected Behavior
The `System.Security.Cryptography.Encryption.ECDiffieHellman.dll` facade is not seen as a threat by Windows Defender.

### On which platforms did you notice this

- [ ] macOS
- [ ] Linux
- [x] Windows

**Version Used**:
Mono-2017-12

**Comment by marek-safar** [comment]
I don't know if we can do anything about it, the assembly contains nothing except few type forwarders

**Comment by marek-safar** [comment]
@pjcollins could you try to submit it using https://www.microsoft.com/en-us/wdsi/filesubmission as false positive (it'd be nice to do it via VSTS but no high hopes you can find it there)

**Comment by luhenry** [comment]
I can't reproduce on my domain joined Surface Book.

**Comment by pjcollins** [comment]
I've applied some updates, and can also no longer reproduce here with the following Windows Defender versions. 

![image](https://user-images.githubusercontent.com/2000163/36231392-de407f74-11ab-11e8-9fb8-be5fc66df9b2.png)
