### ISSUE TITLE
Environment.TickCount not monotonic

### ISSUE THREAD

**Issue by lmccormick246** [mono/mono#7056]
This may or may not be a platform problem with our devices but our old devices running a different operating system had Environment.TickCount as monotonic. 

What I mean by this is that changing the date/time of the device/system is not supposed to effect the Environment.TickCount.

## Steps to Reproduce

1. Run c# application printing Environment.TickCount
2. Change the date/time of the device using date +%T -s "00:00:00"
3. See that TickCount changed when changing the time. If you added a hour to the time, basically a hour of milliseconds would be added to the tickcount.

## Current Behavior

Changing the date/time of the device Changes the Environment.TickCount.

## Expected Behavior

Environment.TickCount should be monotonic and not change if time is changed.

### On which platforms did you notice this

[x ] Linux

**Version Used**:

5.4.1.7

**Comment by migueldeicaza** [comment]
See also: https://bugzilla.xamarin.com/show_bug.cgi?id=40912

**Comment by lmccormick246** [comment]
Also, it seemed to have broke around v4.6 or so. Maybe slightly before that. Ended up using Stopwatch.GetTimeStamp() instead of the tickcount because it actually had the desired behavior while tickcount did not.
