### ISSUE TITLE
Clarify xbuild -> msbuild switchover process

### ISSUE THREAD

**Issue by copumpkin** [mono/mono#7068]
I'm trying to package a recent mono on Nix[OS/pkgs] and I see that `xbuild` is now deprecated, but it's unclear to me how `msbuild` is intended to replace it. Is the design that distros' mono packages should include `msbuild`? If so, do we bootstrap `msbuild` somehow, or otherwise integrate it with the mono build? Or build mono, then build `msbuild`, then bundle the two together in the distro package? Or are users expected to just install the two separately?

Sorry if this sounds clueless, but I'm struggling to find information on how this is supposed to work. I didn't really have to think twice about `xbuild` back when that was the recommended tool 😄

**Comment by directhex** [comment]
`msbuild` comes out of a different git repository to `mono`, so whilst the intention is that both are installed by end users together, the build process is linear (`mono` then `msbuild`).

https://github.com/mono/linux-packaging-msbuild/blob/master/debian/rules gives an idea of the build process for `msbuild`, at least today (major changes in the next major version)

**Comment by copumpkin** [comment]
@directhex thank you! Any opinion on whether it's common for users to want `mono` without `msbuild`? Trying to decide whether I should package them together or separately, to minimize friction for getting started.

I could imagine a situation where `msbuild` versions change at a different rate from `mono` ones, so someone might want more granular control over their `msbuild` installation, but if that doesn't actually happen often, it might still be worth packaging them together.

**Comment by directhex** [comment]
Basically depends on whether "users" means "developers" or "app end-users"

**Comment by akoeplinger** [comment]
We've also had a few cases where we made changes in Mono that relied on changes in msbuild or vice versa so it might not always be possible to use any random version of msbuild with any random version of Mono.

I'd not include msbuild or any of the other development-related tools/libraries in the main `mono` package, we've split our Debian packages into `mono-runtime` and `mono-devel` (among others) so users who just want to run apps can pick the former.

**Comment by akoeplinger** [comment]
Closing this for now since I think all the questions were addressed, but please feel free to ask any followup questions :)
