### ISSUE TITLE
Add internal API for setting native crash handler callback

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7072]
To support a custom native exception handling registration from the managed world we want to introduce managed API to support that.

The proposal is to extend Runtime class https://github.com/mono/mono/blob/master/mcs/class/corlib/Mono/Runtime.cs by following method.

```C#
internal static void SetNativeCrashHandler (IntPtr address);
```

We should assume the address points to a function which takes no arguments and returns/leaves no value and is called using default platform specific calling convention.

**Comment by lewurm** [comment]
what would be the use case for that? I see this only relevant for embedders, and I think it would be better to provide an unmanaged API for that. 

Also it's not quite clear what you exactly mean:
1. handler that should be called for every exception handling event that is done by the runtime?
1. handler that should be called on an _unhandled_ exception?
2. handler that should be called on a native crash, i.e. runtime crash?
    1. on `SIGSEGV`?
    2. on `SIGABRT` too?
    3. other signals?

**Comment by joncham** [comment]
Note there is some native embedding APIs related to crash handling already https://github.com/mono/mono/blob/098f6e8aa8ead1a80b751fa34e5e049439c2f0c3/mono/mini/jit.h#L31

**Comment by luhenry** [comment]
This being for the use of VSfM only, it would be much simpler to just have it as a runtime API, that is not part of the public API but marked as `MONO_API`.

**Comment by alexanderkyte** [comment]
This bug asks for a very general reporter. The MERP reporter was marked as an implementation of this, despite only working for a single proprietary reporter. Is VSfM the only stakeholder who needs a reporter like this?

**Comment by marek-safar** [comment]
@alexanderkyte yes VSfM is very likely going to be the only user of this

**Comment by luhenry** [comment]
Some followup work will need to be done:
 - [ ] Add support for SIGTERM /cc @sgmunn 
 - [ ] Dump stacktrace for MERP to a free form file
