### ISSUE TITLE
Hybrid AOT breaks setting thread UI culture

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#7085]
## Steps to Reproduce

1. Create new Cocoa application in Visual Studio for Mac
2. Add "--aot=all|hybrid" to "mmp" additional arguments in project options
3. Change the code in Main.cs to:

```
using AppKit;
using System.Threading;
using System;

namespace CultureTest
{
	static class MainClass
	{
		static void Main(string[] args)
		{
			Console.Out.WriteLine("Thread.CurrentThread.CurrentUICulture: {0}", Thread.CurrentThread.CurrentUICulture?.ToString());
			Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;
			Console.Out.WriteLine("Thread.CurrentThread.CurrentUICulture: {0}", Thread.CurrentThread.CurrentUICulture?.ToString());
		}
	}
}

```

## Current Behavior

The application crashes with null reference exception when accessing `Thread.CurrentThread.CurrentUICulture` in the second `WriteLine` statement.

## Expected Behavior

Application should not crash.

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.8.0.123 (2017-10/38502063cac Thu Feb  1 12:58:29 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

**Comment by marek-safar** [comment]
I can reproduce the issue and it seems to be hybrid related.

**Comment by marek-safar** [comment]
@vargaz could you investigate? It looks like some stack issue as calling `ToString` on a valid instance in `Thread.CurrentThread.CurrentUICulture.ToString ()` context throws NRE

**Comment by vargaz** [comment]
It is caused by enabling partial sharing for JITted code, which was not tested at all, it was only enabled in full-aot mode.
