### ISSUE TITLE
Regression in Array interface conversions

### ISSUE THREAD

**Issue by slide** [mono/mono#7093]
## Steps to Reproduce

1. Unzip the attachment
2. Run ```mono ipy.exe doit.py``

[ironpython_parameter_issue.zip](https://github.com/mono/mono/files/1733429/ironpython_parameter_issue.zip)

## Current Behavior

Current behavior is that the method is called successfully, you see the message "You are here" printed on the console. 

## Expected Behavior

This should not work as an `int[]` is not an `IEnumerator<int>`. This started failing in the IronPython unit tests on Mono 5.8. It throws an exception as expected on previous versions. On MS.NET I get the following when running the reproduction code as expected

```
Traceback (most recent call last):
  File ".\doit.py", line 7, in <module>
TypeError: expected IEnumerator[int], got Array[int]
```

### On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 18:15:21 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

**Comment by marek-safar** [comment]
@lambdageek could you please investigate

**Comment by lambdageek** [comment]
It's `mono_class_is_assignable_from` again, like #7095. Standalone repro:

```csharp
using System;

public class Repro {
  public static void Main () {
        var a = new int [] {1,2,3};
        var t = typeof (System.Collections.Generic.IEnumerator<int>);
        Console.WriteLine (t.IsAssignableFrom (a.GetType()));
  }
}
```

Expected output: `False`. Actual output: `True`.

**Comment by lambdageek** [comment]
@kumpera I know we talked about it a few times, but I think I don't understand the full story of why ``IEnumerator`1`` must be an array special interface.  It's something like "we return the same instance from `(arr as IEnumerable<byte>).GetEnumerator()` and `(arr as IEnumerable<sbyte>).GetEnumerator()` and therefore we need `IEnumerator<byte>` and `IEnumerator<sbyte>` to have the special hacked `is_assignable_from` semantics.  Is that right so far?

But we dont' need `T[]` and `IEnumerator<T>` to be AssignableFrom-related in any way, right?

**Comment by kumpera** [comment]
@lambdageek the problem is how we implemented Array::GetEnumerator for types that have interfaces. Say string.

We need to be able to do `IEnumerable<ICloneable>::GetEnumerator()` and `IEnumerable<IComparable>::GetEnumerator()` against a `string[]`. Our implementation kinda spits a single weird Enumerator object.

The right way would be to spit one type per IEnumerable that we need. Just like coreclr does.
I strongly agree with you that IEnumerable must stop being a magic interface.

**Comment by lambdageek** [comment]
Ah. Thanks @kumpera.  Interfaces were the piece that I was missing.

Did you mean that IEnumerator should stop being magic or IEnumerable? (For this bug it's just IEnumerator that's a problem - but in general I agree that both should stop being magic).

Did we ever try doing it the coreclr way?  Was there an unacceptable regression in memory or AOT footprint?

**Comment by kumpera** [comment]
IEnumerator is magic cuz we fabricate one type per array type, instead of one per user-visible generic instance.
