### ISSUE TITLE
Question: .pdb files or .mdb?

### ISSUE THREAD

**Issue by define-private-public** [mono/mono#7107]
The main crux of my question comes from this issue over on the NuGet repo: https://github.com/NuGet/NuGetGallery/issues/5504, but I wanted to get an opinion from the Mono project itself.

I'm working on a library that's developed on Linux, but runs on OS X and Windows.  Right now one of my MonoDevelop setups is generating `.pdb`, and the other is generating `.mdb` files.  When I put my packages up on NuGet, I want to make sure that they are compatible with other C# IDEs (i.e Visual Studio).  Is there one that I should give preference to?

**Comment by alexrp** [comment]
As long as they're [Portable PDB](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md) files, they're preferred as they're understood by both Mono and .NET. MDB files are very Mono-specific.

**Comment by define-private-public** [comment]
So my library currently targets Mono/.Net 4.5.  I'm also writing an application that uses that library (as well as the same target too).  When I go to build on my .pdb machine, is it generating portable PDB files?  Or do I need to change the target?

**Comment by marek-safar** [comment]
If you are using VS on Windows you need to set `portable` as the debug output format or you can just do it by hand in the .csproj file

https://docs.microsoft.com/en-us/visualstudio/ide/reference/advanced-build-settings-dialog-box-csharp#output
