### ISSUE TITLE
Changes in Mono.Posix and Mono.Security required for NETSTANDARD 2.0 port of ngit

### ISSUE THREAD

**Issue by ststeiger** [mono/mono#7116]
In order to be able to have ngit compiled for NETSTANDARD 2.0, could we do the following things:

A) Move Mono.Posix Remoting to a separate dll ?
e.g. Mono.Remoting.Channels.Unix
or make the compilation of that namespace conditional to !NETFX ? 

B) In Mono.Posix/Mono.Unix.Native/CdeclFunction.cs
Somehow dispose of

```
	//this.assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly (
			//		assemblyName, AssemblyBuilderAccess.Run);

				///* MethodBuilder mb = */ tb.DefinePInvokeMethod (
				//		method, 
				//		library, 
				//		MethodAttributes.PinvokeImpl | MethodAttributes.Static | MethodAttributes.Public,
				//		CallingConventions.Standard, 
				//		returnType, 
				//		parameterTypes, 
				//		CallingConvention.Cdecl,
				//		CharSet.Ansi);
				//mi = tb.CreateType ().GetMethod (method);
```
as this doesn't compile in netstandard 2.0 

C) In Mono.Security\Mono.Security.Protocol.Tls/DebugHelper.cs
remove the DebugHelper, or move it into a !NETSTANDARD block ? 
DebugHelper.cs -- removed debug.Lisneter.add

D) And in Mono.Security\Mono.Security.Protocol.Tls\HttpsClientStream.cs

somehow replace this code, or make it conditional to full .net framework.

```
#pragma warning disable 618
//if (ServicePointManager.CertificatePolicy != null) {
//	ServicePoint sp = _request.ServicePoint;
//	bool res = ServicePointManager.CertificatePolicy.CheckValidationResult (sp, certificate, _request, _status);
//	if (!res)
//	return false;
//	failed = true;
//}
```

For reference:
https://github.com/mono/ngit/issues/79

Edit:
Never mind B) - compiled it from an old version of Mono.Posix - pre netstandard 2.0.

In latest Mono.Security:
X509Certificate2Impl: 
In outside implementaiton - the implementation of X509Certificate2Impl in system.security.cryptography.x509 is not accessible....

Latest Mono.Security less portable than the version from mono3.0.1

**Comment by marek-safar** [comment]
Couldn't you simply use existing nuget https://www.nuget.org/packages/Mono.Posix.NETStandard/ ?

**Comment by ststeiger** [comment]
Is it pre-release ? Didn't see it on nuget. Otherwise I must have mistyped. 
But anyway, Mono.Posix is not the problem. 
But that still doesn't include Mono.Security.

**Comment by marek-safar** [comment]
Yes, it's still pre-release although I am not sure why (@bholmes).

I don't understand the Mono.Security issue, there should be no Mono.Security build dependency when you are building netstandard 2.0 using the package I linked above.

**Comment by ststeiger** [comment]
Yea, there is no dependency of Mono.Posix on Mono.Security. 
And it builds fine. 

But mono.security and mono.posix both are dependencies of ngit (I'm trying to build ngit, not Mono.Posix) {already successfully finished}. 
Mono.Security is a build-dependency of ngit/NSch.
Mono.Posix is a dependency of ngit/Sharpen.Unix

**Comment by marek-safar** [comment]
@ststeiger I got it and made separate issue to make it clear what the goal is

**Comment by baulig** [comment]
The entire `Mono.Security\Mono.Security.Protocol.Tls.*` namespaces are obsolete and will eventually be removed.

What's your problem with `X509Certificate2Impl`?
