### ISSUE TITLE
storage.bos.xamarin.com connection timed out

### ISSUE THREAD

**Issue by acoolmanfromnowhere** [mono/mono#7124]
I've been trying to compile mono on my seedbox, but I'm not able to download. I'm getting timed out error.

The OS is Debian GNU/Linux 8 (jessie)

rl: (7) Failed to connect to storage.bos.xamarin.com port 80: Connection timed out

**Comment by akoeplinger** [comment]
@acoolmanfromnowhere which Mono commit are you trying to compile and how? storage.bos.xamarin.com was our old NAS in the Xamarin office which no longer exists.

**Comment by akoeplinger** [comment]
Closing this issue until more information is available.
