### ISSUE TITLE
Debuggee crashes when stepping in

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#7125]
## Steps to Reproduce

1. Install XI from here: [xamarin.ios-11.11.0.0.pkg](http://xamarin-storage/macios-mac-master/96/96085adb66129c42e9ae8e28f44d06112f9e1896/xamarin.ios-11.11.0.0.pkg)
2. Download [dbgcrash.zip](https://github.com/mono/mono/files/1738259/dbgcrash.zip), and extract it somewhere. In my case I've extracted it to `/Users/rolf/test/dbgcrash` (that's the path I'll use ahead, fix-up accordingly).
3. Open `/Users/rolf/test/dbgcrash/main-args.txt` and fix all instances of `/Users/rolf/test/dbgcrash` according to your location.
4. Checkout https://github.com/xamarin/xamarin-macios (5788a9fa9ba08fea34e0e28d7810d5f4637229d8) and all its submodules. It's **not** necessary to build xamarin-macios.
5. Run the following commands in the root xamarin-macios directory:

```shell
make -C src build/ios/Constants.cs
make -C tools/mtouch SdkVersions.cs
```

6. Open tools/mtouch/mtouch.sln
7. Edit the property Driver.MonoTouchDirectory (in tools/mtouch/mtouch.cs:204) to return `"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current"`:

```csharp
public static string MonoTouchDirectory {
	get {
		return "/Library/Frameworks/Xamarin.iOS.framework/Versions/Current";
	}
}
```
8. Open the mtouch project's properties, and set the Run/Configuration/Default's Arguments to `@/Users/rolf/test/dbgcrash/main-args.txt` (fix according to your own path)
.
9. Open `tools/common/StaticRegistrar.cs:` and put a breakpoint on line 1631 (the first line of the `GetProtocolAttributeWrapperType` function):

![screenshot 2018-02-19 22 48 56](https://user-images.githubusercontent.com/249268/36398375-14d2b358-15c7-11e8-8509-d6074cc02b4f.png)

10. Run the project. When the breakpoint is hit, step into twice.

## Current Behavior

Crash. Complete output: https://gist.github.com/rolfbjarne/0a3856587363398a8fa35b72b99daba5

## Expected Behavior

No crash

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
$ mono --version
Mono JIT compiler version 5.10.0.15 (2017-12/907075a5f01 Fri Dec 29 11:26:30 EST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```

```
Visual Studio Community 2017 for Mac (Preview)
Version 7.4 Preview (7.4 build 985)
Installation UUID: 3de793cc-1bea-4b7e-9e90-bb6747c5ca7e
Runtime:
	Mono 5.10.0.15 (2017-12/907075a5f01) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 510000015

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.5.5
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Version: 4.5.0.3 (Visual Studio Community)

Xamarin.iOS
Version: 11.11.0.3 (Visual Studio Community)
Hash: 7c8861011
Branch: master
Build date: 2018-02-16 11:15:45+0100

Xamarin.Android
Version: 7.0.99.113 (Visual Studio Community)
Android SDK: Not found

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704000985
Git revision: 0bed5a3380dbe82009f80c895623208d6c0df152
Build date: 2018-02-02 20:00:14-05
Xamarin addins: 612453baa9a0faea49aa554be49c01c2e0542bf3
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jan 11 22:59:40 PST 2018
    root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
```

**Comment by lewurm** [comment]
fixed by #6456
