### ISSUE TITLE
[Discussion] What would dotnet webassembly dependency be like?

### ISSUE THREAD

**Issue by Thaina** [mono/mono#7132]
In many place that talk about webassembly with huge application I would heard about download size of bulk webassembly generated from the system that need to include everything

And so I think we should have something like CDN that we could split our application in to many small dll-like wasm and able to share library and manage dependency like nuget on browser cache. And while in development we could also depend on dll-like wasm like that in place of dll too

I mean when we compile our C# code with mono to wasm. We don't need to refer to a real dll for dependency but could refer to the url of dll-like wasm that was compiled from mono instead

Did/will it be possible? Should it? And what we need from mono to make it possible?

**Comment by marek-safar** [comment]
Yes, this is something we have on our long-term roadmap but it's not something we are actively working on right now. Our short-term focus is to reduce the overall size via different measures.
