### ISSUE TITLE
CoreFX System.IO.Pipes namespace

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7143]

**Comment by luhenry** [comment]
Depends on https://github.com/mono/mono/pull/8051.

**Comment by mfilippov** [comment]
@luhenry Have you any news about this issue. I very want to have parallel build on macOS in MSBuild.

**Comment by filipnavara** [comment]
I reworked the original GSoC patch. It doesn't work, but feel free to pick it up and debug

https://github.com/filipnavara/corefx/tree/corefx-pipes (CoreFX changes needed because of some code not yet imported to Mono)
https://github.com/filipnavara/mono/tree/corefx-pipes

**Comment by jaykrell** [comment]
3 tests from here are failing several PRs in CI.
 https://github.com/mono/mono/issues/9776
