### ISSUE TITLE
[XI] RuntimeFeatureTest.NoNewFeaturesAdded failure in mscorlib tests

### ISSUE THREAD

**Issue by dalexsoto** [mono/mono#7145]
_From @GouriKumari on February 19, 2018 16:29_

### Steps to Reproduce

1. Update System to Xamarin.iOS d15-7 build, mtouch 11.10.0.1 (d15-7: eadb8376)
2. Execute mscorlib tests on iOS and tvOS device

### Expected Behavior
Tests should pass

### Actual Behavior
RuntimeFeatureTest
2018-02-18 21:41:04.320 mscorlibtests[55322:12178179] 	[FAIL] RuntimeFeatureTest.NoNewFeaturesAdded :   Expected is <System.ValueTuple`2[System.String,System.Boolean][1]>, actual is <System.ValueTuple`2[System.String,System.Boolean][0]>
  Values differ at index [0]

### Environment

```
mtouch 11.10.0.1 (d15-7: eadb8376)
```

### Build Logs

XI Test Log: http://xqa.blob.core.windows.net/gist/log-38175501bfc743d9862974451b9997ce.txt

tvOS build log: http://xqa.blob.core.windows.net/gist/report-c3fa275a07304e95bb8f58315d7cbfe9.txt
Test Log:http://xqa.blob.core.windows.net/gist/mscorlib-tvos08-41-5785652fd1ecb4eddd80ebefb1562b316473fa559b08-41-57-8940ddcbc60a417aba807f4d43c6cc8d.zip

###Regression: yes. This failure is not observed in d15-6.

_Copied from original issue: xamarin/xamarin-macios#3533_

**Comment by dalexsoto** [comment]
I can confirm this issue

```
	[FAIL] RuntimeFeatureTest.NoNewFeaturesAdded :   Expected is <System.ValueTuple`2[System.String,System.Boolean][1]>, actual is <System.ValueTuple`2[System.String,System.Boolean][0]>
Tests run: 8023 Passed: 8022 Inconclusive: 0 Failed: 1 Ignored: 39
```

using 

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.4 Preview (7.4 build 985)
Installation UUID: 4e014908-906a-4d2b-9aed-1d598a6d71cf
Runtime:
	Mono 5.10.0.105 (2017-12/4b1745401d5) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 510000105

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.4.0.3 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.10.0.4 (Visual Studio Enterprise)
Hash: a8e5fc54
Branch: d15-7
Build date: 2018-02-19 11:57:55-0600

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

**Comment by dalexsoto** [comment]
cc/ @spouliot / @vargaz

**Comment by dalexsoto** [comment]
_From @spouliot on February 20, 2018 14:15_

@dalexsoto move issue to mono repo and label with with `target-xamarin-ios`

**Comment by luhenry** [comment]
This also fails on XA after `mono:2017-12` bump https://github.com/xamarin/xamarin-android/issues/1310

**Comment by akoeplinger** [comment]
The public const field in `RuntimeFeatures` was probably linked out. I'm wondering why this wasn't catched during integration?
