### ISSUE TITLE
add CI lane for Hybrid AOT

### ISSUE THREAD

**Issue by lewurm** [mono/mono#7162]
similar to the Full AOT lane.

/cc https://github.com/mono/mono/pull/7158 https://github.com/mono/mono/pull/7161

**Comment by marek-safar** [comment]
@lewurm @vargaz what should be Mono config values for this lane?

**Comment by vargaz** [comment]
We can run make hybridcheck in mini/ on the normal lanes, it doesn't take too much time.

**Comment by lewurm** [comment]
https://github.com/mono/mono/issues/7172
