### ISSUE TITLE
Filipino Localization 

### ISSUE THREAD

**Issue by cordeta** [mono/mono#7169]
I would like to offer Filipino Localization to some important documents

Reponse is highly appreciated

**Comment by akoeplinger** [comment]
which documents did you have in mind?

**Comment by cordeta** [comment]
https://github.com/mono/mono/blob/master/README.md
https://github.com/mono/mono/blob/master/LICENSE
https://github.com/mono/mono/blob/master/PATENTS.TXT
https://github.com/mono/mono/blob/master/docs/threading
https://github.com/mono/mono/blob/master/docs/stack-overflow.txt
https://github.com/mono/mono/blob/master/docs/ssapre.txt
https://github.com/mono/mono/blob/master/docs/remoting
https://github.com/mono/mono/blob/master/docs/precise-gc
https://github.com/mono/mono/blob/master/docs/object-layout
https://github.com/mono/mono/blob/master/docs/mini-doc.txt
https://github.com/mono/mono/blob/master/docs/jit-trampolines
https://github.com/mono/mono/blob/master/docs/jit-thoughts
https://github.com/mono/mono/blob/master/docs/jit-imt
https://github.com/mono/mono/blob/master/docs/ir-desc
https://github.com/mono/mono/blob/master/docs/internal-calls
https://github.com/mono/mono/blob/master/docs/glossary.txt
https://github.com/mono/mono/blob/master/docs/file-share-modes
https://github.com/mono/mono/blob/master/docs/exceptions
https://github.com/mono/mono/blob/master/docs/README

Typically some of the docs file and sources file . 
If you may , i would request a staging repo  il8n/tl_PH

**Comment by akoeplinger** [comment]
@marek-safar @luhenry what do you think?

**Comment by marek-safar** [comment]
I certainly don't want to discourage the contributions but most of the documents are quite a low level so not sure how effective the translation will be. I'd encourage you to help translating more user-facing projects like http://www.monodevelop.com/developers/articles/translations/
