### ISSUE TITLE
Create CI PR job for more AOT configurations

### ISSUE THREAD

**Issue by luhenry** [mono/mono#7172]
We should be able to run any PR against these configurations. They should run on Linux i386 and Linux x64, and extend it to OS X i386, OS X x64, Linux ARMv5, Linux ARMv7 and Linux Aarch64 depending on available capacity.

They should be trigger-based until fixed but should be enabled on all PR in the near-term. In the long-term they should all be made required.

We already have a set of jobs for master for these configurations:
 - AOT: https://jenkins.mono-project.com/job/test-mono-mainline-aot/
 - AOT+LLVM: https://jenkins.mono-project.com/job/test-mono-mainline-aot+llvm/
 - hybridAOT: https://jenkins.mono-project.com/job/test-mono-mainline-hybridaot/
 - hybridAOT+LLVM: https://jenkins.mono-project.com/job/test-mono-mainline-hybridaot+llvm/
 - fullAOT+LLVM: https://jenkins.mono-project.com/job/test-mono-mainline-fullaot+llvm/

The fullAOT configuration (https://jenkins.mono-project.com/view/Pull%20requests/job/test-mono-pull-request-amd64-fullaot/) is already enabled on all PR, and the bitcode configuration (https://jenkins.mono-project.com/view/Pull%20requests/job/test-mono-pull-request-amd64-bitcode/) is already trigger-based. These 2 configurations should also be enabled and required in the long term.

**Comment by luhenry** [comment]
Updated with Bitcode

**Comment by akoeplinger** [comment]
Most of this was already done.
