### ISSUE TITLE
Structural comparison in an FSharp struct fails silently in Windows Mono 64 bit 

### ISSUE THREAD

**Issue by anticrisis** [mono/mono#7177]
Using a `[<Struct>]` record type with various collection functions seems to produce incorrect results when equality and comparison are needed. This example shows `List.distinct` failing, but I've run into problems with Set, Map and others in this same environment.

I originally experienced this running an FSharp DLL on Unity3D on Windows, but was able to eliminate Unity from the steps required to reproduce the problem.

Originally reported at https://github.com/fsharp/fsharp/issues/823

## Steps to Reproduce

1. Install Mono for Windows 64 bit from [here](http://www.mono-project.com/download/stable/)

2. Build this project with Visual Studio 2017 Community: [github repo](https://github.com/anticrisis/fsharp-struct-mono-64). The test code is in `Program.fs` and simplified here:

```
[<Struct>] type V3 = { a: int; b: int; c: int; } 
let v1 = { a=1; b=2; c=3 }
let v2 = { a=4; b=5; c=6 }
let v3 = { a=1; b=2; c=3 }
let vs = [ v1; v2; v3 ]
printfn "vs = %A\n" vs

// mono 64-bit: returns a list of three items, including the duplicate
printfn "distinct vs = %A" (List.distinct vs)

// mono 64-bit: returns 3 
printfn "length of distinct vs = %i" (List.distinct vs |> List.length)
```

## Current Behavior

The output of `List.distinct` is a list with `3` elements. 

## Expected Behavior

The output of `List.distinct` should be a list with `2` elements.

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

In other testing, I've noticed that the code runs correctly on 32-bit versions of Mono.

**Version Used**:

Mono JIT compiler version 5.8.0 (Visual Studio built mono)

### Output of test
```
C:\Program Files\Mono>mono --version
Mono JIT compiler version 5.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

C:\Program Files\Mono>mono c:\users\anticrisis\source\repos\fsharp-struct-mono-64\fsharp-struct-mono-64\bin\Debug\fsharp_struct_mono_64.exe
[||]
System.IntPtr.Size = 8
vs = [{a = 1;
  b = 2;
  c = 3;}; {a = 4;
            b = 5;
            c = 6;}; {a = 1;
                      b = 2;
                      c = 3;}]

distinct vs = [{a = 1;
  b = 2;
  c = 3;}; {a = 4;
            b = 5;
            c = 6;}; {a = 1;
                      b = 2;
                      c = 3;}]
length of distinct vs = 3
```

**Comment by lambdageek** [comment]
Mono 5.8.0.108 and 5.12.0.1 (2018-02/3320f45d98e) on OSX both give the correct answer using both `mono32` and `mono64`.
I wonder what's up on Windows...

**Comment by joncham** [comment]
Corresponds to Unity issue https://issuetracker.unity3d.com/issues/unity-incorrectly-compares-two-values-when-the-comparison-method-is-written-in-f-number-and-added-to-unity-through-external-dll

**Comment by marek-safar** [comment]
Closing based on @anticrisis comment
