### ISSUE TITLE
MSBuild always recompiles project if it has a resx with a windows path.

### ISSUE THREAD

**Issue by cwensley** [mono/mono#7184]
## Steps to Reproduce

1.  Unzip attached solution: [TestResXCompile.zip](https://github.com/mono/mono/files/1745608/TestResXCompile.zip)
2. Run msbuild, notice it says `Processing resource file "Properties/Resources.resx" into "obj/x86/Debug/TestResXCompile.Properties.Resources.resources"` and runs `csc.exe` to compile (good).
3. Run msbuild again, and notice it compiles the resources and output dll again (not good)

## Current Behavior

If the path to the file in a resx contains a windows backslash '\\', then it will always recompile.  This is very detrimental with a large solution and your core library has a .resx.

Changing the path to use forward slashes '/' makes it work as expected, however should not be necessary.

## Expected Behavior

The project should not recompile if no inputs have changed.

### On which platforms did you notice this

[X] macOS

**Version Used**:

```
Mono JIT compiler version 5.8.0.123 (2017-10/38502063cac Thu Feb  1 12:58:29 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

**Comment by radical** [comment]
No, this isn't a regression. I have a fix for this.

**Comment by marek-safar** [comment]
@radical do you have PR for the fix?

**Comment by radical** [comment]
Fixed in https://github.com/mono/msbuild/pull/44 .
