### ISSUE TITLE
The new web stack sometimes leaves exceptions unobserved for its internal Tasks when web requests are canceled

### ISSUE THREAD

**Issue by brendanzagaeski** [mono/mono#7194]
This is related to <https://github.com/mono/mono/issues/7094> since both issues are about exceptions when canceling web requests. The fixes for the 2 issues will need to be compatible with each other.

## Regression status: regression in the new web stack

- BAD: Local build of <https://github.com/mono/mono/pull/7080> (at 7b992bb) in my testing environment
- BAD: [master@cd09ddbc55c](https://jenkins.mono-project.com/view/Per-commit%20packages/job/build-package-osx-mono/job/master/110/) (The new web stack)
- GOOD: [master@7bf60c3ec95](https://jenkins.mono-project.com/view/Per-commit%20packages/job/build-package-osx-mono/job/master/106/) (A few builds before the new web stack)

## Steps to Reproduce

1. Set up a local HTTP server for testing. (Or change the endpoint in the test case to use a remote server.)
2. Compile and run the following program. This is very similar to the test case from <https://github.com/mono/mono/issues/7094>, but it uses a shorter cancellation timeout (to test an earlier time window during the web request), adds an event handler for the `UnobservedTaskException` event, and modifies the try-catch statement to ignore exceptions (since any exception caught there is already correctly observed).

    ```csharp
    using System;
    using System.IO;
    using System.Net.Http;
    using System.Threading.Tasks;
    using System.Threading;
    
    class Program {
    	static CancellationTokenSource cts;
    	static HttpClient client;
    
    	public static void Main () {
    		System.Threading.Tasks.TaskScheduler.UnobservedTaskException += (sender, e) => {
    			var ex = e.Exception.Flatten ().InnerException;
    			Console.WriteLine ($"* Unobserved exception! {ex.GetType ()}: {ex.Message}");
    			e.SetObserved ();
    		};
    
    		var data = new byte [600 * 1024 * 1024];
    		using (var stream = new MemoryStream (data)) {
    			for (var i = 0; i < 4; i++) {
    				Run (stream).Wait ();
    				stream.Position = 0;
    			}
    		}
    
    		Thread.Sleep (500);
    		GC.Collect ();
    		GC.WaitForPendingFinalizers ();
    
    		Console.WriteLine ("done");
    	}
    
    	async static Task Run (Stream stream)
    	{
    		cts = new CancellationTokenSource ();
    		cts.CancelAfter (20);
    		try {
    			using (client = new HttpClient ()) {
    				var response = await client.PostAsync ("http://localhost", new StreamContent (stream), cts.Token);
    			}
    		} catch (Exception ex) {
    		}
    	}
    }
    ```

## Current Behavior

Depending on the particular timing of how the program runs, various [unobserved exceptions](https://blogs.msdn.microsoft.com/pfxteam/2011/09/28/task-exception-handling-in-net-4-5/) appear. For example:

```
* Unobserved exception! System.Net.WebException: Error writing headers
* Unobserved exception! System.Net.WebException: The request was canceled
* Unobserved exception! System.Net.WebException: Error writing headers
* Unobserved exception! System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
* Unobserved exception! System.Net.WebException: The request was canceled
done
```

(The `Message` for the outer `AggregateException` in all cases is "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.")

## Expected Behavior

With mono/master@7bf60c3ec95 or .NET Core 2.1.4, _no_ exceptions are left unobserved, so the program outputs just the final message:

```
done
```

(Combined with <https://github.com/mono/mono/issues/7094>, this means that every canceled web request should throw a `TaskCanceledException` and leave 0 unobserved exceptions.)

## Additional testing environment info (brief)

macOS 10.12.6
US English locale

### On which platforms did you notice this

\[x\] macOS
\[ \] Linux
\[ \] Windows

**Comment by baulig** [comment]
You can actually trigger this without cancellation by issuing a web request that will return an error.

It looks like code such as this will trigger this:

    var myTcs = new TaskCompletionSource<object> ();
    try {
        DoStuffHere ();
    } catch (AggregateException aggregate) {
        throw;
    } catch (Exception error) {
        // Make sure error is not an AggregateException
        myTcs.TrySetException (error);
        throw;
    }

I believe this is because `TrySetException ()` will wrap the `error` in a new `AggregateException` - which won't be observed even through we do observe the original `error`.

Next week, I will get rid of these `TaskCompletionSource<T>`s and replace them with a better approach.

**Comment by baulig** [comment]
See #7293.

**Comment by brendanzagaeski** [comment]
I'm not sure if <https://github.com/mono/mono/pull/7293> by itself was expected to resolve this scenario completely? It looks like maybe some follow-up changes might be required to make those adjustments effective for this scenario?

Thanks in advance!

## Verification status: not yet resolved

BAD: [`master` at 2c2fac29ebc](https://jenkins.mono-project.com/view/Per-commit%20packages/job/build-package-osx-mono/job/master/608/)
BAD: [`2018-02` at 28c171a](https://jenkins.mono-project.com/view/Per-commit%20packages/job/build-package-osx-mono/job/2018-02/57/)

(Both of these builds include the changes from <https://github.com/mono/mono/pull/7293>.)

**Comment by baulig** [comment]
The objective of #7293 was not to fix this issue, but merely a coincidence when working on something else.

**Comment by akoeplinger** [comment]
Let's reopen this then :)

**Comment by baulig** [comment]
Fix incoming -> work-week-09.

**Comment by baulig** [comment]
https://github.com/mono/mono/pull/7358
