### ISSUE TITLE
RuntimeInformation.IsOSPlatform(OSPlatform.OSX) returns true on iOS

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#7203]
## Steps to Reproduce

1. Execute the following on iOS:

```csharp
Console.WriteLine (RuntimeInformation.IsOSPlatform(OSPlatform.OSX));
```

and it prints `true`.

An improvement would be to at least make `RuntimeInformation.IsOSPlatform(OSPlatform.Create("iOS"))` return true.

tvOS and watchOS have the same issue.

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] iOS

**Comment by migueldeicaza** [comment]
Proposed this API, once we get it, we can do the Mono and Unity changes:

https://github.com/dotnet/corefx/pull/27378

**Comment by akoeplinger** [comment]
This is fixed in modern .NET for iOS.
