### ISSUE TITLE
Need to no longer depend on `/etc/mono/registry` when mono is not installed (running an mkbundle'd app)

### ISSUE THREAD

**Issue by nddipiazza** [mono/mono#7231]
We use `mkbundle` to build mono applications so that our customers without mono installed can use it. The whole point of this is to avoid admins having to make changes (i.e. `sudo apt-get install mono-runtime`) to the environment to support our software. It will just download and run.

Our mkbundle command is `mkbundle --simple --static --deps -L ../packages/Microsoft.SharePointOnline.CSOM.16.1.7317.1200/lib/net45 -L ../packages/Utility.CommandLine.Arguments.1.3.0/lib -o ./bin/Debug/SharepointOnlineSecurityUtil --config /etc/mono/config --machine-config /etc/mono/4.5/machine.config ./bin/Debug/SharepointOnlineCookieFetcher.exe`

Our c# programs use `securePassword = new SecureString();`

But we constantly get hit with this issue: https://stackoverflow.com/questions/24872394/access-to-the-path-etc-mono-registry-is-denied

```
System.Security.SecurityException: No access to the given key ---> System.UnauthorizedAccessException: Access to the path "/etc/mono/registry" is denied.
```

So they have to run a sudo step to fix it:

```
sudo mkdir /etc/mono/registry

# set the right permissions using chmod

sudo chmod uog+rw /etc/mono/registry
```

Because of this, now sudo access is needed which totally defeats the purpose of the `mkbundle`! In our case, this is a deal breaker because our competition will likely have an app that does not have this need for `sudo` access during installation. 

We need to find a way for mono to more gracefully handle a /etc/mono/registry and create one in an app-data, cwd, or something else.

**Comment by marek-safar** [comment]
Could you include full exception stack trace?

However, your code requires HKLM like registry access and you can use one of existing ways to overwrite it or try to change the code

The implementation https://github.com/mono/mono/blob/03371921a180d70965e7d132ae4da9fc90785a2b/mcs/class/corlib/Microsoft.Win32/UnixRegistryApi.cs#L815 reveals way to customize it

**Comment by migueldeicaza** [comment]
MkBundle is about not requiring the Mono runtime to be installed in the system, not about virtualizing the registry.   

We could make it so that if the directory does not exist, we do not crash, I think that is worth doing, just not a trivial change.

In the meantime you can configure this with `MONO_REGISTRY_PATH` before you startup your application to point to a directory you control.

**Comment by nddipiazza** [comment]
Yep that works for now. And I can even built it into my c# app to do it for the user so it's really not a big deal.
