### ISSUE TITLE
Fast Span<T>

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7249]
We bundle portable (slow) version of Span<T> which is using [`Pinnable<T>`](https://github.com/dotnet/corefx/blob/1885cf8e6590fc7c4f48ef22a368beeb4fc1ee59/src/System.Memory/src/System/Pinnable.cs) type to do all the memory operations which is not as efficient as it could be.

We'd like to switch to CoreClr [fast](https://github.com/dotnet/coreclr/blob/6b27fa740ad44962093c5af4e6060011ec454a46/src/mscorlib/shared/System/Span.Fast.cs) implementation  which is using [`ByReference<T>`](https://github.com/dotnet/coreclr/blob/6b27fa740ad44962093c5af4e6060011ec454a46/src/mscorlib/src/System/ByReference.cs) as JIT intristic around ref T fields.

Same applies to `ReadOnlySpan<T>`.

**Comment by Therzok** [comment]
Would this mean that the NuGet version of Span would be switched to the BCL (Fast) supplied one? Or would it still be available only in modern API targets?

**Comment by Therzok** [comment]
Ah, redundant question, I'll just check if the type is TypeForwarded

**Comment by marek-safar** [comment]
@vargaz please look at the pending PR, it has the managed pieces wired-up but needs runtime icalls or a different way of implementing them. The build fails due to that right now.
