### ISSUE TITLE
make check from root

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#7252]
In discussion of making tests run incrementally, two out of two people replying answered that they gave up on make check from root. This seems like an issue.

**Comment by marek-safar** [comment]
What's the issue they hit when doing this?

**Comment by akoeplinger** [comment]
Since I was one of the two: for me it boils down to flaky tests and since you only need to hit a test failure _somewhere_ in the 40k+ tests to abort the whole run it doesn't make sense for me to run locally.

Usually you work on a specific area and know roughly the spots it will affect so you can run those tests separately and rely on PR/CI testing to assess the rest.

**Comment by jaykrell** [comment]
There is a secondary problem here -- make check from root is horrible in its logging vs. error output. There needs to be a default easy to use everyone uses it thing that splits errors out from the log -- you should get a log file with everything, and an error file with just errors and a few lines of context each, and it should be really obvious from log and error, what directory and command and environment variables issued the error.

Ok I tried make check from root. As I said, it is hard to sift through the output, but here is some that looks not right:

Test/DummyAssembly/Convertable.cs(57,16): error CS0518: Predefined type 'System.Void' is not defined or imported
Test/DummyAssembly/Convertable.cs(63,25): error CS0518: Predefined type 'System.String' is not defined or imported
Test/DummyAssembly/Convertable.cs(68,38): error CS0518: Predefined type 'System.Object' is not defined or imported
Test/DummyAssembly/Convertable.cs(68,25): error CS0518: Predefined type 'System.Boolean' is not defined or imported
Test/DummyAssembly/Convertable.cs(63,32): error CS0115: 'Convertable.ToString()': no suitable method found to override
Test/DummyAssembly/Convertable.cs(68,30): error CS0115: 'Convertable.Equals(object)': no suitable method found to override
Test/DummyAssembly/Convertable.cs(47,9): error CS0518: Predefined type 'System.Void' is not defined or imported
Test/DummyAssembly/Convertable.cs(51,29): error CS0518: Predefined type 'System.String' is not defined or imported
Test/DummyAssembly/Convertable.cs(51,42): error CS0518: Predefined type 'System.String' is not defined or imported
Test/DummyAssembly/Convertable.cs(51,9): error CS0518: Predefined type 'System.Void' is not defined or imported
Test/DummyAssembly/Convertable.cs(44,19): error CS0518: Predefined type 'System.String' is not defined or imported
Test/DummyAssembly/AnotherSerializable.cs(39,10): error CS0518: Predefined type 'System.String' is not defined or imported
Test/DummyAssembly/Convertable.cs(45,19): error CS0518: Predefined type 'System.String' is not defined or imported
Test/DummyAssembly/AnotherSerializable.cs(40,10): error CS0518: Predefined type 'System.String' is not defined or imported
m

**Comment by akoeplinger** [comment]
I don't see this issue anymore when doing a `make check -k` from the repo root and there don't seem to be any other suspicious errors other than flaky tests locally.
