### ISSUE TITLE
tailcall notes for future

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#7259]
Collecting notes for somewhat future tailcall work.

csc can emit things like:
    IL_0002:  callvirt   instance string Test.Base::AbstractOverrideNil()
    IL_0007:  stloc.0
    IL_0008:  br.s       IL_000a
    IL_000a:  ldloc.0
    IL_000b:  ret

or if you say csc -optimize:
    IL_0001:  callvirt   instance string Test.Base::VirtualOverrideNil()
    IL_0006:  ret

JIT should recognize the second and possibly the first pattern and attempt to tail call. Even without the tail prefix. 

The first pattern is somewhat generalizable in that "effectively nop" is unbounded -- a general optimization problem. Some of this this work might involve more surveying of what csc/mcs tends to emit. And surveying of people tend to use csc -optimize. The second pattern is trivial.

If these are already handled, then just add tests to assert it.

 Meta-point is that csc never outputs "tail." yet programmers might deliberately write code amenable to tail optimizations. Until/unless C#/csc are fixed, the burden is all on the JIT. C# should gain a syntax though, and then this bug can be skipped.

**Comment by marek-safar** [comment]
@jaykrell please use existing tasks for future comments like this. I moved this one to `Epic: Tail calls optimizations` myself

**Comment by jaykrell** [comment]
I wasn't sure. ok. I just wanted to make sure I had somewhere to keep notes.
