### ISSUE TITLE
Creating EnumMirror fails in a multi-domain context.

### ISSUE THREAD

**Issue by sailro** [mono/mono#7289]
[Enum mirror ctor](https://github.com/mono/mono/blob/0bcbe39b148bb498742fc68416f8293ccd350fb6/mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/EnumMirror.cs#L22) makes the wrong assumption that the enum type is in the RootDomain. 

When trying to create an enum mirror within a **Unity** context (where the majority of types are in a child domain), it results in a ArgumentException whereas all arguments are perfectly valid.

Original customer report [here](https://forum.unity.com/threads/case-1006282-vstu-using-enum-flags-displays-node-not-supported.519222/#post-3405207).

**Comment by sailro** [comment]
cc @jbevain

**Comment by jbevain** [comment]
For you attention, @vargaz @DavidKarlas

**Comment by sailro** [comment]
I confirm the patch fixes our issue. Thanks guys.
