### ISSUE TITLE
[XI]LegacyXmlSettingsAreDisabled in XMLReaderSettings failed on iOS and tvOS device

### ISSUE THREAD

**Issue by dalexsoto** [mono/mono#7302]
_From @GouriKumari on February 25, 2018 20:6_

### Steps to Reproduce

1. Update System to Xamarin.iOS d15-7 bcecd11d
2. Build and Execute System.Xml tests on iOS or tvOS device

### Expected Behavior
All tests should pass. 

### Actual Behavior
[FAIL] XmlReaderSettingsTests.LegacyXmlSettingsAreDisabled :   Expected: False

### Environment
mtouch 11.10.0.13 (d15-7: bcecd11d) . This issue was occurring  on mtouch 11.10.0.1 (d15-7: eadb8376) as well.

### Build Logs
http://xqa.blob.core.windows.net/gist/report-e67afa12d52d45ab8ae1b5d92312e3f6.txt
TestLog: http://xqa.blob.core.windows.net/gist/System.Xml-tvos10-29-1585652fd1ecb4eddd80ebefb1562b316473fa559b10-29-15-421768f5c5764af8bbd67b3d8f42781b.zip

_Copied from original issue: xamarin/xamarin-macios#3593_

**Comment by dalexsoto** [comment]
I can confirm [1] the issue @GouriKumari is seeing, it seems mono regressed https://bugzilla.xamarin.com/show_bug.cgi?id=60621

[1]:
```
	[FAIL] XmlReaderSettingsTests.LegacyXmlSettingsAreDisabled :   Expected: False
Tests run: 1890 Passed: 1889 Inconclusive: 0 Failed: 1 Ignored: 62
Test run failed
```

**Comment by marek-safar** [comment]
yeah, I didn't check that we have the file referenced from multiple sources.

**Comment by marek-safar** [comment]
It should be fixed now, please bump mono again
