### ISSUE TITLE
WebGL with Systems.Numerics?

### ISSUE THREAD

**Issue by Thaina** [mono/mono#7306]
Did or will the mono webassembly project would covering the port of WebGL?

Also I wish that we could natively bridge types in `Systems.Numerics` namespace efficiently into wasm and utilize it in webgl API. Would it possible?

**Comment by akoeplinger** [comment]
@kumpera any comment on the question?

**Comment by kumpera** [comment]
That's a great idea!

I definitely think System.Numerics.Vectors to map to the in-discussion support for simd in WebAssembly.

Beyond that, we should make the WebGL binding work as smoothly with existing dotnet types.

**Comment by alexanderkyte** [comment]
I think this is a great idea. Webgl offers better performance than many non-Nvidia-based toolkits like OpenCL. A number of high-profile open source JS compute libraries are out there:
http://gpu.rocks/
https://tenso.rs/#readmore

It would be compelling to see a similar APIs made. In fact, this motivated me a while ago to look into using GPU acceleration for System.Numerics, expecting OpenCL to be easier to get working initially than WebCL. After a half hour of work, I came to the realization that while the copy-in and copy-out semantics for System.Numerics are perfect for the GPU data copying, our fixed-length vectors are very tiny if we plan to implement this in a generic way. 

I think we may want to consider an arbitrary-sized System.Numerics extension for the GPU-based interface we end up going with.

**Comment by akoeplinger** [comment]
Do we want to use this issue for tracking that work or is there a better place?

**Comment by akoeplinger** [comment]
Since there doesn't seem to be anything actionable in the short term I'm going to close this issue for now.

**Comment by kumpera** [comment]
I filed an enhancement issue about this so we don't forget: https://github.com/mono/mono/issues/7662

**Comment by Thaina** [comment]
Does we already have webgl api in mono?
