### ISSUE TITLE
Mono 5.10 release notes

### ISSUE THREAD

**Issue by cesarnava** [mono/mono#7311]
Hi.

Yesterday they published Mono 5.10, however they did not publish the release notes.

What are they? What's new?

## Steps to Reproduce

1. Go to http://www.mono-project.com/download/stable (There you can see version 5.10)
2. Go to http://www.mono-project.com/docs/about-mono/releases/5.10.0 (not exist).
3. 

### On which platforms did you notice this

[X] macOS
[X] Linux
[X] Windows

**Version Used**:

**Comment by luhenry** [comment]
Fixed by https://github.com/mono/website/pull/354

**Comment by akoeplinger** [comment]
I'd also like to apologize that we didn't have the release notes available when we pushed the release, we'll make sure this doesn't happen again :)
