### ISSUE TITLE
Incorrect step over in debugger, test ShouldCorrectlyStepOverOnExitFromArgsAfterStepInMethodParameter

### ISSUE THREAD

**Issue by mfilippov** [mono/mono#7326]
## Steps to Reproduce

1. Run test ShouldCorrectlyStepOverOnExitFromArgsAfterStepInMethodParameter

## Current Behavior
Test fail
## Expected Behavior
Test pass

**Comment by akoeplinger** [comment]
The test is already disabled (marked as `[Category("NotWorking")]`) so I'm assuming this is a tracking issue to get it fixe/reenabled.

**Comment by mfilippov** [comment]
@akoeplinger You right. I created this issue for tracking the problem.

**Comment by mfilippov** [comment]
@thaystg Thank you for the fix!
