### ISSUE TITLE
suggest recursive self-calls do not create trampoline

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#7328]
suggest this to test later: 
```
mono_resolve_patch_target:
	case MONO_PATCH_INFO_METHOD_JUMP:

+		// When a function is calling itself (recursively), skip the trampoline.
+		if (method == patch_info->data.method)
+			return code;

		target = mono_create_jump_trampoline (domain, patch_info->data.method, FALSE, error);
		if (!mono_error_ok (error))
			return NULL;
```
It works asis. The trampoline is almost immediately patched out and never ever executed.

**Comment by alexrp** [comment]
cc @vargaz

**Comment by jaykrell** [comment]
I suspect there is actually a missing cooperative GC poll in this case in the current code -- though it is somewhat degenerate. The test just calls itself recursively forever doing nothing else.

.assembly extern mscorlib { }

.assembly a { }

.class b
{
.method static !!f1 f1<f1>() noinlining
{
tail. call !!0 b::f1<!!0>()
ret
}


.method static int32 f2<f2>() noinlining
{
tail. call int32 b::f2<!!0>()
ret
}

.method static void f3<f3>() noinlining
{
tail. call void b::f3<!!0>()
ret
}

.method static void main()
{
.entrypoint
newobj instance void [mscorlib]System.Object::.ctor()
pop
//call !!0 b::f1<object>()
//call int32 b::f2<object>()
//pop
call void b::f3<int32>()
ret
}

}

**Comment by vargaz** [comment]
Looks ok, please post a PR.

**Comment by jaykrell** [comment]
This is a tangent to more important stuff I'm debugging, wanted to leave notes.

**Comment by jaykrell** [comment]
ok, will do.

**Comment by jaykrell** [comment]
Are polling points supposed to be inserted today, or only if cooperative GC is enabled?
You currently get a right loop with no polling.

```
0:000> uf .
Flow analysis was incomplete, some code may be missing
0000016c`3c951420 55              push    rbp
0000016c`3c951421 488bec          mov     rbp,rsp
0000016c`3c951424 4883ec20        sub     rsp,20h
0000016c`3c951428 488b0424        mov     rax,qword ptr [rsp]
0000016c`3c95142c 48894510        mov     qword ptr [rbp+10h],rax
0000016c`3c951430 488b442408      mov     rax,qword ptr [rsp+8]
0000016c`3c951435 48894518        mov     qword ptr [rbp+18h],rax
0000016c`3c951439 488b442410      mov     rax,qword ptr [rsp+10h]
0000016c`3c95143e 48894520        mov     qword ptr [rbp+20h],rax
0000016c`3c951442 488b442418      mov     rax,qword ptr [rsp+18h]
0000016c`3c951447 48894528        mov     qword ptr [rbp+28h],rax
0000016c`3c95144b 488d6500        lea     rsp,[rbp]
0000016c`3c95144f 5d              pop     rbp
0000016c`3c951450 49bb2014953c6c010000 mov r11,16C3C951420h
0000016c`3c95145a 41ffe3          jmp     r11


.assembly extern mscorlib { }

.assembly a { }

.class b
{

.method static void f3<f3>() noinlining
{
tail. call void b::f3<!!0>()
ret
}

.method static void main()
{
.entrypoint
call void b::f3<int32>()
ret
}

}
```

**Comment by jaykrell** [comment]
Heh, the next case looks similar and already does this -- probably for recursive self-call vs. self-tail.call.
