### ISSUE TITLE
Change OSName to return WebAssembly

### ISSUE THREAD

**Issue by kumpera** [mono/mono#7344]
Change corlib to return WebAssembly so user code can detect when running on the web.

**Comment by morganbr** [comment]
This would be a good thing to keep in sync between Mono and CoreRT. Currently, the CoreRT build calls the OS "WebAssembly" and the architecture "wasm". What's Mono doing?

**Comment by akoeplinger** [comment]
The API additions are in review at https://github.com/dotnet/corefx/issues/27417, the OSPlatform string for wasm is currently `WEBASSEMBLY` there.

Mono doesn't return those yet.

**Comment by kumpera** [comment]
Both are good names so I see absolutely no reason to deviate from what CoreRT picked.

**Comment by kumpera** [comment]
@morganbr did you guys figured out a way to handle the multiple deployment environments that WASM can be deployed to?

I think users will want to distinguish between wasm on browsers and wasm on node, for example.

**Comment by morganbr** [comment]
Interesting point...  CoreRT  hasn't yet hit a point where there's an interesting difference between different browsers or Node, but I could certainly see that being useful. Have you seen a case where the runtime/framework should do anything different or did you just want to expose something about it from ```Environment```?.

**Comment by kumpera** [comment]
@morganbr yes, this is particularly relevant for BCL coverage. node.js will have working FS API's for example.

**Comment by kumpera** [comment]
This was fixed by a recent PR.
