### ISSUE TITLE
Where is 5.10.0.140 release on github?

### ISSUE THREAD

**Issue by mfilippov** [mono/mono#7360]
I try to find the point in the repository which used for build 5.10.0.140. I see it release on mono-project.com but not see any tag or release on the GitHub.

**Comment by akoeplinger** [comment]
@directhex let's use this issue to track adding tagging to the Jenkins release process.

**Comment by directhex** [comment]
OK. I'll manually tag the "missing" versions, and I'll add tagging to Jenkins. Tim says it won't break the publisher if a tag already exists at his end.

**Comment by directhex** [comment]
OK, all missing 5.10 branch tags pushed, and in theory, the tarball job reconfigured to create & push a tag; and to run CDN invalidation on `http://download.mono-project.com/sources/mono/`

**Comment by mfilippov** [comment]
@akoeplinger @directhex Great thanks!

**Comment by directhex** [comment]
(Last night's tags are missing, for dumb reasons)
