### ISSUE TITLE
watchOS/LLVM crashes at launch on device

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#7364]
## Steps to Reproduce

1. Run any watchOS project in release mode (i.e. with LLVM enabled) on device (debug works fine).

Small test project I've used:  [mono-watchos-llvmissue.zip](https://github.com/mono/mono/files/1770830/mono-watchos-llvmissue.zip)

2. Something like this shows up in the Application Output:

    2018-02-28 14:13:57.840 MinimalisticWatchAppExtension[282:101894] *** Terminating app due to uncaught exception 'System.InvalidOperationException', reason: 'Could not execute the method because the containing type is not fully instantiated.'
    *** First throw call stack:
    (0x21074363 0x207231c3 0x491c23 0x492003 0x496e9f 0xfee7b 0x20bc8567)
    libc++abi.dylib: terminating with uncaught exception of type NSException

Unfortunately it seems watchOS doesn't produce crash reports for SIGABRT, so there's no crash report.

However, running with lldb I was able to get a stack trace and some info: https://gist.github.com/rolfbjarne/302a97bc805f7dc16364565d414704e4

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] watchOS

**Version Used**:

xamarin-macios/master: xamarin/xamarin-macios@27e757e45e14336f78ea7ef79355df727f8d28f6
xamarin-macios/d15-7: xamarin/xamarin-macios@0181ac3daa554ceba5b329c7e15a1d066c41cbe6

[VSTS](https://devdiv.visualstudio.com/DevDiv/Default/_workitems/edit/574329)

**Comment by rolfbjarne** [comment]
CC @spouliot (this is a blocker for d15-7)

**Comment by vargaz** [comment]
Testcase:
<<<<<<<<<<<<<<<<
using System;
using System.Collections.Generic;

public static class Program {
    public static int Main () {
		var map1 = new Dictionary <Type, IntPtr> (EqualityComparer<Type>.Default);
		var object_map = new Dictionary <IntPtr, WeakReference> (EqualityComparer<IntPtr>.Default);
		return 0;
	}
}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
