### ISSUE TITLE
WeakAttribute causes all fields within a class to become weak

### ISSUE THREAD

**Issue by dalexsoto** [mono/mono#7378]
Using `[WeakAttribute]` in Xamarin.iOS @ [7d9208](https://github.com/xamarin/xamarin-macios/commit/7d92085edd0a8e91a908ecb28fd8f9a20ef0c2cb) (d15-7 branch) seems to be marking all fields within a class as `Weak`, it just takes the mere presence of `[Weak]` on any field even if the field is unused. 

## Steps to Reproduce

1. Open `RetainCycles.sln` and open `ProblematicViewController.cs`
2. Observe `[Weak]` is not used inside `MyButton` class

```csharp
public class MyButton : UIButton {

	UIViewController strong;
	// TODO: Uncomment to avoid leaking
	// This field is unused
	//[Weak] UIViewController weak;

	public MyButton (UIViewController parent)
	{
		strong = parent;
	}
}
```

3. Build and instrument the app, click `Present VC` and `Close` multiple times
4. Observe memory grows exponentially on instruments while clicking `Present VC` and `Close` multiple times

<img width="996" alt="screen shot 2018-03-01 at 5 50 00 pm" src="https://user-images.githubusercontent.com/204671/36876150-2c5d13d8-1d79-11e8-8f65-ecb382735772.png">

5. Uncomment `[Weak] UIViewController weak;` field

```csharp
public class MyButton : UIButton {
	UIViewController strong;
	// TODO: Uncomment to avoid leaking
	// This field is unused
	[Weak] UIViewController weak;

	public MyButton (UIViewController parent)
	{
		strong = parent;
	}
}
``` 

6. Build and instrument the app, click `Present VC` and `Close` multiple times
7. Observe memory **does not** grow exponentially on instruments while clicking `Present VC` and `Close` multiple times

<img width="994" alt="screen shot 2018-03-01 at 6 02 48 pm" src="https://user-images.githubusercontent.com/204671/36876465-cb8ee3ea-1d7a-11e8-822b-67a68041fb7d.png">

Test case: [RetainCycles.zip](https://www.dropbox.com/s/ummk18eo9up8v7u/RetainCycles.zip?dl=0)

## Current Behavior

`[Weak]` seems to make all fields weak.

## Expected Behavior

`[Weak]` should only make weak the decorated field.

### On which platforms did you notice this

- [x] iOS

**Version Used**:

As for xamarin-macios we are using mono @ 3f4f070 and my installed mono is:

```
Mono JIT compiler version 5.10.0.105 (2017-12/4b1745401d5 Mon Feb 12 18:13:56 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

**Comment by marek-safar** [comment]
@vargaz why is this happening?

**Comment by VincentDondain** [comment]
I can reproduce this with the following environment: https://gist.github.com/VincentDondain/50ce75f917781ac27ba565b2b5379f75

I saw the memory leak and can confirm that uncommenting `[Weak] UIViewController weak;` as suggested fixes the issue.

**Comment by spouliot** [comment]
@vargaz was this back ported to 2017-12 ? because that's where the issue was reported and needs to be fixed :)

**Comment by vargaz** [comment]
Its in progress.

**Comment by vargaz** [comment]
The fix should be in the 2017-12 branch now.
