### ISSUE TITLE
Run a build with `--enable-checked-build=private_types` on PRs

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#7438]
Hopefully we will have the [Extract the getter/setter + assertion + leveled init for MonoClass](https://github.com/mono/mono/issues/6925) project far enough along that all of the runtime code will be using `MonoClass` getter functions soon.

We will need a Jenkins job that runs on PRs and just compiles the runtime with `--enable-checked-build=private_types` in order to ensure that we're using getters everywhere.

I don't think we'd need to run the tests in this configuration - just compile the C code.  (Ideally, compile with `make -k` so we can see all the compilation errors not just the first one).

**Comment by lambdageek** [comment]
We set up a job here: https://jenkins.mono-project.com/view/Pull%20requests/job/test-mono-pull-request-amd64-checked-build/

Waiting on #7802

**Comment by luhenry** [comment]
Done and verified with https://github.com/mono/mono/pull/7802
