### ISSUE TITLE
PInvoke to function that takes a struct with an array of double gets incorrect results on Android

### ISSUE THREAD

**Issue by brianradunity** [mono/mono#7449]
## Steps to Reproduce

This issue was discovered by a Unity user running a Mono player on an Android device.  When calling the DLLImport function defined below on Android, the native function receives incorrect data.

Source code for native function is located here: https://github.com/Gobra/UAM_Params/tree/master/source/cpplib-1.0

This corresponds to Unity issue: https://issuetracker.unity3d.com/issues/android-mono-dllimport-function-doesnt-receive-passed-parameters

c# code calling native function:

```csharp
[Serializable]
[StructLayout(LayoutKind.Sequential)]
public struct Rectangle
{
	public int X;
	public int Y;
	public int Width;
	public int Height;
		
	public Rectangle(int x, int y, int width, int height)
	{
		X = x;
		Y = y;
		Width = width;
		Height = height;
	}
}

[Serializable]
public struct Scalar
{
	public double Val0;
	public double Val1;
	public double Val2;
	public double Val3;

	public Scalar(double v0, double v1, double v2, double v3)
	{
		Val0 = v0;
		Val1 = v1;
		Val2 = v2;
		Val3 = v3;
	}
}

/// <summary>
/// DllExports
/// </summary>
internal static class Native
{
	[DllImport("CppLib", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
	[return: MarshalAs(UnmanagedType.LPStr)]
	public static extern string binding(IntPtr ptr, Rectangle rect, Scalar color, int thickness, int lineType, int shift);
}
 public static void main()
{
    string formatted = Native.binding(IntPtr.Zero, new Rectangle(10, 10, 100, 20), new Scalar(32, 64, 128, 256), 1, 2, 3);
}
```

## Current Behavior

Return string is:
"ptr, {10, 10, 100, 20 }, color = { 0.0, 0.0, 0.0, 0.0 }, 2, 3, 0"

## Expected Behavior

The output string of the above native.binding() call should be:
"ptr, { 10, 10, 100, 20 }, color = { 32.0, 64.0, 128.0, 256.0 }, 1, 2, 3"

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] Android

**Version Used**:

recent master

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by EgorBo** [comment]
Why is [StructLayout(LayoutKind.Sequential)] missing on `Scalar`?

**Comment by joncham** [comment]
Sequential is default for structs AFAIK.

**Comment by joncham** [comment]
`To reduce layout-related problems associated with the Auto value, C#, Visual Basic, and C++ compilers specify Sequential layout for value types.` 

https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.layoutkind(v=vs.110).aspx

**Comment by EgorBo** [comment]
@joncham correct, I was wondering if there any "Explicit" was defined  🙂 
I can not reproduce this issue on arm64-v8a, Google Pixel 2, Xamarin.Android 8.1.5.0
it returns the expected "ptr, { 10, 10, 100, 20 }, color = { 32.0, 64.0, 128.0, 256.0 }, 1, 2, 3" for me

**Comment by joncham** [comment]
Can you try ARMv7? I believe the issue was there.

**Comment by EgorBo** [comment]
@joncham reproduces on armeabi-v7a

**Comment by lewurm** [comment]
Could this be an ABI issue?  I can't reproduce on a "pure" linux-gnueabihf system.

To be honest, I don't see quite through the ABI mess on ARM. (Fun sidenote: Throwing several keywords at Google led me to a post by @alexrp http://blog.alexrp.com/2014/02/18/android-hard-float-support/ looks like he's been there as well 😄 ).

Could you play around with the `__attribute__((pcs("aapcs")))`/`__attribute__((pcs("aapcs-vfp")))` on the `binding` function in your native lib?

Have a look at the disassembly: 
```c
struct Scalar4 {
       double val[4];
};

__attribute__((pcs("aapcs-vfp")))
double
mono_return_struct_4_double_hard (struct Scalar4 sc4)
{
    return sc4.val[1];
}

__attribute__((pcs("aapcs")))
double
mono_return_struct_4_double_soft (struct Scalar4 sc4)
{
    return sc4.val[1];
}
```

`gcc -c -O2` gives me this:
```
00000000 <mono_return_struct_4_double_hard>:
   0:   eeb0 0b41       vmov.f64        d0, d1
   4:   b088            sub     sp, #32
   6:   b008            add     sp, #32
   8:   4770            bx      lr
   a:   bf00            nop

0000000c <mono_return_struct_4_double_soft>:
   c:   b084            sub     sp, #16
   e:   e88d 000f       stmia.w sp, {r0, r1, r2, r3}
  12:   e9dd 0102       ldrd    r0, r1, [sp, #8]
  16:   b004            add     sp, #16
  18:   4770            bx      lr
  1a:   bf00            nop
```

I can see how this doesn't work.

**Comment by lewurm** [comment]
Ok, my hunch in my previous comment was wrong: `doubles` _inside_ structs have nothing to do with the ABI differences between hardfp, softfp and soft. That said, it's still a horrible mess, and the difficult part was to reproduce the issue on a non-android system. I was able to reproduce the issue on `arm-linux-gnueabi`, also known as `armv5`, which assumes `softfp`. I couldn't get `softfp` working on a `armv7` Linux system.

The situation on Android is a bit different: Even on `armv7` everything is compiled `softfp`. So that was the source of my confusion.

A PR for the `struct` fix will follow shortly.
