### ISSUE TITLE
w32handles require much memory when the minimum required is much lower

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#7460]
## Steps to Reproduce

1. Create an iOS project from a template, run on device and profile memory using Instruments.

## Current Behavior

mono_w32handle_init allocates 256kb of memory for its `private_handles`.
 
![screenshot 2018-03-07 16 17 54](https://user-images.githubusercontent.com/249268/37100392-1ea28986-2223-11e8-8cf5-455f220891fd.png)

## Expected Behavior

Less memory allocated by default.

Running with lldb and putting a breakpoint on `mono_w32handle_new*` shows that only a [single handle is created](https://gist.github.com/rolfbjarne/2a1bfb71f62dc9c3256bbba13e04bab3).

IMHO allocating 256kb to have space for 8 million handles sounds a bit excessive for this scenario.

This is a problem for some iOS extensions, where the OS enforces a low memory limit (10MB in some cases).

Maybe this could be implemented as something that grows dynamically instead?

**Comment by marek-safar** [comment]
This got worse with #4856

/cc @luhenry

**Comment by luhenry** [comment]
This is already implemented as something that grows dynamically (or we would have to allocate 8M * `sizeof(void*)` -> 64MB). It is implemented as a `MonoW32Handle[32768][256]`, so what we can easily do is rebalance the values to `MonoW32Handle[2048][4096]`, this will lower the basic memory usage to 16k.

**Comment by rolfbjarne** [comment]
@luhenry actually this made it worse.

The private_handles array now only takes 16kb, but the first entry inside it takes 544 kb:

![screenshot 2018-03-08 12 05 48](https://user-images.githubusercontent.com/249268/37148021-39b278b6-22c9-11e8-8c52-5e947b5d7b08.png)

**Comment by luhenry** [comment]
The best we can do to tweak these 2 values is `SLOT_MAX = 11942` and `HANDLE_PER_SLOT = 702`, giving us a memory consumption of ~186KiB for 1 handle.

**Comment by luhenry** [comment]
After some more work, we can do `SLOT_MAX = 2896` and `HANDLE_PER_SLOT = 2896` for a memory consumption of ~45KiB for 1 handle.

**Comment by luhenry** [comment]
Took a linked-list approach at https://github.com/mono/mono/pull/7508 as suggested by @rolfbjarne

**Comment by rolfbjarne** [comment]
I've confirmed the second fix is working fine.

@luhenry would it be possible to backport it to 2018-02 so that we could get it in d15-8?
