### ISSUE TITLE
`NullReferenceException` when trying to use an extension method on a `null` object as an assignment value for an `Action` or `Func` variable

### ISSUE THREAD

**Issue by brendanzagaeski** [mono/mono#7472]
## Regression status: regression caused by  https://github.com/mono/mono/commit/1cfd52452a4af3fd6eee32f45a8067926af8479e 

@lewurm completed confirmation and verification testing for this issue using the test case from a corresponding [Developer Community report](https://developercommunity.visualstudio.com/content/problem/209531/null-reference-exception-on-no-subscribers-action.html):

- Good: Current Mono `2017-10` branch plus a cherry-pick of the changes from <https://github.com/mono/mono/pull/5833>. Those changes were a follow-up fix for the changes that introduced the regression: <https://github.com/mono/mono/pull/5404>.
- Bad: Current Mono `2017-10` branch. (Mono framework version 5.8.0.108 (2017-10/9aa78573ee2).)

In short, https://github.com/mono/mono/pull/5833 needs to be backported to the `2017-10` branch for inclusion in the Mono desktop framework as well as a new `d15-6-2017-10` branch for inclusion into [xamarin-macios](https://github.com/xamarin/xamarin-macios) and [xamarin-android](https://github.com/xamarin/xamarin-android). (The extra `d15-6-2017-10` branch is needed to avoid forcing the Xamarin SDKs to take <https://github.com/mono/mono/pull/7444>.)

## Steps to reproduce

Build and run the following program (minimized from the test case in the Developer Community report):

```csharp
using System;

static class Program
{
	static event Action SomeEvent;

	static void Main (string [] args)
	{
		Foo (SomeEvent.ExtensionMethod);
	}

	static void Foo (Action action)
	{
	}
}

public static class Extensions
{
	public static void ExtensionMethod (this Action action)
	{
	}
}
```

### Additional notes

- It is not required to use `Action` for the extension method. The issue affects _any_ extension method. For example:

    ```csharp
    using System;
    
    static class Program
    {
    	static void Main (string [] args)
    	{
    		Class1 class1 = null;
    		Foo (class1.ExtensionMethod);
    	}
    
    	static void Foo (Action action)
    	{
    	}
    }
    
    public class Class1 {
    }
    
    public static class Extensions
    {
    	public static void ExtensionMethod (this Class1 class1)
    	{
    	}
    }
    ```

- A similar automated test was also committed alongside the fix in <https://github.com/mono/mono/commit/77b4cd11d1d7c7b79c426ddc5a343b373a3b2cc3>.

## Current Behavior

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
  at Program.Main (System.String[] args) [0x00003] in /Users/Shared/src/Program.cs:8 
```

## Expected Behavior

With Mono framework version 5.4.1.7 (2017-06/e66d9abbb27), the program completes with no exceptions.

## Additional testing environment info (brief)

macOS 10.12.6
US English locale

### On which platforms did you notice this

\[x\] macOS
\[ \] Linux
\[ \] Windows

**Comment by brendanzagaeski** [comment]
Trying to assign the extension method to an `Action` variable (rather than trying to pass it to `Foo()`) is also sufficient to hit the problem:

```csharp
using System;

static class Program
{
	static event Action SomeEvent;

	static void Main (string [] args)
	{
		Action action = SomeEvent.ExtensionMethod;
	}
}

public static class Extensions
{
	public static void ExtensionMethod (this Action action)
	{
	}
}
```

**Comment by luhenry** [comment]
The PR to backport to 2017-10 and d15-6-2017-10 have been created.

**Comment by brendanzagaeski** [comment]
Non-public work items to track inclusion of the fix into Visual Studio 2017:

- xamarin-android: <https://devdiv.visualstudio.com/DevDiv/_workitems?id=578437>
- xamarin-macios: <https://devdiv.visualstudio.com/DevDiv/_workitems?id=578437>

**Comment by luhenry** [comment]
It's been merged into XA and XI.
