### ISSUE TITLE
Update Xamarin platforms APIs in standard repo

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7496]
We need to update https://github.com/dotnet/standard/tree/master/platforms with the latest dev15-7 preview as we are missing types which will need to be type-forwarded.

**Comment by akoeplinger** [comment]
Not sure I understand, netstandard.dll didn't add any new APIs so we shouldn't be missing any of those?

**Comment by marek-safar** [comment]
This is not about netstandard but we are reusing this repo for any nugets which are part of corefx

**Comment by akoeplinger** [comment]
so we have a separate repo/script that takes this repo and checks which APIs are missing from those additional nugets?

**Comment by marek-safar** [comment]
We don't and there is no repo to check against as this is our API. When there is a new API and the same API exists in corefx nuget (like Span<T>) it needs to type-forward but when building such nuget they need a type to forward to which they get from our API descriptor in standard repo
