### ISSUE TITLE
[XA] Cannot find FSharp.Core or one of its dependencies during testing

### ISSUE THREAD

**Issue by luhenry** [mono/mono#7511]
`Xamarin.Android.Build.Tests.AndroidUpdateResourcesTest.CheckResourceDesignerIsCreated.Xamarin.Android.Build.Tests.AndroidUpdateResourcesTest.CheckResourceDesignerIsCreated` is failing for the `mono:2018-02` integration

The exception is the following:

```
/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Error executing task GenerateResourceDesigner: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Error executing task GenerateResourceDesigner: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at System.CodeDom.Compiler.CodeDomProvider.CreateGenerator (System.IO.TextWriter output) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.CodeDom/src/System/CodeDom/Compiler/CodeDomProvider.cs:123 
  at Xamarin.Android.Tasks.GenerateResourceDesigner.WriteFile (System.String file, System.CodeDom.CodeTypeDeclaration resources, System.String language, System.Boolean isFSharp, System.Boolean isCSharp) [0x0012a] in /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs:217 
  at Xamarin.Android.Tasks.GenerateResourceDesigner.Execute () [0x0065b] in /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs:155 
  at Microsoft.Build.BuildEngine.TaskEngine.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/TaskEngine.cs:134 
  at Microsoft.Build.BuildEngine.BuildTask.Execute () [0x0008d] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/BuildTask.cs:101 
```

Logs:
https://jenkins.mono-project.com/job/xamarin-android-pr-builder/2618/testReport/junit/Xamarin.Android.Build.Tests.AndroidUpdateResourcesTest/CheckResourceDesignerIsCreated/Xamarin_Android_Build_Tests_AndroidUpdateResourcesTest_CheckResourceDesignerIsCreated_False_FSharp____Debug/
https://jenkins.mono-project.com/job/xamarin-android-pr-builder/2618/testReport/junit/Xamarin.Android.Build.Tests.AndroidUpdateResourcesTest/CheckResourceDesignerIsCreated/Xamarin_Android_Build_Tests_AndroidUpdateResourcesTest_CheckResourceDesignerIsCreated_True_FSharp____Debug/

/cc @jonpryor 

https://github.com/mono/mono/issues/6842 https://github.com/xamarin/xamarin-android/pull/1289

**Comment by lewurm** [comment]
not sure if it's related, but the F# version we ship got bumped three weeks ago on the `2018-02` branch: https://github.com/mono/mono/commit/ba542c0b1ec97975bc147f2f044ad38bb078525f

**Comment by jonpryor** [comment]
@lewurm: It's possible. Note from the stack trace that it's in `System.CodeDom`. The problem is that the stack trace doesn't actually make sense: assuming that "system mono" is based on mono/2018-02 (fair?), the last stack frame is at:

https://github.com/mono/corefx/blob/e327d2855ed74dac96f684797e4820345297a690/src/System.CodeDom/src/System/CodeDom/Compiler/CodeDomProvider.cs#L123

However, that `CodeDomProvider.CreateGenerator(System.IO.TextWriter)` method simply calls the *`abstract`* `CreateGenerator()` overload, which *presumably* has been overridden...but where?

The stack trace doesn't entirely make sense.

Ignoring that bit of weirdness, we *should* be using the [`FSharp.Compiler.CodeDom` NuGet package](https://www.nuget.org/packages/FSharp.Compiler.CodeDom/), which has a reference on `FSharp.Core.dll` v4.3.1.0:

```bash
$ monodis --assemblyref packages/FSharp.Compiler.CodeDom.1.0.0.1/lib/net40/FSharp.Compiler.CodeDom.dll 
AssemblyRef Table
1: Version=4.0.0.0
	Name=mscorlib
	Flags=0x00000000
	Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
2: Version=4.0.0.0
	Name=System
	Flags=0x00000000
	Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
3: Version=4.3.1.0
	Name=FSharp.Core
	Flags=0x00000000
	Public Key:
0x00000000: B0 3F 5F 7F 11 D5 0A 3A 
4: Version=4.0.0.0
	Name=System.Core
	Flags=0x00000000
	Public Key:
0x00000000: B7 7A 5C 56 19 34 E0 89 
```

That's presumably where 4.3.1.0 is coming form.

---

Perhaps, then, the fix is for Xamarin.Android to also package and distribute `FSharp.Core.dll` alongside `FSharp.Compiler.CodeDom.dll`

**Comment by marek-safar** [comment]
I think @jonpryor investigation makes sense.

FSharp.Compiler.CodeDom references 4.3.1 but we now ship only 4.4.1 version which breaks the dependency as the assemblies are signed. The problem is that there is no newer nuget version of FSharp.Compiler.CodeDom available.

@dsyme @nosami could you help?

**Comment by marek-safar** [comment]
@jonpryor the suggested workaround is to reference also correct FSharp.Core and not assume the system one is the right one.

Could you add FSharp.Core 4.3.3 package (it should be added automatically as FSharp.Compiler.CodeDom reference but that's a different bug) ?

**Comment by marek-safar** [comment]
Could you guys decide which of you is going to work on this issue?

**Comment by nosami** [comment]
We haven't needed FSharp.Compiler.CodeDom for Android for about 18 months now. It could be removed.

Recompiling an old app would then break, but would only require minor fix ups. Any app created in the last 18 months would be unaffected.

**Comment by jonpryor** [comment]
@marek-safar asked:

> Could you add FSharp.Core 4.3.3 package

[*This* FSharp.Core 4.3.3 package](https://www.nuget.org/packages/FSharp.Core/4.3.3)? I don't see how that would fix the problem:

```bash
$ curl -o fsharp.core.4.3.1.nupkg https://az320820.vo.msecnd.net/packages/fsharp.core.4.3.1.nupkg
$ unzip  fsharp.core.4.3.1.nupkg lib/netstandard1.6/FSharp.Core.dll
$ monodis --assembly lib/netstandard1.6/FSharp.Core.dll
Assembly Table
Name:          FSharp.Core
Hash Algoritm: 0x00008004
Version:       4.4.3.0
Flags:         0x00000001
PublicKey:     BlobPtr (0x00002175)
	Dump:
0x00000000: 00 24 00 00 04 80 00 00 94 00 00 00 06 02 00 00 
0x00000010: 00 24 00 00 52 53 41 31 00 04 00 00 01 00 01 00 
0x00000020: 07 D1 FA 57 C4 AE D9 F0 A3 2E 84 AA 0F AE FD 0D 
0x00000030: E9 E8 FD 6A EC 8F 87 FB 03 76 6C 83 4C 99 92 1E 
0x00000040: B2 3B E7 9A D9 D5 DC C1 DD 9A D2 36 13 21 02 90 
0x00000050: 0B 72 3C F9 80 95 7F C4 E1 77 10 8F C6 07 77 4F 
0x00000060: 29 E8 32 0E 92 EA 05 EC E4 E8 21 C0 A5 EF E8 F1 
0x00000070: 64 5C 4C 0C 93 C1 AB 99 28 5D 62 2C AA 65 2C 1D 
0x00000080: FA D6 3D 74 5D 6F 2D E5 F1 7E 5E AF 0F C4 96 3D 
0x00000090: 26 1C 8A 12 43 65 18 20 6D C0 93 34 4D 5A D2 93 
Culture:       
```

Note that the 4.3.3 NuGet package bundles FSharp.Core v4.4.3.

We need 4.3.1.

"Interestingly", the [FSharp.Core 4.3.1 NuGet Package](https://www.nuget.org/packages/FSharp.Core/4.3.1) *also* has an assembly version of 4.4.3, and I have not yet found a NuGet package which *does* provide FSharp.Core 4.3.1 (though I'm still looking...).

**Comment by jonpryor** [comment]
From the "have I lost my sanity (again?)" department, [FSharp.Core 4.0.0.1](https://www.nuget.org/packages/FSharp.Core/4.0.0.1) has an assembly version of 4.4.0.0.

Apparently I need to use [FSharp.Core 3.1.2.5](https://www.nuget.org/packages/FSharp.Core/3.1.2.5) in order to get an assembly version of 4.3.1.0. (?!)

**Comment by dsyme** [comment]
All these are binary compatible, so you just use the latest (4.3.4) with
a binding redirect.

On Sat, Mar 17, 2018, at 1:15 AM, Jonathan Pryor wrote:
> From the "have I lost my sanity (again?)" department, FSharp.Core
> 4.0.0.1[1] has an assembly version of 4.4.0.0.> Apparently I need to use FSharp.Core 3.1.2.5[2] in order to get an
> assembly version of 4.3.1.0. (?!)> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 

Links:

  1. https://www.nuget.org/packages/FSharp.Core/4.0.0.1
  2. https://www.nuget.org/packages/FSharp.Core/3.1.2.5
  3. https://github.com/mono/mono/issues/7511#issuecomment-373882809

**Comment by nosami** [comment]
I don't think a binding redirect can be used here, as it's for an msbuild task.

**Comment by luhenry** [comment]
Fixed by https://github.com/xamarin/xamarin-android/pull/1440
