### ISSUE TITLE
[XI/XM] Failing ShouldStripMonoPosixHelper test

### ISSUE THREAD

**Issue by luhenry** [mono/mono#7516]
`Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper` is failing for the `mono:2018-02` integration.

The errors are the following:

```
MESSAGE:
Release lipo usage did not match expectations
  Expected: True
  But was:  False

+++++++++++++++++++
STACK TRACE:
  at Xamarin.MMP.Tests.CodeStrippingTests.StripTestCore (Xamarin.MMP.Tests.TI+UnifiedTestConfig test, System.Boolean debugStrips, System.Boolean releaseStrips, System.String libPath, System.Boolean shouldWarn) [0x000a3] in <25f0b5cecc4f4d2794901c6faa0ed902>:0
  at Xamarin.MMP.Tests.CodeStrippingTests+<>c__DisplayClass7_0.<ShouldStripMonoPosixHelper>b__0 (System.String tmpDir) [0x00013] in <25f0b5cecc4f4d2794901c6faa0ed902>:0
  at Xamarin.MMP.Tests.MMPTests.RunMMPTest (System.Action`1[T] test, System.String directoryName) [0x00008] in <25f0b5cecc4f4d2794901c6faa0ed902>:0
  at Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper (System.Nullable`1[T] strip, System.Boolean debugStrips, System.Boolean releaseStrips) [0x00023] in <25f0b5cecc4f4d2794901c6faa0ed902>:0
```

```
MESSAGE:
System.IO.FileNotFoundException : Could not find file "/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/xharness/tmp-test-dir/mmptest/bin/Debug/tmp-test-dir/Xamarin.MMP.Tests.MMPTests.RunMMPTest8/bin/Release/UnifiedExample.app/Contents/MonoBundle/libMonoPosixHelper.dylib"
+++++++++++++++++++
STACK TRACE:
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <5ecad466620a4909b22e1f6fd8639281>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <5ecad466620a4909b22e1f6fd8639281>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.OpenRead (System.String path) [0x00000] in <5ecad466620a4909b22e1f6fd8639281>:0 
  at Xamarin.Tests.MachO.GetArchitectures (System.String file) [0x00007] in <25f0b5cecc4f4d2794901c6faa0ed902>:0 
  at Xamarin.MMP.Tests.CodeStrippingTests.AssertStrip (System.String libPath, System.Boolean shouldStrip) [0x00001] in <25f0b5cecc4f4d2794901c6faa0ed902>:0 
  at Xamarin.MMP.Tests.CodeStrippingTests.StripTestCore (Xamarin.MMP.Tests.TI+UnifiedTestConfig test, System.Boolean debugStrips, System.Boolean releaseStrips, System.String libPath, System.Boolean shouldWarn) [0x000cc] in <25f0b5cecc4f4d2794901c6faa0ed902>:0 
  at Xamarin.MMP.Tests.CodeStrippingTests+<>c__DisplayClass7_0.<ShouldStripMonoPosixHelper>b__0 (System.String tmpDir) [0x00013] in <25f0b5cecc4f4d2794901c6faa0ed902>:0 
  at Xamarin.MMP.Tests.MMPTests.RunMMPTest (System.Action`1[T] test, System.String directoryName) [0x00008] in <25f0b5cecc4f4d2794901c6faa0ed902>:0 
  at Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper (System.Nullable`1[T] strip, System.Boolean debugStrips, System.Boolean releaseStrips) [0x00023] in <25f0b5cecc4f4d2794901c6faa0ed902>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <5ecad466620a4909b22e1f6fd8639281>:0 
```

Logs:
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/6652/testReport/junit/Xamarin.MMP.Tests/CodeStrippingTests/ShouldStripMonoPosixHelper_null_False_True_/
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/6652/testReport/junit/Xamarin.MMP.Tests/CodeStrippingTests/ShouldStripMonoPosixHelper_True_True_True_/
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/6652/testReport/junit/Xamarin.MMP.Tests/CodeStrippingTests/ShouldStripMonoPosixHelper_False_False_False_/

/cc @spouliot @chamons 

https://github.com/mono/mono/issues/6842 https://github.com/xamarin/xamarin-macios/pull/3402

**Comment by marek-safar** [comment]
@chamons what is this testing? Are we bundling less that we should?

**Comment by chamons** [comment]
I've been discussing this with Bernhard over slack to help him figure out what's going on.

These are the three failing tests:

Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper(null,False,True): Release lipo usage did not match expectations
Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper(True,True,True): Release lipo usage did not match expectations
Xamarin.MMP.Tests.CodeStrippingTests.ShouldStripMonoPosixHelper(False,False,False): System.IO.FileNotFoundException : Could not find file "/Users/builder/data/lanes/5929/a7abab1c/source/xamarin-macios/tests/xharness/tmp-test-dir/mmptest/bin/Debug/tmp-test-dir/Xamarin.MMP.Tests.MMPTests.RunMMPTest8/bin/Release/UnifiedExample.app/Contents/MonoBundle/libMonoPosixHelper.dylib"

All do is test the behavior of this commit: https://github.com/xamarin/xamarin-macios/commit/ca4360116c24aa847f707dad9d7f1d2fb46834b4#diff-e40760bb0940f9688afc05144e54811d

I've suggested (via chat) to modify the assert like this:

Assert.AreEqual (releaseStrips, DidAnyLipoStrip (buildOutput), "Release lipo usage did not match expectations:\n" + buildOutput);

so we can see the full build output and what's missing.

I am a bit shocked that libMonoPosixHelper.dylib isn't being copied in, as that's a behavior in mmp that I didn't expect to be broken by a mono bump.

It's hard to speculate more without seeing the build log.

I've kicked off a build of the branch but that'll be a few hours until I can poke at it locally. If someone can get me the modified test output sooner I'll take a look.

-- Chris H


________________________________

**Comment by lewurm** [comment]
Output for `StripTestCore (true, true, true)`:
https://gist.github.com/lewurm/b4d03b1935e6a4d9ac48537db4c526be

The line
```
xcrun -sdk macosx lipo /Users/[...]/MonoBundle/libMonoPosixHelper.dylib -thin x86_64 -output \
  /Users/[...]/Contents/MonoBundle/libMonoPosixHelper.dylib
```
is indeed missing in the `2018-02` case. Why? 🙂

**Comment by lewurm** [comment]
conclusion so far:
https://github.com/xamarin/xamarin-macios/blob/b242afc8aa72092869bfd95c0610fcdcb31bab9d/tools/mmp/driver.cs#L816

this line contains `libMonoPosixHelper` on `master` (with `2017-12`), but it isn't included in `mono-2018-02` (with `2018-02`).

**Comment by chamons** [comment]
There appears to be at least one behavior change in the linker because 

https://github.com/xamarin/xamarin-macios/blob/master/tools/mmp/driver.cs#L816

is returning this

**mono branch**
```{[ole32.dll, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/usr/lib/libSystem.dylib, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/Security.framework/Security, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/usr/lib/libobjc.dylib, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/Foundation.framework/Foundation, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[oleaut32.dll, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/Carbon.framework/Versions/Current/Carbon, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[__Internal, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}```

**master**
```{[ole32.dll, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/usr/lib/libSystem.dylib, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/usr/lib/libc.dylib, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/usr/lib/libobjc.dylib, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/Foundation.framework/Foundation, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/Security.framework/Security, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[__Internal, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[oleaut32.dll, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/Carbon.framework/Versions/Current/Carbon, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[MonoPosixHelper, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[libc, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}
{[/System/Library/Frameworks/CoreServices.framework/Frameworks/CFNetwork.framework/CFNetwork, System.Collections.Generic.List`1[Mono.Cecil.MethodDefinition]]}```

**Comment by chamons** [comment]
Since MonoPosixHelper isn't being returned, we don't process it, nor we do strip it, thus the test failure.

I am :( that is the only test that caught this.

**Comment by chamons** [comment]
I added https://github.com/xamarin/xamarin-macios/issues/3713 to note we need to beef up test coverage here.

@rolfbjarne FYI on the Linker issue ^

**Comment by rolfbjarne** [comment]
If the linker linked away any references to `MonoPosixHelper`, then in theory `libMonoPosixHelper.dylib` shouldn't be needed at runtime.

**Comment by lewurm** [comment]
The C# code of the test in `ShouldStripMonoPosixHelper` is:
```csharp
using Foundation;
using AppKit;

namespace TestCase
{
        class MainClass
        {
                static void Main (string[] args)
                {
                        NSApplication.Init ();
                        System.IO.File.Create("/Users/lewurm/work/2018-02/xamarin-macios/tests/mmptest/bin/Debug/tmp-test-dir/Xamarin.MMP.Tests.MMPTests.RunMMPTest/3890657d-d351-4914-a44b-e0a3d701bf10").Dispose();
                }
        }
}
```
maybe that's not enough to drag in `libMonoPosixHelper.dylib`?

**Comment by chamons** [comment]
So we bundle in libMonoPosixHelper since a number of BCL assemblies (Mono.Posix.dll and System.dll) depend upon it.

**Comment by chamons** [comment]
So reviewing the test code, it appears we're only testing Modern (this is a bug and I filed https://github.com/xamarin/xamarin-macios/issues/3723) but we're also only failing on Release.

This might be a behavior change (improvement) that is causing the test to fail. If previously we'd always unconditionally ship libMonoPosixHelper even in release, and now the linker is smarter, we'd not even bundle it, and thus not lipo it.

**Comment by chamons** [comment]
I'd like @rolfbjarne opinion, but if my logic is right we should add test that force a usage of libMonoPosix (it looks like CreateZStream should force it) and then file an issue for me to extend the tests to include a "if there is no code forcing libMonoPosix then lipo must run in Full and file must not exist in Modern).

Thoughts?

**Comment by rolfbjarne** [comment]
@chamons sounds like a plan!

**Comment by marek-safar** [comment]
@chamons could you take over this issue and check if it's an issue at all?

**Comment by chamons** [comment]
Yes, I'll run this down, after I sort out the regression in master I just reverted (this week).

**Comment by chamons** [comment]
@marek-safar - I've pushed https://github.com/xamarin/xamarin-macios/commit/9cb27becd2b072197a4f1a09c75d6b237dc2ee12 which fixes the test case locally.

I want to rewrite/improve the test, but no reason to do that in an integration branch. That's just asking for conflict hell.

**Comment by lewurm** [comment]
Thank you @chamons!
