### ISSUE TITLE
Consider reviving the Cecil-based ilasm/ildasm

### ISSUE THREAD

**Issue by alexrp** [mono/mono#7523]
The subject of two past GSoC projects was a rewrite of our `ilasm` tool to use Cecil instead of PEAPI, and also to write an `ildasm` tool based on Cecil to replace `monodis`. Now that we're shipping `ikdasm`, the `ildasm` replacement is probably not something we'd want to pursue anymore, but there would probably still be value in replacing `ilasm` so we can get rid of PEAPI.

The results of those GSoC projects exist in these branches:

* https://github.com/alexrp/mono/commits/ilasm-cecil
* https://github.com/mbartnic/mono/commits/ilasm-cecil

The `ilasm` rewrite happens to come with a test suite that would be nice to somehow integrate even on its own: https://github.com/alexrp/mono/tree/ilasm-cecil/mcs/ilasm/tests

To actually complete these replacements, we'd need at least some of the Cecil issues described here to be addressed: https://github.com/jbevain/cecil/issues/161

**Comment by marek-safar** [comment]
We don't want to do it.

We have ikdasm which is managed disassembler compatible with ildasm and monodis

For ilasm we'd prefer to port corert ilasm which is full featured ilasm instead

**Comment by jaykrell** [comment]
I was wondering that myself -- port CoreCLR ilasm and ildasm?
ikdasm fails with all F# output.

**Comment by marek-safar** [comment]
please report ikdasm issues, they should be easy to fix.
ilasm is different matter where we are missing many features and it's more complex, it this case makes more sense trying to port https://github.com/dotnet/coreclr/tree/master/src/ilasm first
