### ISSUE TITLE
F# test in profiler stress tests is broken

### ISSUE THREAD

**Issue by alexrp** [mono/mono#7527]
This is recent breakage:

* https://jenkins.mono-project.com/job/test-mono-mainline-linux-profilerstress-x86-x64/label=high-mem-ubuntu-1404-amd64/736/testReport/junit/MonoTests/profiler-stress/fsharp/
* https://jenkins.mono-project.com/job/test-mono-mainline-linux-profilerstress-x86-x64/label=high-mem-ubuntu-1404-i386/736/testReport/junit/MonoTests/profiler-stress/fsharp/
* https://jenkins.mono-project.com/job/test-mono-mainline-profilerstress/label=osx-amd64/235/testReport/junit/MonoTests/profiler-stress/fsharp/
* https://jenkins.mono-project.com/job/test-mono-mainline-profilerstress/label=osx-i386/235/testReport/junit/MonoTests/profiler-stress/fsharp/

According to Jenkins, It's caused by one of these commits:

* Provide compile-tests-parallel that honors the command line so e.g. (commit: ab67bcf)
* [Tailcall] Do not create never-executed trampoline for tail.call self. (commit: 8e4f0d8)
* [System]: WebRequestStream now throws correct exception on cancellation (commit: c2bf82f)
* [Tailcall] tail.callvirt support for AMD64 JIT (#7426) (commit: b4ee861)
* Fix generated file when passing --bundled-header (#6736) (commit: e0f8597)
* [interp] Fix runtime invoke of pinvoke method (commit: 940f2d1)
* [interp] Fix detection of pinvoke call (commit: 4ad92ef)
* [interp] Fix pinvoke from dynamic methods (commit: ccbb873)
* [jit] Move the check for open constructed types later in (commit: c745a95)
* [eglib] Fix typo in g_assertf (#7458) (commit: 660e166)

**Comment by alexrp** [comment]
cc @jaykrell @vargaz @BrzVlad

**Comment by jaykrell** [comment]
It isn't ab6.
I didn't want 8e4 commited yet.
Given the break is on i386, b4e isn't likely, but sure seems relevant I agree.
The rest I cannot speak to.
Is the test easily runnable locally, or has useful output? I'll check the links.

**Comment by BrzVlad** [comment]
interp code is not reached in those tests

**Comment by jaykrell** [comment]
How do I run this? I can try undoing some of the changes and test.

**Comment by alexrp** [comment]
```
$ cd acceptance-tests
$ make check-profiler-stress MONO_PROFILER_STRESS_REGEX=fsharp MONO_PROFILER_STRESS_SEED=1381020 MONO_PROFILER_STRESS_DEBUG=true
```

**Comment by jaykrell** [comment]
I expect to revert 8e4 tonight or tomorrow.

**Comment by jaykrell** [comment]
The test ran a while for me locally without evident problem.

**Comment by alexrp** [comment]
Looks like there is more breakage of F# on ARM:

* https://jenkins.mono-project.com/job/test-mono-mainline-linux-profilerstress-arm/label=debian-9-armel/128/
* https://jenkins.mono-project.com/job/test-mono-mainline-linux-profilerstress-arm/label=debian-9-armhf/128/

Note `fsharp` and `ironjs-sunspider` both crashing due to trampoline issues.

**Comment by jaykrell** [comment]
There is a PR to revert 8e4f0d8.
https://github.com/mono/mono/pull/7550

**Comment by jaykrell** [comment]
That is done now. Please keep an eye out and let me know and I'll try same.

**Comment by alexrp** [comment]
Still broken: https://jenkins.mono-project.com/job/test-mono-mainline-linux-profilerstress-x86-x64/label=high-mem-ubuntu-1404-amd64/742/testReport/MonoTests/profiler-stress/fsharp/

**Comment by akoeplinger** [comment]
The problematic commit for https://github.com/mono/mono/issues/7558 was https://github.com/mono/mono/pull/7426, I assume the same applies here.

**Comment by alexrp** [comment]
This looks to be fixed.
