### ISSUE TITLE
new object [int.MaxValue] crashes runtime instead of OOM

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#7537]
## Steps to Reproduce
```
var array1 = new object [Int32.MaxValue];
var array2 = new object [Int32.MaxValue];
//add more arrays if needed :)
```
Alternative way to reproduce the issue:
```
var list = new SortedList();
list.Capacity = Int32.MaxValue;
```
## Current Behavior

mono-sgen.exe has stopped working

## Expected Behavior

`OutOfMemoryException`

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:

mono-master 5.13

**Comment by filipnavara** [comment]
64-bit or 32-bit?

**Comment by EgorBo** [comment]
@filipnavara 64 bit

**Comment by EgorBo** [comment]
So it looks like it reproduces only on Windows x64, other platforms are fine.
Doesn't reproduces on non-concurent GC (`MONO_GC_PARAMS=major=marksweep`).

**Comment by marek-safar** [comment]
@BrzVlad does it sound familiar?

**Comment by BrzVlad** [comment]
@EgorBo I can't reproduce this. I assume you have over 16GB Ram, so allocation succeeds but it crashes somewhere else ? Can you provide a stacktrace ?

**Comment by EgorBo** [comment]
@BrzVlad I've just tested your fix - it works! 🙂
