### ISSUE TITLE
Extend the WASM sample to include C#->JS call

### ISSUE THREAD

**Issue by kumpera** [mono/mono#7548]
The current sample shows how to do very primitive JS->C# calls, it should be extended to include examples of how to go in the other direction.

**Comment by ChristianWeyer** [comment]
Which example are you referring to @kumpera ?

**Comment by kumpera** [comment]
This one here: https://github.com/mono/mono/blob/master/sdks/wasm/sample.html
Or something better to distribute.

**Comment by akoeplinger** [comment]
Done by https://github.com/mono/mono/pull/10847
