### ISSUE TITLE
AppDomain.ProcessExit has a different behavior with .NET Core

### ISSUE THREAD

**Issue by hjc4869** [mono/mono#7552]
## Steps to Reproduce

1. Compile the following program (test.cs) using mono mcs and dotnet core tools
```csharp
using System;

class Program
{
    static void Main()
    {
        AppDomain.CurrentDomain.ProcessExit += (s, e) =>
        {
            Console.WriteLine("Exiting!");
        };

        System.Threading.Thread.Sleep(-1);
    }
}
```

2. Run the program and send a SIGTERM to the process using "kill" command 
3. Check the output

## Current Behavior

When running the program using .NET Core, the "ProcessExit" event fires.

```
~ dotnet run
Exiting!
```

While mono does not handle the signal at all

```
~ mono test.exe
[1]    20267 terminated  mono test.exe
```

## Expected Behavior

The behavior of mono should be close to what .NET Core do.

### On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**: Mono JIT compiler version 5.10.0.140 (tarball Sat Feb 24 15:44:56 UTC 2018)

**Comment by radical** [comment]
@alexanderkyte Kumpera mentioned that you had a PR for this. And the fact that .netcore has this behavior would be useful for that. Considering that, I am removing myself from this issue.

**Comment by jaykrell** [comment]
I'm thinking of taking this but let me think about it more..
