### ISSUE TITLE
Update Facades list in XA/XI linker steps

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#7573]
We need to update [XA](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/Mobile.Tuner/MobileProfile.cs) and [XI](https://github.com/xamarin/xamarin-macios/blob/master/tools/linker/MobileProfile.cs) linker steps with the new facades from https://github.com/mono/mono/pull/7541.

Also the [XA assemblies](https://github.com/xamarin/xamarin-android/blob/34f437d97d6d5f56d684af99449de49b870b32cc/build-tools/mono-runtimes/ProfileAssemblies.projitems) list.

**Comment by marek-safar** [comment]
We should report this to products as different issues. They need to add only 2

- System.Resources.Reader.dll
- System.Resources.Writer.dll

as no such nugets which would use them exist today and we didn't tell CoreFX to update them this is no pressing issue right now but

**Comment by akoeplinger** [comment]
@marek-safar the products have tests that verify they recognize all facades as SDK assemblies so those would start failing, that's why I added this to the products integration milestone.

**Comment by akoeplinger** [comment]
This was done.
