### ISSUE TITLE
Missing KeyValuePair::Create method

### ISSUE THREAD

**Issue by wcoder** [mono/mono#7576]
## Steps to Reproduce

1. Look at [mono KeyValuePair](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/collections/generic/keyvaluepair.cs)
2. Look at [coreclr KeyValuePair](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Collections/Generic/KeyValuePair.cs#L14)

## Current Behavior

Missing `Create` method.

## Expected Behavior

Method `Create` exists.

### On which platforms did you notice this

[x] Android

**Version Used**:
```
mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
```

### Stacktrace

```
error MSB4018: Mono.Linker.MarkException: Error processing method: 
'System.Collections.Generic.KeyValuePair`2<System.String,System.String> TestApp.Droid.Services.XHttpClient/<>c::
<PrepareResponse>b__10_0(System.Collections.Generic.KeyValuePair`2<System.String,System.Collections.Generic.IEnumerable`1<System.String>>)' in assembly: 'TestApp.Droid.dll' ---> 
Mono.Cecil.ResolutionException: 
Failed to resolve System.Collections.Generic.KeyValuePair`2<!!0,!!1> System.Collections.Generic.KeyValuePair::Create(!!0,!!1)
```

**Comment by rjvdboon** [comment]
Note: The static KeyValuePair class is not defined in .Net Standard 2.0, it is only in .Net Core 2.0.

**Comment by marek-safar** [comment]
You cannot use netcore library with Xamarin Android. You need to compile it with again netstandard or XA

**Comment by wcoder** [comment]
@rjvdboon I use Xamarin Android Class Library

**Comment by akoeplinger** [comment]
We're already using the CoreFX version of KeyValuePair.cs so the Create() method should show up as soon as a Xamarin.Android version includes that change.

@wcoder I do see it in Xamarin.Android API 8.3.0-3 for example.

**Comment by marek-safar** [comment]
@wcoder could you attach full repro where you hit the issue?
