### ISSUE TITLE
Visual Studio 15.6.1 regression Android.Util.AndroidRuntimeException Activity did not call through to super.onCreate()

### ISSUE THREAD

**Issue by jalbertSyncroTech** [mono/mono#7577]
Cross posted to Xamarin.Android and Xamarin.Forms
https://github.com/xamarin/xamarin-android/issues/1399
https://github.com/xamarin/Xamarin.Forms/issues/2081

We have a Xamarin.Forms Android app that was previously working with VS 15.5.7 and is no longer working with VS 15.6.1.  It crashes during startup with the unhandled exception AndroidRuntimeException: Activity did not call through to super.onCreate().

Our activity does override OnCreate(), and we've verified via the debugger that the base.OnCreate() is being called.  However, the Xamarin.Forms FormsAppCompatActivity that Android applications are supposed to sub-class also overrides OnCreate(), so if it's just overriding that causes the issue everyone using Xamarin.Forms should be seeing this.

This is currently a show-stopper for our development team.

### Steps to Reproduce

1. Upgrade from VS 15.5.7 or earlier to 15.6.1
2. Android Application crashes at startup with the unhandled exception AndroidRuntimeException: Activity did not call through to super.onCreate()

### Expected Behavior

App should not crash, it was previously working with 15.5.7.

### Actual Behavior

App crashes, this is a regression.

### Version Information

Visual Studio 15.6.1
Xamarin.Android SDK   8.2.0.15 (HEAD/22d97e153)
Xamarin.Forms 2.5.0.280555 (also w/Xamarin.Forms 2.4.0.280)

### Log File

Call Stack
0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
0x6 in Android.Runtime.UncaughtExceptionHandler.UncaughtException	C#
0x1A in Java.Lang.Thread.IUncaughtExceptionHandlerInvoker.n_UncaughtException_Ljava_lang_Thread_Ljava_lang_Throwable_	C#
0x1D in object.9a1fd30c-e995-4621-8122-35964d969409	C#

**Comment by akoeplinger** [comment]
This is most certainly a Xamarin.Forms/Xamarin.Android problem so I'm going to close this one to avoid duplication, please follow the other issue(s).
