### ISSUE TITLE
MerpConfig is not initialized

### ISSUE THREAD

**Issue by migueldeicaza** [mono/mono#7592]
## Steps to Reproduce

This pul request (and the backport):

https://github.com/mono/mono/pull/7451

Do not initialize the config variable, so the enabled flag might contain garbage, and we probe this regardless of Enable/Disable calls to telemetry.

I expect this to incorrectly call MERP, for non-VSMac uses.
https://github.com/mono/mono/pull/7451

**Comment by alexrp** [comment]
C global variables are zero-initialized.
