### ISSUE TITLE
Custom MarshalAs attributes are not included in ParameterInfo objects retrieved via reflection

### ISSUE THREAD

**Issue by Nihlus** [mono/mono#7615]
## Steps to Reproduce

1. Create a method with an attribute decorated with the `MarshalAs` attribute.
2. Use reflection to retrieve a `MethodInfo` instance, and then a `ParameterInfo` instance corresponding to the attribute.
3. Inspect the `CustomAttributes` property.
4. Observe that the `MarshalAs` attribute is not included in the collection.

-- alternatively --

1. Compile the [provided minimal test case][1] using `csc Program.cs` (substituting `Program.cs` for the filename you saved the source as)
3. Execute the test case using `mono Program.exe` (substituting `Program.exe` for the output filename)
2. Observe the output of the application. You should see an output similar to the following:

```
Custom attribute count: 0
Running on Mono.
Type of value in internal field: MarshalAsAttribute
```

## Current Behavior
In the current development version of Mono, `MarshalAs` attributes are not included in the collection assigned to `CustomAttributes`  property. Instead, they are present as an instance of the attribute, assigned to a private field (`marshalAs`).

## Expected Behavior
The `MarshalAs` attribute should be included in the collection assigned to the `CustomAttributes` property, as is the behaviour on the .NET Framework and .NET Core.

### On which platforms did you notice this

-[ ] macOS
-[x] Linux ([System Information][2])
-[ ] Windows

**Version Used**:
```
Mono JIT compiler version 5.10.0.170 (tarball Sat Mar 10 09:49:08 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

```

[1]: https://hastebin.com/subovodode.cs
[2]: https://gist.github.com/400659620841d3e1a96b792e52b00841

**Comment by lambdageek** [comment]
The example call the getter of the `S.R.E.ParameterInfo.CustomAttributes` property which ultimately ends up in `MonoCustomAttrs.GetCustomAttributesData` which doesn't look like it picks up the pseudo custom attributes from the `ICustomAttributeProvider`.

(Note that the other methods in `MonoCustomAttrs` such as `GetCustomAttributes` do eventually call `GetCustomAttributesBase` which calls `GetPseudoCustomAttributes` which delegates back to the custom attribute provider - and `ParameterInfo.GetPseudoCustomAttribute()` does copy over the `MarshalAs` property).

Not sure if this is a regression or if we never had this working.

**Comment by marek-safar** [comment]
We are missing handling for all pseudo attributes when using CustomAttributeData. We need to build separate way how to build them as re-using CustomAttribute is expensive. The way to do it is just start at top with cloning https://github.com/mono/mono/blob/9805cda80fd0d56b452854bbfef1784ebd59b7bf/mcs/class/corlib/System/MonoCustomAttrs.cs#L72-L96 to work with CustomAttributeData
