### ISSUE TITLE
DrawToBitmap in Control.cs does not work

### ISSUE THREAD

**Issue by arj3090** [mono/mono#7620]
## Steps to Reproduce

1. Use DrawToBitmap to draw a controls contents to a bitmap
2. Display the bitmap in a PictureBox

## Current Behavior
No image is drawn to a bitmap

[DrawToBitmapMonoBug.zip](https://github.com/mono/mono/files/1813883/DrawToBitmapMonoBug.zip)

## Expected Behavior
The control's contents should be drawn to the bitmap

### On which platforms did you notice this

[ ] macOS
[X] Linux (Pi3)
[ ] Windows

**Version Used**:
5.10.0.160

**Comment by filipnavara** [comment]
Will look at it.

**Comment by st-arnold** [comment]
Hello,
I noticed that this bug still exists (Mono 5.18.1.0 on Linux/RPi3) if the Control is a TableLayoutPanel container (maybe with other containers as well). The contained controls are not drawn to bitmap.

[TLPDrawToBitmapMonoBug.zip](https://github.com/mono/mono/files/2985356/TLPDrawToBitmapMonoBug.zip)
![TLPDrawToBitmap_Mono](https://user-images.githubusercontent.com/14167665/54637601-aa563300-4a91-11e9-826c-2a609afb7d7e.png)
