### ISSUE TITLE
Try to use named values instead of magic numbers "aot == 2"

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#7645]
Try to use named values instead of magic numbers "aot == 2"

	if (aot) {
		/* 
		 * For page trampolines the data is in r1, so just move it, otherwise use the got slot as below.
		 * The trampoline contains a pc-relative offset to the got slot 
		 * preceeding the got slot where the value is stored. The offset can be
		 * found at [lr + 0].
		 */
		/* See if emit_trampolines () in aot-compiler.c for the '2' */
		if (aot == 2) {
			ARM_MOV_REG_REG (code, ARMREG_V2, ARMREG_R1);
		} else {
			ARM_LDR_IMM (code, ARMREG_V2, ARMREG_LR, 0);

**Comment by luhenry** [comment]
This issue does not contain any useful information. If you ever expect anybody else than you to work on it (as you should since this is a team project), the issue should contain good information that would let anyone else than you work on it. Next time, please follow the issue template.

**Comment by luhenry** [comment]
This is way too general. Which cases should be changed? We all understand `#define` or `enum` are much better than magic numbers, but if you want that issue to be less of a complaint and more of an actionable item - by *anybody* else - you will need to give more info where you found this magic number (a dump of code helps nobody).
