### ISSUE TITLE
CheckListBox maintains check state

### ISSUE THREAD

**Issue by wardancr** [mono/mono#7664]
## Steps to Reproduce

1. Fill CheckListBox with items: CheckListBox.Items.Add(item,false)
2. Check items in CheckListBox
3. Clear CheckListBox: CheckListBox.Items.Clear()
4. Fill CheckListBox with items: CheckListBox.Items.Add(item,false)
5. Check state from line 2 is maintained even though it was cleared and Item.Count is 0 before step 4.

## Current Behavior
Check state from line 2 is maintained even though it was cleared, items were added expressly setting
check state to false and Item.Count is 0 before step 4.

## Expected Behavior
Items added in step 4 should be unchecked.

### On which platforms did you notice this

[ ] macOS
[ X] Linux (Fedora 27)
[ ] Windows

Same code under Windows 10, VS2017 produces the correct results.

**Version Used**:

Mono version: 5.10.0.160

### Stacktrace
 NA

**Comment by filipnavara** [comment]
The likely culprit are the following lines in `CheckedListBox.ObjectCollection.Add`:

```
				if (icea.NewValue != CheckState.Unchecked)
					owner.check_states[item] = icea.NewValue;
```

The state should be reset in any case.
