### ISSUE TITLE
Assertion at /Users/builder/data/lanes/5808/1c6f300e/source/xamarin-macios/external/mono/mono/profiler/log.c:546, condition `mono_lls_insert (&log_profiler.profiler_thread_list, hp, &thread->node) && "Why can't we insert the thread in the LLS?"' not met

### ISSUE THREAD

**Issue by rodrmoya** [mono/mono#7683]
This comes from Xamarin.Profiler bug https://bugzilla.xamarin.com/show_bug.cgi?id=61265

Seems there is not enough information to know why that assertion is being hit, and @alexrp mentioned there should be a better assertion in mono 5.10, so moving it here so that it gets tracked in mono.

**Comment by alexrp** [comment]
There is not much I can tell from the log in the original bug report. This assertion means that a thread wrote an event to its log buffer after it was supposed to have exited, thus reviving itself in the profiler's thread list, but never being removed. A later thread reusing the same ID would then fail to register.

Mono 5.10 and later have an assertion that catches this particular situation much earlier so we can see what kind of event that's being written is causing this.

**Comment by therealjohn** [comment]
@rodrmoya @alexrp 

I think the issue being filed here might cause it to be lost. I left a comment on the bugzilla issue that we need more info. 

Is using the latest 15.7 alpha channel in VSMac sufficient? This would have Xamarin.iOS 11.10.0.50 which is [using Mono 5.10](https://developer.xamarin.com/releases/ios/xamarin.ios_11/xamarin.ios_11.10/#Integrated_Mono_FeaturesFixes). 

Note to anyone trying this that the current 15.7 alpha does not have support for Xcode 9.3, so Xcode 9.2 would have to be used.

**Comment by rodrmoya** [comment]
No, d15-7 has the same problem, I could easily replicate it with the StarWars sample at https://github.com/MvvmCross/MvvmCross-Samples

**Comment by mikeberlin** [comment]
@alexrp I'm running into a very similar situation. The error message I receive is here:

Assertion at /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/mono/mono/profiler/log.c:546
condition `mono_lls_insert (&log_profiler.profiler_thread_list, hp, &thread->node) && "Why can't we insert the thread in the LLS?"'

I'm using Profiler to try and figure out why my app is crashing with no warning, stack trace, nor exception errors. It just crashes hard. When I open Profiler to try and diagnose further, I see the line above in the console. Let me know if I can provide any more information. I'm currently on the latest bits from the stable channel.

**Comment by spouliot** [comment]
cross-linking https://devdiv.visualstudio.com/DevDiv/_workitems/edit/599395
flagged for a 15.7 SR (hence the milestone where the fix needs to be back ported)

**Comment by marek-safar** [comment]
@luhenry is there any update on this issue?

**Comment by kumpera** [comment]
I bet this is due to XM/XI behavior of calling into mono after we detach.

**Comment by marek-safar** [comment]
@luhenry could you please resolve this issue

**Comment by luhenry** [comment]
@kumpera is already looking at the issue

**Comment by marek-safar** [comment]
@kumpera any update on the this?

**Comment by chaselal** [comment]
This happens to me every time with Xamarin.iOS 11.10.1.177 when I start the app with the Xamarin Profiler. The Xamarin Profiler console output ends with:
```
2018-05-21 08:11:14.541 MyApp[288:14030] error: * Assertion at /Users/builder/data/lanes/5944/408d3574/source/xamarin-macios/external/mono/mono/profiler/log.c:555, condition `mono_lls_insert (&log_profiler.profiler_thread_list, hp, &thread->node) && "Why can't we insert the thread in the LLS?"' not met
Xamarin.Hosting: Process '288' exited.
Application 'com.MyApp.ios.debug' terminated.
```

**Comment by kumpera** [comment]
PR with tentative fix: https://github.com/mono/mono/pull/8824

**Comment by Macjon** [comment]
I'm still having this issue while profiling a xamarin.ios app.

`error: * Assertion at /Users/builder/data/lanes/5944/64fece5f/source/xamarin-macios/external/mono/mono/profiler/log.c:555, condition `mono_lls_insert (&log_profiler.profiler_thread_list, hp, &thread->node) && "Why can't we insert the thread in the LLS?"' not met`
