### ISSUE TITLE
Remove mono_mach_get_tls_address_from_thread / mono_mach_arch_get_tls_value_from_thread?

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#7692]
As mentioned in https://github.com/mono/mono/pull/7530 the two functions no longer seem to be used. Can the code be removed altogether?

**Comment by luhenry** [comment]
If you can find no use of these functions anywhere in the code, and they are not marked as `MONO_API` (it's a clear sign it might be used elsewhere), then feel free to submit a PR that removes them. Thank you.

**Comment by kumpera** [comment]
There’s no reason to keep them around. They are part of a failed try at emulating fast TLS on OSX
