### ISSUE TITLE
Mono framework MDK fails to install on macOS High Sierra 10.13.3

### ISSUE THREAD

**Issue by khle** [mono/mono#7700]
## Steps to Reproduce

1. Update Mac to macOS High Sierra 10.13.3
2. Ensure Mac is mono-free (https://docs.microsoft.com/en-us/xamarin/cross-platform/get-started/installation/uninstalling-xamarin#uninstall-mono-sdk-mdk)
3. Download 5.10.0.179 from https://download.mono-project.com/archive/5.10.0/macos-10-universal/
4. Install and error will result.
5. Repeat step 3 for 5.10.0.178, 5.10.0.176, 5.10.0.175, etc

**Comment by filipnavara** [comment]
What error does it show you? I routinely install Mono on macOS 10.13.3 and 10.13.4 betas without an issue.

**Comment by khle** [comment]
The error has no description (meaningful)

<img width="616" alt="mono install error" src="https://user-images.githubusercontent.com/11586092/37713079-c7ceef20-2ce3-11e8-920b-0a881453e3bb.png">

**Comment by filipnavara** [comment]
Look in the menu Window -> Installer Log, or press CMD+L.

**Comment by khle** [comment]
Ah ha,

```
Mar 21 09:15:20 Kevins-MacBook-Pro-2 installd[36352]: PackageKit: ----- Begin install -----
Mar 21 09:15:37 Kevins-MacBook-Pro-2 installd[36352]: PackageKit: Install Failed: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSFilePath=/private/tmp/PKInstallSandbox.XXXXXX} {
	    NSFilePath = "/private/tmp/PKInstallSandbox.XXXXXX";
	}
Mar 21 09:15:38 Kevins-MacBook-Pro-2 Installer[47325]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Mar 21 09:15:38 Kevins-MacBook-Pro-2 Installer[47325]: Displaying 'Install Failed' UI.
Mar 21 09:15:38 Kevins-MacBook-Pro-2 Installer[47325]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

```

**Comment by filipnavara** [comment]
I am going to take a wild guess here. Does the /private/tmp folder exist on your system?

**Comment by khle** [comment]
Fixed. Only if I knew to look in the Installer log in the first place, then I would pick up the phrase "/private/tmp" is missing, then I could try to manually create that missing directory or at least be able to google for "mono install on mac missing /private/tmp".

**Comment by QuotesUK** [comment]
Installation hangs on MacOS 10.13.6, with the beach ball of death on the License step.
There aren’t any logs to report other than the Apple Crash Report.
Through Finder I was able to confirm that /Library/Frameworks/Mono.framework doesn’t exist.
