### ISSUE TITLE
System.Runtime.Intrinsics support

### ISSUE THREAD

**Issue by vargaz** [mono/mono#7711]
https://github.com/dotnet/corefx/issues/27486

- [ ] BCL API import from CoreFX
- [ ] New tests import
- [ ] Runtime support
- [ ] Nuget package inbox redirection

Briefly looking at the code, it looks like we could implement this outside of mscorlib

**Comment by kumpera** [comment]
This would make a great internship project.

**Comment by 4creators** [comment]
> This would make a great internship project.

It's way too large and complex from my experience in implementing them in coreclr

**Comment by kumpera** [comment]
Wow, it's a lot of work, I didn't check to see it.
But just adding a subset should be doable and it's worth as a way to get students exposed to mono.

**Comment by vargaz** [comment]
A large part is now implemented for netcore.
