### ISSUE TITLE
Mono doesn't recognise USB/external drive on Mac OSX10.13.3 (17D102)

### ISSUE THREAD

**Issue by rbcsky5** [mono/mono#7723]
## Steps to Reproduce

1. 
2. 
3. 

## Current Behavior

When I run an app with mono I can't locate my external drive at all. 

People here told me this is a bug of mono:
https://github.com/KSP-CKAN/CKAN/issues/2347

![image](https://user-images.githubusercontent.com/37041568/37682385-66e87b46-2cc4-11e8-8e4e-ef64fac24e7d.png)

![image](https://user-images.githubusercontent.com/37041568/37682378-61610de6-2cc4-11e8-89a5-de093311a1cf.png)

![image](https://user-images.githubusercontent.com/37041568/37682391-6c5e70b2-2cc4-11e8-9a49-653e0aeba380.png)

Similar problem can be found on this site:
https://stackoverflow.com/questions/34503898/monos-system-windows-forms-openfiledialog-wont-allow-me-to-access-usb-drive-i

## Expected Behavior

I can see my USB disk?

### On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:
5.08.0

### Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by filipnavara** [comment]
There's basically zero OS X specific code in the [Open/Save]FileDialog in Mono's System.Windows.Forms. There are internal implementation for Linux (with some KDE specific magic) and Windows. On OS X the Linux one is used and it tries to list devices from /proc/mounts and not /Volumes. The code is in the `MasterMount` class in `FileDialog.cs`.

**Comment by NattyNarwhal** [comment]
I wonder why doesn't it use `System.IO.DriveInfo`, even as a fallback?

**Comment by filipnavara** [comment]
That's a good point. It would probably make much more sense.

**Comment by luhenry** [comment]
Fixed by https://github.com/mono/mono/pull/7791
