### ISSUE TITLE
[mcs] fails to compile code with Tuple

### ISSUE THREAD

**Issue by lewurm** [mono/mono#7729]
## Steps to Reproduce

```csharp
using System.Linq;

class Program {
    public static int Main () {
        var l = (from f in (typeof (Program)).GetFields() select (name: f.Name, offset: 0)).ToList();

        return 0;
    }
}
```

## Current Behavior

```
$ mcs hmm.cs
Compilation failed: 1 error(s), 0 warnings
```
## Expected Behavior

```
$ csc hmm.cs
Microsoft (R) Visual C# Compiler version 2.6.0.62309 (d3f6b8e7)
Copyright (C) Microsoft Corporation. All rights reserved.
```
no failure.

**Version Used**:
`master`

due to this, `mcs` can't compile `mono/tests/sizeof-empty-structs.cs`

/cc https://github.com/mono/mono/pull/7722

**Comment by luhenry** [comment]
@lewurm is it acceptable for now to modify `sizeof-empty-structs.cs` to not use tuples? This is no way the fix, but that would be to unblock https://github.com/mono/mono/pull/7722
