### ISSUE TITLE
finalizer-exit.exe, finalizer-abort.exe and finalizer-thread.exe runtime tests are flaky on Windows

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#7733]
## Steps to Reproduce

1. Run finalizer-exit.exe, finalizer-abort.exe or finalizer-thread.exe on Windows
2. They are flaky

Examples:

- https://jenkins.mono-project.com/job/z/label=w32/6528/testReport/MonoTests/runtime/finalizer_exit_exe/
- https://jenkins.mono-project.com/job/z/label=w32/6522/testReport/MonoTests/runtime/finalizer_exit_exe/
- https://jenkins.mono-project.com/job/z/label=w32/6519/testReport/MonoTests/runtime/finalizer_exit_exe/
- https://jenkins.mono-project.com/job/z/label=w64/6527/testReport/MonoTests/runtime/finalizer_exit_exe/
- https://jenkins.mono-project.com/job/z/label=w64/6524/testReport/MonoTests/runtime/finalizer_exit_exe/

---

- https://jenkins.mono-project.com/job/z/label=w64/6528/testReport/MonoTests/runtime/finalizer_abort_exe/
- https://jenkins.mono-project.com/job/z/label=w64/6517/testReport/MonoTests/runtime/finalizer_abort_exe/
- https://jenkins.mono-project.com/job/z/label=w64/6513/testReport/MonoTests/runtime/finalizer_abort_exe/

---

- https://jenkins.mono-project.com/job/z/label=w64/6530/testReport/MonoTests/runtime/finalizer_thread_exe/
- https://jenkins.mono-project.com/job/z/label=w64/6520/testReport/MonoTests/runtime/finalizer_thread_exe/
- https://jenkins.mono-project.com/job/z/label=w64/6514/testReport/MonoTests/runtime/finalizer_thread_exe/

## Current Behavior

Often fails with this output on Jenkins:

finalizer-exit.exe:
```
MESSAGE:
Set ID: foo
finalizer thread ID: foo

+++++++++++++++++++
STACK TRACE:                                           
```

finalizer-abort.exe:

```
MESSAGE:
Set ID: foo
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!
finalizer thread ID: foo
Aborted!

+++++++++++++++++++
STACK TRACE:
```

finalizer-thread.exe:

```
MESSAGE:
Set ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo
finalizer thread ID: foo

+++++++++++++++++++
STACK TRACE:
```

## Expected Behavior

No failure.

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ X ] Windows

**Version Used**: master

**Comment by lewurm** [comment]
There was a fix for `finalizer-abort.exe` recently: https://github.com/mono/mono/pull/7647

@BrzVlad is this related?

**Comment by BrzVlad** [comment]
That PR fixes finalizer-abort (as far as I tested), and it is plausible that it will fix the others. As I look on the master windows job it seems we didn't have any failures since yesterday (when the PR was merged). Let's wait a few days before closing this issue.

**Comment by akoeplinger** [comment]
These seem to be fixed by https://github.com/mono/mono/pull/7647, good job @BrzVlad !
