### ISSUE TITLE
Mono Basics Documentation for HTTPS Connections test fails

### ISSUE THREAD

**Issue by mindingdata** [mono/mono#7753]
## Steps to Reproduce

1. Download and install mono
2. Go to this page : http://www.mono-project.com/docs/getting-started/mono-basics/ and follow the HTTPS connections guide to test your https connection (Essentially compiling a single .cs file)

## Current Behavior

Doesn't compile. 

```
csc tlstest.cs /r:System.dll /r:Mono.Security.dll
Microsoft (R) Visual C# Compiler version 2.6.0.62309 (d3f6b8e7)
Copyright (C) Microsoft Corporation. All rights reserved.

tlstest.cs(58,44): error CS0433: The type 'SecurityProtocolType' exists in both 'Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' and 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

## Expected Behavior

Compiles. 

### On which platforms did you notice this

[ ] Windows

**Version Used**:

Mono 5.10.0

**Comment by marek-safar** [comment]
@baulig we should remove that file if it's not useful anymore

**Comment by phoenyx08** [comment]
The same on Debian 9

**Comment by bradwitte** [comment]
You can provide an alias to get it to compile:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0433

```
$ csc tlstest.cs /r:System.dll /r:SomeNameSpace=Mono.Security.dll
Microsoft (R) Visual C# Compiler version 2.3.2.61928 (ec1cde8b)
Copyright (C) Microsoft Corporation. All rights reserved.

tlstest.cs(169,3): warning CS0618: 'ServicePointManager.CertificatePolicy' is obsolete: 'Use ServerCertificateValidationCallback instead'
tlstest.cs(199,22): warning CS0618: 'Dns.Resolve(string)' is obsolete: 'Use GetHostEntry instead'
```

**Comment by simue** [comment]
same on Ubuntu 16.04

**Comment by phoenyx08** [comment]
Brad, I found a way to compile the example just having excluded "/r:SomeNameSpace=Mono.Security.dll" from the list of parameters, but it was not the primary goal. I actually compiled the example because documentation proposed to do that in order to check that everything works.

**Comment by bradwitte** [comment]
Sure enough!  My goal was to troubleshoot problems I was having with certificate verification.

**Comment by halcyondude** [comment]
just hit this myself...the route that got me here was fiddler for linux --> install mono (to f27), and here.

**Comment by akoeplinger** [comment]
I removed the /r:Mono.Security.dll, it is no longer needed with csc instead of mcs.

**Comment by jlinkels** [comment]
I just installed Mono on Debian Jessie. 
Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:18:49 UTC 2019)
According to this page: https://www.mono-project.com/docs/getting-started/mono-basics/
I am carrying out the test to compile tlstest.cs:
csc tlstest.cs -r:System.dll
And it fails with this error message:
tlstest.cs(23,30): error CS0234: The type or namespace name 'Tls' does not exist in the namespace 'Mono.Security.Protocol' (are you missing an assembly reference?)

**Comment by fhanik** [comment]
> csc tlstest.cs -r:System.dll
And it fails with this error message:
tlstest.cs(23,30): error CS0234: The type or namespace name 'Tls' does not exist in the namespace 'Mono.Security.Protocol' (are you missing an assembly reference?)

@jlinkels 

It appears as they have moved that library into `Mono.Security.dll`

try this one

    csc tlstest.cs -r:System.dll -r:Mono.Security.dll

**Comment by jlinkels** [comment]
Yes, that works. As I am asking this question you can understand that I am an absolute beginner in Mono. Although I am Windows-free for almost 15 years now, support in the Open Source community never stops to surprise me. Neither the lack thereof with paid software. Thanks a lot for you answer!
