### ISSUE TITLE
"mono/metadata/threads.c:3016, condition `internal' not met" under certain conditions with the soft debugger attached

### ISSUE THREAD

**Issue by brendanzagaeski** [mono/mono#7786]
This report is based on [Xamarin Bugzilla Bug 61261](https://bugzilla.xamarin.com/show_bug.cgi?id=61261) and a corresponding [Developer Community report](https://developercommunity.visualstudio.com/content/problem/221192/android-application-crashing-with-condition-intern.html).

## Regression status: regression in `2017-10` starting at <https://github.com/mono/mono/commit/ce89e4c5fa46a4d8225f43339fab0b0574f81cfe>

- Bad: [xamarin/xamarin-android/master@cf185ad](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-builds-master/540/) (with mono/mono/2017-10 @ ce89e4c)
- Good: [xamarin/xamarin-android/master@34966de](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-builds-master/539/) (with mono/mono/2017-10 @ 63e8dc6)

As a rough guess, maybe the changes to `mono_thread_detach_internal()` in ce89e4c introduced an unexpected timing dependency between the calls to `mono_thread_detach_internal()` and `thread_detach()`?

The problem also happens with [xamarin/xamarin-android/master@79f3707](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-builds-master/573/) (mono/mono/2017-12 @ fbc4f05). There are some newer commits to threads.c on `2018-02` and `master`, but there are not yet CI packages of Xamarin.Android for those newer branches, so I have not yet tested with those newer changes.

## Steps to reproduce

1. `git clone https://github.com/Zebra/samples-emdkforxamarin-2_5.git`
2. `cd samples-emdkforxamarin-2_5; git checkout BarcodeSample1`
3. Connect the Zebra barcode scanner device. Make sure `adb devices` sees it.
4. Build and start debugging the app from Visual Studio. (I tested with Visual Studio for Mac.)
5. When the application UI appears, enable the **Continuous** checkbox. Then tap the **Start** button.
6. Press and release the device's hardware barcode scan trigger button a few times.

I was only able to reproduce the problem with the debugger attached.

### Additional notes

I was also able to reproduce the problem when the application was connected to the `sdb` command line debugger client. For that scenario, I replaced step 4 with the following steps:

1. Set the device to listen for TCP `adb` connections: `adb tcpip 5555`.
2. Disconnect the device's USB cable from the computer.
3. Connect to the device over TCP: `adb connect 192.168.2.2` (adjust the IP address as needed).
4. Set the soft debugger agent in the app to wait for a connection on startup: `adb shell setprop debug.mono.extra debug=192.168.2.2:12345,timeout=2000000000,loglevel=2,server=y`.
5. Build and deploy the app: `msbuild /t:Install /p:Configuration=Debug`.
6. Tap the app to start it on the device.
7. Launch `sdb-dev` and connect to the app from the `(sdb)` prompt: `connect 192.168.2.8 12345`.
8. Enable the **Continuous** checkbox, tap **Start**, and use the barcode scan trigger as before.

## Current Behavior

The application crashes after one or more clicks of the barcode scan trigger button. Here is an excerpt from the end of the `adb logcat` log:

```txt
21:56:44.761 E/mono    (11003): [0x64c94f00] Thread started, obj=0x62ae0698, tls=0x64e5cee0.
21:56:44.761 E/mono    (11003): [0x40027154] Suspended.
21:56:44.761 E/mono    (11003): [dbg] Command VM(RESUME) [92][at=fffee4c8].
21:56:44.761 E/mono    (11003): [0x64c94f00] Suspending vm...
21:56:44.761 E/mono    (11003): [0x64c94f00] Sent 1 events THREAD_START(26), suspend=2.
21:56:44.761 E/mono    (11003): [0x64c94f00] Suspended.
21:56:44.761 E/mono    (11003): [0x63802830] Resuming vm, suspend count=1...
21:56:44.771 E/mono    (11003): [dbg] Command OBJECT_REF(GET_INFO) [93][at=fffee4cb].
21:56:44.771 E/mono    (11003): [dbg]   send class [System.Threading.Thread]
21:56:44.771 E/mono    (11003): [dbg] Command THREAD(GET_NAME) [94][at=fffee4ce].
21:56:44.771 E/mono    (11003): [dbg] Command THREAD(GET_INFO) [95][at=fffee4d0].
21:56:44.771 E/mono    (11003): [dbg] Command THREAD(GET_ID) [96][at=fffee4d2].
21:56:44.781 E/mono    (11003): [dbg] Command VM(RESUME) [97][at=fffee4d5].
21:56:44.781 E/mono    (11003): [0x63802830] Resuming vm, suspend count=0...
21:56:44.781 E/mono    (11003): [0x64e67080] Resumed.
21:56:44.781 E/mono    (11003): [0x64c94f00] Resumed.
21:56:44.781 E/mono    (11003): [0x64c94f00] Suspended.
21:56:44.781 E/mono    (11003): [0x64c94f00] Resumed.
21:56:44.781 E/mono    (11003): [0x40027154] Resumed.
21:56:44.781 F/        (11003): * Assertion at /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mono/metadata/threads.c:3016, condition `internal' not met
```
[logcat.txt](https://github.com/mono/mono/files/1840049/logcat.txt)

## Expected Behavior

With [xamarin/xamarin-android/master@34966de](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-builds-master/539/), the app never crashes, even after many clicks of the scan trigger.

## Additional testing environment info (brief)

macOS 10.12.6
US English locale

Device: TC700H, Android 4.4.3

### On which platforms did you notice this

\[x\] Android
\[ \] macOS
\[ \] Linux
\[ \] Windows

**Comment by marek-safar** [comment]
@luhenry seems to be related to your changes

**Comment by dghenke** [comment]
The reported behavior appears to be unrelated to platform and/or Android version. I can reproduce it on a TC700K running Android 6.0.1, as well as a WT6000 running Android 5.1.1.

**Comment by brendanzagaeski** [comment]
Note to the Mono team: One detail I forgot to add yesterday is that as a small additional experiment I tried stress-testing a simpler scenario where I adjusted the **Stop** button event handler to call `SpawnThread()` (from [mono/tests/threads-leak.cs](https://github.com/mono/mono/blob/ce89e4c5fa46a4d8225f43339fab0b0574f81cfe/mono/tests/threads-leak.cs)) repeatedly in a loop. Unfortunately that was not sufficient to hit the problem, so the test case at the moment is still fairly specific to the Zebra sample.

**Comment by dghenke** [comment]
Additional notes:

1) The bug is easy to reproduce with the Zebra sample code, but is not specific to the Zebra EMDK and/or platforms with the Zebra scan engine. At least one user in the Xamarin Bugzilla is experiencing the same problem in an app using the Google maps API (but no Zebra stuff): https://bugzilla.xamarin.com/show_bug.cgi?id=61261#c2

2) I did open a Zebra case (ID 04000930) upon first discovering the bug. AFAIK, they stopped actively chasing it when it started looking like a problem in Mono rather than with their EMDK specifically.

**Comment by luhenry** [comment]
The issue is at https://github.com/mono/mono/blob/master/mono/metadata/threads.c#L3136: we free the gchandle without removing it from the `MonoThreadInfo` (with `mono_thread_info_unset_internal_thread_gchandle`). This then allows another thread to be allocated and then destroyed again in the meantime. The fix is to remove this `mono_gchandle_free` since we shouldn't do it anyway.

**Comment by marek-safar** [comment]
@brendanzagaeski do we really need it in 15.6 service pack?

**Comment by brendanzagaeski** [comment]
Evaluation for possible inclusion of this fix into the `d15-6` branches of the Xamarin SDKs is in-progress. Depending on the outcome of that evaluation, I will add another comment here to indicate whether to proceed with the merge into the `d15-6-2017-10` branch. Thanks!

**Comment by brendanzagaeski** [comment]
Corresponding xamarin-macios/d15-7 pull request: <https://github.com/xamarin/xamarin-macios/pull/3821>

**Comment by brendanzagaeski** [comment]
Non-public work items to track inclusion of the fix into Visual Studio:

- xamarin-android: <https://devdiv.visualstudio.com/DevDiv/_workitems?id=588246>
- xamarin-macios: <https://devdiv.visualstudio.com/DevDiv/_workitems?id=589009>
