### ISSUE TITLE
mistics bugs in application witch was built due to mono 5.10

### ISSUE THREAD

**Issue by Rombersoft** [mono/mono#7787]
## Steps to Reproduce

I've just rebuilt working source code using last 5.10 mono and begin throubles

My application works with bill validator CashCode (Canada) via ID003 protocol. After 15 hours of application working it  stoped to switch a billvalidator for accepting money. When I opened log which is related with bill validator I saw this:

![default](https://user-images.githubusercontent.com/19586466/37820547-a857ec94-2e89-11e8-89b7-e4e90bdcfeaa.png)

Than log stop to write in  this file.

I saw such "null null null null..." rarely in log when electricity was broken during writing log. But in this case electricity was not broken, moreover log of other parts of application (modem.log, printer.log, mail.log, etc) was normal and application worked but did not switch on bill validator for accepting money

Question: why have troubles happened on 5.10 mono compiler?

[ ] macOS
[*] Linux
[ ] Windows

**Version Used**:

5.10 compiler. 5.2 runtime

### Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by marek-safar** [comment]
This is highly unlikely related to 5.10 compiler. You could compare generated IL but the problem will be somewhere else which I cannot tell without more details

**Comment by Rombersoft** [comment]
I will write you when I will force it to work

**Comment by Rombersoft** [comment]
Hey guys! I know what was changed before achieving problem but I can not understand why it has happened. My application is executable with graphical interface (not console).
So my application run via autostart (.xinitrc, scripts etc) without using terminal emulator.
When I run application using such way:
```
_mainProcess = new Process();
                _mainProcess.Exited += new EventHandler(process_Exited);
                _mainProcess.EnableRaisingEvents = true;
                _mainProcess.StartInfo.FileName = "/bin/bash";
                _mainProcess.StartInfo.Arguments = "-c \"mono --debug myApp.exe  >> Logs/Watchdog/QQQ.log\"";
                _mainProcess.StartInfo.UseShellExecute = false;
                _mainProcess.StartInfo.CreateNoWindow = true;
                _mainProcess.StartInfo.RedirectStandardError = true;
                _mainProcess.StartInfo.RedirectStandardOutput = true;
                _mainProcess.OutputDataReceived += TerminalUI_OutputDataReceived;
                _mainProcess.ErrorDataReceived += TerminalUI_ErrorDataReceived;
                _mainProcess.StartInfo.WorkingDirectory = Directory.GetCurrentDirectory();
                _mainProcess.Start();
                _stopwatch.Reset();
                _stopwatch.Start();
```
that all works EXCELLENT, BUT when I run it using such way:

```
_mainProcess = new Process();
                _mainProcess.Exited += new EventHandler(process_Exited);
                _mainProcess.EnableRaisingEvents = true;
                _mainProcess.StartInfo.FileName = "/bin/bash";
                _mainProcess.StartInfo.Arguments = "-c \"mono --debug myApp.exe\"";
                _mainProcess.StartInfo.UseShellExecute = false;
                _mainProcess.StartInfo.CreateNoWindow = true;
                _mainProcess.StartInfo.RedirectStandardError = true;
                _mainProcess.StartInfo.RedirectStandardOutput = true;
                _mainProcess.OutputDataReceived += TerminalUI_OutputDataReceived;
                _mainProcess.ErrorDataReceived += TerminalUI_ErrorDataReceived;
                _mainProcess.StartInfo.WorkingDirectory = Directory.GetCurrentDirectory();
                _mainProcess.Start();
                _stopwatch.Reset();
                _stopwatch.Start();
```
that it achieves problem. Some threads begins to stop. My code has line view:
```
Console.Writeline(...);
```
for comfortable debugging. But I don't understand HOW IT CAN BE RELATED!!! Really can not application work without redirecting output when Console.WriteLine is in code? Moreover I always run this application on Win OS using second way and there it is not problem!

I'm ready to show my projects properties.
