### ISSUE TITLE
Directory.GetCurrentDirectory() returns a wrong path in several cases

### ISSUE THREAD

**Issue by Rombersoft** [mono/mono#7788]
## Steps to Reproduce

It need Linux OS. I've observed on ArchLinux
But!!! I've observed this on Windows when run application via autostart due to regedit utils

1. create console application with Directory.GetCurrentDirectory() method
2. place your application at /home/user
3. type crontab -e on terminal emulator
4. create task to start application after reboot
5. reboot computer

## Current Behavior

Directory.GetCurrentDirectory() returns "/" !

## Expected Behavior

It has to return "/home/user"

### On which platforms did you notice this

[ ] macOS
[*] Linux
[*] Windows

All versions

But when I close application and run again but manually that all works fine.

My application takes files from some folder which has relative path to it (not absolute) and if application can not define current directory that how can it define path to this some directory?

I guess that must be one universal method which defines current working directory in any conditions

**Comment by filipnavara** [comment]
You are misunderstanding what current directory is. It is NOT the directory where your application is placed.

I can open Terminal in my home directory, eg. "/Users/filipnavara/". That's what "pwd" (Print Working Directory) command will print. Then I can run "./Desktop/myapp/myapp.exe" and the current directory will still be "/User/filipnavara/" even if the application file is actually "/Users/filipnavara/Desktop/myapp/myapp.exe". It doesn't magically change to the directory where the executable file is located.

**Comment by Rombersoft** [comment]
Ok. Let it be. But why must I know Print Working Directory? Why can it be useful for me?
I want to know working directory of my application. It is useful for me!
