### ISSUE TITLE
Failure to AOT compile due to condition `load_opcode != OP_LOADV_MEMBASE' not met

### ISSUE THREAD

**Issue by mandel-macaque** [mono/mono#7792]
_From @mellinoe on March 22, 2018 7:32_

### Steps to Reproduce

1. Create a Xamarin.iOS application.
2. Add a reference to this NuGet package: https://www.nuget.org/packages/Vk/
3. Try to build

### Expected Behavior
It works.

### Actual Behavior
An error is given and compilation fails.

https://github.com/mono/mono/blob/master/mono/mini/method-to-ir.c#L14027

```
Target _CompileToNative:
    Mono Ahead of Time compiler - compiling assembly /Users/eric/projects/veldrid-samples/bin/obj/TexturedCube.iOS/iPhone/Debug/device-builds/iphone7.2-11.2.6/mtouch-cache/Build/vk.dll
    AOTID 8AB2CCE5-F2F1-F5F5-4C24-C94BC0E363F2
    * Assertion at /Users/builder/data/lanes/5944/4d8c4e32/source/xamarin-macios/external/mono/mono/mini/method-to-ir.c:14029, condition `load_opcode != OP_LOADV_MEMBASE' not met
    
    
    MTOUCH : error MT3001: Could not AOT the assembly '/Users/eric/projects/veldrid-samples/bin/obj/TexturedCube.iOS/iPhone/Debug/device-builds/iphone7.2-11.2.6/mtouch-cache/Build/vk.dll'
```
### Environment

```
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.5 Preview (7.5 build 933)
Installation UUID: b1e6ad1a-54b0-46de-8e03-9ed2a705273e
Runtime:
	Mono 5.10.0.179 (2017-12/dac60775616) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510000179

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.0-preview1-26216-03
	2.0.5
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.300-preview1-008174/Sdks
SDK Versions:
	2.1.300-preview1-008174
	2.1.4
	2.1.2
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.0.5 (Visual Studio Community)
Android SDK: /Users/eric/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.4.0.31 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.0.32 (Visual Studio Community)
Hash: 4d8c4e32
Branch: d15-7
Build date: 2018-03-07 18:39:46-0500

=== Build Information ===

Release ID: 705000933
Git revision: ace1e107c88477db1abe5e807809650f064112c4
Build date: 2018-03-19 17:42:41-04
Xamarin addins: a01263bdbba2589b1f6e42ef085bd31f6e3bfcf4
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1
```

_Copied from original issue: xamarin/xamarin-macios#3798_

**Comment by vargaz** [comment]
The vk.dll assembly seems to contain some invalid IL:

  .method public hidebysig static void  vkDebugReportMessageEXT(class Vulkan.VkInstance 'instance',
                                                                class Vulkan.VkDebugReportFlagsEXT 'flags',
                                                                class Vulkan.VkDebugReportObjectTypeEXT objectType,
                                                                uint64 'object',
                                                                native uint location,
                                                                int32 messageCode,
                                                                uint8* pLayerPrefix,
                                                                string pMessage) cil managed
  {
    // Code size       53 (0x35)
    .maxstack  9
    .locals init (class Vulkan.StringHandle V_0)
    IL_0000:  ldarg.0
    IL_0001:  ldarg.1
    IL_0002:  ldarg.2
    IL_0003:  ldarg.3
    IL_0004:  ldarg      location
    IL_0008:  ldarg      messageCode
    IL_000c:  ldarg      pLayerPrefix
    IL_0010:  ldarg      pMessage
    IL_0014:  call       class Vulkan.StringHandle Vulkan.BindingsHelpers::StringToHGlobalUtf8(string)
    IL_0019:  stloc      V_0
    IL_001d:  ldloc      V_0
    IL_0021:  ldsfld     native int Vulkan.VulkanNative::vkDebugReportMessageEXT_ptr
    IL_0026:  calli      unmanaged stdcall void(class Vulkan.VkInstance,class Vulkan.VkDebugReportFlagsEXT,class Vulkan.VkDebugReportObjectTypeEXT,uint64,native uint,int32,uint8*,string)
    IL_002b:  ldloc      V_0
    IL_002f:  call       void Vulkan.BindingsHelpers::FreeHGlobal(class Vulkan.StringHandle)
    IL_0034:  ret
  } // end of method VulkanNative::vkDebugReportMessageEXT

Note that at 0x1d, we push a Vulkan.StringHandle structure on the stack, and pass it to a method expecting 'string'.

**Comment by mellinoe** [comment]
@vargaz Thanks for the clue -- changing that allowed me to get further in my build. If this is indeed invalid IL, then it would be good to have a more actionable error message. Getting a runtime assertion here was confusing.

**Comment by vargaz** [comment]
It looks like the calli opcode is missing the signature checks that normal call opcodes have.

**Comment by vargaz** [comment]
A check was added so we will print some more useful error messages in this case.
