### ISSUE TITLE
System.Drawing.Bitmap incorrectly loads png files (without color profile?)

### ISSUE THREAD

**Issue by tyronx** [mono/mono#7821]
## Steps to Reproduce

```
Bitmap bmp = new Bitmap("in.png");
bmp.Save("out.png")
```

In file (its white): ![in](https://user-images.githubusercontent.com/762006/37864556-83ffaf8a-2f79-11e8-873a-053b6f48a869.png)
Out file: ![out](https://user-images.githubusercontent.com/762006/37864557-84228730-2f79-11e8-8009-24ed3393834d.png)

The in.png file had pngcrush (-ow -rem allb -reduce) run over it. 

## Current Behavior

As shown in out.png.

Without executing pngcrush the png files have a  "known incorrect sRGB profile" as reported by libpng 1.6+, but the pngs seem to load fine for the most part.

### On which platforms did you notice this

macOS and Linux. Not tested on Windows yet. 

**Mono Version Used**: 5.4.0.201

**Comment by filipnavara** [comment]
This was likely fixed already (with newer libgdiplus version).

**Comment by filipnavara** [comment]
Official Mono 5.10 on macOS should have new enough library versions packaged in.

**Comment by copygirl** [comment]
I can confirm that on my system this doesn't occur, while other players of the same game do have that problem. Mono version `5.8.0.108`.

**Comment by filipnavara** [comment]
We had exactly the same issue in our project with our images. Pngcrush used to produce some obscure PNGs with palette, gray-scale colours or palettes with transparency. I submitted patches to libgdiplus to fix these obscure cases, so I am reasonably sure that new enough Mono/libgdiplus has this fixed.

**Comment by marek-safar** [comment]
Please reopen if you can still reproduce it with Mono 5.10
