### ISSUE TITLE
No dark theme when running xaramin studio from `/usr/bin/monodevelop`

### ISSUE THREAD

**Issue by nddipiazza** [mono/mono#7825]
Run `/usr/bin/monodevelop`

there is no way to get a dark text editor theme which is crucial for people with eye floaters / other eye conditions. 

Am I just missing the option? 

There are themes, but none of them change the text editor's theme. Just the outer window. 

Works fine when using flatpak

**Comment by decriptor** [comment]
I think you filed this against the wrong repo? You probably want to file this against github.com/mono/monodevelop.

But, I think you are right that the dark theme is either missing or just not there on monodevelop. On mac there is a dark theme, but for now you can at the very least I believe you can change the text editor theme in preferences:

<img width="981" alt="screenshot 2018-03-25 22 07 27" src="https://user-images.githubusercontent.com/49821/37886516-0edf62ee-3079-11e8-9440-bc666eb9855b.png">

**Comment by nddipiazza** [comment]
closing - wrong repo

**Comment by nddipiazza** [comment]
OK thanks that actually fixed me up @decriptor 
I was able to use the color theme for the text editor + the theme "BlackMate" which was only available once I sudo apt-get upgraded the package to the latest.
