### ISSUE TITLE
Form.Refresh() and Form.Invalidate() + Update() not working

### ISSUE THREAD

**Issue by FalcoGer** [mono/mono#7830]
## Steps to Reproduce

1. Create new C# WinForm Project in VS Community 2017
2. Create basic window with label and button
3a. In Button code add:
```
                    for (int i = 10; i > 0; i--)
                    {
                        label1.Text = i.ToString();
                        this.Invalidate();
                        this.Update();
                        Thread.Sleep(1000);
                    }
```
3b. Alternatively:
```
                    for (int i = 10; i > 0; i--)
                    {
                        label1.Text = i.ToString();
                        this.Refresh();
                        Thread.Sleep(1000);
                    }
```
4. Run in windows, the label will count down
5. run in linux, the window freezes during the 10 second loop

## Current Behavior

The window freezes when trying to manually draw and not allowing the refresh cycle.

## Expected Behavior

The window redraws when calling Update or Refresh

### On which platforms did you notice this

[ ] macOS (Can't test)
[X] Linux (Raspberry Pi w/ latest Raspbian Stretch and mono version from repository)
[ ] Windows (Runs fine in native .Net 4.5)

**Version Used**:

4.6.2 (Debian 4.6.2.7+dfsg-1)

### Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by filipnavara** [comment]
You are using an ancient version of Mono. As far as I can tell this bug has been fixed in the X11 backend long time ago.

**Comment by akoeplinger** [comment]
Closing based upon Filip's comment above. Please reopen if you're still seeing this with a newer Mono.

**Comment by PauloDeSousa** [comment]
I am using mono 5.4.1.6 and the Invalidate does not seem to work in unix but works just fine in windows.
Filip: when was this issue fixed? which version?

**Comment by filipnavara** [comment]
@PauloDeSousa I do not have an exact version, but 5.4 was branched in August 2017 or maybe even earlier. Please test with some up-to-date release and if there is still a problem then feel free to file an issue.
