### ISSUE TITLE
Don't install monograph

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#7845]
`monograph` (https://github.com/mono/mono/tree/master/tools/monograph) is a utility that dumps a callgraph or type hierarchy information from a given assembly (in graphviz dot format).

I'm not sure who this is useful for, but this seems like a tool that ought to be built on top of IKVM or Cecil and not by embedding Mono.

We ship it, but it hasn't worked for a while because we never test it.

```
mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)
Abort trap: 6
```

Since noone complained, I assume noone uses it.  So we should stop shipping it.

**Comment by lambdageek** [comment]
The runtime crash will be fixed by https://github.com/mono/mono/pull/7836, so we can ship something that won't crash anymore.  But we shouldn't ship it at all.

**Comment by akoeplinger** [comment]
Alternatively we could add a test so we don't break it again ;)

**Comment by marek-safar** [comment]
It should be fine to stop shipping it, it's really special dev tools with no maintenance

**Comment by directhex** [comment]
It's been removed on Linux since 4.0.0 packages. https://github.com/mono/mono/pull/13699 for Windows/Mac
