### ISSUE TITLE
[SLE] NRE when using Json.NET

### ISSUE THREAD

**Issue by kumpera** [mono/mono#7852]
Test code from this issue: https://github.com/aspnet/Blazor/issues/370

Use Newtonsoft.Json and this code:

```
protected override async Task OnInitAsync()
{
    var emptyJson = "{ }";
    var json = "{ \"Summary\" : \"Value\" }";

    // all working
    Console.WriteLine($"JObject - {JsonConvert.DeserializeObject<JObject>(json)}");
    Console.WriteLine($"ExpandoObject - {JsonConvert.DeserializeObject<ExpandoObject>(json)}");
    Console.WriteLine($"Dictionary<string, object> - {JsonConvert.DeserializeObject<Dictionary<string, object>>(json)}");

    // no setter called, no problem
    Console.WriteLine($"POCO, no setters called - {JsonConvert.DeserializeObject<WeatherForecast>(emptyJson)}");

    // boom
    Console.WriteLine($"POCO, setter called - {JsonConvert.DeserializeObject<WeatherForecast>(json)}");
}
```

It show work, but we get:
```
WASM: [Newtonsoft.Json.JsonSerializationException] Error setting value to 'Summary' on 'WebApplication5.Pages.FetchData+WeatherForecast'. ---> System.NullReferenceException: Object reference not set to an instance of an object. 
WASM: at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue (System.Object target, System.Object value) <0x1cf1220 + 0x00086> in <d32db49e5e3440729da31845c03ddc3a>:0 
```

**Comment by lewurm** [comment]
It could be a bug in the interpreter. What does the definition of `WeatherForecast` look like?

**Comment by danroth27** [comment]
```c#
    public class WeatherForecast
    {
        public DateTime Date { get; set; }
        public int TemperatureC { get; set; }
        public int TemperatureF { get; set; }
        public string Summary { get; set; }
    }
```

**Comment by lewurm** [comment]
thanks @danroth27. Can't reproduce the crash on Desktop with the runtime interpreter, so it looks like it's a webassembly specific issue 😕

**Comment by danroth27** [comment]
@kumpera What's needed to further investigate this? Do you need a Blazor app that reproduces the issue?

**Comment by kumpera** [comment]
Right now, I need time, I'm going through earlier issues.

**Comment by robertsundstrom** [comment]
I encountered something similar, if not the same, with JSON.NET in SignalR Client on WebAssembly. 

I also got PlatformNotSupportedException, most likely because of JSON.NET.

**Comment by kumpera** [comment]
Working on it

**Comment by kumpera** [comment]
This is an issue with Newtonsoft.Json itself as it tries to use System.Reflection.Emit which is not supported on WebAssembly.

The large fix for this this is not exactly trivial as we lack a nuget TFM meaning library authors can't properly target WASM.

In the meanwhile, there solution is to use library builds designed to be compatible with Xamarin.iOS, which has similar limitations.

In the particular case of Newtonsoft.Json, you can add this at the beginning of your app to workaround the issue:
```
		var t = typeof (Newtonsoft.Json.Linq.JObject).Assembly.GetType ("Newtonsoft.Json.Serialization.JsonTypeReflector");
		var field = t.GetField ("_dynamicCodeGeneration", BindingFlags.NonPublic | BindingFlags.Static);
		field.SetValue(null, false);
```

**Comment by kumpera** [comment]
cc @marek-safar @mhutch

**Comment by robertsundstrom** [comment]
Thanks @kumpera, but it did not work for me. Still the same error. Is this something else?

```
WASM: System.FormatException: Invalid negotiation response received. ---> Newtonsoft.Json.JsonSerializationException: Error setting value to 'ConnectionId' on 'Microsoft.AspNetCore.Sockets.Client.HttpConnection+NegotiationResponse'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
MonoPlatform.ts:191 WASM:   at System.Reflection.Emit.DynamicMethod..ctor (System.String name, System.Type returnType, System.Type[] parameterTypes, System.Boolean restrictedSkipVisibility) <0x1cdec10 + 0x00020> in <52ecf0ed996f4cd598c50223305dbece>:0 
MonoPlatform.ts:191 WASM:   at System.Linq.Expressions.Compiler.LambdaCompiler..ctor (System.Linq.Expressions.Compiler.AnalyzedTree tree, System.Linq.Expressions.LambdaExpression lambda) <0x1cdda58 + 0x00086> in <3b87fe83b5374933a839480144f02d1e>:0 
MonoPlatform.ts:191 WASM:   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile (System.Linq.Expressions.LambdaExpression lambda) <0x1ca4d48 + 0x00016> in <3b87fe83b5374933a839480144f02d1e>:0 
MonoPlatform.ts:191 WASM:   at System.Linq.Expressions.LambdaExpression.Compile (System.Boolean preferInterpretation) <0x1ca4af8 + 0x0002a> in <3b87fe83b5374933a839480144f02d1e>:0 
MonoPlatform.ts:191 WASM:   at System.Linq.Expressions.LambdaExpression.Compile () <0x1ca4828 + 0x0000a> in <3b87fe83b5374933a839480144f02d1e>:0 
MonoPlatform.ts:191 WASM:   at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateSet[T] (System.Reflection.PropertyInfo propertyInfo) <0x1de3468 + 0x00138> in <d1edc9ef2b6545bfaca5143dd43a36de>:0 
```

**Comment by danroth27** [comment]
> This is an issue with Newtonsoft.Json itself as it tries to use System.Reflection.Emit which is not supported on WebAssembly.
> The large fix for this this is not exactly trivial as we lack a nuget TFM meaning library authors can't properly target WASM.
> In the meanwhile, there solution is to use library builds designed to be compatible with Xamarin.iOS, which has similar limitations.

@jamesNK Does Json.NET already have Xamarin.iOS support?

@mhutch Looks like progress on https://github.com/NuGet/NuGet.Client/pull/2159 has stalled. Now that BUILD is over what do we need to do to get adding the TFM unblocked?

**Comment by JamesNK** [comment]
Json.net runs in iso and UWP. ILEmit is swapped out for expressions for reflection in the netstandard build

**Comment by JamesNK** [comment]
Can you confirm what build of Json.NET you are using? Is it the one that targets netstandard2.0?

**Comment by MisinformedDNA** [comment]
@kumpera @JamesNK: I added

> var t = typeof (Newtonsoft.Json.Linq.JObject).Assembly.GetType ("Newtonsoft.Json.Serialization.JsonTypeReflector");
> var field = t.GetField ("_dynamicCodeGeneration", BindingFlags.NonPublic | BindingFlags.Static);
> field.SetValue(null, false);

at the beginning of in Program.cs

But when I try to run it, I get a similar error to @danroth27. Alsom I get the same error message if I don't add the specified code.

**Comment by lawgorht** [comment]
@MisinformedDNA I have the same problem here, setting that field value didn't help. Did you manage to find a solution to user Json.net with wasm?

**Comment by danroth27** [comment]
Turns out the issues we've had with Json.NET are with our linker configuration. If you want to use Json.NET in a Blazor app you should be able to get it to work by using the following linker configuration: https://gist.github.com/Suchiman/a5e65f40c353120c9cf7f6a631ded28b.

**Comment by JamesNK** [comment]
Will the next version of Blazor ship with a fixed configuration?
