### ISSUE TITLE
Reference assemblies need to include private struct fields

### ISSUE THREAD

**Issue by jkpubsrc** [mono/mono#7859]
Hi!

I just accidentally wrote

    Size size = size;

The compiler did not complain: It assigned an empty `Size` structure to `size`. Is this a bug? According to my understanding this should be: `size` is being assigned from an uninitialized `size`.

**Comment by vargaz** [comment]
Please attach a complete testcase.

**Comment by jkpubsrc** [comment]
You're kidding me, right?

```python
using System;
using System.Drawing;
using System.Windows.Forms;

namespace MyTest
{
	class MainClass
	{
		public static void Main()
		{
			Size size = size;
		}
	}
}
```

**Comment by vargaz** [comment]
Can't reproduce this with mono 5.10:

with csc:

bug8.cs(11,16): error CS0165: Use of unassigned local variable 'size'

with mcs:

bug8.cs(11,9): warning CS1717: Assignment made to same variable; did you mean to assign something else?
bug8.cs(11,16): error CS0165: Use of unassigned local variable `size'

**Comment by Therzok** [comment]
I seem to be able to reproduce this from VSMac inside a console app/using msbuild, not csc directly.

**Comment by Therzok** [comment]
[compilerbug.zip](https://github.com/mono/mono/files/1864518/compilerbug.zip)

**Comment by lambdageek** [comment]
Building against `4.7-api/System.Drawing.dll` seems to silence the compiler error.

If I instead build against `4.5/System.Drawing.dll`, I get:
```
mono /Library/Frameworks/Mono.framework/Versions/5.13.0/lib/mono/4.5/cs
c.exe /noconfig /nostdlib+ /platform:x86 /define:DEBUG /reference:/Library/Fram
eworks/Mono.framework/Versions/5.13.0/lib/mono/4.7-api/mscorlib.dll /reference:
/Library/Frameworks/Mono.framework/Versions/5.13.0/lib/mono/4.7-api/System.Core
.dll /reference:/Library/Frameworks/Mono.framework/Versions/5.13.0/lib/mono/4.7
-api/System.dll /reference:/Library/Frameworks/Mono.framework/Versions/5.13.0/l
ib/mono/4.5/System.Drawing.dll  /out:obj/x86/Debug/compilerbug.exe /target:exe 
 Program.cs
Microsoft (R) Visual C# Compiler version 2.7.0.62620 (e873e693)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(10,16): error CS0165: Use of unassigned local variable 'size'
```

**Comment by Therzok** [comment]
Seems like fields are stripped from structs.

https://github.com/dotnet/corefx/issues/6185

**Comment by lambdageek** [comment]
huh. Learned something today.  This is a valid program:

```csharp
using System;


public struct X {
}

public class M {
	public static void Main ()
	{
		X x = x;
		Console.WriteLine ($"x is {x}");
	}
}
```

It's actually okay to use the variable that's being declared on the RHS of the definition.  After all, all of its fields (all zero of them) have been initialized so the whole thing is initialized.

This is also fine:

```csharp
public struct Y {
	public int z;
}

public class M {
	public static void Main ()
	{
		Y y = ((y.z = 42) == 42 ? y : y);
		Console.WriteLine ($"y.z is {y.z}");
	}
}
```

**Comment by jkpubsrc** [comment]
@lambdageek: Hm... You can't reproduce this? That's strange .... Let's try that again here ...

```
Building Solution: StrangeBug (Debug|x86)
Build started 4/12/2018 3:34:33 PM.
__________________________________________________
Project "/home/xxxxxxxx/DevBug/StrangeBug/StrangeBug/StrangeBug/StrangeBug.csproj" (Build target(s)):

Target CoreCompile:
    /usr/lib/mono/4.5/csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:DEBUG /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:/usr/lib/mono/4.6.1-api/mscorlib.dll /reference:/usr/lib/mono/4.6.1-api/System.Core.dll /reference:/usr/lib/mono/4.6.1-api/System.dll /reference:/usr/lib/mono/4.6.1-api/System.Drawing.dll /debug+ /debug:portable /optimize- /out:obj/x86/Debug/StrangeBug.exe /subsystemversion:6.00 /target:exe /utf8output Program.cs Properties/AssemblyInfo.cs "/tmp/.NETFramework,Version=v4.6.1.AssemblyAttributes.cs"
Target CopyFilesToOutputDirectory:
    Copying file from "obj/x86/Debug/StrangeBug.exe" to "bin/Debug/StrangeBug.exe".
    StrangeBug -> /home/xxxxxxxx/DevBug/StrangeBug/StrangeBug/StrangeBug/bin/Debug/StrangeBug.exe
    Copying file from "obj/x86/Debug/StrangeBug.pdb" to "bin/Debug/StrangeBug.pdb".

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.58

---------------------- Done ----------------------

Build successful.
```

If I understand that correctly this only works with structs? interesting.

**Comment by lambdageek** [comment]
@jkpubsrc We can reproduce it. the key is to compile against reference assemblies, not against the framework assemblies. (ie `/usr/lib/mono/4.6.1-api/mscorlib.dll` in your output - reference assemblies; just compiling from the commandline with csc or msc will by default use the framework assemblies).

@marek-safar How can we make all the reference assemblies in Mono follow https://github.com/dotnet/corefx/issues/6185 (TL;DR is in https://github.com/dotnet/buildtools/pull/1859 - for every struct with private fields include at least one int or object field in the reference assemblies)?

**Comment by marek-safar** [comment]
We cannot change the reference assemblies as that'd be a major breaking change. They are fully compatible with .NET and we don't want to change that.

**Comment by akoeplinger** [comment]
I think we should do this, we'll need to regenerate the reference assemblies with an updated GenAPI.exe that includes the changes to preserve fields in structs.

**Comment by akoeplinger** [comment]
@marek-safar the .NET Framework reference assemblies do contain these private struct fields.

**Comment by marek-safar** [comment]
oh! I am not sure why I thought they didn't. In such case it's absolutely issue on our end

**Comment by jaykrell** [comment]
Same thing? Is important for structs to have private fields in the reference assemblies, so that I can put them in my own structs and get the correct sizes. We had memory corruption 10+ years ago when referenceassembly structs were missing their private fields.

**Comment by joncham** [comment]
This issue is tracked for Unity here: https://issuetracker.unity3d.com/issues/creating-a-certain-struct-in-the-script-crashes-the-editor-on-begin-monomanager-reloadassembly
