### ISSUE TITLE
[wasm] Don't fail when TaskCreationOptions.LongRunning is used

### ISSUE THREAD

**Issue by kumpera** [mono/mono#7864]
Repro code:
```
Task.Factory.StartNew (() => { }, TaskCreationOptions.LongRunning);
```

This will fail with

```
System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.ExecutionEngineException: MonoError reused after mono_error_cleanup
  at System.Threading.Thread.StartInternal (System.Security.Principal.IPrincipal principal, System.Threading.StackCrawlMark& stackMark) <0x1df96b0 + 0x00018> in <bd43c24f03094d6f9ea2cbc005ee124e>:0 
```

We're better ignoring `TaskCreationOptions.LongRunning` and treating it as a regular task that failing like that.

**Comment by kumpera** [comment]
Shouldn't this be closed only once I get the mono PR to bump corert merged?

**Comment by marek-safar** [comment]
It closes automatically when you use any of the right keywords like "Fixes"

**Comment by kumpera** [comment]
Oh, didn't know about such automation.
I have probably complained with you about stuff github did on your behalf. Sorry for that. :(

**Comment by marek-safar** [comment]
Here are the keywords https://help.github.com/articles/closing-issues-using-keywords/ (just in case)
