### ISSUE TITLE
Parallel msbuild build support on macOS

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7878]
Implement or port parallel msbuild build support and ensure it works correctly on MacOS.

**Comment by Therzok** [comment]
Afaik, it depends on https://github.com/mono/mono/issues/7143

**Comment by KirillOsenkov** [comment]
@radical do you know what's the latest on this? I think this was supported at some point but then we had to turn it off again? Should we try turning this back on and seeing if this works now?

**Comment by radical** [comment]
This has been working for quite some time. We can close the issue.
