### ISSUE TITLE
Drop xbuild dependency in Xamarin products

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7883]
# Visual Studio for Mac

- [x] Build
- [ ] Project System

It needs verification that there are really no dependencies from the IDE

# XI/XM

- [x] Build
- [x] Tests
	- [x] Add support for fallback search paths for Target frameworks https://github.com/Microsoft/msbuild/pull/3277
	- [x] Add support for fallback search paths for Extension Path
	- [x] Removal of xbuild https://github.com/xamarin/xamarin-macios/pull/4111

# XA

- [x] Build (https://github.com/xamarin/xamarin-android/pull/1571)
	- [ ] Java.Interop switch to msbuild
	- [ ] Update monodroid build to msbuild
- [x] Tests
	- [ ] Use fallback search paths for Target frameworks
	- [ ] Use fallback search paths for MSBuildExtensionsPath

There is testing lane with msbuild changes at https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-msbuild/

**Comment by chamons** [comment]
I am uncertain if this entails just using xbuild as a consumer or also use of xbuild in building/testing our products.

In any case, until MSBuild redirect is available (or we burn time to do an xabuild style hack) we are using xbuild to test XI/XM in auto tests.

**Comment by marek-safar** [comment]
@chamons both, this is a card/task to track the effort not a statement that it does not work
