### ISSUE TITLE
build broken with --enable-minimal=soft_debug

### ISSUE THREAD

**Issue by pr0vieh** [mono/mono#7920]
## Steps to Reproduce

1. `./autogen.sh "--enable-minimal=soft_debug --with-cooperative-gc --with-jemalloc-always --with-mcs-docs=no --with-xen-opt=no"`
2.  make
3. 

## Current Behavior

  CCLD     mono-sgen
  CCLD     mono-boehm
./.libs/libmini.a(libmini_la-aot-runtime.o): In function `load_function_full':
/monomaster/mono/mono/mini/aot-runtime.c:5203: undefined reference to `mono_debugger_agent_breakpoint_from_context'
/monomaster/mono/mono/mini/aot-runtime.c:5201: undefined reference to `mono_debugger_agent_single_step_from_context'
./.libs/libmini.a(libmini_la-tramp-amd64.o): In function `mono_arch_create_sdb_trampoline':
/monomaster/mono/mono/mini/tramp-amd64.c:888: undefined reference to `mono_debugger_agent_single_step_from_context'
/monomaster/mono/mono/mini/tramp-amd64.c:890: undefined reference to `mono_debugger_agent_breakpoint_from_context'
collect2: error: ld returned 1 exit status
Makefile:1389: recipe for target 'mono-boehm' failed
make[3]: *** [mono-boehm] Error 1
make[3]: *** Waiting for unfinished jobs....
./.libs/libmini.a(libmini_la-aot-runtime.o): In function `load_function_full':
/monomaster/mono/mono/mini/aot-runtime.c:5203: undefined reference to `mono_debugger_agent_breakpoint_from_context'
/monomaster/mono/mono/mini/aot-runtime.c:5201: undefined reference to `mono_debugger_agent_single_step_from_context'
./.libs/libmini.a(libmini_la-tramp-amd64.o): In function `mono_arch_create_sdb_trampoline':
/monomaster/mono/mono/mini/tramp-amd64.c:888: undefined reference to `mono_debugger_agent_single_step_from_context'
/monomaster/mono/mono/mini/tramp-amd64.c:890: undefined reference to `mono_debugger_agent_breakpoint_from_context'
collect2: error: ld returned 1 exit status
Makefile:1393: recipe for target 'mono-sgen' failed

### On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
master

### Stacktrace

```
Please paste the stacktrace here if available.
```

**Comment by kumpera** [comment]
Maybe you're confusing my changed to Zoltan's recent changed to move sdb to a obj file? cc @vargaz

**Comment by luhenry** [comment]
I thought https://github.com/mono/mono/pull/7549 had been merged, my bad.
