### ISSUE TITLE
Microsoft.Common.props missing in Fedora 27

### ISSUE THREAD

**Issue by codermantx** [mono/mono#7930]
## Steps to Reproduce

I am using VS Code v1.12.1 to develop on F# on Fedora 27
Followed instructions on the page to install mono-devel in Fedora.

## Current Behavior
The Omnisharp C# extension is throwing error as it is not able to find props file in mono dir (see Stacktrace)

I have similar setup in Ubuntu 17.10, where the props file exists and the extenison works flawlessly.

## Expected Behavior

The required Microsoft.Common.props file to be present in the location as in stack trace.

### On which platforms did you notice this

[ ] macOS
[ x] Linux
[ ] Windows

**Version Used**:
Mono 5.10.1.20 

### Stacktrace

```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "/usr/lib/mono/xbuild/15.0/Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  /usr/share/dotnet/sdk/2.1.101/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props
```

**Comment by ciwchris** [comment]
Same error except C# on Arch Linux and:

- VS Code 1.21
- Mono JIT compiler version 5.10.0
- dotnet 2.1.103

**Comment by directhex** [comment]
```
msbuild:		/usr/lib/mono/xbuild/15.0/Microsoft.Common.props
mono-xbuild:	/usr/lib/mono/xbuild/14.0/Microsoft.Common.props
```

**Comment by akoeplinger** [comment]
@codermantx could you please check if you have the `msbuild` package installed?

**Comment by codermantx** [comment]
Installing ```msbuild``` package resolved the issue ! 👍 
Thanks! Have a good day!!
