### ISSUE TITLE
CreateDelegate produces delegate wrapping incorrect method

### ISSUE THREAD

**Issue by SteveSandersonMS** [mono/mono#7944]
## Steps to Reproduce

1. Define the following class:

```csharp
        class MyClass
        {
            public string Prop1 { get; set; }
            public string Prop2 { get; set; }

            public void DoRepro()
            {
                var prop1Setter = this.GetType().GetProperty(nameof(Prop1)).GetSetMethod();
                var prop2Setter = this.GetType().GetProperty(nameof(Prop2)).GetSetMethod();
                var prop1Delegate = (Action<MyClass, string>)prop1Setter.CreateDelegate(typeof(Action<MyClass, string>));
                var prop2Delegate = (Action<MyClass, string>)prop2Setter.CreateDelegate(typeof(Action<MyClass, string>));
                prop1Delegate(this, "prop1Value");
                prop2Delegate(this, "prop2Value");
                Console.WriteLine($"prop1: {Prop1}");
                Console.WriteLine($"prop2: {Prop2}");
            }
        }
```

2. From `Program::Main` or similar, call `new MyClass().DoRepro();`

## Current Behavior

Prints:

```
prop1: prop2Value
prop2: 
```

## Expected Behavior

Should print:

```
prop1: prop1Value
prop2: prop2Value
```

### On which platforms did you notice this

[x] WebAssembly from commit 67c1708677a

Note: this currently breaks dependency injection in Blazor, reported as https://github.com/aspnet/Blazor/issues/462

**Comment by SteveSandersonMS** [comment]
@kumpera Do you know if this has been fixed on a newer version, or whether this is likely to be WebAssembly-specific or a more general Mono issue?

**Comment by kumpera** [comment]
This looks like it's a WASM only bug as I can't reproduce with desktop mono.
