### ISSUE TITLE
Using MonoNativeFunctionWrapperAttribute without referencing Xamarin libraries

### ISSUE THREAD

**Issue by mellinoe** [mono/mono#8032]
Is there a way to use MonoNativeFunctionWrapperAttribute, or achieve the same effect, without referencing a Xamarin library? Other similar concepts in the .NET ecosystem allow the attribute to be recognized by name, regardless of the assembly they are defined in. A similar approach would be nice here.

**Comment by mellinoe** [comment]
Ah, it looks like it is already recognized by name: https://github.com/mono/mono/blob/431c67415cfed1a33d088dfb50a7cea58a10c388/mono/mini/aot-compiler.c#L4215.

Even better, `UnmanagedFunctionPointerAttribute` seems to serve the same function. If that is supported, then I will just use that, since it's in a system library and more portable.

It would be good to confirm the above, and also add the information to [this page](https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations). I spent a decent chunk of time trying to understand what the problem with my code was, because the error message linked me to that page, which doesn't mention either of these attributes.

**Comment by marek-safar** [comment]
Made a request to update the page at https://github.com/MicrosoftDocs/xamarin-docs/issues/140
