### ISSUE TITLE
DNS: Name Resolution Failure

### ISSUE THREAD

**Issue by bserrao** [mono/mono#8168]
## Steps to Reproduce

1.  run any app that need to make use of DNS
2.  I've modified a snippet of code i've found on other issue to get the status of:
```
 Console.WriteLine("Socket.OSSupportsIPv4: " + Socket.OSSupportsIPv4);
 Console.WriteLine("Socket.SupportsIPv4: " + Socket.SupportsIPv4);

 Console.WriteLine("Socket.OSSupportsIPv6: " + Socket.OSSupportsIPv6);
 Console.WriteLine("Socket.SupportsIPv6: " + Socket.SupportsIPv6);
```
    And do a DNS query:
   `var addresses = Dns.GetHostAddresses("www.google.com");  `  
3. 
    The result:
```
  Socket.OSSupportsIPv4: False
  Socket.SupportsIPv4: False
  Socket.OSSupportsIPv6: False
  Socket.SupportsIPv6: False

  Unhandled Exception:
  System.Net.Sockets.SocketException (0x80004005): Could not resolve host 'www.google.com'
```

## Current Behavior

DNS lookup doesn't return any value and an exception is trown.
In sonarr app as example: [v2.0.0.5153] System.Net.WebException: DNS Name Resolution Failure: 'services.sonarr.tv'

## Expected Behavior

DNS lookup should return the IP address of the hostname

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] DragonFly BSD (Yes i know...)

**Version Used**:
5.10.0.16 and 5.2.0.215
Both build from source with some BSD patches applied. (Freebsd and DragonFly)

If i set those variables to true before the DNS lookup call i have sucess. 
```
   var field = typeof(System.Net.Sockets.Socket).GetField("s_SupportsIPv4", 
   BindingFlags.Static|BindingFlags.NonPublic);
   field.SetValue(null, true);
   Console.WriteLine("Socket.SupportsIPv4: " + Socket.SupportsIPv4);
   Console.WriteLine("Socket.OSSupportsIPv4: " + Socket.OSSupportsIPv4);
```
Result:

```
Socket.SupportsIPv4: True
Socket.OSSupportsIPv4: True
172.217.16.228
```

I understand that DragonflyBSD is not "supported" but i would appreciate some help...
  How does Mono sets those variables? (OssSupportsIPV4, OssSupportsIPV6, ...)
  It is possible for me to force those to "True" in a global Mono base, so that every app that rellies on it is capable of using it?

I belive i just need a small patch or dependencie to get over this issue.

Thanks a lot,

**Comment by bserrao** [comment]
The version i first used didn't have the fix for #6940, but i've applied it a recompile. The result is the same both Socket.OSSupportsIPvx and Socket.SupportsIPvx are initialized with false.

How can i run that GetAllNetworkInterfaces and see the output? I've tried calling it with:
`Console.Write(GetAllNetworkInterfaces ());`
But that's not the way to do it...

Thanks

**Comment by marek-safar** [comment]
The correct syntax is

`Console.WriteLine (System.Net.NetworkInformation.GetAllNetworkInterfaces ());`

**Comment by bserrao** [comment]
Thanks. I did this:
```
NetworkInterface[] adapters = NetworkInterface.GetAllNetworkInterfaces();
        Console.WriteLine(adapters[0].Id);
        Console.WriteLine(adapters[1].Id);
        Console.WriteLine(adapters[2].Id);
        Console.WriteLine(adapters[3].Id);
```
And got the name of the interfaces on my machine, so it means they are identified. 

```
Socket.OSSupportsIPv4: False
Socket.SupportsIPv4: False
Socket.OSSupportsIPv6: False
Socket.SupportsIPv6: False
igb0
fwe0
igb1
lo0
```

Now i don't know how debug why the socket fails to initialize.

**Comment by drobban** [comment]
Think I have the same issue in OpenBSD 6.3. mono version 5.10.0.160.
The "solution" suggested by @bserrao works for me as well.
I have a couple of suspects, but its to early to say more then that, just that I intend to do further investigation (but, should also say that my Mono knowledge is near to none).

**Comment by rfht** [comment]
@drobban I found the cause for the bug. @bserrao: adding DragonFly similarly might very well fix the bug there, too.
