### ISSUE TITLE
Changing eglib doesn't rebuild mono

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#8175]
## Steps to Reproduce

1. `CC='ccache cc' CXX='ccache c++' ./autogen.sh --prefix=${PREFIX} --disable-nls --enable-native-types --enable-debug --enable-checked-build=all --disable-btls --disable-btls-lib`
2. `make -j`
3. `touch mono/eglib/gmarkup.c`
4. `make`

Note that only `eglib` is rebuilt, but the mono binaries and libraries in `mono/mini/` are not.

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**: mono master@ 920267df91abcd7b79a45e81b634d7c107986b09

**Comment by vargaz** [comment]
Probably because of this:

sgen_libs = \
	$(monodir)/mono/metadata/libmonoruntimesgen.la	\
	$(monodir)/mono/sgen/libmonosgen.la	\
	$(monodir)/mono/utils/libmonoutils.la \
	$(GLIB_LIBS)

Note that GLIB_LIBS is an autoconf macro, so automake doesn't see it, so it doesn't know about the dependency.
