### ISSUE TITLE
[XA][2018-02] Certain methods are no longer linked from a local library when link all is enabled

### ISSUE THREAD

**Issue by pjcollins** [mono/mono#8185]
## Steps to Reproduce

1. Download the attached sample and start without debugging in Release mode on an Android device (I used a pixel 2 v8.1). The Release configuration should set the Android link mode to `Full`. 
2. Click the button and check for expected "[PASS]" output to be written to the button's text field.

[Reproduction Project](https://github.com/mono/mono/files/1900631/App59.zip)

## Current Behavior
A method I would expect to be linked is no longer linked away. Previously, the attached test case would result in an NRE being thrown.

## Expected Behavior
The attached test case would throw (and catch) an NRE against all previous xamarin-android versions.

### On which platforms did you notice this
Behavior manifests on Android when deployed from the following environments:
[x] macOS
[ ] Linux
[x] Windows

**Version Used**:
monodroid/mono-2018-02/d69e0b6f1
VS2017 15.7 Preview 3 - https://gist.github.com/pjcollins/245e41b78b0b7abfeea8bb92a805e469

**Comment by marek-safar** [comment]
This is expected. The linker now supports basic reflection detection logic. That means that code like

The check like `typeof(LinkerClass).GetMethod("ThisMethodShouldNotBePreserved");` will actually cause the method to be preserved. You can workaround it by moving `typeof(LinkerClass)` to class field so you will have code like

```
class X
{
	Type t = typeof (LinkerClass)

	void Test ()
	{
		var is_null = t.GetMethod("ThisMethodShouldNotBePreserved");

	}
}
```

**Comment by pjcollins** [comment]
Thanks for the explanation, I will update my tests for 2018-02.
