### ISSUE TITLE
Document steps to run a single set of tests

### ISSUE THREAD

**Issue by luhenry** [mono/mono#8212]
It requires some knowledge to be able to easily run the test suite for only System.Core or System.Drawing for example. Documenting this would make it easier for external contributors to easily reproduce and troubleshoot locally.

Some example of commands that are useful in the daily life of a contributor are:
 - `make check -C mcs/class/corlib`
 - `make check -C mono/tests`
 - `make run-xunit-test -C mcs/class/System`
-  `make check -C mcs/class/corlib FIXTURE=System.Globalization.CultureInfoTest`
-  `make check -C mcs/class/corlib TESTNAME=System.Globalization.CultureInfoTest.CreateSpecificCulture`

**Comment by akoeplinger** [comment]
This is documented on https://www.mono-project.com/community/contributing/test-suite/#running-nunitxunit-class-library-tests
