### ISSUE TITLE
Switch WASM profile to use bundled zlib

### ISSUE THREAD

**Issue by kumpera** [mono/mono#8216]
Found in https://github.com/aspnet/Blazor/issues/445

We need to change the BCL to pinvoke __Internal for zlib: https://github.com/mono/mono/blob/1a8142c7dbb7c5fd4ff53eb50fc7cde04f6a2a06/mcs/class/System/System.IO.Compression/DeflateStream.cs#L502-L522

Then we need to change the runtime to bundle it.

**Comment by SQL-MisterMagoo** [comment]
Hi, is this change likely to happen? I'm guessing more and more projects will hit this as Blazor takes off.
Does this issue need more support?

**Comment by adv12** [comment]
Just chiming in here.  I'm trying to load/save PNG images in Blazor and getting a System.DllNotFoundException when ImageSharp tries to us DEFLATE.

**Comment by kjpou1** [comment]
Closed by: https://github.com/mono/mono/pull/14308
