### ISSUE TITLE
Implement Verbose Unmanaged Crash Reporting

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#8217]
After some feedback on what we wanted to provide during crash time, I've decided to make a list of design constraints that we have so far. 

- We should include all native frames in the full stack trace, on all sides of all trampolines.
- We should make it all human readable, but it needs to be a format that's simple to print from the runtime. We already have json writers. I'd like json.
- We want to include the output of mono --version verbatim
- We should dump the contents of MonoInternalThread for each thread
- GDPR: We are going to use some configuration of this for our telemetry for VS4Mac. We need to abide by GDPR, so we need to be able to configure our dumper to not dump user data. Adding in a mode that doesn't dump any detailed information for the user program would probably be a good idea too. If we did it on a per-assembly basis, we could choose to only track managed stacks in a whitelist for telemetry.

**Comment by migueldeicaza** [comment]
Can this be made reliable?   I just know that typically the lldb invocation hangs for me after displaying the output.

**Comment by lewurm** [comment]
I would like to have the contents of all machine registers. This can be a API for MonoContext; for now we only need to support amd64 (only supported platform for MERP atm).

**Comment by alexanderkyte** [comment]
@migueldeicaza this won't rely on outside processes so the reliability will be up to mono. 

You all have great suggestions. 

I'd like to have an optional mapping of assembly name to .dll file as well, if that's possible. For BCL bugs due to the wrong BCL being loaded, that would make it much easier to spot.

**Comment by alexanderkyte** [comment]
@aleksey, this is an offline dump so I'm not sure how much benefit we can get from the MonoInternalThread pointers.

**Comment by lambdageek** [comment]
@alexanderkyte my main motivation is just to have a way of figuring out which managed thread object corresponds to which native thread.

Existing backtraces that we get in either lldb or the apple crash reporting dialog typically show native thread IDs.

On the other hand a lot of our assertions tend to print the value of `MonoInternalThread*` of some thread or a managed thread object.

It would be convenient if we could map back and forth, even offline, just to figure out which other thread we're asserting about.  Does that make sense?

**Comment by slluis** [comment]
About your comment on GDPR, I think it should be enough to whitelist the assemblies that belong to VSMac, and only report stack frames for those assemblies. In general we don't run user code in the VSMac process, but we may run code from third party extensions.

**Comment by alexanderkyte** [comment]
If we optimistically symbolicate I don't think that we need to do anything complex here, because we simply won't have the symbols for other peoples' code on our servers.

**Comment by slluis** [comment]
what about assembly names?

**Comment by luhenry** [comment]
Hopeful initial deadline: Wednesday, April 25th.
