### ISSUE TITLE
Add SIGTERM signal handler reporting

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#8236]
On OSX, MonoDevelop would like to have the Force Quit action register a telemetry event. This is useful because excessive quitting might indicate livelock or performance regressions. 

This is lower priority for now. It should be implemented after the free-form mono telemetry is implemented. This hook is mostly going to be used to fire that one. 

The biggest goal here is to make sure that this doesn't have any machinery that can break / will be too annoying. A smooth SIGTERM is important for cleanly quitting the runtime in automated scenarios.

**Comment by lewurm** [comment]
why does it need to be SIGTERM?

**Comment by luhenry** [comment]
@monojenkins backport to 2018-02

**Comment by luhenry** [comment]
@monojenkins backport to 2018-04
