### ISSUE TITLE
Some latin characters on Mono GDI+ are drawn incorrectly

### ISSUE THREAD

**Issue by FrozenShade666** [mono/mono#8272]
## Steps to Reproduce

1. Create a winform form, put a TextBox.
2. Run program, enter some random characters there, then try to enter any Unicode char from the range U+0108 to U+010D, for example this one: ĉ. 
3. enter some random characters

## Current Behavior
There are some characters that are drawn incorrectly. Everything looks ok if they are at the middle of the string. If those characters are at the end, they are not drawn. The first character in the string is drawn correctly.

### Tested on

Ubuntu 16.04.3 LTS + Mono 5.4.1.7
Raspbian GNU/Linux 9 (stretch) + Mono 5.10.0.160

**Comment by FrozenShade666** [comment]
I found the bug and made a PR.

**Comment by gatodev** [comment]
This doesn't work for some characters, e.g. 'ト'
