### ISSUE TITLE
[android] respect maximum length of a message when using __android_log_write ()

### ISSUE THREAD

**Issue by lewurm** [mono/mono#8282]
discovered by @jonpryor:

https://github.com/xamarin/xamarin-android/issues/1561#issuecomment-381753774

> In largely unrelated observations, [log-e9dea303ade84275a91249d678efb5d5.txt](http://xqa.blob.core.windows.net/gist/log-e9dea303ade84275a91249d678efb5d5.txt) contains a truncated stack trace:
> 
> ```
> ...
> 04-13 22:14:25.711 E/mono-rt (22802):   at System.Threading.ThreadHelper.ThreadStart_Context > (System.Object state) [0x00014] in <4775dd050ce546a9814a2d17717c9d37>:0 
> 04-13 22:14:25.711 E/mono-rt (22802):   at System.Threading.ExecutionCont
> ```
> 
> The `FATAL UNHANDLED EXCEPTION` message is produced by `mono_runtime_printf_err()`, which calls `g_log()` (`mono/utils/mono-logger-internals.h`), which eventually calls [`__android_log_write()`](https://github.com/mono/mono/blob/8fec8eeeaea6ee5228d10eb749f48915c4644648/mono/eglib/goutput.c#L161). The problem with `__android_log_write()` is that historically it may not print the entire message; it only prints the first *X* characters. (Historically, *X* was ~1024; now it appears to be closer to 4096, but it's still limited.)
> 
> We are thus "losing" some of the stack trace because of this call.
> 
> `Console.WriteLine()` split on newlines by using [`LogcatTextWriter`](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.IO/LogcatTextWriter.cs) before calling `Log(string)` (which calls `g_log()`).

**Comment by marek-safar** [comment]
Ouch, this is problematic. @luhenry who does own that part or can look into it?

**Comment by luhenry** [comment]
@jonpryor is there an alternative to `__android_log_write` which doesn't cut at N characters? `__android_log_print`?
