### ISSUE TITLE
Failing tests on FullAOT+LLVM

### ISSUE THREAD

**Issue by luhenry** [mono/mono#8319]
We have the following tests failing consistently on the FullAOT+LLVM PR job:

 - `MonoTests.runtime.generic-stack-traces2.2.exe`
 - `MonoTests.runtime.finally_block_ending_in_dead_bb.exe`
 - `FileTest.Create_Path_ReadOnly`
 - `FileTest.GetAttributes_ReadOnly`

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-fullaot+llvm/46/testReport/

**Comment by akoeplinger** [comment]
Let's use https://github.com/mono/mono/issues/8321 for tracking since the runtime tests were actually recently broken.
