### ISSUE TITLE
Build break/test failures on FullAOT+LLVM configuration

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#8321]
## Steps to Reproduce

1. Run FullAOT+LLVM config
2. Issue 1: Observe build failures on armel/armhf
3. Issue 2: Observe test failures on amd64/arm64

This started with https://jenkins.mono-project.com/job/test-mono-mainline-linux-fullaot+llvm/507/, commit range:

- [coop] Add new states and transitions for hybrid coop suspend (commit: f2f6a7d)
- [coop] Add MONO_ENABLE_HYBRID_SUSPEND environment variable (commit: 37613bc)
- [threads] Implement hybrid cooperative suspend (commit: b9be955)
- [configure] Add --with-hybrid-suspend option (commit: f214256)
- [threads] Return suspend sort from begin_suspend_for_running_thread (commit: 7e728dc)
- [threads] Make mono_thread_info_get_suspend_state suspend policy aware (commit: d1895b6)
- [coop] Enter GC Safe around mono_os_event_ calls in threads.c (commit: aaece70)
- [mcs] Fixes parameter check for interface types used with default (commit: 0d2609c)
- Updated Readme.md for clarity, and added Windows instructions. (commit: abc4573)
- Updated Readme.md (commit: 18d3890)
- [console-unix] retry `tcsetattr` if it was interrupted by signal (#8138) (commit: 5128cce)
- [profiler] Fix heapshot frequency calculation (#8163) (commit: af43001)
- [threadpool] ThreadPool.SetMinThreads fails if ThreadPool.GetMaxThreads (commit: ff0430b)
- Allow the LLVM optimizer options to be passed on the command line. (commit: 920267d)
- [corlib] Make more crypto oids work on mobile profiles when not linked (commit: 3b2dbf3)
- [runtime] Fix the build. (#8174) (commit: 254a57f)
- Report the proper socket error (#8041) (commit: 5f66c75)
- [jit] Add some implicit r4<->r8 conversions in float32 mode to the JIT (commit: aa729d1)
- [ci] Add {,hybrid,full}aot_llvm presets to make sure we compile with (commit: 4f2522e)
- [sdks] Fix typo (#8186) (commit: 42a62db)
- [sdks] Add ANDROID_BUILD_TOOLS_DIR to differentiate it from (commit: 1fff043)

## Current Behavior

Issue 1: Build on armel/armhf is broken:

```
06:13:45 MONO_PATH=".//class/lib/testing_aot_full" /home/builder/jenkins/workspace/test-mono-mainline-fullaot+llvm/label/debian-9-armel/runtime/mono-wrapper  --runtime=mobile -O=gsharedvt --llvm --aot=full,nimt-trampolines=2000,ntrampolines=10000,nrgctx-fetch-trampolines=256,ngsharedvt-trampolines=4000,temp-path=class/lib/testing_aot_full/I18N.Rare.dll_bitcode_tmp --verbose class/lib/testing_aot_full/I18N.Rare.dll > class/lib/testing_aot_full/I18N.Rare.dll.so.aot-log
06:13:46 class/lib/testing_aot_full/I18N.Other.dll_bitcode_tmp/temp-llvm.o: file not recognized: File format not recognized
06:13:46 
collect2: error: ld returned 1 exit status
06:13:46 AOT of image class/lib/testing_aot_full/I18N.Other.dll failed.
06:13:46 build/rules.make:194: recipe for target 'class/lib/testing_aot_full/I18N.Other.dll.so' failed
```

Issue 2:

Test failures on amd64/arm64:

```
amd64:
MonoTests.runtime.generic-stack-traces2.2.exe
MonoTests.runtime.finally_block_ending_in_dead_bb.exe
MonoTests.gshared.generic-stack-traces2.2.exe
MonoTests.gshared.generic-stack-traces2.2.exe
MonoTests.gshared.generic-stack-traces2.2.exe
MonoTests.gshared.generic-stack-traces2.2.exe

arm64:
MonoTests.test-sgen-regular-ms-conc-simple.bug-17590.exe
MonoTests.test-sgen-regular-ms-simple.bug-17590.exe
```

## Expected Behavior

No build/test failures

### On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**: master

/cc @lambdageek

**Comment by jaykrell** [comment]
Maybe the change to temp file/directory stuff in https://github.com/mono/mono/commit/4f2522e6f4b177f0c5e97cc9847c321543292bbd

That was meant to, and did, fix a bunch of related -- used to be racy build, fighting over same temp files.

**Comment by jaykrell** [comment]
Some of this is understood already, some not.
temp-path, even if not fixed, is probably a race on output file.
We'll see.

generic-stack-traces2.2 should be fixed by updating LLVM with Zoltan's fix.
I asked how and was given the wrong answer.

That still leaves
finally_block_ending_in_dead_bb.exe
test-sgen-regular-ms-conc-simple.bug-17590.exe
test-sgen-regular-ms-simple.bug-17590.exe

**Comment by jaykrell** [comment]
CI_TAGS=osx-amd64,retry-flaky-tests,fullaot_llvm,pull-request ./scripts/ci/run-jenkins.sh 
notice: osx not linux; seems to just work
I'll try Linux.

**Comment by jaykrell** [comment]
Which doesn't make sense, because finally_block_ending_in_dead_bb.exe does fail.
It is partly fixed now. The remaining problem is not entirely obvious but  I'll dig more.
The EH data is bad seeming, and more. Stack walks diverges from non-llvm because a length/end is 0. 
Hacking on that later sigsegvs.

**Comment by jaykrell** [comment]
I don't see the ARM problems in CI, just amd64. I don't see any arm llvm that is. I can try the analogous run-jenkins.sh.

**Comment by jaykrell** [comment]
No repro on Linux either:
PATH=...tollvm...
 CI_TAGS=linux-amd64,retry-flaky-tests,fullaot_llvm,pull-request ./scripts/ci/run-jenkins.sh

**Comment by jaykrell** [comment]
I can repro multiple XML failures now. Will dig deeper.

**Comment by jaykrell** [comment]
We are down to three failures.
2 are due to running LLVM CI as root.
Fix one: https://github.com/mono/mono/pull/8914
Or skip them? https://github.com/mono/mono/pull/8904
Or stop CI'ing as root?

The third is related to LLVM not having start/end of of finally blocks.
This might be fixable by placing labels and inhibiting optimization. Might.
Needs some investigation.
Note that the test does not work on desktop or coreclr.

**Comment by akoeplinger** [comment]
With https://github.com/mono/mono/pull/9213 and Jenkins not running tests as root (or https://github.com/mono/mono/pull/8904) we're green on amd64 now.

I'll file a separate issue for the remaining issues on arm64/armel/armhf since they're different now.

**Comment by jaykrell** [comment]
Should have a bug for the disabled finallybb test. Not easy to fix.

Should have bug to decide root/readonly behavior. Maybe note that we divege from coreclr.
There is other PR to unify some.

I can open them later.

**Comment by akoeplinger** [comment]
@jaykrell yeah we should have a bug for finally_block_ending_in_dead_bb.exe, though it's been disabled in 2015 so nothing recent (https://github.com/mono/mono/commit/7b7692a988f82e71c575e2c75b9293d8bef9ffe7).
