### ISSUE TITLE
Issue with black text on console, possibly ncurses

### ISSUE THREAD

**Issue by grbd** [mono/mono#8340]
Hi,
I've recently noticed an issue with mono producing black text when running things like nuget
I'm using the latest version of gentoo and I suspect this might be related to ncurses

## Steps to Reproduce

Let's say I try to run the latest nuget with an invalid option
```
nuget --invalidoption 
```
This should show a single line of red text giving an error
followed by a stack trace, but what I actually end up with is just a load of unreadable lines of black

To get around this I need to prefix the command 
```
TERM=xterm nuget --invalidoption 
```

I think dotnet core had a similar problem with https://github.com/dotnet/corefx/issues/26966
I thought this might be fixed with https://github.com/mono/mono/issues/6752
but that doesn't seem to have fixed the problem

### On which platforms did you notice this

  * [* ] Linux - gentoo latest
  * **Version Used**: mono 5.10.1.48

**Comment by kasper3** [comment]
Fot donet core, maybe try `dotnet nuget --invalidoption`

**Comment by PiotrZierhoffer** [comment]
I can confirm this on mono 5.12.0.226. Unfortunately it makes console applications that use colors in their output quite unusable.

While this is not fixed, does anyone know if it's safe to set TERM=xterm by default on modern Linux distros? Are you aware of any distributions that lack this config by default?

**Comment by lewurm** [comment]
@PiotrZierhoffer setting `TERM=xterm` is safe for pretty much any distribution out there.
