### ISSUE TITLE
Mono 5.10.1.47 released, but source not downloadable and no releasenotes

### ISSUE THREAD

**Issue by rjvdboon** [mono/mono#8341]
_Not sure if this is mono/mono or a mono/website issue. Filing it here as I think it might involve mono's automation_

## Steps to Reproduce

1. Go to http://www.mono-project.com/download/stable/#download-lin
2. Observe 5.10.1.47 is now stable
3. Click on "tarball", you'll end up at https://download.mono-project.com/sources/mono/
4. Click on mono-5.10.1.47.tar.bz2 to download
5. Go back to step 1. and click on Release Notes 
6. Click on 5.10.1 to get the releasenotes for the new release
 
## Current Behavior

In step 4: there is no mono-5.10.1.47.tar.bz2 (I found it eventually in the preview/ folder)
In step 6: there is no entry for 5.10.1

## Expected Behavior

The .tar.bz2 should be available.
The releasenotes should be available.

### On which platforms did you notice this

[ ] macOS
[X] Linux
[X] Windows

**Version Used**:

N/A

### Stacktrace

N/A

**Comment by directhex** [comment]
Right, right, it's not moved out of the preview/ directory on promoting to stable. Will do that manually, and script for the future.

**Comment by directhex** [comment]
@akoeplinger does https://jenkins.mono-project.com/view/Releases/job/ng-release-promote/jobConfigHistory/showDiffFiles?timestamp1=2018-04-18_03-44-57&timestamp2=2018-04-19_14-46-06 seem sane to you?

**Comment by akoeplinger** [comment]
@directhex I'd `cp` instead of `mv` but otherwise 👍

**Comment by akoeplinger** [comment]
@directhex we also need to trigger CDN invalidation

**Comment by luhenry** [comment]
@marek-safar could you please take care of the release notes?

**Comment by rjvdboon** [comment]
Problem exists with 5.12.0.223 as well, which was promoted to [stable](https://www.mono-project.com/download/stable/) a couple of days ago:
- tar is only in the preview directory
- release notes [overview](https://www.mono-project.com/docs/about-mono/releases/) page state _(not released yet)_
- release notes for [5.12.0](http://www.mono-project.com/docs/about-mono/releases/5.12.0/) start with a warning "These notes are for a current or upcoming PREVIEW release", and the Release History section is empty.

**Comment by akoeplinger** [comment]
I fixed the release notes for 5.12 and the 5.12.0.226 tarball is available in the correct folder: https://download.mono-project.com/sources/mono/mono-5.12.0.226.tar.bz2

We clearly need to do better here, I'll start a discussion.

**Comment by akoeplinger** [comment]
We're now using a checklist on the release issue to make sure we don't miss any steps (see e.g. "Releases" heading in https://github.com/mono/mono/issues/7854)
