### ISSUE TITLE
Implement GC.GetAllocatedBytesForCurrentThread

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#8397]
This is a new API as proposed [here](https://github.com/dotnet/corefx/issues/10157).

It should help us to better integrate with benchmark.net and possibly other tools.

ColeCLR implementation https://github.com/dotnet/coreclr/pull/6953

**Comment by Lexcess** [comment]
Just to lend support to this issue. I've proposed that GetAllocatedBytesForCurrentThread be adopted in .Net Standard vNext here: https://github.com/dotnet/standard/issues/771 . Having a working implementation on Mono would really aid this effort and make runtime memory analysis significantly easier (both for tooling and in process monitoring).

**Comment by naricc** [comment]
Implemented in PR https://github.com/mono/mono/pull/14779
