### ISSUE TITLE
WebAssembly: TimeZone issues related to Mono?

### ISSUE THREAD

**Issue by chassq** [mono/mono#8443]
See https://github.com/aspnet/Blazor/issues/663 for details. Hoping this can be resolved somehow.

**Comment by migueldeicaza** [comment]
This is a duplicate of this issue:

https://github.com/mono/mono/issues/8443

**Comment by chassq** [comment]
Which one was the duplicate issue? #8443 is the closed issue.

**Comment by migueldeicaza** [comment]
My bad: https://github.com/mono/mono/issues/6368

**Comment by chassq** [comment]
Thanks!
