### ISSUE TITLE
[wasm] System.Runtime.dll facade is missing System.Runtime.CompilerServices.TaskAwaiter

### ISSUE THREAD

**Issue by praeclarum** [mono/mono#8456]
It would seem that System.Runtime is missing a few entries around Tasks.

## Steps to Reproduce

1. Compile a .NET Standard library
2. Link it to the wasm SDK using the mono linker

### Current Behavior

Linking fails because `System.Runtime.CompilerServices.TaskAwaiter` cannot be found in System.Runtime.dll

### Expected Behavior

The type forwarder for `System.Runtime.CompilerServices.TaskAwaiter` is in System.Runtime.dll and linking succeeds.

## On which platforms did you notice this

- [x] macOS
- [ ] Linux
- [ ] Windows

**Version Used**:

a14f41ca260

**Comment by akoeplinger** [comment]
This should only happen if you run an assembly compiled against the .NET Core assembly factoring on Mono.

A .NET Standard library should expect System.Runtime.CompilerServices.TaskAwaiter in System.Threading.Tasks.dll (NS1.x) or netstandard.dll (NS2.x)

**Comment by praeclarum** [comment]
Ah yes, I should clarify. I am re-linking a .NET Core (2.0) app against the wasm BCL. Some of the (.NET std 1.3) nugets (CSLA-Core-NS) that it references have TypeRefs that point to System.Runtime.

It's hard for me to tell *why* CSLA has a type ref to System.Runtime but it's there.

If I'm understanding you - this is a particularity of .NET Core?

I'll admit I don't fully understand the whole System.Runtime schism in .NET so will close this if you tell me everything is right.

Currently, I have a simple hack that redirects the linker to mscorlib if it can't find a type in System.Runtime. That seems to work, but I'm not sure if it captures everything.

Thanks for any clarifications!

**Comment by marek-safar** [comment]
@praeclarum this is not going to work, you cannot just take netcore app and expect it to work on a different runtime. The way it works is that it also bundles netcore specific version of all dependencies (down to the runtime internals). You could hack it by copying Mono/Xamarin versions of same assemblies to replace the one you have there but that's kind of hacky and assumes your project is pure netcore
