### ISSUE TITLE
struct with 3 bytes not marshaled correctly with LLVM on watchOS

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#8486]
## Steps to Reproduce

1. Download test case: [struct-bbb-bug.zip](https://github.com/mono/mono/files/1954877/struct-bbb-bug.zip)
2. Open solution, select the watch app as the startup project.
3. Select a Release|Device configuration.
3. Run.

### Current Behavior

Application output:

```
[...]
Assertion failed: (s.x == 1), function set_s, file set_s.c, line 10.
0 -70 32
Xamarin.Hosting: Process '571' exited.
```

The code (in InterfaceController.cs) calls a P/Invoke that takes a struct with 3 bytes, managed code passes a struct with the values [1;2;3], native code receives [0;-72;32].

Other failing tests indicate that structs with 3 shorts and structs with 2 bytes have the same problem (I didn't bother creating separate test cases, since it looks like the same issue). Other variations work fine (structs with 1 or 4 bytes, structs with 1, 2 or 4 shorts, structs with 1, 2, 3 or 4 ints, longs, floats or doubles).

### Expected Behavior

If running the debug configuration:

```
[...]
1 2 3
DONE
```

## On which platforms did you notice this

watchOS with LLVM.

**Version Used**:

xamarin-macios/master (xamarin/xamarin-macios@bf159969f9b5c72abe3d6959cf8c4840495b3f2b) which is mono's 2018-02 branch.

It does not look like a regression (I can reproduce with d15-7, d15-6 and d15-5. I didn't try with earlier versions).

**Comment by lewurm** [comment]
that looks similar to https://github.com/mono/mono/issues/7449 which got fixed by https://github.com/mono/mono/pull/7691

maybe we have a similar issue with the llvm backend

**Comment by marek-safar** [comment]
@vargaz could you confirm that?

**Comment by marek-safar** [comment]
@vargaz what's the status of this issue?

**Comment by rolfbjarne** [comment]
Updated test case that tests for more signatures (structs with 1/2/3 bytes/shorts): 
[struct-bbb-bug-v2.zip](https://github.com/mono/mono/files/2303018/struct-bbb-bug-v2.zip)

Result:

    S1: expected <1>, got <52736>
    S2: success
    S3: expected <1, 2, 3>, got <1, 2, 1>
    B1: expected <1>, got <0>
    B2: expected <1, 2>, got <0, -50>
    B3: expected <1, 2, 3>, got <0, -50, 38>
    DONE status: False

This is using mono 2018-06.

**Comment by rolfbjarne** [comment]
Still happens with mono 2018-08.

**Comment by marek-safar** [comment]
@vargaz could you please address the issue

**Comment by lewurm** [comment]
can reproduce on watch4
```
S1: expected <1>, got <64000>
S2: success
S3: expected <1, 2, 3>, got <1, 2, 0>
B1: expected <1>, got <0>
B2: expected <1, 2>, got <0, -6>
B3: expected <1, 2, 3>, got <0, -6, 52>
2019-02-08 19:32:30.646296+0100 bug601711wappExtension[411:377807] DONE status: False (XI version: 12.7.0)
```
will look into it
