### ISSUE TITLE
msbuild fails to strong-name assemblies regardless of the <DelaySign> property in .csproj

### ISSUE THREAD

**Issue by craigfowler** [mono/mono#8495]
*This issue is a clone/duplicate of [the upstream msbuild issue #2503](https://github.com/Microsoft/msbuild/issues/2503) in the Microsoft/msbuild repo.*

## Steps to Reproduce
1. Create a minimal C# library project which builds and which has the following in the `.csproj` file (generate a suitable signing key pair if required)
```xml
<PropertyGroup>
  <SignAssembly>true</SignAssembly>
  <AssemblyOriginatorKeyFile>MyKeyfile.snk</AssemblyOriginatorKeyFile>
  <DelaySign>false</DelaySign>
</PropertyGroup>
```
2. Use msbuild to build the project
3. Now use `sn -vf MyAssembly.dll` (using the built assembly) to inspect the state of the assembly

### Current Behavior
**sn** reports that the assembly has been *delay-signed* and not strong-named, even though the project settings indicate that we didn't want to delay-sign it.

### Expected Behavior
Because `<DelaySign>` was set to false, the assembly should have been fully strong-named.

## On which platforms did you notice this
I have noticed this on **GNU/Linux** (Debian Jessie).  Given that the same symptoms have been reported upstream with Microsoft msbuild I believe that it also affects Windows too (and any other platforms which use msbuild?).  I haven't tried anything other than Linux personally though.

**Version Used**:
I am using Mono (and msbuild) from the mono-complete **Debian package**:
```
$ dpkg -s mono-complete
Package: mono-complete
Status: install ok installed
Priority: optional
Section: cli-mono
Installed-Size: 64
Maintainer: Debian Mono Group <pkg-mono-group@lists.alioth.debian.org>
Architecture: amd64
Source: mono
Version: 5.10.0.160-0xamarin2+debian7b1
<snip!>
```

Here are the related versions of mono and msbuild, but in reality it's whatever was shipped in the above Debian package.
```
$ mono --version
Mono JIT compiler version 5.10.0.160 (tarball Wed Mar  7 15:30:00 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

$ msbuild /ver
Microsoft (R) Build Engine version 15.4.0.0 ( Wed Nov 29 14:56:11 UTC 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

15.4.0.0
```

**Comment by craigfowler** [comment]
## Workaround
The workaround I'm going to use for the time-being is to run `sn -R MyAssembly.dll MyKeyfile.dll` as an extra step in my build config.  Manually completing the signing process (as if I had intended to delay-sign) seems to work as expected.

**Comment by rainersigwald** [comment]
@radical looks like you can revert https://github.com/mono/msbuild/commit/665f843ac664eb2b4541242c1d6e364a9a838ac8 since dotnet/roslyn#8210 is complete now.

@craigfowler To force Mono's MSBuild to attempt to strong sign, you can set the project property

```xml
<_UseRoslynPublicSignHack>false<_UseRoslynPublicSignHack>
```

**Comment by craigfowler** [comment]
@rainersigwald - thanks but it seems @akoeplinger is correct.  Using the `_UseRoslynPublicSignHack` property doesn't help me for Mono 5.10 (the latest version available in the Debian package repo right now).  If I use msbuild from Mono 5.10 then I get this when attempting to build.

```
(CoreCompile target) -> 
  CSC : error CS7027: Error signing output with public key from file '../MyKey.snk' -- mscoree.dll [/home/craig/Projects/MySolution/MyProject/MyProject.csproj]
```

It's OK.  I'll go back to "Workaround A" which is to manually use `sn -R` with my builds.  Once Mono 5.14 becomes available in the repo, I'll reevaluate the `_UseRoslynPublicSignHack` property.

**Comment by akoeplinger** [comment]
Well by that time the property won't be needed anymore since it'll "just work" :smile:
