### ISSUE TITLE
Support Response Files

### ISSUE THREAD

**Issue by jonpryor** [mono/mono#8518]
It would be useful if `mono` supported [response files](https://msdn.microsoft.com/en-us/library/windows/desktop/aa367156(v=vs.85).aspx).

A "response file" is a plain-text file that contains strings to be treated as arguments for `mono`.

For example, assume a file `foo.rsp` with the contents:

```
--debug=casts foo.exe
```

Then `mono @foo.rsp` would be treated *as if* the user had instead entered `mono --debug=casts foo.exe`.

Response files are useful for working around [Windows command-line length limits](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation) (8191 characters on Windows XP and later), which *sounds* like a lot but can quickly disappear when e.g. [providing AOT commands](https://developercommunity.visualstudio.com/content/problem/237753/xamarin-android-aot-complition-does-not-work-visua.html). (Linked-to bug is a Xamarin.Android bug, but an underlying "cause" of the bug is that Xamarin.Android prefers "8.3" names on Windows when invoking `mono` so that paths are shorter, and so we don't need to deal with path quoting. If we could generate a response file *instead*, it might be easier to support paths-with-spaces.)

**Comment by migueldeicaza** [comment]
Agreed, Mono's C# compiler also supports response files, I think that this request is for the runtime itself.

The issue that I have with @foo.rsp is that it will potentially break (albeit this sounds rare) any executable that was named '@foo.rsp'.

Perhaps this shoudl be mono --response foo

**Comment by lambdageek** [comment]
@migueldeicaza Do we already have `mono -- args ...` meaning "stop interpreting arguments after `--`"?

If yes, we could support `mono @foo.rsp` for response files and if someone really names their assembly "@foo.rsp" then can do `mono -- @foo.rsp` to run it.

**Comment by jaykrell** [comment]
$ mono -- foo.exe
Unknown command line option: '--'
Add that too?

**Comment by migueldeicaza** [comment]
We could explore the "Stop interpreting" option "--", but for now, we can just add "--response=FILE"
