### ISSUE TITLE
configure.ac G_HAVE_ISO_VARARGS problems

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8587]
In configure.ac we have:

```
AC_MSG_CHECKING(for varargs macros)
AC_TRY_COMPILE([],[
int foo (int i, int j);
#define bar(...) foo (1, __VA_ARGS__)
void main () {
	 bar (2);
}
],have_iso_varargs=yes,have_iso_varargs=no)
AC_MSG_RESULT($have_iso_varargs)
G_HAVE_ISO_VARARGS=0
if test "x$have_iso_varargs" = "xyes"; then
   G_HAVE_ISO_VARARGS=1
fi
AC_SUBST(G_HAVE_ISO_VARARGS)
```

This does not work in the way intended.
A main() wrapper is supplied and it tries to compile:

```c
int
main ()
{
		int foo (int i, int j);
		#define bar(...) foo (1, __VA_ARGS__)
		void main () {
			 bar (2);
		}
  ;
  return 0;
}

```

giving:

```
1.c:7:14: error: function definition is not allowed here
void main () {
```

**Comment by marek-safar** [comment]
From @jaykrell comment


Sometimes gcc allows nested functions, sometimes not, i.e. Apple configuration.

Solution is use newer-fangled AC_COMPILE_IFELSE.
Or rename main and put it in the first parameter.
Or remove the entire thing, really, and see what @luhenry did here:

```
#if defined(_MSC_VER) && (_MSC_VER < 1910)
#define g_assertf(x, format, ...) (G_LIKELY((x)) ? 1 : (g_assertion_message ("* Assertion at %s:%d, condition `%s' not met, function:%s, " format "\n", __FILE__, __LINE__, #x, __func__, __VA_ARGS__), 0))
#else
#define g_assertf(x, format, ...) (G_LIKELY((x)) ? 1 : (g_assertion_message ("* Assertion at %s:%d, condition `%s' not met, function:%s, " format "\n", __FILE__, __LINE__, #x, __func__, ##__VA_ARGS__), 0))
#endif
```

Also I don't think the intermediate have_iso_varargs is needed.
Also in the  config.h you can just say `#if @foo@`,  you don't need `#if @foo@ == 1`.

**Comment by jaykrell** [comment]
Or if the parameters end up adjacent, unlike g_assertf,  just consider "format" part of "..." and just say __VA_ARGS__ to take both, with whatever comma the user put in.
The wierdness in g_assertf is justified, unlike in other places, because the parameters get split.

**Comment by jaykrell** [comment]
Fixed.
