### ISSUE TITLE
System.Reflection.Emit: ParameterBuilder.SetConstant(value) throws ArgumentException for nullable value typed parameters

### ISSUE THREAD

**Issue by stakx** [mono/mono#8597]
For example, given a `ParameterBuilder parameterBuilder` for a parameter of type `int?`, `parameterBuilder.SetConstant(42)` will throw an `ArgumentException` ("Constant does not match the defined type").

## Steps to reproduce

Compile and run the following program:

```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

class Program
{
    static void Main()
    {
        var assembly = AppDomain.CurrentDomain.DefineDynamicAssembly(new AssemblyName("Assembly"), AssemblyBuilderAccess.Run);
        var module = assembly.DefineDynamicModule("Module");
        var type = module.DefineType("Type", TypeAttributes.Public | TypeAttributes.Abstract | TypeAttributes.Interface);
        var method = type.DefineMethod("Method", MethodAttributes.Public | MethodAttributes.Abstract | MethodAttributes.Virtual, typeof(void), new[] { typeof(int?) });
        var parameter = method.DefineParameter(1, ParameterAttributes.Optional | ParameterAttributes.HasDefault, "arg");
        parameter.SetConstant(42);
    }
}
```

### Current behavior

The call to `parameter.SetConstant` fails with a `System.ArgumentException` ("Constant does not match the defined type").

### Expected behavior

The call to `ParameterBuilder.SetConstant` should succeed (as it does on the CLR and CoreCLR) because 42 is a valid value for an `int?`-typed parameter.

## Platform on which I noticed this

[ ] macOS
[ ] Linux
[X] Bash on Ubuntu on Windows subsystem of Windows 10 (Ubuntu 16.04.4 LTS)

**Version used**:

Mono 5.10.1.47

## Stacktrace

```
System.ArgumentException: Constant does not match the defined type.
  at System.Reflection.Emit.ParameterBuilder.SetConstant (System.Object defaultValue) [0x0004c]
  at Program.Main()
```

**Comment by lambdageek** [comment]
@stakx Thanks for reporting all of these!

This one is related to #8504, but whereas that one is about initializing a Nullable to `null`, this one is about initializing a Nullable to non-`null`.

**Comment by stakx** [comment]
@lambdageek - You're welcome.

I should perhaps have submitted just one issue for both cases... sorry for that. I've discovered these two bugs on different days while working on different aspects of a larger problem, so I didn't immediately think of the pre-existing issue during round n° 2.

**Comment by lambdageek** [comment]
So I learned something today:

```csharp
public enum E : byte { E1, E2 }
public interface Itf {
  void MyMethod (E? e = E.E2);
}
```

Let's say you wanted to create this with SRE.  Well you can't.

```csharp
   var parameterBuilder = myMethodBuilder.DefineParameter (1, ...);
   parameterBuilder.SetConstant (E.E2); // throws ArgumentException on .NET Framework
```

On .NET Framework the above throws an `ArgumentException 'E is not a supported constant type.'`

`parameterBuilder.SetConstant (null)` works for a nullable enum, however.

**Comment by stakx** [comment]
@lambdageek - (I forgot one more resource that might be helpful in testing Mono: Castle.Core has a [pretty exhaustive set of test cases](https://github.com/castleproject/Core/blob/acbf476f32f751d93c3671de72d8411e76a33b51/src/Castle.Core.Tests/DynamicProxy.Tests/ParameterDefaultValuesTestCase.cs#L244-L393) regarding parameter default values.)
