### ISSUE TITLE
DllImport (PInvoke) passes char[] to char * incorrectly on Raspbian Linux

### ISSUE THREAD

**Issue by imkow** [mono/mono#8622]
## Steps to Reproduce

1. write a c/c++ code with signature like this: 

```
extern "C" int foo(char *bfilepath, char *bfilename, int blongtime)
```

2. write a C# DllImport binding like this: 

```
[DllImport("libxxx.so", EntryPoint="foo", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
static extern int Foo(char[] afilepath, char[] afilename, int alongtime);
```

3. compile all the test code above. Invoke function Foo as following:

```
string file_path = "/home/pi/videospath";
string file_name = "test.avi";
char[] ofilepath = file_path.ToCharArray();
char[] ofilename = file_name.ToCharArray();
int flongtime = 300;
Foo(ofilepath, ofilename, flongtime);
```

### Current Behavior
after passing to native lib:
1st string is (correct): /home/pi/videospath
2nd string becoming (incorrect): test.avi/home/pi/videospath

### Expected Behavior
after passing to native lib:
2nd string should be: test.avi

## On which platforms did you notice this
Raspbian Linux for Raspberry Pi 3B

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

Linux 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux

**Version Used**:
```
Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 10:14:47 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

## Stacktrace
N/A

**Comment by jpbruyere** [comment]
Ensure your char[] array is a null terminated string before calling c func.

##### Example from mono:
```CSharp
		private static byte[] TerminateUtf8(byte[] utf8)
		{
			if (utf8.Length > 0 && utf8[utf8.Length - 1] == 0)
				return utf8;
			var termedArray = new byte[utf8.Length + 1];
			Array.Copy(utf8, termedArray, utf8.Length);
			termedArray[utf8.Length] = 0;
			return termedArray;
		}

		private static byte[] TerminateUtf8(string s)
		{
			// compute the byte count including the trailing \0
			var byteCount = Encoding.UTF8.GetMaxByteCount(s.Length + 1);
			var bytes = new byte[byteCount];
			Encoding.UTF8.GetBytes(s, 0, s.Length, bytes, 0);
			return bytes;
		}
```

**Comment by jpbruyere** [comment]
If it is immutable, yes (`const char *`). You have also to take care who own the pointer and may free it.

**Comment by luhenry** [comment]
@imkow if, instead of passing a `char[]`, you pass a `string`, do you get the same bug? A C# string is not null-terminated by default, so if you get its `char[]`, the last element will not necessarily be `\0`.

Marshalling an `char[]` will simply "fix" it in memory (so it's not moved by the GC) and pass it's address to native, and it will be up to you to figure out the length of it (by passing the length as an additional argument for example). Marshalling a `string`, on the other hand, will make sure that it's encoded correctly (UTF-8, UTF-16, etc.), and make sure that it's null-terminated before passing it to native.

**Comment by imkow** [comment]
@luhenry thx. we tested passing a string instead of char[], it works.
however, Microsoft .NET Core 2.1 (other versions not tested) is ok on the char[] case.
@vargaz @jpbruyere yes, it's caused by the missing ending '\0'.

**Comment by luhenry** [comment]
@imkow interesting that it works with `char[]` on .NET Core.

@jkotas did .NET Core did something specific to treat `char[]` in a specific manner for marshalling? Do you take the assumption that the user, when doing so, expects a null-terminated `char*` in native?

**Comment by jaykrell** [comment]
I thought System.String is always nul terminated. (And can contain embedded nuls, which much code ignores.)

**Comment by jkotas** [comment]
>  .NET Core did something specific to treat `char[]` in a specific manner for marshalling

We have not done anything specific for this. The relevant code is in `OleVariant::MarshalAnsiCharArrayComToOle`. I do not see anything that would append zero terminator to the marshaled array.

> interesting that it works with char[] on .NET Core.

I think you are just getting lucky that the byte after the marshaled array happens to be zero.
