### ISSUE TITLE
.NET 4.7.2 reference assemblies

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#8657]
The 4.7.2 version is out and we need to add it as well. This should be done together with #7859

We keep the reference assemblies in separate repo https://github.com/mono/reference-assemblies

## Steps required
- [x] Add new reference assemblies
- [x] Bump submodule reference in Mono
- [x] Add new framework to mcs/tools/xbuild/frameworks and update Makefile to ship it

**Comment by SwooshyCueb** [comment]
What's the status on this? I see it's in "Backlog." Does this mean it might be a while before 4.7.2 makes it to the preview builds?

**Comment by marek-safar** [comment]
@SwooshyCueb it means nobody is actively working on this task

**Comment by mnowosad** [comment]
Any rough estimate when Mono would incorporate the .NET 4.7.2 assembles (this year, next year)?

**Comment by marek-safar** [comment]
I think this year is realistic (or you could contribute it). Does it block you on specific APIs?

**Comment by sandyarmstrong** [comment]
I wouldn't be surprised if increased interest in this is related to twitter threads like https://twitter.com/terrajobst/status/1031999730320986112 , where the .NET team is recommending that anybody using .NET Standard 1.5 or greater from .NET Framework should be on 4.7.2.

**Comment by mnowosad** [comment]
@marek-safar Thank you for the response. We just wanted to have an idea of the expected roadmap for this task to be addressed. Currently, we are in the process of migrating our .NET components to 4.7.2. Since Mono does not have 4.7.2 assemblies yet, we may need to keep two codebases (one with 4.7 references, to run in Linux, and one with 4.7.2, to run in Windows) for the time being, which is not the ideal situation.

**Comment by akoeplinger** [comment]
@mnowosad just to clarify: you want to compile this codebase on Mono, not just run it right?

The latter is already possible since we implement the new APIs, the reference assemblies are just for compilation.

**Comment by mnowosad** [comment]
@akoeplinger Yes, we want to compile the codebase on Mono as well.

**Comment by akoeplinger** [comment]
Reopening since there's still work to do in mono/mono.

**Comment by akoeplinger** [comment]
@henricm if you need some pointers you can take a look at https://github.com/mono/mono/pull/5974
