### ISSUE TITLE
Scrambled mcs console output on big endian (ppc64be and s390x)

### ISSUE THREAD

**Issue by NattyNarwhal** [mono/mono#8679]
## Steps to Reproduce

1. Build Mono with a new monolite to bootstrap
2. Watch the scrambled output trying to build basic-profile-check

### Current Behavior

Scrambled output

### Expected Behavior

Mono would start bootstrapping corlib

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows
[X] AIX

Commits between April 25th (when the build was broken for PPC and z) and today are suspect; though mostly anything involving text encoding?

**Version Used**:

Latest master, though bisecting works.... until you try to use a newer monolite.

## Stacktrace

This is deterministic; it will output the same.

```
*** The runtime 'mono' doesn't appear to be usable.
*** Trying the 'monolite-linux/1051500005' directory.
mono_thread_internal_set_priority: pthread_setschedparam failed, error: "Operation not permitted." (1)
buli/docmmnob/sacip-orifelc-ehkcc.(s,1)0 :reor rSC5152 :nUxeeptcdes myob lu`nsiyS'
buli/docmmnob/sacip-orifelc-ehkcc.(s813,:)e rrroC 0S85:9I tnrean locpmliree rrrod runi gapsrniSgsyet.moFmrtaxEectpoi:nI pntus rtni gaw son tnia c roertcf roam.t
a  tyStsmeN.mueb.raPsrDeuolb eS(syet.mtSirgnv laeu ,yStsmeG.olabilazitnoN.muebSrytel spoitno,sS syet.mlGbolazitaoi.nuNbmreoFmrtanIofn mumf)t[ x00080]fi  nd<262689a09849cfa360cb9320ceeb26>e0:
   taS syet.moDbuelP.raes( yStsmeS.rtni g,sS syet.mlGbolazitaoi.nuNbmretSlyses ytel ,yStsmeG.olabilazitnoN.muebFrroamItfn oniof )0[0x0000 ]ni< 6d6292088a99f43c0ab63c09e2bc6ee2:> 0
a  tyStsmeD.uolb.eaPsr eS(syet.mtSirgns  ,yStsmeG.olabilazitnoN.muebSrytel stsly,eS syet.mFIroamPtorived rrpvodire )0[0x00e0 ]ni< 6d6292088a99f43c0ab63c09e2bc6ee2:> 0
a  toMonC.hSra.poTekinez.rdaujtsr_ae lS(syet.myTepoCedt  ,oMonC.hSra.poLacitnol co )0[0x003f ]ni< 885e396fe54844f1b86247b27398dcc5:> 0
a  toMonC.hSra.poTekinez.rsin_mueb rS(syet.mnI3t 2,cS syet.moBloae nodLtae)d[ x000d2]4i  n8<e895f3568e44148f2b76243b87c95d>c0:
   taM no.oSCahprT.konezirex.otek n)([ x0000b]2i  n8<e8953f658e44148f2b76243b87c95d>c0:
   taM no.oSCahprT.koneziret.kone(  )0[0x0000 ]ni< 885e396fe54844f1b86247b27398dcc5:> 0
a  toMonC.hSra.pSCahpraPsrrey.pyraes( oMonC.hSra.pyyaPsrrey.Iypntuy Lyxe )0[0x005f ]ni< 885e396fe54844f1b86247b27398dcc5:> 0
a  toMonC.hSra.pSCahpraPsrrep.raes(  )0[0x0082 ]ni< 885e396fe54844f1b86247b27398dcc5:>0
Copmlitaoi naflide : 2reor(r)s , 0awnrings
gmake[8]: *** [build/profiles/basic.make:118: build/deps/basic-profile-check.exe] Error 1
*** The contents of your 'monolite-linux/1051500005' directory may be out-of-date
*** You may want to try 'make get-monolite-latest'
gmake[8]: *** [build/profiles/basic.make:100: do-profile-check-monolite] Error 1
gmake[7]: *** [build/profiles/basic.make:76: do-profile-check] Error 2
gmake[6]: *** [build/profiles/basic.make:112: do-profile-check-monolite] Error 2
gmake[5]: *** [build/profiles/basic.make:76: do-profile-check] Error 2
gmake[4]: *** [Makefile:54: profile-do--basic--all] Error 2
gmake[3]: *** [Makefile:50: profiles-do--all] Error 2
gmake[2]: *** [Makefile:611: all-local] Error 2
gmake[2]: Leaving directory '/opt/monodev/mono/runtime'
gmake[1]: *** [Makefile:551: all-recursive] Error 1
gmake[1]: Leaving directory '/opt/monodev/mono'
gmake: *** [Makefile:481: all] Error 2
```

**Comment by NattyNarwhal** [comment]
Problem commit has been traced back to mono/mono@080e0b4; CI didn't catch it because the z and PPC builds were broken from tailcall.

Mono had fixed these, but that commit regressed:

> Alexander Köplinger @akoeplinger 
> 11:47
> ah, turns out that's because we fixed referencesource: mono/mono@92cec46 and mono/mono@1f9b218

**Comment by akoeplinger** [comment]
@EgorBo could you please take a look? we missed porting 92cec46 and 1f9b218 (and possible others? didn't check) when moving to the corefx Encoding.

**Comment by nealef** [comment]
Is tailcall still broken on Z? I haven't had a chance to build in a couple of weeks so may have missed the breakage.
This type of problem happened a couple of years ago and may be in bugzilla in case it's a repeat.

**Comment by NattyNarwhal** [comment]
I think tailcall got fixed, but the endianness bug got created and CI never got it due to tailcall preventing builds on z in the meantime.

Once I get the CoreFX on AIX stuff merged (I hope real soon) and it builds, I'll try to work on backporting those patches myself.

**Comment by NattyNarwhal** [comment]
corefx/coreclr#18254 got merged. Once it propagates, could @EgorBo cherry pick it into the fork and update submodules?

**Comment by NattyNarwhal** [comment]
It's merged in. Once a new monolite is spat out, z should light up on CI again.

**Comment by NattyNarwhal** [comment]
z seems to be building again. Once dotnet/corefx#30012 gets cherry picked I can try on ppc64be.

**Comment by marek-safar** [comment]
@NattyNarwhal could you port configure.cmake changes to Mono configure before we pull the changes?

**Comment by NattyNarwhal** [comment]
Closing because z and ppc64be seem to be fixed now.

**Comment by nealef** [comment]
2018-06 still seems to suffer from this. I checked out the 2018-06 branch a couple of days ago and the MCS build failed with the same symptoms.
