### ISSUE TITLE
sgen crash with embedded runtime

### ISSUE THREAD

**Issue by rokups** [mono/mono#8697]
## Steps to Reproduce

1. Install following packages: `mono llvm clang`. Note that this is graphics application and testing is not possible on headless system.
2. `git clone --recursive https://github.com/rokups/Urho3D-SampleProject`
3. `cd Urho3D-SampleProject`
4. `./CMake.sh`, it will build everything
5. Open `ManagedTargets.sln` and compile
6. Run `build/bin/Editor`
7. Wait 5 minutes

### Current Behavior

Application runs fine for several minutes, then crashes with message:

> * Assertion: should not be reached at sgen-scan-object.h:91

### Expected Behavior

Application should continue running.

## On which platforms did you notice this

Archlinux

**Version Used**:
```
% mono --version
Mono JIT compiler version 5.10.1 (makepkg/8eb8f7d5e74 Fri Apr 20 23:19:11 CEST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

## Details

Application is pretty big therefore i put together a list of files that you may find interesting while tracking down the issue:

* Binding code: `dep/Urho3D/Source/CSharp/CSharp/Urho3D/Native/Object.cpp`
* Binding code: `dep/Urho3D/Source/CSharp/CSharp/Urho3D/CSharp/Core/Object.cs`
* Code that sets up embedded mono instance: `dep/Urho3D/Source/Urho3D/Script/ScriptSubsystem.cpp`
* Code that invokes plugin: `dep/Urho3D/Source/Tools/Editor/Plugins/PluginManagerManaged.cpp`
* Managed plugin executed by native code: `EpmSampleManagedPlugin/EditorPlugin.cs`

`Object.cs` contains static method `HandleEventWithoutType(...)`. This method is invoked by native code periodically. You should see "Managed Plugin Example" menu item in application menu bar. It is rendered by C# code.

Commenting `callback.Invoke(...` in `HandleEventWithoutType(...)` method prevents application from crashing.

**Comment by migueldeicaza** [comment]
A crash in SGen indicates that you corrupted the managed heap, it is usually a mistake in your binding.

You will need to narrow this problem down on your end, it is not likely a Mono bug, but a bug in the way that you are managing your code.

**Comment by rokups** [comment]
I was pretty sure this is my mistake but i was advised in mono gitter room otherwise. Thank you for clarification and sorry for the noise.
