### ISSUE TITLE
FileSystemWatcher only works for one instance

### ISSUE THREAD

**Issue by Therzok** [mono/mono#8712]
## Steps to Reproduce

1. Create a FSW
2. Create another FSW

### Current Behavior

Whatever configuration you have, the 2nd one does not work when `EnableRaisingEvents` is set to true.

### Expected Behavior

It works

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.14.0.54 (2018-04/599f3dd3afe Mon Apr 23 13:22:00 EDT 2018)

See https://github.com/mono/mono/blob/master/mcs/class/System/System.IO/FileSystemWatcher.cs#L120

`watcher` is a static variable, and when the first watcher is initialized, any other FSW other than the first fails to initialize as the initialization method is exited

**Comment by Therzok** [comment]
cc @alexischr @luhenry

**Comment by luhenry** [comment]
@alexischr could you please take a look at it?
