### ISSUE TITLE
MonoAndroid5.0 does not load .net40 packages correctly built in new VS2017 format

### ISSUE THREAD

**Issue by mishra14** [mono/mono#8724]
_From @generik0 on May 15, 2018 8:27_

Please read the following information before posting the issue.

## Details about Problem

NuGet product used from: VS 2018 15.7.1

## Detailed repro steps so we can see the same problem

1. I have a .net standard template C# project that has <TargetFrameworks>net40;net45;netstandard1.6;netstandard2.0</TargetFrameworks>

2. The csproj uses NLog but has target "ItemGroup Condition" saying the net4 should use NLog 4.3.3 but net standard use Version <Version>4.5.4</Version>

3. When the packages is loaded intro a monoandroid5 , that should use net40 i would beleive, it trys to load dependancy 4.5.4. 

I have added into the csproj
<PackageTargetFallback>net40</PackageTargetFallback>
<DisableImplicitAssetTargetFallback>true</DisableImplicitAssetTargetFallback>
but this does not help

- Should monoandroid not load net40 framework? it does not support .net standard?
- Why is the package manager loading the incorrect dependency version?
- Is there a better way to insure Monoandroid 5 when creating packages using new VS2017 .net standardard tempate?

csproj included in zip

[Comapny.Common.Core.zip](https://github.com/NuGet/Home/files/2003999/Comapny.Common.Core.zip)

_Copied from original issue: NuGet/Home#6933_

**Comment by mishra14** [comment]
NuGet does not have any specific behavior for MonoAndroid5.0. Please let us know if you think this is not the best place.

**Comment by generik0** [comment]
Hi @mishra14
So it is nit Nuget That tries to install the incorrect dependancy version?
Should it not Fall back to net4 dependancies?

**Comment by marek-safar** [comment]
> When the packages is loaded intro a monoandroid5 , that should use net40 i would beleive, it trys to load dependancy 4.5.4.

That's correct if you look inside 4.5.4 nuget version of NLog it has a special version for monoandroid44 which means any Xamarin Android newer than 4.4 will pick it up, see https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/nuget-manual for further details
