### ISSUE TITLE
CookieContainer and expiration date

### ISSUE THREAD

**Issue by MihaMarkic** [mono/mono#8743]
## Steps to Reproduce

1. Use HttpClient with a CookieContainer.
2. Set client application clock i.e. 1 hour in future.
3. Send a request to server which returns a cookie with server's current date and expiration time 30 minutes from that date.

### Current Behavior

Client's cookiecontainer will consider cookie as expired as client's time is hour in future and cookie's expiration date was half hour ago from client's perspective. Even though server issued a 30minutes expiration timespan.

### Expected Behavior

Perhaps cookiecontainer could take cookie's date (which is server's date) into consideration, calculate relative expiration timespan (cookie.expiration - cookie.date) and use client's current time+calculated timespan.
This way clients with time off would handle such cookie expirations without problems.

## On which platforms did you notice this

[x] Xamarin
[ ] Linux
[ ] Windows

**Version Used**:

Xamarin 4.10.0.442

Note, while I noticed this on Xamarin, it applies to all mono based code I think.

**Comment by baulig** [comment]
This is actually the correct behavior and it would also feel very odd to make some kind of advanced calculations based on the assumptions that the client has set its clock to some weird value that does not align with the rest of the world.

Check this out:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie - it says 

> When an expiry date is set, the time and date set is relative to the client the cookie is being set on, not the server.
