### ISSUE TITLE
Build of Master fails with GCC 4.4.7

### ISSUE THREAD

**Issue by rjvdboon** [mono/mono#8759]
## Steps to Reproduce

1. Clone mono/master on a rhel6.x/centos 6.x machine with GCC 4.4.7 as the default compiler
2. configure and make
3. observe build failure

### Current Behavior

Build fails as GCC 4.4.7 does not understand `_Static_assert`

### Expected Behavior

`make` succeeds OR `configure` reports that the GCC version is not supported and you need at least GCC 4.7.x.

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:

```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
```

## Stacktrace

Offending lines in [method-to-ir.c](https://github.com/mono/mono/blob/master/mono/mini/method-to-ir.c#L6294):
```
#ifndef _MSC_VER
_Static_assert (sizeof (float) == 4, "");
_Static_assert (sizeof (double) == 8, "");
#endif
```

**Comment by jaykrell** [comment]
Sorry about that. We don't CI that.
https://github.com/mono/mono/pull/8760

**Comment by rjvdboon** [comment]
Well, that was quick!
Note that I don't really mind if GCC 4.4.7 is deprecated (as was suggested in my previous "doesn't compile on gcc 4.4.7" issue #8572), it might even be the best way forward.
My issue is mainly that this requirement should be explicit, instead of failing during make.
