### ISSUE TITLE
Provide checksums for all files

### ISSUE THREAD

**Issue by einsteinsfool** [mono/mono#8768]
## Steps to Reproduce

1. Download a file from the [download page](http://www.mono-project.com/download/stable).
2. Don't verify the file because there are no checksums.
3. Get the package intercepted by an attacker and have it swapped with a malicious modified version.
4. Get ~~f...~~ hacked. (couldn't resist)

### Current Behavior

No checksums.

### Expected Behavior

SHA512 and SHA256 for every file on the [file server](https://download.mono-project.com/archive) in plaintext (.txt extension) so users dont have to download the file (like with e.g. .sha256 extension) because downloading the checksum defeat its purpose as the attacker can also modify the checksum.

Also, on the [download page](https://www.mono-project.com/download/stable) there should be either SHA256 or SHA512 for the newest files for easy access.

[MD5](https://en.wikipedia.org/wiki/MD5#Security) and [SHA1](https://en.wikipedia.org/wiki/SHA-1#SHAttered_%E2%80%93_first_public_collision) are broken and shouldn't be provided because they give false sense of security.

**Comment by migueldeicaza** [comment]
The files are hosted on an https:// server, I do not understand the attack scenario and how hosting a separate file would help.

We should be signing the packages, at least I know we do for OSX.   So this does not seem like something that would actually prevent anything.

**Comment by einsteinsfool** [comment]
> The files are hosted on an https:// server, I do not understand the attack scenario and how hosting a separate file would help.

I agree. But if someone downloaded the package from GitHub then checksum from the official page would be useful. Providing a checksum on GitHub in each release description would help on the other hand with verifying files from the official website.
A nice idea would be to put all checksums in one file on the file server for each release and upon release add it to [Internet archive](https://web.archive.org). That way people could check if the checksums are the same when they want to download some file.

> We should be signing the packages, at least I know we do for OSX. So this does not seem like something that would actually prevent anything.

Yes, signing is my 2nd suggestion which I give after checksums.
