### ISSUE TITLE
Timeout in HttpWebRequest.GetResponse() when called repeatedly

### ISSUE THREAD

**Issue by AlexRixhardson** [mono/mono#8775]
## Steps to Reproduce

1. Create a web app which calls HttpWebRequest.GetResponse() repeatedly
2. Run app on Mono 5.12 + Apache + CentOS 7 configuration

### Current Behavior

Calls to GetResponse() will eventually stop working and will fail with:

```
The operation has timed out., Stack Trace:   at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000ba] in <93075ab5c03242e39aa9261622b472b8>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.GetResponse () [0x00013] in <93075ab5c03242e39aa9261622b472b8>:0 
```

App does not recover. Restart of the Mono process is required.

### Expected Behavior

GetResponse() method not to fail if called repeatedly

### Sample Code

The following code must be repeatedly called for the bug to start occurring:

```
            Uri myUri = new Uri(...);
            WebRequest myWebRequest = HttpWebRequest.Create(myUri);
            HttpWebRequest request = (HttpWebRequest)myWebRequest;

            request.Method = "GET";
            request.ContentType = "application/json; charset=utf-8";

            using (Stream s = request.GetResponse().GetResponseStream())
            {
                using (StreamReader sr = new StreamReader(s))
                {
                    var jsonData = sr.ReadToEnd();
                    return;
                }
            }
```

## On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.12.0.233 (tarball Tue May  8 09:28:02 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

```

## Stacktrace

```
The operation has timed out., Stack Trace:   at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000ba] in <93075ab5c03242e39aa9261622b472b8>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.GetResponse () [0x00013] in <93075ab5c03242e39aa9261622b472b8>:0 
```

**Comment by smr888** [comment]
I have never done what you are doing quite that way . . . I find myself wondering if the HttpWebResponse you are creating with your call to request.GetResponse() is ever being closed, which it needs to be.  I'm not sure the using(Stream s . . .  would do so. I think it just closes the stream, but not the response.

Anyway, just to see what happens you could try it like this, which is similar to what we do all the time:

```C#
using (HttpWebResponse response = request.GetResponse())
{
    if (response == null)
         return;  // or whatever is appropriate
    using (StreamReader sr = new StreamReader(response.GetResponseStream()))
    {
        var jsonData = sr.ReadToEnd();
        return;
    }
}

and see if that makes any difference.

**Comment by shnaz** [comment]
Any progress on this? Or maybe a workaround? :)

**Comment by shnaz** [comment]
Is there a workaround to this? I would appreciate any feedback. :)

**Comment by shnaz** [comment]
@DragonTM Thanks for the help! 
I too had to downgrade the Xamarin.Android and Xamarin.iOS before it helped .

**Comment by DragonTM** [comment]
@shnaz you are right

**Comment by DragonTM** [comment]
@akoeplinger @marek-safar Any updates?

**Comment by marek-safar** [comment]
I cannot reproduce it with simple repro I made, do you have something you can share for us to try to reproduce it locally?

**Comment by AlexRixhardson** [comment]
> Is there a workaround to this? I would appreciate any feedback. :)

Nope. Had to downgrade the Mono version.

**Comment by hdornemann** [comment]
Are you still seeing this issue if you upgrade to mono 5.16?  I believe that I was hitting this same issue and it stopped happening after switching to 5.16.

**Comment by DragonTM** [comment]
I have updated to the latest version and still experience the issue

**Comment by DragonTM** [comment]
I have found an issue on my side. I had HttpContent objects that weren't disposed after some time and it caused this issue. I don't know how it is related to the mono version.
