### ISSUE TITLE
Performance of mono for WebAssembly is extremely poor (~200x slower than on desktop)

### ISSUE THREAD

**Issue by a-student** [mono/mono#8776]
It is stated [here](https://webassembly.org) that
> WebAssembly aims to execute at native speed

Therefore, **mono-wasm** is expected to perform nearly the same as on desktop. Unfortunately, mono for WebAssembly is far away in performance than expected, it is on average 200x slower.

Consider this code:
```C#
var sw = Stopwatch.StartNew();
var a = Math.PI;
for (var i = 0; i < 1080; i++) {
    for (var j = 0; j < 1000000; j++) {
        a += Math.PI;
    }
}
Console.WriteLine("Elapsed " + sw.Elapsed);
```
It prints
`Elapsed 00:00:00.9990513` when running in **.NET Core**
`Elapsed 00:00:02.9962702` when running in **mono** on desktop
`Elapsed 00:21:38.9038000` when running in **mono-wasm** (Google Chrome browser). This is >400x slower than mono on desktop!

The same code in JavaScript shows almost the same performance as in .NET Core:
```JavaScript
let t = performance.now();
let a = Math.PI;
for (let i = 0; i < 1080; i++) {
    for (let j = 0; j < 1000000; j++) {
        a += Math.PI;
    }
}
t = performance.now() - t;
console.log("Elapsed " + t + " milliseconds");
```
It prints
`Elapsed 1179.1999999986729 milliseconds`

By the way, mono-wasm in the latest Firefox shows better performance than in Chrome (`Elapsed 00:01:13.5770000`), but still very slow on average.

So my questions are:
1. Why **mono-wasm** is too slow?
2. Is it possible to tune its performance somehow?

My environment:
Hardware: ThinkPad X1 Carbon (2nd Gen), CPU: 4th Gen Intel® Core™ i7-4600U (3.30GHz 1600MHz 4MB)
OS: Windows 10 Pro 64-bit 1803
Browser: Google Chrome 66.0.3359.181 (Official Build) (64-bit)
Mono-wasm from [this package](https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Build/0.3.0)
Mono for desktop version 5.12.0 Stable (5.12.0.226) 64-bit
.NET Core version 2.1.300-preview2-008533

**Comment by danroth27** [comment]
@kumpera

Yes, our current runtime an unoptimized interpreter. Significant slowdown compared to peak desktop perf is expected at this point given the experimental nature of Blazor and the underlying bits.

We hope to really start seeing the perf benefits of WebAssembly when we have support for [static ahead-of-time (AoT) compilation to WebAssembly for .NET](http://www.mono-project.com/news/2018/01/16/mono-static-webassembly-compilation/), but that's still being worked on.

Closing this as the main perf feedback is most relevant to the Mono team.

**Comment by a-student** [comment]
I get this error on the `Console.WriteLine` line with the `--interpreter` option:
```
* Assertion at ..\mono\mini\interp\interp.c:3770, condition `csig->call_convention == MONO_CALL_DEFAULT' not met
```

Total execution time of the program is less than a minute:
`Measure-Command {mono --interpreter ConsoleApp1.exe}` prints
TotalSeconds      : 59.2384914
That is close to Firefox performance. Therefore, it is something wrong in Chrome.

Anyway, such poor performance won't make mono-wasm popular for the real world applications. JavaScript is also interpreted language but it shows much faster performance, close to .NET Core.

**Comment by lewurm** [comment]
Regarding the assertion you hit on desktop: this was fixed a few weeks ago, you need a newer mono: https://github.com/mono/mono/issues/8329#issuecomment-383146748

There are some performance related differences between browsers, you should try Edge too.

There is [AOT compilation](http://www.mono-project.com/news/2018/01/16/mono-static-webassembly-compilation/) in the pipeline which should improve performance significantly. It's more complicated than an interpreter to implement, so it takes longer 🙂

**Comment by a-student** [comment]
Unfortunately, mentioned in the article [AOT compilation project](https://github.com/lrz/mono-wasm) seems to be dead - no commits for almost 4 months :(

**Comment by migueldeicaza** [comment]
It is actively being worked on, just not on that branch as we had to do major surgery, we should have something soon.

**Comment by a-student** [comment]
@migueldeicaza thank you for the response.
1) What is the reason of closing this issue? If AOT compilation will totally replace the current interpreter - ok, otherwise you need to do something with it.
2) Are you actively working on AOT compilation? Are there alpha, beta releases we can test? Is repository public?
3)
> something soon

It would be great if you define more specific deadline: a month, a week, a year...
