### ISSUE TITLE
LLVM 6.0 JIT (not AOT) problem?

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8778]
## Steps to Reproduce

1. checkout monollvm release_60
2. run any program with --llvm (JIT)

### Current Behavior

   Expected<T> must be checked before access or destruction.
    Expected<T> value was in success state. (Note: Expected<T> values in success mode must still be checked prior to being destroyed).
    Stacktrace:
    
    Native stacktrace:
    
        0   mono                                0x00000001028a00e8 mono_handle_native_crash + 264
        1   libsystem_platform.dylib            0x00007fffb3ca2b3a _sigtramp + 26
        2   mono                                0x0000000105217860 _ZZN4llvm4dbgsEvE7thestrm + 0
        3   libsystem_c.dylib                   0x00007fffb3b27420 abort + 129
        4   mono                                0x00000001028f1892 _ZNK4llvm8ExpectedINSt3__115__list_iteratorINS1_10unique_ptrINS_3orc28RTDyldObjectLinkingLayerBase12LinkedObjectENS1_14default_deleteIS6_EEEEPvEEE22fatalUncheckedExpectedEv + 226
        5   mono                                0x00000001028edd86 _ZN11MonoLLVMJIT9addModuleEPN4llvm8FunctionENSt3__110shared_ptrINS0_6ModuleEEE + 246
        6   mono                                0x00000001028ecd70 _ZN11MonoLLVMJIT7compileEPN4llvm8FunctionEiPP15LLVMOpaqueValuePPvS7_ + 304
        7   mono                                0x00000001028d79a5 emit_method_inner + 12165
        8   mono                                0x00000001028d47d1 mono_llvm_emit_method + 849
        9   mono                                0x00000001027f10ae mini_method_compile + 878

### Expected Behavior

Success

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Comment by jaykrell** [comment]
See https://github.com/mono/mono/pull/8779.

**Comment by vargaz** [comment]
Fixed by the PR above.
