### ISSUE TITLE
Overlay Elements freeze up: setting Breakpoints in Large Loops

### ISSUE THREAD

**Issue by gamesguru** [mono/mono#8781]
## Steps to Reproduce

1. Set breakpoints and launch windows form app or console app from debugger.
2. Windows forms breakpoints can be at combobox index changed event, console app is best inside of some nested for loop with large data structures.

### Current Behavior

1. On the Console app set breakpoints and investigate the values of some large array inside nested loops.

When displaying variable values, the debugger's on-demand tooltip occasionally freezes up the IDE in a way which _killall mono_ does not resolve, but which clicking around patiently and maybe closing shown dialogues sometimes does.

2. On the Windows form app, have the combobox event trigger some for loop or remote function.  Don't forget your breakpoints.

With luck the combobox will become stuck on top of everything, the whole linux kernel.  _killall mono_ works here

### Expected Behavior

More reliable behavior without elements or forms freezing on top of each other.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

7.5 build 1255, from Synaptic Package Manager

## Stacktrace

Need pointers on collecting error samples as the monodevelop logs are lacking

**Comment by marek-safar** [comment]
This issue was moved to mono/monodevelop#4872
