### ISSUE TITLE
Exceptions should be avoided  except in truly exceptional conditions,  i.e. not merely starting up.

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8804]
I'm  debugging something, anything.
I set breakpoint on mono_handle_exception.
I don't want to see anything unrelated to what I'm debugging.

But starting up on Linux we raise and catch exceptions related to timezone.

This is LLVM AOT but probably not relevant,  except for the better debugging.

(gdb) bt 9
#0  mono_handle_exception (ctx=0x7fffffffcd50, obj=0x7ffff5d0ff50) at mini-exceptions.c:2600
#1  0x00005555557bc83c in mono_amd64_throw_exception (dummy1=<optimized out>, dummy2=<optimized out>, 
    dummy3=<optimized out>, dummy4=<optimized out>, dummy5=<optimized out>, dummy6=<optimized out>, 
    mctx=0x7fffffffcf20, exc=0x7ffff5d0ff50, rethrow=0) at exceptions-amd64.c:401
#2  0x00007ffff3ad6804 in throw_exception () from /s/mono/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#3  0x00007ffff3ace4be in wrapper_managed_to_native_System_TimeZoneInfo_readlink_string_byte___int ()
   from /s/mono/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#4  0x00007ffff390e157 in System_TimeZoneInfo_readlink_string ()
   from /s/mono/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#5  0x00007ffff35226e2 in System_TimeZoneInfo_get_TimeZoneDirectory ()
   from /s/mono/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#6  0x0000555556345ae0 in ?? ()
#7  0x0000000000000000 in ?? ()
(gd

**Comment by marek-safar** [comment]
See #8805
