### ISSUE TITLE
Line numbers in  Linux AOT (LLVM) debugging (Linux)?

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8805]
I'm debugging something.
It is AOT LLVM.
I'd like to see line numbers in the C# that is LLVMAOTed.
lldb didn't work at all btw, so using gdb.

(gdb) bt
#0  mono_handle_exception (ctx=0x7fffffffc020, obj=0x7ffff5d73320) at mini-exceptions.c:2600
#1  0x00005555557bc83c in mono_amd64_throw_exception (dummy1=<optimized out>, dummy2=<optimized out>, 
    dummy3=<optimized out>, dummy4=<optimized out>, dummy5=<optimized out>, dummy6=<optimized out>, 
    mctx=0x7fffffffc1f0, exc=0x7ffff5d73320, rethrow=0) at exceptions-amd64.c:401
#2  0x00007ffff3ad6804 in throw_exception () from /s/mono/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#3  0x00007ffff26e995e in System_Xml_Serialization_XmlCustomFormatter_FromEnum_long_string___long___string ()
   from /s/mono/mcs/class/lib/testing_aot_full/System.Xml.dll.so
#

**Comment by marek-safar** [comment]
@jaykrell Please report issues in the way **anyone** can work on and QA possibly verify. This one is just not good enough
