### ISSUE TITLE
System.Native does not build on Master with compiler without static_assert and _Static_assert

### ISSUE THREAD

**Issue by rjvdboon** [mono/mono#8815]
## Steps to Reproduce

1. Clone Master on a system with an old GCC (Centos6 with gcc 4.4.7 will do)
2. ./autoconf
3. make

### Current Behavior

make fails with:
```
../../doltlibtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -I../.. -I../../mono -I../../libgc/include -I../../mono/eglib -I../../mono/eglib -fvisibility=hidden -Wall -Wunused -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes  -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Wno-format-zero-length  -DGC_LINUX_THREADS -D_GNU_SOURCE -D_REENTRANT -DUSE_MMAP -DUSE_MUNMAP -g -DLARGE_CONFIG  -DUSE_COMPILER_TLS -I/glb/home/nlrvmp/scratch/mono/mono-git/external/corefx/src/Native/Unix/Common -I/glb/home/nlrvmp/scratch/mono/mono-git/external/corefx/src/Native/Unix/System.Native -Wno-typedef-redefinition -Wall -Wunused -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes  -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Wno-format-zero-length -g -O2 -std=gnu99 -fno-strict-aliasing -fwrapv -DMONO_DLL_EXPORT -Wno-unused-but-set-variable -g -mno-tls-direct-seg-refs -Werror-implicit-function-declaration -MT ../../external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.lo -MD -MP -MF ../../external/corefx/src/Native/Unix/System.Native/.deps/libmono_system_native_la-pal_io.Tpo -c -o ../../external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.lo `test -f '../../external/corefx/src/Native/Unix/System.Native/pal_io.c' || echo './'`../../external/corefx/src/Native/Unix/System.Native/pal_io.c
../../external/corefx/src/Native/Unix/System.Native/pal_io.c:53: error: redefinition of typedef ‘__c_static_assert__’
../../external/corefx/src/Native/Unix/System.Native/pal_io.c:52: note: previous declaration of ‘__c_static_assert__’ was here
[snipped lots of similar errors....]
../../external/corefx/src/Native/Unix/System.Native/pal_io.c:142: error: redefinition of typedef ‘__c_static_assert__’
../../external/corefx/src/Native/Unix/System.Native/pal_io.c:138: note: previous declaration of ‘__c_static_assert__’ was here
cc1: warning: unrecognized command line option "-Wno-typedef-redefinition"
make[3]: *** [../../external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_io.lo] Error 1
```

### Expected Behavior

Build succeeds _or_ configure errors on a too old GCC.

## On which platforms did you notice this

[ ] macOS
[ x ] Linux
[ ] Windows

**Version Used**:

```
$ gcc --version|head -1
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
```

## Additional info

It is probably caused by line 25 in [pal_compiler.h](https://github.com/dotnet/corefx/blob/a5eb6c3a3a6678906a15e70701ce1ffaa2846fea/src/Native/Unix/Common/pal_compiler.h#L25) combined with the `-Wno-typedef-redefinition` compiler flag.

Instead of fixing the code or makefiles to compile, it might make more sense to drop support for old compilers.

**Comment by marek-safar** [comment]
@migueldeicaza @directhex any objections to bump the GCC min version?

**Comment by directhex** [comment]
I have no objections to 4.8 as a baseline minimum. It is not available in base CentOS 6, but is available via "Developer Toolset" - https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/6/html/user_guide/

We already use devtoolset to compile for CentOS 6, to enable building BTLS (which needs C++11 support)

**Comment by migueldeicaza** [comment]
I do not mind adding the additional compiler requirement, but perhaps we could just define the macro static_assert to be empty for older compilers and let that run?

It looks from `mono/external/corefx/src/Native/Unix/Common/pal_compiler.h` that we could just define `static_assert` as an empty define.

**Comment by rjvdboon** [comment]
At the moment BTLS is still optional, but if #8568 goes through then BTLS is required (or you will not have any TLS on Linux/Windows).

**Comment by luhenry** [comment]
Let me submit a PR for System.Native.

**Comment by luhenry** [comment]
@rjvdboon could you verify that your problem is fixed with https://github.com/mono/mono/pull/8882?

**Comment by rjvdboon** [comment]
@luhenry No problem. It'll be after the weekend though.
And thanks for working on this one!

**Comment by rjvdboon** [comment]
Works like a charm, mono/master@a1bb39504fa builds correctly. Thanks!
