### ISSUE TITLE
`jit` profiler option crashes iOS apps

### ISSUE THREAD

**Issue by rodrmoya** [mono/mono#8866]
## Steps to Reproduce

1. Profile iOS app with `log:nodefaults,heapshot=ondemand,maxframes=8,jit,gc,gcalloc,gcroot,gcmove,counter,output=/var/folders/rd/w957krqd3rn1zps5z6r75kz00000gn/T/p6xm3z5b.mlpd`
2. See it crash almost immediately
3. Remove the `jit` option from the log... arguments, no crash

### Current Behavior

It crashes, with Xamarin.iOS with mono 5.12

### Expected Behavior

No crash

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

5.12

## Stacktrace

```Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.microsoft.SmartHotel360-df      0x00000001023560ea mono_lls_find + 26
1   com.microsoft.SmartHotel360-df      0x0000000102356220 mono_lls_insert + 32
2   com.microsoft.SmartHotel360-df      0x00000001023bb205 init_thread + 277
3   com.microsoft.SmartHotel360-df      0x00000001023b7e90 code_buffer_new + 64
4   com.microsoft.SmartHotel360-df      0x0000000102296ae6 mono_profiler_raise_jit_code_buffer + 86
5   com.microsoft.SmartHotel360-df      0x00000001021c5713 mono_arch_create_sdb_trampoline + 1139
6   com.microsoft.SmartHotel360-df      0x00000001021ac48c mini_get_breakpoint_trampoline + 60
7   com.microsoft.SmartHotel360-df      0x000000010216d24c mono_arch_init + 204
8   com.microsoft.SmartHotel360-df      0x00000001021a59a2 mini_init + 770
9   com.microsoft.SmartHotel360-df      0x00000001023abdf1 xamarin_main + 1969
10  com.microsoft.SmartHotel360-df      0x0000000102097c90 main + 80 (main.m:73)
11  libdyld.dylib                       0x00000001130fb955 start + 1```

**Comment by marek-safar** [comment]
@luhenry can we get it fixed in 2018-02?

**Comment by kumpera** [comment]
The problem here is that XI driver loads the profiler module before initing the runtime and it depends on the runtime being initialized to function.

**Comment by kumpera** [comment]
PR https://github.com/mono/mono/pull/8885
