### ISSUE TITLE
msbuild msvc/mono.sln does not build mkbundle.exe.

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#8894]
## Steps to Reproduce

1.  msbuild msvc\mono.sln

### Current Behavior

No mkbundle.exe produced.

### Expected Behavior

mkbundle.exe produced.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Comment by akoeplinger** [comment]
mkbundle is a managed tool so I wouldn't expect it to be built by the runtime solution file. We should add it to bcl.sln though.

**Comment by jaykrell** [comment]
I don't care which sln/proj does it, but I think there should be something that does.
And probably a sln that ties stuff together, i.e. runtime + bcl + tools + maybe tests (building them, maybe not running them -- there should be some knobs but I'm not sure what they should all be).

**Comment by marek-safar** [comment]
It should be in bcl solution already. @kg could you double check that?

**Comment by jaykrell** [comment]
I didn't realize there were other sln files, I thought just mono.sln.
That looks right.

$ grep -i mkbundl *sln
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "mkbundle", "mcs/tools/mkbundle/mkbundle.csproj", "{86B79F77-3DDC-4E2F-8CA8-E392E040366A}"
