### ISSUE TITLE
It would be a good idea to link the "make a good bug report" page from CONTRIBUTING.md

### ISSUE THREAD

**Issue by mcclure** [mono/mono#8916]
This bug concerns github issues. I filed a bug report just now. It popped up a dialog saying "it looks like this is your first bug! read this:" or something and linked
https://www.mono-project.com/community/bugs/make-a-good-bug-report/
What a helpful document! I closed the window and opened an issue. After completing my bug, I wanted to check the "please include these ten things" list in the Make A Good Bug Report file. But it wasn't linked anywhere in the github issue display. There's a "Helpful Resources" link list to the right of this box I'm typing into. It links CONTRIBUTING.md and the code of conduct. CONTRIBUTING.md does not link the "good bug report" page either. Probably the link should be in one of these places.

**Comment by marek-safar** [comment]
Thank you for the suggestion. I tweaked the issue template to include the link (https://github.com/mono/mono/pull/8920)

**Comment by luhenry** [comment]
Fixed with https://github.com/mono/mono/pull/8920
