### ISSUE TITLE
Mixed mode bitcode+ interpreter

### ISSUE THREAD

**Issue by kumpera** [mono/mono#8927]
This issue tracks the technical problems and proposed solution

The problem with mixed-mode is that the interpreter is entered through a trampoline. As those are not available in bitcode, we use a function descriptor (address + extra arg) instead.

The issue with ftndescs is that the caller must know about it, meaning we must conditionally check for them at every call site and either do a direct call or setup the descriptor and make the indirect call.

**Comment by alexanderkyte** [comment]
I think that the combination of a function to call and a context to pass is universal enough to describe any closure we'll see at runtime. If we need to support the most general call option, it doesn't make sense to say 

``` 
if (mode_1) {
    call_option_one (fn);
}
if (mode_2) {
     call_option_two (fn);
}
if (mode_3) {
ftn_desc = get_tls_val ("key");
most_general_call_option (fn, ftn_desc);
}

When we can put the indirection in the choice of the fn and the ftn_desc (closure state).

In more concrete terms, what I'm suggesting is that when we have mixed-mode interpreter calls enabled, we probably should just call everything through the same interface we call the interpreter calls through.
