### ISSUE TITLE
Specific Images used by GdipCreateBitmapFromFile wrapped by Bitmap cause a fatal runtime crash with no further info

### ISSUE THREAD

**Issue by turbo** [mono/mono#8949]
## Steps to Reproduce

Use this image: https://bugzilla.xamarin.com/attachment.cgi?id=24057

Run this code:

```csharp
using System;
using System.Drawing;

namespace TestMonoMacBitmapCrash
{
    class MainClass
    {
        public static void Main(string[] args)
        {
           Bitmap bmp = new Bitmap("bitmap_crash.png");
        }
    }
}
```

This is an old, **confirmed** bug from [Bugzilla \#58613](https://bugzilla.xamarin.com/show_bug.cgi?id=58613). I'm also running into this.

### Current Behavior

Runtime crash + stack trace.

### Expected Behavior

Valid Bitmap instance.

## On which platforms did you notice this

[ ] macOS
[x] Linux, Ubuntu 16.04, 18.04
[ ] Windows

**Version Used**:

```text
Mono JIT compiler version 5.14.0.87 (tarball Sun May 20 09:45:09 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

## Stacktrace

[stack.log](https://github.com/mono/mono/files/2053403/stack.log)

**Comment by migueldeicaza** [comment]
This is caused by the image being a 2-bit greyscale, and this sets the png_palette to null, which we do not account for in the case for the 2-bit depth.

**Comment by migueldeicaza** [comment]
This is a bug in libgdiplus, moved the bug there: https://github.com/mono/libgdiplus/issues/378
