### ISSUE TITLE
Exceptions not working in dynamically loaded assemblies

### ISSUE THREAD

**Issue by bdonnahue** [mono/mono#8954]
## Steps to Reproduce

1. Dynamically load DLL
2. Call a method which throws an Exception
or
2. Invoke a method through reflection

### Current Behavior

I have an Assembly I load dynamically into the current AppDomain. If an Exception is thrown from functions/objects defined in the dynamically loaded assembly it cannot be handled by the objects defined in assemblies which are loaded through project reference. While the catch blocks etc work in the dynamically loaded library they do not catch in the other assemblies. 

### Expected Behavior

I expect an exception to be thrown

## On which platforms did you notice this

[ ] macOS
[x] Linux (CentOS 7)
[ ] Windows

**Version Used**:

5.12.0.233

**Comment by luhenry** [comment]
Could you please provide us with a sample project that reproduce the issue you are observing? Thank you.

**Comment by bdonnahue** [comment]
@luhenry you are right, more info is needed.

After digging around in the code base it seems that the DLL was being loaded into a child AppDomain with the same friendly name as the current (A bug obviously). Then for whatever reason the exception was not crossing the AppDomain boundary.

I am working on a solution composed of several projects. So posting it all is a problem but I will try if I cannot get to the root issue.

As this seems to be a bit confusing and no longer a mono issue I think this issue can be closed. Apologies for the false alarm.
