### ISSUE TITLE
Memory leak in WCF sessions handling

### ISSUE THREAD

**Issue by paulfertser** [mono/mono#8970]
This issue was diagnosed with hyperfastcgi in native listener mode but it's also present with XSP-based servers. Minimal example is provided in attachment. The end goal is running RapidSCADA and fixing this issue is essential for a reliable service.

## Steps to Reproduce

1. Configure nginx to support Mono in FastCGI mode, use ``fastcgi_split_path_info ^(.+\.(?:as.x|svc))(/?.+)$;`` to support calling *.svc functions;
2. Start a FastCGI server, e.g.
```
MONO_GC_PARAMS=max-heap-size=100m \
	MONO_OPTIONS="--debug --profile=log:heapshot=10gc,heapshot-on-shutdown" \
		hyperfastcgi4 --applications /:TestWCF/Releases/TestWcfWebPublish/ \
			--printlog --verbose  --loglevels=All \
			/config=HyperFastCgi/samples/hello-world.config
```
3. Perform 1000 requests with
```
for i in `seq 1000`; do
	wget -q -O/dev/null http://localhost/testwcf/TestSvc.svc/Sum?a=2\&b=3
done
```
4. Wait 10 minutes, stop the server, parse the profile output.

### Current Behavior

Memory leaks on every service request, see wcf-memory-leak.txt "Heap shot 1"

### Expected Behavior

No memory leaks, see wcf-memory-leak-fixed.txt.

## On which platforms did you notice this

[ ] macOS
[X] GNU/Linux
[ ] Windows

**Version Used**:

tags/mono-3.2.3-20055-g9bbe5e5e5f8 + e2e66cb4f8f11edd15e444ae7554054453f195b4

## Stacktrace

No stacktrace as this is not a crash.

[TestWCF.zip](https://github.com/mono/mono/files/2058016/TestWCF.zip)
[wcf-memory-leak.txt](https://github.com/mono/mono/files/2058014/wcf-memory-leak.txt)
[wcf-memory-leak-fixed.txt](https://github.com/mono/mono/files/2058015/wcf-memory-leak-fixed.txt)

**Comment by 2mik** [comment]
Hi,
I facing with memory leak in Mono WCF either in web applications or self-hosted console applications. In my opinion, this issue is critical because WCF is a main technology of communication between .NET applications and thus we can't guarantee reliable operating of our applications on Linux.

**Comment by sonicmouse** [comment]
I am currently on 5.12.0.226 and am having a massive amount of memory leaks when making a WCF request. Is this fix in 5.12.0.226? If so, it didn't resolve the WCF memory leak issues at all.

**Comment by 2mik** [comment]
mono-5.12.0.226 released on May 8, see https://github.com/mono/mono/releases

**Comment by sonicmouse** [comment]
Anyway -- I don't know if this went out or not on 5.12, so I updated to the pre-release 5.14.0.125 and it's still leaking on Linux (I am running on Ubuntu/Lubuntu). Just do a test server/client and do 1,000 calls on a loop and you'll see it. My profiler report looks almost identical to @paulfertser's above.

I opened up a new bug report here: https://github.com/mono/mono/issues/9207
