### ISSUE TITLE
HttpWebRequest.EndGetRequestStream throws wrong exception on abort

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#9031]
## Steps to Reproduce

1. Issue a HTTP request using HttpWebRequest class.
2. Abort the request using HttpWebRequest.Abort after HttpWebRequest.BeginGetRequestStream was called.
3. Call HttpWebRequest.EndGetRequestStream

### Current Behavior

System.Threading.Tasks.TaskCanceledException exception is thrown. Note that these APIs are present in .NET 2.0, where TaskCanceledException didn't even exist yet. Thus applications cannot be aware of this particular exception.

### Expected Behavior

WebException with status WebExceptionStatus.RequestCanceled is thrown.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.12.0.226 (2018-02/9824e260f56 Mon Apr 30 18:45:52 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

## Stacktrace

```
:35:52 PM   System.Threading.Tasks.TaskCanceledException: A task was canceled.
5:35:52 PM   at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000b5] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.5.0.280/src/Xamarin.Mac/mcs/class/System/System.Net/HttpWebRequest.cs:952 
5:35:52 PM --- End of stack trace from previous location where exception was thrown ---
5:35:52 PM   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x00018] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.5.0.280/src/Xamarin.Mac/mcs/class/System/System.Net/HttpWebRequest.cs:903 
5:35:52 PM   at MailClient.Protocols.CalDav.ProtocolCommands.RequestCommand.Execute (System.Net.HttpWebRequest httpRequest, System.Threading.CancellationToken cancellationToken, System.Action`1[T] logBody) [0x00078] in /Users/filipnavara/Desktop/svn/trunk/MailClient.Protocols.CalDav/ProtocolCommands/RequestCommand.cs:24 
```

**Comment by filipnavara** [comment]
cc @baulig

**Comment by filipnavara** [comment]
Possibly related to changes made in response to https://github.com/mono/mono/issues/7194.

**Comment by filipnavara** [comment]
Seems like the solution is to change occurrences of `throw FlattenException (...)` in HttpWebRequest to `throw GetWebException (...)`.

**Comment by filipnavara** [comment]
Turns out there's actually a test for this - `System.Net.HttpWebRequestTest.EndGetRequestStream_Request_Aborted` - but it is disabled. It fails. `BeginGetRequestStream` starts the `MyGetRequestStreamAsync` method, which successfully reaches the end before `Abort` is called. Thus the exception cannot be caught and thrown inside the `MyGetRequestStreamAsync` method.

For the sake of completeness I wrote a similar test for `EndGetResponse`:
```
		[Test]
#if FEATURE_NO_BSD_SOCKETS
		[ExpectedException (typeof (PlatformNotSupportedException))]
#endif
		public void EndGetResponse_Response_Aborted ()
		{
			IPEndPoint ep = NetworkHelpers.LocalEphemeralEndPoint ();
			string url = "http://" + ep.ToString () + "/test/";

			using (SocketResponder responder = new SocketResponder (ep, s => EchoRequestHandler (s))) {
				HttpWebRequest req = (HttpWebRequest) WebRequest.Create (url);
				req.Method = "POST";
				IAsyncResult ar = req.BeginGetResponse (null, null);
				Thread.Sleep (500);
				req.Abort ();

				try {
					req.EndGetResponse (ar);
					Assert.Fail ("#1");
				} catch (WebException ex) {
					// The request was aborted: The request was canceled
					Assert.AreEqual (typeof (WebException), ex.GetType (), "#2");
					Assert.IsNull (ex.InnerException, "#3");
					Assert.IsNotNull (ex.Message, "#4");
					Assert.IsNull (ex.Response, "#5");
					Assert.AreEqual (WebExceptionStatus.RequestCanceled, ex.Status, "#6");
				}
			}
		}
```

In the case of `EndGetResponse` a web exception is generated at the end of `MyGetRequestStreamAsync` method. That works only when the `Abort` timing is good though. Inserting a `Thread.Sleep` call makes it fail the same way as `EndGetRequestStream`.

**Comment by baulig** [comment]
I gave this some love during bug week and will have a new PR for this ready shortly.

It turns out that we already have a test for this in the web-tests, but it only tests `HttpWebRequest.GetResponseAsync()` with a `GET` request.  I extended this test to also test the synchronous and begin/end-async APIs doing both a `GET` and a `POST` request.

**Comment by baulig** [comment]
The new tests are now done:
https://github.com/xamarin/web-tests/blob/master/Xamarin.WebTests.Tests/Xamarin.WebTests.HttpInstrumentationTests/AbortDuringHandshake.cs.

You can run them with
```
$ msbuild Xamarin.WebTests.Console.sln
$ mono --debug ./Console/Xamarin.WebTests.Console/bin/Debug/Xamarin.WebTests.Console.exe --select=HttpInstrumentationTests.AbortDuringHandshake --features=+RecentlyFixed
```
