### ISSUE TITLE
Mono.CSharp.Evaluator doesn't support partial classes?

### ISSUE THREAD

**Issue by jswigart** [mono/mono#9040]
## Steps to Reproduce

1. Create a single .cs file with an empty class definition
2. Evaluator.Run it, observe it functions properly
3. Add partial to the class declaration
4. Observe it now fails to function properly, and the error returned by the reportPrinter doesn't appear to have anything to do with the partial class(see stacktrace below).

### Expected Behavior

Expected that one can declare a partial class in multiple .cs files and by doing Evaluator.Run on them separately, each may contribute to the final class declaration, just as one does in normal C# code.

## On which platforms did you notice this

[X] Windows

**Version Used**:

According to the file version of Mono.CSharp.dll, the assembly is 4.6.57.0

## Stacktrace

```
(4,18): error CS0589: Internal compiler error during parsingSystem.MissingMethodException: Method not found: 'Void System.Array.Reverse(!!0[])'.
   at Mono.CSharp.Tokenizer.Position..ctor(Tokenizer t)
   at Mono.CSharp.Tokenizer.GetKeyword(Char[] id, Int32 id_len)
   at Mono.CSharp.Tokenizer.consume_identifier(Int32 c, Boolean quoted)
   at Mono.CSharp.Tokenizer.consume_identifier(Int32 s)
   at Mono.CSharp.Tokenizer.xtoken()
   at Mono.CSharp.Tokenizer.token()
   at Mono.CSharp.CSharpParser.yyparse(yyInput yyLex)
   at Mono.CSharp.CSharpParser.parse()
```

Note that this is the error reported back from the evaluator printer, it's not an actual application crash.

**Comment by marek-safar** [comment]
The error means you ran on different/older version of Mono than the csharp tool was compiled for (same applies if you tried to run it on .NET framework)

**Comment by jswigart** [comment]
Thanks, I will check that.

So just including the partial keyword ultimately results in the compiler trying to invoke a method it can't find?
