### ISSUE TITLE
Mono Uri parser is too strict and does not behave like dotnet framework

### ISSUE THREAD

**Issue by nover** [mono/mono#9041]
## Steps to Reproduce

While attempting to run a small dotnet application, written and built with full fat dotnet framework version 4.5, using mono, I have encountered a discrepancy in how Mono and dotnet are parsing / validating uris relating to the file system. 

1. Running the code `Console.WriteLine(Path.Combine(new Uri(Path.GetDirectoryName(typeof(Program).Assembly.CodeBase)).LocalPath, "some", "dir"));`

Inspecting the value of `Path.GetDirectoryName(typeof(Program).Assembly.CodeBase)` reveals that `file:/Users/myUsername/path/to/test.exe` is returned, which is obviously not a valid URI - however, `new Uri` on dotnet framework and windows handles this without fuzz and creates the URI.

Mono on all platforms bail out.

### Current Behavior

Exception is thrown (Stacktrace listed below) 

### Expected Behavior

Constructs the URI without complaints.

## On which platforms did you notice this

[x] macOS
[x] Linux
[x] Windows

**Version Used**:
```
$ mono --version 

Mono JIT compiler version 5.12.0.226 (2018-02/9824e260f56 Mon Apr 30 18:45:52 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
        GC:            sgen (concurrent by default)
```
## Stacktrace

```
Unhandled Exception:
System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <9279d6f02a9d42dc8fa07e8490517b4c>:0
  at System.Uri..ctor (System.String uriString) [0x00014] in <9279d6f02a9d42dc8fa07e8490517b4c>:0
  at Test.Program.Main (System.String[] args) [0x00019] in <1266c0b995d14e98b9549accf10ea544>:0
```

Full test program 

```csharp
using System;
using System.IO;

namespace Test
{
   class Program
   {
       static void Main(string[] args){
           Console.WriteLine(Path.Combine(new Uri(Path.GetDirectoryName(typeof(Program).Assembly.CodeBase)).LocalPath, "some", "dir"));
       }
   }
}

```

Build and run with:

```
mcs test.cs
mono test.exe
```

**Comment by EgorBo** [comment]
.NET Core (2.1) throws the same exception for me on macOS

**Comment by nover** [comment]
@EgorBo It's not dotnet core I'm comparing with here, it's full fat dotnet framework on Windows, where the piece of code works. If executed via Mono on windows, it fails, thus my conclusion that Mono's URI implementation is not following that of dotnet full fat framework.

**Comment by marek-safar** [comment]
It works on Mono on Windows so this is not really a bug.

It might break on non-Windows platforms but I suspect that's because the value returned by `LocalPath` is of a different format than on Windows. I agree this should be addressed to work cross-platform but for that please report the issue at https://github.com/dotnet/corefx as we don't want to incompatible with netcore either.

**Comment by EgorBo** [comment]
@marek-safar @nover sorry, forgot to mention - I filed an issue in corefx - https://github.com/dotnet/corefx/issues/30213
