### ISSUE TITLE
System.InvalidOperationException: Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by Rombersoft** [mono/mono#9043]
## Steps to Reproduce

1. Create List<SomeObject> _list
2. Fill this list by data
3. SomeObject temp = _list.SingleOrDefault(x => x.Key == "bla-bla-bla");

### Current Behavior

System.InvalidOperationException: Operation is not valid due to the current state of the object

### Expected Behavior

One element from collection
## On which platforms did you notice this

[ ] macOS
[*] Linux
[ ] Windows

**Version Used**:

mono 5.10

## Stacktrace

```
at System.Linq.Enumerable.Single[Item] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00038] in /tmp/yaourt-tmp-root/aur-mono2/src/mono-2.10.9/mcs/class/System.Core/System.Linq/Enumerable.cs:2330 
  at System.Linq.Enumerable.SingleOrDefault[Item] (IEnumerable`1 source, System.Func`2 predicate) [0x00007] in /tmp/yaourt-tmp-root/aur-mono2/src/mono-2.10.9/mcs/class/System.Core/System.Linq/Enumerable.cs:2371 
  at XNA.Controls.ListBoxBig.set_SelectedItem (System.String value) [0x00000] in <filename unknown>:0 
```

**Comment by EgorBo** [comment]
Could you please create a small repro?
It looks like your `_list` contains more than one object with `Key = "bla-bla-bla"` and InvalidOperationException is expected in this case (you might want to use `FirstOrDefault` instead).

**Comment by Rombersoft** [comment]
No. I know error about many repeated cases. But there is another error message

**Comment by EgorBo** [comment]
in this case a repro would be helpful because it's not clear what `2. Fill this list by data` means.
Also `in /tmp/yaourt-tmp-root/aur-mono2/src/mono-2.10.9/mcs/class/` in your stack-traces looks suspicious - are you sure you use mono 5.10 ?

**Comment by Rombersoft** [comment]
I can't repro this case, because it appears one time. As for your suggest that I must say I've gotten this error message often in another calling
_list.Last();
And I don't understand what state about it means.

**Comment by rjvdboon** [comment]
AFAICT the path `mcs/class/System.Core/System.Linq/Enumerable.cs` hasn't existed in the mono source for ages, the last release not using referencesource (and thus pulling the Enumerable class from that location) was mono-4.0.0-branch. 
Can you paste the full output from `mono --version`?

**Comment by Rombersoft** [comment]
I'm sorry this was on another computer there is mono 2.10
