### ISSUE TITLE
Sleep uses non-monotonic timer on Linux

### ISSUE THREAD

**Issue by rincewound** [mono/mono#9052]
Apparently a thread that is currently in a call to Thread.Sleep will block, if during the call the systemtime is set to a past date. The thread will continue to run, when the systemtime is set to the current date (or a point in the future!)

Testprogram:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Systime
{
    class Program
    {
        static void SetClock(DateTime T)
        {
            // command line from date man-page: date [-u|--utc|--universal] [MMDDhhmm[[CC]YY][.ss]]
            var utc = T.ToUniversalTime();
            var process = System.Diagnostics.Process.Start("/bin/date", "--utc " + utc.ToString("MMddHHmmyyyy.ss"));
            if (process == null)
            {
                throw new Exception("no date process was started!?");
            }

            process.WaitForExit();
            if (process.ExitCode != 0)
            {
                throw new Exception("date process returned non-successful error code " + process.ExitCode);
            }
        }

        static void Main(string[] args)
        {
            SetClock(new DateTime(2018, 7, 1, 10, 00, 00));
            var thread = new Thread(InfinitLoop);
            thread.Start();
            var dt = DateTime.Now;
            Thread.Sleep(15000);
            System.Diagnostics.Trace.WriteLine("Timetravel to 2017!");
            SetClock(new DateTime(2017, 1, 1, 1, 15, 00));
            Thread.Sleep(15000);
            System.Diagnostics.Trace.WriteLine("Timetravel to 2018!");
            SetClock(dt + TimeSpan.FromSeconds(35.0));
            thread.Join();
        }

        private static void InfinitLoop()
        {
            var i = 0;
            while (true)
            {
                Thread.Sleep(1000);
                System.Diagnostics.Trace.WriteLine($"Count {i}");
                i++;
            }
        }
    }
}

```

### Current Behavior
Program output is:

Count 0
Count 1
Count 2
Count 3
Count 4
Count 5
Count 6
Count 7
Count 8
Count 9
Count 10
Timetravel to 2017!
---> 15 Second delay between these lines <---
Timetravel to 2018!
Count 11
Count 12
Count 13
Count 14
Count 15
Count 16
Count 17

### Expected Behavior
* Thread should not block due to changes in systemtime, i.e. the output shoule be:
Count 0
Count 1
Count 2
Count 3
Count 4
Count 5
Count 6
Count 7
Count 8
Count 9
Count 10
Timetravel to 2017!
Count 11
Count 12
Count 13
Count 14
Count 15
Count 16
Count 17
(...)
Timetravel to 2018!
Count N
Count N + 1
(...)

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu Apr  5 08:39:07 -01 2018)

**Comment by jaykrell** [comment]
The code in mono looks correct and this program worked for me.

**Comment by rincewound** [comment]
Weird, we're experiencing the same problem, if we wait for an event instead of using sleep.

**Comment by rincewound** [comment]
After I did some digging in the mono codebase I suspect I'm bitten by https://github.com/mono/mono/issues/7056, as I'm currently on a version that should exhibit this behavior.

Changing my testprogram to output the ticks yields the following output:

Sun Jul  1 10:00:00 UTC 2018
Ticks: 18468990
Timetravel to one hour ago!
Sun Jul  1 09:00:00 UTC 2018
Ticks: 14868902 <--- Ticks jumps backwards!

So, we can close this issue - I'll have to update our image to use a more recent mono version.
