### ISSUE TITLE
WaitHandle.WaitAny returns invalid result

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#9089]
## Steps to Reproduce
The following code should print "0" (array index of the object that satisfied the wait)
```csharp
using System;
using System.Threading;

namespace ConsoleApplication11
{
    internal class Program
    {
        public static void Main()
        {         
            ManualResetEvent[] wh = new ManualResetEvent[2];
            wh[0] = new ManualResetEvent(true);
            wh[1] = wh[0];

            Console.WriteLine(WaitHandle.WaitAny(wh));
        }      
    }   
}
```

### Current Behavior

The code prints:
```
2147483647
```

### Expected Behavior
Should print `0` (just like .NET Core 2.1 does)

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

## UPD:
Also, `WaitAll` instead of `WaitAny` in this case should throw `ArgumentException` (mono doesn't throw).

**Comment by jaykrell** [comment]
I believe we malfunction on all the platforms, even Windows somewhat.

**Comment by jaykrell** [comment]
Fix sitting in PR for months. https://github.com/mono/mono/pull/9114

**Comment by jaykrell** [comment]
Fix sitting in PR for months. #9114

**Comment by marek-safar** [comment]
@lateralusX could you please review the fix
