### ISSUE TITLE
 MSB3073 on JetBrains Rider

### ISSUE THREAD

**Issue by dayanfcosta** [mono/mono#9094]
## Steps to Reproduce

1.  JetBrains Rider on Ubuntu 18.04 LTS
2. Checkout solution from VSTS
3. Run build
[log-rider.log](https://github.com/mono/mono/files/2087363/log-rider.log)

### Current Behavior

When I try to build my solution I got the error described below

### Expected Behavior

It's expected the build to be successfully

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:42:09 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

## Stacktrace

```
Target RestorePackages:
    mono --runtime=v4.0.30319 /home/dayanfcosta/Documentos/Projetos/Isthmus/Isthmus.Web/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/home/dayanfcosta/Documentos/Projetos/Isthmus/Isthmus.Web/ " 
    Package restore is disabled by default. To give consent, open the Visual Studio Options dialog, click on Package Manager node and check 'Allow NuGet to download missing packages during build.' You can also give consent by setting the environment variable 'EnableNuGetPackageRestore' to 'true'.
    /home/dayanfcosta/Documentos/Projetos/Isthmus/Isthmus.Web/.nuget/NuGet.targets(86,9): error MSB3073: The command "mono --runtime=v4.0.30319 /home/dayanfcosta/Documentos/Projetos/Isthmus/Isthmus.Web/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/home/dayanfcosta/Documentos/Projetos/Isthmus/Isthmus.Web/ " " exited with code 1.
Done building target "RestorePackages" in project "Isthmus.Dominio.csproj" -- FAILED.
```

**Comment by marek-safar** [comment]
This is sort of expected behaviour. See https://blog.nuget.org/20130829/nuget-2.7-package-restore-consent-errors.html
