### ISSUE TITLE
Bump minimum requirement to Windows 7.

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#9102]
The source currently tacitly supports Windows Vista.
We should increment this to Windows 7.

i.e. here:
```
$ grep 600 *ac win*h
configure.ac:		CPPFLAGS="$CPPFLAGS -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -D_WIN32_IE=0x0501 -D_UNICODE -DUNICODE -DWIN32_THREADS -DFD_SETSIZE=1024"
winconfig.h:#if _WIN32_WINNT < 0x0600
winconfig.h:#endif /* _WIN32_WINNT < 0x0600 */
```

**Comment by jaykrell** [comment]
Change 600 to 601.

**Comment by jaykrell** [comment]
I'm not sure about the 501.

**Comment by marek-safar** [comment]
We should align the minimum Windows requirement with netcore, see https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md

**Comment by jaykrell** [comment]
Yeah, oops, it looks like Unity still runs on Vista so I guess close or delay this a while.
The code I was going to make require Win7, I can keep back at Vista.

netcore requires Win7 though.

**Comment by akoeplinger** [comment]
We should really talk to Unity about whether they still need Vista. It's out of Microsoft support since April 2017 and we could silently call Win7+ APIs already since corefx assumes that as the baseline.

**Comment by marek-safar** [comment]
@joncham could you confirm the Unity minimal OS requirements going forward?

**Comment by akoeplinger** [comment]
Here's one example: [DriveInfo.Windows.cs#L65](https://github.com/dotnet/corefx/blob/ceda383ca0c165dbcc274f34476538051bf42f8d/src/System.IO.FileSystem.DriveInfo/src/System/IO/DriveInfo.Windows.cs#L65) uses `SetThreadErrorMode()` which is a Win7+ API

**Comment by jaykrell** [comment]
Here is another Windows 7 dependency:
https://github.com/dotnet/corefx/blob/96eddf39539879915e5bf570825e78af37149154/src/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/RandomNumberGeneratorImplementation.Windows.cs#L15

We don't use this code currently, and Vista is easy to support with a few more lines.

**Comment by jaykrell** [comment]
Indeed!

**Comment by akoeplinger** [comment]
Done with https://github.com/mono/mono/pull/9568.
