### ISSUE TITLE
Client certificate with HttpWebRequest does not run on iOS platform

### ISSUE THREAD

**Issue by kotrs** [mono/mono#9119]
## Steps to Reproduce

1. Prepare https server requiring client certificate
2. Create instance of X509Certificate2
3. Create instance of X509CertificateCollection and add instance of X509Certificate2.
4. Create instance of HttpWebRequest and set ClientCertificates properties with instance of X509CertificateCollection
5. Set HttpWebRequest callback ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;
6. invoke method GetResponseAsync()

### Current Behavior

It runs on MacOS. It does not run on iOS
### Expected Behavior

Running on all platforms
## On which platforms did you notice this

iOS

**Version Used**:
5.12.0.260

## Stacktrace

```
System.Net.WebException: Error: SecureChannelFailure (One or more errors occurred.) ---> System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'SecItemImport' in '/System/Library/Frameworks/Security.framework/Security'.
  at Mono.AppleTls.SecImportExport.SecItemImport (System.IntPtr importedData, System.IntPtr fileNameOrExtension, Mono.AppleTls.SecImportExport+SecExternalFormat& inputFormat, Mono.AppleTls.SecImportExport+SecExternalItemType& itemType, Mono.AppleTls.SecImportExport+SecItemImportExportFlags flags, System.IntPtr keyParams, System.IntPtr importKeychain, System.IntPtr& outItems) [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by baulig** [comment]
Client Certificates are not officially supported in iOS yet as the code that I recently committed into master has not made it into an iOS release yet.  However, I will make sure that the new code will work as expected.

Which device and which version of iOS are you using?

This could either be a linker issue with the entry point being linked out - or we're using a newer iOS API that is not available on your device.

**Comment by kotrs** [comment]
I am using iPad 2017 with iOS 11.2.6
I know where is the problem maybe. My application is developed in Unity. Unity does not use MonoTouch, but only Mono for all platforms. I searched condition for MONOTOUCH in AppleCertificateHelper class. It calls SecImportExport.ItemImport if not MONOTOUCH. So my application calls SecImportExport.ItemImport on iOS too.

Please, when do you release version with client certificate support for iOS ? Approximately.

Thank you

**Comment by baulig** [comment]
Client Certificates have been implemented a long time ago, please reopen this issue if you're still experiencing any problems.

**Comment by LifeWind1** [comment]
> I am using iPad 2017 with iOS 11.2.6
> I know where is the problem maybe. My application is developed in Unity. Unity does not use MonoTouch, but only Mono for all platforms. I searched condition for MONOTOUCH in AppleCertificateHelper class. It calls SecImportExport.ItemImport if not MONOTOUCH. So my application calls SecImportExport.ItemImport on iOS too.
> 
> Please, when do you release version with client certificate support for iOS ? Approximately.
> 
> Thank you

Could you solve this problem? I have this issue too (unity and iOS)

**Comment by kotrs** [comment]
I had to create iOS plugin for Unity.
