### ISSUE TITLE
Missing cross-compile target 5.12.0 for mkbundle

### ISSUE THREAD

**Issue by petlof** [mono/mono#9132]
Hi,
Looks like 5.12.0 still isn't available for download through https://download.mono-project.com/runtimes/raw/

How long does it normally take before a new version is available for download (and thereby cross-compile with mkbundle)

**Comment by directhex** [comment]
I'm running that job right now. https://jenkins.mono-project.com/job/ng-extract-mkbundle-runtimes/48/consoleFull
