### ISSUE TITLE
New ports for FreeBSD plz

### ISSUE THREAD

**Issue by oasisck** [mono/mono#9161]
## Steps to Reproduce

1. pkg install mono
2. pkg info mono
3. Version        : 5.2.0.215

### Expected Behavior
Need at least 5.8 for Jackett

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] FreeBSD 11.1

**Version Used**:

Mono JIT compiler version 5.2.0 (5.2.0.215 Thu Jun  7 01:29:44 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by akoeplinger** [comment]
We don't maintain the FreeBSD port ourselves, we rely on community contributions for it :)

I'm not sure how the packaging works on FreeBSD though so no idea what it'd take to get a newer Mono release into their repositories.

/cc @smortex

**Comment by NattyNarwhal** [comment]
I've talked to a FreeBSD porter about it - they're working on it.

**Comment by jaykrell** [comment]
I think some of their patches we could take asis (errno == 0) or under configure flags ("mono" vs. ".mono"). It bugs me that people feel the need to maintain patches.

I'd like to confirm errno==0 is really a thing there, I didn't track down either its history or the underlying code path. It could be under ifdef freebsd or unconditional.

The "mono" vs. ".mono" could be either an explict -foo-path=.mono or -enable-config-dot or just based on targeting FreeBSD, or defaulted for FreeBSD.

I forget what else they had, but ".mono" vs. "mono" was repeated throughout their patches.

**Comment by NattyNarwhal** [comment]
I believe they're jettisoning most of their patches as they're upstreamed or no longer relevant. (I did a build with FreeBSD on master and got the runtime and BCL building fine - just needed a CoreFX PAL patch I told them to upstream.) I'd have to talk to the ports guy again about it though.

**Comment by smortex** [comment]
Hey!

The `lang/mono` port was [updated to 5.10](https://www.freshports.org/lang/mono) recently.

Please refer to this message for further details about this:
https://lists.freebsd.org/pipermail/freebsd-mono/2018-June/002779.html

I think that this issue can be closed.  If you are interested in the state of mono on FreeBSD, I would suggest registering to the [FreeBSD mono@ mailing list](https://lists.freebsd.org/mailman/listinfo/freebsd-mono).

Thanks!
