### ISSUE TITLE
Missing submodules during compilation

### ISSUE THREAD

**Issue by kotrs** [mono/mono#9169]
## Steps to Reproduce

1. Download Mono release zip file and unpack it
2. Run ./autogen.sh --prefix=/Library/Frameworks/Mono.framework/Versions/5.12.xx --disable-nls 
    (I have to use autogen.sh, configure file is missing)
3. Run make

### Current Behavior

Compiliation failed with error because all folders in external directory is empty
When I download it manualy I get error "No rule to make target". A few files in corefx are missing. 
IRetainable.cs and so on.

## On which platforms did you notice this

MacOS

**Version Used**:
5.12.0.260

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by akoeplinger** [comment]
"release zip" makes me think you downloaded the zip through GitHub. Unfortunately the zip GitHub creates just omits any submodules so it's basically broken.

Please either clone the repo via git or use the tarballs from https://download.mono-project.com/sources/mono/
