### ISSUE TITLE
CI build breakage for 2018-04, msbuild

### ISSUE THREAD

**Issue by radical** [mono/mono#9179]
Jenkins build for mono 2018-04 is breaking while building msbuild with errors:

```
@/external/bockbuild/builds/msbuild-15/artifacts/toolset/restore.proj : error MSB4242: The SDK resolver "NuGetSdkResolver" failed to run. Unexpected failure reading NuGet.Config. Path: '@/external/bockbuild/builds/msbuild-15/artifacts/toolset/restore.proj/$HOME/.config/NuGet/NuGet.Config'.
@/external/bockbuild/builds/msbuild-15/artifacts/toolset/restore.proj : error MSB4236: The SDK 'RoslynTools.RepoToolset' specified could not be found.
``` 

Digging in, we found that this was due to the environment variable `XDG_CONFIG_HOME` having the literal value of `$HOME/.config` while running msbuild. And this gets surfaced
to nuget via mono's `Environment.SpecialFolder.ApplicationData`, causing the nuget tasks to treat this as a relative path and thus breaking the resolver.

1. Turns out that bockbuild sets this [here](https://github.com/mono/bockbuild/blob/master/bockbuild/unixprofile.py#L42). And that gets exported to the environment [here](https://github.com/mono/bockbuild/blob/master/bockbuild/environment.py#L65-L67), without expansion.
This is fixed in https://github.com/mono/bockbuild/pull/67 .

2. On the msbuild side, this started happening on 2018-04 branch because it moved to using a `RoslynTools.RepoToolset` SDK which needs to be obtained via a nuget. But the `NuGetSdkResolver` was getting
affected by the `XDG_CONFIG_HOME` issue.
Also, it was seen that master and 2018-06 builds were not affected by this. That is because both of these branches explicitly import targets for the `RoslynTools.RepoToolset` SDK and so do *not* depend
on the `NuGetSdkResolver` to make it available. No fix is required on msbuild side for this.

3. This should have been caught by mono tests for `Environment.SpecialFolder.ApplicationData`, so either we are missing proper tests or something else caused them not to be hit.

- @akoeplinger, @radical

**Comment by akoeplinger** [comment]
> This should have been caught by mono tests for Environment.SpecialFolder.ApplicationData, so either we are missing proper tests or something else caused them not to be hit.

We found out this didn't occur in the tests because the `XDG_CONFIG_HOME` variable is only set during the bockbuild build, but not when we're running the tests. That's why we didn't see it.
