### ISSUE TITLE
Windows x64 AOT/Full AOT LLVM support.

### ISSUE THREAD

**Issue by lateralusX** [mono/mono#9218]
Add LLVM codegen support on Windows x64 Visual Studio build mono runtime. Since AOT/Full AOT is only supported using Visual Studio build Windows x64 mono runtime, this will not support cygwin build mono runtime or standard configure steps.

- [x] Fix mono LLVM master to build and work on Windows using cmake and VS 2015/2017. https://github.com/mono/llvm/pull/14
- [x] Fix mono Visual Studio runtime build to enable and use LLVM codegen. https://github.com/mono/mono/pull/9230
- [x] Fix mono AOT compiler to work with LLVM codegen. https://github.com/mono/mono/pull/9230
- [x] Fix mono AOT runtime to work with binaries build using mono AOT LLVM codegen. https://github.com/mono/mono/pull/9230
- [x] Get all mini regression tests pass on AOT/Full AOT using LLVM on Windows x64. https://github.com/mono/mono/pull/9230
- [x] Fix mono mingw cross compile with LLVM in master and 2018-08. https://github.com/mono/mono/pull/10321
- [x] Add support for dynamic loading of LLVM libraries. Put on hold, https://github.com/mono/mono/issues/9218#issuecomment-444508128.
- [x] Implement additional value type parameters used by Win64 ABI currently not supported in mono LLVM. Will increase number of value type methods compiled using LLVM. https://github.com/mono/mono/pull/11873
- [x] Switch support to Release_60 LLVM branch. https://github.com/mono/llvm/pull/18, https://github.com/mono/mono/pull/11786
- [x] Integrate LLVM build into msvc regular build based on autoconf results. https://github.com/mono/mono/pull/11666
- [x] Update documentation http://www.mono-project.com/docs/advanced/mono-llvm/ on how to configure and build LLVM support for Windows x64. https://github.com/mono/website/pull/423

**Comment by lateralusX** [comment]
Investigated the LLVM load library support and found a couple of issue. First, the dynamic library support in LLVM cmake files is not working on Windows. The generated build files will not include LLVM.lib used by the tools and there is currently no way to generate that.

The Mono LLVM load library is also something that can't be ported to Windows the way it currently works. The Mono library libmono-llvm includes all static linked LLVM libraries + a couple of Mono sources that still has dependencies into libmono, so the build of libmono-llvm currently have unresolved externals that will be resolved by OS loader on platforms supporting that, Windows don't. So due to that, Windows needs a different solution if we are going to support load library support using LLVM.

One option could be to fix LLVM build making sure it builds a LLVM.lib -> LLVM.dll meaning that all LLVM tools, will share the library code instead of duplicating it into each binary (opt, llc..). When that library exist we could leverage that together with delayload msvc feature making sure LLVM is only loaded when needed into Mono runtime. This solution will however be different compared to what we currently support for loadable LLVM.


I believe we should put that task on hold for LLVM on Windows until we have a real use case in need for a loadable LLVM library.

**Comment by luhenry** [comment]
Is the statically linking of LLVM into mono works on Windows? If so, the dynamic loading is more of an optimization (both in binary size and startup time), rather than a necessity.

I agree with your proposal of putting that task on hold for now, and maybe revisit it later if the need arises. Only the documentation at https://www.mono-project.com/docs/advanced/mono-llvm/ is left to do.

**Comment by lateralusX** [comment]
Yes, statically linking LLVM into mono is how its currently done. After merging https://github.com/mono/mono/pull/11946 and updating documentation I believe we have completed the tasks covered by this issue.
