### ISSUE TITLE
The i386 architecture is deprecated for macOS during LLVM build

### ISSUE THREAD

**Issue by VincentDondain** [mono/mono#9227]
## Steps to Reproduce

Build `xamarin-macios` with `Xcode10-beta2` on macOS Mojave (dunno if the same thing happen on High Sierra).

### Current Behavior

Short build output focused on issue: https://gist.github.com/VincentDondain/1ae5aaf93cbd8b374d99cfbf7cc24226

Full build output: https://gist.github.com/VincentDondain/f16a7926659abbbb4e3fa931faa79c28

### Expected Behavior

Build `xamarin-macios` successfully.

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.10.1.57 (2017-12/ea8a24b1bbf Tue Apr 24 14:53:01 EDT 2018)
## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by vargaz** [comment]
When running:
c++ -m32 -std=c++11 foo.cpp 
I get:
ld: warning: The i386 architecture is deprecated for macOS (remove from Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode10beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode10beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: warning: ignoring file /Applications/Xcode10beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libc++.tbd, missing required architecture i386 in file /Applications/Xcode10beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libc++.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jaykrell** [comment]
Wow they are pretty serious. Does it work if specify the flag to indicate targeting old macos?

**Comment by vargaz** [comment]
So it looks like 32 bit osx is already deprecated in xcode10.

Note that we default to downloading a prebuild llvm from azure, not sure why that doesn't happen on your system.

**Comment by vargaz** [comment]
xcode 10 only has a MacOSX10.14.sdk sysroot.

**Comment by jaykrell** [comment]
Yeah that was my next question, contents of /Applications/Xcode10beta2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs other than 10.14? I guess nothing.

**Comment by jaykrell** [comment]
When you  upgrade, you still have /Applications/Xcode<old>, and that works?

**Comment by vargaz** [comment]
c++ -m32 -std=c++11 -mmacosx-version-min=10.9 foo.cpp  fails as well.

**Comment by jaykrell** [comment]
Makes sense. The most that will do is defines/compiler-switches to guide header-declarations and flags to mark version in binary. It can't find a nonexistant x86 libSystem.dylib.

Upgrade from older might do, and maybe it'll come back before release.

Can you point the compiler/linker at the native root and do those still have i386, i.e. for runtime compat? I realize native root is an old bad construct, nice not to use any more.

**Comment by lewurm** [comment]
Short-term fixed: Having a Xcode9 parallel install.

Long-term fix: https://github.com/mono/mono/issues/9621
