### ISSUE TITLE
Build infrastructure: Error out on missing files

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#9232]
When a (library).sources file in mcs/class/(library)/ contains a reference to non-existent file the build should result in an error. Right now it silently ignores the missing files.

**Comment by marek-safar** [comment]
@kg this looks like regression in `gensources`

**Comment by kg** [comment]
gensources.cs implements this. From what I could tell, gensources.sh didn't have any error messages or handling for this, so I didn't enable it. We had some bad paths in our .sources files already.

**Comment by filipnavara** [comment]
Got bitten by it again... https://github.com/mono/mono/pull/9478/files ... is it supposed to work now?

**Comment by kg** [comment]
Yes. I'll look into it

On July 10, 2018 9:25:39 AM PDT, Filip Navara <notifications@github.com> wrote:
>Got bitten by it again... https://github.com/mono/mono/pull/9478/files
>... is it supposed to work now?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mono/mono/issues/9232#issuecomment-403883938

- kg (mobile)
