### ISSUE TITLE
Release tarballs should be compressed with xz

### ISSUE THREAD

**Issue by thiagomacieira** [mono/mono#9267]
Mono should release its sources in a `.tar.xz` format. Quick benchmark for the 5.12.0 release file:

Compression Format | Tarball size | Decompression time
-------------------|--------------|-------------------
BZip2 | 204 MB | 31.04s
Xz | 132 MB | 9.89s

**Comment by akoeplinger** [comment]
@directhex what do you think about this?

**Comment by directhex** [comment]
It's a 1-line change to configure.ac, plus however many hours to fix assumptions made in our relevant Jenkins jobs

**Comment by directhex** [comment]
I'm not terribly keen on supporting both.

Are there any distributions which can't handle .tar.xz? We only care about tarballs on Linux & friends, so if there's a distribution adjacent to our support matrix which can't handle .xz then I could be persuaded to do both - otherwise I'd prefer to just switch to .xz wholesale.

Any Debian derivative with dpkg 1.15.5 (Nov 2009) is fine with it. Not sure on RPM

**Comment by thiagomacieira** [comment]
There's a lot of software that has switched to only .xz (and even .7z for Windows), ditching the .gz and especially ditching the .bz2 files. Unlike the Lempel-Ziv family of decompressors, bunzip2 takes a lot of CPU time to work. It's not only more bandwidth consumed for the project, it's also time for the user. It's so bad that decompressing the 5.12.0 release tarball on-the-fly while downloading stalls the download (averaged 5 MB/s while a pure download saturated my 100 Mbit/s office connection).

If you want to hedge your bets, add .xz and keep the current compression (bzip2) for another year, then check your download stats.

And if you want to be bold, try zstd.

Tarball Size | Decompression time
-------------|-------------------
141 MB | 3.047s

Just a pure xxxcat of the compressed tarball:

Decompressor | xxxxcat time
--------------|---------------
bunzip2 | 35.86 s
xzcat | 10.86 s
zstdcat | 1.23 s

**Comment by akoeplinger** [comment]
I've seen build scripts that do stuff like `wget https://download.mono-project.com/sources/mono/mono-$(VERSION).tar.bz2` so I'd like to avoid breaking them if we can avoid it.

@directhex is there a reason why we can't easily do both?
