### ISSUE TITLE
Build warnings in Boehm GC (QA issue with Mono Gentoo package)

### ISSUE THREAD

**Issue by fturco** [mono/mono#9278]
My GNU/Linux distribution is Gentoo Linux. The Portage package manager reports the following warning message when installing `dev-lang/mono-5.4.1.6`:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * gc_dlopen.c:52:30: warning: implicit declaration of function 'GC_collection_in_progress'; did you mean 'GC_collect_or_expand'? [-Wimplicit-function-declaration]
 * gcj_mlc.c:210:6: warning: implicit declaration of function 'GC_start_debugging'; did you mean 'GC_store_debug_info'? [-Wimplicit-function-declaration]
 * new_hblk.c:227:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://www.mono-project.com/Main_Page
```

[build.log](https://github.com/mono/mono/files/2130032/build.log)

**Comment by jaykrell** [comment]
Compiler warnings are easy to fix if we care to.

**Comment by lewurm** [comment]
Those are warnings from files in `libgc` which is Boehm GC. I would recommend to disable Boehm GC support as it is something we don't test anymore: `./configure --disable-boehm`

**Comment by jaykrell** [comment]
CI doesn't run tests with boehm?

**Comment by directhex** [comment]
We also don't ship it on every platform - our Boehm fork is pretty ancient, and lacks e.g. ARM64. The default switched to SGen on all platforms years ago. We should probably look at our use-cases & determine whether it's time to retire Boehm entirely

**Comment by akoeplinger** [comment]
Closing as we don't plan to invest in Boehm going forward.
