### ISSUE TITLE
MSBuild: Restore doesn't add targets to NETStandard.Library

### ISSUE THREAD

**Issue by xforever1313** [mono/mono#9280]
I'm running into an issue while compiling my project with MSBuild on my Linux system.

I have a C# project that outputs a class library and it targets netstandard2.0.  I have another project in the same solution that outputs an EXE and targets NET461 and has a reference to the class library.

If I run ```msbuild /restore```, my class library project will not compile.  I get a lot of CS0246 errors (e.g  ```The type or namespace name 'Thread' could not be found (are you missing a using directive or an assembly reference?)```).

I also have dotnet core installed on my Linux Machine.  Just out of curosity, I tried to run ```dotnet restore``` before running just ```msbuild``` (without the /restore flag), and it compiles just fine! ```msbuild /restore``` however, will not.

I think the issue has something to do with not being able to find the NETStandard.Library package (v2.0.3).  If, in my .csproj, I explicitly put in ```<PackageReference Include="NETStandard.Library" Version="2.0.3"/>```, ```msbuild /restore``` compiles the project just fine.  But, a warning is generated:

```/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.DefaultItems.targets(201,5): warning : A PackageReference for 'NETStandard.Library' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs```

Looking at what is outputted when running ```dotnet restore``` and ```msbuild /restore```, I noticed there is a difference in what is generated that may explain the compile errors:

``dotnet restore`` generates:

* obj/myProject.csproj.nuget.g.props:

```XML
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">/home/me/myProject/obj/project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">/home/me/.nuget/packages/</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">/home/me/.nuget/packages/;/opt/dotnet/sdk/NuGetFallbackFolder</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">4.7.0</NuGetToolVersion>
  </PropertyGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
</Project>
```

* obj/myProject.csproj.nuget.g.targets:
```XML
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <!-- This ImportGroup is missing from files generated with msbuild -->
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="/opt/dotnet/sdk/NuGetFallbackFolder/netstandard.library/2.0.3/build/netstandard2.0/NETStandard.Library.targets" Condition="Exists('/opt/dotnet/sdk/NuGetFallbackFolder/netstandard.library/2.0.3/build/netstandard2.0/NETStandard.Library.targets')" />
  </ImportGroup>
</Project>
```
``msbuild /restore`` generates:

* obj/myProject.csproj.nuget.g.props:
```XML
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">/home/me/myProject/obj/project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">/home/me/.nuget/packages/</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">/home/me/.nuget/packages/</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">4.6.0</NuGetToolVersion>
  </PropertyGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
</Project>
```
* obj/myProject.csproj.nuget.g.targets:
```XML
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
</Project>
```

I think the issue lies in the fact that ```msbuild /restore``` does not add the Import tag for NETStandard.Library.targets in myProject.csproj.nuget.g.targets, like ```dotnet restore``` does.

The question becomes, is this a bug in MSBuild, is this by design where MSBuild requires us to explicitly add in this package, or is there some configuration I need to set up on my Linux box?

## Steps to Reproduce

I created a simple project located here that reproduces the issue: https://bitbucket.org/xforever1313/msbuildissue/src/master/ . To reproduce, git clone the repo and simply run ```msbuild /restore``` in the root directory where the .sln file is.  You'll get an error that says ```Waiter.cs(13,17): error CS0103: The name 'Thread' does not exist in the current context```.  

But, if you uncomment the commented section in ClassLibrary/ClassLibrary.csproj, which adds a reference to NetStandard.Library, the build will succeed, but with warnings.

## On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

**Version Used**:

$ dotnet --version (in case it matters)
2.1.300

$ mono --version
Mono JIT compiler version 5.12.0 (makepkg/58637d0ee7c Wed Jun  6 22:41:15 CEST 2018)

$ msbuild /version
Microsoft (R) Build Engine version 15.6.0.0 ( Fri Apr  6 15:55:10 UTC 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

$ nuget
NuGet Version: 4.6.2.5055

$ uname -a
Linux myhostname 4.13.9-1-ARCH #1 SMP PREEMPT Sun Oct 22 09:07:32 CEST 2017 x86_64 GNU/Linux

**Comment by marek-safar** [comment]
@radical could you advice on the issue

**Comment by radical** [comment]
This builds fine for me on macOS.

@xforever1313 could you please clean out the obj and bin folders and run `msbuild /fl /flp:v=diag /restore` and then attach the generated `msbuild.log` file?

**Comment by xforever1313** [comment]
Log from trying to build on my Linux system: [msbuild.log](https://github.com/mono/mono/files/2138132/msbuild.log)

**Comment by radical** [comment]
How did you install msbuild and mono?

**Comment by xforever1313** [comment]
I'm happy you asked that question.  It caused me to take a closer look into the three different Linux systems I have access to, and I think I figured out what was going on.  

The version of Mono and Msbuild all match on all three systems.  The difference was the version of the dotnet SDK that was installed.

On one setup, it was dotnet 2.1.300.  The project did NOT compile on this system (this is the same system that I extracted msbuild.log).

On another machine, I don't think the dotnet SDK was installed.  The project also did NOT compile on this machine.

My third machine I didn't try building on until today.  dotnet 2.1.4 was installed.  It SUCCESSFULLY compiled.  With 2.1.4 installed, ```msbuild /restore```'s ```ClassLibrary.csproj.nuget.g.targets``` resembles the same output as ```dotnet restore```.  The second I uninstalled the dotnet SDK and tried again, the same compilation errors that appeared on my other machines happened.

I think what this tells me is make sure dotnet 2.1.4 is installed?  And 2.1.300 apparently won't work?

**Comment by radical** [comment]
Thanks, that is good information!

But can you please tell me where you install mono and msbuild from? And the package versions. Also, can you get the diag logs, using `msbuild /fl /flp:v=diag /restore /t:Build` from the machine with `2.1.300` installed? And the `*nuget.g*` files. Thanks!

**Comment by xforever1313** [comment]
Oops, in my excitement I forgot to include that information :P

System 1 is the Arch Linux system.  This is also the system that has dotnet 2.1.300 installed, and had compile errors.

For the Arch Linux system, these are the msbuild & dotnet packages that are installed:
```
community/dotnet-host 2.1.0-3 [installed]
    A generic driver for the .NET Core Command Line Interface
community/dotnet-runtime 2.1.0-3 [installed]
    The .NET Core runtime
community/dotnet-sdk 2.1.300-2 [installed]
    The .NET Core SDK
extra/mono 5.12.0.260-1 [installed]
    Free implementation of the .NET platform including runtime and compiler
aur/msbuild-stable 15.6_xamarinxplat.2018.01.17.14.14_0xamarin1_ubuntu1404b1-3 [installed] (23) (8.47)
    Xamarin implementation of the Microsoft build system
```

I installed Mono from Arch Linux's 'extra' repositories with the command ```pacman -S mono```.  I believe it downloaded it from here: [http://mirrors.rit.edu/archlinux/extra/os/x86_64/mono-5.12.0.260-1-x86_64.pkg.tar.xz](http://mirrors.rit.edu/archlinux/extra/os/x86_64/mono-5.12.0.260-1-x86_64.pkg.tar.xz).

However, that package does NOT include msbuild.  According to [this](https://bbs.archlinux.org/viewtopic.php?id=226229) thread on archlinux.org, they didn't include it because, according to them, it requires dotnet 1.x to be installed to build it (not sure why that matters to them...).  To install msbuild, Arch Linux users need to use the AUR with the command ```yaourt -S msbuild-stable```.  According to the package's [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=msbuild-stable), it appears to just download the .deb file located at [download.mono-project.com/repo/ubuntu/pool/main/m/msbuild/msbuild_15.6+xamarinxplat.2018.01.17.14.14-0xamarin1+ubuntu1404b1_all.deb](download.mono-project.com/repo/ubuntu/pool/main/m/msbuild/msbuild_15.6+xamarinxplat.2018.01.17.14.14-0xamarin1+ubuntu1404b1_all.deb) and extracts it.

System 2 is Travis-CI.  This was the system without dotnet installed.  They appear to be using Ubuntu 14.04 (Trusty).  According to one of my build [logs](https://travis-ci.org/xforever1313/Chaskis/builds/395712348), I see these messages which point to which version of Mono/msbuild they use:

```
Setting up msbuild (1:15.6+xamarinxplat.2018.01.17.14.14-0xamarin2+ubuntu1404b1) 
Setting up mono-devel (5.12.0.226-0xamarin3+ubuntu1404b1)
```
Unfortunately, I can't seem to find *where* they get their packages from.

System 3 is my Ubuntu laptop (16.04).  This is the system that had dotnet 2.1.4 installed and compiled successfully.  I followed the instructions located at [https://www.mono-project.com/download/stable/#download-lin](https://www.mono-project.com/download/stable/#download-lin) for Ubuntu 16.04 and installed the package mono-complete.  Here's the package information from running "apt-get install" for mono-complete, msbuild, and dotnet.

```
mono-complete is already the newest version (5.12.0.226-0xamarin3+ubuntu1604b1).
msbuild is already the newest version (1:15.6+xamarinxplat.2018.01.17.14.14-0xamarin2+ubuntu1404b1).
dotnet-sdk-2.1.4 is already the newest version (2.1.4-1).
```

I'll attach those files you requested in my next comment, stand by...

**Comment by xforever1313** [comment]
[msbuild.log](https://github.com/mono/mono/files/2139276/msbuild.log)

I had to add '.txt' to the end of these file names, or GitHub wouldn't upload them:
[ClassLibrary.csproj.nuget.cache.txt](https://github.com/mono/mono/files/2139279/ClassLibrary.csproj.nuget.cache.txt)
[ClassLibrary.csproj.nuget.g.props.txt](https://github.com/mono/mono/files/2139280/ClassLibrary.csproj.nuget.g.props.txt)
[ClassLibrary.csproj.nuget.g.targets.txt](https://github.com/mono/mono/files/2139281/ClassLibrary.csproj.nuget.g.targets.txt)

**Comment by directhex** [comment]
The native SDK resolver library is not actually part of the msbuild package.

The managed part (`/usr/lib/mono/msbuild/15.0/bin/SdkResolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.dll`) is in `msbuild-sdkresolver` from the `msbuild` source package, and the unmanaged part (`/usr/lib/mono/msbuild/15.0/bin/SdkResolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.dll`) is in `msbuild-libhostfxr` from the `core-setup` source package.
