### ISSUE TITLE
watchOS: "fastcc" not supported with Xcode 10's clang

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#9318]
Repro:

* Download Xcode 10 beta 2, and configure Visual Studio for Mac to use it. Restart Visual Studio for Mac.
* Create a new iOS app and add a watchOS extension (or download & open [nofastcc.zip](https://github.com/mono/mono/files/2138071/nofastcc.zip))
* Change to a Release|Device configuration and build.
* Install Xamarin.iOS from the xcode10 branch - either built from source or a package from CI, which are available as GitHub statuses here: https://github.com/xamarin/xamarin-macios/commits/xcode10 (I'm not sure this is required, believe this bug should reproduce with any version of Xamarin.iOS, but I haven't tested it)

Result:

> error MT5209 : Native linking error : fatal error: error in backend: Unsupported calling convention

Complete build log: https://gist.github.com/rolfbjarne/d664ac9440da1e127e97d9779a7bafa2

I opened a radar with Apple about this, and they said:

--- 

This issue behaves as intended based on the following:

The Mono developers decided to use "fastcc". This has never been a supported configuration but happened to "work" before clang-1000 because Clang is compiled with assertions turned off. 

The check was turned into a true error on clang-1000, leading to this failure. 

---

So we need to stop using fastcc.

This is a blocker for our Xcode 10 support, since it breaks our watchOS story completely.

**Comment by luhenry** [comment]
@vargaz could you please take a look at that? Thank you.

**Comment by marek-safar** [comment]
@spouliot what is the dev releases alignment for our xcode 10 support?

**Comment by vargaz** [comment]
Where is the error message about using 'fastcc' ? We are using preserveall_cc, we can get rid of that if needed.

**Comment by vargaz** [comment]
preserve_allcc is a calling convention saving all registers, we use it around calls to init functions so they don't clobber argument registers. Disabling it is going to make the code slower/bigger, but it will still work.

**Comment by spouliot** [comment]
@marek-safar we need the PR backported to `2017-12`, that's what's used in stable 15.7, to fix watchOS support on our next previews. Thanks!

**Comment by vargaz** [comment]
Note that previous xcode versions probably didn't support this calling convention they just didn't assert on it so this will not actually make things slower/bigger.

**Comment by luhenry** [comment]
@spouliot done at https://github.com/mono/mono/pull/9355

**Comment by GLjackyvaswani** [comment]
Have tested it with latest build shared for Xcode 10 beta , issue still reproducible.

Tested it with : 
https://github.com/xamarin/release-manifests/blob/Xcode10/manifests/xcode10-beta3-preview2.json

Logs:  https://gist.github.com/GLjackyvaswani/15beca0beb7331c144057a978c22335c

BuildInfo: 

Version 7.5.4 (build 5)
Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
Xamarin.Android Version: 8.3.3.2
Xamarin.Mac Version: 4.99.1.164
Xamarin.iOS Version: 11.99.1.44
Apple Developer Tools Xcode 10.0 (14301.4) Build 10L201y
Operating System Mac OS X 10.14.0
Xamarin.Profiler Version: 1.6.2
Xamarin Inspector Version: 1.4.0

Build Info: https://gist.github.com/GLjackyvaswani/bbf556eb8dbfe16e7619c6013a863a5c

**Comment by lewurm** [comment]
mentioned Xamarin.iOS build points to https://github.com/mono/mono/commit/10feb7c which should have fixed it, thus reopen.

**Comment by GLjackyvaswani** [comment]
Same issue also observed when tried to deploy Watch App on device in Release mode.

Build output with errors: https://gist.github.com/p-lad/f63aa5a892be66ccfeb0110c3ea758f5

Tested it with :
https://github.com/xamarin/release-manifests/blob/Xcode10/manifests/xcode10-beta3-preview2.json

Build Info: https://gist.github.com/GLjackyvaswani/bbf556eb8dbfe16e7619c6013a863a5c

**Comment by vargaz** [comment]
Missed a case, sorry about that.

**Comment by lewurm** [comment]
let's reopen until it's confirmed to be fixed

**Comment by p-lad** [comment]
Hello @lewurm,
Tested with Xcode 10 beta 5 builds , we are able to build the WatchApp in Release mode and also we have successfully submitted the WatchApp to app store.

Build taken from:-
https://github.com/xamarin/release-manifests/blob/Xcode10/manifests/xcode10-beta5-webpreview3.json

Build Info:-
Mojave OS 18A347e
Xcode Version 10.0 beta 5 (10L221o)
Visual Studio Enterprise 2017 for Mac Version 7.5.4 (build 7)
Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
Xamarin.Android Version: 8.3.3.2 (Visual Studio Enterprise)
Xamarin.Mac Version: 4.99.2.250 (Visual Studio Enterprise)
Xamarin.iOS Version: 11.99.2.130 (Visual Studio Enterprise)
Xamarin Workbooks 1.4.3
Xamarin Profiler 1.6.2-165

Build Information gist :-
https://gist.github.com/mohakbarokar/5d53e995e08a21ba08f9d109bb71752c

Thanks.

**Comment by lewurm** [comment]
Thank you @p-lad!

**Comment by rolfbjarne** [comment]
@vargaz can this be back ported to 2018-02?
