### ISSUE TITLE
Method not found: double System.Math.Log(double) 

### ISSUE THREAD

**Issue by w8w8w8** [mono/mono#9350]
I use the blazor to assembly.load(bytes[]),https://github.com/aspnet/Blazor/issues/1044
my code is this:
var assembly = Assembly.Load(bytes); obj = assembly.CreateInstance(ClassFullName); var t = assembly.GetType(ClassFullName); method = t.GetMethod("Run");

but there is some error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of
an invocation. ---> System.MissingMethodException: Method not found: double System.Math.Log(double)

![41948881-84012a28-79f1-11e8-99e1-dc2a3fbe97ab](https://user-images.githubusercontent.com/4744039/42007129-d101c0e8-7ab0-11e8-89d3-227c6366e547.png)

I think the blazor this is a bug at Math.Log

**Comment by kumpera** [comment]
Did you enable linking in your project? Can you try to disable it and see if it's still an issue?
Could you provide a test case that shows this issue?

**Comment by w8w8w8** [comment]
@kumpera the attach files is this project, when you run the project, you could click left 'run' link , then you will see the error on the Console.
you need vs2017 preview.
[WebApplication1.zip](https://github.com/mono/mono/files/2151324/WebApplication1.zip)

thank you!

**Comment by w8w8w8** [comment]
@kumpera  can you see my demo ?

**Comment by kumpera** [comment]
Yes, this is a linker issue.
The linker did not process Rectifyf.dll and removed all methods from mscorlib that the later uses.

Either disable the blazor linker or configure your solution to properly feed it all your assemblies.
