### ISSUE TITLE
Calling functions from shared libraries that take wchar_t* parameters

### ISSUE THREAD

**Issue by stmax82** [mono/mono#9362]
I'm trying to make a C# application run on Linux / ARMv7 that uses an [IDS uEye camera](https://en.ids-imaging.com/download-ueye-emb-hardfloat.html). It almost works except for one function that uses a wchar_t* parameter to pass a filename as Unicode string.

I have [DllImport]ed the function. Calling it works fine on Windows, but doesn't on Linux. On Linux I end up with garbled / invalid filenames.

The problem seems to be that on Windows sizeof(wchar_t) is 2, while on Linux it is 4 - but Mono always converts the string using 2 bytes per character.

I cannot change the shared library. What'd be the best way to make this work?

Here's example code that shows the problem:

**testlib.h**

The header file of a library that will be called. The function *callme* takes a wchar_t* parameter.

```
#ifndef __testlib_h__
#define __testlib_h__

#include <wchar.h>

extern void callme(wchar_t* foo);

#endif
```

**testlib.c**

The implementation of the callme function. It uses / prints the contents of the wchar_t* parameter - once with printf %ls and once as hex characters.

```
#include <stdio.h>
#include <wchar.h>
#include "testlib.h"

void callme(wchar_t* foo) {
        unsigned char *p = (unsigned char *)foo;

        printf("%ls\n", foo);

        for (int i = 0; i < 48; i++)
                printf("%02X ", p[i]);
        printf("\n");
}
```

**testapp.c**

A C application that calls the library (this works as expected).

```
#include <stdio.h>
#include "testlib.h"

int main() {
        callme(L"foo.ini");

        return 0;
}
```

To build the library and the C application:

```
gcc -shared -o libtestlib.so -fpic testlib.c
gcc -o testapp testapp.c -L. -ltestlib
```

Running ./testapp outputs:

```
foo.ini
66 00 00 00 6F 00 00 00 6F 00 00 00 2E 00 00 00 69 00 00 00 6E 00 00 00 69 00 00 00 00 00 00 00 28 FE FF 7F 01 00 00 00 00 00 00 00 00 00 00 00
f           o           o           .           i           n           i           <end>       <...>
```

**TestAppCSharp.cs**

Now for the C# / Mono part - this [DllImport]s the callme function and calls it with "foo.ini".

```
using System.Runtime.InteropServices;

namespace TestAppMono {
    public class Program {
        [DllImport("testlib", EntryPoint = "callme")]
        private static extern void CallMe([MarshalAs(UnmanagedType.LPWStr)]string foo);

        public static void Main(string[] args) {
            CallMe("foo.ini");
        }
    }
}
```

The output is:

```
▒▒▒i <- garbage
66 00 6F 00 6F 00 2E 00 69 00 6E 00 69 00 00 00 00 00 00 00 60 01 27 76 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
f     o     o     .     i     n     i     <end> <...>
```

^- this one outputs junk because the characters are only 2 bytes wide instead of 4.

Is there a (sane) way to make this work on Linux?

My current work around is hand crafting a byte[] and passing that to the function...:

```
using System;
using System.Linq;
using System.Runtime.InteropServices;

namespace TestAppMono {
    public class Program {
        [DllImport("testlib", EntryPoint = "callme")]
        private static extern void CallMe(byte[] foo);

        public static void Main(string[] args) {
            byte[] bytes =
                System.Text.Encoding.ASCII.GetBytes("foo.ini") // get ASCII bytes
                .Concat(new byte[] { 0 }) // add null termination
                .SelectMany(x => new byte[] { x, 0, 0, 0 }) // append 3x 0 bytes to each byte
                .ToArray();

            CallMe(bytes);
        }
    }
}
```

This actually works for my use case (I can control the file names that are passed in), but...

## On which platforms did you notice this

[ ] macOS
[X] Linux (on a Raspberry running Raspbian)
[ ] Windows

**Version Used**:

pi@raspberrypi:~/ueye $ mono --version
Mono JIT compiler version 5.4.1.7 (tarball Thu Feb  1 00:33:38 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

**Comment by NattyNarwhal** [comment]
Stupid idea: maybe try involving `Encoding.UTF32`?

**Comment by stmax82** [comment]
@NattyNarwhal that's one of the many things I tried, but it doesn't work... UTF uses variable length characters and plain ASCII characters like "foo.ini" are encoded as single bytes.

**Comment by rjvdboon** [comment]
Re https://github.com/mono/mono/issues/9362#issuecomment-401136870: UTF32 gives 4 bytes per character. You may be confused with UTF8 (which is 1 to 7 bytes per character). You would still need to add the terminating 0 though.
```
$ csharp
Mono C# Shell, type "help;" for help
csharp> System.Text.Encoding.UTF32.GetBytes(@"123 ¯\(ツ)/¯")
{ 49, 0, 0, 0, 50, 0, 0, 0, 51, 0, 0, 0, 32, 0, 0, 0, 175, 0, 0, 0, 92, 0, 0, 0, 40, 0, 0, 0, 196, 48, 0, 0, 41, 0, 0, 0, 47, 0, 0, 0, 175, 0, 0, 0 }
  1            2             3            <space>     ¯             \            (            ツ             )             /            ¯
```

**Comment by rjvdboon** [comment]
As 4 byte `wchar_t` is not part of the default marshallers, you'll problably have to roll your own. Did you have a look at https://www.mono-project.com/docs/advanced/pinvoke/#custom-marshaling ?

**Comment by stmax82** [comment]
@NattyNarwhal sorry I was wrong - it looks like UTF32 works fine!

For future generations - I did this to make it work on both Windows on Linux:

Function to convert a .NET string to either Unicode (on Windows) or UTF32 (on Linux):

```
        static byte[] StringToWCHAR_T(string s) {
            var encoding =
                Environment.OSVersion.Platform == PlatformID.Unix
                ? System.Text.Encoding.UTF32
                : System.Text.Encoding.Unicode;

            return encoding.GetBytes(s + '\0');
        }
```

The [DllImport]ed function gets a byte[]:

```
        [DllImport("ueye_api.dll", EntryPoint = "is_ParameterSet")]
        static extern uEye.Defines.Status ParameterSet(int s32CamHandle, uint u32Command, byte[] pParam, uint u32SizeOfParam);
```

Calling it:

```
        ParameterSet(camHandle, 4, StringToWCHAR_T("foo-äöüß.ini"), 0)
```

Thanks for your help. I'll close this..!
