### ISSUE TITLE
SslClientStream TLSv1.2 support

### ISSUE THREAD

**Issue by harishvadali** [mono/mono#9363]
I am using Novell Ldap library to connect to an AD server and I need to support TLSv1.2. The Novell library was using `Mono.Security` to connect to AD via secure transport and noticed that it was using `SslClientStream` passing `SecurityProtocolType.Ssl3 | SecurityProtocolType. Tls`.

Wireshark Report is below:

**Changed the code to pass `SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls12`:**

![screen shot 2018-06-28 at 11 09 50 am](https://user-images.githubusercontent.com/1455823/42043346-3ac3c950-7ac4-11e8-9e2b-fef359f14cea.png)

It picked up `Ssl3` and the handshake failed.

**Changed the code to pass `SecurityProtocolType.Tls12`:**

![screen shot 2018-06-28 at 11 10 57 am](https://user-images.githubusercontent.com/1455823/42043404-6103e5fa-7ac4-11e8-98e0-54279963fe55.png)

Fails right away.

I am using `Mono.Security` nuget package version `5.4.0.201` which is latest available.

After looking at the code of `SslClientStream`, I noticed the comment below:
https://github.com/mono/mono/blob/mono-5.12.0.273/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/Context.cs#L421

Does it mean that TLSv1.2 is not supported by `SslClientStream` yet or am I missing something? Please clarify.

**Comment by baulig** [comment]
It's not going to happen, we're about to remove the code.  Checkout https://github.com/mono/mono/pull/9301 - this also contains a port of the Novell Ldap library to use the new API.
