### ISSUE TITLE
SerialPort.cs Read: serial packet corruption(extra byte(00) added)

### ISSUE THREAD

**Issue by sunzone93** [mono/mono#9373]
Hi,

I have been using mono program to test Serial communication.
After upgrading from Linux kernal 4.11.7﻿-sun8i﻿﻿ to 4.14.18-sunxi I started seeing CheckSum errors and packet corruption in the received packets.
I wrote a simple program to send byte[] in Visual studio and ran the program on Orange Pi Zero using Mono Remote Debugger.

Test was successful in "ARMBIAN 5.32 user-built Ubuntu 16.04.2 LTS 4.11.7﻿-sun8i﻿﻿" kernal image.
But in "ARMBIAN 5.38 stable Ubuntu 16.04.4 LTS 4.14.18-sunxi" corrupt packets were received.
**When looked in the corrupt byte[], I obsertved extra '00'(byte) is added at random places.**

I tested with mono version 5.10.1.20 and 5.12.0.226 and result is the same. 

With some research, I found out extra bytes are added when termios structure is not properly initialized.
Specifically when PARMRK and INPCK flags are set and IGNPAR flag is not set.
https://stackoverflow.com/a/50401627

In [termios ](http://man7.org/linux/man-pages/man3/termios.3.html)man page, IGNPAR flag is used to Ignore framing errors and parity errors.

When I checked sunxi source code I could not find any changes to this parameters.

I am guessing a change to the Linux source code in Serial Communication(may be a new parameter introduced)  and this change is not supported in mono.

I also tried using the parameter SerialPort.set_DiscardNull. But seems monohas not implmented set_discardNull parameter. "System.NotImplementedException: The method or operation is not implemented  at System.IO.Ports.SerialPort.set_DiscardNull (System.Boolean value)."

I posted about this problem in [Armbian](https://forum.armbian.com/topic/7507-orangi-pi-zero-uart-error-with-armbian-538-and-532/?tab=comments#comment-56479) forum and [linux sun-xi google groups](https://groups.google.com/d/msg/linux-sunxi/yUbcI1O1drA/0Ww08FbeCQAJ). But haven't got any replies yet.

Can someone please give me any suggestions or any thoughts on this issue?

Thank You.

**Comment by lewurm** [comment]
I don't think your issue is mono related. If you think it is, feel free to reopen and please provide some information on how to reproduce.
