### ISSUE TITLE
fsharpi FileNotFound running script

### ISSUE THREAD

**Issue by goekboet** [mono/mono#9391]
## Steps to Reproduce

[Here's](https://github.com/mono/mono/files/2152198/repro.zip) my dotnet core project:

``` bash
# This reproduces my issue:
dotnet build src/MyCSharplib
dotnet restore
fsharpi src/MyFSharpProgram/Script.fsx
```

### Current Behavior

I get the following error:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.
```

### Expected Behavior

I expect the script to print "1" to my console.

* If i replace `u 1 |> printfn "%s"` with `"1" |> printfn "%s"` in Script.fsx I get "1" as expected
* If I `dotnet run --project src/MyFsharpProgram` i get "1" (even though its the same code as in Script.fsx) as expected
*  The unexpected behaviour also happens when I repeat in fsharpi interactively

I have run in to this issue a couple of times in different setups but this seems to always happen when I call csharp code from fsharp and the csharp code calls a dependency (like Newtonsoft.Json in the repro)

## On which platforms did you notice this

[ X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.12.0.226 (tarball Tue Jun 26 14:05:36 BST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

## Stacktrace

```
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
  at <StartupCode$FSI_0001>.$FSI_0001.main@ () [0x00000] in <f708f4ba3677469ebb3ca28f43e4a2d6>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <47b74980241a4d7898fb5dbf7819d2e5>:0 
Stopped due to error
```

**Comment by nosami** [comment]
This isn't a bug but just the way that fsharpi works. You need to reference Newtonsoft.Json from the `.fsx` script using `#r /path/to/Newtonsoft.Json.dll` otherwise fsharpi won't know about the reference. It can't read the references from your project file.

**Comment by goekboet** [comment]
I see, thank you, my bad
