### ISSUE TITLE
Support per-platform sources for xunit tests

### ISSUE THREAD

**Issue by MaximLipnin** [mono/mono#9395]
It needs the ability to include/exclude xunit tests depending on platform.
As example - CoreFX ProtectedData class which has no non-windows implementation so the related xunit test doesn't make sense on other platforms but they still run and lead to CI target failures.

**Comment by filipnavara** [comment]
I am not big fan of changes in the CoreFX fork, but xunit has the concept of `PlatformSpecific` attribute that has exactly this functionality. Shouldn't it be used here?

**Comment by MaximLipnin** [comment]
Good point, thanks. I've tried it locally and seems that it can be possible to use xunit platform specific attribute (e.g. `[PlatformSpecific(TestPlatforms.Windows)]`) to reach the goal in case when there are not so many test that should be marked.
@akoeplinger @marek-safar Does it make sense for you?

**Comment by marek-safar** [comment]
We try to avoid `[PlatformSpecific(TestPlatforms.Windows)]` as this should really be used for platform-specific tests like checking for `c:\` for other things we use PlatformDetection. Considering the tests will probably never work on non-windows [PlatformSpecific(TestPlatforms.Windows)] could just work

**Comment by MaximLipnin** [comment]
Do we plan to support different xunit test source profiles like `win32_System.Security_xtest.dll.sources` or `winaot_System.Security_xtest.dll.sources` ?

**Comment by marek-safar** [comment]
Not at the moment

**Comment by akoeplinger** [comment]
Closing since this seems to be answered.
