### ISSUE TITLE
UnixServiceController implementation

### ISSUE THREAD

**Issue by JTrotta** [mono/mono#9396]
[ ] macOS
[X] Linux
[ ] Windows

**Version Used**: LAST
Any chance this library will be implemented?

**Comment by akoeplinger** [comment]
It's not been touched in the last 12 years so probably not anytime soon :)

We'd appreciate a pull request if you decide to implement it yourself.

**Comment by JTrotta** [comment]
@akoeplinger will do.
I'm valuating a porting and some new implementation

Thank you
