### ISSUE TITLE
The wasm debugger is case sensitive for assembly names

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#9405]
## Steps to Reproduce
1. Follow the instructions for wasm debugging setup
2. Debug an assembly with upper case letters in it

### Current Behavior
The wasm runtime will fail saying `Could not resolve assembly [assembly_all_lower_case].dll`

### Expected Behavior
The debugging session starts properly.

## On which platforms did you notice this
Windows

**Version Used**:
https://jenkins.mono-project.com/job/test-mono-mainline-wasm/463/label=ubuntu-1804-amd64/Azure/processDownloadRequest/463/ubuntu-1804-amd64/sdks/wasm/mono-wasm-643e6c47ee5.zip

**Comment by kumpera** [comment]
How are you trying to load the assembly?

We use the emscripten VFS which is case sensitive, so it won't be able to deal with incorrectly cased assembly names. This is the same behavior of CoreCLR and mono on unix.

**Comment by jeromelaban** [comment]
I'm not trying to load the assembly explicitly, it's the debugger/runtime that does. I made this change https://github.com/jeromelaban/ws-proxy/commit/96c579d90e5d76a16adb73a9808e2eb90eb9f42b#diff-cef10777de86065b0fc5bbe222543bbaR424 which allowed for the breakpoints to hit properly. Though I'm not sure this is the only update that was required, as this one is required as well: https://github.com/jeromelaban/ws-proxy/commit/a7534e75e83accd22701eff28df0d7eb03193823#diff-fd7276410c33a06b1042949c137888bdR300

**Comment by kumpera** [comment]
Any idea of how could I reproduce this?

**Comment by kumpera** [comment]
And I managed by adding an upper case assembly to my solution. Working on it.

**Comment by kumpera** [comment]
Merged the fix ToLower fix to ws-proxy.
