### ISSUE TITLE
A wasm debugging session ends prematurely after 30 seconds

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#9406]
## Steps to Reproduce
1. Follow the instructions for wasm debugging setup
2. Start the debugging session in Chrome, hit a breakpoint
3. Wait.

### Current Behavior
The debugging session stops in the browser, with the debugging proxy showing this exception: 
```
got exception System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.) ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. 
```

It looks like the `browser` websocket is being terminated, [making this line fail](https://github.com/kumpera/ws-proxy/blob/66d6743359c55a6a56416e1b610b4cfc380380b7/WsProxy.cs#L290)

### Expected Behavior
The debugging session keeps going.

## On which platforms did you notice this
Windows

**Version Used**:
https://jenkins.mono-project.com/job/test-mono-mainline-wasm/463/label=ubuntu-1804-amd64/Azure/processDownloadRequest/463/ubuntu-1804-amd64/sdks/wasm/mono-wasm-643e6c47ee5.zip

**Comment by kumpera** [comment]
Could you provide the full log of the web sockets proxy? which version of dotnet core are you using?

I'm on 2.1.300 as the previous one had bugs in the WebSocket client.

**Comment by jeromelaban** [comment]
I was running under this version, but looks like under the debugger another version was running. I made this change: https://github.com/jeromelaban/ws-proxy/blob/96c579d90e5d76a16adb73a9808e2eb90eb9f42b/global.json#L2 and it seems to have fixed it under VS2017 debugging as well.
