### ISSUE TITLE
Use CoreFX Pal for AppleCrypto

### ISSUE THREAD

**Issue by baulig** [mono/mono#9417]
Before I can proceed with my ongoing `System.Security.Certificates.X509Certificates` work, we need to bring some of CoreFX's `System.Security.Cryptography.Native.Apple` PAL.

I have already started to work on this, this task is intended to keep track of progress.

**Comment by baulig** [comment]
Challenges so far:

- We need `SafePasswordHandle` for this: https://github.com/mono/mono/issues/9416
- The native code from CoreFX does not compile with `-Werror=incompatible-pointer-types`
- Need some `.sources` magic in `mcs/class/System` for the `build` profile.

**Comment by filipnavara** [comment]
> The native code from CoreFX does not compile with -Werror=incompatible-pointer-types

IIRC this is already fixed in upstream CoreFX.
