### ISSUE TITLE
build failures on a clean checkout

### ISSUE THREAD

**Issue by vargaz** [mono/mono#9421]
## Steps to Reproduce

git clone git@github.com:mono/mono.git
cd mono/
./autogen.sh --disable-boehm

### Current Behavior
fatal: destination path '/Users/vargaz/git/foo/mono/external/corefx' already exists and is not an empty directory.
fatal: clone of 'git://github.com/mono/corefx.git' into submodule path '/Users/vargaz/git/foo/mono/external/corefx' failed
Failed to clone 'external/corefx' a second time, aborting

## On which platforms did you notice this

[x ] macOS
[ ] Linux
[ ] Windows

**Version Used**:
master
==============================================
So what happens is that metadata/Makefile.am refers to files from external/corefx, so autoconf generates dep files for it in external/corefx/src/Native/Unix/System.Native/.deps/, so by the time git submodule init/update is ran, the external/corefx dir is no longer empty.

Caused by eec6abca721a189ee4f0b1646e73248e24319a95.

**Comment by NattyNarwhal** [comment]
Workaround: run `git submodule update --init` before autogen, or run `git clone` with `--recursive`?

**Comment by marek-safar** [comment]
Any objections to run `submodule update` before autogen?

**Comment by vargaz** [comment]
We can run it before the AOT_OUTPUT line, no idea when automake generates these .dep files.

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-06

**Comment by akoeplinger** [comment]
@monojenkins backport to 2018-08
