### ISSUE TITLE
Performance drop when attaching soft debugger to a mono process started with suspend=n.

### ISSUE THREAD

**Issue by lateralusX** [mono/mono#9422]
Problem is currently reported on a none desktop Windows platform but is probably a generic error that could be hit on other configurations as well.

This is an embedding scenario starting up debugger in server mode without suspending the runtime and waiting for debugger to attach during startup (suspend=n).

Application performance is good until debugger attaches when performance drops significantly and remains poor afterwards. Running the same application, but using suspend=y and attach debugger during startup, doesn't indicate the same performance problems.

Expected the performance to be equal between the two scenarios after initial debugger attach has been done.

**Comment by ntherning** [comment]
@marek-safar Can we add this to the [Bugs Week](../projects/3) board please?

**Comment by lateralusX** [comment]
Should be fixed by https://github.com/mono/debugger-libs/pull/264.

NOTE, when doing late attach against applications embedding Mono and not running Main method, a main method needs to be registered with runtime, or debug client will receive and request information about a NULL thread, shutting down the runtime.
