### ISSUE TITLE
Use of SO_REUSEPORT dictates kernel level of 3.9 or better

### ISSUE THREAD

**Issue by nealef** [mono/mono#9439]
SO_REUSEPORT used by pal_networking but only defined in kernels 3.9 or better.

## Steps to Reproduce

1.  git clone
2. autoconf.sh
3. make

### Current Behavior

  CC     ../../external/corefx/src/Native/Unix/System.Native/libmono_system_native_la-pal_networking.lo
../../external/corefx/src/Native/Unix/System.Native/pal_networking.c:1067:16: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
../../external/corefx/src/Native/Unix/System.Native/pal_networking.c: In function ‘SystemNative_GetSockOpt’:
../../external/corefx/src/Native/Unix/System.Native/pal_networking.c:1709:50: error: ‘SO_REUSEPORT’ undeclared (first use in this function)
../../external/corefx/src/Native/Unix/System.Native/pal_networking.c:1709:50: note: each undeclared identifier is reported only once for each function it appears in
../../external/corefx/src/Native/Unix/System.Native/pal_networking.c: In function ‘SystemNative_SetSockOpt’:
../../external/corefx/src/Native/Unix/System.Native/pal_networking.c:1806:50: error: ‘SO_REUSEPORT’ undeclared (first use in this function)

### Expected Behavior

Clean compilation

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**: mono 2016-08 under Ubuntu - wheezy/sid (3.0.0-12)

## Stacktrace

N/A

**Comment by nealef** [comment]
Circumvention:
```
--- a/src/Native/Unix/System.Native/pal_networking.c
+++ b/src/Native/Unix/System.Native/pal_networking.c
@@ -1704,6 +1704,7 @@ int32_t SystemNative_GetSockOpt(
                 return Error_EINVAL;
             }
 
+#ifdef SO_REUSEPORT
             socklen_t optLen = (socklen_t)*optionLen;
             // On Unix, SO_REUSEPORT controls the ability to bind multiple sockets to the same address.
             int err = getsockopt(fd, SOL_SOCKET, SO_REUSEPORT, optionValue, &optLen);
@@ -1724,6 +1725,9 @@ int32_t SystemNative_GetSockOpt(
                 value = value == 0 ? 1 : 0;
             }
             *(int32_t*)optionValue = value;
+#else
+            *(int32_t*)optionValue = 0;
+#endif
 
             return Error_SUCCESS;
         }
@@ -1773,6 +1777,7 @@ SystemNative_SetSockOpt(intptr_t socket, int32_t socketOptionLevel, int32_t sock
     //
     if (socketOptionLevel == SocketOptionLevel_SOL_SOCKET)
     {
+#ifdef SO_REUSEPORT
         // Windows supports 3 address sharing modes:
         // - not sharing      (SO_EXCLUSIVEADDRUSE=1, SO_REUSEADDR=0)
         // - explicit sharing (SO_EXCLUSIVEADDRUSE=0, SO_REUSEADDR=1)
@@ -1806,6 +1811,9 @@ SystemNative_SetSockOpt(intptr_t socket, int32_t socketOptionLevel, int32_t sock
             int err = setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, &value, (socklen_t)optionLen);
             return err == 0 ? Error_SUCCESS : SystemNative_ConvertErrorPlatformToPal(errno);
         }
+#else
+	return Error_SUCCESS;
+#endif
     }
 #ifdef IP_MTU_DISCOVER
     else if (socketOptionLevel == SocketOptionLevel_SOL_IP)
```

**Comment by directhex** [comment]
Our support matrix covers older kernels (CentOS 6 has a 2.6 kernel???!?!?!?!?!?!) so this ought to be addressed.

**Comment by nealef** [comment]
My suggested circumvention simply pretends the set operation works. Should it return ENOTSUP instead?
