### ISSUE TITLE
Why can't mono directly use the netstandard class library?

### ISSUE THREAD

**Issue by kamikyo** [mono/mono#9441]
Why can't mono directly use the netstandard class library?
I found a problem when using xamarin.android for app development.
I want to use httpclient for https request,but mono's WebRequestHandler has many methods and properties that are not implemented.
This is link:https://github.com/mono/mono/blob/debdc1c1273402d43bccbe156ca608f7af6262f5/mcs/class/System.Net.Http.WebRequest/System.Net.Http.WebRequest/WebRequestHandler.cs#L84
Similarly, the same class of netstandar is implemented very well. 
This is link:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Unix.cs
So, I am confused now.
Mono, xamarin, netstandard, whether they are one or the other.

Remarks: Translated by Google

**Comment by filipnavara** [comment]
There's no such thing as .NET Standard class library. .NET Standard specifies the API contract (ie. what classes are available; their methods and properties), not the implementation. .NET Core (CoreFX) provides one implementation of the contract, other implementations being the Mono one and the .NET Framework one.

There is an ongoing effort to reuse parts of .NET Core (CoreFX) class library for Mono. Specifically System.Net.Http is tracked in issue #6986. Support for client certificates is tracked in issue #7075.

**Comment by marek-safar** [comment]
You can use netstandard library with Xamarin.Android otherwise you'd not hit the issue. The netstandard is not equal to .NET Core for a full explanation see https://msdn.microsoft.com/en-us/magazine/mt842506.aspx.

HttClient on Xamarin.Android does not use WebRequest (or can be configured that way) so that code is not relevant

**Comment by kamikyo** [comment]
@filipnavara @marek-safar Thank you so much. Your answers have made me learn a lot.
