### ISSUE TITLE
Runtime uses multiple instances of custom marshaller for marshalling single argument

### ISSUE THREAD

**Issue by rokups** [mono/mono#9452]
## Steps to Reproduce

Code reproducing issue:
```cs
struct MarshalTest : ICustomMarshaler
{
    private IntPtr _stored;
    public static ICustomMarshaler GetInstance(string _)
    {
        return new MarshalTest();        // This is important
    }

    public void CleanUpManagedData(object ManagedObj)
    {
    }

    public void CleanUpNativeData(IntPtr pNativeData)
    {
        System.Console.WriteLine($"CleanUpNativeData: _stored = {_stored}, pNativeData = {pNativeData}, identity = {GetHashCode()}");
    }

    public int GetNativeDataSize()
    {
        return -1;
    }

    public IntPtr MarshalManagedToNative(object ManagedObj)
    {
        _stored = (IntPtr)int.Parse((string)ManagedObj);
        System.Console.WriteLine($"MarshalManagedToNative: _stored = {_stored}, returning = {_stored}, identity = {GetHashCode()}");
        return _stored;
    }

    public object MarshalNativeToManaged(IntPtr pNativeData)
    {
        System.Console.WriteLine($"MarshalNativeToManaged: {pNativeData}");
        return pNativeData.ToString();
    }
}

[DllImport("NativeLibrary", CallingConvention = CallingConvention.Cdecl)]
private static extern void TestMarshalling([param: MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(MarshalTest))]ref string p);

public static void Main(string[] args)
{
    var param = "1";
    TestMarshalling(ref param);
}
```
```cpp
EXPORT_API void TestMarshalling(void** ptr)
{
    *ptr = (void*)2;
}
```

### Current Behavior

mono 5.12.0 prints:

    MarshalManagedToNative: _stored = 1, returning = 1, identity = 1192725433
    MarshalNativeToManaged: 2
    CleanUpNativeData: _stored = 0, pNativeData = 2, identity = 1192725432

Mono calls `MarshalManagedToNative()` on one instance of the struct and then calls `CleanUpNativeData()` on a new instance. Due to this behaviour no state (like `_stored`) can be used in custom marshaller.

### Expected Behavior

.net framework 4.7 prints:

    MarshalManagedToNative: _stored = 1, returning = 1, identity = 346948957
    MarshalNativeToManaged: 2
    CleanUpNativeData: _stored = 1, pNativeData = 2, identity = 346948957

Like .net framework, mono should use same instance of marshaller for all operations for marshalling a argument or return value.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.12.0 (makepkg/58637d0ee7c Wed Jun  6 22:41:15 CEST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

**Comment by kg** [comment]
Started on this but didn't get a usable patch ready by the end of the week. We currently create a new instance every time we call a custom marshaler method, universally. The fix I think we need to make is to move most of this logic into managed code so we can properly cache the custom marshalers. The correct way for it to work is to have a single cached instance per type+cookie pair (not, as you might have assumed from the bug repro, a single instance per marshaled call or per argument). We need to be careful to do the right thing if the marshaler is a struct (as in the bug repro).

**Comment by kg** [comment]
For time-saving the next time someone looks at this, here is a test-case that should work on linux .net core and linux mono. Should work on Windows too but I didn't do the work to make native.c export the entry point.
[marshalertest.zip](https://github.com/mono/mono/files/2198476/marshalertest.zip)

**Comment by rokups** [comment]
> The correct way for it to work is to have a single cached instance per type+cookie pair (not, as you might have assumed from the bug repro, a single instance per marshaled call or per argument).

Why is that? My assumption for per-argument marashaller stems from from a need to properly free memory when native code overwrites pointer of `ref` parameter. If this is done per-type+cookie then tracking additional data becomes impossible. Of course this is not that big of a deal, i will just use different cookies for each parameter, but i am still interested in reasons behind this requirement.

P.S. Thank you for taking this on this quick :+1:

**Comment by kg** [comment]
It's not a documented requirement, so I was surprised by this behavior as well. I guess they expect you to track the per-argument data elsewhere. It definitely works that way on both windows .net framework and linux .net core. I suspect it's for performance reasons.
