### ISSUE TITLE
fullaotmixed-regression test fails on Linux x64 Interpreter

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#9501]
The crash can be seen here: 
https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter/7196/parsed_console/log_content.html#WARNING1

(To load the error in a reasonable amount of time)
https://gist.github.com/alexanderkyte/dd0882dc83d7b451f83c43b92c99c526

**Comment by lewurm** [comment]
fixed by https://github.com/mono/mono/commit/a0d0af6d3998fcd969ca09659fd72d49bbf14193#diff-307195a8afdfeac6e3df25eef5aaf9d6R2769
