### ISSUE TITLE
flaky runtime.finalizer-exception.exe (Assertion at unwind.c:640, condition `cfa_reg != -1' not met)

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#9566]
## Steps to Reproduce

1. Submit a PR. 

### Current Behavior

Failures, for example:

https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/11720/

MonoTests.runtime.finalizer-exception.exe

https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/11720/testReport/junit/MonoTests/runtime/finalizer_exception_exe/

```
Failing for the past 1 build (Since Unstable#11720 )
Took 0.38 sec.
add description
Stacktrace
                                                MESSAGE:
                                                caught
* Assertion at unwind.c:640, condition `cfa_reg != -1' not met

* Assertion at mini-exceptions.c:1191, condition `unwind_options == MONO_UNWIND_NONE' not met

                                                +++++++++++++++++++
                                                STACK TRACE:
                                                Stacktrace:
```

For this we probably could use some EH stress that forces
an exception at every instruction or every call, or every call and dereference.

### Expected Behavior

Success.

**Comment by jaykrell** [comment]
Another instance:

https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/11707/

MonoTests.test-unhandled-exception-2-255-with-managed-handler.unhandled-exception-2.exe

https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/11707/testReport/junit/MonoTests/test-unhandled-exception-2-255-with-managed-handler/unhandled_exception_2_exe/

**Comment by DaanTacoSchool** [comment]
not a 100% sure this is the correct thread, but the error in the title still appears. i can find a lot about it in unity threads, but for me it occurs in VS2017 w/ Xamarin forms. in the android emulator. see the [link](https://forums.xamarin.com/discussion/69205/ios-crash-error?) for details

**Comment by BrzVlad** [comment]
@DaanTacoSchool This error is not really actionable from the assertion only, we would need a reproduction case. In the meantime, for the next release, I'll include additional logging when this error shows so we can hopefully debug it more easily.

**Comment by DaanTacoSchool** [comment]
I Cannot supply a reproduction case as i dont know what causes this. It
happens on all installed emulators. (ranging from api 26-28 and ram
512mb-2gb, even the heap size and renderes are varying). this occurred
since android studio was installed alongside visual studio (which should be
a problem) and visual studio received an update. to 15.9.3.


Op di 4 dec. 2018 09:18 schreef Vlad Brezae <notifications@github.com:

**Comment by DaanTacoSchool** [comment]
@BrzVlad I narrowed down the cause to a method in the REST service implementation. To be more specific the following line;
`  oc = JsonConvert.DeserializeObject<ObservableCollection<T>>(content);`

This is wierd as this line hasnt changed for the last months. it throws the following error without native stacktrace;
`* Assertion at /Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/mono/mini/unwind.c:640, condition `cfa_reg != -1' not met`

The JsonConvert method is from the newtonsoft.json niuget package. which i guess internally calls the mono assert. i will try to find out if this is the case.

**Comment by jaykrell** [comment]
But is it fixed by?
https://github.com/mono/mono/commit/bbd6a6a286119387d0a1d71cdd2172fafd7d995b
?
What version are you  running?

**Comment by DaanTacoSchool** [comment]
@jaykrell  the reference in the android project says Runtime version v4.0.30319 (the dotnet version its compiled against) the version field (version of reference) shows as 0.0.0.0 and the xamarin forms dependency (in root proj.) is 3.0.0.561731
