### ISSUE TITLE
Update macOS minimal version

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#9581]
Due to limitations in the TLS stack on 10.7, we are updating the minimum macOS development target from 10.7 to 10.9. Mono will be supported only on 10.9 or newer versions.

We need to update configure checks and documentation at least at https://www.mono-project.com/docs/about-mono/supported-platforms/macos/

**Comment by akoeplinger** [comment]
See https://github.com/mono/mono/commit/ef995321161f69eacd324e0e1cffef6ff1317079 for where we need to bump.

Note: looks like we forgot to bump `--host` and `--build` there, `i386-apple-darwin11.2.0` still means 10.7. There are a few more matches for `apple-darwin11` and even `apple-darwin10` in mono and bockbuild, we should fix those too.

**Comment by kg** [comment]
This is next on my todo list. If it's blocking you I can stop what I'm doing to try to knock it out.

**Comment by baulig** [comment]
It is "blocking" in the sense that I require a commitment towards this happening in 2018-08.  It is irrelevant to me at which point in the 2018-08 integration process this is happening as I can easily do it locally for the time being.

In other words, as long as I can expect this to happen for 2018-08, it makes no difference to me when it is going to happen.
