### ISSUE TITLE
Visual Studio for Mac crash on startup with Mono 5.14

### ISSUE THREAD

**Issue by mrward** [mono/mono#9592]
## Steps to Reproduce

Install a recent Mono 5.14 and try to run Visual Studio for Mac.

Reported on the Developer Community Forum - https://developercommunity.visualstudio.com/content/problem/294242/visual-studio-keeps-crashing-2.html

Also saw this locally when running Visual Studio for Mac with Mono 5.14.0.161.

https://gist.github.com/mrward/94570bdfdb772d65045f358029e26416

### Current Behavior

Visual Studio for Mac crashes on startup.

### Expected Behavior

Visual Studio for Mac launches.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono 5.14.0.161 (2018-04/c95a4a2d2c5) (64-bit)
Mono 5.14.0.167 (2018-04/d4a680b045c) (64-bit)

## Stacktrace

https://gist.github.com/mrward/94570bdfdb772d65045f358029e26416
https://developercommunity.visualstudio.com/storage/attachments/34950-ide2018-07-16-20-23-44.log

**Comment by Therzok** [comment]
cc @bratsche seems related to the gtk fix we did for nsviews

**Comment by marek-safar** [comment]
@mrward does it crash all the time?

@bratsche could you estimate when you can address the issue?

**Comment by mrward** [comment]
Yes, VS Mac was crashing on startup every time when I trying a recent Mono 5.14.

**Comment by bratsche** [comment]
Sorry, I still don't have a proper fix for this. Until I can get one can we disable this patch?

**Comment by mykyta-bondarenko-gl** [comment]
HI, I have the same issue. VSfM crashes if the mono 2018-04 is installed. 
VSfM - release 7.6 (7.6.0.2056) 
Mono - 2018-04 (5.14.0.160)

- System Report:
[https://gist.github.com/mykyta-bondarenko-gl/2c31dcbd203153d560d29c734a880de4](https://gist.github.com/mykyta-bondarenko-gl/2c31dcbd203153d560d29c734a880de4)
- VSfM log:
[https://gist.github.com/mykyta-bondarenko-gl/54ab16f5aa1ccbef26c073264f124ce6](https://gist.github.com/mykyta-bondarenko-gl/54ab16f5aa1ccbef26c073264f124ce6)

**Comment by marek-safar** [comment]
Fixed by the bump
