### ISSUE TITLE
binary sym file for electron crash reporter

### ISSUE THREAD

**Issue by goldylucks** [mono/mono#9603]
I haven't found sym files in the repo or the [website](https://www.mono-project.com/).

I think it would be useful to have them in an easy to access place, instead of each developer creating it on their own.

Thoughts?

Debug identifier: `56050FFDF5F0342099F4CC45B120E20F0`
file name: `mono`

**Comment by marek-safar** [comment]
We don't store them

**Comment by goldylucks** [comment]
I see that, im saying it will be valuable to have reference for that.

And for someone who knows how to do so, this will take probably a few
minutes
