### ISSUE TITLE
MSBuild ResolveAssemblyReferences is significantly slower than on .NET

### ISSUE THREAD

**Issue by Therzok** [mono/mono#9657]
## Steps to Reproduce

1. Build MonoDevelop on Mono
2. Build MonoDevelop on Windows
3. Observe MSBuild falls back to multiple dll resolution on Mono

### Current Behavior

Mac build log: https://gist.github.com/Therzok/a793d4a0dfae22bede8a422fe357a6a1
Windows build log: https://gist.github.com/Therzok/d541b3c5a190f611f70e0476780d8592

It seems that nuget packages from corefx (i.e. System.IO.Compression) don't match in version number with the BCL assemblies for swapped libraries.

The builds are almost identical. If you grep for `No way to resolve conflict between`, you'll see a handful of assemblies that do not appear on the Windows build, as opposed to the Mono build.

### Expected Behavior

They should match on both Mac and Windows

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Anything 5.12+ (it most likely happens in earlier versions)

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by Therzok** [comment]
Adding more info:

What happens there is that when `no way to resolve conflict between` happens, MSBuild will fallback to iterating the GAC and framework folders to find the best match.

This causes NOP builds of MonoDevelop to take 40 seconds.

When building on Windows, the ResolveAssemblyReferences does not take the amount of time it does for MSBuild on mono.

The only differences I could see between the two binlogs I viewed were these assembly version mismatches between corefx's nuget package versions and mono's gac/framework folder versions of the same dll.

**Comment by marek-safar** [comment]
@radical this is probably not a strictly msbuild issue but could you come up with ideas how we can fix the issue.

**Comment by Therzok** [comment]
Reminder: upload binlogs for both NOP builds

One thing to check is whether settings `<SpecificVersion>false</SpecificVersion>` fixes this.

**Comment by Therzok** [comment]
Sharing privately, as binlogs contain secrets...

**Comment by Therzok** [comment]
Closing. Will reopen when I have performance tracing on both platforms demonstrating differences.
