### ISSUE TITLE
Regression: bug in Type.GetMethod(string name)

### ISSUE THREAD

**Issue by rvdginste** [mono/mono#9685]
## Steps to Reproduce

The following code gives an AmbiguousMatchException on mono 5.14.0.167, while it runs fine on mono 5.12.0.226.

I noticed this already on earlier versions of mono-5.14 but never took the time to figure out what exactly was causing the issue.

```
// works fine on 5.12
// AmbiguousMatchException on 5.14
var methodInfo1 = typeof(string).GetMethod(nameof(string.Contains));

// works fine on both 5.12 and 5.14
var methodInfo2 = typeof(string).GetMethod(nameof(string.Contains), new[] { typeof(string) });
```

### Current Behavior

The code gives an AmbiguousMatchException, even though there is only one public method on string with the name "Contains". GetMethod(string) should return the public method with the given name, and only give an AmbiguousMatchException when there are multiple public methods with the given name.

### Expected Behavior

Method returns the MethodInfo for 'string.Contains(string)'.

## On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

(Not tested on Windows.)

**Version Used**:

```
Mono JIT compiler version 5.14.0.167 (tarball Tue Jul 17 10:02:38 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)
```

This version comes from the debian packages distributed on mono-project.com:

```
ruben@raptor ~ $ apt-cache policy mono-runtime
mono-runtime:
  Installed: 5.14.0.167-0xamarin3+debian9b1
  Candidate: 5.14.0.167-0xamarin3+debian9b1
  Version table:
 *** 5.14.0.167-0xamarin3+debian9b1 500
        500 http://download.mono-project.com/repo/debian preview-stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     5.12.0.226-0xamarin3+debian9b1 500
        500 http://download.mono-project.com/repo/debian stretch/main amd64 Packages
     4.6.2.7+dfsg-2 110
        110 http://ftp.belnet.be/debian unstable/main amd64 Packages
     4.6.2.7+dfsg-1 600
        600 http://ftp.belnet.be/debian testing/main amd64 Packages

```

## Stacktrace

No stracktrace.

**Comment by EgorBo** [comment]
It might look like a breaking change but actually it now matches .NET Core's behavior (same exception is thrown for this case).

**Comment by rvdginste** [comment]
Ok, I see that in .NET Core 2.1 there are 2 methods [string.contains](https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?view=netcore-2.1) and then the AmbiguousMatchException is normal.

However, the project where I noticed this, has as target framework net47. Does this mean that mono does not take into account the target framework and currently aims to match the .NET Core api?

**Comment by EgorBo** [comment]
@rvdginste Mono uses CoreFX (.NET Core) sources for String (see https://github.com/mono/mono/blob/master/mcs/class/corlib/corlib.dll.sources#L1640-L1643) for all profiles

**Comment by rvdginste** [comment]
Ok, clear. I didn't know this. Then this issue can be closed.
Thanks!
