### ISSUE TITLE
Mono in WebAssembly has some memory leak.

### ISSUE THREAD

**Issue by kant2002** [mono/mono#9698]
## Steps to Reproduce

1. Create Blazor application (internally used Mono in WebAssembly)
2. Add `<input type="file" onchanged="uploadFile" />`
3. Implement uploading procedure as described in Blazor docs

### Current Behavior

When I upload 900KB file, everything is good and processing is working.
But when I try to upload 7818KB file, then Mono crashing with error below.

### Expected Behavior

I expect OutOfMemoryException happens, or if there some memory limit in the browser, at least clearly report that browser has some memory limite.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows / WebAssembly inside Chrome and Edge

**Version Used**:

Mono under WebAssembly.

## Stacktrace

```
mono.js:1 Uncaught (in promise) RuntimeError: memory access out of bounds
    at wasm-function[290]:104
    at wasm-function[2458]:125
    at wasm-function[563]:16
    at wasm-function[246]:115
    at wasm-function[2428]:33
    at wasm-function[2429]:41
    at wasm-function[4877]:10
    at Module._mono_wasm_string_from_js (http://localhost:58134/_framework/wasm/mono.js:1:173587)
    at ccall (http://localhost:58134/_framework/wasm/mono.js:1:5651)
    at http://localhost:58134/_framework/wasm/mono.js:1:6032
```

Original error reported in https://github.com/aspnet/Blazor/issues/1167

**Comment by kant2002** [comment]
If I split file on chunks of 1Mb, then processing starts working.

**Comment by w8w8w8** [comment]
when I used blazor.  I use javascript setInterval call the .NET methods, then .NET methods call javascript function to update svg(text,image) dom(>300) value.
but , 2 hours later, the chrome crash.
I think it  has some memory leak too

**Comment by jonmiller1** [comment]
I'm having the same issue when uploading a 10MB file in blazor.  I'm getting the same error.

**Comment by kumpera** [comment]
This is due to how blazor does binary marshaling and configures the mono runtime during initialization to have no explicit memory limits.

Without an explicit memory limit, it's not possible to fail cleanly and throw an OOM Exception.

**Comment by SteveSandersonMS** [comment]
@kumpera Hopefully we can chat about how Blazor should best fix this. We definitely need to be able to fetch 10MB files :) Currently the binary marshalling for HTTP responses is:

* JS-side code calls .NET asking it to allocate a byte array of the required length. .NET side returns a pointer.
* JS-side code copies the response array buffer into the WASM heap at that location
* .NET-side code passes the populated array back to user code.

I'm not sure what we should do differently, but would love to get your input.

**Comment by SteveSandersonMS** [comment]
Oh wait, the bug is about **uploading**, not downloading. That marshalls differently. Maybe we need to make it marshal the request body in the same way as for the response body.

**Comment by kjpou1** [comment]
@SteveSandersonMS this may have been addressed with https://github.com/mono/mono/pull/11840.

Specifically due to allocation of a byte array.

**Comment by w8w8w8** [comment]
@jonmiller1 
can you see this question? I do not know how to fix this .
https://github.com/mono/mono/issues/10250
thank you

**Comment by kjpou1** [comment]
Closing this for now.  Please re-open if it is still causing problems.
