### ISSUE TITLE
[loader] LoadFile from application base should load in default context

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#9753]
If an assembly is found in the application base directory, even if starting from `LoadFrom` or `LoadFile`, it should go into the default context.  That affects loading of subsequent referenced assemblies:

[LoadAndReference.zip](https://github.com/mono/mono/files/2233363/LoadAndReference.zip)

Here we have `Main.exe` which can do either a `LoadFrom` or a `LoadFile` of `Thing.dll` which, in turn, references `Relative.dll`.

The behavior of .NET Framework observed with FUSLOGVW:

* if all three assemblies are in the same directory, then both Thing.dll and Relative.dll are found and loaded into the default context.
* if Thing.dll and Relative.dll are both in an unrelated directory
  * `LoadFile` will load Thing.dll in an individual load context and subsequently fail to find `Relative.dll` (it's says it's starting from the default context).
  * `LoadFrom` will load Thing.dll in LoadFrom context and subsequently find `Relative.dll` next to Thing.dll and load it also in LoadFrom context.
* if Thing.dll is in an unrelated directory, but Relative.dll is next to Main.dll then:
  * `LoadFrom`  will load Thing.dll in LoadFrom context; then Relative.dll will be searched for starting in LoadFrom context and successfully loaded in the default context since it's in the application base directory.
  * `LoadFile` will load Thing.dll in individual context; then Relative.dll will be searched for starting in the default context and successfully loaded in the default context since it's in the application base directory.

This is kind of related to #9542 in that assemblies in the application base directory, even if loaded using `LoadFrom` or `LoadFile` should load in a default context. (In 9542 we actually _don't_ want to be in the default context, but here we _do_).

**Comment by lambdageek** [comment]
oh. also this is a regression in `2018-06` from `2018-04` since before we had asmctx in Mono, LoadFile was just an alias for LoadFrom and they both used to look in the application base (and now they don't).

This affects some nunitlite runners because you end up with a single directory containing `nunitlite-runner.exe, someAsmFullOfTests.dll, someImplementationAsm.dll, someOtherDependency.dll`

if you say `mono nunitlite-runner.exe someAsmFullOfTests.dll`, the first thing the runner does is call `LoadFile` on the test assembly and then iterate over all the types in it. that causes referenced assemblies to be probed and `someImplementationAsm` and `someOtherDependency` are not found since our buggy individual context doesn't look in the application base.  😢

**Comment by alanmcgovern** [comment]
👍

**Comment by alanmcgovern** [comment]
This is a blocker for 15.9 testing/releasing now!

/cc @Aguilex
