### ISSUE TITLE
Flaky IO.Pipes.Tests.AnonymousPipeTest_*

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#9776]
See these on a few PRs this morning.

## Steps to Reproduce

1. Submit a PR.

### Current Behavior

Fails.
For example:

https://github.com/mono/mono/pull/9768

https://jenkins.mono-project.com/job/test-mono-pull-request-i386/16378/#showFailuresLink

```
	Test Result (3 failures / ±0)
.IO.Pipes.Tests.AnonymousPipeTest_Specific.ClonedServer_ActsAsOriginalServer
.IO.Pipes.Tests.AnonymousPipeTest_Write_ServerIn_ClientOut.WriteToPipeWithClosedPartner_Throws_IOException
.IO.Pipes.Tests.AnonymousPipeTest_Write_ServerOut_ClientIn.WriteToPipeWithClosedPartner_Throws_IOException
```

### Expected Behavior

Success.

**Comment by filipnavara** [comment]
Uh, the failure are actually because some API is missing in the PAL:

```
      ---- System.EntryPointNotFoundException : SystemNative_ConvertErrorPlatformToPal
      Stack Trace:
          at (wrapper managed-to-native) Interop+Sys.ConvertErrorPlatformToPal(int)
```

I will check it tonight unless someone beats me to it.

**Comment by filipnavara** [comment]
I think it's broken since https://github.com/mono/mono/commit/1e9be63015ee88ec2e7ca6d92c22904902989440#diff-0ff844e784e15d2542b71c85d2c0133e. There's `if !TARGET_WIN32` in the Makefile that prevents inclusion of many PAL files. /cc @alexischr

**Comment by alexischr** [comment]
@filipnavara Sorry about that, I'm not sure how I missed that. I'll fix it up

**Comment by jaykrell** [comment]
Eek, how did that get merged?

**Comment by filipnavara** [comment]
@alexischr Sorry. I may have misread the diff. Nevertheless it looks like some configuration doesn't include correct PAL files.

**Comment by filipnavara** [comment]
@alexischr BTW, I think the problem is that ENABLE_MONODROID (and same for MONOTOUCH) means "enable the profiles along with the other ones", not "building for Android/iOS exclusively".
