### ISSUE TITLE
CurrentThread.CurrentCulture and CurrentUICulture are returning "en-EN" with Chinese Traditional

### ISSUE THREAD

**Issue by netonjm** [mono/mono#9827]
I am targeting this issue in Mac

## Steps to Reproduce
 language selected like main language.

1. Change your main language in Settings to Chinese Traditional
2. Create a empty Xamarin.Mac application with NetFramework 4.6 platform
3. Get current values for:
`var culture = Thread.CurrentThread.CurrentCulture;`
            `var uiCulture = Thread.CurrentThread.CurrentUICulture;`

Expected
Both should be : zh-CHT
Result: en-EN

(looks like is failing for some reason and returning the default language)

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.10.1.57 (2017-12/ea8a24b1bbf Tue Apr 24 14:53:01 EDT 2018)

**Comment by netonjm** [comment]
Ok, discovered what was the issue, not related to mono. thanks!

**Comment by bocciab** [comment]
Can you say what it was? I'm seeing the same thing. I set my Region to China in System Preferences, but the region code always comes back US.

**Comment by bocciab** [comment]
I’m not sure why a three year old technical note would cause just the CN region setting to cause RegionInfo.CurrentRegion and CultureInfo.CurrentCulture to return as US while other regions (changing to United Kingdom returns GB as it should) work fine.

**Comment by Therzok** [comment]
macOS itself changed behaviour for this, even native mac apps which don't have a preferred language will default to the english locale (region in your case `en-GB` is still a match, as it only tries `en`).

**Comment by bocciab** [comment]
Foundation.NSLocale.CurrentLocale in Xamarin.Mac returns the correct language, culture and region info in the same app. I’ve switched to using that in place but it seems like mono could return the correct values if Xamarin, based on mono, can.
