### ISSUE TITLE
Make Command Failing on IBM i

### ISSUE THREAD

**Issue by ThreeNameNelson** [mono/mono#9842]
## Steps to Reproduce

1. ./autogen.sh --prefix=/home/NELSONCJ/mono
2. make get-monolite-latest
3.  make

### Current Behavior

Make command is failing:

mv: cannot rename t-es.gmo to es.gmo: 
No such file or directory

### Expected Behavior

The make command to complete successfully.

## On which platforms did you notice this

IBM i v7.3

**Version Used**:

N/A - no working mono installation.

## Stacktrace

Here is the failing step when calling 'make'.
![make](https://user-images.githubusercontent.com/40034530/43529087-1dda27fa-9570-11e8-9c0d-369b70ae8bf8.JPG)

Here is the complete output from running the steps to reproduce.
[output.txt](https://github.com/mono/mono/files/2249897/output.txt)

### Notes

I'm attempting to install mono on the IBM i v7.3 that @NattyNarwhal made a post about on the Mono blog. It is failing to build when calling the 'make' command. Since there is no mono distribution for released IBM i distribution (or AIX) I'm using monolite.

I can see the obvious, it failed to rename something but why that happened and how to fix it is what I'm curious about.

Any ideas as to what is causing this issue?

**Comment by NattyNarwhal** [comment]
Do you have gettext installed? This happens on any platform where you don't have gettext's translation file management tools.

**Comment by NattyNarwhal** [comment]
Also, I do have a [periodically updated set of builds](https://github.com/MonoOni/binarydist) available. These aren't official builds from the Mono project, but I will try to help you with those.

**Comment by ThreeNameNelson** [comment]
So I can either do a build from the source, or do the save/restore?
Or are they not mutually exclusive? If so, is any one better than the other?

I appreciate your quick response. Thanks for the assistance!

**Comment by NattyNarwhal** [comment]
The binary builds are built on an irregular schedule, but kept reasonably in date. If you just want to try it out, restoring the savefile will be easiest, and has all dependencies baked in.

Building from source will be useful for when you want to actually start writing patches for Mono.

**Comment by ThreeNameNelson** [comment]
Spoken like a true developer.

Thanks!

**Comment by ThreeNameNelson** [comment]
For posterity to others attempting to build mono on the IBM i (aka as400) and might come across this issue - make sure all tools are updated to latest released versions. I was getting a segfault during the make process because 'cmake' wasn't at the latest release.

Everything builds fine now.

@NattyNarwhal I appreciate the help. Thanks.
@marek-safar I don't see anywhere I can change the labels so I'm mentioning you, but the 'os-linux' label is incorrect. It should be 'os-ibmi' or 'os-as400' (the previous name for the IBM i). While Mono does run in PASE (Portable Application System Environment) which is like an AIX emulator, the base OS is not Linux.
