### ISSUE TITLE
watchOS: linker failure with llvm: don't know how to convert branch instruction

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#9867]
## Steps to Reproduce

1. Checkout & build the `mono-2018-06` branch from xamarin-macios
2. `msbuild "tests/linker/ios/dont link-watchos.csproj /p:Configuration=Release /p:Platform=iPhone"`

### Current Behavior

    error MT5209 : Native linking error : don't know how to convert branch instruction ff0fe7e6 referencing _memset.island to bx in '_mscorlib_Mono_Globalization_Unicode_SimpleCollator_CompareInternal_string_int_int_string_int_int_bool__bool__bool_bool_Mono_Globalization_Unicode_SimpleCollator_Context_' from /var/folders/k6/t7zlb7s502n6hx9fmqptp3w40000gp/T/mscorlib

Full build log: https://gist.github.com/rolfbjarne/fdeafad86a954901d2c453b02f32e2dc

### Expected Behavior

Successful build

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Comment by vargaz** [comment]
I think this has nothing to do with the llvm bump, it fails the same way when using the old 3.6 based llvm.

Its probably have to do with the increased bcl code size: it happens on the dontlink test on watchos.

Some comments:
- mtouch passes all the .bc files to clang which seems to compile them sequentially, so its very slow.
- clang is not passed the -O2 argument so it doesn't generate optimized code. Passing -O2
  makes the compilation even more slow, but fixes the problem.

Suggestion: remove do-not-link support at least for watchos. It has no use, and it only leads to bugs like
this.

**Comment by rolfbjarne** [comment]
Looks like this is the watchOS version of https://bugzilla.xamarin.com/show_bug.cgi?id=1102.

**Comment by marek-safar** [comment]
@rolfbjarne are you ok to close this as by-design?

**Comment by rolfbjarne** [comment]
@marek-safar yes, that's fine.

**Comment by vargaz** [comment]
We should disable dontlink for watchos somewhere in mtouch or the ide.
