### ISSUE TITLE
iOS: 32-bit device unit test failure: [FAIL] FSharpTest.SprintfTest :   Expected: True

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#9870]
## Steps to Reproduce

1. Checkout & build the `mono-2018-06` branch from xamarin-macios
2. Open tests/tests.sln
3. Select the fsharp project as the startup project, and select a Debug32|iPhone configuration (this failure does not happen in 64-bit).
4. Execute and run all the tests

### Current Behavior

    [FAIL] FSharpTest.SprintfTest :   Expected: True
        But was:  False
		  at fsharp.FSharpTest.SprintfTest () [0x00052] in /work/maccore/mono-master/xamarin-macios/tests/fsharp/FSharpTests.fs:34 
		  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)

improving the test a bit gets me a better assert message:

    [FAIL] FSharpTest.SprintfTest :   String lengths are both 24. Strings differ at index 10.
      Expected: "1111 2222 3333 4444 5555"
      But was:  "1111 2222 4444 3333 5555"
      ---------------------^
    at fsharp.FSharpTest.SprintfTest () [0x00044] in /work/maccore/mono-master/xamarin-macios/tests/fsharp/FSharpTests.fs:33 
    at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)

### Expected Behavior

No test failure.

## On which platforms did you notice this

[x] iOS
[ ] macOS
[ ] Linux
[ ] Windows

**Comment by vargaz** [comment]
Did this use to work ?

**Comment by vargaz** [comment]
Which was the last version where this was tested and it succeeded ?

**Comment by jaykrell** [comment]
Does this require device or repros in emulator?
Simple desktop/amd64 test passes.

**Comment by rolfbjarne** [comment]
@jaykrell it requires an iOS device capable of running 32-bit code

@vargaz it passes in d15-7.

the same thing happens with watchOS on device:

    FSharpTest
    	[PASS] FSharpTest.Func
    	[FAIL] FSharpTest.SprintfTest :   Expected string length 24 but was 32. Strings differ at index 5.
      Expected: "1111 2222 3333 4444 5555"
      But was:  "1111 57822332 2222 57822332 5555"
