### ISSUE TITLE
iOS: 32-bit apps built with LLVM crashes at launch

### ISSUE THREAD

**Issue by rolfbjarne** [mono/mono#9872]
## Steps to Reproduce

1. Checkout & build the `mono-2018-06` branch from xamarin-macios
2. Open tests/tests.sln
3. Select the `link all` project as the startup project, and select a Release32|iPhone configuration (this is a 32-bit only issue)
4. Execute the app

### Current Behavior

Crash at launch:

    (lldb) run
    Process 540 launched: '/work/maccore/mono-master/xamarin-macios/tests/linker/ios/link all/bin/iPhone/Release32-unified/link all.app/link all' (armv7)
    Process 540 stopped
    * thread #1, name = 'tid_c07', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
        frame #0: 0x00000000
    error: memory read failed for 0x0
    Target 0: (link all) stopped.
    (lldb) bt
    * thread #1, name = 'tid_c07', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
      * frame #0: 0x00000000
        frame #1: 0x002584dc link all`mscorlib_System_Type_FindInterfaces_System_Reflection_TypeFilter_object at type.cs:616 [opt]
        frame #2: 0x0044e15c link all`Xamarin_iOS_Registrar_SharedDynamic_PrepareInterfaceMethodMapping_System_Type at DynamicRegistrar.cs:30 [opt]
        frame #3: 0x0044f018 link all`Xamarin_iOS_Registrar_DynamicRegistrar_PrepareMethodMapping_System_Type at DynamicRegistrar.cs:301 [opt]
        frame #4: 0x0042b2f4 link all`Registrar_Registrar_RegisterTypeUnsafe_System_Type_System_Collections_Generic_List_1_System_Exception_(this=0x01900430, param0=0x023ac390, param1=20672136) at Registrar.cs:2220
        frame #5: 0x00454fa0 link all`Xamarin_iOS_Registrar_Registrar_RegisterType_System_Type_System_Collections_Generic_List_1_System_Exception_ at Registrar.cs:1416 [opt]
        frame #6: 0x00452da8 link all`Xamarin_iOS_Registrar_DynamicRegistrar_Register_System_Type at DynamicRegistrar.cs:1159 [opt]
        frame #7: 0x0046cc48 link all`Xamarin_iOS_ObjCRuntime_Class_Register_System_Type at Class.cs:205 [opt]
        frame #8: 0x0046498c link all`Xamarin_iOS_ObjCRuntime_Runtime_RegisterAssembly_System_Reflection_Assembly at Runtime.cs:593 [opt]
        frame #9: 0x0046451c link all`Xamarin_iOS_ObjCRuntime_Runtime_RegisterAssembly_intptr at Runtime.cs:385 [opt]
        frame #10: 0x0045fb74 link all`Xamarin_iOS_ObjCRuntime_Runtime_register_assembly_intptr_int_ at Delegates.generated.cs:118 [opt]
        frame #11: 0x0043e29c link all`wrapper_native_to_managed_ObjCRuntime_Runtime_register_assembly_intptr_int_(param0=26215080, param1=20672440) + 176
        frame #12: 0x010d8124 link all`::xamarin_initialize() [inlined] xamarin_register_assembly(assembly=<unavailable>, exception_gchandle=0x00000000) at delegates.inc:102 [opt]
        frame #13: 0x010d8118 link all`::xamarin_initialize() [inlined] register_assembly(assembly=<unavailable>) at runtime.m:960 [opt]
        frame #14: 0x010d80f4 link all`::xamarin_initialize() at runtime.m:1373 [opt]
        frame #15: 0x010def68 link all`::xamarin_main(argc=1, argv=<unavailable>, launch_mode=XamarinLaunchModeApp) at monotouch-main.m:428 [opt]
        frame #16: 0x000b0aa2 link all`main(argc=1, argv=0x013b7c68) at main.m:79
        frame #17: 0x20660872 libdyld.dylib`start + 2

### Expected Behavior

No crash

**Comment by vargaz** [comment]
Can't reproduce this anymore.

**Comment by rolfbjarne** [comment]
I can confirm this doesn't reproduce anymore.
