### ISSUE TITLE
GPG error: https://download.mono-project.com/repo/ubuntu preview-bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A6A19B38D3D831EF

### ISSUE THREAD

**Issue by mi-hol** [mono/mono#9891]
WSL can not retrieve Mono's public key from Ubuntu repository 

## Steps to Reproduce

1. WSL - Ubuntu 18.04.1
2. sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

### Current Behavior

error:
Executing: /tmp/apt-key-gpghome.5tmP6rjryd/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.5tmP6rjryd/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr

### Expected Behavior

no error

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x ] Windows

**Version Used**:
uname -a
Linux W10D-RS4 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

 `mono --version` 
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by marek-safar** [comment]
@directhex could you check this

**Comment by directhex** [comment]
Can you make sure you have `dirmngr` installed? It seems it might be in the regular base install of Ubuntu, but missing from the WSL image

**Comment by mi-hol** [comment]
seems installed and microsoft repository for <PowerShell got added earlier

sudo apt-get install dirmngr
Reading package lists... Done
Building dependency tree
Reading state information... Done
dirmngr is already the newest version (2.2.4-1ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

sudo apt update
[sudo] password for mihol:
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 https://download.mono-project.com/repo/ubuntu preview-bionic InRelease [5154 B]
Hit:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
...

**Comment by directhex** [comment]
If you want to take the same approach, passing curl to apt-key add, you can:

`curl https://download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -`

**Comment by mi-hol** [comment]
1. Thx, this worked
curl https://download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2125  100  2125    0     0    362      0  0:00:05  0:00:05 --:--:--   494
OK

2. Original command gives error not a key ID: skipping
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831E
[sudo] password for mihol:
Executing: /tmp/apt-key-gpghome.6dnWdUW0P5/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831E
gpg: "3FA7E0328081BFF6A14DA29AA6A19B38D3D831E" not a key ID: skipping

**Comment by mi-hol** [comment]
just found this is WSL bug that is now fixed in W10 insider preview https://github.com/Microsoft/WSL/issues/3286

**Comment by 5aturnius** [comment]
Thanks to everyone! I finally fixed my stuff.

**Comment by GEkuL** [comment]
@mi-hol could you reopen the issue, so the changes were applied in instructions on the webpage: https://www.mono-project.com/download/stable/#download-lin

**Comment by mi-hol** [comment]
@GEkuL sorry don't understand the reasoning, issue was fixed back in Aug 2018!
 see (https://github.com/mono/mono/issues/9891#issuecomment-411717422)
