### ISSUE TITLE
Hybrid/coop suspend: We need a wrapper for malloc

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#9921]
# Summary of the problem

We don't know what third-party code will take locks.  Where third-party includes things like "libc" and "the kernel".

In order for hybrid and cooperative suspend to work correctly without deadlock, logically suspended threads (that is, threads that the suspend initiator perceives as suspended) must not prevent any running thread from being able to reach a safepoint.

One way to prevent a running thread from being able to reach a safepoint is by taking a lock that the running thread needs.

We don't know where the locks are.  They are inside `malloc` and `free`, for example.

If thread 1 is the GC initiator, thread 2 is suspended while calling `malloc`, and thread 3 is running (and would be cooperatively suspended - that is, only when it reaches a safepoint) and also calls `malloc` we will get a deadlock: 

* thread 1 is waiting for thread 3 to suspend;
* thread 2 is waiting for thread 1 to wake it up;
* thread 3 is waiting for the lock held by thread 2.

# Possible solutions

## Option 1: always call via glib; wrap all library calls in GC Safe transitions

Never call `malloc`, always call `g_malloc`.  Same for every other 3rd party function that Mono calls directly from inside the runtime.  (P/Invokes automatically get GC Safe transitions in the wrapper - nothing to do there.)

```c
  inline void* g_malloc (size_t size)
  {
    void *result;
    MONO_ENTER_GC_SAFE;
    result = malloc (size);
    MONO_EXIT_GC_SAFE;
    return result;
  }
```

### Issues

* We will need some way to automatically check that we never call outside the runtime.  Maybe by doing a special build with a dynamically linked glib and without linking metadata/, mini/ and utils/ with libc.
* AOT Compiler and early startup code: the `MONO_ENTER_GC_SAFE` macro asserts if the current thread isn't attached.  We'll need variants `MONO_TRY_ENTER_GC_SAFE` that are usable when the thread state machinery isn't initialized yet (in which case it should be a no-op instead of an assertion).
* Unknown how expensive this will be.  It's every library and syscall in Mono...

## Option 2: Two-phase hybrid suspend

Motivating observation: this is a problem because we preemptively suspended some threads before we cooperatively suspend some others.  The cooperative suspend should get a chance to happen first.

The proposed solution is outlined in a comment below https://github.com/mono/mono/issues/9921#issuecomment-411897101

## Option 3: ???

We should brainstorm some other options.

For example, we decided early on that the runtime will mostly be in GC Unsafe (hence cooperatively-suspended) thread state most of the time and only switch to GC Safe around blocking calls.  Maybe we can roll that back and stay in GC Safe mode longer.

**Comment by jaykrell** [comment]
LD_PRELOAD? Detours? I've been wanting to port Detours to Linux, but there are synchronization  problems, and some slightly non-obvious parts of the port -- CreateProcess(suspended) == fork(). LD_PRELOAD goes far, if you are in control of process launch.

**Comment by kumpera** [comment]
We can't count on syscalls being safe.
First, we must not use syscalls on Apple platforms as they are implementation details. We must rely on libc wrappers.
Any libc wrapper can interposed with code that takes locks. Instruments does it for mmap and so it's not possible to do memory profiling with it and mono cuz we deadlock quite easily.

**Comment by jaykrell** [comment]
Agreed syscalls are at somewhat implementation-defined/changing/indeterminate places, must wrap higher level.

For layers to interpose locks where there weren't any normally is kinda a breaking interface change to be avoided, alas. Though lock presence is also implementation detail, it is dangerous to add them.

Syscalls themselves cannot take locks that are exposed to usermode as that would mean usermode can cause kernel deadlocks. Kernel and usermode are separate in this regard. At least on some systems but I suspect it is general kernel architecture.

But the implementation-defined placement of syscalls makes it kinda not matter.

But I believe Posix signal-safe offers significant insurance here.
Posix signal-safe functions probably cannot lock? Unless taking a lock is itself reentrant?

http://man7.org/linux/man-pages/man7/signal-safety.7.html suggests this also.
"An async-signal-safe function is one that can be safely called from
       within a signal handler.  Many functions are not async-signal-safe.
       In particular, nonreentrant functions are generally unsafe to call
       from a signal handler."

These functions can be slow (open, read), but should not be possible to cause deadlock.

**Comment by lambdageek** [comment]
I'm still infatuated with the idea of a two-phase suspend:
* In the first phase:

   * cooperatively suspend all GC Unsafe threads
   * for GC Safe threads, switch them to `BLOCKING_SUSPEND_REQUESTED` thread state but don't bother sending a signal yet.
   * wait for the coop threads to reach safepoints.

   We can do this because `mono_threads_transition_request_suspension` will return `ReqSuspendInitSuspendRunning` for GC Unsafe threads and `ReqSuspendInitSuspendBlocking` for GC Safe ones.  

* In the second phase, preemptively suspend any GC Safe threads that haven't self-suspended yet  (`mono_threads_transition_request_suspension` will return `ReqSuspendAlreadySuspendedBlocking` which is misleading - the thread is just in `BLOCKING_SUSPEND_REQUESTED` not `BLOCKING_SELF_SUSPENDED`).

I believe that should absolve us of deadlocks: we only risk suspending a thread while it's holding a lock in the second phase, but by that point all the cooperative threads have safepointed.

References: mostly just a lot of staring at [this picture](https://www.mono-project.com/docs/advanced/runtime/docs/coop-state-machine.png)

**Comment by lambdageek** [comment]
Update on the two-phase suspend idea:

It's surprisingly easy to implement.  All the right state machine transition return values are already there and adding phases wasn't too bad.

The only hangup is that right now threads in blocking get their `suspend_count` incremented twice. We do two calls to `mono_threads_transition_request_suspension`: in the first phase to transition from `BLOCKING` to `BLOCKING_SUSPEND_REQUESTED` and then defer actual suspension until the second phase; and in the second phase to stay in `BLOCKING_SUSPEND_REQUESTED` (and this is the step that increments the `suspend_count`) and then to preemptively suspend the thread anyway.

When we resume, we only decrement the `suspend_count` once, so the thread stays suspended.  (And moreover as the number of STWs goes up, the suspend count goes up until Mono asserts when it goes above the max suspend count.)  Not great.

Probably the most straightforward way to fix this is to change the second phase to just peek at the thread state and not do any transition - if the state is `BLOCKING_SUSPEND_REQUESTED` preemptively suspend the thread - if it's `BLOCKING_SELF_SUSPENDED` that means the thread reached an abort blocking or done blocking transition - if it's any other state it's an error (because STW is still holding the global suspend lock).

Going to push on this a bit more.

----

Assuming it continues to pan out there's two more TODO items around this:

1. The prototype only does two-phase in the first suspend attempt in the unified STW function.  Second shouldn't be that different.
2. The prototype is focused on hybrid suspend - so the code always does two phases; a clean commit should only do one phase for preemptive and full-coop.

**Comment by lambdageek** [comment]
Update on two phase hybrid suspend: a prototype is at #10140 ([lambdageek/mono:stw-two-phase branch](https://github.com/lambdageek/mono/tree/stw-two-phase)).  Seems to work.  Only one dirty trick in there (peek blocking suspend requested).

**Comment by lambdageek** [comment]
Two-phase STW for hybrid suspend landed on `master` and `2018-08`.

As I summarized in https://github.com/mono/mono/issues/9921#issuecomment-411897101 two-phase stop the world should alleviate problems with unknown locks in system calls, so we don't need (but could still benefit from) wrappers around every syscall or library function.
