### ISSUE TITLE
Step Over fails if first seq point has MONO_SEQ_POINT_FLAG_NONEMPTY_STACK

### ISSUE THREAD

**Issue by 0xd4d** [mono/mono#9934]
1. No PDB file
2. Step Over a method call

It very often misses the breakpoint and instead hits the breakpoint in the caller method (thus stepping out instead of over).

Here's what happens (verified with Unity's 2018.2-mbe branch, but the relevant code seems identical to latest mono master):

The stepper BP is hit: mono_de_ss_update

https://github.com/mono/mono/blob/master/mono/mini/debugger-engine.c#L941-L947

It returns if the sequence point has MONO_SEQ_POINT_FLAG_NONEMPTY_STACK set.

mono_de_ss_start is called which eventually calls insert_breakpoint()

https://github.com/mono/mono/blob/master/mono/mini/debugger-engine.c#L153-L159

It picks the first sequence point, even if it has MONO_SEQ_POINT_FLAG_NONEMPTY_STACK set.

The result is that step over fails because the code won't hit any breakpoint in the same method.

**Comment by thaystg** [comment]
@0xd4d could you send us more information about how to reproduce?

**Comment by thaystg** [comment]
As we don't have more information about how to reproduce and I think this is fixed https://github.com/mono/mono/pull/12114, I'm closing this issue. :)
