### ISSUE TITLE
cross build regressed wrt System.Native and "shm_open that works well enough with mmap"

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#9951]
## Steps to Reproduce

1. on e.g. linux amd64: 
`./autogen.sh  CFLAGS="-g -O0" -disable-nls -disable-system-aot --host=arm-linux-gnueabihf CC=arm-linux-gnueabihf-gcc -enable-cross-compiling`

### Current Behavior

```
.
.
.
checking for shm_open that works well enough with mmap... configure: error: in `/s/mono3':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
```

### Expected Behavior

Uncertain. Perhaps success and compile and link, perhaps not.
Maybe cross builds too esoteric.

We have defaults in some places and don't run programs.

```
      dnl ***********************************
        dnl *** Checks for working __thread ***
        dnl ***********************************
        AC_MSG_CHECKING(for working __thread)
        if test "x$with_tls" != "x__thread"; then
                AC_MSG_RESULT(disabled)
        elif test "x$cross_compiling" = "xyes"; then
                AC_MSG_RESULT(cross compiling, assuming yes)
        else
                AC_TRY_RUN([
  
```

and

```
        dnl **************************************
        dnl *** Checks for working sigaltstack ***
        dnl **************************************
        AC_MSG_CHECKING(for working sigaltstack)
        if test "x$with_sigaltstack" != "xyes"; then
                AC_MSG_RESULT(disabled)
        elif test "x$cross_compiling" = "xyes"; then
                AC_MSG_RESULT(cross compiling, assuming yes)
        else
                AC_TRY_RUN([
```

but:

```
       AC_MSG_CHECKING(for shm_open that works well enough with mmap)
        if test "x$ac_cv_func_shm_open" = "xno" -o "x$ac_cv_func_shm_open_working_with_mmap" = "xno" ; then
                AC_MSG_RESULT(no)
        else
                AC_TRY_RUN([
 ```

therefore:

```
checking for shm_open that works well enough with mmap... configure: error: in `/s/mono3':
configure: error: cannot run test program while cross compiling
```

Is there a good default maybe?
This came in prematurely with System.Native ahead of its memory mapped file support?
Which is coming?

Anyway, I'll just set ac_cv_func_shm_open_working_with_mmap and move on.

## On which platforms did you notice this

Linux

**Comment by jaykrell** [comment]
I will workaround by setting ac_cv_func_shm_open.

**Comment by solabc16** [comment]
Hello - did anything further happen with this? I've just tried to cross-compile 5.16.0.179 for arm64, to start testing.

configure:25883: checking for shm_open that works well enough with mmap
configure:25890: error: in `/source/mono':
configure:25892: error: cannot run test program while cross compiling
See `config.log' for more details

Best
- James

**Comment by solabc16** [comment]
FYI, this is the minimal configure we needed to reproduce, whilst trying to cross compile for AArch64.

We've built and are currently running the following releases without issue on this arch: 5.10.1.57, 5.12.0.301 & 5.14.0.177.
```
./configure
	--prefix=/source/mono/test
	--build=x86_64-linux-gnu
	--host=aarch64-unknown-linux-gnueabi
	--disable-mcs-build
```
Best
- James

**Comment by mandawah** [comment]
Hello,
Same here with --host=arm-linux-gnueabihf 
Previous versions had no issues.

Thanks.

**Comment by m4tt075** [comment]
Same here when trying to update Synology packages via the spksrc cross-compilation framework...
https://github.com/SynoCommunity/spksrc/tree/master/cross/mono
@jaykrell Could you share how you've worked around the problem, please?

**Comment by jbatt33** [comment]
I feel the pain of this as well with : arm-angstrom-linux-gnueabi

**Comment by jbatt33** [comment]
> Wrapped that part of the configure step with :
> 
> `if test "x$host" == "x$target"; then`
> 
> Get's me past this... I'm not too sure how to solve this as my target does support the test it is attempting to run....

--I thought that was working for me, but bitbake hurt me a little. I changed my local build to just check for "arm " in the target name.  It appears that at this point the configuration has the host and the target set to the same values. Oh well. Hope this is resolved.  Thanks everyone.

**Comment by jbatt33** [comment]
> > > Wrapped that part of the configure step with :
> > > `if test "x$host" == "x$target"; then`
> > > Get's me past this... I'm not too sure how to solve this as my target does support the test it is attempting to run....
> > 
> > 
> > --I thought that was working for me, but bitbake hurt me a little. I changed my local build to just check for "arm " in the target name. It appears that at this point the configuration has the host and the target set to the same values. Oh well. Hope this is resolved. Thanks everyone.
> 
> @jbatt33 : Could you detail where you set this up with bitbake/Yocto? I have the same issue. Do you have your own mono recipe or are you just using the meta-mono layer with a .bbappend? I have created some extra recipes for the newer mono releases which otherwise look to compile and run fine (well 5.14 release does)
> 
> edit: Fixed configure.ac as per the first post to configure OK but then run into this one: #11744

Using the standard mono-layer with bitbake, except a LOCAL check out of mono repo instead of patching the release from git. each time it builds.

**Comment by ShonkyCH** [comment]
Ok, thanks. Attached patch fixes the configuration issue, but then hits #11744

[fix_shm_open_issue.patch.txt](https://github.com/mono/mono/files/2627183/fix_shm_open_issue.patch.txt)

**Comment by m4tt075** [comment]
@ShonkyCH I can confirm that your patch fixed the issue for me. As it will probably help others, too, do you want to PR it?

**Comment by solabc16** [comment]
Hello - as a more general observation, is there anything we can do to assist with arm/arm64 release testing? As far as I can tell this was broken 'out of the box', with the issue being raised before 5.16.0.179 was released 2018-10-05.

Best
- James

**Comment by ajlennon** [comment]
@solabc16 - if anybody wants to send PRs to me for updates to Poky meta-mono to support new releases these will auto-build on my Jenkins instance. It also does some very basic runtime sanity checks.

https://github.com/dynamicdevices/meta-mono

http://jenkins.dynamicdevices.co.uk:8080/job/meta-mono

**Comment by Apteryks** [comment]
Hello! Sadly the fix didn't have an effect on my side. I used the latest released mono archive (5.18.0.240) patched it with the patches from commit 97e410a6529d4c3ef345ab6bc9034af
[config.log](https://github.com/mono/mono/files/2847138/config.log)
797872f84 and fa290a62d92fb5a3139490b17a9e1cce3e0fd5dc (there was an offset 9 but I verified the fix applied correctly) and retried compilation. I still get the:
```
[...]
checking for bind with unsigned addrlen... no
checking for struct ipv6_mreq with unsigned ipv6mr_interface... no
checking for inotify_rm_watch with unsigned wd... no
checking for shm_open that works well enough with mmap... configure: error: in `/some/path/build_dir/target-x86_64-centos7-linux-gnu/mono-5.18.0.240':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
```
I've attached the full config.log for forensics.
[config.log.txt](https://github.com/mono/mono/files/2847144/config.log.txt)

**Comment by solabc16** [comment]
Hello @Apteryks

Did you run autoreconf after applying the patch?

Best
- James

**Comment by Apteryks** [comment]
@solabc16 Indeed, my bad! Thanks for the hint :-)
