### ISSUE TITLE
[XA/2018-04] Unable to compile Android project with "Embed assemblies in native code" enabled

### ISSUE THREAD

**Issue by pjcollins** [mono/mono#9984]
## Steps to Reproduce

1. Enable the "Embed assemblies in native code" project option in a new or existing Android project and attempt to archive or deploy the project to a device/emu.

### Current Behavior
Packaging fails due to a missing file:
```
[mkbundle stderr] 
    [mkbundle stderr] Unhandled Exception:
    [mkbundle stderr] System.IO.FileNotFoundException: Could not find file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/mkbundle-api.h"
    [mkbundle stderr] File name: '/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/mkbundle-api.h'
```

### Expected Behavior
Packaging succeeds.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
https://gist.github.com/pjcollins/8011b93e8beef67b40326a3896605e32

## Logs
https://gist.github.com/pjcollins/515e04b45113618cdf2e1f66871b4b63

**Comment by alexanderkyte** [comment]
Looks like https://github.com/mono/mono/commit/170e9442c976ed6cd4a499093e11a9e12e7368bb is a related change, though it was merged after 2018-04 AFAICT

**Comment by alexanderkyte** [comment]
It seems like @ludovic and @jonp incorporated this dependency here: https://github.com/xamarin/xamarin-android/commit/90edf815a679a7e5488733d7629ef45a6ba75751

putting the requirement on master here:
https://github.com/xamarin/xamarin-android/blob/90edf815a679a7e5488733d7629ef45a6ba75751/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj#L585

But the required mono commit here:
https://github.com/mono/mono/commit/170e9442c976ed6cd4a499093e11a9e12e7368bb

has not been backported to 

`mono/2018-04`.

**Comment by alexanderkyte** [comment]
Credits: @jaykrell is very fast with github, he found `170e944`

**Comment by jonp** [comment]
I think you meant to tag @jonpryor

**Comment by luhenry** [comment]
It's been backported to `mono:2018-04` with https://github.com/mono/mono/pull/8788, so it's very likely to be the commit at fault.

**Comment by luhenry** [comment]
The corresponding PR on XA https://github.com/xamarin/xamarin-android/pull/1503

**Comment by alexanderkyte** [comment]
I think you have an undocumented dependency on a recent VS4M version here. "Embed assemblies in native code" is missing from the "Android build" section on the mainline VS4M. 

I cannot find that string anywhere in the source of monodevelop. Is this proprietary?

**Comment by pjcollins** [comment]
@alexanderkyte this feature requires that you be logged in with an "Enterprise" license for it to be visible. If you log in to VS Mac with your Microsoft account it should be present.

**Comment by alexanderkyte** [comment]
If you look at the build log for the linked android package, in package.log we never include that file, but in make.log we build it. 

I believe this to be a bug in the android build system.

**Comment by luhenry** [comment]
Likely fixed with https://github.com/xamarin/monodroid/pull/828
